### ISSUE TITLE
Transfering Character Models/Animations

### ISSUE THREAD

**Issue by Zaraath** [suriyun-production/mmorpg-kit-docs#10]
Hello!  Thanks for the asset, I love the features.  I am really new to unity.  After making a controller, canvas and a few other small items, I thought I would see what I could do in your asset.

In trying to make it my own, I have tried to put in a few assets from the unity store to change it up a bit.  Trying to transfer.  I can put in the mesh, but the chars do not animate, and despite following your tips in your readme, they cannot be shot either.

When I try to copy via copying the rig via another avatar, the system you used with the empty avatar doesn't work.  It deletes the avatar altogether.  I was able to do it in another environment between that asset and another, just not the one included here.  Any help would be appreciated.

Z

**Comment by insthync** [comment]
They cannot play every animation or just an attack animations

**Comment by Zaraath** [comment]
They just stand, and for some reason, I cant attack them, I walk thru them, despite turning collision on, and rigid body.  

I played around with the Animation Override Control and now they are stuck in midair animation, not falling thru the floor, falling in place.  Still cannot interact with them with the player though.

**Comment by insthync** [comment]
Try following this video https://www.youtube.com/watch?v=_O5dJjkq_ug

You do not have to create your own `Animator Override Animation` it will be created automatically, you may duplicate demo character animator controller (file named `AdvanceCharacterAnimationController`) for your character but change some animation clips

**Comment by Zaraath** [comment]
Thank you for the video.  

I put two chars in, they have idle animations and can jump, turn, but can't move.   I get the following error.

NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.BaseCharacterEntity.EntityAwake () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity.cs:166)
MultiplayerARPG.BasePlayerCharacterEntity.EntityAwake () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity.cs:57)
MultiplayerARPG.PlayerCharacterEntity.EntityAwake () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/PlayerCharacterEntity.cs:85)
MultiplayerARPG.BaseGameEntity.Awake () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/BaseGameEntity.cs:93)

Also: 
"Move" can only be called on an active agent that has been placed on a NavMesh.

**Comment by insthync** [comment]
Not sure that you added `Nav Mesh Agent` to your character entity or not, because it is not required so if you add it, you have to remove it. 

Then check `Rigidbody` constraints, all freeze rotation must be checked.
![screenshot_644](https://user-images.githubusercontent.com/2697550/53282565-f00e2d00-376b-11e9-91f7-051528332449.png)

Another thing is to check your Character Data → Base Stats → Movespeed
![screenshot_643](https://user-images.githubusercontent.com/2697550/53282559-d66ce580-376b-11e9-81b3-44f70b7abd8a.png)

**Comment by Zaraath** [comment]
I did not have NavMesh on.  Those values did it, thank you so much!! I now have player characters!!

I will start to screw up the monsters now.  Really appreciate the help and the quick reply.
