### ISSUE TITLE
Are there plans for unreal engine version?

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1000]
Are there plans for unreal engine version?

**Comment by insthync** [comment]
It will be done maybe in the next 2 months, but it is not easy to customize as Unity version, you must be able to write C++, at least to customize list of stats (It was just struct. No attribute, damage element, game data), kind of armor/weapon were declared as enum. It uses Unreal's networking system. It also not put everything in one project, it have separated login-service, database-service, cluster-service which developed outside UE, only the map server developed by UE (the same codes as client)
