### ISSUE TITLE
Requirement Character Class

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1001]
![Untitled](https://user-images.githubusercontent.com/64667641/120208525-dd79dc80-c22d-11eb-8f44-957e06aa8c0f.jpg)
Could you make it able to add different character's class ( more than 1x kind ) to be able to make classes for each character with own skills . i just want to add that items for different classes , not all characters 
Thanks in Advance

**Comment by insthync** [comment]
Okay, I will do it.

**Comment by RunOrDi3** [comment]
Thank you so much

**Comment by insthync** [comment]
Added in 1.66
