### ISSUE TITLE
[Bug]Skills

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1002]
hi,

there is a small issue on skills when you use item/ammo for it. 
https://gyazo.com/78846e64fbb7b3a1c55d8c1de04b1c88

player cast the skill even when you dont have item in inventar, but not apply it. so it seem the check for item in inventory is somewhere after casting. maybe better to check before cast.

https://gyazo.com/a2af20f2f8ed0f317c24aa66517b5d5e
in video. first cast is when player has item in inventory, 2 and 3 are without. so you can see player try to cast but dont apply the spell.

something similar on the option "Can be interrupted while casting"
when the player cast a skill and is interrupted by damage, the skill still goes in cooldown and it took mana.
i dont know maybe some ppls like that but in common games, it goes in cooldown and took mana when you successfully cast the spell.

i dont know if its better to change it that it dont go in cooldown and take mana or make it optional?

thank you for 1.65f it almost fixed all issues i found.
i still test everything everyday. so i can report bugs. right now it feels alot stabler as before :) very nice

**Comment by moepi2k** [comment]
@insthync ok the issue that you can cast a spell even when you not have item in inventory only happens when you use 
Buff - BuffToTarget
https://gyazo.com/06cfcf024f110da12bf6b7c39470e3d3

with every other it checks first and if item <= 0 you will get the msg 
https://gyazo.com/ac00c483035e26164c8ba84f2c2b6999

so you need to check BuffToTarget. therese the issue

**Comment by insthync** [comment]
It is checking for items before casting, and as I tested it's working properly for all kinds of skills. It's checking for items in `BaseSkill` -> `CanUse` function which will be called in `BaseCharacterEntity` -> `ValidateUseSkill` at client before use skill.

![Screenshot_447](https://user-images.githubusercontent.com/2697550/120870833-377af900-c5c4-11eb-80a0-994397df6f94.png)

You may try checks if any condition were wrong or not.

**Comment by moepi2k** [comment]
yes with default controller it works. but with AimAtCursor there is a problem when buff is set to "BuffToUser"
here default kit 1.66 with AimAtCursorsController

https://gyazo.com/69f5f782396e18e1e0319d58d13a60e6
https://gyazo.com/5586fc18b701d0993489e8ec694d93a7/draw

you see sometimes he begins to cast even when no item is in inventory. the spell will not apply but he still try to cast.

**Comment by insthync** [comment]
Okay, I will fix it.
