### ISSUE TITLE
Errors with importing plugins

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1003]
when i import a plugin as .dll files i get those errors , Any solution for this ?
![2](https://user-images.githubusercontent.com/64667641/120338618-b1755e80-c2f4-11eb-8641-e30ba7637b20.jpg)

**Comment by insthync** [comment]
Which plugins?

**Comment by RunOrDi3** [comment]
called Nirvana , i wanna use it for fx ( you can check them ) https://mega.nz/file/jgsQ1C6C#3ZhRxFyAfiZE-IxzrwRbR0jL5XarDo1uHRD04iogjm0

**Comment by insthync** [comment]
You can changes codes in UniTask -> `TaskTracker` to use its WeakDictionary by add namespace to the dictionary

![Screenshot_441](https://user-images.githubusercontent.com/2697550/120370647-0fc72f00-c33f-11eb-8175-8ba9fcd8fbe1.png)
