### ISSUE TITLE
Pet XP

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1004]
what is the pet's xp for?

**Comment by insthync** [comment]
For level up the pet item

**Comment by juniormagalhaes** [comment]
> For level up the pet item

where did the pet level settings go?

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/120488234-f947c480-c38c-11eb-892c-6c51d185a284.png)
when I put any value here when using the pet it immediately dies, when I set all values to zero it works normally

**Comment by insthync** [comment]
Where those settings come from? You have to set your pet stats in `MonsterCharacter` game data for example
![Screenshot_442](https://user-images.githubusercontent.com/2697550/120489558-edd2b880-c3e1-11eb-9a4a-cf56a6bbfdc6.png)

**Comment by juniormagalhaes** [comment]
> Where those settings come from? You have to set your pet stats in `MonsterCharacter` game data for example
> ![Screenshot_442](https://user-images.githubusercontent.com/2697550/120489558-edd2b880-c3e1-11eb-9a4a-cf56a6bbfdc6.png)

![image](https://user-images.githubusercontent.com/56885137/120489764-45473900-c38e-11eb-8031-5013bd7a7301.png)

when I put any value here when using the pet it immediately dies, when I set all values to zero it works normally

**Comment by juniormagalhaes** [comment]
and where is the pet's xp table?

**Comment by insthync** [comment]
Did you set base stats ? or attributes which increase hp to your monster ?, pet's xp table use the same with player's character

**Comment by juniormagalhaes** [comment]
> > Where those settings come from? You have to set your pet stats in `MonsterCharacter` game data for example
> > ![Screenshot_442](https://user-images.githubusercontent.com/2697550/120489558-edd2b880-c3e1-11eb-9a4a-cf56a6bbfdc6.png)
> 
> ![image](https://user-images.githubusercontent.com/56885137/120489764-45473900-c38e-11eb-8031-5013bd7a7301.png)
> 
> when I put any value here when using the pet it immediately dies, when I set all values to zero it works normally

I decided, I have to set the default level to 1, before it was 10

**Comment by juniormagalhaes** [comment]
> Did you set base stats ? or attributes which increase hp to your monster ?, pet's xp table use the same with player's character

ok

**Comment by insthync** [comment]
Oh, I see
`I decided, I have to set the default level to 1, before it was 10`

So stats you set to character is stats for character level 10 so when it adjusted to level 1 it will decrease `hp` by level -(11 * (10-1))

**Comment by juniormagalhaes** [comment]
> Oh, I see
> `I decided, I have to set the default level to 1, before it was 10`
> 
> So stats you set to character is stats for character level 10 so when it adjusted to level 1 it will decrease `hp` by level -(11 * (10-1))

aaahhhh
