### ISSUE TITLE
New Errors upon update with LiteNetLibManager

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1005]
i updated to the latest and got these errors i asked in discord but no luck, my asset id's were also erased... that could be the issue how do i get the ID's back? its visablity checker errors 
https://gyazo.com/85304d2c211fffec8b76b51ca009471f
please help~! thank you!

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\GameApi\BaseInterestManager.cs(66,28): error CS1061: 'LiteNetLibIdentity' does not contain a definition for 'AddSubscribing' and no accessible extension method 'AddSubscribing' accepting a first argument of type 'LiteNetLibIdentity' could be found (are you missing a using directive or an assembly reference?)

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\GameApi\BaseInterestManager.cs(59,139): error CS1061: 'LiteNetLibIdentity' does not contain a definition for 'AlwaysVisible' and no accessible extension method 'AlwaysVisible' accepting a first argument of type 'LiteNetLibIdentity' could be found (are you missing a using directive or an assembly reference?)

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\GameApi\BaseInterestManager.cs(52,58): error CS1061: 'LiteNetLibIdentity' does not contain a definition for 'VisibleRange' and no accessible extension method 'VisibleRange' accepting a first argument of type 'LiteNetLibIdentity' could be found (are you missing a using directive or an assembly reference?)

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\GameApi\BaseInterestManager.cs(52,29): error CS1061: 'LiteNetLibIdentity' does not contain a definition for 'VisibleRange' and no accessible extension method 'VisibleRange' accepting a first argument of type 'LiteNetLibIdentity' could be found (are you missing a using directive or an assembly reference?)

**Comment by insthync** [comment]
Try delete `Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\` folder and re import it.

**Comment by insthync** [comment]
About empty asset Id, it will be assigned when save prefab or prefab has any changes

**Comment by Sour-J** [comment]
that didnt work but deleting the core and reimporting did thanks
