### ISSUE TITLE
Small bug with stats [Solution]

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1006]
uiTextFood,
uiTextWater,
they are missing in line 213 , should be added after <uiTextStaminaLeechRate,>
thank you for this amazing kit man :)

**Comment by insthync** [comment]
Oh, thank you :)

**Comment by RunOrDi3** [comment]
no prob :)

**Comment by insthync** [comment]
Fixed in 1.66
