### ISSUE TITLE
BUG in attributes

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1007]
![image](https://user-images.githubusercontent.com/56885137/120566466-abab7600-c3e5-11eb-9ad5-ed2824433461.png)

as you can see in the image, the intelligence attribute is set to increase the critical, but it's not increasing the critical, it's increasing the blocking, as you can see in the video

https://cdn.discordapp.com/attachments/460803281455939595/849798009026117652/02.06.2021_20.52.58_REC.mp4

**Comment by insthync** [comment]
Yeah, the last version I've added new stats then I forget to put some data to function parameter, can fix it by changes codes in `UICharacterStats` class
![Screenshot_444](https://user-images.githubusercontent.com/2697550/120570883-3e2e3280-c443-11eb-8ab4-0a4aa1f89cfb.png)

**Comment by insthync** [comment]
Fixed in 1.66
