### ISSUE TITLE
Entity poping range

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#1008]
Hi ! How can i change the range for entity visibility ? 

Like this : 
https://gyazo.com/28c0bf28425dfa387ec4551ce7d1b77f

My enemy appear really close from me, it's the same things for harvestable.

**Comment by insthync** [comment]
Changes visible range in LiteNetLibIdentity component

![Screenshot_445](https://user-images.githubusercontent.com/2697550/120741168-c3d2e080-c51e-11eb-8f0d-a227df9a8d04.png)

If it's more than 0 it will override interest manager settings
