### ISSUE TITLE
Weapon Damage infliction

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#101]
If you use this parameter with
![image](https://user-images.githubusercontent.com/47291794/66834456-4bdd2e80-ef66-11e9-8e36-134f6ac05070.png)
then all is well.

If you use this parameter with
![image](https://user-images.githubusercontent.com/47291794/66834494-66afa300-ef66-11e9-986b-6148f9bbb818.png)
then the skill deals 0 damage. In the 1.48 version, this worked.

Can you add Weapon Damage infliction for new AOE skills?

**Comment by insthync** [comment]
Fixed, and also add skill attack type to AOE skills
