### ISSUE TITLE
MonsterCharacter database's "Characteristic" value is not important at summons.

### ISSUE THREAD

**Issue by xafgun** [suriyun-production/mmorpg-kit-docs#1010]
At "MonsterActivityComponent.cs",  "isAggressiveWhileSummonerIdle" need to be changed with "isAggressiveWhileSummonerIdle || MonsterDatabase.Characteristic == MonsterCharacteristic.Aggressive" at 3 line. Otherwise MonsterCharacter database's "Characteristic" value is not important at summons.

**Comment by insthync** [comment]
Okay, I will change it, thank you.

**Comment by insthync** [comment]
Fixed in 1.66
