### ISSUE TITLE
suggestion for the shop

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1011]
Suggestion: that in the npc shop, password is possible to see the item details before buying, currently clicking on the item does not show the dialog with the item information, it is kind of annoying for a player to buy an item to see its information before

**Comment by insthync** [comment]
It actually can do it by setup dialog in `UI Npc Dialog` -> `Ui Sell Item Dialog`

![Screenshot_446](https://user-images.githubusercontent.com/2697550/120834607-717cd880-c58d-11eb-926e-9852246bcef6.png)

I will update the demo later

**Comment by insthync** [comment]
Added in 1.66 demo
