### ISSUE TITLE
Limit XP

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1014]
![image](https://user-images.githubusercontent.com/56885137/120899113-729d1c80-c604-11eb-93ce-c7bd266a2317.png)

hello, I was setting up my xp table and I realized there is an xp limit of 2147483647, I just can't put more than that, if I type a higher heat it returns to the value of 2147483647, I would like to know how I remove this limit? since I need to put more xp than the limit

**Comment by insthync** [comment]
Can't change it, it's the max value of 32 bit integer number, If change it to 64 bit, it has to change a lot of code structure.

**Comment by juniormagalhaes** [comment]
oh I understand, a doubt, does gold also have this limit?

**Comment by insthync** [comment]
Yes, it is.
