### ISSUE TITLE
swimming system problem

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1016]
when using the auto swin to suface, the character is buggy and the swimming animation does not happen, as in the video of the first link.

another problem is when you jump in the water, it doesn't get anything either, as in the video on the second link.

and sometimes what is on the third link happens.

https://cdn.discordapp.com/attachments/460803281455939595/851470176942686278/MMO2_-_f17_-_PC_Mac__Linux_Standalone_-_Unity_2020.3.11f1_Personal__DX11__2021-06-07_11-37-13.mp4

https://cdn.discordapp.com/attachments/460803281455939595/851477279724011520/MMO2_-_f15_-_PC_Mac__Linux_Standalone_-_Unity_2020.3.11f1_Personal__DX11__2021-06-07_12-04-29.mp4

https://cdn.discordapp.com/attachments/460803281455939595/851479394803515452/MMO2_-_f15_-_PC_Mac__Linux_Standalone_-_Unity_2020.3.11f1_Personal__DX11__2021-06-07_12-14-34.mp4

**Comment by juniormagalhaes** [comment]
when it jumps in the water it keeps falling

![image](https://user-images.githubusercontent.com/56885137/121048631-5a0c3e00-c78d-11eb-9bf1-ccf721ca51c9.png)

**Comment by insthync** [comment]
Which entity movement component are you using?

**Comment by juniormagalhaes** [comment]
> Which entity movement component are you using?

Rigid Body

![image](https://user-images.githubusercontent.com/56885137/121054927-35b36000-c793-11eb-91e4-7531f3fb8504.png)

**Comment by insthync** [comment]
Fixed in 1.66b
