### ISSUE TITLE
After editing the map: NullReferenceException

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#1017]
After editing the map, I got the following errors:
NullReferenceException: Object reference not set to an instance of an object
Assets/UnityMultiplayerARPG/Core/Scripts/UI/Chat/UIChatHandler.cs:138
Assets/UnityMultiplayerARPG/Core/Scripts/UI/Scenes/UISceneGameplay.cs:449
Assets/UnityMultiplayerARPG/Core/CameraAndInput/Scripts/Input/MobileSwipeArea.cs:52
Assets/UnityMultiplayerARPG/Core/CameraAndInput/Scripts/Input/MobilePinchArea.cs:48
I don’t understand what’s the matter, I didn’t seem to change anything in the system...
![2](https://user-images.githubusercontent.com/16080577/121256008-c6ce2800-c8b4-11eb-85f0-fed835c19479.jpg)

**Comment by insthync** [comment]
Try add event system

![Screenshot_448](https://user-images.githubusercontent.com/2697550/121263625-15dd8280-c8e0-11eb-9876-981d30753943.png)

**Comment by brabaris** [comment]
Exactly! Accidentally deleted event system ... Thanks a lot!
