### ISSUE TITLE
Issue with Skill filtering

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#1020]
![image](https://user-images.githubusercontent.com/57778639/121416857-4997c700-c937-11eb-9862-89102c03cb4f.png)

BaseSkill
![image](https://user-images.githubusercontent.com/57778639/121416975-692eef80-c937-11eb-9343-a607fa212c8e.png)

UICharacterSkills_SL
![image](https://user-images.githubusercontent.com/57778639/121417280-b6ab5c80-c937-11eb-979f-7de8b430c490.png)

![image](https://user-images.githubusercontent.com/57778639/121417145-924f8000-c937-11eb-9086-e3e6c5f2af4e.png)

What am i doing wrong here, no matter what i do it just displays the whole skill list. Been at this for a couple of days, please save me from myself... lol

Thanks for your time!

**Comment by insthync** [comment]
It seems to be correct, It should be hidden, Not sure that it calling your overridden function correctly or not.

**Comment by Fallen01** [comment]
I keep looking at it and it looks right... Why im so frustraited

**Comment by Fallen01** [comment]
https://mega.nz/file/FAhkhDQb#C3t2VtNh2bMlX73nmeGTViLRT7WGxFik_BSa70FO3t8

**Comment by Fallen01** [comment]
those are the files if you didnt mind checking them out when you have time, thank you for responding.

**Comment by insthync** [comment]
I think you should change `UpdateData` in `UICharacterSkills` to be a virtual function to overriding it instead of creating a new `UpdateData_SL` function because it will be called from other places to set the skill list.

**Comment by Fallen01** [comment]
Thank you Ill try it

**Comment by Fallen01** [comment]
I was trying to avoid a core mod, could you please update the method to virtual on your side? Thank you again for pointing out the issue, was driving me crazy...

**Comment by Fallen01** [comment]
I have to assume people in the future will want to filter skills there own way aside from myself hehe.

**Comment by insthync** [comment]
In 1.66c
- Change listing UI components (such as `UICharacterBuffs`, `UICharacterCurrencies` and so on) to have the same variable/function names (with other classes), intend to make it easier to find things and also changes some functions to be overridable.
  - Dialog reference (Example: `uiCurrencyDialog`) variable name will be changed to `uiDialog`.
  - Prefab reference (Example: `uiCharacterCurrencyPrefab`) variable name will be changed to `uiPrefab`.
  - Container reference (Example: `uiCharacterCurrencyContainer`) variable name will be changed to `uiContainer`.
  - On dialog hide function (Example: `OnItemDialogHide`) name will be changed to `OnDialogHide` and also overrideable.
  - On entry select function (Example: `OnSelectCharacterItem`) name will be changed to `OnSelect` and also overrideable.
  - On entry deselect function (Example: `OnDeselectCharacterItem`) name will be changed to `OnDeselect` and also overrideable.
  - `UpdateData` function will be overridable.

So.. now you can override  `UpdateData` function to do your stuff.
