### ISSUE TITLE
[Question] Attributes reset

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1021]
Sorry to bother again but I have a question, in order to reset your attributes you need to use attributes.clear. But that reset all attributes, there isnt a way to just reset some of them? Or to dont reset one of them?. Thanks :D

**Comment by insthync** [comment]
It has `ResetAttributes` function in `PlayerCharacterDataExtension`

**Comment by MosesGomez** [comment]
> It has `ResetAttributes` function in `PlayerCharacterDataExtension`

Yeah got that, but that reset all attributes, Ill like to know if there is a way to just reset one of them.

**Comment by insthync** [comment]
```
            for (int i = characterData.Attributes.Count - 1; i >= 0; --i)
            {
                if (characterData.Attributes[i].GetAttribute() == YOUR_ATTRIBUTE)
                {
                    returnStatPoint += characterData.Attributes[i].amount;
                    characterData.Attributes[i].amount = 0;
                    break;
                }
            }
            characterData.StatPoint += returnStatPoint;
```

**Comment by MosesGomez** [comment]
> ```
>             for (int i = characterData.Attributes.Count - 1; i >= 0; --i)
>             {
>                 if (characterData.Attributes[i].GetAttribute() == YOUR_ATTRIBUTE)
>                 {
>                     returnStatPoint += characterData.Attributes[i].amount;
>                     characterData.Attributes[i].amount = 0;
>                     break;
>                 }
>             }
>             characterData.StatPoint += returnStatPoint;
> ```

For example, this lines of code should be done trough server or trough client? I was doing trough server call, maybe that was my bad part.

**Comment by insthync** [comment]
Do it at server

**Comment by MosesGomez** [comment]
Thank you so much, Ill give it a try again.

**Comment by MosesGomez** [comment]
This is what happens to me after the reset. they got reseted but it keeps the value until I try to add again a stat point in one attribute. 
In the video can see. 
https://user-images.githubusercontent.com/12781104/121572762-c0899a00-c9e1-11eb-81b7-be4c68ee3458.mp4

**Comment by MosesGomez** [comment]
![Captura](https://user-images.githubusercontent.com/12781104/121572923-e7e06700-c9e1-11eb-84eb-c86f596ce818.PNG)
And I make this, I dont want to save the points. juts reset them so thats why im not adding the stat count.

**Comment by insthync** [comment]
Okay, seems like it is not marked to update, you can do like this
```
if (entity.Attributes[i].GetAttribute() != entity.prestAttr)
{
  CharacterAttribute tempAttribute = entity.Attributes[i]
  tempAttribute .amount = 0;
  entity.Attributes[i] = tempAttribute;
}
