### ISSUE TITLE
Survival random spawning

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1022]
Hey Suri, First I would like to say I appreciate everything you do.

I was wondering if theres a way to make an option to have random spawn on a map. Im making a survival game with your kit and most survival games spawn you randomly around the map with your kit its a static spawn it seems.

Thanks

**Comment by insthync** [comment]
I have planned to add seed for the map randomizing system :P

**Comment by insthync** [comment]
You actually can override `BaseMapInfo` and change `StartPosition` property result to random positions

**Comment by Sour-J** [comment]
thank you thats genius I appreciate you
