### ISSUE TITLE
when upgrading to version 166b this error occurred

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1023]
I deleted the folder Assets/UnityMultiplayerARPG/Core/LiteNetLibManager and Assets/UnityMultiplayerARPG/MMO/Plugins before updating as it asks in the changelog but I still got this error

![image](https://user-images.githubusercontent.com/56885137/121551124-bff30280-c9e5-11eb-93da-67d1eeb30954.png)

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\GameApi\LiteNetLibGameManager.cs(63,59): error CS0246: The type or namespace name 'DefaultInterestManager' could not be found (are you missing a using directive or an assembly reference?)

**Comment by RunOrDi3** [comment]
so you should delete Assets/UnityMultiplayerARPG/Core/LiteNetLibManager and Assets/UnityMultiplayerARPG/MMO/Plugins folder before import the new version.

**Comment by juniormagalhaes** [comment]
> you should delete Assets/UnityMultiplayerARPG/Core/LiteNetLibManager and Assets/UnityMultiplayerARPG/MMO/Plugins folder before import the new version.

I did it

**Comment by juniormagalhaes** [comment]
I created a new project and imported just the kit, and the same error happens

**Comment by RunOrDi3** [comment]
remove the asset then import it again , should everything work

**Comment by juniormagalhaes** [comment]
> remove the asset then import it again , should everything work

I created a new project and imported just the kit, and the same error happens

**Comment by juniormagalhaes** [comment]
> remove the asset then import it again , should everything work

I deleted the asset and imported it again and the same error continues

**Comment by juniormagalhaes** [comment]
I think the error is here somewhere, but I have no idea what to do to fix it.

![image](https://user-images.githubusercontent.com/56885137/121559715-3810f680-c9ed-11eb-94cd-9c5fe9fb77ab.png)

**Comment by juniormagalhaes** [comment]
I imported it again, but when I import it doesn't stay in the folder

![image](https://user-images.githubusercontent.com/56885137/121581956-d65c8680-ca04-11eb-8a1b-d7f0e880dac5.png)

**Comment by juniormagalhaes** [comment]
> Any message when imported?

only this

![image](https://user-images.githubusercontent.com/56885137/121582404-5aaf0980-ca05-11eb-9c98-608deda7ae99.png)

**Comment by insthync** [comment]
Okay try delete it (in file explorer) then re-import it.

**Comment by juniormagalhaes** [comment]
> Okay try delete it (in file explorer) then re-import it.

I deleted the DefaultInterestManager.cs and it worked, you can close the topic

**Comment by juniormagalhaes** [comment]
Thanks XD

**Comment by insthync** [comment]
:)

**Comment by sdk2016** [comment]
just delete "DefaultInterestManager.cs.meta" ini "Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\GameApi" solved this problem
