### ISSUE TITLE
Suggestion: Item that increases exp rate

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1024]
hey suri
would be nice for us to have a item that increases rate of exp x2 x3 etc. you could even put it on gear maybe or a potion or buff

its a really good feature to have in the kit, thank you for your hard work

**Comment by insthync** [comment]
Okay, I will add increase exp rate, increase gold rate to buff and add some condition to not delete sum buff when character dead

**Comment by Sour-J** [comment]
thank you so much!

**Comment by Sour-J** [comment]
maybe it could be an item so we can sell it in the cash shop?

**Comment by insthync** [comment]
You will be able to make an item like potion items but set buff to increase exp rate and set it to not deleted on character dead. No new game data just add something to buffs.

**Comment by RunOrDi3** [comment]
@insthync  Are we able to make like command for admin to make like an 1 hour or something to increase exp ?

**Comment by insthync** [comment]
> @insthync Are we able to make like command for admin to make like an 1 hour or something to increase exp ?

Can't do it yet.

**Comment by Sour-J** [comment]
The admin could just give that item works that way if that's what you wanted

**Comment by RunOrDi3** [comment]
@insthync ahh kk , i hope you add it also with items for exp

**Comment by RunOrDi3** [comment]
@Sour-J i mean something called exp event for players everyday for 1 hour :)

**Comment by insthync** [comment]
In 1.66c
- Add `goldRate` to `CharacterStats` struct.
- Add `expRate` to `CharacterStats` struct.
- Add `/gold_rate (float)` to default GM commands, use it to set gold rate.
- Add `/exp_rate (float)` to default GM commands, use it to set exp rate.
- Add `isExtendDuration` to `Buff` struct. If it is `TRUE` buff duration can be extended, when extending it will change buff level to the latest applying level.
- Add `maxStack` to `Buff` struct. It will be used while `isExtendDuration` is `FALSE` to make buff stackable.
- Add `doNotRemoveOnDead`. If it is `TRUE` buff won't be removed from the character when the character dead.

Try use them to implement your EXP rate potion.
