### ISSUE TITLE
Suggestion: Declutter the entity components

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1025]
I wanted to make a suggestion to perhaps declutter the entity components a bit, specially separate all the network/sync options to a separate component.  
Currently the entity component (player/monster) is quite huge with a variety of options which can sometimes be overwhelming when configuring characters one by one, by hand. Yet a lot of the options available in the component are not really needed to be changed/customized, specially the network related (sync) options, so maybe can separate them into another dependent component instead ?  
This way, the main component will only have the actual options and settings we need to configure like the UI transforms, etc.

**Comment by rasto61** [comment]
You dont modify the network parts in editor.

**Comment by shubhank008** [comment]
> You dont need to modify the network parts in editor. You can just ignore them.
> Doing what you are suggesting would require 30+ components just to setup a player. Current design is Good.

Exactly, don't need to modify network parts in editor thus why suggesting just the network parts be separated to another component so the overall size and options in single component is lesser.  
No need to divide it into 30+ or even so many components, just dividing the entity component into 2 components would do, one for the network parts (which I suppose rarely anyone uses) and one for actual entity changes, setting UI transforms, etc.  

![image](https://user-images.githubusercontent.com/3790163/121799981-f1213c00-cc4c-11eb-9872-13e04c4bf357.png)

**Comment by insthync** [comment]
Okay, I will do it, I actually want to do it too

**Comment by insthync** [comment]
Just afraid that it can break other customer's projects, so I have to do the migration and test it a lot.

**Comment by shubhank008** [comment]
> Just afraid that it can break other customer's projects, so I have to do the migration and test it a lot.

How about if you leave the (Character/Monster/NPC)_Entity class as it is and just for better inspector visual purpose, create a companion class Character_Entity_Simple which will basically be the current Entity class behind the scene, but will just override the fields shown in inspector, then people like me who just want a simpler view of the inspector can instead use that component instead.  

And as its just overwriting the fields visible in inspector and using same codebase as actual entity class, should not break anything (fingers crossed)

**Comment by insthync** [comment]
![Screenshot_566](https://user-images.githubusercontent.com/2697550/127030122-4855f61e-7fe3-4b5f-9b32-007218bdfca5.png)

Like this?

In case you may interest how it works https://github.com/insthync/UnityEditorUtils/commit/47a97efd2ad30fc64a5fa3471bb4725985b24432

**Comment by shubhank008** [comment]
> ![Screenshot_566](https://user-images.githubusercontent.com/2697550/127030122-4855f61e-7fe3-4b5f-9b32-007218bdfca5.png)
> 
> Like this?
> 
> In case you may interest how it works [insthync/UnityEditorUtils@47a97ef](https://github.com/insthync/UnityEditorUtils/commit/47a97efd2ad30fc64a5fa3471bb4725985b24432)

Hi, I meant to separate them to two different components itself, PlayerCharacterEntity and PlayerCharacterEntityNetwork but if that is too complex or prone to break stuff, this works too, cleaner than right now.

**Comment by insthync** [comment]
Improved in 1.67b
