### ISSUE TITLE
Suggestion: Hot-swappable characters (Genshin Impact)

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1026]
Possibility to swap/change your hero/character during gameplay. Something like Genshin Impact where you can have selectable/playable characters from your unlocked ones and swap between them during gameplay.  

In-game swappable players/characters would be a huge boost to the kit given the popularity of Genshin Impact and how unique and limitless this kind of feature can have for any game type. Heck even if actual swappable characters is not possible, being able to swap your character with your summon can work, as then we can just "unlock or drop" new characters as summon items and upon summoning player's character can change with that of the summon.

**Comment by shubhank008** [comment]
I think this is somewhat similar to #983 as both suggestions are to change your player/character model (and skills/attacks/animations)

**Comment by shubhank008** [comment]
PS: This is a low priority request, something to consider once you are free and want something new to add, otherwise I am very well happy seeing the kit being updated very frequently and the updates being to its cores, stability, performance and bug fixes instead of endless new features.

**Comment by Kanera66** [comment]
I also allow myself to posted here. 
I would like a system to easily change the appearance of the character, during leveling for example. 
like a kind of evolution. 

thank you for this wonderful project

**Comment by insthync** [comment]
Offer me a number to do it then I will consider whether to do it or not. It simply just destroys player's entity and respawns a new one as different character for the player.

**Comment by insthync** [comment]
I will close it until you offer anything to me.
