### ISSUE TITLE
Player experience reward for pvp

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1027]
hello, 
ive been trying to reverse engineer the kit to give players exp for killing another player and more exp per level of that player, you have it for monsters now so im trying to add it to the player too! just want to give exp to players as a reward for pvp its possible with what you have already im just not smart enough! :(
thank you for all you do <3 whats your donation link?

**Comment by insthync** [comment]
You can do like this, give exp to attacker when damage receiver dies https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand/blob/master/Scripts/PvpGetRewardExtension/BasePlayerCharacterEntity_PvpGetExp.cs

**Comment by Sour-J** [comment]
> You can do like this, give exp to attacker when damage receiver dies https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand/blob/master/Scripts/PvpGetRewardExtension/BasePlayerCharacterEntity_PvpGetExp.cs
@insthync 
is there a way to make this into give exp per player level instead of a flat rate? thank you <3 ill buy you a coffee XD

**Comment by insthync** [comment]
Just store EXP table for each level somewhere and calculate rewarding EXP at line 39 by the character level.
