### ISSUE TITLE
[Suggestion]UI Info

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1029]
if value are 0 like Stam/Mana consume like in this example, the text should be hidden

https://gyazo.com/440f0a8824b6ee2ae005ec2457e8bce4

**Comment by insthync** [comment]
Okay, I will do it.

**Comment by insthync** [comment]
In 1.66c

- Don't show consuming HP text component if consume amount = 0.
- Don't show consuming MP text component if consume amount = 0.
- Don't show consuming Stamina text component if consume amount = 0.
