### ISSUE TITLE
[Question] Missiles can lock target and follow the target?

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1031]
I have this question because right now I throw my skill and goes to my forward direction and in a straight line.

**Comment by insthync** [comment]
It won't follow the target, you can make a new component which inherits from `MissileDamageEntity` class to change the update function to follow the target.

**Comment by MosesGomez** [comment]
> It won't follow the target, you can make a new component which inherits from `MissileDamageEntity` class to change the update function to follow the target.

Great thanks man, Ill do that and send it over discord :D
