### ISSUE TITLE
Status Effect

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1032]
It would be good if the Status Effect is stackable, that is, if you have an item that gives an effect that when you are hit by an enemy your strength increases by +5 but is stackable with a maximum of times.

that is, if the cumulative limit is 3, the limit will be strength +15

**Comment by insthync** [comment]
When adding new things there is always a new request for the new thing, I am pretty tired. *-*

**Comment by insthync** [comment]
Okay, I will do it.

**Comment by moepi2k** [comment]
Yesterday i tried status effect with sockets and put socked on my weapon, but it seems the effect not worked with socked?

**Comment by insthync** [comment]
No, it's not worked with socket item yet.

**Comment by insthync** [comment]
In the next version, it will have it, but for socket enhancer items, status effects will be fixed to `1`.

I also add it to buff data, so buff which applied by item or skills or status effects can apply other status effects.

**Comment by insthync** [comment]
In 1.66c
- Add `isExtendDuration` to `Buff` struct. If it is `TRUE` buff duration can be extended, when extending it will change buff level to the latest applying level.
- Add `maxStack` to `Buff` struct. It will be used while `isExtendDuration` is `FALSE` to make buff stackable.
- Add `doNotRemoveOnDead`. If it is `TRUE` buff won't be remove from character when character dead.
- Socket enhancer items can apply status effects.
- Buffs can apply status effects.
