### ISSUE TITLE
BUG: Inventory/stash

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1033]
1. When transferring items from inventory to storage, the stack is transferred completely regardless of how many items we have selected.
https://youtu.be/Y_eu4Bp4kOg

2. When you drag items in the inventory from the stack to the stack, some items disappear, and the value in the stacks changes in different ways. Everything works well in the repository.
https://youtu.be/72Vw5CQlWac

**Comment by insthync** [comment]
As I test, mine still working properly, how can I reproduce it?

**Comment by DimasjkTV** [comment]
> As I test, mine still working properly, how can I reproduce it?

it was on 1.65e or 1.65d. I will test on fresh last version.

**Comment by DimasjkTV** [comment]
> As I test, mine still working properly, how can I reproduce it?

First bug. If we use slots.
![image](https://user-images.githubusercontent.com/47291794/122391406-a4ef3800-cf7b-11eb-8267-ba1934340a5f.png)

**Comment by insthync** [comment]
I've tested it.

**Comment by DimasjkTV** [comment]
> I've tested this is 

> I've tested it.

This is last version of fresh project

**Comment by DimasjkTV** [comment]
https://youtu.be/NdEIZZtPsAc

**Comment by insthync** [comment]
https://youtu.be/ni9k40viTGQ

**Comment by DimasjkTV** [comment]
> https://youtu.be/ni9k40viTGQ

Or maybe this is due to the fact that i had to delete some scripts after the update?

**Comment by DimasjkTV** [comment]
I have updated my test fresh version of the project to the latest and have this error. But I created a new project and this error is not there. Looks like something needs to be removed? Or reconfigure.

**Comment by moepi2k** [comment]
@DimasjkTV an info for updating current project. create a fresh project with latest version. then in your current project remove UnityMultiplayerARPG Folder an copy paste from fresh project into yours. i do it since beginning and never had any issues.

since this kit is great to put all your own stuff with partials and devext into seperate folder its the easiest way to update project.
never directly import unity package into current project, this will throw errors

@insthync maybe it would make sense to mention this in the docs. alot of ppls in discord always have the same issue after updating project.

**Comment by DimasjkTV** [comment]
> @DimasjkTV an info for updating current project. create a fresh project with latest version. then in your current project remove UnityMultiplayerARPG Folder an copy paste from fresh project into yours. i do it since beginning and never had any issues.
> 
> since this kit is great to put all your own stuff with partials and devext into seperate folder its the easiest way to update project.
> never directly import unity package into current project, this will throw errors
> 
> @insthync maybe it would make sense to mention this in the docs. alot of ppls in discord always have the same issue after updating project.

I have a test project that is based solely on a fresh, empty project. First, I update it to the current patch. In the video, you can see that a regular updated project has this bug without changes.

**Comment by insthync** [comment]
Try update `Core\Scripts\LanGame\Networking\LanRpgServerStorageMessageHandlers.cs`

**Comment by DimasjkTV** [comment]
> LanRpgServerStorageMessageHandlers

the same. It looks like this file has been updated

**Comment by insthync** [comment]
Or just delete Core\Scripts and re-import the package

**Comment by moepi2k** [comment]
mh i dont know, i updated from 1.65 to 1.66b without any errors and issues. everything works

**Comment by DimasjkTV** [comment]
> Core

yes works. Thanks!

**Comment by DimasjkTV** [comment]
> Or just delete Core\Scripts and re-import the package

I just noticed that after the update, I did not receive new stats on items.
Updated to the last version
![image](https://user-images.githubusercontent.com/47291794/123049144-ea8e8380-d407-11eb-9f84-1b5508c46ab8.png)

Fresh install
![image](https://user-images.githubusercontent.com/47291794/123049196-f8dc9f80-d407-11eb-8e95-0f1dcd73ff92.png)

**Comment by insthync** [comment]
Because the scripts are not updated, you have to update by delete an un-updated file and re-import, that is it. Old story.

**Comment by DimasjkTV** [comment]
> Because the scripts are not updated, you have to update by delete an un-updated file and re-import, that is it. Old story.

But why is this happening. There were no such problems before. Now, in order to update the project every time, do we need to delete all scripts? I have been using this kit for over two years now. During this time, I have been updated 30-40 times already and this has never happened.

**Comment by DimasjkTV** [comment]
i deleted script folder in core and reinstall but i still havent this new stats

**Comment by insthync** [comment]
Did you moved scripts to other folders ?

**Comment by DimasjkTV** [comment]
> Did you moved scripts to other folders ?

no. I just delete script folder in core folder and reinstall package

**Comment by insthync** [comment]
TeamViewer, let's see what happen.

**Comment by insthync** [comment]
I actually annoying with questions like why is this happening, because I don't know too. what I know is your scripts are outdated.
