### ISSUE TITLE
LiteNetLib GameManager.cs(63,59): error CS0246

### ISSUE THREAD

**Issue by lordarous** [suriyun-production/mmorpg-kit-docs#1034]
seem to have something wrong with my server coding, or did I not do something so that it corrects it by itself?
the full error is as followed:
Assets\Unity MultiplayerARPG\Core\LiteNetLib Manager\Scripts\GameApi\LiteNetLib GameManager.cs(63,59): error CS0246: The type or namespace name 'DefaultInterestManager' could not be found (are you missing a using directive or an assembly reference?)

or is it a must to use an older unity version like 2019, it's frustrating that there is no tutorial on the newest version of how to use them.
and I am getting quite a number of exclamation marks of errors and 2 red errors off the newest version of unity, my unity version is 2020.3.11f1

thanks in advance, Michael

**Comment by insthync** [comment]
Try delete `DefaultInterestManager.cs.meta`, following this https://github.com/suriyun-production/mmorpg-kit-docs/issues/1023

In next version I will re-generate `DefaultInterestManager.cs.meta` to fix this issues.
