### ISSUE TITLE
Incomprehensible attack with a bow.

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#1035]
Whenever I attack an enemy with a bow: the first attack deals damage, and subsequent attacks are very rare. In this case, the arrows are not consumed. Melee weapons are fine.
https://youtu.be/Imh4hv1bLKs

![10](https://user-images.githubusercontent.com/16080577/122686671-1b5d9580-d21b-11eb-991c-ba4b4bd038ac.jpg)

**Comment by moepi2k** [comment]
check if it works on fresh project, if yes, its an issue in your project. im on 1.66b and everythings fine

**Comment by insthync** [comment]
Any server error log ?

**Comment by insthync** [comment]
Found it, I will fix it.

**Comment by brabaris** [comment]
Ok.

**Comment by insthync** [comment]
Fixed in 1.66c

**Comment by moepi2k** [comment]
https://gyazo.com/902185742e82553a07842f6b23132025

i tested with default projectile and i still got the issue on 1.66c

**Comment by insthync** [comment]
You see it hit at client but it might not hit at server.

**Comment by moepi2k** [comment]
exactly, i check it now with fresh 1.66c project

**Comment by insthync** [comment]
Must be because it has no lag compensation for missile damage entity.

**Comment by moepi2k** [comment]
Where can i see if it has lag compensation, the projectile is from default kit without any changes

**Comment by insthync** [comment]
I did not implement it yet

**Comment by moepi2k** [comment]
ah is lag compensation for raycast already added?

**Comment by insthync** [comment]
Yes, only have lag compensation for raycast
