### ISSUE TITLE
toggleAutoLogin does not work in 1.66b

### ISSUE THREAD

**Issue by TY3rd** [suriyun-production/mmorpg-kit-docs#1036]
The values stored to the PlayerPrefs are always empty.

The issue is solved by changing the following lines in UIMmoLogin.cs from:

            string storingUsername = string.Empty;
            string storingPassword = string.Empty;

to:

            string storingUsername = textUsername.text;
            string storingPassword = textPassword.text;

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.66c
