### ISSUE TITLE
4 new errors after deleting defaultinterestmanager.meta

### ISSUE THREAD

**Issue by lordarous** [suriyun-production/mmorpg-kit-docs#1039]
1st error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(14,18): error CS0101: The namespace 'MultiplayerARPG' already contains a definition for 'GameDatabase'
2nd error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(13,6): error CS0579: Duplicate 'CreateAssetMenu' attribute
3rd error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(42,30): error CS0111: Type 'GameDatabase' already defines a member called 'LoadData' with the same parameter types
4th error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(68,21): error CS0111: Type 'GameDatabase' already defines a member called 'LoadReferredData' with the same parameter types

**Comment by insthync** [comment]
It looks like that you have import duplicated file, you have to delete files with the same name. You may try find files `GameDatabase` in `Project` tab, if it has more than 1 file, delete it.

**Comment by lordarous** [comment]
even more, errors came out, initially, it was quite a handful of errors too. it had 41 yellow and 2 red, but now it has 41 yellow and 5 reds[
![41yellow 5 reds](https://user-images.githubusercontent.com/86187446/122880045-22e08400-d36c-11eb-8a12-56c94cc7e1bd.png)
](url)
like I said, please do a tutorial on how to use them, because I tried all tutorials of your MMORPG kit that wasn't from you, and either it doesn't have what is shown on the youtube video, or somehow, unable to achieve what they did.

**Comment by insthync** [comment]
Try press clear button, I want to see only compile error, you can ignore some error which won't block you to play game. I did tested the package on 2021.1.11, and it has no problem

**Comment by insthync** [comment]
You said about tutorials, can you tell me where it is ?

**Comment by lordarous** [comment]
it's on youtube, search for "MMORPG kit tutorial" and most of it are tutorials for your kit. at least it seems to be, and sadly while I have so many resources, I don't know how to use them at all, I mean "at ALL" it's like I am given a precious metal but I don't know how to use it for my advantage. it's the same thing here, I paid 80usd but I don't know how to use all these assets, then why did I buy it for?
unless you don't mind me asking almost everything on how to use from configuring the server to configuring these assets properly

**Comment by insthync** [comment]
It might be made by me, I don't get why you can't do anything at all, at least you should be able to start offline demo by open 00Init scene and press play.

**Comment by lordarous** [comment]
I can get scenes going but only "Gamedata" i can't duplicate,  don't know why.

**Comment by insthync** [comment]
Is there any error when you try to duplicate ?

**Comment by insthync** [comment]
You may try use game database manager to manage game data

![Screenshot_455](https://user-images.githubusercontent.com/2697550/122899877-693ae080-d376-11eb-9605-10f99ac05aee.png)

![Screenshot_456](https://user-images.githubusercontent.com/2697550/122899961-7bb51a00-d376-11eb-998c-0cb091a4388b.png)

**Comment by lordarous** [comment]
> Is there any error when you try to duplicate?

when I select Gamedata and press ctrl + d, nothing happens, when I use edit>duplicate also nothing happens

**Comment by lordarous** [comment]
> You may try use game database manager to manage game data
> 
> ![Screenshot_455](https://user-images.githubusercontent.com/2697550/122899877-693ae080-d376-11eb-9605-10f99ac05aee.png)
> 
> ![Screenshot_456](https://user-images.githubusercontent.com/2697550/122899961-7bb51a00-d376-11eb-998c-0cb091a4388b.png)

I can access that Gamedata, but I can't duplicate and make a new one out for myself. when I copy your Gamedata script and create a new c# script, the error of having a new Gamedata are shown as above

> 1st error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(14,18): error CS0101: The namespace 'MultiplayerARPG' already contains a definition for 'GameDatabase'
> 2nd error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(13,6): error CS0579: Duplicate 'CreateAssetMenu' attribute
> 3rd error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(42,30): error CS0111: Type 'GameDatabase' already defines a member called 'LoadData' with the same parameter types
> 4th error: Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Database\GameDatabase.cs(68,21): error CS0111: Type 'GameDatabase' already defines a member called 'LoadReferredData' with the same parameter types

**Comment by insthync** [comment]
Did you duplicate the code file? If you are going to duplicate game database don't duplicate the code file.
![Screenshot_457](https://user-images.githubusercontent.com/2697550/122917189-f0448480-d387-11eb-9909-bca59b68c0b5.png)

You actually can create your game database by create menu instead of duplicating it.
![Screenshot_458](https://user-images.githubusercontent.com/2697550/122917403-30a40280-d388-11eb-9d80-321115ae2d59.png)

**Comment by lordarous** [comment]
nevermind, it's weird now I can duplicate it, it seems that after restarting my computer it happens to be able to duplicate, or maybe it's because I deleted the .meta file. don't really know.

**Comment by insthync** [comment]
I think it is not related to .meta file deleting because meta file is just made for store file ID and properties. It would not affect the editor.
