### ISSUE TITLE
1.49d BUG new area skills

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#104]
Damage from new AOEs now occurs very often.![image](https://user-images.githubusercontent.com/47291794/66919073-56acc780-f029-11e9-9f1b-4a683bd4565e.png)

and the recovery time of one skill occurs 2 times

Everything seems to be in order in the new version. It's just me

**Comment by DimasjkTV** [comment]
I recreated the skill and the cooldown of the skill now happens 1 time

**Comment by insthync** [comment]
![Screenshot_97](https://user-images.githubusercontent.com/2697550/66920672-fa0fd380-f04d-11e9-93b4-b1904e253aab.png)
Try set `Apply Duration`

**Comment by DimasjkTV** [comment]
Yes. That helped. You can close it. Thanks =)
