### ISSUE TITLE
About damageReceiver play unique Hurt and Dead animations

### ISSUE THREAD

**Issue by gkegkn** [suriyun-production/mmorpg-kit-docs#1040]
Could you please tell me how to let damageReceiver play unique Hurt and Dead animations when attacker equipped with different weapons?

**Comment by insthync** [comment]
If you want to do it without CORE code changes, you may create a new component which attaches to the same game object with the `PlayerCharacterEntity` (or `MonsterCharacterEntity`), the component will set `PlayerCharacterEntity` -> `onReceiveDamage` event to change hurt and dead clip by change `AnimatorCharacterModel` -> `CurrentAnimatorController` clip (`CurrentAnimatorController[CLIP_HURT] = yourClip`).
```
public class ChangeHurtAndDeadAnimComp {
  void Awake() {
    var entity = gameObject.GetComponent<BaseCharacterEntity>();
    entity.onReceiveDamage += OnReceiveDamage;
  }
  void OnDestroy() {
    entity.onReceiveDamage -= OnReceiveDamage;
  }
  void OnReceiveDamage(
        Vector3 fromPosition,
        IGameEntity attacker,
        Dictionary<DamageElement, MinMaxFloat> damageAmounts,
        CharacterItem weapon,
        BaseSkill skill,
        short skillLevel)
  {
    AnimCollection animCollection;
    if (weapon == null || !animCollections.TryGetValue(weapon, out animCollection)
      return;
    var model = ModelManager.ActiveModel as AnimatorCharacterModel;
    model.CurrentAnimatorController[CLIP_HURT] = animCollection.hurtClip;
    model.CurrentAnimatorController[CLIP_DEAD] = animCollection.deadClip;
  }
}
```
I didn't try it yet.
