### ISSUE TITLE
1.66c Animator Error

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1041]
After Update to 1.66c sometimes when login to game i got this error

`NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.AnimatorCharacterModel+<PlayActionAnimation_Animator>d__73.MoveNext () (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Model/3D/AnimatorCharacterModel.cs:687)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <526469d5a48c43eebd9af19f8745afa1>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
MultiplayerARPG.AnimatorCharacterModel:PlayActionAnimation(AnimActionType, Int32, Int32, Single) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Model/3D/AnimatorCharacterModel.cs:677)
MultiplayerARPG.<UseSkillRoutine>d__48:MoveNext() (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterSystems/CharacterActionsSystem/DefaultCharacterUseSkillComponent.cs:301)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(Object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.DelayIgnoreTimeScalePromise:MoveNext() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.Delay.cs:675)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:104)`

then also in login screen, player has no animations

**Comment by insthync** [comment]
In your login screen your character will play any action animations (attack or use skill)?

**Comment by moepi2k** [comment]
no he only stand in t-pose without any animations

**Comment by insthync** [comment]
But in the log, it seems like something order it to play skill animation.

**Comment by moepi2k** [comment]
when login, in the login screen player just stand in t-pose without any errors. but this error appears when i try to attack. player is always in t-pose.
https://gyazo.com/4696ecfd6078a740ab87be4a06f1c384

also a logger issue i seen now.

`ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
Microsoft.Extensions.Logging.LoggerFactory.CreateLogger (System.String categoryName) (at <848d7ce8883c402a930e4bccac6ee80e>:0)
ZLogger.UnityLoggerFactory+DisposingLoggerFactory.CreateLogger (System.String categoryName) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/Unity/UnityLoggerFactory.cs:240)
LiteNetLibManager.LogManager.GetLogger (System.String tag) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LogManager.cs:90)
LiteNetLibManager.Logging.LogWarning (System.String tag, System.Object message) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Logging.cs:25)
MultiplayerARPG.GameSpawnArea`1[T].LateUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:53)`

weird

**Comment by moepi2k** [comment]
right now im on my laptop,

i will test it on my computer again after work. just wanted to let u know, i dont know if its something from 1.66c or on mine side, but before updating everything was fine

**Comment by insthync** [comment]
May I try looks at it by TeamViewr?

**Comment by moepi2k** [comment]
let me check first if its not an issue on my side. yesterday on my computer it worked, maybe there was an issue when i uploaded project to git and now downloaded to laptop. i test when im home and let you know :) thanks for your time

**Comment by moepi2k** [comment]
ok same issue on computer. if you have time im ready for teamviewer

**Comment by insthync** [comment]
Okay, I've time now, send your info to my email ittipon.bay@gmail.com

**Comment by moepi2k** [comment]
done
