### ISSUE TITLE
StatusEffect  selfStatusEffectsWhenAttacked

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1042]
in the Status Effect as I understand ** selfStatusEffectsWhenAttacked** should add x characteristic apply status effects to the character equipped with an item when attacked. But it's not working that way

if not that works the same as selfStatusEffectsWhenAttacking

version 1.66c

**Comment by insthync** [comment]
If `A` attacking `B`, `selfStatusEffectsWhenAttacked` will applies on `B`

**Comment by Blunnyn** [comment]
https://youtu.be/PbDE0XlDG-s

**Comment by Blunnyn** [comment]
When attacking a monster the buff is obtained by the player and it should be the monster who obtains the buff, right?

**Comment by insthync** [comment]
Try fix it in `DefaultGameplayRule` I don't have time yet.

**Comment by insthync** [comment]
Okay, fixed in 1.66d
