### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1044]
There is version control in the asset?. I was having the problem that people that dont update was able to log in.

**Comment by insthync** [comment]
You mean version checker? Which is if players have a difference version it should bring players to download page? No, I did not implement it to the kit yet.

**Comment by MosesGomez** [comment]
> You mean version checker? Which is if players have a difference version it should bring players to download page? No, I did not implement it to the kit yet.

Ooooh okay :D. Thanks
