### ISSUE TITLE
Option to set Blendmode for Animations

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1045]
is it possible to add option for animation for blending 

https://gyazo.com/3b46a1d1e8654ca4a06ccf134424abb8

in shooter you often need additive for shoot animation
but the rest lik reloading and so on is override

animatopm["YOURANIM"].blendMode = AnimationBlendMode.Additive;

**Comment by insthync** [comment]
Unity doesn't have any function that allows me to do it programmatically. Only a playable character model (which made by playable APIs) can do it, but I didn't add the option yet.

**Comment by insthync** [comment]
In 1.69
```
- Add `Is Additive` setting to playable character model's `Anim State` and `Action State` structs.
```
