### ISSUE TITLE
where do i find modularRPGheroes & modularAnimalKnight

### ISSUE THREAD

**Issue by lordarous** [suriyun-production/mmorpg-kit-docs#1046]
it's not inside my default folder, even after restarting my computer, I don't know where to find it. when I imported, these are what I get, but not those 2 modular folders. please guide and thanks for your patience too, as I am very new to unity.
![where is modularRPGheroes and modularAnimalKnight](https://user-images.githubusercontent.com/86187446/123083839-12570900-d453-11eb-88ce-1e6dbd901074.png)

I tried finding in asset store, but found nothing about it.

**Comment by insthync** [comment]
Have to buy it from 

https://assetstore.unity.com/packages/3d/characters/humanoids/fantasy/modular-rpg-hero-polyart-138600

**Comment by insthync** [comment]
Seems like you are never use Unity, aren't you?

**Comment by lordarous** [comment]
can there be other replacements for these modular assets?

**Comment by lordarous** [comment]
> Seems like you are never use Unity, aren't you?

yes sorry, very new to unity, thanks for you help

**Comment by insthync** [comment]
Yes, you can use other assets for character

**Comment by lordarous** [comment]
sorry, I don't know why my character couldn't move, be it left clicking or press W A S D. is something wrong with my config?

**Comment by lordarous** [comment]
After I added the component of Rigid body entity movement script and tested my map, my character kept falling into the abyss and dies. when I checked your video and mine, our difference was that I have no ground check distance for my script, but the thing is, I did not change nor alter anything at all, as you did in the video. 
![no ground check system](https://user-images.githubusercontent.com/86187446/123131817-a2f80e00-d480-11eb-9ebb-e01fb680a49c.png)

**Comment by insthync** [comment]
I will remake all new videos this weekend l, now it is a lot easier to create character

**Comment by lordarous** [comment]
thanks mate ^^

**Comment by lordarous** [comment]
oh and, is it possible for you to do a tutorial on how to do the settings for multiplayer, for server and client side? sorry if I am asking too much, because I am totally clueless on how to use all these

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/

**Comment by insthync** [comment]
Are you have knowledge about networking, database?

**Comment by lordarous** [comment]
quite clueless about networking and database, have tiny bit of idea only

**Comment by lordarous** [comment]
> I will remake all new videos this weekend l, now it is a lot easier to create character

what would your new video be named as?
