### ISSUE TITLE
Projectile dont hit sometimes in MMO mode

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1047]
like i already posted in the other closed thread i thought i opened a new one because this is a critical bug.
https://gyazo.com/d734cd4e95949aa37ec0a105e358d6ab

i tested now many things. and i cant find the issue.
it happen only in mmo mode that MissileDamageEntity projectiles dont hit.

with that bug its unplayable and make no fun. im sure i dont had this issue in the past. any ideas how to fix it?

**Comment by insthync** [comment]
You may help me find out what it hitting

**Comment by insthync** [comment]
Because it should hit that very near character, but it seems like it hot something else.

**Comment by moepi2k** [comment]
https://gyazo.com/c0efdb117f08b2a6b02e87a02ec3218c

https://gyazo.com/1beb2092cd6ccc0469535ed2b0933b33

**Comment by moepi2k** [comment]
this pic is hit on a enemy the not count as hit

https://gyazo.com/2d242e0bbea8c9a9a40261f03310e487

**Comment by moepi2k** [comment]
soo i tested with fresh kit 1.66c.

first i thought its an issue in my project because on fresh project it worked for the first time, but after testing a while i saw the issue is also on fresh project.

https://gyazo.com/a929655cbe15e450e7bb73a20603c870

i hope you can reproduce it and fix it

**Comment by insthync** [comment]
Yep, I think it is because of hit box, it must hit the hit box to applies damage, but it hitting character's colliders which used for movement .

**Comment by insthync** [comment]
I can't reproduce it yet, may I try on your PC ?

**Comment by moepi2k** [comment]
Yea its difficult to reproduce it, i set missile speed to 30 and distance to 15 thats all i changed,but sure you can try here

**Comment by insthync** [comment]
Try add 
```
            if (CurrentGameInstance.DimensionType == DimensionType.Dimension2D)
            {
                if (CacheRigidbody2D != null)
                    CacheRigidbody2D.velocity = Vector2.zero;
            }
            else
            {
                if (CacheRigidbody != null)
                    CacheRigidbody.velocity = Vector3.zero;
            }
``` 
To `OnPushBack` function
![Screenshot_461](https://user-images.githubusercontent.com/2697550/123371636-59a4dd00-d5ac-11eb-9bd9-aa2e5a055a44.png)

**Comment by moepi2k** [comment]
same issue :(

**Comment by insthync** [comment]
Let make an appointment to try it on your PC, send me your TeamViewer info when you're ready.

**Comment by LordPhrozen** [comment]
I actually think you can see this happening in the official video showing off the FPS camera at :38 in. The first shot on the greatsword wielding orc should have hit but just fizzles.

https://youtu.be/yIxPP37nuVA?t=35

**Comment by moepi2k** [comment]
your right @LordPhrozen 

@insthync i sent teamviewer data per mail

**Comment by Monty001** [comment]
Is this what's happening? I recorded server(top) and client(bottom) perspective and slowed it down. You can see the projectile be destroyed client side but not do anything where on the server it carries on past.

https://www.youtube.com/watch?v=uoH5TUFoe2g

**Comment by Monty001** [comment]
Maybe this to, on the client all of these projectiles from the player started in the middle, registered hits but did no damage.

The view from the server in the video below, you can see projectiles spawning in different positions. The most obvious ones being at 1 second and 7 seconds. As they spawn so far left, they actually miss on the server which I guess is why no damage got dealt.

https://www.youtube.com/watch?v=MqmdZLbiAqM

**Comment by insthync** [comment]
> Maybe this too, on the client all of these projectiles started from the middle of the player and registered hits / destroyed the object but did no damage.
> 
> The view from the server in the video below, you can see projectiles spawning in different positions. The most obvious ones being at 1 second and 7 seconds. As they spawn so far left, they actually miss on the server which I guess is why no damage got dealt.
> 
> https://www.youtube.com/watch?v=MqmdZLbiAqM

Yes, that is why I try to set rigidbody's velocity to 0 when disable the object, because it seems like it is going to update velocity immediately when re-eanable the object

**Comment by moepi2k** [comment]
@insthync i sent you teamviewer data again. if you have time feel free to login.

**Comment by moepi2k** [comment]
Sorry dont saw your mail. I was not online overthe weekend, let me know when you have time, then we can plan exactly the time

**Comment by moepi2k** [comment]
Ok im abit near to the problem, figured out some stuff and noticed some other issues that should be fixxed. Do you have time for teamviewer tomorrow? Now its 00:00 am here. I have time the whole day @insthync

**Comment by insthync** [comment]
I have time today, tell me your TeamViewer info to my email when you're ready.

**Comment by moepi2k** [comment]
Ok im at computer in about 30min,then i will send it

**Comment by moepi2k** [comment]
im ready i sent you tw data
