### ISSUE TITLE
FpsHands -> Player clone

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1048]
when i use shootercontroller with FPS and add FpsHands Prefab to the CharacterModelManager. it clones the player when enter game.

https://gyazo.com/9b2d6183fa9fe907c37cc6d598ec9db8
https://gyazo.com/c0141b5702d393093e11000ef454b1e7

**Comment by moepi2k** [comment]
ah it seems this only happen when i add AnimatorCharacterModel component to the FpsHands
with AnimationCharacterModel it works.

so whats the diffrent?

**Comment by insthync** [comment]
I will check it, latest version changed how animator controller caching.

**Comment by insthync** [comment]
Fixed in 1.67b
