### ISSUE TITLE
 `Animator` is empty error

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1049]
do you know what this error means or how to get rid of it? i am unable to figure it out any guidance is appreciated

`Animator` is empty
UnityEngine.Debug:LogError (object)
ZLogger.Providers.UnityDebugLogProcessor:Post (ZLogger.IZLoggerEntry) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/Unity/ZLoggerUnityLoggerProvider.cs:69)
ZLogger.AsyncProcessZLogger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/AsyncProcessZLogger.cs:36)
Microsoft.Extensions.Logging.Logger:<Log>g__LoggerLog|12_0<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.ILogger,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>,System.Collections.Generic.List`1<System.Exception>&,Microsoft.Extensions.Logging.FormattedLogValues&)
Microsoft.Extensions.Logging.Logger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>)
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,System.Exception,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:LogError (Microsoft.Extensions.Logging.ILogger,string,object[])
LiteNetLibManager.Logging:LogError (string,object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Logging.cs:18)
MultiplayerARPG.AnimatorCharacterModel:OnValidate () (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Model/3D/AnimatorCharacterModel.cs:413)

**Comment by insthync** [comment]
Set this

![Screenshot_459](https://user-images.githubusercontent.com/2697550/123259426-a6da6d80-d51e-11eb-93d4-747a84d74d60.png)

**Comment by Sour-J** [comment]
It's already set I dragged the player main root over again and it still happens but the character works fine this error can clear but just worried something might be wrong if I leave it but yes it's same as your picture

**Comment by insthync** [comment]
This should be showing up in the editor only when just add `AnimatorCharacterModel` component to game object which has no `Animator` component attached.
