### ISSUE TITLE
Disconnection problem

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1051]
Single player mode
Sometimes I get this error. A very rare error.
![image](https://user-images.githubusercontent.com/47291794/123406495-a8a24080-d5b3-11eb-98a5-f5f58d0cd06b.png)

**Comment by insthync** [comment]
Oh, I will check it.

**Comment by insthync** [comment]
I will close this, if it is still occurring, you can reopen it.
