### ISSUE TITLE
Last version Android build

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1052]
Cant build for Android

![image](https://user-images.githubusercontent.com/47291794/123472519-f2b11380-d5ff-11eb-93fe-637422c29a24.png)
![image](https://user-images.githubusercontent.com/47291794/123472602-0b212e00-d600-11eb-8ca5-7928c7eff880.png)

Everything is fine in the fresh project. It looks like I haven't added something after the update

**Comment by insthync** [comment]
![Screenshot_463](https://user-images.githubusercontent.com/2697550/123474106-aed00580-d623-11eb-9117-bac7891b434c.png)

Try delete this line

**Comment by insthync** [comment]
Then tell me, is it work or not :P

**Comment by DimasjkTV** [comment]
> Then tell me, is it work or not :P

fresh project works well without deleting this code. Trying delete in my project.

**Comment by DimasjkTV** [comment]
> Then tell me, is it work or not :P
Now this. 
![image](https://user-images.githubusercontent.com/47291794/123476657-af59a380-d605-11eb-9dd8-b8ab9d24fc5b.png)

I had errors with animators before, but they did not interfere with the creation of the apk file. Now can it affect it?

**Comment by insthync** [comment]
This should showing up when `AnimatorCharacterModel` -> `controllerType` is `Custom` and there is no `animatorController` was set. Or if `controllerType` set to `Simple` or `Advance` but there is no animator controller (`__Animator/__SimpleCharacter` and `__Animator/__AdvanceCharacter`) in resource folder.

**Comment by DimasjkTV** [comment]
> This should showing up when `AnimatorCharacterModel` -> `controllerType` is `Custom` and there is no `animatorController` was set. Or if `controllerType` set to `Simple` or `Advance` but there is no animator controller (`__Animator/__SimpleCharacter` and `__Animator/__AdvanceCharacter`) in resource folder.

![image](https://user-images.githubusercontent.com/47291794/123487671-12a00180-d617-11eb-860d-3660eb1236a1.png)

**Comment by DimasjkTV** [comment]
> This should showing up when `AnimatorCharacterModel` -> `controllerType` is `Custom` and there is no `animatorController` was set. Or if `controllerType` set to `Simple` or `Advance` but there is no animator controller (`__Animator/__SimpleCharacter` and `__Animator/__AdvanceCharacter`) in resource folder.

now only this 
![image](https://user-images.githubusercontent.com/47291794/123488259-3879d600-d618-11eb-99a2-50ca03ee007b.png)
I can't understand why on a fresh project the apk is created without problems and errors. My project has this error. Looks like you need to add something? Or delete something. T_T

**Comment by insthync** [comment]
When you try build the fresh project, you try to build as IL2CPP APK ?

**Comment by DimasjkTV** [comment]
> When you try build the fresh project, you try to build as IL2CPP APK ?

Fresh and my with same settings
![image](https://user-images.githubusercontent.com/47291794/123489216-29942300-d61a-11eb-80ff-91d3a1f3d5eb.png)

**Comment by DimasjkTV** [comment]
> When you try build the fresh project, you try to build as IL2CPP APK ?

i think problem in my some asset but not sure

**Comment by DimasjkTV** [comment]
I just created an apk file on my copied project, which was based on one of the 1.64 versions. Seem to be. that some features of the new version caused some kind of conflict with some kind of asset. Is that possible?

**Comment by insthync** [comment]
How about this setting?
![Screenshot_464](https://user-images.githubusercontent.com/2697550/123491817-e057c980-d641-11eb-97a3-da17732c169b.png)

**Comment by DimasjkTV** [comment]
Oh my god. The problem was that the title of the copied project had a Russian word that caused this problem. I faced this situation for a long time and forgot about it. Sorry for that. My bad...
