### ISSUE TITLE
Monster Skill ussage

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1058]
is it possible to improve the function for checking ammo/items for skills when monster use it?

because when you add a skill to monster which require ammo/item, they cant use it.
when its fixed you are able to use same skills for monster and players. without you need everything twice

https://gyazo.com/b186895e2db595bdf1a072481b6a161d

**Comment by insthync** [comment]
Okay, I will change it

**Comment by moepi2k** [comment]
also for this, is it possible to post fix here :P or coming next update soon?

**Comment by insthync** [comment]
![Screenshot_520](https://user-images.githubusercontent.com/2697550/125955904-917de3ae-c3de-437f-88c1-d0b43cb82c60.png)

**Comment by moepi2k** [comment]
mh same issue, monster never use skill.

**Comment by insthync** [comment]
Oh, I see, here is what I did.

![Screenshot_543](https://user-images.githubusercontent.com/2697550/126086333-8b7ab7d3-a07b-4e97-aad3-0b9c9e9b04ac.png)

**Comment by moepi2k** [comment]
great thanks, looks cleaner :P
