### ISSUE TITLE
Bulding suggestion / Bug fix

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#1060]
![image](https://user-images.githubusercontent.com/57778639/124111715-96068c00-da37-11eb-98a8-19dc01325a58.png)

Just a suggestion here but i think it would be better that "IF" you can place the piece it lines up better with the pieces near it. Give it a little room for adjustment perhaps.

**Comment by Fallen01** [comment]
Most these building systems snap together and this system really needs that i think.

**Comment by moepi2k** [comment]
it does, i think you made something wrong with the containers. if you setup correct it snap perfect in line

**Comment by Fallen01** [comment]
i copied the existing set up, but i will try again.

**Comment by Fallen01** [comment]
after messing with it for quite awhile ive discovered it has an issue with depth. I had to add extra empty space to the collider to get it to work correctly but the results are pretty much perfect, so complaint withdrawn lol

**Comment by Fallen01** [comment]
![image](https://user-images.githubusercontent.com/57778639/124205682-ba05b400-daaf-11eb-81f1-e2a67f943121.png)

**Comment by Fallen01** [comment]
Maybe its the model if you guys are not having similar issues *shrugs* But thank you for pointing out the set up could be bad.
