### ISSUE TITLE
Stress Test 166D

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1062]
I have send u a Document in ur Mail about the stress test i performed..

Here is a video showcasing the default map with 450 players on 1 scene .

https://youtu.be/WMsAW0E18Eg

and another with 20k entities on the map

https://user-images.githubusercontent.com/7702658/124341598-c710c900-dbbd-11eb-91b4-4400ab4e4a21.mp4

The improvements the changes on the kit networking aspect has been amazing.. i honestly didnt expect it to go up so much

**Comment by Callepo** [comment]
@insthync have u received the Stress test results through mail ?

**Comment by insthync** [comment]
Re-send it to ittipon.bay@gmail.com :)

**Comment by Callepo** [comment]
done

**Comment by insthync** [comment]
Thank you :)

**Comment by Fr-Coder** [comment]
@Callepo 35% CPU usage was related to the single-core used for that map or 35 % of total CPU?

**Comment by Callepo** [comment]
total
