### ISSUE TITLE
An error occurs when using 'Status Effect when attacking' as skills.

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#1063]
An error occurs when using 'Status Effect when attacking' as a skill.

Can't I use 'Status Effect when attacking' as a passive skill?

please Update....

![dfdfdf](https://user-images.githubusercontent.com/58978516/124396759-81333c80-dd46-11eb-908c-44346ee6b0d5.png)

**Comment by insthync** [comment]
Okay, I will do it.

**Comment by insthync** [comment]
Fixed in 1.67
