### ISSUE TITLE
Item Dupe in MMO

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1066]
i dont know how to reproduce but see video
https://gyazo.com/8d3eea2e48327e437cc21d42250366ea

after placing my chest and put some items in furnance. the chest will dupe in inventory

**Comment by moepi2k** [comment]
ok it happen to buildingparts only. to reproduce. 

1) put 1 campfire in your inventory. 
2) place the campfire
3) go to a placed chest or campfire and put an item init
4) the last placed building item will be duped

**Comment by insthync** [comment]
I will fix it.

**Comment by moepi2k** [comment]
is it possible to post fix here if its small? we wanted to make a mmo test, but not possible with this bug

**Comment by insthync** [comment]
https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/a45da19ec037da6ffd13618794819a61df5d35f8

**Comment by moepi2k** [comment]
great thanks, that fixed it
