### ISSUE TITLE
Unity version 2021 question

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1069]
Hello,
Do you think I'll have an issue with the kit if I use unity 2021 latest? It seems to be fine.

**Comment by insthync** [comment]
It should be fine if you have problems you can tell me.

**Comment by RunOrDi3** [comment]
@Sour-J Neomis using 2021 and no issues so should be fine.

**Comment by Sour-J** [comment]
Thank you much appreciated
