### ISSUE TITLE
How do I upgrade my plug-ins to the latest version after the project has been in production for a long time? Prompt me when installing the plug-in (please import in the new project, it will overwrite the original project)

### ISSUE THREAD

**Issue by qipaworld** [suriyun-production/mmorpg-kit-docs#107]
How do I upgrade my plug-ins to the latest version after the project has been in production for a long time? Prompt me when installing the plug-in (please import in the new project, it will overwrite the original project)

**Comment by insthync** [comment]
You can import just `Core`, `MMO\Plugins` and `MMO\Scripts` folders to update your project
![Screenshot_100](https://user-images.githubusercontent.com/2697550/66984535-1579ed80-f0e5-11e9-822e-5dfb73574b39.png)

**Comment by qipaworld** [comment]
Thank you
