### ISSUE TITLE
I have a target problem. 

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1070]
When I try to atack enemies in the top part it doesnt deal any damage or target other enemies.  

In the picture you can see the position where if you try to attack the enemy you cant. 
![Screenshot_668](https://user-images.githubusercontent.com/12781104/125238716-d7533300-e2a4-11eb-9961-9cc4e4c39ebd.png)

**Comment by insthync** [comment]
I want to try it, you can make an appointment to test it on your PC via TeamViewer

**Comment by insthync** [comment]
I want to see how you set colliders, you should have one for movement wall hit and another one for damage hit detection.

**Comment by MosesGomez** [comment]
Sorry for late repply. Ill send screenshot. 
![Captura](https://user-images.githubusercontent.com/12781104/126396830-04a3a252-aa81-4b73-beca-85c5ea680918.PNG)
![Captura](https://user-images.githubusercontent.com/12781104/126396848-6107b5b0-6036-4645-82f8-1c9c8cf23fc8.PNG)

**Comment by insthync** [comment]
How about `Damage transforms ? is it centered on the character?

![Screenshot_550](https://user-images.githubusercontent.com/2697550/126435541-2a4c9cc4-33a3-4226-a2d9-dcc152ea6f03.png)

![Screenshot_551](https://user-images.githubusercontent.com/2697550/126435645-e7b8473d-0c14-4d34-b89a-b90c844e822c.png)

**Comment by MosesGomez** [comment]
> How about `Damage transforms ? is it centered on the character?
> 
> ![Screenshot_550](https://user-images.githubusercontent.com/2697550/126435541-2a4c9cc4-33a3-4226-a2d9-dcc152ea6f03.png)
> 
> ![Screenshot_551](https://user-images.githubusercontent.com/2697550/126435645-e7b8473d-0c14-4d34-b89a-b90c844e822c.png)

Melee transform wasnt centered. 
![Captura](https://user-images.githubusercontent.com/12781104/126671223-3371caf6-f6b5-42de-b280-e3467d934034.PNG)

**Comment by insthync** [comment]
So the monster located below your character might not be receiving damages because it is not in attack range.

Damages will apply to monsters within attack range from the damage transform's position

**Comment by insthync** [comment]
No response, so I will close it.
