### ISSUE TITLE
Invisible Bug lol

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1072]
Now u see me Now u dont !

https://user-images.githubusercontent.com/7702658/125331389-37e77c00-e348-11eb-9248-cad56b8045e7.mp4

Using buff  ishide
![image](https://user-images.githubusercontent.com/7702658/125331418-42097a80-e348-11eb-8aa2-3ac5d11d801e.png)

doesnt just hide urself.. but every single entity in the scene.. Literally all...

**Comment by insthync** [comment]
Thank you for bug reporting, I will fix it.

**Comment by insthync** [comment]
Fixed https://github.com/insthync/LiteNetLibManager/commit/1fa9cc6f30c7f11240bfa8884a3e0bbf7bd59d2b

**Comment by insthync** [comment]
Fixed in 1.67
