### ISSUE TITLE
BUG: Status effect & EXP

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1073]
If we use the reflection of damage using the status effect, then the character does not gain experience if the monster dies from this effect.

**Comment by insthync** [comment]
I will fix it.

**Comment by DimasjkTV** [comment]
> I will fix it.

can you post fix here? If you can

**Comment by insthync** [comment]
No, it changed a lot.

**Comment by insthync** [comment]
Fixed in 1.67
