### ISSUE TITLE
[Suggestion]Add Logout delay Timer

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1074]
would be great if you can add a logout delay timer. this make sense when you use pvp so that player cant quick logout like Alt + F4 for example when he nearly dead. so when you set delay to 1min and player are logged out, player remains in game for 1min and other have time to kill em.

this is common feature in mmos.

**Comment by verfirman** [comment]
+1

**Comment by brabaris** [comment]
+1

**Comment by RunOrDi3** [comment]
+1 , great idea

**Comment by brabaris** [comment]
+1

**Comment by Sour-J** [comment]
Please!!!

**Comment by insthync** [comment]
In 1.69c
- Add `Player Character Despawn Milliseconds Delay` to `Map Network Manager`. If players quit the game, their characters won't be destroyed immediately, it will have some delay before it was destroyed.
