### ISSUE TITLE
you can send money via mail, without having money

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#1077]
This made me giggle, but looks like its doable :D

**Comment by insthync** [comment]
Oh, I will fix it.

**Comment by insthync** [comment]
As I test it will check for the money before send the email, it's works properly, not sure why yours not work, you may check your UI events or check your codes is updated or not (https://github.com/insthync/UnityMultiplayerARPG_MMO/blob/main/Scripts/MMOGame/Networking/Map/MMOServerMailMessageHandlers.cs)

**Comment by LordPhrozen** [comment]
weird. ill double check.
