### ISSUE TITLE
Damage by direction - like backstab

### ISSUE THREAD

**Issue by gordowebdesign** [suriyun-production/mmorpg-kit-docs#1079]
It is possible to get direction of damage? (for regular damage and skill) Would like to have increased damage from sides and rear and to be able to create skills like backstab using angle of attack.

**Comment by Sour-J** [comment]
the kit already has this feature, 
1. simply add a collider on the player or monsters back mark the collider as trigger
2. then add the script damageable hitbox to the inspector
3.  change the values in the inspector to be like 3 thats 3 times the damage when hitting that collider.

thanks

**Comment by gordowebdesign** [comment]
> the kit already has this feature,
> 
> 1. simply add a collider on the player or monsters back mark the collider as trigger
> 2. then add the script damageable hitbox to the inspector
> 3. change the values in the inspector to be like 3 thats 3 times the damage when hitting that collider.
> 
> thanks

Thanks, but this is not really what I mean.  I mean to be able to do this in code on something like ReceiveDamage().  We already get Vector3 fromPosition of the attacker BUT how do I calculate directional position in relation is what I am trying to achieve.

**Comment by insthync** [comment]
Should I add an event or new function to gameplay rule to calculate the damage?

**Comment by insthync** [comment]
I've added 2 functions to `BaseGameplayRule`
- float RandomAttackDamage(Vector3 fromPosition, BaseCharacterEntity attacker, BaseCharacterEntity damageReceiver, DamageElement damageElement, MinMaxFloat damageAmount, CharacterItem weapon, BaseSkill skill, short skillLevel, int randomSeed) it will be called when calculating damage amounts for each damage element
- int GetTotalDamage(Vector3 fromPosition, EntityInfo instigator, DamageableEntity damageReceiver, float totalDamage, CharacterItem weapon, BaseSkill skill, short skillLevel) it will be called when it calculated and sum all damage amounts

You can override it by creating your own gameplay rule (by extends `BaseGameplayRule` or `DefaultGameplayRule`) and set it to the game instance component.
