### ISSUE TITLE
Full Inventory Issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#108]
https://youtu.be/OdcpokdIKOI

When inventory full and u unequip an item .. it add another slot instead of saying inventory full like when u try to buy from npc ( using limit Slot)

**Comment by insthync** [comment]
Fixed, :p

**Comment by Callepo** [comment]
is it small patch or alot of work ? if small can i get code here ?

**Comment by insthync** [comment]
It's a lot of changes :p

**Comment by Callepo** [comment]
ah rip.. ok

**Comment by insthync** [comment]
Fixed in 1.50
