### ISSUE TITLE
Missing reference script

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1080]
On every Character Entity the CharacterSkillAndBuffComponent is missing for some reason

![image](https://user-images.githubusercontent.com/7702658/126414176-6a54448a-174f-4137-8bdf-a3f8c706a2e4.png)

Missing

![image](https://user-images.githubusercontent.com/7702658/126414240-e1d1d952-9039-460e-9061-c5232c873b8e.png)

Dk why its not there anymore, u have to readd it manually for the message to go away.

It gets added automatically during play 
but still 

![image](https://user-images.githubusercontent.com/7702658/126414428-3546dc74-72ef-437f-8e18-dfecf177b24b.png)

**Comment by insthync** [comment]
Maybe it is Unity package export.

**Comment by insthync** [comment]
The script's GUID changed, I will re-export to fix it.

**Comment by insthync** [comment]
Re-exported and uploaded
