### ISSUE TITLE
mail button missing new version

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1081]
on updating the mail button goes missing this is a fresh install https://gyazo.com/7afa7f35fcb10ecb20461c624e929b27

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/126417079-809fef63-18d5-4237-894a-997dd3f44585.png)
This prolly why, its getting turned off cuase lan. only works mmo

**Comment by Sour-J** [comment]
oh thank you just worked before in single theres no need for it was just for testing ui
