### ISSUE TITLE
[Suggestion] Version checker in the asset. 

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1082]
I think we really need that one for the asset. I been trying but cant get it work.

**Comment by moepi2k** [comment]
+1

**Comment by insthync** [comment]
Here is just some example for version checker:

Write JSON file you may write it data like this:
```
{"ios_ver":"1.11", "android_ver":"1.10"}
```
and upload it to web-hosting

Then in the game client, uses Unity Web Request to request to the web and check the version by a running platform like this:
```
[System.Serializable]
public struct GameVersion {
    public string ios_ver;
    public string android_ver;
}

// Request and compare version
var request = UnityWebRequest.Get(uri));
yield return request.SendWebRequest();
var gameVer = JsonUtility.FromJson<GameVersion>(request.downloadHandler.text);
if (!string.Equals(Application.version)) {
    Application.OpenURL(downloadWebPage);
    return;
}
```

**Comment by MosesGomez** [comment]
> Here is just some example for version checker:
> 
> Write JSON file you may write it data like this:
> 
> ```
> {"ios_ver":"1.11", "android_ver":"1.10"}
> ```
> 
> and upload it to web-hosting
> 
> Then in the game client, uses Unity Web Request to request to the web and check the version by a running platform like this:
> 
> ```
> [System.Serializable]
> public struct GameVersion {
>     public string ios_ver;
>     public string android_ver;
> }
> 
> // Request and compare version
> var request = UnityWebRequest.Get(urlToTheJsonFile));
> yield return request.SendWebRequest();
> var gameVer = JsonUtility.FromJson<GameVersion>(request.downloadHandler.text);
> if (Application.platform == RuntimePlatform.Android && !gameVer.android_var.Equals(Application.version)) {
>     Application.OpenURL(urlToDownloadAndroidClient);
>     return;
> }
> if (Application.platform == RuntimePlatform.IPhonePlayer && !gameVer.ios_var.Equals(Application.version)) {
>     Application.OpenURL(urlToDownloadiOSClient);
>     return;
> }
> ```

Thanks sury, I have a question, how can I do that but instead of web host Ill use the server for that. I get a null error while trying with server.

**Comment by MosesGomez** [comment]
![Captura](https://user-images.githubusercontent.com/12781104/127385418-8c960540-64b6-4a10-ae1e-48790af1bd03.PNG)
Im getting this error

**Comment by insthync** [comment]
I think You should create a new component instead of putting it to `UIMmoServerList`.

About the code above it is just a sample I didn't test it yet, but it should give you some idea.

**Comment by insthync** [comment]
If you still don't know how to do it, you may check https://github.com/insthync/simple-version-checker
