### ISSUE TITLE
Spawning Issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1083]
theres a few others in discord with the same issue very strange im not new to the kit i know how to do spawns but something changed somewhere because it didnt do this before, I dont have any other camera in my scene i just have a custom terrain and the player spawns at 0,0,0 when its a new character OR its just spawning back on the server after exiting. When i die the respawn works perfectly, ive even tried the overrides nothing works my initial spawn is under the terrain no matter what
https://gyazo.com/b939f991aaa8a08278d4964f956e5503
https://gyazo.com/d6ff86d8f649ba39048f4776a16b738c

**Comment by insthync** [comment]
So the problem is your character not spawned at start position when you just created the character and when you enter the game?

**Comment by insthync** [comment]
It always occurring or just sometimes? As I try it's still working properly.

**Comment by insthync** [comment]
Offline game or MMO ?

**Comment by Sour-J** [comment]
offlinelan and mmo, so yes the start position is not working for all characters. even male female they all spawn at 0,0,0 but it wasnt like that before in earlier versions, its always when you make a new charatcer it spawns at 0.0.0 or when you leave the game and come back in it puts it at the spawn point 0.,0,0 but when you die and respawn it works with the map info respawns perfectly, so its initial spawn and when you leave and rejoin the game it puts you at initial spawn of 0.0,0 its happening to a few of us in discord with custom terrains, is there a way to remove the inital respawn and just use map info repawns because i clicked overide spawn on the map info but it doesnt override the initial spawn

**Comment by Sour-J** [comment]
heres when i join the game: https://gyazo.com/b6fd3cbd1d3cffa570142ae1fcb10124
heres when i click respawn because falling under the terrain kills me: https://gyazo.com/d4703571c078e9bb2f869f3ffa3ba5ac

**Comment by insthync** [comment]
May I try on your PC by TeamViewer?

**Comment by insthync** [comment]
If you're ready and allow me to do it, send your TeamViewer info to my email: ittipon.bay@gmail.com

**Comment by Sour-J** [comment]
yes please thank you, no matter what i do i spawn at 0.0.0 i tried just making a new map info same thing, even checked the class, i emailed you. im making a survival game i was wondering if i could just remove the initial spawn and replace it with the respawn points instead. I really dont need an initial spawn

**Comment by Sour-J** [comment]
weird thing is i just found out its actually doing the initial spawn after i fall from 0.0.0 and the respawn points are not working just the initial spawn AFTER the 0.0.0 spawn

**Comment by Sour-J** [comment]
it will respawn me at the correct initial NOT respawn i was mistaken but thats only after a inital spawn at 0.0.0 then it goes to whatever it set at after that

**Comment by Sour-J** [comment]
its 3am here I missed you on that teamviewer offer but im going to head to sleep. i wonder if theres a way i can just not use the initial spawn and just use override respawn points in the map info as my initial spawn because in survival games you dont spawn in the same spot its random around the map

**Comment by insthync** [comment]
Now I don't get whats you actually want, it is pretty confusing to me what is initial spawn what is respawn point, 

- How do you remove the initial spawn point?,
- How do you override the respawn point? 
- Did you set `Override respawn point mode` to `Override`?

**Comment by Sour-J** [comment]
Ok when i make a new character or rejoin the game it puts me at 0.0.0 and i fall and die and respawn at the map info spawn point
https://gyazo.com/01711a85907847ee30f33a659e3faef2

Ive tried everything to fix it searched all around, so i figured to get around this bug im having that seems unfixable, i just want to remove the spawn point and have the character spawn at the override respawn points instead in the map info. 

I was originally asking for help with the 0.0.0 spawn point, it works after i die from falling at 0.0.0 so something is bugged with my spawn point, so i decided to remove it since i have a survival game and i want random spawn points so can the spawn point be removed and replaced with the override respawn points?

**Comment by Sour-J** [comment]
Basically need the player to start at one of the respawn points instead of the start position 

Hope this will fix my issue with the 0.0.0 start position

**Comment by Sour-J** [comment]
It doesn't matter what I set for any spawn positions I always spawn at 0.0.0 at start of the game so I'm hoping that removing start position works

**Comment by Sour-J** [comment]
Spawn position is on the map info middle section there's only one point. 

Respawn position is when you die and hit respawn I'm using the override on the map info

**Comment by insthync** [comment]
Okay, so your problem is just you can't use override spawn points for the newly created characters, right?

**Comment by Sour-J** [comment]
Correct it works as normal after I spawn at 0.0.0 then die and click respawn. I want to remove the new character spawn point. But this also happens when I log back into a old character they spawn at 0.0.0 then the overrides work after death.

**Comment by Sour-J** [comment]
Maybe it's because I'm using terrain and not a plane? I'm going to make a video and go thru all the respawn settings on it and show you tommorow

**Comment by insthync** [comment]
- It never uses `override respawn points` as the newly created character's start position, it will be used when respawning only, can be improved later by adding some codes, 

- `useOverrideStartPosition` and `overrideStartPosition` settings in `PlayerCharacter` game data are mean it will override `Map Info` -> `Start Position`, NOT uses `override respawn points`.

So those are whats you might misunderstand.

* * *

About the terrain, it does not have to be a plane, it has codes that finding a grounded position within range but you still have to set point nearly with the grounded position.

* * *

The problem I see here is the wrong re-login character's position.

**Comment by Sour-J** [comment]
so i tried to override the start position in character https://gyazo.com/8987640c66b0bf4c7feec7f889e167f0 and it still puts me at 0.0.0 then when i fall to death it puts me at the correct start point.

How do i remove the start point completely from the kit and just start at override respawn points instead something is really wrong here and with re-login puts me at .0.0.0 what could be causing this? any ideas? i tried deleting my library folder and searched and did everything suggested in discord. my map info: https://gyazo.com/74089d41da460274cdcad13828d41a4c

my project is bugged somehow

**Comment by Sour-J** [comment]
i really dont want a start point in the game i need to spawn at the respawn points instead like other survival games, im afraid even if we remove the start point spawn completely it will still spawn at 0.0.0

**Comment by Sour-J** [comment]
https://user-images.githubusercontent.com/78616165/126698896-72384ae4-2c84-4087-a130-856f05e18338.mov

**Comment by Sour-J** [comment]
ok real head scratcher here. when i spawn as one of your default characters (female) it works perfectly... even if i use one of my custom classes. so its the player model somehow. but my player model is set to 0.0.0 transform..

**Comment by Sour-J** [comment]
turns out this was caused from a custom script that has nothing to do with spawning, thank you for your time will tip you a coffee

**Comment by Sour-J** [comment]
its just weird because the script had nothing to do with spawning, we didnt change the script just remade the character with the same scripts as this one above and it worked

**Comment by insthync** [comment]
Are you sure that the character spawning at 0, 0, 0 position? It may be other positions but under the ground, so the character falling underground, uses 0, 0, 0 to communicate here lead to confusion. I think I should check on your PC.

**Comment by Sour-J** [comment]
after like 10 hours of process of elimination i found out what was causing it

on the character entity you cant have the root transform or nothing in these slots see images
https://gyazo.com/3a81fb05bcd2635ace73ee13c5d9f2cb
https://gyazo.com/d9f50c394c36a3e53b0a17df024782f4
I had it like that^

so i made some empty objects on the character like this image
https://gyazo.com/c79a0f7c777482169a411f7c22aaf371

and whala it works perfectly after you put emptys probably user error or bug i dont know but i appreciate you

**Comment by insthync** [comment]
Okay, may I see what is in character UI and minimap UI ?

**Comment by Sour-J** [comment]
https://gyazo.com/f21d7935d2b5b5f368f4292fa55691ad
https://gyazo.com/02ca88f12c9f17075db1c8d345210f30
nothing just emptys with character tag

**Comment by Sour-J** [comment]
most of my characters attack from the transform so i thought it could be blank theres no issue going forwsrd ill just make the transforms just opened this to let you know what the issue was

**Comment by insthync** [comment]
> https://gyazo.com/f21d7935d2b5b5f368f4292fa55691ad
> https://gyazo.com/02ca88f12c9f17075db1c8d345210f30
> nothing just emptys with character tag

No, I mean in when playing a game, it will have an instantiate character UI and minimap UI, what is in it?

**Comment by Sour-J** [comment]
https://gyazo.com/460811b10592054efaa7aa67672c1c85 
Looks like when i leave it blank its putting the character entity transform there. 
Im all good now though just was trying to understand why this happened maybe if someone has this question in the future now we know lol thank you suri! <3

**Comment by Sour-J** [comment]
i didnt know the script that was made for me grabbed the transforms so thats why it bugged thank you,
