### ISSUE TITLE
[Small Bug]UiCharacterHotkey

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1085]
on the hotkeys you have the filtering option. like in the picture

https://gyazo.com/d4c820f736f6e595950ee1700eeea715

i splited my hotkeys so that only specific slots can be filled with skills only and some only with items.
but when u let the list for Skill Types empty. you can attach active passives and crafting.

maybe need to add anoption for None?

**Comment by Callepo** [comment]
there is a way to get none, but its not the ideal way, without doing any coding or changing anything.

u can give all the skills and items a Category
and filter based on category.. 
u will only get that specific category.
But all ur items need to have category + all skills..
if they dont have  1 and is empty aka null.. it will get picked up by the filter cuase it picks null + the specified category.

i think its like that becuase there needs to be a way to show all items + skills without filter and how u do that is by showing all thats empty

**Comment by insthync** [comment]
I will add these  settings

![Screenshot_581](https://user-images.githubusercontent.com/2697550/127660048-26a6f848-9ca8-4b9d-a00d-2545bf46f967.png)

**Comment by insthync** [comment]
Those settings were added, if it is not fixing the issues, you can reopen this post.
