### ISSUE TITLE
[Bug]1.67 Debuff dmg over time no longer works on skills

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1086]
debuff apply to enemy but dmg over time no longer works.

**Comment by insthync** [comment]
Not sure that it maybe because of this problem https://github.com/suriyun-production/mmorpg-kit-docs/issues/1080

**Comment by moepi2k** [comment]
no component is attached. i tested in my project and on fresh. both same. dmg over time not work

**Comment by insthync** [comment]
It should have `CharacterSkillAndBuffComponent` attached, you may try re-download the package because there is a GUID problem in 1.67 exporting, so I fixed by re-export and upload.

**Comment by moepi2k** [comment]
it is attached https://gyazo.com/2ae896020d1dcd9db926dd6224e597cf

i also reimported 1.67 again and have same issue. my fireball which has a debuff (dmg over time) will be applied but it does no dmg. 

https://gyazo.com/41dcc51c603089b5569bfa89c0b8dfad

it worked fine before

**Comment by insthync** [comment]
I will check it again :P

**Comment by moepi2k** [comment]
heeellooooo :) i wont stress you xD but was you able to check it again? its weird. i backported project and it worked with older version, i cant see what changed in core

**Comment by insthync** [comment]
It may just not showing combat text, I am going to fix it.

**Comment by moepi2k** [comment]
ou yea your right, didnt noticed that. it does damage but dmg text is missing

**Comment by insthync** [comment]
Fixed in 1.67b
