### ISSUE TITLE
[Suggestion] Buff to disable monsters collision

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#1087]
To create "evade" skills to be used for example when the player is surrounded by monsters.

**Comment by insthync** [comment]
May just change player's character layer while buff applying to a layer which ignored `character` layer collision (by https://docs.unity3d.com/ScriptReference/Physics.IgnoreLayerCollision.html)

**Comment by Fr-Coder** [comment]
I never thought of that, great idea, thank you!
