### ISSUE TITLE
Prefab Animation Issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1089]
When 2 players , ( Same Prefab) use a skill as the same time, the 2nd player who caster will copy the animations of the other character. 

https://user-images.githubusercontent.com/7702658/127734467-3c96e53d-4418-432a-a020-e6a6e7cd47c8.mp4

I Casted Heal on 1 of the character to show the animation , then did bash on left player and then heal again on right player.. they both do bash animation

But doing same thing with 2 different models doesnt produce this..

https://user-images.githubusercontent.com/7702658/127734490-755bc89e-d76f-4ba8-8e3d-f4860c7b7849.mp4

More proof of the bug 
https://imgur.com/a/j44M0M3

**Comment by insthync** [comment]
I will fix it

**Comment by insthync** [comment]
Have to use Playable Graph to play action animations :P

**Comment by insthync** [comment]
It is acutally fixed in 1.67c by using non-cached animator override controller, But for better performance, I've added `Playable Character Model` to 1.68 update.
