### ISSUE TITLE
Sorting Inventory

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#109]
I made a script that lets me sort my inventory .. aka move items around it uses a method already created by u in the kit, RequestSwapOrMergeItem
alot of people like it and want me to make a tutorial on how to do it
Should i make it a addon for them and put it in discord? or do u wanna add it to the kit?
Ill send u the script on discord if u want to see it

https://www.youtube.com/watch?v=xNEYHsyXtO8&feature=youtu.be

**Comment by insthync** [comment]
I just do it by myself and also implement a function to swap or merge items in storage :p

**Comment by Callepo** [comment]
cool.. ty

**Comment by insthync** [comment]
Added in 1.50
