### ISSUE TITLE
UnityWebRequest.isNetworkError is deprecated

### ISSUE THREAD

**Issue by Randolphjand** [suriyun-production/mmorpg-kit-docs#1090]
Assets\UnityMultiplayerARPG\Core\Scripts\UI\CashShop\UICashPackage.cs(81,18): warning CS0618: 'UnityWebRequest.isNetworkError' is obsolete: 'UnityWebRequest.isNetworkError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ConnectionError) instead.'

**Comment by insthync** [comment]
New Unity changes it again? :(

**Comment by insthync** [comment]
Fixed in 1.69
