### ISSUE TITLE
missing scripts upon updating

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1091]
hello, i noticed that all my character and monster prefabs are missing two unknown scripts and i compared them to a 1.66 character and its not missing anything this happened when updating maybe something was merged 
also i got a bunch of these guild war errors so i delete guild wars from my project since im not using it but maybe this will interest you

Assets\UnityMultiplayerARPG\GuildWar\Scripts\GuildWarMonsterCharacterEntity.cs(9,17): error CS0117: 'EntityInfo' does not contain a definition for 'type'
this script GuildWarMonsterCharacterEntity.cs and GuildWarMapInfo.cs causing errors

**Comment by moepi2k** [comment]
Was type not changed to Type in 1.67b?

**Comment by insthync** [comment]
Delete `Assets/UnityMultiplayerARPG/GuildWar` then re-import it, I will update the document later.
