### ISSUE TITLE
Equip Containers not Visible

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1092]
There is no option to setup Character equip containers, its simply not visible.
![image](https://user-images.githubusercontent.com/7702658/128135326-7e0307cf-4c69-4177-ad66-5b7f91d69e2f.png)

Only at runtime do u see it

![image](https://user-images.githubusercontent.com/7702658/128135394-a3904803-5def-4b35-b302-8ecf86bcde99.png)

I thought it was being auto generated by the equip setter u put on the model.. but that doesnt seem to be the case.
is this some kind of new feature im not doing right? or is it simply bugged?

**Comment by insthync** [comment]
It's a bug

**Comment by Callepo** [comment]
@insthync 
![image](https://user-images.githubusercontent.com/7702658/128239479-90a0eed9-0c69-4adf-b8e1-e371881b31e4.png)

Mail system bug, got it after won guild war u get mail
![image](https://user-images.githubusercontent.com/7702658/128239525-1c4ef788-e675-47c4-ad34-18031ad3aa8f.png)

doesnt show mail either

**Comment by insthync** [comment]
Fixed in 1.67c
