### ISSUE TITLE
BaseGameEntity (TextTitle & TextTitleB)

### ISSUE THREAD

**Issue by WillisStephen** [suriyun-production/mmorpg-kit-docs#1094]
Just something I've noticed and I'm not sure if it's legacy code that just gets left in just in case someone is using it, but TextTitle and TextTitleB are never set that I can tell. From what I can tell, the titles are set through the UI script UICharacterEntity. Just not sure if the variables set in BaseGameEntity are necessary as well as the checks that are done in the EntityLateUpdate for it.

**Comment by insthync** [comment]
Just options to set titles like in UICharacterEntity, no difference.

**Comment by insthync** [comment]
It will be removed in next version, I don't think anyone will use it too

**Comment by insthync** [comment]
Removed (in 1.68 update)
