### ISSUE TITLE
Missing Field for Buffs?

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1096]
i cant see the field for effectiveness for buffs. so that you can increase the buff effect (e.g Heal) like you can do for damage.
is it missing?

**Comment by insthync** [comment]
No effectiveness for buffs.

**Comment by moepi2k** [comment]
Oh okey, will you add it? If not i will make my own :)

**Comment by insthync** [comment]
I won't add it.

**Comment by moepi2k** [comment]
ok thx for info :)
