### ISSUE TITLE
Error when use projectiles (spells)  1.67c

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1097]
it throws me an error and the projectile never disappear

`NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.DefaultGameplayRule.OnCharacterReceivedDamage (MultiplayerARPG.BaseCharacterEntity attacker, MultiplayerARPG.BaseCharacterEntity damageReceiver, MultiplayerARPG.CombatAmountType combatAmountType, System.Int32 damage, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Rule/DefaultGameplayRule.cs:594)
MultiplayerARPG.BaseCharacterEntity.ReceivedDamage (UnityEngine.Vector3 fromPosition, MultiplayerARPG.EntityInfo instigator, System.Collections.Generic.Dictionary`2[TKey,TValue] damageAmounts, MultiplayerARPG.CombatAmountType combatAmountType, System.Int32 totalDamage, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity.cs:477)
MultiplayerARPG.DamageableEntity.ApplyDamage (UnityEngine.Vector3 fromPosition, MultiplayerARPG.EntityInfo instigator, System.Collections.Generic.Dictionary`2[TKey,TValue] damageAmounts, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel, System.Int32 randomSeed) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageableEntity.cs:230)
MultiplayerARPG.DamageableHitBox.ReceiveDamage (UnityEngine.Vector3 fromPosition, MultiplayerARPG.EntityInfo instigator, System.Collections.Generic.Dictionary`2[TKey,TValue] damageAmounts, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel, System.Int32 randomSeed) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageableHitBox.cs:155)
MultiplayerARPG.BaseDamageEntity.ApplyDamageTo (MultiplayerARPG.DamageableHitBox target) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageEntities/BaseDamageEntity.cs:83)
MultiplayerARPG.MissileDamageEntity.FindAndApplyDamage (UnityEngine.GameObject other) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageEntities/MissileDamageEntity.cs:245)
MultiplayerARPG.MissileDamageEntity.ExplodeApplyDamage () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageEntities/MissileDamageEntity.cs:286)
MultiplayerARPG.MissileDamageEntity.Explode () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageEntities/MissileDamageEntity.cs:268)
MultiplayerARPG.ProjectileDamageEntity.Impact (UnityEngine.GameObject hitted) (at Assets/Hubi/Scripts/ProjectileDamageEntity.cs:210)
MultiplayerARPG.ProjectileDamageEntity.FixedUpdate () (at Assets/Hubi/Scripts/ProjectileDamageEntity.cs:146)`

https://gyazo.com/ee58429d87b9cc84240de7e8838e609d
DefaultGameplayRule.cs

**Comment by insthync** [comment]
![Screenshot_593](https://user-images.githubusercontent.com/2697550/128716898-524532ae-030e-48ee-9608-e474012bc560.png)

I've changed it like this to make status effects from passive skills that come from equipped items working too.
