### ISSUE TITLE
Trees not showing

### ISSUE THREAD

**Issue by Randolphjand** [suriyun-production/mmorpg-kit-docs#1099]
If I make a new scene and add trees they do not appear in gameplay.  They do show up if I switch to scene mode while in play mode.  I tried different things to fix it but cannot figure it out.  I tried adding a few trees to Map001 and they were not visible in playmode except in the scene view.

**Comment by insthync** [comment]
How you add tree to the scene ? use spawner or just place in the scene, if you just placed it in the scene then did you made it as prefab?

**Comment by Randolphjand** [comment]
I was using a Gaia terrain,  then I tried just placing tree prefabs by hand but both did not work.  I had placed a few trees in the scene Map001 in the kit and it does not appear when  it is running but the trees are visible if I switch to scene mode.

**Comment by insthync** [comment]
You use Gaia to spawn trees ?

**Comment by Randolphjand** [comment]
When you use Gaia to create terrains, Gaia places trees and grass using the same method as Unity when you tell Unity to mass place trees.  I tried both ways of placing trees.   I used Gaia and I tried just adding a tree prefab to your default Map001 scene but it did not show either way.

**Comment by Randolphjand** [comment]
I am using the latest kit and I tried Unity 2020 and tried 2021 in new projects with only the kit installed and with the kit and gaia installed but it did not change anything.

**Comment by insthync** [comment]
So how do I know how you test it?
- I don't know how you put the tree in the scene, just put it in the scene or uses Gaia.
- I don't know when you test you just enter play mode from map scene or start from init scene.

**Comment by Randolphjand** [comment]
I tried placing a tree in the scene by adding a tree prefab into Map001 and then just loaded everything from init scene like you would to play the game but the tree did not show up in the game scene but if you switch to scene view while in play mode you can see that the tree is there but not showing in game view.

**Comment by Randolphjand** [comment]
![Screenshot 2021-08-14 143623](https://user-images.githubusercontent.com/36803394/129458445-7f0b38ee-8a59-46d6-a620-8a4f5d60e606.png)
![Screenshot 2021-08-14 144037](https://user-images.githubusercontent.com/36803394/129458452-35704036-a00b-4748-805f-6d70a21c85b4.png)

**Comment by insthync** [comment]
So the tree is not invisible in the camera?, you may have to try to change tree's layer or your character is too far from the tree

**Comment by Randolphjand** [comment]
I was showing you that the character is standing beside the tree in game view.  You see the tree and where the character is in the scene view.

**Comment by Randolphjand** [comment]
You can see the tree in the minimap in game view.

**Comment by insthync** [comment]
Yeah, so the problem might be because of the tree's layer

**Comment by Randolphjand** [comment]
I had to change all of the tree prefabs to Default layer to make them appear.  Thank you for your help and thank you for the kit.
