### ISSUE TITLE
Terrain/attack questions

### ISSUE THREAD

**Issue by Zaraath** [suriyun-production/mmorpg-kit-docs#11]
Can you please share how to change the terrain and map dimensions.  I love to circle and want to keep it, and the built in navmesh, just would like to change the grid pattern.

Also, where do you store the attack speed variable?    Ideally I want to change attack speed for each weapon (my bow is a machine gun), and in survivor mode melee auto attacks the same speed regardless of weapon.

Also trying to add FOV for a range weapon (shotgun).

Thanks in advance.

**Comment by insthync** [comment]
Not understand about your question, you want it to move in grid?

You can increase attack speed by Increase stats in your weapon item data
![screenshot_652](https://user-images.githubusercontent.com/2697550/53473856-1e5a7800-3a9e-11e9-993d-4694147f674f.png)

For shotgun, rifle, or other guns is under development
