### ISSUE TITLE
Armor doesn't work

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#110]
![image](https://user-images.githubusercontent.com/47291794/67104480-b3e27d80-f1cf-11e9-891c-92e9c4a23208.png)
![image](https://user-images.githubusercontent.com/47291794/67104624-f1dfa180-f1cf-11e9-9297-6924fdf7d216.png)
![image](https://user-images.githubusercontent.com/47291794/67104689-10de3380-f1d0-11e9-9a16-293f252bb26d.png)

10000 fire armor. Monster has 100-100 fire damage. He continues to do 100 fire damage.
Resistances work well.

**Comment by insthync** [comment]
You can fix it by changes codes in `SimpleGameplayRule.cs` line 131
From
```
            damageReceiver.GetCaches().Armors.TryGetValue(damageElement, out resistanceAmount);
```
To
```
            damageReceiver.GetCaches().Armors.TryGetValue(damageElement, out armorAmount);
```

**Comment by DimasjkTV** [comment]
> You can fix it by changes codes in `SimpleGameplayRule.cs` line 131
> From
> 
> ```
>             damageReceiver.GetCaches().Armors.TryGetValue(damageElement, out resistanceAmount);
> ```
> 
> To
> 
> ```
>             damageReceiver.GetCaches().Armors.TryGetValue(damageElement, out armorAmount);
> ```
