### ISSUE TITLE
I increased number of scenes in game and now cant turn on server

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1100]
I increased the number of scenes to 40 in my game, from 10 to 40 and now when I try to turn on server it crashes. And I find out that log carpet is buged when I open the server in my winscp. I cant delete log folder even if server is turn off. In order to delete the folder I need to reboot server.

**Comment by insthync** [comment]
Isn't it just the server can't handle all game server instances ?, you may try uses more computers to run more game server instances.

**Comment by MosesGomez** [comment]
> Isn't it just the server can't handle all game server instances ?, you may try uses more computers to run more game server instances.

So answer will be, buying another server to handle half of the maps?

**Comment by insthync** [comment]
Yes, because I don't know any information, no processes monitoring info, no error logs. That is what I can guess, you may try to run 10 then 20 then 30 then 40, and find when it will be crashed. Or try to use Linux's processes monitoring.

**Comment by insthync** [comment]
Close this because it has no responding
