### ISSUE TITLE
Automatic weapons bug

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1101]
I few other customers i know have the same issue in discord
Sometimes Automatic weapons dont disengage when you let go of the trigger They get stuck going forever until you click a bunch of times to unstick it its hard to reproduce but it does happen often especially when you remove the ammo requirement so its infinite

**Comment by insthync** [comment]
I don't get what is happen.

**Comment by Sour-J** [comment]
it stopped with the new version no idea why
