### ISSUE TITLE
Guilds are not saved

### ISSUE THREAD

**Issue by CaptainMaxwell7** [suriyun-production/mmorpg-kit-docs#1102]
The game doesn't remember that I am in a Guild.

- Make a Guild
- Exit to Main Menu
- Get back into the game
- Guild is forgotten, and you'd have to make it again

Unless this happens because the Guild needs 2 people to register? Then again, players would spend Gold to make a Guild. So it should always save.

Tried this in the demos linked in the asset store, as well as in the kit itself as of latest update (1.67). Bug is present in both.

**Comment by insthync** [comment]
Did you testing offline game ?

**Comment by CaptainMaxwell7** [comment]
> Did you testing offline game ?

Yeah. I wrote this issue yesterday and while I was thinking before sleeping, I thought it had to do with the offline version.
I just tested now on the MMO one and everything is working fine.

Sorry if this caused any inconvenience. I'll check thoroughly in the appropriate game mode in the future!
