### ISSUE TITLE
Auction House 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1104]
When will you work on Auction system ?

**Comment by juniormagalhaes** [comment]
I was thinking this right now and come see if anyone had already asked about XD

> When will you work on Auction system ?

**Comment by RunOrDi3** [comment]
^^i hope this system will be available soon

**Comment by insthync** [comment]
Please describe its feature, how it works, then I will be able to develop it easily.

**Comment by moepi2k** [comment]
This is a good article how auction house in WoW works

https://wowpedia.fandom.com/wiki/Auction_House

**Comment by RunOrDi3** [comment]
@insthync https://assetstore.unity.com/packages/tools/integration/auction-house-remastered-191906 its good example to understand what it is (check it ) .. 
![auction-house-for-ummorpg-135135-004-scaled](https://user-images.githubusercontent.com/64667641/130778128-44480112-95a7-42fa-a44c-bd2f59c2bf5f.jpg)
![a12f58b7-cf2c-4025-b9d1-9518b347fec4](https://user-images.githubusercontent.com/64667641/130778148-f185f9f3-d703-40a6-85f2-250892946a38.png)
![d97f3870-9fe1-4df0-a43a-0afffb056743_scaled](https://user-images.githubusercontent.com/64667641/130778424-679a35e2-e866-4f6e-8e92-1b1be970daeb.jpg)

1- Every tab of the auction house supports pages, will show a max of 20 items per page and is changeable.
Search items by full or partial item name with level range and category/subcategory.

2- Sort items by clicking on the column names to sort ascending (a-z/0-9) or descending (z-a/9-0).

3- You can bid on selected items at the minimum bid allowed, enter in a higher bid if you wish, or you can buyout the item. (Note: You cannot bid or buyout your own auctions)

4- If a bid matches or is higher than the buyout then it will buyout the item at buyout price.

5- View active auctions you have previously bid on to allow you to bid if you have been outbid or increase your previous bid.
Post auctions up for sale to other players. Posting of auctions has a deposit fee based on this calculation: (ItemVendorSalePrice x StackSize x DurationFeePercent).

6- Each duration length is in days and can be changed along with its fee percent. Default values are: (1 Day - 0.1%, 3 Days - 0.2%, 5 Days - 0.3%)

7- If you post an auction and it sales you will be refunded the deposit fee.

8- When an auction has ended, there is a final value fee that is subtracted from the sellers earnings automatically. (Default fee is 0.1% of the auctions final value)

9- You can claim all your gold and items from a claims tab from auctions that have ended or been outbid on.

10- Every 15mins (changeable) a check for auctions that are needing to be ended is ran and processed.

11- Categories are stored in an enum, you can edit/add/remove categories.

12- Multiple Auction Houses based off an Id on the player. This will enable you to have separate auction houses based on class or if your game has factions. All players with the same Id will see the same auctions.
