### ISSUE TITLE
Player fall in the ground with Playable Character Model

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#1105]
Using the new Playable Character Model, the player sometimes falls in the ground for a short time, something like when in the animator we are transitioning to a state without an animation clip.
It mostly happens when you do a fast switch between sprint and move (press and release shift).
Small video:
[https://gfycat.com/ifr/PaleDearCrocodile](https://gfycat.com/ifr/PaleDearCrocodile)

Changing the transition duration value the problem can be stronger

**Comment by insthync** [comment]
May I see your setting?, how you set transition duration, and how playable graph work?

![Screenshot_609](https://user-images.githubusercontent.com/2697550/131248763-fb742ae6-8805-42a8-8b52-3782984e2510.png)

**Comment by Fr-Coder** [comment]
I am using the clean kit as-is from the asset store, then I changed Transition Duration to 0.5 and press shift repeatedly, you should see a sort of "bouncing" as in the video.
With different animations/configurations it's strongly visible also at a lower values like 0.2.

**Comment by insthync** [comment]
Fixed in 1.69
