### ISSUE TITLE
MySql Exception; Access Denied for user 'root@localhost'

### ISSUE THREAD

**Issue by jessidion** [suriyun-production/mmorpg-kit-docs#1107]
Still tryna setup the server, here's some logs from centralchat

 INFO GameInstance (MultiplayerARPG.GameInstance) [2021-08-28 19:55:40] - [IAP_INIT]: Initialized without purchasing
 INFO DatabaseNetworkManager(DatabaseNetworkManager) [2021-08-28 19:55:40] - OnStartServer
 INFO No Tag [2021-08-28 19:55:40] - Reading config file from ./config/mySqlConfig.json
 INFO CentralNetworkManager(CentralNetworkManager) [2021-08-28 19:55:40] - OnStartServer
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - [Chat] Starting server
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - [Chat] Connecting to Central Server: 127.0.0.1:7000
 INFO ChatNetworkManager(ChatNetworkManager) [2021-08-28 19:55:40] - OnStartServer
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - [MapSpawnServer] Starting server
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - [MapSpawnServer] Connecting to Central Server: 127.0.0.1:7000
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager) [2021-08-28 19:55:40] - OnStartServer
 INFO DatabaseNetworkManager(DatabaseNetworkManager) [2021-08-28 19:55:40] - OnStartClient
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibClient [2021-08-28 19:55:40] - OnPeerConnected
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - OnPeerConnected.
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - [Chat] Connected to Central Server
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - OnPeerConnected.
 INFO (No Manager)->LiteNetLibClient [2021-08-28 19:55:40] - [MapSpawnServer] Connected to Central Server
 INFO DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer [2021-08-28 19:55:40] - OnPeerConnected peer.ConnectionId: 0
 INFO CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer [2021-08-28 19:55:40] - OnPeerConnected peer.ConnectionId: 0
 INFO CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer [2021-08-28 19:55:40] - OnPeerConnected peer.ConnectionId: 1
**ERROR No Tag [2021-08-28 19:55:40] - MySqlConnector.MySqlException (0x80004005): Access denied for user 'root'@'localhost' (using password: YES)**
  at MySqlConnector.Core.ServerSession+<ReceiveReplyAsyncAwaited>d__84.MoveNext () [0x000d1] in <8dab677316c94c399e9033dcbf307466>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at MySqlConnector.Core.ServerSession+<ConnectAsync>d__76.MoveNext () [0x009d5] in <8dab677316c94c399e9033dcbf307466>:0 
--- End of stack trace from previous location where exception was thrown ---

**Comment by jessidion** [comment]
Please help it doesn't work at all

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/131234762-c22adf70-5e3b-4877-a02f-1d3233d9113f.png)

ur credentials are bad, its not a kit issue its you doing something wrong, 
![image](https://user-images.githubusercontent.com/7702658/131234776-24fa9f60-3c36-404e-a785-44097d6324b5.png)

u are using mysql config files, check if ur pw is good or if the username is good

If ur not trying to use mysql at all, then change ur config files the server one to use database index 0 and not 1 it will use sqlite
