### ISSUE TITLE
Damage over time persisting through respawn

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1108]
I noticed while doing a closed alpha test of my game that when I get a damage over time effect on me, if you die with the buff on you, it persists after death and respawn.
 
lets say poison for example, if you get poisoned for 30 seconds and die right away if you respawn quickly youll have the poison still on the respawned character for the remainder of the time. is this a bug or just me?

**Comment by insthync** [comment]
Is the poison doesn't has `doNotRemoveOnDead` turned on?

**Comment by insthync** [comment]
You may helps me check it, in `BaseCharacterEntity` -> `Killed` function

**Comment by Sour-J** [comment]
I will check and get back to you thanks

**Comment by Sour-J** [comment]
that was the issue thank you i didnt know that was an option i appreciate your time
