### ISSUE TITLE
Invalid Data - Creating New Player Character

### ISSUE THREAD

**Issue by jessidion** [suriyun-production/mmorpg-kit-docs#1109]
So i've spent hours watching and reading the tutorials I could find and I'm probably just bad at this but I find it extremely hard.

Basically I've done pretty much everything step by step but when I create a new character and try to select the new character it says "Invalid Data" and won't let me create it.

I have all my imported characters and gears ready but I'm having such a hard time.

**Comment by insthync** [comment]
Are you testing a MMO game right?, Did you rebuild the game-server after made changes?

**Comment by jessidion** [comment]
> Are you testing a MMO game right?, Did you rebuild the game-server after made changes?

o nooo. I have to build everytime I want to test changes? DDDD:

**Comment by insthync** [comment]
Your game have an factions setting?

**Comment by insthync** [comment]
Your character entity have a `PlayerCharacter` data set in this list ?
![Screenshot_608](https://user-images.githubusercontent.com/2697550/131244393-e9386a07-2710-46eb-9492-7ba9a6a01581.png)

**Comment by insthync** [comment]
May you capture screen of the character creating scene?

**Comment by jessidion** [comment]
![image](https://user-images.githubusercontent.com/75174055/131244610-13a812fa-3917-4e3c-8e69-ff0e4715925e.png)

I've rebuilt the game server and now it works. Now I have to figure out how to setup the armors.

**Comment by insthync** [comment]
Yes, you have to rebuild evertime you change something, but in the next version which have asset bundle integration you will have to rebuild only asset bundle if you change something (but have to rebuild the game if codes changed)
