### ISSUE TITLE
BUG? Character stats update

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#111]
For example, we have an item that gives +10 to healing skill. We put it on, but in the tooltip does not write that we got +10 to the skill. We have to do a logout and after that the data is updated. I think this is very bad for the player. After putting on the item, we need to do logout in order to see the characteristics.
1. 
![image](https://user-images.githubusercontent.com/47291794/67111184-17bf7300-f1dd-11e9-8609-476c2b5c1811.png)
2. 
![image](https://user-images.githubusercontent.com/47291794/67111207-227a0800-f1dd-11e9-84c0-cc049964ef4e.png)
3.
![image](https://user-images.githubusercontent.com/47291794/67111228-2c9c0680-f1dd-11e9-9383-3602a154348f.png)
4. After logout
![image](https://user-images.githubusercontent.com/47291794/67111300-4f2e1f80-f1dd-11e9-948d-7b3c231a14c9.png)

**Comment by insthync** [comment]
Cause of issues is UIs not update after equipment changed :p, 
You can fix it by add codes to `BasePlayerCharacterController.cs` 
Line 249 (in OnEquipWeaponSetChange())
```
                CacheUISceneGameplay.UpdateSkills();
```
Line 260 (in OnSelectableWeaponSetsOperation())
```
                CacheUISceneGameplay.UpdateSkills();
```
Line 305 (in OnEquipItemsOperation())
```
                CacheUISceneGameplay.UpdateSkills();
```

**Comment by DimasjkTV** [comment]
> Cause of issues is UIs not update after equipment changed :p,
> You can fix it by add codes to `BasePlayerCharacterController.cs`
> Line 249 (in OnEquipWeaponSetChange())
> 
> ```
>                 CacheUISceneGameplay.UpdateSkills();
> ```
> 
> Line 260 (in OnSelectableWeaponSetsOperation())
> 
> ```
>                 CacheUISceneGameplay.UpdateSkills();
> ```
> 
> Line 305 (in OnEquipItemsOperation())
> 
> ```
>                 CacheUISceneGameplay.UpdateSkills();
> ```

I put on an item with a + skill. I have not learned the skill. Put the skill on the panel. Can you make sure that when removing an item, the skills from the panel disappear? But only if there are no more bonuses to this skill. It looks like the same problem as above 
![image](https://user-images.githubusercontent.com/47291794/67159846-c802b800-f352-11e9-9cbf-45fd6302e9e2.png)

**Comment by insthync** [comment]
Yes, do the same thing 
calls `CacheUISceneGameplay.UpdateHotkeys()` when there are equip items changes

**Comment by DimasjkTV** [comment]
> Yes, do the same thing
> calls `CacheUISceneGameplay.UpdateHotkeys()` when there are equip items changes

![image](https://user-images.githubusercontent.com/47291794/67163249-58ea8b00-f375-11e9-9d23-00c746290bcd.png)
![image](https://user-images.githubusercontent.com/47291794/67163255-630c8980-f375-11e9-9a32-211e0af9a2d2.png)
![image](https://user-images.githubusercontent.com/47291794/67163256-6bfd5b00-f375-11e9-80d5-5cf25242bebb.png)

Right? skills in slots are still not updated

**Comment by Callepo** [comment]
u didnt do the update hotkey one
that he said 

calls CacheUISceneGameplay.UpdateHotkeys() when there are equip items changes

**Comment by DimasjkTV** [comment]
> u didnt do the update hotkey one
> that he said
> 
> calls CacheUISceneGameplay.UpdateHotkeys() when there are equip items changes

Yes, I can read. But I do not know how to fix this bug

**Comment by insthync** [comment]
> > Yes, do the same thing
> > calls `CacheUISceneGameplay.UpdateHotkeys()` when there are equip items changes
> 
> ![image](https://user-images.githubusercontent.com/47291794/67163249-58ea8b00-f375-11e9-9d23-00c746290bcd.png)
> ![image](https://user-images.githubusercontent.com/47291794/67163255-630c8980-f375-11e9-9a32-211e0af9a2d2.png)
> ![image](https://user-images.githubusercontent.com/47291794/67163256-6bfd5b00-f375-11e9-80d5-5cf25242bebb.png)
> 
> Right? skills in slots are still not updated

Yes, It looks correct. Still, have an issue?

**Comment by DimasjkTV** [comment]
> > > Yes, do the same thing
> > > calls `CacheUISceneGameplay.UpdateHotkeys()` when there are equip items changes
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/47291794/67163249-58ea8b00-f375-11e9-9d23-00c746290bcd.png)
> > ![image](https://user-images.githubusercontent.com/47291794/67163255-630c8980-f375-11e9-9a32-211e0af9a2d2.png)
> > ![image](https://user-images.githubusercontent.com/47291794/67163256-6bfd5b00-f375-11e9-80d5-5cf25242bebb.png)
> > Right? skills in slots are still not updated
> 
> Yes, It looks correct. Still, have an issue?

Yes, the only problem is updating the slots.

**Comment by insthync** [comment]
As I try, I haven't found the issues anymore, not sure how is your issues exactly, can you upload the video to show me how it is?

**Comment by DimasjkTV** [comment]
> As I try, I haven't found the issues anymore, not sure how is your issues exactly, can you upload the video to show me how it is?

i can in discrod

**Comment by DimasjkTV** [comment]
[20191020220214.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3748224/20191020220214.zip)

**Comment by DimasjkTV** [comment]
> Cause of issues is UIs not update after equipment changed :p,
> You can fix it by add codes to `BasePlayerCharacterController.cs`
> Line 249 (in OnEquipWeaponSetChange())
> 
> ```
>                 CacheUISceneGameplay.UpdateSkills();
> ```
> 
> Line 260 (in OnSelectableWeaponSetsOperation())
> 
> ```
>                 CacheUISceneGameplay.UpdateSkills();
> ```
> 
> Line 305 (in OnEquipItemsOperation())
> 
> ```
>                 CacheUISceneGameplay.UpdateSkills();
> ```


Hi! =) It works well, but. If item gives a skill, then the skills are updated in the list. If the set bonus gives a skill, then the skills are not updated

**Comment by insthync** [comment]
Fixed
