### ISSUE TITLE
Addon: Uma dont work with last Uma and last mmo kit

### ISSUE THREAD

**Issue by xEdwinF** [suriyun-production/mmorpg-kit-docs#1110]
Uma dont work with last Uma and last mmo kit Addon

i downloaded and added the last  UMA and MMO kit addon from this:

Import UMA package from https://github.com/umasteeringgroup/UMA/releases
- UMA 2.12

Import addon package from https://github.com/insthync/UnityMultiplayerARPG_UMA/releases
- Update for 1.66c

The last MMO kit Version 1.68. 

Can you fix/update this ? :)

![image](https://user-images.githubusercontent.com/89734606/131251451-d238b31f-09b3-4fb4-baf5-248aa9de0461.png)

**Comment by insthync** [comment]
Updated https://github.com/insthync/UnityMultiplayerARPG_UMA/releases/tag/1.16j
