### ISSUE TITLE
Hard time with Animations

### ISSUE THREAD

**Issue by jessidion** [suriyun-production/mmorpg-kit-docs#1111]
So I followed this step-by-step: https://dev.to/insthync/create-game-with-mmorpg-kit-part-2-map-and-first-character-54dl

Everything is set exactly the same I believe but in-game, character has no animations.. :(

I've been looking for what I did wrong for hours.

**Comment by insthync** [comment]
No more info? How I can help you? You should try attach some screenshots

**Comment by jessidion** [comment]
> No more info? How I can help you? You should try attach some screenshots

Is it normal that after putting in my animations they dont work?

I‘ll grab screenshots in a few seconds

**Comment by jessidion** [comment]
![123AA1E0-3110-4D8E-8272-26558B07629B](https://user-images.githubusercontent.com/75174055/131273585-c0fa0059-1ba4-4ffa-b5a0-63146fdbe51b.jpeg)

![50CABC73-E990-4AA6-B1EC-F63B24622BDC](https://user-images.githubusercontent.com/75174055/131273592-94a7a4c8-af2e-4cb9-814e-9bd6b1eb9728.jpeg)

![Uploading FB976713-97F3-465F-8FE4-62115D24C240.jpeg…]()

**Comment by jessidion** [comment]
O
/ | \
  |
  
All he does is like that

**Comment by insthync** [comment]
How about animator ?

**Comment by jessidion** [comment]
> How about animator ?

![0C405730-4423-4819-B03B-B644D23AFE3A](https://user-images.githubusercontent.com/75174055/131386317-eae6aeeb-bcda-4a5f-a3e6-766963623162.jpeg)
![C3950980-CD3E-4006-ACED-DBABED9FABE2](https://user-images.githubusercontent.com/75174055/131386320-5a5b5acb-0960-427e-85c5-6a98c64d1f19.jpeg)

it shows the animation is going but in-game character doesnt move at all

**Comment by insthync** [comment]
So you create your own animator controller? 

And how about this settings? 

![Screenshot_610](https://user-images.githubusercontent.com/2697550/131387042-ce9f7b94-fbdc-4481-8693-68364f5a78f9.png)

Did you set your animator component here?

**Comment by jessidion** [comment]
Yeah. Also it always says 0 clips

![625B2F93-26A9-4B1F-BF60-A2C52938111B](https://user-images.githubusercontent.com/75174055/131389274-f5bd0ae6-8287-4a0a-a1de-fc8d653b0300.jpeg)
![D9E471A2-E175-4697-8238-E2D2345A37DE](https://user-images.githubusercontent.com/75174055/131389282-92aae092-9bdc-407d-8e22-3315d2bb70fa.jpeg)

**Comment by insthync** [comment]
Did you test the game by run from Init scene?

**Comment by jessidion** [comment]
> Did you test the game by run from Init scene?

Hi, yes :((((

**Comment by jessidion** [comment]
> So you create your own animator controller?

I didn’t I was trying different things but I put back the advanced controller

**Comment by jessidion** [comment]
I got it to work by using AdvanceController and another Avatar as I probably had the wrong Avatar O: tysm!
