### ISSUE TITLE
Swimming Error

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1113]
the same problem is happening again in the latest version of the kit

https://github.com/suriyun-production/mmorpg-kit-docs/issues/1016

**Comment by insthync** [comment]
Do you know what is the source of the problem?, I didn't change anything relates to the Entity movement, how did this can be occured? it is an animation error or a movement error?

**Comment by juniormagalhaes** [comment]
> Sabe qual é a origem do problema ?, não mudei nada relacionado ao movimento de Entidade, como isso pode ter ocorrido? é um erro de animação ou um erro de movimento?

I think it's in the animation, I'll look deeper to see if I can find the source of the problem

**Comment by juniormagalhaes** [comment]
> Do you know what is the source of the problem?, I didn't change anything relates to the Entity movement, how did this can be occured? it is an animation error or a movement error?

I think it's in the animation, I'll look deeper to see if I can find the source of the problem

**Comment by insthync** [comment]
You uses Animator Character Model or Playable Character Model?

**Comment by insthync** [comment]
Uses `RigidbodyEntityMovement` or `CharacterControllerEntityMovement`?

**Comment by juniormagalhaes** [comment]
> Uses `RigidbodyEntityMovement` or `CharacterControllerEntityMovement`?

![image](https://user-images.githubusercontent.com/56885137/131384173-1bc52541-3182-4d97-ba91-82ba3017b98f.png)

**Comment by insthync** [comment]
Okay, do you remember which version that it upgraded from?

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/131384652-60cab600-5eec-4815-baa8-bb1b704cff24.png)



> Okay, do you remember which version that it upgraded from?

**Comment by juniormagalhaes** [comment]
I think there's too much script linked to the character

**Comment by juniormagalhaes** [comment]
> Okay, do you remember which version that it upgraded from?

1.66b (2021-06-10)

**Comment by insthync** [comment]
> I think there's too much script linked to the character

When it has 1 god class, many users requested to split it, I agree with them because it will be easier to change functionality by just switching class, not inherit then override functions to change it.

**Comment by insthync** [comment]
You may search about Composition Over Inheritance to learn about it.

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/131387899-9a348f7a-beb3-4218-a958-fe41edb4d0a2.png)


it's not switching from animation on land to animation on water, it stays idle, activating while walking on water

**Comment by insthync** [comment]
Your water tag is `Water` and your `Open Character Controller` -> `Collision Layer Mask` has no `Water` turned on?

![Screenshot_611](https://user-images.githubusercontent.com/2697550/131388368-e90aa526-1b30-4274-98d0-9e4cd32b8aca.png)

**Comment by juniormagalhaes** [comment]
> Your water tag is `Water` and your `Open Character Controller` -> `Collision Layer Mask` has no `Water` turned on?
> 
> ![Screenshot_611](https://user-images.githubusercontent.com/2697550/131388368-e90aa526-1b30-4274-98d0-9e4cd32b8aca.png)

was turned off I turned it on, now the character walks as if he were on solid ground

**Comment by juniormagalhaes** [comment]
I had forgotten to use a trigger, I put the trigger in the water, but msm like that it doesn't exrcuta the swimming animation

**Comment by insthync** [comment]
You have to set water's collider to be trigger and set its layer to `Water`

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/131390463-8e10ed9c-2fce-40ec-aa81-7b43928bf0d6.png)


it's already like this

**Comment by insthync** [comment]
How about `Under Water Ratio` settings? 
![Screenshot_612](https://user-images.githubusercontent.com/2697550/131390773-0f514ccc-9231-4155-bd18-e617fa25c465.png)

You also should shoot the video to show me how animator controller is working, so I will be able to find out what is happening easier.

**Comment by juniormagalhaes** [comment]
> How about `Under Water Ratio` settings?
> ![Screenshot_612](https://user-images.githubusercontent.com/2697550/131390773-0f514ccc-9231-4155-bd18-e617fa25c465.png)
> 
> You also should shoot the video to show me how animator controller is working, so I will be able to find out what is happening easier.

![image](https://user-images.githubusercontent.com/56885137/131391209-09efaf89-054f-4a97-854c-ca4b462903ec.png)

**Comment by juniormagalhaes** [comment]
for you is working normally?

**Comment by insthync** [comment]
As I test on my PC swimming is still work like version 1.66b, 

About your project, I think it might have something preventing the character to fall into the water but I don't know what is it.

I am going to sleep now.

**Comment by juniormagalhaes** [comment]
> As I test on my PC swimming is still work like version 1.66b,
> 
> About your project, I think it might have something preventing the character to fall into the water but I don't know what is it.
> 
> I am going to sleep now.

I copied the demo scripts

**Comment by juniormagalhaes** [comment]
I noticed that this same problem happens, when I should switch to the swimming animation

https://github.com/suriyun-production/mmorpg-kit-docs/issues/1105

**Comment by insthync** [comment]
No, I think so, because I don't see your character fall under the water. It might not under water yet so it won't play swimming animation

**Comment by insthync** [comment]
You may check under water state

![Screenshot_613](https://user-images.githubusercontent.com/2697550/131491486-69b81e13-ed36-4215-8d18-5e76b7dcbfbd.png)

**Comment by juniormagalhaes** [comment]
> You may check under water state
> 
> ![Screenshot_613](https://user-images.githubusercontent.com/2697550/131491486-69b81e13-ed36-4215-8d18-5e76b7dcbfbd.png)

I can't get to the screen


![image](https://user-images.githubusercontent.com/56885137/131496055-d8b1434f-f2c1-4dc1-902f-24206bbde23b.png)


it enters the water but the swimming animation doesn't happen yet

**Comment by insthync** [comment]
![Screenshot_614](https://user-images.githubusercontent.com/2697550/131500480-26ffbf2a-7293-4e35-bf70-bd1f65d6813a.png)

Click on this

**Comment by juniormagalhaes** [comment]
> ![Screenshot_614](https://user-images.githubusercontent.com/2697550/131500480-26ffbf2a-7293-4e35-bf70-bd1f65d6813a.png)
> 
> Click on this

![image](https://user-images.githubusercontent.com/56885137/131500900-6472e392-e64c-4055-ab33-8ac600d16530.png)

**Comment by juniormagalhaes** [comment]
which of the character models are you using?

![image](https://user-images.githubusercontent.com/56885137/131501091-4e5bb55b-5665-4f21-94ac-98a795cd3039.png)

**Comment by insthync** [comment]
I've test Male and Male_CC

**Comment by juniormagalhaes** [comment]
> I've test Male and Male_CC

I tested them both, and the same thing happens

**Comment by insthync** [comment]
This is pretty much wasting my time, send me your TeamViewer info to check it on your PC.

**Comment by insthync** [comment]
Send it to my email ittipon.bay@gmail.com

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/131502068-c03d04fb-c497-4d93-87d2-1760b0b50aa0.png)


tries to activate auto Swin Surface, on yours to see

**Comment by insthync** [comment]
I tried it.

**Comment by juniormagalhaes** [comment]
I send the email

**Comment by juniormagalhaes** [comment]
Thanks, is working now XD
