### ISSUE TITLE
[Bug]Debuff 

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1114]
When use debuff with this settings:
https://gyazo.com/739488306b2b30dc6c794d3d71403247

sometime monster still walks to the next position even when debuff with "Disallow Move" is applied

https://gyazo.com/ad6afa65905078fe9ce1d3af9c960a50

here a video where u can see it

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.69
