### ISSUE TITLE
No really a bug, but could be confused

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1116]
when use buff/debuff with max stack like

https://gyazo.com/febf2dab06e7abe8b02a05d1eb8618eb

the max stack is always the value u set + 1

so when u set 2 you can stack 3, when u set 3 u can stack 4.

:)

**Comment by insthync** [comment]
I will change it.

**Comment by insthync** [comment]
Fixed in 1.69
