### ISSUE TITLE
Who is this SourJ person and why is he vet status?

### ISSUE THREAD

**Issue by kittrellbj** [suriyun-production/mmorpg-kit-docs#1117]
What qualifies this person to be a moderator in the Discord with no proof of qualifications (work, supporting users, etc.) and who is he even?

I cannot recommend the kit to new users if you continue to add people to positions of power who have been in the community 5 seconds and really have no experience at all. Vet is more about product support, not chat police, and this person has not proven his ability to offer support.

Edit: Suri has decided to revoke vet status from this person, and I can wholeheartedly recommend the kit solely on its merits. Sometimes there are hiccups in communities, but don't let that detract from your decision to purchase/use the kit. This kit is the best multiplayer asset on the Unity Asset Store.

**Comment by Sour-J** [comment]
Too bad your biased and fallen and callepo got you to write this to suri.  I'm here to delete virus links and keep the trash talk out of discord we have had many customers turned away and I have proof of that.. because of the drama I'm helping suriyun mod and I've been in the community for over a year now. I don't need to publicly show my qualifications even though I'm overqualified. I literally watched fallen put you up to this don't you  actually be doxxed somebody in discord before and that's highly illegal so there needs to be a police in the chat that's not apart of the click like you. I provide a ton of support. Where is Fallens and callepo and most hated qualifications??? I think you and your friends are now targeting me because you can't disrespect new customers in chat now. Nice try 🤣

**Comment by Sour-J** [comment]
![unknown (1)](https://user-images.githubusercontent.com/78616165/131711399-2c039b95-4b87-457c-9bfe-8fcfa664ad0a.png)
Here's my qualifications

**Comment by Fallen01** [comment]
Its been said many times we have great community support, and the reason for that is vets are not people who asked. They are people who demonstrated a high level of ability with the kit and help the community, then they are asked to become vets.  You are correct to say Vets are not chat police they are community support people who moderate only when they must and answer to the admin right after they do. So i would understand your confusion as to why someone whos done neither of these things is a vet.

**Comment by Fallen01** [comment]
I didnt dox anyone and if you asked the so called doxed person about it he will tell you we are square. He posted that stuff himself, its not doxing unless i expose him. Hes also very happy with his addons, so its a cool story bro, but lets here it from him the guy you claim to be defending.

**Comment by Sour-J** [comment]
It's not about ability with the kit which by the way I'm well versed it's about people scamming and doing illegal things in the server along with bashing new customers talking shit and just flat out disrespect. Knowledge of programming or kit has nothing to do with moderation.

**Comment by Fallen01** [comment]
you cant provide high level support like any other vet, youve done very little for the community. Whatever you say about me doesnt change that. The same guy your using as an example is a good customer and a good friend. I hope he takes the time to comment here, because im sure he wouldnt like you slandering me because we got into it after we made up and got everything straight.

**Comment by kittrellbj** [comment]
> Too bad your biased and fallen and callepo got you to write this to suri. 

Nobody put me up to this. These are my own feelings.

>I've been in the community for over a year now.

The first time you talked was January 28th, 2021. That is not "over a year"
![Capture](https://user-images.githubusercontent.com/5172361/131712311-f274b960-718e-4c58-893d-9bf192826d11.JPG)

>I literally watched fallen put you up to this don't you actually be doxxed somebody in discord before and that's highly illegal so there needs to be a police in the chat that's not apart of the click like you. I provide a ton of support.

Are you talking about when I linked to the public information that another user posted in public to the whole community, and you're calling that a dox? Or are you talking about when that user went out on the internet and posted location about me that I didn't authorize, and nothing was done to him? Because if you don't know these differences, you really don't need to be a chat policeman.

>I don't need to publicly show my qualifications even though I'm overqualified.

Well, allow me to show your underqualifications. You don't even know what an iterator is, merely days before you're now in charge of the developer Discord?

![Capture2](https://user-images.githubusercontent.com/5172361/131712940-da4e341e-4b07-4972-8d6d-ebf109bcfdc1.JPG)

>I think you and the others should respect the developers decisions it's his discord and a place of business

As a paying customer of the kit and a member of the community, I'll voice my thoughts and concerns regardless of your opinion. This is the only medium by which to contact Suriyun, so I am contacting him via his preferred method. You can kindly see your way out if it offends you.

**Comment by Fallen01** [comment]
You roll into vet pick a fight with other vets right away and then remove our posts when we respond to it. Your chasing off the best the community support has to offer and for what? You wanna tell me your doing this for the community? Thats a hard sell.

**Comment by Sour-J** [comment]
Again I do help with support where I can. Again moderation has nothing to do with the kit. There's more than this guy you can just scroll and see fallen arguing with somebody almost every other day 😅 shall I provide the screenshots ? You have no right to say what I can and can't do is this your discord fallen? Maybe spend less time in development and start learning respect. Start with respecting the developers decision.

**Comment by Callepo** [comment]
yall know this is public right?
nice

**Comment by insthync** [comment]
Yeah, as I rethink again, I agree that Sour-J actually has no proof of qualifications (work, supporting users, etc.), while there are some users that emailed me to ask something or request new features were mentioned that community veterans are helping them.

And I actually never help them to improve the Discord, never help them to build the community, I actually should not have permission to set anyone's role. So I decide to remove Sour-J from the veteran role.

I will let MostHated manage users.

Apologies for my decision.

**Comment by Fallen01** [comment]
I respect his decision i just dont think if he really knew you were just out to make trouble and chase his best community support off by acting like a complete jerk that he would make that choice.

**Comment by kittrellbj** [comment]
> Yeah, as I rethink again, I agree that Sour-J actually has no proof of qualifications (work, supporting users, etc.), while there are some users that emailed me to ask something or request new features were mentioned that community veterans are helping them.
> 
> And I actually never help them to improve the Discord, never help them to build the community, I actually should not have permission to set anyone's role. So I decide to remove Sour-J from the veteran role.
> 
> I will let MostHated manage users.
> 
> Apologies for my decision.

Everyone makes mistakes, Suri. I thank you very much for your decision and consideration in this matter. Thank you for making the best kit on the Unity Asset Store and making it better every single day. Your dedication to your customers is unmatched and very much appreciated.

**Comment by Fallen01** [comment]
Suri just know that Ive learned so much from your work and I owe the coder i am now to both you and the other vets. I will always deeply appreciate that, thank you.

**Comment by Sour-J** [comment]
to my understanding you dont need qualifications to respect others in discord, i was trying to help mod the server. looks like the fallen and his click wins. keep losing money i guess. 

so let me get this straight fallen rallyd all his little friends to stop me from exposing his scams and bad behavior and its believable lol here

**Comment by Fallen01** [comment]
I didnt rally anything, this just happened.

**Comment by Sour-J** [comment]
![8ee2e2491f9612a6ec02cea7b3ed2c7b](https://user-images.githubusercontent.com/78616165/131714535-427d4a57-2816-4c65-aeef-fffcc47914e9.png)
![5ca72fa41d54559298df56ca8e9ecdbe](https://user-images.githubusercontent.com/78616165/131714540-e879f283-5376-4c63-9336-38c03137e607.png)
![aafe63dea131c05fedf8a3ad5f2b5038](https://user-images.githubusercontent.com/78616165/131714548-e9a82428-79f9-45eb-989b-dfcf74257f69.png)

**Comment by Sour-J** [comment]
![b70015a9a57c71cf3501daef62fc160d](https://user-images.githubusercontent.com/78616165/131714614-6023ee9e-695a-4e67-9e10-d8ff294b5582.png)
![Inked5ca72fa41d54559298df56ca8e9ecdbe_LI](https://user-images.githubusercontent.com/78616165/131714626-b011c53c-7e9f-41a9-ae41-a315d3e4843a.jpg)

**Comment by Sour-J** [comment]
![190b4c785ed300f03e3ae36f783b2f72](https://user-images.githubusercontent.com/78616165/131714668-8ab209a2-0ff4-4f36-a851-a5e6708cf691.png)

**Comment by Fallen01** [comment]
![image](https://user-images.githubusercontent.com/57778639/131714738-6124945a-edbe-4077-9f61-9fc09e0e5a0d.png)

**Comment by Fallen01** [comment]
theres grandmaster the guy you said i robbed cool story bro im done here....

**Comment by Sour-J** [comment]
https://gyazo.com/8015dfa93803846b9c6fb0fa7b46a6b5

**Comment by Callepo** [comment]
so u saying fallen doxxed someone and than go and share the same person u said fallen doxxed personal data on github,, on a public repo.. which literally everyone can see, not even just the discord server
classic

**Comment by Sour-J** [comment]
![98c4ef8fd7e2fb87679819a3294d53ea](https://user-images.githubusercontent.com/78616165/131715204-b3909e0e-b206-4ce2-baae-7ca4832ff6a0.png)
![8015dfa93803846b9c6fb0fa7b46a6b5](https://user-images.githubusercontent.com/78616165/131715222-02190cbc-c010-4fef-abb0-b0f3777547cc.png)

**Comment by Sour-J** [comment]
how is this shit okay to be in a business this guy has a hard on for me

**Comment by Sour-J** [comment]
![aafe63dea131c05fedf8a3ad5f2b5038](https://user-images.githubusercontent.com/78616165/131715427-2af96677-9a15-4f36-bde2-6a4dfb76df8e.png)

**Comment by Sour-J** [comment]
![Inked5ca72fa41d54559298df56ca8e9ecdbe_LI](https://user-images.githubusercontent.com/78616165/131715460-0813961e-f3b3-4654-bfb6-d5161b21c8c2.jpg)

**Comment by moepi2k** [comment]
wtf is going on here xD pls close this. its public

**Comment by insthync** [comment]
I've made the decision, @Sour-J you should stop. As I said that I never help them to build the community, I should not have permission to set anyone's role.

You don't have to worry about me so much.

**Comment by Sour-J** [comment]
Doxing (sometimes written as Doxxing) is the act of revealing identifying information about someone online, such as their real name, home address, workplace, phone, financial, and other personal information. ... "Docs" became "dox" and eventually became a verb by itself (i.e., without the prefix "drop").

brian he released his real name

**Comment by Callepo** [comment]
i closed it..but u can still comment on closed shit.. i even mentioned this is public like 2 times oh well

**Comment by insthync** [comment]
I will delete it.

**Comment by Sour-J** [comment]
ill take it to unity then

**Comment by Sour-J** [comment]
funny how you all question my qualifications but let this fallen guy be a criminal and disrespectful sure he knows the kit but that doesnt make it right

**Comment by Callepo** [comment]
what i dont understand is if something is so bad, so terrible, why stay ?

**Comment by Sour-J** [comment]
what i dont understand is how can somebody be qualified to be a mod that constantly argues with people trash talks and disrespects people, scams, doxx's, yet my qualification is questioned lmao.

**Comment by gordowebdesign** [comment]
this should be hidden from public.

**Comment by Callepo** [comment]
this whole thing should be deleted
