### ISSUE TITLE
not a bug , just very small improve to map info

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1118]
Could you add a rotation here with start position to be able to rotate the players to the best side :) .. its important
![1](https://user-images.githubusercontent.com/64667641/131865527-5712e5ed-e2f6-4cd8-8d7f-dfc710b096cb.jpg)

**Comment by insthync** [comment]
In 1.69
```
- Add `Start Rotation` setting to map info game data.
- Add `Use Override Start Rotation` and `Override Start Rotation` to player character game data, use them to override map info's `Start Rotation`.
```
