### ISSUE TITLE
Dualwield animation

### ISSUE THREAD

**Issue by Syrus198327** [suriyun-production/mmorpg-kit-docs#112]
does dualwieling animation currenty work my guy only attacks with his right hand and not with his left i have have animation for left and right arms attacks just he only attacks with right hand i setup left hand attack animation

**Comment by insthync** [comment]
I want to see how you setup your character model, please capture screenshot of your character model → weapon animations settings

**Comment by Syrus198327** [comment]
it was my skinned mesh that was causing the animation problem I have it set up right so dual wielding animation work fine
