### ISSUE TITLE
Building Entity ExtraData is not saved or loaded (with a fix)

### ISSUE THREAD

**Issue by Fashtas** [suriyun-production/mmorpg-kit-docs#1122]
Building Entity data has a property called ExtraData for user defined data for extensions. 
The fireplace entity uses this data for Turn On states and timer but at no point in time is the property ever called so save never happens.

ExtraData appears to be passed and serialized and everything in almost all places in the save/load code but is missed in two places, the first step in save/load (Not being passed to the save structures). I made the following changes and ExtraData now saves and fireplaces that are lit are still lit when you exit and come back into the game.

\UnityMultiplayerARPG\Core\Scripts\Networking\BaseGameNetworkManager.cs
Line 821
	buildingEntity.ExtraData = saveData.ExtraData;
 
\UnityMultiplayerARPG\Core\Scripts\LanGame\SaveSystem\DefaultGameSaveSystem.cs
Line 153
	ExtraData = buildingEntity.ExtraData,

**Comment by insthync** [comment]
Thank you :)

**Comment by insthync** [comment]
Fixed in 1.69
