### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1124]
When you try to create a character this happens:
![image](https://user-images.githubusercontent.com/56482598/132367779-d4d5db87-bd67-40c6-b274-73563433dab8.png)
Everything worked in version 1.67. Then I didn't change anything, just updated the files to 1.68 and this problem occurred. And, with the old base, where the character was already created when trying to list the client thought for a long time and gave the error that there is no response. In version 1.69 all the same.

SQLite database.

P.S. I don't know English, it was translated with online translator.

Translated with www.DeepL.com/Translator (free version)

**Comment by insthync** [comment]
Hmm, as I test, I still can create characters

**Comment by Serivatech** [comment]
How do I find out what the problem is?

**Comment by Serivatech** [comment]
Ouch. The topic can be closed. I negligently uploaded the wrong server :)
