### ISSUE TITLE
[Bug]Inventory Limit Slots

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1125]
when i use limit Slots without weight. and the inventory is full. then create an item as admin like

/add_item Dagger 1

the item goes in "invisible" slot, then when the player remove an existing item, the dagger appears.

here a video: https://gyazo.com/95f3991984ea75aa3a23fcdfb0b60777

i use the same codestructure for other addons. and i have the same issue. so with that bug player can carry more then the inventory limit

**Comment by insthync** [comment]
Fixed in 1.69b

**Comment by moepi2k** [comment]
hm have same issue. i can add items when inventory is full and it just creates a new slot with the item
