### ISSUE TITLE
[BUG] idle crouch not working with shooter character controller

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1126]
when i press ctrl to crouch idle animation doesnt active .. when i move crouch walk active fine... tested in fresh project and my project .. have the same issue .. v 1.69

**Comment by insthync** [comment]
Thank you, I will fix it and upload it in a few hours

**Comment by RunOrDi3** [comment]
@insthync np and thank you.

**Comment by insthync** [comment]
Fixed in 1.69b
