### ISSUE TITLE
Android build gives ERROR´s on MMORPG kit 1.69

### ISSUE THREAD

**Issue by Ervalord** [suriyun-production/mmorpg-kit-docs#1127]
This is with a fresh project and only with MMORPG kit asset.
It gives no errors when windows build, but when switching to android build it throws a bunch of errors. 

![169_windows](https://user-images.githubusercontent.com/56819674/132565604-30f609cb-4933-4659-aad0-eac3dae9d563.JPG)
![169_android](https://user-images.githubusercontent.com/56819674/132565617-3d3f2644-f784-456d-960e-d0cceea461df.JPG)
![169_android_console](https://user-images.githubusercontent.com/56819674/132565625-517e8b29-c5ec-423b-9382-7c904f7af8f6.JPG)

**Comment by insthync** [comment]
If you are going to set up in-game item purchasing, you have to set up Unity Purcahsing.

Or remove `ENABLE_PURCHASING` and `UNITY_PURCHASING` from `Scripting Define Symbols` if you don't intended to set up in-game item purchasing.
