### ISSUE TITLE
Suggestion: Auction House

### ISSUE THREAD

**Issue by AKCore** [suriyun-production/mmorpg-kit-docs#1129]
In many popular mmos player driven economy is a really good retention method. 
Having an auction house with timed auctions would help bolster engagement. 
There are a lot of players that have fun just trying to play the market. 

Also you should add bountysource to this repo so that we can put money towards bounties for commonly requested features.

**Comment by RunOrDi3** [comment]
we have talked to suriyun and he told us he will do it .. you have to wait till he make it

**Comment by AKCore** [comment]
well I would put 100$ towards it happening faster :)

**Comment by Callepo** [comment]
https://ko-fi.com/insthync 

Can always donate to his coffee

**Comment by AKCore** [comment]
Is there a way we could possibly pool a bounty for this @insthync 
I know there are a few people that would also dedicate to the pool.

**Comment by kittrellbj** [comment]
I'd be interested in throwing into a bounty fund for priority on this feature.

**Comment by GrandmasterPennell** [comment]
Please add. please please please please please please please pretty please

**Comment by insthync** [comment]
I will start it next month, I am going to finish the multiplayer arena part for the turn-base RPG project before doing it.

**Comment by insthync** [comment]
Will start the development next week, thank you :)

**Comment by AKCore** [comment]
No problem. I only have one major request for the auction house, that it has buy orders as well. 
I/e 
player can put item + amount and cost they will pay :)
