### ISSUE TITLE
Bug With Storage Sorting

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#113]
Squares... Squares everywhere.. u deposit an item and try to change its location... Squares... squares everywhere 
XD
https://www.youtube.com/watch?v=IUUCqMc8tSo&feature=youtu.be

**Comment by Callepo** [comment]
![storage](https://user-images.githubusercontent.com/7702658/67407966-90954500-f5b8-11e9-81d1-8e48c101949a.JPG)
 this fixed it

**Comment by insthync** [comment]
Yes, that is it :p

**Comment by insthync** [comment]
And I think to remove that 2 lines will not cause other issues because `CanDrag` can just check at `BeginDrag`. If it cannot drag then it will not begin.

**Comment by Callepo** [comment]
cool, ill tell the others
