### ISSUE TITLE
PlayableCharacterModel - Hurt animation issue

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#1130]
Hi,
When I am attacking and any enemy hurt me, the attack animation instantly gets interrupted, and then the player can kill the enemy without playing any animations (because the attack routine continues calculating other damages specified in Trigger Duration Rates).
This happens also without specifying any clip for hurt.
![image](https://user-images.githubusercontent.com/55019005/132761348-3c27eb68-57be-4a66-b71b-96a47de6e6a1.png)

**Comment by insthync** [comment]
It actually shouldn't play hurt animation while playing attack animation, I actually added conditions to check if it is playing attack animation or not (try to find `isDoingAction`). 

About idle state playing when hurt, 
Try add this condition to `PlayHitAnimation` function
```

            if (defaultAnimations.hurtState.clip != null)
```

![Screenshot_639](https://user-images.githubusercontent.com/2697550/132962379-632f7cfc-e738-4d10-ac44-7ade5b575d71.png)

**Comment by DevMMORPG01** [comment]
Hi insthync. Even normal attack animation is interrupted by monsters. We cannot find a solution to fix it.
Normal attack animation should not be interrupted.

**Comment by insthync** [comment]
But as I test it is not interrupted

**Comment by insthync** [comment]
As I mentioned here, I've added conditions to check if it is playing attack animation or not (try to find `isDoingAction`). You should try to find that the attack animation is actually interrupted while the character is attacking. Or it's not interrupted, it's just playing hurt animation after attacking animation played.

**Comment by insthync** [comment]
Are you using `AnimatorCharacterModel` or `PlayableCharacterModel` for your character?

**Comment by DevMMORPG01** [comment]
I am using AnimatorCharacterModel the default for the Male Prefab
![image](https://user-images.githubusercontent.com/90834568/133953667-aa117e39-db7d-46a2-8d5a-c57b1b1cb93b.png)

My normal attack animation is punching the enemy.
The swinging of arm is just halfway and it stop and play the hurt animation when hit by monster.
I found the code isDoingAction. I put    isDoingAction = true;      so now it doesnt interrupt.

**Comment by insthync** [comment]
Ahh I see, I was testing only `PlayableCharacterModel`
