### ISSUE TITLE
NullReferenceException after using a Instance Map/Dungeon (while trying to auto-clean/destroy)

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1132]
Using Unity 2021
Unity MMORPGKit 1.69 (latest)  

If I spawn a instance dungeon or map (or rather use a warp portal with instance mode), and once I exit the map (so the map has no players/use), I think the server tries to clean the instances and destroy them.  
Except that it's not able to and throws a NullReferenceException (on server) with OnDestroy->StopHost->OnStopHost chain  

I am testing on a local windows server (build) and local windows client (build) in MMO mode.  

![image](https://user-images.githubusercontent.com/3790163/132981416-4aca0019-9a97-4195-b8e3-7501510e82d3.png)

![image](https://user-images.githubusercontent.com/3790163/132981420-74ea0875-5cc4-449c-945c-316c4444596b.png)

**Comment by insthync** [comment]
It is from `LogManager` -> `LoggerFactory` which is disposing when application quitting, I think it's actually can be ignored, but I will add null checks to `GetLogger` functions
