### ISSUE TITLE
Add a weapon attack animation event

### ISSUE THREAD

**Issue by 417329908** [suriyun-production/mmorpg-kit-docs#1135]
When you attack with a weapon,sometimes the weapon has it's own animation ,such like  bows,guns and some melee weapons,or can you make a tutorial to show how to add a bowstring animation?

**Comment by Fr-Coder** [comment]
I don't think this is a kit-related question, anyway take a look at blendshape to animate the bow and create a script that starts animation based on animation event.

**Comment by 417329908** [comment]
I only know invector Controller's bow system,where can I find blendshape bow tutorial?If it worked I will learn.

**Comment by insthync** [comment]
Can you tell me how it is ?

**Comment by 417329908** [comment]
Maybe ti's like this :
[https://www.youtube.com/watch?v=1rv8lv_TOc8](url)
I have used invector Controller's gun and bow system,it gives every weapon a animator event to do this.

**Comment by insthync** [comment]
This kit may not likes others, there is no single standard to implement animation playing.

With this kit, after you create an animation set it to `Animator Character Model` component -> `Default Animations` or `Weapon Animations` -> `Right Hand Attack Animations` or `Left Hand Attack Animations`.

You can see how to set animations here https://dev.to/insthync/create-game-with-mmorpg-kit-part-2-map-and-first-character-54dl

**Comment by 417329908** [comment]
> 这个套件可能不喜欢其他的，没有单一的标准来实现动画播放。
> 
> 使用此工具包，在创建动画后将其设置为`Animator Character Model`component ->`Default Animations`或`Weapon Animations`->`Right Hand Attack Animations`或`Left Hand Attack Animations`。
> 
> 您可以在此处查看如何设置动画https://dev.to/insthync/create-game-with-mmorpg-kit-part-2-map-and-first-character-54dl

Yes,I checked MMORPGKIT,addding character animations is very easy.
But the weapon needs animations too,so I checked the weapon item prefabs Weapon065,it has launch effect and launch sound ,very cool,now the gun need a launch animation too,such like these weapons:
https://www.youtube.com/watch?v=ZZzirMjyLuc

**Comment by insthync** [comment]
Oh, I see, I will add an event to `Equipment Entity` which will be called when attack/reload/charge start and charge ends. You can create another component to play animation when the event is triggered.

**Comment by 417329908** [comment]
> 哦，我明白了，我将添加一个事件，`Equipment Entity`该事件将在攻击/重新加载/充电开始和充电结束时调用。您可以创建另一个组件来在触发事件时播放动画。

Yes,we'll get Lifelike weapons.

**Comment by insthync** [comment]
In 1.69d 
- Add `onPlayLaunch` event to `Equipment Entity` component, can use it to play gun firing animation.
- Add `onPlayReload` event to `Equipment Entity` component, can use it to play gun reloading animation.
- Add `onPlayCharge` event to `Equipment Entity` component, can use it to play bow's string holding animation.
