### ISSUE TITLE
server errors

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1136]
this is not my log in the pic but i have the same errors should i be concerned about these fallback errors for lib when the server is running fine? 
![unknown](https://user-images.githubusercontent.com/78616165/133292123-36f3aab3-b7e7-40e9-b9c8-efe0823a228c.png)

**Comment by insthync** [comment]
You can ignore them it is the shaders thing, which server doesn't use them.

**Comment by Sour-J** [comment]
Not the shader warning below that I'm concerned . It's the mono/libadvapi32.dll all the fallback handlers those are shaders too?

**Comment by insthync** [comment]
https://forum.unity.com/threads/libadvapi32.828759/

**Comment by Sour-J** [comment]
Thanks
