### ISSUE TITLE
Small improvement for Skill Hotkeys

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1138]
When using a skill (in this case an AOE) and the skill goes in cooldown, then when you try using the same skill again while in cooldown you can activate it and only after try to apply to skill you will get the message that its in cooldown.

would be cleaner and better when it checks before so when u click on skill if its on cooldown

https://gyazo.com/8d9c6f42d2b99b774fb4411ad1fbab14

**Comment by insthync** [comment]
Applied in 1.69c
