### ISSUE TITLE
Attack Animations

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1139]
If the character is hit by a monster while using a skill or attack, the animation will be interrupted.
Cannot find the option to disable to interrupt.
When a character is attacked by more monsters. It cannot do any normal attack animation because it is always interrupted.

**Comment by DevMMORPG01** [comment]
When a character is attacked by more monsters. It cannot do any normal attack animation because it is always interrupted.

**Comment by moepi2k** [comment]
normal attacks cant be interrupted. its just the animation  that looks so. but the attack will still apply.
for skill you have the option on the scriptable
https://gyazo.com/2e438f5c7732cddbb63248e9c4b52fd9

**Comment by DevMMORPG01** [comment]
the normal attack animation is interrupted. yes the skill option is updated, we can now select the option for interrupt. 
but there should also be option to disable normal attack animation interruption.

**Comment by moepi2k** [comment]
thats another thing, your first post was regarding interruption normal attackts, and normal attacks will never be interrupted. only skills.

but i cant see the sense for interruption normal attacks. normal attacks has no casting time

**Comment by DevMMORPG01** [comment]
please re read my first post.
or let me type here again.
=========
If the character is hit by a monster while using a skill or attack, the animation will be interrupted.
Cannot find the option to disable to interrupt.
When a character is attacked by more monsters. It cannot do any normal attack animation because it is always interrupted.
=========

I will highlight this "When a character is attacked by more monsters. It cannot do any normal attack animation because it is always interrupted."

**Comment by DevMMORPG01** [comment]
I want to state it clearly.

PROBLEM: "Normal attack animation is interrupted by monster attack."
SOLUTION: "Disable the interrupt and let the normal attack animation finish the whole animation clip."
