### ISSUE TITLE
Request issue 1117 be deleted, and this one, too.

### ISSUE THREAD

**Issue by kittrellbj** [suriyun-production/mmorpg-kit-docs#1140]
I request https://github.com/suriyun-production/mmorpg-kit-docs/issues/1117 be deleted, which can only be done by Suriyun (or a repository administrator). The conversation has been completed, action was taken, and for the benefit of the community going forward, it should be removed from public view, such as by this method: 

https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue 

Since it does not provide a useful knowledgebase purpose, it should be deleted. And feel free to delete this issue requesting the other one be deleted.

**Comment by insthync** [comment]
Deleted
