### ISSUE TITLE
UIMmoLogin.cs and UIMmoRegister.cs don't accept InputFieldWrapper, only InputField

### ISSUE THREAD

**Issue by gordowebdesign** [suriyun-production/mmorpg-kit-docs#1141]
Set to only accept InputFields not the InputFieldWrapper (for TextMeshPro Input Fields with correct wrapper)

**Comment by gordowebdesign** [comment]
Also: UIMmoServerEntry.cs line 11 Text vs TextWrapper

**Comment by insthync** [comment]
Changed in 1.69c
