### ISSUE TITLE
[1.69b Bug] Guilds not registering in MMO Mode

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1142]
A player can register a guild and get the yellow name beneath him, but it won't allow access to the guild window.
When the player relogs, the guild will no longer exist, but the money is taken.

Video:
https://i.imgur.com/k7dnpU4.mp4

Note: I've only added a Synty character and map, no other changes made to the base demo.

**Comment by insthync** [comment]
Fixed in 1.69c
