### ISSUE TITLE
[1.69b Bug] Whispers not working in MMO mode

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1143]
Sending a whisper in chat to another player will show in the SENDERS chat box, but won't arrive at the receivers chatbox.

Video:
https://i.imgur.com/KpVDG2T.mp4

**Comment by insthync** [comment]
Try set receiver input field to UI Chat Handler 
![Screenshot_647](https://user-images.githubusercontent.com/2697550/133892359-0d01e911-a5e7-4e4f-814e-27ebd9d80ab6.png)

**Comment by BJPickles** [comment]
> Try set receiver input field to UI Chat Handler
> ![Screenshot_647](https://user-images.githubusercontent.com/2697550/133892359-0d01e911-a5e7-4e4f-814e-27ebd9d80ab6.png)

Sadly did not work.
I created a fresh server build (and then uploaded to VPS) and client to test on, and deleted the old characters and used fresh characters.

Video:
https://streamable.com/eo5i4y

**Comment by insthync** [comment]
Fixed in 1.69c
