### ISSUE TITLE
Guild Friendly fire

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1144]
Is there a way to make it so you can't hurt your own guild? 
It's just annoying having your pets attack your own guild you have to be in a party for no friendly fire. In survival if you build a base with your guild it's very sensitive because you can hurt each other easily with aoe and pets

Also you can debuff your own party members I'm able to stun them so if friendly fire is not a thing for partys debuff shouldn't be either 

Any advice is appreciated thank you

**Comment by insthync** [comment]
If you don't want guild members able to attack each other, you have to change rules in your `Map Info` class, you can see `Guild War Map Info` as an example.

If you don't want to apply debuff to other characters, you can check other character is ally or not by `IsAlly` function

**Comment by Sour-J** [comment]
thank you
