### ISSUE TITLE
Party exp share issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1145]
when players are offline and still in a party they share exp with offline party.

for example killing monsters that give 20 exp each player gets 5 exp.  player 1, 2, 3, 4 are in the same party with share exp on, when player 2, 3, 4 logoff, player 1 keeps playing and is getting less exp (5 still) because its still being shared with 2, 3,4. Anyway to make it so when they go offline it stops the exp share?

**Comment by insthync** [comment]
Fixed in 1.69d
