### ISSUE TITLE
[Improvement] Top-Down Controller

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1149]
Could you add more features to top down controller like moving by [ wasd ] and zoom in and out .. also will be good if you add it inside kit as an 3rd controller with player character controller and shooter character controller .. many developers using it

**Comment by insthync** [comment]
It's an open-source project, I hope someone will do it and make a pull request, I am very tired.

**Comment by RunOrDi3** [comment]
i will try to make it , its fine :)
