### ISSUE TITLE
BUG? In-game purchases

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#115]
Single Player Game Android
After buying crystals in google play in the game, I received the following warning. Because of this, money was deducted from the card, but crystals were not added.
![m5xvLkDxjRs](https://user-images.githubusercontent.com/47291794/67481363-8cc1fb00-f66a-11e9-995f-552f6a985fd8.jpg)
The standard inscription "Connection timed out". While the payment was being processed, the screen went blank and as a result we have this warning. Sometimes for 1 second you turn off the screen and immediately receive this warning. Probably need to remove it.
After a repeated purchase, I constantly receive the following warning.
![g9VYF7qm4vg](https://user-images.githubusercontent.com/47291794/67482572-a106f780-f66c-11e9-909f-bf8a79cc5118.jpg)
In fact, due to the extinction of the screen, 1 pack stopped working completely and now it is impossible to buy it.
![XJco6EdHllQ](https://user-images.githubusercontent.com/47291794/67482745-ef1bfb00-f66c-11e9-9d61-cdcfd2cafd08.jpg)

After I made the second payment and it went well. I got 210 crystals into the account and decided to buy an item. But the item could not be bought and I received an empty warning.
![-xUu2Ir9ocg](https://user-images.githubusercontent.com/47291794/67481699-09ed7000-f66b-11e9-8be4-1b2fa0ca8751.jpg)

if there are not enough crystals, then the warning is as follows. Everything is fine here.
![ANcp1C0asvE](https://user-images.githubusercontent.com/47291794/67503399-3ff11b00-f690-11e9-8ec4-186d01cd9321.jpg)

Everything was done in a single game and on a closed test in google play.

In fact, the system works. Buying an item for crystals does not work. And we need to do something with the shutdown when the screen goes blank.

**Comment by insthync** [comment]
Okay, I will check it.

I think it's disconnected because game-networking thread stop working while you make payment

And then you can't buy it again (2nd image) because there is pending purchasing that is not finished.

**Comment by DimasjkTV** [comment]
> Okay, I will check it.
> 
> I think it's disconnected because game-networking thread stop working while you make payment
> 
> And then you can't buy it again (2nd image) because there is pending purchasing that is not finished.

It looks like this. Application disconnects after the screen is turned off. Is this a feature in the Mmorpg kit or is the android?designed?

**Comment by insthync** [comment]
Now, while playing singleplayer it will start server which allow only 1 player to connect then connect to itself, so the server can stop and it will disconnect after screen is turned off, To fix this problem, I think I will make offline transport system for networking system.

**Comment by DimasjkTV** [comment]
> Now, while playing singleplayer it will start server which allow only 1 player to connect then connect to itself, so the server can stop and it will disconnect after screen is turned off, To fix this problem, I think I will make offline transport system for networking system.

it will be very cool! I do not want my game to be paid xD Thank you !

**Comment by DimasjkTV** [comment]
With this system it will be possible to do so that the character's chest in single player was common? Like in MMO

**Comment by insthync** [comment]
No, to do like as you say it's possible but it will have to change save codes

**Comment by DimasjkTV** [comment]
> No, to do like as you say it's possible but it will have to change save codes



> No, to do like as you say it's possible but it will have to change save codes

I understood. Thanks for the clarification =)

**Comment by insthync** [comment]
I've added offline transport to 1.50b

**Comment by DimasjkTV** [comment]
> I've added offline transport to 1.50b
this?
![image](https://user-images.githubusercontent.com/47291794/68037892-ced9e500-fcd9-11e9-92aa-f147bf176848.png)

**Comment by insthync** [comment]
No, this is for server load validation. For offline transport, just update the CORE it will be included.

**Comment by DimasjkTV** [comment]
> No, this is for server load validation. For offline transport, just update the CORE it will be included.

oh very good

**Comment by DimasjkTV** [comment]
> No, this is for server load validation. For offline transport, just update the CORE it will be included.

I tested the purchases. Everything works fine in a single player game. Thanks!

**Comment by insthync** [comment]
Error message will be improved in 1.52b update.

**Comment by insthync** [comment]
Error messages were improved in 1.52b, I will close this issue post.
