### ISSUE TITLE
Sprite 2D

### ISSUE THREAD

**Issue by alexengel1992** [suriyun-production/mmorpg-kit-docs#1153]
I wanted to know if it is possible to use this sprite as a playing character ,and if there is any tutorial on how to do it

https://user-images.githubusercontent.com/83098223/134785826-e36cf0fb-7e20-4d3e-8737-e57cc500f8c3.png

**Comment by insthync** [comment]
Yes, you can do it, but I didn't write the tutorial for it yet.

You have to learn https://learn.unity.com/tutorial/introduction-to-sprite-editor-and-sheets

Then you may see demo data in `UnityMultiplayerARPG\Demo2D\Animations\Warrior2D\ as an example of animation clip 2d data

When you are going to create your animation clip 2d -> you have to right-click in `Project` window -> `Create` -> `Animation Clip 2D`

Then set an animation clip 2d to your character entity -> character model 2d component
You can find `Warrior2D` to see how to set your animation clip 2d to `Character Model 2D` component

![Screenshot_663](https://user-images.githubusercontent.com/2697550/134786392-364e484e-b928-4e24-92d7-7116381caf99.png)

**Comment by insthync** [comment]
I will close this, if it is still occurring, you can reopen this.
