### ISSUE TITLE
Bows Magically Lose Scale

### ISSUE THREAD

**Issue by MrBeatngU** [suriyun-production/mmorpg-kit-docs#1154]
For some reason, bows seem to randomly scale down when attacking. I'll leave a video for reference.
This only happens with bows. All of my other character's weapons have no issues what so ever.
https://www.youtube.com/watch?v=4PGo1Iptzxo

**Comment by insthync** [comment]
Please help me check that the Bow transform is scaling down or its parent is scaling down

**Comment by MrBeatngU** [comment]
The equipment container is what scales. The model itself stays at a scale of 1x1x1, The container itself is what scales. If you manage to fix it. Could you share the fix with me so I can stop racking my brain over this?
![scaleissue](https://user-images.githubusercontent.com/70456509/134851687-ca3c6125-f94c-4d2d-88c4-bf23fa9b9b8a.jpg)
.

**Comment by insthync** [comment]
The `lefthandweapon` is the transform that you create by yourself, it is not included with the character model?

**Comment by insthync** [comment]
I want to make sure that the animation clip will not be a cause of problems :P

**Comment by insthync** [comment]
I think you may try to create a new component that will be attached to `lefthandweapon` game object.

The component which will do only 1 thing is to set the local scale to 1

**Comment by MrBeatngU** [comment]
The only issue I've had with doing that is that the weapon itself doesn't set properly. So the model will place itself on the ground and not be attached to any of the animations or anything. That's why I had linked it directly to the player's hand lol

**Comment by MrBeatngU** [comment]
It also only happens once the projectile hits the enemy. Like the moment the sound is made and the damage pops up, the item randomly shrinks.

**Comment by insthync** [comment]
May I check it by using TeamViewer?

**Comment by MrBeatngU** [comment]
Yes of course. My discord is BawsMan#5101. I can send you the teamviewer information on there

**Comment by insthync** [comment]
Send your team viewer info to my email ittipon.bay@gmail.com

**Comment by MrBeatngU** [comment]
Emailed over
