### ISSUE TITLE
Suggestion: NPC body as harvestable

### ISSUE THREAD

**Issue by kittrellbj** [suriyun-production/mmorpg-kit-docs#1155]
Suggestion to make NPCs that can be harvested in the same way as resource nodes when they are killed. Examples:
- Kill a deer to skin it with a knife, receive resources, increase related skill.
- Kill rock monster to get certain rocks from the body with a mining tool, increase related skill.
- Kill a dragon to get dragon scales with a special tool, increase related skill.

If this already exists, you guys can let me know. It feels like a feature many games could use in the default kit.

**Comment by Callepo** [comment]
seems really game specific, especially the part bout lvling the related skill part, 
there is a lootbag addon in the server which basically is kinda like this. 
u kill something body drops on floor, u loot the body. we could have a system where it does certain animations or something

**Comment by kittrellbj** [comment]
These are features in every survival game, so I wouldn't really call it game-specific. Genre-specific, yes, applying to all projects, definitely not. The leveling skill part is also usually part of it in games that involve skill levels, but not so in those that do not.

So yes, survival MMOs and those with more intricate harvesting systems would benefit, but not all genres/types. The lootbag addon could be modified to perform in a similar way, but if Suri likes it and it wouldn't take a long time (I really don't think it would), it could be useful for others in those situations.

**Comment by Callepo** [comment]
true, survivals do have it, pretty common also, and the kit has survival so yea i can see it

**Comment by insthync** [comment]
I might not implement it soon, but you may try to use onDead event to spawn harvestable entity when character dead

**Comment by kittrellbj** [comment]
Yes, I was thinking something like that as an alternative if it didn't make it into the core kit. Update is fast, so they may not notice or mind much.

Since we're on the topic, where would be the best place to place events like this, where the character (or player) dies and would be triggered? I've looked through the code for the best place for other events that also trigger on death, and I can't decide where would be the best place for those.

**Comment by Callepo** [comment]
there is already an on death event, he meant just using the current events to achieve this, no need to make new ones.

Look on the playercharacter entity script in the inspector while selecting one of ur player character, 
or the monster entity script, while selecting a monster. u will see some events there visible. 
one of which is  dead... thats one easy way to make use of it without coding

**Comment by kittrellbj** [comment]
Ok, good. I could only find references to IsDead iirc, but I was doing a very big search on the code base. I'm not saying it's not there by any means, just that I didn't find it last time.

What I'm looking for is a trigger to hook to at the moment of death, so that will probably be exactly what I couldn't find before.

**Comment by moepi2k** [comment]
MonsterCharacterEntity.cs -> Events ->

https://gyazo.com/087593affea18e13253afd0792c31ddb

**Comment by kittrellbj** [comment]
Oh very nice. Thank you for pointing it out.

**Comment by insthync** [comment]
In version `1.85`, I've added `SimpleNetworkingSpawn`, you can use it to do like moepi2k told.
