### ISSUE TITLE
AreaSpanwer Harvestable

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1156]
When i place an harvestable area spawner and set range to 256 for example, i noticed that some harvestable far away are spawned but they are disabled like outside of net range.

i found this component on network manager

https://gyazo.com/f349d7090eeb11f357db641c1e8fc2df

increasing cell size fix the issue. can you explain me what exactly it does and if increasing that value is k?

**Comment by insthync** [comment]
I think the harvestable entity is just outside of the visible range, cell size will be used to generate grid for spatial positioning https://gameprogrammingpatterns.com/spatial-partition.html

**Comment by moepi2k** [comment]
mh okey thats weird, when i increase the cell size to 256 and it works.

check this first picture
https://gyazo.com/1c8189bdc130d699823e86c44042cfe2
here cell size is 100, all harvestabled on right side of the red line is disabled

and here with 256 its fine
https://gyazo.com/a65f43c357cd5d9dfaaea4e90b564ab3

map is also 256x256 and area spawner is at pos 0,0,0

**Comment by insthync** [comment]
![Screenshot_697](https://user-images.githubusercontent.com/2697550/135439189-6e09c6d1-cbbd-4fc2-9b83-ca84b0f438f8.png)

Try select your network manager and see how the grid is, is it cover the map this image above or not.

**Comment by moepi2k** [comment]
it looks like this 
https://gyazo.com/dd6ab4995c0ae7ce54f7695181c7629c

**Comment by moepi2k** [comment]
i changed pos of terrain to 0 0 0 now the grid looks same but the issue is still there.

i figured out when net range of harvestable is 50+ everythings fine. when i put it to >= 40 the issue occure

https://gyazo.com/fbe8c1f2d8137c72349e356a7964086b
https://gyazo.com/75a0c4041aa597bfc56e316434c8ff27
here u see with net range of 40 everythings cut on right side of the red border.

all harvestables are spaned with only one area spaner. radius 256x256 to spread over the whole map.

and here i use net range of 50 for harvestables
https://gyazo.com/4d1eaaed97f1747125d18f50697d1a28

the harvestables on right side of border are visible.

i also figure id out when net range is <=40 so that the issue occure but i manualy place an harvestable on the right side like this 

https://gyazo.com/7f6dc8ef240e597ad244866b92207f12

everything works
https://gyazo.com/192fa967f0c7e1a8ff7ca3cc5ef43c88

somewhere is an issue with the range i think

**Comment by insthync** [comment]
I will change `generateGridMode` options, seems like your problem is the grid manager generates grid to cover renderer, no terrain included so it won't generate grid cover the terrain

**Comment by moepi2k** [comment]
Great thank you ❤️
