### ISSUE TITLE
[Bug]NoConstructionArea

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1157]
When add a gameobject like this:

https://gyazo.com/ac29bf972075b22004e71cbe1feb1410

it works that player can build, but the problem is that projectiles collide at the border. you can shoot inside but not through the collider when you stand inside or vise versa

**Comment by insthync** [comment]
Not sure how it is, but as I test, it fire pass through and I think `NoConstructionArea ` is not the cause of the problem, maybe collider's layer, not sure that you use custom projectile or something?
https://youtu.be/k2zM31dVdIM

**Comment by moepi2k** [comment]
yea strange. small ones also works for me. no its not custom its the default raycast projectile.

https://gyazo.com/f81c0bd90ebefae4944b43a44f847789

i have a big collider. shoot from outside to inside works. but when stand inside collider and try shoot out its not working.

weird thing :/ i will debug to check what it hit

**Comment by moepi2k** [comment]
ok got it, it was a layer issue. my fault :)
