### ISSUE TITLE
[Bug]Campfire

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1158]
issue happen in singleplayer (not tested yet in mmo)
when u build a campfire and activate it then log out and login the campfire is runnig with this error

`KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].ThrowKeyNotFoundException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
MultiplayerARPG.LanRpgServerStorageHandlers.NotifyStorageItemsUpdated (MultiplayerARPG.StorageType storageType, System.String storageOwnerId) (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgServerStorageHandlers.cs:192)
MultiplayerARPG.LanRpgServerStorageHandlers+<DecreaseStorageItems>d__7.MoveNext () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgServerStorageHandlers.cs:96)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:342)
MultiplayerARPG.CampFireEntity+<ConvertItem>d__31.MoveNext () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/BuildingSystems/CampFireEntity.cs:202)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskScheduler.cs:90)
MultiplayerARPG.<ConvertItem>d__31:MoveNext() (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/BuildingSystems/CampFireEntity.cs:212)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetException(Exception) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:334)
MultiplayerARPG.<DecreaseStorageItems>d__7:MoveNext() (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgServerStorageHandlers.cs:103)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:194)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Update() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:159)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:118)
`

**Comment by insthync** [comment]
It is occurring because campfire was spawned and updating before storage items were loaded, it is actually can be ignored, but I will add codes to avoid the error.
