### ISSUE TITLE
BUG Set bonus stats rate UI

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#116]
1. Stats 10 hp - All is ok
![image](https://user-images.githubusercontent.com/47291794/67518578-bb14fa00-f6ad-11e9-9b00-f2e982c62729.png)
2. Stats 10 hp + Stats Rate 100% hp - All is ok
![image](https://user-images.githubusercontent.com/47291794/67518675-eac40200-f6ad-11e9-9c01-80bb85cc7e12.png)
3. Only Stats Rate 100% hp - not displayed in bonus sets. Bonus works, but not displayed.
![image](https://user-images.githubusercontent.com/47291794/67518767-15ae5600-f6ae-11e9-887a-9b352a6e4c5a.png)
seems to need an additional component to the sets, as is done in attributes and stats.

**Comment by insthync** [comment]
Okay, I will fix it

**Comment by insthync** [comment]
Fixed
