### ISSUE TITLE
Avatar Mask problem

### ISSUE THREAD

**Issue by 417329908** [suriyun-production/mmorpg-kit-docs#1160]
In new version playable character model,I want to make a TwoHandSword,right hand attack has a topmask animation,bash skill has a fullbody root motion animation.
I click Action Avatar Mask empity and Root Moting Settings on.
When I give Right Hand Attack one clip a topmask,all twohandsword animations and skills will get it,so I give Bash Skill a fullbodymask,but the root motion stops work.I test animator character model ,it can't work,so I test old version,there's no problem.

**Comment by insthync** [comment]
You mean old playable character model has no problem or animator character model has no problem?

**Comment by 417329908** [comment]
> You mean old playable character model has no problem or animator character model has no problem?

My old version is mmokit v1.63g,it only has animator character model,it can work.Now I use 1.69d,can't work.

**Comment by insthync** [comment]
So... playable character model with root motion animation is not working. I will check Unity again that the root motion animation will work with root motion animation properly or not.

**Comment by 417329908** [comment]
> So... playable character model with root motion animation is not working. I will check Unity again that the root motion animation will work with root motion animation properly or not.

Thanks,exactly,it's two problems,one clip with Avatar Mask changes other clips with empity mask,and root motion can't work with fullbody mask,if all the clips have empity mask,root motion can work,animator character model has the same problem.

**Comment by insthync** [comment]
Not sure it was fixed in 1.70 please try it.

**Comment by insthync** [comment]
May I ask for your email, I will send an updated scripts for you to try it.

**Comment by 417329908** [comment]
> Just sent the email (my email is [ittipon.bay@gmail.com](mailto:ittipon.bay@gmail.com))

All problems above have been fixed in new scripts.
I test more:
https://www.youtube.com/watch?v=I_lBNYChboM
jump,sometimes animator character model rotates twice during synchronization.
move one step，sometimes characters move two steps during synchronization.
