### ISSUE TITLE
Quest UI does not work

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1161]
I tested the latest version 1.69d. Clean New Project. I accepted one quest. But the quest tab on the new UI design doesn't work. same with the create party button.
When i create new party using the old method via the menu. The party members shows up on the new party UI.
![image](https://user-images.githubusercontent.com/56482598/135661507-e4550254-eaf5-4a32-999c-4ee0ca2d2419.png)
![image](https://user-images.githubusercontent.com/56482598/135661536-451ff891-53ff-4e8a-92f7-08c2ff25c47f.png)

**Also, the chat button does not work**. Previously, when you clicked the chat window would appear and disappear. Now nothing happens.

**Comment by insthync** [comment]
Just wrong order of UIs and missing button events, the fixing will be included in next version

**Comment by insthync** [comment]
Fixed in 1.70
