### ISSUE TITLE
Character does not attack

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1162]
When a character appears, the very first attack does not work. When you press attack, the target is highlighted, but the character does not go to it and does not attack. If you come close to the mob and several times to press attack, it works and then everything goes fine. The problem in the very first attack when entering the game.

**Comment by insthync** [comment]
![Screenshot_701](https://user-images.githubusercontent.com/2697550/135677726-cf53681d-82f6-4c86-b5bc-ab2591e49ef6.png)

Turn this on.

**Comment by Serivatech** [comment]
Apparently, you don't understand what I mean :)

I'm talking about the mobile version. Pressing the attack button selects the target, but does not attack. No matter how many times you press it, the character just stands there. Only starts to attack when you come close. After that, begins to attack normally. I mean, after the first mob the rest of him and chooses to attack. But not the very first!

I am so lazy to record a video :(

**Comment by insthync** [comment]
Seems like a problem occurring because your character is in a safe area, you have to exit from safe area to attack.
