### ISSUE TITLE
Question: How to gain experience for Guild?

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1163]
![guild](https://user-images.githubusercontent.com/90834568/135713809-bfdf4070-ef1b-49fb-82d4-c227c374b1bb.png)
I cannot find in the documentation or in discord.
I tried doing quest and normal character levelup. But no experience gain.

**Comment by insthync** [comment]
You have to set exp sharing in guild roles setting

**Comment by DevMMORPG01** [comment]
Ohhh. So it becomes like a guild tax in a form of xp. Nice. Thanks.
