### ISSUE TITLE
FPS Hidding Renderers no shadow

### ISSUE THREAD

**Issue by 417329908** [suriyun-production/mmorpg-kit-docs#1168]
FPS Hidding Renderers should hide mesh and open shadow,it will be very nice.

**Comment by insthync** [comment]
Seems like I have to add something to make it able to change shader when hide or show meshes

**Comment by LordPhrozen** [comment]
What about a dummy material that is fully transparent but treated as opaque?

**Comment by insthync** [comment]
In 1.72
```
- Add `visibleMaterials`, `invisibleMaterials` and `fpsMaterials` settings to `GameEntityModel`.
```

Try set your shader
