### ISSUE TITLE
Filtering Crafting working?

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1169]
can you confirm if the filtering for queued crafting formulas is working?

https://gyazo.com/e1dfdcd087d5be91afb7897374863e55

i use filtering for skills and works fine, but somehow it not filter crafting formulas.

**Comment by insthync** [comment]
As I test, it's working
https://youtu.be/qHscpzdnGog

But I've set category in formula data
![Screenshot_710](https://user-images.githubusercontent.com/2697550/135909731-bc54d254-8414-4537-bdde-d5138c3f63bc.png)

I guess that you've set it to item data, which is make sense. 

So I will add it to check the item's category too, its filter priority is if the formula's category is empty check the item.

**Comment by moepi2k** [comment]
Hm no i used ales category in formula, can u show how your setup looks like for multible filters like Weapon and Armor for example? Maybe i do something wrong with tje ui stuff. I made few buttons where player can filter between formulas
