### ISSUE TITLE
Mmorpg kit supports webgl?

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#117]
Mmorpg kit supports webgl? After the build, there are no errors, but when launched in the browser it displays "not found".

**Comment by insthync** [comment]
What is not found? please attach the screen shot.

**Comment by Serivatech** [comment]
Does it make sense to take a screenshot? Just select WebGL in a clean project and click "Build And Run".

**Comment by insthync** [comment]
Yes, it makes sense because I don't know what and how that does not work and what is **Not found** you mean in the browser showing up webpage not found ?

**Comment by Serivatech** [comment]
Can I write via discord?
This is too easy to check:
1. Clean project. Only package "mmorpg kit".
2. MMO. All according to the instructions in the documentation.
3. Select WebGL. Press the "Build And Run" button.
4. See the problem.

Why screenshots? It’s not difficult for me, but it will not add clarity, it’s easier to see in person.
Step 1: [https://pastenow.ru/6e1411c36323f14da0ffd038e95d62fa](url)
Step 2: [https://pastenow.ru/b6be5421bc2cb0aaf27f2380f14f9674](url)
For convenience, I uploaded the result to my server. On the working PC, everything is the same.
[game.seriva.tech](url)
error: [https://pastenow.ru/2f4a0b460bc6b25b15f49462f14c7946](url)

link to my server [game.seriva.tech](url)

**Comment by insthync** [comment]
As I try to see how files loads I see that file cannot be loaded
![Screenshot_131](https://user-images.githubusercontent.com/2697550/67623044-d79a6900-f84a-11e9-9777-38c3f55efb7d.png)

Then it is redirecting to the page https://pastenow.ru/2f4a0b460bc6b25b15f49462f14c7946 which is the same the url with the above image.

Oh, And I also found it is trying to read "serverConfig" file it might be the cause of issues
![Screenshot_133](https://user-images.githubusercontent.com/2697550/67623258-3a8cff80-f84d-11e9-8ddd-7eb6c472be44.png)

So, please try set scene name **00Init_MMO_ClientOnly** as first scene in **Scene In Builds** setting

**Comment by Serivatech** [comment]
So? https://pastenow.ru/d55842cc3b02f7adb13dae1e6033fed7
Updated files on the server. Now it starts. I think it will take some help with tuning so that everything works for sure. 10 minutes and I will start the game server and change the IP in the client.

**Comment by Serivatech** [comment]
Use WebSocket? If so, where to indicate?

My English through Google Translator

**Comment by insthync** [comment]
Yes, you will have to set networking transport which able to use with websocket. If your game is making for web-browser players only, you can check on **Use Web Socket** in **MMOServerInstance** and **MMOClientInstance**

![Screenshot_134](https://user-images.githubusercontent.com/2697550/67623598-5c888100-f851-11e9-9cff-89d8ac216758.png)

![Screenshot_135](https://user-images.githubusercontent.com/2697550/67623601-601c0800-f851-11e9-89e4-d91ece3a698a.png)

Do it in both **00Init_MMO** and **00Init_MMO_ClientOnly** scenes 

* * *

If you want it to be playable together in every platform (Web, Mobile, PC) you have to attach **MixTransport** and set to all network managers

![Screenshot_136](https://user-images.githubusercontent.com/2697550/67623894-d0785880-f854-11e9-9bfd-958e54caeb3b.png)

![Screenshot_137](https://user-images.githubusercontent.com/2697550/67623899-d9692a00-f854-11e9-848a-fc8c23d40daa.png)

![Screenshot_138](https://user-images.githubusercontent.com/2697550/67623903-dec67480-f854-11e9-9995-9100c45b8cd0.png)

![Screenshot_139](https://user-images.githubusercontent.com/2697550/67623905-e2f29200-f854-11e9-9fb4-1fa81608ed95.png)

**Comment by Serivatech** [comment]
Error. http://game.seriva.tech

**Comment by insthync** [comment]
Oh, the port is blocked (https://www-archive.mozilla.org/projects/netlib/portbanning#portlist)

You have to change port. For the server, you won't have to rebuild the server, you can change ports in server config, just change **centralPort** port to other port, you may set it to 7000

![Screenshot_141](https://user-images.githubusercontent.com/2697550/67624340-965d8580-f859-11e9-86a0-2966499af85d.png)

* * *

But for the client you will have to change port in network setting like as server and rebuild it

![Screenshot_140](https://user-images.githubusercontent.com/2697550/67624343-a2494780-f859-11e9-922a-f27b1363ecfb.png)

**Comment by insthync** [comment]
You may doubt about what are differences between **00Init_MMO** and **00Init_MMO_ClientOnly**

00Init_MMO made for server build because it has **MMOServerInstance** which contains network managers which made for server

So if you want to build game server, you must set 00Init_MMO scene as first **Scene In Build**

* * *

**00Init_MMO_ClientOnly** will have only **MMOClientInstance** which contains network managers which made for client 

So if you want to build game server, you must set 00Init_MMO_ClientOnly scene as first **Scene In Build**

**Comment by Serivatech** [comment]
The server is running, but does not connect.

**Comment by insthync** [comment]
You may have to setup firewall to allow ports (or turn off the firewall) if you use linux server you may see this article https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-18-04

You will have to allow port 7000 (Central Server), 6001 (Map Spawn Server), 6002 (Chat Server), 8000 (Map 001 Server), 8001 (Map 002 Server)

**Comment by Serivatech** [comment]
Why aren't there any mistakes? Nothing just happens.

**Comment by insthync** [comment]
You may have to restart server machine, to applies firewall rules

**Comment by Serivatech** [comment]
server IP : rvrgame.zapto.org (the server is running on my computer through the service https://www.noip.com/ )
Launch : D:\Project\bin\server\Project.exe -startMapSpawnServer -spawnExePath "D:\Project\bin\server\Project.exe" -startCentralServer -startChatServer -machineAddress "rvrgame.zapto.org"

firewall does not block anything.

Result: http://game.seriva.tech/

**Comment by insthync** [comment]
As I try, it still can't reach to rvrgame.zapto.org (I try pinging it)

**Comment by Serivatech** [comment]
Uploaded to VPS. Does not work. It does not connect and does not produce any errors. BUT! If you remove WebSocket then it connects to the PC.

**Comment by insthync** [comment]
As I try, I can connect to server then I found the issues that chat-server / mapspawn-server / map-server cannot connect to central-server, so I fixed it. 

This is the patch: 
[FixInvalidWebSocketTransport(MMO).zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3776354/FixInvalidWebSocketTransport.MMO.zip)

I also capture video about how I setup for WebGL games
https://youtu.be/m-tNN4oGwsc

**Comment by bedrygamed** [comment]
is that it ?
