### ISSUE TITLE
Question: How to hide instantiated objects in runtime?

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1170]
Hi Ithy, this is really not an issue. Just want to know how can I hide instantiated objects.

Like hide the arrow when the character is idle. And only show it when the animation to shoot arrow is playing.
![arrow](https://user-images.githubusercontent.com/90834568/136036730-ad1b34bd-b57b-46c1-9e55-093c117e4bfb.JPG)

**Comment by insthync** [comment]
You actually can use (https://docs.unity3d.com/Manual/script-AnimationWindowEvent.html) to do it, you may do it like:

Create the arrow manager component which will be attached to the same game object with animator component. 

Then when it's going to attack, use arrow manager component to show arrow and hide the arrow when the attack animation is ending.

**Comment by insthync** [comment]
Are you able to do it?

**Comment by DevMMORPG01** [comment]
Hi Suri, thank you for asking. Still not, but soon I am slowly studying how to make custom extensions for the kit.
