### ISSUE TITLE
Wandering issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1174]
Know why this might be happening? some monsters will teleport on the server and others wont, the client and the server are the same so it shouldn't be moving faster than the server and I'm not using root motion, also the nav is correct. 

I checked on single player and this doesn't happen its only MMO and not all monsters, players are fine too I had a stress test with about 40 players and everything was cool only teleporting monsters.. its strange...... 

any advice is appreciated maybe there some sync settings somewhere that i need to mess with? its not a cheap server its the most expensive one digital ocean offers so its definitely not lagging. Its weird how this doesn't happen in single player at all only MMO and only some monsters not all only certain ones and the same kinds for instances theres a few monsters that will never teleport and its only certain ones that will

https://user-images.githubusercontent.com/78616165/136136974-6e845b23-7158-4fd0-acb0-80f7605c2a56.mp4

https://user-images.githubusercontent.com/78616165/136136979-8798925a-f83f-4c75-a764-1834ddd6312b.mp4

**Comment by Sour-J** [comment]
so i did a ton of tests and tried fixes and the monster doesn't do this once its attacked its normal. its ONLY when wandering. i think something may be wrong with the wander.

**Comment by Sour-J** [comment]
Seems if I match the wander and movement it fixes it for most of my monsters I still had one doing it no matter the speed so I'm going to try and remake that one at a later time

**Comment by insthync** [comment]
Fixed in 1.70
