### ISSUE TITLE
Necessary GM/Moderation Commands

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1178]
Some players break rules, and we need in-game commands to respond accordingly. Here are some very basic moderation commands.

**Teleport to player**: *Either the one issuing the command, or put another player name in.* - `/ttp PlayerA PlayerB`

**Teleport Player**: *Teleports the player to the one issuing the command.* - `/tp PlayerB`

**Kill**: *Kills the person issuing the command. If you get stuck for whatever reason, this is necessary.* - `/kill`

**Warp**: *Warps the one issuing the command to a specific map.* - `/warp Map002`

**Mute**: *Mutes a player. If they send a message in chat, it'll respond "you have been muted".* - `/mute PlayerA 120` *(seconds)*

**Unmute**: *Unmutes a player.* - `/unmute PlayerA`

**Freeze**: *Unable to move.* - `/freeze PlayerB`

**Thaw**: *Reenable movement for a player*. - `/thaw PlayerB`

**Ban**: *Blocks IP of the account of player.* - `/ban PlayerC`

**Unban**: *Allows connection from account*. - `/unban PlayerC`

**Kick**: *Disconnects a player*. - `/kick PlayerD`

Chop and change as you need to, but these are basic moderation commands that Mods and Admins really need for user management in-game.

**Comment by moepi2k** [comment]
very good point, also thought about these commands for gm already

**Comment by insthync** [comment]
In 1.70
```
- Add GM comand: `/warp {map_id}` = Warp to specific map.
- Add GM comand: `/warp_character {name} {map_id} {x} {y} {z}` = Warp to specific character to specific map and position.
- Add GM comand: `/warp_to_character {name}` = Warp to character which its name is `{name}`. (Not working properly yet, players have to be in the same map to warp).
- Add GM comand: `/summon {name}` = Summon character which its name is `{name}`. (Not working properly yet, players have to be in the same map to summon).
- Add GM comand: `/monster {monster_id} {level} {amount}` = Summon monster which its ID is `{monster_id}`, lv. `{level}`, amount `{amount}`.
- Add GM comand: `/kill {name}` = Kill character which its name is `{name}`.
- Add GM comand: `/suicide = Kill` yourself.
- Add GM comand: `/mute {name} {duration}` = Mute character which its name is `{name}` for `{duration}` minutes.
- Add GM comand: `/unmute {name}` = Unmute character which its name is `{name}`.
- Add GM comand: `/ban {name} {duration}` = Ban character's account which its name is `{name}` for `{duration}` days.
- Add GM comand: `/unban {name}` = Unban character's account which its name is `{name}`.
- Add GM comand: `/kick {name}` = Kick character which its name is `{name}`.
```

**Comment by BJPickles** [comment]
> In 1.70
> 
> ```
> - Add GM comand: `/warp {map_id}` = Warp to specific map.
> - Add GM comand: `/warp_character {name} {map_id} {x} {y} {z}` = Warp to specific character to specific map and position.
> - Add GM comand: `/warp_to_character {name}` = Warp to character which its name is `{name}`. (Not working properly yet, players have to be in the same map to warp).
> - Add GM comand: `/summon {name}` = Summon character which its name is `{name}`. (Not working properly yet, players have to be in the same map to summon).
> - Add GM comand: `/monster {monster_id} {level} {amount}` = Summon monster which its ID is `{monster_id}`, lv. `{level}`, amount `{amount}`.
> - Add GM comand: `/kill {name}` = Kill character which its name is `{name}`.
> - Add GM comand: `/suicide = Kill` yourself.
> - Add GM comand: `/mute {name} {duration}` = Mute character which its name is `{name}` for `{duration}` minutes.
> - Add GM comand: `/unmute {name}` = Unmute character which its name is `{name}`.
> - Add GM comand: `/ban {name} {duration}` = Ban character's account which its name is `{name}` for `{duration}` days.
> - Add GM comand: `/unban {name}` = Unban character's account which its name is `{name}`.
> - Add GM comand: `/kick {name}` = Kick character which its name is `{name}`.
> ```

You absolute hero!
