### ISSUE TITLE
Dead Animation Speed - Playable Character Model

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#1179]
Sometimes, when a monster using PlayableCharacterModel dies, the animation doesn't get played immediately, but as you can see below, the **Time** starts, and then after a while, the animation gets played at a very high speed, looking innatural.

![image](https://user-images.githubusercontent.com/55019005/136704526-a5a4bb4d-3a71-4e9f-b160-7293e74a6202.png)

It's happening randomically, sometimes works as expected sometimes not. It doesn't happen with default kit monsters.
The problem is not present using the Animator Character Model.
Any advise to fix this?

**EDIT: The problem probably happens when a monster dies while is playing attacking animation.**

**Comment by insthync** [comment]
I will close this, if it is still occurring, you can reopen this.
