### ISSUE TITLE
I see skills and attributes resets

### ISSUE THREAD

**Issue by Syrus198327** [suriyun-production/mmorpg-kit-docs#118]
Could possibly add a character level reset and have options to ether completely reset all characters stats or keep a % of them after reset

**Comment by insthync** [comment]
Yes, there are attribute reset and skill reset skill item, character level can be added, I think reset all character stats is the same thing with attribute reset, I don't understand how to keep % of them after reset.

**Comment by DimasjkTV** [comment]
> Yes, there are attribute reset and skill reset skill item, character level can be added, I think reset all character stats is the same thing with attribute reset, I don't understand how to keep % of them after reset.

maybe he means dropping attribute and skill points by 1. Like in POE. There you use 1 item that cancels 1 passive skill.

**Comment by Syrus198327** [comment]
What i mean is when play reaches the max lv which is set too 100 he can tier or prestige back to lv 1 keeping all bases stats from points he added from lving so hes a stronger lv 1 then he was when he first started something like that

**Comment by insthync** [comment]
It's reset level, right ?
You can create new potion item which when consume it, it will reset level and exp
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MultiplayerARPG
{
    [CreateAssetMenu(fileName = "Reset Level Potion Item", menuName = "Create GameData/Item/Reset Level Potion Item", order = -4886)]
    public partial class ResetLevelPotionItem : BaseItem, IPotionItem
    {
        public override string TypeTitle
        {
            get { return LanguageManager.GetText(UIItemTypeKeys.UI_ITEM_TYPE_POTION.ToString()); }
        }

        public override ItemType ItemType
        {
            get { return ItemType.Potion; }
        }

        public Buff Buff
        {
            get { return default(Buff); }
        }

        public void UseItem(BaseCharacterEntity characterEntity, short itemIndex, CharacterItem characterItem)
        {
            if (!characterEntity.CanUseItem() || characterItem.level <= 0 || !characterEntity.DecreaseItemsByIndex(itemIndex, 1))
                return;
            characterEntity.Level = 1;
            characterEntity.Exp = 0;
        }

        public bool HasCustomAimControls()
        {
            return false;
        }

        public Vector3? UpdateAimControls(Vector2 aimAxes, params object[] data)
        {
            return null;
        }

        public void FinishAimControls(bool isCancel)
        {

        }
    }
}
```
