### ISSUE TITLE
1.70 Random stats suggestion

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1183]
1. Add a choice of limiting the maximum number of stats on the items for random stats. For example, now we can set 20 or more random attributes etc and there is a chance that all these stats will appear on one item. I also suggest a system of rare items. For example, if 1-2 stats have appeared on an item, then this is a normal item. If 3-4 stats have appeared on an item, then this is a rare item. If the item has 5-6 stats, then it is a legendary item. That is, we limit the maximum number of stats to 6 on an item.
2. Add random stats, now we can only add skills, attributes, damage, armor and resistance

**Comment by DimasjkTV** [comment]
> It has randoming apply rate, not enough?

Just imagine when 30-40 stats appear on one item with a chance.

**Comment by insthync** [comment]
How you would put 30-40 stats?

**Comment by insthync** [comment]
If you have any idea to do it then you can tell me.

**Comment by DimasjkTV** [comment]
https://youtu.be/oaX05ECeT7M

**Comment by DimasjkTV** [comment]
> Hey, you don't have to show any example, I understand it. And I don't get why you always bring other assets is it helpful? or just you just want to brag me, that is it?

I just want to say that in the current state, I can't even imagine how we can use random stats. But I understood your position. I have not yet seen a game on this planet where there would be more than 8 characteristics on a random item with random stats, when there are more than 100 of them in the game.
