### ISSUE TITLE
[Bug]1.70 

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1184]
Hi thank you for the great update, already tested few things.

-> GM Commands.

when u ban a player he will kicked out but he is still able to login again
the command for /monster alsways give me the msg "cannot find the monster" i tried both with id and filename.

/warp_character also not working

**Comment by insthync** [comment]
@moepi2k  It should check login and reject player in `CentralNetworkManager` -> function `HandleRequestUserLogin` -> line 70-79, you may try check that `unbanTime > System.DateTimeOffset.UtcNow.ToUnixTimeSeconds()` or not.

**Comment by moepi2k** [comment]
oh yea though it was scriptable name. problem with prefab name was because i used two words :) works now.

the thing with ban. could it be that it only works with mysql? for testing i use sql and when i use the command it throws me an error.

and for the /warp_character now i dont geht the msg for wrong map or anything. seems command works but player not warping. i tested it in my project, i will check it later on default one. maybe somethings wrong on my side.

one thing. maybe u can help me

i made a new command for change time. like

if (commandKey.Equals(Time))
                {
                    short amount;
                    if (short.TryParse(data[1], out amount))
                        CurrentGameInstance.DayNightTimeUpdater.SetTimeOfDay(amount);
                }

it works well, problem is it only change time in current map in mmo. so can you lead me how to change time on all maps at same time?

best regards and thank you for this great kit again :)

**Comment by moepi2k** [comment]
ok cool 1.70c fixed it :)

but the /warp_to_character seems still bugged. tested on fresh project
https://gyazo.com/6af4b2ec0f0d1e3144ec9bb7c0c82f87 :/

do you have any idea for my custom time GM command above to call it on other map server also?
