### ISSUE TITLE
bug monster attack animation

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1185]
![image](https://user-images.githubusercontent.com/56885137/137391218-cd37585e-ed25-412e-ae3c-817154f94717.png)

when the monster will attack the player, it does not perform the attack animation and generates this error every time the monster attacks

**Comment by insthync** [comment]
I found the source of issues

In `AnimationPlayableBehaviour` class, add 
```
            if (avatarMask == null)
                avatarMask = new AvatarMask();
```
at line `524`

![Screenshot_715](https://user-images.githubusercontent.com/2697550/137433362-89c638a8-275c-4357-b450-eb993710b030.png)
