### ISSUE TITLE
Version 1.70-1.70c Fps situtation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1187]
Fresh versions. Tested on 1.70 and 1.70c. Single player.
FPS decreases over time. For example initially I have 65-70 fps. In a minute it's already 30-40.
https://youtu.be/6edMq-S3Q0A
Also the same situation in game menu
![image](https://user-images.githubusercontent.com/47291794/137495661-57affa23-cc1c-4e1a-b529-6f736d6c52d8.png)
![image](https://user-images.githubusercontent.com/47291794/137495693-9de13fe0-1673-4603-b736-d53f110d88d6.png)
Seems like somthing wrong with character.
https://youtu.be/oM9csG5__0Y

**Comment by insthync** [comment]
The source of problem might be `Character Pitch IK` component, if you want to test it, you may remove it from character prefab then test it.

**Comment by DimasjkTV** [comment]
> Fixed, I will release next update in .. maybe next 2 hours

By the way. No random stats
![image](https://user-images.githubusercontent.com/47291794/137506817-9f8bd62f-6e58-4bf0-ad14-a7ead2227efb.png)
Or I misunderstood this:
![image](https://user-images.githubusercontent.com/47291794/137506970-a7ac23f0-5a44-4e4f-be1a-317ec5b171e2.png)
