### ISSUE TITLE
Supports to change the skinned mesh renderer on the character? 

### ISSUE THREAD

**Issue by lundgren84** [suriyun-production/mmorpg-kit-docs#119]
Hi! My characters is build up with one skinned mesh renderer  containing clothes and gender, So when i change armor i want to change that. 

It dont work so whell with the "simple-controller" but when i use the "advance-controller" it works better, exept on character creation when toggeling bettwen class types the animation sometimes freezes and when i start game it stats in freeze state so i need to un-equip and equip armor to make the animations run again.

Almost like it havent got the right skinned mesh renderer in start

**Video in bug-report channel**
Search in discord with this id
4e314564-fce9-4a29-99aa-e6f68a9e2d2b

**Comment by Syrus198327** [comment]
You have to put the skinned mesh part only with the root for it to animate right that happened to me also. So its it the body part for chest it should be that part as the parent and the root as the child thats how i got it to work.

**Comment by lundgren84** [comment]
Thats how i have it. And its not all times.

**Comment by insthync** [comment]
Okay, I will check it

**Comment by insthync** [comment]
You use CharacterModel or AnimatorCharacterModel

**Comment by insthync** [comment]
I don't know how you setup it, for me I make character model based on `Naked Male White` / `Naked Female White`, then set its `Base` to `Skinned Mesh Renderer` field in `Animator Character Data` and also set `Base` to equipment container for armor item
![Screenshot_148](https://user-images.githubusercontent.com/2697550/67903459-38ed6f80-fb9e-11e9-9ac7-964c28e1e743.png)

For equipment model, I just remove `Animator` component from its root then make it as prefab, then set it to item
![Screenshot_149](https://user-images.githubusercontent.com/2697550/67903553-7225df80-fb9e-11e9-952e-1743c3ac0fd4.png)
![Screenshot_150](https://user-images.githubusercontent.com/2697550/67903588-8d90ea80-fb9e-11e9-8883-618cb1a3828a.png)

**Comment by poaq** [comment]
What if you have more than one skinned mesh not just base? for example head, torso, gloves, legs, shoe ?

**Comment by insthync** [comment]
> What if you have more than one skinned mesh not just base? for example head, torso, gloves, legs, shoe ?

Suggest to do like this https://www.youtube.com/watch?v=K1x7ZhGFhqw

I actually made the way to setup it, you just set skinned mesh as default model then when equip item it will find skinned mesh from default model to apply bones and root bone to equipping item mesh.

**Comment by insthync** [comment]
Default model I mentioned is: 
![Screenshot_35](https://user-images.githubusercontent.com/2697550/92302720-7da11e80-ef98-11ea-9495-10b79786022e.png)
