### ISSUE TITLE
Secure Websocket (WSS) over HTTPS (not working otherwise with insecure connection warning)

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1194]
Hi, when running using websocket (webgl) from a https website, it shows a warning and error about websocket construct failing due to insecure connection not being allowed over https.  

The website/webgl is on a https domain and considering how https and ssl is now becoming kind of a requirement for websites, it will be great to make the websocket (server) run on secure websocket as well, otherwise webgl client cannot connect to it.  

Exact error being:  
```failed to construct websocket an insecure websocket connection may not be initiated over https```

I  changed ws:// to wss:// in WebSocketTransport.cs  

```
public bool StartClient(string address, int port)
        {
            if (IsClientStarted)
                return false;
            dirtyIsConnected = false;
            client = new WebSocket(new System.Uri("wss://" + address + ":" + port));
            client.Connect();
            return true;
        }
```

But does not seem to work

**Comment by shubhank008** [comment]
I think the server also needs to be started with/in TLS/SSL mode  

```
       public bool StartServer(int port, int maxConnections)
        {
#if !UNITY_WEBGL || UNITY_EDITOR
            if (IsServerStarted)
                return false;
            ServerMaxConnections = maxConnections;
            serverPeers.Clear();
            server = new WebSocketServer(port);
            server.AddWebSocketService<WebSocketServerBehavior>("/", (behavior) =>
            {
                tempConnectionId = nextConnectionId++;
                behavior.Initialize(tempConnectionId, serverEventQueue, serverPeers);
            });
            server.Start();
            return true;
#else
            return false;
#endif
        }
```

**Comment by insthync** [comment]
If you still have issues, you can create a new one or reopen this.
