### ISSUE TITLE
Problems with importing the kit in unity version 2021.2.0b16

### ISSUE THREAD

**Issue by aggaton** [suriyun-production/mmorpg-kit-docs#1199]
Hi,

I wanted to try out version 2021.10b16 of unity since it supposedly have removed the shader limits which used to be 384 (from 256) in the past, however I ran into compile errors for the ZString plugin, I get a ton of these errors now (I have downloaded version 1.70e of the kit, did the same in version 1.69f). I am  guessing this is due to .NET being updated to 4.8 in unity 2021.2

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZString\FormatHelper.cs(96,95): error CS0433: The type 'StandardFormat' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZString\EnumUtil.cs(48,51): error CS0433: The type 'Span<T>' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZString\EnumUtil.cs(48,85): error CS0433: The type 'StandardFormat' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZString\FormatHelper.cs(128,108): error CS0433: The type 'StandardFormat' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZString\FastNumberWriter.cs(11,42): error CS0433: The type 'Span<T>' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZString\FormatHelper.cs(97,35): error CS0433: The type 'IBufferWriter<T>' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by aggaton** [comment]
I was able to get the editor past above issue, by renaming the files System,Memory and System.Buffers in the Core/LiteNetLibManager/Plugins directory and installing the Nuget 5.0 version of Microsoft.Bcl.AsyncInterfaces and replacing this file in that same directory. It's a hack, but made the errors go away. Don't know if it will actually work during runtime.

**Comment by gambit-monkey** [comment]
Insthync there is still an ambiguity error with the Microsoft.Bcl.AsyncInterfaces.dll and mscorlib in the 2021.2 version of Unity.

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

**Comment by shubhank008** [comment]
@insthync although that fixes the issue with those 3 files, it still leaves the error with Microsoft.Bcl.AsyncInterfaces as stated by @gambit-monkey
