### ISSUE TITLE
Falling through mesh

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#120]
Im using a Terrain with meshes on it to make my game map
and using Procedural world to Stream my map in Sectors 
so my meshes are not static on login they are spawned but the player spawns before the meshes do and falls through them... how can i make the player hold his position untill map is fully loaded.
been trying to find where character gets instantiated too but cant find it

Like when u create a new character i added a Collidor under the mesh on the location u spawn so it doesnt fall but i cant do this for the whole map lol

https://www.youtube.com/watch?v=5QfZzA5dVck&feature=youtu.be

**Comment by insthync** [comment]
Okay, I will add an option to validate that it can spawn players or not.

**Comment by Callepo** [comment]
if code not much can u share here so i add to project? and thank you

**Comment by insthync** [comment]
Added to 1.50b
