### ISSUE TITLE
HitOnlySelectedTarget and AimAtCursorController

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1208]
Hi,

i noticed a strange behaviour on the AimAtCursorsController when using HitOnlySelectedTarget for WeaponTypes.
i tried to debug it and checked the Damage.cs script where it make the checks.

https://gyazo.com/83b745f3915d7849aad8d7da5eb837ef

i thought this line 
bool hasSelectedTarget = attacker.TryGetTargetEntity(out selectedTarget);
checks what enemy you have in target when hovering mouse over it (UITargetDamageableHp appeard)

but it seems its not. because its hard to attack the right enemy when for example 5 enemies are around you. it took not exactly the one you are targeting. i not checked on fresh project with default controller. but could it be that this check is meant taking an enemy in target with the "FindEnemy" command?

p.s i checked default controller and it is as i assumed it. selectedTarget only works with defaultController but not with AimAtCursorController.

can you maye check it what need to be changed? 

i would appreciate it very much :)

**Comment by LordPhrozen** [comment]
IS *this* why my PvP isnt working. goodness. 

I run the shooter controller in "combat" mode, and all my weapons have the "hit only selected target" unchecked.

**Comment by insthync** [comment]
@LordPhrozen if you have that uncheched it should hit multiple characters, what is the problem?

**Comment by LordPhrozen** [comment]
Yeah I'm not actually sure here. Gonna go through some steps of setting up my kit, right now zero PvP works. melee, or projectiles. map set to PvP, new controler, non-root motion, PvE works fine. pretty confused :D ill open a separate bug report if I can reproduce it on a fresh install.

**Comment by moepi2k** [comment]
What about the issue i mention in first post for the aimatcursor controller?

:P

**Comment by insthync** [comment]
@moepi2k 
Have to change it to send target along with attack message, now it has a separate set target and attack functions so it can set target after attack function called.

**Comment by moepi2k** [comment]
Will you do that? When not can you lead what changes are needed? 

Thank you very much

**Comment by insthync** [comment]
Yes, I am going to do it

**Comment by insthync** [comment]
Fixed

I actually forget to set target before attacking https://github.com/insthync/UnityMultiplayerARPG_AimAtCursorController/commit/14d4f0356f045317bc155c5560c3dcff9487fac0
