### ISSUE TITLE
Hide and teleport

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#121]
Hello, can you add few skill for example, didn't understand how can i add teleport skill, i mean not for target by coordinate x y z, i mean teleport bihind character by skill, for example, i use teleport and it change position of my character by few xyz near me, right left or behind.

About hide skill i have questions too, i need to hide player out of others character for few seconds, but  if i use some skill i alredy stay visible for all again? Visible checker didn't help me with that ?

**Comment by insthync** [comment]
I will make example of that skill types later

**Comment by 1isenok** [comment]
Okey, I'll be waiting

**Comment by insthync** [comment]
Hide skill is done, it will be included in next version. Teleport nearby target character may be finished in next version too.

**Comment by insthync** [comment]
I've implement hide effect in buff, you can set buff to hide character

Try 1.50c
