### ISSUE TITLE
Playable Graphs, Masks

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1210]
i cant seem to get the animations looking properly no matter what option i pick, the feet float of the ground, looks weird, glide around etc. animation mask is full body + ik, and all of that. 

am i missing something? or some up with the graphs ? 

https://gyazo.com/e9f599a74924e49b672afd2f16acc234

**Comment by Callepo** [comment]
this wasnt resolved in the new version

**Comment by Callepo** [comment]
The FootIK true is what fixes it 
![image](https://user-images.githubusercontent.com/7702658/140318000-8a2598b8-f1c5-478c-85aa-e8aece0ed78a.png)

**Comment by insthync** [comment]
I will make it configurable

**Comment by insthync** [comment]
In 1.71f

- Add `applyFootIk` and `applyPlayableIk` to animation state settings for playable character model.
