### ISSUE TITLE
Walk key name?

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1212]
May seem like a silly question but how do you enable the character to walk?

I've set up in GameInstance input setting manager:
![image](https://user-images.githubusercontent.com/48354382/138591915-caae95a2-91cb-450b-9a5c-16ef66b939ad.png)

However this does nothing.  All animations have been setup in the character as well, so is the Key Name different?

**Comment by insthync** [comment]
Added in 1.71

**Comment by BJPickles** [comment]
Thanks for adding this, just tested out. Doesn't currently work for the 'shooter' controller, but does work for the regular controller.

**Comment by BJPickles** [comment]
Thanks for adding this, just tested out. **Doesn't currently work for the 'shooter' controller**, but does work for the regular controller @insthync 
(Not sure if you'll get notified or not)

**Comment by insthync** [comment]
Try set `walkActiveMode` setting in 
![Screenshot_753](https://user-images.githubusercontent.com/2697550/139915375-dd28bbcc-9e70-47ac-bb46-66c9778b0698.png)

**Comment by BJPickles** [comment]
Oh lol, I am so sorry I didn't even see that! Yeah works perfectly! Thank you!
