### ISSUE TITLE
Item Features ...

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1215]
Hello guys,

i'm a customer and have some request about item features. I would like to talk to you directly about implementation ideas.
The problem is, I had to change the packages code and would run into troubles with updating ...
I did not find any forum to talk about it?

I would also like to see any manual or help to insert 3d graphics for example made with blender. I created some sword and had many troubles with positioning and sizing...

**Comment by Pymann** [comment]
@insthync yes I tried this, but it took me 20 game launches, until size and position was acceptable, isnt there any formula?!

Well, I'm asking if the work can be done by itself ... =)

I will checkout this community.
But all in all I need more features in the C# code...

**Comment by insthync** [comment]
You actually can drag weapon prefab into character slot in edit scene, you may create empty object as parent for the weapon model before adjust transform and save prefab.

**Comment by Pymann** [comment]
This is helpful. thank you.
