### ISSUE TITLE
[BUG] Character pitch ik bugged with playable character

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1217]
sometimes when i login , that happen
![1](https://user-images.githubusercontent.com/64667641/138984296-5dc90a2b-7088-4a97-8e85-93740c5185a5.jpg)
when i relog again it comes fine as it should
![2](https://user-images.githubusercontent.com/64667641/138984353-32e6580f-d432-490c-ab36-9dfdd6874327.jpg)
thats my pitch ik
![3](https://user-images.githubusercontent.com/64667641/138984456-ea653019-faeb-42a2-9247-550726ef0560.jpg)

**Comment by insthync** [comment]
Please try 1.71, if it's still occurring, you can reopen this.
