### ISSUE TITLE
Building ExtraData

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1219]
I noticed Buildings have an ExtraData value, but this doesnt get saved in the mysql or sqlite db, 
But it does get saved in lan with surrogates etc.

is this intentional? 
Example a campfire which was on, when u reboot server it goes back to default aka off state, this is cuase the data was never send to the db, but only saved in memory at runtime.

Was this A oversight? or intentional?

**Comment by insthync** [comment]
Did it in 1.71
