### ISSUE TITLE
cannot equip Armor Item

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1225]
I created an armor item, but when trying to equip it, this error appears.

![image](https://user-images.githubusercontent.com/56885137/139467686-0d653e78-8d2b-4f4c-bca2-1e813baf9d28.png)

This is the item I created
![image](https://user-images.githubusercontent.com/56885137/139467305-1d1b7117-c7c4-4498-91e7-10821a505e2a.png)

this is the standard item (this one I can equip)
![image](https://user-images.githubusercontent.com/56885137/139467517-2e1fabcd-0dfb-4174-9d09-090ae735f59e.png)

**Comment by moepi2k** [comment]
You need to set equip position on the scriptable

**Comment by juniormagalhaes** [comment]
> You need to set equip position on the scriptable

what do you mean?

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/139536911-d3030988-b742-494b-a449-87dcae35bc2a.png)

This?

**Comment by DimasjkTV** [comment]
> ![image](https://user-images.githubusercontent.com/56885137/139536911-d3030988-b742-494b-a449-87dcae35bc2a.png)
> 
> This?

did u add this item to game data?
