### ISSUE TITLE
GM commands question

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1226]
Is there anyway to grant gm without editing the database like a cvar file granting permission or maybe a password that adds gm I'm working with a big server hosting company for my game trying to make private servers so far it's successful just they don't give customers SQLite access or console access so we're trying to figure out a way to give GM commands without using your method.

**Comment by insthync** [comment]
You may try change codes in `DefaultGMCommands` -> `CanUseGMCommand` function

**Comment by Sour-J** [comment]
thanks
