### ISSUE TITLE
I got an issue

### ISSUE THREAD

**Issue by kissstar11** [suriyun-production/mmorpg-kit-docs#1228]
I got this issue only in the Map002_2D(mobile mode) when the player was attacked by the enemies.![image](https://user-images.githubusercontent.com/72058863/139572585-8a043736-7e3e-49bc-8045-460672289367.png)

**Comment by insthync** [comment]
![Screenshot_748](https://user-images.githubusercontent.com/2697550/139580633-9a5ba6e4-8d83-4096-8a8f-638f199b5841.png)

add this line

**Comment by insthync** [comment]
The fix included in 1.71

**Comment by kissstar11** [comment]
> The fix included in 1.71

Thank you so much for the quick response 😀
