### ISSUE TITLE
1.70g "Reports of bulding not working correctly"

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1229]
Checking with Neomis it would seem that for his custom building parts its working correctly, but reports suggest the demo is not working correctly. This leads me to believe their might be an issue with the parts themselves, as Neomis's report suggests the code itself is fine. You might want to look over it just in case.

Thanks for your time.

**Comment by Fallen-Entertainment** [comment]
Neomis told me he thinks its to do with building grid size. He says he is gonna fix it, you might want to contact him.

**Comment by insthync** [comment]
Not sure this is the same issues ? 
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1222

**Comment by moepi2k** [comment]
exactly that one :)

**Comment by insthync** [comment]
The fix included in 1.71
