### ISSUE TITLE
Suggestion: Inventory

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1230]
May be this is only for inventory Slot system.
Separate inventory. For example, the ability to choose 50 slots for armors/weapons categories, 50 slots for resources categorie, 50 slots for potions categories, etc. We have categories, but they use the entire inventory.

In my game, I divided my inventory into categories and chose the "Slots" inventory system. But since the inventory is divided into categories, the slots are gone. It seems that they are, but they are invisible. For example, if I drop an item from the center of the list and pick up a new item, then the new item goes into the invisible slot from where I dropped the old item. Items picked up are not returned to the end of the list. (see video)
https://youtu.be/c7HiiUyPxW4

![image](https://user-images.githubusercontent.com/47291794/139675202-5aa450f1-2335-4411-ace0-22f0b496cfae.png)
![image](https://user-images.githubusercontent.com/47291794/139675296-2aef2594-ecc6-4fca-a4aa-7bcb62e8bcd5.png)

If I remove the categories, then the empty slots will be visible.

**Comment by LordPhrozen** [comment]
Its more and more common to have games that use this sort of inventory filtering system. does your system filter by the item in the slot **AND** empty? Cause you'll obviously want the logic to say show items that match AND empty.
