### ISSUE TITLE
Version for UE4

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1231]
I've already asked if there are plans for a version for UE4. That was at the end of May and then you said it might be in two months, now it's been more than five months... is the work being done?

**Comment by insthync** [comment]
Yes it is being done,

**Comment by Fallen-Entertainment** [comment]
Considering their was no promise for UE4 support when you bought the kit the very fact that hes doing it at all should be enough. If he takes a year that would be great. Considering how much work all of this is, gratitude and patience is something we can all afford.
