### ISSUE TITLE
BUG 1.71: Crafting

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1232]
![image](https://user-images.githubusercontent.com/47291794/139694178-763fc514-082d-4301-8f06-c91b0a18889a.png)
![image](https://user-images.githubusercontent.com/47291794/139694401-b627f1d6-603b-42e3-b744-992396d11ee9.png)

This happens when the character has the necessary resources to craft.

**Comment by insthync** [comment]
Please try redownload the package again, I was replace it with the new one around 6 hours ago, I will check it tomorrow.

**Comment by DimasjkTV** [comment]
> Please try redownload the package again, I was replace it with the new one around 6 hours ago, I will check it tomorrow.

yes it works. Were these changes in the code?

**Comment by insthync** [comment]
UI Item Amounts

**Comment by insthync** [comment]
Find .currencies
