### ISSUE TITLE
Few situtations with animations.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1233]
I use this 
![image](https://user-images.githubusercontent.com/47291794/139793524-760f58aa-7ba0-4762-be4d-317b032df112.png)

1. The monster chases the character during the attack. (look at the video)
https://youtu.be/BnzAyLaTb2c

2. If I add the "Hurt" animation for the monster, then we can see that the monster cannot complete the animation of its hits normally, as the character and his summoned creatures are knocking it down. As a result, we receive damage from the monster, but we cannot see the animation. (look at the video)
https://youtu.be/WxQ0jNPpEa0

3. But, if we remove the"Hurt" animation from the monster, we will get the next unpleasant moment. The death animation does not interfere with the monster's attack animation. (look at the video)
https://youtu.be/tCH0XEXe_ZM
Normal death animation:
https://youtu.be/6bsr_kRzqvU

In older versions, I could remove the "Hurt" animation from the animator controller and there were no such problems.
If I understand correctly now we are not using the animator controller? Or I just didn't find where to choose it now for PlayableCharacterModel.

**Comment by insthync** [comment]
1. Set this
![Screenshot_750](https://user-images.githubusercontent.com/2697550/139798523-0024d8ec-ba0c-4018-9393-c0cde6bd7a00.png)

**Comment by insthync** [comment]
2. It should not do that, I actually add condition to don't play hurt animation while attacking
3. 
![Screenshot_751](https://user-images.githubusercontent.com/2697550/139799946-7435a679-d14d-49b1-a92a-cfa097696386.png)

**Comment by insthync** [comment]
3. Try import this

[MMORPG_KIT-StopActionAnimationWhenDead.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7458418/MMORPG_KIT-StopActionAnimationWhenDead.zip)

**Comment by DimasjkTV** [comment]
> 1. Set this
>    ![Screenshot_750](https://user-images.githubusercontent.com/2697550/139798523-0024d8ec-ba0c-4018-9393-c0cde6bd7a00.png)

![image](https://user-images.githubusercontent.com/47291794/139801692-6c0420dc-a61d-41a9-8bed-93daceab145e.png)
monster in video has this and all my monsters have 0

**Comment by DimasjkTV** [comment]
> 1. Try import this
> 
> [MMORPG_KIT-StopActionAnimationWhenDead.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7458418/MMORPG_KIT-StopActionAnimationWhenDead.zip)

hm 
![image](https://user-images.githubusercontent.com/47291794/139802050-f70ce666-7e04-4f25-993c-1ace4223d938.png)

**Comment by DimasjkTV** [comment]
> 1. Try import this
> 
> [MMORPG_KIT-StopActionAnimationWhenDead.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7458418/MMORPG_KIT-StopActionAnimationWhenDead.zip)

Didn't help, but I think this archive with the script is unchanged. Not sure.

**Comment by insthync** [comment]
2 / 3.
[MMORPG_KIT-StopActionAnimationWhenDead.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7458678/MMORPG_KIT-StopActionAnimationWhenDead.zip)

**Comment by DimasjkTV** [comment]
> 2 / 3. [MMORPG_KIT-StopActionAnimationWhenDead.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7458678/MMORPG_KIT-StopActionAnimationWhenDead.zip)

2. Fixed
3. Not fixed

**Comment by insthync** [comment]
[MMORPG_KIT-StopActionAnimationWhenDead.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7458753/MMORPG_KIT-StopActionAnimationWhenDead.zip)

**Comment by DimasjkTV** [comment]
> [MMORPG_KIT-StopActionAnimationWhenDead.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7458753/MMORPG_KIT-StopActionAnimationWhenDead.zip)

Fixed. Thank You!
