### ISSUE TITLE
UI Gauge Slider Support Request

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1236]
Currently only image gauge is supported as seen below.
![image](https://user-images.githubusercontent.com/48354382/140062541-6ab85389-f2fe-4a45-8ee4-93cafc5db9e8.png)

Request for sliders to be supported.
![Unity_i7cQL7iNSA](https://user-images.githubusercontent.com/48354382/140063141-95e2adcd-d8e2-4dde-b40d-dc23d14b919d.png)

The primary reason for this is I don't always use sprites for the fill rect, but an image always requires one.

**Comment by insthync** [comment]
Okay, I will add the option

**Comment by BJPickles** [comment]
> Okay, I will add the option

Thanks, Suri!

**Comment by insthync** [comment]
Added in 1.71b
