### ISSUE TITLE
Issue: Resistance texts

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1237]
In which script can i change the display of inserted stones/gems? 
Or a piece of code for this has not been added? Because the other stats in the inserted stones/gems automatically look like stats on the item.
I'm talking about decimal places in numbers.
![image](https://user-images.githubusercontent.com/47291794/140078427-3f82ddf3-05f2-4c6c-a1d4-ef3f4293962c.png)
![image](https://user-images.githubusercontent.com/47291794/140078568-6334912b-2377-4c20-8911-9f501eef153c.png)
![image](https://user-images.githubusercontent.com/47291794/140078941-3b1417f7-ce87-43dc-bd19-0612a5c63b64.png)

**Comment by insthync** [comment]
In `UIBaseEquipmentBonus`

**Comment by DimasjkTV** [comment]
> UIBaseEquipmentBonus

Thank you!
This was empty
![image](https://user-images.githubusercontent.com/47291794/140270457-c5ac707d-ce4b-43cb-becc-30f53adf5105.png)
