### ISSUE TITLE
Gm Commands Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1238]
Giveitem command has a code error in it.
![image](https://user-images.githubusercontent.com/7702658/140164822-3301dcfe-105a-4cc2-b14e-b3287fec4640.png)

the Data for items should be 2 but in the kits its 1 aka looking for targetcharacter on data[1] and then going to look for items name also on data[1], which keeps giving u the error in game, cant find item. 

its needs to be 2 as showns above

**Comment by insthync** [comment]
I will gix it.

**Comment by insthync** [comment]
Fixed in 1.71b
