### ISSUE TITLE
Job System Question

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1239]
hi, i would like to know if you have any plans to add profession system to the kit.

**Comment by insthync** [comment]
Something like character's class changing or something like crafting mastery, harvest mastery?

**Comment by juniormagalhaes** [comment]
> Which one?
> 
> * Something like character's class changing?
> * Or something like crafting mastery, harvest mastery?

Like something like crafting mastery, harvest mastery.

**Comment by insthync** [comment]
No plan for that yet.

**Comment by juniormagalhaes** [comment]
> No plan for that yet.

but Something like character's class changing have a plan?

**Comment by insthync** [comment]
It actually can be changed anytime (just change `dataId` value), but have to implement it via NPC.

**Comment by LordPhrozen** [comment]
What about allowing characters to have more than 1 class? 
Could easily make crafting.gathering professions into a second kind of class, and do it that way?

I'm also looking for multiclass options, and this would probably address both our use cases
