### ISSUE TITLE
BUG? monster situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#124]
I noticed that aggro monsters works differently in single player and in MMO mode
in a single player game you can take a small step during a monster attack. After that, the monster runs away from you. See video
[20191101171251.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3798263/20191101171251.zip)

**Comment by insthync** [comment]
That monster have skills ?

**Comment by DimasjkTV** [comment]
> That monster have skills ?

no. 
I forgot to say that those monsters that have a skill do not attack the character. Use only skill. So it was at 1.50

**Comment by DimasjkTV** [comment]
there was another mistake with skills. Monsters used only the first skill on their list.

**Comment by DimasjkTV** [comment]
[20191101173335.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3798323/20191101173335.zip)
monster with skill

**Comment by DimasjkTV** [comment]
> That monster have skills ?

Summoned creatures attack enemies only if the character attacks. Maybe this is due to the situation of the monsters.

**Comment by DimasjkTV** [comment]
- Can you add the ability to add several drop lists to monsters at the same time? This may affect game updates. For example, in the first patch, we released 30 items and in order not to add them to the old drop lists, we can create a new drop list and add it. It makes the task a little easier.

**Comment by DimasjkTV** [comment]
> That monster have skills ?

if during the animation of a monster hit the character goes beyond his attack range, the monster runs away from us. Therefore, melee monsters always run away if we step back a little
![image](https://user-images.githubusercontent.com/47291794/70396049-33ddd480-1a16-11ea-8657-6a9088806330.png)
![image](https://user-images.githubusercontent.com/47291794/70396052-4526e100-1a16-11ea-9526-dc9ff95187c8.png)

**Comment by DimasjkTV** [comment]
1 video has 2 hit distance
2 video has 15 hit distance
[1.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3937148/1.zip)
[Uploading 2.zip…]()

**Comment by insthync** [comment]
Try version 1.51, I've rework on `MonsterActivityComponent`, hope it can fixes an issues

**Comment by DimasjkTV** [comment]
> Try version 1.51, I've rework on `MonsterActivityComponent`, hope it can fixes an issues

Ситуация с монстрами не изменилась. Они продолжают выходить из боя. Похоже, что призванные существа стали работать лучше.

**Comment by DimasjkTV** [comment]
> Try version 1.51, I've rework on `MonsterActivityComponent`, hope it can fixes an issues

I like in the new version that monsters now choose our summoned creatures as targets.

**Comment by insthync** [comment]
How about `Visual Range` in `Monster Character` game data settings?, is it more than attack distance ?

**Comment by DimasjkTV** [comment]
> How about `Visual Range` in `Monster Character` game data settings?, is it more than attack distance ?

Yes Visual Range 8, attack range 2

**Comment by DimasjkTV** [comment]
Video made here on fresh project 1.51. 
![image](https://user-images.githubusercontent.com/47291794/71084560-9d907800-21a6-11ea-83b4-59086fd50c01.png)

**Comment by insthync** [comment]
Not sure that the character is in safe zone?, then monster stop attacking.

**Comment by DimasjkTV** [comment]
> Not sure that the character is in safe zone?, then monster stop attacking.

Checked, my save zone has been deleted

**Comment by DimasjkTV** [comment]
[1.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3978320/1.zip)

**Comment by insthync** [comment]
[MMORPGKIT-FixingMonsterStopMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3984535/MMORPGKIT-FixingMonsterStopMovement.zip)
Try this package.

**Comment by DimasjkTV** [comment]
> [MMORPGKIT-FixingMonsterStopMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3984535/MMORPGKIT-FixingMonsterStopMovement.zip)
> Try this package.

Works great!
