### ISSUE TITLE
About the Language

### ISSUE THREAD

**Issue by kissstar11** [suriyun-production/mmorpg-kit-docs#1240]
Hi Suri, it may be a novice question but how can I set a local key to a text? For example I want to translate the TextLable of the Stats Window. Should I add a local key to it? or what should be the best process to do it？
Thank you and sorry for asking such novice question
![image](https://user-images.githubusercontent.com/72058863/140482329-416d2bcc-4fe0-4e1a-963a-643900255bdc.jpeg)

**Comment by insthync** [comment]
You can use `Text Setter By Locale Key` component
![Screenshot_759](https://user-images.githubusercontent.com/2697550/141115152-174fe1ae-5741-4e13-8bf3-4f0af48ccab9.png)

**Comment by kissstar11** [comment]
> You can use `Text Setter By Locale Key` component
> 
> ![Screenshot_759](https://user-images.githubusercontent.com/2697550/141115152-174fe1ae-5741-4e13-8bf3-4f0af48ccab9.png)
> 
> 
> 
> 

Thank you for the help. I tested it showing in the picture,but It seems don't work,did I miss something?
![image](https://user-images.githubusercontent.com/72058863/141612959-83d4df26-5605-4fc6-b22d-65f3f230d395.jpeg)

**Comment by insthync** [comment]
![Screenshot_770](https://user-images.githubusercontent.com/2697550/141664676-09630de5-6228-4273-9036-590d513ca9d9.png)

Set text wrapper component here

**Comment by kissstar11** [comment]
> ![Screenshot_770](https://user-images.githubusercontent.com/2697550/141664676-09630de5-6228-4273-9036-590d513ca9d9.png)
> 
> 
> 
> Set text wrapper component here

It works now,thank you for the help.
