### ISSUE TITLE
WarpPortalEntity Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1241]
You cant teleport through a portal if ur on a Vehicle using charactercontroller, cause it turns off the controller to use the one on the bike.

 basically u have to unmount to tp and then get back up which is dumb..
 
 
![image](https://user-images.githubusercontent.com/7702658/140537791-2e2e79bd-9eff-4939-9fda-ff219e6b6c15.png)

This code made it able to tp anyways, cuase the portal still see the players _HitBox which has also Player Tag, so by getting that objects parent i still grab the playerentity and can tp... Maybe u can solve this internally, but this works for now.

**Comment by insthync** [comment]
I will change it to

![Screenshot_755](https://user-images.githubusercontent.com/2697550/140602104-113f3851-49af-4b57-a407-89a732650d91.png)

**Comment by insthync** [comment]
Fixed in 1.71b
