### ISSUE TITLE
Problems when upgrading to 1.71

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#1242]
Hey!
After upgrading to version 1.71, I get the following error:
![1](https://user-images.githubusercontent.com/16080577/140585803-494199ec-3e1a-4762-a642-783816bde561.jpg)

After that, deleted the entire UnityMultiplayerARPG folder and reinstalled.
But there are many messages in the game Animator is not playing an AnimatorController.
At the same time, all characters move normally ...
![2](https://user-images.githubusercontent.com/16080577/140586979-2d51cb4e-7011-4c4a-a874-c9f5a54aa971.jpg)

**Comment by brabaris** [comment]
Each NPC has a message that Can't find `CharacterModelManager`
![3](https://user-images.githubusercontent.com/16080577/140659398-30413391-14d4-4daf-8785-ebe11b6875cd.jpg)

**Comment by insthync** [comment]
Fixed in 1.71b
