### ISSUE TITLE
Quest Rewards

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1243]
I should add:
1. Random rewards. After completing the quest, the player is given a random item.
2. Choice Awards. After completing the quest, the player chooses one of the suggested rewards.

Thanks in advance.

**Comment by juniormagalhaes** [comment]
> I should add:
> 
> 1. Random rewards. After completing the quest, the player is given a random item.
> 2. Choice Awards. After completing the quest, the player chooses one of the suggested rewards.
> 
> Thanks in advance.

would also put random tasks, to use in repeatable quests

**Comment by insthync** [comment]
Done in 1.71e

@juniormagalhaes Create new post.
