### ISSUE TITLE
Top down control in 3D mobile mode

### ISSUE THREAD

**Issue by VEsttas** [suriyun-production/mmorpg-kit-docs#1244]
Hi,how to set the controller to top down mode in the 3D demo(mobile mode)? Just like in the 2D demo 
Thank you

**Comment by Serivatech** [comment]
This one?
https://github.com/insthync/UnityMultiplayerARPG_TopDownController

You need the files in the Prefab folder.
Minimal changes: 
In PlayerCharacterController -> "Gameplay Camera Prefab" you specify the file TopDownGameplayCamera.prefab.
Completely change the controller:
In scene init -> GameInstance -> "Default Controller Prefab" you specify the file TopDownPlayerCharacterController.prefab

**Comment by Serivatech** [comment]
In the last variant there are also files from the scripts folder

**Comment by VEsttas** [comment]
> In the last variant there are also files from the scripts folder

Thank you
