### ISSUE TITLE
Remember me login

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1245]
Hello,

I was wondering if I could buy a feature for the kit I think everyone wouldn't mind having too. Better login:  Remember me [] option for the login along with tab to go down a line and enter button to submit because the current setup is annoying and I don't have the time or skill to figure it out myself haha! if your willing to add it to the kit ill gladly fund your time to add it to the kit no rush, or let me know if you can't and ill find a freelancer. I just think it will add quality of life to the login I had thousands of people play during a beta and that was the #1 complaint.

**Comment by insthync** [comment]
Already did it, in `UIMmoLogin` component you can set reference to toggle component to remember username or remember both username and password.

**Comment by Sour-J** [comment]
Thank you didn't know it was there I appreciate you
