### ISSUE TITLE
pet attacking issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1246]
Having an issue where pets/summons attack your own group but not a guild member? is there an option somewhere for this? thank you

**Comment by insthync** [comment]
Which kind of map info ?
Default or Guildwar?

If it is default, which Pvp Mode?

As I test default with `PVP` mode, it is working properly

**Comment by Sour-J** [comment]
ill check again thank you its default pvp, for some reason my pet skills attack group but not colony ill retry

**Comment by insthync** [comment]
Only skills?

**Comment by Sour-J** [comment]
yeah im not using pet items only skills they attack their own group but they wont hurt guild members.
is there a setting somewhere for this? I have been trying to figure this out for weeks.
Do you have a spot where I can donate to you? I appreciate your time

**Comment by insthync** [comment]
There are ally/enemy checking functions in `MapInfo.cs`, `GuildWarMapInfo.cs` you can check them:
```
        bool IsPlayerAlly(BasePlayerCharacterEntity playerCharacter, EntityInfo targetEntityInfo);
        bool IsMonsterAlly(BaseMonsterCharacterEntity monsterCharacter, EntityInfo targetEntityInfo);
        bool IsPlayerEnemy(BasePlayerCharacterEntity playerCharacter, EntityInfo targetEntityInfo);
        bool IsMonsterEnemy(BaseMonsterCharacterEntity monsterCharacter, EntityInfo targetEntityInfo);
```

If you want to donate me, do it via: https://ko-fi.com/insthync
