### ISSUE TITLE
Negative gold

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1247]
For some odd reason on 1.70g I'm gaining negative gold when killing a monster the monster definitely gives positive gold maybe the newest update fixes this? I can't find out why

**Comment by Sour-J** [comment]
Trying to find out if it's me or a bug thank you

**Comment by insthync** [comment]
How much gold are you adding?

**Comment by insthync** [comment]
Did you set `MonsterCharacter` -> `defaultLevel` more than `1`?

**Comment by Sour-J** [comment]
Only adding small amounts 1-10
Default level is 1 or 0 I think I have to check I'll get back to you thank you!!
