### ISSUE TITLE
Debug Log for Sql C# files?

### ISSUE THREAD

**Issue by sinfulspartan** [suriyun-production/mmorpg-kit-docs#1248]
Is there a way to debug log for the sql files? I have some data that is causing a table to wipe, but I can't tell what format is being sent.
![image](https://user-images.githubusercontent.com/89873705/141041231-f4a35046-5157-4369-aafb-bf94248461c9.png)

**Comment by insthync** [comment]
Try use LiteNetLibManager.Logging.Log("") or LiteNetLibManager.Logging.LogWarning("") or LiteNetLibManager.Logging.LogError("")
