### ISSUE TITLE
What file handles the client listener for sever messages?

### ISSUE THREAD

**Issue by sinfulspartan** [suriyun-production/mmorpg-kit-docs#1249]
I'm trying to figure out where the C# file is that handles the client receiving messages for receiving items from harvesting.
I've added a stat for quality to harvest items and the sever is aware of the number but the client doesn't seem to know about the number and I can't figure out where to even start debugging.

**Comment by insthync** [comment]
It's actually add to character entity 's `nonEquipItems` variable which is sync list variable (don't know that you ever use UNET or not sync list concept of this project is like UNET's sync list).

But when it's going to add to player inventory it will do in `HarvestableEntity.cs` -> `ApplyReceiveDamage` line 163 (`attackerCharacter.IncreaseItems(CharacterItem.Create(itemDataId, 1, itemAmount))`)

**Comment by sinfulspartan** [comment]
I'm not familiar with UNET but I assume it has something to do with this:
![image](https://user-images.githubusercontent.com/89873705/141222645-6f1defee-66ab-4112-a316-767b5334b6f0.png)

**Comment by insthync** [comment]
Are you going to add new variable to character item ?

**Comment by sinfulspartan** [comment]
Yes. I added a new variable. I had to update this as it was causing my
database error.
———————
Shane Mummaw
General Adjuster, CGA
Insurance Appraisal & Mediation
561-235-8762


ᐧ

**Comment by insthync** [comment]
So, you have to add codes in serialize and deserialize function.
