### ISSUE TITLE
Damage text

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#125]
![image](https://user-images.githubusercontent.com/47291794/68045449-9262b500-fcea-11e9-86e8-4afdb6d84bdf.png)

How to remove the second plus now? Must be + 10-14

**Comment by insthync** [comment]
Changes in `UIDamageElementAmounts.cs`

From line 93 to
```
                    if (isBonus)
                        tempMinValue = tempAmount.min.ToBonusString("N0");
                    else
                        tempMinValue = tempAmount.min.ToString("N0");
                    tempMaxValue = tempAmount.max.ToString("N0");
```

**Comment by DimasjkTV** [comment]
> UIDamageElementAmounts

How can i remove "+" from "Armor"? 
![image](https://user-images.githubusercontent.com/47291794/68064252-4f283680-fd2a-11e9-8a12-986403384715.png)

**Comment by insthync** [comment]
Now, there is main armor setting in item data: 
![Screenshot_159](https://user-images.githubusercontent.com/2697550/68068590-f89e1500-fd88-11e9-92c1-310c6840930c.png)

But you will have to set text component in item dialog
![Screenshot_160](https://user-images.githubusercontent.com/2697550/68068611-2b480d80-fd89-11e9-83f2-b5701172549c.png)

I think the easiest way for you is to changes code in `UICharacterItem.cs`  by
set `uiIncreaseArmors.isBonus = true` to `uiIncreaseArmors.isBonus = false` at line 557

**Comment by DimasjkTV** [comment]
> uiIncreaseArmors.isBonus = false
Nice! it works. thank you=)
![image](https://user-images.githubusercontent.com/47291794/68069557-802c5980-fd72-11e9-8793-3ae1516cf422.png)

**Comment by DimasjkTV** [comment]
Hello! Is it possible to add a function - after logout the character appears in Town. Or is there such a function already?

**Comment by insthync** [comment]
Just don't save current position right ?

**Comment by DimasjkTV** [comment]
> Just don't save current position right ?

i think yes

**Comment by insthync** [comment]
It will be included in next version

**Comment by insthync** [comment]
Add `currentPositionSaveMode` config to `GameInstance`, you can set it to `UseRespawnPosition` to make it save character current position as respawn position, not current position. So when enter game it will load respawn position, not last character position.

**Comment by DimasjkTV** [comment]
> Add `currentPositionSaveMode` config to `GameInstance`, you can set it to `UseRespawnPosition` to make it save character current position as respawn position, not current position. So when enter game it will load respawn position, not last character position.

Extra plus if a set of items gives us bonuses in the form of damage.
![image](https://user-images.githubusercontent.com/47291794/71090721-bbfd7000-21b4-11ea-8049-a2942fb7717c.png)

No pluses on ordinary items (it was removed earlier).
![image](https://user-images.githubusercontent.com/47291794/71090865-0383fc00-21b5-11ea-843c-639bd6b0fbd4.png)

**Comment by insthync** [comment]
Please open new issues post.

**Comment by DimasjkTV** [comment]
> Please open new issues post.

Sure tomorrow
