### ISSUE TITLE
New update MMO question

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1250]
With the newest update the MMO servers lag a lot and with the older one before that it didn't lag I am using the same build. Maybe it's just me 🤣 not sure I can't even attack monsters it's delayed but single player works perfectly

**Comment by insthync** [comment]
Is there any error logging?

**Comment by Sour-J** [comment]
Nevermind resolved it was because client_build protection was on the server build by mistake I'm sorry
