### ISSUE TITLE
Something wrong sometimes with character prefab [ bug ]

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1254]
sometimes when i login that happen to character
![1](https://user-images.githubusercontent.com/64667641/141299379-7e3592c4-4fa6-4cdb-916e-3b36d6147515.jpg)
it comes fine when i re login 
![2](https://user-images.githubusercontent.com/64667641/141299432-05da5995-4591-4948-bf69-25dfebb7d418.jpg)
im using unity 2021.1.15f1

**Comment by Sour-J** [comment]
is IK pitch enabled on the character?

**Comment by RunOrDi3** [comment]
@Sour-J  yes

**Comment by Sour-J** [comment]
Try to uncheck the ik pitch script and see if that fixes it inexperienced something similar before not sure if it's the same issue

**Comment by insthync** [comment]
Character Pitch IK issues were fixed, it will be included in next version
