### ISSUE TITLE
The skill’s tooltip issue

### ISSUE THREAD

**Issue by VEsttas** [suriyun-production/mmorpg-kit-docs#1258]
Hello!
1.In the 2D demo (mobile),the tooltip of the skill can not correctly show the %number of the weapon damage infliction as I set in the "bash"skill.
2.How to show the skill description in the skill tooltip ?

Thank you 

![image](https://user-images.githubusercontent.com/93812849/141602028-4b9cf0b8-4024-4d66-9d5f-92bc0fb23201.jpeg)

![image](https://user-images.githubusercontent.com/93812849/141602035-1e41fc1e-a835-44df-9147-d33d50b38023.jpeg)

**Comment by insthync** [comment]
Fixed in 1.71b
