### ISSUE TITLE
No construction area

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1259]
hello, I just bought you x7 coffee's thank you for your time!

 one question: What collider is for the no construction zone? I have a trigger sphere collider on a game object with the no construction script and players can still build within the sphere. I'm trying to block a main town. 

Thanks I appreciate you.

**Comment by insthync** [comment]
Try add kinematic rigidbody to the area to make it able to trigger

**Comment by insthync** [comment]
As I test, it work properly, not sure how you expected it to work, but how it works is: it will allow players to press hot key to start constructing the building but it won't allow constructing if the building is inside no construction area.

**Comment by Sour-J** [comment]
thanks ill try that

**Comment by Sour-J** [comment]
Strange its still not working for me I have a game object with no construction script a sphere collider with trigger on and a rigid body that's marked kinematic and players can still build in that zone :(
