### ISSUE TITLE
1.50b BUG Icon Hotkey Assigner

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#126]
The item and skill icon does not appear after we select a skill. In mobile
![image](https://user-images.githubusercontent.com/47291794/68061373-9526cf80-fd15-11e9-8853-9496d50106d7.png)

**Comment by DimasjkTV** [comment]
Also, a filter that extends to skills does not work. In this case, items are shown, but no skills.
![image](https://user-images.githubusercontent.com/47291794/68061681-2b0f2a00-fd17-11e9-841c-9e35144ed194.png)

**Comment by insthync** [comment]
Just uploaded fixed package, fields in prefab are missing, so icon disappear
