### ISSUE TITLE
Negative values in MMO

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1262]
I am experiencing some weird issues in MMO

first I had negative gold gain I put a gold cost to refine gear and then update and remove the gold cost. the current gear on the characters still require the gold to upgrade even though gold doesn't exist anymore on the item refine. 

Second is some monsters give negative experience you kill it and it gives you minus experience. their hp is not the same as single player in single monster has 5000 hp but in MMO the monster has 50. I set the levels to default at 2

I'm on the newest version.
Sorry to ask so many questions lately my game launched and over 100k people seen it so I have a lot of reports.

I noticed that some monsters do this not all.. do you have any idea why?

**Comment by insthync** [comment]
In `MonsterCharacter.cs` replace `RandomExp` and `RandomGold` functions to
```
        public virtual int RandomExp(short level)
        {
            int exp = AdjustedRandomExp.GetAmount(level).Random();
            if (exp < 0) 
                return 0;
            return exp;
        }

        public virtual int RandomGold(short level)
        {
            int exp = AdjustedRandomGold.GetAmount(level).Random();
            if (exp < 0)
                return 0;
            return exp;
        }
```

**Comment by Sour-J** [comment]
seems to work was this fixed in the new update? not sure you wrote in the new patch notes "Fix wrong dealing gold amount."

**Comment by insthync** [comment]
This is not related to fix wrong dealing gold amount, but it was included in latest version

**Comment by insthync** [comment]
Is it solved?

**Comment by Sour-J** [comment]
Solved thanks
