### ISSUE TITLE
Character not completely stop while attacking using automatic rifle

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1263]
while im using rifle with automatic fire and i set move speed while attack to 0 but its still not move completely , check the video
https://youtu.be/FaykIqAT6l0
![1](https://user-images.githubusercontent.com/64667641/141708847-b2a0f273-8b22-4b64-9e41-5502222bad2c.jpg)
![2](https://user-images.githubusercontent.com/64667641/141708922-21d409dd-439e-4b87-81f4-e425097b945a.jpg)
i want to disable moving while attacking

**Comment by RunOrDi3** [comment]
Its online happen when i press v to attack , when i press on monster by mouse its attacking and when i move attack got cancel .. i want allso when i use v to attack , i want to cancel the attack when i press on any move keys like awsd

**Comment by insthync** [comment]
Fixed in 1.71c
