### ISSUE TITLE
Trading gold is broken in MMO mode

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1264]
1. When trading **items** in MMO mode, player gold randomly increases, even though no gold is sent or received. This occurs for both players.

2. Sending gold through trade does not always detract from owning player, and sends a random amount to receiving character. MMO mode.

In the video below, player starts off with 107,000 gold, and after sending 5,000 to another player, ends up with 356,000 gold even though no gold was sent.

VIDEO:
https://i.imgur.com/PbLKklQ.mp4

**Comment by insthync** [comment]
Fixed in 1.71c

**Comment by BJPickles** [comment]
Amazing, thank you!
