### ISSUE TITLE
1.71b Loot Corpse

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1265]
cool new feature thank you, i tested it.

one thing, the loot corpse cant be targeted so that the ui prefab (UITargetGameEntity) appears when interact with it or when mouse hover over it with aimatcursor controller. so you cant see what kind of loot it is (name of dead monster/player) and you cant interact/loot it with aimatcursors controller.

**Comment by insthync** [comment]
Can't press E to interact it?

**Comment by moepi2k** [comment]
yes it works when press e to open it. i mean that ui prefab appear when interacting with the corpse. to see what corpse it 
https://gyazo.com/f67fb2af65858a1909cccaade723d738

**Comment by insthync** [comment]
Corpse title was implemented in 1.71c update
