### ISSUE TITLE
PickUpItem Mobile

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1266]
Hello, I was testing version 1.71C and I noticed that when throwing an object to the ground and then picking it up by clicking on it, the PickUpItemButton keeps appearing and showing the object.

It is the version for mobiles

https://user-images.githubusercontent.com/45702662/141827206-8b434304-b2d2-4361-8abb-7fe9fdb53288.mov

.

**Comment by insthync** [comment]
Fixed in 1.71d update
