### ISSUE TITLE
guild war errors

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1268]
when i updated i got these errors not sure why

Assets\UnityMultiplayerARPG\GuildWar\Scripts\BaseGameNetworkManager_GuildWar.cs(226,75): error CS0029: Cannot implicitly convert type 'int' to 'MultiplayerARPG.CharacterCurrency'

Assets\UnityMultiplayerARPG\GuildWar\Scripts\BaseGameNetworkManager_GuildWar.cs(231,62): error CS0029: Cannot implicitly convert type 'short' to 'MultiplayerARPG.CharacterItem'

**Comment by insthync** [comment]
Try delete `Assets\UnityMultiplayerARPG\GuildWar` folder and reimport the package.

**Comment by Sour-J** [comment]
resolved on new version
