### ISSUE TITLE
Multi attack animations support

### ISSUE THREAD

**Issue by Syrus198327** [suriyun-production/mmorpg-kit-docs#127]
Animation thats have multi attacks can you add support for this so if an animation have 2 or more swings in it thats how many times you hit the enemy. Mainly used for skills normal attacks will just be single attack animations or can i add the damage funtions in the animation event to do damage at the end of each swing ?

**Comment by insthync** [comment]
I don't understand it, you want to make it play multiple hits skills ?

**Comment by Syrus198327** [comment]
https://assetstore.unity.com/packages/3d/animations/frank-rpg-dual-combo-set-137161 animations like this one has combos animation with multiple attacks when i put it for skill it only hits onces for a 3 hit animation

**Comment by Syrus198327** [comment]
Trigger duration rate can you make that so we can set multiple trigger rates for animations that have multiple attacks in it

**Comment by insthync** [comment]
Yes, I was thought that I will change trigger duration to array. But I afraid that it will affect other people's project, So I decide to add new array variable, if this array length > 0 it will use trigger duration from array.

**Comment by Syrus198327** [comment]
Is there a damage function that i can set to the animation event to do the damage at diferent time frames during the animation

**Comment by insthync** [comment]
> Is there a damage function that i can set to the animation event to do the damage at diferent time frames during the animation

I will consider to add it, but for the next version you will able to set multiple trigger durations and each trigger it will do damages, damages will not be divided by hit count.

**Comment by insthync** [comment]
Updated, try 1.50c
