### ISSUE TITLE
GridManager

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1271]
any idea from where this error come from? 

https://gyazo.com/7122f886fab8c2001971115533b6f676

never saw that before and since i updated to 1.71c i get it

**Comment by RunOrDi3** [comment]
Happened to me also one time today with same version

**Comment by insthync** [comment]
Rarely occurring?, when maybe just occurred at the same frame when the identity was destroyed and grid manager updating objects positions nearby player, you actually can ignore it or just add null checking at line 220, it is not because of 1.71c I didn't change anything relates to grid manager.

**Comment by moepi2k** [comment]
never saw it before so thought its because of update :) 
thanks for info

**Comment by Sour-J** [comment]
Is there a fix for this? It's happening daily to my players I'm on the version before the newest
