### ISSUE TITLE
[Suggestion]Cooldown for Potions/Consumables

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1272]
A cooldown would be good for potions, so player are not able to spam it. 
maybe a string for global cooldown so u can set cooldown to "Potion" so diffrent kind of potions has same cooldown

just a suggestion :)

**Comment by insthync** [comment]
In 1.71f

- Add `useItemDelay` to game instance, use it to change delay before use item again.
- Add `UseItemCooldown` to usable item, it's cooldown after use the item.
