### ISSUE TITLE
Warping Bug (Singleplayer & MMO)

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1273]
1.71d - This bug has existed for a while and doesn't seem to change on updating to new versions, so I thought I'd make a post.

This seems to only occur when warping within the same map, but it happens in any map i.e could be Map001 -> Map001, or Map002 -> Map002. 
Unfortunately it was difficult to reproduce because it doesn't happen all the time, and seems to be random when it does.

The warp doesn't always seem to move the player to the target location of the warp. This occurs on respawn, as well as warp through NPC dialogue. Please see the videos:

**EXPECTED #1 [RESPAWN WARP]**: https://i.imgur.com/WUi7xsE.mp4

**BUG** #1 [RESPAWN WARP]: https://i.imgur.com/NZ0p7ZD.mp4

**BUG #2** [DIALOGUE WARP]: https://i.imgur.com/mU8VeaG.mp4

**Comment by insthync** [comment]
Are you using RigidbodyEntityMovement, right?

**Comment by BJPickles** [comment]
> Are you using RigidbodyEntityMovement, right?

Yes!

**Comment by insthync** [comment]
I was try to fix it by pausing `OpenCharacterController` movement update about 3 frames after teleport, but then I remove it because I think it's not a good way to fix the issues, but forget to do something to fix it :P, I will bring it back.

**Comment by insthync** [comment]
[MMORPG_KIT_RigibodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7554561/MMORPG_KIT_RigibodyEntityMovement.zip)

Try this

**Comment by BJPickles** [comment]
Haha yeah I get that. If I had a penny for every time I forgot to do the thing I wanted to do but got sidetracked and forgot, I'd be rich!!

I had noticed the bug occurred more when there was movement input (holding W or something), so I had wondered if the controller was trying to apply gravity or find walkable terrain nearer Y:0 before reaching the warp coordinates. (I have geometry that clips under each other, as seen in the videos).

I've tried the fix, the dialogue warps seemed fine and respawn fine - but when I used the /warp command, I ended up beneath the ground again.
![image](https://user-images.githubusercontent.com/48354382/142201425-687ad738-5654-4d0a-aa2d-58eda1fc70c4.png)

**Comment by BJPickles** [comment]
Just a thought - I am using GPU occlusion culling. Will that have an affect if the meshes are disabled, or does it rely on NavMesh at all?

**Comment by BJPickles** [comment]
Still ocurring on respawn, unfortunately.

VIDEO: https://i.imgur.com/T1hUp4q.mp4

**Comment by insthync** [comment]
[MMORPG_KIT_RigibodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7554774/MMORPG_KIT_RigibodyEntityMovement.zip)

**Comment by BJPickles** [comment]
> [MMORPG_KIT_RigibodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7554774/MMORPG_KIT_RigibodyEntityMovement.zip)

Still ocurring, unfortunately: https://i.imgur.com/R61YOpv.mp4

**Comment by insthync** [comment]
May I try it at your PC with TeamViewer?

**Comment by BJPickles** [comment]
> May I try it at your PC with TeamViewer?

Sure, BJPickles#6640 on Discord.

**Comment by insthync** [comment]
[MMORPG_KIT_RigibodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7556258/MMORPG_KIT_RigibodyEntityMovement.zip)

Try this.

**Comment by insthync** [comment]
Or just change to CharacterControllerEntityMovement

**Comment by insthync** [comment]
Hey as I try it again, for the far object it will completely disable object, not just disable renderer. I think it can be cause of problem.

**Comment by insthync** [comment]
![Screenshot_789](https://user-images.githubusercontent.com/2697550/142344799-cdff2f6e-e567-47ed-a781-f037254118bc.png)

You may try set very high `full disable distance` to make it not deactivate objects

**Comment by BJPickles** [comment]
> ![Screenshot_789](https://user-images.githubusercontent.com/2697550/142344799-cdff2f6e-e567-47ed-a781-f037254118bc.png)
> 
> You may try set very high `full disable distance` to make it not deactivate objects

Thanks Suri, I'll give this a go. Failing that, I'll specifically set the individual mesh under the warp location to never disable.

**Comment by BJPickles** [comment]
Can confirm using an exclusion layer, having specific meshes that are completely ignored by occlusion culling and your additional changes have fixed this problem.
