### ISSUE TITLE
Relog Desync

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1274]
on newest version, players are reporting that sometimes,
"I can't hurt things, enemies don't spawn, and I lose no stamina
some sort of desync happens on first load
fixes itself immediately on loading a second time"

so when they first load its like they actually didn't load into the game its a blank world no monsters or harvests they have to re-login for it to work.  I check with my server engineers and they said theres nothing wrong on server side, I'm sending you a steam key via email maybe you could try it

**Comment by insthync** [comment]
Okay, I will try it

**Comment by insthync** [comment]
Is it rarely occuring? I think it might relates to this https://github.com/suriyun-production/mmorpg-kit-docs/issues/1271 but still doubt why it is just occurring.

**Comment by Sour-J** [comment]
Yes it's rare

**Comment by Sour-J** [comment]
Is there a fix for this? It's happening daily to my players I'm on the version before the newest

**Comment by insthync** [comment]
I fix the grid manager but not sure this will be fixed too.

**Comment by Sour-J** [comment]
I am sorry to say this is still happening in 1.72b. ;(

**Comment by insthync** [comment]
I still can't reproduce it, even with your game.

**Comment by Sour-J** [comment]
XD I'll see if I can take a video but not even sure why this would even happen. It's no big deal I guess people can just relog but some players buy the game and experience a empty world leave a bad review and refund but they don't know to relog.

**Comment by Sour-J** [comment]
Sadly it's random sometimes it does it sometimes it doesn't here's a players review of the game. I can't seem to catch a video but I don't think the video would even help.

"Possibly may be a bug preventing me from interacting with anything, so the issue may be technical rather than due to the quality the actual content."

"Sometimes I spawn in and there's no monsters or harvestable around the map I have to relog to go back to normal"

tried everything I could to fix this but still randomly happens. I think I may be one of the few that actually put the kit up in a production setting to see how it performs and it's doing really well just a few little things like this fixed and it's gold. 

Thank you for all you do I appreciate you and will donate some steam sales to you for trying to fix these things

**Comment by Sour-J** [comment]
i started a new better server today ill reopen if this still exists I think its resolved not sure
