### ISSUE TITLE
ongoing dialog conditions

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1275]
even after completing the quest, the dialog that should only appear while the quest is being completed is appearing after completing the quest.

![image](https://user-images.githubusercontent.com/56885137/142271467-0aa81eac-1716-4203-bde3-bc21da54b7ab.png)

**Comment by insthync** [comment]
[MMORPG_KIT_NpcDialogCondition.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7559687/MMORPG_KIT_NpcDialogCondition.zip)

Fix by this package

**Comment by juniormagalhaes** [comment]
> [MMORPG_KIT_NpcDialogCondition.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7559687/MMORPG_KIT_NpcDialogCondition.zip)
> 
> Fix by this package

Worked, thank you
