### ISSUE TITLE
[Question For Suri]Item DataID

### ISSUE THREAD

**Issue by MrBeatngU** [suriyun-production/mmorpg-kit-docs#1277]
Suri, is there an easy way to get the DataID of items without having to associate what DataID belongs to which item through the characteritem database? It's extremely time consuming having to test items to get their ID's to use for websites. If you've implemented this somewhere within the files without having to reverse the create item hash could you let me know? Thanks

**Comment by insthync** [comment]
What are you going todo?, are you going to make a website which will be used to see items in character's inventory?

**Comment by MrBeatngU** [comment]
I'm working on a website that will use the item information to pull data and display the items the character owns, skills, allow modifying things as an admin, website mail implementation. If you have an alternative to having to hunt down the item id's I would be extremely thankful.

**Comment by insthync** [comment]
I think you should make game data exporter may export game data as JSON, then read from it, data ID is in game data.

**Comment by insthync** [comment]
As I check again, Unity .asset file content is in YAML format, I think it might have YAML reader for your website. But still have to write how it read data.

**Comment by MrBeatngU** [comment]
The GUID? Thats the dataid in YAML format?

**Comment by insthync** [comment]
![Screenshot_791](https://user-images.githubusercontent.com/2697550/142366138-ae73dc42-cbac-4c5e-bbe4-912e7624e345.png)

It has id, and name, we still have to write codes which convert id or name to hashed value

**Comment by MrBeatngU** [comment]
So basically I need to write this section of code to convert the name to the id?
    public static int GenerateHashId(this string id)
    {
        if (string.IsNullOrEmpty(id))
            return 0;

        unchecked
        {
            int hash1 = 5381;
            int hash2 = hash1;

            for (int i = 0; i < id.Length && id[i] != '\0'; i += 2)
            {
                hash1 = ((hash1 << 5) + hash1) ^ id[i];
                if (i == id.Length - 1 || id[i + 1] == '\0')
                    break;
                hash2 = ((hash2 << 5) + hash2) ^ id[i + 1];
            }

            return hash1 + (hash2 * 1566083941);
        }
    }

**Comment by insthync** [comment]
Yes

**Comment by MrBeatngU** [comment]
Thanks, I'll do that tomorrow then. I'm not sure what PHP's equivalent of unchecked is but I'll look into it tomorrow.

**Comment by insthync** [comment]
It may not need, I not sure that PHP will throw overflow exception or not

**Comment by insthync** [comment]
https://gist.github.com/insthync/f8a24fa94021a37fb7e0a1c6f07b9777
