### ISSUE TITLE
Game Object Query Database?

### ISSUE THREAD

**Issue by sinfulspartan** [suriyun-production/mmorpg-kit-docs#1278]
So I'm trying to figure out how to have a server side game object query the database?

The specifics of what I'm trying to do is to have the HavestableSpawnArea query the database for a new table that I've created.

**Comment by insthync** [comment]
Querying everytime when attacking it or just when initializing the game server?

**Comment by sinfulspartan** [comment]
Just on initializing.
———————
Shane Mummaw
General Adjuster, CGA
Insurance Appraisal & Mediation
561-235-8762


ᐧ

**Comment by insthync** [comment]
You may create extension function to load your data like this:
```
namespace MultiplayerARPG
{
    public partial class GameInstance {
        
        [DevExtMethods("LoadedGameData")]
        protected void ReplaceGameData() {
                // Connect to your service and load data
        }
    }
}
```

**Comment by sinfulspartan** [comment]
Okay. But I don't see how to query the data from the sql database?

**Comment by sinfulspartan** [comment]
What I'm attempting to do is have the HavestableSpawnArea run a query to the SQL database when the server starts to get its world location data and other stats that I have stored in the SQL database.

But it seems that there may be several steps to make this work and I can't find any examples of this in the code. Or at least I don't understand how this is working if it is coded somewhere.

**Comment by insthync** [comment]
You should create a service externally for that part, don't have to do everything in Unity. In my opinion, it's a lot easier than doing everything in Unity. But if you want to do everything in Unity, based on this project and you want to follow whats I did, you will have to create messages in `Database Network Manager` , notice in `Database Network Manager` there is a `RegisterMessages` function which contains codes which uses `RegisterRequestToServer` to register message handlers which will do something when the server receives messages from client to do something, you can find message handler functions in `DatabaseNetworkManager_RequestHandlers.cs` and can see how to send messages from client to server in `DatabaseNetworkManager_Requests.cs`.
