### ISSUE TITLE
1.50b BUG Hotkey Assigner Filter

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#128]
The filter takes into account only those skills that we have pumped. If we put on an item with a skill, then the filter does not take this skill into account.
[20191102044514.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3800036/20191102044514.zip)
Or is it my wish that I asked earlier? So that a character cannot use skills that he has not learned?
If so, you can close it. I will return to the old skill system.😆

**Comment by insthync** [comment]
Ahh, I see. I will fix it

**Comment by DimasjkTV** [comment]
> Ahh, I see. I will fix it


Can you post the changes here? If there are not many.

**Comment by insthync** [comment]
Fixed in 1.50c
