### ISSUE TITLE
The area skill cant work

### ISSUE THREAD

**Issue by VEsttas** [suriyun-production/mmorpg-kit-docs#1283]
Hi,the area skill can't work in 2D demo scene (mobile mode), should I set something to make it work?

**Comment by insthync** [comment]
[MMORPG_KIT_Demo2D_AreaDamageEntity.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7576550/MMORPG_KIT_Demo2D_AreaDamageEntity.zip)
