### ISSUE TITLE
movement issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1284]
not sure if there is a open issue already but with the newest version when I press the activate button on a npc or building storage while moving i get stuck moving in that direction until i exit the ui

**Comment by moepi2k** [comment]
thats actually the same issue you already reported. so player auto move in one direction without pressing a key. i still got this too

**Comment by insthync** [comment]
I cannot reproduce it yet.

**Comment by moepi2k** [comment]
Yea forgot to add aimatcursor controller, it seems it works now :) thanks

**Comment by Sour-J** [comment]
> Yea forgot to add aimatcursor controller, it seems it works now :) thanks

?? How did you fix this? My controller is set in game instance

**Comment by moepi2k** [comment]
Just updated my aimatcursors controller with the latest fix

**Comment by insthync** [comment]
As I try your game, your game uses `Shooter Player Character Controller` right?, try check this line:

![Screenshot_809](https://user-images.githubusercontent.com/2697550/143508334-863d020e-ceae-4729-8857-24e656199db9.png)

When it found any enabled `UI Block Controller` component, `IsBlockController` will be `TRUE` then it should stop movement by codes at line `553`

**Comment by Sour-J** [comment]
Thank you I will try this and yes it uses that controller

**Comment by Sour-J** [comment]
seems to be resolved now thanks
