### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1285]
there is a bug in the warehouses, if you try to add them to your inventory quickly, they are added to the warehouse as many times as you press unlimited, and if you try to take more than one item into the inventory while taking it from the warehouse, this time the items will be lost.This problem is in the mmo section. To do it, you need to click on the item and press deposit from there, then quickly repeat

**Comment by BarzoStrike** [comment]
https://www.youtube.com/watch?v=a0WJqcEwxZk

**Comment by insthync** [comment]
Oh O_O

**Comment by insthync** [comment]
[MMORPG_KIT_AvoidDupeItems.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7578368/MMORPG_KIT_AvoidDupeItems.zip)

Try this package

**Comment by BarzoStrike** [comment]
Dupe is not working now, this problem has been solved, but when I buy a sword from the warehouse, it goes on the potion instead of the empty slot in the inventory and the potion disappears

**Comment by BarzoStrike** [comment]
this is nothing new actually dupe is more important i ignored this and forgot i'm sorry

**Comment by insthync** [comment]
I don't understand

**Comment by BarzoStrike** [comment]
https://www.youtube.com/watch?v=oWTqjgEO6Cw

**Comment by insthync** [comment]
How about data when you logout and re-login, data are invalid or not?

**Comment by BarzoStrike** [comment]
Items disappear, when I relog items do not come back

**Comment by insthync** [comment]
Please post server log files here.

**Comment by insthync** [comment]
So it was solved?

**Comment by BarzoStrike** [comment]
my server is on google.The server no longer log files due to an event I don't know the reason for. After solving them, I will try again. You solved the dupe side, that's enough for me for now. I'll transfer an empty project to the server and try it there, if it does then I'll come back
