### ISSUE TITLE
[Little Fix] in Movement Speed Delay

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1286]
First it was that when you added it 
public const float RETURN_MOVEMENT_SPEED_DELAY = 0.2f; 
after that you changed it to : 
public const float RETURN_MOVEMENT_SPEED_DELAY = 0.01f;
the one with 0.01f looks like when we dont have a delay .. so i have tested 0.1f and it is the best one for automatic guns so it should be : 
public const float RETURN_MOVEMENT_SPEED_DELAY = 0.1f;

thanks in advance

**Comment by moepi2k** [comment]
Then best solution is to make it accessible by inspector. Because 100ms is a big delay and affect every action and make it unsmooth

**Comment by RunOrDi3** [comment]
make it accessible by inspector good idea , i swear 0.01 looks like without delay .. anyway access by inspector is good idea

**Comment by RunOrDi3** [comment]
with 0.01 >> https://www.youtube.com/watch?v=7gQpAJyew4o
with 0.1>> https://www.youtube.com/watch?v=VL_fq0mZGY8

**Comment by insthync** [comment]
In 1.71f

- Move `RETURN_MOVEMENT_SPEED_DELAY` from character entity to game instance `returnMoveSpeedDelayAfterAction` settings to allow developer to change delay before return move speed while attack or use skill to generic move speed.
