### ISSUE TITLE
[Issue]Player Character controller's Camera

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1287]
I have changed some settings to make the default one to be like top down , its fine when i test in unity editor like this >>
![2](https://user-images.githubusercontent.com/64667641/142790576-0017da41-6396-4a5e-b66b-abe07560631a.jpg)
but when i test in build the game and test in mmo mode, its not like the same one inside editor like this >>
![1](https://user-images.githubusercontent.com/64667641/142790638-cce3791c-3a9d-4ae7-8f42-ff6f88689460.jpg)

**Comment by insthync** [comment]
Not sure what is wrong, in the build it is wrong rotation?

**Comment by RunOrDi3** [comment]
@insthync X Rotation turns to wrong number when i build the game , in this image thats the one i made and in editor works fine 
![Untitled](https://user-images.githubusercontent.com/64667641/142854617-c3a3c0c8-f818-4a3d-b4fe-93048819906c.jpg)

**Comment by insthync** [comment]
So... you want to fix X rotation to 40 ?

**Comment by RunOrDi3** [comment]
@insthync yes , i want t fix it when i build it .. in editor its fine but when i build it its not the same in editor

**Comment by insthync** [comment]
Set both Min X Rotation and Max X Rotation to 40

**Comment by RunOrDi3** [comment]
oO thanks alot suri <3 , it works now :) @insthync
