### ISSUE TITLE
System chat to be server wide or expanded

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1288]
Currently `/s` system messages are limited to a single map. Please could it be expanded to function like `/a` to reach all maps, or 2 separate commands like `/s` (local) and `/s_all` (all maps) or something.

I think this would serve a greater purpose in sending server-wide announcements.

![image](https://user-images.githubusercontent.com/48354382/142845256-9a08122a-c298-4469-9a59-6c01ef4cdcca.png)

**Comment by insthync** [comment]
Fixed in 1.71f
