### ISSUE TITLE
[issue] With Snigle Fire

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1290]
when i add damage like 10-12 to sniper or pistol ( single fire ) and attack enemies it gives 2x shots first shot is highly fast then character turns so fast to shot another bullet to another enemy like in video ,, attack with v , mouse or anything>> note ( in video the turn speed to another enemy so so fast so you wont see the turn ) so test in kit demo .. https://youtu.be/8GPiDN2Ue20

**Comment by insthync** [comment]
?? So it was solved?

**Comment by RunOrDi3** [comment]
yes it was from wasd attack i made checked it by mistake , sorry :)
