### ISSUE TITLE
Consume % change to Skill Activation

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1292]
An option to consume % of total when activating skill would be very useful. I.e consume 25% of total Mana when activating skill.
This means there's a base cost, regardless of how much mana/hp/stamina you may have etc.

![image](https://user-images.githubusercontent.com/48354382/143047844-830aa106-ac4d-41bc-bb55-d308abcab333.png)

**Comment by insthync** [comment]
Added to `1.71f`

- Add `consumeHpRate`, `consumeMpRate` and `consumeStaminaRate` settings to skill, it will be used to calculate consuming Hp or Mp or Stamina amount by multiplies with character's max Hp or Mp or Stamina value, for example if `consumeHpRate` is `0.1` and character's max Hp is `100` consuming Hp will be `10`.
