### ISSUE TITLE
[question] Can I change a player spawn location for each faction separately? 

### ISSUE THREAD

**Issue by vladyslu** [suriyun-production/mmorpg-kit-docs#1293]
Hi. Can I change a player spawn location for each faction separately? for an MMO map?

**Comment by insthync** [comment]
You can set respawn position at map data game object

![Screenshot_810](https://user-images.githubusercontent.com/2697550/143512552-9c430026-5671-45d0-8e03-60187523f7bf.png)

**Comment by vladyslu** [comment]
> You can set respawn position at map data game object
> 
> ![Screenshot_810](https://user-images.githubusercontent.com/2697550/143512552-9c430026-5671-45d0-8e03-60187523f7bf.png)

Will the respawn position change starting position?

**Comment by insthync** [comment]
No, has to wait the next version, I've made it can change position in warp portal, and also able to set the start position for a different faction.

**Comment by vladyslu** [comment]
> No, has to wait the next version, I've made it can change position in warp portal, and also able to set the start position for a different faction.

Awesome. thank you very much. :) It helped a lot. 
I have one more question though. 
How do I set a shop to sell and buy items with gold?

**Comment by vladyslu** [comment]
> No, has to wait the next version, I've made it can change position in warp portal, and also able to set the start position for a different faction.

Awesome. thank you very much. :) It helped a lot. 
I have one more question though. 
How do I set a shop to sell and buy items with gold?
