### ISSUE TITLE
Sell items anywhere bug

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1295]
If you interact with a shop npc your able to sell items from your inventory anywhere after that until you relog in MMO

Would be a nice option in game instance if you could sell anywhere but this one is a bug 🐛

**Comment by Sour-J** [comment]
Maybe it's not a bug and my UI should be hiding that button but it's not :( my sell is always showing probably just my UI issue sorry

**Comment by moepi2k** [comment]
Anyway if ur ui works properly, tjere should be a distance check serverside when click sell. Because ui can be injected

**Comment by Sour-J** [comment]
it was my UI
