### ISSUE TITLE
Queued Workbench

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1296]
This is not really a bug, but could be confused without improvement

-> the queued workbench can be opened for example through walls or from distance (outside of interaction distance)

Both opens the ui but in both case the player cant use the queued workbench. Then when player select a formula and try to craft nothing, nothing happens because player is to far away or blocked by an obstacle.

To fix it, would be good the ui only opens when player really can use it. (In sight of player its a bug)

**Comment by insthync** [comment]
Only queued workbench that has these issues?

**Comment by moepi2k** [comment]
I only use queued workbench. I need to check if normal workbench also has the issue.

**Comment by moepi2k** [comment]
so i tested again. here the video:
https://gyazo.com/7e7393f9090a19f67df2c6d9e61706bd

as you can see Campfire and BuildingStorage UI wont open and you will get msg that you are too far away. but the UI for queued workbench opens even when player are too far away. then when u try to craft something, it wont work without any message. you need to walk then in interaction range.

would be be good that it work same like Campfire and Storage, else players get confused and mean its a bug.

**Comment by insthync** [comment]
Fixed in 1.72

**Comment by moepi2k** [comment]
Ui can still be opened outside onteraction range, you never get the msg like "you are too far away"

**Comment by moepi2k** [comment]
i checked code, from the logic it shouldn open the ui but it does :/

https://gyazo.com/72f9633de2af240e72d2e5ad29956fba
https://gyazo.com/3bc94fd85c7385131264796e0fb7a67a

**Comment by moepi2k** [comment]
sorry for spaming.

its not the cleanest way but it works
https://gyazo.com/fe1e7520004101df2ca6a54b65ea5783
https://gyazo.com/c2742b4797a3338c36d7db43800a69a6

**Comment by insthync** [comment]
Great, thank :)
