### ISSUE TITLE
Turning on websockets in 00Init scene makes the game very sluggish

### ISSUE THREAD

**Issue by chankc** [suriyun-production/mmorpg-kit-docs#1297]
When I check the "Use web Socket" option in NetworkManager component of the demo scene "00Init", the game becomes very sluggish and unplayable on play. I'm using the latest package (1.71f) on Unity 2020.3.22f1.

**Comment by insthync** [comment]
`00Init` not `00Init_MMO` ?

**Comment by insthync** [comment]
Why you tick it on for offline/LAN game?

**Comment by chankc** [comment]
Yes 00Init.
May I know what's the different between 00Init and 00Init_MMO demos?

I still haven't figured out how to run 00Init_MMO. It stays on the Server
selection screen and pressing Connect doesn't do anything.

**Comment by insthync** [comment]
Don't know too, you didn't give me enough info.

**Comment by insthync** [comment]
Found the issues, I will fix it, Thank you for your reporting :)

**Comment by chankc** [comment]
Thanks!

**Comment by insthync** [comment]
Fixed in 1.72
