### ISSUE TITLE
游戏运行报错

### ISSUE THREAD

**Issue by naughty66** [suriyun-production/mmorpg-kit-docs#1298]
我刚刚在unity商店购买您的 “MMORPG KIT (2D/3D/Survival)”，但是打开会报错误，请问这是怎么回事？

![image](https://user-images.githubusercontent.com/95008248/143374889-fa23edfb-0255-420d-9695-4055f18f76da.png)

**Comment by naughty66** [comment]
1、按设置指南调整后，又出现如下问题。
![image](https://user-images.githubusercontent.com/95008248/143388972-4531b633-0a20-4ba8-84a8-c6967b1e9e33.png)

![image](https://user-images.githubusercontent.com/95008248/143388917-b042deef-6dde-4c75-a8ac-8f16943aa4ca.png)

2、按设置指南-入门内容操作，进行构建游戏，又会出现如下问题。
![image](https://user-images.githubusercontent.com/95008248/143389114-ed19123b-4959-4d7e-8940-0ec147587433.png)
![image](https://user-images.githubusercontent.com/95008248/143389191-d4c94662-7fef-4719-bf18-67d3cda2d3ba.png)

**Comment by insthync** [comment]
Try delete `http://volumes/XXX/New%20Unity%20Project02/Library/Bee/artifacts/200b0aE.dag/ZString.dll.movedfrom`, I will try to build the game with my Mac when I arrived home.

**Comment by insthync** [comment]
As I try, it is working properly, how about yours after delete that file?

**Comment by insthync** [comment]
I will close this because it has no answer from you

**Comment by naughty66** [comment]
感谢您的回答，我降低Unity版本之后可以打包。
