### ISSUE TITLE
AreaDamageEntity self damage option

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1300]
Might be fun to have a toggle option for AoE to also inflict self-damage to caster.

**Comment by insthync** [comment]
Added in 1.72

**Comment by BJPickles** [comment]
Thanks for adding!
Tested in 1.72 fresh project and sadly does not work. 

VIDEO: https://i.imgur.com/tjq2lZZ.mp4
