### ISSUE TITLE
"bug" with task completed

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1301]
when completing the task a "?" still remains on top of the NPC.

![image](https://user-images.githubusercontent.com/56885137/143493732-1efb5294-16d9-4235-a6d2-b2d19b85e186.png)

**Comment by insthync** [comment]
I actually design it to work like that :(

**Comment by juniormagalhaes** [comment]
> I actually design it to work like that :(
why?

I think it gets weird, because you can have more than one npc quest to complete.

**Comment by juniormagalhaes** [comment]
and counter intuitive in my opinion, the player when you see the "?" you'll want to talk to npc again and you'll think it's a game bug

**Comment by juniormagalhaes** [comment]
> I actually design it to work like that :(

is there any way to disable this?

**Comment by juniormagalhaes** [comment]
if the person puts a compass for targeting even talking to the npc, it will still appear in the compass

**Comment by insthync** [comment]
Disabled

**Comment by juniormagalhaes** [comment]
> Disabled

ok

**Comment by insthync** [comment]
Included in 1.72

**Comment by moepi2k** [comment]
i dont know if its regarding this change, but in 1.72 my quest "talkt to npc" no longer works
when i accept the quest i get the this:
https://gyazo.com/1b19b3faa7ce8f4639f932571c55704c
-> Talk to uknown

and there is no symbol on npc and i cant finish the quest.
https://gyazo.com/0873c8a57d43d05706763bb6fc6b4376

**Comment by juniormagalhaes** [comment]
> 

![image](https://user-images.githubusercontent.com/56885137/143876022-0e25d7ea-8c76-4513-9084-529c8cb795b4.png)

here it is working normally in version 1.72

**Comment by moepi2k** [comment]
strange. i dont know from where the Talk to Unknown coming from.
the quest also never complete when i talk to npc. 
it worked in 1.71f
