### ISSUE TITLE
Feature request: Multiple idle animations

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#1302]
Please change idle animations to be an array so we can add more than one and have them randomly selected.

**Comment by LordPhrozen** [comment]
Yes please.

**Comment by insthync** [comment]
So the random idle state has to be synced with other clients?

**Comment by vaughanb** [comment]
Ideally it should be synced somehow. Although, since it's just an idle
state, I doubt it would ever be an issue if it wasn't.

**Comment by LordPhrozen** [comment]
I'd say anim-sync is far less of a concern.

Personally Id set up 8 of the same animation, and 3 unique ones ( cracking knuckles/neck, seeing something fly by, etc) to have the more 'event' ones spaced out from the normal idle. 

idk if i would be concerned about idle anim syncing, unless your players are trying to line up funny screenshots.
