### ISSUE TITLE
Show/hide CanvasOwningCharacterUI toggle

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1303]
Some players like to see their character's name above their head, some players do not. Having a toggle option would be useful to give players the choice.

![image](https://user-images.githubusercontent.com/48354382/143510131-5b6e24be-6fbd-45ad-a7f6-4f490c5ea07a.png)

**Comment by insthync** [comment]
Please do it by yourself, you may create a new component which will be attached to `UICharacterEntity` prefab (In demo prefab name is `CanvasOwningCharacterUI`) the component will be able to store name's gameobject reference and also read settings that may be stored to player prefs to toggle it on/off.
