### ISSUE TITLE
Hotkeys no more clickable on mobile view for items only for skills

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#1305]
Hello! @insthync, hope you doing great. After updating to 1.71b (2021-11-14) version, I can not select the hotkeys (for my weapons) by clicking after assigning, now I can only pick a hotkey with keys (eg. key 2, key 3, key 4) from the keyboard only in mobile view. This happens both in an edited kit and a freshly installed kit. This was not happening before. Please what is wrong?

https://user-images.githubusercontent.com/4920405/143580556-69faf2a5-2109-4cfc-a727-880c91d1da4e.mp4

https://user-images.githubusercontent.com/4920405/143580562-90da320b-07b2-4047-81fa-75ce52a2d0e2.mp4

**Comment by isaanyoha** [comment]
Again, I noticed that if I assign a skill and try to select/click it from the hotkey slot, it picks but other items like weapons refuses to pick

**Comment by isaanyoha** [comment]
Even on a real mobile device, it refuses

**Comment by isaanyoha** [comment]
Hi @insthync, I will be glad if you can point me in the direction of fixing this. It may be a dumb question, but I am just stranded were trying to resolve this. Also, it was working for me before I made the update. Please kindly assist me with a clue. Thanks!

**Comment by insthync** [comment]
Please wait, I just wake up.

**Comment by isaanyoha** [comment]
Ok @insthync, I will be waiting like the sun. Take your time. Thanks!

**Comment by isaanyoha** [comment]
Hi @insthync! Hope you doing well. Hope you have not forgotten me. Thanks!

**Comment by insthync** [comment]
Stop please, I read it already. If you keep posting I will help you later.

**Comment by insthync** [comment]
In `UICharacterHotkey` 
replace `FinishAimControls`  function to

```
        public void FinishAimControls(bool isCancel, AimPosition aimPosition)
        {
            ICustomAimController ability = null;
            if (usingItem != null)
                ability = usingItem;
            if (usingSkill != null)
                ability = usingSkill;
            if (ability != null)
            {
                ability.FinishAimControls(isCancel);
                if (ability.IsChanneledAbility())
                {
                    StopChanneledAbility();
                    return;
                }
            }
            if (!isCancel)
                Use(aimPosition);
        }
```

**Comment by isaanyoha** [comment]
Solve now. Thanks, buddy! I appreciate!
