### ISSUE TITLE
MoveSpeedRateWhileAttacking not working while attacking on mount

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1307]
^ like title :)

**Comment by insthync** [comment]
Not sure it should be applied on mount too, what if I make a game that can drive a car, it should slower while attacking?

**Comment by moepi2k** [comment]
your right xD, maybe just a bool like useMoveSpeedRateWhileAttacking?

**Comment by insthync** [comment]
Another option again, it would be great if someone can help me to update the document.

**Comment by moepi2k** [comment]
sure i can do, let me know. u also can send email for more infos about access for docu

hublard2000@gmx.ch

**Comment by insthync** [comment]
Just fork this repository, update pages and make pull request

**Comment by moepi2k** [comment]
can u explain more?

**Comment by insthync** [comment]
You know how to use git?

**Comment by moepi2k** [comment]
Yes, i use it also for my project

**Comment by insthync** [comment]
Do like this 

https://jarv.is/notes/how-to-pull-request-fork-github/

pages are in /docs/pages

document system is https://docsify.js.org/#/

**Comment by moepi2k** [comment]
great, i will do it

**Comment by insthync** [comment]
Oh, I just found `moveSpeedType` in `VehicleEntity`, did you try it, not sure when it was added, try setting it to `BasedOnDriverMoveSpeed` and set `driverMoveSpeedRate` to some number.

**Comment by moepi2k** [comment]
ohhh good idea, let me check :)

**Comment by moepi2k** [comment]
that works :) great thank you
