### ISSUE TITLE
Websocket problem when trying to run game in WEBGL

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1308]
![Screenshot_1382](https://user-images.githubusercontent.com/12781104/143671005-09b42ac2-6663-40cd-b6d4-b9d39b36fcde.png)
I have all websocket checkboxes enabled in the client and server isntances. But dont know what to do next

**Comment by MosesGomez** [comment]
Btw, got the same erorr in a bought domain and web. The ss one was a test.

**Comment by insthync** [comment]
Try 1.72

**Comment by MosesGomez** [comment]
> Try 1.72

Thank you, ill try it

**Comment by insthync** [comment]
Have new update which will be uploaded today, please wait.

**Comment by MosesGomez** [comment]
> Have new update which will be uploaded today, please wait.

Ok, Let me know please, was updating last one of today minutes ago

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144354563-406ba990-d787-42fb-ba7f-219243af18f9.png)

Sorry, how do I get the data of the websocket? I seen that you had like a tutorial with more info, but the link is broken.

**Comment by insthync** [comment]
That page is https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/030-server-command-line-argument

Which data do you want to get?

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144361292-cd3fdad7-7c68-45ed-8ef9-1996945523d3.png)
Those

**Comment by insthync** [comment]
Try googling `how to create .pfx`
