### ISSUE TITLE
Ability cooldown

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#1309]
Hello, there is a problem after death, abilities can be minted before the cooldown expires.

**Comment by insthync** [comment]
I intend to make it work like that.

**Comment by CLAXES** [comment]
What should I do to prevent my abilities from being printed right after I die?

**Comment by CLAXES** [comment]
I don't want cooldowns to reset after I die.

**Comment by insthync** [comment]
In `BaseCharacterEntity_DamageFunctions`

Delete line 51

**Comment by insthync** [comment]
![Screenshot_813](https://user-images.githubusercontent.com/2697550/143687014-7a5324c2-9fdc-4a05-8ee4-4d50104bb41a.png)
