### ISSUE TITLE
I get an error when I use 2 different abilities

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#1310]
What is the reason for this error when I use the buff ability?
![Adsız](https://user-images.githubusercontent.com/95127578/143691918-5e9b8d0c-81a4-48e8-b96d-91a9f542a714.png)

**Comment by juniormagalhaes** [comment]
I get this same error when replacing the weapon by dragging it to the slot while there is already a weapon there.

![image](https://user-images.githubusercontent.com/56885137/143699613-1f00ab2c-8fd2-44a4-9caf-4d7d854b757b.png)

**Comment by insthync** [comment]
[LiteNetLibSyncListFix 2021-11-28.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7612516/LiteNetLibSyncListFix.2021-11-28.zip)

Import this, if you found error relates to `AddRange`, delete codes which relate to it.

**Comment by moepi2k** [comment]
had this error also with 1.71f

after importing zip, i got this

https://gyazo.com/37c7a0856bfec03b545f8966d1b27284

**Comment by juniormagalhaes** [comment]
> [LiteNetLibSyncListFix 2021-11-28.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7612516/LiteNetLibSyncListFix.2021-11-28.zip)
> 
> Import this, if you found error relates to `AddRange`, delete codes which relate to it.

![image](https://user-images.githubusercontent.com/56885137/143767400-6ceb1d3c-5a9a-4989-af29-b6131478a09e.png)

**Comment by insthync** [comment]
Fixed in 1.72
