### ISSUE TITLE
Few MMO Bugs since 1.70+

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1311]
i update my project to 1.71f.

last mmo test was around 1.70 so i cant say from what version the issues coming from.

3) when i drop items. they stick somwhere in the air. **in singelplayer everythings fine**
https://gyazo.com/6ce03469675e58f1d9cb422d6a6bb186sa

**Comment by moepi2k** [comment]
one more thing, when logout and relog. your player is duplicated until logouttimer logsout the first one O.o
https://gyazo.com/2cb50913c90e925597118922c2af8ae6

**Comment by insthync** [comment]
Try 1.72

**Comment by moepi2k** [comment]
the thing that player remains and duplicated in mmo after relog when PlayerCharacterDespawnMilisecodsDelay is not 0 still there
https://gyazo.com/a3d251969fdc780751ef4e2a4b9aff17

**Comment by insthync** [comment]
Fixed in 1.72b
