### ISSUE TITLE
Can no longer control the follow camera at the same time when moving the main character using the MOVE joystick in a real mobile device

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#1312]
Hello @insthync , in a real mobile device I noticed when moving the main character using the MOVE joystick, I can no longer control the follow camera at the same time which I used to do before the update. I must have to stop holding the MOVE button before I can adjust the follow camera unless I started with adjusting the follow camera before touching the MOVE button that is the only time it works. It also happens in a fresh install. This used to work before my update. Same with fresh install of update

**Comment by isaanyoha** [comment]
I am using ShooterCharacterController

**Comment by isaanyoha** [comment]
Hi! @insthync please I would like to know if you attended to this in 1.72b (2021-11-30). And if it is not really a bug, how can I get it to work as it usually works before in other fresh versions. Please, Thanks man!

**Comment by insthync** [comment]
:(

**Comment by insthync** [comment]
Please do not flood

**Comment by insthync** [comment]
Fixed in 1.72b2

**Comment by isaanyoha** [comment]
Ok, Thanks!

**Comment by Kanera66** [comment]
I have the same problem I have the latest version 1.72c5
