### ISSUE TITLE
Short question

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1313]
can help lead me to the right direction?

i need to get item of EquipItem e.g body, head, gloves when its equiped.

similar like `EquipWeapons.GetLeftHandShieldItem()` to get shield item.

thank you very much

**Comment by insthync** [comment]
They are in EquipItems list, to get each item data you can use function like this 

equipItems[0].GetArmorItem()

**Comment by moepi2k** [comment]
peeeerfect thank you very much :))

**Comment by moepi2k** [comment]
another question.
it works when i set exactly the right index of the equipitem. for example

 if (equipItems[1].GetArmorItem().DataId.Equals(ssm.passiveSkill[i].requiredArmor[j].DataId))

then i need to equip the item at second place.

i just want to check if the specific item is equiped, beucase i have 6 equip slots. so it should just check if its equiped in one of them.
with the index solution it not work proberly. sometimes i get an ArgumentOutOfRangeException: Index was out of range  error.

else it works great

any better idea?

**Comment by insthync** [comment]
Not sure what you are going to do, why it must be `equipItem[1]`?, it is specific kind of armor?, you may try find index of specific item before use it, for example:

```
int indexOfItem = -1;
for (int i = 0; i < equipItems.Count; ++i) {
  if (equipItems[i].GetArmorItem().ArmorType == armorType)
  {
    indexOfItem = i;
    break;
  }
}
if (equipItems[indexOfItem ].GetArmorItem().DataId.Equals(ssm.passiveSkill[i].requiredArmor[j].DataId))
{

}
```

**Comment by moepi2k** [comment]
exactly i do it like that and works :)
thank you very much
