### ISSUE TITLE
RPG Character Mecanim Player Controller Intergration

### ISSUE THREAD

**Issue by SkyDuckzx** [suriyun-production/mmorpg-kit-docs#1314]
hello i bought the kit and i was wondering would you have time to intergrate the RPG Character mecanim asset player controller with the kit? or any kind of guide what i need to do to make it work ?

**Comment by insthync** [comment]
If you are going to use just their animation, just set animations to character model settings.

You can find how to do it in https://dev.to/insthync/create-game-with-mmorpg-kit-part-2-map-and-first-character-54dl

**Comment by SkyDuckzx** [comment]
Im trying to Use Custom Player Controller , can you give me some guide where to start or what to do ?

**Comment by insthync** [comment]
Controller for movement? not only animation?

**Comment by SkyDuckzx** [comment]
Movement controller with Animation, inside the RPG Character mecanim pack  had player controller and i wanted to implement that or use with it, but have no clue how to do it

**Comment by insthync** [comment]
For animations, you have to make a character model class which inherit from `BaseCharacterModel`, you can find example here: https://github.com/insthync/UnityMultiplayerARPG_InvectorCharacterModel

For movement control, you have to make a entity movement class which implement `IEntityMovement` interface, you can use `CharacterControllingEntityMovement`, `NavMeshEntityMovement` as an example.

**Comment by SkyDuckzx** [comment]
and what about the character object? what i need to put in the component?

**Comment by insthync** [comment]
You character model and your entity movement component

**Comment by SkyDuckzx** [comment]
sorry im kinda new to this , but i have the character controller scripts, character input script ,character movement script and weapon controller script so which one should i be  edit to work with the kit?

**Comment by insthync** [comment]
I can't tell the exact answer, have to check their scripts, I won't do it.
