### ISSUE TITLE
Error importing new version (1.72)

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1315]
I got this error when importing the new version.

![image](https://user-images.githubusercontent.com/56885137/143869494-5d7717b5-b825-49ca-ba11-8bf369af701f.png)

**Comment by moepi2k** [comment]
Remove ChatNetworkManager.cs

p.s i net recomment import new version into project. i always would remove UnityMultiplayerARPG folder and import the one from new version.
use separate folder for ur stuff (prefabs, devext, partials and so on)

**Comment by juniormagalhaes** [comment]
> 

I just did this, I'm opening the project to see

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/147-how-to-update-to-new-version
