### ISSUE TITLE
[BUG] Pet system bugged

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1317]
I have tested in fresh project to be sure that is a bug , so when you go so far , pet moving so fast like a ghost .. watch the video : https://youtu.be/6LO2XvsN0rg
also when the pet face an object and the character go to the back , pet get disappear and get 3x red errors .. check the video : https://youtu.be/TgW0r3AqMCU
note : any kind of pet > item , skill .. any kind have that issues

**Comment by insthync** [comment]
The 2nd video is occurring because it can't find path to that position

**Comment by RunOrDi3** [comment]
ahh kk , i noticed that .. first video is with fresh project

**Comment by insthync** [comment]
Fixed, please wait for the next update

**Comment by moepi2k** [comment]
https://gyazo.com/99f7023ab16dd8219f5b2b8381b830f8
it was when monster reach MaxFollowSummonerDistance, monster not porting back to owner

**Comment by insthync** [comment]
Fixed

**Comment by RunOrDi3** [comment]
thank you so much

**Comment by insthync** [comment]
Fixed in 1.72b
