### ISSUE TITLE
[Question] Melee Attacking Impact Effects (what component is needed)

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1319]
![image](https://user-images.githubusercontent.com/90834568/144025167-341ab856-23fa-4752-9dd6-f116474ad8b1.png)
What entity or component do we need to attach to a game object be able to drag it to Impact Effect slot?

As we can attach missile damage entity to missile effect and drag it to missile attack slot.
But I cannot find impact component in the kit.

**Comment by insthync** [comment]
![Screenshot_815](https://user-images.githubusercontent.com/2697550/144025971-53b9086e-5526-43ed-a4e3-d41107e89073.png)

**Comment by DevMMORPG01** [comment]
Thank you Suri. You're the best.
