### ISSUE TITLE
Combat text

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#132]
is it possible to display text combat (normal damage, critic, heal etc ...) only for its own player?  when many players are nearby, there is a lot of text fighting and this overloads the UI.

**Comment by insthync** [comment]
Noted

**Comment by Syrus198327** [comment]
You can remove the ui follow world position script from the from the combat text ui found in the gamplay folder. That script puts it in world space so everyone see its

**Comment by insthync** [comment]
You will see settings about this in next update

**Comment by insthync** [comment]
I've added `Combat Text Distance` config to `Game Instance` in 1.52, try it :)
