### ISSUE TITLE
errors on update 1.72b

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1322]
I got these when updating any advice here is appreciated not sure why this is happening  thank you!

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\ChatNetworkManager.cs(36,33): error CS0115: 'ChatNetworkManager.Awake()': no suitable method found to override

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\ChatNetworkManager.cs(9,84): error CS0535: 'ChatNetworkManager' does not implement interface member 'IAppServer.ClusterServerAddress'

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\ChatNetworkManager.cs(9,84): error CS0535: 'ChatNetworkManager' does not implement interface member 'IAppServer.ClusterServerPort'

**Comment by insthync** [comment]
- https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/147-how-to-update-to-new-version
- https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/000-changelog?id=mmo-structure-changes

**Comment by Sour-J** [comment]
thanks the first link worked no more errors.. but the second link you posted is just the changes right? I dont have to do anything else or to the server config?

thank you for your time. I appreciate you

**Comment by insthync** [comment]
There is no config for chat server, but it has only new config for cluster server is cluser server port

https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/027-server-configs

**Comment by Sour-J** [comment]
Thanks last question I noticed on the digital ocean guide the server command your using didn't change shouldn't there be a cluster argument in the command line? 

Also is the websocket for browser games on the config? Can I remove that section from the config or do you recommend just putting false.

**Comment by insthync** [comment]
There is no argument to run cluster server

Should put it in the config file to make sure it will change setting in the component
