### ISSUE TITLE
1.72b max amounts

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1323]
Fresh install. Single player.
The maximum amount of materials is not displayed when the character has enough materials for crafting, etc.
![image](https://user-images.githubusercontent.com/47291794/144294182-0200d9b1-a7ec-4879-b65c-61627ae8e727.png)
![image](https://user-images.githubusercontent.com/47291794/144294502-62a214fd-97fa-4bbf-8ce7-95535ec950b4.png)

**Comment by LordPhrozen** [comment]
Yes, still being able to see how many I'm going to use is key. If I have 100 RESOURCE, knowing if the craft is going to use all 100, 10 of it, or 1 of it, is still good information.

**Comment by moepi2k** [comment]
where is the problem? you see the amount. you need 2 wood and 2 stones. so you have 2 woods and 2 stoned are still required

**Comment by LordPhrozen** [comment]
Oh, so if I had 100 wood, it would still show 2?

**Comment by moepi2k** [comment]
yes

**Comment by DimasjkTV** [comment]
> yes



> where is the problem? you see the amount. you need 2 wood and 2 stones. so you have 2 woods and 2 stoned are still required

the problem is that it should show 2/100 for example. As it was before the new version.

**Comment by DimasjkTV** [comment]
![dBIPjDGPHHQ](https://user-images.githubusercontent.com/47291794/144325658-c1b93c6f-8862-46fc-86d7-023f652cebf9.jpg)

**Comment by insthync** [comment]
![Screenshot_826](https://user-images.githubusercontent.com/2697550/144327455-22566f0e-931d-4fe3-abae-e2a66403cabc.png)

Try change `Format Key Simple Amount` to the format which has one amount input.

Or Uncheck  `Use Simple Format If Amount Enough` to make it shows {amoun}/{max amount}

**Comment by insthync** [comment]
Just uncheck `Use Simple Format If Amount Enough`

**Comment by insthync** [comment]
I pretty upset when someone request to improve something, then I did it and conflict with other.

**Comment by DimasjkTV** [comment]
> Just uncheck `Use Simple Format If Amount Enough`

It works. Thanks!
