### ISSUE TITLE
UICharacterSkills Filtering Performance

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1326]
https://gyazo.com/07498b7de0cc255e5ce292bf57d18a8e

i have a toggle to open the ui, which sorts the required skills.
when i start game and open the ui for filtering skill, it has a lag for 50-100ms, only for the first time when u open it. after that it works.
strange is in a build the delay is bigger then in editor. like 100-200ms

can u check this?

**Comment by DimasjkTV** [comment]
Also with crafting with few categories for crafting recipes. When we switch between categories, there is a slight lag.

**Comment by insthync** [comment]
If there is no one requesting a new feature within next week, I will start improve it :D

**Comment by moepi2k** [comment]
xD 
you should have someone to handle this git to filter it before somehting is posted :) many things can be solved by community

**Comment by insthync** [comment]
Today I see a new feature request again :D, let's see next week.

**Comment by moepi2k** [comment]
Thats why i mean xD the community grows fast. Hard to stop them all posting here and ask for features.

But hey we all appreciate your great work mate.

Btw, check ur discord when u can, i send u something :)

**Comment by moepi2k** [comment]
also this works now. great thanks
