### ISSUE TITLE
Enemies are not aggressive and my character dies every time I relogin to the game. 

### ISSUE THREAD

**Issue by vladyslu** [suriyun-production/mmorpg-kit-docs#1327]
My enemies are not aggressive despite I made them aggressive in the enemy database. 
Also, I die from fall damage when I reload the game(login and out.)
What did I do wrong?

**Comment by insthync** [comment]
After you made changes, did you reupload the server?

**Comment by vladyslu** [comment]
> 

offline mode. 
I think that it respawns me in the same place and very high on the ground.

**Comment by insthync** [comment]
- Is the monster in safe-area?
- I don't know about your map

**Comment by DevMMORPG01** [comment]
Probably the monsters are aggressive but inside a safezone.

**Comment by insthync** [comment]
No enough info to guess whats happening

**Comment by vladyslu** [comment]
> No enough info to guess whats happening

the enemy is not that big of an issue. However, the player dying every time I log in is an issue. Can it be because it is lower than 0 Y position? 
Where can I check how it positions the player at the start of the map? ( i mean loading an existing character)

**Comment by insthync** [comment]
You can just use debug .log to show position in start function to see where it was spawned

**Comment by vladyslu** [comment]
> You can just use debug .log to show position in start function to see where it was spawned

thank you. It makes sense.  
do you know how I can change the position it spawns the player after loading? 
Also, how can I change a default respawn position?

**Comment by insthync** [comment]
The first respawn position is spawning position when create a character then you can change respawn position by NPC Dialog

**Comment by vladyslu** [comment]
> 

oh. I see. Thank you. It makes a lot of sense. :D
and do you know how I can change or manipulate the save position(that position that the server saves when I close the game and loads when I open)?

**Comment by insthync** [comment]
`MapNetworkManager_PlayerActivity.cs` -> `Vector3 GetCurrentPosition(BasePlayerCharacterEntity playerCharacterEntity)`

**Comment by insthync** [comment]
May be the map ground position is less than `Dead Y` settings in `Map Info`

**Comment by insthync** [comment]
But it should not be the cause of the issues because you told that character dying only when entering the game.

**Comment by vladyslu** [comment]
> But it should not be the cause of the issues because you told that character dying only when entering the game.

yes. It is not the issue. Dead Y is -200. I die at -50.
