### ISSUE TITLE
[UI Issue]

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1328]
Whenever I do something on the UI. But I am not changing/touching the quest UI. I receive this error.
This error is from 1.71d and now on the latest 1.72b2

```
NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.UICharacterQuest.OnToggleTracking (System.Boolean isOn) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Quest/UICharacterQuest.cs:326)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <5e24da9c972e4f5888d47a5ad4e28202>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <5e24da9c972e4f5888d47a5ad4e28202>:0)
UnityEngine.UI.Toggle.Rebuild (UnityEngine.UI.CanvasUpdate executing) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Toggle.cs:132)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:181)
UnityEngine.UI.ScrollRect:LateUpdate() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs:834)
```

**Comment by DevMMORPG01** [comment]
![image](https://user-images.githubusercontent.com/90834568/144391221-812bf1b9-22ce-40ad-8ec2-59d903318448.png)
Fresh Kit have this error.
How to get the error?

Just open the MobileCanvas and show hide any prefab and save and run the game again.

**Comment by DevMMORPG01** [comment]
![image](https://user-images.githubusercontent.com/90834568/144392492-b76fe98d-4e95-44c9-88e2-d8af75f95dcc.png)
I remove the Event UICharacterQuest and no more error and the quest tracking is still working. So I don't understand If what I did was right of removing the event.

**Comment by insthync** [comment]
No, it is not, and it should not have that error, as I checked the codes
