### ISSUE TITLE
1.72b2

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1329]
1.72b2 (2021-11-30)
Bug Fixes
Fix MobileSwipeArea not working properly.
=================================

Everytime I update I use my old mobile canvas but you updated it and I don't know if my old mobile canvas inherit the fix or need to use the new mobilecanvas.

So regarding this change log
**Fix MobileSwipeArea not working properly.**
Can we extract the specific component for this? And paste to our old mobile canvas?
Or we need to customize the default canvasgameplaymobile?

**Comment by insthync** [comment]
I didn't change CanvasGameplayMobile, you can notice in import window

**Comment by insthync** [comment]
This is pretty non sense

**Comment by DevMMORPG01** [comment]
Sorry for asking but the reason I cannot see the changes and I ask here is to be sure because I import fresh project and copy paste it manually by folder and not using Unity Editor. So I cannot see the changes in the Unity import window. 
But I will try to do it using the import window so I can see the changes from now on.

**Comment by insthync** [comment]
Next time I will upload the package which exclude demo files
