### ISSUE TITLE
Skills Not Learned when PlayerCharacter skill lvls are already set at 1

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#133]
if u set ur playercharacters skills at lvl 1 to be able to use them instantly when u create new character at lvl 1 u cant. it tells u skill not learned.. this is cuase Skills are only learner when u Click AddSkill/ Leveup Skill in game.. it doesnt check if skills are already lvl 1 since character creation.. this problem is new.. i think the Skill.IsLearned bool came out in 1.50B 
u cant assing the skill or use it .. it sees it as lvl 0 untill u lvl it up again manually

https://www.youtube.com/watch?v=rKsEA-JxhLw&feature=youtu.be

(if possible can the codefix be shared here)

**Comment by insthync** [comment]
Fixed in 1.50c, I also check the function name from IsLearned to IsAvailable
