### ISSUE TITLE
Building not working probably

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1330]
it was working , i cant build anything above my map .. i use the same ground objects in another scene and it works fine .. i dunno whats wrong >>> https://www.youtube.com/watch?v=tBaAKjZ9vOA
i have tested in fresh project and building works fine .. but in mine , i dont know whats wrong in my map

**Comment by insthync** [comment]
You may try debugging `BuildingEntity` -> `CanBuild()` to find why it can't build.

**Comment by RunOrDi3** [comment]
@insthync it always give me red (cant build here) in this map .. but in other maps works fine
![2](https://user-images.githubusercontent.com/64667641/144457516-668cd510-a8ef-4139-92ec-2b3bc7c42d86.jpg)
![1](https://user-images.githubusercontent.com/64667641/144457523-a0ea24fd-f150-4fa6-ab8d-a92431c5753f.jpg)

**Comment by RunOrDi3** [comment]
@insthync all ground's objects have building area component
![3](https://user-images.githubusercontent.com/64667641/144459703-44cfdefb-7b6a-454c-9f00-7468d0794f8f.jpg)

**Comment by moepi2k** [comment]
I had same issue many times with my terrain, changed nothing. Mde new scene new terrain add. Copy paste build arena from other scene and everythings fine with same building parts.

I debuged, but cant find the reason, only solution was tonremove whole terrain and create new one. Very odd

**Comment by insthync** [comment]
Or may try to add Rigidbody which is kinematic and has no gravity.

**Comment by moepi2k** [comment]
To the terrain? Or the object where buildingarea is attached?

**Comment by insthync** [comment]
If BuildingArea attached to terrain then attach to that terrain too

**Comment by moepi2k** [comment]
Cool i will try, thank you

**Comment by RunOrDi3** [comment]
@insthync Doesn't work with rigidbody
![1](https://user-images.githubusercontent.com/64667641/144489538-e40b7fe0-7a16-42bf-b5dc-fe7f3e957662.jpg)

**Comment by insthync** [comment]
Yeah, I guess that it might not work too.

**Comment by RunOrDi3** [comment]
i took the whole map as a prefab to a new scene but it doesnt work also

**Comment by insthync** [comment]
Or just make an appointment for TeamViewing

**Comment by RunOrDi3** [comment]
ok i will be very happy if you can :)

**Comment by insthync** [comment]
Send your TeamViewer info to my email: ittipon.bay@gmail.com

**Comment by RunOrDi3** [comment]
i have sent them to you @insthync
