### ISSUE TITLE
Cannot see changes in MySql

### ISSUE THREAD

**Issue by vladyslu** [suriyun-production/mmorpg-kit-docs#1332]
my friends can connect to the game and everything works fine. However, when I try to check MySQL tables it shows only one character and almost no info. What can be wrong?

**Comment by insthync** [comment]
Are you sure you running a server that connects to MySQL not SQLite?

**Comment by vladyslu** [comment]
yes
![image](https://user-images.githubusercontent.com/64493917/144484015-f293ad1a-9b0f-468a-b6ba-4b78fc11acf5.png)

**Comment by vladyslu** [comment]
ok. I guess I cannot fix this one. I try many things and MySQL does not work. I will have to go back to sqlite and learn how it works because I cannot even make anyone a game master...
Stuff happens :D
