### ISSUE TITLE
Problem wearing left hand items

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#1333]
I add a left hand item to the game, I can't wear it on mobile. Also, I can't drag and wear the item on mobile.

**Comment by insthync** [comment]
Why it can't be equipped? It has no message when it can't equip?

I intend to make it can't drag because it will conflict with scroll view.

**Comment by CLAXES** [comment]
It gives error "Invalid equip position for left hand equipment"

**Comment by insthync** [comment]
![Screenshot_831](https://user-images.githubusercontent.com/2697550/144506650-f721ad4e-af2a-4c83-8c1b-eb04fd213569.png)

Set this correctly?

**Comment by insthync** [comment]
Okay, I found the issues

**Comment by CLAXES** [comment]
I guess it's because of the weapon type.

**Comment by insthync** [comment]
In `ClientInventoryHandlersExtensions`

```
                else if (equippingWeaponItem.GetEquipType() == WeaponItemEquipType.OffHandOnly)
                {
                    handlers.RequestEquipWeapon(new RequestEquipWeaponMessage()
                    {
                        nonEquipIndex = nonEquipIndex,
                        equipWeaponSet = playerCharacter.EquipWeaponSet,
                        isLeftHand = true,
                    }, responseEquipWeapon);
                }
```

![Screenshot_832](https://user-images.githubusercontent.com/2697550/144507481-ffee2cf1-cc41-4e64-a460-1f035842f98a.png)
