### ISSUE TITLE
[BUG] with corpse looting UI 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1336]
When you kill  an enemy and check the corpse , ui window shows a double of the items but you pick only 1 item from each kind  .... for example : when the monster drob bow and sword , ui window will show you 2x bows and 2x swords  but when you loot them you will get only 1x bow and 1 sword .... check the video >>> https://youtu.be/qiTVJKNA8GI

**Comment by insthync** [comment]
It's already fixed

**Comment by RunOrDi3** [comment]
thank you , in next update ?

**Comment by insthync** [comment]
In 1.72b

**Comment by RunOrDi3** [comment]
@insthync unfortunately im using latest version , issue happen when you build the games and test with local but when you test in editor its fine

**Comment by moepi2k** [comment]
can confirm, only happen in build

**Comment by RunOrDi3** [comment]
@insthync this happen in build only

**Comment by insthync** [comment]
Fixed in 1.72c

**Comment by RunOrDi3** [comment]
thank you :)
