### ISSUE TITLE
Passengers unable to get on a mount

### ISSUE THREAD

**Issue by ApolloGM** [suriyun-production/mmorpg-kit-docs#1339]
The player trading (Deal) pops up when you try to get on a 2 person mount preventing the 2nd person from mounting on the passenger seat.

**Comment by ApolloGM** [comment]
to replicate, make a 2 person mount with 2 seats.
One player gets on the mount
Second player tries to get on the same mount and a deal dialog pops up preventing the mounting process.

**Comment by insthync** [comment]
It is Deal dialog or request dialog which can contain deal, request to join party, request to join guild.

If it's a request dialog, that is normal, it uses the same key for dealing and riding a vehicle, you can double click on a vehicle to ride.

Any idea?

**Comment by ApolloGM** [comment]
I will try the double click thanks. Will let you know. Great work!

**Comment by ApolloGM** [comment]
double click worked, thanks. Though the issue of mount location not persisting through log off, still persists lol. I will close this one.
