### ISSUE TITLE
Cant add building parts to hotkey panel.

### ISSUE THREAD

**Issue by Hellwood** [suriyun-production/mmorpg-kit-docs#134]
I updated this morning to the newest version and afterward, I'm no longer able to add build items to the hockey panel. So there's no way to build.

**Comment by insthync** [comment]
Okay, will fix it now

**Comment by insthync** [comment]
It's about hotkeys filter, You can fix it by edit your UI Scene Gameplay by drag in empty scene or double click on the prefab then find component `UICharacterHotkeys` then add `Building` to `Filter Item Types`

![Screenshot_178](https://user-images.githubusercontent.com/2697550/68904194-f320d180-076f-11ea-86cc-cf20cdb81166.png)

**Comment by Hellwood** [comment]
Thank you sir
