### ISSUE TITLE
I got this error after the update for the websocket. Before wasnt showing this. 

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1341]
![image](https://user-images.githubusercontent.com/12781104/144726625-0dd7d8ea-1f8c-48d8-9a4f-805c655a4e67.png)
Sorry to bother again but I get this problem in my webgl. This error appears just after I update the kit.

**Comment by insthync** [comment]
![Screenshot_835](https://user-images.githubusercontent.com/2697550/144727328-5e237469-19f7-4819-9dc9-d9da2c427f2a.png)

![Screenshot_836](https://user-images.githubusercontent.com/2697550/144727329-417f5273-d7d9-4e8d-bdeb-8e6210bf8aac.png)

Try setup like this.

**Comment by MosesGomez** [comment]
Got the same error

**Comment by insthync** [comment]
Change to uses Unity 2021.2

**Comment by MosesGomez** [comment]
> Change to uses Unity 2021.2

You mean to upgrade my unity to 2021.2?

**Comment by insthync** [comment]
Yes

**Comment by MosesGomez** [comment]
> Yes

Got it, Ill upgrade

**Comment by MosesGomez** [comment]
Upgraded and shown this errors 
![image](https://user-images.githubusercontent.com/12781104/144729313-641bff86-586d-4002-88c8-fe299dc28971.png)

**Comment by MosesGomez** [comment]
I changed to net 2.1 framework in project settings and changed to this one.
![image](https://user-images.githubusercontent.com/12781104/144729896-5e82ff3a-577f-496b-aa0d-719cdaa168be.png)

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

**Comment by MosesGomez** [comment]
> https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

Thank you so much, Should I use net 2.1?

**Comment by insthync** [comment]
Yes

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144908695-94904bde-1857-40a5-b177-583977b620c6.png)
Everything worked but now this error shown when clicking connect in the main menu

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144909244-42945255-7953-4306-bbd7-c6743ccb663b.png)
Also before loading the game I have this error shown

**Comment by MosesGomez** [comment]
I turned off the server to see if server was causing the error and was the same.

**Comment by insthync** [comment]
Open `/Assets/MultiplayerARPG/Core/LiteNetLibManager/Plugins/WebSocket/WebSocket.jslib` replace `Pointer_stringify` to `UTF8ToString`

**Comment by insthync** [comment]
https://github.com/insthync/LiteNetLibManager/commit/2e19781b71b3649114b4050801f362e820baedd8

**Comment by MosesGomez** [comment]
Still getting the same error after changed that

**Comment by insthync** [comment]
the "Pointer_stringify is not defined" again ?, how it will still show that message if it was removed from the code file?

**Comment by MosesGomez** [comment]
I cant tell. 
![image](https://user-images.githubusercontent.com/12781104/144946459-d21c0001-2f98-4807-8df3-f1d7eedf3530.png)
![image](https://user-images.githubusercontent.com/12781104/144946473-5fab1a3c-4dfd-4c32-ac11-cb7314d4404f.png)

**Comment by insthync** [comment]
Scroll up, I can't see the readable messages

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144946650-878b9079-c5ee-474d-9919-72569ec3f23f.png)
Sure, sorry

**Comment by insthync** [comment]
Try CTRL + F5 to refresh with cache clearing

**Comment by MosesGomez** [comment]
It works, thank you so much. I just have one question more, In this unity version I have 2 types to build server (Dedicated server and the normal one, linux) Which should I select? I have a VPS

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144953749-bb03071c-dfd0-43b9-9a53-43d92d1430a4.png)
This is what I mean.
![image](https://user-images.githubusercontent.com/12781104/144953772-c633b363-998f-4a84-b3c4-b5820900b864.png)
Using the normal one this happens and when using dedicated server it keeps running forever

**Comment by insthync** [comment]
Should use dedicated server, what do you about "it keeps running forever?"

**Comment by MosesGomez** [comment]
> Should use dedicated server, what do you about "it keeps running forever?"

When running the game in the vps it starts writing a lot and never ends

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144960960-c9c473eb-9700-4def-b7c1-af738a6c4da8.png)
Keeps like this and never stops

**Comment by insthync** [comment]
An audio error never stop?

**Comment by MosesGomez** [comment]
> An audio error never stop?

Repeats a lot of errors and info. and never stops. Ill take a look at some of my audio scripts

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/144974361-28ededde-ddd4-49bf-aa17-58ed47618fe7.png)
And it causes that I cant log in

**Comment by MosesGomez** [comment]
I still cant get able to run the server well.

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/145268834-dc837a20-a04d-4458-bdec-a3ac4e0a49bf.png)
Settings and using centos 8 as VPS

**Comment by insthync** [comment]
You may try build server which uses `Mono` as scripting backend, `.NET Framework` Api compatibility

And set server config to make it runs the server with web socket transport

**Comment by MosesGomez** [comment]
> You may try build server which uses `Mono` as scripting backend, `.NET Framework` Api compatibility
> 
> And set server config to make it runs the server with web socket transport (by just set config file)

You mean uploading the config file into the server? Not using the objects inside the unity project?

**Comment by MosesGomez** [comment]
./Game.x86_64 -startMapSpawnServer -spawnExePath "Path of your execution file such as /Game/Game.x86_64" -startCentralServer -startDatabaseServer -machineAddress "192.168.1.102" 

This command to start server is updated?

**Comment by insthync** [comment]
> > You may try build server which uses `Mono` as scripting backend, `.NET Framework` Api compatibility
> > And set server config to make it runs the server with web socket transport (by just set config file)
> 
> You mean uploading the config file into the server? Not using the objects inside the unity project?

Yes

> ./Game.x86_64 -startMapSpawnServer -spawnExePath "Path of your execution file such as /Game/Game.x86_64" -startCentralServer -startDatabaseServer -machineAddress "192.168.1.102"
> 
> This command to start server is updated?

Just has no -startChatServer anymore.

**Comment by MosesGomez** [comment]
Really sorry but still the same error :(

Config priority from high to low is Command Line -> Config files -> Component data (I should change something based on this)

**Comment by MosesGomez** [comment]
It seems that in server something is looping or that it restarts the launch everytime as I see almost the same errors

**Comment by MosesGomez** [comment]
https://user-images.githubusercontent.com/12781104/145449504-24c4e5e7-9442-4710-88d7-bad49c1c2854.mp4

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/145482751-76682f4c-c0f3-412e-b15a-1699aa167437.png)
I dont know if this is normal but seems that there is a lot of this messages in the last try to turn on server

**Comment by insthync** [comment]
Hmm, weird thing is map-server processes are being killed instantly

**Comment by MosesGomez** [comment]
> Hmm, weird thing is map-server processes are being killed instantly

Cant tell why

**Comment by insthync** [comment]
Yes

**Comment by MosesGomez** [comment]
Mmm I think I have tried everything and isnt working. Cant really tell why

**Comment by insthync** [comment]
I am available at Saturday, let's make an appointment to looks how you did by using TeamViewer

**Comment by MosesGomez** [comment]
> I am available at Saturday, let's make an appointment to looks how you did by using TeamViewer

Sure its fine. There is something that I can do? So Ill still try with that.

**Comment by MosesGomez** [comment]
In cluster address shoul I set the IP of the server right?

**Comment by insthync** [comment]
Yes, all if you runs all server in 1 device, you set it to 127.0.0.1

**Comment by MosesGomez** [comment]
> Yes, all if you runs all server in 1 device, you set it to 127.0.0.1

That could be the problem

**Comment by MosesGomez** [comment]
Please let me know the hrs where you are going to be available tomorrow. please

**Comment by MosesGomez** [comment]
Or let me your email please

**Comment by insthync** [comment]
My email ittipon.bay@gmail.com

**Comment by MosesGomez** [comment]
Sended a message

**Comment by insthync** [comment]
Which version of Linux are you using?

As I try 18.04 it works properly but 20.04 not

**Comment by MosesGomez** [comment]
[image: image.png]
I'm using 16.04 that could be the problem?

**Comment by MosesGomez** [comment]
Tried with 18.04 ubuntu and still the same

**Comment by MosesGomez** [comment]
If there is something that I should change let me know please.

**Comment by MosesGomez** [comment]
I changed my unity version to 2021.2.6f1 and server now works. but now when clicking connect in the webgl version nothing happens and if I double click sends the client already connected in the console error.

**Comment by MosesGomez** [comment]
Now gets stuck here 
![image](https://user-images.githubusercontent.com/12781104/146440703-213f5fbf-7898-411d-be7c-364c191877f9.png)

**Comment by MosesGomez** [comment]
![image](https://user-images.githubusercontent.com/12781104/146448186-12c008d2-b8f7-4b79-a7e8-2d48c471bc7b.png)
Result after loading some time

**Comment by MosesGomez** [comment]
This just happens with webgl version. If tried in other, I can log in fine

**Comment by insthync** [comment]
Let's check it again, tomorrow (Saturday)

**Comment by MosesGomez** [comment]
Now I just need to fix that webgl problem

**Comment by MosesGomez** [comment]
Where I can enter to login scene but cant create any account

**Comment by insthync** [comment]
Are you currently available?, let's check at your PC again.

**Comment by MosesGomez** [comment]
Sure, just give me 15 minutes please

**Comment by insthync** [comment]
Okay

**Comment by MosesGomez** [comment]
Im ready

**Comment by MosesGomez** [comment]
671 846 041
cbjdrfdk

**Comment by MosesGomez** [comment]
I upload to web but there I cant connect. Ill mail you the link so you can
test
