### ISSUE TITLE
delay in using the skill after cooldown

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1342]
I set the 0.5s colldown, when I click right after cooldawn ends the character doesn't cast the skill again, sometimes I have to press the key 3 times to be able to cast the skill again, even though the colldown time is over.

and sometimes the cooldown loads twice in a row

https://gyazo.com/5f810898c4ddb84c7ff101c75f076829

**Comment by insthync** [comment]
Try 1.72c

**Comment by juniormagalhaes** [comment]
> 

continue
