### ISSUE TITLE
Suggestion: FPS lock for settings.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1349]
Can you add FPS lock to settings? In previous versions I used my script, but in newer versions it does not save FPS settings to playerpref after exiting the game. Most likely this is due to the fact that in recent versions you added new game settings + FPS changes in the first scene.

**Comment by moepi2k** [comment]
suri told no more suggestion so he have more time for bugfixed and improvements. do it yourself...
