### ISSUE TITLE
Unable to attack monster if monster moves

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#135]
Windows 10
MMO Mode
1.50c

-Rarely, if the player double-clicks to attack an Orc and at the same time the Orc decides to move away.
-Orc will move away but is still hit once.
-Orc stops, turns back to player and starts attacking player.
-Player cannot attack Orc until the player moves (updates their position).

Difficult to reproduce but might be indicative of another issue.

**Comment by insthync** [comment]
Okay, will fix it now

**Comment by insthync** [comment]
Fixed in 1.51, try it, if it's still not working well, then reopen this issues again.

**Comment by Hawkadium** [comment]
Fixed in 1.51
