### ISSUE TITLE
Summary of MMO test and the experience

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1350]
hi suri,

as you already know. im testing alot since near alpha. i made already some post about that in the past, but get never some attention :P

as we tested alot in mmo heres a summary for few things which will be a gamebreaker.

1) https://gyazo.com/9ac98498883ef0c0109492b959293220 
when use server auth movmement. that you rubberband many times becuase client pos != server pos. here a simple example to reproduce.
just build a simple door. when you are fast open it walk through and immdediatly close it. at clients view you are already throught the door but at server not, so you always get rubberband back.

this can happen everywhere, even when u walk near at a corner, on client you walk but at server u stucked there and rubberband back. 

another thin is when you use MoveSpeedRateWhileAttack 0. when u attack while moving. client stops at diffrent position then server. so while  attacking. otther ppls see you always on diffrent position and can attack you, but at clients view you thing they hit the nothing. (i can make some more videos about that in server view it it helps)

2) Hit registration. this is a very very bad experience in mmo. i tested it on a local mmo machine. so means ping is very low and got this issue already.

i tested with Melee, Raycast and MissileDamageEntity, as i saw Lag compensation is only implemented for Melee and Raycast, but it seems bot not works proberly

most from kit use default monsters, so they  never noticed it, because monsters always run to the player, means server pos of the monster is always a bit nearer to the player as the clients really see. problem is when a moster walk away, in clients view you see the monster in the past as the server pos is already more far away -> problem your hits always miss, even with raycast and melee which uses lag compensation.

here 2 videos. the first one with fireball use MissileDamageEntity with a ExplodeDistance of 1.5 and even with that radius it wont hit because server pos of he monster is outside range.
https://gyazo.com/54edf9c720c839371edc5940d2f677bc
https://gyazo.com/03e52fc11713680721a066455b261b67

and in this case i use bow which uses raycast. you see when monster walk to player everythings fine but when it walks away, never hit
https://gyazo.com/f2b40ed98d012c64a4ca10225a8d191b

i hope this pos has some attention, because this is really a gamebreaker. player complains it.

and i hope theres a solution for it. when u need any more info. let me know. i will help as good as i can

**Comment by RunOrDi3** [comment]
i agree , it will break any game .. its important for get fixed

**Comment by insthync** [comment]
- It has a lag compensation added later
- Entity movement remade
- Character attack component remade (DefaultCharacterAttackComponent/LegacyCharacterAttackComponent/DefaultCharacterUseSkillComponent/LegacyCharacterUseSkillComponent)
Never get some attention?

**Comment by insthync** [comment]
My next plan is to make it batches movement and action packet and send at the same time.

**Comment by moepi2k** [comment]
> * It has a lag compensation added later
> * Entity movement remade
> * Character attack component remade (DefaultCharacterAttackComponent/LegacyCharacterAttackComponent/DefaultCharacterUseSkillComponent/LegacyCharacterUseSkillComponent)
>   Never get some attention?

hey do not get me wrong :) I just meant that I have made 1-2 posts about it, but have received no response.

you know that I appreciate your work :) 

just wanted to make a summary, because we momenten check everything from A to Z, therefore also so many git reports



> My next plan is to make it batches movement and action packet and send at the same time.

nice, im excited. thank for letting me know

**Comment by Fr-Coder** [comment]
I agree, I also noticed that sometimes the player goes out of sync (not so big desync, but can happen). Also, MoveSpeedRateWhileAttack wasn't working as expected in the past to me, but not tested again in newer versions.

> My next plan is to make it batches movement and action packet and send at the same time.

Very interesting 😍

**Comment by moepi2k** [comment]
> My next plan is to make it batches movement and action packet and send at the same time.

would this fix the movement issue, or also the one for attacking?

**Comment by Callepo** [comment]
> 

yea, attacking with movespeedrate while attacking you always desync

**Comment by Sour-J** [comment]
I also have these issues but the biggest game breaking one is desync often when you attack a monster it doesn't register the hits even with a amazing ping. the biggest thing is the desync the server is not registering the clients hits in sync. The server responds to the hits delayed it's gotten a little better but still exists.

**Comment by Sour-J** [comment]
So not sure if its related to anybody's issue here but my desync is gone in the dev build of my game. 

Monty told me the move threshold stopped the server sending small movements, which overtime can become big discrepancies.  He suggested to tighten up the Move Threshold on the Entity movement. It worked, I changed it to 0.001 It was set to 0.01 by default.  Hope this helps somebody here.
![unknown](https://user-images.githubusercontent.com/78616165/146504279-97d7dab8-6b13-44f7-b918-5fc061ab13a8.png)

**Comment by moepi2k** [comment]
i tested that and not solve my issue, i noticed even some other weird things.
2 clients connetcted, one attack a monster, the one who attack the monster has a complete diffrent view of the servers monster.
https://gyazo.com/61b472c6ead4240abc1899ab1da07b95
check when attacking the second rabbit

and here the problem with server auth movement when use MoveSpeedRateWhielAttack = 0
https://gyazo.com/531cbeab699d97de34b22d14e1dbd2ef

player always out of sync and correct in a really weird way. check when i walk left side, player correct first to the right side.
