### ISSUE TITLE
Playermovement stuck in SlowMotion and Sprint input not function

### ISSUE THREAD

**Issue by SkyDuckzx** [suriyun-production/mmorpg-kit-docs#1352]
Im currently using the lastest version 1.72C and it seem my player controller movement does not work after update the kits, the movement is like slow motion and the sprint input dont function only the jump input it working properly, i even try to clean install the kit and it still facing the same issues

**Comment by Fallen-Entertainment** [comment]
Solved in discord bad gamedata.

**Comment by insthync** [comment]
May I close this ?

**Comment by moepi2k** [comment]
Yea we solved in discord, user updated wrong
