### ISSUE TITLE
Virtual Method

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1354]
Could CanAttack() Method be virtual..
CanDoAction() is, but this is used for more than just attacking.. 
so making it check for example if weapon is sheated.. it will cuase every other interaction  to also stop..
there for if CanAttack() was Overridable, it would be straight to the point.. and much easier

**Comment by insthync** [comment]
Changed in 1.72c4

**Comment by Callepo** [comment]
> Changed in 1.72c4

Appreciate it man, ty
