### ISSUE TITLE
Broken Version 1.72C.2

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1355]
The version is broken, when u try to run in mmo and create a character, it simply times out and there is a Exception thrown.
![image](https://user-images.githubusercontent.com/7702658/145492986-70c7afd2-29b1-4c39-8a81-580729e61c62.png)

![image](https://user-images.githubusercontent.com/7702658/145493004-c9d7adb8-bc25-4592-8a4a-840872e87d06.png)

1.72C was fine tho

**Comment by RunOrDi3** [comment]
![2](https://user-images.githubusercontent.com/64667641/145496604-de71c2c2-b291-48d0-8c9a-39200fee4c3f.jpg)
![1](https://user-images.githubusercontent.com/64667641/145496607-1b4ab0f5-7a4f-4c7b-be77-6a671278653a.jpg)
It works fine to me , maybe you did something

**Comment by RunOrDi3** [comment]
ohh , nvm .. happened to me too when i logged out

**Comment by insthync** [comment]
Thank you for bug reporting, It was fixed in 1.72c3
