### ISSUE TITLE
New Weight Limit  system

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1356]
I think it would be great to have a 0 = no limit option.
for example, alot of people been reporting issue with the their characters being in slow motion
cuase their playerdata weight limit is 0 and any item with weight will cuase u to go slow.

i checked the script and there doesnt seem to be a off switch for this.  Ofc people can just put a weight limit on the playerdata.
or make sure all the items weight are 0.

But a 0 value means not being used would be nice

**Comment by insthync** [comment]
What if the user accidentally adds weight limit stats?

**Comment by insthync** [comment]
Change this will have to change inventory checking when increase item to inventory too.

**Comment by insthync** [comment]
Added in 1.72c4

**Comment by Callepo** [comment]
> What if the user accidentally adds weight limit stats?

they gotta pay attention to what they doing lol, than its actually their fault and not some random thing they didnt know bout

Thank you for quick work , appreciate u
