### ISSUE TITLE
[BUG] Move speed rate while attacking in monster character

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1357]
I have set Move speed rate while attacking in monster character scriptable to 0 and monsters still moving abit while attacking when your character moves away .. https://youtu.be/JSnbvP43nCE >> thats in my game .
i have checked also default kit demo and i found it also and here is the video >> https://youtu.be/QfjT4Us_mJw

**Comment by DimasjkTV** [comment]
Yes. I posted this too
https://www.youtube.com/watch?v=BnzAyLaTb2c

**Comment by insthync** [comment]
Try add set speed code to  `NavMeshEntityMovement` update function like this:
```
CacheNavMeshAgent.speed = Entity.GetMoveSpeed();
```

![Screenshot_856](https://user-images.githubusercontent.com/2697550/145667909-a53e2ea5-b312-413b-8574-eeacf5a35c81.png)

**Comment by DimasjkTV** [comment]
> Try add set speed code to `NavMeshEntityMovement` update function like this:
> 
> ```
> CacheNavMeshAgent.speed = Entity.GetMoveSpeed();
> ```
> 
> ![Screenshot_856](https://user-images.githubusercontent.com/2697550/145667909-a53e2ea5-b312-413b-8574-eeacf5a35c81.png)

Seems like works for me

**Comment by RunOrDi3** [comment]
> Try add set speed code to `NavMeshEntityMovement` update function like this:
> 
> ```
> CacheNavMeshAgent.speed = Entity.GetMoveSpeed();
> ```
> 
> ![Screenshot_856](https://user-images.githubusercontent.com/2697550/145667909-a53e2ea5-b312-413b-8574-eeacf5a35c81.png)

i have added it but i still have the issue

**Comment by RunOrDi3** [comment]
Any solution ?

**Comment by RunOrDi3** [comment]
fixed it
