### ISSUE TITLE
BUG? TargetFramerateSetting script

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1359]
Fresh install. Single player.
With this spcript I added a choice of FPS limits to the game settings. Chose 30 and 60 FPS. If we exit the game menu, then the setting is saved. If we leave the game completely, then the setting is not saved.
![image](https://user-images.githubusercontent.com/47291794/145671905-d2ddb19f-3eb9-4719-b001-80df4ea08e69.png)

Other settings such as texture resolution are saved after a complete exit from the game.

**Comment by insthync** [comment]
That is part of sub project(which contains graphic setting component), for MMORPG KIT it won't apply framerate setting from that component yet, I will change it later.
