### ISSUE TITLE
Character Creation MMO

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#136]
Hi, I have a small Issue.. i used the Race Addon and Expanded it to make Race and Genders for my characters
And i went further with a Full Character Customization for my models.. 
It uses Face Items as Armortypes .. and equips them as u select which u want.. 
This works Perfectly in Singleplayer mode 
But in MMO it works well but when i click Create character it goes back to default in Characterlist ...
How can i send a copy of the Edited Playercharacter with the changed items i have equipped to be saved properly? 

Preview====== https://youtu.be/Ee_IeR8ey9s
THis how it looks when u finished Selecting how u wanna look 
![elfchar1](https://user-images.githubusercontent.com/7702658/68890409-18d1ba80-071f-11ea-95c7-b4ae64887c9c.JPG)

This how the Base Playercharacter looks

![Elfchar0](https://user-images.githubusercontent.com/7702658/68890384-05beea80-071f-11ea-9985-c6051bd4a366.JPG)

**Comment by Callepo** [comment]
Any General advice would work too.. u dont need to fix it just give me an idea ill do it myself

**Comment by insthync** [comment]
You to send equipment data to server when create charcter, you can use dev extension to serialize and deserialize extra data, for example

```
using LiteNetLib.Utils;

namespace MultiplayerARPG.MMO
{
    public partial class CentralNetworkManager
    {
        [DevExtMethods("SerializeCreateCharacterExtra")]
        public void SerializeCreateCharacterExtra_Custom(PlayerCharacterData characterData, NetDataWriter writer)
        {
            // Item 0 = Hair ?
            // Item 1 = Beard ?
            // Item 2 = Face ?
            // Item 3 = Eyebrow ?
            for (int i = 0; i < 4; ++i)
            {
                characterData.EquipItems[i].Serialize(writer); 
            }
        }

        [DevExtMethods("DeserializeCreateCharacterExtra")]
        public void DeserializeCreateCharacterExtra_Custom(PlayerCharacterData characterData, NetDataReader reader)
        {
            for (int i = 0; i < 4; ++i)
            {
                CharacterItem tempItem = new CharacterItem();
                tempItem.Deserialize(reader);
                characterData.EquipItems.Add(tempItem);
            }
        }
    }
}
```

That it is, let's try :) (codes above is untested)

**Comment by Callepo** [comment]
LOOOOOL worked perfectly thanks @insthync

**Comment by Callepo** [comment]
hmm
In the Character List it shows up fine . but when i click Start game it all dissapears again.. and exit in characterlist all is gone too...
maybe its not saving it in database properly? or loading it properly?
https://youtu.be/jsuOPw7qkrM

**Comment by insthync** [comment]
Not sure that you added an items to game database yet ?

**Comment by Callepo** [comment]
yea they all added, when loading and equipping im using the database
![databaseequip](https://user-images.githubusercontent.com/7702658/68969121-87c51700-07e4-11ea-8385-5f96aa401616.JPG)

**Comment by Callepo** [comment]
![itempic](https://user-images.githubusercontent.com/7702658/68972538-610ade80-07ec-11ea-81ea-04d8e9c095ad.JPG)

In the database 2 characters have the same exact item id's 
While they look completely different.. First pic is base char with base custom id...

2nd pic is Edited character with same base id...
![char1](https://user-images.githubusercontent.com/7702658/68972572-75e77200-07ec-11ea-897b-2c2bbe423b1b.JPG)
![char2](https://user-images.githubusercontent.com/7702658/68972574-77b13580-07ec-11ea-90cb-28032661933e.JPG)

**Comment by insthync** [comment]
Seems like an items does n't removed so it should not disappear, right ?

**Comment by Callepo** [comment]
it doesnt save the new items .. it saves the same old items in database instead of the new one i put when i create character.. 2 character.. 1 with 0 edit and 1 with edit have same items in database idk why

**Comment by insthync** [comment]
Did you set character item's amount more than 0 when create character ?

**Comment by Callepo** [comment]
This is Base Playercharacter
![Elfchar0](https://user-images.githubusercontent.com/7702658/68975481-a8489d80-07f3-11ea-9cb4-b98d9640c466.JPG)

this checks 4 items

Where else should be 4?
![4](https://user-images.githubusercontent.com/7702658/68975550-d8903c00-07f3-11ea-8337-de3ecb59fb7d.JPG)

**Comment by insthync** [comment]
Skip it, I think it's not about character item's amount.

I think it's because there are duplicate kind of items when deserialize because `SetNewPlayerCharacterData` will be called at server-side to fill start items from player character
So I want you to try to change deserialize codes to:
```
        [DevExtMethods("DeserializeCreateCharacterExtra")]
        public void DeserializeCreateCharacterExtra_Custom(PlayerCharacterData characterData, NetDataReader reader)
        {
            for (int i = 0; i < 4; ++i)
            {
                CharacterItem tempItem = new CharacterItem();
                tempItem.Deserialize(reader);
                characterData.EquipItems[i] = tempItem;
            }
        }
```

**Comment by Callepo** [comment]
![Fixed](https://user-images.githubusercontent.com/7702658/68976743-c9f75400-07f6-11ea-9b47-0f808937958c.JPG)
OFC,, we were adding items insteado f Replacing.., The first codes
characterData.EquipItems.Add(tempItem); 

its working now ill do some more testing .. but i believe its all good now ! Thank you so much.. 
I worked so long on this lol .. couldnt figure out how to make it work.. Almost changed the Core scripts lol.. Thank you again

**Comment by Callepo** [comment]
![2chars](https://user-images.githubusercontent.com/7702658/68977075-ac76ba00-07f7-11ea-97fa-3fb9b9358053.JPG)
Yup .. 2 different client both client work fine in multi
