### ISSUE TITLE
Guild Bank Bug

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1360]
I have the kit in production also on the newest update, I am getting a lot of reports from players all saying this:

"Tried to put some items into guild storage but couldn't. After I tried a couple of times my inventory disappeared. Logged out and logged back in and my inventory was gone and not in my storage."

(the guild npc is just default I haven't changed anything, this does not happen to everyone its just random I tried to reproduce but couldn't),

Not sure if there is a bug or not but im going to keep trying to reproduce and send you a video on how I did it

**Comment by moepi2k** [comment]
Was that with mysql or sqlite?

**Comment by Sour-J** [comment]
sqlite hasnt happened with mysql
