### ISSUE TITLE
如何修改商品列表的UI？

### ISSUE THREAD

**Issue by naughty66** [suriyun-production/mmorpg-kit-docs#1361]
请问这个位置的UI怎么更改？我在【CanvasGameplayMobile】里没有找到。
![image](https://user-images.githubusercontent.com/95008248/146011954-98ea2345-d725-434e-a6e2-48d582a25a9f.png)
![image](https://user-images.githubusercontent.com/95008248/146010455-7a49e73f-73e4-473b-8a72-fcda9933f43f.png)

**Comment by DevMMORPG01** [comment]
I think here

Prefabs > UI > Cash Shop

![image](https://user-images.githubusercontent.com/90834568/146141888-94863083-ab8f-4522-8840-579a8cb40ff3.png)

**Comment by DevMMORPG01** [comment]
![image](https://user-images.githubusercontent.com/90834568/146142074-0b15a692-a238-4145-8f9d-015cef278b49.png)
