### ISSUE TITLE
Cannot split items when moving to and from a chest

### ISSUE THREAD

**Issue by ApolloGM** [suriyun-production/mmorpg-kit-docs#1363]
UISceneGlobal.Singleton.ShowInputDialog(LanguageManager.GetText(UITextKeys.UI_MOVE_ITEM_TO_STORAGE.ToString()),

when you enter an amount here like 20/99 , it is ignored and full stack of 99 is transferred

**Comment by insthync** [comment]
Fixed in 1.72c5

**Comment by ApolloGM** [comment]
Thanks ! any chance you can tell what files were changed for this fix?

**Comment by insthync** [comment]
In `CharacterInventoryExtension.cs` -> `MoveItemFromStorage` and `MoveItemToStorage`

**Comment by ApolloGM** [comment]
many thanks you rock!
