### ISSUE TITLE
Partial Scripts

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1365]
Could theseScripts be Partials?
for Example PlayablecharacterModel is not partial but animatorcharactermodel is. 
AnimatorCharacterModel is, AnimationCharacterModel isn't
same with AnimatorCharacterModel2d is but CharacterModel2d isn't

**Comment by insthync** [comment]
Okay, I will changes all character model to be partial class

**Comment by Callepo** [comment]
ty
