### ISSUE TITLE
BUG: Item stacks in craft

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1366]
For example, we have 2 stacks of crafting resources in our inventory. The first stack on the list has 1/99 items and the second one 99/99. Crafting item requires 2 resources. So in the list of required resources, we see only the first stack and cannot craft an item, although we have the required number of items in our inventory. The game sees only the first stack in the list. 
![image](https://user-images.githubusercontent.com/47291794/146508875-aa37a477-cacd-4a70-afae-f43ec70cefad.png)
![image](https://user-images.githubusercontent.com/47291794/146508919-a02ad5ca-18e2-47b5-9d8c-9760661e8309.png)
![image](https://user-images.githubusercontent.com/47291794/146508939-005144da-194a-41b7-9c3e-24380d135054.png)

**Comment by insthync** [comment]
Fixed in 1.72c5
