### ISSUE TITLE
Small Suggestion about the UIQuest Dialog

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1367]
Its almost stupid of me to mention this but it is a very small tweak that i think will look better in most UI Work. 

![image](https://user-images.githubusercontent.com/71889605/146581071-86a04c4b-be2c-4754-9d12-45385c7c8327.png)

You have completed or ongoing on the quest name, but in reality this should probably be determined in the quest details.
Its not really a bug but something thats annoyed me for 2 years.. .lol.

Ill end up fixing it for myself its not a big deal or anything, but it would make for more attractive UI work.

Thanks for your time and perhaps considering this tweak.

personally im toying with the idea of doing this with color, completed quests greying out. 
If im just being crazy to even say this please feel free to tell me... lol.

Thanks again <3

**Comment by insthync** [comment]
Any suggestion for component's configuration implementation?, How about activating game objects for each kind of quests status?

**Comment by Fallen-Entertainment** [comment]
that actually sounds great.

**Comment by insthync** [comment]
In 1.73

- Add `questOnGoingStatusObjects` to `UICharacterQuest` it is list for game objects which will visible while quest status is on going.
- Add `questTasksCompleteStatusObjects` to `UICharacterQuest` it is list for game objects which will visible while quest status is tasks complete.
- Add `questCompleteStatusObjects` to `UICharacterQuest` it is list for game objects which will visible while quest status is complete.
- Add `questIsTrackingObjects` to `UICharacterQuest` it is list for game objects which will visible while quest is tracking.
- Add `questIsNotTrackingObjects` to `UICharacterQuest` it is list for game objects which will visible while quest is not tracking.
