### ISSUE TITLE
Mysql vs Sqlite

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1368]
i started an alpha yesterday. and had a very bad experience with mysql.
it really slow compared to sqlite. warping to a single map takes almost 3 seconds (sqlite takes <1s)

exchanging items to storaga like bank or player building storage taks 2 seconds.
any idea why this happen? and do you have an idea to convert mysql to sqlite?

**Comment by insthync** [comment]
You may try googling SQLite vs MySQL, it has many good answers, I actually recommend SQLite for testing purposes only.

**Comment by insthync** [comment]
The main reason that I don't recommend using SQLite for production projects is MMORPG KIT can run multiple instances of map-server and each map will connect to the database to work with data, when SQLite is writing file it will be locked so if you run multiple map servers, any map servers can be blocked by one map server to write players data.

**Comment by Sour-J** [comment]
I had the opposite happen, SQLite is not for MMORPG's and its vulnerable to hacks and injections (actually you told me that) Its only meant for dev servers or testing.
I switched to MYSQL and its the same speed if not better maybe your server doesn't have a lot of RAM? or SSD? I have 48gb ram and 2X SSD and its working great no desync either.

**Comment by Callepo** [comment]
Ram has nothing to do with it, i have a server with 64 gb ram, 32 Cores CPU, 1gbit up and down, and using mysql, player warping and overall processing is slower, things that require instant saving take more time, i  tried this on 2 different servers, 2 games of mine. the Kit itself doesnt even use more than 4gb so having anything above 16gb doesnt change anything. 

its thread Reliant.

I ran the same build 2 times, changing config file databaseindex , first time with sqlite , 2nd time with mysql. 
u can literally see a difference. Mysql is slower saving for some reason.

I understand Sqlite could be faster cuase there is no server involved, it literally just writing to file, but we shouldnt feel such a big difference. 
I will make 2 video's showing what me and @moepi2k  is saying
@insthync ill make a youtube video or someway to share it properly.

**Comment by insthync** [comment]
I actually have a plan to recreate services that can runs outside Unity such as Login, Register, Character Management, Map-server cluster and spawning, now it has only database manager https://github.com/insthync/mmorpg-kit-nodejs-db

**Comment by Callepo** [comment]
@insthync @Sour-J @moepi2k https://www.youtube.com/watch?v=r5V1DIS6vdY

i dont fully understand it, but i dont see why mysql can be so slow compared to Sqlite, mysql is normally fast af.
so im assuming it might be something in the kit cuasing it to hickup like that

**Comment by Callepo** [comment]
Same Version , Same build, Same server, Same connection, Recorded 2 minutes from eachother. 

Version 1.72c4

**Comment by insthync** [comment]
Hmm, may be because of async query codes

**Comment by Callepo** [comment]
when the version becomes stable ill do a full stress test again like my previous test with 1k Bot clients etc and make a report like ive done in the past so we can see the progression of the kit.
The last time the kit performance went up more than double lol.
from barely 200 players 1 map to almost 500

**Comment by Sour-J** [comment]
@Callepo @insthync 
Now I understand what he is saying it is slower SQLITE was instant and MYSQL does this delay on transactions look: https://gyazo.com/bf845e90377fcc6eca3d9ef232ec2675

Open player bank
Exchange items
or warping

**Comment by Callepo** [comment]
> @Callepo @insthync Now I understand what he is saying it is slower. SQLITE was instant and MYSQL does this delay on transactions look: https://gyazo.com/bf845e90377fcc6eca3d9ef232ec2675
> 
> Open player bank Exchange items or warping

already shared a video of them side by side above, but yes. like we said, its just mysql, and the reason is prolly what @insthync  just said, i checked the codes, 
SQLITE just does a void method.
![image](https://user-images.githubusercontent.com/7702658/146643197-abd9a0f7-218e-48cf-86cc-249179102911.png)

while MYSQL does a Async UniTask 
![image](https://user-images.githubusercontent.com/7702658/146643215-80bdcc9e-bd3d-4aa5-ba18-c41642dc7fd3.png)

This is  the main difference between the 2 like i mentioned, sqlite just writes to file, while mysql has more attached

**Comment by moepi2k** [comment]
> 

Yea and in this example you drag an drop each object. I can just right the item to put on storage or vise versa. And it wont work during the 2 seconds delay so means when u want to put 10 items in storage it takes 2 seconds. Always need to wait until item is exchanged. That make the experience really bad

**Comment by insthync** [comment]
[MMORPG_KIT_NonAsyncDatabase.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7740397/MMORPG_KIT_NonAsyncDatabase.zip)

Try this

**Comment by moepi2k** [comment]
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/7740774/Log_Database_Central_MapSpawn.log)

now i cant start server

**Comment by moepi2k** [comment]
sorry, removed post was an issue on my side xD
that package fixxed both problems. Great work. thank u very much <3
