### ISSUE TITLE
Addon

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#137]
Hello.. 
I turned the Character creator i made into an Addon for the kit and people who own the kit can download and use it like the other addons 
It was made the same way as ur Race Addon works .. thus im sharing no real game scripts 
All my scripts attach themselfs to ur scripts.

https://github.com/Callepo/MMORPG_CharacterCreationAddon

is this ok ? if not i will pull it down

**Comment by insthync** [comment]
It is okay :)

**Comment by Callepo** [comment]
thank you
