### ISSUE TITLE
[BUG] with Monsters 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1370]
Monsters attack animations works before they reach the player >> https://youtu.be/z1_g6zY1BIE 
it happens in mmo only when you build it , in single its fine .. Neomis have it also he confirmed it as a bug

**Comment by DimasjkTV** [comment]
Seems like this is same #1357

**Comment by RunOrDi3** [comment]
yes , its a bug in mmo
