### ISSUE TITLE
Some GameEffects no longer works

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1372]
https://gyazo.com/fa9b100151d94e81ed43878b1289b924
i upgraded to latest version and noticed that few GameEffects no longer works, i saw in patchnotes some changes.

as u can see in video, the effects are instantiated and called. but not visible an game view, only editor when play it.

any ideas?

p.s noticed that even after lifetime the effect not deactivate in hirarchy

https://gyazo.com/f541469a9c585b0277b3db250c013aa2
it just instantiate new effect instead of rotating

**Comment by moepi2k** [comment]
now i got this error when start game
NullReferenceException: Do not create your own module instances, get them from a ParticleSystem instance
UnityEngine.ParticleSystem+MainModule.set_playOnAwake (System.Boolean value) (at <51e7ba985b03449fa807cf0c6504869c>:0)

no longer possible to start/login, and even cant find what gameeffect throw that error

**Comment by insthync** [comment]
You mean you upgrade to Unity latest version?

Because I didn't change that codes, you may try delete codes in `FxCollection` -> `InitPrefab()` -> line 80 - 85

**Comment by moepi2k** [comment]
no still on 2021.1.23

upgrade to latest kit. reattaching gameeffect prefab solved the issue, weird :/
