### ISSUE TITLE
Waiting for the unreal engine version this year?

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#1373]
?

**Comment by insthync** [comment]
No, you don't have to wait, if it's released, you will see.

May I ask you, why you always waiting for this? Do you make any promises to anyone to make games with Unreal?

**Comment by insthync** [comment]
It is slow because it is a very low priority to me if it has more customer waiting for this, I might change my mind :P

**Comment by Callepo** [comment]
u can ignore him, lol, he does nothing but cause problems and talk shit to people
and now he demands shit too lol
