### ISSUE TITLE
 лицензия

### ISSUE THREAD

**Issue by asfaraon** [suriyun-production/mmorpg-kit-docs#1374]

**Comment by asfaraon** [comment]
Доброго времени суток. Я нашёл ваш продукт на assetstore и заинтересовался им. Возникли несколько вопросов которые я хотел бы уточнить перед приобретением...
1. После приобретения, каждый новый релиз я смогу получить или нужно будет покупать новую лицензию?  Если смогу - то какова продолжительность "свободного" получения обновлений?
2. Техническая поддержка продукта есть и какова ее продолжительность?

**Comment by insthync** [comment]
1. You don't have to buy a new license, it is free to update.
2. You can ask anything here.
