### ISSUE TITLE
Double Attacking Bug

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1375]
Hello, 
Found a issue where if you have an item thats automatic firing with shooter controller.

To reproduce, 
put on automatic weapon easier to make it use no ammo.
hold mouse click to attack with it
while holding mouse click use a active skill
continue to hold and it will turn your automatic attacks into double attacks instead of attacking once for each auto its two times for each auto making double attacks/damage.
the player will attack twice for each hit you can see it in the animation here in the video.
I checked my animations and nothing is weird this is found by my players

**Comment by Callepo** [comment]
ye i had to usse legacy attack component to not get that, its been a thing a while now

**Comment by Sour-J** [comment]
so that seemed to fix the issue by adding that legacy attack component but i also still have my other attack component on xD thank you

**Comment by insthync** [comment]
I will fix it

**Comment by Sour-J** [comment]
> I will fix it

thank you i tried just legacy and it still happens to me, I appreciate you fixing it.

**Comment by Sour-J** [comment]
I tried to use the legacy component that callepo mentioned in the meantime but it still happens even with that, I'm using the shooter controller and have automatic weapons. It's a game breaking issue, sadly I have been struggling with it for two weeks. 

Is there a temp fix for this I could add? I don't even know what's causing it.

**Comment by insthync** [comment]
It is just animation issues or it is also taking double damage?

**Comment by insthync** [comment]
I still can't reproduce it yet.

**Comment by Sour-J** [comment]
It's attacking twice not sure

So what you do is get any active skill put it on your hotbar
Then have any weapon let's say melee sword on make sure it's set to automatic so you can hold down the mouse button to attack
So with the shooter controller in game hold down the mouse button to attack. Don't let go now press the active skill hotkey on your hotbar and still don't let go of the mouse attack it will now turn those mouse hold attacks into double hits the character with any animation will start to do two swings rapidly like the video above you can just hold the mouse button down forever and it will hit the enemy two times really quick. This happens to me no matter what animation I use I think it's the attack component because @Callepo mentioned using legacy to help

**Comment by Sour-J** [comment]
I think I found the issue Ill let you know if it worked but it seems to have stopped when i removed this option on the characters attack
https://gyazo.com/c375431b78c1cd54898f273b808d22db

**Comment by Sour-J** [comment]
I also had play all clip layers on attack animations might be causing it too, I will let you know

**Comment by insthync** [comment]
Thank you, I didn't test the case that it has multi hit trigger enabled

**Comment by Sour-J** [comment]
> Thank you, I didn't test the case that it has multi hit trigger enabled

well it worked fine in single player I have play all clip layers disabled, and no multi hit trigger disabled just normal attacking and it works perfectly in single player

Then i got into MMO and it's still double attacking, I think the issue is with MMO mode attacks, try my game, play as wulv go around attacking things get level 1 then try this hold down mouse click then use the first skill keep holding mouse and it will do the double attacks this happens with all skills and all characters, Weird it doesnt do it in single player

**Comment by Sour-J** [comment]
I also just found out if I keep holding it and using more active abilities it can go even more attacks like triple quadruple and so on you can make it so it hits 10 times with 1 attack

**Comment by insthync** [comment]
The last 2 posts make me confusing

**Comment by Sour-J** [comment]
I'll make a video today and show you both single player and MMO with the information on the second post so you can see

**Comment by insthync** [comment]
If the single player works well, why have to show it?

**Comment by insthync** [comment]
I still can't reproduce it, you should capture screenshots of character model -> attack animations, and skill data setting.

**Comment by insthync** [comment]
Okay, I can reproduce it now, I have to use clumsy to simulate lagging, issues occurring while it has high RTT and multi-hit trigger disabled .

**Comment by Sour-J** [comment]
Sorry I wasn't online to make a video. I'm not using multi hit anymore and it still happens.

You got it doing double attacks? You can keep pressing a active skill and hold.mouse and it will go triple attacks and more

**Comment by Sour-J** [comment]
> Okay, I can reproduce it now, I have to use clumsy to simulate lagging, issues occurring while it has high RTT and multi-hit trigger enabled.

I tested without multi hit trigger and it still happens its with automatic attacking and high RTT it seems yes

**Comment by insthync** [comment]
Fixed

**Comment by Sour-J** [comment]
Thank you I look forward to the next kit version. I appreciate your help.

**Comment by Sour-J** [comment]
@insthync Do you mind if i have the fix for this here separately? My kit has a lot of custom stuff I would really appreciate it so I dont have to pick apart the update to find it, I just want to add this fix to my current version c5 Thank you

**Comment by insthync** [comment]
What is your email ?

**Comment by insthync** [comment]
[MMORPG_KIT_NewActionComponents.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7898220/MMORPG_KIT_NewActionComponents.zip)

Then add following codes to `CharacterDataExtension.cs`
```
        public static bool ValidateSkillToUse(this BaseCharacterEntity character, int dataId, bool isLeftHand, uint targetObjectId, out BaseSkill skill, out short skillLevel, out UITextKeys gameMessage)
        {
            skillLevel = 0;
            gameMessage = UITextKeys.NONE;

            if (!GameInstance.Skills.TryGetValue(dataId, out skill) ||
                !character.GetCaches().Skills.TryGetValue(skill, out skillLevel) ||
                !skill.CanUse(character, skillLevel, isLeftHand, targetObjectId, out gameMessage))
            {
                return false;
            }

            return true;
        }

        public static bool ValidateSkillItemToUse(this BaseCharacterEntity character, short itemIndex, bool isLeftHand, uint targetObjectId, out BaseSkill skill, out short skillLevel, out UITextKeys gameMessage)
        {
            skill = null;
            skillLevel = 0;
            gameMessage = UITextKeys.NONE;

            if (itemIndex >= character.NonEquipItems.Count ||
                character.NonEquipItems[itemIndex].IsLock())
            {
                return false;
            }

            ISkillItem item = character.NonEquipItems[itemIndex].GetSkillItem();
            if (item == null || item.UsingSkill == null ||
                !item.UsingSkill.CanUse(character, item.UsingSkillLevel, isLeftHand, targetObjectId, out gameMessage, true))
            {
                return false;
            }

            return true;
        }
```

Delete codes in `BaseCharacterEntity.cs` line 95-96
```
        public AnimActionType AnimActionType { get; set; }
        public int AnimActionDataId { get; set; }
```

Change codes in function `IsPlayingAttackOrUseSkillAnimation`  and `IsPlayingReloadAnimation` (`BaseCharacterEntity.cs`)
```
        public virtual bool IsPlayingAttackOrUseSkillAnimation()
        {
            return AttackComponent.IsAttacking || UseSkillComponent.IsUsingSkill;
        }

        public virtual bool IsPlayingReloadAnimation()
        {
            return ReloadComponent.IsReloading;
        }
```

**Comment by Sour-J** [comment]
This fixed it perfectly thank you so much got you a coffee <3

**Comment by Sour-J** [comment]
@insthync one last thing for some reason once this is applied my monsters dont do attack animations anymore, they just stare at you and deal damage. the damage still works but no left or right hand monster attack animations are playing.

**Comment by insthync** [comment]
[MMORPG_KIT_NewActionComponentsFixes.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7918176/MMORPG_KIT_NewActionComponentsFixes.zip)

Fix by this package
