### ISSUE TITLE
模型资源的问题

### ISSUE THREAD

**Issue by naughty66** [suriyun-production/mmorpg-kit-docs#1377]
这个角色模型在 Hierarchy的列表内怎么没有看到？
![image](https://user-images.githubusercontent.com/95008248/147314339-81d6d093-80a3-461f-b4af-92f48b52d562.png)

![image](https://user-images.githubusercontent.com/95008248/147314305-3e4a42da-94a3-429a-ae90-b15d8b72679e.png)

**Comment by insthync** [comment]
No Error ?
