### ISSUE TITLE
BUG: Life leech on ground area dmg spells

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1378]
I use the resurrection of the character in the city after death. The character has a life leech. If the character uses skills that damage in the area and remain on the ground (for example, the area of poison on the ground), then the character dies, but the area of poison continues to do damage and continues to restore health to a dead character.. The character presses at this moment the resurrection button and is resurrected in the same place, but not in the city.
https://www.youtube.com/watch?v=oCk5g_4sy9k

**Comment by insthync** [comment]
I didn't see the video

**Comment by DimasjkTV** [comment]
> I didn't see the video

Sorry, the video was not mine and the user has already deleted it.
The area of damage continues to restore the character's health after death. (If the character has a life leech bonus)

**Comment by insthync** [comment]
I can't reproduce it yet
