### ISSUE TITLE
Map Scene generate Random Gameobjects in Hirarchy

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1379]
https://gyazo.com/deaccd6c809115b7d7964650ac1ea486

never seen this before. is this from kit?
when i play in editor and exit sometimes it generates

**Comment by BarzoStrike** [comment]
this has nothing to do with the kit. If you delete the files attached to a scene and leave the prefabs inside the scene, you will see them, look carefully, there are some things you deleted for sure I've experienced this

**Comment by moepi2k** [comment]
I removed nothing, just starded in editor and close. Never had this and i use unity for years

**Comment by insthync** [comment]
Seems like it is occurring because of missing scripts, but I don't know which scripts

https://answers.unity.com/questions/1870766/what-is-the-recovery-gameobject.html

**Comment by moepi2k** [comment]
nice, thank you @insthync. i try to track them down
