### ISSUE TITLE
Warp portal entity does not warp clients

### ISSUE THREAD

**Issue by ApolloGM** [suriyun-production/mmorpg-kit-docs#1382]
I have a warp portal entity set to instance and only the server can use it, clients can not. 
When server enters, all clients are ported as well. Is this behavior default? if so, how can I change it so a party leader can warp the party regardless of client or server.

**Comment by insthync** [comment]
Hmm? warp portal entity can be used by host only? Are you making LAN games?

**Comment by ApolloGM** [comment]
yes i was testing LAN behavior. Is there a tether setting somewhere or is this the Lan behavior by default?

**Comment by Callepo** [comment]
> yes i was testing LAN behavior. Is there a tether setting somewhere or is this the Lan behavior by default?

ye this is lan behavior, mmo works differently

**Comment by ApolloGM** [comment]
ok thank you, will close for now.
