### ISSUE TITLE
Listing multiple issues

### ISSUE THREAD

**Issue by MrBeatngU** [suriyun-production/mmorpg-kit-docs#1386]
These are a few issues I've personally come across while testing my game to a closed community.
Guild:
If you bring someone into the guild, it does not display their guild name until they log out and back in.
If the leader of the guild logs off, you lose your position in the guild.

I'll continue to add more as I come across.

NOTE: I tested all of these issues on a blank fresh install of 1.72c5

Suri if any of these are simple fixes with like a few lines of code. If you could share it, I would adore you. 
Thanks.

**Comment by Sour-J** [comment]
I also have the same issues. the guild one for losing position. I've opened another issue for it for that too.

**Comment by insthync** [comment]
Try 1.73
