### ISSUE TITLE
Sudden Issue 

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#1387]
Hello , 
 This morning when I started the project and tried to play the game , I suddenly giving this error 
 There was no changes made between last night and this morning 
 
 
![image](https://user-images.githubusercontent.com/1295862/147869966-9f251310-41ae-4e6b-a3da-758cd6e7b66f.png)

**Comment by insthync** [comment]
Is this always occurring or just once after open Unity?

**Comment by Deepankar1993** [comment]
Opposite of it now 
Last time it fixed itself no Idea how as I have not made any changes 

From yesterday it started again 
Now game starts once after Unity restart from second time it throws this error
