### ISSUE TITLE
Mobile - rotate the camera and move the joystick. and also fire button rotate camera

### ISSUE THREAD

**Issue by Kanera66** [suriyun-production/mmorpg-kit-docs#1389]
I would like to report a bug, which is very annoying on mobile. the rotation of the camera no longer works if the joystick is pressed before the rotation.

Also on the attack button if you keep pressing attack (for example automatic gun) the rotation of the camera does not work. you have to stop pressing the attack (or the joystick to move) press anywhere on the screen for the camera roation, do not let go of the camera press and then click on the joystick or the button fire ect ..

 It seems to me that this bug was reported by isaanyoha but still nothing after a lot of version ...
I specify that I am on the last current version.

I also specify that it is with the ShooterCharacterController but it does not work with the PlayerCharacterController either.

 I tried to modify the CanvasMobile but I still have this problem ..

It doesn't just work on mobile.

Cordially,

**Comment by insthync** [comment]
As I try it is still working properly, not sure what is happening.

**Comment by focushyper** [comment]
i have the same  issue on 1.80

**Comment by insthync** [comment]
Try use this one

![Screenshot_417](https://user-images.githubusercontent.com/2697550/228988015-d467c17b-604f-4694-9831-b0322629ba53.png)

**Comment by insthync** [comment]
Do you guys try to do something, such as try to fix button codes?

**Comment by insthync** [comment]
I can reproduce it, I will fix it now.

**Comment by insthync** [comment]
Fixed in 1.81h2
