### ISSUE TITLE
FPS with lots of monsters

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#139]
Assume that this situation is only in a single player game. It has long been noticed that if you are simultaneously attacked by 5+ monsters, then the FPS drops sharply. We get microfreezes. Also, the total FPS decreases from the number of monsters on the map. I want to note that this is a single player game. In the video, 10 monsters hit me. In the first video, monsters are present on the map. In the second video there are only 10 monsters that beat the character.
[1.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3855865/1.zip)
[2.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3855866/2.zip)
In the third video, there are 200 monsters on the map.
[3.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3855872/3.zip)

**Comment by Fallen01** [comment]
I just tested it with synty equipment and monsters I did not experience the same issue even with 300 monsters being the most i tried to get your results. The number of monsters isnt completely relevant because the networking only updates you about those near you but i tried anyway in order to get your issues. If your prefabs are done wrong they will lag.

**Comment by Fallen01** [comment]
Are you getting any errors? If so please post them.

**Comment by DimasjkTV** [comment]
> Are you getting any errors? If so please post them.


no errors. This is a fresh project.

**Comment by DimasjkTV** [comment]
With 300 monsters on map
![image](https://user-images.githubusercontent.com/47291794/69017085-7b43e880-09b5-11ea-8529-e4c73dfdfe92.png)

**Comment by Callepo** [comment]
![300 monsters](https://user-images.githubusercontent.com/7702658/69017346-a83ccf00-09a6-11ea-8831-f91884db3a8e.JPG)
![300fps](https://user-images.githubusercontent.com/7702658/69017347-aa069280-09a6-11ea-8fe8-7d0f3d327fe9.JPG)

**Comment by DimasjkTV** [comment]
Very strange. Probably with my version of unity, not everything is so good. Or what could it be

**Comment by Fallen01** [comment]
300 monsters on map shouldnt matter. only the monsters within a certain distance to you are updated on the network. its like was telling you about the total polygons of a map are less important then the ones you actual render.

**Comment by DimasjkTV** [comment]
> 300 monsters on map shouldnt matter. only the monsters within a certain distance to you are updated on the network. its like was telling you about the total polygons of a map are less important then the ones you actual render.


yes, that’s understandable. But then what could be the reason? This is a fresh project. This is a mystery to me.

**Comment by Fallen01** [comment]
well the prefabs for the old character might not be set up with this in mind. Callepo had to make the synty prefabs extremely efficient. Im guessing thats the issue. Its just a guess though.

**Comment by Fallen01** [comment]
Still the addon does give you an example of how to do player customization and it does work with efficient prefabs.

**Comment by DimasjkTV** [comment]
> Still the addon does give you an example of how to do player customization and it does work with efficient prefabs.


I have a fresh project on the screenshots. I just installed it from scratch. There are no assets. There is only what is included in the Kit. I didn’t change anything. Just installed from the store and launched.

**Comment by Fallen01** [comment]
Ya but i dont think callepo optimized the prefabs for the base model of the kit because what is it just hair?

**Comment by DimasjkTV** [comment]
I do not say anything against prefabs. I want to find a solution to my problem.

**Comment by Fallen01** [comment]
The only difference between us is the prefabs I'm using. I'm also using  5 or 6 times more of them then you are with no lag. I think Callepo just added the models own hair and its probably whats lagging you. For the Synty models they were optimized greatly to avoid lag. It all comes down to prefabs. Hopefully I've explained this in a way you understand this time.

**Comment by DimasjkTV** [comment]
> For the Synty models they were optimized greatly to avoid lag. It all comes down to prefabs. Hopefully I've explained this in a way you understand this time.

What can be with prefabs if this is a fresh project?

**Comment by Fallen01** [comment]
The kit is loaded with prefabs in a fresh project as is Callepos Addon. Thats how may UI elements work I would think you would know this. Every instantiated object is based on a prefab and character customization with this addon is no different. I mean your player is a prefab. ;)

**Comment by DimasjkTV** [comment]
> The kit is loaded with prefabs in a fresh project as is Callepos Addon. Thats how many UI elements work I would think you would know this. Every instantiated object is based on a prefab and character customization with this addon is no different. I mean your player is a prefab. ;)


what does this have to do with the current issue? I have a problem with FPS, and you're talking to me about the add-on and prefabs that are not in KIT. I ask again, what could happen with the prefabs from KIT in a fresh project?

**Comment by Fallen01** [comment]
Im sorry i thought you were using the addon. Is your pc decent?

**Comment by DimasjkTV** [comment]
> Im sorry i thought you were using the addon. Is your pc decent?


I think it's not the PC matter. Something with unity. On my PC, I can play modern games at 60 fps.

**Comment by Fallen01** [comment]
unity has over head, I deal with that myself as my laptop is a potato. Still i dont have your issue. I thought you were using the addon.

**Comment by Fallen01** [comment]
If it was the over head of unity on your pc, it would not be present in a build.

**Comment by DimasjkTV** [comment]
> If it was the over head of unity on your pc, it would not be present in a build.


Just made a build. There are no problems with a PC with 300 monsters. Something in Unity Editor is wrong

**Comment by Fallen01** [comment]
`its nothing wrong its the editors over head. the monsters are all loaded in the scene but not in game. Its alot to manage when the client is running to. It means you probably could upgrade your memory. playing games and making them is different. Anyway im glad i could help resolve your issue.
