### ISSUE TITLE
Game Message

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1391]
hi,

short hint whats best way to add custom game message since Language.cs is not partial
https://gyazo.com/8e4b2161009db0458ccf31a0e6236311

thank u very much

**Comment by insthync** [comment]
It still can't make enum to be partial

**Comment by moepi2k** [comment]
yea i got this, just thought there is maybe an other way to add own game message, but i add my own function now :)

thank you

**Comment by insthync** [comment]
May add new function called, send/receive custom game message which uses string as a message key

**Comment by moepi2k** [comment]
That would be cool 👍
