### ISSUE TITLE
A question involving your Dev Ext Example for adding Stats

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1392]
Taking the time to study how you did this it was pretty straight up until I wanted to plug it into the UI. 
![image](https://user-images.githubusercontent.com/71889605/148534875-410aa475-b129-4bb6-a182-2ba8619ebe18.png)

So I added the GetText() method to my partial and updated it accordingy as seen in the picture.

![image](https://user-images.githubusercontent.com/71889605/148535169-514dbfd3-6258-4afe-89b8-4804f68dd57a.png)

Then I inherited UICharacterStats and did the same.

Still my UI doesnt seem to update, what am i doing wrong here?

**Comment by Fallen-Entertainment** [comment]
![image](https://user-images.githubusercontent.com/71889605/148535336-c9c7a04e-eb11-4c1f-857f-5b16f2419c4a.png)

I added it to the bottom which you couldnt see in the pictures

**Comment by Fallen-Entertainment** [comment]
![image](https://user-images.githubusercontent.com/71889605/148535493-971dda5a-a650-4153-a894-c79063e16a43.png)

**Comment by Fallen-Entertainment** [comment]
Any Insight you can give me on this would be appreciated.

**Comment by insthync** [comment]
Did you change component from `UICharacterStats` to `UICharacterStats_CS`?

But after I see how you implement, I think I should  create new struct which will be passed to the `GetText()` function and change `GetText()` function to have only 1 parameter which is the struct that I mentioned, so you will not have to create new class which extends `UICharacterStats`, just create partial struct file which have your stat format added, and create partial class file for `UICharacterStats` which have your stat format setting added too.

**Comment by Fallen-Entertainment** [comment]
I added a separate UICharacterStats component to the generic layout UI component and then plugged in my new stat to display on the Hp bar. That actually sounds pretty great. Is there anything wrong with my implementation? I mean i learned everything i know studying you. Always open to feed back.

**Comment by insthync** [comment]
Not sure yet, it seems to be correct.

You might forget to set its reference to the components that use it.

for example:
![Screenshot_910](https://user-images.githubusercontent.com/2697550/148599749-ea46277f-161e-4539-a9bb-8c3aed9924e4.png)

**Comment by Fallen-Entertainment** [comment]
Ohh i didnt even think of that

**Comment by Fallen-Entertainment** [comment]
Ya no matter what i do it doesnt seem to update just stays at zero despite setting it to 5 in warrior class data

**Comment by insthync** [comment]
Did you set reference of `UICharacterStats` or `UICharacterStats_CS`?
