### ISSUE TITLE
Mount(skill) as Ranged attack type but does not work

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1393]
So created a mount skill and everything works great including melee attack by both player and mount.  
But if I change the attack mode on the mount skill from melee to missile or raycast, it does not attack at all.  

Is it currently not implemented yet ?

**Comment by shubhank008** [comment]
Unity 2020.3
Kit v1.72

**Comment by insthync** [comment]
Do you mean you create a new skill game data then add your vehicle types(mount types) to `Available Vehicles` then change to missile or raycast and it is not working?

**Comment by shubhank008** [comment]
Yes meele attack happens by mount and does damage too but not when change attack mode to missile or raycast


![](https://media.discordapp.net/attachments/641012114517000213/929087047858266112/unknown.png)

**Comment by shubhank008** [comment]
@insthync is it not implemented yet or am I doing something wrong
Asking because mount/vehicle entity also dont have a launch damage/projectile transform that character entity do

**Comment by insthync** [comment]
It is actually not different to generic skills, it just add condition to be able to use the skill while riding vehicle. So it must work.

**Comment by shubhank008** [comment]
Just to confirm, the player can attack and use skills while on mount

i am talking about the mount itself attacking and doing ranged damage
Found it weird cause there is no ranged damage transform so where will the mount even spawn the projectile

**Comment by insthync** [comment]
It will be spawned from character not the mount
