### ISSUE TITLE
Mount is destroyed when client disconnects

### ISSUE THREAD

**Issue by ApolloGM** [suriyun-production/mmorpg-kit-docs#1394]
I am not sure if this issue was fixed already.  If a client is riding a scene mount and exits or logs out , the mount is destroyed.
This does not happen for server. When server logs out and logs back in, mount is still there.

Is there anyway to not destroy the mount when a client exits or disconnects? 
Not sure if this has something to do with it?
        public static bool IsDestroyWhenExit(this IVehicleEntity vehicleEntity, byte seatIndex)
        {
            return vehicleEntity.IsDriver(seatIndex) && !vehicleEntity.Entity.IsSceneObject;
        }

though I have commented it and the vehicle still gets destroyed so I am not sure.

**Comment by insthync** [comment]
Not sure we understand the same thing or not?, But for me it won't be destroyed, It was fixed in the version after your report.

https://youtu.be/ngmRVifWkuk

**Comment by ApolloGM** [comment]
yes, I see that yours was not destroyed. Could you let me know what files were changed for this fix please? Thanks in advance.

**Comment by ApolloGM** [comment]
Identity.DoNotDestroyWhenDisconnect = true; fixed the problem
