### ISSUE TITLE
Guild Object Reference Null

### ISSUE THREAD

**Issue by MrBeatngU** [suriyun-production/mmorpg-kit-docs#1395]
I've gotten down to it's something with this piece of code or the memberroles dictionary.
`        public void SetMemberRole(string characterId, byte guildRole)
        {
            if (members.ContainsKey(characterId))
            {
                if (!IsRoleAvailable(guildRole))
                    guildRole = IsLeader(characterId) ? LeaderRole : LowestMemberRole;
                // Validate role
                if (guildRole == LeaderRole && !IsLeader(characterId))
                    memberRoles[characterId] = LowestMemberRole;
                else
                    memberRoles[characterId] = guildRole;
            }
        }`

Error:
`NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.MMO.DatabaseNetworkManager+<UpdateGuildMemberRole>d__63.MoveNext () (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Database/DatabaseNetworkManager_RequestHandlers.cs:661)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskScheduler.cs:90)
MultiplayerARPG.MMO.<UpdateGuildMemberRole>d__63:MoveNext() (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Database/DatabaseNetworkManager_RequestHandlers.cs:666)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(GuildData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(GuildData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:328)
MultiplayerARPG.MMO.<ReadGuild>d__101:MoveNext() (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Database/DatabaseNetworkManager_RequestHandlers.cs:1539)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(GuildData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(GuildData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:328)
MultiplayerARPG.MMO.<ReadGuild>d__93:MoveNext() (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Database/SQLite/SQLiteDatabase_Guild.cs:100)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:194)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Update() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:159)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:118)
`

The issue with the title not updating looks like you meant for it to be updated clientside when it received the accepted. Currently fixing this by updating the titleb itself. 
If you know what this error comes from and could give me a bandaid for it that would be great. If I manage to fix it myself I will post it here for other people.

**Comment by insthync** [comment]
You can fix by following this changes

https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/44939a90a37cc476ce85d6eca89cee4d341e6ddf

**Comment by MrBeatngU** [comment]
Thank you.
