### ISSUE TITLE
Request: Player layer

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#1396]
Please put the player on its own layer so we can exclude other characters on render textures and ignore the player for raycasts, etc..

**Comment by insthync** [comment]
You mean to have separate kinds of layers for characters such as player, monster instead of just character layer, right?

**Comment by vaughanb** [comment]
Yes, please!

**Comment by insthync** [comment]
Added in 1.73

**Comment by vaughanb** [comment]
Thanks for implementing this! 

Am I correct in assuming that all players will be on the same player layer? If so, I was hoping that you would make a separate layer for only the current player character and no other players. The problem I'm trying to solve is that render textures for the character window should show only the player character and no other characters/players. If all players share the same layer, the render texture will display all player characters who happen to be close enough for the camera to view them. So if you have your character window open in a crowded area, you'll see lots of other players in the window. I've been able to work around this myself, but only by doing core edits, which I try to avoid. 

Any chance you could implement a separate layer for only the local player character? I know others would like this as well. I apologize for not explaining properly the first time.
