### ISSUE TITLE
Vehicles/Mounts (only) having lag for random players

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1397]
This is a very weird issue where the vehicle/mount is lagging and causing rubberband effect but its randomly for some players.  

1. Out of a 4 player test mounts movement was smooth for 2 and laggy for 2. 
2. Even for players with laggy mount, their own character moves lag free
3. Even for players with mount lag, they can see mount movement of other players lag free.
4. For players without mount lag, they see laggy mount movement for player who have mount lag
5. Tested with default alpaca mount as well
6. not a latency issue as player with 100 and 400rtt had rhe problem while player with 250 and 300 rtt did not

Unity 2020.3
Kit is 1.72
Mmo mode

Video (its same for ground based alpaca mount too)
https://we.tl/t-QzGvBkpVGt

here is how the rigidbody movement script looks like

![](https://media.discordapp.net/attachments/460803281455939595/929714772465844264/unknown.png)

**Comment by shubhank008** [comment]
@insthync any idea ? Its quite urgent as nearing release

**Comment by shubhank008** [comment]
> Try this
> 
> [MMORPG_KIT_EntityMovements.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7847548/MMORPG_KIT_EntityMovements.zip)

Sorry for late reply, was waiting for multiple people test.  

No improvement, still same behavior of lag/rubberband on same players. 

PS: There is LiteNetLibTransform also attached to the mounts and I remember seeing a warning the script is no longed used and should be removed ? Should I leave it attached or remove it.

Very weird issue.

**Comment by insthync** [comment]
Remove it

**Comment by shubhank008** [comment]
Removed it and from the above package these are my current rigidbodyentitymovement settings

![image](https://user-images.githubusercontent.com/3790163/149334563-474e1b1e-7c3e-4fb8-891e-1a25fb821340.png)

**Comment by shubhank008** [comment]
> Yes, like mine, still bad?

Yep, still same.  

A few unique findings:

1. Even if Player A is lagging, he can see Player B smoothly
2. Player B can see Player A lagging
3. If Player A is moving the mount backward, he does not face any lag, only front movements

**Comment by shubhank008** [comment]
@insthync anything on this ? Kind of making using mounts impossible

**Comment by insthync** [comment]
How about your mount entity movement component, it's using a custom entity movement component? or which component are you using?

**Comment by shubhank008** [comment]
> Removed it and from the above package these are my current rigidbodyentitymovement settings
> 
> ![image](https://user-images.githubusercontent.com/3790163/149334563-474e1b1e-7c3e-4fb8-891e-1a25fb821340.png)

@insthync using the RigidBodyEntityMovement, I duplicated the default Alpaca mount so using all its default components, only removed that LiteNetLibTransform component
