### ISSUE TITLE
mmorpg error with digital ocean

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#1398]
**use mmorpg v1.72c5
use unity v2020.3.22f1**

**I followed the tutorial**

 https://suriyun-production.github.io/mmorpg-kit-docs/#/dedicates/digitalocean

 **but it crashes.**

serverConfig.json

{
  "databaseOptionIndex" : 1,

  "centralAddress" : "myIpAdress",
  "centralPort" : 7000,
  "clusterPort" : 7010,
  "centralMaxConnections" : 1000,
  "machineAddress" : "myIpAdress",
  
  "mapSpawnPort" : 6001,
  "mapSpawnMaxConnections" : 2,
  "spawnExePath" : "/root/Build.x86_64",
  "notSpawnInBatchMode" : false,
  "spawnStartPort" : 8000,
  "spawnMaps" : ["Map001", "Map002"],

  "databaseManagerAddress" : "localhost",
  "databaseManagerPort" : 6003,

  "useWebSocket": false.
  "webSocketSecure": true,
  "webSocketCertPath": "./localhost.pfx",
  "webSocketCertPassword": "123456"
}

**Below is the log I've encountered a crash, how do I fix it?**

===== Logger Initialized =====
[DevExt] GameInstance - Awake
Reading config file from ./config/serverConfig.json
Found config file
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at MultiplayerARPG.MMO.ConfigReader.ReadConfigs (System.Collections.Generic.Dictionary`2[TKey,TValue] config, System.String configName, System.Boolean& result, System.Boolean defaultValue) [0x00019] in <efe49c9ea34a43e78e2afdc0d0104e8c>:0 
  at MultiplayerARPG.MMO.MMOServerInstance.Awake () [0x0011c] in <efe49c9ea34a43e78e2afdc0d0104e8c>:0 

[DevExt] GameInstance - LoadedGameData
[IAP_INIT]: Initialized without purchasing
ERROR: Shader UI/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.972488 ms

Unloading 6 unused Assets to reduce memory usage. Loaded Objects now: 25461.
Total: 49.285968 ms (FindLiveObjects: 1.770218 ms CreateObjectMapping: 3.236705 ms MarkObjects: 44.202946 ms  DeleteObjects: 0.075196 ms)

![crash](https://user-images.githubusercontent.com/58978516/148726799-80c2b57d-cdd6-4ea5-b7f5-bcff10b3afd6.png)

**Comment by insthync** [comment]
Your config is wrong

{
"databaseOptionIndex" : 1,

"centralAddress" : "myIpAdress",
"centralPort" : 7000,
"clusterPort" : 7010,
"centralMaxConnections" : 1000,
"machineAddress" : "myIpAdress",

"mapSpawnPort" : 6001,
"mapSpawnMaxConnections" : 2,
"spawnExePath" : "/root/Build.x86_64",
"notSpawnInBatchMode" : false,
"spawnStartPort" : 8000,
"spawnMaps" : ["Map001", "Map002"],

"databaseManagerAddress" : "localhost",
"databaseManagerPort" : 6003,

"useWebSocket": false`,`
"webSocketSecure": true,
"webSocketCertPath": "./localhost.pfx",
"webSocketCertPassword": "123456"
}

**Comment by ybb95** [comment]
thank you. succeeded

but 

I can't register, what's the problem?



![111111111111](https://user-images.githubusercontent.com/58978516/148736882-1422cf7f-81e6-4ada-bb12-4218d752222d.png)

![22222222](https://user-images.githubusercontent.com/58978516/148736888-96597f1b-3b93-4435-80ea-870aec1ce5c8.png)




mySqlConfig:
{
  "mySqlAddress" : "myipaddress",
  "mySqlPort" : 3306,
  "mySqlUsername" : "admin",
  "mySqlPassword" : "mysqlpassword",
  "mySqlDbName" : "myGameName"
}


sudo ufw allow 7000
sudo ufw allow 8000
sudo ufw allow 8001

/root/Build.x86_64 -startCentralServer -startMapSpawnServer -startMapServer -startDatabaseServer

**Comment by ybb95** [comment]
I solved it. I wrote mySql Config wrong.
