### ISSUE TITLE
Translation of the word physical

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#1399]
Hello everyone! Can't find anywhere where to translate physical damage ?!
![1](https://user-images.githubusercontent.com/16080577/148770835-d22bbb2b-4f03-419e-818d-1064b5b2de55.jpg)

**Comment by insthync** [comment]
You have to create a new damage element then you will be able to set its title, and then set it as the default damage element here.

![Screenshot_912](https://user-images.githubusercontent.com/2697550/148967146-02e977ab-c291-41fc-ab49-0949bfceb69e.png)

**Comment by brabaris** [comment]
Many thanks!
