### ISSUE TITLE
2D equipment using spritesheets

### ISSUE THREAD

**Issue by therealjohn** [suriyun-production/mmorpg-kit-docs#1400]
Add support for equipment when using 2D using layered sprite sheets and AnimationClips. This is similar to https://github.com/suriyun-production/mmorpg-kit-docs/issues/717, but the technique requested here can't use HeroEditor4D. 

For example, a system is needed to handle sprite sheets like this:

![character-base](https://user-images.githubusercontent.com/1501196/148864054-a08ee3a7-b8d0-49a7-83fb-ee4cde04ee77.png)
![pants](https://user-images.githubusercontent.com/1501196/148864067-d09cf472-6fe7-4271-89b5-363994719264.png)
![hair-01](https://user-images.githubusercontent.com/1501196/148864074-0641282b-eb2c-4cdd-a275-b20608318ba8.png)
![hat-01](https://user-images.githubusercontent.com/1501196/148864083-f30e2b95-58ba-455a-8c78-9d31a338b47c.png)
etc.

To do this, I think:
- Items/Armor need a new property for holding the sprite sheet information
- Items/Armor need a way to map their equipment slot / armor type to a specific SpriteRenderer on the character
- A character script needs to handle displaying or removing the sprites from the appropriate renderer based on the armor type / equip position and its spite sheet
- Need a way to handle the layer order / sorting order based on direction of movement. i.e. when moving up, the "Cape" might be the top layer, but when moving down, it would be the bottom layer. 
- Need a way to do the same for shadows

I implemented something that's working using the new Unity Animation 2D package and the `SpriteLibrary`, `SpriteLibraryAsset`, and `SpriteResolver`. 

Each set of equipment has a `SpriteLibraryAsset`. In there, a new Category is added for each supported animation name. i.e. IdleDown, IdleUp, etc. Then each sprite for each frame is added to that category and a Label with the frame number is assigned. This matches the AnimationClip created for each animation type so that they can be reused for each sprite. 

I then have a new `BaseCharacterModel` implementation that is similar to the Hero4D extension, except it customizes the `SetEquipItems` to work with the SpriteResolvers and SpriteLibrary of each object on the character. 

This might be one way to do it, but happy to have something officially supported in the kit and covers all the scenarios.

**Comment by insthync** [comment]
Talks about it here https://github.com/suriyun-production/mmorpg-kit-docs/issues/2236
