### ISSUE TITLE
Multiple Death Bug

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1401]
Found a bug where you can die multiple times on the same death. This could be bad because if you have a exp death penalty or drop penalty.

I was able to reproduce this in a clean default kit.
to reproduce.

spawn in, walk over to big orc boss hit him once then die on purpose, while dead hit the exit button instead of respawn, then go back to that character hit start. That's it you will notice that you die again when you go back into the game, With item drop on death it dupes the item drops and other death penalty's from EXT scripts are also affected.

**Comment by moepi2k** [comment]
someone reported that in my alpha, and i forgot to post it here :D

**Comment by insthync** [comment]
I can't reproduce it yet.

**Comment by insthync** [comment]
This is for single player ?

**Comment by Sour-J** [comment]
its because of the life leech
If a player dies while leech is active, they can respawn at that location.
they have an active hp when they respawn, they respawn at the point they died.
And can continue attacking the enemy

**Comment by Sour-J** [comment]
Yes

**Comment by moepi2k** [comment]
ah sorry mine was a bit diffrent, this video is from a player. i dont tried to reproduce yet. but if it works. its critcal :)

https://cdn.discordapp.com/attachments/627525768280408077/921519210335719464/Gnome_Online_2021.12.18_-_00.46.59.08.DVR_Trim.mp4

**Comment by insthync** [comment]
I think both are because of character saving when disconnect issues

**Comment by moepi2k** [comment]
mine is in mmo

**Comment by Sour-J** [comment]
also sometimes the player spawns dead not sure if its related but if they log off with 100 food they log back in hours later dead with survival food and water empty i think the game is still decreasing the food and water when offline.

**Comment by Sour-J** [comment]
theres two different issues here, one is the one i posted and the other with an issue with lifeleech

1. to reproduce spawn in, walk over to big orc boss hit him once then die on purpose, while dead hit the exit button instead of respawn, then go back to that character hit start. That's it you will notice that you die again when you go back into the game, With item drop on death it dupes the item drops and other death penalty's from EXT scripts are also affected.

2. have any lifeleech while attacking a monster you can respawn because it heals you after death

**Comment by Sour-J** [comment]
seems to be fixed in new version
