### ISSUE TITLE
Update asset to use layout recommended for Packages

### ISSUE THREAD

**Issue by therealjohn** [suriyun-production/mmorpg-kit-docs#1402]
It's increasingly difficult to organize a large project and update the asset. It's also not obvious which version is added when it's already in a Unity project. That makes it hard to track the changelog too. The standard import list for an asset is very long which makes it hard to recognize the Demo content that you want, or don't want. The recommended layout offers the Samples~ format and can provide a nice UX for downloading the demo content you want. 

The recommended layout for packages can help solve these issues and make it easier to maintain this asset as a package in a private UPM registry in a separate git repo.

Does it make sense to adopt this layout to help solve these problems? 
https://docs.unity3d.com/Manual/cus-layout.html

**Comment by insthync** [comment]
It may break other customer projects
