### ISSUE TITLE
No agro/threat/tank-pull system??

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#1403]
Hi. I'm using the 2d version of your asset to make a game. For now I'm just making a single player game...

I'm noticing that my summoned minions do not pull any agro, meaning the enimy ai will not target them if they have already targeted the player character.

This means the player can't use a minion to tank which is the main reason to summon a minion for most players and classes.

Basically an Archer summons a bear to get enemies to attack the bear and not the Archer. So the Archer can attack safely from the side.

This is a part of any MMORPG I have played that has a pet class. What is the use of summoning a minion if enemies ignore it and keep attacking the player.

The way minions work on your asset makes it possible to make an enemy chase the player around while sommoned minions attack the enemy freely and never get targeted. This can ruin boss fights and in non boss fights, this looks really bad as well...

I tried different things and now I'm noticing that the enemy, when set to "agreesive" mode will not try to attack my minion when it's in range even when the enemy isn't trying to attack the player.

The enemy will only attack my minion after my minion attacks first as if the enemy is in "normal mode", but if I move the player character in enemy view range, the enemy will still move to the player character and walk straight passed the summoned minion if it hasn't started attacking it yet.

That can't be right!

Also I have not tried the multiplayer modes yet, but I don't see any agro/threat/tank-pull type skills or statuses available, so I'm wondering what happens when two or more players attack a boss.

If a tank with a billion hp and 1 dps gets targeted, will the boss keep attacking him while a mage with 1hp and a billion dps is pounding the boss from the side... Will the boss start attacking the higher threat mage even after it was locked on to the tank?

Also if the mage gets locked on to by the boss first, does the tank have any way to pull agro off the mage? Which is what tanks are for...

I'm not seeing any agro system on this asset at all in the single player mode at Least. And the fact that enemies won't act agreesive to my summoned minions has stopped my production in its tracks several times in the past year of trying to use this asset pack. I would have been had a finished game by now if not for that annoying roadblock.

What's the point of summoning a minion if the enemy ignores it and keeps attacking you.???

Is there a quick fix for this?

Is there an agro system I'm not seeing or that just isn't set up for sommoned minions?? Is there a fix for that?

Thanks for reading. Looking forward to a response.

**Comment by moepi2k** [comment]
hi, just from my side. there is no agro system by default. as u said even in mmo. uf a group attack e.g a boss. the boss will have only aggro on the first one who are in visual range of the boss or do the first damage. even when the one do no more dmg and all of ur group do alot.

i know agro systen is a comming feature in every mmo.

u need to have an option on every skill/default attack to increase agro. and the monster switch target to the one with highest agro which are involved into fight.

**Comment by shinimaru** [comment]
Yes but I also think there is a second separate issue where your sommoned minion doesn't draw agro at all (when enemy is set to "agreesive" it will not react to summoned minions until the minion attacks it. As if the enemy is in "normal mode" but the enemy will still try to agreesively attack the player if the player moves in range)

Another arpg asset pack I tried, simply let's the enemy ai repeatedly choose to Target the closest target, so if it's targeting on player or minion and another player or minion moves closer than the original target, then the ai will switch to the new closer target. That would work like a charm for my single player pet class needs at least... But that asset pack isn't set for multiplayer so...

I tried making the ai on the MMORPG survival asset pack to work the same way when enemy ai is set to "aggressive" but that's when I found out that summoned minions don't get targeted from walking into range of the agressive ai. Very frustrating.

Possible fixes;

Add a classic simple agro system with pulls and ai choice of target based on damage received from each individual target

Also, giving ai targeting choice based on potential targets with lowest hp, or weaknesses to certain eliments, a chance to resist pulls (with adjustable parameters), and skills that will target players (class based) even if agroed by a different player or minion.

And of course making "agressive" ai target summoned minions or enemy NPCs in the same way it targets players.

**Comment by moepi2k** [comment]
yea your right, agro system is really important for an mmo.

**Comment by insthync** [comment]
Too long, didn't read.

**Comment by shinimaru** [comment]
I'm hoping the devs give a response. Because otherwise the asset pack seems perfect. I don't have the time or skill to work within their code and add my own aggro system that would still work with the server stuff that I don't understand. Lol my "duct tape on a bridge" approach at novice level coding could screw up the multiplayer eliments of this asset pack so I can't use it in the future like I planned for my game.

**Comment by shinimaru** [comment]
> 

Fair enough. In a nutshell. There is no agro system, and summoned minions are not being targeted by ai that is set to "aggressive". Massive gameplay issues!

**Comment by moepi2k** [comment]
> Too long, didn't read.

🤣 In short words: agro system for ai is missing

**Comment by Fallen-Entertainment** [comment]
Thats the longest strangest bug report / feature request Ive ever seen.  I mean was it really critical to explain a basic game feature to suri like hes a little kid?
