### ISSUE TITLE
Ai movement and attack variations.

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#1404]
This is less an issue and more a suggestion.

1. Add in combat movement cue to ai. So it just doesn't stand still shooting and taking damage without reacting.

Linking movement options to skill use could work. On the skill list in monseter data. Under the skill slot in each field, add a choice of random movement before the cast or set a direction relative to the player or in a set world based direction for a set time or distance before the skill is cast... Up, down, left, right, diagonal each way. Towards target (charge) or away from Target (retreat) 

Also making the ai move based on it's hp or status effects in the same way as above.

An arpg asset pack I found uses something similar to this. And it makes it seem like the ai is thinking and reacting and dodging attacks and so on...

We don't need the ai to be smart. We just need it to seem smart...

Also it would be nice if both player and ai could shoot ranged attacks in a spread patterns with multiple projectiles. To ad more diverse combat either way.

Also set up path indicators for charged melee aoe attacks letting player know what area will be hit so they can Dodge.

Peace

**Comment by MrBeatngU** [comment]
On the ranged attacks, you can use missile with a VFX with the spread of choice, each effect having its own collider. It's simple to achieve. Charge path indicators can be done with game effects tied to a location on the player... There's ways to do almost everything you're wanting and if not, it's fairly simple to add. There's AI addons in the discord you can pick up for little to nothing.

**Comment by shinimaru** [comment]
Thanks but if I wanted Jerry rig something with spread ranged attacks. I would figure something out. The vfx thing you said doesn't sound like what I want. I'm not looking for a shot gun effect... That can just be mimiced by an invisible wide single damage eliment with a shotgun shot animation over top of it. Super easy. But not what I was talking about.

I'm talking separate damage entities fired in a set spread based on code from the pros who made the asset pack i bought. 

The "topdown engine" from more mountains simply gives you a x/y spread field and number of projectiles field and a random spread bool on the inspector on an intuitive part if the firing process that is easy to find and use.

This could be added to ranged weapons and ranged skills in MMORPG survival kit, properly and in a fully integrated way by the devs of this asset pack... That's what I'm suggesting in the opposite.

I'm not a coder. I'm a storyteller with video game ideas for some of the stories in the shared fictional universe I created...

We have different skill sets and focuses for our time and energy, bro. But thanks for the advice tho...


As far as your solution for area attack warnings, I'm using the 2d version so my models don't actually turn in the direction of attacks...

My solution would be to make  a short ranged, rang attack instead of a melee and just make it look like it's melee because, 2d lol. And give the damage element a delayed effect where the actual spawned element from the weapon or skill is skinned to look like the "warning area" and the delayed damage out put is represented by the 2d melee animation... I was already planning on trying this, but it would be better if the devs didvit a proper way because the way they have damage eliments work doesn't really allow me to delay the damage. I was considering freaking the dot area skill to where the first tick of damage of the area damage element is delayed and then the eliment self destructs right after the first tick. But I'm noticing the aoe dot ticks move really fast and you can't really change that in the inspector...

And as far as paid add-ons. I already paid for an MMORPG survival kit... Ya know what I mean? I don't have money to keep throwing at a project that isn't making me any money yet. I already sunk a bunch of money in on other asset packs. Ya dig?

**Comment by shinimaru** [comment]
I see how to make area damage and throwables function how to work like warning areas for "melee" attacks. It was simple.

But I would still want a professionally done LONG RANGED spread shot system.

**Comment by Callepo** [comment]
> On the ranged attacks, you can use missile with a VFX with the spread of choice, each effect having its own collider. It's simple to achieve. Charge path indicators can be done with game effects tied to a location on the player... There's ways to do almost everything you're wanting and if not, it's fairly simple to add. There's AI addons in the discord you can pick up for little to nothing.

Exactly what he said here.

the kit is made as base to be build upon to achieve ur own goal for ur game. cant be asking him every little feature u want for ur game etc.

there are AI assets u can use to integrate into the kit and achieve any behavior u want with enemy's.
a community member even made a full addon for Behavior Design asset which u simply import into the kit and ur done. much easier it cant really get tbh.

With his addon u can have enemy flee when their hp is low, can have them patrol, guard and much more. 
Plus u can create ur own behaviors, its not hard.
