### ISSUE TITLE
No agro/threat/tank-pull system?? (Shortened)

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#1405]
1. This asset pack is lacking an aggro system of any type.

2. Summoned minions don't pull any aggro from ai that is set to "aggressive" even if no other target. Massive gameplay issue.

3. When sommonig a minion in combat, the enemy ai will ignore the minion and keep attacking the player even if the player stops attacking while the minion keeps attacking. An oversight? I think, maybe.

**Comment by shinimaru** [comment]
hmm I have a feeling the devs have a whole lot on their plate and To do list. I wasn't planning on releasing my game with a co-op mode at launch so the main aggro issue is not something I need handled anytime soon...

And the summoned minion drawing no aggro at all is annoying, but I can just bypass that issue by not giving the player any summon "tank pet" skills for now. There are other summoned minion types I can get to work for now...

And I'm pretty sure I can set up pvp without the aggro system or the summoned minion fix..  so no rush I guess.

But an aggro system  for ai is a must have for those who are making a full on MMORPG. There is no way around it. They might have to make their own...

Anyway thanks for reading. I hope y'all can pencil in a fix for the summoned minion issue sooner than later tho.

Thank you

**Comment by MrBeatngU** [comment]
The best way to handle this IMO would be to create a stat called aggro, and in the attack method in the gameplay rule, have the attack focus whoever has the highest aggro level... At least that's how I would handle it.

**Comment by shinimaru** [comment]
I could try that. Thank you. But my more immediate problem is the minion not drawing agro at all.

I'm not sure if such a method would work on the minion if the enemy ai doesn't pick it up at all... I'm planning on trying some things... But I think that might be a bug...

I remember last year on an older release that my summoned minions drew aggro just like the player character did. Now it doesn't. I'm not sure why not

**Comment by shinimaru** [comment]
> The best way to handle this IMO would be to create a stat called aggro, and in the attack method in the gameplay rule, have the attack focus whoever has the highest aggro level... At least that's how I would handle it.

Ok I thought about what you said.

So basically add a "threat" stat to base stats.

Give tank class an initial static bonus in threat. And make all tank gear sets give up to a Max static threat bonus. And make tank pull/threaten skills give a massive buff in threat stat.

Then make every attack and heal spell in the game a short duration spike in the casters threat based on the damage or healing the spell does, so that it temporarily puts them above the tanks class/gear based static threat stat but only the most powerful high level attack skills and heals give higher threat than tank skills...

And of course heals should tend to have more threat than attacks because the bbeg is supposed to be smart... 

And it's on the tank to keep his longer threaten buffs up to cover the threat spikes from the dps and healers...

Classic agro system. Just like that. Thanks for seeing me the idea of just adding it as a base stats. I could set all that up pretty easily...

But

The part you said about adjusting the attack in the game rules lost me. I only see the option to always hit on crit and nothing else about attacking or targeting. 

But I last updated the asset pack a bunch of months ago when my internet was on so maybe that change to the game rules script was from a recent update?
