### ISSUE TITLE
Something weird with login server

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1406]
sometimes in MMO when certain player logs in it makes the login server crash and the map server is still running, people in game are fine but the login will timeout. I tried to look into the players account but didn't see anything weird. they can make a new account and log back in just fine. I had this happen to 3 players so far not sure what's causing it but was wondering if you had any idea or advice. Maybe the data becomes corrupted? or they have too many items to load? not sure. I didn't see anything in the server log it just stopped working and times out for everyone trying to login only when a certain player logs in everyone else can login just fine, I disabled the players account to investigate why it would make the login server crash

**Comment by insthync** [comment]
No error log?

**Comment by Sour-J** [comment]
I run a nohup and & command so it doesn't output anything in the console that way I can exit putty. I need to find a way to have a log with nohup on I can't see with nohup I believe unless there's a lot stored in server folder

**Comment by Sour-J** [comment]
how would i go about getting logs? are they saved somewhere? or should i run without a nohup and test the account logging in and send the putty console info? I appreciate your advice on this just seems strange they dont have anything crazy or mass amounts

**Comment by insthync** [comment]
In logs folder

**Comment by Sour-J** [comment]
Thank you I looked thru the files I found where it happened in the map log but it doesnt say anything about the login server the map is fine, is there a log for the login section?

**Comment by Sour-J** [comment]
so heres an example I closed the server, then reopened it tried to login to the account and is says connection failed in the log then i restart the server and it goes back to normal but if the other account that had the connection fail tries to login it breaks the login server where nobody can login
`12:40:39] - OnPeerConnected peer.ConnectionId: 1
 INFO CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer [2022-01-15 12:40:45] - OnPeerDisconnected peer.ConnectionId: 1 disconnectInfo.Reason: RemoteConnectionClose
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:49] - OnPeerConnected peer.ConnectionId: 13
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:49] - OnPeerDisconnected peer.ConnectionId: 12 disconnectInfo.Reason: ConnectionFailed
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:50] - OnPeerDisconnected peer.ConnectionId: 13 disconnectInfo.Reason: ConnectionFailed
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:50] - OnPeerConnected peer.ConnectionId: 14
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:53] - OnPeerDisconnected peer.ConnectionId: 14 disconnectInfo.Reason: ConnectionFailed
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:53] - OnPeerConnected peer.ConnectionId: 15
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:57] - OnPeerDisconnected peer.ConnectionId: 15 disconnectInfo.Reason: ConnectionFailed
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:57] - OnPeerConnected peer.ConnectionId: 16
 INFO MapSpawnNetworkManager(MapSpawnNetworkManager)->LiteNetLibServer [2022-01-15 12:40:57] - OnPeerDisconnected peer.ConnectionId: 16 disconnectInfo.Reason: ConnectionFailed
 INFO CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer [2022-01-15 12:47:53] - OnPeerConnected peer.ConnectionId: 0
 INFO CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer [2022-01-15 12:48:04] - OnPeerDisconnected peer.ConnectionId: 0 disconnectInfo.Reason: RemoteConnectionClose
 INFO CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer [2022-01-15 12:48:38] - OnPeerConnected peer.ConnectionId: 1
 INFO CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer [2022-01-15 12:49:23] - OnPeerDisconnected peer.ConnectionId: 1 disconnectInfo.Reason: RemoteConnectionClose `

**Comment by Sour-J** [comment]
it wont let anyone login after this certain account tried to login and failed got timed out/connection failed. but everyone else can login just fine. this happened to about 3 accounts over 2 months time

**Comment by insthync** [comment]
Which kind of your database mysql or sqlite?

**Comment by Sour-J** [comment]
mysql, with your async thing you posted in another git thread

**Comment by insthync** [comment]
I guess that it has some problem with the user's characters, after logging in it will load characters from the server to show in the character selection list. It may have problem when load characters

**Comment by moepi2k** [comment]
i had similar issues when a player tried to login with outdated data/e.g server changed some skills/abilities for example.

**Comment by Sour-J** [comment]
> i had similar issues when a player tried to login with outdated data/e.g server changed some skills/abilities for example.

@insthync This makes sense because it usually happens when i update and change a item or skill, they get the problem after the update but weird because its not all players just random 1-3 and also sometimes the login will timeout 5 times before letting them in and some people its right away 1 time

**Comment by insthync** [comment]
Okay, I will try to find cause of issues and fix it.

**Comment by Sour-J** [comment]
issue resolved in new version
