### ISSUE TITLE
No inventory loss or any  real punishment for death

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#1407]
In a nutshell. Most survival games punish you for death in ways players really want to avoid. Which is why they try so hard to survive. 

This asset pack only list xp loss as an on death punishment which is hardly a punishment and will stop mattering at Max level. There should be an option for loosing items and equipment from inventory AND/OR loosing items/equipment durability on death. There are options for neither. And finding stuff like that to change in the script is way to overcomplicated specifical because of the scripts in this asset pack spreading things out between many scripts. 

1. How can I make it so the player loses his inventory on death??

2. Where is the function for saving or loading inventory contents??

3. I see the "on respawn" function in the default game rules script. But where is an existing delete player inventory function in any existing script that I can call in the respawn function??? (All the inventory stuff is plit between many different scrpts. Where is the core inventory management script???! (So frustrating))

Why is there not a simple bool on the game play rules inspector that toggles whether the player loses their inventory on death???? (So frustrating. It's a SURVIVAL game kit. That should be a main feature. It is a feature on other inventory based asset packs that aren't for survival games. Just saying)

**Comment by moepi2k** [comment]
item los on death is already a feature of this kit

**Comment by Callepo** [comment]
u should really learn how to talk to people, the way u are talking is like ur talking to a little kid, which he is not.
This is not a Survival kit, it has survival aspect yes, but its mainly MMO/ Lan... 

Read the docs or atleast look around before u make random issue reports, Which aint even issues.
![image](https://user-images.githubusercontent.com/7702658/149791440-6f4a3ca1-e5c9-4ed8-b5fa-53a05e079970.png)


like ?

**Comment by Callepo** [comment]
im closing this thread
