### ISSUE TITLE
???

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#1409]
I get sculded and then the thread gets closed before I respond. Siri told me he didn't bother to read my original post and when I remade the post shorter he didn't respond at all. That left a pretty sour taste in my mouth frfr. Sorry I'm not in the know with all this stuff, but I spent  most of the last 3 days trying to figure out the issues I brought up before I made any posts about it. I'm sure my kit is just out of date and someone could have simple said that. I can't update it rn. It just is what it is. 

But I guess everything I wanted was added in since I last updated a few months ago??? I had the asset pack since like December 2020, sorry if I didn't think everything that's been missing that whole time just happened to be added in the last few months since me internet been off. What are the chances of that???

But I just felt condecending energy from the responses I got so I returned that energy. 

Here is another weird bug report. Now someone can tell me off then close the thread before I can respond again 🤦🤷

Anyway it is a great asset and worth the money, and I will be looking to donate if I achieve any real success using it. But I won't be asking anymore questions on this website tho. Peace.

**Comment by insthync** [comment]
I am planning to develop behaviour tree system like Unreal does, you will be able to use graph to create your AI

**Comment by shinimaru** [comment]
I really appreciate the response.

My version of the asset pack might be outdated by now. I haven't updated the asset pack since around 3 months ago, which is why I think I'm not seeing the new inventory bools. Internet is off. Times been hard since 2020. Money be funny, Life's a bitch, then you turn 40 and that's when she goes Savage, if you not careful. When you live alone, life is the ultimate survival game... Lol

Gonna try to get latest update by this weekend or sometime next week. 

Also I'm making it a point to change as little code as possible to make sure there is little chance of issue when updating the kit, and no chance of screwing up the online networking stuff. I only changed and made renamed versions of player character controller inputs script and the mobile input button script. And I already plopped them into a fresh import of the asset pack and it works fine. I also made massive changes to the mobile ui layout but that shouldn't be an issue when I update I would think

Sorry I'm new to this kind of community... Peace

**Comment by Fallen-Entertainment** [comment]
you dont need to change as little code as possible to make updates easier, you just need to learn to work with the kit. Suri has made just about anything important in such a way that you can easily write a partial or inherit. Thats what makes this kit so good. Duplicate the UI prefab do whatever you want to it and youll be fine on updates, but if suri adds a new UI you might need to add it to your own prefab yourself, which really isnt a big deal. As a rule if i touch anything in the kit thats a prefab i duplicate it and roll my own, often even inheriting its associated script. Thats the joy of MMORPG Kit, you can do what you want to do about as easily as it gets. GL

**Comment by shinimaru** [comment]
Thank you for the info
