### ISSUE TITLE
1.50c loot is broken

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#141]
On 1.50c Monsters do not loot anything. (normal and loot table).

**Comment by Callepo** [comment]
Confirmed.. even on 100% chance it doesnt drop anything

**Comment by DimasjkTV** [comment]
I don’t have drop item in unity editor. But for the test I made an APK file and on the phone items dropped lol

**Comment by Callepo** [comment]
same for pc builds

**Comment by insthync** [comment]
To fix this, add `[System.NonSerialized]` to line  62 (Above codes: `private List<ItemDrop> cacheRandomItems;`)

Just knowing that Unity will construct the private list for Scriptable Objects, I also have to check other Scriptable Objects which have an private list too.
