### ISSUE TITLE
Potions effect does not appear in item window

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1412]
would you add the potion effect in the item window? it is important to know what each player does potion before you buy it or use.

![image](https://user-images.githubusercontent.com/56885137/150352899-06537859-8e15-46e8-89ca-d757606f93ff.png)

**Comment by moepi2k** [comment]
if you want to make the customize, would it be possible to add requirement to consumables to use it like we have already for weapons/armors?

https://gyazo.com/6fab06a1059560ce562bfb2a4f0cdd8e

**Comment by Blunnyn** [comment]
Has anyone been able to do something with this?

**Comment by insthync** [comment]
I will do it

**Comment by insthync** [comment]
Add UIBuff reference to UICharacterItem, use it for potion buff data showing. In 1.73c
