### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1415]
Empty slots behave like an item only for the first time u drag em.

https://gyazo.com/01876b46c949899a131d1e0064d89cbf

after that u cant drag it anymore.

**Comment by LordPhrozen** [comment]
If thats the case, why are they draggable in the first place..

**Comment by moepi2k** [comment]
the prefab itself which u set for invenotry items is a dragable thing. thats why i post it here

**Comment by insthync** [comment]
I will fix it by make empty slot not able to move

**Comment by insthync** [comment]
Fixed in 1.73
