### ISSUE TITLE
Connection Timeout Question

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1416]
Today I experienced a lot of players connections timing out and they cant reconnect and some players stay online. 
I checked the logs but there's nothing it just says the played Timed out and they all timed out at the same time

Did this ever happen to anyone else that you know of? Any advice is appreciated on why maybe this could happen.
I think maybe it has to do with the database interval saving 30 seconds not sure on what it could be.

Thanks

**Comment by moepi2k** [comment]
Same issue here noticed in alpha. Some players has connection time out while playing. Happen also while just idle around

**Comment by insthync** [comment]
Not sure that the problem is occurring after changing database functions to be synchronous or has it occurred before?

**Comment by Sour-J** [comment]
I had this issue before asynchronous, I didn't report it because I thought it was my server. Since then I got a new server and it's still doing it before and after asynchronous.

It's strange it didn't happen at all today in game but it does happen after I update the game everyone times out a few times before they can login but when I try it goes right in the player must timeout about 3 times before it lets them in.

**Comment by insthync** [comment]
[MMORPG_KIT_TCPTransport.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7920566/MMORPG_KIT_TCPTransport.zip)

Try update this

**Comment by Sour-J** [comment]
Thanks ill try this today, was also having an issue players getting request timeout on login but some can get in just fine. not sure if its related

**Comment by Sour-J** [comment]
I did start getting request timeout on the login after using the async though not sure whats causing it since theres nothing in the logs just says remote connection closed in the logs for the user

**Comment by Sour-J** [comment]
> [MMORPG_KIT_TCPTransport.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7920566/MMORPG_KIT_TCPTransport.zip)
> 
> Try update this

This seemed to have solved the issue and improved login times too I think its solved. I don't have any issues with it anymore so far with the timeouts and disconnects. Ill reopen if it continues but pretty sure this is solved now. 

Thanks
