### ISSUE TITLE
Destroy Respawn Delay does not persist through log out on single player

### ISSUE THREAD

**Issue by ApolloGM** [suriyun-production/mmorpg-kit-docs#1418]
Just wondering if there is a setting I am missing. If the respawn delay is set to 5 min and player logs out and logs back in, the entities respawn immediately. Is there a way to persist the respawn delay through player log out? Or will I need to custom code this?

File BaseMonsterCharacterEntity.cs
         if (SpawnArea != null)
                SpawnArea.Spawn(SpawnPrefab, SpawnLevel, DestroyDelay + DestroyRespawnDelay);
            else if (Identity.IsSceneObject)
                RespawnRoutine(DestroyDelay + DestroyRespawnDelay).Forget();
            // Destroy this entity
            NetworkDestroy(DestroyDelay);

**Comment by insthync** [comment]
Yes, it needs custom code for respawning persistence for single-player games, Now when you exit the game it won't save monster respawning time.

**Comment by ApolloGM** [comment]
ok thanks for clarifying.
