### ISSUE TITLE
Skills change the order in the list.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#142]
A small bug.
1. We put on an item with a skill bonus. Everything works well, the list of skills is not broken.
2. We put on some set items. Set Bonus + Skill. This skill moves to the top of the list. For example, the skill was the last on the list, but if you get a bonus from the kit, then the skill moves to the beginning.

1. Skill list 1 and 2 skills.
![image](https://user-images.githubusercontent.com/47291794/69256216-31801b80-0bca-11ea-96cd-0d4252f6fa05.png)
2. Equip this item with bonus to 2 skill
![image](https://user-images.githubusercontent.com/47291794/69256299-51174400-0bca-11ea-91c7-32673464541c.png)
3. Everything works well, the list of skills is not broken.
![image](https://user-images.githubusercontent.com/47291794/69256360-68563180-0bca-11ea-953c-87453642b6da.png)
4. Equip set with set bonus to 2 skill
![image](https://user-images.githubusercontent.com/47291794/69256715-f5998600-0bca-11ea-9864-1af9c358a9ca.png)
5. The sequence of skills has changed. Now 2 skill has become 1.
![image](https://user-images.githubusercontent.com/47291794/69256807-1661db80-0bcb-11ea-9afc-3c32c61902ff.png)

**Comment by insthync** [comment]
Try these, In `CharacterDataExtension.cs` find function `GetAllStats` line 1507
Changes
```
        resultAttributes = GameDataHelpers.CombineAttributes(resultAttributes, data.GetAttributes());
        resultResistances = GameDataHelpers.CombineResistances(resultResistances, data.GetResistances());
        resultArmors = GameDataHelpers.CombineArmors(resultArmors, data.GetArmors());
        resultIncreaseDamages = GameDataHelpers.CombineDamages(resultIncreaseDamages, data.GetIncreaseDamages());
        resultSkills = GameDataHelpers.CombineSkills(resultSkills, data.GetSkills());
```
To
```
        resultAttributes = GameDataHelpers.CombineAttributes(data.GetAttributes(), resultAttributes);
        resultResistances = GameDataHelpers.CombineResistances(data.GetResistances(), resultResistances);
        resultArmors = GameDataHelpers.CombineArmors(data.GetArmors(), resultArmors);
        resultIncreaseDamages = GameDataHelpers.CombineDamages(data.GetIncreaseDamages(), resultIncreaseDamages);
        resultSkills = GameDataHelpers.CombineSkills(data.GetSkills(), resultSkills);
```

**Comment by DimasjkTV** [comment]
With these changes, only the skills that we received from the set bonus are now visible.

**Comment by DimasjkTV** [comment]
1.Without this changes.
![image](https://user-images.githubusercontent.com/47291794/69430473-bdb74d80-0d46-11ea-9474-979c147b1ae7.png)
2. With this changes. 
![image](https://user-images.githubusercontent.com/47291794/69430566-f6efbd80-0d46-11ea-964c-01a1ab7d5c07.png)

**Comment by insthync** [comment]
[FixListOrder.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3880638/FixListOrder.zip)

Try import this

**Comment by insthync** [comment]
Update version 1.50d which contains this fix is already uploaded.
