### ISSUE TITLE
Bug: 2D movement

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1420]
Mobile 2D.
The character continues to use the walking animation when it hits a wall.
Also, after we stop pressing the joystick, the character continues to move within a fraction of a second.
https://youtu.be/h2xS1WkZc9Q
also is there an option to turn off character slowdown while moving near a wall? (look at video)
https://youtu.be/W5INOwai5Xw

**Comment by RunOrDi3** [comment]
yes i noticed that too
