### ISSUE TITLE
[Bug] When players choose to Respawn, they revive first and can attack/kill before warping out

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1421]
This bug is related to the flow of players reviving first when they are dead->respawn->WarpOut 

When they choose respawn, they revive first and while warping they can attack and kill other players
Its to do with the fact that revive happens first, warp happens later

and its causing problem cause a guy whom I killed, pressed respawn and was warping to the village, but as his chara revived he just killed me before warping out :/  

For now I made a dirty patch by putting the revive code with a delay of 3 seconds so that warp happens/completes first and then revive happens but its not reliable and well, dirty

**Comment by Sour-J** [comment]
I was having a issue like this but it was because the dead character was gaining lifesteal while dead and brought him back to life

**Comment by insthync** [comment]
Okay, it should teleport before respawn :)

**Comment by insthync** [comment]
I change it to add some delay before character can receive damage

**Comment by shubhank008** [comment]
@insthync can you please share the code/change to fix it ? I cannot do a full version upgrade of the kit yet

**Comment by insthync** [comment]
In `BaseCharacterEntity.cs` line `21` add `public const float RESPAWN_INVINCIBLE_DURATION = 1f;` (after `public const float RESPAWN_GROUNDED_CHECK_DURATION = 1f;`)

Then at line `114` add `public float RespawnInvincibleCountDown { get; protected set; }` (after `public float RespawnGroundedCheckCountDown { get; protected set; }`)

After that, at line `126` add `public override bool IsImmune { get { return base.IsImmune || RespawnInvincibleCountDown > 0f; } set { base.IsImmune = value; } }` (after `public IPhysicFunctions FindPhysicFunctions { get; protected set; }`)

And, line `264` (in `EntityUpdate()` function) add 
```
            if (RespawnInvincibleCountDown > 0f)
            {
                // Character won't receive damage
                RespawnInvincibleCountDown -= deltaTime;
            }
```

* * *

File `BaseCharacterEntity_DamageFunctions.cs` at line `66` (in `OnRespawn()` function) add 
```
            RespawnInvincibleCountDown = RESPAWN_INVINCIBLE_DURATION;
```

**Comment by shubhank008** [comment]
> In `BaseCharacterEntity.cs` line `21` add `public const float RESPAWN_INVINCIBLE_DURATION = 1f;` (after `public const float RESPAWN_GROUNDED_CHECK_DURATION = 1f;`)
> 
> Then at line `114` add `public float RespawnInvincibleCountDown { get; protected set; }` (after `public float RespawnGroundedCheckCountDown { get; protected set; }`)
> 
> After that, at line `126` add `public override bool IsImmune { get { return base.IsImmune || RespawnInvincibleCountDown > 0f; } set { base.IsImmune = value; } }` (after `public IPhysicFunctions FindPhysicFunctions { get; protected set; }`)
> 
> And, line `264` (in `EntityUpdate()` function) add
> 
> ```
>             if (RespawnInvincibleCountDown > 0f)
>             {
>                 // Character won't receive damage
>                 RespawnInvincibleCountDown -= deltaTime;
>             }
> ```
> 
> File `BaseCharacterEntity_DamageFunctions.cs` at line `66` (in `OnRespawn()` function) add
> 
> ```
>             RespawnInvincibleCountDown = RESPAWN_INVINCIBLE_DURATION;
> ```

Correct me if I am wrong, but that makes the "respawning" player immune to damage while he's warping out after reviving right ?  

My issue is different, it's that when a player tries to respawn and is revived, he can control his character while warping out and even attack/use skills, during which he can damage and even kill other players.  

Like a player I killed in my game, clicked respawn and while warping out his player had revived and he attacked me and killed me.
