### ISSUE TITLE
Random Bonus stat + Bank issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1422]
with random bonus stats. sometimes when using the personal bank or NPC with random bonus stats it will glitch the bonus stats and override them with all the same stats, for example if you place an item that has 1000 hp into the bank it will come out with +stamina instead all the time. Ill find out how to reproduce this more but this is what ive found so far in mmo

to be specific every item gets  **Accuracy +7.29 and Survival(a type of attribute that gives food and water) +7.73**
Its really weird because the item wont have that bonus stat at all then will gain/replace it once its moved to into personal or colony storage, the base item is not affected.

![unknown](https://user-images.githubusercontent.com/78616165/150707143-ae1456fb-5c80-46f3-93a2-0c070e0824be.png)
![unknown3](https://user-images.githubusercontent.com/78616165/150707151-f30f97e0-614d-4ead-8729-faf488532c25.png)
![unknown2](https://user-images.githubusercontent.com/78616165/150707153-0bd02a3d-4eb2-4550-a1d8-af8bbc78cbd7.png)
![unknown1](https://user-images.githubusercontent.com/78616165/150707154-4eba2d2f-7ee5-4c96-ae36-0bb1d8d52864.png)

**Comment by Sour-J** [comment]
heres an example item, not sure if its the random stats or the database doing this
[example.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/7921951/example.zip)

**Comment by insthync** [comment]
Add this migration codes to fix it.

https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/56120bcfbbcae4756bf776eece1c12d5afb8d8f5

**Comment by Sour-J** [comment]
fixed thank you
