### ISSUE TITLE
[Error][Audio Clip] Ran out of Virtual Channels, Audio Clip XXX will not be played

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1424]
This error keeps spamming on my server's console (MMO)  
 Ran out of Virtual Channels, Audio Clip XXX will not be played
 
 And I think for whenever this occurs I hear no sound/sfx effect
 
 Using Kit 1.72

![image](https://user-images.githubusercontent.com/3790163/150818881-1450f4de-e52b-46af-9759-9060e65e645a.png)

**Comment by BJPickles** [comment]
Following this up, I'm also getting this.

**Comment by insthync** [comment]
In the latest version, I try to force it to not playing audio in batch mode, try it, I will close this. If the problem still occuring then you should report to me with which component causes audio playing.

You guys actually should tell Unity about this too.
