### ISSUE TITLE
[Error] NetDataReader.GetByte IndexOutOfRangeException

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1426]
Hello,  

I was running 1.72 till yesterday which was working fine, but then updated to the 1.72c5 update and applied the double attack fix from here  
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1375

After which the server started throwing these errors

![image](https://user-images.githubusercontent.com/3790163/150991843-f8b69057-895e-4fd9-88a2-d27bb3cf77d9.png)

**Comment by shubhank008** [comment]
@insthync any tips ? Seeing a lot more similar errors on the server side since the update to 1.72c5 and applying the animation fix (although don't think its related to animation fix)

**Comment by insthync** [comment]
Did you rebuild the server?

**Comment by shubhank008** [comment]
yep, multiple times
Also reimported the c5 package and then the animations fix package again just in case and rebuilt again
