### ISSUE TITLE
1.73 title field issue

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1428]
![image](https://user-images.githubusercontent.com/71889605/151002910-19d2e2b4-c619-436a-b0c8-a19eb8d066c3.png)
![image](https://user-images.githubusercontent.com/71889605/151002952-83dab10c-ba04-4549-ae24-54a74f6b5e3c.png)

I thought maybe the text just needed adjustment going as far as doubling its area it still wouldnt show, I checked to make sure it was plugged in and it was.

No idea whats going on with that, but seemed like something i should tell you about.

**Comment by Fallen-Entertainment** [comment]
Ohh thank you very much for the changes with get text! makes things alot easier!

**Comment by Fallen-Entertainment** [comment]
![image](https://user-images.githubusercontent.com/71889605/151003892-23a93570-e1ac-49de-96d5-669818b76ea6.png)
Also i noticed this i think this belongs in character and I am only checking in case you intended for it to be outside for some reason im clueless about.

**Comment by insthync** [comment]
That `: +5` and `: +10` are your custom character stats?

**Comment by Fallen-Entertainment** [comment]
no this is a default kit 1.73 I was checking out to see the new update. Zero work done to it. I was just thanking you for doing that aside from reporting these issues.

**Comment by Fallen-Entertainment** [comment]
I am looking forward to updating my project to 1.73 and trying you the new get text stuff!!!

**Comment by moepi2k** [comment]
got same issue on 1.73. some titles are missing

**Comment by moepi2k** [comment]
update: after imported adressables and restart unity it works.

seems the issue only occure when u directly import adressables without restarting unity

**Comment by Fallen-Entertainment** [comment]
Ahh thank you moepi2k I did not check after a restart. I actually reinstalled and found the same issue and then wondered why nobody else noticed this... Youve explained everything.
