### ISSUE TITLE
Collections Package Incompatibility (Unsafe DLL)

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1429]
Request for a compatability patch for the **Collections Package**.
Where MMOKit contains an unsafe DLL already, Unity only allows 1 of these DLLs per platform.

![image](https://user-images.githubusercontent.com/48354382/151013138-b40ba9ef-a5b1-42b6-b0c8-768b04c4f9a9.png)

Package:
![image](https://user-images.githubusercontent.com/48354382/151014182-c4ad29c5-c320-4c64-a391-1ded27fa42b1.png)

**Comment by insthync** [comment]
Did you try to find the dll file and delete it?

**Comment by BJPickles** [comment]
> Did you try to find the dll file and delete it?

Yeah that's what I've been doing for a little while and works fine as far as I can tell, but Collections DLL gets re-downloaded on every significant import. Not sure if there's a way to block it from pulling from Git every time to avoid this, or get the MMOKit to use the Collections DLL.

**Comment by BJPickles** [comment]
Fixed in Unity 2020.3.26f1 and Collections v1.0.0 pre-5
