### ISSUE TITLE
Stamina issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#143]
ive added Sprinting to game using movementstate on key down..
character runs and everything working fine..
I have 5 stamina decrease per second while sprinting..
stamina stays at 100..

i looked if it there was even a method for it .. and there was.. i checked if the method is being called properly... it is.. i added debug to if the If statement is true so that it can decrease stamina.. all good.. 
Debug logs are printing in unity
![shooter](https://user-images.githubusercontent.com/7702658/69269207-d3a30200-0bd0-11ea-902d-0dd8eef99377.JPG)
![debugs logs](https://user-images.githubusercontent.com/7702658/69269214-d69df280-0bd0-11ea-9ffa-460c68796c6f.JPG)
![debug ingame](https://user-images.githubusercontent.com/7702658/69269216-d9004c80-0bd0-11ea-8b18-9dc68b9545aa.JPG)

**Comment by insthync** [comment]
I will fix it and also implement it to the demo in next version

**Comment by Callepo** [comment]
simple code fix on the stamina drain ? if so can i get it here?

and cool

**Comment by insthync** [comment]
Let's me check, if it's simple I will post here

**Comment by insthync** [comment]
You must log `characterEntity.CurrentStamina` to for current stamina, `characterEntity.GetStats().stamina.ToString()` is total stamina.

**Comment by insthync** [comment]
You also have to set `stamina recovery per seconds` in `simple gameplay rules` value to be lesser than `stamina decrease per seconds`.

**Comment by insthync** [comment]
The thing I have to fix is: if character stamina <= 0 it must not sprint

**Comment by insthync** [comment]
I will move condition 
`!character.MovementState.HasFlag(MovementState.IsSprinting)`
To `SimpleGameplayRule` → `GetDecreasingStaminaPerSeconds` function
So the function codes will be
```
        public override float GetDecreasingStaminaPerSeconds(BaseCharacterEntity character)
        {
            if (character is BaseMonsterCharacterEntity || !character.MovementState.HasFlag(MovementState.IsSprinting))
                return 0f;
            return staminaDecreasePerSeconds;
        }
```

**Comment by Callepo** [comment]
Thank you.. and yea my SimpleGameplay stamina was set to decrease 50 for test 

I will add all these and test it

**Comment by Callepo** [comment]
Works .. ty
