### ISSUE TITLE
Question: 2D movement

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1431]
2D version
Can we change the movement of the monsters only left and right without changing the code? I mean remove the movement of monsters up and down. I found how to do this by changing the core code, but maybe I didn’t notice something and can this be done without changing the code? If no just close this question.

**Comment by RunOrDi3** [comment]
you need to change the code , you cant do it by default

**Comment by DimasjkTV** [comment]
> you need to change the code , you cant do it by default

thanks. Did that
