### ISSUE TITLE
Movements and PVP situation

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#1433]
Since there are many bug syncing movements as we reported many times:
For example:
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1376

What about implementing Client Authoritative movements with speed hack detection server side? This migration will fix all problems we reported related to movement and PVP? I think this is a very high priority to be production-ready for everyone here.

**Comment by moepi2k** [comment]
that alone fix not all the problems. lag compensation for projectiles is really important. pvp right now feels bad, because of bad hit registration. even when movement is client auth. you have those problems

**Comment by insthync** [comment]
Yes, it was reported many times, and it is not fixed because it is hard to fix :P

The easiest way is to make it tell the server when it hit, but you won't like it, because you feel it is not secure.

**Comment by Fr-Coder** [comment]
What about telling the server when it hit, but the server does a double check (maybe by distance) if the hit is correct? So it is not fully secure yes, they can hack but just to hit more mob in the distance "hack detection offset". what do you think about that? @insthync

**Comment by insthync** [comment]
I working on it :)

**Comment by LordPhrozen** [comment]
Very excited for this to be addressed. As a full loot pvp project... this has to feel very good.

Thanks @insthync ! WE really all do very much appreciate your hard work and dedication to continued support.

**Comment by moepi2k** [comment]
is this something that can help?
https://assetstore.unity.com/packages/tools/network/net-rewinder-50484

**Comment by insthync** [comment]
No difference to what I already did.

**Comment by moepi2k** [comment]
Okey :) 👍
