### ISSUE TITLE
GUILD ERROR

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1439]
When you create a guild in MMO, everyone can see the elements displays it correctly, but when you close the application and reopen it, it does not load correctly.
in the database the guild exists but it is not displayed correctly in the guild panel

<img width="465" alt="Captura de Pantalla 2022-01-28 a la(s) 12 39 33" src="https://user-images.githubusercontent.com/45702662/151580766-eb084fb8-2112-4785-88cc-45d10c7f10fb.png">

**Comment by insthync** [comment]
I will check it

**Comment by insthync** [comment]
Fix by this codes changes

https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/eee0cdf769681d093c30fb6dc87a6d4138876941

**Comment by Blunnyn** [comment]
thnks

**Comment by Blunnyn** [comment]
I made the changes, but the error still persists

<img width="559" alt="Captura de Pantalla 2022-02-01 a la(s) 13 10 56" src="https://user-images.githubusercontent.com/45702662/152008371-20c92714-fc6c-42ef-80a5-441be3789e84.png">
.

**Comment by insthync** [comment]
I want to see replaced codes

**Comment by Blunnyn** [comment]
<img width="753" alt="Captura de Pantalla 2022-02-01 a la(s) 13 38 15" src="https://user-images.githubusercontent.com/45702662/152010751-d58d2229-9e14-404b-9fba-7affabea24ff.png">

**Comment by insthync** [comment]
Correct, but why is it still occurring? there is no error in log files?

**Comment by insthync** [comment]
Found it: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/5a00901ee7f7e4ecc56cb2a4006fb0b60f968b01

**Comment by Blunnyn** [comment]
fixed now, thnks
