### ISSUE TITLE
Resource Folder bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#144]
when ur using resources folder.. the first time u need to keep spamming run and stop untill all the items are loaded properly..
literaly just run and stop.. it gets stuck at a few items idk why.. but after it runs good the first time.. it wont do it again.. it loads everything fine ..

But when u import files or change scenes .. u have to redo it again till it goes away..
I added a debug log.. to show the item name where its stuck .. and everytime i run again.. its a different item.. the first one that made it crash is now fixed for some reason.. it continues fine till it finds another item

Client builds work fine.. its just unity editor

https://youtu.be/Zb9myk4mQB4

**Comment by insthync** [comment]
Want to see that `ArgumentNullException` in details, to see where it is occurring.

**Comment by Callepo** [comment]
it was here..
it says in Editor Item value can not be null
![gameinstance](https://user-images.githubusercontent.com/7702658/69430876-d28be500-0d36-11ea-8665-387e4287c3d1.JPG)

I completely rebuild my project by removing library and project settings cuase i had a package error
that i was trying to fix that broke my project.. ( the one fallen said) and it somehow stopped it from happening

**Comment by Callepo** [comment]
Nvm .. here it is.. I added Gamedatabase back to Gameinstance.. Run it stop remove GameDatabase and Run again to use resource folder and boom its back 
![wedf](https://user-images.githubusercontent.com/7702658/69431503-2a771b80-0d38-11ea-8d5d-a49be02f958f.JPG)

**Comment by Syrus198327** [comment]
i am geting the same error also

**Comment by insthync** [comment]
I think problem may occurs because sometime when serialize array empty, it won't constructed so its value is null, so when it's going to add an array to the list the error occurs. So I will check null before add an array to list.

This is example
![Screenshot_192](https://user-images.githubusercontent.com/2697550/69499711-a97e7680-0f27-11ea-80a0-7f1356db3b54.png)

**Comment by insthync** [comment]
This should be fixed, I'll close it, If you still having this issue, you can reopen it.
