### ISSUE TITLE
v1.73 CashItem Error in mmo mode

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#1440]
'Receive gold' and 'receive currencies' are not applicable in Cash Shop items

Tested with version 1.73 Digital Ocean

![error](https://user-images.githubusercontent.com/58978516/151629487-4a6cb6ba-bac9-4cad-a9a0-70a34910a25f.png)

**Comment by insthync** [comment]
I will check it

**Comment by insthync** [comment]
Fix by following these changes: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/8b9d5bbd1c4295496fdfbc55ab689aa058721cf3

**Comment by insthync** [comment]
Fixed in 1.73b
