### ISSUE TITLE
Update to 1.73 and a bunch of UILanguageText.cs bugs!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#1441]
First, there was a SetAssetBundleNameByAddressableGroups.cs error due to the Addressables package not being installed (You should at least mention to the changelog that additional packages are required!)
Secondly, a bunch of errors due to the UILanguageText.cs file. It looks like it comes from UILanguageText.cs

![1](https://user-images.githubusercontent.com/16080577/151674687-11894875-290d-4b80-94fd-1ccac004d4dc.jpg)

**Comment by brabaris** [comment]
Downloaded the old file UILanguageText.cs the errors were gone. But WHERE DO THE WEAPON GO?! WTF?!
It seems that the task of the developer is to create as many quests as possible.
You can see the weapons on the scene, but there is nothing in the game! 

![2](https://user-images.githubusercontent.com/16080577/151675105-c298fb06-7961-4d9b-bd58-f1afff6ef304.jpg)

![3](https://user-images.githubusercontent.com/16080577/151675115-080b96fa-e529-4076-9e07-5fe3910481bd.jpg)

**Comment by ybb95** [comment]
Try changing the Culling mask in GamePlayCamera

![adfdaf](https://user-images.githubusercontent.com/58978516/151676568-31243dff-b1b0-4054-ad05-99f842faeb14.png)

**Comment by insthync** [comment]
- About `SetAssetBundleNameByAddressableGroups` I forgot about it, it is actually used in my project only, it should not be included in the project. 
- What is changed in `UILanguageText.cs`? The last change is on 4 Nov 2021, isn't yours is too old, or yours is different from the project's current file? 
- About lost axe, follow @ybb95 's answer.

**Comment by RunOrDi3** [comment]
just check  on player in culling mask

**Comment by brabaris** [comment]
Thanks @ybb95.
UILanguageText.cs я уже давно подменю старого проповедника. Эта версия (Без использования TMPro работает, новая версия файла с множеством ошибок!)
UILanguageText.cs (OLD Version):

using UnityEngine;
using UnityEngine.UI;
#if USE_TEXT_MESH_PRO
using TMPro;
#endif

namespace MultiplayerARPG
{
    public class UILanguageText : MonoBehaviour
    {
        public string dataKey;
        [TextArea(1, 10)]
        public string defaultText;

        private Text unityText;
        public Text UnityText
        {
            get
            {
                if (unityText == null)
                    unityText = GetComponent<Text>();
                return unityText;
            }
        }

#if USE_TEXT_MESH_PRO
        private TextMeshProUGUI textMeshText;
        public TextMeshProUGUI TextMeshText
        {
            get
            {
                if (textMeshText == null)
                    textMeshText = GetComponent<TextMeshProUGUI>();
                return textMeshText;
            }
        }
#endif

        private string languageKey;

        private void Update()
        {
            if (languageKey != LanguageManager.CurrentLanguageKey)
            {
                string text = "";
                if (LanguageManager.Texts.TryGetValue(dataKey, out text))
                {
                    UnityText.text = text;
#if USE_TEXT_MESH_PRO
                    TextMeshText.text = text;
#endif
                }
                else
                {
                    UnityText.text = defaultText;
#if USE_TEXT_MESH_PRO
                    TextMeshText.text = defaultText;
#endif
                }
                languageKey = LanguageManager.CurrentLanguageKey;
            }
        }

        void OnValidate()
        {
            UnityText.text = defaultText;
#if USE_TEXT_MESH_PRO
            TextMeshText.text = defaultText;
#endif
        }
    }
}

**Comment by insthync** [comment]
In the next version it will be replaced by this codes
```
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace MultiplayerARPG
{
    public class UILanguageText : MonoBehaviour
    {
        public string dataKey;
        [TextArea(1, 10)]
        public string defaultText;
        public Text unityText;
        public TextMeshProUGUI textMeshText;

        private string languageKey;

        private void Awake()
        {
            if (unityText == null)
                unityText = GetComponent<Text>();
            if (textMeshText == null)
                textMeshText = GetComponent<TextMeshProUGUI>();
        }

        private void Update()
        {
            if (languageKey != LanguageManager.CurrentLanguageKey)
            {
                string text = "";
                if (LanguageManager.Texts.TryGetValue(dataKey, out text))
                {
                    if (unityText != null)
                        unityText.text = text;
                    if (textMeshText != null)
                        textMeshText.text = text;
                }
                else
                {
                    if (unityText != null)
                        unityText.text = defaultText;
                    if (textMeshText != null)
                        textMeshText.text = defaultText;
                }
                languageKey = LanguageManager.CurrentLanguageKey;
            }
        }

        void OnValidate()
        {
            if (unityText != null)
                unityText.text = defaultText;
            if (textMeshText != null)
                textMeshText.text = defaultText;
        }
    }
}

```

**Comment by brabaris** [comment]
Thanks, insthync.
