### ISSUE TITLE
Equipment set UI is weird.

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#1442]
Both single mode and MMO mode are displayed strangely.

![error1](https://user-images.githubusercontent.com/58978516/151698696-5bdbb1cd-7d8e-45ec-9150-aceee0c1c4dd.png)
![error2](https://user-images.githubusercontent.com/58978516/151698698-1c7c807e-4338-466d-8572-be473343d9f3.png)

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/151700537-541cff30-4e07-496b-be74-3865423fa75b.png)
this is your +1 acc. Seems like you added 1 to rate stats and you got +100% acc

**Comment by ybb95** [comment]
@DimasjkTV 

This is 1.73v

This was not a problem with previous versions.

![sdfsdfsd](https://user-images.githubusercontent.com/58978516/151701502-bae220f5-0472-426c-879b-a7543e893eeb.png)

**Comment by DimasjkTV** [comment]
> 

![image](https://user-images.githubusercontent.com/47291794/151701564-60559018-c4f8-41a9-bd18-28e81e4cea82.png)
Are you sure you opened it here? and not for example in element 1. I also checked the latest version and my screenshots from the latest version of the game.

**Comment by ybb95** [comment]
![sadffsdfsdfsd](https://user-images.githubusercontent.com/58978516/151701807-fb07106f-c32e-4bf6-bf3d-f41c21371e1e.png)


![151698698-1c7c807e-4338-466d-8572-be473343d9f3](https://user-images.githubusercontent.com/58978516/151701810-6b96532d-b5d1-4b5d-b452-eb5815d48d8e.png)


Am I the only one experiencing this? I'm sad..

**Comment by DimasjkTV** [comment]
> Am I the only one experiencing this? I'm sad..
This only with acc? or with all stats?

**Comment by DimasjkTV** [comment]
May mistake. The previous fresh version was based on 1.72c5. In the new version 1.73, sets have a bug with a double designation. You're right.

**Comment by ybb95** [comment]
The same goes for hp , mp , and eva 

i`m afraid to update.....

**Comment by insthync** [comment]
![Screenshot_939](https://user-images.githubusercontent.com/2697550/151710281-212fab53-d93f-4f4e-ba1b-a55927f28cc0.png)


Fix by change codes in `UIBaseEquipmentBonus` at `182`

**Comment by ybb95** [comment]
thank you!!!
