### ISSUE TITLE
Bug: Skill tooltip

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1445]
In the tooltip, the required character level is displayed incorrectly.
![image](https://user-images.githubusercontent.com/47291794/152071247-44122e29-ca17-4be9-a1af-aed962b71f5a.png)
![image](https://user-images.githubusercontent.com/47291794/152071271-34f32f78-318e-4052-a2e9-6ef739030f1b.png)
![image](https://user-images.githubusercontent.com/47291794/152071298-c7f5cd83-733d-4dd4-9aa9-23d253418ee5.png)
In this case, the required level should be 1/1.
This is just a display bug, I can still start leveling this skill from the second level.

**Comment by insthync** [comment]
Fix it by changes codes in `UISkillRequirement.cs` at line `21` to

`short level = (short)(Data.targetLevel - 1);`

**Comment by DimasjkTV** [comment]
> Fix it by changes codes in `UISkillRequirement.cs` at line `21` to
> 
> `short level = (short)(Data.targetLevel - 1);`

Works well. Thank you!
