### ISSUE TITLE
user already logged in

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1446]
looks like some people cant connect for hours even days sometimes unless i reboot the server its random not everyone but they get
"user already logged in" 
I have the logout timer set to 2 seconds maybe I should change it to 0? 
ill let you know if i find anything else about this but its still happening just not as bad as before

**Comment by Sour-J** [comment]
im going to try [1.73b]

**Comment by colt0560** [comment]
any fix???
