### ISSUE TITLE
1.73b UMA question

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1447]
Hello, I updated my UMA project to 1.73b and got these errors, I would appreciate if you could let me know how to fix this, Ill gladly ko-fi you a coffee :) 
thanks

Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(76,129): error CS0103: The name 'rightHandEquipmentEntity' does not exist in the current context

Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(88,152): error CS0103: The name 'leftHandEquipmentEntity' does not exist in the current context

Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(96,128): error CS0103: The name 'leftHandEquipmentEntity' does not exist in the current context

Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(185,88): error CS1061: 'GameInstance' does not contain a definition for 'characterLayer' and no accessible extension method 'characterLayer' accepting a first argument of type 'GameInstance' could be found (are you missing a using directive or an assembly reference?)

**Comment by insthync** [comment]
You can change it following this https://github.com/insthync/UnityMultiplayerARPG_UMA/commit/ba48c9420dbd8f5ac84edf93f572a78a127b326a

I will export the package later

**Comment by Sour-J** [comment]
Thanks!
