### ISSUE TITLE
Question about optimizing network traffic

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1448]
for static entities like harvestables or building parts e.g 
https://gyazo.com/6d21e016559f21a65ca4d343ddf1dbb6

the send interval is 0.1 by default. so it means it updates it every 100ms even when there is no change. is this ideal? i mean when u have 1000 harvestables they always update every 100ms even when noone interacts with it.

is it not better to only broadcast data only when someone interacts with the entitie e.g chop wood, do dmg on walls etc.?

**Comment by insthync** [comment]
For those entities it will be sent spawn, destroy, hp changes network messages only. 

send interval won't affect anything, and it's not sending anything, not sure how you get that info?

**Comment by moepi2k** [comment]
ahhh thanks for info, i dont dig through code for those, just noticed that send interval in inspectors :)
