### ISSUE TITLE
1.50с currentPositionSave BUG

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#145]
If we use this function, then the location in which our character is saved cannot be entered from other locations.
[1.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3873200/1.zip)

**Comment by insthync** [comment]
Fixed, will be included in next update

**Comment by insthync** [comment]
Update version 1.50d which contains this fix is already uploaded.
