### ISSUE TITLE
Characters can't move when switching weapons to machine gun, Pistol and Sniper

### ISSUE THREAD

**Issue by langtusaupt** [suriyun-production/mmorpg-kit-docs#1450]
1- Create new project in Unity 2020.3.27
2- Import asset MMORPG-KIT 1.73b
3- Play Demo
4- Switching weapons to machine gun, Pistol or Sniper
5- Characters can't move
*.  Switching weapons to sword, bow, staff -> No problem with the character

**Comment by insthync** [comment]
You can fix it by delete codes in `DefaultCharacterReloadComponent.cs` at line `211`

So it must be

![Screenshot_941](https://user-images.githubusercontent.com/2697550/152681292-bd277d7a-d2e6-4eea-8f93-a3f0ebc3c938.png)

**Comment by langtusaupt** [comment]
Thanks for correcting
