### ISSUE TITLE
[Mobile UI] Loot - All Button

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1451]
![image](https://user-images.githubusercontent.com/90834568/152680601-098e5885-b54e-46d0-a9c5-d2282d314d62.png)

All Loot Button doesn't work. If it's job is to loot all.

**Comment by BarzoStrike** [comment]
Make changes in "CanvasGameplayMobile" will work

![1](https://user-images.githubusercontent.com/54517546/152681003-3cfdfec3-4d77-4405-a53e-52be4612a53c.png)
![2](https://user-images.githubusercontent.com/54517546/152681010-a25049ea-5928-4eca-ae50-d86b2af420c2.png)

**Comment by DevMMORPG01** [comment]
Thanks
