### ISSUE TITLE
Bug: Hp cost for skills

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1452]
![image](https://user-images.githubusercontent.com/47291794/152707382-56c7c680-1a9a-46a6-847f-61f9954a4db6.png)
For example, a skill has a 20% health cost. After 6 clicks, we get a negative health reserve, but the character does not die, but remains motionless. But if we restart the game, then the character is dead.
I propose to add a limiter, if there is not enough health for the skill, then there will be a warning as with mana "Not enough health". Although even in this case there is a chance to get 0 health, if for example the skill requires 20 health and we will have 20 health at that moment.

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
In `BaseSkill` find for `public virtual bool CanUse` (around line `592`), then find for `if (character.CurrentHp < GetConsumeHp(level))` changes to 
```

            if (character.CurrentHp < GetTotalConsumeHp(level, character))
            {
                gameMessage = UITextKeys.UI_ERROR_NOT_ENOUGH_HP;
                return false;
            }

            if (character.CurrentMp < GetTotalConsumeMp(level, character))
            {
                gameMessage = UITextKeys.UI_ERROR_NOT_ENOUGH_MP;
                return false;
            }

            if (character.CurrentStamina < GetTotalConsumeStamina(level, character))
            {
                gameMessage = UITextKeys.UI_ERROR_NOT_ENOUGH_STAMINA;
                return false;
            }
```
