### ISSUE TITLE
2D movement animation situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1453]
2D Version of the Kit.
I use non-sprite animations. 
![image](https://user-images.githubusercontent.com/47291794/152847559-99169e86-9a5f-4bc8-81d1-f9c92929c068.png)
There is a ready-made animation that shows the movement of the character to the right side. I created the second animation by changing Y to 180 degrees. This allows the animation to show that the character is walking to the left. Similarly with any animations, such as an attack. 
![image](https://user-images.githubusercontent.com/47291794/152847669-80ab0b30-ee55-4eba-b7b5-1d80902cafc3.png)
Left-Right move animation video
https://youtu.be/eo_Ps4QoqSM

The problem is this:
1. If I move to the right with the standard animation and do a right side attack with the standard animation, then everything is fine.
2. Then I start moving to the left with a 180 degree animation and do a attack to the left with a 180 degree animation.
3. I'm moving right again with the standard 0 degrees animations, but the character doesn't return the Y degree back to 0 and continue with 180 degrees.

Video with 0 and 180 degrees "bug"?  
https://youtu.be/O-WczFUMEZU

**Comment by insthync** [comment]
You should check the state in the animator controller, check animator variables, and the playing state.

**Comment by DimasjkTV** [comment]
> You should check the state in the animator controller, check animator variables, and the playing state.

https://youtu.be/B9poXQUgH_o
I like Unity magic. I just added Y 360 for standard animations where was 0 degrees and it works.
