### ISSUE TITLE
guild question

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1454]
is it normal to make a guild in single player then exit and go back in to that same character and the guild is gone doesn't exist. Im afraid this will happen in MMO. am i missing something with the newest version b? maybe a fix or does it not do this in mmo mode. happens with a fresh kit

**Comment by DimasjkTV** [comment]
yes, this is normal for single player. Also with shared storage

**Comment by Sour-J** [comment]
Thanks
