### ISSUE TITLE
Server starts but get shaderr errors

### ISSUE THREAD

**Issue by pacomms** [suriyun-production/mmorpg-kit-docs#1455]
Hi, new start here got the server running on seperate machine of site, using mysql and all works ok, server starts and i can login and play demo, however i get alot of the following error when server starts, and i dont like errors lol 

ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader UI/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?

Any way to stop this issue ?

Thanks
Kurt

**Comment by insthync** [comment]
For the server build, graphic stuff won't be used, so you don't have to worry about it. But seems like we can't hide those messages, it is generated by Unity.

**Comment by pacomms** [comment]
Thansk for that , server does run ok just thought i had caused an error somehow.
