### ISSUE TITLE
[Bug]173 and 173b, (maybe even versions before)

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1457]
when equip machine gun or pistol. player cant move anymore. tested on fresh project

when change custom animation for machune gun and pistole, it only play default animation

**Comment by RunOrDi3** [comment]
also you cant un equip it

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1450

**Comment by moepi2k** [comment]
thank you
