### ISSUE TITLE
[Bug]Fps Arms

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1458]
when add fps arms and enter game, the model will duplicate.
tryied animatorcharactermodel and playablechareactermodel. happens with both

https://gyazo.com/394bf5c4cb44ff337b331ce2ec2449d0

it worked in older version. i tryied it around v1.5x

**Comment by moepi2k** [comment]
https://gyazo.com/33d6d2f4b771a1d6e23212a9c497c2e3

fps hidding object for playablecharactermodel also no working

**Comment by insthync** [comment]
Can you send me your project to my email: ittipon.bay@gmail.com

**Comment by moepi2k** [comment]
sure, i sent u an email

**Comment by moepi2k** [comment]
damn xD thank you very much. happened when i copy pasted male cc.
