### ISSUE TITLE
Where do i add Races

### ISSUE THREAD

**Issue by pacomms** [suriyun-production/mmorpg-kit-docs#1459]
Hi , not sure if this is correct place but i am struggling to find where in the kit i can edit / add races/genders and make multiple selections. I am going to be using your base asset so the standard male and female characters, i have found the prefabs and models but where do i set the races, and how can i get it to be able to select different hairstyles etc, sorry if noob question just i cat seem to find it anywhere.

Thanks

**Comment by insthync** [comment]
You will have to create Race game data from menu: Create -> Game Data -> Character Race

![Screenshot_944](https://user-images.githubusercontent.com/2697550/153204726-2768a941-de82-4cef-a2bd-a8d8d0c8ccee.png)

created Race game data can be set to `PlayerCharacterEntity` component

![Screenshot_945](https://user-images.githubusercontent.com/2697550/153204957-912899ea-748c-431e-a1a9-e8cd338da8b6.png)

**Comment by pacomms** [comment]
Thanks for this , and can you edit stuff already saved in the database ? And is it possible to add extras for the character like hair styles etc ?

**Comment by insthync** [comment]
Not sure what you mean about saving to database, you means that you want to change game data in game database (In Unity editor) or you mean you want to change game-server data which saved in MySQL?, about extras stuff, it is up to how you are going to implement it I didn't offer any specific way yet, but it has a UMA extension which did it [Link](https://github.com/insthync/UnityMultiplayerARPG_UMA). I know you might not use it but if I going to implement it in the kit, I might do it as a plugin which just can change hair, hair color, eyes, eyes color, face, and skin no more extra stuff such as arm length/legs length and so on like the UMA one. 

I don't have to do it soon.

**Comment by pacomms** [comment]
OK Thanks , i will have a play.

**Comment by pacomms** [comment]
Sorry, so i have craeted races of human and orc, how do i add that into the character creation section ? i see race toggles = 0 but i dont see anywhere to add the actual races for selection ?

Thanks again, sorry for daft questions im still learning :-)

**Comment by insthync** [comment]
You have to create toggle layout, for the simple example, you can create a game object which will contain toggles for each race
Then add `ToggleGroup` component to make it able to untoggle other toggle components when players toggle the one that player wants to choose.
![Screenshot_964](https://user-images.githubusercontent.com/2697550/155525958-37e04c5b-c82d-4ce4-b727-aeaa7708862b.png)

Then in the game object, it will have toggles as children, then you have to set group into each toggle
![Screenshot_965](https://user-images.githubusercontent.com/2697550/155526282-a1f2ca25-7708-4d56-99b4-d566daed33d8.png)

Then set `Toggle` components to `UICharacterCreate` -> `Race Toggles`

![Screenshot_966](https://user-images.githubusercontent.com/2697550/155526604-5e181b73-30c6-4b35-89a7-a09eaa634fc2.png)

![Screenshot_967](https://user-images.githubusercontent.com/2697550/155526581-81f39563-a947-4ae9-94e7-f42aa4d9b6d3.png)
 
![Screenshot_968](https://user-images.githubusercontent.com/2697550/155526627-5cac00f0-41f6-4c4d-ad39-c4fcd052bffb.png)
