### ISSUE TITLE
Package issues with the kit.

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#146]
In unity 2019.2.12 I was installing the correct packages for Vegetation Studio Pro. My project blew up. So i created a fresh project set up these packages with no issue and then installed the kit and it blows up every time. In order to use vegetation studio you need to install Jobs, Burst, Collections, PostProcessing, and Math. Vegetation Studio Pro is almost an industry standard for unity at this point and though I wouldnt expect you to provide support out of the box I should be able to install the correct packages to use it and the kit.  Heres a sample of some of the errors.
![image](https://user-images.githubusercontent.com/57778639/69368264-c7b64f00-0c67-11ea-90e6-b62814215486.png)
Hopefully this is something you can fix or perhaps I did something wrong. Thanks for your time.

**Comment by insthync** [comment]
![Screenshot_182](https://user-images.githubusercontent.com/2697550/69370522-afc6e580-0cd0-11ea-85e1-287e264de4c1.png)
Is Unity UI package already turned on?

**Comment by Fallen01** [comment]
Yes and i just reinstalled it and text mesh pro to make sure.
![image](https://user-images.githubusercontent.com/57778639/69371523-fc2d0980-0c6d-11ea-9e9b-a109990c0bef.png)

**Comment by insthync** [comment]
Still having an issues?, As I see in the logs it was told exactly that it's no installed UI package.

**Comment by Fallen01** [comment]
In the screen shot youll notice that I have the UI package installed and no still loaded with errors.

**Comment by Fallen01** [comment]
I think collections is causing this somehow.

**Comment by jaredgregersen** [comment]
I am having the same issue as Fallen01 (On Unity 2019.2.21f1), while trying to use Magica Cloth (which also uses Jobs, Burst, Collections, and Math), in conjunction with MMORPG Kit. After fighting with it for over a day (including so many slow project rebuilds, etc...), I finally realized it was MMORPG Kit having issue with those packages. I also get the Unity UI errors, as Fallen01 mentions (even though it is installed), and a host of other errors, related to Namespace issues, especially related to Unity.Collections related methods. I went through each package, to try and narrow down where the error was occurring, and it happens each time when trying to install Collections (any version) through package manager, if MMORPG Kit is also present. So far, I haven't found a solution. 

I have tried just about every version combination of Burst/Jobs/Collections available through Package Manager, along side MMORPG Kit, to no avail. Just to be clear, if you install Collections, by itself, or if you install Jobs (a version that auto-installs Collections as a dependency) the error will happen.

I have scoured the internet for hours, looking for issues related to Collections, but hadn't found any related to what I am seeing, until I realized the conflict was between those MMORPG Kit and Collections... I came here and found this Open issue, so thought I would add that I am also seeing the problem. Needless to say, but I am relieved (though, frustrated) to see someone else, having a similar issue. 

I really like MMORPG Kit, though (having used several others). I think it is the most straight-forward design, so I hope this can be resolved.

**Comment by insthync** [comment]
Okay, I will try it today

**Comment by jaredgregersen** [comment]
Cool! BTW, I just noticed, if I import everything from MMORPG Kit, except the ProjectSettings.asset, the Unity project will not produce the errors (Of course, that leaves other parts that MMORPG Kit needs, out, Layers/Tags…). I suspect the ProjectSettings.asset has a configuration that isn't compatible with Unity.Collections, somehow, probably under Player or Quality, but I am not totally sure.

If I do import that last ProjectSettings.asset from the MMORPG Kit asset, the errors appear. It looks like after importing ProjectSettings.asset, one thing it changes is the scripting language under 'Edit->Project Settings->Player->Scripting Language', to "Mono". For the other package mentioned, I need to have this set to "IL2CPP", but even after setting it back to "IL2CPP", the errors remain (which may be some goofy Unity bug...)

And just FYI, these are the only 'Player' settings I must explicitly change, from a default 2019.2.21f project, for Magica Cloth (and Burst/Jobs/Collections/etc) to work:

![image](https://user-images.githubusercontent.com/46325243/77837019-c4f1cc00-7129-11ea-9389-72c04bf27697.png)

Hope this helps!! Thanks!

**Comment by insthync** [comment]
I try to create new project then import following package: Burst, Collection and Job. Then the issues occurs, it's just a empty project, no script files, I will ask in Unity forum about this.

**Comment by insthync** [comment]
Try Install: Burst version 1.3.0 preview 5, then install Job, then find `System.Runtime.CompilerServices.Unsafe` in `Project` tab and remove. 
And reopen the project.

**Comment by MostHated** [comment]
Not sure if it is related in this particular issue, but in a few instances of things randomly blowing up that seem like they have to do with the package manager, you have to hit this

![](https://i.imgur.com/134r4cI.png)

**Comment by jaredgregersen** [comment]
It worked! As a first attempt, I updated Burst to "1.3.0 preview 5" on an already existing project, left Jobs installed (0.1.1), removed the DLL you mentioned, and then restarted the Project/Unity. Thank you! Great work figuring it out!
