### ISSUE TITLE
2D Monsters situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1460]
Monsters tremble/twitch when following the character. This happens if the monsters and the character have a high movement speed.

First video: character has 4 speed, monster has 5.
https://youtu.be/8z1anc40PBU

Second video: character has 1 speed, monster has 1
https://youtu.be/hlQuVd0zXc4

**Comment by insthync** [comment]
Maybe because of camera
