### ISSUE TITLE
Missing Text when running client only

### ISSUE THREAD

**Issue by pacomms** [suriyun-production/mmorpg-kit-docs#1461]
Hi, not sure if this is a bug or i am doing something wrong. 
I can build the server and client no problem, and if i run the clients outside unity all is well. However if i run the server outside unity and then try and run the client only scene live in unity all the text is missing from the server select screen and the character details, i can connect if i press the box but there is no text is this a bug or am i simply doing something wrong. Only thing i have change is the server connection details in MmoNetworkSettings, i have changed the servers address and title.

Thanks
Kurt

**Comment by insthync** [comment]
You may try to change Unity editor window size.
