### ISSUE TITLE
New Map not starting

### ISSUE THREAD

**Issue by pacomms** [suriyun-production/mmorpg-kit-docs#1462]
Hi , 

i have created a really basic map to test , i have set it as map 003 , then set the novice class to spawn there at 0 0 10 , i have added it to the build and created a map info file, and build the server and client, however when i try and spawn a novice it says map server not ready , all ports from 8000 to 8100 are open , any ideas what im missing , i have tried with and without a ai mesh , looking in server log only map 001 and 002 seem to be launching 

Thanks ,

**Comment by Sour-J** [comment]
does the new map have at least 1 object and baked navmesh?
also did you add the map to the config or inspector? and also the game instance map info?

**Comment by insthync** [comment]
Did you add a new map to `spawnMaps` part in `serverConfig.json` ?

![Screenshot_949](https://user-images.githubusercontent.com/2697550/153534512-fe5ec298-acd1-4862-acc0-687b6f0a3895.png)

**Comment by pacomms** [comment]
I added  a nav mesh and i did the add mapinfo part, how do you add the map to the config or inspector ?

**Comment by pacomms** [comment]
Found the issue, i had not set it in the game database .. dohh
