### ISSUE TITLE
Question about player layers

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1463]
Do the player characters layer need to be changed to player? right now its on character not sure with the new update seems it needs to be player

**Comment by insthync** [comment]
No, you can set settings in GameInstace to Character
![Screenshot_950](https://user-images.githubusercontent.com/2697550/153534670-d4f6e9d2-dbbc-4a29-8d4e-99b9ff0e1b0c.png)
