### ISSUE TITLE
[Bug]Skill Item

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1469]
when use a skill with Skill Item, it throws this error and let character stuck

https://gyazo.com/c8c9c47cbe06784735f511524646a439
https://gyazo.com/dd4c85b7f96247e55d6e7e9e7d5674a0

**Comment by insthync** [comment]
When?

**Comment by moepi2k** [comment]
i just created new Skill Item and add an existing skill (which works when i use without a skill item)
i also tried legacy item and in dropt down selected Skill Item.

i dont know if it happen because i use AimAtCursorController

**Comment by moepi2k** [comment]
hi, found the issue, i was on 173 and use a community addon. i noticed u changed charactermodel caching. so fixing those lines and now it works :)
