### ISSUE TITLE
Scriptable object

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#147]
In the new version, dragging objects works very poorly. Each time after dragging us returns to the top of the list. 1 video shows how it works now. 2 videos show how this worked before.
[1.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3877875/1.zip)
[2.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3877876/2.zip)

The tin begins, we make drop tables. I have tables of 300-500 items. Every time I assign an item, it pushes me to the top of the list. Lol

I guess it started after the color change.

**Comment by insthync** [comment]
As I try in version 2019.2.10 it's good. So I think it's Unity editor bug

**Comment by DimasjkTV** [comment]
> I also encounter these issues too, but then I try with version 2019.2.10 it's good. So I think it's Unity editor bug


I just launched the set version 1.48 and 150s and they work differently. Have you used more than 30 objects in your test?

**Comment by insthync** [comment]
Here I test it with Unity 2019.2.10

[bandicam 2019-11-22 19-31-18-512.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3879487/bandicam.2019-11-22.19-31-18-512.zip)

**Comment by DimasjkTV** [comment]
> Here I test it with Unity 2019.2.10
> 
> [bandicam 2019-11-22 19-31-18-512.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3879487/bandicam.2019-11-22.19-31-18-512.zip)

what could affect this error in unity? With 1.48 all fine but 1.50c...

**Comment by insthync** [comment]
I try to improve the package and I won't revert it because of bugs that I didn't make. So if you want to remove it, try find `[ArrayElementTitle(` and remove the lines.

**Comment by insthync** [comment]
Or I should use #define directives to check version of Unity ?

**Comment by DimasjkTV** [comment]
> Or I should use #define directives to check version of Unity ?


no. Just now for normal work with this kit we need the unity version 2019

**Comment by insthync** [comment]
It's because Unity's Property Drawer bugs, You can see codes in `ArrayElementTitleDrawer` it's very simple as you can see in the document (https://docs.unity3d.com/ScriptReference/PropertyDrawer.html)

**Comment by DimasjkTV** [comment]
> It's because Unity's Property Drawer bugs, You can see codes in `ArrayElementTitleDrawer` it's very simple as you can see in the document (https://docs.unity3d.com/ScriptReference/PropertyDrawer.html)

By the way, in the game data base I have no jumps, but there is no color there either

**Comment by DimasjkTV** [comment]
lol, when I closed these tabs, I inserted the following without jumping
![image](https://user-images.githubusercontent.com/47291794/69477511-31656300-0df8-11ea-8a62-08f9735d3a99.png)
