### ISSUE TITLE
[Bug]PlayerableCharacterModel missing fields

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1470]
for fpsarm for example when i add the PlayableCharacterModel, some fields are missing like effect container and so on

this is fpsarms
https://gyazo.com/7592492a9af7262eec2428dbea9322b5

this is normal model
https://gyazo.com/9776e53628e5eb5051f134e59c9158d5

**Comment by juniormagalhaes** [comment]
> for fpsarm for example when i add the PlayableCharacterModel, some fields are missing like effect container and so on
> 
> this is fpsarms https://gyazo.com/7592492a9af7262eec2428dbea9322b5
> 
> this is normal model https://gyazo.com/9776e53628e5eb5051f134e59c9158d5

Close and open the prefab, which solves it, I had the same problem

**Comment by moepi2k** [comment]
Not working, even closing unity and reopen not works

**Comment by moepi2k** [comment]
after adding PlayerCharacterEntity Component, the fields appear. but this seems wrong, because i use it for my fps arms.
how do you manage it with fps arms?

**Comment by insthync** [comment]
I will check it

**Comment by moepi2k** [comment]
ok thx,

one thing more. in older version you had an option to attach the fps arms, now in latest version you only have CharacterModelManager to attach it. so it instantiate fps arms at camera.

but how to handle the fps camera to follow players up/down when crouch?
camera stay always in same height.
https://gyazo.com/78548cd9c4cc0af3544ca2687eca8594

**Comment by moepi2k** [comment]
p.s when i add charactermodel and remove it, the fields appears in PlayableCharacterModel. maybe this can help to find issue

**Comment by insthync** [comment]
Fix it by change codes in `BaseCharacterModelEditor`
At line `23` changes codes to `model.MainModel = model;`
![Screenshot_952](https://user-images.githubusercontent.com/2697550/154342200-28dc7093-e35a-490e-b657-723e4bc10b7d.png)

**Comment by moepi2k** [comment]
great that fixed the issue :)

thank you very much
