### ISSUE TITLE
[Bug]Pets

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1471]
i working on pets and noticed few bugs
1) for UI -> Prefab UICharacterSummon -> UiCharacter - UiGage Stamina

https://gyazo.com/6cb98f01dc99e16f92ad3d42e3f95a18

It works for Hp and Mana but not for Stamina, also Text for Stamina.

**Comment by insthync** [comment]
How is it not work?

**Comment by moepi2k** [comment]
sorry my fault, it just showed always 0. but the pets stam was set to 0.
