### ISSUE TITLE
Duplicate names and guilds issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1472]
you can make the same named character as anyone or same guild name this is bad for people impersonating people in-game don't know if it will mess with MYSQL but people can have the same names

**Comment by RunOrDi3** [comment]
No you cant make the same name .. something wrong in your side .. kit is fine

**Comment by RunOrDi3** [comment]
![Untitled](https://user-images.githubusercontent.com/64667641/154661227-10f30ac0-113b-4dc4-93f3-eb7c65147b2e.jpg)
i use MySQL

**Comment by Sour-J** [comment]
Hey I appreciate the help.. Wondering how I would fix it then I didn't modify the core, I have to find where the setting is to enable it because as of right now I can make multiple of the same name on MMO and the same guild name did you try guild name in MMO @RunOrDi3 ?

Also you can make names with spaces and ASCII symbols that evade GM commands you can't do any commands when somebody makes spaces after the name or ASCII or symbol

**Comment by RunOrDi3** [comment]
also fine with guild , but yea you can use spaces before and after also you can use ( @!#$%^&*()) with names too and its bad

**Comment by Sour-J** [comment]
> @Sour-J also fine with guild , but yea you can use spaces before and after also you can use ( @!#$%^&*()) with names too and its bad

I'm sorry but Its much more severe than it sounds I have 1000's of players making names with spaces and you can't see the spaces therefore you can't ban or mute them because or any GM command because they can put some in front and on the end so I could make the name run 1000 different ways with spaces before and after


also the symbols are bad it's not just those basic symbols... It's ALL symbols here's some of the bad ones that people abuse and can put after any name or just alone

Here's some examples of symbols that can be used:
卐 卍࿕࿖࿗࿘ꖦ there's hundreds more...

**Comment by LordPhrozen** [comment]
if (Regex.IsMatch(str, "^[a-zA-Z0-9]*$")) {
            //This looks good fam!
        }
        else {
            //the hell is this?! throw an error!
        }
}

**Comment by LordPhrozen** [comment]
Awesome. I'd say format checking needs to happen on guild names too @insthync . I don't think anyone wants to see:

"GuildName"
"GuildName "
"GuildName  "
and
"GuildName    "

**Comment by RunOrDi3** [comment]
i use the new version ! its fine to me like i show you

**Comment by Sour-J** [comment]
> I'm using the new version ! its fine to me @Sour-J

I'm glad it's fine for you but it's not fine for me and neomis not sure how your comment helps the situation.

**Comment by Sour-J** [comment]
> I am gonna fix it, but after I saw last 3 comments, I don't want to do anything :(

Nobody is making you do anything, do whatever you want. I didn't expect anything to be done anyway. I'm just frustrated with things working then not working after updating. I am sorry for my frustrations but were all human.  Isn't got for reporting issues? I remember when you thanked me for donating to you and you apologized for all the bugs. The kit is great only has a few small bugs like this one.

I'm a customer I'm just trying to get help for something but if you want I'll stop reporting issues I find and just let it be if anything I'm just trying to help the future of the kit.

I respectfully told somebody that their not helping I don't see anything bad with what I said. If how people talk to each other is what determines if you fix things then forget it. We're all adults here no reason to refuse service because of how people talk... I didn't say anything bad... I just asked for the developer...

**Comment by insthync** [comment]
Hmm, that comment is bad for you?

**Comment by Sour-J** [comment]
I think that text can be taken wrong were all adults here... I appreciate any fixes you do @insthync I am just human and very frustrated with something working fine then breaking when I didn't touch it.

If you can fix it I'll buy you a coffee when it's fixed. No disrespect here....  If you don't do anything that's fine too.

Thanks for your time
