### ISSUE TITLE
Would it be possible for you to change the HarvestableEntity Private Variable to Protected?

### ISSUE THREAD

**Issue by gordowebdesign** [suriyun-production/mmorpg-kit-docs#1476]
Would it be possible to make the "private bool isDestroyed;" on HarvestableEntity.cs into "protected bool isDestroyed;"?  

Thank you for your time and hard work!

![private to protected](https://user-images.githubusercontent.com/71939436/154872343-551a3efd-cb8c-4707-b7bc-1dc1e59f49d3.JPG)

(as a side note, for context of why i wanted to do this, i have attached the script i was working on)
[HarvestableEntityNewEvents cs.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/8105409/HarvestableEntityNewEvents.cs.txt)

**Comment by moepi2k** [comment]
if you do maybe also for other entitie like BuildingEntity?
its also something i need to change to protected after every update :)

**Comment by insthync** [comment]
Okay

**Comment by insthync** [comment]
You can list more of them

**Comment by moepi2k** [comment]
BaseCharacterModel :)
