### ISSUE TITLE
Animation For Jump State for FPS arms not working

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1477]
like title said
https://gyazo.com/99ed945d244589b57ad07a3d184040ee

u can add animation to jump state for fps arms but it never plays

**Comment by moepi2k** [comment]
one more thing noticed.
did u changed someting with this? 
https://gyazo.com/71ce39be273c19dde2ab73d69bb6ff91

with that setting it just shoot one projectile that do damage for 8 times.

in the past u was able to add shotgun style projectil

**Comment by insthync** [comment]
I will fix them

**Comment by insthync** [comment]
Fixed in 1.74
