### ISSUE TITLE
problem with server auth.

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1478]
i wont stress you with this again :P

but since i updated my project i noticed alot of rubberband when use server auth. 2 other ppls talked to me they have same issue.
now i created fresh project and tested by myself again. -> Tested version is 173b
but it even happen in C

https://gyazo.com/f9495eef38b1bce30c0aa42fe37f979d
like u can see in video only normal move and sprint will sync player. when u "walk" or "crouch" it stop sync and start rubberbanding.

**Comment by RunOrDi3** [comment]
https://www.youtube.com/watch?v=OX-0w3gFmww here is another video when i face any stone

**Comment by Sour-J** [comment]
Same issue here if I use server auth it laggs everyone on the server so bad they can't even move disconnect them after a while due to lagg too

**Comment by insthync** [comment]
@moepi2k Oh, I will check it.
@RunOrDi3 This can occur because the server can have different physic calculating results with the client.

**Comment by insthync** [comment]
In case you may want to know how it works nowadays you can read from this https://doc.photonengine.com/ko-kr/bolt/current/community-wiki/extra-bits/use-cases

For non-server auth movement, it works as `Completely Client Authoritative`, the server auth movement one is as `Completely Client Predicted, Server Authoritative Using Commands`, which still has simulation problems.

**Comment by moepi2k** [comment]
> In case you may want to know how it works nowadays you can read from this https://doc.photonengine.com/ko-kr/bolt/current/community-wiki/extra-bits/use-cases
> 
> For non-server auth movement, it works as `Completely Client Authoritative`, the server auth movement one is as `Completely Client Predicted, Server Authoritative Using Commands`, which still has simulation problems.

very good article. do you plan to make it hybrid styled like in point 3?
i know some ppl dont like client auth, but its always depends on the kind of game they doing. but i think there need to be a good balance between security and experience while playing the game (e.g hit registration movement) and so on.

**Comment by RunOrDi3** [comment]
> @moepi2k Oh, I will check it. @RunOrDi3 This can occur because the server can have different physic calculating results with the client.

thank you so much , i have fixed it now

**Comment by insthync** [comment]
In 1.74, client auth movement will be validated at server

**Comment by Sour-J** [comment]
> In 1.74, client auth movement will be validated at server

Thank you for all you do. I'm wondering how much strain is on the server in the new version is there a way to go back to no server auth movement like 1.73 had the check box in the inspector for it. Not sure how its handled now but im worried about lagg still. I will try 1.74 and see how it goes!
