### ISSUE TITLE
150с BUG Skill reset items

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#148]
Items that reset skill points when used are not spent.

Attributes reset works well

**Comment by insthync** [comment]
Use can fix it by changes some codes in `BasePlayerCharacterEntity_UseItemFunctions.cs` Function `UseItemSkillReset` Line `149`
from `this.ResetSkills();` to `this.ResetSkills(itemIndex);`

**Comment by insthync** [comment]
Update version 1.50d which contains this fix is already uploaded.
