### ISSUE TITLE
[Bug] Currencies not working in killing rewards 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1481]
When you add currencies in Killing rewards in monsters SO , currencies will never drob from monsters .. i have tested with fresh project too and same .. tried to remove gold and add fame only and still never get them .. tried item drob table too and same issue
![1](https://user-images.githubusercontent.com/64667641/155154583-e9fe654b-ba39-4634-9e89-d8413d918556.jpg)

**Comment by insthync** [comment]
`BaseMonsterCharacterEntity`
![Screenshot_963](https://user-images.githubusercontent.com/2697550/155183350-aa2f643c-1303-4781-9c18-94c850b98500.png)

**Comment by RunOrDi3** [comment]
> `BaseMonsterCharacterEntity` ![Screenshot_963](https://user-images.githubusercontent.com/2697550/155183350-aa2f643c-1303-4781-9c18-94c850b98500.png)

now i get yes currency but i get only 1 .. min and max doesnt work.. whatever i add , i just get only 1 from each currency from monsters
![Untitled](https://user-images.githubusercontent.com/64667641/155230596-da87e71d-ebd4-4e7e-a7e5-23c825383a1a.jpg)

**Comment by moepi2k** [comment]
works for me

**Comment by RunOrDi3** [comment]
was my mistake , thanks alot suri
