### ISSUE TITLE
[Bug]Grenade Collide with player self when throw.

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1482]
When throw grenade, grenade collider with player self and the WarpPortalDetector on the players prefab.
in default demo u need to put spawntransform a bit more in middle of prefab because else grenade spawn outside of players collider

https://gyazo.com/78fe6c9e79d1a9c2636fd43c159191e5

**Comment by insthync** [comment]
Try set rigidbody's Interpolate to Extrapolate and Collision Detection to Continuous Dynamic

**Comment by moepi2k** [comment]
thats not working
https://gyazo.com/38ef2b2ab111b601de3a7f7cd17a25a4
