### ISSUE TITLE
Cant change character start location

### ISSUE THREAD

**Issue by pacomms** [suriyun-production/mmorpg-kit-docs#1483]
Hi  so i have set the characters spawn location to override and set in some coordinates, saved and rebuilt and when i spawn in its not following that spawn location its still the origional, is there somewhere else i need to change it or set it so the override works ?

Thanks

**Comment by insthync** [comment]
When character dead and respawn or when character created

**Comment by pacomms** [comment]
when dead or spawn it doesnt go where i set in class override start, is there somewhere else this is or can be set that may be stopping it ?

**Comment by insthync** [comment]
Are you overrides `MapInfo` -> `GetRespawnPoint` , right?
