### ISSUE TITLE
Unity 2021 errors after importing Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1484]
Hi suri , im using 2021 and always need to restart unity after changing any thing in any so or a prefab to make them works .. so i have followed this article >> https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021 but doesnt work , i get 280 errors
![1](https://user-images.githubusercontent.com/64667641/155714875-9a77040b-02ac-4e2b-8c72-bb34b7ccc34b.jpg)
i have deleted ( System.Buffers.dll , System.Memory.dll , System.Threading.Tasks.Extensions.dll ) and then get 280 errors , i imported the package which added in this article but i still have the 280 errors

**Comment by insthync** [comment]
Is it solved?, how you solve it?

**Comment by RunOrDi3** [comment]
@insthync nope i didnt , but i try to dont bother you .. i reimported the package again using the default one with those dlls

**Comment by insthync** [comment]
How about this setting ?
![Screenshot_971](https://user-images.githubusercontent.com/2697550/155806790-f5819aa7-7fc4-4f96-9158-b9f118391c3c.png)

**Comment by RunOrDi3** [comment]
sorry , i still have the issues :(
![1](https://user-images.githubusercontent.com/64667641/155810818-82e28d15-c2f3-49ed-a86c-d449931b9cee.jpg)

**Comment by Randolphjand** [comment]
Did you delete these files first. 
You have to delete following files:

Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Buffers.dll
Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Memory.dll
Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Threading.Tasks.Extensions.dll

**Comment by insthync** [comment]
Try revert everything back, I want to see error messages

**Comment by RunOrDi3** [comment]
> Did you delete these files first. You have to delete following files:
> 
> Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Buffers.dll Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Memory.dll Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/System.Threading.Tasks.Extensions.dll

yes i did

**Comment by RunOrDi3** [comment]
> Try revert everything back, I want to see error messages
![Untitled](https://user-images.githubusercontent.com/64667641/156345927-db3af057-bf3e-4078-a265-006ff4b1de48.jpg)
here it is

**Comment by RunOrDi3** [comment]
@insthync here it is with fresh project 
![Untitled](https://user-images.githubusercontent.com/64667641/156346694-2410e774-97da-4319-a69a-6cf22a6ca01d.jpg)
