### ISSUE TITLE
Can't share Player Storage in single mode?

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#1486]
Where do I fix it to make it Player Storage share?
Let me know and I'll do it myself

**Comment by insthync** [comment]
Try set `CanUseByEveryone ` setting to `TRUE`

**Comment by insthync** [comment]
Share to who?, your other characters?

**Comment by insthync** [comment]
You have to change how it load and save storage items in `DefaultGameSaveSystem` and also changes how to send list of items in storage to player in `LanRpgServerStorageMessageHandlers` and `LanRpgServerStorageHandlers`
