### ISSUE TITLE
UMA convert AnimatorCharacterModelUMA

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1489]
for the UMA there is an extended version of AnimatorCharacterModelUMA

when convert it to PlayableCharacterModel it replace with default one.

https://gyazo.com/a3d1864c3376e45b7e071ebe203dd35c

**Comment by moepi2k** [comment]
[PlayableCharacterModelUMA.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/8192475/PlayableCharacterModelUMA.zip)

i tired to convert it to PlayableCharacterModel

it works but when changing gender it stuck on male.
https://gyazo.com/68279fe81fea2cf0ad674b85d21371bb

maybe u can check it out  when u have free time :)

**Comment by insthync** [comment]
I will update it

**Comment by moepi2k** [comment]
ohh thank u very much. one coffee for u my lord :)

**Comment by insthync** [comment]
Not sure it can do it, I will check it again on this weekend, it might have to modify some of UMA codes

**Comment by moepi2k** [comment]
ouuu, i hope you find a solution, because the PlayableCharacterModel is alot better than the old one, let me know :)

**Comment by a5196** [comment]
I import UMA 2.12 and addon 1.17.Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(76,129): error CS0103: The name 'rightHandEquipmentEntity' does not exist in the current context
Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(88,152): error CS0103: The name 'leftHandEquipmentEntity' does not exist in the current context
Assets\UMAExtension\Scripts\AnimatorCharacterModelUMA.cs(96,128): error CS0103: The name 'leftHandEquipmentEntity' does not exist in the current context

**Comment by moepi2k** [comment]
any updates for PlayableCharacterModelUMA? still struggling with it :/
