### ISSUE TITLE
Using melee skills animation while dualwield issue

### ISSUE THREAD

**Issue by Syrus198327** [suriyun-production/mmorpg-kit-docs#149]
Whenever i use a melee skill with a weapon in both hands. First time use of the skill works. But if i use the same attack skill the characters does the left hand attack animation if i use it again after the animation for skill plays it repeats right hand does the skill but left hand wont am i missing something. In the skills ? To make both right and left hand do the skill anmation if remove the left hand weapon the skill plays correctly. If i remove the right hand weapon. And leave the left hand weapon equip left hand wont play the skill animation

**Comment by Syrus198327** [comment]
Work around equipment type 2hand main weapon for both hands ill have to make dual weapon items for the animation to work correctly for both hands.

**Comment by insthync** [comment]
You want it to play only 1 animation, right?

**Comment by Syrus198327** [comment]
Yes when using the activate animation for the skill

**Comment by Syrus198327** [comment]
Yes for the skills just looks weird when activating the skill a second time and the left hand weapon does the normal attack instead of the correct animation

**Comment by insthync** [comment]
Okay, I will check it. I might have to fix something

**Comment by insthync** [comment]
As I try it's working correctly, I want to see your settings. Please capture screenshot of your skill animations. Like this:
![Screenshot_196](https://user-images.githubusercontent.com/2697550/69782423-90095300-11e3-11ea-908c-485140870d13.png)

**Comment by Syrus198327** [comment]
![15749622880896145871986314838269](https://user-images.githubusercontent.com/56697866/69824819-0b1a3b80-11db-11ea-80e5-fa2d4b3963af.jpg)

**Comment by Syrus198327** [comment]
I made 2 skills the same to see the non area attack skill works fine but the areaakill one does the left hand attack animation instead of the skill

**Comment by insthync** [comment]
Is this still occurring?, I remember that I was fixed it.
