### ISSUE TITLE
Creating missing PlayerCharacter...

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#1490]
Acceptance of changes in character prefab show messages: 
Creating missing PlayerCharacterBuildingComponent component for PlayerCharacterEntity in Human_Male.
Creating missing PlayerCharacterDealingComponent component for PlayerCharacterEntity in Human_Male.
Creating missing PlayerCharacterNpcActionComponent component for PlayerCharacterEntity in Human_Male.
But all changes are saved... 
P.S.: ver. 1.73c

![1](https://user-images.githubusercontent.com/16080577/157013967-72b645c9-4521-4c2b-89d5-28974a8cdaaf.jpg)
.

**Comment by insthync** [comment]
You don't have to worry about it, new Unity just added missing required components (components that were defined by `RequireComponent` attribute on top of character entity class)

**Comment by brabaris** [comment]
I understand, thank you, I couldn’t answer right away, shelling of Ukraine is going on ...
