### ISSUE TITLE
Fixed: Monsters Animation Not Fluently Switching

### ISSUE THREAD

**Issue by darkdaysbyron** [suriyun-production/mmorpg-kit-docs#1491]
Im having a problem with monster animations when it comes to them stopping after walking it seems to jump between the idle and moving animation multiple times really quickly making a janky looking animation.

I thought it might just be the humanoid model and animation but when i changed it to a wolf model and animation to it did the same thing whenever the wolf stopped it did a janky switch animation between idle and wander.

Im not sure if ive done something wrong or theres a fix for this I can probably add a video if need be.

Thanks in Advance

Fixed: It was the Height Mesh

**Comment by insthync** [comment]
Not sure how is it?, can you attach its video to show me how it is?
