### ISSUE TITLE
Party Issue (when in party and party member's character has been deleted)

### ISSUE THREAD

**Issue by Leerael** [suriyun-production/mmorpg-kit-docs#1493]
In MMO:

Steps to reproduce:
- Start a party with another player's character.
- Delete the other player's character in character select. (they don't disappear from the party).
- Try to kick the other player's character because they're apparently still in the party? (doesn't kick them).

Feel like what needs to happen is one of the below:
- Characters are automatically booted from the party on disconnect.
- You should be able to kick the deleted character from the party.
- The party should update if the character is deleted.

This last one is preferred with the current setup of not kicking people from party if they disconnect.

**Comment by insthync** [comment]
Okay, I will check it.

**Comment by insthync** [comment]
Fixed in 1.74
