### ISSUE TITLE
[Issue] with updated version UnityMultiplayerARPG_ShooterExtensions

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1496]
![Untitled](https://user-images.githubusercontent.com/64667641/158582232-ced56b7b-df52-4708-8fbc-ba7399475376.jpg)
when i updated it to my project , this errors appear

**Comment by insthync** [comment]
You have to use older commit of `UnityMultiplayerARPG_ShooterExtensions` [here](https://github.com/insthync/UnityMultiplayerARPG_ShooterExtensions/tree/1bd5bc67e4177bf6b50275046e83fe1f5af0db09), I'm currently working on new version of MMORPG KIT.

**Comment by RunOrDi3** [comment]
@insthync ahh ok , thanks alot <3
