### ISSUE TITLE
Hide completed quests on Quest Dialog UI

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#15]
Can you add an option to hide completed quests in the UI quest dialog. When you finish a lot of quests it's hard to follow the remaining quests.
Thank you

**Comment by insthync** [comment]
Yes, I can :)

**Comment by Koodetat** [comment]
Great ! Thank you

**Comment by Koodetat** [comment]
Done ! Thank you
