### ISSUE TITLE
Falling animation issue

### ISSUE THREAD

**Issue by Syrus198327** [suriyun-production/mmorpg-kit-docs#150]
Falling animations plays while going down hill or stairs

**Comment by insthync** [comment]
Try increase `groundCheckDistance` value

**Comment by Syrus198327** [comment]
Yes been setting different numbers i get the same results im using rootmotion for my animations and have the jump fall air and move checked for rootmotion

**Comment by insthync** [comment]
I don't know how your character animation move, Try to turn off `useRootMotionForFall`.

**Comment by Syrus198327** [comment]
I turned off Airmove  jump and fall rootmotion and move is still on. Iam not having the fall animation issue any more with animation that are non rootmotion just the one with rootmotion
