### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1501]
Your super busy with much more important stuff at the moment, so no pressure. I noticed that your A* addon for 2d could easily work with 3d. I would like to suggest an A* movement entity for the demo. People have brought it up many times and it would be a cool option. Thanks for your time.

**Comment by majimboo** [comment]
I think this would help a lot since navmesh is giving most of us issues. 👍

**Comment by Fallen-Entertainment** [comment]
Also A* works outside of unity...;)

**Comment by tylerguitar75** [comment]
good call fallen :)

**Comment by insthync** [comment]
Not sure what do you mean, you want me to include it to the package which selling at asset store?, because [this](https://github.com/insthync/UnityMultiplayerARPG_2DAI) is already has a 3d A* integrated (but might have to improve it)

**Comment by Fallen-Entertainment** [comment]
currently have the 2DAI uses the A* Implementation and its aimed more at 2d. With some tweaks it works on 3d but it would be nice to see an example from you. Anyway I know you have better things to do I just wanted to suggest it cause people ask for it ALL the time. Thanks for your time.

**Comment by insthync** [comment]
Not sure that [this](https://github.com/insthync/UnityMultiplayerARPG_2DAI/blob/master/Scripts/AstarCharacterMovement3D.cs) is it?

**Comment by Fallen-Entertainment** [comment]
ya thats it but a few people have bumped into issues it would be cool to see a little demo and a few 3d examples.  Its constantly asked for, maybe great to include a demon in the kit. Anyway thanks for your time, its appreciated.
