### ISSUE TITLE
Vehicle + CLIENT_BUILD Bug

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1502]
Not sure why this is happening but when you do a CLIENT_BUILD the vehicles wont let you activate, you cant use the vehicle once you build in a CLIENT_BUILD. Do you know how I can resolve this? I would like to use the client build but need players to be able to use vehicles.

**Comment by Sour-J** [comment]
Not using CLIENT_BUILD for a server build its for a client build. I havnt tried MMO with this function it didnt work on LAN as a test so I assumed it wouldnt work in MMO too. When using client build for single player or lan not sure on mmo hadn't tried.  But the vehicles are no longer accessible but everything else is fine. I appreciate your help on this.

**Comment by insthync** [comment]
Don't use `CLIENT_BUILD` for single-player/LAN games because when you are going to play it, it has to simulate everything as a server, when you play the single-player or hosting for LAN multiplayer, you can assume that it is both server and client in the instance.

**Comment by Sour-J** [comment]
Thanks I'll try in MMO

**Comment by molonlabe1337** [comment]
No I don't use client build on server it's a client build I didn't test in
MMO just lan it does this and single player I will test in MMO eventually
but I assumed it didn't work in MMO if lan is not
