### ISSUE TITLE
Spinning camera

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1503]
Im using shooter controller and when I alt tab out of the game and back into the game the camera is spinning uncontrollably. I have to exit the game completely to fix the issue. Any idea why this would be happening? I appreciate your help everything is fine until I tab out and back in. It's in Fullscreen and a build doesn't do it in the editor it's very strange. I was going to try messing with the camera but wanted to check with you maybe someone had this issue before.

**Comment by moepi2k** [comment]
do you plugged in a joystick or gamepad? i had similar issues with it

**Comment by Sour-J** [comment]
> do you plugged in a joystick or gamepad? i had similar issues with it

Thanks for the reply no gamepad or joystick just regular setup shooter when I alt tab out of a build and back into the game the camera just spins

**Comment by insthync** [comment]
I guess it may occurring because of the controller, but I can't reproduce it yet.

**Comment by Sour-J** [comment]
> I guess it may occurring because of the controller, but I can't reproduce it yet.
So in a default kit it does not do this, I apologize for not trying that first. Next time I have an issue ill try in default kit but I do appreciate your advice.
You're right the spinning was caused by the controller It was camera smoothing set too high on the controller that was causing the spinning, I imported the default controller and camera over and now its not spinning, however its now getting stuck so when I tab out of the game and back in the character cant move its stuck in place and I noticed the portals stop animating it seems that the game crashes, I have to mess with it more but I think its not something with the kit since default fresh kit works fine. if I exit and go back it wont load it gets stuck at 90%.  This is so strange the game works perfectly, until you ALT+TAB out. Do you know what would be affected when you alt tab?

**Comment by Sour-J** [comment]
Issue resolved, turns out I had another error from a different asset that caused this, thanks
