### ISSUE TITLE
broken instances

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1504]
when u enter an instance, u cant leave it ( mmo mode) 
there is an error with key in a dictionairy being null or not found 
![image](https://user-images.githubusercontent.com/7702658/160464705-ee149991-802c-4943-a530-c91edc2955be.png)

**Comment by Callepo** [comment]
@insthync Tested in 1.72c5 and it works fine. so something in 1.73+ broke it.. i tried 1.73b + C both broken.

https://user-images.githubusercontent.com/7702658/160475109-744e4bde-7fbd-4a60-baf1-51d605f0c943.mp4

**Comment by insthync** [comment]
I will fix it.

**Comment by Callepo** [comment]
> I will fix it.

can i have the code fix for this? or added to repo to see changes when u fix? have live game atm with the issue

**Comment by insthync** [comment]
https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/3d79a8ac0d46b382668bf577406ffb77d87b5f66

**Comment by insthync** [comment]
Fixed in 1.74
