### ISSUE TITLE
00Init_MMO Start Map Spawn On Awake, spawn maps didn't work

### ISSUE THREAD

**Issue by wlof202** [suriyun-production/mmorpg-kit-docs#1506]
00Init_MMO Start Map Spawn On Awake, spawn maps didn't work
![1](https://user-images.githubusercontent.com/8343782/161237715-38aa4627-6a69-4309-bb4a-0dbc0eee5191.png)
![2](https://user-images.githubusercontent.com/8343782/161237770-01bd62f0-9563-4e2f-b013-8680688194b6.png)
![3](https://user-images.githubusercontent.com/8343782/161237910-c26e26cb-7b67-437d-8450-fa79768cf26d.png)

**Comment by insthync** [comment]
No error messages? , why the game instance is blank?

**Comment by wlof202** [comment]
i have no idea,but i run spawn server by commond , it work
