### ISSUE TITLE
SerializableCallback<IPlayerCharacterData, bool>  does not show up

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1509]
Hi guys,

I designed a prefab for a custom condition within dialogs, with following cs attached:
```

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MultiplayerARPG
{

  public class DialogItemRequired : MonoBehaviour
  {
    public bool CheckItem(IPlayerCharacterData characterData)
    {
      return true;  //characterData.HasOneInNonEquipItems(this ICharacterData data, int dataId)
    }
  }
}
```

Unfortunately the method is not selectable within the Dialog?!
Considering this: https://github.com/Siccity/SerializableCallback/issues/11
It should be possible.

Logs/Tests:

1.) This is something that works (CharacterHasInt is assignable to SthElse and visible in the editor, without the Dialog Context):
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Serialization;

namespace MultiplayerARPG
{

  public class DialogItemRequired : MonoBehaviour
  {

      //[NpcDialogConditionData]
      [System.Serializable]
      public class SthElse : SerializableCallback<int, bool> {}
      public SthElse conditionData;

      void Start()
      {
      }

      public bool CharacterHasItem(IPlayerCharacterData characterData)
      {
        return true;
      }

      public bool CharacterHasInt(int i)
      {
        return true;
      }

  }
}
```
2.) It seems, that any type except IPlayerCharacterData is showing up:
![20220406_221221](https://user-images.githubusercontent.com/18898408/162063185-8608be2c-e42a-4f02-8374-521700f0b49d.jpg)

**Comment by Pymann** [comment]
I conclude, that there is definitely bug in the core:
It seems, that inerfaces are not applicable to SerializeCallback<T> classes.

**Comment by insthync** [comment]
Hmm, seems like I have to changes `NpcDialogConditionData` to not inherit from SerializableCallback<IPlayerCharacterData, bool>, I will change it to inherit from SerializableCallback<string, bool> (the string is character ID, bool is result), then you can use BaseGameNetworkManager.GameInstance.ServerUserHandlers.TryGetPlayerCharacterById to get character.

**Comment by Pymann** [comment]
Maybe those posts can be considered, by finding nicest solution:
https://forum.unity.com/threads/favourite-way-to-serialize-interfaces.513874/

**Comment by Pymann** [comment]
By the way: 
I think its not out-of-the-box possible to implement warp, that need to be paid for...
Maybe need extra-dialog for confirmation...

Maybe you can have it somehow nice prepared for this use-case. Or tiny example with implementation of a custom condition for paid warp.

**Comment by Pymann** [comment]
> Hmm, seems like I have to changes `NpcDialogConditionData` to not inherit from SerializableCallback<IPlayerCharacterData, bool>, I will change it to inherit from SerializableCallback<string, bool> (the string is character ID, bool is result), then you can use BaseGameNetworkManager.GameInstance.ServerUserHandlers.TryGetPlayerCharacterById to get character.
> 
> Because Unity is acutally can't serialize interface too.

Changing SerializeCallback<string, bool> works

But I tried this: 
BaseGameNetworkManager.CurrentGameInstance.ServerUserHandlers.TryGetPlayerCharacterById(characterId, out playerCharacterEntity);

And its not possible, because the fields "CurrentGameInstance" are not accesible (protected).
I normally dont want to change the public/protected/private layout of those classes, as I dont know much about the efficiency.

The get method is not public, and if I do so, I get following error:
Assets/UnityMultiplayerARPG/Core/Scripts/Networking/BaseGameNetworkManager.cs(22,32): error CS0276: 'BaseGameNetworkManager.CurrentGameInstance': accessibility modifiers on accessors may only be used if the property or indexer has both a get and a set accessor

**Comment by insthync** [comment]
BaseGameNetworkManager.Singleton.

**Comment by Pymann** [comment]
I switched those public: ServerUserHandlers
What at least compiles =)

**Comment by Pymann** [comment]
Since 1.7.4 changes are implemented.
