### ISSUE TITLE
How to play game on html 5?

### ISSUE THREAD

**Issue by muzicvn** [suriyun-production/mmorpg-kit-docs#1512]
Hi, I was trying to Use Web Socket on both server instance and client instance, but I still cannot connect to the server on browser. I wonder if there is any other configurations?
Am I still using this arguments: D:\Demo03\WindowsBuild\Demo03.exe -startMapSpawnServer -spawnExePath "D:\Demo03\WindowsBuild\Demo03.exe" -startCentralServer -startDatabaseServer -machineAddress "192.168.0.115"?
Thank you.

![Untitled](https://user-images.githubusercontent.com/21272747/162599415-ccb1aefb-bb10-4f17-9f13-4f89bb9e5d90.jpg)
![Untitled2](https://user-images.githubusercontent.com/21272747/162599479-abaede42-2229-44a5-8fe9-5ffd6e76699f.jpg)
![Untitled3](https://user-images.githubusercontent.com/21272747/162599483-eaabe800-764c-4aa8-9a1a-509a09bae5aa.jpg)
![Untitled4](https://user-images.githubusercontent.com/21272747/162599514-5fd340d5-3978-476d-9acc-a83d6be72c6e.jpg)

**Comment by muzicvn** [comment]
I followed the guides of [insthync](https://github.com/insthync) on Youtube https://www.youtube.com/watch?v=m-tNN4oGwsc, and I finally solved the problem. Thank you very much.

**Comment by bedrygamed** [comment]
really ? 
how do you host it ?
if we using certain dedicated server
