### ISSUE TITLE
Open Character Controller Reverting

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1513]
No idea why but in runtime my open character controller changes settings. 
Do you know why its changing at runtime? 

Runtime: 
https://gyazo.com/c68d4607b66ee44b0b65325b4ed9bf6b

Editor:
https://gyazo.com/ad58c4c201cddba09a265f2ebb0ba1f7

**Comment by moepi2k** [comment]
There is a component on ur prefab to adjust colliders for stand crouch and so on

**Comment by Sour-J** [comment]
Thank you!
