### ISSUE TITLE
Guild Titles

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1515]
Guild titles doesnt use lang formats, wanted my guild name to show up as "<Guild Name>" instead of "Guild Name", so i made a custom lang and used it nothing happend, checked code realised even tho the lang is there on script and ui, but its never used.

![image](https://user-images.githubusercontent.com/7702658/162813726-e5421d80-025b-4add-a533-ddec4834237f.png)

added it by myself but would be nice if was default, dont wanna make custom script for something simple as this

**Comment by insthync** [comment]
Fixed in 1.74
