### ISSUE TITLE
Monster's attack animation don't work if they don't have weapon like Slime

### ISSUE THREAD

**Issue by muzicvn** [suriyun-production/mmorpg-kit-docs#1516]
Hi, I am new to this project, and I figure that monster's attack animation don't work if they don't have weapon like Slime. Do I need to adjust something? Thanks

**Comment by moepi2k** [comment]
Slime? Join community discord, we can help there.
If u mean weapon scriptable. Monster dont need it to work properly

**Comment by Sour-J** [comment]
Adjust the animation mask or remove it for slime maybe
