### ISSUE TITLE
I think Currency is bugged, beyond Fame. 

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1517]
In PlayerDataExtension 
Im trying to work with currency

int cashIndex = characterData.IndexOfCurrency(currency.dataId);
CharacterCurrency cash = characterData.Currencies[CashIndex];

cash += 1;
cash = 0;

characterData.Currencies[ExpIndex]  = cash;

etc

is this correct?
It seems like about the same thing as skills or attributes, but i cant seem to return a value.
Thanks for your time!

**Comment by Fallen-Entertainment** [comment]
public static bool IncreaseCash(this IPlayerCharacterData characterData, short targetLevel, short XpAward)
        {
            if (characterData.Currencies.Count <= 0)
            {
                CharacterCurrency.Create(Currency.MakeDataId("Cash"), 100);
                Debug.Log("Currencies are null attempting correction.");
            }

            foreach (CharacterCurrency Cash in characterData.Currencies)
            {
                if (Cash.GetCurrency().CashType == CashType.Uber)
                {
                    Cash.amount += 100;
                    Debug.Log("Cash:" + Cash.amount);
                    return true;
                }

                else
                {
                    CharacterCurrency.Create(Currency.MakeDataId("Cash"), 100);
                    return true;
                }
            }

            Debug.Log("Currency not found and could not be created.");
            return true;
        }

**Comment by Fallen-Entertainment** [comment]
Little test i wokred out using a simple tag i added to currency
![image](https://user-images.githubusercontent.com/71889605/163597682-20f00eed-64d2-43cb-89da-a522ddd4e9bc.png)
Even messed with creating the currency, I think somethings wrong here.
If im at fault i wanted to be corrected for sure.

**Comment by Fallen-Entertainment** [comment]
I worked through this and i got it down to one issue
I cant seem to get a solid reference to currency amount from PlayerCharacterDataExt

**Comment by Fallen-Entertainment** [comment]
This seems set up like Attributes no idea why i had to treat them a bit differently probably something i dont know, but ya please help me get a reference to the amount and ill go away lmao

**Comment by Fallen-Entertainment** [comment]
figured out the mystery please close this post ;)

**Comment by moepi2k** [comment]
You can close all ur own posts by self :-p

**Comment by Fallen-Entertainment** [comment]
good point lol
