### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#152]
https://youtu.be/BWjLt-h-yiA

**Comment by insthync** [comment]
Oh, thank you for bugs report, try impot this package to fix it
[MMORPG_KIT-FixCharacterSummonSerialize.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3903003/MMORPG_KIT-FixCharacterSummonSerialize.zip)

**Comment by insthync** [comment]
Fixed in 1.51.
