### ISSUE TITLE
CharacterStats from dev-extension are forgotten for random-item-stats

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1520]
Pymann:
--
Mh, about random stats, the developer extension is forgotten.
I wrote some character stats to the dev-extension, they can not be choosen for random item-stats.

Monty:
 — 
heute um 13:36 Uhr
yeah I think it only supports the defaults without extension

I will save some time, instead of making screenshots about it.

**Comment by Pymann** [comment]
I think its enough to add in Line 350 of ItemBonusCache.cs:
randomStats.InvokeInstanceDevExtMethods("RandomCharacterStats", random, randomBonus, randomStats, stats, appliedAmount);

and Implement such class (for sure you need the CharacterStat analogously):

﻿using UnityEngine;

namespace MultiplayerARPG
{
    public partial struct RandomCharacterStats
    {

      [Header("Demo Developer Extension")]
        
        [Header("RoundPercent")]
        public float min_round_percent;
        public float max_round_percent;
        [Range(0, 1f)]
        public float round_percent_ApplyRate;

        public float GetRandomedRoundPercent(System.Random random)
        {
            return random.RandomFloat(minExpRate, maxExpRate);
        }

        public bool ApplyRoundPercent(System.Random random)
        {
            return random.NextDouble() <= round_percent_ApplyRate;
        }


      [DevExtMethods("RandomCharacterStats")]
      public void DevExtDemo_RandomCharacterStats(System.Random random, ItemRandomBonus randomBonus, RandomCharacterStats randomStats, ref CharacterStats stats, ref int appliedAmount)
      {
            if (randomStats.ApplyRoundPercent(random))
            {
                stats.round_percent = randomStats.GetRandomedRoundPercent(random);
                appliedAmount++;
                if (randomBonus.maxRandomStatsAmount > 0 && appliedAmount >= randomBonus.maxRandomStatsAmount)
                    return;
            }
      }

    }

}

**Comment by Pymann** [comment]
Actually this is not working, custom characterStats show up properly within ItemUI.
But the random-amount is not applied.

**Comment by insthync** [comment]
I never invoke "RandomCharacterStats" so your dev ex method won't work.

**Comment by Pymann** [comment]
I wrote before:

"
I think its enough to add in Line 350 of ItemBonusCache.cs:
randomStats.InvokeInstanceDevExtMethods("RandomCharacterStats", random, randomBonus, randomStats, stats, appliedAmount);
"

But this invokation doesnt work...

**Comment by insthync** [comment]
Wait a new version, I've just uploaded it, it also have changes on character stats extension, to improve performance

**Comment by Pymann** [comment]
Will check that.

**Comment by Pymann** [comment]
Language.cs should be expandable too.
Otherwise you can barely format your new characterstats ;)

**Comment by Pymann** [comment]
How to deal with this ?

Am Mo., 18. Apr. 2022 um 10:22 Uhr schrieb Ittipon Teerapruettikulchai <
***@***.***>:

**Comment by Pymann** [comment]
Its interesting to see, that the PackageManager does not update the assets
properly.


Am Mo., 18. Apr. 2022 um 18:13 Uhr schrieb Nikolai Ehrhardt <
***@***.***>:

**Comment by Pymann** [comment]
Since 1.7.4 there is delegate for extending: 

```
if (GameExtensionInstance.onRandomCharacterStats != null)
    GameExtensionInstance.onRandomCharacterStats(random, randomBonus, randomStats, ref stats, ref appliedAmount);
```
