### ISSUE TITLE
WEBGL on localhost

### ISSUE THREAD

**Issue by bedrygamed** [suriyun-production/mmorpg-kit-docs#1521]
hello Suri

how to run webgl client with windows headless on localhost ?
I need actual scene and configuration you use for both server and the client

I'm facing situation why everytime I check the 'use websocket' option
on MMO Client Instance, Client refuse to login / connect on the Playmode.

I can't do webgl build if it's not even running on Playmode.

Please don't refer me to the Headless Linux & WebGL tutorial that you made on 2019,
coz I also failed to do such thing, maybe it's obsolete, none of the discord members 
acknowledge this stuff.

thx in advance
bedry

**Comment by muzicvn** [comment]
Just follow this video https://www.youtube.com/watch?v=m-tNN4oGwsc, that's all you need

**Comment by insthync** [comment]
https://medium.com/@ittipon-bay/mmorpg-kit-how-to-build-webgl-and-connect-to-localhost-server-6c9d9426fbf0
