### ISSUE TITLE
174

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1523]
first, thank u very much for this update. i see u spend alot of work in it. 

i updated my project. took me only 10 min :-P
now i test everything.
so far i noticed only a weird behaviour on projectiles.

this is default BowDamageEntity
https://gyazo.com/1fbdbd3d63d420f6b9bd571307d3d1db

and this is the projectileDamageEntity.cs
https://gyazo.com/d71c40278ec7f13b530f1c85fbeb5cd1

tested in MMO. as u can see. sometimes it wont register the hit.
in projectiledamageentity i add a debuglog for hit raycast 

https://gyazo.com/e9e6b3fd5c17df283a3ac2235f68eb1d
as u can see sometimes it hit the collider of the monster entitie
and sometimes the hitbox gameobject in child.

i dont know if its because of this and weird is why the default missiledamageentity also sometimes not hit.

it happen also in singleplayer but less frequent

p.s as u can see the default projectile sometimes fly through the entitie even when it hits it.
https://gyazo.com/e01bd9b23261a66077558b22c8254189

**Comment by insthync** [comment]
[MissileDamageEntity_2022-04-19.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/8507555/MissileDamageEntity_2022-04-19.zip)

Help me try this

**Comment by moepi2k** [comment]
ok seems the fixed the first problem that projectile goin through entitie when hit for MissileDamageEntity

https://gyazo.com/01fcfd36ef7f559869f070360b145dc5

but the ProjectileDamageEntity sitll not hit sometimes.

**Comment by moepi2k** [comment]
here a test with melee. also 50% of the hit not register
https://gyazo.com/57c79d1dc15d5c82b9d6f679876cfea0

**Comment by moepi2k** [comment]
so after long debug. i found the bug. its same like i already posted here for buffs which are not apply sometimes.
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1518

when u set triggerdurationrate to 0 like
https://gyazo.com/2c158d2d96b14b20fee40336359c0ff7

melee attack not work sometimes. 173 was fine with set it to 0.
