### ISSUE TITLE
MiniMapMaker throws exception

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1524]
Dont know, maybe its the unity version...
I click make and exception occurs. Does it harm anything?

![Bildschirmfoto von 2022-04-18 23-51-01](https://user-images.githubusercontent.com/18898408/163883665-0684c430-5415-4a13-a037-4e07e6fc24b5.png)

**Comment by insthync** [comment]
I will fix it, problem is just it have functions with the same name `Create`
