### ISSUE TITLE
assetbundle

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1525]
I have my application compiled only with this scene
<img width="626" alt="Captura de Pantalla 2022-04-19 a la(s) 13 02 10" src="https://user-images.githubusercontent.com/45702662/164056999-f8fbc56b-2bb8-41ca-90cf-a1a2eb927162.png">

The rest should be updated through assetbundle.
this loads the scenes, characters, etc.
However, when updating an item or anything, it is not reflected in the game.

I build these packages, I upload them to the server and they are downloaded correctly but the changes are not made
I have tried to change icons, name of items, but nothing happens. It's like ignoring the update

<img width="294" alt="Captura de Pantalla 2022-04-19 a la(s) 13 03 35" src="https://user-images.githubusercontent.com/45702662/164057256-120b1171-38f5-4a15-a9ae-ab09853d1422.png">

**Comment by SkyRain2020** [comment]
up for this

**Comment by insthync** [comment]
Ask unity, don't ask me.
