### ISSUE TITLE
[Suggestion] 2D Character customization/visual armor using sprite library and sprite resolver

### ISSUE THREAD

**Issue by MimiVRC** [suriyun-production/mmorpg-kit-docs#1526]
a 2D character customization/visual equipment system using the "new" sprite library/sprite resolver 2D components. it is a generic way to do 2D sprite customization. you use 1 animation to animate the sprite resolver. you create a "visual armor" or "customization" asset similar to a scriptable object. as seen here

https://cdn.discordapp.com/attachments/507151835388313600/966182341569552474/unknown.png
https://cdn.discordapp.com/attachments/507151835388313600/966182086715265104/unknown.png

the animation above is animating this https://cdn.discordapp.com/attachments/672178123579719740/966918544807833621/unknown.png

you have a gameobject per layer of customization as seen here https://cdn.discordapp.com/attachments/672178123579719740/966919072514179113/unknown.png

each of these has a sprite library and sprite resolver on it

the armor scriptable object would have a slot for its "sprite library" on it. when you equip it, you set that parts library asset to the one in the armor.

this creates a generic way to do armor or character customization visuals in 2D! I posted about it on the discord here, with videos https://discord.com/channels/460801727789137920/460802884397957120/966919522701422602

**Comment by insthync** [comment]
Thank you for your suggestion, this is interesting

**Comment by insthync** [comment]
Talks about it here https://github.com/suriyun-production/mmorpg-kit-docs/issues/2236
