### ISSUE TITLE
my mysql partial is not creating a table

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1527]
[DevExtMethods("Init")]
        public void Init_MCC()
        {
            // Create MCC Table
            Logging.Log("Mcc Init");
            Debug.Log("Mcc Init");
            CreateTable_MCC();
        }
        
        is this wrong?

**Comment by Fallen-Entertainment** [comment]
if i do this with a core mod it makes the table but obviously i dont wanna mod the core so perhaps im doing something wrong thanks for your time.

**Comment by Fallen-Entertainment** [comment]
this also seems to work fine for sqlite maybe there is something specific you do with mysql?

**Comment by insthync** [comment]
MySQLDatabase has no "Init" dev ext invoking, I have to add it

**Comment by insthync** [comment]
Fixed in 1.74d
