### ISSUE TITLE
NPC shop price UI currency issue

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#1528]
I think I found a bug, maybe user error but I was able to reproduce it in the default kit.
I cant seem to add a new currency to be displayed in the NPC shop the currency works just wont display the sell price in the NPC UI shop, I followed the documentation exactly and made sure the UI was correct also added to resource database. 

In the shop I have them all assigned for the item to be sold with Fame 1 and i left one item to be sold with regular fame in this picture so you can see that the second currency wont show up only the first currency you have works on the UI. I think its a UI issue since the currency works to buy just wont display the price at all.
https://gyazo.com/b5d4071f41553be75a1c4eedf9e91c09

I also noticed the UI is unchecked for it when you have the new currency assigned to the shop I tried to check the box to enable it but it still didnt show the price in the shop
https://gyazo.com/1bfd88621296f8dbb417f9a6d2127bed

Any advice on how to fix this is appreciated! Thank you for your time.

**Comment by BarzoStrike** [comment]
actually this is not an error.You can do it in 2 ways. 1. Editing "Text Amounts".2. if option is to pass "TextCashSellPrice" directly to "UITextAllAmounts"
![new1](https://user-images.githubusercontent.com/54517546/164894652-ab2c5af6-e87d-49a0-8178-650b02d624f1.png)

**Comment by Sour-J** [comment]
> actually this is not an error.You can do it in 2 ways. 1. Editing "Text Amounts".2. if option is to pass "TextCashSellPrice" directly to "UITextAllAmounts" ![new1](https://user-images.githubusercontent.com/54517546/164894652-ab2c5af6-e87d-49a0-8178-650b02d624f1.png)

Thanks, I did that but I didnt realize I could use the same UI for TextCashSellPrice I had two of those. Rather than sharing the same one. Thanks :)
