### ISSUE TITLE
1.74c has serialization changed or something?

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1529]
My character creation addon is not serializing in single player as it has for around 2 years without fail. its not working in sqlite, nor is it working in mysql. I have no errors and i have no clue whats going on but its killing me. Its making tables and everything but data is no longer making it.

Leads me to believe something has changed.

**Comment by insthync** [comment]
May I see your addon codes?

**Comment by Fallen-Entertainment** [comment]
I can add you to the repo if you like

**Comment by insthync** [comment]
Okay, invite me (my email: ittipon.bay@gmail.com)

**Comment by insthync** [comment]
But I am going to sleep, so I can check it later.

**Comment by Fallen-Entertainment** [comment]
invite sent, but knowing youll make time to look at it makes me feel a lot better so sleep well. Im nearly ready to put my game together and this was an upsetting set back. Thank you for your time bro.

**Comment by insthync** [comment]
Can't sleep, I will check it now

**Comment by Fallen-Entertainment** [comment]
Sorry :( but thank you

**Comment by insthync** [comment]
I've made a pull request, did you see it ?

**Comment by Fallen-Entertainment** [comment]
hold on sorry i was eating  let me check

**Comment by Fallen-Entertainment** [comment]
ya i just merged
thank you :)
Such a great relief

**Comment by Fallen-Entertainment** [comment]
serialization is indeed repaired thank you so much :)
