### ISSUE TITLE
Resistance bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#153]
Resistance in ui bugged
Wrong lang format set and ui resistance component was empty
i fixed for people in discord but would be good if main branch was fixed too

Lang was set to Simple Percentage
![ress](https://user-images.githubusercontent.com/7702658/69843458-e4561680-1267-11ea-97db-ea3b6a9db799.JPG)
![ress2](https://user-images.githubusercontent.com/7702658/69843482-fd5ec780-1267-11ea-97fa-c596037c318e.JPG)

**Comment by insthync** [comment]
Oh, thank you, I will fix it :)
