### ISSUE TITLE
GameDataBase changes do not affect anything

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1530]
So, I created a custom folder with my own scenes, and started to copy the data.
I created a new DataBase with new asset-id. But obviously it is not correctly loaded?
I assume there is an issue... but could be on my side too. I am searching several days now..
I asked in the chat, but hints came up.

**Comment by insthync** [comment]
Did you set game database to your game instance?

**Comment by insthync** [comment]
![Screenshot_1056](https://user-images.githubusercontent.com/2697550/164937366-1a5228b3-c5a3-4259-b235-affe7094288b.png)

**Comment by Pymann** [comment]
Yes I put this into respect.

**Comment by Pymann** [comment]
One question: Isnt it useless to attach all PlayerCharacter to the PlayerCharacterEntities, unless you want to exclude some?
Therefore better idea is to have a list of exlcusion.

**Comment by insthync** [comment]
Do you mean to add a exclude list in the player character entity ?

**Comment by Pymann** [comment]
Yes, currently you have list in GameDataBase for each PlayerCharacter (most people call it characterclass) and then you copy this list to each PlayerCharacterEntity (Male,Female,...). But its more accurate to have a list of exclusions (of that in GameDataBase).
Because this is the only use-case I could imagine to have this list.

**Comment by Pymann** [comment]
After Several deletions of characters and reloads the skills show up now.
