### ISSUE TITLE
[Suggestion] Assign Operators like <= or >= or == to skill-requirements

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1531]
Actually its not possible, to have something  like craftmanships, exg.: A blacksmith can craft swords easily, but not draw runes, like a runemaster.

But still both is skillable.

Actually I dont think there is any way to mutually exclude skills.
and if you had the feature: you could say this or that skill must be zero for skilling another one.
Same would be great for attributes. Its somehow problematic, that you have one pool for statpoints.
If you want to use that statpoint or those stats and another kind of statpoint for other stats.

Do you understand what I am requesting?

**Comment by insthync** [comment]
It can't because the skill requirement has to calculate by skill level.

**Comment by Pymann** [comment]
Yes exactly, actual if I setup a skill level rquirement, the character will be able to skill the new skill with this required, only if req-skill is that level or above. So we we have req-skill-lvl >= x. And I suggest to have more operators, than >=, exg.: == or <=.

**Comment by Fallen-Entertainment** [comment]
In the past ive done this with suris robust filter system making skills only appear when you meet the requirements

**Comment by Pymann** [comment]
Where can I find this: robust filter system ?

**Comment by Fallen-Entertainment** [comment]
if you want the skills to still appear on the list instead of hiding them you can do a lock screen set up ive done that to

**Comment by Fallen-Entertainment** [comment]
right on the skill list component you can easily extend generate list with an inherit and do whatever you want just add logic.

**Comment by Fallen-Entertainment** [comment]
i favor enum types for filters like suris type filter but he also shows an example for strings

**Comment by Fallen-Entertainment** [comment]
in my weapon skill system i even use attributes as skills and treat skills in the kit like spells, I mean so much is possible. GL

**Comment by Pymann** [comment]
Maybe such operator is less work ;)

**Comment by Fallen-Entertainment** [comment]
if i were making a crafting system i would want more then requirements. I would probably use a passive skill as the crafting value say blacksmithing and i would set up xp and level for developing black smithing by making items. This will make my game unique and more game specific which is exactly what suri really cant do because hes trying to please all of us not just one game. Its a hard position and he does his best, but in the end this mess as you call it is what makes your game unique. So i cant really admit that we will have to disagree there.

**Comment by Fallen-Entertainment** [comment]
However im not telling you its a bad idea or suggesting suri shouldnt do it, thats not my purpose my point is you can still get the job done and provide you with some information to help you achieve that. I wish you the best of luck.

**Comment by insthync** [comment]
This was requested many times, so I will add it, so you have to tell me about how it works.

**Comment by Pymann** [comment]
I will take such attribute, and provide the first one in form of an item, selectable in a talking quest.

**Comment by Fallen-Entertainment** [comment]
Ya it has been requested many times. Generally people want it so you cant learn skills until your at a specific skill level suri

**Comment by Fallen-Entertainment** [comment]
so like fire ball you cant learn until fire dart is level 10

**Comment by Pymann** [comment]
you need to exclude skills mutually. Means you cant skill this one, if you have that one.

**Comment by Pymann** [comment]
Normally its not much to do there, with skillsystem from meopi2k and the attribute solution you are well done.

But it would still be nice to have seperate pools for statpoints, exg.: statpoints a.) can be use for str/dex/int/vit and statpoints b can be used for blacksmith/cook/whatever

**Comment by Fallen-Entertainment** [comment]
I wonder if you can add alternate stat points with partials ive never tried lol

**Comment by Pymann** [comment]
Actually I dont get you ...

**Comment by Fallen-Entertainment** [comment]
I was wondering if it was possible to add more stat points in partials nothing confusing there. I just realized Ive never tried it.

**Comment by Fallen-Entertainment** [comment]
If it is possible maybe suri can show us a dev ext example of how to get it done, that would be pretty dope as a provided example in dev ext.

**Comment by Pymann** [comment]
If the day becomes longer, I would like to have much, like character-bound items =)

**Comment by Fallen-Entertainment** [comment]
easy to add if you look at the item drop bit you can check for a tag like Bound. A simple bool on the item data.

**Comment by Fallen-Entertainment** [comment]
but its a feature often asked for to so maybe suri will consider it.

**Comment by moepi2k** [comment]
In my skillsystem u have @Pymann i completly replaced kits system. Also for the crafting part which is nlt pushen on git atm. (Still custom stuff for my project) but it has exactly what u need. U can easely add skill req for diffrent professionals eg smithing blacksmithing. 

Like longsword req 25 blacksmithing skill, also i added recipes which u need to learn first to unlock it and show up in filter.

I dont require just using filters because its only clientside.
I add serverside checks also for req and filter.

Hit me up in discord so i can lead u.

**Comment by Pymann** [comment]
Actually you are not often in discord.

**Comment by Pymann** [comment]
Your skillsystem is just buggy. A soon as you drag it to GameInstance the Respawn-Dialog wont show up, if you die.
And it throws exception while running. Actually the Monsters become that strong ... that you cant beat one anymore. For unknown reason?!

**Comment by moepi2k** [comment]
That has nothing todo with my skillsystem. Its how u set it up.  Many ppls use it and i use it in my own project without any issues. Monsters are not affected by it

**Comment by Pymann** [comment]
And I dont collect any xp anymore... maybe we can design it more flexible ...

**Comment by Pymann** [comment]
I will close this. Things could be solved in another way.

**Comment by insthync** [comment]
What is stat point pools ?

**Comment by Fallen-Entertainment** [comment]
Moe's  skill system works just fine a number of people are using it with
zero issues including a game near release.

**Comment by Fallen-Entertainment** [comment]
Pymann I really don't understand why your here bugging insthync. All you basically do is go on about clean code and complain about his code, while you present yourself as code guru wise with the code... You would think with all that raw power you would just be modifying the kit to your liking or at least have a better understanding of how it works. Every time you have an issue its never your fault its always someone or something else's. I watch you struggle with basic things and thats fine, nothing wrong with learning and I totally support that, but your attitude and aptitude don't seem to line up. You should turn it down a notch until you at least know how to use the kit.  Say whatever you want about Moe's skill system, but he actually wrote one and put himself out there, and it works well for everyone i know who owns it. Ill tell you this, Moe is a decent coder and insthync is amazing, you have zero credit so far and many complaints.

**Comment by Callepo** [comment]
> 

lol i  think its best you just say u dont understand how it works and dont have enough code knowledge to even look into it.. 
none of the stuff u mentioned above, are the case. you prolly just did some weird stuff, any error u get also should be easily to read from the console. and like neomis said, it doesnt alter any monster stats.. only interaction it has is when monsters take dmg...
i use it in 2 games, even made adjustments to it, also changed it to be fully exp based per skill mastery...

**Comment by Pymann** [comment]
You are somehow attacking.
You somehow try to forbid instync to talk to me ?! I think he will know best, if he is annoyed or not.
I closed this.
I explained stat pools above. Currently there is only 1 stat pool for all attribtues.
But If I would like to have one for that set of attributes and one for other set of attributes. I need to start coding.
What, believe me, is no problem. Iam just doing suggestions.

**Comment by Fallen-Entertainment** [comment]
You can talk to whoever you want but how you talk to them has consequences I would urge you to remember that. Good luck with your project I wish you the best.

**Comment by insthync** [comment]
Regarding to new stat points, I have an idea to use custom currency as stat points.

**Comment by Pymann** [comment]
Mh sounds good. Will you contribute it?

**Comment by insthync** [comment]
It already has a custom currency

**Comment by Fallen-Entertainment** [comment]
Currency is pretty awsome its an int so it can have a very high number and its easy to use with events. Also the way currency was added it wouldnt be to hard to add your own version of it if you needed to.  Huge fan.

**Comment by Pymann** [comment]
Well, I think nearly every script would have to be rewritten ...

**Comment by Callepo** [comment]
> Well, I think nearly every script would have to be rewritten ...

well, thank god we dont pay u to think

**Comment by Pymann** [comment]
Yes, thank god, that i dont have to think for everybody.
