### ISSUE TITLE
Webgl windowed attacking faster than normal window. 

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1534]
We had this problem, where if you are attacking a monster at normal window the attack speed is normal but if you keep attacking and then windowed the attacks gets like 2x. This on webgl and 2d.

**Comment by MosesGomez** [comment]
https://www.youtube.com/watch?v=xqALDZUfpWo&feature=youtu.be

**Comment by insthync** [comment]
Which MMORPG KIT version?, Is it the newest one?

I asked because I've add a speed hack detection some time ago.

**Comment by MosesGomez** [comment]
> Which MMORPG KIT version?, Is it the newest one?
> 
> I asked because I've add a speed hack detection some time ago.

I think its 1.73b

**Comment by MosesGomez** [comment]
Any news?

**Comment by insthync** [comment]
I should try your project, may try by AnyDesk

**Comment by MosesGomez** [comment]
> I should try your project, may try by AnyDesk

Lets schedule it :D

**Comment by MosesGomez** [comment]
> I should try your project, may try by AnyDesk

Please mail me so we can schedule the date :D

**Comment by insthync** [comment]
Maybe in next hour?

**Comment by MosesGomez** [comment]
> Maybe in next hour?

I can

**Comment by insthync** [comment]
How about now ?

**Comment by MosesGomez** [comment]
> How about now ?

I cant :( But if we can do it at this same hr tomorrow Ill be ready man 

Sorry.

**Comment by insthync** [comment]
Okay

**Comment by MosesGomez** [comment]
> Okay

Im available, let me know please

**Comment by insthync** [comment]
Okay, send your AnyDesk info to my email: ittipon.bay@gmail.com

**Comment by MosesGomez** [comment]
> Okay, send your AnyDesk info to my email: [ittipon.bay@gmail.com](mailto:ittipon.bay@gmail.com)

Sended

**Comment by insthync** [comment]
As I try, when you focus on another browser tab, let's say when you switch from tab A to tab B, the tab A character's animation will be played slower (not faster), so that's why it can't detect speed hacking.

**Comment by MosesGomez** [comment]
> As I try, when you focus on another browser tab, let's say when you switch from tab A to tab B, the tab A character's animation will be played slower (not faster), so that's why it can't detect speed hacking.

So its just visual thing?

**Comment by insthync** [comment]
Maybe Unity issues

**Comment by insthync** [comment]
https://docs.unity3d.com/Manual/webgl-performance.html , read **WebGL content in background tabs**, it is browser issues, will slower than Unity can run, it will update only 1 time per second.
