### ISSUE TITLE
Party Exp Share Distance Bug

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#1535]
Hi bro,

Thanks for implementing the party exp share distance, it is appreciated, but there is a small issue...

When a party member is far the experience gained is not shared between then which is correct and expected. But the issue is the exp gained is still divided between the members even when the exp is not being shared. which is a bug.

Bug:
Monster A gives 10 exp. 
Player A and Player B in a party is close enough to share exp they each get 5 exp.
But when Player A and Player B is far away and is not sharing exp, if Player A kills a monster, Player A still gets 5 exp even if its not shared.

Expected:
Player A should get the full 10 exp. 

Thank you.

**Comment by insthync** [comment]
Fixed in 1.74e
