### ISSUE TITLE
Override animations for off-hand items (shield / torch etc)

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1537]
I've seen lots of folks (including myself) ask for off-hand or shield animation options. However I think the most universal system that will allow everyone to customise their needs is to have an "animation override list" through weapon types.

For example, setup another weapon type that you want to override with (such as a torch) with the animations you want, and in the animator character model when its setting the animations, do a check to see whats equipped and if its inside an override list switch to that animation set instead of whats normally expected.  

Eg, if a character equips a shield rather than using 1h sword animations, override it to use animations set in the Override_Shield 'weapon type', or if the player equips a torch, then it overrides the current 1h sword animation and uses animations of the torch weapon type.

VIDEO: https://i.imgur.com/3AKYysK.mp4
(Credit to Monty for the explanation, videos and screenshots - they're not mine).

Just have a list of overrides extended onto the animator character model.

![image](https://user-images.githubusercontent.com/48354382/165249044-eba3a4be-468a-4af5-bf61-8e504805e430.png)

In that little video, normally the kit would just set the character to use the 1h sword animation set for all those shown, but when the character equips the shield, it overrides with the animation setup for shield using the weapon type "shield_override", and then changes again when he equips the torch, to the weapon type "torch_override".

![image](https://user-images.githubusercontent.com/48354382/165249098-f2e1572f-29ff-4fad-b0dd-7dae57c5384a.png)

This means people are free to set their own override animations for off-hand based on the weapon type. For example holding a torch above the head etc, and it won't be limited to just a single "off-hand" animation. With the override system, it can be whatever we setup making the best use of modularity and appealing to a much wider userbase (rather than being niche).

**Comment by LordPhrozen** [comment]
*THIS*

**Comment by insthync** [comment]
Okay, I will implement it
