### ISSUE TITLE
Game Spawn Area random level issue

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#1538]
Hello bro,

Small issue. [Random.Range](https://docs.unity3d.com/ScriptReference/Random.Range.html) has 2 overloads float and int. 

#Float
```
public static float Range(float minInclusive, float maxInclusive);
```

#Int
```
public static int Range(int minInclusive, int maxExclusive);
```

GameSpawnArea is using **int**
```
        public virtual void SpawnAll()
        {
            SpawnByAmount(prefab, (short)Random.Range(minLevel, maxLevel + 1), amount);
            foreach (SpawnPrefabData<T> spawningPrefab in SpawningPrefabs)
            {
                SpawnByAmount(spawningPrefab.prefab, spawningPrefab.level, spawningPrefab.amount);
            }
        }
```

So it means max level is exclusive. On `MonsterSpawnerArea` if you set `minLevel = 1` and `maxLevel = 2`. It will only spawn level 1 monsters. I think it is better if you set `minLevel=1 maxLevel=2` that it should spawn random between level 1 and 2.

Also, maybe random level should be generated inside the `SpawnByAmount` loop. So level will be random for each spawned monster?

Thank you.

**Comment by insthync** [comment]
Fixed in 1.75
