### ISSUE TITLE
Dead party members still gain experience 

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#1539]
Hello bro,

When using limit distance to gain experience, dead party members within the range still receive exp. I think they should not. And exp should not be divided to dead members. 

1.74e

Thank you.

**Comment by juniormagalhaes** [comment]
well there are some situations in which the dead player must gain xp, like in a dungeon, when they are about to defeat the boss and a player dies and the boss is defeated it's not fair he doesn't gain xp because he died a little before the boss dies

**Comment by juniormagalhaes** [comment]
well there are some situations in which the dead player must gain xp, like in a dungeon, when they are about to defeat the boss and a player dies and the boss is defeated it's not fair he doesn't gain xp because he died a little before the boss dies

**Comment by majimboo** [comment]
> well there are some situations in which the dead player must gain xp, like in a dungeon, when they are about to defeat the boss and a player dies and the boss is defeated it's not fair he doesn't gain xp because he died a little before the boss dies

In this case the player gains exp even when he has been dead for a long time, and didn’t deal any damage to the monsters. in my test the player has been dead from level 3 and while dead gained level up to 7.

**Comment by majimboo** [comment]
> > > well there are some situations in which the dead player must gain xp, like in a dungeon, when they are about to defeat the boss and a player dies and the boss is defeated it's not fair he doesn't gain xp because he died a little before the boss dies
> > 
> > 
> > In this case the player gains exp even when he has been dead for a long time, and didn’t deal any damage to the monsters. in my test the player has been dead from level 3 and while dead gained level up to 7.
> 
> I think it would be more functional, to put an automatic respawn time, to avoid this glith, but without breaking the mechanics in other areas of the game.

I personally think it would just complicate the logic. A DontReceiveExpIfDead boolean would suffice.

**Comment by tqfa** [comment]
After the death of the character can also receive experience of the game, really not played, received items, or acceptable

**Comment by tqfa** [comment]
If it won't be changed in the future, just change it yourself, it's not a big deal

**Comment by insthync** [comment]
Fixed in 1.75, character won't receive EXP while dead, if you still want it able to receive EXP, delete codes in `BaseMonsterCharacterEntity` line `506` (` && !nearbyPartyMember.IsDead()`)
