### ISSUE TITLE
Monster HP regeneration 

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#154]
Health regeneration from "SimpleGameplayRule" now affects monsters. This was not the case before. Is this a bug? 
If not a bug, can it be done separately for monsters?
![image](https://user-images.githubusercontent.com/47291794/69871410-c7e7c780-12c3-11ea-8f94-7796e53b79a8.png)

**Comment by Callepo** [comment]
always effected monsters
even SimpleAreaheal skill from the player effects monsters
Cuase monster is also a character

**Comment by DimasjkTV** [comment]
In previous versions, I did not notice that the monsters regained their health.

**Comment by DimasjkTV** [comment]
I just installed 1.48 and there the monsters do not restore their health. The whole balance of my game I built on this.

**Comment by Callepo** [comment]
maybe in 1.48 its bugged XD or was changed
i saw monster regen since 1.46.. they kept getting +1 hp every few seconds 

but u can change it in simplegameplayrule

**Comment by DimasjkTV** [comment]
There we can change the general meaning. I want that my character restore a percentage of health. I don’t want that monsters restore their health. Therefore, separation is necessary in the rules.

**Comment by Callepo** [comment]
character = already regen % of health.. and  u wanna change a "Rule".. which is why i told u SimpleGameplay "Rule"

**Comment by DimasjkTV** [comment]
No. If we set the value to 0, then the character will not restore health. Reread my first post. You probably do not understand.

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/69877988-ad6a1a00-12d4-11ea-9a7f-1497ed376367.png)
earlier, the restoration of health from the rules did not affect monsters, but only on the character. Now the rules apply to monsters too.

**Comment by DimasjkTV** [comment]
I want my character to restore 2.5% health per second, and monsters 0. But in the current situation, monsters also restore 2.5% health. I wrote about this at the very beginning.

**Comment by Callepo** [comment]
![hp](https://user-images.githubusercontent.com/7702658/69878078-2ad95e80-12c4-11ea-8eb6-b261d4c124e5.JPG)
This is HP Regen per second... Which clearly say ! MAxHP * RecoveryRate... which is character hp % regen...

If u dont want monsters to heal.. add a IF() function to check if character = Player character or Monster character.. and if player do heal .. if monster return 0.. 
SO monsters do not heal ..

believe me .. i understand this kit perfectly and the codes

**Comment by Callepo** [comment]
but gl

**Comment by DimasjkTV** [comment]
> but gl

you just showed me something that is not relevant to my question. I'd rather wait for a response from the developer.

**Comment by Fallen01** [comment]
simple bool and an if statement. Your all set. I mean if you wait for Suri maybe he will do it for you, but Dont be afraid to give it a try! :) This is an easy one so a great chance for you to learn a bit. What you have done without code is amazing, but I cant help but think how much more amazing your project could be if you learned to code just a little bit! GL my friend.

**Comment by Fallen01** [comment]
Ohh and in case you didnt understand Callepo showed you where recovery is done, which is completely relevant to your question.  you need to confirm the character is a player. So so you would need to confirm the character is a player and if he is then heal. You could change the reference from character to player maybe or flag the player with a bool value like isPlayer = true. Theirs probably other ways to do it to, but these would be my first couple of attempts. It doesnt hurt to try while you wait for suri to respond. I hope that helps a little.

**Comment by DimasjkTV** [comment]
Guys, everything is simple. I need to find out if this is a bug. In previous versions, there was no health restoration for monsters. And here you started to write it is not clear what.

**Comment by Fallen01** [comment]
Well in most games monsters do heal, I dont think this is a bug. I think this is a fix, but what i was trying to impress upon you is that your not limited by such things and they require simple edits. At the end of the day your depending on a demo to produce your game. I was simply pointing out its completely ok to turn the demo into your game. Best of luck hope it gets resolved.

**Comment by insthync** [comment]
It's not bug, I intently makes an monster hp/mp recoverable.

**Comment by insthync** [comment]
For now it can't set this seperately

**Comment by DimasjkTV** [comment]
> For now it can't set this seperately

Thx
