### ISSUE TITLE
Crafting UI queueing items even when requirements are not met

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#1543]
Hello,

Crafting UI has a bug, where when you have 1 item in queue, and then you try to queue other formulas even when the requirements are not met, it gets queued.

See video:
[link to view](https://user-images.githubusercontent.com/6186420/165905353-fe5e527d-8a25-4061-a5e1-e8b848ed3481.mp4)

Only the first formula has complete requirements, the other 3 aren't supposed to be queueable.

**Comment by moepi2k** [comment]
Its just in queue but it wont craft the items

**Comment by insthync** [comment]
Fixed in 1.75, it won't queue a new entry while it has not enough materials, but it still not fully working for all cases, such as before enqueue it has enough materials but later items are consumed then the queued items won't be removed, it will be removed later when it starting to craft the item.
