### ISSUE TITLE
[Bug]HitTarget FoV since 174

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1544]
there is an issue since 174 when target entity with FoV

https://gyazo.com/e9c6a3e64fa22078b3ffaa9b521ef8e8

i use AimAtCursor controller.

like u can see in video. aslong as Entity is in FoV range and not directly selected, attack is bugged.
it happens since 174.

this happens random. sometime it works sometimes not. i dont  get it why

edit: found out that bug happen only when this is enabled -> https://gyazo.com/9f3d4ca6725d723a71657607697a45f6

like said before. it worked with that option in < 1.74

**Comment by moepi2k** [comment]
btw here the error when it start spam attacking when in FoV

https://gyazo.com/d22d7c3c2595873948a36a41e5048910

**Comment by insthync** [comment]
Fixed in 1.75
