### ISSUE TITLE
Playercontroller as well as TopDownController Position/Rotation Bug

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#1546]
Hello, i used the TopDownController. But when moving the mouse very near the Player and/or clicking to Positions near him, the Rotation gets out of hand and a little bit later the position also. I made a video of it and hope you get what i mean:

https://youtu.be/noUplgma0HE

**Comment by xnitro1** [comment]
i tried the normal character controller aswell and could reproduce the bug there aswell when harvesing and trying to move at the same time (with WASD movement) :
https://youtu.be/ASm4KvjscXI

**Comment by insthync** [comment]
How is your animator?, is it the child of player character entity?

**Comment by xnitro1** [comment]
![animator1](https://user-images.githubusercontent.com/93816817/166108209-6cfb27ec-8019-4d79-8102-3197bf92bad3.PNG)
![animator2](https://user-images.githubusercontent.com/93816817/166108211-70273f83-4cea-4530-b514-71f4c66d9464.PNG)
i have my new player unter the "Male_CC" where i disabled the animator. on my SM_Char...which is under "Male_CC" is the new animator. i hope my screenshots are good enough

**Comment by insthync** [comment]
It is a root motion issue, but it is different to #1545 , this problem is the transform (named `SM_Chr_`) is moving when playing move animation. I don't know current Unity version has a way to fix it, I found that Unity's new TPS sample has setup animator as a child, I will check it later.

**Comment by insthync** [comment]
Don't use root motion animator if it is a child of another game object, because when use root motion it can move/rotate itself, this is cause of problems.
