### ISSUE TITLE
[Issue] Buff target enemy

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1547]
I tried to create a skill to buff enemies with normal skill or area buff skill.
I didnt succeed yet.

I tried following and within game it will say "NO TARGET" in red, although I selected enemy.

![Bildschirmfoto von 2022-05-01 20-00-10](https://user-images.githubusercontent.com/18898408/166158448-65db9e8c-9b03-462d-aca7-8d8a13f29a07.png)

**Comment by BarzoStrike** [comment]
actually there is a typo
cannot buff enemy = life buff enemy
if you enable it it will work

**Comment by Pymann** [comment]
haha lol, thx, will try it.

**Comment by Pymann** [comment]
Iam missing same for area-buff-skill?

**Comment by insthync** [comment]
For area buff, set `applyBuffToEveryone` to `true`

**Comment by insthync** [comment]
You can set it in `AreaBuffEntity`

**Comment by insthync** [comment]
In next version I will move it to `SimpleAreaBuffSkill` game data

**Comment by insthync** [comment]
Applied in 1.75

**Comment by Pymann** [comment]
There is one more question... why cant I add normal dmg to passive skill?

**Comment by insthync** [comment]
Don't know, not sure why you ask 'why', maybe you just don't know how to do it, you have to set increase damage in buff setting

**Comment by Pymann** [comment]
For the normal dmg, there is a damage-element? I know how to add those damage elements, but not how to add normal-dmg ...

**Comment by insthync** [comment]
Don't set damage element, leave it none

**Comment by Pymann** [comment]
Its confusing, because Unity marks it red, but works ...
