### ISSUE TITLE
NPC vender issue with currency

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1548]
Ive added currency everywhere gamedata and to the character component. Still my Currency doesnt show when set on a vender NPC. Am I missing a spot? Because the normal Fame Vender works fine and I basically duplicated his data. Which I also placed on my new vender. I figure im missing something.

![image](https://user-images.githubusercontent.com/71889605/166187251-eb59097d-7f54-4b68-b226-04d4a5ef5211.png)

**Comment by RunOrDi3** [comment]
you are missing something for sure if it works fine with fame :)

**Comment by BarzoStrike** [comment]
You need to edit the UI. Add a new one will appear
![Adsız](https://user-images.githubusercontent.com/54517546/166216247-db020be1-81c0-4192-a859-f7a55b03520f.png)

**Comment by Fallen-Entertainment** [comment]
I have in fact added added them to the UI or i could not have added currency to character which is a pair requiring the UI entry and the Currency data much like attribute.
