### ISSUE TITLE
EquipmentSet number of parts bug

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#1549]
Hello,

When using equipment set and adding bonus, say for example, 6 parts will get a bonus. The UI shows (6) bonus, yet it only turns to the enabled color, or it only activates the bonus when my number of part is 7. It should be 6 parts. Any number of parts you set, it only activates when there is +1 of that number you set. UI display also confusing since it shows 6 parts, but activates on +1 only.

**Comment by insthync** [comment]
![Screenshot_1066](https://user-images.githubusercontent.com/2697550/166338697-ddff8d20-c8ab-427d-b44a-1014681d5d2a.png)

It should be like this, right ?

**Comment by insthync** [comment]
Fixed in 1.75
