### ISSUE TITLE
[Issue] Skills from equipment show up, althoug they have different category

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1550]
Skills from equipment show up, althoug they have different category.
I created filtered Skill scrolledView, but skills from equipment show up, that have other Category...

**Comment by insthync** [comment]
Did you set the category in skill data? not in the item data.

**Comment by Pymann** [comment]
Mh, I never touched those demo skills, therefore they have no category. but show up in the UICharacterSkills
My own skills show up correctly, they have category.

![Bildschirmfoto von 2022-05-03 20-50-20](https://user-images.githubusercontent.com/18898408/166522549-071115af-d025-43c6-beed-ff4f9a1c13f5.png)

**Comment by insthync** [comment]
Yep, because it has no category set, so it will be shown.

**Comment by insthync** [comment]
So it is not an issues

**Comment by insthync** [comment]
But what you told me is make sense, I might change it.
