### ISSUE TITLE
Skill UI bug -- ver 1.75

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1551]
![1](https://user-images.githubusercontent.com/54517546/166832835-001aea95-b4fb-4cf7-8b29-b84c87a27a88.png)
When I click on some of the skills, it gives an error and some does not. I tried it in an empty project, there is the same problem, am I doing something missing?
For example Bash ability is fine but Endure gives an error

**Comment by BarzoStrike** [comment]
I understood how the problem occurred, I think it will help you. If the skill level is 0, it gives an error, but when you give 1 level, it works without any problems.

**Comment by insthync** [comment]
Fixed in 1.75b
