### ISSUE TITLE
Character Loading glitch on login

### ISSUE THREAD

**Issue by ApolloGM** [suriyun-production/mmorpg-kit-docs#1552]
I have had this happen quite a few times on random logins. Can anyone advise why this happens and how to fix it?
This is on default character with no changes made to the model. Here is a pic.
![MMORPGKit-CharacterLoadingBug](https://user-images.githubusercontent.com/95550185/166985721-7a127f56-1c92-4088-b68d-220c8821fd39.png)

**Comment by insthync** [comment]
Which package version?, this was reported and fixed, it cause of problem is `CharacterPitchIK` component.

**Comment by ApolloGM** [comment]
ah ok, I havent updated to the unity 2021 version yet (likely not updating for a while due to significant code merge requirement)
could you let me know what files were impacted for this change? I can just import those, or  replicate the fix on my end.
Is it the CharacterPitchIK.cs and CharacterPitchIKManager.cs?

**Comment by ApolloGM** [comment]
after importing the fix, it is no longer happening! Thanks
