### ISSUE TITLE
[Bug]ProjectileDamageEntity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1553]
hi, since 174 there is an issue with ProjectileDamageEntity. sometimes it not hit like u can see in this video
https://gyazo.com/9bf82ec6492973c9dcd68f8396a014d4

here are the settings
https://gyazo.com/e98c0775a16953ae7c67d8bb05dfbb5c

i assume its because of _hitbox and collider of parent object.
it collide with it instead of hitbox. it worked well in all versions < 1.74
https://gyazo.com/43f707d8b0ef5b55b4b7091cd1f6918e

this test was in 175b

**Comment by insthync** [comment]
Fixed in 1.75c
