### ISSUE TITLE
[Bug]received EXP from monster

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1554]
i noticed a weird behaviour in my project. (not tested in fresh project right now) but i changed nothing coreside so i assume its in default too.

https://gyazo.com/94c5c2b9b64f971a25b05b80ad136d85

i set received xp to 8 in monster.
it works aslong as player not reach max level.
but when player reach max level (in this case lvl 10) player get alot  of xp. 7k+

i dont know from where the number comes from.

**Comment by insthync** [comment]
I can't reproduce it yet.

**Comment by moepi2k** [comment]
i check again. i noticed it only in singleplayer, but seems that mmo seems fine. i wil test today and let u know
