### ISSUE TITLE
Visual issue when enter Chat

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1555]
when enter chat. the ui stuff like recover stuff is paused. and after exit chat it spams in like u can see in video

https://gyazo.com/100cf8f8cc4f7c52bf3a63a14a14ead2

**Comment by moepi2k** [comment]
Since i use it 😆 always forgot to report it

**Comment by RunOrDi3** [comment]
😂😂😂😂

**Comment by BJPickles** [comment]
Can confirm this has been around a long while. 

https://i.imgur.com/tloF9Lk.mp4

**Comment by insthync** [comment]
Fixed in 1.75d
