### ISSUE TITLE
MapSpawnNetworkManager bug/limitation when built with IL2CPP

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#1557]
When using IL2CPP  `Process.Start(startProcessInfo)` fails. But when I use MONO it works. Both are the exact same project with the only difference is that they are built with different scripting backend.

After some research I found this on the unity forums.
https://forum.unity.com/threads/solved-il2cpp-and-process-start.533988/

There is no official support but there are workarounds that might work. Maybe we can also add support for IL2CPP on MapSpawnNetworkManager? 

Thank you!

**Comment by insthync** [comment]
Next month I will continue the remake of some services, to make them run outside Unity  (this)[https://github.com/insthync/mmorpg-kit-nodejs-db] is part of them, it will have a new login service and new map-spawn service.

**Comment by Reinhartdelille** [comment]
Hi, First I don't know if we really want IL2CPP support for the backend? What would the benefit be?

For the remake of services, do you have somewhere a roadmap? I have some ideas that would be very good in scaling MMOKit, mainly in creating a server directory services (when a mapspawn or other services comes online, it registers itself at a central service, and then you can read that out in the UI). Now the UI only has the prefixed servers in their.

Happy to contribute on this one as you know I am also looking for this kind of solution :)

**Comment by insthync** [comment]
Now it has this: https://github.com/insthync/UnityMultiplayerARPG_MMO.NET
