### ISSUE TITLE
BUG Quests

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#156]
If our summoned creature killed the quest target, then the quest does not count.

**Comment by insthync** [comment]
Okay, I will fix it :P

**Comment by DimasjkTV** [comment]
> Okay, I will fix it :P

Also, if we kill a monster with skill, then the quest does not count. Quests are count only if we kill monsters with a normal attack.

**Comment by insthync** [comment]
> > Okay, I will fix it :P
> 
> Also, if we kill a monster with our skill, then the quest does not count. Quests are count only if we kill monsters with a normal attack.

Which kind of skill?, As I try when I kill enemy with skill it's counting.

**Comment by DimasjkTV** [comment]
> > > Okay, I will fix it :P
> > 
> > 
> > Also, if we kill a monster with our skill, then the quest does not count. Quests are count only if we kill monsters with a normal attack.
> 
> Which kind of skill?, As I try when I kill enemy with skill it's counting.

Skills that have periodic damage debuffs. If the target dies of periodic damage, the quest does not count

**Comment by insthync** [comment]
Ahhh, I see

**Comment by insthync** [comment]
Fixed in 1.51, try it, if it's still not working well, then reopen this issues again.
