### ISSUE TITLE
Skill UI bug and Request

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1562]
1- There is a problem with UISkillDialog. The requirements don't look right.
For example the level seems insufficient but actually my level is sufficient and I can do it.

2-I think you should avoid using the same type of skills.
For example, if a speed skill was used and a similar skill was used on top of it, the first used skill should be deleted.

![1](https://user-images.githubusercontent.com/54517546/167529932-c444c1f5-322c-46e7-9a95-5e7dce83e924.png)
![2](https://user-images.githubusercontent.com/54517546/167530274-660afe37-a669-40ff-b488-fe48d31999d5.png)

**Comment by moepi2k** [comment]
Your setup for req is wrong. Its how u design it. For lvl 1 u need char level 5 but for level 2 u need char level 0?

**Comment by BarzoStrike** [comment]
Version 1.75c
you can try to see what's wrong. Same problem with empty project. Requirements are not working properly but it just seems like that. the requirements show 1 level up but you can level up
maybe i'm doing something wrong

**Comment by moepi2k** [comment]
ahh sorry, then i understand it wrong. if u could level up even without met the req then its a bug :)

**Comment by insthync** [comment]
I will fix it.
