### ISSUE TITLE
Bug --Skill Reset---

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1565]
If you give a skill more than 1 skill point, it will not give it back. For example, if you gave the skill 5 points for each level and 10 level is the max level, you gave 50 points. When I use "skill reset" it only gives 10 points back. In other words, it calculates 1 point for each level, regardless of how many points you give.

**Comment by insthync** [comment]
I will fix it

**Comment by insthync** [comment]
Fixed in 1.75d
