### ISSUE TITLE
[PAID REQUEST]: Paid Membership

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1567]
Hi Suri,
Whilst we have in-app purchasing, we don't have the ability to allow players to pay monthly and reward them. Monetisation is an important factor of MMOs and I believe it would be a great value to offer benefits to players who pay monthly or annually for membership.

Premium Membership should be added to allow us to monetise our games further and open up new possibilities in the kit. I've added ideas that are modular, giving the most range for everyone using the kit.

**1. INTEGRATED PAYMENT METHOD**
-
- Unity IAP utilising [Subscription Product support](https://docs.unity3d.com/Manual/UnityIAPSubscriptionProducts.html) makes the most sense as it's already partially added.

---

**2. AUTOMATIC ITEM, CURRENCY AND BENEFITS FOR PREMIUM PLAYERS** 
- 
**EXP MULTIPLIER**: 
- Ability to set different exp per player / exp multiplier (i.e x2 exp for premium members, but NOT regular players) **and importnatly** to **_remove_** the multiplier if a player stops/cancels their membership at the end of the billing cycle. 

**MAILBOX ITEM REWARD**: 
- Automatically mail items to premium player (through mailbox) on a set date. I.e the last day of every month. This is useful if developers are rewarding physical items like "Exclusive armour" or "Crafting Items" to players on a monthly basis.

**MAILBOX CURRENCY REWARD**: 
- Automatically award defined currency on a set date. I.e give 1000 gold, or 500 fame on the start of every month to the player through the mailbox. Utilising the mailbox means players have to claim it manually.

**SKILL REWARD**:
- Ability to reward specific skills/abilities to players who are premium, and the option to remove them if they cancel their membership.

---

**3. PREMIUM MEMBERSHIP PERMISSIONS**
-
The option to check if a player is Premium and allow or deny the action. "Can only use if Premium" bool.

**QUESTS**:
- Can only start quest if a Premium player.

**EQUIPPING ARMOUR ITEM (INDIVIDUAL)**:
- Can only equip armour item if a Premium player. 
- For example a "Premium Cape" item.

**EQUIPPING ARMOUR TYPE**:
- Can only equip armour type if a Premium player. 
- For example armour type "Wings" only available to Premium players.

**EQUIPPING WEAPON ITEM (INDIVIDUAL)**:
- Can only equip weapon item if a Premium player.
- For example "Premium 1H sword" item.

**EQUIPPING WEAPON TYPE**:
- Can only equip weapon type if a Premium player. 
- For example weapon type "GODSWORD" only available to Premium players.

**SKILL**:
- Can only use skill if a Premium player.

**LEVEL UP**:
- Option to stop gaining EXP at defined level, unless a premium player.
- For example: Stop gaining EXP at level 30. Premium players can reach level 60.
- Would be set in GameInstance.

**RESTRICTED WARP**:
- Option to restrict warping to premium players only.
- For example: A "Premium Members Only" island / map server.

---

Thank you for your consideration.

**Comment by BJPickles** [comment]
Added warp suggestion, but again goes under "Can only use if Premium" bool check. I.e could be added to lots of things.

**Comment by xSxSxSsX** [comment]
> Added warp suggestion, but again goes under "Can only use if Premium" bool check. I.e could be added to lots of things.

I have a reverse engineering trick for this. 
make premium a actual item you have or wear, a cash shop item, and have the npc need that item to warp.

**Comment by BJPickles** [comment]
> > Added warp suggestion, but again goes under "Can only use if Premium" bool check. I.e could be added to lots of things.
> 
> I have a reverse engineering trick for this. make premium a actual item you have or wear, a cash shop item, and have the npc need that item to warp. you can do this with no coding

Nifty trick, thanks for sharing!
Hopefully Suri adds all of this so we don't have to use work arounds anymore. :)

**Comment by tylerguitar75** [comment]
> > Added warp suggestion, but again goes under "Can only use if Premium" bool check. I.e could be added to lots of things.
> 
> I have a reverse engineering trick for this. make premium a actual item you have or wear, a cash shop item, and have the npc need that item to warp. you can do this with no coding

This is a fantastic idea, would make for a handy tutorial or addon in the discord or forum :)

**Comment by BJPickles** [comment]
Updated to paid request.
