### ISSUE TITLE
[Bug]Item Refine Dialog

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1568]
since 174/175 there is an issue with item Refine Dialog.

in this case it requite 100 gold and an item.
when player have less then 100 gold it shows this
https://gyazo.com/c5bc4642981857ce37cebdc76d53b7b9

when player has enough gold it shows 
https://gyazo.com/47abc52365a9778a298b37d11959f0f5

**Comment by insthync** [comment]
Fixed in 1.75d
