### ISSUE TITLE
MMO warping issue

### ISSUE THREAD

**Issue by xSxSxSsX** [suriyun-production/mmorpg-kit-docs#1569]
in 1.73c When I enter a map dungeon instance in MMO and die, if I hit respawn it says warping, then respawns me right where I died and still says warping you have to exit the game to leave the instance. Also have an issue loading it seems when I use a portal to go back to the main map it just says loading forever. Ports are open and I know its loading a map but is there anyway to make it instant or quicker and rely on the players hardware>? also not respawn while its warping xD

**Comment by insthync** [comment]
Try change codes following this: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/3d79a8ac0d46b382668bf577406ffb77d87b5f66

**Comment by xSxSxSsX** [comment]
thanks ill try that, also when you hit exit from inside the instance it doesnt save anything that happened in the instance do you know why this is?

**Comment by insthync** [comment]
Don't save anything or just don't save position?

**Comment by xSxSxSsX** [comment]
> Don't save anything or just don't save position?

nothing saves no items or experience its like they never went in

**Comment by xSxSxSsX** [comment]
had a database issue

**Comment by xSxSxSsX** [comment]
> in 1.73c When I enter a map dungeon instance in MMO and die, if I hit respawn it says warping, then respawns me right where I died and still says warping you have to exit the game to leave the instance. Also have an issue loading it seems when I use a portal to go back to the main map it just says loading forever. Ports are open and I know its loading a map but is there anyway to make it instant or quicker and rely on the players hardware>? also not respawn while its warping xD

This is still happening, I fixed the saving but it still has the same slow warp time so when you hit respawn you respawn in the dungeon where you died while your warping then you warp xD  I tried https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/3d79a8ac0d46b382668bf577406ffb77d87b5f66
still the same 
:( any advice?

**Comment by insthync** [comment]
I can't remember where I've made changes, do I have to load the old version and check it just for you?

**Comment by insthync** [comment]
I will check it this weekend

**Comment by insthync** [comment]
I guess it might be the same issues with https://github.com/suriyun-production/mmorpg-kit-docs/issues/1576

**Comment by xSxSxSsX** [comment]
yes the same issue. thank you
