### ISSUE TITLE
Why the map server always crash in MMO?

### ISSUE THREAD

**Issue by HuiZIZhang** [suriyun-production/mmorpg-kit-docs#157]
when I  connect two device in the game,the server will crash show "Server has been closed",Then you can't connect to the game again unless you restart the server，because it is show "Map server is not ready"

I am using the 1.51 version

**Comment by HuiZIZhang** [comment]
two or more people to connect would  crash, but not one

**Comment by insthync** [comment]
Which database you're using, MySQL or SQLite?. please zip your server log files and post the zip file here.

**Comment by HuiZIZhang** [comment]
[log.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/3961194/log.txt)
 using sqlite

**Comment by insthync** [comment]
I see the message `Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found` seems like it is cause of crashes but, you built it for Linux headless right?

**Comment by HuiZIZhang** [comment]
nope, I am using mac os

**Comment by insthync** [comment]
I have to build the Sqlite plugin for MacOS but today I am travelling, I may available to do it tomorrow :p

**Comment by HuiZIZhang** [comment]
Ok,I'll be waiting for you

**Comment by HuiZIZhang** [comment]
Sir,I have solved it,you need to check the sqlite3.dll in all platform,the default just Editor and standalone. if not ,when build an android or ios app ,it would crash

**Comment by HuiZIZhang** [comment]
hey dude,I have solved it,you need to check the sqlite3.dll in all platform,the default just Editor and standalone. if not ,when build an android or ios app ,it would crash, so I think you should change it in your unitypackage for next version

**Comment by insthync** [comment]
Thank you :)
