### ISSUE TITLE
[Suggestion] animal escape 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#1571]
Would be great if you make the monsters escape from players for ( survival games ) this option is useful for animals

**Comment by gordowebdesign** [comment]
What does this even mean?

**Comment by RunOrDi3** [comment]
When you go to attack the animal , animal run away from you ... you just need to put distance when you reach this distance , animal should escape from you

**Comment by gordowebdesign** [comment]
Like a fearful ai?  We have written addon for this in discord community addons
