### ISSUE TITLE
How to open a chest to receive a random item to inventory.

### ISSUE THREAD

**Issue by muzicvn** [suriyun-production/mmorpg-kit-docs#1574]
Hi everyone,

I wonder if someone can guide me how to open a chest (in inventory) to receive a random items? I think it is a bit tricky because we need to create script files. I am new to this project, please help me. Thank you very much.

**Comment by gordowebdesign** [comment]
Someone post loot box addon code in discord, check that out: https://discord.com/channels/460801727789137920/460803151121874944/977209112989401088
