### ISSUE TITLE
[Bug]Logout in an instance

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1576]
there is an issue when logout in an instance while using "Player Character Despawn Milliseconds Delay"

for example when u set it to 30 sec and player logout or has disconnet, other player has 30 second time to kill em. but when the player login back during this time, he is already ported out with his stuff. so you are able to dupe stuff or make other weird things when item drop on death is enabled

**Comment by moepi2k** [comment]
I think thats an other issue. Mine is like that player get duped

**Comment by xSxSxSsX** [comment]
I think "Player Character Despawn Milliseconds Delay" in general seems bugged sometimes in the regular maps Im getting player already logged in when the player tries to log back in but the "Player Character Despawn Milliseconds Delay" is only set to 1 ive tried 0 and it still says that randomly. not all the time. but I have the same issue.

**Comment by moepi2k** [comment]
i think easy fix for this is when use "Player Character Despawn Milliseconds Delay" with following setting and scenario

"Player Character Despawn Milliseconds Delay" = 1 min

when user logout in an instance the player remains for 1 min.
so when player now login before the 1 min is over. it should just check if the player is still in instance and destroy is. so it wont duplicate it.

i remember we had same issue for normal maps (few versions ago) when used that option and user loged back in to game and player was duplicated.

**Comment by insthync** [comment]
Fixed in 1.75e
