### ISSUE TITLE
[Suggestion] How its possible, cant enter game?

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1577]
![Bildschirmfoto von 2022-05-22 17-41-25](https://user-images.githubusercontent.com/18898408/169709980-02e6cec4-aa0d-43a9-8d93-80dec9ffd258.png)

Same on mobile.
But not in editor?

Can not enter game... 
Single Player Button doesnt work, hosting either.

I dont think its up to the package, because the demo is working, but maybe this point could be designed more stable...

**Comment by insthync** [comment]
Is this suggestion? or bug reporting?

**Comment by Pymann** [comment]
Dont know, I dont know if its up to your package, up to any unity version, up to my changes, or up to any incompaiblity.
I cant copy any scene in my project and have it working.
The Demo itself works.
In fresh clones I can copy scenes and have them working.

**Comment by Pymann** [comment]
Maybe anybody has any hint to figure this out ...

**Comment by Pymann** [comment]
I migrated to a new project now. And there is one skill corrupt because of AreaBuffEntity...

**Comment by Pymann** [comment]
I just readded to the db, and its fine ...

So all in all I needed to completely re-setup the project. To fix the not-working Single-Player Button.
