### ISSUE TITLE
[Bug] Fall Damage taken on login, without falling

### ISSUE THREAD

**Issue by ljars** [suriyun-production/mmorpg-kit-docs#1580]
If the player's saved position is negative, the player can take damage when they log in.
For example, if the `Fall Damage Min Distance` is 5, and the player's saved position is the vector [0, -6, 0], then when the player enters the game the player will take fall damage.

Here is a demo where I moved the floor height and player spawn position height to -40:
https://user-images.githubusercontent.com/72370023/169719295-ad49ecb3-3f81-45f9-888d-9a1b4e820c27.mp4

**Comment by BJPickles** [comment]
This has existed for a while. I've also experienced it with distances greater than 1000 metres away from map origin.

**Comment by insthync** [comment]
Fixed, please wait next version

**Comment by insthync** [comment]
Fixed in 1.75e
