### ISSUE TITLE
Duping item that gives bag slots

### ISSUE THREAD

**Issue by xSxSxSsX** [suriyun-production/mmorpg-kit-docs#1582]
Hello I found a dupe its easy to reproduce with a default kit. 

1. make a item like a backpack that gives 10 bag slots.
2. make a item like a backpack that gives 5 bag slots.
3. equip the bigger backpack
4. move the smaller backpack in the last inventory slot you have
5. now drag the smaller backpack into the equip slot replacing the bigger backpack 
6. now you have 2 small backpacks it duplicates the smaller one since it was in a slot that was unavailable

This only works for items that give slots if you have a item on that gives slots and have a item that gives lower slots in the slots that the bigger item opens (at the end) and drag the smaller one onto the bigger one it duplicates it. 

removing the big one removes the extra slot difference you have and if the smaller bag is inside one of those slots that get removed then it dupes.

sorry if make it sound complicated to make it sound easier to understand in other words:

Put on a big backpack, put a smaller backpack item in your last inventory slot now click the smaller backpack in the last slot and select equip and you'll have 2 small backpacks now

**Comment by insthync** [comment]
Not sure how to reproduce, is this correct? https://youtu.be/qGKbphLSPPM

**Comment by xSxSxSsX** [comment]
> Not sure how to reproduce, is this correct? https://youtu.be/qGKbphLSPPM
wear item with bigger bag slots.
have item that gives less bag slots.
equip the bigger slot item
move the smaller slot item in the last inventory slot you have
now drag the smaller item into the equip slot replacing the bigger item
now you have 2 small item it duplicates the smaller one since it was in a slot that was unavailable
check this video for example.
https://vimeo.com/718570031

**Comment by insthync** [comment]
Okay, I will fix it

**Comment by insthync** [comment]
Fixed in 1.75f

**Comment by xSxSxSsX** [comment]
> Fixed in 1.75f

Is there anyway I can get the fix here? I will never be upgrading to 1.75f due to I do not like the movement changes being server sided and don't want all my add-ons to break I appreciate you and will donate on kofi

**Comment by insthync** [comment]
Import just a `CharacterInventoryExtensions.cs` file.

**Comment by xSxSxSsX** [comment]
Thank you <3

**Comment by Skskskskskskssss** [comment]
i imported it and had a bunch of errors so i deleted characterinventoryextention.cs and have this now

Assets\CoreGame\Core\Scripts\CharacterData\CharacterInventoryExtensions.cs(753,22): error CS1501: No overload for method 'GetDismantleReturnItems' takes 4 arguments

**Comment by xSxSxSsX** [comment]
i imported it and had a bunch of errors so i deleted characterinventoryextention.cs and have this now

Assets\CoreGame\Core\Scripts\CharacterData\CharacterInventoryExtensions.cs(753,22): error CS1501: No overload for method 'GetDismantleReturnItems' takes 4 arguments

**Comment by xSxSxSsX** [comment]
yeah still not working with CharacterInventoryExtensions.cs alone :( I appreciate your time any advice on this?

**Comment by insthync** [comment]
Try change that line to BaseItem.GetDismantleReturnItems(nonEquipItem, amount, out returningItems);

**Comment by xSxSxSsX** [comment]
> Try change that line to BaseItem.GetDismantleReturnItems(nonEquipItem, amount, out returningItems);

Im sorry im a bit embarrassed to say im new and have no idea where to change that i've been trying for 15 days... still learning here and you taught me so much with the kit. Thank you for all you do. if you can assist me on fixing this here i will buy you a coffee for your time  thanks!

**Comment by xSxSxSsX** [comment]
@insthync I am very sorry to bother you but im willing to pay for this fix! you're my only hope lol

**Comment by insthync** [comment]
Send your AnyDesk info to my email: ittipon.bay@gmail.com

**Comment by insthync** [comment]
I not available for 2 weeks, I will come back at 26 Jul
