### ISSUE TITLE
[Issue] Cant change npc title

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#1583]
![](https://cdn.discordapp.com/attachments/460803281455939595/978388519481405440/unknown.png)
![](https://cdn.discordapp.com/attachments/460803281455939595/978388661278216212/unknown.png)

![](https://cdn.discordapp.com/attachments/460803281455939595/978387744004898836/unknown.png)

![](https://cdn.discordapp.com/attachments/460803281455939595/978387971512361030/unknown.png)

I can change npc title for the orcish npc only ...?!
For the chieftain its not working ...

**Comment by insthync** [comment]
Is it placed-in-scene NPC Entity?

**Comment by Pymann** [comment]
y

**Comment by Pymann** [comment]
standard ones from demo

**Comment by moepi2k** [comment]
its because name is set in sync field for the human npc but not for the orc. sync field override entity title.
maybe need to change by default that npc name is set in entity title

**Comment by Pymann** [comment]
Its solved by Neomis, the sync fields value will overwrite the title.
