### ISSUE TITLE
Recieved damaged events are busted in 1.75d

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1585]
Seems you made some changes what do i do? lol

**Comment by Fallen-Entertainment** [comment]
![image](https://user-images.githubusercontent.com/71889605/170532016-cbb0ed81-2f65-406a-a259-86394373a421.png)

**Comment by moepi2k** [comment]
hard to say without seeing full script, but i would say u miss some overload of the methode.
in 174 therese something new -> HitBoxPosition position

**Comment by Fallen-Entertainment** [comment]
ya i have hit box position

**Comment by Fallen-Entertainment** [comment]
Im stupid never mind lmao
