### ISSUE TITLE
IAsync Error

### ISSUE THREAD

**Issue by viktorbrenek** [suriyun-production/mmorpg-kit-docs#1586]
Hi, after importing your project into 2021 LTS Unity. I have 2 compile errors and several warnings. I will attach them into this channel. 
![image](https://user-images.githubusercontent.com/70347594/170537000-d2abe69c-6f13-40d3-b395-ba4756307a69.png)

Thank you for any advise. Have a nice day. 
 Viktor

**Comment by viktorbrenek** [comment]
Okey it isnt bug. I just missed it in the documentation. Sorry. Closed

**Comment by chibisann** [comment]
Could you help me you think?  Even after deleting the appropriate dll files, I still can’t acces scripts like GameData. It just show that I have a compiler error in the Inspector. 

Are you using an older version of Unity?

**Comment by viktorbrenek** [comment]
Hi. I need to download Unity 2021.3.2f1. bcs LTs version has massive bugs
for now.
Then delete dll files accordingly to the documentation and download the
extension provided in docs. You should be good to go.
I hope i could help you bro. Have a nice day
Viktor

pá 27. 5. 2022 v 19:28 odesílatel chibisann ***@***.***>
napsal:

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021
