### ISSUE TITLE
Importing problems and compiler errors.

### ISSUE THREAD

**Issue by chibisann** [suriyun-production/mmorpg-kit-docs#1587]
So, whenever I import the project, whether by importing it into a separate project or in the same project, none of the scripts are "compiled" and I can't open them at all in the Inspector.

I delete the appropriate dll files, but still. I can't build the Init file, I can't open any of the scripts, nothing. 

Is the version of Unity I'm using the problem? Is there something I'm missing during import? Is there something I'm missing after import? I can't use the Kit whatsoever and I'd really appreciate some help. 

I don't have a lick of code knowledge, and I've been watching videos in regards to MMORPG kit, and just really want to try my hand at development. Please, some help with importing this package would be greatly appreciated.

**Comment by Randolphjand** [comment]
If you are on 2021 or above you need to follow the directions in the docs for using 2021 under Troubleshooting at the bottom of the docs.

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021
