### ISSUE TITLE
 adding Hotkey Mobile version

### ISSUE THREAD

**Issue by alexengel1992** [suriyun-production/mmorpg-kit-docs#1588]
I've tried everything and I haven't been successful when adding Hotkay in the mobile version, is there any tutorial or explanation on how to do it?
![image](https://user-images.githubusercontent.com/83098223/170824018-dbc4eb7f-ce33-4ce7-bbf8-25bcd9036ce9.png)

**Comment by insthync** [comment]
Everything?

**Comment by insthync** [comment]
![Screenshot_1103](https://user-images.githubusercontent.com/2697550/171998441-6b76ddb8-97e8-4738-b90b-bb0a29fcce1f.png)
![Screenshot_1104](https://user-images.githubusercontent.com/2697550/171998448-9dbc223e-8442-4eab-9dfc-4bd6c18ed3e1.png)
![Screenshot_1105](https://user-images.githubusercontent.com/2697550/171998452-5d65fad3-b9a2-4ac9-bb50-fd5021f9c913.png)
