### ISSUE TITLE
Any Plan for Auction House ?

### ISSUE THREAD

**Issue by temelkirciInventuna** [suriyun-production/mmorpg-kit-docs#1590]
@insthync 
Are you working on Auction house feature?.I made a mobile offline rpg game and I would like to release a MMORPG version next mount.I need a Auction house?

https://play.google.com/store/apps/details?id=com.TemelKIRCI.TheWrathOfTheErlik

if no, can I add a auction house by using guild storage feature in MMORPG kit ?
if yes, when can you add auction house for MMORPG kit?

**Comment by insthync** [comment]
https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse
