### ISSUE TITLE
Bug Pet removed from inventory

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#1591]
Pets killed in reload time disappear from the inventory after closing the game and opening it again

**Comment by insthync** [comment]
MMO or Singleplay/LAN mode?

**Comment by insthync** [comment]
I can't reproduce it yet.

**Comment by RafaelRBizachi** [comment]
Singleplayer , if the pet dies and closes the editor with it in reload time, the item simply disappears from the inventory

**Comment by RafaelRBizachi** [comment]
I managed to solve it, the error was my own because the item was not registered in the base data, thanks for your attention
