### ISSUE TITLE
GetMovingspeed is not correct

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#1592]
Hey there, 

i found out, that when in sprinting mode the player won´t move, a false value will get returned by getmovingspeed().

https://youtu.be/lEeHTY17ICs

For example: 
Runningspeed: 1.5-2
Sprintingspeed: 4

When i press SHIFT, my player begins the sprinting and the result from getmovingspeed() is 4. but when i stop moving, the result is STILL 4 and not 0

**Comment by insthync** [comment]
It's constantly updated to correct value when it has movement state changes, so I don't know why it has to be correct? , how will you going to use it?

**Comment by xnitro1** [comment]
i´m using the TopDown-Controller for my Shooter-Game and used the getmovingspeed() to get the actual moving speed from the player. I need that in order to prevent shooting while sprinting. But it is possible to have sprinting enabled, but when looking not forward the animation changes to walking sidewards and therefore reducing the movement speed (and therefore enabling shooting again).

it´s not possible to just use isSprinting, because even when sprinting the player can have different movingspeeds. So i needed the actual moving speed when moving (or when not moving it should be zero)

**Comment by insthync** [comment]
Don't shoot while sprint?

**Comment by xnitro1** [comment]
well there is no option to prevent shooting while sprinting or have i overseen this option?

got a workaround now working with :

if(isSprinting == false || (isSprinting == true && PlayerCharacterEntity.MovementState.ToString().Contains("Forward") == false))
{
//do something
}

but this way is miles away from the perfect way to code. when having a method named "PlayerCharacterEntity.GetMoveSpeed()´" i thought i get the actual moving speed from the player. If this is not the case, then the method name is not as clear as i thought it would be

**Comment by insthync** [comment]
You want a "don't shoot while sprint" option, right?

**Comment by xnitro1** [comment]
Correct. But rather "dont shoot while doing the sprint Animation". Because Sprint can bei true but when Walking sidewards the Animation is the Walking one. So a simple "dont shoot while Sprint" is mit enough

**Comment by insthync** [comment]
Okay, I will fix it by making the extra movement state correct then the movement speed will automatically correct too.

**Comment by xnitro1** [comment]
thank you and sorry to cause you inconvenience :)

**Comment by insthync** [comment]
Try `CurrentMoveSpeed` property which added in 1.75f
