### ISSUE TITLE
Building issue's

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1594]
If you create a small area where building is possible, only the first piece of foundation u place will actually check if building spot is buildable. after u place one u can endlessly attach foundations to the side of it, extending outside the buildable spot with no limitation.

Also if u make like a 2 story high house, ur top floor can build into the neighbours land with the same logic.

this is becuase there is no ground check to see if buildable, it will just check the already placed foundation, snap  the new one to the grid on one of the sides and continue.. 

this is extremely inefficiënt if u wanna have any serious building system, for example where people can own lands etc.

Would highly appreciate it if u could take a look at this.

**Comment by insthync** [comment]
You want it to check owner of the area before allow to build a building ?

**Comment by Callepo** [comment]
> You want it to check owner of the area before allow to build a building ?

no, i am doing that myself, but the building needs to check if its possible to build before placing new area, ill make a video to explain better.. give me 1 min

**Comment by insthync** [comment]
In 1.75f I have added a way to add conditions to allow to build and also implement a way to fix it by creating  a `AllowToBuildOnSameAreaBelow` component, adding this component anywhere in the building entity prefab then set it to building area's `buildConditions` field

![Screenshot_1115](https://user-images.githubusercontent.com/2697550/172954027-c01047fe-c70d-47bd-a375-18e47fc8bc1e.png)

**Comment by Callepo** [comment]
much appreciated!
