### ISSUE TITLE
CharacterDeathSoundComponent

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1595]
for that Component you have just the option for Volume like
https://gyazo.com/e3c52dae60848a617f2847921ffea9b3

since u already added an audio manager it would be better to have option to use type for output to controll it like
https://gyazo.com/638699686e473ee05af5a3be527af540

because right now u can reduce the volume in option to 0 but u still have deathsound volume of 1

**Comment by insthync** [comment]
Changed in 1.75f, now its settings is like audio source setter component
