### ISSUE TITLE
Cant seem to get skills to gather resources

### ISSUE THREAD

**Issue by Fallen-Entertainment** [suriyun-production/mmorpg-kit-docs#1596]
I checked the documents nothing on the subject if you could explain how it should be set up I would appreciate it.

**Comment by insthync** [comment]
I don't remember that I've implement it already :P

**Comment by Fallen-Entertainment** [comment]
Well that would explain why it doesnt work... LoL Its listed on the spawner

![image](https://user-images.githubusercontent.com/71889605/172737549-9d146909-8178-4f39-aecc-9f172ecbbfb3.png)

**Comment by Fallen-Entertainment** [comment]
anyway let me know if this implemented or not lol

**Comment by insthync** [comment]
In skill game data it has a `HarvestType` setting, 
- if you set it to based on weapon, it will calculate damage based on weapon type's effectiveness (which is set in `Harvestable` game data) and weapon item's `harvestDamageAmount` setting.
- if you set it to based on skill, it will calculate damage based on skill's effectiveness (which is set in `Harvestable` game data) and skill's `harvestDamageAmount` setting.

**Comment by Fallen-Entertainment** [comment]
Thank you for explaining, Ill check it out ASAP.
