### ISSUE TITLE
Suggestion: Currency.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1597]
1. ![image](https://user-images.githubusercontent.com/47291794/172807356-32d45076-2abb-4799-a627-90a097582a6e.png)
You've added the use of currency for crafting, but it still doesn't seem to apply.
Skills:
![image](https://user-images.githubusercontent.com/47291794/172807593-3557fa80-e564-4eb2-82e5-c883fd9e3a1e.png)
Formulas:
![image](https://user-images.githubusercontent.com/47291794/172807701-aac56bc3-faf8-4a2c-b4d0-2203d2dce166.png)
2. Ability to upgrade items using currency.
![image](https://user-images.githubusercontent.com/47291794/172808292-5d551633-2115-4b4a-8b75-d7fd7aba8cdf.png)
Also for repair.
![image](https://user-images.githubusercontent.com/47291794/172808237-34c0d5a7-0612-4dd1-93e2-62a5d1038bf4.png)
3. Ability to create a currency (crafting currency) using a currency (similar to converting a currency into another currency).

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.75f

**Comment by DimasjkTV** [comment]
> Fixed in 1.75f

Thanks for adding these features! It would be cool if you added the ability to craft currency. It's like converting one currency to another.
![image](https://user-images.githubusercontent.com/47291794/173030373-18c2cfa2-ca73-4942-8f12-a851dbcb05d6.png)
