### ISSUE TITLE
[1.75e] Fall Damage Broken (Spam kills player)

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1598]
Any fall damage taken will result in a bug server side where it'll be continuously applied to the player and then killed.

VIDEO: https://i.imgur.com/lGuXhqy.mp4

I had to load up the production/standalone client because I could no longer connect to the server through Unity. Server kept refusing connection.

Second video: https://streamable.com/o7stc6
Recreated fall damage bug near the end of the video.

Error on server:
![image](https://user-images.githubusercontent.com/48354382/172929213-ef47e4a0-a39b-4e15-800f-539a605bcead.png)

Spammed very quickly.

**Comment by insthync** [comment]
What is in  `OnReceivedDamage_WSS` ?

**Comment by Fallen-Entertainment** [comment]
I dont have this bug.
