### ISSUE TITLE
Has the level requirement been removed to use the skill?

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1599]
Has the level requirement been removed to use the skill?

I looked and only found the requirement to level the skill, but the level requirement to use the skill no longer exists

**Comment by insthync** [comment]
I can't remember that it has that implemented.

**Comment by insthync** [comment]
Do you want it for skill items? because for skills it does not make sense to have it, if you can't learn it how it can be used?

**Comment by juniormagalhaes** [comment]
You're right, but one thing, when the skill is at level zero you can't open the skill dialog

**Comment by insthync** [comment]
I want to see full log message

**Comment by juniormagalhaes** [comment]
> I want to see full log message

https://gyazo.com/006992e8c4cb31c81701070f3e1ab602

**Comment by insthync** [comment]
Full log message, please

**Comment by insthync** [comment]
Just click on the error message entry then full log message will be appear below

**Comment by insthync** [comment]
And this was fixed, try reimport UICharacterSkill

**Comment by juniormagalhaes** [comment]
> 

![image](https://user-images.githubusercontent.com/56885137/173109746-3e34d534-eea9-4e3a-8ec2-ec52c88a3255.png)

**Comment by juniormagalhaes** [comment]
> 

ok

**Comment by insthync** [comment]
Reimport `UISkillRequirement`, `UICharacterSkill` and you might have to change your UICharacterSkill prefab

**Comment by insthync** [comment]
What I mentioned above is delete UISkillRequirement from current level

![Screenshot_1119](https://user-images.githubusercontent.com/2697550/173110833-eed6d480-3648-4a0d-8f9c-86d2f23c9da4.png)

Only next level will have it

![Screenshot_1120](https://user-images.githubusercontent.com/2697550/173111121-e8335a5e-0a6c-4efb-bff6-4b73a4b4ae54.png)

**Comment by insthync** [comment]
No answer, then I will close it.
