### ISSUE TITLE
class

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#16]
Hello, can you help me? i try add a class of character, but can't do this.

I try copy prefab and change player character settings and add it to database, but nothing happen, can you help me ?

I want add a class character to first page, how it we can see as "Adventure"

**Comment by insthync** [comment]
See this document https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/017-player-characters

You will have to create `PlayerCharacter` add it to your `GameDatabase` or `Resources` folder 

Then in your `Player Character Entity` you will see **Player Character Settings** section, set created `Player Character` to `Player Characters`

![](https://suriyun-production.github.io/mmorpg-kit-docs/images/new_player_character_entity_setting.png)

**Comment by 1isenok** [comment]
yeah, thank you but i understand this. I mean how can i add it in this scene i try do all that you write but it's didn't help(

![image](https://user-images.githubusercontent.com/48797909/54846083-c6263700-4d26-11e9-8a29-966d83723ff2.png)

**Comment by 1isenok** [comment]
and if you can explain me please tell were is contains information about button

**Comment by insthync** [comment]
Not sure this is what you wanted or not , In Home scene → UI Character List → Ui Character Prefab

![Screenshot_3](https://user-images.githubusercontent.com/2697550/58947862-12740580-87b3-11e9-905e-6263c9c343bc.png)
