### ISSUE TITLE
items not dropping

### ISSUE THREAD

**Issue by xSxSxSsX** [suriyun-production/mmorpg-kit-docs#1605]
weird thing happening not expecting you to fix anything just maybe some advice if you can think of anything but, none of my item drops are working from killing monsters they worked before but stopped recently no errors in the console. any idea why?

**Comment by insthync** [comment]
![Screenshot_1122](https://user-images.githubusercontent.com/2697550/173247408-95241cb0-e144-41a3-8cbb-ec1502a481fa.png)

What is your setting?

**Comment by xSxSxSsX** [comment]
It's set to drop on ground that's why I'm confused

**Comment by xSxSxSsX** [comment]
nevermind your right it got switched back somehow. Buying you a coffee for this thank you
