### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ChaosXIII** [suriyun-production/mmorpg-kit-docs#1606]
is there a way to turn off "Client Authoritative Entity Movement will be validated at server" from 1.74 (2022-04-18)?

I dont want to decrease server performance it seems this update made the client movement server auth is this true? 

If i update am I am i able to turn off client movement auth? 

Thank you!

**Comment by insthync** [comment]
Okay, I will add the option later

**Comment by xSxSxSsX** [comment]
Thank you, I appreciate it especially because we have active GM and if any speed hacking we just ban them when this setting is turned on nobody can move it lags so bad 😔

You're the best

**Comment by xSxSxSsX** [comment]
just got you a coffee on ko-fi for this too :) thank you once its added ill tip you more, do you really drink that much coffee? lol ;)

you're the best Developer ever... by the way thank you for helping me learn to make games I appreciate you so much I learned from the best!
