### ISSUE TITLE
Cannot connect to the server..... ???

### ISSUE THREAD

**Issue by temelkirciInventuna** [suriyun-production/mmorpg-kit-docs#1607]
I am having this error when I tried to connect to local server in my laptop. ??????
@insthync 

![qwert](https://user-images.githubusercontent.com/105419408/173230986-01aa0ea9-b5f9-467d-bb09-2019c37946a3.png)

**Comment by insthync** [comment]
Want to see arguments that you put into shortcut's target setting.

**Comment by temelkirciInventuna** [comment]
solved, thank you @insthync
