### ISSUE TITLE
BUG: Currency text in crafting window

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1608]
Only when we use a currencies like materials for item craft.
1. When we do not have enough materials for crafting, everything is displayed well.
![image](https://user-images.githubusercontent.com/47291794/173238393-55f32e60-7762-4dff-a8e3-8a18c85ec2ca.png)

2. But when we have enough materials for crafting, then we lose the current value of the currency that the character has. All that is left is what is needed to create the item.
![image](https://user-images.githubusercontent.com/47291794/173238593-7fb40947-49f9-4e1c-b1f9-a93a2d862db8.png)
It looks like it's starting to use "UI_FORMAT_CURRENCY_AMOUNT" and not a "UI_FORMAT_CURRENT_CURRENCY" and we cant use {2} in this, but only {0} and {1}

When we use items like materials for item craft all works well.
1. 
![image](https://user-images.githubusercontent.com/47291794/173238696-e1097e5c-40f3-4ec1-83ac-3460a94328bf.png)
2. 
![image](https://user-images.githubusercontent.com/47291794/173238711-98621209-cf85-4b02-8d2d-50fe9f19e3e5.png)

**Comment by insthync** [comment]
Set `useSimpleFormatIfAmountEnough` in `UICharaterCurrencies` to `False`

**Comment by DimasjkTV** [comment]
> UICharaterCurrencies

I havent this line in this script. What line should I add this to?
