### ISSUE TITLE
Having issues getting character to move

### ISSUE THREAD

**Issue by chibisann** [suriyun-production/mmorpg-kit-docs#1609]
Not sure what I'm doing wrong. I have NavMesh implemented onto my terrain, as well as a NavMeshAgent onto my character, but it won't move? Is there something I'm missing? Is there an input or something that's not enabled for my character?

**Comment by insthync** [comment]
Did you add `NavMeshEntityMovement` component?

**Comment by chibisann** [comment]
![Capture](https://user-images.githubusercontent.com/106354490/173247411-359cd34a-4cd0-456f-a3ec-7e9d504bbf57.PNG)
Yes, I essentially just copied over the MMORPG Kit PlayerCharacter into the scene to test out movement.

**Comment by insthync** [comment]
You may check your player character's base stats  -> move speed 

![Screenshot_1124](https://user-images.githubusercontent.com/2697550/173247592-69f2e767-2332-4659-abce-b6b6c9234581.png)

**Comment by chibisann** [comment]
So, I was missing Move Speed, however, it's still not working :/ I tried just making a simple cylinder and adding the appropriate scripts, and still nothing.
![Capture](https://user-images.githubusercontent.com/106354490/173248194-08590308-0d52-4dfc-b679-643dadac0386.PNG)
![Navmesh character](https://user-images.githubusercontent.com/106354490/173248199-7aa4600b-40f0-4463-8d23-cf4e7eab8340.PNG)
![Terrain Mesh](https://user-images.githubusercontent.com/106354490/173248202-30539f41-f889-4b3c-9eb8-6bc90f7d6e2f.PNG)

This is what I'm seeing in regards to the movement stuff.

**Comment by insthync** [comment]
Try to add `CharacterModelManager` component, there is an error because it is missing.

**Comment by chibisann** [comment]
I ended up just downloading another movement thing from the asset store. wasn't able to get any of these things to work :/

Just having trouble trying to figure out how to have enemies become targetable now

**Comment by insthync** [comment]
What is the problem now ?
