### ISSUE TITLE
MMO2D bow does not hit target, arrows are used 

### ISSUE THREAD

**Issue by marcos1991** [suriyun-production/mmorpg-kit-docs#161]
bow does not hit target, arrows are used but do not hit enemy (orc archer) i'm using mmo2d. Physical attack works perfect.
how to fix? thanks

**Comment by insthync** [comment]
[MMORPGKIT-FixingMissileHitNonTarget.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3989761/MMORPGKIT-FixingMissileHitNonTarget.zip)
Fix by this package

**Comment by marcos1991** [comment]
work, thanks :)
