### ISSUE TITLE
Adding damage amount and magical attack for int and str stats

### ISSUE THREAD

**Issue by temelkirciInventuna** [suriyun-production/mmorpg-kit-docs#1610]
I want to add damage amount and magical attack when I increase str or int stats.How can add damage amount and magical attack amount for character stats.

For example : When I give a stat point for int, It will increase magical attack for mage, when I give a stat point for str, I will increase default damage amount for warrior.

@insthync

**Comment by moepi2k** [comment]
On Scriptables for Skills or Weapontype u have a field for Effectivness which increasse the damage. but wont work with buffs like healing
