### ISSUE TITLE
Virtual & Sealed Scripts.

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1611]
Can The Mount(); Method in BaseCharacterEntity be a virtual Method so we can add extra conditions for Mounting.

![image](https://user-images.githubusercontent.com/7702658/173428869-5d8c48a3-0042-4d13-b459-4187cf294f40.png)

MapNetworkmanager is also a Sealed script, we cant Inherit it to be able to override methods inside this script.

Basically i couldnt override anything to add 1 more condition for mounting.

Simply making Mount(); Virtual will solve all of these issues.

![image](https://user-images.githubusercontent.com/7702658/173429419-04362b74-8c97-4671-9f47-99770db35130.png)

**Comment by insthync** [comment]
Did it.

**Comment by insthync** [comment]
Fixed in 1.76
