### ISSUE TITLE
GM ban not working

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1612]
I tried to ban a player that was offline the command seemed that it worked but it didnt ban the account. I just went into the database and changed the password as a ban which is fine but if it did work they can just make a new account... 

Is there anyway we can do a IP ban instead of a account ban? if not i understand no big deal im just letting you know about it not working

**Comment by insthync** [comment]
It don't have IP Ban

**Comment by Skskskskskskssss** [comment]
yes entered right no big deal i just change the password on the account in the database as a solution

**Comment by molonlabe1337** [comment]
Thank you

**Comment by molonlabe1337** [comment]
Yes I tried that didn't ban anything I just changed their password

**Comment by insthync** [comment]
Seems like only you having these issues.

**Comment by molonlabe1337** [comment]
That was a old message my email synced from months ago this was resolved sorry
