### ISSUE TITLE
[Bug]Building Stuff not saved in MMO when restat server -> 175d

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1614]
as title said.
worked before

**Comment by insthync** [comment]
As I try it still being saved.

**Comment by moepi2k** [comment]
uf damn, then i need to check whats goin on here. everything was fine so far.

do you tested wit latest version or 175d?

**Comment by insthync** [comment]
I tested with the latest version.
Nothing changed in the tables.

**Comment by moepi2k** [comment]
Alright, thanks for ur time. I noticed it happen only in my maps. Map001 works. Weird. I need to debug

✌️

**Comment by moepi2k** [comment]
mh can u maybe lead me how to debug it?
its really weird.

all my building stuff on my maps are not saved in mmo
when i add map001 it works.

i also copied my full scene into map001 and it also works.

these are logs for map001
https://gyazo.com/d04c639ef8cc50db77c84dcb7730b8f6

this are my map
https://gyazo.com/f3689e89bc45d77e5d593af7ffcfd865

it seems that it save it. but when i restart server all is gone only map001 building stuff remians

**Comment by moepi2k** [comment]
ok i found the issue.
i checked my db and saw that building stuff is saved. so i checked why its never loaded. the thing is this
-> https://gyazo.com/5013c585afd22211fa54907ce3c744ee

mapName is Scenename. actually this is not the problem. the problem was that i have multible MapInfos with same Scene attached.

so i assume when server starts and it should load building stuff. he not know on what mapinfo he should load it. so it seems u neeed to have unique scenes attached to mapinfo.

**Comment by insthync** [comment]
Hmm, I think I should fix it to change from scene name to map info ID, but I afraid that it would affect some customer projects

**Comment by insthync** [comment]
Fixed in 1.76
