### ISSUE TITLE
Foot IK, Playable IK

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#1616]
These two checkboxes don't appear to do anything.

I'm sure this is a config/setup issue on my end, but I cant find any documentation on how to use these features.... :(

**Comment by insthync** [comment]
I add those options because the [AnimationClipPlayable](https://docs.unity3d.com/ScriptReference/Animations.AnimationClipPlayable.html) has them, but I don't know how foot IK work too, I think I actually should enable all of them and remove the settings.

**Comment by BJPickles** [comment]
Please leave the settings. There's some unintended effects of enabling them on some models and having them permanently on would cause issues.

Maybe add a tool tip instead?

**Comment by LordPhrozen** [comment]
So, to extend this conversation a bit. I did have a bunch of luck implementing this **free** asset to do foot IK, needed some basic configuring for our model, and was good to go : https://assetstore.unity.com/packages/tools/animation/homebrew-foot-ik-220358#publisher

The only issue left to resolve is to toggle it off when I jump, and toggle back on when I land. 

Any opinions of the best place to do that?

**Comment by insthync** [comment]
May uses entity movement's (such as `CharacterControllerEntityMovement`, `RigidbodyEntityMovement`) `MovementState` to find that the character is on ground or not like this `MovementState.Has(MovementState.IsGrounded)` to apply foot IK.
