### ISSUE TITLE
Disconnect issue when idle

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1619]
Hi my community is having an issue where if they're idle in the game for a while the game will disconnect you for being idle. Wondering what I can change to stop this. I cant find where the afk setting is.

I tried to reach out to a few other guys from the community and they said its a bug not feature.
Thank you for your time. If you can help me with this im willing to buy you some coffee to bribe you haha ;)

**Comment by insthync** [comment]
I will check it.

**Comment by molonlabe1337** [comment]
> I will check it.

Thank you I really appreciate it. I spent a lot of time trying to find where it would even be if you made one.
