### ISSUE TITLE
1.51 Bug Summoned Creatures

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#162]
Single player. 
- Summoned Creatures reset their level to 1 after log out or moving between locations.

**Comment by insthync** [comment]
Summon from item?

**Comment by DimasjkTV** [comment]
> Summon from item?

Skills

**Comment by insthync** [comment]
[MMORPGKIT-FixingCharacterSummonNotSerialize.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3990583/MMORPGKIT-FixingCharacterSummonNotSerialize.zip)
Try this

**Comment by DimasjkTV** [comment]
> [MMORPGKIT-FixingCharacterSummonNotSerialize.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3990583/MMORPGKIT-FixingCharacterSummonNotSerialize.zip)
> Try this

Works!

**Comment by DimasjkTV** [comment]
> [MMORPGKIT-FixingCharacterSummonNotSerialize.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3990583/MMORPGKIT-FixingCharacterSummonNotSerialize.zip)
> Try this

- Is it possible to make summoned creatures (skills) immediately attack the target? Now they attack only if the character do strike to the enemy or receives a strike from the enemy.
- Monsters attack only the character. I think that monsters must attack summoned creatures. Maybe Taunt skill  will help?
