### ISSUE TITLE
Player remains even when logout

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1620]
few players idle around for few days now. they stay exactly at same positon, so they are logged out. may alt f4 or something. but somehow the player still in game. only way to kick em is to restart server.

hard to reproduce. its random. but it happen sometimes

**Comment by insthync** [comment]
@colt0560 Did you try the latest version?

**Comment by colt0560** [comment]
im scared to update bc i edited alot of core code... im like 3 versions behind. do you know what script it was or what got fixed so I can try to update just that?

**Comment by colt0560** [comment]
i am on 1.78 currently

**Comment by insthync** [comment]
But still having issues?
