### ISSUE TITLE
Limited Quest

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1621]
**On going quest**
Quest A has 3 task. 
Quest B Requires Quest A to be ongoing to be able to start it.. 

If u complete all 3 task on Quest A... during Quest B, u cant complete Quest B becuase the kit now thinks that Quest A is complete before if the QuestTasksDone Bool in the check.. which is not smart.. Ongoing should be untill u fully complete Quest A..
![image](https://user-images.githubusercontent.com/7702658/175073652-471fcd48-3827-4835-b249-1090a3029710.png)

**Complete Quest**
the method is not virtual, and there is no event plugged in to Quest Completion.. there is no way to alter this or add on this...
![image](https://user-images.githubusercontent.com/7702658/175073920-7087c997-6148-4f5a-b3a0-9bdf27a6596d.png)

Can this be updated to virtual pls. Thank you.

Also dont forget bout this post. 
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1611

Also u said u will change this one a while ago, but its still not in the kit , maybe u forgot idk.
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1494

@insthync

**Comment by insthync** [comment]
Changed

**Comment by insthync** [comment]
Fixed in 1.76
