### ISSUE TITLE
1 warp not working

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1623]
for some reason my 7th warp in the scene is not working ports are open im not using a config file i have it set in the inspector like the others. all my portals work except this last one it works perfect in single player but not mmo any idea why?

**Comment by insthync** [comment]
There is any error message when enter warp portal ?

**Comment by molonlabe1337** [comment]
sadly no error message it was strange im going to try again and let you know
