### ISSUE TITLE
Alpaca

### ISSUE THREAD

**Issue by Randolphjand** [suriyun-production/mmorpg-kit-docs#1625]
If you ride the Alpaca in the Demo scene you receive this error.
MissingReferenceException: The object of type 'AnimationClip' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
MultiplayerARPG.GameData.Model.Playables.AnimationPlayableBehaviour+BaseStateInfo.GetClipLength (System.Single rate) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Model/3D/PlayableBehaviours/AnimationPlayableBehaviour.cs:28)
MultiplayerARPG.GameData.Model.Playables.AnimationPlayableBehaviour.PrepareFrame (UnityEngine.Playables.Playable playable, UnityEngine.Playables.FrameData info) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Model/3D/PlayableBehaviours/AnimationPlayableBehaviour.cs:398)

**Comment by insthync** [comment]
Animation clip is missing from state setting, but I don't know which clip, you may add log to show which state in `PrepareFrame` function add codes to show log: 

![Screenshot_1160](https://user-images.githubusercontent.com/2697550/175531942-aef78e1b-6b8d-4a32-9f62-32222f989147.png)

**Comment by Randolphjand** [comment]
I know what I did.  I removed the grid visible script from the Alpaca because it said it was deprecated. That causes this error.

**Comment by insthync** [comment]
No, it must not be the cause of issues.

**Comment by Randolphjand** [comment]
You are correct.  I tried removing the grid visible script in other projects and the error did not appear.  This project is not important so it does not matter but I thought you should see the error but I don't think I changed anything else.  It is just a project for testing so the issue can be closed and I will tell you if it happens again.
