### ISSUE TITLE
Console UI Controls (PS/XBox/Nintendo Switch)

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1627]
What are the plans to put Console UI Controls (PS/XBox/Nintendo Switch)? Is it in progress or is it stopped for now?

I'm just curious about

**Comment by insthync** [comment]
I was actually lazy to remake all UI prefabs for the Console :P

**Comment by juniormagalhaes** [comment]
> 



> I was actually lazy to remake all UI prefabs for the Console :P

XD
