### ISSUE TITLE
no reload animation and sound in MMO Mode

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#1628]
After updating the MMO Kit to the version 1.75e there is no reload animation and reload sound on the client anymore. It is still visiable for other clients, but not for "myself"

Client A reloads -> Client A has no Animation, but Client B can see the animation like they should. 

So the animation and sound is not played "locally".

Is this a bug or was it already posted? Sorry i havent seen it, but could find another person on discord who had the same issue

**Comment by insthync** [comment]
Weird, it was reported and fixed before 1.75e, I will recheck it.

**Comment by xnitro1** [comment]
I saw you updated the asset yesterday and today, but i couldnt find any news on this topic. are there any news?

**Comment by insthync** [comment]
Fixed in 1.76c4

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.76d
