### ISSUE TITLE
ReceivedDamage no skill.dataId when use DamagerOverTime

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1629]
hi, 
i have a small issue. lemme show a video and a screenshot. its easier to understand
https://gyazo.com/3f9fe638e47fa4c315c0059878af451e
https://gyazo.com/c6965d9595f11e1dc86ff55e884ac735

1) first shot is normal attack (no skill) -> it shoes the weaponId
2) second shot is a fireball (skill) with damage over time -> when hit u see weaponId and the Skillid, BUT when the DOT count it never show weaponId or SkillId
3) Firewall is a SimpleAreaAttackSKill with damager over time -> here the DOT will show skillID on every tick.

why is it not showing for the Skill Dot? is it a bug or is it possible to fix this somehow?

**Comment by insthync** [comment]
I will check it.

**Comment by insthync** [comment]
Damages that are applied by buff's `damageOverTimes` won't have weapon item data, skill data, skill level included because it has to store so much data. So I won't pass it to `ReceivedDamage`'s parameters.

**Comment by moepi2k** [comment]
Hmm okey, do you have abother solution then, because for your kill notify integration u made,  it wont count/show when someone  get killed by a debuff

**Comment by insthync** [comment]
From this one? https://github.com/insthync/UnityMultiplayerARPG_ShooterExtensions

**Comment by moepi2k** [comment]
exactly

**Comment by insthync** [comment]
Updated

**Comment by moepi2k** [comment]
cool thx,

but it still not work when someone died by a debuff
https://gyazo.com/b21ecd6650ba51d7ab4a842c902be093

it throws an format error
https://gyazo.com/cc250b3c2184bf32a02641666f96b89e

**Comment by insthync** [comment]
Wrong format fixed

**Comment by moepi2k** [comment]
great works now, thank you very much

**Comment by insthync** [comment]
I've changed my mind, I've changed it to pass weapon, skill and skill level to `ReceivedDamage` function, I was over thinking about networking data syncing. But it have some limitation, it cannot have those data when loaded from saved, so when you exit the game or change the map, it can't define weapon, skill, and skill level data, so it won't have those data pass to `ReceivedDamage` function.

**Comment by moepi2k** [comment]
great, thanks for the info. i think it would be enough for realtime like the KillNotify addon to inform ppls that they get killed by a spell or debuff for example.
