### ISSUE TITLE
Mobile inventory situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1631]
It is still possible to drop items from the inventory if we are using the "UIItemIcon_WithDragHandler" prefab on mobile. The item will drop from the inventory if we move it a little and release our finger. You can see that only on mobile. You cant see that in Editor.
Items also drop if you drag them off the screen.
For example like this
![image](https://user-images.githubusercontent.com/47291794/176544977-1bd193f5-097c-411e-92ed-d6456c12968d.png)
For my game, I solved this problem by disabling this code in UICharacterItemDragHandler.
![image](https://user-images.githubusercontent.com/47291794/176548155-2c2a0686-afd2-456d-8134-a1a3eef01bb3.png)

But it would be better if you could add a checkbox to disable the drop of items on the ground by dragging them from the inventory. If possible.

**Comment by insthync** [comment]
In 1.76b
- Add `enableDropItemAction` option to `UICharacterItemDragHandler`, enable it to drop item when drop the dragged UI.
- Add `enableUnequipItemAction` option to `UICharacterItemDragHandler`, enable it to unequip item when drop the dragged UI.
- Add `enableMoveFromStorageAction` option to `UICharacterItemDragHandler`, enable it to move item from storage when drop the dragged UI.
- Add `enablePickupFromContainerAction` option to `UICharacterItemDragHandler`, enable it to pick up item from container when drop the dragged UI.
- Add `enableUnassignHotkeyAction` option to `UICharacterItemDragHandler`, enable it to unassign hotkey when drop the dragged UI.
- Add `enableUnassignHotkeyAction` option to `UICharacterSkillDragHandler`, enable it to unassign hotkey when drop the dragged UI.
