### ISSUE TITLE
Audio Source Setter situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1632]
Single player game.
![image](https://user-images.githubusercontent.com/47291794/177006693-8a1685fc-916b-4c96-9573-86772ef6a7fc.png)
All this for BGM (Background music) or ambient.
It seems that the sound randomization in the audio manager is not working correctly. For example, we added two sounds per location. Random occurs only at the moment when we enter a location or scene. For example, we randomly played the first sound, then it will always loop until we leave this scene. In my example, the second sound will never play again until we restart the game or move to another scene.

**Comment by insthync** [comment]
If it is an audio source setter component, then it is works as intended, random clips will random plays 1 clip and 1 time.

**Comment by DimasjkTV** [comment]
> If it is an audio source setter component, then it is works as intended, random clips will random plays 1 clip and 1 time.

Yes. I mean what is now happening randomly at the moment of appearing on the scene. There are three sounds in the video, but only one plays in the current location. To change it, you need to re-enter the stage.
https://youtu.be/5x6lxY4w3rg

**Comment by BJPickles** [comment]
> If it is an audio source setter component, then it is works as intended, random clips will random plays 1 clip and 1 time.

Having the same experience, only 1 sound from the list will play, none of the others will. So it just loops on the same sound etc, rather than move forward to another random sound.

**Comment by insthync** [comment]
It is working as intended, the random clip part is made for SFX, not BGM or ambient. If you want something like that, do it by yourself.
