### ISSUE TITLE
IsCharging never not set back to false after using

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1633]
hi,

i debuged the IsCharging in BasePlayerCharacterEntity. After Charging, the bool never switch back from true to false.

https://gyazo.com/a8d047630e659a444578e3784e0c1872

**Comment by moepi2k** [comment]
sorry the above post was a bit weird. i made a new video and debug in BasePlayerCharacterEntity to see it better

-> https://gyazo.com/7d1429e3240f58b5787535f72648b3e0

here u can see after charging, the bool never go back to false.

**Comment by insthync** [comment]
Fixed in 1.76
