### ISSUE TITLE
1.75f weird desync issues

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1634]
just tested 1.75f

just check the video 
https://gyazo.com/f6a4df53af5fbc1e7cff6f8f0e8d103e

1) Jump desync in view from others. player random jump forward backwards or sidewards then after that server correct position
2) Sometimes jump not registered and synced in view of other players
3) When running on a slope an stop, sometimes in view of other player still running, but owning player stand still. In view of server player are running, you can see that stam drains
4) jitter player when go back to idle

this was reported in discord from many players already.

-> this test was with server auth movement. Same issue with non secure only the jitter thing is gone with non secure.

**Comment by DevMMORPG01** [comment]
similar to mine also. https://gyazo.com/a2d46a249b4a63b4f0f0226944879579

**Comment by insthync** [comment]
Root motion enabled?

**Comment by moepi2k** [comment]
no

**Comment by insthync** [comment]
Any components that affecting to IK, Root motion setting being used?

**Comment by moepi2k** [comment]
i just use uma, nothing custom atm, but i also seen this behaviour in default kit. lemme create a fresh project.

**Comment by moepi2k** [comment]
here with default kit.
https://gyazo.com/932475d83f51c7ff6052e08541d4e15d

you can see all behaviour. also the sync state for runing.
what i cant replicate is the jump thing with default models. (jump random in one direction and correcting after landed)

**Comment by insthync** [comment]
Send the scene to me, I will use it for testing

**Comment by insthync** [comment]
How do you test it? test it locally or run a server, how is character movement speed settings?

**Comment by moepi2k** [comment]
Its all default, i just placed some cubes and spheres into the scene. Because the thing that player state in server view is always running, happen only when stop on slopes.

**Comment by insthync** [comment]
Character is sprinting?

**Comment by moepi2k** [comment]
Happen with sprint and normal move.

But as you asked regarding test. I dont have tehe jitter issue in my maingame, there i alwys test with mysql and not sql.

Im few mins im at computer, lemme check if this makes a diffrence

**Comment by moepi2k** [comment]
this is with sql
https://gyazo.com/c36c253ab9056c634c1181f9cf25c3d4

this with mysql
https://gyazo.com/b995962bee1e34baff81dd1ee66da20f

happens with both. but what i noticed. the jitter thing happen only with WASD movement. click to move is fine.

this is aimatcursor controller
https://gyazo.com/f300e8969e3d18005cedbe58dda781eb

happens also. i just dont have the issue in my game because i dont have jump and dont have slopes. my whole maps are flat.

**Comment by insthync** [comment]
Fixed in 1.76
