### ISSUE TITLE
BUG: Swimming audio

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1635]
Sometimes swimming sounds stop playing. This happens with a 100% chance when the character jumps into the water. But sometimes this happens when the character just walks into the water. Also, after the jump, the character in the water is higher above the water. I'm guessing there were little jumps where the character would run into the water without jumping. Therefore, the sounds would sometimes not play when the character was not jumping. (look at the video)
https://youtu.be/uAmK8hNhRl0

**Comment by insthync** [comment]
Fixed, I will upload it today.

**Comment by insthync** [comment]
Fixed in 1.76b
