### ISSUE TITLE
Cant seem to warp to any maps

### ISSUE THREAD

**Issue by bdodroid** [suriyun-production/mmorpg-kit-docs#1636]
I'm running as an MMO. Everything is configured for running locally including the mysql database.

I created the map, generated the map info, attached that to the GameDatabase, added a warp dialog to my npc and added the warp to the warp database as well, added scene to my build settings and built the project.

Then I created a shortcut to the mmo.exe with 
`C:\Users\bdodr\mmo-project\Build\mmo.exe -startMapSpawnServer -spawnExePath "C:\Users\bdodr\mmo-project\Build\mmo.exe" -startCentralServer -startDatabaseServer`

Everything seems to run fine and I'm able to register, login, and spawn on map 1 but as soon as I try to warp to map 2 I either get nothing or if I try to warp to an instance I get stuck with "warping" displayed.

The server output shows both maps starting the process with map 1 getting mapPort 8000 and map 2 getting mapPort 8001, though I only see "Register Map Server: [3] [map1]" and nothing for map 2

I'm kinda at a loss here. I have no idea whats not connecting with the map server.

**Comment by bdodroid** [comment]
I just noticed that as soon as I select a created character and enter the world the server outputs
`OnPeerDisconnected peer.ConnectionId: 0 disconnectInfo.Reason: RemoteConnectionClose`
But I am still in the game and everything apart from warping is running just fine so I have no idea why it would say the connection is closed.  
If I close the server I am kicked out so the connection is still active even though the server says the remote connection was closed.

**Comment by insthync** [comment]
May I try with AnyDesk?, you can send AnyDesk info to my email: ittipon.bay@gmail.com
