### ISSUE TITLE
After command ./Build.x86_64 got this error 

### ISSUE THREAD

**Issue by charin79** [suriyun-production/mmorpg-kit-docs#1639]
Hello 
I'm stuck here, does anyone know how to fix it
![05](https://user-images.githubusercontent.com/102839729/178080918-d948da53-7dec-45ae-b6d8-bc3c2508c95e.jpg)
?

**Comment by insthync** [comment]
Please send full log file, from what I can see above, I guess that it can't connect to database

**Comment by charin79** [comment]
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9076391/Log_Database_Central_MapSpawn.log)

**Comment by charin79** [comment]
[Log_Map(Map_GuildWar) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9076420/Log_Map.Map_GuildWar.Instance.log)
[Log_Map(Map001) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9076421/Log_Map.Map001.Instance.log)
[Log_Map(Map002) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9076422/Log_Map.Map002.Instance.log)
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9076423/Log_Database_Central_MapSpawn.log)

**Comment by insthync** [comment]
Seems like it don't have any issues in these log files, can you register/login/create character and enter game?

**Comment by charin79** [comment]
it said "Cannot connet to the server"
 Changed local network address already.

**Comment by charin79** [comment]
I got it working now, but I need to keep Putty open

**Comment by charin79** [comment]
Is there a way to close Putty while keeping the server running? 
In my instruction, I was told to press Ctrl + a + d, but it just prints ^
![07](https://user-images.githubusercontent.com/102839729/178121946-563101fe-230c-432a-9fa5-09a0942db3f8.jpg)
A

**Comment by insthync** [comment]
Try googling `linux nohup` and try use it.

**Comment by charin79** [comment]
![01](https://user-images.githubusercontent.com/102839729/180891392-0101c34c-a05d-494e-a80b-1ab164314819.jpg)
