### ISSUE TITLE
Monsters with missiles

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#164]
* Monsters fire missiles in the wrong direction. I would like them to release missiles in the direction they are looking. Now the situation is when a monster shoots itself behind its back, but at the same time it looks towards the character.
[Monster missules.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3994797/Monster.missules.zip)

**Comment by insthync** [comment]
This was fixed in 1.53. If this issue still occurs, you can reopen this issue post.
