### ISSUE TITLE
version 1.76C Bug Damage Over Times

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1640]
There are 2 errors in this section
1- Skill damage repeats continuously when Duration is more than 0.
2- it shoots continuously when duration is at 0
I added the video of the 2 mistakes, I hope you can fix it, thank you

https://user-images.githubusercontent.com/54517546/178086956-be50acfa-ec21-49df-b9d2-35206de9974d.mp4

https://user-images.githubusercontent.com/54517546/178086822-d6437acc-bc3a-4f63-b4ad-5be972c043b2.mp4

**Comment by insthync** [comment]
Fixed in Try 1.76c2
