### ISSUE TITLE
Suggestion New item sharing

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1641]
When item sharing is turned on, the nearest character collects items. This is advantageous for melee fighters. If item sharing is turned off, this time tank-style characters can't get items because they can't deal enough damage to the enemy. my opinion is that the items are shared with the party in order.

**Comment by LordPhrozen** [comment]
Random distro + Need/Greed rolls for flagged items ( you can add this to specific drops, rarity items, etc)

This seems like a more flushed out option.
