### ISSUE TITLE
Unable to drag guild skills to hotbar

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1644]
seems that I can drag normal skills but not guild skills to my hotbar if its a active skills it wont let you drag it. any idea why?

**Comment by insthync** [comment]
I didn't implement guild skills for hotbar yet.

**Comment by ChaosXIII** [comment]
ah ok thought i was missing something also doesn't show cooldown on skills for other guild members.

is there a way to also restrict guild bank to certain roles? so new members cant steal out of the bank
I am willing to donate for this

thanks for your time

**Comment by ChaosXIII** [comment]
ah ok thought i was missing something I have the same problem but didn't know it wasn't there yet!
 doesn't show cooldown on skills for other guild members too 

is there a way to also restrict guild bank to certain roles? so new members cant steal out of the bank
I am willing to donate for this

thanks for your time

**Comment by molonlabe1337** [comment]
Thank you ☺️
