### ISSUE TITLE
Null error with latest version

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1648]
This error appears with the new version , when i press on start game
![Untitled](https://user-images.githubusercontent.com/71017004/178844195-1cde7526-518a-4e9d-803a-53667541cf6f.jpg) 
![dsfg](https://user-images.githubusercontent.com/71017004/178844624-aa05270f-e1a7-4335-80a2-3ea95d2b535e.jpg)

**Comment by Randolphjand** [comment]
He is gone for 2 weeks.  I have tried the newest version on a fresh install and it works so check your models maybe??

**Comment by AhmedHon** [comment]
it was fine before i updated to latest version

**Comment by Randolphjand** [comment]
I don't know how to help except maybe disable the characters in the scene and try hitting play and see if it gives any errors.  If not, then you might have to set the characters up again from scratch.  I am making the assumption that you have custom characters in the scene.

**Comment by insthync** [comment]
Can you edit codes by just add null checks like if (something != null) doSomething to avoid the error?

**Comment by insthync** [comment]
Weird, it has null checks already

**Comment by AhmedHon** [comment]
ye , i dont know why its happening

**Comment by AhmedHon** [comment]
> I don't know how to help except maybe disable the characters in the scene and try hitting play and see if it gives any errors. If not, then you might have to set the characters up again from scratch. I am making the assumption that you have custom characters in the scene.

created my character from zero again and same issue , didnt touch any core codes

**Comment by AhmedHon** [comment]
i have reimported the package again and same issue , i really don't know why it's happening :(

**Comment by AhmedHon** [comment]
Tested with clean project , same issue
![dsfg](https://user-images.githubusercontent.com/71017004/178985800-f6e919af-0522-4092-95bc-fa812f91a5d4.jpg)

**Comment by AhmedHon** [comment]
latest check , changed from playable character model to animator character model and animator character model works fine with no errors .. so something wrong with playable character  model

**Comment by insthync** [comment]
I will try Unity 2021.1 later, it might be the cause of issues

**Comment by AhmedHon** [comment]
Ok , have a good time in vacation :)

**Comment by AhmedHon** [comment]
i found what was causing my issues , was those... kit is fine <3 
![Untitled](https://user-images.githubusercontent.com/71017004/181116803-acbd9a15-f902-40a2-b264-ade19558c243.jpg)
