### ISSUE TITLE
Mouse smoothness rough and IK choppy

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1649]
the mouse smoothness is something i noticed for almost 2 years now, i remember i reported this already when i started with the kit.
i wonder why the mouse smoothness with this kit is so rough compared to assets and games

here the comparsion
you can see its almost imposible to target the mushroom. the mouse jumps are so big.
https://gyazo.com/be0a762f5da964b6dec7178890c1576d

here for example a survival kit from asset store. same likle common shooter titles. you can aim ultra smooth
https://gyazo.com/bdd42afb0b4bff411e327d055165f1b2

also the thing u can see n the first video. when IK compnent bends body. it looks really choppy
https://gyazo.com/cdc979043bb056e52d93f2009c81eed7

**Comment by moepi2k** [comment]
nvm the mouse thing is done,
never noticed the mouse sensitivity option xD maybe it was added somewhere between.

but to point 2. IK choppy thing. 
https://gyazo.com/cdc979043bb056e52d93f2009c81eed7 when i change to 0.001 * 360 for example its smoother. but then it not rotate (bend) correctly to the aim possition.

is it made like that to reduce network traffic for syncinc that field?

**Comment by insthync** [comment]
Okay
