### ISSUE TITLE
Issue regarding version 1.76d2

### ISSUE THREAD

**Issue by sdk2016** [suriyun-production/mmorpg-kit-docs#1650]
After upgrading from 1.76c4 to 1.76d2, i use git and found that lot of my files being replaced but with no difference.

![gambar](https://user-images.githubusercontent.com/20059348/178857948-c5e1fe4d-aee1-4919-9e7c-8003f0c551fd.png)

![gambar](https://user-images.githubusercontent.com/20059348/178858277-577bc0ad-2837-4893-af98-0ee528e853aa.png)

I wonder what caused this.

**Comment by insthync** [comment]
Might be becuase I uses difference device to compress a package.
