### ISSUE TITLE
Hold and release / Charge does not work as expected in non-shooter mode

### ISSUE THREAD

**Issue by tylerguitar75** [suriyun-production/mmorpg-kit-docs#1651]
Weapon attack types don't work the way you would expect.

For the charge and release, it would be best if it worked as follows: 1) charge (load) animation 2) hold animation 3) release animation

That way you can charge/load, aim, and then attack, for example with a bow, before firing. Right now all attack modes work the same, instant fire.

**Comment by moepi2k** [comment]
It also works like that with shooter controller. A pre charge animation (same like the attack one) would be best to have like u said charge(load) -> hold -> release (attack) like it is for example in genshin or zelda
