### ISSUE TITLE
Bug: Duplicate chat messages

### ISSUE THREAD

**Issue by ljars** [suriyun-production/mmorpg-kit-docs#1652]
![image](https://user-images.githubusercontent.com/72370023/179370436-c3c06ce7-5292-4947-af16-163970cb900e.png)
![image](https://user-images.githubusercontent.com/72370023/179370442-e0fcde70-baf5-4fa2-b9c1-7b347bc2dbde.png)

When you send a message in the "All" tab, this message appears twice in the "Local" tab.
This bug happens in MMO mode and in single player.

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed, you can apply the fix by yourself by edit codes in `UIChatHandler.cs`

Add `private bool aleradySetupReceiveEvent;` variable

![Screenshot_104](https://user-images.githubusercontent.com/2697550/182484460-1adf3abf-6290-4cbb-8a5a-60e41ea380f0.png)

Then in function `Awake()`, use it to `aleradySetupReceiveEvent` to check whether it is already set up a chat message received event or not. If not, then add received messages from chat history.

![Screenshot_105](https://user-images.githubusercontent.com/2697550/182484558-161f3271-362d-4d0d-85b4-9df562afa2ab.png)

Then in `SetOnClientReceiveChatMessage()` function, set `aleradySetupReceiveEvent` to `true`. And in `RemoveOnClientReceiveChatMessage()` function, set `aleradySetupReceiveEvent` to `false`.

![Screenshot_106](https://user-images.githubusercontent.com/2697550/182484724-33fe86e0-248f-41c5-aeb0-7b2d72f742c5.png)
