### ISSUE TITLE
Move to TMP

### ISSUE THREAD

**Issue by OfficialTeKniKo** [suriyun-production/mmorpg-kit-docs#1653]
Is there a way to bulk change all text to TMP?

**Comment by insthync** [comment]
You can use it, the project uses TextWrapper component as a bridge to Text or TMP Text, you just have to changes code...

Oh or you means you want to change text components in the scene to TMP?

**Comment by OfficialTeKniKo** [comment]
I would like to change the player name, guild name, etc to TMP.

**Comment by insthync** [comment]
Did you see `TextWrapper` component, set the TMP text to `TextWrapper`

**Comment by OfficialTeKniKo** [comment]
I'm sorry I don't understand what that is.

**Comment by insthync** [comment]
![Screenshot_126](https://user-images.githubusercontent.com/2697550/183531053-26c338f4-f936-4142-bb4f-7c7e75d6c9b6.png)

**Comment by Deepankar1993** [comment]
I have made a small script for quickly converting a the Legacy Text component to TMP Text
