### ISSUE TITLE
[Bug]Jump

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1657]
https://gyazo.com/3ce7b97749e68227f1eedca8312d9840

when "Do Not Change Velocity While Airbone" is checked, jump is out of sync in view of other clients.
player jump and after landed it walk to the right position.

another thing. when its unchecked, the jump behavior is very weird, it seems it stop velocity a bit. i dont know if its intended like that, but it feels weird, and it dont have this behavior when the option is checked.

so maybe better to not reduce velocity while its uncheked and let player move only a bit in air.

**Comment by insthync** [comment]
I will fix it. About when that setting turns off, its movement will follow player's WASD inputs, so you can see it stop a bit.

**Comment by moepi2k** [comment]
great thank you.
yeah when turned of it slow movement when jump. i just mean if its not better to keep movement speed lik when its turned on, just have the ability to move while in air.
because right now, it slow movespeed so hard, you cant even jump over a small gap :P

**Comment by LordPhrozen** [comment]
Perhaps air velocity should be a %  slider?
