### ISSUE TITLE
Left hand skill animation.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#166]
If we use paired weapons, we cannot assign left-hand animation to the skill. We can, but only one for all skills. We need animation for each skill for two hands, and not just for the right one.
![image](https://user-images.githubusercontent.com/47291794/71400400-a914f080-2637-11ea-982c-5613b1bf5f98.png)

**Comment by insthync** [comment]
I think it will make settings too complicates. And I have to do migration stuffs for other customer, I don't want to do it.
