### ISSUE TITLE
Question regarding hit detection

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1660]
Hi mate,

The hit detection since 174 is really good, but i noticed a weird behavior. So far i only used one capsule collider for enemies, but in this project i use hitboxes for body head and arms.

In my test i used missileDamageEntity (first part of video)
And raycast (second part of video)

As u can see. The missileDamageEntity hits only register on body, but not on arms.
The raycast works fine and always register.

https://gyazo.com/25227be070e06af27caf1d96902c4231

Is there something diffrent with raycast and missile?
I remember in 174 u changed to make hit detection client side. But the rewind function was just for raycast.

Since ray is instant projectile without balistic, its almost not useable for an arrow and can only use for guns.

If there is somwthing i can do to register missile always clientside i would really appreciate if u can lead me in the right direction.

Greeeets

**Comment by moepi2k** [comment]
ok followed the code, and it seems that missile works like before 174. there are dead end code for missile and throwables in both damage.cs and DefaultHitRegistrationManager.cs

so seems the integration for rewind is missing there.

do you planned to do this part of code? because right now missile is still almost unusable because of bad hit registration :/

**Comment by ChaosXIII** [comment]
do you have the same issue with melee? I also have similar issue when 1.76 was smooth.  my major issue is melee and projectiles it worked fine before but i dont use damageablehitbox.cs hitboxes just a capsule collider on the monster

**Comment by insthync** [comment]
@ChaosXIII You said 1.76 was good, so which version has an issue, I can't find that I changed anything related to melee hit detection.

**Comment by moepi2k** [comment]
> 

No melee is also fine since 174. Only have problems with missile

**Comment by ChaosXIII** [comment]
Sorry typo there I meant 1.74 I think my melee issue is separate it seems to be fine now I think it was the clients ping RTT I'll let you know if it still happen but I think melee is fine now because clients with issue are far away from the server

**Comment by moepi2k** [comment]
@insthync do you plan to add the rewind function also for the missile one?

**Comment by insthync** [comment]
I am thinking about how to do it, I don't think it should rewind the hitbox every frame for missiles movement.

I have to 2 plans in my mind:
1. Adjust missile movement speed at the client who fires it by latency.
2. Make the client who fires it tells the server when it hit then rewind at the server, in this way its message size will vary up to hit objects amount.

**Comment by moepi2k** [comment]
Option 2 wouldnt that bad. Let client decide what it hit since missile distance, speed and so is still server side. Just thought about hacking

**Comment by LordPhrozen** [comment]
@insthync  You have to trust the client in this situation, and let it tell the server. 

Degrading the user experience frequently,  in favor of security, I dont think is the best idea. This will result in angry players saying "I HIT HIM / NO REG" and youtube videos of arrows passing through other players. 

Building out anticheat should be on your roadmap anyways @moepi2k

**Comment by moepi2k** [comment]
I agree, and since all other stuff like missile range, speed is still serverside, it wouldnt that bad trusting the client for the hit and rewind at server
