### ISSUE TITLE
Instance Issues

### ISSUE THREAD

**Issue by ChaosXIII** [suriyun-production/mmorpg-kit-docs#1663]
Experienced this in the new version with instances
1. when the party leader dies it resets the instance and brings the entire party back to respawn.
2. If any party member dies in the dungeon they can hit respawn and resurrect in the spot they died in.

**Comment by insthync** [comment]
As I test, it is working as intended. Not sure that you test it with LAN game?

**Comment by ChaosXIII** [comment]
its in mmo weird,  if you're in a group and regular party dies not the leader the members can respawn in the place they died. 
if party leader dies it teleports everyone back to instance spawn.   i dont know what im doing wrong!
