### ISSUE TITLE
BUG: Buff timer

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1664]
The first buff has a duration of 999 seconds. The second is 30 seconds.
After activating the first buff, we see a timer of 999 seconds. 
After activating the second buff, we see a timer of 30 seconds.
After activating the first buff again, we see a 990+ seconds timer on the second buff, although its duration is only 30 seconds.
Seems like just visual bug.
https://youtu.be/ffFZB1sy_b0

**Comment by ChaosXIII** [comment]
I also have the same issue in the newest version.

**Comment by insthync** [comment]
Fixed: If you want to apply the fix by yourself, you have to change codes in UI classes. By using `Mathf.Abs()` function to find duration properly.

In `UICharacterBuff.cs`
![Screenshot_107](https://user-images.githubusercontent.com/2697550/182489176-9c57e8c7-5a56-4e33-b25b-aef221583109.png)

In `UICharacterSkill.cs`
![Screenshot_108](https://user-images.githubusercontent.com/2697550/182489314-d65d0b0c-678d-4876-92e4-025fd8f38f0f.png)

In `UICharacterItem.cs`
![Screenshot_109](https://user-images.githubusercontent.com/2697550/182489714-0afe2aaa-b23b-4588-877f-bdcb6b2a5336.png)

In `UIGuildSkill.cs`
![Screenshot_110](https://user-images.githubusercontent.com/2697550/182489828-b1983d4a-05f6-49f3-a462-fb9e0edfa13d.png)

In `UICraftingQueueItem.cs`
![Screenshot_111](https://user-images.githubusercontent.com/2697550/182489940-d9e3c19c-162c-4417-8928-1ff49066f97b.png)
