### ISSUE TITLE
Monster Issue

### ISSUE THREAD

**Issue by ChaosXIII** [suriyun-production/mmorpg-kit-docs#1665]
I didnt have this issue in older versions but in the newest, once you attack a monster everything is normal then when you run away during the fight until monster stops chasing, it will bug out and never attack you again even if set to aggressive or normal the monster will just stand there not fighting back if you attack it again or if its aggressive it wont attack you again just stands there.

**Comment by moepi2k** [comment]
Had same issue, but not chased the bug atm. But maybe something related with the new option, maxDistanceFromHome

**Comment by ChaosXIII** [comment]
> Had same issue, but not chased the bug atm. But maybe something related with the new option, maxDistanceFromHome

What setting value for max distance helped you? 
Did you resolve it?

**Comment by moepi2k** [comment]
i dont use maxDistanceFromHome. was just a test when id was implemented. but im really sure monster nocht attack because of it. when monster reach limit it get stuck.

set it to 0 and monster will attack without issue

**Comment by insthync** [comment]
Fixed: you can apply the fix by yourself by change codes in `MonsterActivityComponent.cs` to make monster moves to spawn point immediately after it is far from the spawn point.

![Screenshot_112](https://user-images.githubusercontent.com/2697550/182492585-7d355dc9-a905-4226-8d48-fff6d953dc11.png)
