### ISSUE TITLE
Found path:

### ISSUE THREAD

**Issue by charin79** [suriyun-production/mmorpg-kit-docs#1666]
![05](https://user-images.githubusercontent.com/102839729/182056299-6ed177fc-463c-4f9a-9f58-1a09a5714585.jpg)

Hi, nothing happened after that. You know what the problem is

**Comment by ChaosXIII** [comment]
make sure you followed the guide first in the documents here: https://suriyun-production.github.io/mmorpg-kit-docs/#/dedicates/digitalocean

then send a command to the server like this:
nohup /root/Build.x86_64 -startCentralServer -startMapSpawnServer -startDatabaseServer &

then it should connect if you setup right

**Comment by charin79** [comment]
![03](https://user-images.githubusercontent.com/102839729/182142069-1a8b3829-f3db-4514-b88e-182382a9d3b2.jpg)

**Comment by ChaosXIII** [comment]
You only have to run the command once then go to the game it should work in MMO. The command I gave you shows no syntax so you can exit freely without the server closing it stays on until you restart it again. 

If you use the command in the docs it will show the server syntax to be sure it worked. Make sure to restart the server between commands

**Comment by ChaosXIII** [comment]
Try 
nohup /root/Build.x86_64 -startCentralServer -startMapSpawnServer -startDatabaseServer

**Comment by ChaosXIII** [comment]
If you still need help let me know what's your discord I'll add you and walk you thru it much easier in VC

**Comment by insthync** [comment]
I will close this, Charin told me that it was fine now.
