### ISSUE TITLE
BUG: Status effect

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1668]
If we add a status effect to the "Buff" skill in "Self status effect when attacked" and "Self status effect when attacking"
![image](https://user-images.githubusercontent.com/47291794/183243085-db55af06-aef0-4173-b05c-e761f14c2a37.png)
![image](https://user-images.githubusercontent.com/47291794/183243288-fcf0b4be-ed53-455e-be2f-32d3c1dd0a28.png)
then after taking damage from monsters or attack them we will get this error.
![image](https://user-images.githubusercontent.com/47291794/183242993-839f3ec5-bc82-4cf8-9fd7-8ef58674621c.png)
If we add a status effect to the same fields on the item, then it works without errors.
If we add status effects to all other two fields for the skill, then there are no errors either and they work fine.

This error also occurs in the following case:
1. With the help of the status effect, I created the "Buff" skill for 60 seconds, which reflects damage back to the enemy for each attack on the character.
2. With the help of the status effect, I created the "Debuff" skill for 10 seconds, which restores the character's health for each attack on the cursed enemy.

Separately, these two skills work well without errors. But, if we apply them at the same time, then damage reflection causes the same error as above. Reflective damage triggers a status effect on a debuff (hp recover) and creates this error.
Also if I add all this to an item, then there are no errors.

**Comment by insthync** [comment]
I think this is ocurring because the character dies when status applied, so the collection it change, I will fix it.

**Comment by insthync** [comment]
You can fix it by changes codes in `DefaultGameplayRule.cs`

Replace `OnCharacterReceivedDamage` function codes to
```
        public override void OnCharacterReceivedDamage(BaseCharacterEntity attacker, BaseCharacterEntity damageReceiver, CombatAmountType combatAmountType, int damage, CharacterItem weapon, BaseSkill skill, short skillLevel)
        {
            float decreaseWeaponDurability;
            float decreaseShieldDurability;
            float decreaseArmorDurability;
            GetDecreaseDurabilityAmount(combatAmountType, out decreaseWeaponDurability, out decreaseShieldDurability, out decreaseArmorDurability);
            if (attacker != null)
            {
                // Decrease Weapon Durability
                DecreaseEquipWeaponsDurability(attacker, decreaseWeaponDurability);
                CharacterStats stats = attacker.GetCaches().Stats;
                // Hp Leeching, don't decrease damage receiver's Hp again
                int leechAmount = Mathf.CeilToInt(damage * stats.hpLeechRate);
                if (leechAmount != 0)
                {
                    attacker.CurrentHp += leechAmount;
                    attacker.CurrentHp = Mathf.Clamp(attacker.CurrentHp, 0, attacker.MaxHp);
                }
                // Mp Leeching
                leechAmount = Mathf.CeilToInt(damage * stats.mpLeechRate);
                if (leechAmount != 0)
                {
                    attacker.CurrentMp += leechAmount;
                    attacker.CurrentMp = Mathf.Clamp(attacker.CurrentMp, 0, attacker.MaxMp);
                    damageReceiver.CurrentMp -= leechAmount;
                    damageReceiver.CurrentMp = Mathf.Clamp(damageReceiver.CurrentMp, 0, damageReceiver.MaxMp);
                }
                // Stamina Leeching
                leechAmount = Mathf.CeilToInt(damage * stats.staminaLeechRate);
                if (leechAmount != 0)
                {
                    attacker.CurrentStamina += leechAmount;
                    attacker.CurrentStamina = Mathf.Clamp(attacker.CurrentStamina, 0, attacker.MaxStamina);
                    damageReceiver.CurrentStamina -= leechAmount;
                    damageReceiver.CurrentStamina = Mathf.Clamp(damageReceiver.CurrentStamina, 0, damageReceiver.MaxStamina);
                }
                // Applies status effects
                IEquipmentItem tempEquipmentItem;
                Buff tempBuff;
                BaseSkill tempSkill;
                EntityInfo attackerInfo = attacker.GetInfo();
                EntityInfo damageReceiverInfo = damageReceiver.GetInfo();
                // Attacker
                if (!attacker.IsDead())
                {
                    // Armors
                    foreach (CharacterItem armorItem in attacker.EquipItems)
                    {
                        tempEquipmentItem = armorItem.GetEquipmentItem();
                        ApplyStatusEffectsWhenAttacking(armorItem, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
                        if (attacker.IsDead())
                            break;
                    }
                }
                if (!attacker.IsDead())
                {
                    // Right-hand weapon
                    tempEquipmentItem = attacker.EquipWeapons.GetRightHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacking(attacker.EquipWeapons.rightHand, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
                    }
                }
                if (!attacker.IsDead())
                {
                    // Left-hand weapon / shield
                    tempEquipmentItem = attacker.EquipWeapons.GetLeftHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacking(attacker.EquipWeapons.leftHand, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
                    }
                }
                if (!attacker.IsDead())
                {
                    // Buffs/Debuffs
                    foreach (CharacterBuff characterBuff in attacker.Buffs)
                    {
                        tempBuff = characterBuff.GetBuff();
                        tempBuff.ApplySelfStatusEffectsWhenAttacking(characterBuff.level, attackerInfo, attacker);
                        tempBuff.ApplyEnemyStatusEffectsWhenAttacking(characterBuff.level, attackerInfo, damageReceiver);
                        if (attacker.IsDead())
                            break;
                    }
                }
                if (!attacker.IsDead())
                {
                    // Passive skills
                    foreach (KeyValuePair<BaseSkill, short> characterSkill in attacker.GetCaches().Skills)
                    {
                        tempSkill = characterSkill.Key;
                        if (!tempSkill.IsPassive)
                            continue;
                        tempSkill.Buff.ApplySelfStatusEffectsWhenAttacking(characterSkill.Value, attackerInfo, attacker);
                        tempSkill.Buff.ApplyEnemyStatusEffectsWhenAttacking(characterSkill.Value, attackerInfo, damageReceiver);
                        if (attacker.IsDead())
                            break;
                    }
                }
                // Damage Receiver
                if (!damageReceiver.IsDead())
                {
                    // Armors
                    foreach (CharacterItem armorItem in damageReceiver.EquipItems)
                    {
                        tempEquipmentItem = armorItem.GetEquipmentItem();
                        ApplyStatusEffectsWhenAttacked(armorItem, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
                        if (damageReceiver.IsDead())
                            break;
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Right-hand weapon
                    tempEquipmentItem = damageReceiver.EquipWeapons.GetRightHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacked(damageReceiver.EquipWeapons.rightHand, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Left-hand weapon / shield
                    tempEquipmentItem = damageReceiver.EquipWeapons.GetLeftHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacked(damageReceiver.EquipWeapons.leftHand, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Buffs/Debuffs
                    foreach (CharacterBuff characterBuff in damageReceiver.Buffs)
                    {
                        tempBuff = characterBuff.GetBuff();
                        tempBuff.ApplySelfStatusEffectsWhenAttacked(characterBuff.level, damageReceiverInfo, damageReceiver);
                        tempBuff.ApplyEnemyStatusEffectsWhenAttacked(characterBuff.level, damageReceiverInfo, attacker);
                        if (damageReceiver.IsDead())
                            break;
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Passive skills
                    foreach (KeyValuePair<BaseSkill, short> characterSkill in damageReceiver.GetCaches().Skills)
                    {
                        tempSkill = characterSkill.Key;
                        if (!tempSkill.IsPassive)
                            continue;
                        tempSkill.Buff.ApplySelfStatusEffectsWhenAttacked(characterSkill.Value, damageReceiverInfo, damageReceiver);
                        tempSkill.Buff.ApplyEnemyStatusEffectsWhenAttacked(characterSkill.Value, damageReceiverInfo, attacker);
                        if (damageReceiver.IsDead())
                            break;
                    }
                }
            }
            // Decrease Shield Durability
            DecreaseEquipShieldsDurability(damageReceiver, decreaseShieldDurability);
            // Decrease Armor Durability
            DecreaseEquipItemsDurability(damageReceiver, decreaseArmorDurability);
        }
```

**Comment by DimasjkTV** [comment]
> public override void OnCharacterReceivedDamage(BaseCharacterEntity attacker, BaseCharacterEntity damageReceiver, CombatAmountType combatAmountType, int damage, CharacterItem weapon, BaseSkill skill, short skillLevel)
>         {
>             float decreaseWeaponDurability;
>             float decreaseShieldDurability;
>             float decreaseArmorDurability;
>             GetDecreaseDurabilityAmount(combatAmountType, out decreaseWeaponDurability, out decreaseShieldDurability, out decreaseArmorDurability);
>             if (attacker != null)
>             {
>                 // Decrease Weapon Durability
>                 DecreaseEquipWeaponsDurability(attacker, decreaseWeaponDurability);
>                 CharacterStats stats = attacker.GetCaches().Stats;
>                 // Hp Leeching, don't decrease damage receiver's Hp again
>                 int leechAmount = Mathf.CeilToInt(damage * stats.hpLeechRate);
>                 if (leechAmount != 0)
>                 {
>                     attacker.CurrentHp += leechAmount;
>                     attacker.CurrentHp = Mathf.Clamp(attacker.CurrentHp, 0, attacker.MaxHp);
>                 }
>                 // Mp Leeching
>                 leechAmount = Mathf.CeilToInt(damage * stats.mpLeechRate);
>                 if (leechAmount != 0)
>                 {
>                     attacker.CurrentMp += leechAmount;
>                     attacker.CurrentMp = Mathf.Clamp(attacker.CurrentMp, 0, attacker.MaxMp);
>                     damageReceiver.CurrentMp -= leechAmount;
>                     damageReceiver.CurrentMp = Mathf.Clamp(damageReceiver.CurrentMp, 0, damageReceiver.MaxMp);
>                 }
>                 // Stamina Leeching
>                 leechAmount = Mathf.CeilToInt(damage * stats.staminaLeechRate);
>                 if (leechAmount != 0)
>                 {
>                     attacker.CurrentStamina += leechAmount;
>                     attacker.CurrentStamina = Mathf.Clamp(attacker.CurrentStamina, 0, attacker.MaxStamina);
>                     damageReceiver.CurrentStamina -= leechAmount;
>                     damageReceiver.CurrentStamina = Mathf.Clamp(damageReceiver.CurrentStamina, 0, damageReceiver.MaxStamina);
>                 }
>                 // Applies status effects
>                 IEquipmentItem tempEquipmentItem;
>                 Buff tempBuff;
>                 BaseSkill tempSkill;
>                 EntityInfo attackerInfo = attacker.GetInfo();
>                 EntityInfo damageReceiverInfo = damageReceiver.GetInfo();
>                 // Attacker
>                 if (!attacker.IsDead())
>                 {
>                     // Armors
>                     foreach (CharacterItem armorItem in attacker.EquipItems)
>                     {
>                         tempEquipmentItem = armorItem.GetEquipmentItem();
>                         ApplyStatusEffectsWhenAttacking(armorItem, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
>                         if (attacker.IsDead())
>                             break;
>                     }
>                 }
>                 if (!attacker.IsDead())
>                 {
>                     // Right-hand weapon
>                     tempEquipmentItem = attacker.EquipWeapons.GetRightHandEquipmentItem();
>                     if (tempEquipmentItem != null)
>                     {
>                         ApplyStatusEffectsWhenAttacking(attacker.EquipWeapons.rightHand, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
>                     }
>                 }
>                 if (!attacker.IsDead())
>                 {
>                     // Left-hand weapon / shield
>                     tempEquipmentItem = attacker.EquipWeapons.GetLeftHandEquipmentItem();
>                     if (tempEquipmentItem != null)
>                     {
>                         ApplyStatusEffectsWhenAttacking(attacker.EquipWeapons.leftHand, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
>                     }
>                 }
>                 if (!attacker.IsDead())
>                 {
>                     // Buffs/Debuffs
>                     foreach (CharacterBuff characterBuff in attacker.Buffs)
>                     {
>                         tempBuff = characterBuff.GetBuff();
>                         tempBuff.ApplySelfStatusEffectsWhenAttacking(characterBuff.level, attackerInfo, attacker);
>                         tempBuff.ApplyEnemyStatusEffectsWhenAttacking(characterBuff.level, attackerInfo, damageReceiver);
>                         if (attacker.IsDead())
>                             break;
>                     }
>                 }
>                 if (!attacker.IsDead())
>                 {
>                     // Passive skills
>                     foreach (KeyValuePair<BaseSkill, short> characterSkill in attacker.GetCaches().Skills)
>                     {
>                         tempSkill = characterSkill.Key;
>                         if (!tempSkill.IsPassive)
>                             continue;
>                         tempSkill.Buff.ApplySelfStatusEffectsWhenAttacking(characterSkill.Value, attackerInfo, attacker);
>                         tempSkill.Buff.ApplyEnemyStatusEffectsWhenAttacking(characterSkill.Value, attackerInfo, damageReceiver);
>                         if (attacker.IsDead())
>                             break;
>                     }
>                 }
>                 // Damage Receiver
>                 if (!damageReceiver.IsDead())
>                 {
>                     // Armors
>                     foreach (CharacterItem armorItem in damageReceiver.EquipItems)
>                     {
>                         tempEquipmentItem = armorItem.GetEquipmentItem();
>                         ApplyStatusEffectsWhenAttacked(armorItem, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
>                         if (damageReceiver.IsDead())
>                             break;
>                     }
>                 }
>                 if (!damageReceiver.IsDead())
>                 {
>                     // Right-hand weapon
>                     tempEquipmentItem = damageReceiver.EquipWeapons.GetRightHandEquipmentItem();
>                     if (tempEquipmentItem != null)
>                     {
>                         ApplyStatusEffectsWhenAttacked(damageReceiver.EquipWeapons.rightHand, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
>                     }
>                 }
>                 if (!damageReceiver.IsDead())
>                 {
>                     // Left-hand weapon / shield
>                     tempEquipmentItem = damageReceiver.EquipWeapons.GetLeftHandEquipmentItem();
>                     if (tempEquipmentItem != null)
>                     {
>                         ApplyStatusEffectsWhenAttacked(damageReceiver.EquipWeapons.leftHand, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
>                     }
>                 }
>                 if (!damageReceiver.IsDead())
>                 {
>                     // Buffs/Debuffs
>                     foreach (CharacterBuff characterBuff in damageReceiver.Buffs)
>                     {
>                         tempBuff = characterBuff.GetBuff();
>                         tempBuff.ApplySelfStatusEffectsWhenAttacked(characterBuff.level, damageReceiverInfo, damageReceiver);
>                         tempBuff.ApplyEnemyStatusEffectsWhenAttacked(characterBuff.level, damageReceiverInfo, attacker);
>                         if (damageReceiver.IsDead())
>                             break;
>                     }
>                 }
>                 if (!damageReceiver.IsDead())
>                 {
>                     // Passive skills
>                     foreach (KeyValuePair<BaseSkill, short> characterSkill in damageReceiver.GetCaches().Skills)
>                     {
>                         tempSkill = characterSkill.Key;
>                         if (!tempSkill.IsPassive)
>                             continue;
>                         tempSkill.Buff.ApplySelfStatusEffectsWhenAttacked(characterSkill.Value, damageReceiverInfo, damageReceiver);
>                         tempSkill.Buff.ApplyEnemyStatusEffectsWhenAttacked(characterSkill.Value, damageReceiverInfo, attacker);
>                         if (damageReceiver.IsDead())
>                             break;
>                     }
>                 }
>             }
>             // Decrease Shield Durability
>             DecreaseEquipShieldsDurability(damageReceiver, decreaseShieldDurability);
>             // Decrease Armor Durability
>             DecreaseEquipItemsDurability(damageReceiver, decreaseArmorDurability);
>         }

The error is still happening.

**Comment by insthync** [comment]
Which line of codes?

**Comment by DimasjkTV** [comment]
> Which line of codes?

![image](https://user-images.githubusercontent.com/47291794/183381016-3e4dc147-3a6d-47f3-991e-d204cd380ae3.png)

**Comment by DimasjkTV** [comment]
> Send me your your AnyDesk info to my email: [ittipon.bay@gmail.com](mailto:ittipon.bay@gmail.com), I want to see it.

I don't know what the term "AnyDesk". Can you explain?

**Comment by insthync** [comment]
Software like TeamViewer but it is not TeamViewer

**Comment by insthync** [comment]
Try this: 
```
        public override void OnCharacterReceivedDamage(BaseCharacterEntity attacker, BaseCharacterEntity damageReceiver, CombatAmountType combatAmountType, int damage, CharacterItem weapon, BaseSkill skill, short skillLevel)
        {
            float decreaseWeaponDurability;
            float decreaseShieldDurability;
            float decreaseArmorDurability;
            GetDecreaseDurabilityAmount(combatAmountType, out decreaseWeaponDurability, out decreaseShieldDurability, out decreaseArmorDurability);
            if (attacker != null)
            {
                // Decrease Weapon Durability
                DecreaseEquipWeaponsDurability(attacker, decreaseWeaponDurability);
                CharacterStats stats = attacker.GetCaches().Stats;
                // Hp Leeching, don't decrease damage receiver's Hp again
                int leechAmount = Mathf.CeilToInt(damage * stats.hpLeechRate);
                if (leechAmount != 0)
                {
                    attacker.CurrentHp += leechAmount;
                    attacker.CurrentHp = Mathf.Clamp(attacker.CurrentHp, 0, attacker.MaxHp);
                }
                // Mp Leeching
                leechAmount = Mathf.CeilToInt(damage * stats.mpLeechRate);
                if (leechAmount != 0)
                {
                    attacker.CurrentMp += leechAmount;
                    attacker.CurrentMp = Mathf.Clamp(attacker.CurrentMp, 0, attacker.MaxMp);
                    damageReceiver.CurrentMp -= leechAmount;
                    damageReceiver.CurrentMp = Mathf.Clamp(damageReceiver.CurrentMp, 0, damageReceiver.MaxMp);
                }
                // Stamina Leeching
                leechAmount = Mathf.CeilToInt(damage * stats.staminaLeechRate);
                if (leechAmount != 0)
                {
                    attacker.CurrentStamina += leechAmount;
                    attacker.CurrentStamina = Mathf.Clamp(attacker.CurrentStamina, 0, attacker.MaxStamina);
                    damageReceiver.CurrentStamina -= leechAmount;
                    damageReceiver.CurrentStamina = Mathf.Clamp(damageReceiver.CurrentStamina, 0, damageReceiver.MaxStamina);
                }
                // Applies status effects
                int i = 0;
                IEquipmentItem tempEquipmentItem;
                CharacterItem tempCharacterItem;
                CharacterBuff tempCharacterBuff;
                Buff tempBuff;
                BaseSkill tempSkill;
                EntityInfo attackerInfo = attacker.GetInfo();
                EntityInfo damageReceiverInfo = damageReceiver.GetInfo();
                // Attacker
                if (!attacker.IsDead())
                {
                    // Armors
                    for (i = 0; i < attacker.EquipItems.Count; ++i)
                    {
                        tempCharacterItem = attacker.EquipItems[i];
                        tempEquipmentItem = tempCharacterItem.GetEquipmentItem();
                        ApplyStatusEffectsWhenAttacking(tempCharacterItem, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
                        if (attacker.IsDead())
                            break;
                    }
                }
                if (!attacker.IsDead())
                {
                    // Right-hand weapon
                    tempEquipmentItem = attacker.EquipWeapons.GetRightHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacking(attacker.EquipWeapons.rightHand, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
                    }
                }
                if (!attacker.IsDead())
                {
                    // Left-hand weapon / shield
                    tempEquipmentItem = attacker.EquipWeapons.GetLeftHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacking(attacker.EquipWeapons.leftHand, tempEquipmentItem, attackerInfo, attacker, damageReceiver);
                    }
                }
                if (!attacker.IsDead())
                {
                    // Buffs/Debuffs
                    for (i = 0; i < attacker.Buffs.Count; ++i)
                    {
                        tempCharacterBuff = attacker.Buffs[i];
                        tempBuff = tempCharacterBuff.GetBuff();
                        tempBuff.ApplySelfStatusEffectsWhenAttacking(tempCharacterBuff.level, attackerInfo, attacker);
                        tempBuff.ApplyEnemyStatusEffectsWhenAttacking(tempCharacterBuff.level, attackerInfo, damageReceiver);
                        if (attacker.IsDead())
                            break;
                    }
                }
                if (!attacker.IsDead())
                {
                    // Passive skills
                    foreach (KeyValuePair<BaseSkill, short> characterSkill in attacker.GetCaches().Skills)
                    {
                        tempSkill = characterSkill.Key;
                        if (!tempSkill.IsPassive)
                            continue;
                        tempSkill.Buff.ApplySelfStatusEffectsWhenAttacking(characterSkill.Value, attackerInfo, attacker);
                        tempSkill.Buff.ApplyEnemyStatusEffectsWhenAttacking(characterSkill.Value, attackerInfo, damageReceiver);
                        if (attacker.IsDead())
                            break;
                    }
                }
                // Damage Receiver
                if (!damageReceiver.IsDead())
                {
                    // Armors
                    for (i = 0; i < damageReceiver.EquipItems.Count; ++i)
                    {
                        tempCharacterItem = damageReceiver.EquipItems[i];
                        tempEquipmentItem = tempCharacterItem.GetEquipmentItem();
                        ApplyStatusEffectsWhenAttacked(tempCharacterItem, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
                        if (damageReceiver.IsDead())
                            break;
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Right-hand weapon
                    tempEquipmentItem = damageReceiver.EquipWeapons.GetRightHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacked(damageReceiver.EquipWeapons.rightHand, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Left-hand weapon / shield
                    tempEquipmentItem = damageReceiver.EquipWeapons.GetLeftHandEquipmentItem();
                    if (tempEquipmentItem != null)
                    {
                        ApplyStatusEffectsWhenAttacked(damageReceiver.EquipWeapons.leftHand, tempEquipmentItem, damageReceiverInfo, attacker, damageReceiver);
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Buffs/Debuffs
                    for (i = 0; i < damageReceiver.Buffs.Count; ++i)
                    {
                        tempCharacterBuff = damageReceiver.Buffs[i];
                        tempBuff = tempCharacterBuff.GetBuff();
                        tempBuff.ApplySelfStatusEffectsWhenAttacked(tempCharacterBuff.level, damageReceiverInfo, damageReceiver);
                        tempBuff.ApplyEnemyStatusEffectsWhenAttacked(tempCharacterBuff.level, damageReceiverInfo, attacker);
                        if (damageReceiver.IsDead())
                            break;
                    }
                }
                if (!damageReceiver.IsDead())
                {
                    // Passive skills
                    foreach (KeyValuePair<BaseSkill, short> characterSkill in damageReceiver.GetCaches().Skills)
                    {
                        tempSkill = characterSkill.Key;
                        if (!tempSkill.IsPassive)
                            continue;
                        tempSkill.Buff.ApplySelfStatusEffectsWhenAttacked(characterSkill.Value, damageReceiverInfo, damageReceiver);
                        tempSkill.Buff.ApplyEnemyStatusEffectsWhenAttacked(characterSkill.Value, damageReceiverInfo, attacker);
                        if (damageReceiver.IsDead())
                            break;
                    }
                }
            }
            // Decrease Shield Durability
            DecreaseEquipShieldsDurability(damageReceiver, decreaseShieldDurability);
            // Decrease Armor Durability
            DecreaseEquipItemsDurability(damageReceiver, decreaseArmorDurability);
        }
```

**Comment by DimasjkTV** [comment]
Seems like it works. Thank you!
