### ISSUE TITLE
Character position not sync MMO2D

### ISSUE THREAD

**Issue by marcos1991** [suriyun-production/mmorpg-kit-docs#167]
Hello, I am having this problem the character does not sync position follows the attached image, any ideas why this is occurring?

![nosync](https://user-images.githubusercontent.com/40783613/71449089-ec995880-2724-11ea-8852-9234e6510d3b.png)

**Comment by insthync** [comment]
Fixed, please wait for next update

**Comment by insthync** [comment]
This fix included in 1.52

**Comment by marcos1991** [comment]
same problem on 1.52

**Comment by insthync** [comment]
Please attach image of `player character entity`, `character model 2d`, `entity movement` settings, I want to find out what is wrong.

**Comment by marcos1991** [comment]
![image](https://user-images.githubusercontent.com/40783613/72668184-d7050f00-3a02-11ea-9adb-306435e0cf23.png)
I don't use the 2d character model because I can't insert my animations I don't use spritesheet

**Comment by insthync** [comment]
Try Animator Character Model 2D

**Comment by marcos1991** [comment]
same problem :/

**Comment by insthync** [comment]
Okay, I will send the fix package today

**Comment by insthync** [comment]
[UnityMultiplayerARPG_1.52-patch-fix-animator-character-model-2d.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4082330/UnityMultiplayerARPG_1.52-patch-fix-animator-character-model-2d.zip)

Import the package inside the zip.

**Comment by insthync** [comment]
This is also fixed in 1.52b, I will close this issue post. If this problem still occurs, you can reopen it.

**Comment by marcos1991** [comment]
hi continues no sync position :( i'm using latest version

**Comment by insthync** [comment]
As I try, it's still working for me.

**Comment by insthync** [comment]
Show me your LiteNetLibTransform and PlayerCharacterEntity settings, please.

**Comment by marcos1991** [comment]
![litenetlibtransform](https://user-images.githubusercontent.com/40783613/76001811-6ea3bb80-5ee4-11ea-9a3d-2626a6a17a0d.png)
![character01](https://user-images.githubusercontent.com/40783613/76001821-72cfd900-5ee4-11ea-97b3-5f2bb489abf4.png)
![character02](https://user-images.githubusercontent.com/40783613/76001824-74999c80-5ee4-11ea-846c-29c5339225b1.png)
![character03](https://user-images.githubusercontent.com/40783613/76001828-76fbf680-5ee4-11ea-80e3-60dc158ad153.png)

**Comment by insthync** [comment]
Not sure that character can move but it is not updating to others? Or it can't move?

**Comment by marcos1991** [comment]
the user moves only does not synchronize the position. for example one is turned to the right but in the other client it only shows the front of the character.

**Comment by insthync** [comment]
Try set LiteNetLibTransform setting like this: 
![Screenshot_52](https://user-images.githubusercontent.com/2697550/76004014-6dea4400-5f3b-11ea-97a4-c122d3600af3.png)

**Comment by marcos1991** [comment]
no work
Video
https://drive.google.com/open?id=10YGYg7rfqmsTurBvEptLZOWjgbFqxcDi

**Comment by insthync** [comment]
How about monster? are their postion and look direction syncing correctly ?

**Comment by marcos1991** [comment]
yes the monsters are synchronizing.

**Comment by insthync** [comment]
You use `RigidBodyEntityMovement2D` as entity movement component right?

**Comment by insthync** [comment]
And which character model component are you using? `CharacterModel2D` or `AnimatorCharacterModel2D`

**Comment by marcos1991** [comment]
AnimatorCharacterModel2D

**Comment by insthync** [comment]
Are you using `RigidBodyEntityMovement2D`?, No error in console?

**Comment by insthync** [comment]
You may help me to figure out by add codes to show values to `AnimatorCharacterModel2D` function `PlayMoveAnimation()` to line  238

```
                Debug.Log(movementState +" " + direction2D.x + " " + direction2D.y);
```

Then take console log screen shot while playing. So I can see that values are correct or not.
