### ISSUE TITLE
[Bug]DamageHitEffect

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1670]
When use a Skill with DamageOverTime

the DamageHitEffect https://gyazo.com/3eeda7847e082ffa09c5fdc0b6cb597f
repeats on every damage tick. 

for the loop there is the field https://gyazo.com/13597600eea985f974c2813932cdf1ff

it worked always, i dont know on what version it broke. but i assume a 1.72+

**Comment by insthync** [comment]
To fix it you have to add a parameter to `ReceivedDamage` function in `DamageableEntity` 

![Screenshot_122](https://user-images.githubusercontent.com/2697550/183348456-a7201936-d0f8-4189-8dc7-4eb12635d2da.png)

Then in `BaseCharacterEntity_DamageFunctions`
![Screenshot_123](https://user-images.githubusercontent.com/2697550/183348933-ce54b851-55ac-4458-90ed-80269f629b45.png)

The problem occurring after this change: https://github.com/suriyun-production/mmorpg-kit-docs/issues/1629

**Comment by insthync** [comment]
Then in `CharacterRecoveryData`

![Screenshot_124](https://user-images.githubusercontent.com/2697550/183349706-4a589236-bb1e-4581-95c7-1c5fd7fb47ce.png)

**Comment by moepi2k** [comment]
Greaaat, thank u very much for the fast answer 👌
