### ISSUE TITLE
Invalid data with new character

### ISSUE THREAD

**Issue by charin79** [suriyun-production/mmorpg-kit-docs#1671]
Hi 
I got an errors message is said" fail to create agent bacuase there is no valid Navmesh. 
I would like to know how I can fix this
![12](https://user-images.githubusercontent.com/102839729/183315777-5481542b-efda-4506-bf3a-d8b3e9c0216f.jpg)
.

**Comment by insthync** [comment]
You can ignore that warning messages, it appearing because there is no baked nav mesh in the character management scene. Avoid Invalid data error, did you try to rebuild/reupload/ and restart the server after add new character data?

**Comment by charin79** [comment]
Yes I rebuild/reupload now Im testing on new server. got this error.
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9278215/Log_Database_Central_MapSpawn.log)

**Comment by insthync** [comment]
If you planned to host MySQL in the same device with other game-servers, you can use `localhost` instead of `142.93.50.111`.

If you still want to connect to `142.93.50.111` you have to create a new MySQL user or change created user to allow to connect, you may try googling "mysql grant remote access"

**Comment by charin79** [comment]
Still getting the error with localhos
![08](https://user-images.githubusercontent.com/102839729/183389413-6b893405-87c6-44af-a616-524308b3b219.jpg)
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9280713/Log_Database_Central_MapSpawn.log)

**Comment by insthync** [comment]
It seems like the MySQL error is gone, the log file won't be rewritten, it will continue writting the old one so you have to look at the date/time.

**Comment by charin79** [comment]
The new MySQL user has been created and is now working, so you can close this issue
