### ISSUE TITLE
multiple warp portal entity

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1672]
is there a way I can add more warp portal entitys to database with this method?
https://gyazo.com/ed85611927702366019b929211f46b1b

I really dont want to use the other database method as its confusing.

**Comment by insthync** [comment]
How you add warp portal entities nowsday?

**Comment by insthync** [comment]
It has only one kind of warp portal database, so I don't know what are other databases?

**Comment by molonlabe1337** [comment]
So I didn't know I needed them added to the game instance I'm using a warp portal entity but none of my portals are in the database and they work just with warp portal entity. I thought I needed to add them to the game Instance

**Comment by molonlabe1337** [comment]
I just have the default warp portal entity there and there's a different prefab for each portal it seems to work fine but not sure if it will cause issues

**Comment by insthync** [comment]
![Screenshot_120](https://user-images.githubusercontent.com/2697550/183323045-21fc19d6-1778-4507-b4ce-42f7228c1140.png)

You means that you are adding warp portal to this database?

**Comment by molonlabe1337** [comment]
Yes so can I just use warp portal entity by itself instead of database? Even multiple entity?

**Comment by insthync** [comment]
Very confuse, which database ?

You actaully can put warp entity in your game scenes and it can be any kind of game object but it must have warp portal entity attached (with other required components)

**Comment by insthync** [comment]
Game Instance, Warp Portal Database ?

**Comment by molonlabe1337** [comment]
> Very confuse, which database ?
> 
> You actaully can put warp entity in your game scenes and it can be any kind of game object but it must have warp portal entity attached (with other required components)

Sorry for any confusion let me retry
My question is since I put multiple portal entity do I need to put them all into game instance here? I can only put 1 prefab 
https://gyazo.com/ed85611927702366019b929211f46b1b

**Comment by insthync** [comment]
No, in the game instance is for default prefab when instantiating warp portal entities that set in `Warp Portal Database`.

**Comment by molonlabe1337** [comment]
Thanks
