### ISSUE TITLE
SUG: Exclude Items from being dropped (map info)

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1673]
This is a suggestion to add an exclusion list for `items`, `armour types` and `weapon types` (3 lists) on the map data so that if `drop equipped items` is enabled, certain items, armour types and weapon types will not be dropped on death.

![image](https://user-images.githubusercontent.com/48354382/183408906-0808876a-8a87-4db9-a901-69071d13f815.png)

**Comment by BJPickles** [comment]
This is rather important for full loot games where quest items may be lost on death etc.

**Comment by BJPickles** [comment]
Further to add to this quest items are being dropped on death as well.

**Comment by BJPickles** [comment]
Any news on this?

**Comment by insthync** [comment]
Added in `1.77`
