### ISSUE TITLE
[Bug]Left Hand Wielding Weapon Animations not working

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1674]
When the left-hand weapon type is equipped (both weapon types set as `dual wield`), no override animations are played.
Is there a specific way to setup the animations?

I've tested the left-hand weapon type set as `off-hand only` but still no animations are played when the left hand weapon is equipped.

**Comment by insthync** [comment]
Did you try to setup this? (in Playable Character Model component)

![Screenshot_125](https://user-images.githubusercontent.com/2697550/183530663-7ee3df42-909a-42fd-a96e-2e2dc6786f1c.png)

**Comment by BJPickles** [comment]
Yes, the weapon type was exclusively in the `left hand wielding weapon animation` list.

I equipped the weapon and non of the animations played, only the default ones.

**Comment by insthync** [comment]
Can I try on your device?, you can send your AnyDesk info to my email: ittipon.bay@gmail.com

**Comment by BJPickles** [comment]
> Can I try on your device?, you can send your AnyDesk info to my email: [ittipon.bay@gmail.com](mailto:ittipon.bay@gmail.com)

I've emailed you :)

**Comment by BJPickles** [comment]
Suri has fixed this, thanks again!
