### ISSUE TITLE
[BUG] Trigger colliders increases hitbox size

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1677]
When a trigger collider is on the root prefab of the Human_CC - the hitbox scales to the size of trigger collider.

There are times when a collider is necessary on the root for example using the Dissonance integration.

As you can see the sphere collider (trigger) increases the hitbox to size 12.

![image](https://user-images.githubusercontent.com/48354382/183727753-41f8cd03-f72d-46ad-ab06-d58904e44022.png)

![image](https://user-images.githubusercontent.com/48354382/183727839-4203a462-4185-44cb-ba76-81466fc5dca2.png)

**Comment by insthync** [comment]
It is intended to work like that. If you don't want it to create hit box automatically, you have to create hitbox by yourself by adding a child with hitbox component, trigger collider and kinematic rigidbody .

**Comment by BJPickles** [comment]
Ah okay, I'll give that a try! Thanks!

**Comment by BJPickles** [comment]
> It is intended to work like that. If you don't want it to create hit box automatically, you have to create hitbox by yourself by adding a child with hitbox component, trigger collider and kinematic rigidbody .

This worked perfectly. Thank you!
