### ISSUE TITLE
BUG: Dissonance doesn't reconnect on map change

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1678]
Dissonance integration works great and I'm really enjoying it, thank you for making the integration. Absolutely love it!

I think I've discovered an odd bug. Should a player leave the current map server, when they rejoin the map, existing players won't re-connect with them and they won't be able to speak.

I.E:
- `Player A` is talking to `Player B`
- `Player B` enters a warp portal and leaves the map.
- `Player B` comes back and tries to talk with `Player A`.
- `Player A` cannot hear `Player B`.
- `Player A` has to log out and log back in.

It seems Dissonance only connects to the global room on the map the player spawns in, but disconnects when the map is changed.

The only way I've found to reconnect the players is for `Player A` to log out and then log back in before being able to hear `Player B`, which is weird.

Here is my Dissonance setup:

**Player Prefab**:
![image](https://user-images.githubusercontent.com/48354382/183902836-1e88e6b3-c4a3-4fe9-a7ca-31478c3f3cc0.png)

**DoNotDestroy**:
![image](https://user-images.githubusercontent.com/48354382/183902979-6a0440fc-a2b9-4839-88ec-476de12f924b.png)

![image](https://user-images.githubusercontent.com/48354382/183903026-b3f85ea7-da9a-4c6b-8d19-d34f9479403b.png)

**Comment by moepi2k** [comment]
I had same issue, but i thought my setup was wrong :)

**Comment by BJPickles** [comment]
Just a follow up on this. Any news?

**Comment by insthync** [comment]
I will make a project to show you how dissonance should be implemented later.

**Comment by BJPickles** [comment]
> I will make a project to show you how dissonance should be implemented later.

Thanks. This is my current setup.
I've setup the hitboxes manually because otherwise the Dissonance sphere trigger increases the hitbox to a massive size (lol).

So I've create a child object for Dissonance, but left the main script on the parent character object.
Unfortunately when a player logs in, it's fairly random which players can hear each other. For example, `Player C` can only hear `Player A`.   Likewise `Player B` cannot hear anyone. `Player A` can hear `Player B`. It's a bit odd. Sometimes it changes when players log out and log back in, sometimes it doesn't.

![InkedUnity_G4oImZbrID](https://user-images.githubusercontent.com/48354382/190910921-dbb09160-3a08-4949-a767-b64b04e76b7e.jpg)

![InkedUnity_B5xPbdH81L](https://user-images.githubusercontent.com/48354382/190910931-9bceac5d-e699-4bee-9582-a120ba94b4ed.jpg)

![InkedUnity_E6Fg4Sly0h](https://user-images.githubusercontent.com/48354382/190910938-89e6dcd9-d9ea-4dfd-b49e-f6aa74473a94.jpg)

![InkedUnity_I8UwQ6FImo](https://user-images.githubusercontent.com/48354382/190910941-9d7fa7aa-477d-454e-9530-b5a049aa6ace.jpg)
