### ISSUE TITLE
[BUG] Turn Forward While Doing Action (Shooter)

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1679]
On the shooter controller -> TPS settings, I've noticed that the bool `Turn Forward While Doing Action` doesn't work. When it's turned `off`, when the player presses the `action` button, the player snaps forward on both `action` and `attack`.

Is there a way to disable this for both `action` and `attack`?

**VIDEO**: https://i.imgur.com/eQf4mr5.mp4

**VIDEO 2**: https://i.imgur.com/fDtAyAN.mp4

![image](https://user-images.githubusercontent.com/48354382/183903850-a34e7d2c-4ba6-4587-86a7-3abfbfc6a687.png)

**Comment by insthync** [comment]
Try change codes in `ShooterPlayerCharacterController` -> `SetTargetLookDirectionWhileDoingAction` function

```
Vector3 doActionLookDirection = turnForwardWhileDoingAction ? cameraForward : (moveLookDirection.sqrMagnitude > 0f ? moveLookDirection : targetLookDirection);
```

![Screenshot_144](https://user-images.githubusercontent.com/2697550/183927698-76efae04-6c93-48b0-80b5-257286aa3396.png)

**Comment by BJPickles** [comment]
Can confirm worked! Thanks for the quick response!
