### ISSUE TITLE
Multiple Players in Vehicles

### ISSUE THREAD

**Issue by Skillerdk5** [suriyun-production/mmorpg-kit-docs#168]
Could be awesome that you can be more than one player in a vehicle

**Comment by Koodetat** [comment]
it was planned a few months ago, I don't know if it is still planned.  As well as the possibility of persistent vehicles (which do not disappear). that would be really good!

**Comment by Skillerdk5** [comment]
i agree Koodetat :D

**Comment by insthync** [comment]
Will add it to version 1.53

**Comment by insthync** [comment]
Added to 1.52c
