### ISSUE TITLE
BUG: Dual weapon damage stat text displaing

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1680]
For example, we have two one-handed weapons with 3-6 damage. Equip the first weapon, we will see 3-6 damage for one hand. Equip the second weapon, we will see 6-12 damage for the first hand and 6-12 damage for the left hand. Although the character still deals 3-6 damage with each hand.
Just a visual bug.
With one weapon 
![image](https://user-images.githubusercontent.com/47291794/184029962-9d134774-5d65-491e-b8e1-07ec08e54096.png)

With two weapons
![image](https://user-images.githubusercontent.com/47291794/184029998-47d5a075-6f89-4a98-a086-72023f67b320.png)

But should:
Damage for first hand - 3-6
Damage for second hand - 3-6

**Comment by insthync** [comment]
To fix it you have to replace codes in `UICharacter.cs` -> `UpdateData` function

Find
```
            Dictionary<DamageElement, MinMaxFloat> rightHandDamages = rightHandWeapon != null ? GameDataHelpers.CombineDamages(cacheDamages, rightHandItem.GetDamageAmount(Data)) : null;
            Dictionary<DamageElement, MinMaxFloat> leftHandDamages = leftHandWeapon != null ? GameDataHelpers.CombineDamages(cacheDamages, leftHandItem.GetDamageAmount(Data)) : null;
```

Replace to 
```
            Dictionary<DamageElement, MinMaxFloat> rightHandDamages = null;
            Dictionary<DamageElement, MinMaxFloat> leftHandDamages = null;
            if (rightHandWeapon != null)
            {
                rightHandDamages = GameDataHelpers.CombineDamages(null, cacheDamages);
                rightHandDamages = GameDataHelpers.CombineDamages(rightHandDamages, rightHandItem.GetDamageAmount(Data));
            }
            if (leftHandWeapon != null)
            {
                leftHandDamages = GameDataHelpers.CombineDamages(null, cacheDamages);
                leftHandDamages = GameDataHelpers.CombineDamages(leftHandDamages, leftHandItem.GetDamageAmount(Data));
            }
```

**Comment by DimasjkTV** [comment]
Works. Thank you!
