### ISSUE TITLE
Import with Unity 2021.3.7f1 erros 

### ISSUE THREAD

**Issue by charin79** [suriyun-production/mmorpg-kit-docs#1681]
Hi 
I am trying to import with Unity version 2021.3.7f1, but I am getting the following errors. Is there a way to fix it? This is a brand new installation. 
![01](https://user-images.githubusercontent.com/102839729/184544108-791ad9d1-bc58-4777-82aa-301124b0c08e.jpg)

**Comment by Randolphjand** [comment]
It tells you in the docs what to do if you are using 2021.

**Comment by charin79** [comment]
Ahh Thanks.
Close
