### ISSUE TITLE
BUG: "living" corpses

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1682]
After the target dies, the character continues to attack the monster's corpse. In this case, the character does not turn towards the corpse.
Video:
https://youtu.be/pTv_geamcCI
My controller settings:
![image](https://user-images.githubusercontent.com/47291794/184550054-10a3f66b-703b-47a9-bf47-c38d5da1949d.png)

**Comment by insthync** [comment]
Fix it by changing codes in `BaseCharacterEntity` -> `GetAttackAimPosition`

![Screenshot_156](https://user-images.githubusercontent.com/2697550/184759793-896ccf9e-c2cb-40d5-a8c0-90ab95cd476a.png)

```
if (!(targetEntity as DamageableEntity).IsDead())
```

**Comment by DimasjkTV** [comment]
Thank you. Works!
