### ISSUE TITLE
(SUG) Mount Stats

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1685]
I suggest adding stats while on a mount as currently you can only increase the speed of your mount.

Thanks.

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/185271853-d9333a93-17d8-43b1-a2c6-343c50efd90a.png)

**Comment by Blunnyn** [comment]
i mean something like that
![image](https://user-images.githubusercontent.com/45702662/185272411-8c7d6539-c462-4201-a468-36b4876d359a.png)

**Comment by Callepo** [comment]
but there already is?
![image](https://user-images.githubusercontent.com/7702658/186036131-dea62070-b4cc-46bd-84a2-ea95c6f78e41.png)

**Comment by Blunnyn** [comment]
But that is in the monsters, in the mounts it is this way

![image](https://user-images.githubusercontent.com/45702662/186292966-6117f717-6d05-4437-abfa-ab8871d29257.png)

![image](https://user-images.githubusercontent.com/45702662/186293195-2b95e1ec-3733-4714-a320-6e1d5322e520.png)

**Comment by Callepo** [comment]
yea i understand, u could have mounts be spawned from skills, which gives u the stats and everything like pic above, but its not gonna stay, its gonna be a buff only. 

But dont think the player should even take dmg when on mount/ vehicle to need passives etc, which i think thats why mount have only armor , resistance, hp etc for itself. but in the kit player still takes dmg.. which is weird..

**Comment by insthync** [comment]
Did it.

About players can receive damage while riding it is up to how vehicle entity hitboxes were set up.

**Comment by insthync** [comment]
Added in 1.77
