### ISSUE TITLE
how to increase npc and player interaction range?

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1686]
i need the NPC and players to be able to be interact at a bigger range. I increased the trigger collider on the NPC but not sure if its working right to talk to the npc from a bigger range. I need interacting with players bigger range too so you dont have to hug people to trade and stuff. 

is there a setting im missing? 

thanks for the help

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/185271664-6b3da397-da1f-4dae-9e79-6c32b5b7df77.png)

gameinstance

**Comment by molonlabe1337** [comment]
thank you
