### ISSUE TITLE
Player Cloning Bug

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1687]
In MMO mode once you select your character while the game is loading into the first scene about 90% just ALT+F4 out of the game close it completely dont let it load (this happened when a player crashed) then reload the game join the server as normal and there will be 2 of your character and other players can take control of the clone if they stand on top of it. Very weird! I was able to reproduce in a default setting.

**Comment by molonlabe1337** [comment]
newest version

**Comment by molonlabe1337** [comment]
if you make a bunch of clones it makes everyone lagg out on the server,  not sure why this is happening

**Comment by insthync** [comment]
Try this changes https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/c633ee3503dcff676d34caa6a352f8b97a61c04e

**Comment by molonlabe1337** [comment]
thanks for this, I tried but got errors in console think i did the structure of coding wrong by copy pasting it, is there anyway you send send the script instead of me making the changes? i screwed it up lol sorry im still a noob. I appreciate your time and will send you a ko-fi

**Comment by insthync** [comment]
Copy-paste this file: https://raw.githubusercontent.com/insthync/UnityMultiplayerARPG_MMO/c633ee3503dcff676d34caa6a352f8b97a61c04e/Scripts/MMOGame/Networking/Map/MapNetworkManager.cs

**Comment by insthync** [comment]
Fixed in 1.77
