### ISSUE TITLE
Character And Item dupe

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1689]
I'm going to show you a simple dupe. I enter the game with the same character and transfer my items :) latest kit
The same process is also available in the fresh kit. The loading screen is triggered at time
https://www.youtube.com/watch?v=JM0hBga6eak

**Comment by insthync** [comment]
Fixed, you may try update MMO codes from https://github.com/insthync/UnityMultiplayerARPG_MMO 

or wait for a new version.

**Comment by insthync** [comment]
Fixed in 1.77
