### ISSUE TITLE
[PAID REQUEST]: Buff/Bonus Settings: [Jump height], [Fall speed/gravity] & [Fall damage modifiers]

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1691]
It would be useful to have a few more buff/bonus settings added.

## FALL SPEED / GRAVITY
This is to change how quickly the player falls. 
**EXAMPLE**: A potion that slows your fall speed by 75% only for the duration of the potion (5 seconds), acting similarly to HP potions.

---

## JUMP HEIGHT
Changing jump height is useful for items, or buffs where temporary increase in jump height is necessary. I.e parkour challenges, quests etc.
**EXAMPLE**: An item - boots - that increases jump height by 75%.

---

## FALL DAMAGE MODIFIERS
This is to toggle when and how fall damage is applied. For example:

1. Being able to `toggle fall damage`. I.e Have a potion that turns OFF fall damage only for the duration of the potion.

2. Having a `Fall damage multiplier` on an item to either increase the amount of fall damage, or reduce it. I.e a cape that reduces fall damage by 50%. Another example could be strong armour, but increases fall damage by 75%. (Negative buff).

3. `Fall damage range` - Having items that buff fall damage min/max. I.e a ring that increases the maximum fall damage from `25` -> `40`, but decreases the minimum from `10` -> `5`.

---

And of course these could all be mixed together and included in random/buffs/debuffs etc.

**Comment by BJPickles** [comment]
Updated to paid request.

**Comment by insthync** [comment]
I'd like to charge for those features 15 USD.

**Comment by BJPickles** [comment]
I've sent $20 as a thank you for your hardwork and dedication!
