### ISSUE TITLE
BUG: Fall damage is applied after exiting water

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1694]
1.76D2

> - Drop player from a large height into water. When player swims around, it's fine.
> - When player goes to exit the water, the fall damage is immediately applied upon contact with the ground.

Can be replicated in offline/singleplayer mode.

**Comment by insthync** [comment]
![Screenshot_43](https://user-images.githubusercontent.com/2697550/189474796-e5cf4597-9d63-4939-a731-e62f12f24411.png)

Fix by adding these codes

```
lastGrounded = MovementState.Has(MovementState.IsGrounded) || MovementState.Has(MovementState.IsUnderWater);
```

**Comment by BJPickles** [comment]
Note to self: `BaseCharacterEntity`
Worked a treat, thanks for the quick fix!

**Comment by shubhank008** [comment]
@insthync sorry for replying to a closed issue but do you think it will be possible in one of the future updates to add something like a "damage source" when receive damage ?  
Anything generic like player, monster, water, fall, etc. would do  

It will make debugging a lot easier to know what is causing damage by just adding a debugLog
