### ISSUE TITLE
Pool system bug 

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1695]
There is a bug in the pool system. When the player uses a skill, it works fine as long as it is in the pool, but when the pool is empty (pool size 5, triggered after we use 5 skills), it uses it over the coordinates we used before. Thus, the user can damage any area.
https://www.youtube.com/watch?v=bNy7p3ozbDM

**Comment by insthync** [comment]
![Screenshot_42](https://user-images.githubusercontent.com/2697550/189474503-851542b1-49fe-422b-ba13-150c3b0213e9.png)

Fix it by add this codes

**Comment by BarzoStrike** [comment]
Everything looks good now

**Comment by BarzoStrike** [comment]
same thing there is "AreaBuffEntity". When we use buff, the field repeats the old place. I would appreciate if you fix it in the new update.
