### ISSUE TITLE
how can i add another currency?

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#17]
how can i add another currency?
for example i want drop from boss another currency, not gold example crystals and npc can change it

**Comment by 1isenok** [comment]
![image](https://user-images.githubusercontent.com/48797909/54901567-93e12900-4f22-11e9-881d-4b822207749e.png)

for example, shop need only gold currency, i need enother how can i add this ?

**Comment by insthync** [comment]
For now, you will have to changes codes (in many source files). I will show example later

**Comment by 1isenok** [comment]
thank you very much i will wait

**Comment by 1isenok** [comment]
can you ask me how a can do it? or example

**Comment by insthync** [comment]
In the version 1.61, I've added currency game data, now custom currencies can be received by quests and can be used to buy items from NPCs, some info (https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/146-currency)
