### ISSUE TITLE
Mobile Сanvas

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#170]
Any ideas why items are not drop from inventory with "UIItemIcon_WithDragHandler" in Mobile Canvas? But if i create a mobile client and run the game on the phone, then items drop from inventory. 
* [Mobile canvas.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4015470/Mobile.canvas.zip)

But if i create a mobile client and run the game on the phone, then items drop from inventory. But there is a problem. If I move an item between the slots, the item drops Can see on video.
* [Mobile Item Drop.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4015491/Mobile.Item.Drop.zip)

**Comment by insthync** [comment]
In the first clip it can't drop because it dropping on another UI (Camera rotation area), try deactivate it and drop the item.

![Screenshot_277](https://user-images.githubusercontent.com/2697550/72329194-e6284c00-36e6-11ea-9ee4-89e2a91d9df2.png)

I will add codes to detect drop area later.

**Comment by insthync** [comment]
About the second clip, it's dropping to the ground right? If it's drop to the ground it may not detect pointing UI from cursor (touch position).

**Comment by DimasjkTV** [comment]
> About the second clip, it's dropping to the ground right? If it's drop to the ground it may not detect pointing UI from cursor (touch position) so it might be unity bugs then I have to find other way to detect pointing UI.

in the second clip, yes. (This is a compiled client running on the phone). Interestingly, the item drops inside the inventory, and not just outside.
