### ISSUE TITLE
BUG 1.77 Update

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1700]
After updating to 1.77 when approaching an activable like campfire or workbench the activate button does not appear.
![image](https://user-images.githubusercontent.com/45702662/190467558-80163d7e-cc48-46b2-94be-b24246f0a78c.png)

It also happens that when dragging a dropentity item to the map (without the spawner) it does not activate when starting the map
![image](https://user-images.githubusercontent.com/45702662/190468275-44bc4b5a-8936-4fab-93c6-b5f148534941.png)

I must also say that when uploading the mysql_main file, it throws the following error.
![image](https://user-images.githubusercontent.com/45702662/190529231-c0cc984f-4c17-41eb-9fa3-61e70614138a.png)

**Comment by insthync** [comment]
Thank you for bug reporting, the fixed package is uploading

**Comment by insthync** [comment]
Fixed in 1.77b
