### ISSUE TITLE
1.77 Update

### ISSUE THREAD

**Issue by Dannx93** [suriyun-production/mmorpg-kit-docs#1701]
Hello just tried downloading the package with unity 2022.1.11f1 into a new project
Mmo Demo2D dont work as it should (im assuming) 
2D Demo dont work as it should (Im assuming)
![fail](https://user-images.githubusercontent.com/113635926/190552896-19095757-964e-4412-9e54-722f3ddf8fea.PNG)
![wtf](https://user-images.githubusercontent.com/113635926/190552898-33488654-9469-4a51-b8aa-611fb2f6f478.PNG)
![mmoservlist](https://user-images.githubusercontent.com/113635926/190552900-a326e994-12ad-49d9-a85b-9fbee6890ba5.PNG)

ive done this https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021
Let me know if i missed doing something

**Comment by insthync** [comment]
Did you set up the servers?

**Comment by insthync** [comment]
You can can't connect to map-server or you still can't connect to login/regiser/manage your characters?

**Comment by insthync** [comment]
No answer so I will close this.
