### ISSUE TITLE
Update 1.77b mysql question

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1702]
`Fix mysql_main.sql wrong syntax (missing one ;)`
With this change should I reimport this to the database tables? not sure if I import this to my current mysql will it over-write my data?

**Comment by insthync** [comment]
No, for an old projecst it does not have to import it again because it has a migration system

**Comment by insthync** [comment]
No, for old peoject it doesnot have to importit again because it has a
migration system

ในวันที่ ส. 17 ก.ย. 2022 06:52 น. molon labe ***@***.***>
เขียนว่า:
