### ISSUE TITLE
Change all !CLIENT_BUILD defines to SERVER_BUILD

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1703]
Currently the kit uses !CLIENT_BUILD defines for server-specific code which needs us to add CLIENT_BUILD to player settings/scripting defines when building clientBuild and remove it when doing serverBuild, each and everytime.  

However, Unity has had UNITY_SERVER define built-in since 2019 atleast which is auto-added when we do serverbuilds or dedicated-server builds (2021.2+), thus no longer needing to handle adding any define manually when building.  

As such, I think you should replace all occurrences of !CLIENT_BUILD with `(UNITY_SERVER || UNITY_EDITOR)`  so we no longer need to manage the define symbols.
using `(UNITY_SERVER || UNITY_EDITOR)` as this lets us code properly while in editor and not disable the code block.

![image](https://user-images.githubusercontent.com/3790163/190859975-5389e3e4-e6f4-4060-8e3a-a9a4dfb40f1f.png)

**Comment by shubhank008** [comment]
PS: By mistake I had typed SERVER_BUILD in title and in screenshot, actual define is UNITY_SERVER and exists since Unity 2019    
https://docs.unity3d.com/2019.1/Documentation/Manual/BuildSettings.html     
https://forum.unity.com/threads/unity-2021-2-dedicated-server-target-and-stripping-optimizations-now-live-please-share-feedback.1143734/

**Comment by insthync** [comment]
1.77c update: Server code exclusion with scripting define symbols conditions changed, now `CLIENT_BUILD` is removed, but you will have to use `MMO_BUILD` for MMO games, it will exclude server codes from the build when it was built as unity server build.

It still requires a `MMO_BUILD` symbol because, for offline/LAN games, they have to use codes from both the server and client sides.

**Comment by moepi2k** [comment]
Hmm i dont understand. An offline/lan game anyway not use the server check option, so servercode is there for both, client and server right? And for mmo build u just can click server build for server and uncheck when build for client.

**Comment by insthync** [comment]
It uses some server codes for offline/Lan games because they are both server and client. So don't put `MMO_BUILD` to scripting define symbols.

Put `MMO_BUILD` for MMO games to exclude server codes from client build.

**Comment by shubhank008** [comment]
> It uses some server codes for offline/Lan games because they are both server and client. So don't put `MMO_BUILD` to scripting define symbols. If you are going to build offline/Lan games.
> 
> Put `MMO_BUILD` for MMO games only to exclude server codes from the client build.

But that brings us back to the same problem that was with CLIENT_BUILD that we have to manage the define and add/remove it everytime we build client and server.  
The point of using UNITY_SERVER for server code in MMO was so we donot have to manually manage any define symbols through setting each and everytime we build client or server.  

Why not instead use something like RPG_BUILD or LAN_BUILD for rpg/lan mode to include server code within the client for them, as for the kit the MMO users are more than lan/rpg and so making us manage the define manually instead of the LAN/RPG users is weird.

PS: You could use something like `(UNITY_SERVER || UNITY_EDITOR ||RPG_BUILD)` I think as this will keep server code excluded in MMO and also include it for lan/rpg users when they define RPG_BUILD

**Comment by moepi2k** [comment]
as i understand you correctly. to MMO_BUILD is only for singleplayer/lan? in Lan bow server and client should have access to server code? if yes, then why not just use 

UNITY_SERVER || UNITY_EDITOR

so you dont have do manualy add and remove defines for server and client
when you build mmo server, u jus can use the Server Build option. ths will automaticly add the Unity_server defines.
and when u build client or singleplayer/lan u just build without Server Build option checked.

**Comment by shubhank008** [comment]
@insthync actually, why even add or manage a new define for anyone ? If you use just UNITY_SERVER for server code in MMO, can't the LAN/RPG users just add that UNITY_SERVER define to their settings and it will include client and server code for their builds ?  
While for MMO users, everything will be auto-handled when making server builds.

No need for a new define and for lan/rpg users they just need to add UNITY_SERVER define once and forget it.

**Comment by insthync** [comment]
Don't add `MMO_BUILD` for Offline/LAN games

Add it for MMO games only

**Comment by insthync** [comment]
Just add `MMO_BUILD` if you making MMO games and want to exclude server codes from client.

**Comment by insthync** [comment]
It can't just add `UNITY_SERVER` as condition to exclude server codes because when you build Offline/LAN games server codes are needed.

**Comment by moepi2k** [comment]
hm still dont get it. maybe im confused. 

that sounds like u need to do it manually like before to exclude server code when build client
> Just add `MMO_BUILD` if you making MMO games and want to exclude server codes from client.


but here you say u dont need to swtich if you only work with mmo
> @shubhank008 It is different because you won't have to add/remove anything to `scripting define symbols` if you won't switch to build Offline/LAN games.

> It can't just add `UNITY_SERVER` as condition to exclude server codes because when you build Offline/LAN games, server codes are needed.

UNITY_SERVER means that servercode is included and not included. so if you add it once manualy. Servercode is always there when u build for Singleplayer/LAN

and when ut not add it. u can just use Server Build option to make Server Build or let it empty to make Client build. it will add it automaticly -> https://gyazo.com/0b2753e188ae0a886c936321c967262c

**Comment by insthync** [comment]
I said Offline/LAN games need server codes, So I can't exclude server codes from Offline/LAN games build. 

I uses `MMO_BUILD` to exclude server codes from client for MMO games build.

And maybe, you guys can stop thinking about this anymore, I will add a build menu, when you press the menu to build it will add things to scripting define symbols automatically.

**Comment by Callepo** [comment]
" why even add or manage a new define for anyone ? If you use just UNITY_SERVER for server code in MMO"

@moepi2k @shubhank008 he is saying he cant use UNITY_SERVER becuase Single Player/ Lan .. needs alot of codes which are inside the Server Build for mmo.. 
And it will all be excluded when u do a normal Lan Build.. becuase UNITY_SERVER will only include these codes, when u make Headless Build or Dedicated Server build with unity 2021+. 

"can't the LAN/RPG users just add that UNITY_SERVER define to their settings and it will include client and server code for their builds ?
While for MMO users, everything will be auto-handled when making server builds.

No need for a new define and for lan/rpg users they just need to add UNITY_SERVER define once and forget it."

This is very good option tbh.. 
cuase mmo users need to have 1 build without the IF# and then add it to make a normal Client.. 
Or use stuff like Build Automator, and set it up to have separate Defines, to make builds.. 

While if ur Single players u just add it once and ur done.. 

They dont even need to add it.. add it in the default kit project settings.. 
so when a new player join its already there and working.. and when they learn the kit and wanna make mmo clients.. they can remove it and have it be for mmo automated..

@insthync

**Comment by insthync** [comment]
Okay, I may remove `MMO_BUILD` then add `NON_MMO_BUILD` then change the condition, and I will add `NON_MMO_BUILD` as its default setting. And also still add a build menu :P

**Comment by insthync** [comment]
Or may just use `UNITY_SERVER` as @shubhank008 suggestion, and still add a build menu.

**Comment by Callepo** [comment]
the UNITY_SERVER makes it so that its handled by unity itself when u make a new build. that would be nice.. 
so when i dont make a Dedicated server build or headless, it auto exclude the server codes.. 

And when i do make Dedicated/ headless, the codes are always there.. 
and people creating LAN, Will by default already have the Define added, so they dont have to worry bout it.. 

But us mmo users, will have to remove it only 1 time and we fine, well unless we want to test stuff in singleplayer in editor LOL
But it is what it is, u decide whats best

**Comment by moepi2k** [comment]
> But us mmo users, will have to remove it only 1 time and we fine, well unless we want to test stuff in singleplayer in editor LOL
> But it is what it is, u decide whats best

thats what i tried to say xD. add the UNITY_SERVER define in default kit. so new customer can work and test in singleplayer.
and for mmo just remove it once and done. Server/Client build then you can easy switch with just use the Server Build option in building settings. so actually only need to add UNITY_SERVER || UNITY_EDITOR, so u can code proberly in editor too.

but for sure the choice is yours :)

**Comment by Callepo** [comment]
UNITY_SERVER || UNITY_EDITOR

yea This will solve it all, so even when ur doing mmo testing in singleplayer in editor.. it will work fine.. 
then u build u have ur code separated. 

This should be perfect
@insthync
