### ISSUE TITLE
MMO - Linux Connection Problem

### ISSUE THREAD

**Issue by Siphrioth** [suriyun-production/mmorpg-kit-docs#1704]
I need Help. I cant connected zu the Server. have built everything according to the instructions:

https://www.youtube.com/watch?v=1CGRlHGDu8U

1.)
![Snag_18da1f2](https://user-images.githubusercontent.com/33433389/190911946-32b64bd1-d86d-411f-9a5f-fcafc4fd51f2.png)

2.)
![Snag_18f1e51](https://user-images.githubusercontent.com/33433389/190912021-32ab73e4-ec87-4937-883e-eb1590b0b0d4.png)

3.) Create Configfile "serverConfig.json"
![Snag_194f04e](https://user-images.githubusercontent.com/33433389/190912330-ce8e1d39-dd2a-4d4e-9500-bb92389fa48b.png)

4.) Start Server with:
nohup ./MMO_Linux.x86_64 -startCentralServer -startChatServer -startMapSpawnServer -startDatabaseServer &
![Snag_190579c](https://user-images.githubusercontent.com/33433389/190912076-557887b4-e27d-4d9f-b349-8d68095717f2.png)

Logs:
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9594168/Log_Database_Central_MapSpawn.log)
[Log_Map(Map001) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9594169/Log_Map.Map001.Instance.log)
[Log_Map(Map002) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9594170/Log_Map.Map002.Instance.log)

Than:
5.)
![Snag_19274ee](https://user-images.githubusercontent.com/33433389/190912197-01d01900-74fe-4c6c-bbbf-c35f15479b1e.png)
![Snag_1928634](https://user-images.githubusercontent.com/33433389/190912201-e1b3f345-63bb-4943-aefc-61e2a4fd2a13.png)
![Snag_1936db5](https://user-images.githubusercontent.com/33433389/190912246-56514f02-1b0e-449e-a834-104c5cdba98c.png)
![Snag_1938525](https://user-images.githubusercontent.com/33433389/190912247-3d1138da-d362-4217-93a4-5b3428ae6ce5.png)

Hope anyone can help me :) Thx @all

**Comment by insthync** [comment]
In serverConfig.json, delete `,` at line `17`

Then you have to check that the ports are accessible from other device (try to setup firewall with ufw)

**Comment by Siphrioth** [comment]
Thx Now ive:
![Snag_2118c83](https://user-images.githubusercontent.com/33433389/190918614-4142e6de-5e60-499d-b65f-1d535e7e2976.png)
![Snag_211a02a](https://user-images.githubusercontent.com/33433389/190918619-e4c49f0b-4198-40c7-8384-5518e62e090c.png)

And the Log:
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9594447/Log_Database_Central_MapSpawn.log)

he does not want to start :(
