### ISSUE TITLE
[Bug?]Change Class Quest

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1706]
in the demo, there are 3 quests to change class
https://gyazo.com/20ac6c78cd0779ea3a18b354204d8aa3

somehow it not show it when select the npc.

anyway. i tested it in my project, and im not sure if it works proberly. for example:
i have following classes with Skill

Class A : Fireball
Class B : Power Attack

so now when i create a Character with Class A and train Fireball, then make a quest to change Class to B, it will unlock Power Attack,
but i can still use Fireball.

even when the player learn Fireball for example level 2 it should be there but not useable, right? @insthync

**Comment by insthync** [comment]
To make it show in the NPC, you must choose a Novice class when you create a new character

![Screenshot_56](https://user-images.githubusercontent.com/2697550/191640648-4fe194d8-f7b3-45bb-90a7-b9217d077934.png)

Then levelup it to 10 and talk to NPC: `Test Quest 01`

![Screenshot_55](https://user-images.githubusercontent.com/2697550/191640708-fec6c490-39a4-4910-b664-81722718a27b.png)

About skill..., I think I will add an option to make it able to reset skill/attribute when completing quest.

**Comment by moepi2k** [comment]
Alright thank you very much for clarify. The skill/attribute reset is a good option. But is it also possible without reset. For example a game shere player have alot of skills but u want to restrict i
