### ISSUE TITLE
[Bug]BoundsSizeRateWhilePlacing

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1707]
in 175f some things for building stuff changed. i dont know if its becaus of the update but the https://gyazo.com/0ecb382de8a5ddbab1b19ee50ef847b0 
no longer works

**Comment by insthync** [comment]
As I try, it still works as intended, not sure how it should work in your expectation?

**Comment by moepi2k** [comment]
I check in fresh kit then. Overlapping colliders are no longer placeable in my project. So a checked docs an saw the building changes in 175. Just though its because of this.

Il take a look again. Thx for info 👍
