### ISSUE TITLE
Virtuals

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1709]
i just updated my project to latest kit version and noticed that some method are no longer virtual. e.g this

https://gyazo.com/ddc227f3788ffbe0dfe5725778f8a33c

i remember in an update you changed alot method to virtual. i just wondering if there is a specific reason to change it back?
or was that maybe a coremod from me? :P

**Comment by insthync** [comment]
Use `onEquipWeaponSetChange`

**Comment by moepi2k** [comment]
will do, thank you :)
