### ISSUE TITLE
[BUG] ActivateButton

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1711]
ActivateButton does not work when on a mount.

even if another person is on a mount you will not be able to interact with them either
https://imgur.com/a/1vJoS9Y

Besides this is always active when mounted
![image](https://user-images.githubusercontent.com/45702662/192076064-4b40676e-bef4-4d8e-b179-890d3f549bbb.png)

**Comment by insthync** [comment]
Fix it by changes codes in `VehicleEntity` class -> `CanActivate` function to

```
        public virtual bool CanActivate()
        {
            return !this.IsDead() && GameInstance.PlayingCharacterEntity.PassengingVehicleEntity == null;
        }
```

**Comment by Blunnyn** [comment]
thnks
