### ISSUE TITLE
[Suggestion] Effectiveness attributes for weapons

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1713]
An interesting option for the kit is that the Weapon also has the option of Effectiveness attributes as in the skills, to be able to increase the weapon's damage based on the player's attributes, I don't know if it's difficult to do that, but it would be nice if it had.

**Comment by moepi2k** [comment]
That is already added on weapon type

**Comment by juniormagalhaes** [comment]
> That is already added on weapon type

but sometimes the person wants to create swords with damage in different attributes XD

**Comment by khongtuong** [comment]
> > That is already added on weapon type
> 
> but sometimes the person wants to create swords with damage in different attributes XD

you can create many type (int, dex, str,...) of one-hand sword or something like that, and then add it to craft skill to make different attribute
