### ISSUE TITLE
Skill turn player? Skill jump / fall bug? MMO

### ISSUE THREAD

**Issue by colt0560** [suriyun-production/mmorpg-kit-docs#1716]
Im using skills as a way to make the player do emotes. but it turns the players direction the whole time the skill is being played. Is there way to check this off when do skill? Also when players do skill in MMO, player can jump and once player falls, it lags all weird and player slowly falls down while playing skill

**Comment by insthync** [comment]
I don't get it, please attach a video which shows how is it going.

**Comment by colt0560** [comment]
https://user-images.githubusercontent.com/113489731/193412259-0963adfc-6b8c-48b4-bb60-901e7baaa3ee.mp4

the player turns all the time trying to do the skill / emote. for my purpose as an emote i think it doesnt look right. where in the code can i turn off the player turn when do skill?

**Comment by colt0560** [comment]
at the end i jump doing skill. in shooter it works great, but in mmo the player falls down slowly and lags, which isnt shown at the end bc im using shooter int
