### ISSUE TITLE
Player Aim Lock-on bug? Aims at pets

### ISSUE THREAD

**Issue by colt0560** [suriyun-production/mmorpg-kit-docs#1717]
How do I turn off the player aiming at character when doing an action? I have turned this setting off before but can't find it anymore... Whenever you summon a pet, player can sometimes lock-on/aim/face at pet. this can be pretty annoying when fighting with pets

**Comment by insthync** [comment]
I will check it.

**Comment by insthync** [comment]
Fixed in 1.78
