### ISSUE TITLE
Players child objects Layer in character selection

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1718]
When start game and in character selection screen. all Layer from Character are set to Player, even when those which are changed.
only when you enter the game it changs to the right one you set.

i cant find where or why the player change before enter the game

**Comment by insthync** [comment]
It's intended to set to the layer which set in-game instance, you can find where it is going to change it in `BasePlayerCharacterEntity` -> `EntityAwake` function

**Comment by moepi2k** [comment]
yea i got that. but why it change all layers (parent and child) to player in character seleciton. but when in game. the layer for child object are correct (like what i set in editor). on game only parent layer will change.

for example.
https://gyazo.com/7ad7c1306b8d6f1c167e1dc9cc894ba7
this is my player prefab in editor.

and here in character selection (all gameobject layers changed to player)
https://gyazo.com/fc07241b9f95ea08453c0b12e85e82f2

and here in game (layer are correct, like i set)
https://gyazo.com/7ddd88e8cbbc2a8e0c82529e08d3f87c

only the parent layer change in game. by default i set it to character. and ingame it changes to player (what i set in gameinstance) just wondering why it behave diffrent in player selection window

**Comment by insthync** [comment]
The `CharacterDataExtensions` -> `InstantiateModel` did it (find: result.gameObject.SetLayerRecursively(GameInstance.Singleton.playerLayer, true);)

**Comment by moepi2k** [comment]
I will check, thank you 👍
