### ISSUE TITLE
Restrict attack when crawl or crouch?

### ISSUE THREAD

**Issue by colt0560** [suriyun-production/mmorpg-kit-docs#1719]
im using shooter controller, i want to make it so player cant attack when crawl or crouch. is this already a thing?

**Comment by insthync** [comment]
Don't have the settings for that yet.

**Comment by colt0560** [comment]
i was able to do this by editing shooter controller script to stand up using the already made functions, stand up when jumping in crouch mode

**Comment by insthync** [comment]
In 1.78
- Add `MovementRestrictionWhileReloading` settings to `IWeaponItem`.
- Add `MovementRestrictionWhileCharging` settings to `IWeaponItem`.
- Add `MovementRestrictionWhileAttacking` settings to `IWeaponItem`.
- Add `MovementRestrictionWhileReloading` settings to `IWeaponItem`.
- Add `AttackRestriction` settings to `IWeaponItem`.
- Add `ReloadRestriction` settings to `IWeaponItem`.
- Add `MovementRestrictionWhileUsingSkill` settings to `BaseSkill`.
- Add `UseSkillRestriction` settings to `BaseSkill`.

**Comment by colt0560** [comment]
i have tried only updateing the scripts you have said here. but it tells me movement restriction could not be found. what other script associates that?

**Comment by insthync** [comment]
You actually should use version control to find difference codes, I will try to help you but your information above is useless, how can I know which are scripts that can't find them? you should copy log messages or capture error messages.

**Comment by colt0560** [comment]
yes. I dont want to update the whole package because I made alot of core changes to scripts.... i'm on a older version of 1.78.
I only updated BaseSkill and IWeaponItem script, as mentioned above. But i get this error, where is movement restriction coming from?

**Comment by colt0560** [comment]
![TinyTake01-12-2022-12-43-07](https://user-images.githubusercontent.com/113489731/205124184-13d2a278-375b-4e62-8364-1a66344c34f1.png)
![TinyTake01-12-2022-12-40-01](https://user-images.githubusercontent.com/113489731/205124185-a3f470d1-9842-48f9-abf1-4ed328603a39.png)

**Comment by colt0560** [comment]
the shooter controller?? should i update shooter controller too and it will work?????

**Comment by insthync** [comment]
It might have changes on it, weapon item and so on, I can't remember, I will available to answer you on monday

**Comment by colt0560** [comment]
Thankyou plz let me know
