### ISSUE TITLE
Mobile item drag problem !

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#1722]
![image](https://user-images.githubusercontent.com/95127578/193861539-fe7dfdb1-6928-43a9-8b3d-8de40d3f746d.png)

There is a problem of changing the location of the item on mobile, this way the item is dragged on PC, but it does not happen on mobile.

**Comment by insthync** [comment]
If it can drag icons, then how about scroll view scrolling?

**Comment by CLAXES** [comment]
When I select a mobile user interface, the item is not dragged.

**Comment by CLAXES** [comment]
for mobile can you put a button called move when item is clicked, most rpg games have a similar move button

**Comment by insthync** [comment]
Which one?, I am going to try it.

**Comment by insthync** [comment]
Which one?

**Comment by insthync** [comment]
Wait for your answer over a month but there is no answer, so I will close it.
