### ISSUE TITLE
[BUG?] Move speed

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1723]
When the character has a movement speed reduction debuff, it is not affected by being on a mount.
https://imgur.com/a/X34RycB

**Comment by insthync** [comment]
It has a `moveSpeedType` setting in `VehicleEntity`, try set it to `BasedOnDriverMoveSpeed`

**Comment by Blunnyn** [comment]
Ah ok, but How can I make the buff of a MountEntity (stats,attributes,etc) show when selecting the item? as well as the potions, etc.

**Comment by insthync** [comment]
Changes codes in UICharacterItem
