### ISSUE TITLE
Spawning issue

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1724]
im running 1.76d with some scripts pulled from newest. I cant update to newest yet because it breaks all my custom stuff I dont have time to fix it all at the moment so I dont know if upgrading completely will fix this.
I changed the spawn point and all old players are still spawning at the old spawn point and new character after the new spawn point was made are fine it spawns as normal in the new spot. its only the old characters from the database that still spawn in the old spawn point. any idea how to fix this?

**Comment by moepi2k** [comment]
i think its because they created with old data, and the respawn position is stored in db. change id manualy in db or let player rebind respawn position on a npc for example

**Comment by molonlabe1337** [comment]
> i think its because they created with old data, and the respawn position is stored in db. change id manualy in db or let player rebind respawn position on a npc for example

thanks for the work around ill rebind it for them
