### ISSUE TITLE
[BUG] Character stuck when you attack while jump 

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1725]
Hi , I'm using shooter character controller and i have added jump , fall and landed animations .. when i jump and attack using 1 hand , 2hand ( any kind of weapon ) my character stuck on air .. so Is there a way to disable attack while jump ? 
![Untitled](https://user-images.githubusercontent.com/71017004/194289355-10d48d46-d85a-4eb0-aca5-bd16a0249dc8.jpg)

**Comment by AhmedHon** [comment]
@insthync i hope you add it :)

**Comment by insthync** [comment]
Added in 1.78, try set weapon item -> `AttackRestriction` -> `restrictedWhileAirborne` to `TRUE`

**Comment by AhmedHon** [comment]
@insthync  Thank you so much <3 every thing works fine now
