### ISSUE TITLE
Question about socket enhancers

### ISSUE THREAD

**Issue by molonlabe1337** [suriyun-production/mmorpg-kit-docs#1726]
I've been digging around in the scripts to find where to do this but can't find it, maybe someone could give me some advice here...

How do I add the incremental stuff to socket enhancers? normal armors have incremental fields where as socket enhancers are missing the incremental stuff for refining. How do I make it incremental? 
This is the armors:
https://gyazo.com/d4b02d4eb12847b2ed95d5c67d607bbc

This is socket enhancer:
https://gyazo.com/0113c5c7f749e2d4e817089201491274

Trying to use the item refine system with socket enhancers I think that if the socket enhancer has option to refine it should also have incremental options. Thanks for the help I appreciate it.

**Comment by insthync** [comment]
It can't, if it can it must store a lot of data in a database and also include networking data size. I recommend making a new socket enhancer item, and using other ways to change from socket enhancer item 1 to 2, for example, talk to NPC to convert socket enhancer item 1 by using some gold to socket enhancer item 2
