### ISSUE TITLE
when doing a skill and having a weapon equipped, it plays the weapon effect 

### ISSUE THREAD

**Issue by colt0560** [suriyun-production/mmorpg-kit-docs#1729]
so im using skills for emotes. I do a dance animation with a skill and when i have a gun or weapon equipped, it will play the attack/shoot FX thats on the weapon

**Comment by colt0560** [comment]
where in script does it play the fx on a weapon when doing a skill?

**Comment by insthync** [comment]
In `DefaultCharacterUseSkillComponent` find `PlayEquippedWeaponLaunch`

I actually change condition to play it in 1.78, you may try it before changing something.
