### ISSUE TITLE
bag with monster

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#173]
need to fix the aggression of the monsters, they begin to attack, but when you move away by 10 steps, the aggression disappears, this is bad, because when installing a messile attack with a greater distance, the mobs simply don’t run to the attacker or run and just don’t reach him during the run going about his business

**Comment by lundgren84** [comment]
@1isenok this will make monsters angry when hit them with ranged weapons

BaseMonsterCharacterEntity.cs

##ADD BOOL##
public bool _isAngry = false;

##SET BOOL TRUE##
public virtual void SetAttackTarget(BaseCharacterEntity target)
        {
            if (target == null  target.IsDead())
                return;
            // Already have target so don't set target
            BaseCharacterEntity oldTarget;
            if (TryGetTargetEntity(out oldTarget) && !oldTarget.IsDead())
                return;
            // Set target to attack
            SetTargetEntity(target);
            _isAngry = true;
        }

MonsterActivityComponent.cs
##IF BOOL IS TRUE##
if (CacheEntity.TryGetTargetEntity(out targetEntity))
      {
            if (targetEntity.IsDead()  targetEntity.isInSafeArea)
                {
                    // If target is dead or in safe area stop attacking
                    CacheEntity.SetTargetEntity(null);
                    return;
                }

            if (CacheMonsterCharacterEntity._isAngry)
{
        startFollowTargetTime = time;
       CacheMonsterCharacterEntity._isAngry = false;
 }

                UpdateAttackTarget(time, currentPosition, targetEntity);
            }
