### ISSUE TITLE
[Bug]Campfire -> DUPE

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1732]
When you add multible 'Fuel' item Stacks. the translate duration will be divided
e.g with one Wood the duration for translate is 5 seconds. when i add 4 stacks its around 1 sec
https://gyazo.com/b2c69f197ebd4a06a83203fe413c1b1b

also noticed that you can dupe items with it. its hard to reproduce but i try to make a video.
for example when you have multible stacks of fuel and while the campfire is running and you drag out items. it duplicates in some cases

https://cdn.discordapp.com/attachments/1031227520005181491/1031304663242395708/2022-10-16_16-20-38_Trim.mp4

**Comment by insthync** [comment]
Fixed

**Comment by insthync** [comment]
Fixed in 1.78b
