### ISSUE TITLE
[Bug]warping

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1735]
Many players reported that when they die while warp they get stuck in an endless loop of warping

https://media.discordapp.net/attachments/1031962508791136377/1031975706160271520/2022-10-18_17-27-17.mp4

Relog server restart, nothing can help. You cant respawn anymore.

**Comment by insthync** [comment]
May I see player's current map, respawn map data?

**Comment by moepi2k** [comment]
https://gyazo.com/5f42c642013f50d75aeda6dae03c1ba9

**Comment by moepi2k** [comment]
Ok it seems the problem is not warp. It happen when player die with a damage over time

**Comment by insthync** [comment]
How to reproduce it?

**Comment by moepi2k** [comment]
its hard to reproduce but it happen many times to my player when they do pvp and warp while having a damage over time debuff on it. 

seems when you receive the Dot in MapA and warp and while warp to MapB you die, there is no killer data. also then you die and cant respawn. you need to relog

**Comment by insthync** [comment]
Not sure that the issues still occurring after restart server?

**Comment by moepi2k** [comment]
yea bug occur also after restart. because the debuff is still active. you even can see the dead body lying on the ground with the debuff effect on it and its never over. 

what i need to do, i remove the debuff from mysql db. but yea this mostly happen when a player has a debug damager over time on it and warp with it

**Comment by insthync** [comment]
You should include your server log files

**Comment by insthync** [comment]
Can reproduce, going to fix it

**Comment by moepi2k** [comment]
great, yea sorry, next time i will send log files too

**Comment by insthync** [comment]
Fixed in 1.78b
