### ISSUE TITLE
Exp share calculation with guild 

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1737]
when use guild and share exp there is a small issue. not big deal

set monster EXP to 50
when share is 2% it should give player 49 exp and guild 1 exp
but it wont. only the player get 49 exp but the 1 exp of guild is lost
only when u set share to 3%, guild will receive it. i think its something with float and rounding? even when 
2% of 50 are a full number of 1

**Comment by insthync** [comment]
I've add `Mathf.CeilToInt` to calculating shared exp in 1.78b
