### ISSUE TITLE
Sheathing Anims Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1738]
That line code should be 
![image](https://user-images.githubusercontent.com/7702658/196833114-d075b15f-6965-441f-8279-2eb6bf4c5bb5.png)
Like this
![image](https://user-images.githubusercontent.com/7702658/196833150-a6f03bdd-e68c-44c3-b65c-5d63cca42ea6.png)

cuase its sending the characteritem data id, and not the weapon type data id.. so its always returns false, and sheathing always only play default animations, and never weapon animations

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.78b
