### ISSUE TITLE
Guild War

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1739]
i noticed that the castle heart only receive damage from AOE, Raycast and melee do nothing
when i comment out that part it behaves like a normal entity and it works, but yea then it not works for GvG :)

not tested in fresh project yet.

**Comment by moepi2k** [comment]
also when restart server the occupied Castle Heart no longer belongs to the winner guild.  @insthync

**Comment by insthync** [comment]
It has nothing storing into database yet :P, so it can't know who is the winner after restarting the server

**Comment by moepi2k** [comment]
ohh :) is it big effort to add it? if not can you tell me how to store it?
