### ISSUE TITLE
IL2CPP Support Server + Client

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1741]
i was going to report bout how mapspawnnetwork doesnt work with IL2CPP back end, but i saw its been reported before. 
is there any updates on this ? 
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1557 

basically **Process.Start(startProcessInfo)** not working, which makes it impossible to have instances.( u can bypass maps by spawning them manually, but instancing is not gonna be a thing)

also on the Client end of things Ncp dialog Custom Condition, the way the code is invoking the condition makes it not possible to be used with IL2CPP. basically it cant find or invoke the code at runtime, u have to precompile it into the build.

I dont have the actual error message atm of it, i will EDIT it later onto this post when i have it clearify it. 

![image](https://user-images.githubusercontent.com/7702658/197115603-a5580eb3-9cda-499e-a30a-4f8cc90b2097.png)

These are the only 2 things i found broken with IL2CPP. if these work, we can have proper builds on both Server + Client

**Comment by Callepo** [comment]
@insthync 
It needs generate the code on build, not runtime
![image](https://user-images.githubusercontent.com/7702658/197315093-06c77257-107b-4fa2-8129-ac83e90e740c.png)

**Comment by insthync** [comment]
Any solution?

**Comment by Callepo** [comment]
https://docs.unity3d.com/Manual/ScriptingRestrictions.html

**Comment by insthync** [comment]
Are there any library which I can use instead of the current one (this: https://github.com/Siccity/SerializableCallback)

**Comment by Callepo** [comment]
i dont know a library which could replace it tbh, we could try have it compile ahead of time. but i been trying to do it. maybe im not doing it right or it doesnt work at all

**Comment by insthync** [comment]
Custom condition issues fixed in 1.80
