### ISSUE TITLE
Teleport to map on click button in MMO

### ISSUE THREAD

**Issue by temelGameFacto** [suriyun-production/mmorpg-kit-docs#1743]
I actually realized the issue.I can teleport when I enter warp portal, but I created a MAP UI and I amtrying to teleport to map by clicking button but not working on UI side.It is working in singleplayer mode but not working in MMO.

    public virtual void EnterWarp(BasePlayerCharacterEntity playerCharacterEntity)
    {
        WarpPortalType portalType = warpPortalType;
        string mapName = warpToMapInfo == null ? string.Empty : warpToMapInfo.Id;
        Vector3 position = warpToPosition;
        bool overrideRotation = warpOverrideRotation;
        Vector3 rotation = warpToRotation;

        if (playerCharacterEntity.Level >= minLevel && playerCharacterEntity.Level <= maxLevel)
        {
            List<WarpPointByCondition> warpPoints;
            if (CacheWarpPointsByCondition.TryGetValue(playerCharacterEntity.FactionId, out warpPoints) ||
                CacheWarpPointsByCondition.TryGetValue(0, out warpPoints))
            {
                WarpPointByCondition warpPoint = warpPoints[Random.Range(0, warpPoints.Count)];
                portalType = warpPoint.warpPortalType;
                mapName = warpPoint.warpToMapInfo == null ? string.Empty : warpPoint.warpToMapInfo.Id;
                position = warpPoint.warpToPosition;
                overrideRotation = warpPoint.warpOverrideRotation;
                rotation = warpPoint.warpToRotation;
            }

            Debug.Log("EnterWarp");

            CurrentGameManager.WarpCharacter(portalType, playerCharacterEntity, mapName, position, overrideRotation, rotation);
        }
    }
I call this function on clicking button.See screen shoot below .

    public void EnterMap()
    {
        //EnterWarp(GameInstance.PlayingCharacterEntity);
        Debug.Log("EnterMap");
        EnterWarp(GameInstance.PlayingCharacterEntity);

        if (!warpImmediatelyWhenEnter)
        {
            foreach (GameObject warpSignal in warpSignals)
            {
                if (warpSignal != null)
                    warpSignal.SetActive(true);
            }
        }
    }

![Ekran Alıntısı](https://user-images.githubusercontent.com/109655407/197342734-444968b5-89c6-4c50-9944-95a278ee8078.PNG)

**Comment by insthync** [comment]
It is because the function calling at the client side, teleport request message was not sent to the server, so the server doesn't know that it has to move a player to somewhere.

**Comment by temelGameFacto** [comment]
how can I send teleport request to server side ?
