### ISSUE TITLE
[Bug]SkillItem Cooldown

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1744]
The Use Item Cooldown on SkillItems not working

https://gyazo.com/743dc33a5257e8750169767c449fb5fa

even the one from gameinstance will be ignored from SkillItems
https://gyazo.com/9e1b6f01db85c895cfd00b5ba37612fb

it works with PotionItems

-> Bug only in MMO, SP is fine

**Comment by moepi2k** [comment]
p.s just noticed, cooldown works for consum the item but somehow you can spam it,
https://gyazo.com/6ffe3fc38f20e4e95d30994d2b7c33bf

check the hotkey bomb, it only consume 2 times but the rest is just visual issue

**Comment by insthync** [comment]
Fixed in 1.78b

**Comment by moepi2k** [comment]
you can still spam skill items -> https://gyazo.com/38a457549c696cbc1967ab2a4c299b16
the logic serverside is fine (consuming, cast time and everything)
but clientside you can just spam it
