### ISSUE TITLE
Why I cannot spawn more than 4 maps on server ?

### ISSUE THREAD

**Issue by temelGameFacto** [suriyun-production/mmorpg-kit-docs#1745]
I only can spawn 4 maps on server.When I trying to teleport other maps Server dissconnect me from map.I cannot spawn my character anymore.Isthere any map spawn limitation ?

**Comment by insthync** [comment]
Are you sure that the port gor that map is open?

About limitation, It is limit by device specs.

**Comment by temelGameFacto** [comment]
Always spawn first 4 maps on server.
![Ekran Alıntısı](https://user-images.githubusercontent.com/109655407/197390284-2ee02f0c-eb06-4c11-96ae-f3c9250e4509.PNG)

**Comment by temelGameFacto** [comment]
You are right.I forgot to open other ports.I solved the issue.Thank you
