### ISSUE TITLE
[Sug]Quest & Groups

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1746]
when player making a group and doing quest, monter kill should be credited to everyone in range even to the only one which makes the last hit, this is how it works in almost every mmo i played. feels a bit sensless to make a group to just share exp

**Comment by insthync** [comment]
Noted, how about the previous warehouse bug :P ?

**Comment by moepi2k** [comment]
Im at computer in about 3h then i will test new update. But yesterday i manualy changed randomseed tinyint to int and it worked. 

Just weird was that even when i setup the mysql fresh in 177d2. The migration from mysqldatabase is listed but it not changed to int which should since migration 1.72.

Could it be that the migration nlt override it in the mysql tables? I assume you changed tinyint to int directly in the mysql file right now.

**Comment by insthync** [comment]
Yes, I forget to make changes to `mysql_main.sql` and I just know that it has a migration code in `MySQLDatabase` just when you told me, that is why it has the same migration code for 1.78.

**Comment by moepi2k** [comment]
ok updated everything to latest version, only 100+ errors to fix from all my addons :P 

but hey so far everythings fine :)) 
-> warehouse works also
