### ISSUE TITLE
Problems with buttons on mobile devices

### ISSUE THREAD

**Issue by SamuelLeyva** [suriyun-production/mmorpg-kit-docs#1747]
I recently updated to version 1.78, I didn't use the package since version 1.73, when I compile for Android when I test it the attack buttons, assign items and interact with NPCs don't work, I imagine there were changes in the package input but I don't know how to make it work, I would greatly appreciate the help, regards

**Comment by insthync** [comment]
It is not testing in editor, it is testing in Android devices and it is not working properly, right?

**Comment by SamuelLeyva** [comment]
> It is not testing in editor, it is testing in Android devices and it is not working properly, right?

if so as you say, in the editor the buttons work correctly but when testing it on android these buttons don't work

**Comment by insthync** [comment]
May I try your game?, as I try it still works properly

**Comment by SamuelLeyva** [comment]
> May I try your game?, as I try it still works properly

I haven't made the game as such just create a new project and add version 1.78 of MMORPG Kit to it but if it works fine for you then it must be something I'm doing wrong

**Comment by ashrafabdelrazik** [comment]
Still no fix for this? I am having the same issue. It works normally in the editor but it doesn't work at all on android devices !

**Comment by insthync** [comment]
It is because of server codes exclusion, you have to do this
 
![Screenshot_202](https://user-images.githubusercontent.com/2697550/203372093-0ee3ae23-f195-4799-9d21-d2694cb6375f.png)

But then it will have error from MMO side when build the game, if you are going to make offline game you can delete MMO folder or wait for a new update which fix it.

**Comment by insthync** [comment]
A version 1.78g which include these changes https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/c6eb400bfaa731d587b06eb192371e90081e9ecf
was uploaded, it will make it able to build to mobile platforms while `UNITY_SERVER` was defined

**Comment by moepi2k** [comment]
With the new changes its nlt exactly like you cant no longer build for mobile with included serverfiles? Because standalone its not mobile

**Comment by insthync** [comment]
What is nlt ?

**Comment by moepi2k** [comment]
typo -> not. i mean if understand correct. standalone means windows linux mac, with the new defines, server code is always excluded when build for mobile, isnt it?

**Comment by insthync** [comment]
Ahh, yes

**Comment by insthync** [comment]
Only server codes that are not required for offline/LAN games (such as all from MMO)

**Comment by moepi2k** [comment]
ahhh got it, not all existing defines was changed with the new standalone changes. thanks for clarify
