### ISSUE TITLE
OnHoldActivate AimAtCoursorController

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1748]
The OnHoldActivate on the AimAtCursor is missing

i just added it with this
https://gyazo.com/4c65ceba3feb7c91e75319405e362ce4

in the BuildingEntity the OnGoldActivate debug is called
https://gyazo.com/15a7d0dca96f25dfcff5d9c9bd7c2fe4

but the BuildingDialog not show up, it works when use standard player controller.
any ideas whats the cause?

**Comment by insthync** [comment]
This might be fixed in latest version 1.78f

**Comment by moepi2k** [comment]
Cant see any changes in aimatcursor controller? 
But i fixed it already
