### ISSUE TITLE
[BUG] Maximum Currency Limit

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1749]
When a player hits the maximum currency limit, the values are no longer displayed and selling / buying items becomes bugged.

A suggestion to have a hard limit for currency and to stop receiving currency, OR have another pot where the excess currency is transferred to so players can still receive & earn currency, but not directly to the inventory.

**Comment by insthync** [comment]
Limit for gold and cash?, or custom currencies ?

**Comment by BJPickles** [comment]
This was experienced with gold, but could occur for any currency. 
Havent tested on other currencies, however.

**Comment by insthync** [comment]
It has an integer increasing function that will not increase the number if it reached a max value, the function is implemented, so as I try it has no problem when my character receives gold and it is going to be over its max value. Not sure why you having the issues.

**Comment by BJPickles** [comment]
I'll get a video for you. Maybe I'm not understanding properly:)
