### ISSUE TITLE
Planting system

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#175]
Hi, Do you have any plan for the planting system for survival mode?
usually survival includes gathering, hunting and planting.
I'm now trying to do this myself but it seems very complex for me becuase it has to include seeding, growth and harvesting.

**Comment by insthync** [comment]
For now the package actually have the gathering (attack harvestable entities) and hunting (attack monster entities). Not sure it's exactly what you want or not.
What if I make the expansion package for sale?, it will including the planting system, hoe using, seeding, watering, growth and harvesting.

**Comment by dglee2592** [comment]
Thank you very much for the comment!
Yes, that's exactly what I want (hoe using, seeding, watering, growth and harvesting).
And I willing to buy the addon, or I'll pay personally. If you can do this, please chat me in discord channel, DG#4519

**Comment by insthync** [comment]
I don't have time to do it yet, there are many promised features that I should finish it first.
