### ISSUE TITLE
[Bug]Queued Workbenchs

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1751]
there is a bug for queues workbenchs
1) the queue is global. so when  a player set 1000 items no one other can ever craft something.

2) sometimes when ppl leave the workbench with an open queue it list still remains even when noone craft it
https://gyazo.com/ffe42331a36db6c3def03f514b34f463

**Comment by insthync** [comment]
1. Isn't it working as intended?
2. Because it is a global workbench then when players leave it, it is still working to craft items.

**Comment by moepi2k** [comment]
I just thought the queue is for esch player. Because player can abue it and just add 100 of items in the queue so no one other can use it
