### ISSUE TITLE
Multiple entries and Item Dupe

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1752]
https://www.youtube.com/watch?v=tnj54x-7QKw
This old bug still persists
please watch the video and see how to do it
same as server sqlite or mysql

**Comment by insthync** [comment]
Try this: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/88bed6578dcd5c1b2e708888cb41f4dfa1a0217a

**Comment by BarzoStrike** [comment]
Works fine thanks
