### ISSUE TITLE
Database read  is cached

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#1755]
hello server reads the data in the db at the first login and caches it, I think when I leave the game and change the value in the db, when I enter the game again, it becomes old again, how can I access all the characters cached on the server side?

**Comment by BarzoStrike** [comment]
first turn off the server, then change the database, turn it on again
if you want to use it in working condition use gm commands

**Comment by CLAXES** [comment]
> 

I am trying to make a sorting system, it does not work with the code I made from the db, so I need to access all the characters that the server caches.

**Comment by CLAXES** [comment]
I am trying to make a sorting system, it does not work with the code I made from the db, so I need to access all the characters that the server caches.

**Comment by CLAXES** [comment]
After entering the game once, I think it caches the character (cachedUserCharacter) The cached character does not change when I process from the db, that is, I write code from the server, but this time the characters that do not enter the game are not in the cache, so it is miss again.

**Comment by insthync** [comment]
I've added disable cache reading setting to the MMO part. But I think for item sorting you should not do it at a database, don't know you plan to get it to work, but you can use RPC to write networking codes to tell the server to sort it.
