### ISSUE TITLE
Partial Classes Again XD

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1757]
Can ItemCraftFormula be made a partial 

And like any class thats connected to the GameDatabase Scriptable would help alot. Most of them already are tho.

This is becuase in order to create like a generator for various Gamedata, we need like getters and setters in these classes.
adding a partial, we can extend the class add a setter and done, instead having to inheritance.

**Comment by ljars** [comment]
Can you make BaseUISceneGameplay partial too? UISceneGameplay is partial, but not BaseUISceneGameplay.

**Comment by insthync** [comment]
Did it in 1.79
