### ISSUE TITLE
rewired HotKey

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1759]
what are the keys names of the hot bar shortcuts? I'm having trouble putting the hot bar action on rewired.

**Comment by insthync** [comment]
Will add it in next version

**Comment by juniormagalhaes** [comment]
> Will add it in next version

:D

**Comment by juniormagalhaes** [comment]
Do you have a forecast for when the Console UI Controls (PS/XBox/Nintendo Switch) will be released?

XD
