### ISSUE TITLE
Monster attack not only character but also his buildings

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#176]
I'm now trying to make monsters to attack not only my character but also my buildings like fens, walls.
I'm looking into monstercharacterentity file but I'm still not able to make this work.
Can you give me any hint for this?

**Comment by insthync** [comment]
First thing you should do is see codes in `MonsterActivityComponent` → `FindEnemy(Vector3 currentPosition)` function. See how it find enemy and how it set set attack target. You may just add codes to find building around the monster then change set attack target codes from 
`CacheEntity.SetAttackTarget(characterEntity)` to ` CacheEntity.SetTargetEntity(characterEntity);`

**Comment by dglee2592** [comment]
Thanks for the advice! I'll try!
