### ISSUE TITLE
[Bug]Code Building Door

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1761]
the code for building door has a bug. sometimes you can enter 4 digits then next time only 2 and sometimes only 1
so you are not able to enter code

**Comment by insthync** [comment]
Only doors?

**Comment by moepi2k** [comment]
Good question, only tried with doors, i will check if it happen with storage too, but this is an old bug. I reported it over a year ago :p

**Comment by insthync** [comment]
I can't reproduce it yet, What is the component that you said it can enter 4 digits, is it an input fields ?

**Comment by moepi2k** [comment]
Yes the window which aopear when a door or chest is locked. Only happens in mmo. I throws an error in console, i will send it to you when at home

**Comment by insthync** [comment]
Please attach the error messages

**Comment by insthync** [comment]
Reopen if it is still occuring
