### ISSUE TITLE
[Sug]Adding Bool for Hotkey

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1762]
problem is when something is in hotkey it will activate in many diffrent ways like:

drag and drop something then while writing the amount it will activate hotkey if u type the number and in specific hotkey is something assigned.
same for when enter code for chest or door.

**Comment by insthync** [comment]
![Screenshot_408](https://user-images.githubusercontent.com/2697550/226601490-c478c267-5e1c-4ea1-92d5-de8e437f2133.png)

Already checked it.
