### ISSUE TITLE
Monster movement

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#1763]
https://user-images.githubusercontent.com/95127578/200060315-64a93f73-5b10-4b6a-958c-1b0669998084.mp4

Why do monsters behave like this? What should I do?

**Comment by insthync** [comment]
May check the monster move animation.

**Comment by insthync** [comment]
Your monster moves animation is root motion animation?

**Comment by CLAXES** [comment]
I remove the running animations and it still comes with a pause, it's not about the animation, I think there is another reason, I add it the same way as the monsters added in the demo, why is this happening?

**Comment by CLAXES** [comment]
I have the same problem when I add the monsters from the demo, there is something else.

**Comment by insthync** [comment]
Why did you ask why?

**Comment by insthync** [comment]
If you want me to help don't ask why because I don't know why.

I don't know why because I don't know how you setup it.

you should ask me to remote to your device to check your project.

**Comment by CLAXES** [comment]
I was getting bake with navmesh surface, the problem was solved when I got bake from the nagivation section, the issue can be closed
