### ISSUE TITLE
[Bug]Campfire

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1764]
in 178d campfire is bugged
https://gyazo.com/58ac0b65015c2144368991f64ad4f922
https://gyazo.com/b4cb04f02b4224c09273095d4bdae20c
https://gyazo.com/a9796c4fb1687d6b26fc3c82745496e3

it no longer convert items you set in prefab.
and the fuel also is random consuming, sometimes it consume 1 then later it consumes 7 each time

**Comment by insthync** [comment]
No, it is not random, it is random by time, just do not convert immediately it will convert every second, this is to reduce database usage.

**Comment by moepi2k** [comment]
so its tent to be like that or a bug?

**Comment by insthync** [comment]
Try add this `preparedConvertItems.Clear();`

![Screenshot_148](https://user-images.githubusercontent.com/2697550/200116760-a62dc2b4-1423-48f6-b798-4af9402b63ac.png)

**Comment by moepi2k** [comment]
that not fix the problem
https://gyazo.com/d4497bb6ac2addeb6c40fb50d986f276
it consume more and more from time to time and non fuel items not converting also

**Comment by moepi2k** [comment]
i think you need to change convert interval in default kit from 1 to eg 5 to test. it only works for the first converting, after that it consume it every second

**Comment by insthync** [comment]
I can't reproduce it yet, my result https://youtu.be/nOANyQZyFbg

This is my settings:

![Screenshot_150](https://user-images.githubusercontent.com/2697550/200240828-199d0155-c2bb-41c6-835b-61e11027aa37.png)

**Comment by insthync** [comment]
I only can find wrong amount issues which can fix like this: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/3cab0b0c9c46e8af37894f335dbb7d1aebe97042

**Comment by moepi2k** [comment]
i dont know why it works for you, but it wont in my project and also not in a fresh project
https://gyazo.com/42d4ade9b9ebb0ab7ac85479c2b9ac96
https://gyazo.com/0b05fa5a638ba9ecb3db132297a265f4

you can see when i turn it on the first 5 sec it not convert the wood,  then after 5 seconds it convert every second
