### ISSUE TITLE
2D monster problem

### ISSUE THREAD

**Issue by alexengel1992** [suriyun-production/mmorpg-kit-docs#1765]
I installed the MMORPG KIT and I didn't change anything, I found an error in which the monster has no animation..

![image](https://user-images.githubusercontent.com/83098223/200084754-a5440eb1-6465-454b-bf4e-7c29f045dc1c.png)

**Comment by insthync** [comment]
![Screenshot_147](https://user-images.githubusercontent.com/2697550/200092390-cbccba46-0c22-4254-b1b4-037acabd1f8c.png)

Animation clip setting is missing set up them to `OrcsArcher2D` prefab

**Comment by alexengel1992** [comment]
Thank you so much you are the best in the world.
