### ISSUE TITLE
TopDownController2D (Aim at cursor possible?)

### ISSUE THREAD

**Issue by MGeistTM** [suriyun-production/mmorpg-kit-docs#177]
Hi, I've recently shrank the scope of my project while trying to learn more about coding and how everything works together before tackling something bigger in 3D.  The project I have in mind is more of an isometric 2D pixelated type game.  

However I'd really like to be able to find a controller where the cursor is essentially the direction the character is attacking.  (Whether its 4 diretions, 8, 16 or more).   Heroes of Hammerwatch or Enter the Gungeon are an idea of what I mean.  I'd like the player to move around with WASD and have the cursor be the target anywhere on the screen so if the player fired arrows lets say, they would go towards the cursor, instead of automatically straight at enemies and hopefully require a bit more hands on playing.  

Currently I'm unable to modify the controller enough to figure out how to do this as there seems to be multiple layers involved and I'm not sure what affects what right now.  Is this something we could possibly add or any suggestion you could make that might help me accomplish this in 2D?

**Comment by insthync** [comment]
Yes, it's possible, whats have to be done is modify the character controller codes to order character to rotate / look follow mouse position. I will make that scripts as open repository later.

**Comment by MGeistTM** [comment]
Thank you, look forward to trying it out!

**Comment by Fallen01** [comment]
Did this ever happen, I'm deeply in need. I've noticed if you switch to wasd movement in 2d on mobile you lose all ability to target. I'd love a fix for this.

**Comment by wtfcolt** [comment]
I'd also love to see this happen!

**Comment by insthync** [comment]
I will start to develop it this weekend.

**Comment by insthync** [comment]
Try this: https://github.com/insthync/UnityMultiplayerARPG_AimAtCursorController

**Comment by insthync** [comment]
Did anyone try it ?

**Comment by wtfcolt** [comment]
I tried it. It's a pretty good start, I like it a lot. However, I noticed a few issues.

Aiming seems off. Only straight up or down shots seem to be accurate to the cursor. Angle shots don't appear to go towards cursor. (Off topic, but FPS aim feels inaccurate too)
![image](https://user-images.githubusercontent.com/1743424/75288911-3cf76a00-57eb-11ea-9ee8-728a7b18416d.png)

I cannot get some heal spells to work. (Heal, first spell on default chars)

Spells where you place area affect only appear under character, like "Poison Area"

Sometimes you fire by clicking UI elements, such as assigning hotkeys.

Walking backwards (look up, walk down with S key) causes player model to go halfway underground
![image](https://user-images.githubusercontent.com/1743424/75289196-bdb66600-57eb-11ea-8d65-38b4e8b3aef1.png)

**Comment by insthync** [comment]
About shot position not the same with aim cursor, it's because of camera view. 
About area skill, it was fixed.
About backward animation it's because backward movement animation does not set to character model.

I will close this if you having issues with the controller, post it on https://github.com/insthync/UnityMultiplayerARPG_AimAtCursorController/issues
