### ISSUE TITLE
Download Assetbundle via digital ocean server URL

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1771]
I am using asset bundle to download files from digital ocean server.But I cannot access it.I get this error.

![server](https://user-images.githubusercontent.com/11313412/200305078-02ebb1e2-0dea-4404-8941-0e147a51b1c3.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/11313412/200305082-a08504a4-002e-4834-a48f-21c59f8be69b.PNG)

**Comment by insthync** [comment]
I think the url is wrong
