### ISSUE TITLE
Dialogs Issue

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#1772]
NPC Dialogs are not working in Builds 
 I am working in Mono > .Net Framework 2.1

**Comment by insthync** [comment]
How does it not work?

**Comment by Deepankar1993** [comment]
NPC dialog doesn't open when clicked or double-clicked on NPC

**Comment by insthync** [comment]
How you setup it? I hope it won't be object id issues again that I told you how to fix it already.

**Comment by Deepankar1993** [comment]
No  , I have double checked it. Before build in editor it's working fine just not in build

**Comment by insthync** [comment]
Singleplayer or MMO game?

**Comment by insthync** [comment]
If it is mmo, did you rebuild the server?

**Comment by Deepankar1993** [comment]
Singleplayer

**Comment by insthync** [comment]
May I try it?

**Comment by Deepankar1993** [comment]
Build of the game ?

**Comment by insthync** [comment]
Your project

**Comment by insthync** [comment]
Maybe via AnyDesk

**Comment by Deepankar1993** [comment]
Sure after office
