### ISSUE TITLE
1.78c changelog

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1773]
What changes were made in the new version, does not appear in the changelog

**Comment by insthync** [comment]
c?

**Comment by juniormagalhaes** [comment]
> c?

e, sorry hihi

**Comment by insthync** [comment]
If `e`, it is storage item duplication issues fixing but doesn't confirm that it was fixed yet, have to try it.

**Comment by juniormagalhaes** [comment]
> 

ah ok XD
