### ISSUE TITLE
[Bug] WarpPortalDatabase warpToPosition doesnt work with "Disable Cache Reading" enabled

### ISSUE THREAD

**Issue by aliegreeza** [suriyun-production/mmorpg-kit-docs#1774]
When we enable "Disable Cache Reading" and edit warp to position property inside warpportaldatabase; it doesnt work and it gets positions from mysql -> characters -> currentPositionX, currentPositionY, currentPositionZ instead.
![1111](https://user-images.githubusercontent.com/118121169/201530343-d08dc8ec-8d13-4339-9767-4db1f5dd5677.png)
![3333](https://user-images.githubusercontent.com/118121169/201530345-9969aa0e-ae54-4254-a1fb-9f750ecf36c8.png)
![22222](https://user-images.githubusercontent.com/118121169/201530347-325e56fa-dd8b-4348-bc63-50356645964a.png)
![4444444](https://user-images.githubusercontent.com/118121169/201530429-f70879f8-b54c-4f46-b851-6ff9e7c771bf.png)

**Comment by aliegreeza** [comment]
It only happens when you're warping to another map, if you use the warp command for the same map youre in, it does get the warpToPosition right.

**Comment by insthync** [comment]
Do you know that `WarpPortalDatabase` is just a name it doesn't mean that when you change something inside it then it will make an update to the database, it is just a kind of game data that you have to make it updated by rebuild the server, so it is not related to `Disable Cache Reading` at all, so if you set the position, then rebuild the server and when you test it, its position is wrong, it is not because `Disable Cache Reading`.

**Comment by aliegreeza** [comment]
It is because of disable cache reading. When you enable it; It doesnt care which position property you set inside warpportaldatabase -> warpToPosition. It always gets your currentposition values inside characters table.

**Comment by aliegreeza** [comment]
Repro steps:
Disable "Disable Cache Reading"
Edit any warp portal "warpToPosition" property. (Not the warp portal position, the one that sets characters position.)
Rebuild the server and you will see its working, okay now go back to "Disable Cache Reading" property again.
Enable "Disable Cache Reading"
Edit any warp portal "warpToPosition" property again.
Rebuild the server.
You will see it will not get the right position you set inside the property

**Comment by insthync** [comment]
Why have to disable cache reading in first step?

**Comment by insthync** [comment]
So help me find why it is not working properly here : https://github.com/insthync/UnityMultiplayerARPG_MMO/blob/main/Scripts/MMOGame/Database/DatabaseNetworkManager_RequestHandlers.cs

**Comment by insthync** [comment]
You actually don't have to rebuild the server, after setup `warpToPosition` as you wish,  you can set config in `serverConfig.json` -> `databaseDisableCacheReading` to `TRUE` or `FALSE`

**Comment by aliegreeza** [comment]
It gets characters "currentPositionX, currentPositionY, currentPositionZ" values instead "warpToPosition" values when its enabled, thats all i know.
But when you use the warp command inside the same map youre in it works okay. I assume during map switches it disconnects your account and doesnt update something right and gets the previous values due its not cached in server.

**Comment by insthync** [comment]
That is why I don't want to add that function, after I add it then there is only me who has to fix it when having issues.

Try change codes in `UpdateCharacter` function to

```
        protected async UniTaskVoid UpdateCharacter(RequestHandlerData requestHandler, UpdateCharacterReq request, RequestProceedResultDelegate<CharacterResp> result)
        {
#if UNITY_EDITOR || UNITY_SERVER
            PlayerCharacterData character = request.CharacterData;
            // Cache the data, it will be used later
            cachedUserCharacter[character.Id] = character;
            // Update data to database
            Database.UpdateCharacter(character);
            // Response success immediately
            result.Invoke(AckResponseCode.Success, new CharacterResp()
            {
                CharacterData = character
            });
            await UniTask.Yield();
#endif
        }
```

**Comment by aliegreeza** [comment]
I did tried this function and re configured my positions while Disable Cache Reading was enabled. And it did not worked. Its getting my position values from db now as i said above

**Comment by insthync** [comment]
Map Name changed or not?

**Comment by aliegreeza** [comment]
Im very sorry suriyun, it was because i forgot to put just one "," to the updatecharacters query after i have added a new column. Due to that game started acting weirdly. Im very apologizing to took your time for my silly fault.
