### ISSUE TITLE
Moving platform Character controller

### ISSUE THREAD

**Issue by colt0560** [suriyun-production/mmorpg-kit-docs#1775]
Im trying to make a moving platform with character controller but player slides off or falls thru. I use this to get it working ... but once player unparents with platform enemies can no longer do damage to player..

    public class PlayerParent : MonoBehaviour
    {
        private void OnTriggerEnter(Collider other)
        {
            if (other.CompareTag(GameInstance.Singleton.playerTag))
            {
                other.gameObject.transform.parent = transform;
            }
        }

        private void OnTriggerExit(Collider other)
        {
            if (other.CompareTag(GameInstance.Singleton.playerTag))
            {
                other.gameObject.transform.parent = null;
            }
        }

**Comment by insthync** [comment]
Don't know

**Comment by colt0560** [comment]
helpful

**Comment by insthync** [comment]
Yes

**Comment by colt0560** [comment]
its the hitbox attached to player, had to edit the script so it would change its layer different from the players...
