### ISSUE TITLE
[FeatureRequest/Question] Prespwaned Storage with Items in it

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#1776]
Hey there, 

i couldnt find any information regarding my problem. I want to add for example a shelve to my gameword (in the editor mode, so no server running at this time). i also want to set predefined items to it, so that when i start the server i have a spawned storage with items in it. 

is this possible?
(i mean a server spwaned storagebox with predinfed items from a config)

**Comment by Carlito1781** [comment]
Whats the purpose if you don't mind me asking as you can already add starting items upon logging into the game for the first time. Unless your talking about for a single player experience, then it could be beneficial and should be rather easy to accomplish.

**Comment by xnitro1** [comment]
you cant spawn a chest on server startup with filled items in it. the only exception is when you manually edit the SQL file.
i dont know what you mean by "you can already add starting items upon logging into the game for the first time".
Maybe i´m missing something, so please feel to enlighten me if i have overseen something.

but after experimenting a lot on this subjet, it is not possible to spawn a chest with the server with prefilled items in it.

and with a chest i mean the StorageEntity.

**Comment by Carlito1781** [comment]
i was referring to this section (Snapshot below). But then again, was  just a alternative suggestion. Although it was more then likely not what you was trying to achieve. 
![Screenshot_20221127_092915](https://user-images.githubusercontent.com/119147929/204140724-ab9e521a-ed9d-4937-b585-f72b44680b56.png)

**Comment by xnitro1** [comment]
this is no alternative at all, because what you are showing are the start items from the PLAYER (when he is created the first time) and not from a STORAGE. Those are 2 completely different things. I´m talking about storages which are counted as buildings (the chests which a player can craft).

**Comment by insthync** [comment]
Will add it, please wait

**Comment by moepi2k** [comment]
> Whats the purpose if you don't mind me asking as you can already add starting items upon logging into the game for the first time. Unless your talking about for a single player experience, then it could be beneficial and should be rather easy to accomplish.

What he means is a chest prefilled with items where player can out in and out items. Best approach is to have randomness to fill stirage on load
