### ISSUE TITLE
[Issue] build objects inside or under meshs have collider in scene

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1778]
Hi , i have noticed that you can build under objects have colliders  in the scene , i have checked in fresh project too .. like this >> 
![asdf](https://user-images.githubusercontent.com/71017004/202307082-a80cc5b6-25b4-422e-92fb-90a005428113.jpg)
as i know any kind of build should ignore any mesh have a collider

**Comment by insthync** [comment]
Fixed in 1.80c3
