### ISSUE TITLE
BUG Skill Effectivenes Attributes

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#178]
1. For example, with us, the damage of a skill depends on strength.
2. If we initially set 10 str when creating a character, then the skills deal extra damage. (it works)
3. If we equip an item on a character with 10 str, then damage to the skill is not added. (bug)

**Comment by insthync** [comment]
Damages not increased in UI or it's also increased when use skill too?

**Comment by insthync** [comment]
As I tested it works correctly both in UI and when use skill.

**Comment by DimasjkTV** [comment]
> As I tested it works correctly both in UI and when use skill.

I just discovered that I used an attribute bonus from a set item. We do not receive bonus damage if the attributes are obtained using the set.

**Comment by insthync** [comment]
Try changes codes in `GameDataHelpers.cs` 
Line 834 
from `Dictionary<Attribute, float> characterAttributes = character.GetAttributes(); to `Dictionary<Attribute, float> characterAttributes = character.GetCaches().Attributes;`

**Comment by insthync** [comment]
This is also fixed in 1.52, I will close this issue post. If this problem still occurs, you can reopen it.
