### ISSUE TITLE
How to make player still move/walk when menus are open

### ISSUE THREAD

**Issue by colt0560** [suriyun-production/mmorpg-kit-docs#1781]
i want to be able to make player move and walk even wen the menus are open, such as inventory and such. i encounter a bug where i drag items and it locks my cursor and player cant do anything

**Comment by khongtuong** [comment]
Join the community, they'll help you, this is not the place to ask for question
https://discord.gg/d6UyczA5

**Comment by colt0560** [comment]
The issue is cursor locks when dragging items then you can’t do nothing  ,
happens on a new project too

**Comment by khongtuong** [comment]
can you upload a clip, and if you want to make player move and walk even when the menus are open, just disable UI Blocking Controler

**Comment by colt0560** [comment]
That’s the answer right there ! Thanks a lot

**Comment by khongtuong** [comment]
please close the issue :)
