### ISSUE TITLE
[BUG] Canvasgameplay_mobile

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#1783]
there is a bug (at least when compiled for android) that prevents attacking or assigning skills/items

version: 1.78f

https://imgur.com/a/4d8IQY2

Fresh project:

https://imgur.com/a/zCUduoa

this only happens on a real device since in the editor it works without problems

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1747
