### ISSUE TITLE
[Suggestion] Refine Addons

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1785]
Please add Refine addons like the following: 
1. Item Destroy Protection - if the refine fails and instead of the it getting destroyed, the Protection Item is the one who gets destroyed. 2. Refine Increase Success Rate Item - if a player has this item, he can increase the success rate depending on the Success rate value of the item added.
3. Refine Decrease Gold Fee Rate Item - if this item is added, it can decrease the rate or percentage of gold fee depending on the value of the Decrease gold fee item.
4. Alternate Item Requirements - lets say you will need "RefineStone-A (50% Success)" to refine item to +1, please add an option that a player can use "RefineStone-X (100% Success)" instead.

Thank you!

**Comment by temelkirci** [comment]
I added this in my game.Just create a currency and check it while refining.And use decreasecurrency function.

**Comment by AsheshPlays** [comment]
> I added this in my game.Just create a currency and check it while refining.And use decreasecurrency function.

can you share guide to me??


Discord:
Ashesh#9704

**Comment by temelkirci** [comment]
I added blessing book as currency in my game.


            int upgradeCurrencyCount = 0;
            Currency upgradeCurrency = null;

            foreach (var tempCurrency in GameInstance.PlayingCharacter.Currencies)
            {
                if (tempCurrency.GetCurrency().DefaultTitle == "Blessing Book")
                {
                    upgradeCurrencyCount = tempCurrency.amount;
                    upgradeCurrency = tempCurrency.GetCurrency();

                    uiBlessingBook.text = "Blessing Book : " + upgradeCurrencyCount.ToString();
                }
            }

            CanRefine = false;
            ReachedMaxLevel = false;
            ItemRefineLevel? refineLevel = null;
            if (!characterItem.IsEmptySlot())
            {
                UITextKeys gameMessage = UITextKeys.UI_ERROR_CANNOT_REFINE;
                CanRefine = EquipmentItem != null && characterItem.GetItem().CanRefine(GameInstance.PlayingCharacter, Level, out gameMessage);
                if (CanRefine)
                {
                    refineLevel = EquipmentItem.ItemRefine.Levels[Level - 1];
                    
                    if (Level > 3)
                        uiWarningDestroy.SetActive(true);
                    else
                        uiWarningDestroy.SetActive(false);

                }
                else
                {
                    switch (gameMessage)
                    {
                        case UITextKeys.UI_ERROR_REFINE_ITEM_REACHED_MAX_LEVEL:
                            ReachedMaxLevel = true;
                            break;
                        case UITextKeys.UI_ERROR_NOT_ENOUGH_GOLD:
                        case UITextKeys.UI_ERROR_NOT_ENOUGH_ITEMS:
                        case UITextKeys.UI_ERROR_NOT_ENOUGH_CURRENCY_AMOUNTS:
                            refineLevel = EquipmentItem.ItemRefine.Levels[Level - 1];
                            break;
                    }
                }
            }

**Comment by temelkirci** [comment]
private static bool RefineItem(IPlayerCharacterData character, CharacterItem refiningItem, System.Action<CharacterItem> onRefine, System.Action onDestroy, out UITextKeys gameMessage)
        {
            if (refiningItem.IsEmptySlot())
            {
                // Cannot refine because character item is empty
                gameMessage = UITextKeys.UI_ERROR_ITEM_NOT_FOUND;
                return false;
            }
            BaseItem equipmentItem = refiningItem.GetEquipmentItem() as BaseItem;
            if (equipmentItem == null)
            {
                // Cannot refine because it's not equipment item
                gameMessage = UITextKeys.UI_ERROR_ITEM_NOT_EQUIPMENT;
                return false;
            }
            if (!equipmentItem.CanRefine(character, refiningItem.level, out gameMessage))
            {
                // Cannot refine because of some reasons
                return false;
            }
            ItemRefineLevel refineLevel = equipmentItem.ItemRefine.Levels[refiningItem.level - 1];
            if (Random.value <= refineLevel.SuccessRate)
            {
                // If success, increase item level
                gameMessage = UITextKeys.UI_REFINE_SUCCESS;
                ++refiningItem.level;
                onRefine.Invoke(refiningItem);
            }
            else
            {
                // Fail
                gameMessage = UITextKeys.UI_REFINE_FAIL;
                if (refineLevel.RefineFailDestroyItem)
                {
                    int upgradeCurrencyCount = 0;
                    Currency upgradeCurrency = null;

                    foreach(var tempCurrency in character.Currencies)
                    {
                        if(tempCurrency.GetCurrency().DefaultTitle == "Blessing Book")
                        {
                            upgradeCurrencyCount = tempCurrency.amount;
                            upgradeCurrency = tempCurrency.GetCurrency();
                        }
                    }

                    if(upgradeCurrency != null)
                    {
                        if (upgradeCurrencyCount > 0)
                        {
                            character.DecreaseCurrency(upgradeCurrency, 1);

                            refiningItem.level -= refineLevel.RefineFailDecreaseLevels;

                            if (refiningItem.level < 1)
                                refiningItem.level = 1;
                            onRefine.Invoke(refiningItem);
                        }
                        else
                        {
                            // If condition when fail is it has to be destroyed
                            onDestroy.Invoke();
                        }
                    }
                    else
                    {
                        // If condition when fail is it has to be destroyed
                        onDestroy.Invoke();
                    }
                }
                else
                {
                    // If condition when fail is reduce its level
                    refiningItem.level -= refineLevel.RefineFailDecreaseLevels;
                    if (refiningItem.level < 1)
                        refiningItem.level = 1;
                    onRefine.Invoke(refiningItem);
                }
            }
            if (refineLevel.RequireItems != null)
            {
                // Decrease required items
                character.DecreaseItems(refineLevel.RequireItems);
                character.FillEmptySlots();
            }
            // Decrease required gold
            GameInstance.Singleton.GameplayRule.DecreaseCurrenciesWhenRefineItem(character, refineLevel);
            return true;
        }
    }

**Comment by temelkirci** [comment]
works very well

**Comment by AsheshPlays** [comment]
> works very well

do i just make them inyo a .cs file?? because im really really bad at making extensions or addons.. sorry for the hassle tho 😓

**Comment by insthync** [comment]
Implemented in 1.80b
