### ISSUE TITLE
[Suggestion] Item Damage Amount Increase Each Level

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1786]
Is it possible to add Percentage Increase Each Level of the Damage Base Amount instead of just adding same value each level? This means, everytime an item is refined, the additional damage added each level increases.

Here's an example:

Sword: 
Base Amount Damage (80-100)
Damage Rate Increase Each Level: 20% (or any rate the Developer enters)
Refine Level 1 = Base Amount Damage + 20% = 96-120 (Damage added is 16-20)
Refine Level 2 = Base Amount Damage + 20% = 115-144 (Damage added is 19-24)
Refine Level 3 = Base Amount Damage + 20% = 138-172 (Damage added is 23-28)

This is to give the refine level more  worth as the refine level increases. 

That is all. Thank you! And keep up the good work!

**Comment by khongtuong** [comment]
![image](https://user-images.githubusercontent.com/6816616/207781910-effa249b-514f-4f65-af63-8a356b5aa699.png)
already there

**Comment by AsheshPlays** [comment]
hello sir.. what i mean with incremental is not static.. lets say +1 to +5
i can put 10-20 dmg increase and when it goes to +6 til +10, i want the
increase dmg maybe 30-50 increase per level

**Comment by insthync** [comment]
How the setting should be? how about its performance when calculating damage?

**Comment by insthync** [comment]
And when I change this one, I will have to change the other (such as buff bonus) later because it will have someone request for it.

**Comment by AsheshPlays** [comment]
But it would be very nice if we had option in how to implement Dmg Increase per Level..

Because other mmorpg games mostly dont use static incremental.


Current Settings on KIT:

Example:

Sword Default Damage: 5-10
Damage Increase per Level: 5-5
+1 = 10-15
+2 = 15-20
+3 = 20-25
+4 = 25-30
+5 = 30-35
This setup will always give the same amount of additional damage per level and will have smaller and smaller worth as the level of item go up..

But if we can make it increase by percentage like lets say I input 10%, result of additional dmage per level is also increasing as the level go up..

**Comment by insthync** [comment]
Implemented in 1.79
