### ISSUE TITLE
[Suggestion] Tab Changes Selected Fields

### ISSUE THREAD

**Issue by Carlito1781** [suriyun-production/mmorpg-kit-docs#1788]
One thing that really bothered me and seemed really easy to add was tabbing to go to the next field. Although this is super simple I feel it should already exists. 

I'm not sure if its the correct way to do it as I'm fairly new with unity. But I created a new script and attached it to both UILogin and UIRegister.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class changeField : MonoBehaviour
{
    public InputFieldWrapper uiTextUsername;
    public InputFieldWrapper uiTextPassword;
    
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Tab)) {
            if(uiTextUsername.isFocused) {
                uiTextPassword.Select();
            }
        }
    }
}
```

![Screenshot_20221127_051432](https://user-images.githubusercontent.com/119147929/204129947-daac953a-41d8-41db-9375-10fb75e72791.png)

**Comment by insthync** [comment]
It is too easy to do, I won't do it.
