### ISSUE TITLE
Connection to server Rejected.

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1789]
Before we was having alot of issues with User already logged in, even with the update to disconnect connection if already online. it was still going on, some connections werent cleared properly.

in 1.78d
![image](https://user-images.githubusercontent.com/7702658/204361313-4fdc8f64-b572-49a6-99a6-ee8d7c222cbf.png)

This was added, the User already logged in issue was gone, people still connect. but now u cant start game. Client is always not ready, 
and u get Connection to server rejected.

![image](https://user-images.githubusercontent.com/7702658/204361471-fc8a5083-0f81-4df6-8472-c9584c8a877b.png)

This is from one of our users.
https://user-images.githubusercontent.com/7702658/204361558-1848f29a-03bf-4908-a966-a4acca6deda5.mp4

The only way to fix it is rebooting the server. so its a problem with caches ingame.

**Comment by Callepo** [comment]
im testing this atm, to forcefully destroy the cached player..
idk if it works, but atleast its not gonna return false, and give connection rejected.
![image](https://user-images.githubusercontent.com/7702658/204380139-c7e08465-6654-4ff3-8ccc-3574d64d9476.png)

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/204413628-5cb28da3-36f5-4db5-84e7-8e94217d8191.png)

I added logs all over to try and find where it crashes..
![image](https://user-images.githubusercontent.com/7702658/204413667-b0ecd418-9ea9-478f-8441-fd69f0c361e3.png)

This is the reason players are locked out and cant play untill i reboot the server, like i said Cache issue. the cache is not cleared properly when u crash/ dc

**Comment by moepi2k** [comment]
I have similar issues, some player get rejected from server just while playing. sometimes they can just relog. sometimes a server restart is required. but now i have a more critical issue and i cant find the source.

few players have that issue. they can login but they cant interact with stuff and cant switch maps. everytime when they interact with something they get an error "not logged in"

https://media.discordapp.net/attachments/908286014471163914/1042644622284963850/20221116203432_1.jpg?width=1298&height=670

the thing is. they can drop all items from inventory to ground. other player can take it. then he can just log out and relog and everything is like it was before. same inventory same position as beginning. it seems everything they do are not stored db. 

those player are bugged that much that even a server restart not fix it. they cant play the game anymore. i dont know what to do

**Comment by insthync** [comment]
@moepi2k Did you apply this ? https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/089c835333bebd6448685ab40b11f2fb273f8a72

**Comment by moepi2k** [comment]
let me check when at home. is this in 178g?

**Comment by insthync** [comment]
Yes, it is.

**Comment by Callepo** [comment]
@insthync did u see my above comments with cache?

**Comment by insthync** [comment]
Yes, I see, I will fix it.

**Comment by moepi2k** [comment]
> @moepi2k Did you apply this ? [insthync/UnityMultiplayerARPG_MMO@089c835](https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/089c835333bebd6448685ab40b11f2fb273f8a72)

This is not working. Ppl who played for that update can login, all new player get this error when register https://media.discordapp.net/attachments/799960569594642443/1047602613807489114/image.png

I need to downgrde again

**Comment by moepi2k** [comment]
@insthync the few players who had the issue with https://media.discordapp.net/attachments/1032170063920373860/1042567892304146453/image.png

Are no longer able to login with the new changes. They stuck in loading screen

@insthync

**Comment by insthync** [comment]
But still can enter a game?

**Comment by moepi2k** [comment]
No longer can enter the game.. other ppl report this now:

**Title:** My char is duplicated
**Text:** I can see my character where i logged off a few minutes ago.
**Player Name;** Fabiano
**Player Position;** (0.0, 0.0, 0.0)
**Current Map;** Schimmerstein

**Comment by insthync** [comment]
Still can drop items with the character?

**Comment by moepi2k** [comment]
No as i said, the guys with the error hang in loading screen, they cant login. Tje duplicate player thing is a new bug now.

**Comment by insthync** [comment]
Confused about that, it has 2 of the same player in the game?

**Comment by moepi2k** [comment]
yes, thats an issue we reported many times in the past. it can happen in diffrent situations. for example when you use that https://gyazo.com/475d3ef1e54bbe64f3d1b05cc1a4963e with a higher amount. 

but i dont get reported that issue for long time since yesterday when i updated server with the new changes.

**Comment by insthync** [comment]
@Callepo Try this: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/e21f1ae4391a27961c7c23afa0b951d084940fdb

If it still not working, try add unregister function here: 

![Screenshot_214](https://user-images.githubusercontent.com/2697550/205272702-abb63351-384c-460b-bf72-68bd0206f264.png)

**Comment by Callepo** [comment]
i didnt try yet, cuase my changes worked and i didnt update kit , i will try it and let u know

**Comment by Callepo** [comment]
The fix above didnt work, 
https://user-images.githubusercontent.com/2697550/205272702-abb63351-384c-460b-bf72-68bd0206f264.png

im trying this one now and see

**Comment by moepi2k** [comment]
Mthis should be reopen, because the bug is still there. Alot of duplicated players

**Comment by insthync** [comment]
When will I see your error logs ?

**Comment by insthync** [comment]
It's probably an error from other source

**Comment by insthync** [comment]
Do you determine that a reject problem is the same with duplicating players?
