### ISSUE TITLE
Destroy Respawn Delay of monsters/harvestables are neglected when every scene load

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#179]
At this moment monsters/harvestables are respawned when load a scene regardless they were destroyed or not. 
i.e, regardless of remaining delay time, they are respawned when load the scene. 
I want to respawn monsters/harvestables after "Destory Respawn Delay" all time. 
I'm looking at the "NetworkSpawn" code but I'm so dizzy about this. 
Do I need to make all monster/harvestable entities save own remaining delay time?
Can you give me any hint for this?

**Comment by insthync** [comment]
Oh, about NetworkSpawn function it's the function which will call at the server after instantiated the prefab to tell clients that the prefab was instantiated so the client will have the same instantiated object.

the `destroyRespawnDelay` is a delay before respawning next time after the monster/harvestables dead and destroyed.

The current game system did not save dead time for monster/harvestables yet. So when scene loaded it will spawn monster/harvestables immediately by `MonsterSpawnArea` and `HarvestableSpawnArea`.

**Comment by insthync** [comment]
Are you making offline game?

**Comment by dglee2592** [comment]
Thank you very much for the comments!!

Yes, I'm making mobile offline game but I want to allow Lan game if possible.

**Comment by dglee2592** [comment]
For my game, I'll put all monsters/harvestables to each scene by hand so I'll not use SpawnArea and SpawnAll.
Like a Big Orca Warrior in the Kit
