### ISSUE TITLE
Wrong msg when same name

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1791]
when try making new player with existing name you get the wrong msg

https://gyazo.com/edcdba72a3bd3c9b543f3a166017f6eb

**Comment by insthync** [comment]
As I try it is still working properly

**Comment by moepi2k** [comment]
ok weird, just found this in the languageManager.cs
https://gyazo.com/7ba6a16ac3826ae718310bcb29d786a5

**Comment by insthync** [comment]
Hmm, the migration system is working incorrectly for some keys, but you can change the message to fix it.

**Comment by moepi2k** [comment]
thats what i did now, thx
