### ISSUE TITLE
[Bug]Gm Commands

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1793]
/warp_to_character and /summon no longer working in 178g

**Comment by insthync** [comment]
Is it working In the same scene ?

**Comment by moepi2k** [comment]
no

**Comment by insthync** [comment]
Fixed: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/070483fd3311277950ba25d04be10dd2cf106b84

**Comment by insthync** [comment]
Is this fixed?

**Comment by moepi2k** [comment]
its fixed, thank you very much
