### ISSUE TITLE
Can't Show Building Menu 

### ISSUE THREAD

**Issue by colt0560** [suriyun-production/mmorpg-kit-docs#1794]
I updated from a older version of 1.78, and now current building menu doesnt show anymore when hold e on building entity

**Comment by colt0560** [comment]
however i did not update the uicanvasgameplay prefab. is this part of the issue?

**Comment by colt0560** [comment]
Okay so i imported a brand new project and still cant show current building settings when hold E on building item

**Comment by khongtuong** [comment]
> As I try, it can hold `e` on door to show the dialog, but press `e` while there is nothing ahead will shows character is so far message, I will fix it.
> 
> https://youtu.be/RxKDB--6yGA

and one more thing that shooter control hold E can open menu but can't use to set password or do anything else, i tested in clean source
[https://zone69.net/images/1.MP4](url)

**Comment by insthync** [comment]
Fixed, thank you for bug reporting

**Comment by colt0560** [comment]
I dont get why for me , i cant open the build settings still. I just imported it another blank project with int_shooter scene. I'm holding E, im holding F... idk why i just dont see it

**Comment by colt0560** [comment]
but what script did u change to fix the character to far issue? i only want to updated that script

**Comment by insthync** [comment]
@colt0560 Seems like you should make an appointment to let me access your PC to applies an update

**Comment by colt0560** [comment]
can i make an apt? i really want to get the build menu working properly again, will pay if needed

**Comment by insthync** [comment]
This Sunday?

**Comment by colt0560** [comment]
That’s fine, what is best way to contact you?

**Comment by insthync** [comment]
My email: ittipon.bay@gmail.com

**Comment by colt0560** [comment]
im ready
