### ISSUE TITLE
Question Equipment socket

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1795]
When changing the equipment, everything is normal, but when I remove the equipment, the sockets that should remain closed open. You will notice when you use equipment sockets together.

https://www.youtube.com/watch?v=HKpxoGk7qvA

**Comment by insthync** [comment]
Use the same equip socket name?

**Comment by BarzoStrike** [comment]
yes
Same thing happens when I try different name

**Comment by BarzoStrike** [comment]
For example i have a bust and i have pants i need to hide the character's leg for both, it looks bad if i don't add an empty leg socket to one of them. When I dress, everything is fine, but when removing, the leg that should not be seen is visible. There is a common socket in both equipment, it still opens when it should be closed.

Am I doing it wrong somewhere, no matter how hard I tried, I couldn't find it

**Comment by insthync** [comment]
In 1.80, I've added `Priority` to `Equipment Model`, use it in case you want to instantiate the equipment model to the same socket but want to hide others which having lesser priority. 

Try use it and reopen if you still having an isssues
