### ISSUE TITLE
I found a few timeout errors in log files

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1796]
My players report disconnect issue every 15-20 minutes, and pet level issue.I have checked log files in server.I found these DatabaseNetwork issues.

ERROR DatabaseNetworkManager [2022-12-09 10:54:39] - Cannot UpdateCharacterAsync status: Timeout
ERROR DatabaseNetworkManager [2022-12-09 07:47:05] - Cannot GetFriendRequestNotificationAsync status: Timeout
ERROR DatabaseNetworkManager [2022-12-08 01:29:27] - Cannot GetMailNotificationAsync status: Timeout
ERROR DatabaseNetworkManager [2022-12-07 22:17:13] - Cannot SetSummonBuffsAsync status: Timeout
ERROR DatabaseNetworkManager [2022-12-07 12:03:30] - Cannot ClearCharacterPartyAsync status: Timeout
ERROR DatabaseNetworkManager [2022-12-05 20:31:54] - Cannot ReadCharacterAsync status: Timeout
ERROR DatabaseNetworkManager [2022-12-09 06:31:05] - Cannot ReadGuildAsync status: Timeout

are these normal ?

Maybe these errors sometimes block server and database.

**Comment by insthync** [comment]
No, not normal. Did you runs database management server in differently device?

**Comment by temelkirci** [comment]
I am using MySQL.

**Comment by insthync** [comment]
Talked about this in other post, so I will close this one
