### ISSUE TITLE
Gacha Timeout error in MMO mode

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1797]
I added free gifts every 15 minutes in my mmorpg game.But when click free open button, wait 15-20 seconds and get timeout error dialog on my screen.Where is problem ?

It works in Singleplayer mode very well.

**Comment by temelkirci** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/11313412/206836345-e484a8b8-15c0-4fda-b5ce-a865249d35db.PNG)

I am using BaseGameNetworkManager.Singleton.ServerTimestamp

**Comment by insthync** [comment]
How it work when you press receive reward button?

**Comment by temelkirci** [comment]
İt keep start time and counting 15 minutes, when it run out, my static variable set to true to obtain free reward.

![Ekran Alıntısı](https://user-images.githubusercontent.com/11313412/206837167-2c81e252-abeb-4a45-bba8-585056a99663.PNG)

Everythink is ok but respond is timeout.Works in sinle player very well
