### ISSUE TITLE
[Bug]Auction House

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1798]
few bugs in auctions house. posting it here as we talked

1) https://gyazo.com/e880a5b3618990e120e72ffb2f97329d
when sell an item for high amount. the item will show as negative number in list (assuming its because of SHORT) -> maybe better to use INT since short limit is only 32k

2) https://gyazo.com/65c1b5ef69865ce336ce1fa96c70ee86
the switching page list not work properly. it not switch and throws some error

3) https://gyazo.com/1409d5fa4db4ce0afa6dc74c8f0ac82b
when sell an item and write a higher amount then you have in inventory, the message show 'Invaild Item Index' instead of something like 'You dont have that much items'

4) https://gyazo.com/38cc6852d0681965721a2064bdf82a12 there is a way to bid when have 0 gold in inventory, so the amount of gold becomes negative.

5) then some random weird msg appears like 
https://gyazo.com/91d17e72e7cedbd981fcb86ae1f0c13a 
and 
https://gyazo.com/ab8f0e0c1dab9bb4584e49849e09f253

Suggestion -> an option to cancle an current auction when there is not already set  a bid from someone would make sense. (in case when player set wrong sell amount for example)

**Comment by insthync** [comment]
All done

**Comment by moepi2k** [comment]
that was fast xD, thx i will check it out
