### ISSUE TITLE
[Suggestion] Skill buff restriction

### ISSUE THREAD

**Issue by khongtuong** [suriyun-production/mmorpg-kit-docs#1799]
Add a skill restrict list to restrict use when this skill is on, to avoid multiple buff at once, because if you use 1 buff with high level, it's effect still lower than multiple buff with low level, it's hard to balance the game.

**Comment by insthync** [comment]
How it work?

**Comment by khongtuong** [comment]
Check that current skill buff is using and then forbid another skill in specific list, mean you can't use the same type of skill in the same time (ex: buff dmg element fire can't use when buff dmg element ice is in use, because it's add more dmg to user, make it extremetly like god mode), i'm currently can't find a way to get current skill are using on character.

**Comment by moepi2k** [comment]
is this not doing the same? i use that kind of logic to check if an entity has specific buff on it to remove the buff when damage applied https://gyazo.com/59be1462ef30da7a64f87119aeaa08d1

**Comment by insthync** [comment]
I read his/her condition, I think it is pretty complex

**Comment by khongtuong** [comment]
> is this not doing the same? i use that kind of logic to check if an entity has specific buff on it to remove the buff when damage applied https://gyazo.com/59be1462ef30da7a64f87119aeaa08d1
> 
> not checked performance yet but i cant notice any performance drop so far

something like that, but we can debuff current buff or restrict to use new buff, i dont think this will affected perfomance, we just check some kind of buff.

**Comment by insthync** [comment]
How are you going to check some kind of buff?, how are you going to define kind of buff?

**Comment by moepi2k** [comment]
as i undrstand him correctly he mean actually exactly that
https://gyazo.com/59be1462ef30da7a64f87119aeaa08d1

an option on skills like in this case DoNotRemoveOnDead. but maybe an array where u can fill with Skills to restrict in the applybuff

https://gyazo.com/5e9c399b8d1fc8acd78d9facb2a7e2e2

**Comment by insthync** [comment]
@khongtuong Answer me

**Comment by insthync** [comment]
Seems like you are going to request what you do not really know how works, you just want something, so how can I implement it, if I implement it and it does not fit your need, then I have to reimplement it?

**Comment by insthync** [comment]
So when applying a new buff, it will have to loop an old list to find and make a list of restricting skills, then use that list to decide whether to apply a new buff or not. How about buff from potion/weapon?

**Comment by insthync** [comment]
And will I have to make a restriction for debuff?

**Comment by khongtuong** [comment]
> So when applying a new buff, it will have to loop an old list to find and make a list of restricting skills, then use that list to decide whether to apply a new buff or not. How about buff from potion/weapon?
yes, and potion/weapon is an extra buff, you can use it, that's not the problem.

> And will I have to make a restriction for debuff?
if we can use restricting skill for buff, we can use it like a skill effect to restrict buff, so we dont need a restriction for debuff

**Comment by insthync** [comment]
Implemented in 1.79

it will has a `tag` and `restrictTags` in buff settings
