### ISSUE TITLE
CanvasGameplay UI Buttons not working with Rewired

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1801]
https://gyazo.com/726826577215a1df6217bd8e53a84a7c

all others works only the one from Canvas not

**Comment by insthync** [comment]
Did you try to use the button name? And how you setup it?

**Comment by insthync** [comment]
As I try it work, my setup is like yours

**Comment by insthync** [comment]
You may try debugging like this

![Screenshot_223](https://user-images.githubusercontent.com/2697550/207630600-244765ae-6fcd-4990-b944-1889b4de0558.png)

**Comment by moepi2k** [comment]
catch nothing, only all other buttons which are set outside of canvas.
also in the controlmapper the setting buttons are not visible from canvas.
do you set keycode to none for those?

https://gyazo.com/79f00894d3264eeec2ee9334b6fe6c99
