### ISSUE TITLE
Missile Pool issue

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1802]
when you use all the items in the pool, example 30 missile, on 31 you get this error, and it no longer launches the missile.

https://prnt.sc/h_RNTtBbLjzn

**Comment by insthync** [comment]
![Screenshot_225](https://user-images.githubusercontent.com/2697550/208120331-b1633c26-44e0-4afe-81cd-432a214f294b.png)

It must instantiate new object

**Comment by insthync** [comment]
Did the pooled object being destroyed?

**Comment by insthync** [comment]
From this video: https://youtu.be/SvJhGsHQw6c

If it reached max pool size, it will instantiates a new object

When pushing back to the pool collection, if the collection size reached the max pool size, it won't be enqueued to the collection, it will be destroyed.

**Comment by juniormagalhaes** [comment]
on monsters it's ok, try to use it in a player's skill or in a weapon

**Comment by insthync** [comment]
My test result https://youtu.be/Bw4rgNYR3Tw

**Comment by insthync** [comment]
https://youtu.be/YBX4ObaLIyU

**Comment by juniormagalhaes** [comment]
I'll see if I fucked up somewhere then XD
