### ISSUE TITLE
[Suggesstion ] Item Dialog(Bonuses) for Auction House

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1804]
Are you thinking to add item dialog for items on Auction house when players click an item.Because players want to see their bonuses and attributes before buy an item from auction house.This is very important.Also players can be cancel their item if they want to cancel it.Would be better these features for auction house

**Comment by moepi2k** [comment]
show item dialog has nothing todo with acution house. thats a thnig which is already in the kit. you just need to change to your need. -> https://gyazo.com/b84a21b848173f06cc29bc25e6f83731

cancle auction is already implemented. maybe you need to update to latest version

**Comment by temelkirci** [comment]
@moepi2k  solved thank you
