### ISSUE TITLE
Suggestion: Requirements for Task Quests

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1805]
I have a quest that the player talks to the owner of the tavern to kill a spider that is scaring the customers, the quest has two tasks, one to talk to the customers in order to find the spider's lair and the other to kill the spider, it happens that both tasks appear at the same time for the player.

my suggestion is to have the option to release the next task only when the previous task is completed.

https://prnt.sc/jD3xm56WeiGm

**Comment by juniormagalhaes** [comment]
> Thats possible by default

how?

**Comment by juniormagalhaes** [comment]
for example I'm talking about a quest that has two tasks, one to talk to the npc and another to kill the monster, I would like to have a way to only show the task to kill the monster after you finish the task to talk to the npc.

**Comment by moepi2k** [comment]
There are an option called conditions

**Comment by juniormagalhaes** [comment]
> There are an option called conditions. Its just a designe thing

I didn't understand

**Comment by khongtuong** [comment]
> > There are an option called conditions. Its just a designe thing
> 
> I didn't understand

conditions in quest task, require complete kill monster quest before you can do talk with npc

**Comment by juniormagalhaes** [comment]
> 

I did not find this option in the kit
