### ISSUE TITLE
[BUG] Sometimes the monster doesn't get hit

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1806]
Yesterday I built the server and I realized that sometimes, most times I attack a monster it doesn't receive the hit, but I also noticed that the monsters that don't receive an item, they also don't move as they should, they stay still for a long time and don't walk. follow some images below.

https://gyazo.com/8ba7d6464fd5618b0bbc490c6d0e3328

https://gyazo.com/e45af0a67526b86eb60a226fc2f9ccf7

https://gyazo.com/0778ea7715158da70f75eaf7d058e32e

https://prnt.sc/SW2A8TG2cxv2

**Comment by juniormagalhaes** [comment]
I also noticed that when the monster walks and stops, sometimes they don't get hit, and when they walk I can hit them.

**Comment by moepi2k** [comment]
seems u messed something up

**Comment by juniormagalhaes** [comment]
> seems u messed something up

I didn't change anything in the code, in fact I just assemble my scenes and put my monsters

**Comment by moepi2k** [comment]
i dont think so. when you play default scene demo it works fine. im on latest version and it works

**Comment by juniormagalhaes** [comment]
I migrated the files to a new project, and the same thing happens, it keeps giving this message on the server console

https://gyazo.com/0778ea7715158da70f75eaf7d058e32e

**Comment by juniormagalhaes** [comment]
> 

did you build the server and run it separately? Or did you test it in single player? in single player works great

**Comment by juniormagalhaes** [comment]
I thought it could be my misconfigured monster, but the default monster is also stuck

https://gyazo.com/2e54ef8ed83cb2b67fbe4c26783cc8b8

**Comment by moepi2k** [comment]
When it works with default fresh project then its cmear something in ylur project. I dont know your settings.

**Comment by temelkirci** [comment]
what is your damage transform position ? also accurancy and evacasion are important
