### ISSUE TITLE
Proper way to detect the Player has spawned for the 'First Time'

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1808]
I am trying to find a way to know if the player spawned/joined for the first time or already exists on map when warping/changing map

Added a bool on the playerEntity isSpawned which I was setting true after player would spawn for first time to know that he joined new and any further respawns will be repeated
But problem is when you warp/change map, the playerEntity is destroyed and recreated/spawned which resets that bool value back to false and thus renders it useless
in short, there is a specific method I need to run for the player when he joins/spawns for the very first time and not call it again whenever he respawns or changes map (which mimics him spawning again)

The PlayerCharacterEntity.lastUpdated is updated whenever player changes map, warps, quits and thus cannot be used reliably to know which of his action was first spawn

To be specific, I am trying to detect the first spawn after logging in and not when player warped/changingMap/respawning

**Comment by temelkirci** [comment]
Check account created date or updated date from database.Also character level should be 1

**Comment by shubhank008** [comment]
> Check account created date or updated date from database.Also character level should be 1

Need for first time after every login, not first time after registration

**Comment by insthync** [comment]
First time of the day?

**Comment by shubhank008** [comment]
> 

No more like first time everytime player logins and spawns
Like if he restarts game and relogins and respawns

**Comment by insthync** [comment]
Respawn after entering the game?

**Comment by shubhank008** [comment]
> Respawn after entering the game?

Yes

**Comment by insthync** [comment]
Should it being checked by server?

**Comment by insthync** [comment]
No answer.. so, I will close it.
