### ISSUE TITLE
Issue disconnected after having used a number of warp portal

### ISSUE THREAD

**Issue by JoRangers** [suriyun-production/mmorpg-kit-docs#1809]
Hi,

Sometimes when I use warp portals, I am disconnected from the server.

Currently, I have 15 maps launched at start on the server.
Each map has an environment different for testing purpose.

Map001 from the asset is my main map with 14 portals.
Others maps have only 1 warp portal and 3d environements / colliders.
The warp system work correctly, I can go and back from each map.

But after having used a number of portal, directly when the loading is finished, I am disconnected from the server.
I am the only player, I can warp around 10-20 times
I have >50 players on the server, I can warp around 5-10 times

I use Unity 2021.3.15f1
The issue appears on editor, desktop build and android build.

I use a digital ocean server at 84$/month
Dedicated CPU - CPU Optimized - Regular Intel - 4 vCPUs - 8 GB Memory

Here is the error from the unity console :

```
Enter game request was refused by server, disconnecting...
UnityEngine.Debug:LogError (object)
ZLogger.Providers.UnityDebugLogProcessor:Post (ZLogger.IZLoggerEntry) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/Unity/ZLoggerUnityLoggerProvider.cs:69)
ZLogger.AsyncProcessZLogger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/AsyncProcessZLogger.cs:36)
Microsoft.Extensions.Logging.Logger:<Log>g__LoggerLog|12_0<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.ILogger,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>,System.Collections.Generic.List`1<System.Exception>&,Microsoft.Extensions.Logging.FormattedLogValues&)
Microsoft.Extensions.Logging.Logger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>)
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,System.Exception,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:LogError (Microsoft.Extensions.Logging.ILogger,string,object[])
LiteNetLibManager.Logging:LogError (string,string,object[]) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Logging.cs:45)
LiteNetLibManager.LiteNetLibGameManager:HandleEnterGameResponse (LiteNetLibManager.ResponseHandlerData,LiteNetLibManager.AckResponseCode,LiteNetLibManager.EnterGameResponseMessage) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:527)
MultiplayerARPG.MMO.MapNetworkManager:HandleEnterGameResponse (LiteNetLibManager.ResponseHandlerData,LiteNetLibManager.AckResponseCode,LiteNetLibManager.EnterGameResponseMessage) (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Networking/Map/MapNetworkManager.cs:526)
LiteNetLibManager.LiteNetLibResponseHandler`2<LiteNetLibManager.EnterGameRequestMessage, LiteNetLibManager.EnterGameResponseMessage>:InvokeResponse (LiteNetLibManager.ResponseHandlerData,LiteNetLibManager.AckResponseCode,LiteNetLibManager.ResponseDelegate`1<LiteNetLib.Utils.INetSerializable>) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibResponseHandler.cs:33)
LiteNetLibManager.LiteNetLibRequestCallback:ResponseTimeout () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibRequestCallback.cs:26)
LiteNetLibManager.TransportHandler/<HandleRequestTimeout>d__38:MoveNext () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:131)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1<LiteNetLibManager.TransportHandler/<HandleRequestTimeout>d__38>:Run () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<object>:TrySetResult (object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/DelayPromise:MoveNext () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.Delay.cs:685)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:104)
```

Do you have solutions ?

Thanks

**Comment by insthync** [comment]
May I see server log fiiles ?

**Comment by JoRangers** [comment]
Here are all the logs.
For the test, I only use Map001 & Map_c_008

[Log_Map(Map_c_011) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294213/Log_Map.Map_c_011.Instance.log)
[Log_Map(Map_c_012) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294214/Log_Map.Map_c_012.Instance.log)
[Log_Map(Map_GuildWar) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294215/Log_Map.Map_GuildWar.Instance.log)
[Log_Map(Map001) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294216/Log_Map.Map001.Instance.log)
[Log_Map(Map002) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294218/Log_Map.Map002.Instance.log)
[Log_Database_Central_MapSpawn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294219/Log_Database_Central_MapSpawn.log)
[Log_Map(Map_c_001) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294220/Log_Map.Map_c_001.Instance.log)
[Log_Map(Map_c_002) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294221/Log_Map.Map_c_002.Instance.log)
[Log_Map(Map_c_003) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294222/Log_Map.Map_c_003.Instance.log)
[Log_Map(Map_c_004) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294223/Log_Map.Map_c_004.Instance.log)
[Log_Map(Map_c_005) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294224/Log_Map.Map_c_005.Instance.log)
[Log_Map(Map_c_006) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294225/Log_Map.Map_c_006.Instance.log)
[Log_Map(Map_c_007) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294226/Log_Map.Map_c_007.Instance.log)
[Log_Map(Map_c_008) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294227/Log_Map.Map_c_008.Instance.log)
[Log_Map(Map_c_009) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294228/Log_Map.Map_c_009.Instance.log)
[Log_Map(Map_c_010) Instance().log](https://github.com/suriyun-production/mmorpg-kit-docs/files/10294229/Log_Map.Map_c_010.Instance.log)

**Comment by insthync** [comment]
Do these ones have the log when the connection is refused?

**Comment by JoRangers** [comment]
I checked some logs but I didn't see anything related to connection refused or error.
All theses logs are from the log folder on the server.

I record a video to show the issue.

I'm on vacation starting today so sorry if I don't respond quickly.

https://user-images.githubusercontent.com/47748200/209328057-28814bca-7509-49fe-8515-cf3595a85462.mp4
