### ISSUE TITLE
Some problems (single player)

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#181]
In the finished project for android (single player game), users have some problems:
* Sometimes all items in the stash disappear
* Very rarely there is duplication of items when we insert sockets into items (after that, 1-2 items disappear in the inventory)

I do not ask for anything, I just let you know that such problems sometimes occur. Perhaps in the MMO mode there are no such problems.

**Comment by insthync** [comment]
I going to improve the save system, and also make it switchable, so other developers may create other save, and maybe the cloud save system for offline games will be created by other developers :p

**Comment by DimasjkTV** [comment]
> I going to improve the save system, and also make it switchable, so other developers may create other save, and maybe the cloud save system for offline games will be created by other developers :p

The new save system will not delete the current characters?

**Comment by insthync** [comment]
Yes, it won't delete current characters

**Comment by DimasjkTV** [comment]
> Yes, it won't delete current characters

Very cool

**Comment by DimasjkTV** [comment]
> Yes, it won't delete current characters

By the way, will this make the stash common to all characters in a single player game?

**Comment by insthync** [comment]
> > Yes, it won't delete current characters
> 
> By the way, will this make the stash general to all characters in a single player game?

I've updated save system in 1.52b, I not sure how storage items were lost but in latest update I made it to not save storage items before the first load.

**Comment by DimasjkTV** [comment]
> > > Yes, it won't delete current characters
> > 
> > 
> > By the way, will this make the stash general to all characters in a single player game?
> 
> I've updated save system in 1.52b, I not sure how storage items were lost but in latest update I made it to not save storage items before the first load.

On question: Is it possible to make a character attack while running with "WASD lock attack target"?
[WASD Loct attack target.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4111625/WASD.Loct.attack.target.zip)

**Comment by Koodetat** [comment]
Yes on mobile it is not possible to attack while moving.

**Comment by DimasjkTV** [comment]
> Yes on mobile it is not possible to attack while moving.

I think it's possible. This is already in the kit. If you remove this checkmark, then the character is attacking while running. He just does not automatically find the target
