### ISSUE TITLE
Auction House remove random bonuses in item

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1811]
After I added a item in Auction house, all random bonuses in item lost.I canceled it and check it in my inventory still lost.It removes random bonuses after added it to Auction house.

**Comment by insthync** [comment]
I want to see your `ReadItems` and `WriteItems` functions source from `Mail.cs`

**Comment by temelkirci** [comment]
public List<CharacterItem> ReadItems(string items)
        {
            Items.Clear();
            string[] splitSets = items.Split(';');
            foreach (string set in splitSets)
            {
                if (string.IsNullOrEmpty(set))
                    continue;
                string[] splitData = set.Split(':');

                int dataId;
                if (splitData.Length < 1 || !int.TryParse(splitData[0], out dataId))
                    continue;

                short amount;
                if (splitData.Length < 2 || !short.TryParse(splitData[1], out amount))
                    amount = 1;

                short level;
                if (splitData.Length < 3 || !short.TryParse(splitData[2], out level))
                    level = 1;

                float durability;
                if (splitData.Length < 4 || !float.TryParse(splitData[3], out durability))
                    durability = 0f;

                int exp;
                if (splitData.Length < 5 || !int.TryParse(splitData[4], out exp))
                    exp = 0;

                float lockRemainsDuration;
                if (splitData.Length < 6 || !float.TryParse(splitData[5], out lockRemainsDuration))
                    lockRemainsDuration = 0f;

                long expireTime;
                if (splitData.Length < 7 || !long.TryParse(splitData[6], out expireTime))
                    expireTime = 0;

                byte randomSeed;
                if (splitData.Length < 8 || !byte.TryParse(splitData[7], out randomSeed))
                    randomSeed = 0;

                string sockets;
                if (splitData.Length < 9)
                    sockets = "";
                else
                    sockets = splitData[8];

                CharacterItem characterItem = CharacterItem.Create(dataId, level, amount);
                characterItem.durability = durability;
                characterItem.exp = exp;
                characterItem.lockRemainsDuration = lockRemainsDuration;
                characterItem.expireTime = expireTime;
                characterItem.randomSeed = randomSeed;
                characterItem.ReadSockets(sockets, '|');
                Items.Add(characterItem);
            }
            return Items;
        }

        public string WriteItems()
        {
            stringBuilder.Clear();
            foreach (CharacterItem item in Items)
            {
                stringBuilder.Append(item.dataId).Append(':');
                stringBuilder.Append(item.amount).Append(':');
                stringBuilder.Append(item.level).Append(':');
                stringBuilder.Append(item.durability.ToString("N2")).Append(':');
                stringBuilder.Append(item.exp).Append(':');
                stringBuilder.Append(item.lockRemainsDuration.ToString("N2")).Append(':');
                stringBuilder.Append(item.expireTime).Append(':');
                stringBuilder.Append(item.randomSeed).Append(':');
                stringBuilder.Append(item.WriteSockets('|')).Append(';');
            }
            return stringBuilder.ToString();
        }

**Comment by insthync** [comment]
I  also want to itemdata in auction table (not sure what is its name)

**Comment by temelkirci** [comment]
![qqqqqq](https://user-images.githubusercontent.com/11313412/209435022-322e18b8-cd6c-4e6f-9995-b2f2c5360033.png)

**Comment by temelkirci** [comment]
![wwwww](https://user-images.githubusercontent.com/11313412/209435037-f590e23c-d642-43b8-886a-e1f2bbc7437a.png)

**Comment by moepi2k** [comment]
https://gyazo.com/8c7b9de164cc9e290c9d1c1937659d4f
i think the problem is, when puting an item in auction house it changes the random seed value @insthync

**Comment by insthync** [comment]
Fix it by change mail writing random seed from byte to short
![Screenshot_282](https://user-images.githubusercontent.com/2697550/209573287-66aeff5b-5de7-4122-8a11-f869524c0904.png)

**Comment by moepi2k** [comment]
That fixxed the issue, thank u

**Comment by temelkirci** [comment]
@insthync Solved.Thank you
