### ISSUE TITLE
How can I add item drop rate stat in MMO?

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1815]
I want to add item drop rate bonus for my mmorg game.I added it to character stat and need to add init item drop function somehow.I will add item drop rate potion and bonuses for gears.But how ?

**Comment by insthync** [comment]
Adding new stats for difference kinds of items?

**Comment by khongtuong** [comment]
> I want to add item drop rate bonus for my mmorg game.I added it to character stat and need to add init item drop function somehow.I will add item drop rate potion and bonuses for gears.But how ?

using item drop table for extra rate

**Comment by temelkirci** [comment]
But think as a bonus between %0 - %100, if killer has %100 item drop rate , item drop chance increase 2x.Items can have item drop rate bonus and also %50 item drop rate potion (for 1 hour)

**Comment by temelkirci** [comment]
> > I want to add item drop rate bonus for my mmorg game.I added it to character stat and need to add init item drop function somehow.I will add item drop rate potion and bonuses for gears.But how ?
> 
> using item drop table for extra rate

how can I get character's item drop rate bonus for item drop table ?

**Comment by temelkirci** [comment]
![Ekran görüntüsü 2022-12-29 104346](https://user-images.githubusercontent.com/11313412/209919715-d6c463f0-b280-470d-933b-e2e0841b2828.png)

**Comment by khongtuong** [comment]
> ![Ekran görüntüsü 2022-12-29 104346](https://user-images.githubusercontent.com/11313412/209919715-d6c463f0-b280-470d-933b-e2e0841b2828.png)

ah, you mean character Attributes rate for item? right?

**Comment by temelkirci** [comment]
yeah.I want to add it somehow,No problem which one is easy for now.I want to add drop rate item on store.Also players should be try obtain this efsun randomly.

**Comment by khongtuong** [comment]
> yeah.I want to add it somehow,No problem which one is easy for now.I want to add drop rate item on store.Also players should be try obtain this efsun randomly.

i think this is a new suggestion for bonus stat to make a buff item increase item drop rate, new character attribute @insthync

**Comment by khongtuong** [comment]
> yeah.I want to add it somehow,No problem which one is easy for now.I want to add drop rate item on store.Also players should be try obtain this bonus randomly.

for now you can add partial class in monstercharacter to add bonus drop rate base on atribbute ext rate, will work

**Comment by temelkirci** [comment]
How can I get character's item drop rate and add it to drop table ?
