### ISSUE TITLE
Why are there so many spots for an IP?

### ISSUE THREAD

**Issue by OfficialTeKniKo** [suriyun-production/mmorpg-kit-docs#1816]
Can someone please explain why there are so many different spots for an IP address and what each one does?  Also, is IPv6 supported?
1)
![Capture](https://user-images.githubusercontent.com/78048801/209882175-02d647b3-1874-40b4-99eb-4e5ca0c1b73c.PNG)
2)
![Capture2](https://user-images.githubusercontent.com/78048801/209882176-79ddcd65-a6a3-41ec-90f0-c8a6ab92f5af.PNG)
3)
![Capture3](https://user-images.githubusercontent.com/78048801/209882177-96b3ba00-d97f-46f4-ae01-3e922b239874.PNG)
4)
![Capture4](https://user-images.githubusercontent.com/78048801/209882179-0b2d9c27-8915-47f2-8ecf-74d9e5df1e59.PNG)
5)
![Capture5](https://user-images.githubusercontent.com/78048801/209882180-81ca1ab9-d618-4467-aa3e-d79bf85a2c3a.PNG)

**Comment by insthync** [comment]
It will be used in case you run servers on different server devices, it is a scalable practice

You may run the central server on device 1, map-server and map-servers on device 2, and the database-management-server on device 3.

And set connections to each device differently.

**Comment by OfficialTeKniKo** [comment]
So if I am just running on one server. Do I put the same IP/Port into all 5 of these spots?

**Comment by insthync** [comment]
Use the config files

**Comment by OfficialTeKniKo** [comment]
Is there a tutorial on how to do that? The website just says, "You will have to create config folder and config files by yourself next to project folder if you are gonna use config in editor, next to execution folder for built execution file" but that doesn't really explain anything.

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/031-server-config-files

![Screenshot_291](https://user-images.githubusercontent.com/2697550/210120897-c85bcf92-e08a-4595-b9c6-2b56d8158617.png)

**Comment by OfficialTeKniKo** [comment]
Still don't really understand.  Thanks anyway.
