### ISSUE TITLE
[Bug]Item lost Loot

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1818]
There is a bug when use Corpse looting

here a video -> https://gyazo.com/72fdf5a33c9754f65091ae63ad125b5f

for exmplaination:
if player has only 1 empty slot left and try to loot a corpse with multible items
he can take the one item. then when clicking loot all. the other items in corpse disappear.
only happen when use loot all button. when click on single item you get the message that no space in inventory

**Comment by insthync** [comment]
Fixed in 1.79
