### ISSUE TITLE
[Quesiton] How to access player's current position(x,y,z) and current map name?

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#1819]
I'm now using the latest version of this kit and it is MMO for android.
I want to display player's current position coordinate(x,y,z) and current map name to UI.
I tried this with below variables,
"GameInstance.PlayingCharacter.CurrentPosition.x"
"GameInstance.PlayingCharacter.CurrentMapName"

In Unity editor, these variables return the values as well.
However when I run this in android phone, those variables return no value.(I checked this with logcat for mobile)

I tried both of "GameInstance.PlayingCharacter" and "GameInstance.PlayingCharacterEntity" which have those variables, but same problem.

Do you have any idea what's wrong with me?

**Comment by insthync** [comment]
Try use `BaseGameNetworkManager.CurrentMapInfo` to get map info data

Use `GameInstance.PlayingCharacterEntity.transform.position` to get current position

**Comment by dglee2592** [comment]
Thanks! Perfect!!!
