### ISSUE TITLE
New character dies at the start of the game

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#182]
I made a new character for player.
But when start a game, the character die but still can move.
I add this new character to Database but this happen.
What should I check?

![image](https://user-images.githubusercontent.com/58107601/72669095-37cb3080-3a71-11ea-9c10-33d857eb2526.png)

**Comment by insthync** [comment]
How about its Base Stats and Base Attributes settings ?
![Screenshot_5](https://user-images.githubusercontent.com/2697550/72675199-54885800-3ab3-11ea-9a63-5cd120ca53e9.png)

Did you add entity movement component ?

**Comment by insthync** [comment]
I will close this because there are no responses from you and anyone relates to this issues for a long time.
