### ISSUE TITLE
Explode Distance for sword(melee attack)

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1821]
I want to add explode distance for melee attack (for warrior).Staff and bow have explode distance but I want to add it to sword.So all class will have area attack (explode distance)

![Ekran görüntüsü 2023-01-02 140446](https://user-images.githubusercontent.com/11313412/210223264-9b1e3b2b-92cd-45b7-9b17-9b7cb2136141.png)
![Ekran görüntüsü 2023-01-02 140518](https://user-images.githubusercontent.com/11313412/210223269-b5a2caf9-0c7c-4768-850d-8b1f7dd298c2.png)

**Comment by moepi2k** [comment]
whats the point to add this to melee? you can set angle which behave same. just set radius to 360

**Comment by temelkirci** [comment]
@moepi2k  It worked.Thank you
