### ISSUE TITLE
Simple Warp to Target Skill doesnt work. 

### ISSUE THREAD

**Issue by RutzStudios** [suriyun-production/mmorpg-kit-docs#1822]
Simple Warp to Target Skill doesnt work. Need some docs on understanding how it works. Im trying to make a dash or teleport skill but it doesnt do anything other than reset position. 

![Screenshot 2023-01-04 022158](https://user-images.githubusercontent.com/77238558/210513030-f8bc5c2c-620e-44e8-aac6-9628ca9ac636.png)

**Comment by insthync** [comment]
This is my setup

![Screenshot_298](https://user-images.githubusercontent.com/2697550/210517340-8efcba6e-ae55-4155-99ce-32c474e31fa7.png)

**Comment by RutzStudios** [comment]
Thanks!
