### ISSUE TITLE
[Question] Removing all Gear from player when disconnecting in an instance/dungeon

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#1823]
Hey there, 

i want the player to loose all his gear when disconnecting in a dungeon. Unfortunately i couldnt find the right function for it. 

i only did find "OnPeerDisconnectedRoutine" in the mapnetworkmanager. But this will only be called when the player disconnects from the normal map and not when he disconnects while in dungeons/instanced maps.

Could you show me where the functions gets called when the player disconnects while being in a dungeon?

**Comment by insthync** [comment]
For which use case?

**Comment by insthync** [comment]
OnPeerDisconnectedRoutine will be called although the character is in the instance map.

**Comment by xnitro1** [comment]
The use case is that i have the event asset from the community, where people can spawn in an instanced map and fight against each other. my idea is a game like tarkov, just with dungeons. 5 player joins an event in an instanced map, kill monster for loot und "escape" through a portal. but players can "cheat" by just logging out and getting teleported back to the NPC where they can register for the event. Thats why i wanna kill the player when logging out or removing all his items.

i debugged the server side but the "OnPeerDisconnectedRoutine" wont get called when i disconnect in an instanced map. or does the asset have multiple "OnPeerDisconnectedRoutine" i was looking in the wrong script? (MapNetworkManager)

**Comment by insthync** [comment]
It is being called by `OnPeerDisconnected` function only you can see it in the codes

**Comment by insthync** [comment]
If you want to find it by yourself, do like this

![Screenshot_301](https://user-images.githubusercontent.com/2697550/210567119-856518c3-8e4a-45e3-94c8-7906b78c6bb4.png)

**Comment by xnitro1** [comment]
i tried the OnPeerDisconnected too, but this also wont get called. or maybe i did something wrong when debugging it?

I made a video of it so you can see what i mean: https://youtu.be/7O1nJxvgLQ8

The video should be processed shortly

**Comment by insthync** [comment]
![Screenshot_302](https://user-images.githubusercontent.com/2697550/210568186-e5d2e5e1-efb5-43ce-8923-fcb41d954749.png)

**Comment by xnitro1** [comment]
![image](https://user-images.githubusercontent.com/93816817/210568874-3cb6f827-4241-4f87-9ad2-022e170e2811.png)

"asdf" didnt get called

**Comment by xnitro1** [comment]
i mean, why get "OnPeerDisconnectedRoutine" called when logging IN ? but i could live with that, but it still get not called when logging out in an instanced map. or i´m doing something wrong and dont see what

**Comment by insthync** [comment]
`OnPeerDisconnectedRoutine` must not being called when logging in, it will called when player leave the map-server, so when teleporting to instance map it will be called, and when teleport back to normal map it will be called too.

**Comment by xnitro1** [comment]
but the player wont be teleported from the instance map when he is logging out. he will "spawn" again where he left before entering the dungeon and therefore he is not switching servers when logging out in the instanced map (so the function wont be called)

**Comment by insthync** [comment]
Yes, in that case (player logout), `OnPeerDisconnectedRoutine ` will be called too.

**Comment by xnitro1** [comment]
have you tried that? because as you can see, in my case it will not be called :/

**Comment by insthync** [comment]
I have tried it.

**Comment by insthync** [comment]
You may try to find where `UnregisterPlayerCharacter` function being called, if it was called, then `ServerUserHandlers.TryGetPlayerCharacter` will returns `false`, so it won't go into the break point.

**Comment by insthync** [comment]
In `WarpCharacterRoutine` function, it will unregister the player character before telling the client to connect to a next map-server

**Comment by xnitro1** [comment]
ok i will check it thank you. but its weird that its not called for me but its working for you. maybe ill check an new project with just the base asset if it works then

**Comment by xnitro1** [comment]
mh yeah i cant get it to work. i don´t know what i´m doing wrong, but i cant figure out how to check if an player leaves an instance with pressing exit or ALT+4. i tried it the whole day and now i´m too frustrated for the rest of the day

**Comment by insthync** [comment]
May I see the event asset codes?

**Comment by xnitro1** [comment]
i talked to the person who made the asset. he tells me that its not his asset because he is not touching the disconnects. he suggested i test it in a new project with just the MMOKit. I did exactly that and here is the result:

https://youtu.be/_L20gHWOvRg

its the exact same thing, so it cant be his asset. the functions wont get called when logging out in an instance

**Comment by insthync** [comment]
Are you able to remove gear when the character teleporting from instanced dungeon (exit)?

**Comment by insthync** [comment]
Try make changes in MapNetworkManager
By find and replace `WarpCharacterRoutine` function codes:
```
        private async UniTaskVoid WarpCharacterRoutine(BasePlayerCharacterEntity playerCharacterEntity, string mapName, Vector3 position, bool overrideRotation, Vector3 rotation)
        {
            // If warping to different map
            long connectionId = playerCharacterEntity.ConnectionId;
            CentralServerPeerInfo peerInfo;
            BaseMapInfo mapInfo;
            if (!string.IsNullOrEmpty(mapName) &&
                ServerUserHandlers.TryGetPlayerCharacter(connectionId, out _) &&
                mapServerConnectionIdsBySceneName.TryGetValue(mapName, out peerInfo) &&
                GameInstance.MapInfos.TryGetValue(mapName, out mapInfo) &&
                mapInfo.IsSceneSet())
            {
                // Add this character to warping list
                playerCharacterEntity.IsWarping = true;
                // Unregister player character
                UnregisterPlayerCharacter(connectionId);
                // Clone character data to save
                while (savingCharacters.Contains(playerCharacterEntity.Id))
                {
                    await UniTask.Yield();
                }
                playerCharacterEntity.EquipItems.Clear();
                await SaveCharacter(playerCharacterEntity, true, mapName, position, overrideRotation, rotation);
                // Remove this character from warping list
                playerCharacterEntity.IsWarping = false;
                // Destroy character from server
                playerCharacterEntity.NetworkDestroy();
                // Unregister character to tell central server that the user is disconnecting from this server
                UnregisterPlayerCharacter(connectionId);
                // Send message to client to warp
                MMOWarpMessage message = new MMOWarpMessage();
                message.networkAddress = peerInfo.networkAddress;
                message.networkPort = peerInfo.networkPort;
                ServerSendPacket(connectionId, 0, DeliveryMethod.ReliableOrdered, GameNetworkingConsts.Warp, message);
            }
        }
```

And `OnPeerDisconnectedRoutine`
```
        private async UniTaskVoid OnPeerDisconnectedRoutine(long connectionId, DisconnectInfo disconnectInfo)
        {
            // Save player character data
            BasePlayerCharacterEntity playerCharacterEntity;
            if (ServerUserHandlers.TryGetPlayerCharacter(connectionId, out playerCharacterEntity))
            {
                playerCharacterEntity.SetOwnerClient(-1);
                playerCharacterEntity.StopMove();
                MovementState movementState = playerCharacterEntity.MovementState;
                movementState &= ~MovementState.Forward;
                movementState &= ~MovementState.Backward;
                movementState &= ~MovementState.Right;
                movementState &= ~MovementState.Left;
                playerCharacterEntity.KeyMovement(Vector3.zero, movementState);
                string id = playerCharacterEntity.Id;
                // Store despawning player character id, it will be used later if player not connect and continue playing the character
                CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
                despawningPlayerCharacterCancellations.TryAdd(id, cancellationTokenSource);
                despawningPlayerCharacterEntities.TryAdd(id, playerCharacterEntity);
                // Unregister player character
                UnregisterPlayerCharacter(connectionId);
                UnregisterUserId(connectionId);
                // Save character immediately when player disconnect
                while (savingCharacters.Contains(id))
                {
                    await UniTask.Yield();
                }
                playerCharacterEntity.EquipItems.Clear();
                await SaveCharacter(playerCharacterEntity);
                try
                {
                    if (!IsInstanceMap())
                        await UniTask.Delay(playerCharacterDespawnMillisecondsDelay, true, PlayerLoopTiming.Update, cancellationTokenSource.Token);
                    // Save character again before despawned (it may attacked by other characters)
                    while (savingCharacters.Contains(id))
                    {
                        await UniTask.Yield(cancellationTokenSource.Token);
                    }
                    if (!cancellationTokenSource.IsCancellationRequested)
                    {
                        await SaveCharacter(playerCharacterEntity);
                        playerCharacterEntity.NetworkDestroy();
                        despawningPlayerCharacterEntities.TryRemove(id, out _);
                    }
                }
                catch (System.OperationCanceledException)
                {
                    // Catch the cancellation
                }
                catch (System.Exception ex)
                {
                    // Other errors
                    Logging.LogException(LogTag, ex);
                }
                finally
                {
                    if (despawningPlayerCharacterCancellations.TryRemove(id, out cancellationTokenSource))
                        cancellationTokenSource.Dispose();
                }
            }
            else
            {
                UnregisterPlayerCharacter(connectionId);
                UnregisterUserId(connectionId);
            }
        }
```

**Comment by insthync** [comment]
In codes above I've just add codes to remove equip item (an armor) before save character.

```
                if (IsInstanceMap())
                    playerCharacterEntity.EquipItems.Clear();
```

**Comment by xnitro1** [comment]
i will test it later thank you :)

but just by looking at it:
   if (IsInstanceMap())
                    playerCharacterEntity.EquipItems.Clear();
in the "WarpCharacterRoutine".

wont it now remove the items everytime a player leaves?

**Comment by insthync** [comment]
Ahhh, I see, you want to remove items when player disconnect when press alt+f4, this makes me miss the  point because you keep asking why the OnPeerDisconnectedRoutine not being called.

In this case, I think you should not make the server finding which one is press alt+f4, you should make the client tell server that it is going to exit then server store client exiting state and won't remove items when player leave.

**Comment by xnitro1** [comment]
Alt +F4 was just an example of leaving. another way is to open the menu and pressing the "exit" button or just turn of the internet in the middle of the game. for those cases i need the disconnect function to react properly when leaving and instance (which you can see is not called when leaving instances in the video, so this has to be a bug i think)

**Comment by insthync** [comment]
I told you that when teleporting to another map it will unregister character so the workflow when disconnect can be differed, and it is not a bug it is working as intended.

**Comment by xnitro1** [comment]
i understand that and thats why i set a breaking point at the unregister function too which also got not called

**Comment by insthync** [comment]
Where did you place the breakpoint

**Comment by xnitro1** [comment]
https://youtu.be/_L20gHWOvRg?t=40

In the MapNetworkManager:
- OnPeerDisconnected
- UnregisterUserID
- OnPeerDisconnectedRoutine
- UnregisterPlayerCharacter

i set a breakpoint in all of those 4 functions and not one got called when disconnecting (the way of the disconnecting doesnt matter, but in this example is logged out with the Menu -> Exit)

**Comment by insthync** [comment]
Not sure that the breakpoint will works with server instances which is spawned by map spawn server

**Comment by insthync** [comment]
Try use Logging.Log something

**Comment by Callepo** [comment]
> Not sure that the breakpoint will works with server instances which is spawned by map spawn server

thats his point, the breakpoints work fine if the player was not in instance and logged out or disconnect.

But if he was in instance none work. thats what he is saying..
Even tho, when ur inside an instance u still disconnect from server, u still unregister

**Comment by Callepo** [comment]
Normal Map log out > OnpeerDisconnect Called
Instance map Log out > Not Called

why would instance, not call the event? it should be the same process no"?

or is there a reason why instance dont call it

Even if its instance from a map server, the disconnect still happens

**Comment by insthync** [comment]
My point is instance map which spawned later might not linking to ide, so you should try to use Logging.Log... to write some thing to log files to see what is happend

**Comment by Callepo** [comment]
> My point is instance map which spawned later might not linking to ide, so the breakpoint will not work, so you should try to use Logging.Log... to write some thing to log files to see what is happend

good idea

**Comment by xnitro1** [comment]
Thank you both. The tip with writing to a file on the filesystem worked better then the breakpoints. for some reason the breakpoints are not reached, but i can see the function will actually get called because the file was written on the filesystem.

i have one last question if you dont mind? 
i want to save the CurrentMapName of the instance. Is there some easy way to add this to the database and save/read them?

for example a new field "CurrentInstanceName". Or if this is too much trouble maybe atleast an boolean "PlayerInAnInstancedDungeon = True/False" ?

**Comment by xnitro1** [comment]
thank you both :) i got it now working and the idea with writing to a file did the trick. the IDE breaking point was really not working, but when writing to a file i could see that the function was being called. thanks :)
