### ISSUE TITLE
[BUG] Server sometimes clones player or mouth in map 

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1825]
I had a issue today.I log out from game.And log in again.My character looks twin in city.Some players also report a free mounts in desert map.
I log out and log in still appear my clone in city.It disappear after I restart server.

![Ekran görüntüsü 2023-01-05 211851](https://user-images.githubusercontent.com/11313412/210855024-2a4029c0-51a1-4403-aa63-246a81597864.png)

**Comment by insthync** [comment]
Please attache server log files

**Comment by temelkirci** [comment]
[log.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/10354858/log.zip)

**Comment by insthync** [comment]
What is that scene in the picture

**Comment by temelkirci** [comment]
City

**Comment by insthync** [comment]
Why it has so many database connection errors like that?

**Comment by insthync** [comment]
![Screenshot_303](https://user-images.githubusercontent.com/2697550/210860757-93ad7c4e-0388-485f-974b-500b1dfdf0dc.png)

It is just having an error immediately when any player connects to the server, am I right?

**Comment by temelkirci** [comment]
Player report that they kill a few mobs at same time in dungeons, and suddenly disconnect from dungeon.They log in game again but dead in dungeon.

Clone issue -> I guess connect to server or warping to map.

**Comment by insthync** [comment]
I think you should fix the database connection timeout first, did you run database management server on the same device with map-servers?, which kind of database?, how about CPU usage and remaining RAM?

**Comment by temelkirci** [comment]
I am using 16 GB Ram ubuntu mysql server in digital ocean.I pay 120 dollars every month.

Game size : 600 mb
8 maps
CCU now : 10-20

![1](https://user-images.githubusercontent.com/11313412/210862783-fee51f79-9dbd-4e48-94d5-2b3b80de7de7.png)
![2](https://user-images.githubusercontent.com/11313412/210862790-3c94dc6d-ff29-40f4-9f8a-ca1c53570e7b.png)
![3](https://user-images.githubusercontent.com/11313412/210862791-f6dd74a8-f2eb-49bd-91e2-dfc9e814cd51.png)
![4](https://user-images.githubusercontent.com/11313412/210862794-0ebc04fc-f739-4233-b019-a90aa5d235d8.png)

**Comment by insthync** [comment]
Did you made changes to request timeout?

**Comment by temelkirci** [comment]
What kind of changes do you mean ?

**Comment by temelkirci** [comment]
Server config.json



{
    "databaseOptionIndex" : 1,
  
    "centralAddress" : "127.0.0.1",
    "centralPort" : 7000,
    "clusterPort" : 7010,
    "centralMaxConnections" : 10000,
    "machineAddress" : "46.101.31.220",
    
    "mapSpawnPort" : 6001,
    "mapSpawnMaxConnections" : 10000,
    "spawnExePath" : "/root/Build.x86_64",
    "notSpawnInBatchMode" : false,
    "spawnStartPort" : 8000,
    "spawnMaps" : ["City","Forest","DarkWinter","BlackDesert","HellGates","Temple","IceDungeon","SpiderCave","HellCaves"],
  
    "databaseManagerAddress" : "localhost",
    "databaseManagerPort" : 6003,
  
    "chatPort" : 3002,
    "chatMaxConnections" : 1000,

    "useWebSocket": false,
    "webSocketSecure": false,
    "webSocketCertPath": "./localhost.pfx",
    "webSocketCertPassword": "123456"
  }

**Comment by insthync** [comment]
Your setup looks fine

**Comment by temelkirci** [comment]
my server usage looks avarage, enough for game.But I guess something wrong in my changes or kit.Players also report that their pets not level up anymore ,but no reset or level decrease anymore

**Comment by insthync** [comment]
Whats you made changes

**Comment by temelkirci** [comment]
I deleted deprecated scripts from prefabs.I added auto attack (with diamond), special scroll to prevent destroy item if it fails, I disabled character picth script, added free reward after 15 minutes in game

I am using Navmesh , some pets and mounts show error GetRemaningDistance.

![Uploading w.png…]()

**Comment by temelkirci** [comment]
A player reported me pet now, his pet is 55 level but bonus looks very low, should be higher

![9b42b54a-eac6-49b3-b9b2-6bac2354c516](https://user-images.githubusercontent.com/11313412/210873140-6f8b9dae-74c2-41c1-92f1-aa5beb9b89ca.jpg)

**Comment by insthync** [comment]
How prevent destroy item working?

How free reward after 15 minutes in game working?

About the pet, did you check your setup?

**Comment by temelkirci** [comment]
I have disconnect issue before I did not add my changes.if it possible ,can you connect my pc via teamviwer when you have free time?, you can check all of them easily and very fast.

**Comment by insthync** [comment]
Maybe because of Ubuntu 20.04, you should try 18.04

**Comment by temelkirci** [comment]
ok.Thank you.I will try it

**Comment by insthync** [comment]
You might expect that it will have no database connection timeout error

**Comment by temelkirci** [comment]
yeah because I do not have much players in my game.But appear a lot of timeout error in server logs.I will move to my game another server with ubuntu 18, I hope this will be solve my most of problems.
