### ISSUE TITLE
UI Min Max Value on NPC Craft Dialog

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1827]
Is there a way to make a script (Ui Character Ramdom Stats)? to show the range that each stat can give, example HP Min 16 ~HP Max 20.

https://prnt.sc/qTLJfKYwcuxx a script like this

https://prnt.sc/vrbNcMd6G89N to show this information

**Comment by juniormagalhaes** [comment]
Or is there a way to do this that I don't know how to do?

**Comment by insthync** [comment]
If you are going to add it in `UICharacterItem`, use `EquipmentItem.RandomBonus`

**Comment by juniormagalhaes** [comment]
> EquipmentItem.RandomBonus

where do I find the "EquipmentItem.RandomBonus"?

**Comment by insthync** [comment]
In `UICharacterItem`

**Comment by juniormagalhaes** [comment]
> 

don't have that option

**Comment by insthync** [comment]
I means to write the codes in `UICharacterItem`

**Comment by juniormagalhaes** [comment]
> 

ah, I don't know how to program in C#, but look for someone to do it, thanks for the tip

**Comment by juniormagalhaes** [comment]
how much would it cost to do this? Do you have an email to contact?
