### ISSUE TITLE
Why packet version is not working ?

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1829]
I am trying to kick clients who has old packet version, but why server does not kick them from server ?. Players are making auction house bug and cash bug, they do not update game via google play.

**Comment by insthync** [comment]
Where did you set the packet version?

**Comment by temelkirci** [comment]
![üü](https://user-images.githubusercontent.com/11313412/211191308-012aab95-7b20-4dfd-b3d4-8fa3c7739540.png)

I always change here packet version before I build game for server and client.What should I do extra for it ?

**Comment by insthync** [comment]
Try find and delete `PacketVersion` function in `BaseGameNetworkManager`, I will remove it in next version too.

**Comment by temelkirci** [comment]
@insthync Thank you.I will try it.

**Comment by temelkirci** [comment]
@insthync it worked.Thank you very much

**Comment by moepi2k** [comment]
Is this a buildin feature?

**Comment by temelkirci** [comment]
yeah.works very well

**Comment by moepi2k** [comment]
good to know thank you
