### ISSUE TITLE
Situation with EXP for level

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#183]
1. We set a limit of 50 levels
2. The character got level 50. After that, he continues to kill monsters and so on.
3. We are releasing a new update, where we increase the level limit to 60
4. We have characters who farm before the update.
5. After increasing the level limit, such characters get level 60 after 1 killing a monster.

* That is, they get 50-60 levels for 1 kill. It turns out that the experience accumulated and when we increase the cap level, then it is applied. Bug?

**Comment by insthync** [comment]
Yes, it's a bug, it's still collecting exp while player reached max level. I will fix it.

**Comment by insthync** [comment]
Fixed in 1.52b, I will close this issue post. If this problem still occuring, you can reopen it.
