### ISSUE TITLE
{BUG} I need help figuring out how to fix this issue with Top Down Controller:

### ISSUE THREAD

**Issue by RutzStudios** [suriyun-production/mmorpg-kit-docs#1830]
I need help figuring out how to fix this issue with Top Down Controller:

I have a target area ability, when activating ability over an enemy entity, the character performs the ability. Now Every time it either activates the basic attack prior to the ability or after followed by moving character to targeted location. When targeting the ground it performs the ability and proceeds to move to target location.

Its like stacking up the actions performed by the same mouse key.

**Comment by insthync** [comment]
Update to `1.79b2` and update the top down controller codes to fix it.
