### ISSUE TITLE
Several errors when importing the new version

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#1832]
I imported the new version through the unity website, followed the step by step and several dev_ext errors appeared, how do I solve this?I imported the new version through the unity website, followed the step by step and several dev_ext errors appeared, how do I solve this?
![Sem título](https://user-images.githubusercontent.com/106054872/211643392-2d221ea0-87e5-4674-935c-65b53d7ddb16.png)

**Comment by insthync** [comment]
Try delete `Assets\UnityMultiplayerARPG\Demo\Scripts\DevExt` folder and re-import it.

**Comment by RafaelRBizachi** [comment]
Thanks, this solved it, but my characters that use Animator Character stopped performing animations, is there any way to solve this?

**Comment by insthync** [comment]
Don't know, I don't see any of your component setups.

**Comment by RafaelRBizachi** [comment]
what I meant is that characters that use Animator Character Model, are in T-pose, both the characters and the Pets and I still haven't changed anything, I just started the game
![Sem título5](https://user-images.githubusercontent.com/106054872/211654175-8d7f40cd-074c-44f4-b7a2-afed5f72939b.png)

**Comment by RafaelRBizachi** [comment]
what I meant is that characters that use Animator Character Model, are in T-pose, both the characters and the Pets and I still haven't changed anything, I just started the game
![Sem título5](https://user-images.githubusercontent.com/106054872/211654449-0f513eb1-6609-4139-b04c-1174247753a7.png)

**Comment by insthync** [comment]
May I see component setting?

**Comment by RafaelRBizachi** [comment]
![5](https://user-images.githubusercontent.com/106054872/211657393-027cc9fb-e1db-4aa9-ac7a-91f19c1c34d2.png)
![Sem título](https://user-images.githubusercontent.com/106054872/211657395-7103119a-92e9-469d-a7f8-f0cd4deebe86.png)
![Sem título5](https://user-images.githubusercontent.com/106054872/211657396-51d5082d-ff07-4e7b-80ab-156cf35a0639.png)
![Sem título2](https://user-images.githubusercontent.com/106054872/211657399-1454d71e-7aa5-49d9-9b60-fc553f39d0c2.png)
![4](https://user-images.githubusercontent.com/106054872/211657400-53c7b9b5-d823-4eb1-a537-51dd3b4ca25b.png)

**Comment by RafaelRBizachi** [comment]
![as](https://user-images.githubusercontent.com/106054872/211657866-778b0167-2ec5-4922-9325-cd7483cd2b74.png)

**Comment by insthync** [comment]
May I try with AnyDesk?

**Comment by RafaelRBizachi** [comment]
yes , how do I configure access?

**Comment by insthync** [comment]
Just open your project and send your address to my email: ittipon.bay@gmail.com

**Comment by RafaelRBizachi** [comment]
already sent

**Comment by insthync** [comment]
Seems like it is working now, the problem is there is no animation clip imported.

**Comment by RafaelRBizachi** [comment]
Wow thank you so much you saved my day <3

**Comment by TheJuicer1** [comment]
@insthync I have the same issue when updating to 1.78b characters no longer animate :( can I buy you a coffee to help fix? 
can you tell me where no animation clip imported? Thank you

**Comment by insthync** [comment]
@TheJuicer1 Okay, let's make an appointment to look into it, you may send your available time and send any desk address to my email: ittipon.bay@gmail.com
