### ISSUE TITLE
Failed to create agent because there is no valid NavMesh

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1834]
Why I get this after run command on my server.More than 200

Failed to create agent because there is no valid NavMesh
Failed to create agent because there is no valid NavMesh
Failed to create agent because there is no valid NavMesh
Failed to create agent because there is no valid NavMesh
Failed to create agent because there is no valid NavMesh

**Comment by insthync** [comment]
Is it has a nav mesh setup on the map?

**Comment by temelkirci** [comment]
yes I have.
![uuu](https://user-images.githubusercontent.com/11313412/211919467-c723e967-115e-4ea8-b902-afc7efaabfdf.png)

![cc77c2c0-5e19-4bb7-8314-a5505be534f8](https://user-images.githubusercontent.com/11313412/211919450-5686e99c-0739-4a1c-b7e4-375f7eb5df39.jpg)
![q](https://user-images.githubusercontent.com/11313412/211919460-1d7f1f92-1e2f-44c6-9c55-f7ec54816033.png)

**Comment by temelkirci** [comment]
![Uploading sss (1).png…]()

**Comment by temelkirci** [comment]
![sss (1)](https://user-images.githubusercontent.com/11313412/211919856-159999c2-ef07-4a12-aa2f-fefc5c1bdc3e.png)

**Comment by temelkirci** [comment]
![Uploading 1.png…]()

**Comment by temelkirci** [comment]
![1](https://user-images.githubusercontent.com/11313412/211920018-93bb150d-fe56-4f70-853b-add47f77a767.png)

**Comment by insthync** [comment]
Are there any characters in the map that can't move?, I guess that the message appears when instantiating a character entity outside the nav mesh, but if all characters can move then it is mean that it moved into the nav mesh later.

**Comment by temelkirci** [comment]
I have egss that never move, only spawn mobs when you hit it.
I do not use npc manager or monster spawn area, harvastables spawn are in my game.Only drag and drop to scene

![q](https://user-images.githubusercontent.com/11313412/211924849-d94b5060-24e4-4224-8d7d-b17f06479f79.png)

**Comment by insthync** [comment]
Not sure that did you try to remove the ones placed on the scene and test it? 

Messages appearing lesser or not?

I actaully think the one which was placed on scene should have lesser problems which other that instantiated later.

**Comment by temelkirci** [comment]
I will remove all monsters from my maps and try like that

**Comment by temelkirci** [comment]
I removed all monsters and harvastables, no navmesh error on my server.I am using monster spawn area and harvastables spawn anymore.I hope it will fix my timeout and disconnect issues
