### ISSUE TITLE
[Suggestion] Change Items from Short to UInt - Core - Max Stack

### ISSUE THREAD

**Issue by tylerguitar75** [suriyun-production/mmorpg-kit-docs#1838]
Some items need to be stacked much higher than 32k. Short data type is too low and limiting - it would be much better if the core was changed to use unsigned integers for items or at least have the option to use unsigned integers for a certain type of stackable items.

This is a core change. Also, it should be unsigned because the max stack of an item will never be negative (hence uint and not int)

**Comment by insthync** [comment]
Can be int?

**Comment by tylerguitar75** [comment]
Yes, int would work too

**Comment by insthync** [comment]
If I change it all to be int then if anyone request to change it to uint, I won't accept the request.

**Comment by tylerguitar75** [comment]
Why not uint? The number will never be negative

**Comment by insthync** [comment]
It will be negative when used as part of the amount calculation, for the case that I want to remove the item's amount by another item obj.

**Comment by tylerguitar75** [comment]
Oh! That makes sense. Yes, int is perfect.

**Comment by moepi2k** [comment]
Never seen a game which use that much item stacks. Wouldnt that affect network traffic to much? If yes its a very bad change

**Comment by tylerguitar75** [comment]
Runescape has had 2.1 billion as the max item stack since classic

**Comment by insthync** [comment]
@moepi2k It can pack int byte size equally to byte or short, up to how much it is, more info: https://sqlite.org/src4/doc/trunk/www/varint.wiki .

@tylerguitar75 I think that developers shouldn't always follow other projects, they should find the solution that suits their projects.

**Comment by moepi2k** [comment]
Exactly. Copy paste a game is never a good idea. And as said already cant see the point using that hight number of item stacks. Gold yes but not items. And since its a slot based inventory system its also bad for economy to can have aömost unlimited stacks of items

**Comment by insthync** [comment]
I will change all short to int because it was requested many times, someone wants to attribute's amount to be an int, and someone wants skill level to be an int too.

**Comment by Callepo** [comment]
> @moepi2k It can pack int byte size equally to byte or short, up to how much it is, more info: https://sqlite.org/src4/doc/trunk/www/varint.wiki .
> 
> @tylerguitar75 I think that developers shouldn't always follow other projects, they should find the solution that suits their projects.

@insthync if u can make the network traffic the same, even with the larger number, idm. 
But if not i highly dont think this is a good idea, and runescape is literally the only game that does stack of that amount, and they habdle it differently...

Creating a knock off of a game, and fcking everyone else project is not ideal.. 

So if u think u can make it work the same way, 0 cons, than sure.. but if thats not the case, id rather not tbh.. but yea
you would know best

**Comment by insthync** [comment]
@Callepo It is 0 cons

**Comment by Callepo** [comment]
> @Callepo It is 0 cons

awesome

**Comment by tylerguitar75** [comment]
Everyone seems really angry about this idea, so if it's too much work, don't worry about it @insthync

**Comment by insthync** [comment]
Wow, I did it for you but you've changed rating from 5 to 3, wow.

**Comment by tylerguitar75** [comment]
You did it? I will change it back, sorry. I have just been harassed by Callepo so much

On Jan 13, 2023, at 2:35 PM, Ittipon Teerapruettikulchai ***@***.***> wrote:

﻿

Wow, I did it for you but you've changed rating from 5 to 3, wow.

**Comment by Callepo** [comment]
> Wow, I did it for you but you've changed rating from 5 to 3, wow.
@insthync 
the dude is a little insecure child, who throws tantrums. he made a suggestion, literally 4 or 5 people had concerns because it could effect everyone.. and he is only thinking about himself when he wants to make a fake copy of runescape.. 

i asked u if it has no cons to it, u said it had 0 cons, which everyone decided than it wouldnt be a problem.. 
But he only mad at me for saying the same thing everyone else said.. 

and also wtf does ME  have to do With Ittipon Rating? im suriyun now? so u mad at me and u give him 3 stars XDDDDDDDD
fcking idiot.

**Comment by tylerguitar75** [comment]
Gave him 5 stars again. I just wish the community was cleaned up from people spamming vitriol.

**Comment by Callepo** [comment]
> Gave him 5 stars again. I just wish the community was cleaned up from people spamming vitriol.

than ur the first one to be kicked, 0 contribution to the community, all u do is cry and beg for features, learn to code.

**Comment by tylerguitar75** [comment]
I've helped a lot of people in discord, and you mostly chime in to criticize, belittle, and attack people. But @insthync doesn't see that because he's busy working.

**Comment by Callepo** [comment]
go cry in a corner, this is not the place for any of that. this was done hours ago, and ur still crying becuase everyone said same shit.

**Comment by tylerguitar75** [comment]
Good, that would be fantastic! :)

**Comment by moepi2k** [comment]
@tylerguitar75 lol u changed rating from 5 to 3 while suri helping you? 🤦

**Comment by tylerguitar75** [comment]
@moepi2k go check the reviews. It’s 5 stars. Only problem is the community being totally toxic. Suri is amazing.
