### ISSUE TITLE
Errors with new version 1.79 

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1839]
I imported the new version with fresh Project and this issues appears 
![Untitled](https://user-images.githubusercontent.com/71017004/212469874-9d3165f5-806c-4df8-9292-a2b74422ea79.jpg)

**Comment by AhmedHon** [comment]
forget to import input manager .. fine now

**Comment by insthync** [comment]
You also can change active input handling to Input Manager (Old),

The input system integration is work in-progress.

**Comment by AhmedHon** [comment]
from where i can change that ?

**Comment by insthync** [comment]
![Screenshot_309](https://user-images.githubusercontent.com/2697550/212470652-0dad221a-e5a1-48a5-a541-3ae28d7b1e56.png)

Project Settings

**Comment by AhmedHon** [comment]
thx alot
