### ISSUE TITLE
Mobile canvas issue

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#184]
On an ios build (running on iphone) (not tested on android), it is necessary to press **twice** on the HotkeyButtons to activate the spells or equip objects. May be a problem with HotkeyJoysticks. Tested on an unmodified 1.52 version, regardless of the version of Unity.
![Sans titre](https://user-images.githubusercontent.com/19147694/72870274-00b28480-3ce8-11ea-83e4-a28941dc5160.png)

**Comment by insthync** [comment]
Fixed in 1.52b, I will close this issue post. If this problem still occuring, you can reopen it.
