### ISSUE TITLE
Party Quest

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1840]
when I'm in a party and I have a quest to kill monsters, the monsters that other party members kill the monsters don't count for me, was it supposed to work like that? Is there any way to count the ones that the party members kill in the quest too? if you don't have it, it would be a good resource to be added, because if you have a quest that needs to kill a boss when you kill it in a party, it counts for everyone and not just for those who killed it.

**Comment by LordPhrozen** [comment]
Uh, yeah this is very much needed for any boss kill quest, having to run it X times for each party member is pretty much never seen in the industry. But I have not tested this, if this IS how it is working, it should probably be adjusted.
