### ISSUE TITLE
[Bug?] Collision ignore layer

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#1842]
Hello,

Now I'm trying to not colliding with my pet monster. I added pet layer and set collision ignore option in gameinstance. Also my pet monster is pet layer in game by adding layer change code (since all monsters automatically have monster layer)
However my pet still colliding with player.

So I tested this in 1.78g fresh kit, just add player-harvestable ingore option.
but in fresh kit, player still colide with tree with ignore option.
![image](https://user-images.githubusercontent.com/58107601/212483448-6a0922b3-ef5c-40ef-9760-0eb1e41e99e7.png)

when you have a time, can you please check this?
when I see the collisionignore script, nothing strange.....

**Comment by insthync** [comment]
How did you test it?

**Comment by insthync** [comment]
Did you check children's layers?

**Comment by dglee2592** [comment]
Hello,
Thanks for the reply.

1. With the fresh kit of 1.78g, I add a new ignore option to the gameinstance > collision ignore script as attached image and play Single game > still colide with the harvestables
2. Yes, since i use fresh ket, the tree entity is all harvestable layer including its children

Does the player not colide with Tree in your test?

**Comment by insthync** [comment]
If you use RigidbodyEntityMovement, try change collision layer mask in open character controller

**Comment by dglee2592** [comment]
Oh it was there, now it works as intended. Thanks.
One last questions. Since all my pets are basically monster, so I need to change my pets' layer to petlayer.
I add below code to BaseMonsterCharacterEntity.cs > EntityUpdate()
                if (IsSummoned)
                {
                    if (gameObject.layer != CurrentGameInstance.petLayer)
                    {
                        gameObject.layer = CurrentGameInstance.petLayer;
                    }

This code works in Single play but not working in MMO.
For MMO which part of code I need to change for this pet layer change?
Any hint or advice will be highly appreciated. 

Thanks!!!

**Comment by insthync** [comment]
Try put the codes outside `IsServer` scope

![Screenshot_316](https://user-images.githubusercontent.com/2697550/212576182-3fff1e69-5a9c-47ec-8ce5-809412787e02.png)

**Comment by dglee2592** [comment]
Works perfect! Thank you so much!!!
