### ISSUE TITLE
Error on 2021.3

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1845]
Hi.. so ive been using 2021.1 latest and nothing was wrong.. using it for months.. then wanred to try 2021.3 and did the instructions on the guide. now it gets gets a lot of errors..

![image-2.png](https://user-images.githubusercontent.com/118698151/212569420-8ea7b65e-4e8e-456e-b0d8-296cefad7772.png)

![image-3.png](https://user-images.githubusercontent.com/118698151/212569427-81be2062-ade7-499e-bd8b-2878946bf652.png)

also tried building with mono and il2cpp.. but still get the errors.. any ideas why?

**Comment by insthync** [comment]
As I try googling it, I found it is relates to render pipeline, post processing settings, you should try find it (Incremental Player build failed)

**Comment by AsheshPlays** [comment]
I found the problem and its related to building directly onto the Google drive.. it seems it doesn't work with 2021.3.. because on 2021.1, i directly build on the google drive so it autosyncs with my host..
