### ISSUE TITLE
[Bug]Int 179

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1847]
after updating to 179 all my skills are broken

https://gyazo.com/dddc59188de175b19103437ceadede0b

only let set ints before was float and the option now looks diffrent.
pic above is buff

and this for example is damage of time. here floats are possible
https://gyazo.com/78514e297bb585cc3884a2e29f28f136

and what is the new option at the bottom? that is really confusing

**Comment by insthync** [comment]
About it https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/153-how-incremental-calculated

I will change the amount increase each level type to be float

**Comment by insthync** [comment]
Improved it in `1.79b`

**Comment by moepi2k** [comment]
Thank you, btw is there a specific reason why buffs not use min max for effect?

**Comment by insthync** [comment]
It seems like it has no reason, I just didn't plan to do it like that and if I change it later, it can affect other customers' projects, and their settings can be gone.
