### ISSUE TITLE
[ Error ] top down controller with version 1.79b also 1.79

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1848]
![Untitled](https://user-images.githubusercontent.com/71017004/212874494-c989fb81-0868-4a60-a9c8-34ff56c2f22b.jpg)

**Comment by insthync** [comment]
It has a b2

**Comment by AhmedHon** [comment]
Oh thx , it doesnt at first so didnt see it xD
