### ISSUE TITLE
New movements problems

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#185]
- New movements do not work with the **default controller** (except swimming).

-  I saw that there were parameters on the shooter controller, but when I launch the scene 00Init_Shooter I have the following error (fresh project):

NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.UISceneGameplay.IsBlockController () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Scenes/UISceneGameplay.cs:681)
MultiplayerARPG.ShooterPlayerCharacterController.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Shooter/ShooterPlayerCharacterController.cs:315)

- There is also a targeting problem on a character who is swimming and when we swim, it is impossible to shoot a target.

- Finally, is there a solution to allow the character to go up and down in the water?

**Comment by insthync** [comment]
Add this codes to `UISceneGameplay` line 680
```
                    if (!ui)
                        continue;
```

**Comment by insthync** [comment]
About "allow the character to go up and down in the water", for  shooter controller, now it can diving up and down follow where camera looking at.

**Comment by insthync** [comment]
About shooting target, I will fix it.

**Comment by Koodetat** [comment]
>                     if (!ui)
>                         continue;

It works !
Is it possible to add the other movements to the default character controller? and the possibility of getting in and out of the water via two other separate keys?

**Comment by insthync** [comment]
Add crouch, crawl, swim for default character controller ?, it's possible.

Getting up and down in water via two other seperate keys also possible too.

**Comment by insthync** [comment]
You can do getting up and down in water via two other separate keys by
Set move direction up/down in ShooterPlayerCharacterController → UpdateMovementInputs() function
For example from line 666:
```
            if (Input.GetKey("SwimUp")) moveDirection.y = 1;
            if (Input.GetKey("SwimDown")) moveDirection.y = -1;
            moveDirection.Normalize();
```

**Comment by Koodetat** [comment]
Great !
