### ISSUE TITLE
Server Build IL2CPP

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1850]
Hello! Im building a server build on il2cpp.. Everything is fine until build is completed.
But when i run server .bat file and run client, it says Map Server is not ready. But if i build server on mono, everything works fine..

this is my .bat file line

"Tantra Genesis Mobile.exe" -startMapSpawnServer -spawnExePath "D:\Google Drive\000000 SERVER_BUILDS\V4\Tantra Genesis Mobile" -startCentralServer -startDatabaseServer -machineAddress "host ip here"

(bat file command works on mono windows server build)

![Untitled](https://user-images.githubusercontent.com/118698151/212988310-e93755f4-cc11-46e4-802f-2fe0e76158b1.png)

this is how the cmd looks

**Comment by moepi2k** [comment]
then build server with mono. no need to build with il2cpp. only clinet build il2cpp

**Comment by AsheshPlays** [comment]
@moepi2k ohhhh.. but is it possible or not??

**Comment by moepi2k** [comment]
yes, i build server always mono and client il2cpp

**Comment by AsheshPlays** [comment]
@moepi2k what i mean is it possible to build server on il2cpp ?
