### ISSUE TITLE
Hold and release / Charge and Release Don't Work As Expected

### ISSUE THREAD

**Issue by tylerguitar75** [suriyun-production/mmorpg-kit-docs#1851]
Weapon attack types don't work the way you would expect.

For the charge and release, it would be best if it worked as follows: 1) charge (load) animation 2) hold animation 3) release animation

That way you can charge/load, aim, and then attack, for example with a bow, before firing. Right now they all work the same, instant fire.

**Comment by insthync** [comment]
I dont know what are you expecting, Send me your animation file to test to my email: ittipon.bay@gmail.com

**Comment by insthync** [comment]
Then I would say it is working as expected, I don't know how do you want, just do something to show me.

**Comment by insthync** [comment]
You've just not telling me what you actually want, I have to guess and add `Charge Duration` settings to weapon item data, it will be used while `Fire Type` is `Fire On Release`, if players press attack key shorter than this value their characters won't attack in 1.80. If this is not what you want then I will ignore your request about this.
