### ISSUE TITLE
Buff Hide Related Problem

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1852]
Its me again xD.. I'll get straight to thr point. So, one of my Character Class have a skill to br invisible. Going invisible is no problem. The problem is how to deactivate invisibility when my character starts to attack or do a buff skill.
How to add trigger? I tried the layering but it is not very smooth and doesnt work always.

How to add these Triggers for deactivating Invisibility:

-Active Buff
-Attacking
-Casting or Using a skill

I also want to add a self buff and party that will be able to see invisible characters. Characters with no "Eye" buff will still not see invisible characters unless the invisibility buff of that character has been deactivated or has expired, i also tried this with layering method but its not a good workaround. Hope someone can add this as a script extension or anything.

😁😁

**Comment by insthync** [comment]
In version 1.80c, I've added `removeBuffWhenAttackChance`, `removeBuffWhenAttackedChance`, `removeBuffWhenUseSkillChance`, `removeBuffWhenUseItemChance`, and `removeBuffWhenPickupItemChance` to buff data, use it to set chance to remove buff, for an example case if you want your character stop hiding when attacking an enemies, you may set `removeBuffWhenAttackChance` base value to `1` to make it remove the hide buff from your character.

**Comment by AsheshPlays** [comment]
THANK YOU!!!!!!
