### ISSUE TITLE
Item Increase Chance and Item for Increasing 

### ISSUE THREAD

**Issue by johnsmithberlin** [suriyun-production/mmorpg-kit-docs#1853]
I didn't find item enhancement features, only gem sockets. I see that items have +0 designations, but how can I make it possible to use the item and with each new improvement (+1, +2, +3 etc) the chance for a subsequent improvement was reduced? 
Also, if the improvement was not successful when improving the item, then the item was burned. 
Thank you

**Comment by insthync** [comment]
It is sounds like item refine feature

**Comment by johnsmithberlin** [comment]
> 

Yeah, but as I understood this function can be done only in relation to the character? Character statistics increase. 
I see, for example, that I can set the basic parameters for a weapon, but how do I create an item that will be an intermediary? In such a way that parameters are already written on each improvement? For example, I take some "weapon enhancement stone", use it and click on the +0 bow, (remember this is a theory), base attack of bow at +0 equals = 10, up to +3 upgrade (inclusive) - using enhancement stones guarantees a 100% chance of improvement, but after +4 there is a chance of unsuccessful improvement of the item, which means it is broken, but if it is successfully improved by +4, the parameters change according to the parameters on the +4 upgrade (like in base parameters)
So, u said I can implement this by refine option? And how? Thanks.

**Comment by insthync** [comment]
Like this request ?

https://github.com/suriyun-production/mmorpg-kit-docs/issues/1785

**Comment by AsheshPlays** [comment]
@insthync 

This is similar to my request 😁

**Comment by AsheshPlays** [comment]
Additionally, it would be also very nice to add an item that can prevent Item From Disappearing when refine fails. This will greatly enhance the gameplay. But its not a requirement but an option for players to add if they dony feel lucky. 😅

**Comment by insthync** [comment]
Implemented in 1.80b
