### ISSUE TITLE
Errors on import

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#1854]
When importing the asset pack into an empty project on Unity 2021.3.14f1 on my laptop, I get these errors. 

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\IAsyncLogProcessor.cs(7,43): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

And

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\AsyncStreamLineMessageWriter.cs(12,69): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Can anyone help me with this?

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

**Comment by shinimaru** [comment]
Thank you. It worked
