### ISSUE TITLE
White screen when running game

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#1856]
When I press play it's fine throughout the start menu and load game scenes, but once you go into the actual game scene on both 2d and 3d the screen becomes heavily tented white as if a white sprite has been set up in the canvas that covers everything with 50% opacity.

I tried turning off each of the canvases, but they don't affect the white tent. the game is still playable, but this white tent is not ok. how do i stop it?
![Screenshot 2023-01-20 143243](https://user-images.githubusercontent.com/71353444/213800485-57c389bc-5a38-49ac-93b3-548133c94a50.png)
![Screenshot 2023-01-20 143404](https://user-images.githubusercontent.com/71353444/213800509-b1b84dfe-7f88-4cdc-8c59-65e5a455623c.png)

**Comment by insthync** [comment]
Don't know, what are you doing?

**Comment by shinimaru** [comment]
I haven't changed anything. this happens on a fresh import.

**Comment by shinimaru** [comment]
it only happens in this asset pack and it only happens on the in-game scenes and goes away when switching back to main menu scene. something is happening with the camera or ui?

**Comment by moepi2k** [comment]
you write something in the search field ^^

**Comment by shinimaru** [comment]
Huh? what do you mean?

**Comment by moepi2k** [comment]
https://gyazo.com/cb83bb765c6a807e4507bcd8d92c68ff

**Comment by insthync** [comment]
Close because it is not related to the kit
