### ISSUE TITLE
[Bug] Min and max character name not working 

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1859]
I set min and max character name in game instances 2-8 , its working fine in editor but in local doesnt work .. i can write more than 8 
![2](https://user-images.githubusercontent.com/71017004/214140019-434aab95-a3c2-4aff-aa41-9e2078b2aaf4.jpg)
![1](https://user-images.githubusercontent.com/71017004/214140028-64fa1a05-167a-4af6-ab92-60ca155a2fbd.jpg)

**Comment by insthync** [comment]
Where did you set it?

**Comment by AhmedHon** [comment]
in MMO GameInstance

**Comment by insthync** [comment]
https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/7aff4af3b2a8f5f65df0d6c9cc5bcbc5d6972530

**Comment by AhmedHon** [comment]
Thx alot , works now fine
