### ISSUE TITLE
[Bug]OnClickMoveToStorage Function

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1861]
when use OnClickMoveToStorage Function on an item and there is no Storage open the item goes in nowhere
https://gyazo.com/72cc0af8222d0a771195a254c20db177

it seems it not checking if a storage like Player/Guild/Building is open

**Comment by insthync** [comment]
https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/2813cff19de6b672a741629a55c27766e689506d

**Comment by moepi2k** [comment]
is this a fix for mmo only? because in singleplayer is same like before
https://gyazo.com/b10f1879814264701dab31b84d240a1e
