### ISSUE TITLE
Server Not Start

### ISSUE THREAD

**Issue by razadortr** [suriyun-production/mmorpg-kit-docs#1862]
I rented a vds server for mmo (windows) whenever I want to run my server, I get the following error, it connects to the server on the client side, but it just gets stuck on the login or register screen and then it gives a "Request Timeout" error. I couldn't understand where I went wrong. are you

when I run it for the first time, it gives this error and then continues as follows
SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted

![image](https://user-images.githubusercontent.com/82289178/214527329-60e2f1b7-7b88-4acd-aef2-8324d07adce7.png)

I'm leaving here my log file 

[Log.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/10497955/Log.zip)

and some more screenshots
![image](https://user-images.githubusercontent.com/82289178/214528310-afa3f07d-c110-46f0-b3ce-e84392ff2c88.png)
![image](https://user-images.githubusercontent.com/82289178/214528373-d4f364d5-f6be-44a8-86f8-a8e09f0adcff.png)
![image](https://user-images.githubusercontent.com/82289178/214528460-56f1e8de-c4ea-4344-a8d4-564f55b576a3.png)
![image](https://user-images.githubusercontent.com/82289178/214528516-a577f639-5743-46ee-8b0a-7f6fac047b0c.png)
![image](https://user-images.githubusercontent.com/82289178/214528661-c5559589-4000-4f36-8c33-53835feb06e6.png)
![image](https://user-images.githubusercontent.com/82289178/214528714-a972dc97-0b60-4ee7-8ec0-0e2b4b48b0ac.png)

please tell me what is wrong? All ports on the server are open and active.

**Comment by insthync** [comment]
Which command that you use to runs servers

**Comment by razadortr** [comment]
I don't apply any commands, I just bought windows-side build and transfer files to my windows vds server and create a shortcut, then make the settings as in the document and run the exe.

**Comment by insthync** [comment]
So you have made a serverConfig.json file?

**Comment by insthync** [comment]
And which commands you put to the shortcut

**Comment by razadortr** [comment]
yes, the config files were created by itself when I ran the exe, let me share them with you;
![image](https://user-images.githubusercontent.com/82289178/214577803-d0038718-75f7-4a3a-aead-674f66e9afd5.png)
![image](https://user-images.githubusercontent.com/82289178/214577838-4b506d1f-cea4-445c-8ac6-1b3092083cf0.png)
and shortcut commands
D:\MMO\MMO.exe -startMapSpawnServer -spawnExePath "D:\MMO\MMO.exe" -startCentralServer -startDatabaseServer -machineAddress "84.32.4.111"

**Comment by razadortr** [comment]
![image](https://user-images.githubusercontent.com/82289178/214580966-a34974da-a69d-4e98-b697-8962eaac6727.png)

i still get the same error when i do what you said
SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by insthync** [comment]
Set centralPort, clusterPort, mapSpawnPort, startSpawnPort and mapPort differently

**Comment by razadortr** [comment]
So should I set them this way only in the serverconfig.json file? Or do I need to edit them on Unity side?

**Comment by insthync** [comment]
Set in serverconfig.json only, it is easier

**Comment by razadortr** [comment]
no, what I meant was that when I change the ports in the serverConfig.json file, do I need to change these ports on the unity side as well?

**Comment by insthync** [comment]
No you don't have to do it

**Comment by razadortr** [comment]
my serverConfig.json
![image](https://user-images.githubusercontent.com/82289178/214589173-fead629e-aeda-4f08-92f5-c7c0c5275d83.png)

not connecting but server side works perfectly
![image](https://user-images.githubusercontent.com/82289178/214589222-41e589d6-a456-471c-a867-3669a7effa43.png)

**Comment by razadortr** [comment]
Okey everything work perfectly, thanks a lot of !
