### ISSUE TITLE
[Bug]Player stuck latest version

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1864]
the bug still remains where player stuck in game.
https://gyazo.com/f6a5e132553896887c35befc27e8dd1e

this player is stucked in game for 10 hour even when no client is open.
also the player is dupet somehow

**Comment by insthync** [comment]
Any errors in server log?

**Comment by moepi2k** [comment]
checking

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1620
