### ISSUE TITLE
Latest Version , Stats window Issue in Build

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#1865]
In the latest version of MMO build stats window issue 
especially attributes not Updating  , working perfectly in editor  
![image](https://user-images.githubusercontent.com/1295862/214877031-ca2d408f-3a5a-45e9-a9e4-900114093d39.png)

**Comment by insthync** [comment]
Don't know, no enough info to guess, mine still works properly.

**Comment by AhmedHon** [comment]
It works fine , maybe you fucked up something

**Comment by Deepankar1993** [comment]
Not sure but it seems something with cache, as I have duplicated the GamePlaycanvas prefab and assigned the new one to the game instance now its working
