### ISSUE TITLE
swimming

### ISSUE THREAD

**Issue by charin79** [suriyun-production/mmorpg-kit-docs#1866]
Hello
Would you mind telling me what I have forgotten to let my character swim.
Did I miss anything?
![swim01](https://user-images.githubusercontent.com/102839729/214972617-fb02e7f7-a255-479e-ad7e-7719e50b5ea9.jpg)
![swim03](https://user-images.githubusercontent.com/102839729/214972621-844de21e-3da4-43b8-9e68-f81d20a4083c.jpg)
![swim02](https://user-images.githubusercontent.com/102839729/214972625-c8881a3f-f433-4016-b37d-d03cce59231d.jpg)

**Comment by insthync** [comment]
Did you set water later to water?

**Comment by charin79** [comment]
Yes, I did, as shown in picture number 2. Using the base character worked, but not with the new character I created

**Comment by insthync** [comment]
Okay, you use `RigidBodyEntityMovement`, try changing collision layer mask in `Open Character Controller` component

![Screenshot_329](https://user-images.githubusercontent.com/2697550/214997330-1ceaad5f-4a82-4c26-a02e-b0e208145a84.png)

**Comment by charin79** [comment]
I appreciate your help, everything is working now
