### ISSUE TITLE
[BUG] Aim at cursor controller - mobile version

### ISSUE THREAD

**Issue by Espeee** [suriyun-production/mmorpg-kit-docs#1867]
I was trying to set up the aim at cursor controller for my top down mobile game but the player cannot move properly. If is possible to fix it is gonna be awesome for my project . Thanks anyway in advance .

**Comment by insthync** [comment]
How is it? please attaches video files

**Comment by Espeee** [comment]
https://user-images.githubusercontent.com/93352292/215145304-e906fddb-db9e-4dfd-ac53-0384ed367841.mp4

2 things ( movement is not smooth even on my android, and also the attack is not working, only when i release the button he attack and not while i press it)

**Comment by insthync** [comment]
It is all because of the onscreen controller (an UIs which use for character/camrea controller)

For the first issue, moving is not smooth, try to fix it by deactivating `CameraRotation` controller

![Screenshot_330](https://user-images.githubusercontent.com/2697550/215152807-a1a4a6bb-171b-4a35-a2fe-d8f3009b3af1.png)

**Comment by Espeee** [comment]
Deactivating it it does not work the rotation at all for the mobile version. In standalone it works , The attack problem remain still.

**Comment by insthync** [comment]
I know, so you want to still be able to rotate ?

About the attack, I didn't tell you how to fix it yet, please wait for me for my explanation.

**Comment by Espeee** [comment]
yea, if you think about brawl star game. Thats my objective as controller

**Comment by insthync** [comment]
Can it rotate camera?

**Comment by Espeee** [comment]
no, the camera must be blocked. just the player can rotate when i press the attack button in the direction i put with the attack button pressed. #I already setted move speed while attack = 0 so the animations or mask can not be buggy.

**Comment by Espeee** [comment]
i saw an other bug meanwhile testing . Putting the aim at cursor and the mobile canvas gameplay the button (pick up / activate / exit ) does not appear and in the scene if i try to force  set active i cannot do that.

**Comment by insthync** [comment]
These component controlling buttons appearing, if you can read codes, you can find how it work easily
![Screenshot_331](https://user-images.githubusercontent.com/2697550/215159364-1e7b8619-5a4b-466f-a1bc-a3b6bfa386e9.png)

**Comment by Espeee** [comment]
im sorry but i cant fix it by myself, i dont have enough knowledge on the code side. just wanting to know how to fix that in a easier way .

**Comment by insthync** [comment]
Easiest way?, remove `Attack Button Activator`, `Pick Up Button Activator`, that is it.

**Comment by Espeee** [comment]
oh ok , thanks!

**Comment by Espeee** [comment]
is this report gonna close or will you try to fix the attack of the controller? just to know :)

**Comment by insthync** [comment]
You have to change the attack button to a button that can be moving like WASD joystick so you can copy-paste WASD joystick then change `Axis X Name` to `Mouse X` and `Axis Y Name` to `Mouse Y`  and turn on use button and add `Fire1` to button key names
![Screenshot_332](https://user-images.githubusercontent.com/2697550/215190035-1b086e68-1251-4ad0-b3b5-b29ad453b9d4.png)

**Comment by Espeee** [comment]
It almost work, if i add on the button key names Fire1 nothing happen. If i add Attack he attack but only when i release the button. how should i set the fire button works when i continue to press the button?

**Comment by insthync** [comment]
![Screenshot_333](https://user-images.githubusercontent.com/2697550/215295613-39cee0d5-b81e-497e-9780-4190cabc09a2.png)

**Comment by Espeee** [comment]
https://user-images.githubusercontent.com/93352292/215295811-b1da5e7a-2670-410e-8130-7262f2f255b6.mp4

**Comment by Espeee** [comment]
the weapon still cannot automatic attack. i try the default player controller and it works. i think is something inside aim at cursor controller which is bugged.

**Comment by insthync** [comment]
Try 1.80 and update aim at cursor controller codes

**Comment by Espeee** [comment]
it works , thanks a lot for your help !
