### ISSUE TITLE
Auction House Issue

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1868]
I downloaded the git files and put them in my project gave this error

https://prnt.sc/jLSbvqiSwm0o

I put the requirements in the project

https://prnt.sc/5BNqaapKWlhG

https://prnt.sc/gVqDGnyxaGla

**Comment by shubhank008** [comment]
I think you need to enable/add the Unity Purchases (IAP) package via package manager

**Comment by insthync** [comment]
@shubhank008 No, don't have to do it.

To fix it is just delete unused namespace https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/commit/7459e3294c613a6b2bc99bee6118c3d3b58292f7

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/215163767-8d95b4a6-b356-4b07-abc7-56512653da9e.png)
I installed the IAP an error disappeared XD

**Comment by juniormagalhaes** [comment]
Solved, thanks insthync
