### ISSUE TITLE
Player Title, Player Icon, Player Frame ?

### ISSUE THREAD

**Issue by razadortr** [suriyun-production/mmorpg-kit-docs#1870]
How can we use this data? He doesn't have much knowledge in his community.
![image](https://user-images.githubusercontent.com/82289178/215221023-cb442f10-5e41-4b65-a70c-180b767c1d82.png)

**Comment by AhmedHon** [comment]
It's like guild icon , check it in demo and do the same with player icon , title and frame :)

**Comment by razadortr** [comment]
can you show me an example? And how can I give it to the users for gain, so how will the players earn them?

**Comment by AhmedHon** [comment]
Contact me in discord
