### ISSUE TITLE
Connection reject on clients when warping in LAN mode

### ISSUE THREAD

**Issue by danielplont** [suriyun-production/mmorpg-kit-docs#1871]
Ran into this issue while testing, easy to recreate on latest version and a clean import of 1.79b using unity 2021 or 2020.

1. Build a LAN project
2. Launch at least 2 instances of build, host & client
3. Host player enters warp
4. Client player(s) gets disconnected with Connection Rejected by server prompt

I was able to find a workaround for immediate resolution, I'm new to this asset and was curious if there is something else I should be doing to handle this long term.

Issue seems to have been introduced with this change:
https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/f63961b0956d7ff0efa1d823760daca6ca4c8731

I commented out this code in BaseGameNetworkManager and was able to get around the client disconnecting.
![image](https://user-images.githubusercontent.com/12014649/215238754-781c6201-dde7-4135-85fa-73732c091f1d.png)

Hopefully this helps anyone else having the same issue until a long term fix is introduced.

Thanks!

**Comment by insthync** [comment]
Fixed in 1.80, I didn't fix it as you do, I've changed server response when player connect
