### ISSUE TITLE
HELP! [RefineProtectionItem]

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1874]
Hello! I have very little knowledge about scripting and I want to know what I am doing wrong on an extension that I created.

My goal was to add a protection item and a slot on the UI of refine. The item will protect the Item from being destroyed if refine will fail. I wanted to add it as a feature. Please help.

using UnityEditor;
using UnityEngine;

namespace MultiplayerARPG 
{

    public partial class BaseItem
    {
        public static bool RefineProtectionItem(CharacterItem refineProtectionItem, System.Action<CharacterItem> onRefine, System.Action onDestroy)
        {
            if (refineProtectionItem.IsEmpty())
            {
                // Destroy item because there is no protection item
                onDestroy.Invoke();
                return true;
            }
            else
            {
                // Destroy protection item on slot
                onRefine.Invoke(refineProtectionItem);
                return false;
            }
        }
    }

    public partial class ItemRefine : BaseGameData
        {
            
           
            [Header("Refine Protection Item")]
            [ArrayElementTitle("Protection Item")]
            private ItemAmount[] refineProtectionItem;
            public ItemAmount[] RefineProtectionItems;
        }

    public abstract class UIRefineItem : UIBaseOwningCharacterItem
    {
        [Header("Refine Protection Item")]
        public CharacterItem RefineProtectionItem;
        public TextWrapper uiTextRefineProtectionItemDestroy;
        public TextWrapper uiTextRefineProtectionItemSuccess;
        protected bool activatedProtection;
        protected string activeProtectionId;
        [HideInInspector]
        public UICharacterItem uiRefineProtectionItem;
    }

    public class RefineExtUICharacterItemData
    {
        public UICharacterItemData uiCharacterItemData;
        public CharacterItem RefineProtectionItem;
        public RefineExtUICharacterItemData(UICharacterItemData uiCharacterItemData, CharacterItem refineProtectionItem)
        {
            this.uiCharacterItemData = uiCharacterItemData;
            this.RefineProtectionItem = refineProtectionItem;
        }
    }

    public class RefineGenDevExt : UIRefineItem
    {
        private UICharacterItem RefineProtection;

        protected override void Awake()
        {
            base.Awake();
            if (uiCharacterItem == null && uiRefineProtectionItem != null)
                uiCharacterItem = uiRefineProtectionItem;
        }

        private void OnValidate()
        {

#if UNITY_EDITOR
            if (uiCharacterItem == null && uiRefineProtectionItem != null)
            {
                uiCharacterItem = uiRefineProtectionItem;
                EditorUtility.SetDirty(this);
            }
#endif
        }

        public override void OnUpdateCharacterItems()
        {
            if (!IsVisible())
                return;
            
            // Store data to variable so it won't lookup for data from property again
            CharacterItem refineProtection = RefineProtectionItem;
            if (activatedProtection && (refineProtection.IsEmptySlot() || !refineProtection.id.Equals(activeProtectionId)))
            {
                // Item's ID is difference to active protection item ID, so the item may be destroyed
                // So clear data
                Data = new UIOwningCharacterItemData(InventoryType.NonEquipItems, -1);
                return;
            }

            if (uiRefineProtectionItem != null)
            {
                if (refineProtection.IsEmptySlot())
                {
                    // Item is empty slot, still show it
                    uiCharacterItem.Show();
                }
                else
                {
                    // Item is not empty slot, so show it
                    uiCharacterItem.Show();
                }
            }
        }
    }
}

**Comment by insthync** [comment]
Can I says No ?

**Comment by AsheshPlays** [comment]
> Can I says No ?

Ok sir. Im sorry. Ill just close it then. 😔
