### ISSUE TITLE
PlayerCharacterController_Inputs.cs error after updating to 1.80

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1875]
![image](https://user-images.githubusercontent.com/118698151/215402841-7a5a239a-f0b0-4237-9401-d67a887806d2.png)

**Comment by AsheshPlays** [comment]
Heres the error in VSCode

![image](https://user-images.githubusercontent.com/118698151/215411114-422ccda4-0676-4efc-908d-b4b6ae6a2343.png)

**Comment by insthync** [comment]
It is because you not update it properly, the `FindClickObjects` function was moved to `PlayerCharacterController_Inputs.cs`

**Comment by AsheshPlays** [comment]
@insthync But that is PlayerCharacterController_Inputs.cs sir. I updated it properly like how I always update.

**Comment by insthync** [comment]
Did you delete PlayerCharacterController_FindObject ?

**Comment by AsheshPlays** [comment]
@insthync No sir. I only updated the kit and nothing else.

**Comment by AsheshPlays** [comment]
@insthync I deleted it and now its working fine. Thank you and sorry for bening a noob..

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/147-how-to-update-to-new-version
