### ISSUE TITLE
Auction house Build Error

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1876]
follow all the steps correctly as shown in the documentation, but when doing the vuild this error.

![image](https://user-images.githubusercontent.com/56885137/215511177-d235b6e0-eb57-4652-a3a8-5af0e1cd7dda.png)

**Comment by insthync** [comment]
I actually don't want to teach you to use node js you should at least learn about it, did you run `npm install` ?

**Comment by juniormagalhaes** [comment]
> 

I managed to solve the lack of installing typescript on the machine
