### ISSUE TITLE
Auction house quantity of items

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1877]
in the Auction House the quantity of the item that is on offer does not appear.

![image](https://user-images.githubusercontent.com/56885137/215602727-16e4aeb2-1ce9-4fce-a45d-26c861722c4c.png)

**Comment by insthync** [comment]
![Screenshot_341](https://user-images.githubusercontent.com/2697550/215849434-ec551d10-b1b0-43cd-a917-c64b9334c149.png)

**Comment by juniormagalhaes** [comment]
> ![Screenshot_341](https://user-images.githubusercontent.com/2697550/215849434-ec551d10-b1b0-43cd-a917-c64b9334c149.png)

thanks s2
