### ISSUE TITLE
visual issue with equipment

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1878]
https://www.youtube.com/watch?v=jvHAA1siXzg
display problem when equipping items

**Comment by insthync** [comment]
![Screenshot_346](https://user-images.githubusercontent.com/2697550/216015230-7b88d3ae-8aca-4692-9f3f-215bf0e43826.png)

Temporarily fix

**Comment by insthync** [comment]
Fixed in 1.80b
