### ISSUE TITLE
[Suggestion] Default Weapon Type animations

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1879]
A suggestion but it might be better to have default weapon animations set in Weapon Type itself rather than setting weapon attack animations in character model prefab (which needs to be done per character)
This would speed up development phase by setting default animation for each weapon type for all the characters and letting us override them on per-character level, rather than current scenario where need to set it on each and every character itself.

Example:
Currently need to set animation for a sword swing (same weapon type, lets say one hand sword) for 20 characters individually when can be done on weaponType scriptable itself and instead use the Playable component to override the default animation if want to use a custom animation for a particular character. 

![image](https://user-images.githubusercontent.com/3790163/215833569-0d4fc115-5a98-4ed5-aed1-607bcf981905.png)
------
![image](https://user-images.githubusercontent.com/3790163/215833596-95ea822e-7e0a-47e5-b650-1c06c0f1caf6.png)

**Comment by insthync** [comment]
If you request like this, it is better to apply to all weapon types, why just only default one?

**Comment by shubhank008** [comment]
> 

Yes for all weapon types, I meant to say weapon types have a default animation so we don't have to apply them to each character one by one, did not mean default weapon

**Comment by insthync** [comment]
The reasons to having it set to character model is because there are many kind of character models, so if I implement it, it won't work for all character models, I will implement it for playable character model only

**Comment by shubhank008** [comment]
> The reasons to having it set to character model is because there are many kind of character models, so if I implement it, it won't work for all character models, I will implement it for playable character model only

Yeah that would do, Playable model works.
Basically if no weapon animations set in Playable model, just use the default ones set in the WeaponType scriptable

**Comment by shubhank008** [comment]
@insthync if you do decide to do it, can you perhaps also consider default animations for skills too ?
Similar to weapons, currently need to assign skill animation for each skill for each character one by one

**Comment by AsheshPlays** [comment]
@shubhank008 this can be done with playable model.. You can have few of it as a storage or category of animations, skills, etc etc. Then it would be easier to copy paste it on the character you want to use.

**Comment by shubhank008** [comment]
> @shubhank008 this can be done with playable model.. You can have few of it as a storage or category of animations, skills, etc etc. Then it would be easier to copy paste it on the character you want to use.

what do you mean ? Sorry did not get it

**Comment by AsheshPlays** [comment]
So, what i do is create a prefab playable model, and naming it something like,

DefaultWeaponsAnimationFemale:

Ill set all animations for all default weapons animation for female. You can also do it by weapons but i prefer to put all default animations on a single prefab. Then once its set, there is an option on the playable to copy specific and paste it on the playable character prefab. That's what i have been doing recently and it improved and made everything easier and faster to set animations.

**Comment by insthync** [comment]
Added in 1.80e
