### ISSUE TITLE
Situation with quest.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#188]
1. How can we safely remove quests? If we take the quest as a character, and then remove the quest from the game, then this character is buggy. (When you open the quest book)
- I would like the quests to be completely removed from the character if we remove the quests from the game. For example, if we remove an item from the game, then it is deleted on the character and does not cause errors.
![image](https://user-images.githubusercontent.com/47291794/73182847-d703be00-412a-11ea-91f0-d9b9e9389e25.png)
![image](https://user-images.githubusercontent.com/47291794/73182866-dff48f80-412a-11ea-9d81-d314899051ac.png)
2. Bug. (When you open the quest book)
- We take the quest on the first scene.
- We move to the second scene
- Exit completely from the game (not on the menu)
- We go into the game and see an error with quests
![image](https://user-images.githubusercontent.com/47291794/73187353-5779ed00-4132-11ea-9bcb-25d09f0a0c64.png)
![image](https://user-images.githubusercontent.com/47291794/73187388-62cd1880-4132-11ea-8fcb-76cfb0b8efed.png)

- But if we enable the checkmark to display the completed quests, then the quest window opens without errors. But there are such quests there.
![image](https://user-images.githubusercontent.com/47291794/73371628-fe8f8d80-42c6-11ea-8205-0dbc6a5f4dc9.png)

**Comment by insthync** [comment]
This was fixed in 1.53. If this issue still occurs, you can reopen this issue post.
