### ISSUE TITLE
equipment socket

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1880]
When i take off the equipment it still shows up. I also looked at the videos you uploaded. I don't understand where I went wrong can you help me?
https://www.youtube.com/watch?v=NlWfQQNOlNc

**Comment by moepi2k** [comment]
So is there an isssue with equipment in 1.80? Wanted to upgrade my project but if so wiill wait

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1878

**Comment by insthync** [comment]
@moepi2k You've talked about it with me, why do you still like to flood this one?

**Comment by moepi2k** [comment]
Where i talkednto you regarding this? Just saw that post here. I never used 180 before

**Comment by BarzoStrike** [comment]
It just solves the problem of equipment sometimes getting stuck.
> [Sayfa #1878](https://github.com/suriyun-production/mmorpg-kit-docs/issues/1878)

The problem now is different, when I remove the equipment it doesn't happen when it should be invisible and this happens all the time

**Comment by insthync** [comment]
@moepi2k Facebook Chat, you mentioned this post. And said like you won't update yet.

**Comment by insthync** [comment]
@BarzoStrike I will fix it, and might upload it today.

**Comment by insthync** [comment]
Fixed in 1.80b
