### ISSUE TITLE
Custom quest Task

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1882]
Why is the Task index not being send in the Custom quest Task method? 
![image](https://user-images.githubusercontent.com/7702658/216161285-44d23dbe-7f68-4900-8791-5df78a46cf70.png)

it makes it so much harder to check ur custom task, if they are completed or not.. 

![image](https://user-images.githubusercontent.com/7702658/216161680-e59116a2-8c85-4151-bf41-4d398f6b94b7.png)

i could have done something as simple as this.. But since it doesnt have it i have to go figure out a way to find how to come to the corresponding task index

@insthync Could u add to the base that it uses this index?

**Comment by Callepo** [comment]
@insthync thank you

**Comment by insthync** [comment]
Don't know why maybe at that time I just did not realize it, I will add it.

**Comment by Callepo** [comment]
> Don't know why maybe at that time I just did not realize it, I will add it.

If u can send the current quest or the quest dataid also in the method would be even better. 

![image](https://user-images.githubusercontent.com/7702658/216223697-f57c88f8-44d9-411a-93ee-5a1606b6e7b1.png)

Because to find the Task index u need to first have the quest.. 
atm in the custom task method i added a Quest value, so i assign the corresponding quest directly to the task, so it knows which quest..
but if the quest dataid  was also send .. we have the player instance as Character

You can grab Character.IndexOfQuest(DataId)
and have a reference to the quest through code instead of me doing this
![image](https://user-images.githubusercontent.com/7702658/216223942-6fb77a3a-02f8-4cc2-8aad-157b199d7b30.png)

**Comment by insthync** [comment]
Implemented in 1.80b
