### ISSUE TITLE
Quest icon and speech issues

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#1883]
I wanted to put an image in the NPCMenu items, so when I have a main quest it will be an icon that I put in the dialog and side quest another icon, but I only find the title option.
Is there any way to import the dialog image to this menu?
![Sem título](https://user-images.githubusercontent.com/106054872/216524540-51c45a3e-4bd6-40b8-9017-7c200641651e.png)
![Sem título2](https://user-images.githubusercontent.com/106054872/216524547-9fb7e6f1-88ab-4288-8e22-53e87386dfbb.png)

**Comment by insthync** [comment]
Implemented in 1.80b
