### ISSUE TITLE
Status Effect Max Stack is not working

### ISSUE THREAD

**Issue by mmciftciler** [suriyun-production/mmorpg-kit-docs#1886]
Hello, I am using Simple Area damage Attack Skill. Here I use the status effect to the debuff section. Area Damage has been adjusted to be applied 8 times for 4 seconds. (Apply Duration: 0.5) Status effect is applied every 0.5 seconds. But I only want it applied once. I thought it would make sense to use max stack to fix this. But when I set the max stack value to 1, it had no effect.

(https://user-images.githubusercontent.com/118010169/216819788-186cd04b-786e-403c-8888-9198212094c6.png)

(https://user-images.githubusercontent.com/118010169/216819854-e2d161af-7cf3-4b46-b1c2-90211657be16.png)

**Comment by suitechsoftware** [comment]
[](https://i.hizliresim.com/3fpgu7z.png)

**Comment by insthync** [comment]
Want to set Debuff's max stack?

Why use the status effect for Area Skill?

I actually don't know how I can answer you I don't understand your setup.

**Comment by mmciftciler** [comment]
I need to create an area damage skill called Snowstorm. This areal effect; should apply a 70% slowdown to the characters. For this, I thought the Status effect was the right choice. You can see the area where I added the Skillte Status effect in the first comment. Here, the status effect restarts each time the skill deals damage. maxstack 1 or 0 should have been enough to avoid this.

![image](https://user-images.githubusercontent.com/118010169/216827400-695a4d84-167c-466b-847a-194baa2ff7e7.png)
I think the problem comes from here. It seems to have been deleted from the list and added again.

**Comment by insthync** [comment]
You can just use a debuff to decrease movement speed, don't have to set debuff -> enemy status effects when attacked, this one will work like a buff/debuff to the enemy to do something when the enemy got attacked.

**Comment by mmciftciler** [comment]
I want use to chance rate for the status effect. Your solution is not suitable for doing this.

**Comment by insthync** [comment]
I know about the chance, but why use status effects, it will work when a buff is applied to the enemy character when to buff is applied to the playing character and the playing character got attacked.

You better should request for debuff chance.

**Comment by mmciftciler** [comment]
Here is our Skill scenario:
The Wizard starts a blizzard in the area that will last for 4 seconds. Mobs in the area experience a 20% movement restriction, this movement restriction lasts for 7 seconds, and the movement restriction restricts 70% of the mob's or character's movement. Reuse: 13 seconds

**Comment by insthync** [comment]
Update to 1.80b

It will have a `fail Chance` setting in buff data, DON'T set up status effects, set up debuff's `fail chance` instead.

For your case set the debuff's `fail chance` to 0.8

**Comment by mmciftciler** [comment]
Okey.

**Comment by insthync** [comment]
Oh, I will change `fail chance` to `apply chance` because I think `fail chance` is not make sense.
