### ISSUE TITLE
[Bug]Item loss Storage

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1887]
https://gyazo.com/f678790f1adc139451cf46c3d8a6a348

when switching items from storage directly to equickable sometimes items get lost.
and there also sometimes you get a msg 'internal server error' or 'invalid index'

**Comment by moepi2k** [comment]
p.s just noticed after the robe is gone. it seems the player is bugged. robe is no longer there but it seems its equiped and giving the bonus.

https://gyazo.com/16362f24f798a25d1c21b96219304bdb
here a added a new robe. i cant equip it with 'right click' only by drag and drop. and it seems the status are doubled now same as when i wear two robes.

**Comment by insthync** [comment]
I want to see character item data from database

**Comment by moepi2k** [comment]
what exactly?

https://gyazo.com/a0a9c996e39e7f93dce0db7d82345b83

hard to find the right item since there are only ids

btw, its simple to reproduce with rings
https://gyazo.com/a10aaa8e72c7b5ae6f7982773b33673c

but also sometimes works with other equipables

**Comment by insthync** [comment]
Query by your character ID and inventory type = 1 after, item icon is empty

**Comment by insthync** [comment]
Okay, I can reproduce it, I am going to fix it now.

**Comment by insthync** [comment]
Fixed (commit title: fix: invalid `equipSlotIndex` when swapping storage item and equip item)

**Comment by moepi2k** [comment]
Great thanks for the fast replay, i will implement the commit tomorrow and test it 👌

**Comment by insthync** [comment]
Fixed in 1.80b
