### ISSUE TITLE
Auction House - Content is not available

### ISSUE THREAD

**Issue by razadortr** [suriyun-production/mmorpg-kit-docs#1888]
I have done all the necessary setups for the Auction House, the server side works perfectly, but whenever I want to add an item to the Auction House in the game, I get the error below. I don't understand where I went wrong.
![image](https://user-images.githubusercontent.com/82289178/216850408-527ec17f-b382-481a-930b-b3476a063683.png)
![image](https://user-images.githubusercontent.com/82289178/216850441-df650472-1e45-49a8-9aa1-ac3eeb88d30b.png)
![image](https://user-images.githubusercontent.com/82289178/216850481-220e2768-f96b-4b3f-a30d-e79a589385fc.png)

**Comment by razadortr** [comment]
Okay i found issue

**Comment by insthync** [comment]
So.. can I close this one?
