### ISSUE TITLE
Player Title

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1889]
I saw that there is this option in the kit, but I did not find where I use it.

![image](https://user-images.githubusercontent.com/56885137/216854499-9f869bb2-d8f3-4c79-8c34-40202cb4dafa.png)

![image](https://user-images.githubusercontent.com/56885137/216854510-3769cdea-f53c-438b-a73f-a2eb5419ed31.png)

**Comment by insthync** [comment]
After creating the title then add it to the game database

You have to create UIs for title selection, it already has all components for the UIs (try to find `UI Player Title`), I don't know that will you be able to do it.
