### ISSUE TITLE
Switching between cameras on different maps?

### ISSUE THREAD

**Issue by Hellwood** [suriyun-production/mmorpg-kit-docs#189]
First I want to say this is an awesome package, loving it. I have tried for two days to try and find a way around the GameplayCamera. Is there a way? That on map001 it uses GameplayCamera. But after using the WarpPortalEntity to map002. It can use a different camera like (GameplayCamera2)? I need a different camera setting for map002 then Map001. I can't find any documentation on the camera on you sit. If you could just point me to the right spot, Thank you 

If there is a forum for users of MMORPG Kit please point me there.

**Comment by insthync** [comment]
You may make new class which derived from controller class and override Awake function to load another camera prefab for example
```
protected override void Awake()
{
    base.Awake();
    if (Map == Map2) //<-- This is just example codes
    {
        if (CacheGameplayCameraControls != null)
            Destroy(CacheGameplayCameraControls);
        if (gameplayCameraPrefab2 != null)
            CacheGameplayCameraControls = Instantiate(gameplayCameraPrefab2);
    }
}
```

**Comment by Hellwood** [comment]
Thank you, and again this package is AWESOME.

**Comment by insthync** [comment]
Thank you :)
