### ISSUE TITLE
[Bug?] Declined Friend Request not removed

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#1892]
Hello,

After decline a friend request, the request is still remained so it keep giving friend request notification.

I think once user decline a friend request, it need to be removed from the recieved friend request list otherwise it will keep push to accept frient request.

I tested this with 1.79 fresh kit, in MMO mode.
Please have a look.

Thansk.

**Comment by insthync** [comment]
Fixed in 1.80c2

**Comment by dglee2592** [comment]
Thank you so much!!!
