### ISSUE TITLE
Equipment Entity

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1893]
Equipment Entity does not work

**Comment by Niinra** [comment]
It seems that the CacheEquipmentEntities of basecharactermodel was removed, it would be good to know why these changes used the old basecharactermodel for the addon shealth weapons

**Comment by insthync** [comment]
How it does not work?

**Comment by insthync** [comment]
@Niinra Because the structure changes because I've added priority for an equipment model data then it is having workflow changes and then that variable was removed, but it still having `CacheRightHandEquipmentEntity` and `CacheLeftHandEquipmentEntity`.

**Comment by insthync** [comment]
@Niinra `CacheEquipmentEntities`  is just `CacheRightHandEquipmentEntity ` + `CacheLeftHandEquipmentEntity` that is why it was removed.

**Comment by Niinra** [comment]
> @Niinra `CacheEquipmentEntities` is just `CacheRightHandEquipmentEntity ` + `CacheLeftHandEquipmentEntity` that is why it was removed.

Thank you very much for the reply

**Comment by BarzoStrike** [comment]
https://www.youtube.com/watch?v=Hgq2cDYMUzs

**Comment by insthync** [comment]
Fixed in 1.80c2

**Comment by BarzoStrike** [comment]
v1.80c2
https://www.youtube.com/watch?v=uczLb7w6TBg
I don't know if we need to do something different now but it's not working like it used to.

**Comment by insthync** [comment]
No, you guys don't have to do anything, just wait me to fix it.

**Comment by insthync** [comment]
Fixed in 1.80c3, you actually should create or reopen the issues post.
