### ISSUE TITLE
Pierce Through Entities

### ISSUE THREAD

**Issue by charin79** [suriyun-production/mmorpg-kit-docs#1894]
It won't go through when I set pierceThroughEntities to 10. 
![01](https://user-images.githubusercontent.com/102839729/217303442-33d3dc04-97bf-4267-8e87-d8c5ec595f1b.jpg)

**Comment by insthync** [comment]
As I try it works as intended, not sure that you want it to pass through the wall, not just an entity?

**Comment by insthync** [comment]
My test result 
https://youtu.be/3Je4wJ4BEds

**Comment by charin79** [comment]
You are correct, it does work

It would be helpful if you could explain how to configure On init Prefab, On get Instance, On push Back. If you can provide pictures, that would be very helpful
![01](https://user-images.githubusercontent.com/102839729/217587874-204be6c4-b245-4fe5-8e7d-f0e76dfd37e2.jpg)

What script do I use for Impact Effects?

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/178-impact-effect
