### ISSUE TITLE
[Help] Give item/skill to player through code

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1895]
Hi suri, can you help me with example code to give a player a item or skill through code/programmatically ?

Trying to create a airdrop system of sorts to give all existing players/charas any new starting item/skills.

**Comment by insthync** [comment]
var item = CharacterItem.Create();
character.IncreaseItems(item)


CharacterSkill skill = CharacterSkill.Create();
if (character.IndexOfSkill() < 0)
    character.Skills.Add(characterSkill);

**Comment by shubhank008** [comment]
@insthync So I tried using character.AddSkill but it is not working and the `out message` is showing me UI_ERROR_INVALID_CHARACTER_DATA

Which I believe is being returned from here
![image](https://user-images.githubusercontent.com/3790163/221016566-ab093944-d697-4d0c-9f1b-27ace752056e.png)


The AddSkill method calls the `if (!skill.CanLevelUp())` which returns the above error/message if the skill is not part of character's data/database.  
Is it intentional ? I thought we could add new skill to a character regardless if it was part of his data/scriptable or not (just like how we do for items)

**Comment by insthync** [comment]
Yes, it is works as  intend, if you don't want to check the skills are from player character data or not, you have to delete those lines

**Comment by insthync** [comment]
Or should I just change how it work? I remember that someone request to me to add that checking codes so I add it.

**Comment by shubhank008** [comment]
> Or should I just change how it work? I remember that someone request to me to add that checking codes so I add it.

Sorry for late followup, I was away for a wedding.
I donot want to explicitly ask you to change how it works if it is as intended, I just found it weird that the AddSkill method does not actually allow you to add a new skill to character if its not part of his characterData. 

Currently I think AddSkill works more like a LearnSkill or LevelSkill instead.

For my own use, I will delete those CanLevelUp check lines as I want to allow my characters to learn/get skills without them being part of their initial character data.

Thanks for the quick reply as always.
