### ISSUE TITLE
[BUG] Mobs become invulnerable to melee

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1897]
Persisted since v1.76, but only just came across this again today in 1.80c.

Players attack monsters with swords / Melee weapons.

Sometimes the monster will not even register any attack and becomes invulnerable to that player.

Occasionally other players can kill the monster, but sometimes it also glitches out for them, too.

Ranged damage still works.

I had player reports today about this but am not certain on any specific steps to reproduce.
Melee will work most of the time, but then suddenly stop for one or two monsters.

I've only experienced this in MMO.

**Comment by insthync** [comment]
Hope that it is not character inside safe zone issues

**Comment by BJPickles** [comment]
No, very far outside safezone.

**Comment by juniormagalhaes** [comment]
It's the pivot of the melee attack when it's very close to the monster, the pivot is inside the collider of the monsters and doesn't do damage, I had the same problem and I solved it by putting the pivot of melee attack on the player's costars.

![image](https://user-images.githubusercontent.com/56885137/217645162-3e50e317-48f7-4d92-a3ab-1e8bd8d71034.png)

**Comment by BJPickles** [comment]
Not sure it is. Doesn't matter if the player respawns- the mob is completely undamagable from that particular player.

I've seen it at different Melee ranges and entire groups of players try to kill the mob from different angles and none of them could damage it.

**Comment by BJPickles** [comment]
Here's a video:
https://youtu.be/AyE-ladGfEk

**Comment by insthync** [comment]
Are there any error messages?

In the video, it is offline/LAN or MMO?

Have to find why only some monsters

**Comment by BJPickles** [comment]
No error messages. Only experienced on MMO - seems to be when mobs respawn after being killed.
These are spawned via prefab in scene.

**Comment by moepi2k** [comment]
Ahh now i understand, you let spawn monster with prefabs not not with area spawner? I experienced a similar issue when placing monster prefabs in scene. Since then i only use area spawner.

**Comment by insthync** [comment]
I cannot reproduce it yet.

**Comment by BJPickles** [comment]
Just following up on this to say I think it's because of prefab rather than through spawner but I have another game test on Saturday to confirm with players.

**Comment by insthync** [comment]
Still can't be reproduced the bug
