### ISSUE TITLE
[Not Solved..] Declined Friend Request not removed

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#1899]
Hello, 

I'm really sorry to reopen this issue. I have tested this with 1.80c2 but this still happens.
When click "Decline" button, declinded message pops up but it is still not removed from the list (see screenshot)

I'm not sure this happens only with me, but when you have a time can you check this again?
Or is there any setup for this in UI?
I'm so sorry for asking this again.

![image](https://user-images.githubusercontent.com/58107601/217971468-95b1180c-b26f-4af7-80e7-71de571d24e0.png)

**Comment by insthync** [comment]
My test result 

https://youtu.be/3yZbbRxZF3U

**Comment by insthync** [comment]
The fix commit https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/476dbcc2947c8928987c7574d67972a8828cced9

**Comment by dglee2592** [comment]
Oh indeed. The fix is applied on MySQL only. I was using SQLite so that was the problem.

Since I want to use SQlite because it is more simple, I'm looking at the SQLiteDatabase_Character.cs to apply this fix as same, but it is not easy for me.
Is there any chace to have this fix for SQLite as same?

**Comment by insthync** [comment]
No, it actually should fix both

**Comment by dglee2592** [comment]
Oppps. I'm really sorry. I was trying wrong version.. I just downloaded the top one from the list.. it was 1.80c not c2.

Now I confirmed all work perpect! My apology for makeing you waste your valuable time for this stupid reopen issue.
Now I close this. 

Thank you so much!!!!
