### ISSUE TITLE
2D - If you click to move, then WASD, player retains movement from click to move

### ISSUE THREAD

**Issue by wtfcolt** [suriyun-production/mmorpg-kit-docs#190]
1.52b, 2D - Pressing and releasing any of "WASD" after click to move should stop the character. Currently, if you click then use "WASD" to move, and stop pressing and WASD keys, player will start walking towards click target again.

**Comment by insthync** [comment]
Fixed, thank you for bugs report, I will upload new version within 8 hrs.

**Comment by insthync** [comment]
Fixed in 1.52c
