### ISSUE TITLE
[Help]Server does not connect[Digital Ocean]

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#1900]
I hired a digital ocean server and followed the whole step by step, the server apparently is connected and all ports are open correctly but the client says that it is not possible to connect to the server
![image](https://user-images.githubusercontent.com/106054872/218008376-43cd0307-c94e-460d-8a44-fd80a76307df.png)
![image](https://user-images.githubusercontent.com/106054872/218008561-5a5e1d39-ff38-472d-bf84-eef769aae0db.png)
![image](https://user-images.githubusercontent.com/106054872/218008610-1400116d-e4cd-4546-b47f-71602b31f69a.png)
![Sem título](https://user-images.githubusercontent.com/106054872/218008843-fa0e962e-e516-422c-89da-ed528a62fdb4.png)
![image](https://user-images.githubusercontent.com/106054872/218008910-1dbc185a-9fb0-45ed-8f39-39a20f6a739f.png)

**Comment by RafaelRBizachi** [comment]
I changed my settings and the messages changed but I still can't connect to the server
![image](https://user-images.githubusercontent.com/106054872/218250162-990d3e35-49ac-463b-b1ae-5cf8e7c4cee3.png)
![image](https://user-images.githubusercontent.com/106054872/218250183-da6641e4-11c9-4beb-bcf7-b8e7782999b8.png)
![image](https://user-images.githubusercontent.com/106054872/218250208-567bce58-3bde-4043-96d0-b74b5742dfe8.png)
![image](https://user-images.githubusercontent.com/106054872/218250227-6e568683-cb0b-4555-9f33-2e837c7c9838.png)
![image](https://user-images.githubusercontent.com/106054872/218250252-3c71f80c-5ee3-4a2a-8d3c-c89c19de07dd.png)

**Comment by RafaelRBizachi** [comment]
![image](https://user-images.githubusercontent.com/106054872/218250416-d5636424-8ea7-4248-9555-ce1ad316c82e.png)

**Comment by insthync** [comment]
- The first, check your `QueuedWorkbenchEntity` -> `itemCraftFormulas`, if some entry is empty or not.
- The second one might be occurring because it cannot connect to MySQL

**Comment by RafaelRBizachi** [comment]
the first one happened because I ended up using a standard dataBase that had this queue, but in the second one I opened the doors and I'm logged into phpMyAdmin but it still gives the same error regardless of what I do
![image](https://user-images.githubusercontent.com/106054872/218269473-14fff862-aea4-458e-8f4a-512e4133e73a.png)
![image](https://user-images.githubusercontent.com/106054872/218269484-fa6e7eed-343c-4564-be91-6ea0c40bf518.png)
![image](https://user-images.githubusercontent.com/106054872/218269499-435b0c1d-dfa7-4443-bd69-450745d6f09d.png)

**Comment by RafaelRBizachi** [comment]
![image](https://user-images.githubusercontent.com/106054872/218269540-6276d711-9e3f-4273-9df2-5b0b5e917b0c.png)

**Comment by RafaelRBizachi** [comment]
I tested it with sqlite and it worked, is there anything I need to do that I did wrong?

**Comment by RafaelRBizachi** [comment]
I solved the problem by changing root to admin in mySql configuration, for some reason I didn't have root access
