### ISSUE TITLE
MissingReferenceException when portal

### ISSUE THREAD

**Issue by desertfoxgame** [suriyun-production/mmorpg-kit-docs#1901]
I got this problem when run 2D Singleplayer asset. Please help

MissingReferenceException: The object of type 'PlayerCharacterEntity' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
MultiplayerARPG.BaseGameEntity.get_EntityGameObject () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/BaseGameEntity.cs:265)
MultiplayerARPG.NearbyEntityDetector.FindEntity (UnityEngine.GameObject other, MultiplayerARPG.BasePlayerCharacterEntity& player, MultiplayerARPG.BaseMonsterCharacterEntity& monster, MultiplayerARPG.NpcEntity& npc, MultiplayerARPG.ItemDropEntity& itemDrop, MultiplayerARPG.BuildingEntity& building, MultiplayerARPG.VehicleEntity& vehicle, MultiplayerARPG.WarpPortalEntity& warpPortal, MultiplayerARPG.ItemsContainerEntity& itemsContainer, MultiplayerARPG.IActivatableEntity& activatableEntity, MultiplayerARPG.IHoldActivatableEntity& holdActivatableEntity, MultiplayerARPG.IPickupActivatableEntity& pickupActivatableEntity, System.Boolean findWithAdvanceOptions) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Default/NearbyEntityDetector.cs:367)
MultiplayerARPG.NearbyEntityDetector.RemoveEntity (UnityEngine.GameObject other) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Default/NearbyEntityDetector.cs:253)
MultiplayerARPG.NearbyEntityDetector.OnTriggerExit2D (UnityEngine.Collider2D other) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Default/NearbyEntityDetector.cs:145)
UnityEngine.Object:Destroy(Object)
MultiplayerARPG.PlayerCharacterController:OnDestroy() (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Default/PlayerCharacterController.cs:230)

**Comment by insthync** [comment]
When teleporting to another map?

**Comment by desertfoxgame** [comment]
![image](https://user-images.githubusercontent.com/72794028/218067816-d63a5797-0ace-415d-96d0-066108977b90.png)
It happened in Demo2D when teleport from map A to map B only. Maybe missing something in config?

**Comment by insthync** [comment]
This one actually can be ignored, it is a generic error when something tries to access a function or variables in-game object which is destroyed.
