### ISSUE TITLE
 Why do I report errors when importing assets

### ISSUE THREAD

**Issue by checkycechen** [suriyun-production/mmorpg-kit-docs#1904]
the error was ↓

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\IAsyncLogProcessor.cs(7,43): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

how do i fix it?

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021
