### ISSUE TITLE
[Suggestion] Debuff - "Disallow Move" is too many things perhaps?

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#1905]
![image](https://user-images.githubusercontent.com/7896457/218331552-99422deb-6ee8-4ec9-b5a6-a85b192f5e16.png)

So in this section, I'm surprised to see everything bundled up into "movement". I think it would benefit everyone to have this broken up into:
-Walk
-Run
-Jump
-Crouch
-Prone

Probably an easy add, but It should also probably be in the base kit. Just my 2cents Keep up the fantastic work :)

**Comment by insthync** [comment]
Added to 1.81f
