### ISSUE TITLE
[BUG] Missing return in TextSetterByLocaleKey

### ISSUE THREAD

**Issue by JoRangers** [suriyun-production/mmorpg-kit-docs#1906]
Hi, 
I think I found a missing "return" for the method : public string Text (Line 24)
Tested in 1.80d

![image](https://user-images.githubusercontent.com/47748200/218487975-13dbca37-5bcd-4a95-bb3e-ffb5b17d5cac.png)

**Comment by insthync** [comment]
Thank you
