### ISSUE TITLE
[Bug] Webgl Audio Not Playing (SFX/BGM)

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1907]
There seems to be some bug in Webgl due to which any BGM music or some of the SFX do not play in webgl.
They do play fine in Editor or Windows Standalone.

Tried to add a background music (should play all the time), didn't play.
Character's hit effect sound plays.
Damage Hit effect sound does not play (the SFX meant to play when you or something is hit).

No errors in console.

Unity 2021.3.15f
Mmorpgkit 1.80
Webgl

**Comment by insthync** [comment]
WebGL on PC?

**Comment by shubhank008** [comment]
> WebGL on PC?

Yes WebGL, tested on chrome browser and opera browser (Windows PC)

**Comment by insthync** [comment]
As I tried, it is still playing properly.

**Comment by shubhank008** [comment]
> As I try, it is still playing properly.

Weird, in my case player's attack SFX plays
BGM doesn't play
Enemy/Monster hit effect doesn't play (when player's attack hits)

I will do some more testing and report back

**Comment by shubhank008** [comment]
> 

@insthync event after extensive trial and error, could not get the damage/getHit sfx to play
BGM also doesn't play but that is not kit related/included so I understand

Suprisingly the player's attack SFX works

Attack and damage SFX works normal in editor and standalone
