### ISSUE TITLE
[Bug] Monsters not attacking Summons

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#1908]
Seems a bug (unless intended) but Monsters donot attack player's summon even if the summon is near them or even attacking them (and player is far away).

**Comment by shubhank008** [comment]
@insthync exact problem here
https://cdn.discordapp.com/attachments/542092305247502346/1075422476919656478/movie_001.mp4

This is my exact problem, I summoned my monster (its not a pet but a summoned monster through skill)
Its attacking and killing monsters, but they are not attacking it back

My monsterentity and the skeleton monster are both on character layer

**Comment by shubhank008** [comment]
@insthync any idea why this might be happening ? I tested in demo (single player, not mmo) and monsters do were attacking the orc summons  
Both the prefabs are set to Character layer (if layer/tags play any role)

This is my monster

![Unity_6OyHhV00aU](https://user-images.githubusercontent.com/3790163/219966647-c8e73fa9-76c7-49f9-9937-b0d345c279b4.jpg)

![Unity_5SolpWpSUO](https://user-images.githubusercontent.com/3790163/219966695-8fcca839-1047-4d5a-b7cf-4c1e56897f1b.jpg)


and this is my summoned (monster)
![Unity_lfKeY3yBwB](https://user-images.githubusercontent.com/3790163/219966658-8d701179-774d-4308-8f68-59d4d718835b.jpg)

**Comment by insthync** [comment]
Fixed in 1.80e
