### ISSUE TITLE
Self Status Activation On Specific Skill Chain

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1909]
So, I am wondering if its possible to create a status effect or a buff/debuff activated after a skill has been used to apply on the next specific skill.

Let's say I have 3 skills, Skill-1, Skill-2 and Skill-3.

So, if I use Skill 1, a buff will be activated but will only apply on the next specific skill.

Example:

Use Skill1 then Buff Enabled to self like 30% Critical Chance will be applied if I use Skill3. Thr buff will not apply if I use Skill2. It works like a combo skill. Also After using Skill1, the buff activated also has a duration, if duration is expired, then I use skill3, there is no more Critical Chance.

I dont know if it's already implemented or if there is a workaround on that feature. I have been trying to do workarounds but my only problem is I can't apply it to a specific skill.

That is all and Good day to you Suriyun!

**Comment by insthync** [comment]
Very confusing
