### ISSUE TITLE
Warping Instance Issue

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1910]
I try to enter an instantiated map it hangs on the warping screen... and then disconnect the player and when the player tries to enter the game again this happens.

![image](https://user-images.githubusercontent.com/56885137/218723769-d44d14eb-633a-438a-a622-da769c3dd270.png)
![image](https://user-images.githubusercontent.com/56885137/218723817-46f2dc01-4814-47bf-a4f0-8315a626f605.png)
![image](https://user-images.githubusercontent.com/56885137/218723866-51d80356-10a7-488b-9601-8077bb5cb554.png)

Log https://drive.google.com/drive/folders/1y-4WRBymcGt63bwWsHyx6drGwz04fLu3?usp=sharing

**Comment by insthync** [comment]
That instance map may be big and takes too long time to load, then it is timeout and cannot connect to the map

**Comment by juniormagalhaes** [comment]
> That instance map may be big and takes too long time to load, then it is timeout and cannot connect to the map

![image](https://user-images.githubusercontent.com/56885137/218731866-efbd62ce-cd17-4544-9f61-25652e2a7c36.png)

this is the size of the map and what's in it

**Comment by insthync** [comment]
Hmm, then it should not takes long, did you try locally or connecting to server, it might just not able to connect because of unopened ports

**Comment by juniormagalhaes** [comment]
> Hmm, then it should not takes long, did you try locally or connecting to server, it might just not able to connect because of unopened ports

![image](https://user-images.githubusercontent.com/56885137/218735089-e4632c89-e9ca-46a8-afcc-405f1037dfeb.png)

![image](https://user-images.githubusercontent.com/56885137/218735188-51561a48-787a-428d-8375-2c106580f8d5.png)

these are the open doors and the maps that are in my game

**Comment by insthync** [comment]
Warp from which map?

**Comment by juniormagalhaes** [comment]
> Warp from which map?

MAP_006

**Comment by juniormagalhaes** [comment]
the warp of non-instantiated maps is working normally, this Map MAP_006 worked correctly with instance, when I uploaded the new version of the kit the players reported this error.

**Comment by insthync** [comment]
May I try your game, have to check the client log too.

**Comment by juniormagalhaes** [comment]
If you need an Admin account just say

**Comment by juniormagalhaes** [comment]
![image](https://user-images.githubusercontent.com/56885137/218740997-abd93342-814d-4f08-8e5e-ac8a7d882d2f.png)

when you logged in i was logged out too XD

**Comment by juniormagalhaes** [comment]
> Or it might not have enough RAM to load and run a new map, did you check your server usage?

![image](https://user-images.githubusercontent.com/56885137/218752262-cefde30e-c9ef-4fe2-ace8-01f968d5b158.png)

'-'

**Comment by juniormagalhaes** [comment]
how is the consumption of memory ram? before it was in 5gb, does each map add to the memory?

**Comment by juniormagalhaes** [comment]
> 

Yep

**Comment by juniormagalhaes** [comment]
I will remove some maps to see the consumption

**Comment by juniormagalhaes** [comment]
I removed two maps and the ram memory decreases

![image](https://user-images.githubusercontent.com/56885137/218761114-13e77e9e-e359-467a-a6ab-8461ba7cdd1b.png)

**Comment by juniormagalhaes** [comment]
the Warp for the instantiated scene worked, it was the ram memory.

**Comment by insthync** [comment]
Which old version?

**Comment by juniormagalhaes** [comment]
> Which old version?

1.79

but there were less scenes when it was consuming 5gb now there are more scenes.

**Comment by insthync** [comment]
Okay

**Comment by juniormagalhaes** [comment]
a doubt is it normal to give a shader error on the server? I use URP, I ask this because I see other people on discord that when they run the server it doesn't show any shader error

**Comment by insthync** [comment]
Normal

**Comment by juniormagalhaes** [comment]
ok
