### ISSUE TITLE
Monster targeting issues

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#1912]
Where do I change the code so that the first target is the Pet and not the player?
I'm making a pokemon style game and the enemies focus on the player first so I had to add an effect that the player becomes invisible for 1 second after starting the battle, it worked but it's not what I wanted
Another thing is the monsters are changing targets in the middle of the battle, I send the "tank" pet in front it becomes the target but after a few seconds the "BOSS" changes the target to another pet and continues changing the target throughout the battle. battle, is there a way to force him not to change targets while in battle?

**Comment by insthync** [comment]
In `MonsterActivityComponent`
