### ISSUE TITLE
[Bug] Start over-ride position does not work.

### ISSUE THREAD

**Issue by Espeee** [suriyun-production/mmorpg-kit-docs#1917]
![image](https://user-images.githubusercontent.com/93352292/219955497-d922ac81-cc5a-4a61-a2e1-edc9f6955671.png)
Good afternoon, i was tweaking with the start position feature but these conditions by faction does not work as start position when i create the character. Just only when i die and respawn.

**Comment by insthync** [comment]
Fixed in 1.80e
