### ISSUE TITLE
Character Stats 

### ISSUE THREAD

**Issue by phoneixtulpar** [suriyun-production/mmorpg-kit-docs#1919]
We want to create a variable(Standart Character Stat) that will increase Attack Power and Magic Power in Stats.

I give an example:

When players increases STR and INT Stat points
The player's overall attack power and magic power stats will also increase.

How can we make it?

**Comment by moepi2k** [comment]
https://gyazo.com/1b2f352b8b8040ef1d38e56caded992d

**Comment by phoneixtulpar** [comment]
Thank you for your answer but I think there is some misunderstanding.  Actually I'm talking about character stats not about weapon stats.

**Comment by moepi2k** [comment]
yea thats how you can do it. effectiveness is a character attribute which you can use to increase e.g spellpower or attack power in this way

**Comment by insthync** [comment]
Added in 1.80e
