### ISSUE TITLE
Docs linking to wrong place

### ISSUE THREAD

**Issue by ben-roberts** [suriyun-production/mmorpg-kit-docs#192]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/025-getting-started-mmo links to https://medium.com/suriyun-production/mmorpg-kit-getting-started-singleplayer-lan-47f7ce16a0b1 ... looks like it should link to https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan these days

**Comment by insthync** [comment]
Thank you for correcting me. I’ll do it right away.
