### ISSUE TITLE
[ SUG] ] For attributes and damage element

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1920]
Would be nice to make attributes able to increase Damage elements

**Comment by insthync** [comment]
The same ? https://github.com/suriyun-production/mmorpg-kit-docs/issues/1919

**Comment by insthync** [comment]
I think in the future it will have a new post "Attributes to increase resistance", "Attributes to increase defend"

After the next version it won't have free features adding any more, I think I am kind to you guys for so long.

**Comment by AhmedHon** [comment]
I thank you for all your work really .. yea you r so kind i appreciate that

**Comment by AhmedHon** [comment]
> The same ? #1919

same but for damage elements .. i didnt see that post before

**Comment by insthync** [comment]
Added in 1.80e
