### ISSUE TITLE
[Bug] Skinned mesh renderer no working

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#1921]
Before updating this, the skinned mesh renderer thing worked perfectly, the option with the playablecontroller now stopped working
![image](https://user-images.githubusercontent.com/115952096/220033521-09200431-babb-49f5-ad5d-18a3e83a6ed2.png)

**Comment by insthync** [comment]
Update from which version to which version?

How did you setup the hair?

The hair need to use bones data or it ban just place into transform above the head?

**Comment by Niinra** [comment]
The hair you use bones so that it is recognized as humanoid and grab the behavior directly with the skinned mesh renderer everything worked fine using the option:
![image](https://user-images.githubusercontent.com/115952096/220173096-294486e6-b632-4611-9970-b5a4aeae6b78.png)
Since everything is within the same mesh there was no problem but since I updated it stopped working

from 1.80c is working normal and now in 1.80e it doesn't work anymore

**Comment by insthync** [comment]
Hmm, but I didn't make changes relates to skinned mesh renderer, how can this happen?

**Comment by Niinra** [comment]
Of course I don't know this application but I already download it

**Comment by Niinra** [comment]
> May I try it via AnyDesk?

I already have the application, let me know when you are available to see how to fix this problem

**Comment by insthync** [comment]
Hello, did you try 1.81?, if you did, is the problem fixed?

**Comment by Niinra** [comment]
@insthync Still the same with the latest version

**Comment by insthync** [comment]
Fix by add this codes

![Screenshot_402](https://user-images.githubusercontent.com/2697550/226239734-9de73e90-a3d7-4823-b1bd-ae8509010631.png)
