### ISSUE TITLE
Microsoft.Bcl.AsyncInterfaces Errors

### ISSUE THREAD

**Issue by mmciftciler** [suriyun-production/mmorpg-kit-docs#1923]
![image](https://user-images.githubusercontent.com/118010169/220204797-cdc7921c-4dff-4dbd-a93a-34fdf7295b06.png)

**Comment by AhmedHon** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

**Comment by mmciftciler** [comment]
I tried this page infos. But not fixed to errors.

**Comment by insthync** [comment]
Please copy full error message, that one is useless.

**Comment by mmciftciler** [comment]
Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\AsyncStreamLineMessageWriter.cs(12,69): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

andd

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\IAsyncLogProcessor.cs(7,43): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'


Api Compatiblity Level => it doesn't metter Net Framework or Net Standard 2.1 same error.

**Comment by mmciftciler** [comment]
I also downloaded and changed the Microsoft.Bcl.AsyncInterfaces file for other kits and the result did not change. But this way I tried had solved this problem in some previous versions.

**Comment by insthync** [comment]
Which Unity version? from the message you may try delete Microsoft.Bcl.AsyncInterfaces.dll file.

**Comment by mmciftciler** [comment]
unity version: 2021.3.5f1 LTS.

It is strange. Errors did not change even though I deleted the file. No new errors occurred or existing errors were not lost.

**Comment by insthync** [comment]
May I try by using AnyDesk?

**Comment by mmciftciler** [comment]
I made a mistake. In fact, when you delete the DLL file that is the subject, these two logs appear on the console.

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\Unity\UnityLoggerFactory.cs(33,33): error CS0012: The type 'IAsyncDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

and

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Plugins\ZLogger\Unity\UnityLoggerFactory.cs(34,24): error CS0012: The type 'IAsyncDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

**Comment by insthync** [comment]
It might have `Microsoft.Bcl.AsyncInterfaces` included in other packages, try find it remove the package then reimport my `Microsoft.Bcl.AsyncInterfaces`

**Comment by moepi2k** [comment]
i use same unity version and its works fine when do this 
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

**Comment by mmciftciler** [comment]
@moepi2k  this is always the default solution. There are people who have pointed out this solution before. The posted solution does not solve the problem.

**Comment by mmciftciler** [comment]
@insthync Can we try by using AnyDesk?

**Comment by mmciftciler** [comment]
In my opinion, the problem has to do with .NET. Which using .NET version ?

**Comment by moepi2k** [comment]
You not should just import it, you also have to delete the 3 files which are mention. I made a fresh import right now and it works fine

**Comment by mmciftciler** [comment]
@moepi2k  I applied this, the problem is not caused by this.
