### ISSUE TITLE
Physical Impact

### ISSUE THREAD

**Issue by phoneixtulpar** [suriyun-production/mmorpg-kit-docs#1925]
What steps do I need to take in order to:

A character throws Persona B.

Character A wielding the bow weapon pushes character B backward.

a physical interaction between the characters.

You know guys, this experience should be a must in MMORPG, RPG Games. Users want experiences that affect each other.

**Comment by mmciftciler** [comment]
I'm looking for this too. is there a way to do this?

**Comment by phoneixtulpar** [comment]
Any updates?

**Comment by insthync** [comment]
If you want to do it by yourself, you may add apply force function to entity movement and use it to apply force.

**Comment by khongtuong** [comment]
interesting

**Comment by mmciftciler** [comment]
Can you add this to the Next version? What we do can also cause problems in multiplayer.

**Comment by insthync** [comment]
@mmciftciler No

**Comment by phoneixtulpar** [comment]
@insthync You say, you have to pay when you need new features. I sent you an e-mail about the new features, but you didn't reply to my e-mail.

I emailed these addresses;

ittipon.bay@gmail.com
contact@suriyun.com

**Comment by insthync** [comment]
Okay, I see it, now I am going to collect features that people requested, and going to make a donation goal in ko-fi, so people can having participate to the project improvement.
