### ISSUE TITLE
Hit Only Selected Target not work

### ISSUE THREAD

**Issue by desertfoxgame** [suriyun-production/mmorpg-kit-docs#1928]
I tested a bow with hit only selected target but it's not work as expected. 
Seem it is not FindTargetHitBox in missile failed but lockedTarget when Damage spawn missile failed.
Can you check that?

**Comment by moepi2k** [comment]
upgrade to 180e

**Comment by desertfoxgame** [comment]
I just tested latest version 1.80e but still the same. When i fired an arrow to selected target but there are another monster between, arrow will hit the middle one

**Comment by moepi2k** [comment]
Yea that how it works. Its like a physical projectile and always hit the first one

**Comment by desertfoxgame** [comment]
Actually it’s not correct because we have “Hit only selected target” tick and in missile script hit detection have the code for exclude other if it have locked Target. Problem is locked target never get assigned

**Comment by moepi2k** [comment]
Then test older version, i never seen that it works like that

**Comment by desertfoxgame** [comment]
But that mean locketTarget variable never get assigned and hitTargetOnly bool not work as expected

**Comment by moepi2k** [comment]
as i understand its meant for melee. when u use a angle of 90 degree and use hitTargetOnly it only hit the target which is selected. when not use the option it hit all targets in range

**Comment by desertfoxgame** [comment]
Atually it not work with melee also. Just tested that. All monster within range gonna be hit, not only selected one

**Comment by insthync** [comment]
![Screenshot_383](https://user-images.githubusercontent.com/2697550/221150651-0de0e504-7bc2-4a95-abfb-df2d7e8d121b.png)

**Comment by insthync** [comment]
But the melee one seems to be false report, as I try it work as intend.

**Comment by insthync** [comment]
No, melee and missile is difference so the melee one is work properly

**Comment by desertfoxgame** [comment]
Ahh my false when not checked hitOnlySelectedTarget with current using sword. Checked it again and it work as expected. Hmm

**Comment by desertfoxgame** [comment]
Got the issue that missing DamageableHitBox in gameObject. It missing with 2D sample entity. But somehow it worked with Melee logic

**Comment by desertfoxgame** [comment]
Also I need to change logic like this and it work now
![image](https://user-images.githubusercontent.com/72794028/221332257-5210ed34-76d6-486f-920e-6c70ce1cca6e.png)

**Comment by insthync** [comment]
I already told how to make it work.
