### ISSUE TITLE
[Bug?]Cool down for Items not showing

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1929]
When use Item Cool Down on Items like 
https://gyazo.com/d0656bb929318a07e50770a672a81bd5

in the ui it never show it. only for skills.
https://gyazo.com/fb0ae1e8d13d794bd819f834cb984961

https://gyazo.com/be5660ec62605e974c8a233e6f21561e

**Comment by majimboo** [comment]
+1 noticed this on the latest version of the kit. specially on mobile.

**Comment by insthync** [comment]
Fixed in 1.81
