### ISSUE TITLE
[Bug] quest "complete after talked". The indicator not working properly.

### ISSUE THREAD

**Issue by Espeee** [suriyun-production/mmorpg-kit-docs#1930]
![image](https://user-images.githubusercontent.com/93352292/220903950-c8eade19-d431-4d32-845f-0935dbcdb1b5.png)
the indicator is white but it is supposed to be yellow on the npc where i want to talk with.

**Comment by insthync** [comment]
It is actually not a bug, I intended to make it work like that.

**Comment by insthync** [comment]
Fixed in 1.81
