### ISSUE TITLE
[Bug]Pets

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1931]
1) there are two bugs with pets.
when i spawn pet it is marked as Ally (as u can see on minimap). but then when i switch map it becomes red for owning player. even when its not attacking. but it behaves wrong in view to other players then

https://gyazo.com/3a53446e979fdb46c31a9d5f3673f1e9

2) i not use that option -> https://gyazo.com/655f90b1450e6880820589752889e268
but even then when player idle with somoned pet. and an enemey reach range the pet starts attacking

**Comment by moepi2k** [comment]
-> https://gyazo.com/0ab9b1baa3e034d32ebce3a374c1ed6c here in fresh kit 180e

**Comment by insthync** [comment]
> -> https://gyazo.com/0ab9b1baa3e034d32ebce3a374c1ed6c here in fresh kit 180e
I don't understand this one

* * *

I think it is just a visual bug which can be fixed in `CharacterAllianceIndicator`

**Comment by moepi2k** [comment]
Ok let me check, but what about point 2. My summon/pet starts attacking nearby enemies automaticly even when unchecked 'is agressive when summoner is idle'

**Comment by moepi2k** [comment]
for point 2) i found the fix
-> MonsterActivityComponent.cs
https://gyazo.com/e10a3893c153e32dce0a1d094c31b8fe
and
https://gyazo.com/c7523834883201883d7e3b6d93553cb2

**Comment by insthync** [comment]
Thank you

**Comment by moepi2k** [comment]
thank you, worked :)

**Comment by moepi2k** [comment]
oops i need to reopen it. 
for the function it works now. but when i build the client without server code the map indicator is wrong. pet always shows as enemy even when its ally.
https://gyazo.com/0a4bb52ee046afc454791ea39d8b1603

when you have client with server code builded it shows correctly.

**Comment by insthync** [comment]
Fixed in 1.81

**Comment by moepi2k** [comment]
Greeat thanks, can you maybe post the fix?
