### ISSUE TITLE
Movement sideways are broken after/during combat. (Shooter Controller, Combat mode)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#1932]
After a combat or sometimes just attacking without aiming at an enemy, the movement sideways is broken. Instead of using the 45 degre animation it move foward while going sideways.  I've tried for more than a week to fix the problem, playing with the controller, animations, animator, nothing fix it.

There is a video:  https://medal.tv/games/requested/clips/WNrqqlT34iEua/d1337Vz15QmM?invite=cr-MSwzY0QsNDQ3NDMxODYs

Let me know if you need more information (screenshots etc).

Thank you

**Comment by insthync** [comment]
I will fix it.

**Comment by Eniotnacram** [comment]
Thank you, let me know if you need more information, I'm pretty sure it's a bug in the code because as I said, I've tried everything to make it work on my end with the anims settings, configuration, etc.

**Comment by insthync** [comment]
- I can't reproduce it yet, how to make it occurs? just move while attacking?
- Which kind of character model, `Playable Character Model`?

**Comment by Eniotnacram** [comment]
- My default weapon is a range weapon missile
- Using the "Animator Character model"
- Using Generic animations
- Custom Animator (litterally duplicated the default one)

![Controllerinfo](https://user-images.githubusercontent.com/46734935/221929725-466249c3-a1cb-409b-ad7d-708ba09422bc.png)

![Controller](https://user-images.githubusercontent.com/46734935/221929492-8a1d16bd-bd61-4ac0-adf0-3dc94d747c6d.png)

![HeroMale](https://user-images.githubusercontent.com/46734935/221928457-3189d8b7-98ee-4a86-90ba-a829b6f6e734.png)

![CharacterController](https://user-images.githubusercontent.com/46734935/221928216-65403e0a-ac01-4c62-b899-d6e343f9ea44.png)
.

**Comment by Eniotnacram** [comment]
Its working well with the "playable character model" I think I'll go with that. So Its a bug with the "animator character model"
