### ISSUE TITLE
[Bug] Item drop

### ISSUE THREAD

**Issue by Espeee** [suriyun-production/mmorpg-kit-docs#1933]
![image](https://user-images.githubusercontent.com/93352292/221430489-b4128160-4cc9-4ad7-90a8-0815631de8f4.png)
When i die the player lose also the weapon type i setted as excluded.

**Comment by moepi2k** [comment]
That option is not for player loot, its for monster loot

**Comment by Espeee** [comment]
Oh ok thanks. Its not possible to add that to players too?

**Comment by insthync** [comment]
New features request again? 
It seems like a simple request but this is what I have to think:
1. I have to add another option to add items to characters, now it has dropped on the ground, and corpses looting.
2. How about when it is going to overwhelm, drop on ground, or just destroy?
3. Or customers would want an option to set it to drop on ground or just destroy while a new option (add items to character directly) is enabled.
4. I have to add an option to map info and game instance.

**Comment by Espeee** [comment]
?
