### ISSUE TITLE
Damage Sockets

### ISSUE THREAD

**Issue by mmciftciler** [suriyun-production/mmorpg-kit-docs#1938]
What if it was possible to freely add damage transforms and play different animations for damage taken from those points? For example, the effect of pushing the head forward with damage taken from the head for a head shot. But effect sockets cannot be more than one.

**Comment by mmciftciler** [comment]
![image](https://user-images.githubusercontent.com/118010169/223509941-eea1316d-af48-4ed1-9b59-1b662be6fdfa.png)
![image](https://user-images.githubusercontent.com/118010169/223514890-bd4e8840-ec51-4a91-a2fa-b99d23a5a669.png)
![image](https://user-images.githubusercontent.com/118010169/223514987-46df7278-440b-4f4e-b32d-75e932eb09e1.png)

I want to add "DamageTransform" for headshot. A list of "DamageTransforms" created for different body parts like this is required. In the region name and transform structure. This is a list with the same features as "effectContaniers".(Image 1) For example, I can create an "enemy falling on his back" (animation) with a bullet hitting his head, or I can add a different animation that "dies holding his stomach" for an enemy shot in the stomach. I need to be able to specify different "GetHit" animations. A single "GetHit" animation is used.(Image 2) Here I will need the "GetHits" animation list.(Image 3)

**Comment by insthync** [comment]
You misunderstand the damage transform, it is the transform where objects like bullets, fire ball will be spawned, what you are looking for is `DamageableHitBox`, which is already implemented in the kit.
