### ISSUE TITLE
Party functionality exhibiting multiple bugs

### ISSUE THREAD

**Issue by Zurigan** [suriyun-production/mmorpg-kit-docs#194]
This is in the demo LAN project. 2D and 3D

1. If you accept an invite to a party then go through a couple of portals the party UI will show you as 'not in a party' so you can't leave.
2. If the leader leaves the party you still won't be able to use portals
3. If, after leaving the party, the ex-leader uses a portal you'll still get dragged through with him

Unity 2019.3.0f6 / Kit v1.52b / OSX 10.5

**Comment by insthync** [comment]
Fixed sometime ago.
