### ISSUE TITLE
[Bug]data lack in mysql

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1940]
Do you have any plan how to find a damage data in database?

![image-8](https://user-images.githubusercontent.com/2422714/222957769-51159231-8739-4fda-a2cb-f8505037369d.png)

When a data is damaged or whatever the player stuck in loading screeen. I had thise once with few players before i wiped my server. Now someone have the problem again.

Hard to find the brokeb data

**Comment by insthync** [comment]
Try to find just character's related data for example, if you want to find which item data is broken, then find in `characteritem` by `characterId` querying

**Comment by insthync** [comment]
And you should look log messages, if it is not enough info, then try add more log messages writing
