### ISSUE TITLE
(Paid Request) UI Min Max Value

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1943]
Is there any way of contacting me to negotiate the price to make the script you explained [here](https://github.com/suriyun-production/mmorpg-kit-docs/issues/1827)?

**Comment by insthync** [comment]
The codes will be shared with other customers, are you okay?

**Comment by juniormagalhaes** [comment]
yes i'm ok

**Comment by insthync** [comment]
5 usd, pay at https://ko-fi.com/insthync

**Comment by juniormagalhaes** [comment]
> 

https://ko-fi.com/home/coffeeshop?txid=3d49584c-680e-482e-9d42-cd4875038d6b

**Comment by insthync** [comment]
Added to 1.81d
