### ISSUE TITLE
Dupe bug CharacterInventoryExtensions.SwapOrMergeItem

### ISSUE THREAD

**Issue by Monty001** [suriyun-production/mmorpg-kit-docs#1945]
SwapOrMergeItem can result in duplication where the toIndex becomes reduced/invalid as a result of the RemoveAt() reducing the size. As a result you'll get duplicates and destroy / replace items the incorrect item with the new stack.

Will only happen in unlimited/simple inventory modes. Repeatable in 181

![image](https://user-images.githubusercontent.com/61992788/224286137-3373bb66-8dfa-4c75-8106-4edee4ca3850.png)

**Comment by insthync** [comment]
Ahhh, I see, so move character.NonEquipItems[toIndex] = toItem; to above of character.NonEquipItems.RemoveAt(fromIndex); may fix it.

**Comment by Monty001** [comment]
Yeah that's what I've done. Wasn't sure if you intended the order to make sure the original is removed first but that seemed like a way of making it safe. Was surprised I hadn't picked it up before as I've had people randomly losing items and couldn't figure out why, but think it was coming from here.

Monty

**Comment by insthync** [comment]
No intention, just do something to make it work.
