### ISSUE TITLE
Weapon at the back during , run , walk, stay, idle  stances

### ISSUE THREAD

**Issue by SkyRain2020** [suriyun-production/mmorpg-kit-docs#1946]
How can we put the weapons such as, sword, bow, wand etc at the back of the character  when item was equiped?
all i can see in game is attack animation of the weapons and only attack stance is available

can we make weapons at the back of the character while in
Idle
run
walk
?

if tis already inluded in the it, how can we make it??
if not
can you make this add on on next update please

thank you very much

**Comment by insthync** [comment]
When equipped? Not unequipped?

**Comment by SkyRain2020** [comment]
the weapon is still equipped  (sword, bow, wand , etc)
and theres a a toggle   between attack stance and non-attack stance
when we switch to  non-attack the weapon automatically go to character's back
when toggle to attack mode the weapon will go to chracter's hand

thanks again

**Comment by LordPhrozen** [comment]
I believe a sheathing system has been added. @insthync is there any documentation added on its setup?

**Comment by SkyRain2020** [comment]
> I believe a sheathing system has been added. @insthync is there any documentation added on its setup?

I think it s only for gun weapons
Or if i miss something

I hope this add on will be included
Or the guide perhaps if is already available
For sword,bow, wand and other weapon that need that position when in non attack mode

Thanks

**Comment by khongtuong** [comment]
> > I believe a sheathing system has been added. @insthync is there any documentation added on its setup?
> 
> I think its not complete yet There still no sheat animations Or we miss something?
> 
> I hope this add on will be included Or the guide perhaps if is already available For sword,bow, wand and other weapon that need that position when in non attack mode
> 
> Thanks

you can check the discord community, already had a sheath add-on base on Suri animation there

**Comment by insthync** [comment]
Don't have to use any addons

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/155-sheathing-animations

**Comment by SkyRain2020** [comment]
> hink its not complete yet
> There still no sheat animations
> Or we miss something?

thank you very much  sir, ill check it now
