### ISSUE TITLE
MapNetworkManager.SaveCharacter() / SummonBuffs primary key error with multiple players.

### ISSUE THREAD

**Issue by Monty001** [suriyun-production/mmorpg-kit-docs#1947]
Stumbled upon this running through some server logs this morning.

ERROR MySQLDatabase [2023-03-08 20:33:18] - MySqlConnector.MySqlException (0x80004005): Duplicate entry '0_0' for key 'summonbuffs.PRIMARY'

SummonBuffs can't save properly as their id will be the summon index + "_" + the buff index on the summon.

As id is the primary key two players with buffed summons will throw primary key errors when running MapNetworkManager.SaveCharacter() .

I think it probably should be characterId + summon index +"_"+buff index or something similar. Although probably cheaper to do that on the query rather than in the message?

![image](https://user-images.githubusercontent.com/61992788/224481201-2bfe6647-7fe3-417b-837e-aa3dd2c6373b.png)

Monty

**Comment by insthync** [comment]
Thank you
