### ISSUE TITLE
Decrease currency after click button in MMO

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#1948]
I want to decrease a currency after click button on item dialog.

        void ClickChangeBonus()
        {
            GameInstance.PlayingCharacter.IncreaseCurrency(GameInstance.Singleton.GameplayRule.bonusChanger, 1);
            GameInstance.PlayingCharacterEntity.CallServerDecreaseCurrency(GameInstance.Singleton.GameplayRule.bonusChanger, 1);
        }

These are not working in MMO.
But works in singleplayer mode.

I get this error.

ArgumentException: NetDataWriter cannot write type Currency
LiteNetLib.Utils.NetDataWriterExtension.PutValue (LiteNetLib.Utils.NetDataWriter writer, System.Type type, System.Object value) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/NetDataWriterExtension.cs:150)

**Comment by insthync** [comment]
You have to call to do it from client to server, you can use RPC function to do it, for example:

```
public ClickToGetGoldComp : LiteNetLibBehaviour {
  public BasePlayerCharacterEntity entity;

  [ServerRpc]
  private void RpcGetGold() {
    entity.Gold += 10;
  }

  public void OnClickGetGold() {
    RPC(RpcGetGold)
  }
}
```

**Comment by temelkirci** [comment]
public bool CallServerDecreaseCurrency(Currency currency, int amout)
        {
            RPC(ServerDecreaseCurrency, currency, amout);
            return true;
        }


        [ServerRpc]
        protected virtual void ServerDecreaseCurrency(Currency currency, int amout)
        {
#if UNITY_EDITOR || UNITY_SERVER

            (this as BasePlayerCharacterEntity).DecreaseCurrency(currency, 1);
#endif
        }


my code here.But not working.what is the difference between with yours ?

**Comment by insthync** [comment]
You can't send ref of currency, you can send currency's DataId, and find currency at server side (`GameInstance.Currencies.TryGetValue()`)
