### ISSUE TITLE
There's no pathfinding in 2D 

### ISSUE THREAD

**Issue by Zurigan** [suriyun-production/mmorpg-kit-docs#195]
3D uses NavMesh, this seems to be missing in the 2D project. This should be added for feature parity,  can't really build an MMO without some sort of pathfinding system!

**Comment by insthync** [comment]
You can use [this extension](https://github.com/insthync/UnityMultiplayerARPG_2DAI) for 2d pathfinding system

**Comment by ben-roberts** [comment]
> You can use [this extension](https://github.com/insthync/UnityMultiplayerARPG_2DAI) for 2d pathfinding system

I could, or I could copy the navmesh one from the ummorpg asset, or roll my own ... the issue is that many extra steps are needed to get basic MMO functionality if you want to make a 2D game. The kit doesn't live up to expectations in this area.
