### ISSUE TITLE
New Feature: Battle Point

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1950]
Is it just a value to see the strength of the character like the gear score, or does it work in another way or for something else?

**Comment by AeonTR** [comment]
I gave the idea for the development of the system and the working logic is as follows;
the character's total damage power is the sum of everything (weapons, armors, rings,stats)

**Comment by insthync** [comment]
It is a sum of everything, attribute, skill, resistance, armor, damage amount, and stats, you can set the difference score to each https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/154-character-battle-points
