### ISSUE TITLE
UIItemRandomBonus

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1952]
Is there any easy way to leave the integer in UIItemRandomBonus?

https://prnt.sc/KfIU7hOWINXl

**Comment by juniormagalhaes** [comment]
https://prnt.sc/_m5lWe70Yd7K

and for some reason, the HP is the normal value and the percentage, even I don't try to hp by percentage on the item

**Comment by insthync** [comment]
[MMORPG-KIT_UIItemRandomBonus_Fix.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/11013303/MMORPG-KIT_UIItemRandomBonus_Fix.zip)

Try this
