### ISSUE TITLE
Instance issues, not working.

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1953]
Teleporting to instance dont work, and leaving instance dont work..
the code is checking for the instancelocation dictionairy for the player before its even added to the list

![image](https://user-images.githubusercontent.com/7702658/226376083-aa89ae47-0e4f-458e-b24b-0f07f5758833.png)
 this is called at the end of the method, but at the start its trying to get currentposition from the player which checks for the location in the dictionairy, before it was even added. 
![image](https://user-images.githubusercontent.com/7702658/226376368-f8039d7b-380a-462c-9c29-b9b679cc05fd.png)

this throw exception server sided.

**Comment by insthync** [comment]
Can you fix it?

**Comment by JoRangers** [comment]
Hi insthync, 
I tried to copy/paste the fix but the function **public void SetInstanceMapCurrentLocation(uint objectId, string currentMapName, Vector3 currentPosition)** needs to be above the #endif (line 803) else I got some error (mmorpg kit version 1.81d)

**Comment by Callepo** [comment]
> [insthync/UnityMultiplayerARPG_MMO@1083577](https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/1083577c213597c7ad25e0d53ce410cd4cdf69ee)

This only fixed entering the instance, once u are inside and u wanna leave by teleporting , u cant, u get null points again 
![image](https://user-images.githubusercontent.com/7702658/226492634-97094e01-630b-45a9-8a7e-4f5b14f84c43.png)
 from this now

**Comment by insthync** [comment]
Can you fix it?

**Comment by Callepo** [comment]
we did something that made it work, we changed the object id to player id
![image](https://user-images.githubusercontent.com/7702658/226502216-a38b80d2-d22a-4eca-a8be-705f7f68e34a.png)
and the methods for get current location and map name can pick it up
![image](https://user-images.githubusercontent.com/7702658/226502346-9f97eac9-af45-4ef4-b677-4bdbfc14e1a4.png)

and the dictionairy gets filled here 
![image](https://user-images.githubusercontent.com/7702658/226502491-53deb98a-ec93-40d7-9786-09bcaa18e34f.png)

This makes teleporting in and out work fine as far as i tested

**Comment by Callepo** [comment]
also , try remove if the db services fails
![image](https://user-images.githubusercontent.com/7702658/226502785-6d836be6-0801-47a2-a0ce-887a2992b6de.png)

**Comment by Callepo** [comment]
Object id seems to be the problem, its not same on instance, but player id is, so it can actually find the right id and wont throw null pointers

**Comment by insthync** [comment]
Okay, I decided to change it to use character's ID
