### ISSUE TITLE
Potion Ui Elements

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#1956]
When I put it in the ui to show the effects of the potions, even when I leave the potion crafting screen, and I go to craft another item, the effect of the potion still continues in the ui of the other item

https://prnt.sc/DljRpMtiIveV

https://prnt.sc/DKAT13mGZPnL

https://prnt.sc/pOCh2TxfOND-

https://prnt.sc/zEI2m-meIpoP

https://prnt.sc/ZG0Pcc96IgoR

**Comment by insthync** [comment]
You just did not setup ui's root game object properly.

**Comment by juniormagalhaes** [comment]
it was the root gameobject, thanks XD

**Comment by juniormagalhaes** [comment]
When you use the UI Attribute Amounts or the Stats In the UI, and the item is an item with Random Bonus, the item doubles the status, it shows the normal random, but also generates a random number to PRefill the UI Attribute Amounts, Example, I found out because I want to create Sockets that give Fixed attribute status, but in the SOcket UI it is normal, but when you open an item with random bonus, this image happens.

https://prnt.sc/bdj9W3DQqcnH
https://prnt.sc/LE0yGh00gXK1

**Comment by insthync** [comment]
I don't get it.

**Comment by juniormagalhaes** [comment]
Create an item with random intelligence and another with normal fixed intelligence for example, then put it to craft on the npc, in the UI you put the Ui attributes Amounts and the UI Item Random Bonus, as in the image below.

https://prnt.sc/slsC4GYkekA7

In the item with the fixed Attribute, it will appear normal, in the item With random bonus, the normal random bonus will appear, but it will also generate a random number of the random bonus to fill the Ui attributes Amounts, as in the iamge below

https://prnt.sc/bdj9W3DQqcnH

**Comment by insthync** [comment]
Can you change color to show what is UI Attribute Amounts and what is UI Random Bonus?

**Comment by insthync** [comment]
In that picture, how many is the Wisdom in your item setting?

**Comment by insthync** [comment]
Okay, don't do anything, I know whats I have to do.

**Comment by juniormagalhaes** [comment]
https://prnt.sc/r4Z3EmIY0hHI
https://prnt.sc/Zp_dkHb8Yc4p

**Comment by juniormagalhaes** [comment]
I forgot to say, when the item is already in the inventory, it works correctly, even without the random Bonus UI, it must be because the values are already defined for the generated item

**Comment by insthync** [comment]
Fixed in 1.81g, next time, you should create a new post when you having new problem.
