### ISSUE TITLE
Error with newest update Version 1.81f2 with player Character Controller.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#1957]
When (in the editor) you go on the Character prefab Female_CC or Male_CC there is an error in the editor.

"NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.CharacterControllerEntityMovement.OnDrawGizmos () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/EntityMovementSystems/CharacterControllerEntityMovement.cs:164)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)"

With brand new kit untouched freshly imported on an empty project.

Using unity 2021.3.21f1

**Comment by insthync** [comment]
Fixed, but I won't upload it soon because it is very lacking content to update, this one is very easy to fix, you can find what is null easily then you just make it don't null. Or just ignore it, it won't break anything.
