### ISSUE TITLE
Error building Player because scripts have compile errors in the editor

### ISSUE THREAD

**Issue by focushyper** [suriyun-production/mmorpg-kit-docs#1960]
This happend after lastest update. 

Assets\UnityMultiplayerARPG\Core\UnityRestClient\Scripts\RestClient.cs(1,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Error building Player because scripts have compile errors in the editor

Build completed with a result of 'Failed' in 1 seconds (833 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

UnityEditor.BuildPlayerWindow+BuildMethodException: Error building Player because scripts have compile errors in the editor
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002cc] in <683db824f2154b7c9f84bd4e86ddfe9f>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <683db824f2154b7c9f84bd4e86ddfe9f>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan

**Comment by insthync** [comment]
![Screenshot_409](https://user-images.githubusercontent.com/2697550/227272640-9efdab80-2424-41d3-92c2-344ff8ca9d5f.png)
