### ISSUE TITLE
Random Animations after Idle

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1962]
I am wondering if is it possible to have multiple animations for idle. Like if we dont move or dont do anything for like 15 seconds, the character is from Idle animation then initiates a random "Bored Animation"?

**Comment by insthync** [comment]
Possible if you can made changes to character model codes to play other animations

**Comment by AsheshPlays** [comment]
@insthync Can i use the character controllers provided by the kit like Advanced Character Controller with Land? and other controllers? Or how do we use them? Because on the controllers, I know how to add multi animations using blend tree but when i attach any of them, my character dont move anymore.

**Comment by insthync** [comment]
In 1.82, I've implemented custom animation playing, you can setup custom animations in `Playable Character Model` -> `Custom Animations`, you can use entity's `CallAllPlayCustomAnimation` function (which can be called by server) to play animations, can see an usage example in `PlayCustomAnimationAfterIdle` component.

**Comment by AsheshPlays** [comment]
@insthync 

This is working good but there's a small problem with it. Is there a way to disable the custom animation when starting another action?


https://user-images.githubusercontent.com/118698151/230979045-5bd27409-86b5-4013-a85f-f752fc4e6895.mp4

I am currently using Open Character Controller.

**Comment by insthync** [comment]
Try to detect movement changes from character entity -> movement/extra movement to stop custom animation

**Comment by AsheshPlays** [comment]
@insthync 

ok i tried but failed. i also tried using Has(MovementState.Forward) and failed.
Sorry. Im very bad in coding.

**Comment by insthync** [comment]
Pay me 5 USD at https://ko-fi.com/insthync, then I will write a script which did that for you.
