### ISSUE TITLE
Errors (NewtonSoft)

### ISSUE THREAD

**Issue by DevMMORPG01** [suriyun-production/mmorpg-kit-docs#1963]
I was having this error below
![aaaa](https://user-images.githubusercontent.com/90834568/227635791-18960c12-2dbe-4bb6-b4a8-a11f6b83f6b9.png)

So I applied what you replied to others having the same error:
```https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan ```

where I add
``` "com.unity.nuget.newtonsoft-json": "3.0.2" ```
into ```manifest.json```

But now I have another 40 errors.
See image below

![errors](https://user-images.githubusercontent.com/90834568/227634868-dea59fe5-c3a4-459f-ae54-f1f0b2397318.png)

**Comment by DevMMORPG01** [comment]
errors gone after kit update to latest march 22 update. new errors are seen. 

will try to fix on my own.

**Comment by SimionVoda** [comment]
For Version 1.86d still pop-up 12 errors for this Closed Issue.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/155235911/9ec4c0a7-80f2-405e-898a-d84009286cd4)

**Comment by insthync** [comment]
https://docs.unity3d.com/Packages/com.unity.inputsystem@1.7/manual/index.html

Try install this
