### ISSUE TITLE
Spawning Origin of Damage / Missile Entity

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1967]
I have a question about spawning damage entity or missile entity like the arrows of bow. Is it possible to spawn it from a custom location on the kit? Like i want to spawn it from the hand ?

**Comment by insthync** [comment]
Yes, it can you can move missile damage transform to hand bone

**Comment by AsheshPlays** [comment]
@insthync 
ohhhhhh so thats what damage transform is for.. xD
thank you! i never touch those default stuffs..

Thanks again!
