### ISSUE TITLE
(PAID REQUEST) Simple Character Customization 

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1968]
How much does it cost to request a simple character customization on character creation screen like to only change hair atleast? I used UMA but it breaks a lot of my progress, so I decided to stay within the kit only. Im no good in coding, so I have like 1% c# knowledge. 😔😔

**Comment by insthync** [comment]
I think it is pretty specific for your game, I can't make it generic for all projects, I don't know how many options will enough for all users

**Comment by AhmedHon** [comment]
calle made a free one but need tp update it

**Comment by AsheshPlays** [comment]
@insthync
everyone is using UMA for the customization and yes its good for pc, but for mobile, it's kinda heavy. So, a feature from the kit itself would be nice. Everyone can use it. I think also that it would add value to your kit because we all like to do small customization before we start leveling up. atleast 2 slots would be enough maybe?

I tried copying this but as i said, im stupid in c# xD

https://youtu.be/0MDu2W0cldQ

**Comment by AsheshPlays** [comment]
@AhmedHon

A core feature would be nice for people like me that have zero knowledge in coding. All I really know is porting games and rely on AIs 😅😅

So, forgive me if i do sound stupid 😥

**Comment by insthync** [comment]
I have an idea but this one won't support scaling, it means that you can't change eye size, nose size, and so on, can only change its shape by swapping models. Are you okay with that?

**Comment by AsheshPlays** [comment]
@insthync
Sorry for the late reply. No need for scaling. Swapping objects is fine. And how much that would cost sir?

**Comment by juniormagalhaes** [comment]
I think something similar to what Fallen did would be cool

**Comment by insthync** [comment]
@juniormagalhaes I don't know about it.

**Comment by juniormagalhaes** [comment]
I use it and it's pretty cool to put any model, but you have to configure it of course

**Comment by LordPhrozen** [comment]
A simple character creation system with swapping models would be great to have out of the box, and make extending it ( blendshapes and such ) far easier for those who do want to do that.

**Comment by AsheshPlays** [comment]
Well, a simple one is waaaay very nice. Swapping models or GameObjects is enough. We can do so many things with just that only. No need for advanced customizations.

**Comment by BJPickles** [comment]
TBH there are 2 existing, paid addons that already support what you're requesting.

Why not support Fallen and Calle?

**Comment by AsheshPlays** [comment]
@BJPickles
Ill say this straight. Me and my friend are making the the project. Hes the one who bought the asset and not me but only him is on the discord with all the channels accessed. Also we already have fallen's addon, but i guess he didnt update it when the kit updated almost weeks ago, where the kit changed core of equipment of left and right weapon, we actually waited long enough, but idk what happened because I am not the one in contact with him. So, that is the reason why.

**Comment by BJPickles** [comment]
> @BJPickles Ill say this straight. Me and my friend are making the the project. Hes the one who bought the asset and not me but only him is on the discord with all the channels accessed. Also we already have fallen's addon, but i guess he didnt update it when the kit updated almost weeks ago, where the kit changed core of equipment of left and right weapon, we actually waited long enough, but idk what happened because I am not the one in contact with him. So, that is the reason why.

Have you tried Calles? 
I use that and it works perfectly as intended.

**Comment by BJPickles** [comment]
Calles does exactly what Suri is saying he will do. It just swaps meshes.

Eye colour, hair, face, scars etc. Especially if you're willing to pay for it now, then surely it would be quicker to buy something that already exists and works?

**Comment by AsheshPlays** [comment]
@BJPickles
We dont have that much budget. And yes, its a bit disappointing what happened. This is our game btw. 


https://youtu.be/ciiBkxjNRzo

**Comment by AsheshPlays** [comment]
@BJPickles I am only asking Suri how much it would cost and i am not saying i am willing to buy it because i dont know how much it is yet. 😔

**Comment by BJPickles** [comment]
> @BJPickles We dont have that much budget. And yes, its a bit disappointing what happened. This is our game btw.
> 
> https://youtu.be/ciiBkxjNRzo

It's $45
(https://callegaming.online/product/synty-character-creator/)

How much do you think Suri is going to charge for this custom paid addition?

**Comment by AsheshPlays** [comment]
45USD is a huge money here. 😅😅

**Comment by BJPickles** [comment]
Suri might surprise you, but normally if I request a custom feature, I expect to pay $200 or more for it.

**Comment by AhmedHon** [comment]
i prefer it add to core better than an addon one , its not good to ask the one made the addon to update it every time  and wait him .. so im with Ashesh .... and yes not all buys the main cash is dollar .. for example to me 1 dollar cost 34 pounds .. so 45 is much to him and me also ^^ !

**Comment by AsheshPlays** [comment]
@AhmedHon

Same reason too. If Core gets an update that you also must update and breaks the addon, its not good in an urgent situation. Let's say you have players, they will wait until you also update your game while you also wait the addon gets an update. So, a simple customization on the core is enough. We are not asking for small details. Hair and Face is enough for me at least.

**Comment by AhmedHon** [comment]
> @AhmedHon
> 
> Same reason too. If Core gets an update that you also must update and breaks the addon, its not good in an urgent situation. Let's say you have players, they will wait until you also update your game while you also wait the addon gets an update. So, a simple customization on the core is enough. We are not asking for small details. Hair and Face is enough for me at least.

yes , true but just wait till suri answer to you

**Comment by AsheshPlays** [comment]
@AhmedHon

And yes, 45USD is huge here.. people's daily wage here is just 3 to 4 dollars. So if ever Suri's price is too high for me, then I will save for it.

**Comment by AhmedHon** [comment]
> @AhmedHon
> 
> And yes, 45USD is huge here.. people's daily wage here is just 3 to 4 dollars. So if ever Suri's price is too high for me, then I will save for it.

here is 2 or 3 dollars per day max

**Comment by juniormagalhaes** [comment]
> 

The fallen addon he is updating, he recently moved but I talked to him and he will update and make improvements to the addon

**Comment by khongtuong** [comment]
why do we need an core change for customization character when we had a free one and just need to setup your prefab to make it work, or you just lazy that much ? Calle free character customization fully functional and will work in every model if you dig in to it deep enough, for zero coding also make it work in just 1 or 2 hours.

**Comment by AsheshPlays** [comment]
@khongtuong

as far as i know its not a core change but a core feature. the requests made by others including me was never a change but was being added. A core addon will not break if the core updates, while an external addon will likely break if Core gets an update. And we already have bought a customization addon of fallen. Core updated and addon didn't. Now where that lead us, delayed progress and we had to redo the character creation again. So, your situation doesn't apply to me. We had few testers and it definitely had huge impact. And I am not asking suri this for free.

**Comment by AhmedHon** [comment]
also the free one needs an update .. the point is clear for him .. every suri update the kit it updates too so you don't have to wait the owner of the addon to update it ... and he said he will pay so what is the problem

**Comment by Eniotnacram** [comment]
Yes, It would be great to have core customisation and build addons over that. Using an addon for something that important is risky. I totally understand you guys. Something really basic like switching mesh, changing color maybe?

**Comment by AsheshPlays** [comment]
@Eniotnacram
switching models is enough as basic. We could just create different models using same mesh with different textures or different textures with same mesh, or anything we can think i guess. The character customization at start of the game is a must on almost all mmorpg. I understand that lots of people here can easily create their own addons, I am not against that, we have addons bought from them too, but for this one, i prefer it to be a core for these 2 reasons.

1st, If core updates, customization updates too.
2nd, If i use an addon like what we did last month, and someone made an issue and was fixed, ofcourse we also had to update, and since the addon didn't update, we had to wait long enough until we just decided to drop it and go back to core character creation. That made a negative impact on our testers.

I am not blaming the author of the addon. We all have our priorities and we all have lives to live, I understand that. So to avoid that, I'd prefer a core for this. Other addons are no problem for me if they are not updated or breaks after a core update because we can just disable it until it receives an update. Atleast the players can still login and play. That is my whole point. But if ever Suri's price is too much for me, maybe Ill save for it before buying or if Suri decides not to create it. Then it is fine for me. Ill just stick tk what it is then.

**Comment by juniormagalhaes** [comment]
I understand your point of view, I'm also waiting for the addon update to be put in the alpha test version of my game. the points you put above are valid

**Comment by insthync** [comment]
25 USD

**Comment by LordPhrozen** [comment]
Consider it done. where do we fund it?

**Comment by AsheshPlays** [comment]
@LordPhrozen

You can message @insthync he will give you his Ko-fi.. Sorry i am still saving money for my requests.

**Comment by LordPhrozen** [comment]
@insthync I tossed 25 USD to the kofi for CC with model swaps. I'll toss 25 more for Material swap functionality too.

**Comment by LordPhrozen** [comment]
@insthync No rush, just curious if there was a timeline for this piece? Thanks!

**Comment by insthync** [comment]
Will be added in 1.84

**Comment by LordPhrozen** [comment]
Thank you so much <3 I cant wait to try it :D

**Comment by AsheshPlays** [comment]
Kudos!! WORKS PERFECTLY!!
