### ISSUE TITLE
[BUG] -  Attack origin does not change when crouched/prone.

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#1969]
![image](https://user-images.githubusercontent.com/7896457/228259111-898f3460-aeff-4866-a88f-37d54d93ad78.png)

**Comment by juniormagalhaes** [comment]
put inside the model bone

**Comment by LordPhrozen** [comment]
My god. duh.

**Comment by insthync** [comment]
Or move the transform by component which find entity movement's state as condition to change position

**Comment by LordPhrozen** [comment]
Well hold on. If a player's attack origin is based on CLIENT, that seems ripe for cheating....

**Comment by moepi2k** [comment]
its not since it runs serverside

**Comment by insthync** [comment]
No, because hit detection, damage entity spawning will proceed at server.
