### ISSUE TITLE
Directionnal Jump for playable character controller.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#1971]
Hello, I would like to know if it would be possible for you to add a directionnal jump for the playable component.

Because for now, I am using the shooter controller and when I am running sideways and I jump, my character can only jump in a single direction. So it is really not cool for the eyes.

Thank you so much in advance :)

**Comment by Eniotnacram** [comment]
Nvm, seeing that in the kit the character jump facing the direction hes looking at. Investigating why its not doing this on my end.

Thank you and sorry.

**Comment by insthync** [comment]
No option for that, if you want to do it, you have to change codes, you may create a new component, copy codes from `ShooterPlayerCharacterController` and make changes as you wish.

**Comment by Eniotnacram** [comment]
Would you be whilling to add that if I pay? And make it an official release for everyone, I feel like it would be very usefull not only for my specific usecase

**Comment by insthync** [comment]
You should try to do something

hint:

![Screenshot_412](https://user-images.githubusercontent.com/2697550/228382252-fd0cf86f-3518-41f5-b5af-5bfbc7f862d0.png)
