### ISSUE TITLE
Gameplay Rule Armor Calculation Divide Zero

### ISSUE THREAD

**Issue by xafgun** [suriyun-production/mmorpg-kit-docs#1972]
Hello,

There is code like that "damageAmount *= 100f / (100f + armorAmount);". If players have debuff for armor redduction there is problem. It must be like that for protection for zero divide or negative results. 

damageAmount *= 100f / Mathf.Max((100f + armorAmount), 25); 
//25 could be change I put it for maximum 4x damage with armor reduction.

**Comment by insthync** [comment]
How are you going to fix it?

**Comment by xafgun** [comment]
> How are you going to fix it?

like that:

damageAmount *= 100f / Mathf.Max((100f + armorAmount), 25);
//25 could be change I put it for maximum 4x damage with armor reduction.
