### ISSUE TITLE
[Bug]Building System Object placement

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1973]
The Building System seems a bit croppy. placement is bugged as u can see in video

https://gyazo.com/9e72cea0d1bfbd559fef5dbd5e9f41ad

1) objects sometimes stuck when reach a specific distance (i think the object stuck depends on building distance option). instead of stuck it just should mark the object as red when outside of building distance.

2) sometimes object cant placed anymore (turns into red) when moving around, then you need to disable/enable the building object again.

**Comment by AhmedHon** [comment]
@insthync this version doesn't appear on invoice Validation

**Comment by insthync** [comment]
Uploaded

**Comment by AhmedHon** [comment]
thanks alot
