### ISSUE TITLE
Fashion or Costume Slot

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1977]
Does the kit handle fashion overlaying?
Lets say I have Armor on and I want to wear a costume without removing my armor so stats will stay. It is a way of hiding my armors or weapons from players and showing off a styled item instead. Is there a way for the kit to handle that?

**Comment by insthync** [comment]
Create new equipment slots for skins, then create equipment items that will be equipped to that slot and set higher priority in equipment models settings

![Screenshot_416](https://user-images.githubusercontent.com/2697550/228902404-2b253cd5-1818-4cc1-ab58-16ea6c00af1d.png)

**Comment by AsheshPlays** [comment]
@insthync
is higher number higher priority or lower priority ?

**Comment by AhmedHon** [comment]
i tried to make it also but didnt get it work , i have 5 separate items , and my costume is one :(.. so i want that one to be override the five parts

**Comment by insthync** [comment]
How did you try?

**Comment by AhmedHon** [comment]
i have created new equipment container for costume and added my costumes to it as instantiated without default model , then created new armor type .. made new slot ui  and in my item i have set it replace with 5 items  as have clean instantiated part and set them piority to 0 and the costume is 1 .. when i unequip helmet for example ( it removes the costume ) from the model but in ui it is equip

**Comment by AhmedHon** [comment]
i tried other ways also same issue

**Comment by AhmedHon** [comment]
thats a video of what is happening to me .. https://youtu.be/vc06bKukp0k .. check it and also check images 
![3](https://user-images.githubusercontent.com/71017004/228997682-95bdcfb0-8fe5-4f02-a7ff-8eb6cc52d645.jpg)
![1](https://user-images.githubusercontent.com/71017004/228997685-717aa3b3-94d8-4c0e-8ae2-7a74d7fab99a.jpg)
![2](https://user-images.githubusercontent.com/71017004/228997687-2e21e4a6-9ca7-4a90-8919-c80dfae1bdf6.jpg)

**Comment by AsheshPlays** [comment]
@AhmedHon 

so it is not working correctly right now?

**Comment by AhmedHon** [comment]
i tried many ways but i never get it works .. right now .. i don't know if i did it right or wrong tbh :(

**Comment by AhmedHon** [comment]
> @AhmedHon have you tried the model switch?

yes same issue

**Comment by insthync** [comment]
Like this one? 

https://youtu.be/IqBC2baOP5w

**Comment by AsheshPlays** [comment]
@insthync
i will try this

**Comment by AhmedHon** [comment]
> Like this one?
> 
> https://youtu.be/IqBC2baOP5w

yep like this , thank you

**Comment by AsheshPlays** [comment]
i will close this now!
@insthync  thanks for the video..

**Comment by AhmedHon** [comment]
@AsheshPlays  i have tested now suit with newest version and it's working as it should <3
