### ISSUE TITLE
OSX MMO server startup instructions don't work

### ISSUE THREAD

**Issue by ben-roberts** [suriyun-production/mmorpg-kit-docs#198]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/025-getting-started-mmo

Lists the OSX server startup command as:

$ ./Game.app -startMapSpawnServer -spawnExePath "Path of your execution file such as /Game/Game.app" -startCentralServer -startChatServer -machineAddress "192.168.1.102"

This won't work as, in OSX, you need to link to the actual executable *inside* the .app bundle. Should be something like:

$ ./Game.app/Contents/MacOS/<Product Name as it appears in Unity under Project Settings/Player> -startMapSpawnServer -spawnExePath "./Game.app/Contents/MacOS/<Product Name>" -startCentralServer -startChatServer -machineAddress "192.168.1.102"

If the Product Name was 'mmorpgkit', then this would be:

./Game.app/Contents/MacOS/mmorpgkit -startMapSpawnServer -spawnExePath ./Game.app/Contents/MacOS/mmorpgkit -startCentralServer -startChatServer -machineAddress "192.168.1.102"

Please update the docs!

**Comment by insthync** [comment]
Thank you for correcting me. I will do it right now.
