### ISSUE TITLE
Screen Resolution Setting (No textmesh pro option)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#1981]
Hello, There is no option for the text label and dropdown to put textmeshpro. It is only working with the default unity text.

Thank you.

**Comment by Eniotnacram** [comment]
![Screenshot 2023-04-01 193243](https://user-images.githubusercontent.com/46734935/229322745-e8b457fc-f1f9-4514-bf0d-74dc7aa0c115.png)

**Comment by Eniotnacram** [comment]
@insthync Any news on that? :(

**Comment by insthync** [comment]
No any news

**Comment by Eniotnacram** [comment]
What you mean by that? Im not sure to understand. I know Its simple and easy to be fix. But I want the core package to have it. If I make the change on my side I'll need to always care about this script with I reimport the package for updates. Text mesh pro is integrated on all txt scripts. Exept this one I think. So would you be able to add the option on that script to add text mesh pro text and dropdown?

**Comment by insthync** [comment]
If you keep flooding this one, I won't do it.

**Comment by insthync** [comment]
https://github.com/insthync/unity-graphic-settings/commit/62f96077212f938db9c126f4b44f0abec9790563
