### ISSUE TITLE
[BUG] Dedicated linux server not working?

### ISSUE THREAD

**Issue by MystaraTheGreat** [suriyun-production/mmorpg-kit-docs#1982]
I've exactly followed the manual to produce a linux dedicated server (on my mac).  However, although the server does execute, it does not seem to bind to any addresses/ports and cannot be accessed via the client.  I've checked the port listening via lsof.

I've tested this on both my own private dedicated server and digital ocean.  As I say, I've followed the instructions (adapting the install for unity 2021 and for the new input manager).  The server gives the following on startup:

root@phpmyadmin521onubuntu2204-s-1vcpu-1gb-amd-fra1-01:~# /root/Dedicated.x86_64 -startCentralServer -startMapSpawnServer -startDatabaseServer
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/root/Dedicated_Data/Managed'
Mono config path = '/root/Dedicated_Data/MonoBleedingEdge/etc'
PlayerPrefs - Creating folder: /root/.config/unity3d/DefaultCompany
PlayerPrefs - Creating folder: /root/.config/unity3d/DefaultCompany/Game
Unable to load player prefs
Initialize engine version: 2021.3.22f1 (b6c551784ba3)
[Subsystems] Discovering subsystems at path /root/Dedicated_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0; jobified=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.159 seconds
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Mobile/Particles/Additive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Mobile/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/Particles/Alpha Blended Premultiply shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Mobile/Diffuse' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Mobile/Diffuse shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Mobile/Diffuse' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Mobile/Unlit (Supports Lightmap) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Projector/AdditiveTint shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Mobile/Particles/Alpha Blended shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Mobile/Particles/VertexLit Blended shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader GUI/Text Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
There is no texture data available to upload.
UnloadTime: 1.213856 ms
 INFO No Tag [2023-04-01 16:28:22] - ===== Logger Initialized =====
[DevExt] GameInstance - Awake
[DevExt] GameInstance - LoadedGameData
 INFO GameInstance [2023-04-01 16:28:22] - [IAP_INIT]: Initialized without purchasing
ERROR: Shader UI/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
There is no texture data available to upload.
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 3.780208 ms
Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 39100.
Total: 111.057272 ms (FindLiveObjects: 4.559149 ms CreateObjectMapping: 5.562890 ms MarkObjects: 100.743073 ms  DeleteObjects: 0.190207 ms)

None of the ports are bound:

root@phpmyadmin521onubuntu2204-s-1vcpu-1gb-amd-fra1-01:~# sudo lsof -i -P -n
COMMAND    PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-r  622 systemd-resolve   13u  IPv4  18442      0t0  UDP 127.0.0.53:53
systemd-r  622 systemd-resolve   14u  IPv4  18443      0t0  TCP 127.0.0.53:53 (LISTEN)
mysqld    2190           mysql   21u  IPv4  26905      0t0  TCP 127.0.0.1:33060 (LISTEN)
mysqld    2190           mysql   23u  IPv4  26907      0t0  TCP *:3306 (LISTEN)
apache2   2851            root    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
sshd      2855            root    3u  IPv4  27842      0t0  TCP *:22 (LISTEN)
sshd      2855            root    4u  IPv6  27853      0t0  TCP *:22 (LISTEN)
apache2   2856        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   2857        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   2859        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   2866        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
sshd      2991            root    4u  IPv4  28436      0t0  TCP 10.19.0.5:22->31.125.107.31:58102 (ESTABLISHED)
apache2   3099        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   3102        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   3104        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   3109        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   3121        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
apache2   3122        www-data    4u  IPv6  27785      0t0  TCP *:80 (LISTEN)
sshd      3748            root    4u  IPv4  35509      0t0  TCP 10.19.0.5:22->31.125.107.31:58270 (ESTABLISHED)
sshd      3835            root    4u  IPv4  36988      0t0  TCP 138.68.87.162:22->61.177.172.61:10904 (ESTABLISHED)

**Comment by focushyper** [comment]
i had this issue with Ubuntu aswel. then i used CentOS and everything worked after some basic firewall rules.

try CentOS bc i had a lot of issues with ubuntu

**Comment by focushyper** [comment]
also you need to run it with sudo

**Comment by MystaraTheGreat** [comment]
OK, let me try CentOS.
I'm already running as root on Ubuntu, which seems to be what is being used in the docmentation.  But happy to give CentOS a go.

**Comment by focushyper** [comment]
and open the centralPort with firewall and open the map ports 
make use you use the /home/mmo/config serverConfig.json file: 
{
 "databaseOptionIndex": 0,
 "databaseDisableCacheReading": false,
 "useWebSocket": false,
 "webSocketSecure": false,
 "webSocketCertPath": "",
 "webSocketCertPassword": "",
 "centralAddress": "127.0.0.1",
 "centralPort": 7000,
 "centralMaxConnections": 1100,
 "clusterPort": 6010,
 "machineAddress": "YOUR-PUBLIC-IP",
 "mapSpawnPort": 6001,
 "spawnExePath": "/home/opc/mmo/mmo_linux.x86_64",
 "notSpawnInBatchMode": false,
 "spawnStartPort": 8000,
 "spawnMaps": ["Map001","Map002","Map_GuildWar"],
 "mapPort": 7770,
 "mapMaxConnections": 1100,
 "databaseManagerAddress": "127.0.0.1",
 "databaseManagerPort": 6100
}

**Comment by focushyper** [comment]
./Game.x86_64 -startMapSpawnServer -spawnExePath "Path of your execution file such as /Game/Game.x86_64" -startCentralServer -startDatabaseServer -machineAddress "YOUR-PUBLIC-IP-HERE"

**Comment by MystaraTheGreat** [comment]
Alas no luck with that config on Debian.  I'll try CentOS as I previously mentioned.

**Comment by MystaraTheGreat** [comment]
Nope.  No luck with CentOS either.
It's not a firewall issue there either - I can use netcat to listen at port 7000 and I can remotely connect.  The server just isn't opening that port.

**Comment by focushyper** [comment]
are you lissing on a UDP port?

**Comment by MystaraTheGreat** [comment]
THAT....is a good question.

**Comment by focushyper** [comment]
what version of the kit are you using?

**Comment by MystaraTheGreat** [comment]
2021.3.22f1

**Comment by focushyper** [comment]
and what is version of the mmokit

**Comment by MystaraTheGreat** [comment]
Ooops.  Sorry 1.81h3

**Comment by focushyper** [comment]
i had some issues with 2021 but that was something diffrent.
u saw that you used the -spwanexepath that is realy needed otherwise the server can not fully start


./Game.x86_64 -startMapSpawnServer -spawnExePath "Path of your execution file such as /Game/Game.x86_64" -startCentralServer -startDatabaseServer -machineAddress "YOUR-PUBLIC-IP-HERE"

**Comment by MystaraTheGreat** [comment]
Yeah, I've got that in the command line

**Comment by focushyper** [comment]
https://www.youtube.com/watch?v=gwVE-1obV60&list=PLbtX3Q3DrvKzIP2Hly-X1w6sNWlDEJ4sF

i found most of my learning on github google and youtube for this kit

**Comment by MystaraTheGreat** [comment]
I'll give it a look.  In the meantime, I'm going to try and rebuild the client again.  Maybe the problem is there.

**Comment by focushyper** [comment]
lets me know happy to help with this issue

**Comment by MystaraTheGreat** [comment]
Solved: I was loading the wrong 00_Init file, which meant that the config file wasn't being read.
