### ISSUE TITLE
Mount sprinting

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#1983]
I've been experimenting with mounts and I can't find a means to trigger sprinting for mounts - however it has animation slots for sprinting. Is this a bug?

**Comment by insthync** [comment]
Not a bug, not every fields will be used, the character model component is component which reusable it can be attached as part of many other components, both character entity and vehicle entity will use it as part to play animations but only character can sprint.

**Comment by BJPickles** [comment]
Okay thanks! 😁
