### ISSUE TITLE
[Bug]Vehicle

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1989]
check the video

https://gyazo.com/34615f29ca6f23b683504944944e5f12

when player use vehicles and are out of netrange, sometimes it becomes bugged. driver fall out of vehicle, or the vehicle is laggy.
also sometimes when the driver is mounted on the vehicle and are just idle. the vehicle is jittering in place. only thing to fix it is relog the player

**Comment by juniormagalhaes** [comment]
I also have the same problem, but I forgot to report it.

**Comment by insthync** [comment]
Fix by these codes changes: https://github.com/insthync/LiteNetLibManager/commit/fc142b6713c5f9f6d5988799cc40fee089a15903

**Comment by moepi2k** [comment]
thaaanks you :)

**Comment by joabekaul** [comment]
Hello Guys, I made the change in my Code and it didn't solve it, my problem is the following: When I use the mount, my character is standing on top, when he was supposed to be sitting, so when the character leaves the range of another player, and appears in the range seems to be right, but it is still wrong in the player that is using it, I would like to know how to solve this ...

Check Vídeo:

https://www.youtube.com/watch?v=y0Z0wwFzEl8&feature=youtu.be
