### ISSUE TITLE
1.52c client doesn't work with a 1.52b server

### ISSUE THREAD

**Issue by Zurigan** [suriyun-production/mmorpg-kit-docs#199]
This is on OSX, using the 3D demo, server running via command line, client in Unity. 

The Client when run will display a login box, after entering details and hitting the login button the character select screen is shown with a loading... UI element then appears to crash. 

Log output shows:

...
[CentralNetworkManager] LiteNetLibManager::OnStartClient
[CentralNetworkManager] LiteNetLibClient::OnPeerConnected
ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes

Should a newer version client be able to connect to an older version server? 

If this is expected, some sort of readable message would be great to include vs. just crashing without explanation.

**Comment by insthync** [comment]
Yep, it should be able to connect older server version, but now, as it's under development which I have changes network message to reduce size (and I didn't make it supports multi-version of packet). I can define a version to tell clients which connecting with different versions to inform that they can't connect.
