### ISSUE TITLE
[Bug] Monter not attackable

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#1990]
This is happing in 1.81h3 
Sometimes the monster is selected but the player is not attacking. I just disabled all monster spawners and created a New one with amount of 2

https://user-images.githubusercontent.com/1295862/229565240-411c2a3d-5009-4d84-8c1c-4b492dbc4935.mp4

![image](https://user-images.githubusercontent.com/1295862/229565953-4c11b18e-6c35-4487-8197-7cae2363b3da.png)

**Comment by juniormagalhaes** [comment]
is a safearea

**Comment by Deepankar1993** [comment]
No

**Comment by insthync** [comment]
How can I know that it has no safe area?

**Comment by Deepankar1993** [comment]
![image](https://user-images.githubusercontent.com/1295862/229691651-12ef7987-8cbd-4966-8f72-e777f403ff31.png)

**Comment by insthync** [comment]
How can I reproduce it?

**Comment by Deepankar1993** [comment]
This Video is from the default map001 
However, when I cloned the map001 the issue did appear on 1st, but happening when monsters respawn. 
So, hard to say it I will go through all the updates in VC (Plastic SCM) to see any changes 

I am not 100% sure how on the step to reproduce

**Comment by insthync** [comment]
May be because your character is in safe area

**Comment by insthync** [comment]
To my email: ittipon.bay@gmail.com

**Comment by Deepankar1993** [comment]
That will only be possible at night after office 9-10 PM Indian Time

**Comment by insthync** [comment]
Okay

**Comment by AhmedHon** [comment]
i think monster is fine , works fine to me

**Comment by Deepankar1993** [comment]
this was the issue some how 
![image](https://user-images.githubusercontent.com/1295862/229847355-e2e7a7c1-98b7-4702-abcd-f60a5d939bf3.png)
My Enter PlayMode Option was enable 
Disabling it fixed issue it seems

**Comment by insthync** [comment]
I can't fix anything relates to this.
