### ISSUE TITLE
Add Audio Clips (Playable Character Model)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#1991]
It would be very nice to add the option for audio clips for all state of the Playable Character Model)

Audio clips for (Jump, land, fall, dead, all running, walking, moving direction, etc)

For litterally all possible actions, add the possibility to add an audio clip.

For now, it is only possible for the attacks.
Screenshot Below:
![Screenshot 2023-04-03 185930](https://user-images.githubusercontent.com/46734935/229644640-56972ebd-2ae6-41cc-926b-7821a01a312c.png)

Additionnal: Maybe also add the option to add EVENTS to the animations so we can play the audio clips at the perfect time of the animations.

Let me know what you think :)

**Comment by Eniotnacram** [comment]
So I should not use the "built in" audio clip system?

**Comment by AsheshPlays** [comment]
@Eniotnacram there is a component for the mob death available, that is what i use.

**Comment by Eniotnacram** [comment]
You use that for all animations?

**Comment by AsheshPlays** [comment]
@Eniotnacram
i am using the footsteps and death components for monsters.

**Comment by insthync** [comment]
@Eniotnacram What is "built in"?

**Comment by AsheshPlays** [comment]
> We should use animation clip's event, to play audio clips at the time perfectly but I think that one is so easy to do, so I don't add it yet.
> 
> Just create a new component that has a function to play audio clips, that is it.

this would be a nice addition. We then can have multiple animations for idles and will make the game lively if used correctly.

**Comment by insthync** [comment]
How this relates to multiple idle animations?

**Comment by insthync** [comment]
I won't do anything related to this, Unity has an animation clip event, and easy to implement, this task is too easy for me, and I don't want to do it.
