### ISSUE TITLE
NPC Dialog AudioClip on Open

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#1993]
I created an extension using github copilot for NPCs. You can assign an audio on every dialog or just when opening. And audio source object is needed on the UI of the npc on the canvas by the way.

Below are the prompts in "//* i made for copilot

// Extend the BaseNpcDialog class to add custom functionality
// Add a specific AudioClip to play for each dialog

Script below

_using UnityEngine;

namespace MultiplayerARPG
{
    public partial class BaseNpcDialog
    {
        public AudioClip audioClip;
    }

    public partial class UINpcDialog : UISelectionEntry<BaseNpcDialog>
    {
        public AudioSource npcAudioSource;

        private void Start()
        {
            PlayVoice();
        }

        public void PlayVoice()
        {
            if (npcAudioSource != null && Data != null && Data.audioClip != null)
            {
                npcAudioSource.clip = Data.audioClip;
                npcAudioSource.Play();
            }
        }
    }
}_

i dont know if this can be added to core and can be improved and i also dont know if core has it already implemented.

just sharing some AI made scripts that works.

**Comment by insthync** [comment]
Already did it.
