### ISSUE TITLE
[BUG] Mount Vehicle - Help?

### ISSUE THREAD

**Issue by joabekaul** [suriyun-production/mmorpg-kit-docs#1994]
Hello Guys, I made the change in my Code (https://github.com/suriyun-production/mmorpg-kit-docs/issues/1989) and it didn't solve it, my problem is the following: When I use the mount, my character is standing on top, when he was supposed to be sitting, so when the character leaves the range of another player, and appears in the range seems to be right, but it is still wrong in the player that is using it, I would like to know how to solve this ...

Check Vídeo:

https://www.youtube.com/watch?v=y0Z0wwFzEl8&feature=youtu.be

**Comment by insthync** [comment]
Are you using Playable Character Model, right?

**Comment by insthync** [comment]
Fixed in version 1.82

**Comment by joabekaul** [comment]
How do I fit in my project with the current version of it old? Updating would be a lot of work

**Comment by joabekaul** [comment]
Thanks, I'll update my project and see if it's resolved, I'll get back to you soon
