### ISSUE TITLE
[ ISSUE ] wrong animations 

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#1996]
Hi , kit was fine before updating my project to latest version 1.82 , now only ride animation works ! no idle , no anything .. just ride one ..
check the video https://youtu.be/LBcVvuFdffo

**Comment by insthync** [comment]
Send me your AnyDesk info to my email: ittipon.bay@gmail.com, I want to try it.

**Comment by AhmedHon** [comment]
thank you alot
