### ISSUE TITLE
I'm getting some issues like mobs hanging air.

### ISSUE THREAD

**Issue by suitechsoftware** [suriyun-production/mmorpg-kit-docs#1997]
I'm getting some issues like mobs hanging air. Widget body entity moment 

![image](https://user-images.githubusercontent.com/106386940/230253429-9de0d6f2-dc3c-4e3a-ab0e-4e4e1d26a434.png)

**Comment by insthync** [comment]
Because of collider size or nav mesh agent size or animation?

**Comment by Eniotnacram** [comment]
If you are using navmesh you need to put an offset
