### ISSUE TITLE
No overload for method 'GetComponentInParent' takes 1 arguments

### ISSUE THREAD

**Issue by bhgl** [suriyun-production/mmorpg-kit-docs#1998]
>Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Model/BaseCharacterModel.cs(176,27): error CS1501: No overload for method 'GetComponentInParent' takes 1 arguments 

I just downloaded the newest version (1.82b) and is getting this error when importing asset into a fresh project.

Steps I've taken to reproduce:
1. Make a new project (I chose 3d built in, using Unity2020.3.26f1)
2. Import 1.82b from package manager
3. After importing settings and selecting all files the error appears

I have not tried in an existing project.

**Comment by insthync** [comment]
Try download Unity 2020.3.46
