### ISSUE TITLE
Local server crashes when connecting two local clients

### ISSUE THREAD

**Issue by Zurigan** [suriyun-production/mmorpg-kit-docs#200]
OSX 10.5.2 / Unity 2019.3.0f6 / 1.52c kit version

Building the demo 2D project and running it locally, then connecting 2 clients all works for a couple of seconds then the main server crashes leaving some of the other server processes still alive. Is this expected? 

Edit - if one player is in map B and the other logs into A the crash doesn't occur until they join the same map ... then, after a couple of seconds, the server dies. There are a lot of libsqlite errors throughout the logs ... really not sure what to make of that given that character persistence is working so must be working at least partially.

Log output of the crash happening when player A enters the same map as B below:

[Chat] Update map user: RD1gUjk2 by 1
[Chat] Update map user: dH2D2ggu by 0
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
[Chat] Update map user: RD1gUjk2 by 1
[Chat] Update map user: dH2D2ggu by 0
[Central] Remove map user: RD1gUjk2 by 3
Character [wuQSoDuU] Saved
[Chat] Remove map user: RD1gUjk2 by 1
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
[MapNetworkManager] LiteNetLibServer::OnPeerDisconnected peer.ConnectionId: 0 disconnectInfo.Reason: RemoteConnectionClose
[MapNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 1
Add subscriber [0] to [Warrior2D(Clone) (UnityEngine.GameObject)]
[Central] Add map user: RD1gUjk2 by 2
[Chat] Add map user: RD1gUjk2 by 0
[Chat] Update map user: dH2D2ggu by 0
[Chat] Update map user: RD1gUjk2 by 0
Add subscriber [1] to [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
[Chat] Update map user: dH2D2ggu by 0
[Chat] Update map user: RD1gUjk2 by 0
[Chat] Update map user: dH2D2ggu by 0
[Chat] Update map user: RD1gUjk2 by 0
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Obtained 4 stack frames.
#0  0x007fff6aeea9e8 in balance
#1  0x007fff6aee6623 in sqlite3BtreeDelete
#2  0x007fff6aeb5401 in sqlite3VdbeExec
#3  0x007fff6aeb2c5f in sqlite3_step
Could not open the crashlog output file. Error = 2: No such file or directory
Process spawn id: 2 killed.
Starting process from: ./mmokit2DServer.app/Contents/MacOS/mmorpgkit
Starting process with args:  -batchmode -nographics -mapId Map002_2D -centralAddress 127.0.0.1 -centralPort 6000 -machineAddress 127.0.0.1 -mapPort 8001  -startMapServer
Process started. Spawn Id: 3, pid: 29864
Mono path[0] = '/Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Resources/Data/Managed'
Mono config path = '/Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/MonoBleedingEdge/etc'
Initialize engine version: 2019.3.0f6 (27ab2135bccf)
[Subsystems] Discovering subsystems at path /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Resources/Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.092 seconds
UnloadTime: 0.659794 ms
[DevExt] GameInstance - Awake
IOException: Sharing violation on path /Users/benroberts/Library/Application Support/DefaultCompany/mmorpgkit/log.txt 
(Filename: <437ba245d8404784b9fbab9b439ac908> Line: 0)

Plugins: Couldn't open libc, error: dlopen(libc, 2): image not found 
(Filename:  Line: 306)

[MMOServerInstance] Reading config file from ./config/serverConfig.json
[SQLiteDatabase] Reading config file from ./config/sqliteConfig.json
Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open advapi32, error: dlopen(advapi32, 2): image not found 
(Filename:  Line: 306)

Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.dylib
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.so
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.bundle
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/advapi32.dll
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dylib
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.so
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.bundle
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/advapi32
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.dylib
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.so
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.bundle
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll
Plugins: Couldn't open advapi32, error: dlopen(advapi32, 2): image not found 
(Filename:  Line: 306)

Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.dylib
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.so
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.bundle
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/advapi32.dll
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dylib
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.so
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.bundle
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/advapi32
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.dylib
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.so
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll.bundle
Fallback handler could not load library /Users/benroberts/Desktop/Server/mmokit2DServer.app/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi32.dll
Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

[DevExt] GameInstance - LoadedGameData
[IAP_INIT]: Initialized without purchasing
[MapNetworkManager] LiteNetLibManager::OnStartServer
[LiteNetLibGameManager] Loading Scene: Map002_2D is online: True
[CentralNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 4
[CentralNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 5
Obtained 11 stack frames.
#0  0x007fff6aea1a01 in selectExpander
#1  0x007fff6ae9fe81 in sqlite3WalkSelect
#2  0x007fff6af7327a in sqlite3SelectPrep
#3  0x007fff6ae93b42 in sqlite3Select
#4  0x007fff6ae65cca in yy_reduce
#5  0x007fff6ae63435 in sqlite3RunParser
#6  0x007fff6ae6198b in sqlite3LockAndPrepare
#7  0x007fff6af2aa39 in sqlite3_prepare
#8  0x0000011ea1989c in  (wrapper managed-to-native) Mono.Data.Sqlite.UnsafeNativeMethods:sqlite3_prepare (intptr,intptr,int,intptr&,intptr&) {0x7ffc4c24c670} + 0x7c (0x11ea19820 0x11ea19935) [0x116611c80 - Unity Root Domain]
#9  0x007ffc53c37970 in (Unknown)
#10 0x00700012f5b640 in (Unknown)
Could not open the crashlog output file. Error = 2: No such file or directory
Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 1.603618 ms

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 15379.
Total: 14.694153 ms (FindLiveObjects: 0.570953 ms CreateObjectMapping: 0.759683 ms MarkObjects: 13.269040 ms  DeleteObjects: 0.094065 ms)

[LiteNetLibGameManager] Loaded Scene: Map002_2D is online: True
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [547613141] name [ItemDropEntity2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [-1790050832] name [WarpPortalEntity2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [1063866312] name [Warrior2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [1327770859] name [OrcsWarrior2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [159852119] name [OrcsArcher2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [187559334] name [ChestEntity2D]
[LiteNetLibGameManager] Loaded Scene: Map002_2D -> Assets.Initialize()
[LiteNetLibGameManager] Loaded Scene: Map002_2D -> Assets.SpawnSceneObjects()
[LiteNetLibGameManager] Loaded Scene: Map002_2D -> OnServerOnlineSceneLoaded()
[LiteNetLibGameManager] Loaded Scene: Map002_2D -> SendServerSceneChange()
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [159852119] name [OrcsArcher2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [159852119] name [OrcsArcher2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [159852119] name [OrcsArcher2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [159852119] name [OrcsArcher2D]
Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

Plugins: Couldn't open libsqlite3.0, error: dlopen(libsqlite3.0, 2): image not found 
(Filename:  Line: 306)

[MapServer] Starting server
[MapServer] Connecting to Central Server: 127.0.0.1:6000
Saved 0 character(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
CentralAppServerRegister::OnPeerDisconnected. disconnectInfo.Reason: Timeout
[MapServer] Disconnected from Central Server
[MapNetworkManager] LiteNetLibClient::OnPeerDisconnected peer. disconnectInfo.Reason: Timeout
[MapNetworkManager] LiteNetLibManager::StopClient
[MapNetworkManager] LiteNetLibManager::OnStopClient
[MapServer] Reconnect to central in 5 seconds...
[MapServer] Reconnect to central in 4 seconds...
CentralAppServerRegister::OnPeerDisconnected. disconnectInfo.Reason: ConnectionFailed
[MapServer] Disconnected from Central Server
[MapServer] Reconnect to central in 3 seconds...
[MapServer] Reconnect to central in 5 seconds...

**Comment by ben-roberts** [comment]
For anyone finding this in future - this appears to be an issue with using the asset with its default DB (SQLite). The way the asset is setup multiple processes might try to write to the DB at the same time. This will cause a server crash as there's no error handling. The only fix as of writing this is not to use SQLite.
