### ISSUE TITLE
[HELP] Entities die instantly upon spawning, probably ground/navmesh issue

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#2000]
At certain areas of my map, specially with uneven ground, the player (rarely) and monsters/summons/pets (specially) die instantly upon summoning.  
I have tried using mesh collider with and without convex and also plain box collider on the ground.
The ground's Y-death setting is not causing it.

Tried spawning the player/monsters way above the ground but it feels like they spawn a little below the ground and die. 
It's looking some issue with Navmesh Agent Offset, as setting the offset higher than the collider/size of the entity seems to fix it although causes the entities to look floating in the air.

![image](https://user-images.githubusercontent.com/3790163/230402001-dcf4c55f-7fd1-46b0-ac3c-823a8e02be1c.png)

![image](https://user-images.githubusercontent.com/3790163/230402064-5a500787-0a7d-40e1-9fbf-4286af39ff93.png)

![image](https://user-images.githubusercontent.com/3790163/230402305-a61afa52-4953-44b6-8949-f7d605eda5e0.png)

![image](https://user-images.githubusercontent.com/3790163/230402348-809d5960-6c2b-42f3-8f73-3c14eb64de10.png)

![image](https://user-images.githubusercontent.com/3790163/230402412-7785c4a2-12e3-405c-8f65-6fc223915653.png)

**Comment by insthync** [comment]
Try change gameplay rule -> `fallDamageMinDistance`/`fallDamageMaxDistance` to see if it is affecting or not.

**Comment by insthync** [comment]
Hello, how about changing fallDamageMinDistance/fallDamageMaxDistance ?

**Comment by shubhank008** [comment]
> Hello, how about changing fallDamageMinDistance/fallDamageMaxDistance ?

Sorry I didn't update you with the result, it seems the problem was with navmesh itself, after I deleted the whole navmesh and regenerated it, it seems to have fixed.  
Baseoffset seems to be working fine too.

Apparently navmesh surface data seems to have gotten corrupted.

Closing it, thank you for the help.
