### ISSUE TITLE
Drop FPS when opening storage

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2001]
I noticed that when I open the storage the game has a considerable FPS drop, only with 100 slots it is already possible to see a drop, if you put 200 slots in the storage the fps drop is even greater, I don't know if it's a bug or not, just wanted to share, I don't know if it's the slots refresh rate or something else, but anyway it's something I noticed and I'm putting it here XD

https://gyazo.com/0e53247632ce0e1e25409047a339d78b

**Comment by insthync** [comment]
Did you use Navigation group?

**Comment by juniormagalhaes** [comment]
> Did you use Navigation group?

I use the default kit, I just changed the background and text colors, if I put a new project with just the kit the same thing happens

**Comment by insthync** [comment]
Fixed in 1.82c
