### ISSUE TITLE
[ ISSUE ] Doesn't load the local server

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#2002]
Hi , i can't load local server as you wrote here https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/025-getting-started-mmo with version 1.82 .. open short cut one and it join the  to game home scene , not loading black screen .... tested with fresh project and same :( >> thats my target lines ( "C:\Users\Run\Desktop\Kalonline - TNE\Kal-TNE.exe" -startMapSpawnServer -spawnExePath "C:\Users\Run\Desktop\Kalonline - TNE\Kal-TNE.exe" -startCentralServer -startDatabaseServer -machineAddress "127.0.0.1" ) tested with sqlite and mysql and same issue .... check the video ( https://youtu.be/0qyW5awl-IY )

**Comment by AhmedHon** [comment]
tested with version 1.81h2 and it works fine so it's a bug from version 1.82

**Comment by insthync** [comment]
Did you do this ?

![Screenshot_436](https://user-images.githubusercontent.com/2697550/230463918-d74a2247-8866-4dad-9e7c-1c0f47893af0.png)

**Comment by AhmedHon** [comment]
no, just normal setup

**Comment by insthync** [comment]
Try do it

**Comment by AhmedHon** [comment]
thank you so much , its working now
