### ISSUE TITLE
Monster CPU usage

### ISSUE THREAD

**Issue by MystaraTheGreat** [suriyun-production/mmorpg-kit-docs#2005]
I'm curious as to how/why monsters use so much CPU (even when idle) and whether there's something I can adjust in order to reduce this?

Even with no players connected, the CPU for the map server is at 10-15%, which is much more than maps with no monsters (0.7%).

**Comment by insthync** [comment]
I'll check it

**Comment by MystaraTheGreat** [comment]
Thanks.  It seems to be commonly held fact on the discord so it probably isn’t just me.  

The rule of thumb is that five monsters use as much cpu as one player although monsters seem to use cou even when no player is online.

**Comment by insthync** [comment]
Try version 1.83, not sure it will works as your expectation or not.

**Comment by temelkirci** [comment]
@insthync @MystaraTheGreat your problem was solved by 1.83 ?.I am having same issue with 1.82 now.

**Comment by MystaraTheGreat** [comment]
Sorry, I haven't yet had the chance to try.  I'll see if I can get some time this weekend.

**Comment by insthync** [comment]
Not enough

**Comment by temelkirci** [comment]
![bbb](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/0326e873-11e5-4611-9cc3-7e74a19a319e)


Should I uncheck it ?

@insthync

**Comment by insthync** [comment]
If your game is not FPS game which hit boxes needed to be updated, yes, you should uncheck.

**Comment by temelkirci** [comment]
![Ekran görüntüsü 2023-05-26 174437](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/1d3856c0-fe29-437c-b54f-eff21aaa0a2b)

0 online.7 maps,Total 2000 monster.150 harvestables.

I upgraded my kit version to 1.83 from 1.82.Results are fine.I see the improvement and difference.But I am not sure if it is enough or not.
