### ISSUE TITLE
[Bug]Equipment Models -> Priority

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2006]
When use Priority on equipment model then when switching weapons the higher priority switchs back to the normal one
https://gyazo.com/12199e7adc4788e4f36a6da44b3e401a

I use two diffrent head slots and bot use the same Equip Socket
https://gyazo.com/8f9747ee8d9a7a926df4f994155ad0c4

**Comment by insthync** [comment]
Did your codes updated?

![Screenshot_438](https://user-images.githubusercontent.com/2697550/230605423-3b5e6781-610b-4098-afc5-41afcf28ea22.png)

**Comment by AhmedHon** [comment]
@moepi2k  you need to update to latest version , i use it and it works fine

**Comment by AhmedHon** [comment]
@insthync  but there is a bug with multi costumes , i made 1 for armors and 1 for weapon but as armor type .. check the video https://youtu.be/KtpcJe3BT88

**Comment by insthync** [comment]
I will fix it

**Comment by insthync** [comment]
You can fix it by adding these codes

![Screenshot_439](https://user-images.githubusercontent.com/2697550/230795553-083aeef7-922a-4b07-849e-0f89d7310b61.png)

**Comment by AhmedHon** [comment]
> You can fix it by adding these codes
> 
> ![Screenshot_439](https://user-images.githubusercontent.com/2697550/230795553-083aeef7-922a-4b07-849e-0f89d7310b61.png)

In which script ?

**Comment by insthync** [comment]
BaseCharacterModel.cs

You actually can use IDE to find it, may be just use `storingModels.TryGetValue(equipSocket, out EquipmentModel storedModel)` as a text to find it.

**Comment by AhmedHon** [comment]
yea found it , i just removed the comment .. sorry :)

**Comment by AhmedHon** [comment]
thanks alot , its works amazing now as it should <3

**Comment by insthync** [comment]
Fixed in 1.82c
