### ISSUE TITLE
ERROR DatabaseNetworkManager [2023-04-08 02:12:34] - Cannot UpdateUserCount status: Timeout

### ISSUE THREAD

**Issue by sdk2016** [suriyun-production/mmorpg-kit-docs#2007]
I want to know what is causing this. Is this because there are no users online? Thank You.

Specification:
Databases: MySQL
Number of Maps: 2
RAM: 8GB
Kits Version 1.82b (2023-04-06)

**Comment by insthync** [comment]
Please attach full error log files

**Comment by insthync** [comment]
I want to see your serverConfig.json

**Comment by insthync** [comment]
I saw a lot of connection timed out, not only for the database.

**Comment by insthync** [comment]
Hmm.. it's all looks good, how about CPU and RAM usage while servers are running?
