### ISSUE TITLE
Weapon Based Skill Animations

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2008]
Is there a way to set different animations on one skill? Let's say I have a skill name "Critical Slash" and it can be used on 3 types of weapon, 1-Hand Sword, 1-Hand Dagger and 2-Hand Great Sword. And it's also for Magic User Characters that can use, Orbs, Books, Staffs but only using same skill, just different animations depending on the weapon equipped.

**Comment by insthync** [comment]
How it should be setup?, how can I make it not very complex to use? Now I only think that I have to add a list to each skill animations entry to make it able to have different animations settings for each weapon, so it will have lists in skill animation list.

0 -skill animations
--- cast animations by weapon (list of animation, which use weapon type as a key)
------ 0
------ 1
------ n
--- activate animations by weapon (list of animation, which use weapon type as a key)
------ 0
------ 1
------ n

If I do that can you help me write the document?

**Comment by AsheshPlays** [comment]
@insthync

Yes, i can help you write the document of it.

**Comment by insthync** [comment]
Show me.

**Comment by AsheshPlays** [comment]
@insthync
i need your email so i can send the file there.

**Comment by insthync** [comment]
ittipon.bay@gmail.com

**Comment by AsheshPlays** [comment]
sent

**Comment by insthync** [comment]
Good

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2506
