### ISSUE TITLE
Jumping negates stamina drain

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#2009]
**Players that run, and jump constantly do 2 things**
-Basically negates stamina drain from running.
-Makes them move around really quietly ( for games where that matters, thats huge ).

**Proposed Solution:**
-Have an editable stamina usage value on jump

**Additional Tweaks**
-Stamina usage for weapon swings
-Stamina usage for prone/crouch/standup transitions.

_Stamina is a great mechanic to stop constant slamming of things, and more tactical gameplay. Would love to see this an out of the box option._

**Comment by LordPhrozen** [comment]
Agree.

**Comment by insthync** [comment]
I will not implement this one, but from 1.83g, I've added events that I think you can use them to implement it.

- May use `onCanJumpValidated` to check remains stamina before jump
- May use `onJumpForceApplied` to decrease stamina when jump
