### ISSUE TITLE
Excessive warp time 

### ISSUE THREAD

**Issue by Zurigan** [suriyun-production/mmorpg-kit-docs#201]
This is using the 2D demo project, local server and client on OSX. 

Warping from map B > A seems to work fine all the time. Warping the other way seems to take longer and longer over time ... after 4-5 warps it can take up to a minute to change maps. 

Once the issue happens it then has a good chance of causing a server crash somehow. 

Captured this log output over one of these warps where the player did eventually reappear in the right place, server didn't crash ... think it was ~40s.

Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Saved 0 building(s)
[ThreadedJob] Error occurs on UpdateCharacterJob 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

SqliteException: The database file is locked
database is locked 
(Filename: <477aeba2693342e4a5e504b0d877c229> Line: 0)

Character [wuQSoDuU] Saved
Saved 1 character(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
[ThreadedJob] Error occurs on UpdateCharacterJob 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

SqliteException: The database file is locked
database is locked 
(Filename: <477aeba2693342e4a5e504b0d877c229> Line: 0)

Character [wuQSoDuU] Saved
[MapNetworkManager] LiteNetLibServer::OnPeerDisconnected peer.ConnectionId: 0 disconnectInfo.Reason: RemoteConnectionClose
[MapNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 0
[Central] Add map user: RD1gUjk2 by 2
[Chat] Add map user: RD1gUjk2 by 0
Add subscriber [0] to [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Add subscriber [0] to [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Add subscriber [0] to [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Add subscriber [0] to [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Add subscriber [0] to [OrcsArcher2D(Clone) (UnityEngine.GameObject)]

**Comment by insthync** [comment]
This is problems while using SQLite, because there are more than 1 process which access SQLite, to fix it, I have to create new database management server, for now you can switch to use MySQL database to avoid it.

**Comment by ben-roberts** [comment]
> This is problems while using SQLite, because there are more than 1 process which access SQLite, to fix it, I have to create new database management server, for now you can switch to use MySQL database to avoid it.

Thanks for the reply, I think it would be a good idea in the short term to remove SQLite it from the asset until it's functional. Shipping the asset with it in there, and as the default, when it's not usable is going to waste a lot of your customers time.

**Comment by ben-roberts** [comment]
Also, not sure if this actually explains the excessive warp time ... there's a lot of waiting around before that first SqliteException and you can see the 'remove subscribers' is running very slowly as there are multiple saves happening in the time it takes to remove them.
