### ISSUE TITLE
Character Unstuck 

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2010]
Hey! I haven't experienced this yet but incase I will or my testers will, I know what to do.

So, does the kit have unstuck function? Like if characters get stuck on certain places in maps, do we have this /unstuck or Unstuck button like other Mmo Games? Or is there another way to implement it?

**Comment by insthync** [comment]
It have `FindGroundedPosition` and `Teleport` functions in `PlayerCharacterEntity` use them to do it

**Comment by shubhank008** [comment]
> Hey! I haven't experienced this yet but incase I will or my testers will, I know what to do.
> 
> So, does the kit have unstuck function? Like if characters get stuck on certain places in maps, do we have this /unstuck or Unstuck button like other Mmo Games? Or is there another way to implement it?

Two options, you can use Teleport method to make your own unstuck button to do a small teleport of player on same location or nearby (probably just change Y position)
or
you can use respawn method to allow stuck players to just respawn again (not the best option if there are respawn penalties)

**Comment by shubhank008** [comment]
> 

For that you can use something like the below methods to find a valid navmesh position and teleport there, if it doesn't find a valid navmesh point, you can use Respawn() instead
https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html
https://docs.unity3d.com/ScriptReference/AI.NavMesh.FindClosestEdge.html
