### ISSUE TITLE
NpcDialog - Type: Warp

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#2011]
NpcDialog - Type: Warp
I do not specify warp positions because there is no faction selection

Map Info
it's here but only works after death

I remember it used to work but now it doesn't seem to work

**Comment by insthync** [comment]
I don't get it

**Comment by BarzoStrike** [comment]
![1](https://user-images.githubusercontent.com/54517546/231021050-9f48ee96-c3b0-4019-87e5-d05a77b94445.png)
Since I can't set the faction here, it goes to the location we don't want during teleportation.

![2](https://user-images.githubusercontent.com/54517546/231021060-9fa631c1-141f-42f5-a22b-e181c510f18f.png)
when i set it here it goes to these positions after it dies

**Comment by insthync** [comment]
You can set condition in the menu to show/hide menu

**Comment by insthync** [comment]
Never have faction setting in the warp dialog, but has a menu -> `FactionIs` condition type

**Comment by BarzoStrike** [comment]
i spent more than 2 hours for such a simple thing i was looking in the wrong place thanks :D
