### ISSUE TITLE
[Issue] monster character animation issue

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#2012]
I have created my monsters and it works fine in unity editor but when  build my game and test in local there is an issue happens when monster stop moving turn to idle ( https://youtu.be/YREf9nTGv2I ) check the video ..... and this is in editor ( https://youtu.be/tV12drALBUg )

**Comment by insthync** [comment]
Did you try to changes codes maybe in NavMeshEntityMovement, oh I forget to ask, which entity movement are you using for your monsters?

**Comment by AhmedHon** [comment]
> Did you try to changes codes maybe in NavMeshEntityMovement, oh I forget to ask, which entity movement are you using for your monsters?

NavMeshEntityMovement and no i didn't try

**Comment by insthync** [comment]
So I think you didn't try everything.

**Comment by AhmedHon** [comment]
with code changes yes didnt try all :)

**Comment by insthync** [comment]
I never found that issue, in the second video, it is host or client which joined the server?

**Comment by AhmedHon** [comment]
Client joined the server .. testing in local

**Comment by insthync** [comment]
Yep, It does not occur when I test it.

**Comment by AhmedHon** [comment]
Could i send to you 1 monster to test with it with his animations ?

**Comment by insthync** [comment]
Yes, you can

**Comment by insthync** [comment]
May export from Unity then it will include your settings

**Comment by AhmedHon** [comment]
https://mega.nz/file/GktlWKaB#ijDTC8vBvXwrc7-ZNvNxLj0EkbE1uow0Q4d6UsJgPa4 Here it is , sorry for late

**Comment by insthync** [comment]
Fixed in 1.82d
