### ISSUE TITLE
Issue changes in MobileSwipeArea 

### ISSUE THREAD

**Issue by JoRangers** [suriyun-production/mmorpg-kit-docs#2013]
Hi,

I upgraded from 1.81f3 to 1.82b and there are changes on MobileSwipeArea.

Now, the script isn't working on editor and the functions "OnPointerDown / OnPointerUp" don't seem to be called.
I don't know if I need to do more setup on the gameobject, etc.

The previous version of the script works correctly in the 1.82b.

I only tested on editor.

I use Unity 2021.3.21f1, plateform Android.
For the GameInstance, Test in Editor Mode = Mobile With Key Inputs.

**Comment by insthync** [comment]
Why is mine still working?

https://youtu.be/09Q_snUQhlk
