### ISSUE TITLE
NpcDialogGraph missing Voice field

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2015]
The VoiceField is missing NpcDialogGraph. its only in NpcDialog

https://gyazo.com/b1d504bfbde0a320e22ae6d75d48c6db
https://gyazo.com/4320223be850a06329d078ebeb5acbfb

here its missing 
https://gyazo.com/3369ca43d94b8346ebeb6da7355b9814

**Comment by insthync** [comment]
Fixed in 1.82c
