### ISSUE TITLE
1.82c Error

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#2017]
![image](https://user-images.githubusercontent.com/54517546/232172165-2be37e8d-e30a-4f28-aa09-2d092c9cbab3.png)
when i update or clean install i get a lot of errors

**Comment by AhmedHon** [comment]
I think you need to import this https://github.com/insthync/UnityMultiplayerARPG_DatabaseManager to your project , It's not production ready yet

**Comment by insthync** [comment]
@AhmedHon No, it is a different thing, that is a new project which is a web-service for database management. Don't import it.

**Comment by AhmedHon** [comment]
ahh kk

**Comment by insthync** [comment]
Do this: https://github.com/insthync/UnityMultiplayerARPG_DatabaseManagerSource/commit/20b202165024639019b535b1e6338525d083634d

**Comment by insthync** [comment]
And this: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/b04348c98fe7cd01b81cc614378be838c3566f14

**Comment by BarzoStrike** [comment]
i still get error, i will wait until next update

**Comment by insthync** [comment]
It was uploaded, If you can do it properly you won't get an error.
