### ISSUE TITLE
Build WebGL in Linux Unity 2022  -  error CS0103: The name 'Caching' does not exist in the current context

### ISSUE THREAD

**Issue by reidsneo** [suriyun-production/mmorpg-kit-docs#2018]
Building in Linux ENV for WebGL occure error
`Assets/UnityMultiplayerARPG/Core/SimpleAssetBundleClient/Scripts/AssetBundleManager.cs(346,36): error CS0103: The name 'Caching' does not exist in the current context`

Using Kubuntu 22.04
Unity 2022
Net Framework standard (tested to version 2.0) too but still failed
No Compression or Caching used :  [References](https://ittipon-bay.medium.com/mmorpg-kit-how-to-build-webgl-and-connect-to-localhost-server-6c9d9426fbf0)

![image](https://user-images.githubusercontent.com/12298979/232278356-d8958431-3f17-4acc-9fd7-1773ad076533.png)
![image](https://user-images.githubusercontent.com/12298979/232278393-a0f78ff7-009d-4058-9b73-da48c2020037.png)
![image](https://user-images.githubusercontent.com/12298979/232278518-6b349200-f89d-4ce2-ba38-80c3b43a9648.png)

Is it regarding to my NET Framework? I've not yet tested build in window yet
Thanks!

**Comment by insthync** [comment]
https://github.com/insthync/unity-simple-asset-bundle-client/commit/ce22c97ae484bf5b4938e23aaf4d0f194dfcd07a

**Comment by insthync** [comment]
Fixed in 1.82c3

**Comment by reidsneo** [comment]
Nice! 
I will test it after work hour
