### ISSUE TITLE
Map Server Not Ready on 2018.4.16f1 LTS

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#202]
I am getting a "Map Server Not Ready" error, when the player tries to join the game. When the game is built on 2018.4.16f1 LTS.  If I install 2018.4.14f1 LTS and build for MMO mode in there, the Map Server works as intended.

Windows 10 64-bit
Unity 2018.4.16f1 LTS

1) Start MMO server.
2) Create account through client.
3) Create character through client.
4) Click Start Game.
5) Error pop up: Map Server is not ready.

**Log:**
(Log) [SQLiteDatabase] Reading config file from ./config/sqliteConfig.json
(Log) [DevExt] GameInstance - LoadedGameData
(Log) [IAP_INIT]: Initialized without purchasing
(Log) [MapNetworkManager] LiteNetLibManager::OnStartServer
(Log) [LiteNetLibGameManager] Loading Scene: Map002 is online: True
(Log) [CentralNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 2
(Log) Saved 0 character(s)
(Log) Saved 0 building(s)
(Log) [CentralNetworkManager] LiteNetLibServer::OnPeerDisconnected peer.ConnectionId: 2 disconnectInfo.Reason: RemoteConnectionClose

**Comment by insthync** [comment]
Okay, I will check it.

**Comment by Hawkadium** [comment]
Uninstalled everything and reinstalled 2018.4.16f1 LTS, still the same issue.
I installed 2019.3.0f6 and everything worked fine.

**Comment by insthync** [comment]
Yep, it's weird, I can't run map-servers with batch mode, when I set `notSpawnInBatchMode` config to `true` it's working.

**Comment by insthync** [comment]
Try this patch package, I try to use async function to load scenes instead of using coroutine.

[LiteNetLibNetworkManagerFixLoadsceneRoutine.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4139646/LiteNetLibNetworkManagerFixLoadsceneRoutine.zip)

**Comment by Hawkadium** [comment]
Worked for 1.52c on Unity 2018.4.16f1 LTS
Thank you.
