### ISSUE TITLE
1.82c2 Error

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#2020]
throws me the following error in a new project.
Assets\UnityMultiplayerARPG\Core\Scripts\GameData\Model\BaseCharacterModel.cs(174,27): error CS1501: No overload for method 'GetComponentInParent' takes 1 arguments

**Comment by insthync** [comment]
Please use 2020.3.46 or just remove `true` parameter in `GetComponentInParent`.
