### ISSUE TITLE
[Clarification/Inquiry] Mobs after Summon

### ISSUE THREAD

**Issue by SkyRain2020** [suriyun-production/mmorpg-kit-docs#2027]
Good day

i just wanna ask
what happen to the mob(s) that we summon in game
after we restart our server?

will it remain in the map after server restart? or it will just vanish since its not there originally there?

will it cause any server problem if we dont remove it before server restart

thanks we just want to know
Since
we experience server error logs that mobs is not in navmesh and its repeatign rapidly

and if anyone have those errors
what are your ways to fix it?
thanks

https://prnt.sc/HUAB_eNd-dcm

![error](https://user-images.githubusercontent.com/127582299/233091164-2f274f5d-561a-475d-806b-26dfd2b22876.jpg)

**Comment by insthync** [comment]
If it is a monster summoned by a character, it will be stored in the database, and bring it to summon when the player enters a game.

If it is a monster that spawned by spawn areas, it won't be persisted, it will respawn every time when a map server started.

Those errors are from Unity NavMeshAgent, try googling it you may find how to fix it, you just have to build a scene's NavMesh properly and fit the spawn areas.

**Comment by SkyRain2020** [comment]
i mean the mobs was summong by game master in  certain map
the mobs is not there originally

thanks

**Comment by insthync** [comment]
They will be removed from the server.

**Comment by SkyRain2020** [comment]
> They will be removed from the server.

thanks sir

ill try resolve that navmesh agent error

thanks again
