### ISSUE TITLE
(PAID REQUEST) ItemRefineInfo - Color by level

### ISSUE THREAD

**Issue by MoacirCarlos** [suriyun-production/mmorpg-kit-docs#2029]
Hello,

I would like to know the value so that I can implement the colors in the names of the items by level.

In addition to the default color that we can already configure in ItemRefineInfo, we can change it when the item passes a certain level.

Thanks.

**Comment by insthync** [comment]
This will be added to 1.89

![Screenshot_5](https://github.com/user-attachments/assets/a09cef94-7e41-4ad8-89f1-d21a80b43d5a)
