### ISSUE TITLE
Question - Spawn/manually place building in SOLO/LAN

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2030]
IS there an easy way by editing code or settings to just manually place a building such as a campfire or workbench in the world and be permanent and allow the players to interact with it.

For now only building placed by players can be interacted.

**Comment by insthync** [comment]
No easy way

**Comment by sawcisson** [comment]
Allright , where should I look at to instantiated it without owner is ?

**Comment by insthync** [comment]
Okay, then, you may try change condition in building entity -> IsCreator function

**Comment by insthync** [comment]
Did you try to turn `canUseByEveryone` option on?

**Comment by moepi2k** [comment]
I use pre placed queued workbenchs, only thing what you need to do rhat player can interact is. Set the health in syncvar >0, then create a building SO with the workbench prefab and add to db. It seems that it is required on start to load the formulas.

**Comment by sawcisson** [comment]
Tried with a campfire, HP syncfield does allow to be detected but no way to access storage. Getting message "can't open storage"

I'll be checking further more

**Comment by moepi2k** [comment]
Ah yea, storage is not possible in what way. My solution only works for the workbench. But yea would be cool to have pre placed storage which can be used by everyone
