### ISSUE TITLE
Warp lan/solo - spawn position problem

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2031]
Player who are not host don't spawn on the spawn position of the map inside the instance for some reason.
They spawn else where and fall through ground

**Comment by insthync** [comment]
Send me your AnyDesk address to my email, I want to try it by myself

**Comment by insthync** [comment]
My email is ittipon.bay@gmail.com

**Comment by sawcisson** [comment]
Issue is still present

**Comment by insthync** [comment]
what is it?, i cannot remember, and also please tell me reproduce steps, if it is still present, why this one was close, what happended?

**Comment by sawcisson** [comment]
I don't know what changed but with my latest test i updated the kit and when in LANRPG a host join it goes to the right coordinates of the warp, but the other non host players keep their spawn position of the previous map and thus are not where they are supposed. If they respawn it's all good but then when leaving the cave the same happens where the non host character seems to keep the old position and spawns out of the map instead of the warp position.

Only happens to Non host character, the host is all good.

I tried to debug it as much as i could without being able to fix it in the code

**Comment by sawcisson** [comment]
Any idea of what might be causing it ?

**Comment by insthync** [comment]
I can't remember what is it, and you didn't tell me how to reproduce yet, so I have no idea.

**Comment by sawcisson** [comment]
I told you how to reproduce it here 

> I don't know what changed but with my latest test i updated the kit and when in LANRPG a host join it goes to the right coordinates of the warp, but the other non host players keep their spawn position of the previous map and thus are not where they are supposed. If they respawn it's all good but then when leaving the cave the same happens where the non host character seems to keep the old position and spawns out of the map instead of the warp position.
> 
> Only happens to Non host character, the host is all good.
> 
> I tried to debug it as much as i could without being able to fix it in the code

**Comment by insthync** [comment]
Do you know that only host can change the scene?

**Comment by insthync** [comment]
How I was fixed your in the past?

**Comment by insthync** [comment]
Or it has no fixing but just closed because of no answering?

**Comment by sawcisson** [comment]
I'm not sure, yes only host change scene but the non host player can't have their position for spawn and respawn changed.
I tried manually changing  non host players to change their spawn point and it doesn't work. i tried to change respawn point doesn't work.

And when non host player get teleported to new map they don't spawn on the coordinate that are in the mapinfo

I'm really not sure why

**Comment by sawcisson** [comment]
I also noticed that there is some problem with buildingentity where players in lan cannot interact with each other buildable.
