### ISSUE TITLE
Position issue after unmount horse ?

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2032]
https://user-images.githubusercontent.com/11313412/233595405-4faeae6f-7ce3-499b-8c84-92526f6067d5.mp4

![Ekran görüntüsü 2023-04-21 120835](https://user-images.githubusercontent.com/11313412/233595991-198d95aa-1be6-47f2-a268-8850bbcbb684.png)

is it server lag or wrong rigidbody entity movement settings or root motion ?

**Comment by insthync** [comment]
Hmm, weird issues, seems like it is not using root motion, right?

**Comment by temelkirci** [comment]
No root motions for idle and run animations in warrior.only in attack animations

**Comment by temelkirci** [comment]
this also sometimes happen while running without ride on vehicle on map.

**Comment by insthync** [comment]
Send me your RidibodyMovementEntity, I want to compare with mine

**Comment by temelkirci** [comment]
https://drive.google.com/file/d/1GeTXTE5uzJ5uGrXvHZU1nrz3XXDjotzi/view?usp=share_link

here

**Comment by insthync** [comment]
Try set `Platform Layer Mask` to none

**Comment by temelkirci** [comment]
for mount RidibodyMovementEntity ? my character has not any RidibodyMovementEntity component

**Comment by temelkirci** [comment]
![şşş](https://user-images.githubusercontent.com/11313412/233654768-d941660e-2f03-4f0d-96d3-c9669f95aa25.png)

**Comment by insthync** [comment]
Which entity movement you use for your character?

**Comment by insthync** [comment]
And please send all server-log files

**Comment by AhmedHon** [comment]
which version ? cos its working fine to me with secure or not secure

**Comment by temelkirci** [comment]
v1.78.I am using navmesh.
Maybe I should choose not secure ?

![4444](https://user-images.githubusercontent.com/11313412/233673070-48957129-2f44-492e-9286-73ae6787542f.png)

**Comment by insthync** [comment]
Or you may try import the latest version of entity movement components

**Comment by temelkirci** [comment]
I changed as not secure and solved.Thank you
