### ISSUE TITLE
[Question] I am trying to make a script to get the faction that is the user

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2034]
As the title says I am trying to make a script to obtain the information of which faction the players belong to and show a certain image depending on which faction the user is

**Comment by insthync** [comment]
```
public class GetFactionToDoSomething {
  public BasePlayerCharacterEntity entity;
  public void DoIt() {
    if (GameInstance.Singleton.Factions.TryGetValue(entity.FactionId, out Faction faction)) {
      // Do something
    }
  }
}
```

**Comment by Niinra** [comment]
Thank you very much. I put this script in canvasgameplay? I'm trying to make modifications and that and I don't know how to guide myself where to put things like this, really thank you very much for the answer <3

**Comment by insthync** [comment]
That example script should be attached to the player entity prefab. And set ref of entity to `entity` field.

Yes, you can do it like that.

**Comment by Niinra** [comment]
![image](https://user-images.githubusercontent.com/115952096/233795312-48f36cf1-98f5-48b6-bcbf-a742c7ad44a9.png)

I did it this way and I have this error but it is solved if I remove singleton, but it gives me reference errors

**Comment by insthync** [comment]
Which reference error?

**Comment by Niinra** [comment]
![image](https://user-images.githubusercontent.com/115952096/233795615-f277c92f-242e-4278-80fc-c84c6039f2fb.png)
![image](https://user-images.githubusercontent.com/115952096/233795639-e5110197-63e1-4d2f-93bb-56ef46417f5b.png)
I put the script in the player

**Comment by insthync** [comment]
Yep, it having error because there is no value set to the `entity`

**Comment by Niinra** [comment]
I don't understand where I have to assign some value

**Comment by insthync** [comment]
If you can't fix this, don't wish that you can do anything.

You may try changing `entity` to be a public field or serialized field. Then set its value by drag player character entity into it.

Or you may use `GetComponent` function to get the component use it to set the value.

**Comment by Niinra** [comment]
It is that it is the problem and I tried trying to obtain the component directly with a getcomponent and I have not tried changing the access to public now I try it, it is only that I get confused how the asset is designed because I have not reviewed it, that is why I am asking I need to understand it and so I understand your great work

**Comment by insthync** [comment]
I think you did not understand Unity scripting well yet, that part is not very related to the kit. It is just basic Unity scripting. Where is relate to the kit is just getting faction data.

**Comment by Niinra** [comment]
I think you're confusing me, I'm talking about when you talk to me about a reference to some asset method xd, I also think I'm a little confused, sorry, my native language is Spanish

**Comment by Niinra** [comment]
I don't know exactly which methods to access to do a certain thing that I need there I get very confused and many generally have the same name but do something different but little by little I am understanding I was able to fix it thank you very much
