### ISSUE TITLE
The character does not punch while running.

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#2035]
The character does not punch while running. it has to stop. The character is sliding. i can't fix this. I try everyhing. stop when the character punches while running

https://youtu.be/0Qfqu1GWY2g

**Comment by insthync** [comment]
Don't tell me that you try everything, I don't trust anyone who said that, It is better to tell me whats you have tried.

**Comment by insthync** [comment]
You have to set weapon's movespeed rate while attacking to `0`

![Screenshot_454](https://user-images.githubusercontent.com/2697550/233795791-17c41082-f6cc-4e24-9bae-085c9fcf31c9.png)

**Comment by kazuden** [comment]
happens when you have a gun.How do we do it if we have a gun? thank you

**Comment by insthync** [comment]
Just do the same thing with the gun weapon.

**Comment by kazuden** [comment]
I found. Thank you. my whole day is over because of this :)
