### ISSUE TITLE
Fix for missing Unity_server flag and nothing in doc

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2039]
character and monsters not attacking in the build version? Within Unity it works normally.
It was fixed by using the MMo kit unity menu and doing a setup for offline.

but there is nothing in the documentation or changelogs about this. We spent 5 days trying to figure out what was happening.

There is no errors, warnings or anythings. It works in the editor not in the Build.

You should add this to the documentation or automate it.

**Comment by moepi2k** [comment]
Noticed that in new version the unity_server define is missing my default. Bwfore it was added when import kit

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan

It is already written in the Building section, so I think it does not have to be added by default

![Screenshot_455](https://user-images.githubusercontent.com/2697550/233911147-790abccf-d5de-4f30-9c3a-46cca11021dd.png)

**Comment by insthync** [comment]
And you said nothing in the document.

**Comment by insthync** [comment]
I hope this will enougn https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/160-before-you-build

**Comment by sawcisson** [comment]
Yes it does work ,but this section is supposed to be done when you get started on a project.
My project is 3 years old and I wasn't understanding why sundently it wasn't working.

But yes this does fix the problem but don't seem like a logical thing to do at first with an old project. 

I reported it to see if it might be useful to add it as an annotation for existing projects encountering such problems.

**Comment by insthync** [comment]
What do you want me to do?
