### ISSUE TITLE
[Issue] Cannot teleport to another scene 

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#2040]
Hi , i made a teleport npc .. i can teleport to any place in the same scene but i cannot teleport to another map in different scene ( it works fine in unity editor but in build local test i can't teleport ) using latest version.. https://youtu.be/fXWjhJq6hYA check the video

**Comment by insthync** [comment]
Show me your NPC dialog config

**Comment by AhmedHon** [comment]
> Show me your NPC dialog config

![2](https://user-images.githubusercontent.com/71017004/233972483-fc9324bf-6f5c-4f78-bad8-a8957ba79312.jpg)
![1](https://user-images.githubusercontent.com/71017004/233972489-5ae691f1-2480-4b95-9b4d-fcbcdb7d63e9.jpg)

**Comment by AhmedHon** [comment]
What is that ? i do as always

**Comment by insthync** [comment]
I don't know what is the "do as always"

Did you add the map to `spawnMaps` list ?

**Comment by AhmedHon** [comment]
yes i did that 
![1](https://user-images.githubusercontent.com/71017004/233982905-57eb97d7-bab6-4982-b9e3-262cca16e833.jpg)
"C:\Users\Run\Desktop\Kalonline - TNE\Kal-TNE.exe" -startMapSpawnServer -spawnExePath "C:\Users\Run\Desktop\Kalonline - TNE\Kal-TNE.exe" -startCentralServer -startDatabaseServer -machineAddress "127.0.0.1"

**Comment by insthync** [comment]
Added to the config file? did the config file have a different setting?

**Comment by khongtuong** [comment]
did you add spawnMaps to serverConfig.json ?

![image](https://user-images.githubusercontent.com/6816616/233983960-c5c35e52-85c6-4db2-9b6b-8be0e8a3b128.png)

**Comment by AhmedHon** [comment]
i didnt make config out , i just use the built in one

**Comment by insthync** [comment]
You must use it because config files will be created and used to set all config in components.

**Comment by AhmedHon** [comment]
ok i will do it right now

**Comment by AhmedHon** [comment]
i found a config folder when i built the game and found that maps didnt add in serverconfig .. works fine now thanks
