### ISSUE TITLE
[Question] Teleport buttons

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#2042]
I have added condition to require level equal or more than but when im lower than that level buttons disappear and i should reach the require levels to appear them , as i remember there is an option to make it visible always but i can't find it .. Is it still able to do that by default ? 
![1](https://user-images.githubusercontent.com/71017004/234102234-bc6a5c2d-3d64-45b8-a193-591d12eeda67.jpg)

**Comment by insthync** [comment]
No way to do that, I can't remember if it is having that option.

**Comment by AhmedHon** [comment]
ok thank you
