### ISSUE TITLE
Root motion :(

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#2043]
I've been struggling for 5 days but I couldn't find the reason or the problem. I did everything I could think of and everything I researched. I couldn't fix it. Why isn't the character root moving?
[https://youtu.be/BBq6fHzKXwI](url)

**Comment by insthync** [comment]
Show me your entity movement settings

**Comment by kazuden** [comment]
Of course

[https://www.hizliresim.com/o4k7tiy](url)

**Comment by insthync** [comment]
Did you try to turn `Use Root Motion While Not Moving` on?

**Comment by kazuden** [comment]
I've tried. nothing has changed

**Comment by insthync** [comment]
Send me your AnyDesk Address, I want to try it.

**Comment by kazuden** [comment]
549 608 631

**Comment by insthync** [comment]
Done, but your animation just not move properly

**Comment by insthync** [comment]
You just didnot uncheck "Baked into pose" https://docs.unity3d.com/Manual/RootMotion.html

**Comment by kazuden** [comment]
thank you
