### ISSUE TITLE
Savepoint Invalid Position Character Stuck at Respawn Point

### ISSUE THREAD

**Issue by SkyRain2020** [suriyun-production/mmorpg-kit-docs#2044]
respawning in savepoint in current map is causing invalid position for the navmesh agent

which causes the agent to not be put above the navigation mesh

Description:

When character died in game
The character will respawn to its savepoint

When the savepoint of the character is in anothet map
No error occur, the character can move freely and can continue the game

But
When its savepoint is within same map
It will respawn to its savepoint
But this time, there is an error
It is stuck in the respawn point even if the character move
The game will drag the character to that savepoint area
Causing character seems stuck

**Comment by insthync** [comment]
Has any error log messages?

**Comment by insthync** [comment]
Offline or MMO game?

**Comment by SkyRain2020** [comment]
Its online sir MMO

Version
1.82c2

ERROR No Tag [2023-04-18 14:15:00] - "IsStopped" can only be called on an active agent that has been placed on a NavMesh.

ERROR No Tag [2023-04-18 14:15:00] - "GetRemainingDistance" can only be called on an active agent that has been placed on a NavMesh.

That occurs when invalid post happens

**Comment by insthync** [comment]
How about movement secure settings?

**Comment by SkyRain2020** [comment]
> How about movement secure settings?

Navmesh Entity Movement
Server Authoritative
then all default

**Comment by insthync** [comment]
Okay, I will fix it

**Comment by SkyRain2020** [comment]
> Okay, I will fix it

Thanks sir
We are almost done with our 2nd alpha test
Then these problem occurs 
I will wait for the fix soonest
Thanks again
Thank you verymuch

**Comment by insthync** [comment]
[Fix missing data.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/11322744/Fix.missing.data.zip)

This can fix the issue

**Comment by SkyRain2020** [comment]
Thank you
Very fast
