### ISSUE TITLE
Wrong animation using 1.82d latest one 

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#2046]
thank you for all your hard work , navmesh entity works fine now but there is another issue with it ... im using different animation for move and walk .. in unity editor it works fine but with local test it's using move animation for move and walk .. walk animation not working ..
Here it's Local test video ( https://www.youtube.com/watch?v=9fPdpXYFVvQ ) .... now check unity editor ( https://youtu.be/UPVnMW2A7fE )

**Comment by insthync** [comment]
[Fix extra movement state.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/11323914/Fix.extra.movement.state.zip)

Try this

**Comment by AhmedHon** [comment]
Now its walking good but before stop , it go to move then stop to idle ( https://www.youtube.com/watch?v=RBy4_11HIMo )

**Comment by insthync** [comment]
[dont fucking simulate animation at client.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/11324229/dont.fucking.simulate.animation.at.client.zip)

**Comment by AhmedHon** [comment]
yes its working now :) thank you

**Comment by Eniotnacram** [comment]
Thank you suri for the fast fixes as always. Your work is really really appreciated :)
