### ISSUE TITLE
Really long loading with 1.82d.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2047]
Hi I noticed that the loading is taking a really long time, more than before. Looks like all the communication from the server is really slow now. (to log in, register, create a character, join a map) the loading takes 7-8 seconds and it is alsmost instant with previous version of the kit.

I did no changes on my end, simply upgraded my project to kit latest version and now loadings taking a really long time.

**Comment by insthync** [comment]
How?, I don't see any different

**Comment by AhmedHon** [comment]
works fine with me , doesn't take long time

**Comment by AhmedHon** [comment]
but i noticed that the new sync dialog takes time to make the buttons visible and an error appears 
![1](https://user-images.githubusercontent.com/71017004/234432771-1a2c7876-9740-4aa8-b3a9-776c5b88b10e.jpg)

**Comment by insthync** [comment]
That is because it cannot connect to the guild war service to bring occupy guild info

**Comment by AhmedHon** [comment]
ahh kk

**Comment by Eniotnacram** [comment]
There is a video of the loading:
https://medal.tv/games/requested/clips/16txYHh_ee-lOE/d1337kp6OJDK?invite=cr-MSxjakEsNDQ3NDMxODYs

It was really not that long before the kit update. I dont know what I can do to fix that or to see why it is now really long.

Ive rebuilt the server many times, restarted the editor.

**Comment by insthync** [comment]
Having a problem just when login/load characters?, how about while playing game?

**Comment by insthync** [comment]
Please attaches the server logs.

**Comment by Eniotnacram** [comment]
Playing is totally fine, no lagg what so ever

**Comment by insthync** [comment]
Maybe a database-server issue?

**Comment by Eniotnacram** [comment]
Mmm, I changed nothing, its hosted local on the same machine.

**Comment by Eniotnacram** [comment]
Thats really weird, sometimes it is loading kinda fast but sometimes it takes 30-40 seconds

**Comment by insthync** [comment]
Please attaches the server logs.

**Comment by insthync** [comment]
Please attaches the server logs.

**Comment by insthync** [comment]
Please attaches the server logs.

**Comment by Eniotnacram** [comment]
Fudge... I rebuilt the server again and again, and for some reason now the loadings are really fast

**Comment by insthync** [comment]
I think it is slow because connection to database-server (MySQL?) is slow

**Comment by Eniotnacram** [comment]
[log.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/11327835/log.zip)

**Comment by Eniotnacram** [comment]
Using SQLlite for now

**Comment by insthync** [comment]
The issue is still occurring? You said now it is really fast, I am not sure that SQLite lock is a cause of that slow or not

**Comment by Eniotnacram** [comment]
The issue is now gone, but I did nothing to fix it except rebuilding my server. Thats wierd, but its gone now.

**Comment by Eniotnacram** [comment]
That is really weird, im just testing right now, and now I rebuilt my server again and the loading are now slow. It stops, come back sometimes after new builds, thats really weird

**Comment by Eniotnacram** [comment]
Yep it keeps hapening, thats really wierd. Super long loading screen. I cant find what is going on. Going back in previous version remove that problem.

**Comment by Eniotnacram** [comment]
For some reason, I dont have it anymore, with multiple builds. I will close but that was really wierd.
