### ISSUE TITLE
Damageable Hitbox problem still.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2048]
Im still having issue with multiple damageable hitboxs There is a video: https://medal.tv/games/requested/clips/16tQXdhcx8yJ02/d13370WLQCsh?invite=cr-MSxtTmYsNDQ3NDMxODYs

My Goblin have 2 damageable hitbox on it. One for the head and one for the body. Head 1.2X damage. But when attacking him, as my missile have an explosion, it hits both damageable hitbox at the same time and do double damage.

Using Missile Damage Entity. With an explosion radius of 1. 

PS: "I would like to be able to have no explosion on my missile damage entity, but If I put 0. The Entity just disapearing when its out of life or hits anything, and I want it to do an effect when its out of life or hits a surface (thats why im using explosion)

**Comment by Eniotnacram** [comment]
And yeah I dont know what im doing wrong, but I still have the same problem that my missile damage entity sometimes it doesnt do damage to monster entities. The missile clearly hits the target but no damage occurs.

Theres a video:
https://medal.tv/games/requested/clips/16h61tPO3veuhr/d1337pL1SexR?invite=cr-MSxnNlgsNDQ3NDMxODYs

(You can see that the 2, the 6 and the 7 hits clearly hits the target but no damage occurs).

I'll send you below the settings for my missile damage entity and also the damageable hitbox on my monster.

(I maybe think the problem is because of the "explosion" damage. "AOE"

**Comment by Eniotnacram** [comment]
(Missile Damage Entity Prefab)
![Screenshot 2023-04-25 232426](https://user-images.githubusercontent.com/46734935/234461713-6b8c8973-4ec1-4a99-8550-47b3f270970e.png)

(Monster Damageable Hitbox)
![Screenshot 2023-04-25 232513](https://user-images.githubusercontent.com/46734935/234461815-4091d9e6-e154-4e01-b767-6ede676c48e

(Full Monster Prefab)
![Screenshot 2023-04-25 232606](https://user-images.githubusercontent.com/46734935/234462063-8dfb650a-44a5-4b66-a89d-6ba856928458.png)
3.png)

**Comment by insthync** [comment]
Fixed in 1.83
