### ISSUE TITLE
[Bug]Quest

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2049]
anything changed in quests? in latest version my before working quests no longer work as it should

https://gyazo.com/2c65b89a05f5285cce0da6f4d8be7531
https://gyazo.com/08ce3d85a9fba6d9cdb678412c051b89

npc indicator shows available questst but there is none.

**Comment by insthync** [comment]
Wrong indicator?

**Comment by moepi2k** [comment]
no i use the npc1 from demo.
also weird is the graph no longer works as before. when i save and enter game. after close it is not saved
https://gyazo.com/1bb97da543b3eb8bc8c3c37696cd9379

**Comment by insthync** [comment]
I've made a change a bit on how to find available quests which can affect indicators, but I did nothing to NPC graph.

**Comment by moepi2k** [comment]
jup thats the thing
https://gitlab.com/insthync/unity-multiplayer-arpg-core/-/commit/429530e1042e8d466f115d4ac4db1f41724fa700
u just revert those changes and it works

**Comment by Eniotnacram** [comment]
Yea exactly the same issue for me too, indicator not working properly
