### ISSUE TITLE
2D & 3D Instance portals not working

### ISSUE THREAD

**Issue by Zurigan** [suriyun-production/mmorpg-kit-docs#205]
Kit v1.52c, linux server build, 2D demo project

After adding an instance portal / map / mapInfo etc. walking the player character over the portal fails to switch them to the new map instance. 

Logs below from just before player tried to enter instance until after every quiets down, looks like the useful line might be "Coroutine couldn't be started because the the game object 'MapNetworkManager' is inactive!" but unsure how to resolve. Is MapNetworkManager required in instance scenes as well as the init one? 

[Chat] Update map user: 3PMvY3YY by 1
Saved 0 building(s)
Saved 0 character(s)
Saved 0 building(s)
Character [2dQalxIj] Saved
Saved 1 character(s)
[Chat] Update map user: 3PMvY3YY by 1
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Starting process from: /root/server/server.x86_64
Starting process with args:  -batchmode -nographics -mapId Instance001_2D -instanceId VilxkaM2 -centralAddress 64.225.119.193 -centralPort 6000 -machineAddress 64.225.119.193 -mapPort 8002  -startMapServer
Process started. Spawn Id: 3, pid: 9325
Found path: /root/server/server.x86_64
Mono path[0] = '/root/server/server_Data/Managed'
Mono config path = '/root/server/server_Data/MonoBleedingEdge/etc'
Spawn Map Ack Id: 1  Status: Success Error: None
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Initialize engine version: 2019.3.0f6 (27ab2135bccf)
[Subsystems] Discovering subsystems at path /root/server/server_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
Starting process from: /root/server/server.x86_64
Starting process with args:  -batchmode -nographics -mapId Instance001_2D -instanceId 1dXW2sL7 -centralAddress 64.225.119.193 -centralPort 6000 -machineAddress 64.225.119.193 -mapPort 8003  -startMapServer
Process started. Spawn Id: 4, pid: 9348
Spawn Map Ack Id: 2  Status: Success Error: None
Found path: /root/server/server.x86_64
Mono path[0] = '/root/server/server_Data/Managed'
Mono config path = '/root/server/server_Data/MonoBleedingEdge/etc'
Initialize engine version: 2019.3.0f6 (27ab2135bccf)
[Subsystems] Discovering subsystems at path /root/server/server_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
- Completed reload, in  0.207 seconds
- Completed reload, in  0.256 seconds
[Chat] Update map user: 3PMvY3YY by 1
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Saved 0 character(s)
Saved 0 building(s)
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
Saved 0 building(s)
Character [2dQalxIj] Saved
Saved 1 character(s)
[Chat] Update map user: 3PMvY3YY by 1
Add subscriber [0] to [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
UnloadTime: 0.864197 ms
[DevExt] GameInstance - Awake
UnloadTime: 0.589837 ms
[DevExt] GameInstance - Awake
Error: execlp(/root/.config/unity3d/DefaultCompany/mmorpgkit) No such file or directory
[Chat] Update map user: 3PMvY3YY by 1
[MMOServerInstance] Reading config file from ./config/serverConfig.json
[MMOServerInstance] Found config file
[MySQLDatabase] Reading config file from ./config/mySqlConfig.json
[MySQLDatabase] Found config file
Error: execlp(/root/.config/unity3d/DefaultCompany/mmorpgkit) No such file or directory
[DevExt] GameInstance - LoadedGameData
[IAP_INIT]: Initialized without purchasing
[MMOServerInstance] Reading config file from ./config/serverConfig.json
[MMOServerInstance] Found config file
[MySQLDatabase] Reading config file from ./config/mySqlConfig.json
[MySQLDatabase] Found config file
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32.so
Fallback handler could not load library /root/server/server_Data/Mono/Kernel32
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32.so
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32
[DevExt] GameInstance - LoadedGameData
[IAP_INIT]: Initialized without purchasing
[MapNetworkManager] LiteNetLibManager::OnStartServer
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [547613141] name [ItemDropEntity2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [-1790050832] name [WarpPortalEntity2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [1063866312] name [Warrior2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [1327770859] name [OrcsWarrior2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [159852119] name [OrcsArcher2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [187559334] name [ChestEntity2D]
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32.so
Fallback handler could not load library /root/server/server_Data/Mono/Kernel32
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32.so
Fallback handler could not load library /root/server/server_Data/Mono/libKernel32
[InstanceMapServer] Starting server
[InstanceMapServer] Connecting to Central Server: 64.225.119.193:6000
[CentralNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 2
[MapNetworkManager] LiteNetLibManager::OnStartServer
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [547613141] name [ItemDropEntity2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [-1790050832] name [WarpPortalEntity2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [1063866312] name [Warrior2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [1327770859] name [OrcsWarrior2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [159852119] name [OrcsArcher2D]
[MapNetworkManager] LiteNetLibAssets::RegisterPrefab [187559334] name [ChestEntity2D]
[InstanceMapServer] Starting server
[InstanceMapServer] Connecting to Central Server: 64.225.119.193:6000
[CentralNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 5
CentralAppServerRegister::OnPeerConnected.
[InstanceMapServer] Connected to Central Server
[Central] Register Instance Map Server: [5] [1dXW2sL7]
Register instance map server: 1dXW2sL7
Register instance map server: 1dXW2sL7
Register map server: Map002_2D
Register map server: Map001_2D
Connecting to chat server
[MapNetworkManager] LiteNetLibManager::OnStartClient
[ChatNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 2
[MapNetworkManager] LiteNetLibClient::OnPeerConnected
Connected to chat server
[Chat] Update map user: 3PMvY3YY by 1
CentralAppServerRegister::OnPeerConnected.
[InstanceMapServer] Connected to Central Server
[Central] Register Instance Map Server: [2] [VilxkaM2]
Register instance map server: VilxkaM2
Register instance map server: VilxkaM2
Register map server: Map002_2D
Register map server: Map001_2D
Connecting to chat server
[MapNetworkManager] LiteNetLibManager::OnStartClient
[ChatNetworkManager] LiteNetLibServer::OnPeerConnected peer.ConnectionId: 3
[MapNetworkManager] LiteNetLibClient::OnPeerConnected
Connected to chat server
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Character [2dQalxIj] Saved
Saved 1 character(s)
Remove subscriber [0] from [OrcsArcher2D(Clone) (UnityEngine.GameObject)]
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Character [2dQalxIj] Saved
Saved 1 character(s)
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Character [2dQalxIj] Saved
Saved 1 character(s)
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Character [2dQalxIj] Saved
Saved 1 character(s)
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
[Chat] Update map user: 3PMvY3YY by 1
Saved 0 character(s)
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)
Character [2dQalxIj] Saved
Saved 1 character(s)
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
[Chat] Update map user: 3PMvY3YY by 1
Setting up 1 worker threads for Enlighten.
  Thread -> id: 7fbc53fff700 -> priority: 1 
[CentralNetworkManager] LiteNetLibManager::OnStopHost
[MapNetworkManager] LiteNetLibManager::OnStopHost
[MapNetworkManager] LiteNetLibManager::StopServer
[MapNetworkManager] LiteNetLibManager::OnStopServer
Coroutine couldn't be started because the the game object 'MapNetworkManager' is inactive!
[InstanceMapServer] Stopping server
[InstanceMapServer] Disconnecting from Central Server
[CentralNetworkManager] LiteNetLibServer::OnPeerDisconnected peer.ConnectionId: 2 disconnectInfo.Reason: RemoteConnectionClose
[MapNetworkManager] LiteNetLibManager::StopClient
[ChatNetworkManager] LiteNetLibServer::OnPeerDisconnected peer.ConnectionId: 3 disconnectInfo.Reason: RemoteConnectionClose
[MapNetworkManager] LiteNetLibManager::OnStopClient
[MapNetworkManager] LiteNetLibManager::OnStopHost
[CentralNetworkManager] LiteNetLibManager::OnStopHost
[MapSpawnNetworkManager] LiteNetLibManager::OnStopHost
[ChatNetworkManager] LiteNetLibManager::OnStopHost
[Chat] Update map user: 3PMvY3YY by 1
Process spawn id: 3 killed.
Setting up 1 worker threads for Enlighten.
  Thread -> id: 7f1af57dc700 -> priority: 1 
[CentralNetworkManager] LiteNetLibManager::OnStopHost
[MapNetworkManager] LiteNetLibManager::OnStopHost
[MapNetworkManager] LiteNetLibManager::StopServer
[MapNetworkManager] LiteNetLibManager::OnStopServer
**Coroutine couldn't be started because the the game object 'MapNetworkManager' is inactive!**
[InstanceMapServer] Stopping server
[InstanceMapServer] Disconnecting from Central Server
[CentralNetworkManager] LiteNetLibServer::OnPeerDisconnected peer.ConnectionId: 5 disconnectInfo.Reason: RemoteConnectionClose
[MapNetworkManager] LiteNetLibManager::StopClient
[ChatNetworkManager] LiteNetLibServer::OnPeerDisconnected peer.ConnectionId: 2 disconnectInfo.Reason: RemoteConnectionClose
[MapNetworkManager] LiteNetLibManager::OnStopClient
[MapNetworkManager] LiteNetLibManager::OnStopHost
[CentralNetworkManager] LiteNetLibManager::OnStopHost
[MapSpawnNetworkManager] LiteNetLibManager::OnStopHost
[ChatNetworkManager] LiteNetLibManager::OnStopHost
Process spawn id: 4 killed.
Saved 0 character(s)
Saved 0 building(s)
Saved 0 building(s)

**Comment by ben-roberts** [comment]
This is also happening in the 3D demo project after talking to the NPC to warp you to a Map2 Instance. In 3D you'll see 'warping' for a few seconds before a black screen ... then you get kicked out of the server to character select with a 'Cannot connect to the server' UI error.
