### ISSUE TITLE
ClusterServer.cs

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2050]
I always have this error on my project. I even tried removing the whole kit and readding it. Still the same error.
![image](https://user-images.githubusercontent.com/118698151/234691190-e3d383ba-7e83-421b-9743-52f5889bdbaa.png)

**Comment by AsheshPlays** [comment]
This Happens when i changed platform to android..

**Comment by AsheshPlays** [comment]
i changed
UNITY_EDITOR || UNITY_SERVER) && UNITY_STANDALONE
to
UNITY_EDITOR || UNITY_SERVER || UNITY_STANDALONE || UNITY_ANDROID)

and its working, i dont know tho if that is correct.

**Comment by insthync** [comment]
![Screenshot_471](https://user-images.githubusercontent.com/2697550/234714142-77fd531f-be77-4046-abe4-7064842d15d9.png)

**Comment by AsheshPlays** [comment]
Thanks! Works Perfectly!

**Comment by AsheshPlays** [comment]
so, i was done with android and wanted to build the server. Now i have this error.

![image](https://user-images.githubusercontent.com/118698151/235321315-2f920d68-7034-460f-8f72-9ce6a80f6cc0.png)

so i removed the last "}" 
![image](https://user-images.githubusercontent.com/118698151/235321364-d12a4c7b-077c-4b75-8e81-4286cee66486.png)


then i get this error

![image](https://user-images.githubusercontent.com/118698151/235321397-40f340e0-503b-40eb-8ed9-d922ba6dcccb.png)


then i tried using the old file of ClusterServer.cs when it wasnt edited yet and it fixed the errors, but I cannot connect to the server after building it and launching it.

**Comment by insthync** [comment]
Watch `CountUsers` carefully.
