### ISSUE TITLE
[Request] Make RigidBodyEntityMovement more easily extensible

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#2051]
It is currently very difficult to extend the RigidBodyEntityMovement script without extensive core edits. I have made a lot of modifications to it to change the way things like swimming work, so it ends up being a big headache every time there are changes to this script with kit updates. Would you please consider refactoring this file to be more easily extensible? I am willing to pay if necessary. Thanks in advance!

**Comment by insthync** [comment]
You can just create a new component by copy codes from `RigidBodyEntityMovement` and using it, can you tell me the reasons that you won't do it?

**Comment by vaughanb** [comment]
So far that's what I've been doing. I can continue to do so, but I thought
it might be useful for everyone if it was possible to just extend it. I
don't want to miss out on your useful changes/updates, but it has recently
become harder to do anything but completely replace the script when you
update the kit.

I will close this issue. If you feel like making any changes in this regard
in the future, I will appreciate it. Thanks either way!
