### ISSUE TITLE
Movement Button Problem in mobile mode

### ISSUE THREAD

**Issue by Udayabhanu0** [suriyun-production/mmorpg-kit-docs#2052]
Can anyone please help? Suddenly, my movement button is not working. Everything else is working except for that, and no error message is being shown. Any ideas why this is happening? 

https://user-images.githubusercontent.com/116990855/235253189-2a01e99f-0b0b-4b6c-8409-2d26e3a1957e.mp4

**Comment by insthync** [comment]
Hmmm, I never try that Simulator, how can I try it?

**Comment by Udayabhanu0** [comment]
Could we connect over Google Meet so that I can show you my problem? I haven't changed anything, and even the default CanvasGameplayMobile isn't working.

**Comment by insthync** [comment]
I think it is a Simulator issues, so I ask about it.

**Comment by Udayabhanu0** [comment]
i build the apk it also did not work on the mobile

**Comment by insthync** [comment]
As I try it is working properly, which kind of your input handler?, old input manager or new input system?

**Comment by Udayabhanu0** [comment]
sorry sir i fixed it it is the event handler issue i sloved it

**Comment by Udayabhanu0** [comment]
sir one more question where i learn about rpc call can you please guide me i am trying to get which quest is currently active by player

**Comment by Udayabhanu0** [comment]
![Screenshot 2023-04-29 162658](https://user-images.githubusercontent.com/116990855/235299124-d1caf9a7-303a-4729-a283-b3b042efd89c.png)
this is the controller issue
