### ISSUE TITLE
new version 1.82d2 

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#2053]
new version 1.82d2 i am getting error. I'm doing the following, it doesn't work: https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan
Unity version : 2020.3.46f1
![image](https://user-images.githubusercontent.com/50966738/235259555-1a76ca57-30b9-434f-adec-ef1d1bab87ec.png)

**Comment by Time-Token** [comment]
Same error for me aswell.

**Comment by insthync** [comment]
Do it like this https://github.com/suriyun-production/mmorpg-kit-docs/issues/2050#event-9109499318

**Comment by kazuden** [comment]
it didn't work

![image](https://user-images.githubusercontent.com/50966738/235300117-435037f7-3c86-4409-9a73-6696a01c70ce.png)

**Comment by insthync** [comment]
Seems like you don't know to code at all, don't type `0 references`, it is not codes :(

**Comment by kazuden** [comment]
yes I skipped it. Thank you. I have a lot to learn from you.
