### ISSUE TITLE
MobileInputConfig Issue with HotkeyJoystick

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2054]
I add MobileInputConfig Component in each Hotkey-Button for skills in AttackAndAction 
when the MobileInputConfig Saves in runtime all the Instantiated HotkeyJoystick goes into the first Hotkey-button making the other HotkeyButton unclickable

**Comment by chumleader** [comment]
i hope there a fix to this

**Comment by insthync** [comment]
Did you set different `saveKey`?

**Comment by chumleader** [comment]
yes i set a different save key for each Hotkey
such as 
HOTKEY_1,HOTKEY_2 and so on for the remaining skill slots
HotKeyJoystick on the other hand, i tried giving it HOTKEY_JOYSTICK, 
but then, HotkeyJoystick still has bug even without saveKey.
my bug is When i saved the MobileInput all the instantiated HotkeyJoystick is on HOTKEY_1, even HotkeyJoystick has MobileInputConfig Component or not.

**Comment by insthync** [comment]
![Screenshot_473](https://user-images.githubusercontent.com/2697550/235311413-4435472c-ff97-48b3-ba76-0c73d781f48c.png)

??

**Comment by chumleader** [comment]
i have done that already, there are no issues in Hotkeys (Hotkey-1 to Hotkey-??)
the issue is the Instantiated "HotkeyJoystick"
even there are no MobileInputConfig Component on it, the position of it will be on Hotkey-1 when Config is saved, i suggest you recreate my problem
use mobile UI
Set saveKey for each hotkey of "AttackAndAction" child objects
the result is same even you add a saveKey for HotkeyJoystick or not
because the code instantiates it in every Hotkey, it is just the Config Overwrites its position when saved

**Comment by insthync** [comment]
Try to capture video to show me what is the problem

**Comment by chumleader** [comment]
Here is the video link
this contains with component and without component
https://streamable.com/s460qe

**Comment by insthync** [comment]
`UICharacterHotkeyJoystickEventHandler` -> `UpdateEvent()`

```
joystick.transform.localPosition = UICharacterHotkey.transform.localPosition;
```

**Comment by chumleader** [comment]
> `UICharacterHotkeyJoystickEventHandler` -> `UpdateEvent()`
> 
> ```
> joystick.transform.localPosition = UICharacterHotkey.transform.localPosition;
> ```

do this fix needs a MobileInputConfig in Joystick or not?

**Comment by insthync** [comment]
No
