### ISSUE TITLE
Updating to 1.83 no death animation.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2056]
Ive changed nothing, simply updated to 1.83 and now my monsters do not play their death animation when dead. Also, their hp bar doesnt go down when damage is taken. UI also doesnt appear anymore on my monsters. (HP, MP, etc)

**Comment by insthync** [comment]
Why mine playing?

**Comment by insthync** [comment]
Okay, I think I might upload it with wrong submodule codes

**Comment by Eniotnacram** [comment]
Yes, on brand new project with simply the kit it is working. But on my project it is not. And If i got back to previous version of the kit it works on my project.

**Comment by insthync** [comment]
Fixed in 1.83b
