### ISSUE TITLE
Windows Server Build - UserLoginManager

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2057]
Hello! I was wondering why do i have this issue on 1.82d2. I never had this on previous versions. Is this normal or I should do something ? Because i cant connect to my server.

"UserLoginManager not setup yet"

![20230430_144713.jpg](https://user-images.githubusercontent.com/118698151/235340645-f1aa3c6e-b272-4658-9041-1ef730bd5946.jpg)

PS: I am using MariaDB

**Comment by insthync** [comment]
Try do this:

![Screenshot_478](https://user-images.githubusercontent.com/2697550/235341353-8530f5fd-9d40-43fc-8eec-4a37aa2ce733.png)

**Comment by insthync** [comment]
You actually should include log files

**Comment by insthync** [comment]
After I look at that log carefully, I guess that there is something wrong in serverConfig.json

**Comment by AsheshPlays** [comment]
My serverConfig.json



{
  "databaseOptionIndex" : 0,

  "centralAddress": "localhost",
  "centralPort" : 36001,
  "clusterPort" : 8010,
  "centralMaxConnections" : 1000,
  "machineAddress" : "173.68.203.62",
  
  "mapSpawnPort" : 6001,
  "mapSpawnMaxConnections" : 11,
  "spawnExePath" : "G:\My Drive\000000 SERVER_BUILDS\BETA09\ProjektGenesis.exe",
  "notSpawnInBatchMode" : false,
  "spawnStartPort" : 40001,
  "spawnMaps" : ["Mandara Village"],

  "databaseManagerAddress" : "localhost",
  "databaseManagerPort" : 6003,

  "useWebSocket": false,
  "webSocketSecure": false,
  "webSocketCertPath": "",
  "webSocketCertPassword": "",
}

Also before i build, i press this

![image](https://user-images.githubusercontent.com/118698151/235342179-e693de51-d236-4588-b83b-47aef4238689.png)

and build using this

![image](https://user-images.githubusercontent.com/118698151/235342189-b7ef566a-eabd-4953-a152-a13038bb4d9a.png)

**Comment by AsheshPlays** [comment]
> 

Also its strange that it doesnt create a log folder
![image](https://user-images.githubusercontent.com/118698151/235342274-def3a76c-2b4d-4c2f-80cd-bfb3b9d63d6f.png)

**Comment by AsheshPlays** [comment]
@insthync 

I tried running it locally using xampp.
![image](https://user-images.githubusercontent.com/118698151/235352157-4932aabd-8c00-41a7-8d3d-c274f2274ea2.png)

I get the same result.

Should i update the kit? I am on 1.82d2

**Comment by insthync** [comment]
Don't you see it is telling you that it can't deserializs server config ?

**Comment by insthync** [comment]
Just delete , from the last line in serverConfig.json, that is it.

**Comment by AsheshPlays** [comment]
ohhhhhhh sorry for that.. i copy pasted the config from documentation, and it worked.. and now i read your comment, i just realized that it was that easy. im dumb
