### ISSUE TITLE
[Question] Character Update and About the new Update

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#2058]
Hi, 
 I have a couple of  questions I have recently changed the character model for my game which made all the characters that were made with the last character model are not visible as the old Models is not there anymore 

Now I want to migrate the character OLD model to the new one. What is the best solution for it ?
I have tried to update the DataID and entityID from the character table in the DB with the Dataid and entity id of the new characters but it didn't work.

Another question is related to 1.83 
"Make MMO codes shareable with other C# projects, so you won't have to build server projects with Unity, It can speed up your server development, also may improve performance, but you still have to use Unity to build a map-server. You can develop Login, Character Management, Scene Management and Database Management systems outside of Unity ." 

This is a really gree idea and addition to the kit but currently, it is optional or not. For now, if updated to 1.83 can we keep with the existing method of running the server

**Comment by insthync** [comment]
Yes, It is optional. I not sure what you have made changes, only character model?

**Comment by Deepankar1993** [comment]
I meant That, 
I was using custom models for the male player character and now I am using Polytop models for the male character

**Comment by insthync** [comment]
How it is not work?

**Comment by Deepankar1993** [comment]
When I added new character model and removed the old one from the game database player character entity 
![image](https://user-images.githubusercontent.com/1295862/235364937-93b16621-9469-4270-b6ee-a9ae62b1920d.png)

and added the new male model the old characters are not visible anymore

**Comment by insthync** [comment]
Any error messages when it load data from database?

**Comment by Deepankar1993** [comment]
No, the Old character just doesn't show, Only new if create new only it will with new model

**Comment by insthync** [comment]
You said you are going to migrate from old to new, then why the old one should show ?

**Comment by Deepankar1993** [comment]
No, I want new male model should show in place of the old models with all the same stats 
Example 
if Player in 
Game version (OLD)-Male mode prefab (old male model)
Character name : XChar (old male model)

Now in the new version  Male mode prefab (new  male model)
Character Name : XChar (new  male model) 

Did you Understand? if you want the Can show you in Anydesk if needed

**Comment by insthync** [comment]
This is the case that you have 2 different clients?

**Comment by AsheshPlays** [comment]
@Deepankar1993 I think you have material/shader problem. Not sure. Need more info of the issue.

**Comment by AsheshPlays** [comment]
@Deepankar1993 What you can do is convert the old prefab to fbx then export it to your new project. Or export the prefab as package and include the dependencies needed, not all tho, just the needed ones.

**Comment by moepi2k** [comment]
I think the problem is that your player prefab is chabged. It take data from prefab to load the player. An option is to check whats new id and replace it in database (mysql/sql) had the problem once too

**Comment by Deepankar1993** [comment]
@moepi2k yes I have tried it today but It is not working for all characters, Kind of confusing, Still will be working on it tomorrow see if I manage to fix all

**Comment by Deepankar1993** [comment]
I found the solution , Just Updating the DB with new dataID and entityID will not work , It also require that we restart the server
