### ISSUE TITLE
About the flag selection

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#2059]
It is wrong to select more than one flag for each character selection. Only 1 flag can be selected from a single account. Flag color cannot be selected except for the monthly account. different flags can be selected for each character, but this is wrong.

**Comment by insthync** [comment]
Faction?

**Comment by kazuden** [comment]
yes faction

**Comment by insthync** [comment]
Only you said it is wrong, I won't change it because you just told me that, if I change it, then it will affect many other customer, and it has only me is the person in charge

**Comment by kazuden** [comment]
MMOPRG games are as I said. and in addition; Each flag starts the game in a different place. It's up to you to fix it or not. :)

**Comment by insthync** [comment]
All games?

**Comment by kazuden** [comment]
as I said games with flag or fuction.

**Comment by insthync** [comment]
All games which has faction?

**Comment by juniormagalhaes** [comment]
> All games which has faction can have only one faction per account?

nop, sometimes the character starts as neutral and chooses a faction later.

**Comment by insthync** [comment]
Yes, like Cabal

**Comment by kazuden** [comment]
> All games which has faction can have only one faction per account?

I mean that yes.All characters with a faction have only one faction

**Comment by kazuden** [comment]
> nop, sometimes the character starts as neutral and chooses a faction later.

yes, it could be. that's right. but the problem with us is wrong that every character can choose

**Comment by kazuden** [comment]
maybe you don't need to fix it. you can only show how to fix it with video. this would be simpler. You will not have any problems with your customers.

**Comment by insthync** [comment]
@kazuden No, it still change faction later and can have different faction per 1 account.

**Comment by insthync** [comment]
Video is not enough, it needs codes to change, and from what I've seen you are so beginner, you know nothing about coding. And I want to be just an assets developer, not a coding teacher.

**Comment by kazuden** [comment]
may not know coding. But I learn everything very well. though not a teacher.and I'll show you that later. after my project is finished. :))

**Comment by kazuden** [comment]
I may not know coding. But I am a very good student. Even if I don't have a teacher. I'll show you this when my project is done. :)))

**Comment by insthync** [comment]
Then you won't have to show me, you can learn by the codes in the project.

And I don't like how to convince me to help you by telling me what I did is wrong, because it is not like other MMORPG games.

**Comment by AsheshPlays** [comment]
there are lots of games that have different factions per character on a single account.

**Comment by insthync** [comment]
I've added `isLocked` settings to faction data, turn it on to hide it from the character creation scene, and also add `changeCharacterFaction` to quest data, when the quest is completed it will change the character's faction to that specific faction.

I know it is not a solution for @kazuden 's case, but I hope that you can learn something from those changes.

**Comment by kazuden** [comment]
thank you :)
