### ISSUE TITLE
Weapons Re-instantiated on Fire/Taken Damage

### ISSUE THREAD

**Issue by ashley66444** [suriyun-production/mmorpg-kit-docs#206]
Weapons are re-instantiated when firing a weapon that has ammo capacity as well as when you take damage.

SetEquipWeapons() (BaseCharacterModel.cs) is called frequently which has instantiate calls in it.

Reproduction (Fire weapon with ammo):
1) Add Debug.Log statement to SetEquipWeapons(EquipWeapons equipWeapons) under BaseCharacterModel.cs to monitor frequency.
2) Change bow001 to have ammo capacity greater than 0 under weapon config. https://i.imgur.com/itAwAyZ.jpg
3) Fire the bow in either Single Player or MMO mode.

Reproduction (Take damage):
1) Add Debug.Log statement to SetEquipWeapons(EquipWeapons equipWeapons) under BaseCharacterModel.cs to monitor frequency.
2) Take damage

Reproduction of fire weapon with ammo confirmed by Hawkadium in discord.

Upon research this seems to be called due to the way we update Ammo on weapons and Durability (ammo when firing and durability when taking damage) that results in a needless call of "OnSelectableWeaponSetsOperation" which then calls SetEquipWeapons which instantiates the weapons again.

When we update EquipWeapons in CharacterData.cs & BaseCharacterEntity_NetworkData.cs we update the EquipWeaponSets as follows:

`public EquipWeapons EquipWeapons
        {
            get
            {
                this.FillWeaponSetsIfNeeded(EquipWeaponSet);
                return SelectableWeaponSets[EquipWeaponSet];
            }
            set
            {
                this.FillWeaponSetsIfNeeded(EquipWeaponSet);
                SelectableWeaponSets[EquipWeaponSet] = value;
            }
        }`

which in turn calls the observable operations "onSelectableWeaponSetsOperation" (BaseCharacterEntity_NetworkData.cs) and "List_CollectionChanged" (CharacterData.cs)

**Comment by ashley66444** [comment]
Potential fix for this?

Under BaseCharacterEntity_NetworkData.cs

As far as I've tested, doesn't seem to break anything. Just a simple check if we are actually changing the weapons (and not just their data) before calling SetEquipWeapons

        protected virtual void OnSelectableWeaponSetsOperation(LiteNetLibSyncList.Operation operation, int index)
        {

            selectableWeaponSetsRecachingState = new SyncListRecachingState()
            {
                isRecaching = true,
                operation = operation,
                index = index
            };

            if (EquipWeapons.rightHand.id != selectableWeaponSets[index].rightHand.id || EquipWeapons.leftHand.id != selectableWeaponSets[index].leftHand.id)
            {
                CharacterModel.SetEquipWeapons(EquipWeapons);
                if (FpsModel)
                    FpsModel.SetEquipWeapons(EquipWeapons);
            }
        }

**Comment by ashley66444** [comment]
Fix above causes issues with equipping new items. Will investigate further fixes if one is not found.

**Comment by insthync** [comment]
Okay, I'm investigating about this.

**Comment by insthync** [comment]
In next version I will check for data changes before destroy / instantiates equipment model with string like this in BaseCharacterModel.cs → SetEquipWeapons: 
```
            // Clear equipped item models
            tempDirtyEquipItems.Clear(); // <-- This is string builder
            tempAddingKeys.Clear();
            if (rightHandItem)
            {
                tempDirtyEquipItems.Append("_0:").Append(equipWeapons.rightHand.dataId).Append(":").Append(equipWeapons.rightHand.level);
                tempAddingKeys.Add(GameDataConst.EQUIP_POSITION_RIGHT_HAND);
            }
            if (leftHandItem)
            {
                tempDirtyEquipItems.Append("_1:").Append(equipWeapons.leftHand.dataId).Append(":").Append(equipWeapons.leftHand.level);
                tempAddingKeys.Add(GameDataConst.EQUIP_POSITION_LEFT_HAND);
            }

            if (tempDirtyEquipItems.ToString().Equals(dirtyEquipWeapons))
            {
                // No data changes, so skip it
                return;
            }
            // Set dirty equip weapons for check changes later
            dirtyEquipWeapons = tempDirtyEquipItems.ToString();
```

It's actually checking item in `InstantiateEquipModel` function, notice the codes

```
            // Same item Id, just change equipment level don't destroy and re-create
            if (itemIds.ContainsKey(equipPosition) && itemIds[equipPosition] == itemDataId)
            {
                for (i = 0; i < equipmentEntities[equipPosition].Count; ++i)
                {
                    tempEquipmentEntity = equipmentEntities[equipPosition][i];
                    tempEquipmentEntity.Level = itemLevel;
                    if (equipmentEntity == null)
                        equipmentEntity = tempEquipmentEntity;
                }
                return;
            }
```
But I think to check it with string will be better because it will not have to loop to destroy cached model or set equipment entity's level.

**Comment by ashley66444** [comment]
Thanks for the fix! I've been working on item stats randomization so I'll have to modify this a bit as my randomizer uses the same dataId for diff items, but this will work. :)

Thanks for the quick fix! :)

**Comment by ashley66444** [comment]
Also as of note: Since SetEquipWeapons is virtual, if we only specify this fix here and is overwritten by an extension or additional class (such as the uma integration) this will cease to be fixed for that class. It's why I was trying to code this in OnSelectableWeaponSetsOperation to handle any cases where this might get called

**Comment by insthync** [comment]
I was add codes that checking equipment in BaseCharacterEntity_NetworkData.cs (function `SetEquipWeaponsModels()` , `SetEquipItemsModels()`) in 1.53. So I will close this.
