### ISSUE TITLE
[Bug]Quest Track

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2060]
https://gyazo.com/aed65da403134d05efb0fc6867981797 

the quest track seems broken.
it tracks the quest when its unselected and when u select it, it will hide.

also its weird when u select both it gets reenabled again.

**Comment by khongtuong** [comment]
> https://gyazo.com/aed65da403134d05efb0fc6867981797
> 
> the quest track seems broken. it tracks the quest when its unselected and when u select it, it will hide.
> 
> also its weird when u select both it gets reenabled again.

I also noticed this before but thought it was my wrong  ui setup till now

**Comment by Eniotnacram** [comment]
Yes same for me. Was going to create an issue. Using Latest 1.83b

**Comment by insthync** [comment]
@moepi2k @khongtuong It is working as intended look at codes in `UICharacterQuestsUtils` -> `GetFilteredList`

It will show **ALL** quests if there are no tracking quests, that is it.

@Eniotnacram Video or something that can show me your issues, please.

**Comment by moepi2k** [comment]
Ok i check the fikter, bjt even if its work as intend its weird that the quest is gone from the kist when click track, and when track is not selected the quest appears.

The issue what @Eniotnacram  mean is the one i already posted https://github.com/suriyun-production/mmorpg-kit-docs/issues/2049

The latest cha ges u made broke tje quest indicatir. When u revert ur changes the indicator works fine again

**Comment by insthync** [comment]
@moepi2k So what you want?

**Comment by moepi2k** [comment]
@insthync sorry you were right with the quest track. it just lookd  weird when tested with 2 active quests. 
works as it should. but the thing what @Eniotnacram  mean is still there, check #2049 revert last changes and quest indicator works.
in default demot it seems to looks good. but try to add quest condition. quest indicator not show proberly then.

**Comment by insthync** [comment]
I will add `showAllWhenNoTrackedQuests` option to `UICharacterQuests`

**Comment by Eniotnacram** [comment]
Yea same issue here #2049. Not working properly for me either from latest updates. Was working before.

**Comment by insthync** [comment]
Try 1.83c

**Comment by Eniotnacram** [comment]
> 

Where? I dont have access to the repo, cant find 1.83c

**Comment by Eniotnacram** [comment]
> Try 1.83c

It is still buggy for me. On creation of a new character its buggy quest doesnt appears but all icon appears in the mini map. 

If I close the game reopen it, now the quests are showed properly.

**Comment by insthync** [comment]
@Eniotnacram Video or something that can show me your issues, please.

Hope I won't have to repeat it again.

**Comment by Eniotnacram** [comment]
> @Eniotnacram Video or something that can show me your issues, please.
> 
> Hope I won't have to repeat it again.

Sorry, theres the video: https://medal.tv/games/requested/clips/17AVEp9oAv6HMW/d1337H9apBYX?invite=cr-MSx4SU4sNDQ3NDMxODYs

In the begining of the video when I reach the campfire. You can see that theres is no indicator (the glowing orb). Also on the mini map, you can see that all Minimap Icon appears over each others. (Completed, Pending, New). They are all stacked over each other. And it is the same thing for the questboard NPC. When i log off, and return to the game. Everything is fixed, the indicators appears, and not all Icon appears on MINIMAP.

**Comment by insthync** [comment]
That NPC spawned by NPC Database or placed into the scene?

**Comment by Eniotnacram** [comment]
Both npcs place into the scene
