### ISSUE TITLE
(Question) Instantiate effect or objects at a specific moment of some code

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2061]
Well I am developing a script to instantiate an effect or generally an object at a specific time in a script that I have the idea is to instantiate the object or the effect at a specific time I would do it this way

`public GameObject effectToHit;`
`var effect = Instantiate(effectToHit, skillUser.MovementTransform);`

Obviously this is not going to work, I understand why the object has to be created for the client as well as the server and it is something that I cannot find how to do, it is simply to instantiate an effect and then after a few seconds remove it, but I don't know how to instantiate it for both the client as for the server

I would try the methods of the litelibmanager, like this` BaseGameNetworkManager.Singleton.Assets.NetworkSpawn(effectToHit);`

but still nothing

**Comment by insthync** [comment]
Just play effect on the scene right?

**Comment by Niinra** [comment]
Yes If only on the scene

**Comment by insthync** [comment]
You may create a simple networked behaviour component and then add RPC to play effects on client like this:

```
public class DoSomethingAtClient : LiteNetLibBehaviour {

        protected float _countDown = 5f;
        void Update()
        {
            // Send RPC from server only, so if it is not a server, don't do anything
            if (!IsServer) return;
            _countDown -= Time.deltaTime;
            if (_countDown <= 0)
            {
                // Reset count down to make it to do something at clients every 5 seconds
                _countDown = 5f;
                // Call RPC from server to do something at clients
                RPC(DoSomething);
            }
        }

        [AllRpc]
        public void DoSomething()
        {
            Debug.Log("Log at clients");
        }
}
```

Then create a empty game object in the scene and attach this component.

**Comment by Niinra** [comment]
![image](https://user-images.githubusercontent.com/115952096/235813164-b17b77e4-a4d4-4d3f-b833-c5ce4234510a.png)
ok but one question I want to instantiate this effect and if it is generally in the scene it would be activated for all the players (mmo mode) e.g. I have this add-on that makes the players teleport on the back and I want the effect to appear on the players who They used this ability and I want to call it right now, so what would it look like if it just instantiated exactly the class you gave me and the instance where it goes doesn't need it?

**Comment by insthync** [comment]
In that case,  just do that should work because apply skill function will be called on both client and server

**Comment by Niinra** [comment]
I'm sorry I got a bit confused, it would work with the simple code I made or with the class you sent, sorry the translator confuses me, I apologize again
