### ISSUE TITLE
Error Gameplay Mobile

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#2063]
The problem appears when I change the map or exit the game from the settings section.
There is no problem in PC login, but when I turn it into mobile, it gives an error
I think it's only on mobile, when I change it to standalone, the problem goes away
fresh kit version 1.83c
https://www.youtube.com/watch?v=btj011O8Ui0

**Comment by insthync** [comment]
Thank you for bug reporting, you can applies this changes to fix it 

https://github.com/insthync/unity-camera-and-input/commit/26613fe90eb90ffe12989076e95641001b006cc7

**Comment by BarzoStrike** [comment]
I made the changes but I get an error

**Comment by BarzoStrike** [comment]
I failed, I changed them, it still gives an error
![123](https://user-images.githubusercontent.com/54517546/236527381-09ec78c7-03ee-4b50-8c74-1f2f0d713d01.png)

**Comment by kazuden** [comment]
Işınlama konumunu değiştir. warportal konumunu değiştir. warportalın üstünde kalıyo karakter.

**Comment by BarzoStrike** [comment]
Beceri butonlarını kullanamıyorsun warp konumuyla alakalı değil joyistik kontrolüyle alakalı harita değiştirirken veya relogin yaparken yaşıyorsun bu sorunu sadece mobil de var.
