### ISSUE TITLE
Problem：Custom editing interface

### ISSUE THREAD

**Issue by 15291358689** [suriyun-production/mmorpg-kit-docs#2064]
![1683262845318](https://user-images.githubusercontent.com/63120220/236380800-6e9b10ca-1a72-4c96-a066-39ffeb5f09e1.png)
![1683262873589](https://user-images.githubusercontent.com/63120220/236380816-d417f409-3b6f-4365-91b0-512f43dd71c5.png)
As shown in the figure, I want to modify the display of the fields in the editing interface. I tried "Odin's [LabelText]" and "[InspectorName]", but they both don't work properly.What should I do?

**Comment by insthync** [comment]
It maybe because of conflicts between the decorators, I will check it.

**Comment by 15291358689** [comment]
Thank you. If possible, please let me know once it is resolved. @insthync

**Comment by insthync** [comment]
Can't solve, I can't see it source codes and I don't know how it work.
