### ISSUE TITLE
Damage Problem

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2065]
I have this problem where there are lots of times i cannot inflict damage on my mobs especially missile. Missile always no damage.

https://youtu.be/iSDXVJF3cOo

On my old project using 1.81, i have no problems with damage. Is there something i should do or has something changed on the recent version?

**Comment by insthync** [comment]
Your current version is 1.83c ?

**Comment by AsheshPlays** [comment]
@insthync yes sir.. latest version.. 1.83c

**Comment by juniormagalhaes** [comment]
I also have these same problems, and I reported it once

https://github.com/suriyun-production/mmorpg-kit-docs/issues/1806

**Comment by moepi2k** [comment]
> I have this problem where there are lots of times i cannot inflict damage on my mobs especially missile. Missile always no damage.
> 
> https://youtu.be/iSDXVJF3cOo
> 
> On my old project using 1.81, i have no problems with damage. Is there something i should do or has something changed on the recent version?

it just seems ur monster walks out of range so player not hit any hitbox?
try with a static monster.

**Comment by insthync** [comment]
You may check monster's aim transform (I cannot remember its name, I will check it later when I came back to my home) and hit boxes, you may see the missile moved to enemy but it is not the hitbox. I think I should create a new kind of damage applying, may call it simple, which will hit without any collision check, just uses distance for checking.

**Comment by AsheshPlays** [comment]
@insthync
That would be very nice.. If you will make that, will that hit even monster or player move to the side? Like classic mmorpg?

**Comment by Eniotnacram** [comment]
Yes, Ive made post here also about this. Damage not registering on mobs and it is worse vs online players. (With missile damage Entity)

**Comment by AsheshPlays** [comment]
@Eniotnacram 
Yes. It seems missile damage entity is broken.
I tried raycast and it does damage. Only missile has no damage.
Here is the raycast. Its a temporary fix but not a good idea. xD
https://user-images.githubusercontent.com/118698151/236602449-7821cfd7-e1b4-4bc0-9a1e-481dbfbea649.mp4

**Comment by moepi2k** [comment]
Missile damage entity is not broke, it only lack the lag.compensation which.is added only for melee and raycast.

**Comment by AsheshPlays** [comment]
@moepi2k
do you know how to fix it? I tried recreating the monster and missile dmg entity but still nothing.

**Comment by moepi2k** [comment]
Dont have a fix, but to fake it abit inadded a small explode radius. So it compensate the miss thing. But my game is top down sonits anyway a bit diffrent. Maybe use raycast and fake the ballistic of projectile with the speed. Depends on ur game and need

**Comment by Eniotnacram** [comment]
> Dont have a fix, but to fake it abit inadded a small explode radius. So it compensate the miss thing. But my game is top down sonits anyway a bit diffrent. Maybe use raycast and fake the ballistic of projectile with the speed. Depends on ur game and need

Explode radius (if it is small) make it more laggy for me

**Comment by Eniotnacram** [comment]
But yea, really need to have a rework for the missile/projectile. Even the projectile damage entity is really buggy (especially with Particles afffect) After the pooling reset, the particles doesnt play.

**Comment by juniormagalhaes** [comment]
> 



> But yea, really need to have a rework for the missile/projectile. Even the projectile damage entity is really buggy (especially with Particles afffect) After the pooling reset, the particles doesnt play.

I also realized that

**Comment by Eniotnacram** [comment]
Would be really usefull also to add a disappear effect on the missile damage entity.  Now the only way possible to make an explosion if it hits a wall or what ever is to setup an explosion radius. But I dont want it to do damage. Simply do a explosion effects (impact effect) on what ever it hits or if its out of life.

**Comment by moepi2k** [comment]
Yea hope at some point we get lag compensation for missile too

**Comment by Eniotnacram** [comment]
> Yea hope at some point we get lag compensation for missile too

yea it really needs to :)

**Comment by Deepankar1993** [comment]
This happens in my game too, Mostly noticeable in the Online mode

**Comment by insthync** [comment]
Try 1.83d

**Comment by Eniotnacram** [comment]
Thanks will try it! So hithox doesn't work with capsule collider anymore?

**Comment by insthync** [comment]
Yes

**Comment by Eniotnacram** [comment]
> Yes

Would it be possible to make it work again with capsule? What is the reason why the capsule has been removed ? Is it for performance ?

**Comment by Eniotnacram** [comment]
It seems that this update indeed worked! Damage registering properly. BUT, i think the missile damage entity with an explosion doesnt work anymore tho. Without explosion its working perfectly, but with an explosion, no damage. Never.
