### ISSUE TITLE
How to get network entity data?

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2066]
i want to display some data of the networked character or entity.
how can i get that?

**Comment by insthync** [comment]
Which data?

**Comment by chumleader** [comment]
character data
stats
Faction
Class
everything relates to Character
in client side it was

`GameInstance.PlayingCharacter`

how about the Network? how do I print it. To be specific I want to display an icon of faction besides the name, which i have done correctly, but I only seen it being client sided only. On other Players, they don't see my icon.
that's why I want to see all the networked character data. if there is a class or pointer to it.
I need many applications to it not just Faction or class.

**Comment by chumleader** [comment]
my bad i found out that Canvasnonowningcharacter was not modified
but still, i need to get the network Character Data

**Comment by insthync** [comment]
Can't you get data from `PlayerCharacterEntity` component?, it is attached to all player characters.
