### ISSUE TITLE
[Question] Animation Interruption 

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#2067]
Using the Playable character Model, 
Is there a way to tell that animation can't be interpreted for example the pickUp animation, if during the pickup animation Any of the movement keys (w/a/s/d) is press the character starts to move forward while running the pickup animation

**Comment by moepi2k** [comment]
You can block movement when pickup or just use avatar mask to onöy let the animation runs at upper body

**Comment by Deepankar1993** [comment]
How to block the movement when using pick up

**Comment by moepi2k** [comment]
you need to code, there is no option for it.
