### ISSUE TITLE
Missile Entity Shooter Controller just doesnt do damage. Version 1.83c Version 1.83c

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2068]
On a brand new project using Version 1.83c. Take the archer class, using shooter controller. Impossible to do damage on the monsters. Working with melee and simply raycast. But missile doesnt work.

It works when we put explosion on the missile. But with 0 explosion, no damage. Never.

**Comment by insthync** [comment]
Try find `&& _alreadyHitObjects.Contains(target.GetObjectId())` and change it to `&& !_alreadyHitObjects.Contains(target.GetObjectId())`

**Comment by Eniotnacram** [comment]
Yep working with that change. Thank you :)
