### ISSUE TITLE
Animations of other players can get stuck in the wrong state

### ISSUE THREAD

**Issue by ben-roberts** [suriyun-production/mmorpg-kit-docs#207]
For instance:

https://gyazo.com/f27979018a7ce0439dd4542f2d7bd29b

Shows character running in place even though they've stopped. 

Using Unity 2019.3.0f6, kit 1.52c, demo mmo project running on a dedicated server.

**Comment by insthync** [comment]
This was fixed in 1.53. If this issue still occurs, you can reopen this issue post.
