### ISSUE TITLE
The method or operation is not implemented (In-app Purchase)

### ISSUE THREAD

**Issue by tubhluas** [suriyun-production/mmorpg-kit-docs#2072]
Anyone also have this error throw out on making a cash purchase in v1.83c? In the cash shop after press buy it would take a few seconds and it will say connection timeout. When check on the server log, the following error were issue:

ERROR No Tag [2023-05-12 01:01:51] - NotImplementedException: The method or operation is not implemented.
UnityEngine.Purchasing.Security.GooglePlayTangle.Data () (at <67678e9f80da45c282647daf802e3ea1>:0)
MultiplayerARPG.MMO.MMOServerCashShopMessageHandlers.ValidateIAPReceipt (System.String receipt, System.Collections.Generic.List`1[MultiplayerARPG.CashPackage]& cashPackages) (at <67678e9f80da45c282647daf802e3ea1>:0)
MultiplayerARPG.MMO.MMOServerCashShopMessageHandlers+<HandleRequestCashPackageBuyValidation>d__5.MoveNext () (at <67678e9f80da45c282647daf802e3ea1>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.MMO.<HandleRequestCashPackageBuyValidation>d__5:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<HandleRequestCashPackageBuyValidation>d__5&)
MultiplayerARPG.MMO.MMOServerCashShopMessageHandlers:HandleRequestCashPackageBuyValidation(RequestHandlerData, RequestCashPackageBuyValidationMessage, RequestProceedResultDelegate`1)
LiteNetLibManager.LiteNetLibRequestHandler`2:InvokeRequest(RequestHandlerData, RequestProceededDelegate)
LiteNetLibManager.TransportHandler:ProceedRequest(Int64, NetDataReader)
LiteNetLibManager.TransportHandler:ReadPacket(Int64, NetDataReader)
LiteNetLibManager.LiteNetLibServer:OnServerReceive(TransportEventData)
LiteNetLibManager.LiteNetLibServer:Update()
LiteNetLibManager.LiteNetLibManager:FixedUpdate()
LiteNetLibManager.LiteNetLibGameManager:FixedUpdate()
MultiplayerARPG.BaseGameNetworkManager:FixedUpdate()
MultiplayerARPG.MMO.MapNetworkManager:FixedUpdate()

**Comment by insthync** [comment]
I will rework on it, please wait

**Comment by insthync** [comment]
Try 1.83e
