### ISSUE TITLE
Character Snapping Back

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2073]
I made character movement Server Authoritative. And i have this problem. First minute after login, my character keeps snapping back to its position.

Is there a way to remove or to lessen the time?

https://youtu.be/oeHjVJSPjc4

**Comment by moepi2k** [comment]
Alot of my players report that issue also.

**Comment by insthync** [comment]
I think your character may doesn't move at the server.

**Comment by AsheshPlays** [comment]
@insthync

it only goes like that on first login. After maybe 1 minute, its normal again. Does it have something to do with snap threshold?

**Comment by insthync** [comment]
Try find `if (_isServerWaitingTeleportConfirm)`

And delete all of them, then try your game again.

![Screenshot_486](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/2c3a1739-c0ad-4556-8f31-4ae4261fb9d0)

**Comment by moepi2k** [comment]
> @insthync
> 
> it only goes like that on first login. After maybe 1 minute, its normal again. Does it have something to do with snap threshold?

exactly sama what my palyer report. when they login sometimes they have the snapback issue for a short time and then it works.

**Comment by AsheshPlays** [comment]
@moepi2k

short time but its annoying for players who got disconnected during a boss monster fight and when reconnected, cant move and will die instead. And if i remove server authoritative of movement, they can use speedhack.

**Comment by reidsneo** [comment]
Same also here, a brief moment connecting to server it will load a initial position of all object
and about 1-2 seconds it load normally from database position
I using WEBGL with websocket connection currently

**Comment by insthync** [comment]
Did you guys try what I've told you to do?

**Comment by insthync** [comment]
Yes

**Comment by AsheshPlays** [comment]
@insthync

thanks..
