### ISSUE TITLE
SUG: Language Key for Player Class & Player Name

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2074]
To use the language key in dialogue graphs.

For example:
"Hello <UI_FORMAT_PLAYER_NAME>, how are you?"   =>  "Hello _BJPickles_, how are you?"
"Hello <UI_FORMAT_PLAYER_CLASS>, I need your help!"   => "Hello _Warrior_, I need your help!"

**Comment by insthync** [comment]
A new feature in 1.83g, https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/165-npc-dialog-message-by-keys
