### ISSUE TITLE
[Bug]Quest Talk to Npc

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2075]
there is a strange bug with quests talk to npc

https://gyazo.com/4db058fddf5a892e29b696ffd519778c

its a simple quest "talk to npc" without using complete after talked.
so when i talk to the npc the quest will mark as complete which is correct but the dialog shows abonded. it only show the correct dialog after reopen the dialog.

this only happen in mmo but not in singleplayer

**Comment by Eniotnacram** [comment]
Did the same for me, I found a fix, I taught i was not using the kit properly. Ill send you sceens here soon.

**Comment by moepi2k** [comment]
Cool let me know

**Comment by insthync** [comment]
Try 1.83d2
