### ISSUE TITLE
Error on 1.83d

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2076]
I have this error after importing MMORPG_KIT2021.2_Microsoft.Bcl.AsyncInterfaces5.0.0.dll..

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/4e0904c0-a84d-4126-accb-df3c45891d70)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/49dc25f8-44ae-4f40-a6fd-ef0d18cc9f78)

**Comment by AsheshPlays** [comment]
Solved! Had to exclude Unitask of the kit.

**Comment by insthync** [comment]
Why? Then which UniTask are you ising?

**Comment by AsheshPlays** [comment]
@insthync

Its a unitask included in YooAssets. I use it for asynchronous scene and addressables and encryption.

**Comment by AsheshPlays** [comment]
@insthync 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/7efd2463-3ed6-4766-a730-761f2d619e4f)

**Comment by insthync** [comment]
Okay
