### ISSUE TITLE
Add/Change Random Bonuses

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2077]
I want to control random bonus type and values as modular with a bonus changer item.I actually did it on my game but only change all bonuses (add/remove).but I want to keep bonus count.I want to sperate random bonus add and change with item.Random bonus (random seed) can be modular and extent for different options. @insthync

**Comment by insthync** [comment]
What do you want me to do?

**Comment by temelkirci** [comment]
I mean a item should andom efsun count and values.You can seperate add bonus and change bonus.We can control it efficitly.
