### ISSUE TITLE
BUG: Warping within the same map can be inaccurate

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2078]
Server Auth
Shooter controller
Playables
Character controller movement entity

For MMO mode - if a warp is setup to warp players within the same map, players are sometimes not always warped to the correct location. This is normally for players with higher latency, but has happened to players with normal latency of around 60.

In big areas this isn't a big problem, but for smaller areas like dungeon corridors, players are not being teleported high enough above the ground and end up falling through it, OR they teleport the wrong side of the walls and end up falling to their deaths. 

I've also seen it where because a player has fallen a long distance, when I manually warp the player to me with GM commands, again they'll just be warped to me, but under floor and keep falling to their deaths on repeat. It normally takes 4 - 5 GM-command waprs before the player actually warps above the terrain.

On warp, could a forced loading screen be added, and then the playing character be destroyed and a new clone instantiated in it's place, at the warp location? Or would that be too much overhead?

Is there a way to suspend the player for a couple of seconds in the air after teleporting to avoid inaccuracy?

**Comment by insthync** [comment]
I don't get it.

**Comment by BJPickles** [comment]
For example Cube is the warp location. But players will spawn where the naked models are, rather than directly on the warp X, Y, Z of the cube.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/48354382/abfcd1e7-b6b4-4770-9389-df6b431f7a49)

**Comment by BJPickles** [comment]
You can see in this video I summon a player, and instead of teleporting on to me, he appears in the floor and falls, so had to summon again.

Sometimes I have to summon players 4 - 5 times before players actually appear on top of the terrain.

https://i.imgur.com/EGwX0A8.mp4

**Comment by insthync** [comment]
May you try help me to find proper way to find grounded position before move character?

**Comment by moepi2k** [comment]
Isnt it because you use colliding for player? Since the player is pushing away because they are at the same position, i had this problem also when ibused colliding for players

**Comment by BJPickles** [comment]
> On warp, could a forced loading screen be added, and then the playing character be destroyed and a new clone instantiated in it's place, at the warp location? Or would that be too much overhead?
> 
> Is there a way to suspend the player for a couple of seconds in the air after teleporting to avoid inaccuracy?

On warp, could a forced loading screen be added, and then the playing character be destroyed and a new clone instantiated in it's place, at the warp location? Or would that be too much overhead?

Is there a way to suspend the player for a couple of seconds in the air after teleporting to avoid inaccuracy?

> Isnt it because you use colliding for player? Since the player is pushing away because they are at the same position, i had this problem also when ibused colliding for players

Yeah, but also happens when using normal warp without any player being there. Also happens when using `/warp` etc.

**Comment by BJPickles** [comment]
Destroy playing character

Force loading screen

Create new clone at XYZ location.

Stop loading screen once new player clone is spawned.

**Comment by insthync** [comment]
If you use `RigidbodyEntityMovement`, then change it to `CharacterControllerEntityMovement`, or try to fix `RigidbodyEntityMovement` by yourself.
