### ISSUE TITLE
[Question]Run around the ranged enemy

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#2079]
https://www.youtube.com/watch?v=BOqimvM3eOU

If we run around a character with a ranged attack, they become invulnerable.
is there any way to prevent this?
It would be nice to do a follow-up attack on the targeted character

**Comment by insthync** [comment]
Do you want it to be 100% hitting?

**Comment by BarzoStrike** [comment]
if possible

**Comment by insthync** [comment]
How? homing missile?

**Comment by BarzoStrike** [comment]
https://www.youtube.com/watch?v=dGX-2T2s9-w

Homing missile would be perfect. I'm trying to do old-school mmorpg on mobile platform. It would be great for me if the missile followed the Target.

**Comment by juniormagalhaes** [comment]
Removes the cast time from the skills he will hit

**Comment by BarzoStrike** [comment]
there is only animation, no cast time

**Comment by insthync** [comment]
In 1.89 it will has a `HomingMissleDamageEntity` added, you can try to use it to make missile which will move follow target.
