### ISSUE TITLE
CPU usage excessive(?) with tiny numbers of connected clients

### ISSUE THREAD

**Issue by Zurigan** [suriyun-production/mmorpg-kit-docs#208]
CPU use for a map server process on a Digital Ocean $5 droplet is ~27% with the 3D demo project. 

Connecting one client bumps this to ~33%, each additional connection bumps it up another ~2%. This would effectively cap CCU in one area to ~30 players (haven't tested CPU load when spreading players out). 

The server lists the CPU as Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz. 

Is this rapidly increasing CPU load expected?

**Comment by Blunnyn** [comment]
Hi. could you run the server? Might you help me?

**Comment by 1isenok** [comment]
yes, you were not the only one to pay attention to the fact that a similar problem is present in MMO projects, at the initial stages it was hotly discussed in the Discord channel

**Comment by 1isenok** [comment]
on Dekstop PC core i7 it is maximum 3-4 CCU
