### ISSUE TITLE
(PAID REQUEST) Droppable Gold, EXP.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2080]
I would like to Add the option for the monsters/players to drop gold as a Item instead of simply adding gold automatically. Like in the game Diablo. Same thing for EXP. Selectable option in the scriptable object to Drop Gold/EXP item instead of simply automatically receiving them upon a kill. Add the option to automatically loot the item or that the players needs to walk on it to take it.

Im asking for a core change because this is a core mechanic that i cant really modify on my end without breaking the kit. @insthync

**Comment by juniormagalhaes** [comment]
Wouldn't it be simpler to create a type of item that gives gold and xp when you pick it up, and not put xp and gold in the monster settings?

**Comment by Eniotnacram** [comment]
I could make a custom item but I think this should be part of the kit as it is not really specific to my game. Let me know @insthync :)

**Comment by AsheshPlays** [comment]
Default Gold atleast should have an option to drop on ground. Then that way, we could create petskills for the looting of gold or items maybe.. like it has option what type or list of items that it can loot.

**Comment by insthync** [comment]
Done

**Comment by Eniotnacram** [comment]
> Done

Woa I did forgot about this, you'll always surprise me @insthync, thank you so much
