### ISSUE TITLE
Monster and Character Sound Distance 

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2082]
Is there a way to adjust the distance of the sound produced by characters and monsters? I tried adjusting audio sources to 5 meters but i can still hear the sounds from far distance. Or am i changing the wrong object.

**Comment by Eniotnacram** [comment]
not kit releated.. its in the audio source entirely

**Comment by Eniotnacram** [comment]
Make sure the audio source graph reach to 0 for X distance.

**Comment by insthync** [comment]
Hint: `Spatial Blend` + `3D Sound Settings`
