### ISSUE TITLE
Guild Storage

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#2084]
personal storage database records appear, but guild storage does not appear or I could not find it.
Also, the database is a bit difficult to read, I think it will be easier to follow if the names of the items are written next to the id.

**Comment by BarzoStrike** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/54517546/b4b42cdf-b632-43a8-89e9-13a8b2dcfe16)

I was misunderstood. There are items in the warehouse, but I couldn't see where in the database.

It is very difficult to read the database when their names do not appear. I thought it should be for the purpose of checking people's current items. Sometimes people say their items is lost, it's hard for me to find it in the database.
It's a big problem that it disrupts projects. I understand you.

**Comment by AsheshPlays** [comment]
@BarzoStrike 

Add item ids.

**Comment by BarzoStrike** [comment]
I will try
