### ISSUE TITLE
Mobile Frame Rate Gone 

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2085]
I just noticed that Frame Rate settings for client on Gameinstance is no longer there. Is it transferred to another section or it is removed? I only see server target frame rate.

**Comment by insthync** [comment]
Removed

**Comment by AsheshPlays** [comment]
ohhh.. welp, ill just have to find another way.. i was using it to adjust frame rates in mobile.. thanks for the response.
