### ISSUE TITLE
I am receiving an error when starting the multiplayer server.

### ISSUE THREAD

**Issue by suitechsoftware** [suriyun-production/mmorpg-kit-docs#2086]
Running Code: ./build.x86_64 -startCentralServer -startMapSpawnServer -startDatabaseServer
or 
nohup ./Build.x86_64 -startCentralServer -startMapSpawnServer -startDatabaseServer > /dev/null 2>&1&

Server: Ubuntu 20.4

<img width="1058" alt="error1" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/96ad7801-51f6-45c2-a249-6d9c6cc9d201">
<img width="1250" alt="error2" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/fba4b5ab-dbbd-4064-b9c4-ed8adf6e50c2">
<img width="1339" alt="error3" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/5381af7b-6df4-4b9f-bffc-47ef46273553">

Error Message: Cannot connect to the server

MySqlConfig.json:
<img width="680" alt="error5" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/bcd2b061-6df4-42dc-a0ec-66fbd55fec2b">

serverConfig.json:
<img width="536" alt="error6" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/dc3f1f19-2db7-4824-b273-c4e90481b301">

I'm using URP on my project

**Comment by suitechsoftware** [comment]
I'm using URP on my project

**Comment by insthync** [comment]
If all are shader errors, You can't ignore them, it won't use graphics for a headless server.

**Comment by AsheshPlays** [comment]
@suitechsoftware 
he means, if your errors are about shaders, just ignore it. it will be fine.

**Comment by suitechsoftware** [comment]
Okay but how can I ignore this because terminal directly killed.

**Comment by AsheshPlays** [comment]
@suitechsoftware do you have other errors?

**Comment by suitechsoftware** [comment]
There is no other error

**Comment by insthync** [comment]
Did you built it as server build?

**Comment by suitechsoftware** [comment]
![aaaaa](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/80ea6c32-2c2c-4cfb-a9a5-fb3104c60440)
Yes I did it

**Comment by insthync** [comment]
I don't know then, as I see the attached messages it is normal except the "Killed" one, don't know where it come from, did you try to find it?

**Comment by insthync** [comment]
You may try to create a new empty project which no content, no codes, and only has a one empty scene. Then try to run it on your server.

**Comment by Deepankar1993** [comment]
If you are getting the Error on the client when connecting to the server.
Then In your serverConfig.json try using your server IP instead of localhost. also for testing disable the firewall of the server
