### ISSUE TITLE
Per Scene Loading Screen

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2087]
Hello! Is it possible using the kit to have different loading screen depending on the scene or map it teleports to.

Like if a player teleport to map3, map3 loading screen will be the one that will show.

**Comment by Eniotnacram** [comment]
Tidy Map loading screen addons, it does exactly that and for free :)

**Comment by insthync** [comment]
![Screenshot_668](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/02ea1248-b262-4ae5-9554-469c4091bfbb)

**Comment by AsheshPlays** [comment]
@insthync THANK YOU!!
