### ISSUE TITLE
Input System on Mobile

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2088]
I have installed Input System on my project and I use "BOTH" on active input handling. The problem is, when i updated the client apk, some players cannot move but the buttons are working fine they said. The Joystick Mover moves, buttons can be pressed but nothing happens. But when i reverted to "OLD" input system, the problem is gone.
Is there a way to fix this or am i missing something?

**Comment by insthync** [comment]
![Screenshot_669](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/02db7237-9953-4a02-8132-b1e6722250dc)

Maybe this?

**Comment by AsheshPlays** [comment]
@insthync
I actually did that.. I followed your guide.. Same players that have problem also when i use "NEW" and "BOTH" Active handlings.

**Comment by insthync** [comment]
Only some players found this issues?

**Comment by AsheshPlays** [comment]
@insthync

12 players out of 35 testers

**Comment by insthync** [comment]
Fixed 1.83e
