### ISSUE TITLE
IO Exception with Log.txt

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#209]
Kit: 1.52c
Unity 2018.4.16f1 LTS
Windows 10 64-bit
Init_MMO, with Server Build checked.

I keep getting this IOException error pop up in the server window.  But it's somehow still being logged to the log.txt file.

 _-- Log Start: 2020-02-03 6:24:31 PM
(Exception) IOException: Sharing violation on path C:\Users\Hawka\AppData\LocalLow\DefaultCompany\VolitionMMO\log.txt_

**Comment by insthync** [comment]
Fix by this package.

[MMORPG_KIT-FixLogSavePathNotBeingSet.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4151498/MMORPG_KIT-FixLogSavePathNotBeingSet.zip)

**Comment by ben-roberts** [comment]
> Fix by this package.
> 
> [MMORPG_KIT-FixLogSavePathNotBeingSet.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4151498/MMORPG_KIT-FixLogSavePathNotBeingSet.zip)

The issue appears to be that every server instance logs to the same file, not that the log path isn't set.

**Comment by Hawkadium** [comment]
Appears to have fixed the issue!
