### ISSUE TITLE
What is Packet Version 

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2090]
This is my first few times changing packet versions. I wanted to know why some packet versions all players can connect and some cant. There are packet versions that few players can connect and sometimes lots cant connect. I am only changing it from 1 to 9. Does it have specific versions i have to follow? What is the logic behind it?

**Comment by insthync** [comment]
Logic is if client's packet version not equals to server's packet version, then server will refuse client connection.

**Comment by AsheshPlays** [comment]
@insthync
So i can put anything i want there? Like example: "G4XHH"?

**Comment by insthync** [comment]
No, it is a number.

**Comment by AsheshPlays** [comment]
Ok thanks. Much appreciated for tue answers.
