### ISSUE TITLE
Per Scene Loading from Bundle

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2091]
Hi! Is there away where I can insert short script before any specific scene start? So, i can load the scene from custom bundle. Example part of the script is below. Would it work if i add it on the Network Manager on Int Scene by the OnLoadSceneStart event? 

```
public async void LoadBundle() 
{
 {
Action asyncHandler = async () =>
            {
                await Ashesh.LoadSceneAsync("Map002", LoadSceneMode.Single, true, 100, (float progress, float reqSize, float totalSize) =>
                {
                    Debug.Log($"Progress: {progress}, ReqSize: {reqSize}, TotalSize: {totalSize}");
                });
            };
            asyncHandler?.Invoke();
 }
} 
```

**Comment by insthync** [comment]
You want to change default scene loading script to your scene loading script?

**Comment by AsheshPlays** [comment]
Only for loading scene from bundle. Like if my Addressable filename is Map005, it will load that scene from bundle if i warp or go to that map.

**Comment by AsheshPlays** [comment]
@insthync
i have no problems with init, home and first map.. problem starts on the next map.. it doesnt want to load from bundle. I am using YooAssets. Author told me to ask kit owner, means you, if there's a way.

**Comment by insthync** [comment]
What will happen if I don't want to answer you?

**Comment by AsheshPlays** [comment]
@insthync
Then I'll just accept and respect your answer sir.

**Comment by insthync** [comment]
The networked scene loading script is located in `LiteNetLibGameManager`, try to learn which Unity's script is used for scene loading then find it in the `LoadSceneRoutine` function and change to your load scene script.

**Comment by AsheshPlays** [comment]
@insthync

Thank you for the answer. Yes, i will study it. I just want to optimize as much as possible. Thanks for the tips.

**Comment by AsheshPlays** [comment]
Update on this:
I want to thank you @insthync for giving me tips in this.. I have finally succeeded in doing this system. Thanks so much! Now my scenes are loaded via bundles thru memory. Thanks!
