### ISSUE TITLE
Dismounting does not restore animations

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2092]
I updated the kit to version 1.83d2, and I noticed this behavior, I have no idea what it is, but it worked correctly before.

https://gyazo.com/1c0a8c803b678c3460f3ce0728cac51e

**Comment by insthync** [comment]
Don't know too, I want to try it, send me your AnyDesk address to my email: ittipon.bay@gmail.com

**Comment by juniormagalhaes** [comment]
sent

**Comment by insthync** [comment]
Don't use different character models, in your case, you use playable character model as a main animation player and use animator character model as a mount animation player.

**Comment by juniormagalhaes** [comment]
I had to answer a call while you were working, I didn't see exactly where you worked to solve it

**Comment by insthync** [comment]
![Screenshot_675](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/562f0f59-9cd7-4bca-83a4-7ff55753096b)

![Screenshot_676](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/b84c7664-d978-4734-9781-03e41db5a87e)

**Comment by juniormagalhaes** [comment]
thanks
