### ISSUE TITLE
Partial AnimationPlayableBehaviour

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2093]
AnimationPlayableBehaviour
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/5e191e6c-c59d-4a58-91ff-936490d6b80c)

Could this be Partial in kit, need it for some extentions i made

Thank you! <3

**Comment by insthync** [comment]
Added in 1.83e2

**Comment by Callepo** [comment]
@insthync 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/981d8b6d-359a-449d-9b77-f6a004094dc3)

Can this be unsealed? i need to override some methods in it which most of em are all Virtual/ Overrideable..
but the class is sealed so u cant do anything.

**Comment by insthync** [comment]
Did it in 1.83f

**Comment by Callepo** [comment]
@insthync

**Comment by insthync** [comment]
You can make any changes and then make a pull/merge request

**Comment by Callepo** [comment]
awesome cool!
