### ISSUE TITLE
Arrow Increase Damage Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2094]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/51fc5bd2-50b5-47d7-a2ad-68f63b9bbe52)

The increase Dmg option on Ammo Items, seem to only work in singleplayer.
ive build a mmo server for testing, the dmg is not applied, you do the base dmg only.

Ive tested it in default kit + my project, same thing happens.
Single player seems to work as intended, but for some reason, it doesnt in mmo
@insthync

**Comment by insthync** [comment]
I will delete that option

**Comment by Callepo** [comment]
> 

why ? is there any reason ? Im using it atm, i created a system where u can have different arrows for same weapon, with different effects. 

and the increase dmg was the last thing i need to work to be done.

**Comment by insthync** [comment]
Because it has many thing to do

**Comment by insthync** [comment]
That option currently works for bow's arrow which won't be stored in weapon, just decrease from inventory. If I am going to make it work with guns then I have to change `CharacterItem` -> `ammo` structure, have to store which kind of ammo and its remaining amount to make it use the proper kind of bullets.

**Comment by Callepo** [comment]
im not storing ammo in the weapons, my ammo's are equipped, and the dmg is applied in singleplayer fine, just for some reason not in mmo.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/acc07e2d-cb5b-4e5d-a212-4ad9050c5393)

**Comment by Callepo** [comment]
ill look into it and see how i can make it work for my situation then

**Comment by insthync** [comment]
`DefaultCharacterAttackComponent` -> `ApplyAttack` -> `Entity.DecreaseAmmos`

**Comment by Callepo** [comment]
> 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/77e71da3-5169-4dd3-be0d-7912ac05632e)
yup i know, i had to alter the method to decrease the ammo from the equip slot instead of inventory, and its applying the dmg and all

**Comment by insthync** [comment]
Hmm, I will check it

**Comment by Callepo** [comment]
@insthync 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/ae4427e5-fb57-4718-a5e7-7d09fe0ef0da)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/29be5869-4fc7-4472-b027-d511e507a857)

**Comment by Callepo** [comment]
THIS is MMO , Both Arrows Same Dmg
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/4660ef90-0e38-4193-a71d-79800f9bf779


This is Single
Explosive Arrow 1 hits all 20's
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/1e6f57a4-3479-44eb-90c3-32fcc0f91516

**Comment by insthync** [comment]
Fixed

**Comment by Callepo** [comment]
Awesome, what was the issue?

**Comment by insthync** [comment]
Hit register prepares damage amount but not be re-calculate again when decreasing ammo and increasing damage amounts by ammo.

**Comment by Callepo** [comment]
> 

ah, i see

**Comment by Callepo** [comment]
in Attack routine, the hit registration dmg was already applied and then later on in apply attack the extra dmg gets applied, i see it now. did u increase dmg before hit registration? or did u put hit registration inside Apply attack method?

**Comment by insthync** [comment]
I add a new function to increase damage amounts to hit registration manager

**Comment by Callepo** [comment]
@insthync Tested, works nicely, Thank you
