### ISSUE TITLE
Root Motion / Help Please!

### ISSUE THREAD

**Issue by joabekaul** [suriyun-production/mmorpg-kit-docs#2096]
Hello developer, I've been trying to use attacks using animation with root motion for two days, but my character executes them standing still without moving, as if there were no RM, could you help me? I'm using (Bake into Pose = disabled) / my character uses ( is kinematic = true) / motion secure (I've tried both options) / check the images below, but it doesn't work, could you help me? is there any remote support via anydesk something like that? :/

**Comment by joabekaul** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/114507343/09162ebb-c43c-4ea3-a6e3-6f559b7646ad)

**Comment by joabekaul** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/114507343/41bc82b5-e7c7-4c5c-9203-062940527c07)

**Comment by joabekaul** [comment]
Help please?

**Comment by insthync** [comment]
Did you try turn Root Transform Position (XZ) -> Bake Into Pose on?

**Comment by joabekaul** [comment]
yes dont work

**Comment by insthync** [comment]
Send me  your Anydesk address to my email: ittipon.bay@gmail.com

**Comment by joabekaul** [comment]
ok i go send

**Comment by insthync** [comment]
About root motion, your setup hierarchy is wrong,

your model root is inside transform, for example.
-- character entity
---- custom empty transform to store character
------ your character root transform
-------- your characer root bone
So when it won't move character properly

It should look like this

-- character entity
---- your character root transform
------ your characer root bone

Try using character entity creator tool to create your character entity

![Screenshot_680](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/1ec5dd58-89f7-40de-b076-063a342c96c0)

Just drag model file into this field and press create

![Screenshot_681](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/1c3c1875-0f82-4d9a-885b-e84c7e8b767f)

**Comment by insthync** [comment]
It is also has test repo: https://github.com/insthync/UnityMultiplayerARPG_TestRootMotion, you may download and extract to your project's Assets folder and see how it was setup

**Comment by joabekaul** [comment]
ok thank you I will explore more about this tool, and return the result ok?

**Comment by joabekaul** [comment]
thank you very much for now for your support, I will recommend your kit on the site
