### ISSUE TITLE
ROADMAP 2023.  

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#2097]
**Global Map.**

How many MMORPGs do you know that don't have a map? None? Why isn't it implemented?

**Character customization at creation.**

How many MMORPGs do you know where you can't change your character's hairstyle? 1 in 1000? Why is this implemented by third-party add-ons and not bundled in?  Those who don't need it are less than 1% of the total number of developers.

**Navigating quests.**

How many MMORPGs have you seen, in which when you take a quest is not shown where to go to fulfill it? Without marking it on the map? Why this is not implemented?

**Tired of watching how to fix minor bugs while there is not implemented ANY part of the functionality.**

**Comment by insthync** [comment]
Why you asking many why, it is very annoying. The answer maybe I don't have time.

1. Example please, if it can be done by UIs, I won't do it.
2. It is going to be done, next month.
3. I will sell it as addons.

**Comment by insthync** [comment]
The kind of people like you is a main reason why I stop creating any new assets and sell it. So don't ask about the Unreal one anymore, I won't do it.

**Comment by AhmedHon** [comment]
@Serivatech let suri alone man ! thank our god he is fixing bugs and make the asset alive ! if you dont like his work leave .. he is doing his best for this kit .. also he have his life like us .. he is not robot .

**Comment by AhmedHon** [comment]
@insthync bro , don't answer to this questions and live your life man ! we all thank you for all your hard work for this kit and trying to keep it alive <3 we all sorry for those questions

**Comment by Eniotnacram** [comment]
> **Global Map.**
> 
> How many MMORPGs do you know that don't have a map? None? Why isn't it implemented?
> 
> **Character customization at creation.**
> 
> How many MMORPGs do you know where you can't change your character's hairstyle? 1 in 1000? Why is this implemented by third-party add-ons and not bundled in? Those who don't need it are less than 1% of the total number of developers.
> 
> **Navigating quests.**
> 
> How many MMORPGs have you seen, in which when you take a quest is not shown where to go to fulfill it? Without marking it on the map? Why this is not implemented?
> 
> **Tired of watching how to fix minor bugs while there is not implemented ANY part of the functionality.**

Just quit man, we dont want people like you in this community.

**Comment by Serivatech** [comment]
Idiots! **Can't you understand that this is a translation?** When I ask or suggest something, it looks like I'm communicating with aliens. **In my language it looks polite and correct!** I don't understand why the fuck you don't like it!

I bought this asset, even though it's very strange for my country. I could get it for free -> https://unityassetcollection.com/mmorpg-kit-2d-3d-survival-free-download/ . Why did I pay? Because I wanted to support the developer. But what did I get? For 4 years I've been watching small bugs being fixed and as many new ones being added. Walking around in circles. Features that should be mandatory in any MMORPG were not implemented.

**Comment by moepi2k** [comment]
> Idiots! **Can't you understand that this is a translation?** When I ask or suggest something, it looks like I'm communicating with aliens. **In my language it looks polite and correct!** I don't understand why the fuck you don't like it!
> 
> I bought this asset, even though it's very strange for my country. I could get it for free -> https://unityassetcollection.com/mmorpg-kit-2d-3d-survival-free-download/ . Why did I pay? Because I wanted to support the developer. But what did I get? For 4 years I've been watching small bugs being fixed and as many new ones being added. Walking around in circles. Features that should be mandatory in any MMORPG were not implemented.

Are you stupid? When you own the asset for 4 year and think there are just few bug fix then its time to go. This asset growth over the last couple of year like no one other. And its a single developer behind. I saw u many times in discord and here how u talks to ppls. Thats also the reason why u got banne öd.in discord

**Comment by Serivatech** [comment]
In my language it looks polite and correct!

**Comment by moepi2k** [comment]
Even when it looks correct in ur langugage, it seems ur a strange guy. Posting illegal links where u can get piracy assets from unity... Lol

**Comment by khongtuong** [comment]
you buy this kit for 4 years but you didn’t see it grow because you blind or you didn’t join discord community, this github is open but i think need to close to license to access to avoid those looter

**Comment by Serivatech** [comment]
> Даже когда это выглядит правильно на твоем языке, он кажется тебе странным парнем. Размещение незаконных ссылок, где вы можете получить пиратские активы от единства ... LOL



> Even when it looks correct in ur langugage, it seems ur a strange guy. Posting illegal links where u can get piracy assets from unity... Lol

You're in for a big surprise! In our country, not only is there not even a fine for this, but the country's largest Internet provider provides all its subscribers with an official resource with pirated programs, movies and music ( https://mix.sibnet.ru/ ). This is the site of the state Internet provider RosTelecom ( https://en.wikipedia.org/wiki/Rostelecom )

**Comment by moepi2k** [comment]
@insthync u should close this thread, this dude post only shit

**Comment by Serivatech** [comment]
Go to hell, all of you. **All you do is unwarranted aggression!**

**Comment by Callepo** [comment]
> Go to hell, all of you. **All you do is unwarranted aggression!**

unwarrented? are u retarded? u have been for years and all u do is complain and talk shit and cant DO A SINGLE DAMN  THING.
YOU LITERALLY LEARNED NOTHING IN 3 YEARS ,CANT CODE, CANT MAKE A DAMN GAME. you piece of shit.. 
idk why u havent been blocked yet at all.. 

You want a map, MAKE IT.
You want char  customization, MAKE IT!

Stop bitching and do shit ur self u piece of shit

**Comment by Callepo** [comment]
@insthync This guy needs to be removed from discord and blocked from create post.

ALL HE EVER DOES IS START ISSUES AND DRAMA while he does literally nothing.. 

Oh i bought a unity asset MMO KIT,
MAKE ME AN UNREAL ENGINE KIT FOR FREE.


FUCK OFF
@Serivatech find a whole in bury urself vile piece of shit
