### ISSUE TITLE
NPC Save Respawn Point Dialog Bug

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2099]
Hello, The save respawn point confirm dialog and cancel dialog are buggy. They are not getting used. I made a normal dialog "SetRespawnPoint_Accept" for the Confirm Dialog but like in the video, it doesnt go to that dialog at all.
Npc placed directly on the scene and not using the NPC database.
Not using the Graph for the dialogs.
Video: https://medal.tv/games/requested/clips/1aHTJRphEWbiCH/d1337MxK3koy?invite=cr-MSxNd2QsNDQ3NDMxODYs

![Screenshot 2023-05-23 230514](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46734935/a5935291-76e4-46a9-872e-c6df732aa60a)

**Comment by insthync** [comment]
I will fix it, but I am not available yet, I will be back on 1st June.

**Comment by insthync** [comment]
Fixed in 1.83f
