### ISSUE TITLE
Display Weapon

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#21]
Hello, try to do quest, weapon is not visible in rewards:

![image](https://user-images.githubusercontent.com/48797909/55040987-a7050d80-5076-11e9-8694-002c1cbacb15.png)

![image](https://user-images.githubusercontent.com/48797909/55041002-b8e6b080-5076-11e9-8c9a-b4e02547e962.png)

**Comment by insthync** [comment]
Try set amount to 1

**Comment by 1isenok** [comment]
oh, thank you it is my mistake
