### ISSUE TITLE
Items lost after removing from player storage (bank)

### ISSUE THREAD

**Issue by ben-roberts** [suriyun-production/mmorpg-kit-docs#210]
If you remove an item from your bank then log out, on login the item will have vanished from inventory.

This also happens if you move an item from storage to inventory then use a map portal.  

In both cases, the item doesn't reappear in player storage, appears to be lost forever. 

Unity 2019.3.0f6, 1.52c kit, demo 3D project, MMO build on Linux server with MySQL DB.

**Comment by insthync** [comment]
Oh, This is a big problem, I will fix it now.

**Comment by insthync** [comment]
You can fix it by your self like as [commit](https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/e6b5d0a6b707f3b6a9fb9a740df35d118a6a850d)

I will upload new version next week.

**Comment by insthync** [comment]
This was fixed in 1.53. If this issue still occurs, you can reopen this issue post.
