### ISSUE TITLE
Left and right item total damage.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2100]
Hello, I want it to hit the sum of the right and left item damage. Currently it only hits the item damage in the right or left hand, I want it to hit the sum of both when I have the same weapon in both hands, how can I do this?

**Comment by insthync** [comment]
May try to set damage in `increaseDamages` instead of `damageAmount`

**Comment by CLAXES** [comment]
Ok working thanks.
