### ISSUE TITLE
Skinned Mesh Render Equipment

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2101]
There has been an issue with equipping gear thats Skinned mesh renderer for a long time, which made alot of people resort to using The instantiated version of equipping of the kit, where they would Create 1 massive prefab and just turn parts on and off.. 

But thats exactly the issue, Prefabs become massive.. with over 200 armor etc.

Ive shared this code a while ago in the discord for people who wanna use normal way..
its fixes the issue of equipping of the new skinnedmesh model. Ive tested this with Infinity PBR Models, Polytope Models, Blinks, And more.. It seems to work for all.

This is the issue, u can see the first part is the default kit equip code, and 2nd part i override the New model method with my method for rebasing bones.

https://youtu.be/P7g1GXsskyw
=======================
//Code

public override void AddingNewModel(EquipmentModel data, GameObject newModel, EquipmentContainer equipmentContainer)
        {
            if (data.doNotUseEntityBones)
                return;
            //Equipping Model
            SkinnedMeshRenderer newSkinnedMesh = newModel.GetComponentInChildren<SkinnedMeshRenderer>();
            if (newSkinnedMesh != null && skinnedMeshRenderer != null)
            {
                //Model Bones
                Dictionary<string, Transform> boneMap = new Dictionary<string, Transform>();
                //Base Model to get Bones from
                SkinnedMeshRenderer baseSkinnedMeshRenderer = skinnedMeshRenderer;

                if (newSkinnedMesh != null)
                    if (equipmentContainer.defaultModel != null)
                    {
                        if (equipmentContainer.defaultModel.GetComponent<SkinnedMeshRenderer>() != null)
                            baseSkinnedMeshRenderer = equipmentContainer.defaultModel.GetComponent<SkinnedMeshRenderer>();
                    }

                if (baseSkinnedMeshRenderer != null)
                {
                    foreach (Transform bone in baseSkinnedMeshRenderer.rootBone.GetComponentsInChildren<Transform>())
                    {
                        if (bone != null)
                            boneMap[bone.gameObject.name] = bone;
                    }

                    Transform[] newBones = new Transform[newSkinnedMesh.bones.Length];
                    for (int i = 0; i < newSkinnedMesh.bones.Length; ++i)
                    {
                        GameObject bone = newSkinnedMesh.bones[i].gameObject;
                        if (!boneMap.TryGetValue(bone.name, out newBones[i]))
                        {
                            Transform[] children = skinnedMeshRenderer.rootBone.GetComponentsInChildren<Transform>();
                            foreach (Transform child in children)
                            {
                                if (child.name == bone.name)
                                {
                                    newBones[i] = child;
                                    continue;
                                }
                            }
                            Debug.Log("Unable to map bone \"" + bone.name + "\" to target " + data.equipPosition);
                        }
                    }
                    newSkinnedMesh.bones = newBones;
                }
            }
        }
`

**Comment by Callepo** [comment]
`        public override void AddingNewModel(EquipmentModel data, GameObject newModel, EquipmentContainer equipmentContainer)
        {
            if (data.doNotUseEntityBones)
                return;
            //Equipping Model
            SkinnedMeshRenderer newSkinnedMesh = newModel.GetComponentInChildren<SkinnedMeshRenderer>();
            //Model Bones
            Dictionary<string, Transform> boneMap = new Dictionary<string, Transform>();
            //Base Model to get Bones from
            SkinnedMeshRenderer baseSkinnedMeshRenderer = skinnedMeshRenderer;

            if (newSkinnedMesh != null)
                if (equipmentContainer.defaultModel != null)
                {
                    if (equipmentContainer.defaultModel.GetComponent<SkinnedMeshRenderer>() != null)
                        baseSkinnedMeshRenderer = equipmentContainer.defaultModel.GetComponent<SkinnedMeshRenderer>();
                }

            if (baseSkinnedMeshRenderer != null)
            {
                foreach (Transform bone in baseSkinnedMeshRenderer.rootBone.GetComponentsInChildren<Transform>())
                {
                    if (bone != null)
                        boneMap[bone.gameObject.name] = bone;
                }


                Transform[] newBones = new Transform[newSkinnedMesh.bones.Length];
                for (int i = 0; i < newSkinnedMesh.bones.Length; ++i)
                {
                    GameObject bone = newSkinnedMesh.bones[i].gameObject;
                    if (!boneMap.TryGetValue(bone.name, out newBones[i]))
                    {
                        Transform[] children = skinnedMeshRenderer.rootBone.GetComponentsInChildren<Transform>();
                        foreach (Transform child in children)
                        {
                            if (child.name == bone.name)
                            {
                                newBones[i] = child;
                                continue;
                            }
                        }
                        Debug.Log("Unable to map bone \"" + bone.name + "\" to target " + data.equipPosition);
                    }
                }
                newSkinnedMesh.bones = newBones;
            }
        }`

**Comment by Callepo** [comment]
@insthync Idk why the i cant put the full code in the code area 
but here. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/9c051b5f-7e09-4a7f-a0c8-89c15b99b327)
=== Start======
public override void AddingNewModel(EquipmentModel data, GameObject newModel, EquipmentContainer equipmentContainer)
        {
            if (data.doNotUseEntityBones)
                return;
            //Equipping Model
            SkinnedMeshRenderer newSkinnedMesh = newModel.GetComponentInChildren<SkinnedMeshRenderer>();
            //Model Bones
            Dictionary<string, Transform> boneMap = new Dictionary<string, Transform>();
            //Base Model to get Bones from
            SkinnedMeshRenderer baseSkinnedMeshRenderer = skinnedMeshRenderer;

            if (newSkinnedMesh != null)
                if (equipmentContainer.defaultModel != null)
                {
                    if (equipmentContainer.defaultModel.GetComponent<SkinnedMeshRenderer>() != null)
                        baseSkinnedMeshRenderer = equipmentContainer.defaultModel.GetComponent<SkinnedMeshRenderer>();
                }

            if (baseSkinnedMeshRenderer != null)
            {
                foreach (Transform bone in baseSkinnedMeshRenderer.rootBone.GetComponentsInChildren<Transform>())
                {
                    if (bone != null)
                        boneMap[bone.gameObject.name] = bone;
                }

                Transform[] newBones = new Transform[newSkinnedMesh.bones.Length];
                for (int i = 0; i < newSkinnedMesh.bones.Length; ++i)
                {
                    GameObject bone = newSkinnedMesh.bones[i].gameObject;
                    if (!boneMap.TryGetValue(bone.name, out newBones[i]))
                    {
                        Transform[] children = skinnedMeshRenderer.rootBone.GetComponentsInChildren<Transform>();
                        foreach (Transform child in children)
                        {
                            if (child.name == bone.name)
                            {
                                newBones[i] = child;
                                continue;
                            }
                        }
                        Debug.Log("Unable to map bone \"" + bone.name + "\" to target " + data.equipPosition);
                    }
                }
                newSkinnedMesh.bones = newBones;
            }
        }
        
        ====End=======

**Comment by insthync** [comment]
Thank you, I will apply it, but I am not available yet, I will be back on 1st June.

**Comment by Callepo** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/5e5492d7-61e5-4736-8ba5-f16e8113993d)
This is never true also.. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/b13c6e45-70a2-4128-b4fa-8a09afeb77ac)

Cuase this line was never added. its missing from kit, so items ALWAYS use skinned mesh

**Comment by insthync** [comment]
Implemented, https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/163-equipment-bones-setup-manager

**Comment by Callepo** [comment]
thank you, nicely done!

**Comment by Callepo** [comment]
@insthync idk why but the For loop u have doesnt work..i replace it with my  old Foreach  and it works
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/db2be8f0-047a-452b-b803-46cf20420b94)
Scriptname: EquipmentModelBonesSetupByBoneNamesManager


EquipmentModelBonesSetupByBoneNamesManager
This is my foreach..

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/a55e18f3-e426-45c6-910b-603026354dc9)

this is ur For loop.

**Comment by insthync** [comment]
Okay, I will apply yours
