### ISSUE TITLE
[Bug] guild warehouse

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#2102]
My user tells me that the items are lost after being deposited to the warehouse, when withdrawing. He then says that his items have changed to another item[Dupe]. server error log

ERROR DatabaseNetworkManager [2023-05-24 07:27:02] - Cannot UpdateStorageItemsAsync status: Error
ERROR No Tag [2023-05-24 07:27:02] - Unable to update storage items when move item to storage
ERROR DatabaseNetworkManager [2023-05-24 07:27:07] - Cannot UpdateStorageItemsAsync status: Error
ERROR No Tag [2023-05-24 07:27:07] - Unable to update storage items when move item to storage
ERROR DatabaseNetworkManager [2023-05-24 07:28:07] - Cannot UpdateStorageItemsAsync status: Error
ERROR No Tag [2023-05-24 07:28:07] - Unable to update storage items when move item from storage
ERROR DatabaseNetworkManager [2023-05-24 07:29:09] - Cannot UpdateStorageItemsAsync status: Error
ERROR No Tag [2023-05-24 07:29:09] - Unable to update storage items when move item from storage

**Comment by insthync** [comment]
That error usually can be occurring when there are many guild members using storage at the same time to prevent item changing or duplicating issues, are you sure that the item is changing or duplicating?, do you have any video clip which shows the issues?

You can help me find the issues in `DatabaseNetworkManager_RequestHandlers` -> `UpdateStorageItems` function.

Note that items in storage may not be updated when other player moves items.

**Comment by BarzoStrike** [comment]
There are these errors, I don't understand exactly what it is, but I would appreciate it if you could explain a little. I'll get back to you if I have more information about the item being lost.

ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 10:58:37] - User trying to hack?: cPDdvE78yRMU3B6c, connection already registered.
ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 11:16:26] - User trying to hack?: cPDdvE78yRMU3B6c, connection already registered.
ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 11:16:28] - User trying to hack?: cPDdvE78yRMU3B6c, connection already registered.
ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 11:16:45] - User trying to hack?: cPDdvE78yRMU3B6c, connection already registered.
ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 11:16:48] - System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at MultiplayerARPG.MMO.MapNetworkManager.OnPeerDisconnected (System.Int64 connectionId, LiteNetLib.DisconnectReason reason, System.Net.Sockets.SocketError socketError) [0x0022c] in <fb10ae01685d49f88bc816e26385e619>:0 
ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 11:19:13] - User trying to hack?: cPDdvE78yRMU3B6c, connection already registered.
ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 11:19:18] - System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at MultiplayerARPG.MMO.MapNetworkManager.OnPeerDisconnected (System.Int64 connectionId, LiteNetLib.DisconnectReason reason, System.Net.Sockets.SocketError socketError) [0x0022c] in <fb10ae01685d49f88bc816e26385e619>:0 
ERROR MapNetworkManager(MapNetworkManager) [2023-05-24 11:26:58] - User trying to hack?: cPDdvE78yRMU3B6c, connection already registered.

**Comment by insthync** [comment]
You should create a new post, don't talk about differences issues in 1 post, it is confusing.

**Comment by insthync** [comment]
Did you ever try find "User trying to hack?" ?, if you did it, you will find where is the problem can be occured.

**Comment by BarzoStrike** [comment]
The user who reported the problem to me, maybe the problem is common. I don't know.

"Did you ever try find "User trying to hack?" ?, if you did it, you will find where is the problem can be occured"
How can I do this.

**Comment by insthync** [comment]
Just find the codes in visual studio.

**Comment by insthync** [comment]
So don't do anything, "User trying to hack?" can be ignored, it is not cause of storage issues. What you can do is make sure that the item is really lost. Will be better if you can capture video when it is losing.

**Comment by BarzoStrike** [comment]
I understand. If I find the source of the problem, I will take a video.
