### ISSUE TITLE
[issues] Damage Area error when importing new version

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#2104]
When importing to the new version of the kit following the whole step by step, I try to run the project and not even the HUD appears and it presents an area Damage error, I tried to check all the area skills and not leave any area null but the error continues using an empty database
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/c490ef37-6416-4043-b396-8cfc8d3b7d34)

**Comment by insthync** [comment]
Try to do following whats the log messages told you.

**Comment by insthync** [comment]
I will check it, but I am not available yet, I will be back on 1st June

**Comment by RafaelRBizachi** [comment]
No problem, when you have it available and manage to help me with the solution, take a look, I tried to follow what the errors said to try to find some prefab without reference to Area Damage but the error does not signal any
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/00120beb-a570-4935-97b5-cdd54381e6a4)

**Comment by RafaelRBizachi** [comment]
Creating a new project with the kit does not show any error, only in my main project it showed after updating following the usual step by step

**Comment by RafaelRBizachi** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/9abb4089-0c99-4cf6-8e5d-9817e2e75183)

**Comment by RafaelRBizachi** [comment]
Solved, a single skill that I stopped looking at was missing a reference to the area damage and broke the entire project
