### ISSUE TITLE
Abnormal playback speed of Moveing animation

### ISSUE THREAD

**Issue by 15291358689** [suriyun-production/mmorpg-kit-docs#2105]
AnimatorCharacterModel
![1685120695014](https://github.com/suriyun-production/mmorpg-kit-docs/assets/63120220/504a4968-3d1c-4f9d-b9a5-c8b34af96272)

The two clips are the same, but the animation playback speed is slow when moving

**Comment by insthync** [comment]
It might be because of character's move speed stats
