### ISSUE TITLE
Raycast weapons are not hitting their targets in MMO mode (v 1.83e2)

### ISSUE THREAD

**Issue by TheRealKeith** [suriyun-production/mmorpg-kit-docs#2106]
Raycast weapons are not hitting their targets in MMO mode. They work fine in single player mode. I am running the latest version and did see in the change log that this was fixed, but I do not think it was. Melee damage works fine.

![Unity_CWo4fFMBZc](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56834121/df3c593b-aaf0-4c65-a5ec-bd4ebd331d1b)

**Comment by insthync** [comment]
I will check it, but I am not available yet, I will be back on 1st June
