### ISSUE TITLE
Guildwar

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2107]
i followed the documentation for creating a guildwar
i made a mob which has GuildwarCastleHeart, the guildwarmap is GuildwarMapInfo
the settings is 60 mins of war 10am to 11am

i am using MySql

i get this message

```
InvalidOperationException: Insecure connection not allowed
  at (wrapper managed-to-native) UnityEngine.Networking.UnityWebRequest.BeginWebRequest(UnityEngine.Networking.UnityWebRequest)
  at UnityEngine.Networking.UnityWebRequest.SendWebRequest () [0x00001] in <a113f93abd7d4c4c8ef3fd7be147e507>:0
  at UnityRestClient.RestClient.Get (System.String url, System.String authorizationToken) [0x000c7] in <41e24e620745408b80cb5cc43c777afe>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityRestClient.<Get>d__47:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<Get>d__47&)
UnityRestClient.RestClient:Get(String, String)
UnityRestClient.<Get>d__31`1:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<Get>d__31`1&)
UnityRestClient.RestClient:Get(String, Dictionary`2, String)
MultiplayerARPG.GuildWar.GuildWarRestClient:GetOccupy(String)
MultiplayerARPG.<Update_GuildWar>d__280:MoveNext()
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<Update_GuildWar>d__280&)
MultiplayerARPG.BaseGameNetworkManager:Update_GuildWar()

```
so how can i enable the guild war properly?

**Comment by insthync** [comment]
Did you setup ssl for its web service?

**Comment by chumleader** [comment]
i didn't, i just followed the documentation

**Comment by insthync** [comment]
Did you setup this ? https://github.com/insthync/mmorpg-kit-guild-war-service

**Comment by chumleader** [comment]
i didn't setup that as i only followed the documentation about guildwar, i am trying to set that up now

**Comment by insthync** [comment]
Then how is ot not working?, Or you just saw that and you think it is not working?

**Comment by chumleader** [comment]
i ran the service all is working the api is listening but when the guildwar starts in the designated time i still get the error i posted
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/17646440/613dbe8c-cad5-4afc-8139-58da37a5dd51)

**Comment by insthync** [comment]
Did you tried googling : Insecure connection not allowed ?

**Comment by chumleader** [comment]
i'm not trying to be spoonfeed, i always accept direct answer.
But documentations and instructions from the said service is incomplete, i googled it and found out that it does not accept insucure connection(http) on my api, thank you for helping and i am sorry for taking your time
