### ISSUE TITLE
Item Dupe for player storage 1.83v

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2108]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/653ee419-a879-4335-ab3c-c2f40ea1ec3d

**Comment by temelkirci** [comment]
![Ekran görüntüsü 2023-05-27 141005](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/7b934811-1ce4-4745-bd14-515db5d4277d)

**Comment by insthync** [comment]
I don't trust you yet, you always use old version
