### ISSUE TITLE
Monster and Player Level Gap

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2109]
I went through most of the settings available, I say most because I am not sure if maybe I missed something or it is not available. But I am looking if there is a setting that will set a level gap between the player and the monster, like if the player is like 10 levels above the monster, it wont received anymore exp. This is to prevent players staying on the same spot eventhough they are many levels beyond the monster. I am porting a game and i followed the drop rates, exp per mobs of the original. But since players still get exp, they tend to stay on lower level monsters for easy progression.

**Comment by insthync** [comment]
Yep, it has no option for that, but if I remember correctly, you can modify game play rule code -> reward exp to do it
