### ISSUE TITLE
Quest.cs / UIQuestTask.cs CORE modification

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2110]
It would be really usefull if you could make the QuestTask a partial. (Will help me adding more functionnality to the quests without modifying the core).
    
![Screenshot 2023-05-27 125553](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46734935/289f7b2e-641e-4e01-bd27-4c4b3eb84b22)

**Comment by insthync** [comment]
Custom quest task is not enough?

**Comment by Eniotnacram** [comment]
Could be, but really complicated for what im doing. I did create a custom task description for my quests. To talk to NPC is not necessarly Talk to Santa Claus. The task description would be (You need to find Santa claus in the city). But to make that work, I really need the QuestTask to be partial.
![Screenshot 2023-05-27 155840](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46734935/3ec2ef9b-e45d-48b5-880d-360d6c1aa965)

**Comment by Eniotnacram** [comment]
If you dont want or cannot make the quest task partial, I would agree if you want to add this "addon" to the core by sending you my 2 simple scripts. (if you are whilling). The addon is working with the built in LanguageManager and working flawlessly with the kit and i think it would be usefull to anyone as it is essentialto have custom task names without created a completly new quest task.

**Comment by Eniotnacram** [comment]
This is what my Modification looks like in Quest.cs:
Only modified the public struct QuestTask: https://pastebin.com/u0BDaCks
You can see the modifications after the comment //Added fields at the end.

And those are the modification to UIQuestTask.cs:
Again the modification are at the end after the comment //Added fields
https://pastebin.com/ZH6c1XyS

**Comment by Eniotnacram** [comment]
So yea, with a lots and lots of tries, the best way to add Custom Task Description is with those CORE modifications: (My Modifications are after the comment "//Added fields")
https://pastebin.com/u0BDaCks
https://pastebin.com/ZH6c1XyS

Making QuestTask Partial in Quest.cs is not a good idea as we still receive warnings if we are using the partial as it is a struct.

I think those modifications could benifits anyone with the kit, as it is really usefull to have Custom Tasks Description for every quests(tasks). So the best thing to do (I suggest), is to add those modifications to the core. So every one could benifits from that and I will not need to keep track of this CORE modification. @insthync

**Comment by juniormagalhaes** [comment]
This function would help a lot to do the quests, I also have the same situation, which you can solve just by changing the name of the task.

**Comment by insthync** [comment]
Implemented [in 1.83f](https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/164-custom-quest-task-description)

Thank you

**Comment by Eniotnacram** [comment]
0 problems with the upgrade for me, working as intended and perfectly! Thank you for accepting and implementing it @insthync :)

**Comment by juniormagalhaes** [comment]
you can even put the variables, it was very cool

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/6624862b-8970-4806-87e4-3745b9ffb77c)
