### ISSUE TITLE
PVP mode issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2111]
If u have a client build with pvp mode off, but Server is pvp mode On.. 
The client with pvp mode off cant attack anyone.. its doing client side checks, even tho the server has it enabled,

So its not doing it through server, even if the dmg is applies with pvp on on server, the enemy takes no dmg.. 

i also tried turning pvp off on server, and ON on the clients, the client can target the enemy, but there is no dmg applied.. 
This is good!, Cuase server had pvp off, so it shouldnt do dmg..

But if server is ON, clients should be able to do dmg, regardless if what it says.

**Comment by Callepo** [comment]
Is this whats going on ? with the client/ server pvp hit

i think clients register the damage, and then sends to server as "Hit" and server checks if true. and if was true, u take dmg..
so thats why when client pvp is off, there is no registering of "Hit" so it never tells server and server never checks..

And the same if client pvp is On and server is Off, Client sends "Hit" to server and server checks and be like , well cant be cuase pvp is off
its prolly part of the hit improvements shits
so if i see dmg lands on my client, it actually hits
and also u cant spoof it, cuase server checks the location and time of dmg etc to verify it all

**Comment by Callepo** [comment]
@insthync 
Unrelated to the pvp. 
Ui slider, Why are they not Rate same as Image slider value?
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/30e96a2e-3ef1-4871-a76e-30c41891e0b0)

this makes alot of stuff not work cuase most hp/ mana / slider/ globes , custom images go from 0 to 1 and uses Rate..
But rate is used for the images, but not slider.. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/26530aae-2388-496f-a15f-66a227ddd824)

this would simply be more streamlined. i dont see the benefit of having it different then the other slider image

**Comment by insthync** [comment]
Fixed in 1.83g2
