### ISSUE TITLE
[Bug] Pets attacking monsters even though they are not aggressive

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#2112]
All my pet items when summoned are attacking neutral monsters even though they are not aggressive
I made no changes to monster activity.cs and re-imported the new update 3 times but they keep doing this
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/03305c3e-759e-443c-8cfc-c3dcfdef48c0)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/356ee70c-14aa-4306-8294-3e13748c916d)

**Comment by RafaelRBizachi** [comment]
https://youtu.be/gZjZJVxvM-s

**Comment by RafaelRBizachi** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/d2136fd9-1649-47bd-a7bb-f5a240b10c3c)

**Comment by insthync** [comment]
Fixed in 1.83f
