### ISSUE TITLE
Item disappear bug

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2114]
Hello,

I'm having a really wierd bug with my items. They are globally most of the time working perfectly fine.  But in the editor and also when my game is built, sometimes, the item just disappear. Sometimes the item is still equipped and I still see it on my character but in the UI (Equip Item slot) the item is not there. Sometimes when im dragging the item to equip it its not equipping it, but when i click on the item and click "Equip" it works. So yea it is very inconsistent and im very confused why.

When creating a new character the items works, but sometimes (very rare) the item was buggy directly after the character creation.

There is a video: https://medal.tv/games/requested/clips/1bowkDNHs4lvQD/d1337lVHaKud?invite=cr-MSwyajYsNDQ3NDMxODYs

**Comment by RafaelRBizachi** [comment]
by default the game has 2 weapon slots, if you only disabled the second slot in the inspector it could be what is causing it and your wand is going to the second slot, in my game I also only have 1 weapon slot and it appears to be normal

**Comment by Eniotnacram** [comment]
> by default the game has 2 weapon slots, if you only disabled the second slot in the inspector it could be what is causing it and your wand is going to the second slot, in my game I also only have 1 weapon slot and it appears to be normal

Thanks for the info! So an option would be maybe to add the ability to disable the second weapon slot? @insthync 

When the item disappear I'll check in the scenes view if the second slot is populated.

**Comment by RafaelRBizachi** [comment]
try this, it removes the second slot from your gameplay screen because you haven't configured another slot in your player
![Sem título4](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/9f0a7ac7-f3e4-4c69-af29-4507837b8d11)

**Comment by Eniotnacram** [comment]
> try this, it removes the second slot from your gameplay screen because you haven't configured another slot in your player ![Sem título4](https://user-images.githubusercontent.com/106054872/241789653-9f0a7ac7-f3e4-4c69-af29-4507837b8d11.png)

So you are telling me that I should have a second slot but simply disable it? Currently for me. "The Left Hand Slot" is empty in my "UI Equip Items" script.

**Comment by RafaelRBizachi** [comment]
try putting right slot on left slot to force the item to appear and disable alternate slots
![Sem título](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/1ad14bb0-144b-4b91-886f-95dca66293a3)

**Comment by Eniotnacram** [comment]
Will try this thank you :)

**Comment by Eniotnacram** [comment]
Not working with the same slot for both equipement hands. Getting an error that I cant put the item to that slot. Rand hand only blablabla

**Comment by moepi2k** [comment]
Ur serup is just wrong. And i think u messed ur ui. The slot you have in videoo is slot from set 2 not 1

**Comment by Eniotnacram** [comment]
> Ur serup is just wrong. And i think u messed ur ui. The slot you have in videoo is slot from set 2 not 1

I dont think it is. And if it would, why when I create a new character it works? If it would be the wrong slot. It would always to go that wrong slot and not be visible.  As the sreenshot, I only have ! weapon slots using the Set Index (0)

**Comment by moepi2k** [comment]
Because when create character it goes in slot 1. So when u have now the wrong weapon slot in inventory and equip weapon by drag and drop. It goes to slot 2. When equip by button it goes to slot1. Def an issue on ur side. There is no bug

**Comment by moepi2k** [comment]
i dont talk about off hand it talk about weapon set.

**Comment by Eniotnacram** [comment]
> i dont talk about off hand it talk about weapon set.

Not sure to understand then. I got only one weapon set (0) as the screenshot on top. Note that the equipping and desequip works perfecly fine 98% of the time. But for an unknown reason, suddently its stops working and the item disapear like in the video. Its an intermittent "problem"

**Comment by Eniotnacram** [comment]
There is another video that will show the bug in real time! : https://medal.tv/games/requested/clips/1crU06y7xve9Zk/d1337FM5ZmZw?invite=cr-MSxlZ20sNDQ3NDMxODYs

You can see, in the begining of the video, my character as the wand equipped. And I was able to do the fireball skill (required to have a wand) But you can see that when i try to launch the second fireball, my item just disapeared from my hand. And I was not able to do the fireball skill anymore. And atfer that, dragging in or out the item does nothing. If clicking on the item and pressing equip, the item is getting equipped and the item is (working). But it disapear and i cannot unequip it anymore.

@insthync @moepi2k

**Comment by moepi2k** [comment]
Like already said, im def sure u messed something in ur ui.   Never seen that bug and i work for over 2 years with the kit. If you face an issue u should always test fresh kit to. And only when u can reproduce it there too u can make sure its not an issue on ur sidd

**Comment by Eniotnacram** [comment]
> Like already said, im def sure u messed something in ur ui. Never seen that bug and i work for over 2 years with the kit. If you face an issue u should always test fresh kit to. And only when u can reproduce it there too u can make sure its not an issue on ur sidd

I reviewed my UI over and over again, it's pretty straight forward and hard to "fuck it up". As it is a intermittent bug, it is also really hard to reproduce in a fresh kit. 

How can it be a UI problem, you clearly see that im litterally fighting with the wand , and for no reason, suddenly, it disappeared.

**Comment by Eniotnacram** [comment]
> Because you cant reproduce it on fresh kot, and i never had that bug or saw someone in the community had.

Maybe because I'm only using a single item slot? Right hand ? And this bug happens if left hand is empty?

**Comment by insthync** [comment]
Try set weapon type's equip type to two hand or set dual wield restriction to off hand restricted.

**Comment by insthync** [comment]
Or send me your AnyDesk info to my email: ittipon.bay@gmail.com to use your device to check it.

**Comment by Eniotnacram** [comment]
> Try set weapon type's equip type to two hand or set dual wield restriction to off hand restricted.

Will try those and let you know! As it is an intermittent "problem" I cannot confirm or not if it's working but will tell you if the problem still occur with those changes and if it does I will send you my Anydesk. @insthync 

Thank you

**Comment by Eniotnacram** [comment]
After hours of gameplay, even with the leftHandSlot not empty (using a disabled gameobject) and the right weapon type settings you suggest.

Ive sent you my anydesk info.

I'm sorry for bothering you with this.

**Comment by Eniotnacram** [comment]
Big love suri!

Thank you, and sorry for that newby mistake from me.
