### ISSUE TITLE
Problem: After entering the map

### ISSUE THREAD

**Issue by 15291358689** [suriyun-production/mmorpg-kit-docs#2117]
![1685441595473](https://github.com/suriyun-production/mmorpg-kit-docs/assets/63120220/752d5540-c2c8-4408-8b79-c48cacf01216)
After entering the map, there are many objects in the red box. Here are some screenshots that I have deleted. Is this normal. If it's normal, please tell me which script created it and I want to give them a parent.

**Comment by moepi2k** [comment]
this is normal. its from the pooling system
