### ISSUE TITLE
Damage Calculation w/ Effectiveness Attributes

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#2118]
I have noticed that using some skills or weapons if the damage example is 11 this will hit 10. This happens when using Effectiveness Attributes

https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/633ec17e-0bb6-400f-905d-becdd5f6b8e4

**Comment by insthync** [comment]
Always `1` ?

**Comment by Blunnyn** [comment]
Yes, it's always 1 more

I think it is due to the amount of the attribute itself, for example for the weapon it scales with 0.1 of the attribute
in that attribute I have 729 and the blow is 172 when it indicates that it should be 173
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/c3c72cf0-1c4d-4292-b63b-14b9ea664f41)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/726dab78-ed69-44da-89d9-c204e0bedf02)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/d4024e7b-248a-40a1-8d25-f23c653566e8)


But here I have 730 of the attribute and the hit is 173 as indicated

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/e079839f-2129-404d-9395-58a4b6825aaa)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/4aeeeb2a-0ec7-47f9-b42e-54872767c7cc)

**Comment by insthync** [comment]
Fixed in 1.83f

**Comment by Blunnyn** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/9132efca-715b-4263-8ba6-c3f6f46eda27)

I'm using 1.83g2 but the hit is still higher than indicated.

**Comment by insthync** [comment]
I don't want to fix it because it is just a wrong float calculating and it won't over `1`, just `1` why is that so important?, if you want to fix it then you may try made changes to `DefaultGameplayRule` -> `GetTotalDamage` function

**Comment by insthync** [comment]
Or make changes to the UI codes
