### ISSUE TITLE
Damage Transforms

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2119]
Would this idea work? Or how do i make my hitboxes better? Because there are time arrows dont deal damage but it doesnt say 0 damage or it doesnt register.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/f81463bf-d21f-4d9d-942d-063c688e483b)

**Comment by Deepankar1993** [comment]
Damage issues with missile skills seem to only affect MMO mode at least for me

**Comment by insthync** [comment]
I don't get what you are going to tell me.

**Comment by AsheshPlays** [comment]
@insthync 
I made a gameobject with a collider then added the gameobject on Damage Transform. Will this improve the hitbox?

**Comment by insthync** [comment]
No, you have to understand that the damage transform is where the damage entities instantiated and launch (origin for melee sphere cast, origin for missile damage entity), it is not related to the hitboxes at all. And that collider will do nothing but it can intercept missile entity movement.

If you want to setup your hitbox, you must attach `DamageableHitBox` component.

**Comment by AsheshPlays** [comment]
@insthync 

Ohh.. Can i use the DamageableHitBox component to create a bigger hitbox? because I also have problem that when the monster turns back, the damage does not register.

**Comment by insthync** [comment]
Yes

**Comment by AsheshPlays** [comment]
@insthync
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/2003057e-30fb-4de7-a879-6cc4fec32fe6)
will this work?

**Comment by insthync** [comment]
Yep, it should work
