### ISSUE TITLE
Harvestable entity not harvestable 100% of the time

### ISSUE THREAD

**Issue by imakeinternet** [suriyun-production/mmorpg-kit-docs#212]
Often times the first hit doesn't register, other times all the hits register, and occasionally the hits do not register at all and the character is left swinging for eternity.

Video: https://www.youtube.com/watch?v=I0lq29SEPg0

**Comment by insthync** [comment]
Oh, I will fix it.

**Comment by JestHWas** [comment]
Is this fixed?

**Comment by imakeinternet** [comment]
@JestHWas It was reported as fixed. I haven't tested it yet.

**Comment by insthync** [comment]
This was fixed, if the issues still occurring, you can reopen this post.
