### ISSUE TITLE
Missile Skill Missing 

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#2120]
Damage issues with missile skills seem to only affect MMO mode at least for me 
kit version 1.83e2 
Till kit version 1.83c  it was working skill hitting how checking back I didn't find much that could cause this issue
this issue is only there in the MMO mode single player works fine, maybe once in every 50 hits one misses

https://youtu.be/zLjCI3Lk1OU

**Comment by Deepankar1993** [comment]
The old apply damage function is working for missile damage like before 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/1295862/d4d62281-bc67-4a3c-8416-e0c409442611)
 
 The ApplyDamage() function is causing the missile skills to miss in MMO mode working perfectly in SinglePlayerMode
 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/1295862/d3099f84-2777-4a55-80c2-5d9be1bb0d1e)

**Comment by insthync** [comment]
Mine work, how can I test yours?

**Comment by Deepankar1993** [comment]
On my PC or I can send you a key or build of the game

**Comment by Deepankar1993** [comment]
Fixed in 1.83f

**Comment by Deepankar1993** [comment]
I am reopening this issue as the in 1.83f missile damages have improved single player however in MMO mode it still missing especially if the Missle skill doesn't have an explosion  even with explosion it is missing 
However in single player mode one even 1 shot that misses

**Comment by insthync** [comment]
Send your AnyDesk address to my email: ittipon.bay@gmail.com

**Comment by Deepankar1993** [comment]
Just Sent the Anydesk details on your email
