### ISSUE TITLE
Inquiries about Cheat Prevention

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2121]
I am currently on BETA Test Phase. And some players reported to me their conversations with other players that telling them that they will try to use speedhacks, or increase their golds, increase their damage outputs. My question is, would that be possible? If yes, how can we prevent those things?

**Comment by insthync** [comment]
I think what you can do is just tell me where it can be hacked, and how the users do it, that is it.
