### ISSUE TITLE
Can anyone tell me how I can correct this error or if anyone has had something like this?

### ISSUE THREAD

**Issue by Caveirola** [suriyun-production/mmorpg-kit-docs#2122]
Can anyone tell me how I can correct this error or if anyone has had something like this?
![oie_4114247RVVSrReb](https://github.com/suriyun-production/mmorpg-kit-docs/assets/135279672/b09c8ef5-cd35-4c49-a41d-280e82c23a6a)

**Comment by insthync** [comment]
Please scroll it up I want to see more details
