### ISSUE TITLE
[Suggestion] Faction requirement for items

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2124]
A suggestion that I think would be useful for several projects is to put the faction requirement for the items too, so that you can make specific armor for each faction, so a person from another faction would not use the armor of another, thus confusing the player.

I am suggesting this because games may have faction-specific quests and that as a reward for these quests grant the player armor from that faction as a way of showing that you have completed the faction quests.

Just an idea! XP

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/d25ae0f1-06e6-45e9-bb68-4986b0b0f3fe)

**Comment by AsheshPlays** [comment]
@juniormagalhaes this would be very helpful for faction emblems, faction capes, faction fashion sets and any faction related items.

**Comment by Eniotnacram** [comment]
Now with this change, when a weapon as no factions requirement, it doesnt let the player equip that weapon. @insthync
