### ISSUE TITLE
Root Motion Lag 

### ISSUE THREAD

**Issue by joabekaul** [suriyun-production/mmorpg-kit-docs#2125]
Hello, I'm using root motion in my project, I was using two marked options (Root Motion Movement, While not Moving) but with both the situation is even worse, so I decided to stick with just the one (While not Moving), in this case I use rootmotion in my forward attack skills and also for dash, but I can't find a configuration that doesn't happen lag, I've done several tests already and always the same thing, what am I doing wrong? my server is on a great computer and connection.

Exemplo 1;
https://youtu.be/jFk_jby0FrE

Exemplo 2: 
https://youtu.be/T0y-UZCPcik

Is it really not feasible to use rootmotion with this kit these days? I've also tried with no secure movement, it was even worse... Is there another solution for scrolling on the ground and dash without root motion? so i can sacrifice this root motion function?

**Comment by insthync** [comment]
Yep, you should `NotSecure`, the problem is speed hack detection system, it will detect speed hack by character's move speed stats, you may try change the condition in `BuiltInEntityMovementFunctions3D` -> `ReadSyncTransformAtServer`

![Screenshot_693](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/98e39160-278c-4e53-90e8-c7cdb5bacc20)

**Comment by joabekaul** [comment]
Alright, look what happens when I use unsecured, check my character settings, my screen flickers and won't move

https://youtu.be/_izqmphooQ4

**Comment by insthync** [comment]
I know it that is why I told you to change the condition.

**Comment by insthync** [comment]
Changes codes as you wish

**Comment by joabekaul** [comment]
Got it thanks, I'll try something... any simple idea to change the code in this case to solve it? or some starting point

**Comment by joabekaul** [comment]
Got it thanks, I'll try something... any simple idea to change the code in this case to solve it? or some starting point

**Comment by insthync** [comment]
Then don't do anything.

**Comment by insthync** [comment]
I will try to use `AnimationClip.averageSpeed` to fix it

**Comment by joabekaul** [comment]
Will you try and give me feedback? sorry to take your time, it's because i really would like to use rootmotion for some things, i have a big project going on, but i'm in no rush... if there is some simple and working solution i will definitely adopt it...

**Comment by insthync** [comment]
Simplest changes which will make it work but your game will hackable is change condition at line 941 to true

**Comment by joabekaul** [comment]
ok i'll use this for now, if there's a safe solution in the future let me know, the project won't be released anytime soon, but for testing issues it'll be useful, thx

**Comment by joabekaul** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/114507343/c23a16cc-59fe-4d42-8224-d87c19bee019)


I made the following change, it worked perfectly, so this way the game will have hackers?

**Comment by joabekaul** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/114507343/76da4b42-941b-4091-a15b-9538061dd27f)

I made the following change, it worked perfectly, so this way the game will have hackers?

do you intend to do something in the future to get around this?

**Comment by insthync** [comment]
Yes
