### ISSUE TITLE
Language in Settings

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#213]
Single player game
1. You have chosen a second language in the settings.
2. Quit the game.
3. Entered the game.
4. Open the settings with languages ​​and language automatically switches to the first in the list

**Comment by insthync** [comment]
Ahh, I will fix it.

**Comment by DimasjkTV** [comment]
> Ahh, I will fix it.

Thanks! Can you post fix here?

**Comment by insthync** [comment]
[MMORPG_KIT-FixInvalidLanguageToggleAtStart.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4177746/MMORPG_KIT-FixInvalidLanguageToggleAtStart.zip)

Fix by this package
