### ISSUE TITLE
GameInstance Conversation Distance not working.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2131]
Hello,

The conversation distance works for NPC's but looks like its not working with other players.

Conversation Distance set to 3.
I can interact (trade, invite party) with other players that are 30m away when a weapon is equipped on my character. (Damage Type: Missile, Missile Distance: 30) when i remove the item and use my fists (melee weapon) the conversation distance is working.

Note that I am using the ShooterController.

PS: The game prevent the player to interact with the player after X distance. But he still can press E to interact. Instead of shooting an error that i cannot interact with the player, would be better that i simply doesnt let the player press the interaction key  if hes too far away to interact. The same way it does with the NPCs.

**Comment by insthync** [comment]
Fixed in 1.83g
