### ISSUE TITLE
Item Sprite 2D

### ISSUE THREAD

**Issue by alexengel1992** [suriyun-production/mmorpg-kit-docs#2132]
Is there a way to create a 2D item where when equipped it changes the character's Sprite?
this would be really good for KIT 2D

**Comment by insthync** [comment]
Do you have any idea of how to implement it?

If you have you may tell me how, and I may implement it like this project: https://github.com/insthync/UnityMultiplayerARPG_HeroEditor4D

**Comment by alexengel1992** [comment]
![334](https://github.com/suriyun-production/mmorpg-kit-docs/assets/83098223/de52c2a4-b08f-476f-93b5-7455e2dc9a21)
![364](https://github.com/suriyun-production/mmorpg-kit-docs/assets/83098223/843cfe50-d3ab-4ef4-9895-f6a0c5b76828)
![220](https://github.com/suriyun-production/mmorpg-kit-docs/assets/83098223/484a22ab-bd26-4756-9837-e1c8ab19df8e)

Hello!
Would you be able to use Hero Editor 4D with these sprites?
because I wanted to be able to equip these sprites on my naked character's body, I have no idea where to start

Example:

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/83098223/73c30224-bbc2-42b6-b9f9-60552384d0ae)

**Comment by alexengel1992** [comment]
Something wrong when I change armor and helmet, it's not just changing Weapon changes

https://github.com/suriyun-production/mmorpg-kit-docs/assets/83098223/e3b60118-099b-49a3-bdb6-b5a8eb43bf73
