### ISSUE TITLE
Guild and party bugged with instances

### ISSUE THREAD

**Issue by n0dai** [suriyun-production/mmorpg-kit-docs#2133]
Looks like the guild and/or the party is not correctly saved when entering an instance.

Example: if 2 characters are in the same guild and are in the same party, then enter into an instance (NPC > "Warp to Map002 (Instance)"), the group leader will no longer be in the guild but will stay in the party, and the other character will no longer be in the party but will stay in the guild.

https://youtu.be/02FggXMA_PU

Tested on a clean fresh install, using Unity 2022.3.0f1, in an MMO configuration with MySQL.

**Comment by insthync** [comment]
Fixed: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/3def5e031e9af9f56a60c3bf2e1e11a3100aabb7

**Comment by n0dai** [comment]
> Fixed: [insthync/UnityMultiplayerARPG_MMO@3def5e0](https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/3def5e031e9af9f56a60c3bf2e1e11a3100aabb7)

Thanks! :-)

**Comment by temelkirci** [comment]
Not fixed bro.Still guild and party issue on my game.

**Comment by insthync** [comment]
Why you always having an old bug occurring*-*

**Comment by insthync** [comment]
@temelkirci Can you help me do something like this, put all codes into a submodule repository, then give me access to update codes in that submodule?

**Comment by temelkirci** [comment]
@insthync I am really having these issue.No lie.I can create a rar file included all scripts.Or I can give you my all game project to examine it.No problem for me.There are a lot of issue.I can explain you by one by.I just need help, because I am making much money and a lot of players.I want to improve it.Maybe my mistake but I know you can take a look into it.

**Comment by insthync** [comment]
Okay, you can give me access by inviting me with my email: ittipon.bay@gmail.com (github/gitlab)

**Comment by temelkirci** [comment]
@insthync Done.
