### ISSUE TITLE
Fall Animation after Teleport (Bug? Help?)

### ISSUE THREAD

**Issue by joabekaul** [suriyun-production/mmorpg-kit-docs#2134]
Hello, I'm having a problem using the teleport skill, always at the end of the teleport my character performs the Fall and Landing animation, how can I solve this?
Version: 1.83f

https://youtu.be/6Sa1OZAKUTU

Is it possible to configure the minimum height to consider that it is falling?

**Comment by AlcidesJunior123** [comment]
This problem occurs when the Z or Y axis is not locked in the animation. I also had problems with this in the root motion animations and I believe that locking one of these axes in the animation settings does not solve it, you can test it.

**Comment by insthync** [comment]
Try 1.85b
