### ISSUE TITLE
MISS Text not showing 

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2135]
I don't know when or how the "MISS" text is missing. I only noticed it now when one of my testers reported it. I tried looking for it on the project and I only see that miss has a value of "0". All my miss damage are 0, which is correct but the "Miss" text should be the one showing. I havent noticed it until its been reported to me. Was it removed or changed? How do I add it back? Thanks

**Comment by insthync** [comment]
Nah, it still have Miss messages

**Comment by insthync** [comment]
![Screenshot_734](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/750b6c6c-9420-4e7c-8140-462514e16803)

**Comment by AsheshPlays** [comment]
question about this, which string of miss should i change for localization?

**Comment by insthync** [comment]
Change in combat text prefab (named: MissText)

**Comment by AsheshPlays** [comment]
oohhh.. i never thought its on the prefab. was searching the codes but never found it. 🤣🤣 thank you for this info..
