### ISSUE TITLE
No Faction on Start: Invalid Data

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2136]
My game has 3 Factions (God Based) and a player can only Join or Choose when he reaches a certain level and a quest will appear. What i did was create the 3 factions and enabled the Lock checkbox. When I start the game, I get an "INVALID DATA" when creating the character. But if I unlocked the Factions and create a character with a starting faction, there is no problem. How to make players start with no faction? Is there something that I did wrong or missed something?

**Comment by insthync** [comment]
Create a new faction as default faction, that is it.

**Comment by AsheshPlays** [comment]
@insthync
Creating a Faction with a name of "No Faction"?
oohh Ok.. funny but makes sense.. thanks 😅😅
