### ISSUE TITLE
Faction Item bug..

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2138]
I cannot equip my items anymore error saying "not match character faction".

There is no factions required on my weapon.

**Comment by insthync** [comment]
As I test, it is not occurring.

**Comment by Eniotnacram** [comment]
Trying to investigate further, I cannot reproduce it either on brand new kit. Thats really weird. Clearly something is up with my items

**Comment by Eniotnacram** [comment]
Found the bug. Remove all factions from the Database. The problem occurs. So currently, absolutly needs factions in the database to make the game work.

**Comment by insthync** [comment]
Fixed in 1.83g2
