### ISSUE TITLE
Swimming issue..

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2139]
When The character is set to auto swim to surface, there is a bug with the y velocity that keeps the character glitching between isUnderwater true or false..
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/c1e8c95c-b1e9-4d28-a9d7-b67052271b74)
at first glance it doesnt seem to matter.. But when u add animations for swimming and falling .. u see the difference..

https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/0605f780-0e7e-4326-9635-5a96b43a817b

when i comment this code out, it works fine.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/7960be5b-a71b-4b63-a5a1-25ac76365e18)

Even when swim to surface is off, and u try to swim manually to the top of water it starts glitching.. 

Only when u are fully underwater it stops, u can not come to surface or u will have same bug again..

Because the upwards velocity is pushing the character outside the Underwater threshold set here 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/e01b0409-414b-4858-a59d-0bf1c9953872)

The margin for this is too small
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/5b59a4f0-1cd7-4227-a63c-9580a2d439c3)

it needs to have a margin before saying true or false, so that the upwards movement from just going to water surface doesnt make u go outside of water..

Or make the upwards velocity not take you outside of the water.

**Comment by Callepo** [comment]
The problem here is the Currentmovespeed.. when u are at the top of the water, movespeed should be 0 or <0.01
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/eb51d4d3-88a8-4e5a-a9a1-19b5332dcfd0)

But its never that, so it pushes you out the water. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/7e571c57-c5b6-457b-aa71-4f5ed1275fc8)
The movespeed calculations is bad

@insthync

**Comment by Callepo** [comment]
@insthync

**Comment by insthync** [comment]
Try the `fix: wrong current move speed calculation when it should stop` commit

**Comment by BJPickles** [comment]
Common solution for this is to have 2 states for swimming:

Surface swimming: which is Y locked and just X & Z active. This would also work well with the shooter controller. To enable diving it would require a button to be pressed or something to trigger the dive / switch to sub-surface swimming.

Diving / sub surface swimming: Which enables below-surface swimming in all 3 axis. When you return to surface, you again become locked.

Just my 2 cents but a frequent choice in games today.

**Comment by insthync** [comment]
Try in 1.84
