### ISSUE TITLE
InvokeInstanceDevExtMethods

### ISSUE THREAD

**Issue by astromediaonly** [suriyun-production/mmorpg-kit-docs#214]
Im tracking weird behavior and i would like to know if i got it right or something else is happening. Is there possibility when i do:
```
[DevExtMethods("SomeMethod")]
public void SomeMethod_A(object o)
{
	this.InvokeInstanceDevExtMethods("SomeOtherMethod", o);
}
```
that inside call of another devext method in already called devext method breaks calling of other methods (SomeMethod_B) for example? I hope it makes sense :)
I have SomeMethod_A and SomeMethod_B (both of them with ``[DevExtMethods("SomeMethod")]``) and only _A gets called and i have feeling that inner call (``this.InvokeInstanceDevExtMethods("SomeOtherMethod", o);``) is the culprit why but im not totaly sure ... is it possible? Its probably not the best design choice but i was not expecting to break something by it :) (if its indeed the problem)

**Comment by insthync** [comment]
It can do nested invoke dev ext methods
```
    void Update()
    {
        this.InvokeInstanceDevExtMethods("SomeMethod", "test");
    }

    [DevExtMethods("SomeMethod")]
    public void SomeMethod_A(string test)
    {
        this.InvokeInstanceDevExtMethods("SomeOtherMethod", test);
    }

    [DevExtMethods("SomeOtherMethod")]
    public void SomeMethod_B(string test)
    {
        Debug.Log(test);
    }
```
As the codes above, it will write "test" every frame.

**Comment by insthync** [comment]
Oh, I see the problem, if we do nested invoke, other methods will not invoked

**Comment by insthync** [comment]
[MMORPG-KIT_FixNestedInvokeDevExtMethodBugs.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4199308/MMORPG-KIT_FixNestedInvokeDevExtMethodBugs.zip)
Fix by this package

**Comment by astromediaonly** [comment]
Good to know there was indeed some issue :) ... Thanks for the fix - as i know my self im sure i would fall to that trap in future again and it was not easy to spot what was happening it that case :)
