### ISSUE TITLE
Guilds passives skills bugged

### ISSUE THREAD

**Issue by n0dai** [suriyun-production/mmorpg-kit-docs#2142]
The guilds passives skills can be "used" (like the actives skills). If you use a passive guild skill, an error occured. The "use" button on a passive skill should be hide.

https://www.youtube.com/watch?v=iqcc4wva4Yo

Tested on a clean fresh install, using Unity 2022.3.0f1, in an MMO configuration with MySQL.

**Comment by insthync** [comment]
It cannot be used because it is a passive skill so it is not a bug, a button not hidden is not a bug too, it is just not hiding, just have to write a script to hide it.

**Comment by insthync** [comment]
![Screenshot_775](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/06878dce-372f-41b1-90ff-205b70b0f0d4)
