### ISSUE TITLE
Blocking Passage to Monsters

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2143]
How can I block monsters or prevent them from passing through an object with collider that i created?
I added a "BlockMonster" layer, also added it to include layer on the monster's layer overrides but they can still pass through it. I don't want to use `SafeArea` component on this for a separate reason. I just want to block monsters from passing through. Is there something i missed? Pictures attached below.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/3d1f125a-37bf-4158-a8da-8bc635f555da)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/2ce5fef1-fa6f-4b4c-a5f8-58746c540ddc)

**Comment by insthync** [comment]
https://docs.unity3d.com/Manual/class-NavMeshObstacle.html
