### ISSUE TITLE
[Question] how to import settings or import values  from animator character model  to playable character model

### ISSUE THREAD

**Issue by SkyRain2020** [suriyun-production/mmorpg-kit-docs#2145]
how to import settigns or import values 
from animator character model 
to playable character model
so that we can use sheating 
since is the sheating update state that,

" Sheathing animations is available for Playable Character Model only. "

**Comment by insthync** [comment]
Try its context menu, if you don't what it is, try googling it, it is a gear icon, click it then it will has a convert menu.
