### ISSUE TITLE
this problem always occurs in new version update

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#2146]
This happens after every update. Game Instance.I'm getting an error. i tried this - https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan
i tried this -  https://github.com/suriyun-production/mmorpg-kit-docs/issues/2050#event-9109499318
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/50966738/fc8f6f34-b57f-4a8a-a985-4809b84c1713)

**Comment by insthync** [comment]
What is the error?, no helpful information here.

**Comment by Eniotnacram** [comment]
You are just doing the update wrong, the kit is not imported properly cannot find the scripts. How are you upgrading your versions? @kazuden ?
