### ISSUE TITLE
Skinned mesh renderer bug again

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2148]
The error that occurred with the skinned mesh renderer is happening again, the line of code that you put to solve it is there
!![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/04d9f139-69f9-40b2-9240-10e6d90078d0)

**Comment by insthync** [comment]
Can you change your hair mesh to be humanoid?

**Comment by insthync** [comment]
Did you try to use any of this? https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/163-equipment-bones-setup-manager

**Comment by Niinra** [comment]
Yes, I tried following documentation steps. I tried use it only in GameInstance, only use it in Hair item and on both but didn't work

**Comment by insthync** [comment]
[LegacyEquipmentModelBonesSetupManager.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/11803632/LegacyEquipmentModelBonesSetupManager.zip)

Try  import this package, then create equipment model bones setup from this one.

**Comment by Niinra** [comment]
it works
