### ISSUE TITLE
Jittery Movement while Walking.

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2149]
When player moves normally or sprint, it moves smooth.. 
But when you walk, movement becomes really jittery, maybe becuase movement speed is lower and , but its really noticeable.
maybe lerping not working properly idk.. i tried many different settings, different controllers, used character controller  + Open character controller, both same. 

https://youtu.be/STXW5gmy9zk

Tried default kit, and saw the same result.

https://youtu.be/lsZdPZIVX3Y

**Comment by Callepo** [comment]
@insthync Sprint in 1.83g2 is also bugged..
default kit no changes..
Sprint works fine on main client + server view, the speed is adjusted, ur location on server is good.. but everyone else in the game see you teleporting.. 

Movement speed from character is not changed on other people client.. u see them still move the same speed before they start sprinting.. and than the server location gets out of sync with their client position, so the player rubberband..

https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/dce9f964-e159-4d43-9df0-991c48a229b9

**Comment by insthync** [comment]
Try apply the latest commit: `fix: invalid simulate movement state`

**Comment by Callepo** [comment]
> Try applying the latest commit: `fix: invalid simulate movement state`
> 
> And no, they are not part of the problem

cool ill check it.
Also i didnt check the code changes, i just looked if there was any movement updates in change log and seen that
