### ISSUE TITLE
Hotkey in mobile do not work the first time you press

### ISSUE THREAD

**Issue by majausone** [suriyun-production/mmorpg-kit-docs#215]
It happen with unity remote also.
I test it in 2 mobiles.
I think it happen cause MobileMovementJoystick.cs -->
OnPointerDown (line 53 more or less)
Sometimes is not working.

**Comment by insthync** [comment]
Which version are you using?

**Comment by majausone** [comment]
I think im on 1.52, but i have no way to see my current version. I download it like one month ago.

**Comment by insthync** [comment]
I will close this, if you tried newer version and it's still occurring, you can reopen it.
