### ISSUE TITLE
MonsterActivityComponent -> FolowTargetDuration no longer working

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2150]
the option in title no longe working. first i thought its an issue on my side because in fresh kit it worked, then i noticed in kit u use  MaxDistanceFromHome. in my game i dont use it so only FollowTargetDuration

so now when u set MaxDistancFromHome to 0 monster chase player forever

**Comment by juniormagalhaes** [comment]
I've been having this problem for a while too, and I ended up forgetting to report it.
