### ISSUE TITLE
Status Effect with Runes not work properly

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2151]
here my settings 

https://gyazo.com/2e4bdeccd223b12ec51a0001e824cee6
https://gyazo.com/e16b7845d7fc88aaf06608a6554e93ce

it should apply every time.
so the effect (particle) applies but never the health
https://gyazo.com/54b838611c2bfd74bd2c3bc8e52a48f2

**Comment by moepi2k** [comment]
I will check it when at home but i think duration is set to 0. So when increase buff duration it only leech on next attack? That seems wrong, no?

**Comment by insthync** [comment]
No, because it is part of character stats, it will increase character stats, not a leech effect applying.

Only recovery HP/MP (and so on) can be applied immediately.

**Comment by moepi2k** [comment]
Tried with duration 5 seconds but also on second hit it not apply leech. It seems leech only works when use it directly on weapon scriptable stats but not with sockets

**Comment by insthync** [comment]
Tried with that too, but it leech
