### ISSUE TITLE
Layer Mask for Skill Cast

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2153]
Hello,

Currently when using the "SimpleAreaAttackSkill" it uses the GameInstance "AttackObstacleLayers" to know where the player can cast the skill. It would be usefull that for each skill if we could choose the layer where the skill can be casted. Because For me, currently, in the "AttackObstacleLayers" I got "Default" and "Terrain" Layer. Because I want my Missile to hit those and get destroyed and not go trough them. But because of that, I can cast my "SimpleAreaAttackSkill" anywhere on those layers, so on my trees, on my props, etc. So I would like to only select the "Terrain" Layer to my skill so I can only cast it on the terrain. (If I change the layers of my trees, and do not add it to the "AttackObstacleLayers", I cant cast my skills on them anymore, great, but my missile go trough them and I dont want that).

Again, I could do this on my own but it would need core modifications and I think this functionnality could be usefull to anyone using the kit.

ALSO, the "Can Apply Damage to User" in the Area Damage Entity is not working.

Let me know  :)

**Comment by insthync** [comment]
Create a new component and use it then you won't have to change the core codes

**Comment by Eniotnacram** [comment]
Okay will do but the "Can apply damage to user" is not working still, tested on fresh kit.

**Comment by insthync** [comment]
Fixed
