### ISSUE TITLE
Problem HeroEditor4D

### ISSUE THREAD

**Issue by alexengel1992** [suriyun-production/mmorpg-kit-docs#2154]
Hello
 I have a problem using HeroEditor4D because it doesn't change armor and capacity, it just changes Weapon

https://github.com/suriyun-production/mmorpg-kit-docs/assets/83098223/e96353ae-2d13-4ca9-b00d-4c56bd4a0399

**Comment by insthync** [comment]
Mine still work properly, but I use old version of HeroEditor 4D, I will check with the latest version later.
