### ISSUE TITLE
Monsters do not respawn after a while in maps :(

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2155]
I am having v1.87g but my monsters do not respawn after a while in maps.I added different scripts and fucntions I could not solve it for 2 weeks.I have to solve this.I have a lot of players online right now.I always restart my server :( @insthync Help me pls

**Comment by juniormagalhaes** [comment]
I have the same problem, did you manage to solve it?

**Comment by temelkirci** [comment]
@juniormagalhaes yes.I solved it myself.I added some code but I realized that it breaks my respawnroutine function.Check your latest changes in your code.

**Comment by juniormagalhaes** [comment]
> @juniormagalhaes yes.I solved it myself.I added some code but I realized that it breaks my respawnroutine function.Check your latest changes in your code.

Could you help me with this? where did you change it exactly?
