### ISSUE TITLE
Add SliderGage to UI Network Scene Loading, UI Scene Loading & UICharacterEntity

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2157]
For all the UI scripts that plays with value, there is the option to add an image or a slider for the gages, (exp bar, hp bar, etc). Im using a slider in my case, but the slider option is not added to those mensionned scripts.

I've added them but would be really nice to add this to the core so I dont need to check this forever for every updates :)

Modified scripts: (Only added the slider gage option)
UI Scene Loading: https://pastebin.com/eCEzwjku
UINetworkSceneLoading: https://pastebin.com/jHnfx8Mk
UICharacterEntity: https://pastebin.com/8LFePTUV

(Probably other scripts that is missing the slider option)

**Comment by insthync** [comment]
Okay, I will add it.
