### ISSUE TITLE
hprecovery death issue

### ISSUE THREAD

**Issue by TheJuicer1** [suriyun-production/mmorpg-kit-docs#2158]
it looks like when you die and have hprecovery, you will come back to life again after death because it recovers health. Where would I fix this? 

Thanks

**Comment by insthync** [comment]
Recoverying by buff ?

**Comment by insthync** [comment]
Try to fix it in `CharacterRecoveryComponent`, but it already has a dead character checking before the recovering

**Comment by insthync** [comment]
And in `CharacterSkillAndBuffComponent`

**Comment by TheJuicer1** [comment]
thanks
