### ISSUE TITLE
Able to teleport into a vehicle after going away from it

### ISSUE THREAD

**Issue by TheJuicer1** [suriyun-production/mmorpg-kit-docs#2159]
Maybe I'm missing a setting somewhere but when I interact with a vehicle enter it with E. I can then get out of the vehicle and run across the map and press E and it will teleport me back inside the vehicle across the map. Happens in MMO. Not sure why this happens. 

Thank you

**Comment by insthync** [comment]
I will check it, thank you for your reporting

**Comment by TheJuicer1** [comment]
I was able to reproduce in single player and MMO the issue only happen when using shootercharactercontroller all other controllers are okay. see video below thank you

https://youtu.be/85KW-Q7UHnI

**Comment by TheJuicer1** [comment]
@insthync I feel bad asking... I'm sorry if this is a pain but could I get the fix for this here? I am on 1.76 due to custom scripts that will break if I upgrade to the newest version. I will upgrade in the future just too many custom things to resolve. 

I can send you a ko fi for the time if you don't mind
Thank you
