### ISSUE TITLE
Damageable hitbox problem

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2160]
Sometimes this problem occurs when I attack a creature, it does not damage the creature, what should I do?

Version: 1.83g2

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/3a78f568-68d4-4e47-ab0b-94302bf70981)

**Comment by insthync** [comment]
I will fix it, but I want to ask if this one is occurring just sometimes, or very frequently?

**Comment by CLAXES** [comment]
when the monster is attacking, it gives this error every 10-20 seconds or more, so I get it often.
