### ISSUE TITLE
Can summon pet from skill ?

### ISSUE THREAD

**Issue by ozantekce** [suriyun-production/mmorpg-kit-docs#2162]
I want to summon the pet from skill such as summoning from items. How can i do it? Summon skills do not keep the level of the pet.

**Comment by ozantekce** [comment]
Yes, I can summon it that way but it doesn't preserve the level. For example, my pet is level 20, I want to summon it with skill and it should be level 20.

**Comment by ozantekce** [comment]
The level of the pet will be fixed in this way, so it will always be at the same level that it cannot level up.

**Comment by insthync** [comment]
If you want it to store pet level and its progress to database, then, you can't.
