### ISSUE TITLE
Map user limit.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2164]
I don't know if there is a system like this, but can you do something like this.

Hi, can a user limit be set for maps? If there are 100 people on a map, can it be set to automatically create a virtual map for the 101st person, so that person doesn't see the others. I want to have a maximum of 100 people on a map, then I want a new map to be created from the same map. can you make a system like this, since it is a mobile game, more on the same map is a problem.

**Comment by insthync** [comment]
Do you asking for channel system ?

**Comment by CLAXES** [comment]
Yeah, do you have that system?

**Comment by insthync** [comment]
Not yet.

**Comment by CLAXES** [comment]
When can you add this system

**Comment by insthync** [comment]
I don't know too.

**Comment by CLAXES** [comment]
how can I make a system similar to this now, can I start 2-3 separate mapserver or something like that, or should I start the central server separately, should I start them all separately, should I show more than one server at the entrance to the game, if I make it for 100 people, should I buy a new build for each one, by changing the ports.

**Comment by insthync** [comment]
I think this https://github.com/suriyun-production/mmorpg-kit-docs/issues/2152 might be the same thing, let's move to talk about it there.
