### ISSUE TITLE
(Paid Request) Ui Character Entity

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2166]
I would like it to show in addition to the lvl, hp and name, it also shows the status of the monsters, such as resistances, armors, category, description and icon of the monster.

it would be nice to have this in the kit as you can give the player more feedback on the monster they are facing.

https://prnt.sc/_9_aRFTMt39A

**Comment by khongtuong** [comment]
dude, it's all there, just set it up

**Comment by juniormagalhaes** [comment]
> 

Where?

**Comment by Eniotnacram** [comment]
> > 
> 
> Where?

Its not in the Ui Character Entity but there is a lot of UI script for all of that.

- UI Character
- UI Character Class
- UI Character Stats

Etc etc.

**Comment by juniormagalhaes** [comment]
I don't think it works for monsters

**Comment by khongtuong** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/6816616/bb5a58c2-0886-49bf-a072-d3f6669d6acd)
even you can add color title by level

**Comment by insthync** [comment]
I try to improve performance by don't add everything to that component, but if you still want to show more data, in the next version I've add event when set entity, you can use it to set data to other components, for example, set data to another `UICharacter` component which is component which have all character data

![Screenshot_774](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/34d6291f-51b4-4de5-8a3e-ac0dd6af7019)

**Comment by juniormagalhaes** [comment]
Thank you very much, it will help a lot
