### ISSUE TITLE
In-App Purchasing & Guild bug.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2167]
Hello

#if UNITY_PURCHASING this definition doesn't work anymore, I think it was removed in unity, can you remove it in the project.

Also, when the guild leader deletes the character, the guild is still in the database table, shouldn't it be deleted?

**Comment by juniormagalhaes** [comment]
not going to someone in the guild?

**Comment by insthync** [comment]
@CLAXES Are you sure?, I can delete `UNITY_PURCHASING` but if it has an error on other customer's projects, then it will have only me who have to fix it later.

And why have to delete it?

**Comment by tubhluas** [comment]
dont need to delete it. if you dont need it you just dont define it in the unity build setting
