### ISSUE TITLE
1.53 Item Dismantle

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#217]
When you click on "Dismantle" button, nothing happens. Free Project 1.53

And a little wish. Is it possible in the future to separate:
* dismantle items (item destroys)
* get stones (jewels) from items (items don't destroy)

**Comment by insthync** [comment]
Oh, onclick dismantle event was missing from the button, I will fix it and repackage.

**Comment by DimasjkTV** [comment]
> Oh, onclick dismantle event was missing from the button, I will fix it and repackage.

i added. Works well. thank you!
