### ISSUE TITLE
 Untradable, Unsellable and Undroppable Items

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2171]
Hi. How do i make items Untradable, Unsellable and Undroppable? I have certain items that are not meant to be traded or to be sold like Quest Items, that will be used for other Quests. I want to set it to that because I want to avoid people making accidentally selling the quest item and getting stuck on a quest.

**Comment by insthync** [comment]
No way to do it, have to add by coding

**Comment by AsheshPlays** [comment]
@insthync 

How much would it cost if I request it as addon from you sir?
