### ISSUE TITLE
Facebook Login doesn't seem to be working

### ISSUE THREAD

**Issue by codecustard** [suriyun-production/mmorpg-kit-docs#2173]
Tried using my facebook login in the user/pass fields. Tried leaving it  blank. When I click the "Login with Facebook" button with both cases it gives me the following error:
![error](https://github.com/suriyun-production/mmorpg-kit-docs/assets/139997/04a55d10-9b46-4081-b3a3-05cd83a99783)

Tested using SQL Lite.

**Comment by insthync** [comment]
You might just didn't set up Facebook SDK properly yet, add error messages like this: https://github.com/insthync/MMORPGKIT_FacebookAuth/commit/9f0d1bf6007584b7bd510511d637737439db1267
and try again, to see what is happening.

**Comment by codecustard** [comment]
Yeah, probably.

I tested on Android, got the webpage popup.

Does it not work out of the box for Desktop? I was under the impression that the kit takes care of the browser popup, or is that something that needs to be implemented yourself? Or maybe as you've said before I didn't set up the SDK properly.

**Comment by insthync** [comment]
https://developers.facebook.com/docs/unity/gettingstarted
