### ISSUE TITLE
Monsters not aggressive when visual range is above 50

### ISSUE THREAD

**Issue by TheJuicer1** [suriyun-production/mmorpg-kit-docs#2174]
I am trying to get monsters to attack me and chase me but they wont. I have it set to aggressive and the visual range is 1000 and not safe area. monsters just wonder around they wont attack me first on newest version default scene.  I even changed the default orc warrior visual range to be high and aggressive but it wont attack me only if I attack first. I want the monster to chase and attack me. 

thanks

**Comment by TheJuicer1** [comment]
update I found the issue, when I increase the visual range in the monster settings higher than 50 they wont be aggressive anymore.  is there a way to increase it above 50? I wanted it to be very far like 1000+

**Comment by insthync** [comment]
Because it is using https://docs.unity3d.com/ScriptReference/Physics.SphereCastNonAlloc.html to find enemies, and if it reached max size of the array then it might not be able to find an enemy as you expected. you may change alloc size in `BaseCharacterEntity.cs` -> `EntityStart` function.
