### ISSUE TITLE
[Request] Add "UI Faction" to "UI Character"

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2177]
Hello, I can easily do it but I think this should be in the core kit and it would benefit anyone with the kit.

So yea, the idea is to simply add the option to see which faction the player is when opening the UI Character.

Thank you :)

**Comment by khongtuong** [comment]
i already made this, so just contact me via discord

**Comment by Eniotnacram** [comment]
But I've made this post because I think this should be part of the kit. As everyone most likely needs this. :)
