### ISSUE TITLE
[Paid / Feature Request] Move/Lerp Character without Animation/PointClickMovement

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#2179]
Hey Suri, 

is there any chance you could implement a function to move/lerp the character from Position A to Position B without teleporting or triggering the movement (PointClickMovement) animation?

Background why i want it:
I want to try to implement some kind of Dash animation without root motion. I want the character to lerp to a certain position instead of a fixed root motion animation. So i want to be able to play an animation at the same time the character would be moving/lerping from A to B.

i tried the function "PointClickMovementPointClickMovement", but this of course triggers the normal movement after the skill animation of the player instead of just lerping the position.

If it is not possible, never mind. But asking never hurts :)
Thank you for your Response!

**Comment by juniormagalhaes** [comment]
warp skill doesn't work for what do you want?

**Comment by xnitro1** [comment]
Nope, because warping isntantly moves the player from A to B. but i think i have to do it via the PlayerCharacterController. But moving the player there gives me rubberbanding (using not secure movment). So maybe its not a thing for Suri at all and i´ll have to do it somehow myself :D

**Comment by khongtuong** [comment]
try to use root motion - animation

**Comment by xnitro1** [comment]
thats exactly what i wanted to avoid because root motion is extremly buggy with synty models (or i´m doing something wrong :D )
