### ISSUE TITLE
Campfire lost all data when change maps

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#218]
Put some wood and meat into the campfire then move to another map and comeback, nothing left in the campfire. (both of turn on and off)

**Comment by insthync** [comment]
[MMORPG_KIT-FixLocalStorageSaveBugs.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4182105/MMORPG_KIT-FixLocalStorageSaveBugs.zip)
It's local storage save system bugs, try this package it may fix the issue.

**Comment by insthync** [comment]
I will close this, if the problem still occurring, you can reopen it.

**Comment by JestHWas** [comment]
This fix in 1.53b?

**Comment by insthync** [comment]
Yes
