### ISSUE TITLE
(Paid Request/Feature) Mount Entity

### ISSUE THREAD

**Issue by AlcidesJunior123** [suriyun-production/mmorpg-kit-docs#2180]
Is there currently a function already implemented by someone where the mount entity can be instantiated in the map from the use of the mount item independently of the Player and that follows the Player when dismounted? If not, could it be implemented?

**Comment by khongtuong** [comment]
you can contact Wynixor at discord, he''s already done follow mount

**Comment by AlcidesJunior123** [comment]
Unfortunately I was unable to contact him. Please, if you have contact, ask him to send a message to Email alcidessfjr@gmail.com Thank you.

**Comment by AlcidesJunior123** [comment]
@insthync Bro, can you implement this function? I really need her.

**Comment by insthync** [comment]
Why did you tag me?

**Comment by AlcidesJunior123** [comment]
Sorry, I didn't know I couldn't tag you. I thought tagging you would get some support as I really need it. Thanks

**Comment by insthync** [comment]
I see all notifications, so don't have to tag me, it is feeling like you are rushing me, and I don't like it.

**Comment by AlcidesJunior123** [comment]
I understand, it was not my intention. I'm not a programmer, I'm a graphic designer and sometimes I need to request something here. Thank you for the feedback, if you can analyze my request I would be grateful too. Congratulations on the advances.
