### ISSUE TITLE
[ERROR] with new version 1.84 in new project 

### ISSUE THREAD

**Issue by AhmedHon** [suriyun-production/mmorpg-kit-docs#2181]
First , thank you for this amazing update .. when i imported the package to new project in unity 2021 .. those errors appears after i imported this pack ( https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021 ) 
![asd](https://github.com/suriyun-production/mmorpg-kit-docs/assets/71017004/f93dc0b9-0380-4c9f-88eb-5908d46aac85)

**Comment by insthync** [comment]
Can you fix it?

**Comment by juniormagalhaes** [comment]
I have the same error

**Comment by juniormagalhaes** [comment]
I changed from UNITY_2021_3_OR_NEWER to UNITY_2021_3_OR_OLDER and it solved

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/8f8c50c3-5310-4399-a8b1-0f40f0a5de9d)

**Comment by juniormagalhaes** [comment]
it worked for me hehe, but I think it's just inverting the if else logic then

**Comment by juniormagalhaes** [comment]
globalTextureMipmapLimit it's from the older version of unity

**Comment by insthync** [comment]
No it is from 2022.2 or above

**Comment by insthync** [comment]
https://docs.unity3d.com/2022.2/Documentation/ScriptReference/QualitySettings-globalTextureMipmapLimit.html

**Comment by juniormagalhaes** [comment]
Weird, I searched the GPT chat and it's what's in the image below, so I changed it like in the previous message and now it's working.

OBS; I'm not a programmer, I was just trying to solve the error XD

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/c009d067-d243-4d88-b3d6-13fa71a13455)

**Comment by insthync** [comment]
Very helpful

**Comment by AhmedHon** [comment]
nope but i did like junior ^^ .. i don't know its this way is right or not ^^
