### ISSUE TITLE
v1.84 Body Part Customization helmet issue.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2182]
Hello, I am doing Body Part Customization, but when I wear helmet-style items in the game, I need to cover the hair, how do I do this?

**Comment by insthync** [comment]
Can just hide a hair mesh?

**Comment by CLAXES** [comment]
I try something like this, I add hair to the helmet object, I make it 0, there is an empty object there, but the hair that I initially selected does not close.

**Comment by Eniotnacram** [comment]
> I try something like this, I add hair to the helmet object, I make it 0, there is an empty object there, but the hair that I initially selected does not close.

Go look Denarius blendshapes addon. You need to add blendshapes on your hair (head) model and trigger them when you are equipping a helmet. Its not a bug, its simply some UI stuff you need to take care of.

**Comment by LordPhrozen** [comment]
So, On the head if you set it up like this:

HEAD
-Helmets
--Hairs
---Hair 1
---Hair 2
---Hair 3
--Helmet 1
--Helmet 2
-- Helmet 3

then do the following:
-Set Helmets to be a equipment slot and the default helmet model is "--Hairs". An empty child object.
-set "--Hairs" to be its own equipment slot, with no default model.


Equipping ANY Helmet should disable "--Hairs" turning off the default model, which... as you set this up, is ALL THE HAIRS.
