### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by cetinkrt** [suriyun-production/mmorpg-kit-docs#2183]
Hi,

i try login and register say request time out 

https://prnt.sc/viz7wc9PbGZB
https://prnt.sc/r6_qTwGTyaQF

my server config i try install xaamp and i think mysqlite3 not project file

My log files https://we.tl/t-g3PHzRecN8 how to fixed  this problem thank you any help

{
  "useCustomDatabaseClient": false,
  "databaseOptionIndex": 0,
  "databaseDisableCacheReading": false,
  "useWebSocket": false,
  "webSocketSecure": false,
  "webSocketCertPath": "",
  "webSocketCertPassword": "",
  "centralAddress": "127.0.0.1",
  "centralPort": 7000,
  "centralMaxConnections": 1100,
  "clusterPort": 6010,
  "machineAddress": "127.0.0.1",
  "mapSpawnPort": 6001,
  "spawnExePath": "C:\\MMO\\MMO.exe",
  "notSpawnInBatchMode": false,
  "spawnStartPort": 8000,
  "spawnMaps": [
    "Map001",
    "Map002",
    "Map_GuildWar"
  ],
  "mapPort": 7770,
  "mapMaxConnections": 1100,
  "databaseManagerAddress": "127.0.0.1",
  "databaseManagerPort": 6100
}

Regards

**Comment by insthync** [comment]
Did you run servers?

**Comment by cetinkrt** [comment]
yes i runed server i try local host connect then come login and register screen,

this time the request gives a timeout


i've never been able to log in to the game, I can only log in offline, without a server


when the server starts, it stays on the black screen, there is no writing at all

but it creates server files, at least I can connect to localhosta, but I can't log in and register

**Comment by cetinkrt** [comment]
local host server connected then register says https://prnt.sc/r6_qTwGTyaQF

**Comment by insthync** [comment]
Any error on server-side? in logs folder?

**Comment by cetinkrt** [comment]
https://wetransfer.com/downloads/eb3e7d5ca5140e26d77d82a94a099c9820230802214211/6a248a log files

i think no

**Comment by insthync** [comment]
You did not run the database management server, that is it.

**Comment by cetinkrt** [comment]
how to start this database managment server?

**Comment by insthync** [comment]
Where did you learn how to run servers?

**Comment by cetinkrt** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/025-getting-started-mmo

here and i write all command and xammp server

C:\MMO\MMO.exe -startMapSpawnServer -spawnExePath "C:\MMO\MMO.exe" -startCentralServer -startDatabaseServer -machineAddress "192.168.1.103"

**Comment by cetinkrt** [comment]
and i watch ur video run linux and windows server

**Comment by insthync** [comment]
Are you sure that your command is correct?

**Comment by insthync** [comment]
Your command is wrong

**Comment by cetinkrt** [comment]
i understand thanks for help, if I asked you for support, how many dollars would you help?

**Comment by insthync** [comment]
Did you run a server by shortcut?

**Comment by cetinkrt** [comment]
yes, I ran it with a shortcut

**Comment by insthync** [comment]
Check your command in the shortcut, check that the `-startDatabaseServer` is missing or not
