### ISSUE TITLE
v1.84 Mount issue

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#2184]
When trying to get on a mount even when you are very close, the following message appears
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/7eb71166-3d19-43c6-9755-30f4e8af31ef)

**Comment by insthync** [comment]
Is it in conversation distance's range ?

**Comment by Blunnyn** [comment]
Yes, the mount is on the side of the character and the range is set to 5

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/5869ee5b-6b35-4b94-a0fb-da52b4e46c52)
