### ISSUE TITLE
Damageable hitbox problem.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2185]
hello this problem still persists.

Sometimes this problem occurs when I attack a creature, it does not damage the creature, what should I do?

Version: 1.84

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/c162e0e8-6071-42fd-a34c-87c44c640e33)

**Comment by insthync** [comment]
It can occur when it is found to attack speed hacking, so it won't apply damage. If you want to fix it you may try to change speed hack avoidance number in `DefaultCharacterAttackComponent` -> `ProceedAttackStateAtServer` function
