### ISSUE TITLE
Can Backward Sprint in the PlayerCharacterEntity Doesnt work.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2188]
I got my Can Backward Sprint disabled on my characters but I still can sprint while going backward. (Using ShooterController)

**Comment by insthync** [comment]
Please upload a video when you sprint backward

**Comment by Eniotnacram** [comment]
There is the link of the problem:
https://medal.tv/games/requested/clips/1nb5vOyoV1c1Oq/d13376V4xzXq?invite=cr-MSx1T3MsNDQ3NDMxODYs

**Comment by Eniotnacram** [comment]
Im using the Character Controller

**Comment by Eniotnacram** [comment]
There is another video that is clearer: https://medal.tv/games/screen-capture/clips/1npWSFmUWB45V9/d13375KWB3XB?invite=cr-MSxISWMsNDQ3NDMxODYs

Using fresh 1.84 kit, MMO, shooter controller.

Seems like the server is cancelling the movement but character is still able to sprint backward even tho its desactivated. (Using Character Controller)
