### ISSUE TITLE
Body Parts skinned mesh renderer Issue

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2189]
It seems that when using the skinned mesh renderer on the model it is not able to change the material (the model changes normally).

(Video) https://gyazo.com/c3d7c174a186433d38523348364bf549

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/f5dd4bee-f8bc-4c05-9d44-91da8ba9e59a)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/318dba61-61b2-4e17-a7c6-d95fcb247ec0)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/7b811cfb-5e71-4355-a900-f3226abb3857)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/28443394-f754-4c3a-89d8-bb1b9011b820)

**Comment by khongtuong** [comment]
https://discord.com/channels/460801727789137920/460856634302922763/1137201442009133167

**Comment by juniormagalhaes** [comment]
I don't know if it's the right way, but I replace the MeshRenderer to Renderer only, and apparently it works fine.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/3dd1593b-741f-4ae2-b901-2c796b7d01aa)

**Comment by insthync** [comment]
Maybe because your part is skinned mesh, so you can change codes like you did to make it able to set materials
