### ISSUE TITLE
Cannot access player storage on mmo

### ISSUE THREAD

**Issue by JestHWas** [suriyun-production/mmorpg-kit-docs#219]
Cannot access the player storage in mmo version for 1.53. Unity 2019.3

Re-creation:
- Import into a new project
- Create a new account
- Go to an NPC and click player storage
- Click on Open storage.
- Get a message saying that it cannot access storage

This seems to be down to the storage id not matching the player id.

**Comment by insthync** [comment]
[MMORPG_KIT-FixInvalidStorageOwner.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4184300/MMORPG_KIT-FixInvalidStorageOwner.zip)
Fix by this package, I will reupload 1.53 which includes this fix, Thank you for bug report :p.

**Comment by JestHWas** [comment]
Has this already been uploaded to 1.53

**Comment by insthync** [comment]
Yep.

**Comment by JestHWas** [comment]
Fixed thanks
