### ISSUE TITLE
Random Stat UI question

### ISSUE THREAD

**Issue by TheJuicer1** [suriyun-production/mmorpg-kit-docs#2190]
Is there a way to separate random Stat values on item UI? so player can tell what is random stat and what is base normal stat/ It seems the current system combines the stats together random+base in the UI

**Comment by insthync** [comment]
Try setup UI by using `UIItemRandomBonus` component, and set it to `UICharacterItem` -> `uiItemRandomBonus`

**Comment by molonlabe1337** [comment]
thank you!

**Comment by TheJuicer1** [comment]
Thank you it works
