### ISSUE TITLE
1.84 Mysql character_pk

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#2192]
in the mysql database there is no table character_pk, esto pasa solo en mysql en sqlite funciona correctamente.

CREATE TABLE IF NOT EXISTS character_pk (
     id VARCHAR(255) NOT NULL PRIMARY KEY,
     isPkOn TINYINT(1) NOT NULL DEFAULT 0,
     lastPkOnTime INT NOT NULL DEFAULT 0,
     pkPoint INT NOT NULL DEFAULT 0,
     consecutivePkKills INT NOT NULL DEFAULT 0,
     highestPkPoint INT NOT NULL DEFAULT 0,
     highestConsecutivePkKills INT NOT NULL DEFAULT 0
) ENGINE=InnoDB;

**Comment by khongtuong** [comment]
simple just delete last row (1.84 maybe) in  _migration table, server will do the rest
