### ISSUE TITLE
Invalid Data

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2194]
I migrated my project to version 1.84, when testing the local mmo mode, when creating the character this error appears, what could it be? the prefabs are in the database.

in single player mode it works

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/cc88694a-e204-43c4-a9b4-3a5866dd4992)

**Comment by insthync** [comment]
Maybe a factions

**Comment by insthync** [comment]
Your game has locked factions? or you didn't use factions for your game?

**Comment by juniormagalhaes** [comment]
> Your game has locked factions? or you didn't use factions for your game?

locked factions

**Comment by insthync** [comment]
https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/570381c36aaf4876ebcb0c9e02796625f6d55166
