### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2195]
the issue of the previous error was resolved, it was the same faction, but now this error appears when clicking on create the character

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/28a36abb-25b6-4fbe-b8b4-5a1dfecc5a72)

and when I try to log in the same account again the same error happens

**Comment by juniormagalhaes** [comment]
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at MultiplayerARPG.MMO.DatabaseNetworkManager.ReadCharacters (LiteNetLibManager.RequestHandlerData requestHandler, MultiplayerARPG.MMO.ReadCharactersReq request, LiteNetLibManager.RequestProceedResultDelegate`1[TResponse] result) [0x0004e] in <21238283bcaa4245ad185b792b2cc3f9>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.MMO.<ReadCharacters>d__43:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<ReadCharacters>d__43&)
MultiplayerARPG.MMO.DatabaseNetworkManager:ReadCharacters(RequestHandlerData, ReadCharactersReq, RequestProceedResultDelegate`1)
LiteNetLibManager.LiteNetLibRequestHandler`2:InvokeRequest(RequestHandlerData, RequestProceededDelegate)
LiteNetLibManager.TransportHandler:ProceedRequest(Int64, NetDataReader)
LiteNetLibManager.TransportHandler:ReadPacket(Int64, NetDataReader)
LiteNetLibManager.LiteNetLibServer:OnServerReceive(TransportEventData)
LiteNetLibManager.LiteNetLibServer:Update()
LiteNetLibManager.LiteNetLibManager:Update()

NullReferenceException: Object reference not set to an instance of an object
  at MultiplayerARPG.MMO.DatabaseNetworkManager.ReadCharacters (LiteNetLibManager.RequestHandlerData requestHandler, MultiplayerARPG.MMO.ReadCharactersReq request, LiteNetLibManager.RequestProceedResultDelegate`1[TResponse] result) [0x0004e] in <21238283bcaa4245ad185b792b2cc3f9>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.MMO.<ReadCharacters>d__43:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<ReadCharacters>d__43&)
MultiplayerARPG.MMO.DatabaseNetworkManager:ReadCharacters(RequestHandlerData, ReadCharactersReq, RequestProceedResultDelegate`1)
LiteNetLibManager.LiteNetLibRequestHandler`2:InvokeRequest(RequestHandlerData, RequestProceededDelegate)
LiteNetLibManager.TransportHandler:ProceedRequest(Int64, NetDataReader)
LiteNetLibManager.TransportHandler:ReadPacket(Int64, NetDataReader)
LiteNetLibManager.LiteNetLibServer:OnServerReceive(TransportEventData)
LiteNetLibManager.LiteNetLibServer:Update()
LiteNetLibManager.LiteNetLibManager:Update()

**Comment by insthync** [comment]
Try build a development guild and test it to show which line is source of error

**Comment by juniormagalhaes** [comment]
> Try build a development guild and test it to show which line is source of error

I literally just imported the database, it was causing the error, thanks
