### ISSUE TITLE
(PAID REQUEST) Climbing. Can be simple Ladder climbing

### ISSUE THREAD

**Issue by timspurgeon** [suriyun-production/mmorpg-kit-docs#2196]
Can we get climbing implemented? Will gladly pay

**Comment by insthync** [comment]
How much you can pay?

**Comment by timspurgeon** [comment]
What is fair pay for you? Do you work by hour or by job? I want to be fair
and I would also like to have maybe an add-on or part of the  kit for
cars,planes etc. I wish I could code lol. I code enough to mess up things.
Let me know how much for climbing and if interested in other wishes. I
would also like to have these as part of the kit for everyone to enjoy if
that is how you want it. Very excited to hear back. Love your work. The kit
is so much fun.

 Thank you and have a Blessed Day!!

**Comment by timspurgeon** [comment]
Hello,  Did you come to a price?

**Comment by insthync** [comment]
https://ko-fi.com/insthync/goal?g=0

**Comment by timspurgeon** [comment]
How can I donate to you page? I see no support or donate button?

Have a Blessed Day!!

**Comment by timspurgeon** [comment]
Thank you!!!
cant wait to try it out.

Have a Blessed day!!
