### ISSUE TITLE
sometimes the monster doesn't take the damage

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2197]
sometimes the monster does not receive the damage, and this error occurs on the server

https://gyazo.com/0bc1b46d9db1d450e8cb48199eab4c18

**Comment by insthync** [comment]
Because the server detects speed hack, you may try to change `DefaultCharacterAttackComponent` -> `ProceedAttackStateAtServer` speed hack checking number

**Comment by juniormagalhaes** [comment]
Thanks, that's right, the attack animation was without the Trigger Duration Rates.
