### ISSUE TITLE
Build client issue

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2198]
when building only the client using the Setup for MMO Build gives this error.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/8045b717-7ee7-41f5-b52d-35d36fcfef47)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/2d0ae172-93f6-4432-a401-9a745dad4085)

**Comment by insthync** [comment]
I did not write that script, but if you want to try to fix it you have to learn about [this](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) and use `UNITY_SERVER` condition to fix it.
