### ISSUE TITLE
Player Character Body Part Component

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2199]
Hello,

Tell me if i dont understand it properly, but for EACH body part that we want to be able to modify we need to add a new "Player Character Body Part Component" script to our character?

So in my case, if 7 body parts are modifiable in the home scene, (hair, shoes, eyes, eyebrows, etc) I need to add 7 "Player Character Body Part Component" script to my character prefab?

I really dont like this approach and if it's the case, if possible, it would be very nice to modify the Player Character Body Part Component script to be able to have multiples Body parts and that way, it will let us put only 1 "Player Character Body Part Component" script on our characters.

So multiple Model Setting IDs (Color setting IDs), and each of those their own options.

Thank you :)

**Comment by insthync** [comment]
Yes, you have to add multiple components, and I won't change it.

You can create a new component copy those codes to create yours.

**Comment by Eniotnacram** [comment]
Well it makes it very complex, because i need to modify 37 scripts, may I modify your script directly to make that work, and when its finished let you review then and add them to the kit? 

No one will want to have 12 scripts for each body parts that they want to modify.
