### ISSUE TITLE
Losing guild storage items

### ISSUE THREAD

**Issue by JestHWas** [suriyun-production/mmorpg-kit-docs#220]
The same bug - https://github.com/suriyun-production/mmorpg-kit-docs/issues/210

This bug is also occurring with guild storage.

**Comment by insthync** [comment]
[MMORPG_KIT-FixMissingItemId.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4184303/MMORPG_KIT-FixMissingItemId.zip)
Fix by this package, I will reupload 1.53 which includes this fix, Thank you for bug report :p.

**Comment by JestHWas** [comment]
Fixed
