### ISSUE TITLE
QualitySettings ERROR, Using unity 2021 1.84b

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2200]
Hello, Its a simple fix, but when using unity 2021, on a fresh kit, we have those errors:

Assets\UnityMultiplayerARPG\Core\GraphicSettings\Scripts\TextureQualitySetting.cs(29,61): error CS0117: 'QualitySettings' does not contain a definition for 'globalTextureMipmapLimit'
Assets\UnityMultiplayerARPG\Core\GraphicSettings\Scripts\TextureQualitySetting.cs(68,33): error CS0117: 'QualitySettings' does not contain a definition for 'globalTextureMipmapLimit'
Assets\UnityMultiplayerARPG\Core\GraphicSettings\Scripts\TextureQualitySetting.cs(83,33): error CS0117: 'QualitySettings' does not contain a definition for 'globalTextureMipmapLimit'

**Comment by insthync** [comment]
Already fixed 5 days ago

https://github.com/insthync/unity-graphic-settings

**Comment by Eniotnacram** [comment]
I just imported 1.84b 1h ago and the errors occurs.
