### ISSUE TITLE
1.84 mount issue

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#2202]
Using version 1.84 when wearing a mount "disables" the armor that is equipped (including the hair that was set at character creation).

https://gyazo.com/e945b0f8949dea867785a7cf98365dd7

**Comment by insthync** [comment]
How can I try it?

**Comment by insthync** [comment]
@juniormagalhaes I think it should not, have to try.

**Comment by insthync** [comment]
Did you use the same equip sockets for all models?

**Comment by juniormagalhaes** [comment]
no, each body part is a socket, but i have hair skins that overlap the base hair.

https://gyazo.com/4fef92a84f58f383204d8d0050197196

**Comment by insthync** [comment]
@juniormagalhaes your problem is related to mounting ?

**Comment by juniormagalhaes** [comment]
> 
Yes, the problem is that when the base hair and equippable hair have the same priority when you get on and off the mount, it changes, just like the clothes and hair of Blunnyn's character that keeps changing when getting on and off the mount.

**Comment by juniormagalhaes** [comment]
priority 0 it happens

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/ee46a4f4-bf24-48a8-b28f-22ab8cc428b6)


https://gyazo.com/9eb6c9078cb617b07cd43d704def87c5


priority 1 does not happen

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/7d1380bc-4a31-476f-bd91-16e4c25f5859)

https://gyazo.com/39e90105b6145fd5f098740db6b4a264

it's not a kit error, it's just the misconfigured item

Unless it's something else he's showing, but in my case it was this

**Comment by insthync** [comment]
If you have `MORE THAN 1 MODEL` which will be equipped `INTO 1 SLOT`, you must set a different priority to make, the one which has the highest will be shown, otherwise will be hidden, that is it.

**Comment by juniormagalhaes** [comment]
> 

Yep

**Comment by Blunnyn** [comment]
I think it's not because of priority.
In my project I set the skin of the character as follows
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/bdd62230-3445-4f07-9b4b-71792f58dbad)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/10fdce14-2d6c-4e3e-afda-974e6889ba37)

When you choose the class (warrior, magician, archer) one or the other suit is put on (depending on the skin color)
https://gyazo.com/82ebc751dd23f7da8f67c15447d46e4f
And it is configured like this:

Class: Warrior
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/08b38766-c9a6-4361-948a-e6899e8757b8)
Item: Clase 0
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/1652c1e8-d7d1-47aa-975e-84f59fc023c0)

The problem is that when using a mount, it ignores all of the above and disables the item that was set to the class and currently equipped armor.
https://gyazo.com/88ffd1ef0df5c278470a9345f517ca29

**Comment by insthync** [comment]
What is `TrajeDefault` how is it showing while mounting?

**Comment by Blunnyn** [comment]
It's just a default model.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/ebb410d2-aea7-4c36-9c13-f62ebb50a0b4)
If I changed SkinColor in this way(not includingDefaultSuit)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/48af0589-d708-423f-8028-fc6b207722f8)
This happens:
https://gyazo.com/b601b112dcc3a9a8464085775005999f

**Comment by insthync** [comment]
Can you send your project including with your character prefab and character data to me (to my email: ittipon.bay@gmail.com)

**Comment by insthync** [comment]
Try this

[MMORPG_KIT-FixMissingBodyPartSetupEvents.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/12299755/MMORPG_KIT-FixMissingBodyPartSetupEvents.zip)

**Comment by juniormagalhaes** [comment]
I managed to reproduce the bug in my project, I put your fix, in the game it's normal no, the parts don't disappear but this error appears in the console

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/eb352497-73a3-4435-ae34-215860796456)

**Comment by Blunnyn** [comment]
Yes, it works now, as juniormagalhaes says, it indicates these errors. But it works.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/38b5d6bb-b89a-43ac-95ee-ea98688371d6)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/05994e86-30b5-4ec1-a8b9-bb015359ed14)

**Comment by insthync** [comment]
`OnBeforeUpdate...` are debugging messages, you have to find and delete it.

**Comment by juniormagalhaes** [comment]
when removing the debug it is giving this error, it still works, but this error appears.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/324aebed-827f-4652-a039-d5fa3048a547)

**Comment by insthync** [comment]
Try add codes to check null variables.
