### ISSUE TITLE
Can players change the name of an item?

### ISSUE THREAD

**Issue by ozantekce** [suriyun-production/mmorpg-kit-docs#2203]
I want to allow players to change their item names. For example, a player can change the name of a weapon to 'MyWeapon'. Can I do this?

**Comment by insthync** [comment]
Can you do coding?, you will have to add a new variable for the item name, and then have to add serialize/deserialize codes, then implement item name changing feature later.

**Comment by ozantekce** [comment]
Yes actually I tried that, this way the name is reset when the game is closed.

**Comment by insthync** [comment]
You also have to make it save. If you are making an offline games, you will have to add serialize/deserialize codes to `CharacterItemSerializationSurrogate` and `StorageCharacterItemSerializationSurrogate`.

If you are making an online games, you will have to add CRUD codes to `MySQLDatabase_CharacterItem` and `MySQLDatabase_StorageItem`.

Or `SQLiteDatabase_CharacterItem` and `SQLiteDatabase_StorageItem`, for SQLite database.

**Comment by ozantekce** [comment]
Okay, thank you.
