### ISSUE TITLE
Colors in the UIBodyPartManager not showing.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2206]
The colors in the UIBodyPartManager not showing when the game is freshly open. We need to "refresh" the page to make them show.

This is not hapening when using Sqlite but bug occur using MySql.

There is the video:
https://medal.tv/games/screen-capture/clips/1octfDpSnGxyic/d1337GPF6OrH?invite=cr-MSxQUzEsNDQ3NDMxODYs****

**Comment by insthync** [comment]
It does not connect to database when create character, so it is not because of Sqlite and MySQL

**Comment by Eniotnacram** [comment]
With further investigation I cant find the reason why I need to "refresh" to be able to see the color options. Any ideas where I should check?

**Comment by Eniotnacram** [comment]
@insthync I Found the problem, the UIBodyPartManager wasnt showing the colors instantly. It was waiting for a selection to show the colors (if available). The problem is, if the first model has color, the colors wasnt showing even tho the first model is automatically selected. So the player needed to unselect the model and select it again to show the colors.

There is the necessary modifications to instantly show the colors if they are available on the selected model.
using UnityEngine;

namespace MultiplayerARPG
{
    public class UIBodyPartManager : MonoBehaviour
    {
        public string modelSettingId;

        [Header("Model Option Settings")]
        public GameObject uiModelRoot;
        public UIBodyPartModelOption uiSelectedModel;
        public UIBodyPartModelOption uiModelPrefab;
        public Transform uiModelContainer;

        [Header("Color Option Settings")]
        public GameObject uiColorRoot;
        public UIBodyPartColorOption uiSelectedColor;
        public UIBodyPartColorOption uiColorPrefab;
        public Transform uiColorContainer;

        private UIList _modelList;
        public UIList ModelList
        {
            get
            {
                if (_modelList == null)
                {
                    _modelList = gameObject.AddComponent<UIList>();
                    _modelList.uiPrefab = uiModelPrefab.gameObject;
                    _modelList.uiContainer = uiModelContainer;
                }
                return _modelList;
            }
        }

        private UIBodyPartModelListSelectionManager _modelSelectionManager;
        public UIBodyPartModelListSelectionManager ModelSelectionManager
        {
            get
            {
                if (_modelSelectionManager == null)
                    _modelSelectionManager = gameObject.GetOrAddComponent<UIBodyPartModelListSelectionManager>();
                _modelSelectionManager.selectionMode = UISelectionMode.SelectSingle;
                return _modelSelectionManager;
            }
        }

        private UIList _colorList;
        public UIList ColorList
        {
            get
            {
                if (_colorList == null)
                {
                    _colorList = gameObject.AddComponent<UIList>();
                    _colorList.uiPrefab = uiColorPrefab.gameObject;
                    _colorList.uiContainer = uiColorContainer;
                }
                return _colorList;
            }
        }


        private UIBodyPartColorListSelectionManager _colorSelectionManager;
        public UIBodyPartColorListSelectionManager ColorSelectionManager
        {
            get
            {
                if (_colorSelectionManager == null)
                    _colorSelectionManager = gameObject.GetOrAddComponent<UIBodyPartColorListSelectionManager>();
                _colorSelectionManager.selectionMode = UISelectionMode.SelectSingle;
                return _colorSelectionManager;
            }
        }

        private UISelectionManagerShowOnSelectEventManager<PlayerCharacterBodyPartComponent.ModelOption, UIBodyPartModelOption> _modelUIEventSetupManager = new UISelectionManagerShowOnSelectEventManager<PlayerCharacterBodyPartComponent.ModelOption, UIBodyPartModelOption>();
        private UISelectionManagerShowOnSelectEventManager<PlayerCharacterBodyPartComponent.ColorOption, UIBodyPartColorOption> _colorUIEventSetupManager = new UISelectionManagerShowOnSelectEventManager<PlayerCharacterBodyPartComponent.ColorOption, UIBodyPartColorOption>();
        private BaseCharacterModel _model;
        private PlayerCharacterBodyPartComponent _component;

        private void OnEnable()
        {
            _modelUIEventSetupManager.OnEnable(ModelSelectionManager, uiSelectedModel);
            _colorUIEventSetupManager.OnEnable(ColorSelectionManager, uiSelectedColor);
            ModelSelectionManager.eventOnSelect.RemoveListener(OnSelectModelUI);
            ColorSelectionManager.eventOnSelect.RemoveListener(OnSelectColorUI);
            ModelSelectionManager.eventOnSelect.AddListener(OnSelectModelUI);
            ColorSelectionManager.eventOnSelect.AddListener(OnSelectColorUI);
        }

        private void OnDisable()
        {
            _modelUIEventSetupManager.OnDisable();
            _colorUIEventSetupManager.OnDisable();
            ModelSelectionManager.eventOnSelect.RemoveListener(OnSelectModelUI);
            ColorSelectionManager.eventOnSelect.RemoveListener(OnSelectColorUI);
        }

        private void OnSelectModelUI(UIBodyPartModelOption ui)
        {
            if (_component == null)
                return;
            _component.SetModel(ui.Index);
            _model.UpdateEquipmentModels();
            SetupColorList();
        }

        private void OnSelectColorUI(UIBodyPartColorOption ui)
        {
            if (_component == null)
                return;
            _component.SetColor(ui.Index);
            _model.UpdateEquipmentModels();
        }

        public void SetCharacterModel(BaseCharacterModel model)
        {
            _model = model;
            _component = null;
            PlayerCharacterBodyPartComponent[] comps = _model.transform.root.GetComponentsInChildren<PlayerCharacterBodyPartComponent>();
            for (int i = 0; i < comps.Length; ++i)
            {
                if (!modelSettingId.Equals(comps[i].modelSettingId))
                    continue;
                comps[i].SetupCharacterModelEvents(model);
                _component = comps[i];
                break;
            }
            SetupModelList();
        }

        private void SetupModelList()
        {
            if (_component == null || _component.MaxModelOptions <= 0)
            {
                if (uiModelRoot != null)
                    uiModelRoot.SetActive(false);
                if (uiColorRoot != null)
                    uiColorRoot.SetActive(false);
                return;
            }

            if (uiModelRoot != null)
                uiModelRoot.SetActive(true);

            // Setup model list
            ModelSelectionManager.Clear();
            ModelList.HideAll();
            ModelList.Generate(_component.ModelOptions, (index, data, ui) =>
            {
                UIBodyPartModelOption uiComp = ui.GetComponent<UIBodyPartModelOption>();
                uiComp.Data = data;
                uiComp.HashedSettingId = _component.GetHashedModelSettingId();
                uiComp.Index = index;
                ModelSelectionManager.Add(uiComp);
                if (index == 0)
                {
                    uiComp.OnClickSelect();
                    SetupColorList();
                }
            });
        }

        private void SetupColorList()
        {
            if (_component == null || _component.MaxColorOptions <= 0)
            {
                if (uiColorRoot != null)
                    uiColorRoot.SetActive(false);
                return;
            }

            if (uiColorRoot != null)
                uiColorRoot.SetActive(true);

            // Setup color list
            ColorSelectionManager.Clear();
            ColorList.HideAll();
            ColorList.Generate(_component.ColorOptions, (index, data, ui) =>
            {
                UIBodyPartColorOption uiComp = ui.GetComponent<UIBodyPartColorOption>();
                uiComp.Data = data;
                uiComp.HashedSettingId = _component.GetHashedColorSettingId();
                uiComp.Index = index;
                ColorSelectionManager.Add(uiComp);
                if (index == 0)
                {
                    uiComp.OnClickSelect();
                    OnSelectColorUI(uiComp);
                }
            });
        }
    }
}

Please add this modifications to the core kit, because  it will be helpfull to anyone that is using this.

**Comment by insthync** [comment]
Okay
