### ISSUE TITLE
MMO party bug.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2209]
Hello, when the guy in the party exits the game he still appears in the party and if I cut the monster it gives this error and the monster does not respawn.

![Adsız](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/2589bdcb-b463-48a5-81ec-0619db61c84b)

**Comment by insthync** [comment]
Okay, I will check it, but you sould attach log files, because I cannot find anything from that image

**Comment by insthync** [comment]
But when the party member still does not leave the party it works as intended, not a bug.

**Comment by CLAXES** [comment]
When the person in the party leaves the game, this problem occurs when the other person in the party cuts monsters. Can we make a system such that the person who leaves the game automatically leaves the party, and if the party leader is the party leader, the party is handed over to someone else?

**Comment by CLAXES** [comment]
I made a video you can watch.

[Video](https://www.youtube.com/watch?v=59CFIIB0LPM)

**Comment by CLAXES** [comment]
The problem was caused by a code I added, sorry.
