### ISSUE TITLE
Characters are created indefinitely

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#221]
![sfsdfsdf](https://user-images.githubusercontent.com/58978516/74237672-6b6b4480-4d17-11ea-9919-203374adf31c.png)

Characters are created indefinitely

I want to make less than four.
Where can I modify it?

**Comment by Koodetat** [comment]
yes it would be useful to have a parameter to limit the number of characters created.

**Comment by ybb95** [comment]
> yes it would be useful to have a parameter to limit the number of characters created.

Where can I use it?

**Comment by insthync** [comment]
I will add it in next version. :)

**Comment by ybb95** [comment]
> I will add it in next version. :)

Can you tell me where to coding?
I'll do it.

I'm sorry to keep you busy.

**Comment by Callepo** [comment]
u could just create a simple script that checks the Container list size or something
if its 4 it turns the Create new button inactive ( unclickable)
dont need much diving into kit to do it just simple ui work

**Comment by insthync** [comment]
In 1.53b:
- Add `maxCharacterSaves` setting to `GameInstance` but does not validating with server when creating character yet. Just count characters after loaded and trigger `UICharacterList`'s events.
- Add `eventOnAbleToCreateCharacter` event to `UICharacterList` which will be triggered when character count not reached `maxCharacterSaves` setting yet.
- Add `eventOnNotAbleToCreateCharacter` event to `UICharacterList` which will be triggered when character count reached `maxCharacterSaves` setting.
