### ISSUE TITLE
MMO skill display error.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2210]
Hello, the skills do not appear when I enter and exit the game or when I change the map, I added a video you can check it out.

[Video](https://www.youtube.com/watch?v=GJj22AnX6Ew)

**Comment by insthync** [comment]
![Screenshot_786](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/f286bda0-7d54-4c35-9019-9831e6172a26)

**Comment by CLAXES** [comment]
I did what you said, sometimes it comes and sometimes it doesn't

**Comment by insthync** [comment]
![Screenshot_787](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/fb874535-4930-46e6-81c1-d4eb4342331c)

Try this.

**Comment by CLAXES** [comment]
Unfortunately the same problem still persists.

**Comment by insthync** [comment]
I can't reproduce it

**Comment by insthync** [comment]
![Screenshot_788](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/b4528d0a-6d23-47b3-9748-acf809959af1)

Try this.

**Comment by CLAXES** [comment]
There's no difference, it's still the same.

**Comment by insthync** [comment]
Okay, try this

![Screenshot_789](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/33ef693d-5d35-4794-9d3a-f813f4984dd3)

![Screenshot_790](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/9fd49fae-a225-4d9a-ad70-4f934275a043)

![Screenshot_791](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/ff415529-9cf4-48cc-82e1-6f756e194d8f)

**Comment by CLAXES** [comment]
Now working properly thank you very much.
