### ISSUE TITLE
Invaild Data mmo 2d

### ISSUE THREAD

**Issue by profaiith** [suriyun-production/mmorpg-kit-docs#2211]
i get inviald data with the 2D kit when creating new character

**Comment by insthync** [comment]
How?

**Comment by profaiith** [comment]
i found the fix in the code.

**Comment by profaiith** [comment]
this are the settings/code that work for me. 
That was the problem loading the kit in to a new project. 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/3957746/3144fd54-2217-4ce6-9c58-6dc8af753435)

**Comment by profaiith** [comment]
also i added this file.
dont know if that matters...?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/3957746/795cd64d-8cd8-4383-a6d3-92eeb8f56027)
