### ISSUE TITLE
[Ask] Is there any Documentation or Walkthrough to Integrate MMORPG Kit to Unity Gaming Service (server hosting) ?

### ISSUE THREAD

**Issue by anakpayah** [suriyun-production/mmorpg-kit-docs#2212]
hy, iam unity junior developer here.

i would ask u about Unity new service feature, its Unity Gaming Multiplay. Can this kit Integrate with Unity hosting server? if can, can you adding any documentation of doing so? or even a Walkthrough or two to your youtube channel.

**Comment by anakpayah** [comment]
and, is there any newbie helper in your discord server(Suriyan MMORPG) for me as beginner developer using your kit?

**Comment by insthync** [comment]
No UGS integration so no its document. The discord server is not mine, and I am not online there too, so I don't know about it nowadays.

**Comment by LordPhrozen** [comment]
> is there any newbie helper in your discord server

Theres quite a few active people in the discord who help out. Just dont expect split second results, as everyone there helping, is volunteering their time.
