### ISSUE TITLE
[Error] there in some code error when i create farm land object (the error is in GrowControllerEntity.cs)

### ISSUE THREAD

**Issue by anakpayah** [suriyun-production/mmorpg-kit-docs#2213]
hy, i would like to report error code about some your code when i follow your walkthrough in a video:
https://www.youtube.com/watch?v=tsQ4cGPIb2c&list=PLbtX3Q3DrvKzIP2Hly-X1w6sNWlDEJ4sF&index=16

i got your code reference on your patreon link that you provide on thats videos description
https://www.patreon.com/posts/55824460

the error code in `GrowControllerEntity.cs` is below:
```c#
ItemDropEntity.DropItem(this, convertedItem, new uint[0]);
```
the code above is conflict with other script `ItemDropEntity.cs` on this function :
```c#
public static ItemDropEntity DropItem(BaseGameEntity dropper, CharacterItem dropData, IEnumerable<string> looters) 
{
...
}
```

the error says:
`GrowControllerEntity.cs(109,50): error CS1503: Argument 3: cannot convert from 'uint[]' to 'System.Collections.Generic.IEnumerable<string>`

**Comment by moepi2k** [comment]
this is an outdated addon from a community member and not from the kits creator

**Comment by anakpayah** [comment]
oh i see, sorry for the misunderstand it. and thanks for your answer
