### ISSUE TITLE
Character Controller Entity Server sync problem

### ISSUE THREAD

**Issue by mmciftciler** [suriyun-production/mmorpg-kit-docs#2214]
It is normal skill this video.
https://github.com/suriyun-production/mmorpg-kit-docs/assets/118010169/7e74a632-308c-4d1d-a945-ea50b34df334

Server connected and used skill this video. the result is strange

https://github.com/suriyun-production/mmorpg-kit-docs/assets/118010169/6f0b5e13-d391-43ff-94e6-237b2c686bdf

I guess there is a difference between animation time and server time.

**Comment by insthync** [comment]
Server auth movement?

**Comment by mmciftciler** [comment]
Not Secure

**Comment by insthync** [comment]
The client might find the position synced from the server is very far from the snap threshold so the client snaps the client position to the server position.

**Comment by mmciftciler** [comment]
Tried snapThreshold equalizing 5, 1000, and 0.001. Tried "Server Authoritive" mode. The result is the same. What is the solution? Do these attempts require a server build again each time?

**Comment by mmciftciler** [comment]
Is it possible to stop location sync when using the skill?

**Comment by insthync** [comment]
Possible by adding codes to do it.

**Comment by insthync** [comment]
In the next version (1.85b), I've added config to skip entity movement while playing action animation

![Screenshot_858](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/a3ecb0fc-dcbf-4407-a006-7bd34681a3b9)
