### ISSUE TITLE
Paid Request: Press "Escape" to close / deselect active window

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2215]
Quality of life request for the following:
- Press Escape to deselect mob (not opening settings).
- Press Escape to close active window rather than pressing button (not opening settings).

**Comment by Eniotnacram** [comment]
All of this is UI related, specific for each projects. Dont ask suri for basic things like this... I've made my own script to close active windows using ESC. This is 100% client sided and not kit related.

**Comment by LordPhrozen** [comment]
> All of this is UI related, specific for each projects. Dont ask suri for basic things like this... I've made my own script to close active windows using ESC. This is 100% client sided and not kit related.

I don't disagree with you, but on the flipside, this is something frustrating to those who aren't super UI focused. I don't see the way its currently working to be desirable for anyone, and with that in mind, a decent candidate for improvement. 

However if you've already solved this in a quick and easy way, I'm sure plenty of folk would love this to be added to the discords addons section.

**Comment by Eniotnacram** [comment]
> > All of this is UI related, specific for each projects. Dont ask suri for basic things like this... I've made my own script to close active windows using ESC. This is 100% client sided and not kit related.
> 
> I don't disagree with you, but on the flipside, this is something frustrating to those who aren't super UI focused. I don't see the way its currently working to be desirable for anyone, and with that in mind, a decent candidate for improvement.
> 
> However if you've already solved this in a quick and easy way, I'm sure plenty of folk would love this to be added to the discords addons section.

I also understand what you are saying, I know for a fact that no game will be released with the current UI implementation of the kit. But I feel like Suri's attention should be in the core aspect of the kit, new functionality, etc than UI. 

I'll gladly post my scripts as add-ons if it could help anyone :)
