### ISSUE TITLE
ImpacrEffects

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2217]
when using impact effects on a raycast weapon the impact effect does not work, I tested it with a melee weapon and it works normally.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/e8b6ed5c-618b-4574-8fd4-2685b1ae2479)

**Comment by insthync** [comment]
![Screenshot_794](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/55913953-7e64-4929-934b-a6b3bcfc6df3)
