### ISSUE TITLE
[Error] skill requirements

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#2218]
This error occurs when gold is set in skill requirements. 
If you set the gold to 0, no error occurs.   

kit version 1.84b2,  Unity version 2022.3.4f

![111111111 (1)11](https://github.com/suriyun-production/mmorpg-kit-docs/assets/58978516/65babf27-0f7a-499f-bc97-085db3a92ad1)

![2222222222 (1)](https://github.com/suriyun-production/mmorpg-kit-docs/assets/58978516/b22b4f3d-3ebd-492c-8d15-45eed8ad02b8)

**Comment by insthync** [comment]
Add this

![Screenshot_795](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/159ca63b-b8b8-4e3e-bb21-5e30e5691057)
