### ISSUE TITLE
Player rotation is jittery when use shooter controller fps

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2219]
https://gyazo.com/aa82b4b50174ba3fa84c2edbb7bdde30

i added 2 simple sphere, one directly on the player prefab (left sphere) and the other on the camera (right sphere)
when you rotate player, the player rotation is jittery, it looks really bad when you use fps with tps body (not fps arms)

any idea what cause it and how to fix?

**Comment by insthync** [comment]
I actually don't know too, it did not have one proper solution, some solution works for specific transform movement, you can try googling it.

The easiest solution might be to move the camera to be a child of the character entity, and rotate the character entity, not the camera, because it is currently rotating the character follow the camera.

**Comment by moepi2k** [comment]
yea i tried already many things, but i cant find the issue. maybe best will as u said to make the camera a child of the player.

**Comment by moepi2k** [comment]
Yea followed it also and it wad really hard to understand. Also trying to instantiate the camera as a child of the pöayer instead of unparented object. This could solve the issue also. But yea best would def when the execution or is right

**Comment by insthync** [comment]
Try this in `ShooterPlayerCharacterController.cs`

Add codes in `LateUpdate`

```
            _cameraForward = CacheGameplayCameraController.CameraTransform.forward;
            _cameraForward.y = 0f;
            _cameraForward.Normalize();
            _targetLookDirection = _cameraForward;
            UpdateLookAtTarget();
```

![Screenshot_803](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/827160de-0267-4deb-9e0a-44a269d8536d)

Then in `CharacterControllerEntityMovement.cs` (or other built-in entity movement)

Move update rotation calling to late update

![Screenshot_803](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/695d05cd-3c85-4d00-835a-6f3a18734655)

**Comment by insthync** [comment]
Edit:  `ShooterPlayerCharacterController.cs`

Changes codes which I've told to add in LateUpdate to 
```
PlayingCharacterEntity.SetLookRotation(Quaternion.Euler(Vector3.up * CacheGameplayCameraController.CameraTransform.eulerAngles.y));
```

**Comment by insthync** [comment]
And may set execution order for shooter player character controller to be lower than the entity movement

**Comment by moepi2k** [comment]
its a bit better with the jitter but still has https://gyazo.com/523dcce64239445b4e0d10d029ff3866
also the rotation of the character is delayed compared to the camera rotation.

**Comment by insthync** [comment]
Try set execute order for `FollowCameraControls` to be lower than the shooter player character controller

**Comment by moepi2k** [comment]
ok added 
    [DefaultExecutionOrder(-1)] to ShooterPlayerCharacterController

and

    [DefaultExecutionOrder(-2)] to FollowCameraControls and now its fine

**Comment by moepi2k** [comment]
one thing for the KCC, since rotation is driven from the interface ICharacterController ->https://gyazo.com/d4c22b8365e153dc4ea9886ff3ce235b

how to put it in late update here?
