### ISSUE TITLE
Can't sign in to Google on Android device

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#222]
![sdfsd11](https://user-images.githubusercontent.com/58978516/74240366-2cd88880-4d1d-11ea-81fb-ff30dbeb0519.jpg)

Google login not available
I'm using digital ocean

mmo kit version 1.51
unity version 2018 4.14f1        
Googld play games plugin version 0.10.06

Is your script wrong?
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using LiteNetLibManager;
using GooglePlayGames;
using GooglePlayGames.BasicApi;

namespace MultiplayerARPG.MMO
{
    public class GooglePlayLogin : MonoBehaviour
    {
        public bool debugLogEnabled;
        public UnityEvent onLoginSuccess;
        public UnityEvent onLoginFail;

        private void Awake()
        {
#if UNITY_ANDROID
            var builder = new PlayGamesClientConfiguration.Builder()
                // requests the email address of the player be available.
                // Will bring up a prompt for consent.
                .RequestEmail()
                // requests a server auth code be generated so it can be passed to an
                //  associated back end server application and exchanged for an OAuth token.
                .RequestServerAuthCode(false)
                // requests an ID token be generated.  This OAuth token can be used to
                //  identify the player to other services such as Firebase.
                .RequestIdToken();
            var config = builder.Build();
            PlayGamesPlatform.InitializeInstance(config);
            PlayGamesPlatform.DebugLogEnabled = debugLogEnabled;
#endif
        }

        public void OnClickGooglePlayLogin()
        {
#if UNITY_ANDROID
            PlayGamesPlatform.Instance.SignOut();
            PlayGamesPlatform.Instance.Authenticate((success, message) => {
                if (success)
                {
                    // When google play login success, send login request to server
                    var idToken = PlayGamesPlatform.Instance.GetIdToken();
                    RequestGooglePlayLogin(idToken);
                }
                else
                {
                    // Show error message
                    UISceneGlobal.Singleton.ShowMessageDialog("Cannot Login", "Cannot Login with Google Play: " + message);
                }
            });
#else
            Debug.Log("Only Android can login with Google Play");
#endif
        }

        private void RequestGooglePlayLogin(string idToken)
        {
            UISceneGlobal uiSceneGlobal = UISceneGlobal.Singleton;
            if (string.IsNullOrEmpty(idToken))
            {
                uiSceneGlobal.ShowMessageDialog("Cannot login", "ID token is empty");
                return;
            }
            MMOClientInstance.Singleton.RequestGooglePlayLogin(idToken, OnLogin);
        }

        public void OnLogin(AckResponseCode responseCode, BaseAckMessage message)
        {
            ResponseUserLoginMessage castedMessage = (ResponseUserLoginMessage)message;
            switch (responseCode)
            {
                case AckResponseCode.Error:
                    string errorMessage = string.Empty;
                    switch (castedMessage.error)
                    {
                        case ResponseUserLoginMessage.Error.AlreadyLogin:
                            errorMessage = "User already logged in";
                            break;
                        case ResponseUserLoginMessage.Error.InvalidUsernameOrPassword:
                            errorMessage = "Invalid username or password";
                            break;
                    }
                    UISceneGlobal.Singleton.ShowMessageDialog("Cannot Login", errorMessage);
                    if (onLoginFail != null)
                        onLoginFail.Invoke();
                    break;
                case AckResponseCode.Timeout:
                    UISceneGlobal.Singleton.ShowMessageDialog("Cannot Login", "Connection timeout");
                    if (onLoginFail != null)
                        onLoginFail.Invoke();
                    break;
                default:
                    if (onLoginSuccess != null)
                        onLoginSuccess.Invoke();
                    break;
            }
        }
    }
}

**Comment by ybb95** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/034-how-to-integrate-google-play-login


I followed the guide

**Comment by insthync** [comment]
I will try it again this weekend but as I see it's said that you've canceled the login process

**Comment by ybb95** [comment]
> I will try it again this weekend but as I see it's said that you've canceled the login process

I have been struggling with this for a few days

Do it when you're not busy.
I think it'll be great if it's resolved.

**Comment by insthync** [comment]
I just update guide, add content about how to setup OAuth client, try follow that instructions https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/034-how-to-integrate-google-play-login

**Comment by insthync** [comment]
Hello, is that works?

**Comment by insthync** [comment]
I will close this, if you still having the problem, you can reopen it.
