### ISSUE TITLE
Cast Effects Skill

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2220]
It seems that the casting effects of the kills don't wait for the animation trigger to be executed, I don't know if that's how it should work, if that's how it should work, you can disregard this post.

**Comment by insthync** [comment]
How ?

**Comment by juniormagalhaes** [comment]
> How ?

When you put the skill activation animation on the character, the effect comes out before the animation is played


![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/97631a7e-0cb2-4011-b29d-fc9bf3eacc87)

**Comment by insthync** [comment]
You want the effect to be instantiated after animation "Played" or "Starting playing" ?

**Comment by juniormagalhaes** [comment]
> You want the effect to be instantiated after animation "Played" or "Starting playing" ?

at the same time that the hiit is applied, I think that if I delay the effect particles it should resolve.

**Comment by insthync** [comment]
![Screenshot_796](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/e7fd7956-ffcc-45ff-bed4-82dbc0e9b04d)

![Screenshot_797](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/f13d4190-f7bf-4a61-be61-8e7b8d1b11ea)
