### ISSUE TITLE
Map server is not ready

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2222]
I put the server on a linux hosting from digital ocean, but when entering the game this error occurs.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/793e4f25-0fd0-4ecf-8a8d-c8848ae14f8f)

my serverConfig

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/f432454f-f893-432c-a9b2-6061c5a20b72)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/aa10a606-d731-4a10-b055-af85173cccf0)

open ports

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/904c7901-ad38-406f-8080-a360d6c095ed)

I'm using this command

nohup /root/MMO.x86_64 -startCentralServer -startMapSpawnServer -startDatabaseServer

**Comment by juniormagalhaes** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/45943084-5118-4bce-b7d8-b1603220bdc1)

**Comment by juniormagalhaes** [comment]
in singleplayer mode it gives this error

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/91f0d046-2441-417e-b483-fbc90632302d)

**Comment by insthync** [comment]
Have to find what is cause null ref exception

**Comment by juniormagalhaes** [comment]
how do I do that?

**Comment by insthync** [comment]
May build a develop build and test it

**Comment by juniormagalhaes** [comment]
When I build for WIndows it works normally.

**Comment by insthync** [comment]
I don't get it, you are having a problem with Linux, so you have to find out why it is having a problem with Linux, isn't it?

**Comment by juniormagalhaes** [comment]
in the log it is giving this error

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/e201d426-cada-4ff1-bfb6-08ce32edb3f8)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/536d13c2-6085-4ef3-8519-966dea1fff52)

**Comment by juniormagalhaes** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/9bea12c0-a56c-4a54-a332-e98ecdad4d28)

**Comment by juniormagalhaes** [comment]
I don't know what I did, it worked, sorry for the hassle
