### ISSUE TITLE
EquipmentEntity effect bug.

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2223]
Hello, I set the effect on the weapon to +5 with EquipmentEntity, I put on the first +5 item, then I take it off and put on the same +0 item, the effect that should appear when it is +5 also appears on the +0 item.

**Comment by CLAXES** [comment]
If (_isFoundEffect) needs to be taken into if (_isFoundEffect) I think it works properly when I do this, there is such a problem because the one in _usingEffect is not reset, when I take that part into if (_isFoundEffect), the problem is corrected.


        public override void OnLevelChanged(int level)
        {
            if (_allEffectObjects != null && _allEffectObjects.Count > 0)
            {
                foreach (GameObject allEffectObject in _allEffectObjects)
                {
                    if (allEffectObject.activeSelf)
                    {
                        Debug.Log("test");
                        allEffectObject.SetActive(false);
                    }
                }
            }

            _isFoundEffect = false;
            if (effects != null && effects.Count > 0)
            {
                foreach (EquipmentEntityEffect effect in effects)
                {
                    if (level >= effect.level)
                    {
                        _isFoundEffect = true;
                        _usingEffect = effect;
                    }
                    else
                        break;
                }

-                 if (_isFoundEffect)

                {
                    // Apply materials
                    _usingEffect.equipmentMaterials.ApplyMaterials();
                    // Activate effect objects
                    if (_usingEffect.effectObjects != null && _usingEffect.effectObjects.Length > 0)
                    {
                        foreach (GameObject effectObject in _usingEffect.effectObjects)
                        {
                            effectObject.SetActive(true);
                        }
                    }

                }

-             }

            // Not found effect apply default materials
            if (!_isFoundEffect)
            {
                defaultMaterials.ApplyMaterials();
            }
        }

**Comment by insthync** [comment]
Is your condition correct?, is it works properly?

**Comment by insthync** [comment]
It should not be able to find the effect if `level` is `0` (and in `effects` list there is no effect which its `level` value is `0`), then if it not able to find its `_isFoundEffect` will be `false`, and it will apply default material, which I think it is correct workflow, please capture video to show your problem

**Comment by CLAXES** [comment]
There is a problem like in the video, normally the +2 item should have no effect. If I attach a +10 item and then attach the same weapon with +2, the effect remains.

[Video](https://youtu.be/YxEZ5tfzpDo)

**Comment by CLAXES** [comment]
here is the code:

              // Apply materials
              _usingEffect.equipmentMaterials.ApplyMaterials();
              // Activate effect objects
              if (_usingEffect.effectObjects != null && _usingEffect.effectObjects.Length > 0)
              {
                  foreach (GameObject effectObject in _usingEffect.effectObjects)
                  {
                      effectObject.SetActive(true);
                  }
              }

When I do it this way, the problem is corrected :

            if (_isFoundEffect)
          {
              // Apply materials
              _usingEffect.equipmentMaterials.ApplyMaterials();
              // Activate effect objects
              if (_usingEffect.effectObjects != null && _usingEffect.effectObjects.Length > 0)
              {
                  foreach (GameObject effectObject in _usingEffect.effectObjects)
                  {
                      effectObject.SetActive(true);
                  }
              }
          }

**Comment by insthync** [comment]
Did you setup default materials?

**Comment by CLAXES** [comment]
The settings I made are :

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/6fb163ca-313f-43fb-9301-448906852357)

**Comment by insthync** [comment]
Ahhh, i see, you use effect objects not just materials and an effect objects still being applied. Okay, your correct.
