### ISSUE TITLE
[Vulnerability/Bug] simulateSeed is set by client

### ISSUE THREAD

**Issue by ljars** [suriyun-production/mmorpg-kit-docs#2224]
In DefaultCharacterUseSkillComponent.UseSkill(), simulateSeed is randomly chosen by the client:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/72370023/7767978e-2917-451d-ba33-4539b63c4887)
On the server, ReadClientUseSkillStateAtServer() reads the seed, and it gets used in UseSkillRoutine().

A cheating client could manipulate the seed that is sent to gain an advantage.
For example, the seed is used to compute random damage in DefaultGameplayRule.RandomAttackDamage(). The attacker could find a seed that gives good damage and send that seed every time.

The same problem exists in DefaultCharacterUseSkillComponent.UseItemSkill(), and DefaultCharacterAttackComponent.Attack().

The seed should chosen by the server so the client can't cheat.

**Comment by insthync** [comment]
Seems like you have knowledge, can you help me to improve it?, you may send the codes which you think it is working to me.

**Comment by insthync** [comment]
The animation index random codes is incorrect, I will change it to
```
                animationIndex = GenericUtils.RandomInt(simulateSeed, 0, randomMax);
```

**Comment by insthync** [comment]
[mmorpg_kit-attackanduseskillhackprevention-230823.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/12411223/mmorpg_kit-attackanduseskillhackprevention-230823.zip)

You may help me review this one

**Comment by insthync** [comment]
I intend to use simulate-seed just to make clients play an animations, firing, and so on in the same way with server and other clients). I've changed it, now server will generate new simulate-seed to all clients, then it will re-generate when player do an actions, client may play the wrong animation/firing to a bit difference direction if they are lag and didn't receive new simulate-seed before do an actions.

**Comment by insthync** [comment]
I've changed to use timestamp as a seed, you can check it it 1.85 which I will release today.
