### ISSUE TITLE
(Bug) Door entity bug

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#2227]
Door system, only open door menu to add passwords or other settings in Shooter mode, in any other mode holding E button does not open door menu
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/7261de6a-1799-49ab-9e97-f100bef5d3c9)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/e8b3eba1-cc68-4772-8d30-9bb5d92da851)

**Comment by insthync** [comment]
In your screen shot, it is a door frame

**Comment by RafaelRBizachi** [comment]
Yes, because it is impossible to open the Door Menu even if you are very close to it

**Comment by insthync** [comment]
Because it found door frame before the door

**Comment by RafaelRBizachi** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/6f89bc16-3fbf-4731-943a-37c0ff7bba6a
Sorry to put another question in the same request, but it also has to do with the construction system, I changed something in the settings and now I can trigger the constructions but whenever I try to destroy the object it gives the error that I am also far from the target
Where can I change this setting?

**Comment by RafaelRBizachi** [comment]
increasing door collisions solves this, thanks
