### ISSUE TITLE
Warp to Map not working

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2228]
hello, could you give me a light of what might be happening? When trying to teleport to the map even through the npc dialog or the GM command, the message appears but it does not teleport, the other maps work correctly except this one.

in the NPC's Dialogue, he discounts the gold that is charged for the teleport, but does not teleport

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/52fabdd4-e6d5-44b9-92ff-061cbe85c83c)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/c767ca54-62a9-4224-a9d5-0fc428023eb9)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/2f0700e9-7219-412a-83e4-f67026b1bceb)

MY CONFIG

{
  "useCustomDatabaseClient": false,
  "databaseOptionIndex": 1,
  "databaseDisableCacheReading": false,
  "useWebSocket": false,
  "webSocketSecure": false,
  "webSocketCertPath": "",
  "webSocketCertPassword": "",
  "centralAddress": "104.675.665.38",
  "centralPort": 7000,
  "centralMaxConnections": 1100,
  "mapSpawnMillisecondsTimeout": 0,
  "defaultChannelMaxConnections": 500,
  "channels": [
    {
      "id": "0",
      "title": "Test Channel",
      "maxConnections": 500
    }
  ],
  "clusterPort": 6010,
  "machineAddress": "104.675.665.38",
  "mapSpawnPort": 6001,
  "spawnExePath": "/root/MMO.x86_64",
  "notSpawnInBatchMode": false,
  "spawnStartPort": 8000,
  "spawnChannels": [
    "0"
  ],
  "spawnMaps": [
    "MAP001",
    "MAP002",
    "MD001",
    "MD002",
    "MD003",
    "MD004",
    "MD005",
    "MD006",
    "MG001"
  ],
  "spawnAllocateMaps": [],
  "mapPort": 7770,
  "mapMaxConnections": 1100,
  "databaseManagerAddress": "127.0.0.1",
  "databaseManagerPort": 6003
}

**Comment by juniormagalhaes** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/51923787-cee5-45b4-b142-0fc77048d9d9)

**Comment by insthync** [comment]
Do you runs all servers on one device?

**Comment by juniormagalhaes** [comment]
> Do you runs all servers on one device?

Yep, server on digitalocean

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/b648ef0c-370d-49d4-9327-7590e13c822c)

**Comment by juniormagalhaes** [comment]
ah, I forgot to inform, in single player mode it works normally.

**Comment by insthync** [comment]
Try set "centralAddress": "127.0.0.1"

Why?

Because it is config for map-server to connects to central address, the address which will be sent to clients is `machineAddress` only

**Comment by juniormagalhaes** [comment]
Map server is not ready

in linux I keep having this error, but if I keep trying several times an hour it works.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/04aa538c-7f4a-4302-a1cc-6380028a0b67)

https://drive.google.com/file/d/1NcGfN9TpbT_iWe6p94YDNUbN34njk9Xy/view?usp=sharing

**Comment by juniormagalhaes** [comment]
I put "centralAddress": "127.0.0.1" but the same problem still persists when trying to teleport to the map

**Comment by insthync** [comment]
The same old issues isn't it?

 The map-server did not started yet, because it have and error saids

```
NullReferenceException: Object reference not set to an instance of an object
  at MultiplayerARPG.MMO.MapNetworkManager.PreSpawnEntities () [0x00053] in <9861a7e1b59746f0b8af141248fcd048>:0 
  at Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) [0x00015] in <83b2a702dbde424492ca524b4d6238a3>:0 
  at MultiplayerARPG.BaseGameNetworkManager.SpawnEntities () [0x00143] in <9861a7e1b59746f0b8af141248fcd048>:0 
```

**Comment by juniormagalhaes** [comment]
> The same old issues isn't it?
> 
> The map-server did not started yet, because it have and error saids
> 
> ```
> NullReferenceException: Object reference not set to an instance of an object
>   at MultiplayerARPG.MMO.MapNetworkManager.PreSpawnEntities () [0x00053] in <9861a7e1b59746f0b8af141248fcd048>:0 
>   at Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) [0x00015] in <83b2a702dbde424492ca524b4d6238a3>:0 
>   at MultiplayerARPG.BaseGameNetworkManager.SpawnEntities () [0x00143] in <9861a7e1b59746f0b8af141248fcd048>:0 
> ```

yep

**Comment by juniormagalhaes** [comment]
I was looking here, I'm using Ubuntu 22, it may be a problem related to the ubuntu version

**Comment by insthync** [comment]
I actually told you to try a development build.

Or better try to debug it, the easiest way is to add log writing in the `PreSpawnEntities ()` function, like this example

```

        protected override async UniTask PreSpawnEntities()
        {
            // Spawn buildings
Logging.LogError(1);
            if (!IsAllocate && !IsInstanceMap())
            {
Logging.LogError(2);
                // Load buildings
                BuildingEntity[] inSceneBuildings = FindObjectsByType<BuildingEntity>(FindObjectsSortMode.None);
                Dictionary<string, BuildingEntity> inSceneBuildingDicts = new Dictionary<string, BuildingEntity>();
                for (int i = 0; i < inSceneBuildings.Length; ++i)
                {
Logging.LogError(3 +"." + i);
                    inSceneBuildingDicts.Add(inSceneBuildings[i].Id, inSceneBuildings[i]);
                }

```

This is an example, don't copy-paste it, I hope you can do it, if you can't you will find a new problem in the future, and can't do anything to find a solution and ask me to help endlessly, without any helping info.
