### ISSUE TITLE
CameraFollow Fps

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2229]
when use FpsCameraTargetTransform -> https://gyazo.com/5388a2a47dfd1862df546948baeb1732

it behaves same like tps. the follow target object is static so not moving with the target. but for fps the camera should go with the target.

**Comment by insthync** [comment]
It works and intended

**Comment by insthync** [comment]
I don't get your question, what do you expect?, It is just change the following transform, from TPS one to FPS, and it works as intended.

**Comment by moepi2k** [comment]
let me explain.

1) Head_M is assigned to Fps Camera Target
https://gyazo.com/5bd1eb0f74c43d3da9764792f6c0b9fa

2) This is how the camera should follow now in Fps
https://gyazo.com/8c72504027d5534b493af6a501ce993d

3) The the pont is. Is creates a new Object _cameraTargetFollower, which not follow the assigned Object (Head_M)
https://gyazo.com/b66501a1945598b079700ca2b4d80e59

so in fps the camera is not out of place. when look around jump/crouch etc.

**Comment by insthync** [comment]
The `_cameraTargetFollower`  will be updated its transform following `FpsCameraTargetTransform`, so it is works as intended.

Did you try to find `_cameraTargetFollower` in the codes and try to read how it work?

**Comment by moepi2k** [comment]
yes its that part

`protected virtual void LateUpdate()
    {
        if (Application.isPlaying)
        {
            if (target != null)
            {
                if (!smoothFollow)
                {
                    targetFollower.transform.position = target.transform.position;
                    targetFollower.transform.eulerAngles = target.transform.eulerAngles;
                }
                else
                {
                    targetFollower.transform.position = Vector3.Lerp(targetFollower.transform.position, target.transform.position, followSmoothing * Time.deltaTime);
                    targetFollower.transform.eulerAngles = target.transform.eulerAngles;
                }
                targetPosition = targetFollower.transform.position;
                targetUp = targetFollower.transform.up;
                targetYRotation = targetFollower.transform.eulerAngles.y;
            }
        }`

targetFollower (_cameraTargetFollower) should transform its transform following target (in this case Head_M) but as u see in the video it does not. but anyway when u say it works as intended, how u manage it then to use fps camera to follow correctly head possition when look up down?

**Comment by insthync** [comment]
I don't get it, what are you expecting?

I actually don't see any difference from those videos.

The codes are simple, just follow the target transform, and it works as intended, it is mean I want to make it work like that.

**Comment by moepi2k** [comment]
maybe im a bad explainer. but show just those two videos. just look in editor view

https://gyazo.com/8c72504027d5534b493af6a501ce993d -> look at the gameobject Head_M which should be camera target transform
https://gyazo.com/b66501a1945598b079700ca2b4d80e59 -> and here its the  _cameraTargetFollow, as u see it not follow Head_M transform, it stays in place. the problem in fps is when the camera should exactly follow heads transform since it simulate view of the eyes

**Comment by insthync** [comment]
I still don't get it, you may just change it as you wish, and make a pull request.

I've given you guys a core repo accessibility, try to do something, I don't get why you guys requested repo accessibility but not trying to do anything.

**Comment by moepi2k** [comment]
because i cant find why it happen.

that line of code should do its job -> targetFollower.transform.position = target.transform.position;
but i dont know why the transform not follow target position

**Comment by moepi2k** [comment]
ok i found the issue.

i add debug log in CameraFollow like
https://gyazo.com/b2f7be0f451c930b7c793ea3eb0e2ea3
and noticed that the transform only update when you attack or jump. but not when look around
so i thought its because if the LateUpdate 

so i changed from LateUpdate to Update like https://gyazo.com/df0b192e27779c54c6a963ef60ead668
and the _cameraTargetFollower works as intend.

result -> https://gyazo.com/58bc17b26f494ff2a864c628a4330f43

but the problem with Upate now is. that the rotation of the player is already jittery.
