### ISSUE TITLE
Community help

### ISSUE THREAD

**Issue by Hellwood** [suriyun-production/mmorpg-kit-docs#223]
Maybe you could start a place discord or something. Where fellow MMORPG users can ask questions on how too's. I know I have dumb questions and someone has already worked through it. I would help others and they help me, so you can keep working on the big picture. Your community can help each other with the little stuff.

**Comment by JestHWas** [comment]
Before Suriyyun answers. There is a discord already. If you go to the asset store and go to the description for this kit you'll see a link for the discord.

**Comment by Hellwood** [comment]
Thank you

**Comment by insthync** [comment]
Okay, you can find it?, so I will close this issue post.
