### ISSUE TITLE
(Paid Request) Icon Amounts

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2230]
Would it be possible to put in the NPC's craft dialog the necessary items for the icon of these items to appear? so that the player has a visual return of the items he needs to craft the item? if so how much do you charge to put this option?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/e19ca769-933a-4b7e-a361-1f64fe515308)

I saw that you have this option here, but it doesn't work, or more likely I don't know how to configure it.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/9d444661-e169-4301-88aa-e775983be671)

**Comment by insthync** [comment]
That option (`Text Amounts` list) is for a specific item, you must know whats will show  in that UI and then set up the UI for each item.

**Comment by juniormagalhaes** [comment]
Um, I see, so would it be possible to make the icon appear in the normal required items? like Paid Request?

**Comment by insthync** [comment]
What is normal required items ?

**Comment by juniormagalhaes** [comment]
> 
The icon for these items will appear.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/59febe07-b529-44b6-a2fe-3420016d1855)

**Comment by juniormagalhaes** [comment]
I want to try to do something like this in the craft ui

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/c1ab3a68-97dc-49b0-b8ee-6a9376f85efa)

**Comment by juniormagalhaes** [comment]
was the kit default, I used a wrong expression.

**Comment by insthync** [comment]
Actually still don't get what you want to tell me yet, but I know you want it to have icons.

**Comment by juniormagalhaes** [comment]
that's exactly what I wanted to talk about, icons and a way to organize it like in the image above XD,

**Comment by insthync** [comment]
How much you would pay for this?

**Comment by juniormagalhaes** [comment]
I really have no idea how much it's worth, or how difficult it is to do this, I trust you to give the price.

**Comment by insthync** [comment]
I actually can't give a price that is worth for me, because it is too high for most customers. I always give a very low price, which is why I also don't want to accept any new feature requests including paid ones.

I like to accept requests for features that are interesting, or that I feel challenge me, more than basic ones.

**Comment by juniormagalhaes** [comment]
Is $15 good for you?

**Comment by insthync** [comment]
It is okay

**Comment by juniormagalhaes** [comment]
where do i send you?

**Comment by insthync** [comment]
https://ko-fi.com/insthync

**Comment by juniormagalhaes** [comment]
Send!

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/6bb4f387-6f35-40a0-a238-d0fd76e72149)

**Comment by LordPhrozen** [comment]
I generally think this is a good add, and was on my to-do list as well. It being in the base kit would be great. I'll put some money in some at the beginning of the month as well for ya. @insthync

**Comment by AsheshPlays** [comment]
AWESOME!!

**Comment by Eniotnacram** [comment]
I was litteraly doing some custom stuff for that, thank you! Will also use it

**Comment by juniormagalhaes** [comment]
I was messing around here, where do I configure it to place the quantity of resources along with the images?

**Comment by insthync** [comment]
![Uploading Screenshot_2023-09-22-19-22-05-291_com.android.chrome.jpg…]()

**Comment by insthync** [comment]
![Uploading Screenshot_2023-09-22-19-22-05-291_com.android.chrome.jpg…]()

**Comment by insthync** [comment]
![Screenshot_2023-09-22-19-22-05-291_com android chrome](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/5f83ca4e-4590-4a26-9bb6-ad81ce9279bf)

**Comment by tubhluas** [comment]
Hi, so if i want this feature I have to sent $15 too?
