### ISSUE TITLE
Clothes Prefabs Animations

### ISSUE THREAD

**Issue by ayaldabos** [suriyun-production/mmorpg-kit-docs#2231]
so i noticed if you make clothes for the character and add them to the item as prefab and not instance since they are separated fbx/prefab 
animations will stop working and the character clothes will appear in T-pose is there any fix or solution for that ?

**Comment by Niinra** [comment]
put bones in clothes

**Comment by Niinra** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/a7013487-8a83-45d2-990e-4a54ead161b0)
you use this configuration to bones?

**Comment by ayaldabos** [comment]
> ![image](https://user-images.githubusercontent.com/115952096/263477863-a7013487-8a83-45d2-990e-4a54ead161b0.png) you use this configuration to bones?

nop!! what is that ? what's ur discord name if you dont mind sir

**Comment by Niinra** [comment]
sorry for the delay in your gameinstance there is this option that enables the behavior of the skeleton of the objects if I'm not wrong put the scriptableobject here and take the behavior of the script 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/16c5904a-f3e8-4f02-bb02-162b2022af53)
Here we create the scriptableObject , I hope I have helped you
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/5cb84e1c-a849-4f4f-a835-7c7162426fbc)
