### ISSUE TITLE
MMO memory problem

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2233]
Hello, I tried to make such a code, I want to reset the kPoints value every week, I made a code like the following, but it doesn't work, the man who enters the game once is memorised, when he is not in the game, the sql update code does not process it, it continues from the memory again, how can I do this, I need to reset the kPoints values of both those who are in the game and those who are not in the game here.

        private DateTime dailyCheck;
        public override void CheckKing()
        {
            ExecuteReaderSync((reader) =>
            {
                if (reader.Read())
                {
                    dailyCheck = reader.GetDateTime(0);
                }
            }, "SELECT dailyCheck FROM checkking LIMIT 1");

            if (DateTime.Now.Date == dailyCheck.Date)
            {
                ExecuteNonQuerySync("CALL UpdateKing();");

                List<PlayerCharacterData> characterData = new List<PlayerCharacterData>();
                List<string> characterId = new List<string>();
                ExecuteReaderSync((reader) =>
                {
                    while (reader.Read())
                    {
                        characterId.Add(reader.GetString(0));
                    }
                }, "SELECT id FROM characters WHERE kPoints > 0");

                foreach (string id in characterId)
                {
                    characterData = ReadCharacters(id);
                }

                foreach (IPlayerCharacterData playerCharacter in characterData)
                {
                    playerCharacter.kPoints = 0;
                }

                ExecuteNonQuerySync("UPDATE characters SET kPoints = 0 WHERE kPoints > 0");
            }
        }

**Comment by insthync** [comment]
Maybe because your character data was cached, you may try delete it and reload character data when login.

**Comment by CLAXES** [comment]
Yes, I want to delete the cache of the person who leaves the game, I want to pull the database information again every time I enter the game, how can I do this, where can I do it, can you help me, how can I do this?

**Comment by insthync** [comment]
Can I answer no?

**Comment by insthync** [comment]
![Screenshot_810](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/59df1331-33fe-408c-9543-a8981edec9a4)

You may do like this

**Comment by CLAXES** [comment]
Ok I will try thank you very much.

**Comment by CLAXES** [comment]
it works this way, but if it is deleted from the cache when it exits the game, it would be better if the person who is not in the game is not kept in vain

**Comment by insthync** [comment]
I don't know why you want to do it, but if you want to do, you may send message from map or central server to database management server to delete it.

**Comment by CLAXES** [comment]
It was working when I made DisableCacheReading true in DatabaseNetworkManager, no need to do anything else. I just realised this, sorry, it works fine now.
