### ISSUE TITLE
Enable Apply Chance

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2234]
I have tried the settings of the Apply Chance on the debuff and buff skills. I experimented with enabling it and disabling it but setting to 1, which means 100% chance. Also sent you the videos personally and it doesn't apply 100% and not 50%. 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/c60bb8cb-8b45-4b2d-8f2c-631264fc992c)

**Comment by insthync** [comment]
You just don't understand how debuff is applied, it will be applied when attacking the enemy, and attacking it is not 100% hit.

So in the next version, I've made changes to `Skill` by adding a new kind of `skillBuffType`, it is `BuffToEnemy` which you can select to only enemy as a target to use skill.
