### ISSUE TITLE
How to create monsters in the map, apart from using the 'Monster Spawn Area' component?

### ISSUE THREAD

**Issue by shawnmc00** [suriyun-production/mmorpg-kit-docs#2239]
If I want to generate enemies round by round in maps,For example, after killed 10 enemies, another area of 10 monsters appears at a different location, instead of having pairs of enemies simultaneously appear in multiple areas.I'm unsure how to handle this kind of logic. I only see the Monster Spawn Area component for creating enemies, and they all appear on the map at once after it's been created.

**Comment by Eniotnacram** [comment]
Well, its really specific for your game. You mosly need to create that script that controls all of that

**Comment by insthync** [comment]
You may try to learn how to change spawning workflow from here: 

https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_ScriptsOnDemand/blob/master/Scripts/QuestMonsterSpawnArea.cs
