### ISSUE TITLE
[Request] Add the "Filter Categories" to UICharacterQuests

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2241]
@insthync 
The logic to use the Category is implemented for the Items (Inventory) and for the Skills but they are not added to the UICharacterQuests. I need to add the FilterCategories array to the UICharacterQuests and also add the Utils for that in UICharacterQuestsUtils. I already added it on my own but I think this is important for all of us and should be in the core scripts of the kit.

The goal is to use the category for the quests for MAIN quests, SECONDARY quests, etc.

Thank you

**Comment by insthync** [comment]
Gave you a repo accessibility, try create a pull request

**Comment by Eniotnacram** [comment]
Thank you for the confiance, really busy at the moment but I will.

Thank you again :)

**Comment by Eniotnacram** [comment]
Pull Request sent.

**Comment by insthync** [comment]
Maybe because I uses free plan

**Comment by Eniotnacram** [comment]
I think this change affected the NPC dialog  related to the quests.

(I am currently investigating)

@insthync

**Comment by insthync** [comment]
May have to make it filter only when the list of category is not empty

**Comment by Eniotnacram** [comment]
I have tested on fresh kit only modifying the UICharacterQuestsUtils & the UICharacterQuests like we did and it works. (MMO) So there is something wrong in my main project, not related to this.

On my main project ive modified the UICharacterQuest script by inheriting it and using my own class. Could that be the problem?

**Comment by Eniotnacram** [comment]
Found the problem sorry, everything is good :)
