### ISSUE TITLE
[Bug] Hotkeys need to be refreshed after logoff and logon.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2242]
The title is pretty much self explanatory.

When a player leave the game and come back, nothing is showing in the hotkeys until he use something in it or drag an item to refresh the total hotkey.

Using latest kit.

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2237
