### ISSUE TITLE
[Suggestion]Buffs feature

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#2243]
Hello, I want to add 2 features to the buff.
Example
Increase armor rate
Increase damage rate
Increase the affected person's armor by 10%
Increase the affected person's damage by 20%
thanks.

**Comment by fedas61** [comment]
BuffExtensions.cs not have partial
CalculatedBuff.cs not have partial
CalculatedBuff.cs function Build() maybe DevExtensions Invoke
thanks

**Comment by insthync** [comment]
If you really want to improve it, you may try to change the core codes then share what you've made changes to me, that is it. Saying it is not open to development is sounds bullshitting to me.

**Comment by fedas61** [comment]
Your kit is normally open for development but, The problem is that when I wanted to add the buff feature, I couldn't do it. What I want to do is to reduce the attack and defense rates of the players in the area by 30% or 50% when the area skill is used. I may have expressed myself a little wrong, I am using translation.

I would be glad if you can help with this.
Your kit is normally open for development but, The problem is that when I wanted to add the buff feature, I couldn't do it. What I want to do is to reduce the attack and defense rates of the players in the area by 30% or 50% when the area skill is used. I may have expressed myself a little wrong, I am using translation.

I would be glad if you can help with this. :)

**Comment by fedas61** [comment]
Hello,
I tried to do my best.
It only multiplies the attributes from the buffs, but the character has to multiply all its values.
Example
Other functions like GetEquipmentIncreaseDamages() need to be added inside

I'm using the translation, I can't express myself, sorry.
Thank you.


![damage](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46999478/0e905285-237f-4ad7-a14a-10fef46bd4ec)
![calculatedBuff](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46999478/db5828cd-6136-48d7-a13b-a3c835652232)
![armor](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46999478/af996b22-e023-4560-a8ea-0a85f9963aa7)

[Scripts
](https://discord.com/channels/460801727789137920/460803200208076800/1146748123931217925)

**Comment by insthync** [comment]
I don't use Discord, send the scripts to my email: ittipon.bay@gmail.com

**Comment by insthync** [comment]
I will add actions to make some functions more extensible because those functions will be called frequently and should use actions instead of dev extensions to improve its performance.

**Comment by insthync** [comment]
I actually don't know which should be used as base armor/damage amounts. then I have to take a time to re-write all calculation for better performance.
