### ISSUE TITLE
[BUG] 1.84b2 - Weight 1 sync behind [confirmed in fresh kit]

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#2244]
weight reads as 0.00/0.00 until moving items around in the inventory.

**Comment by LordPhrozen** [comment]
It may be doing the weight calculation *after* the sync. The data always seems 1 instruction behind. Dropping items, swapping items, selling an item, it doesnt seem to matter.

**Comment by LordPhrozen** [comment]
Video: https://i.imgur.com/g5Xk62q.mp4

**Comment by insthync** [comment]
Try add on recached event like [this](https://github.com/suriyun-production/mmorpg-kit-docs/issues/2210#issuecomment-1679094258)

Then use it to update weight like this 

![Screenshot_819](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/d4087d32-8dc6-48d1-9e48-e91c39db3958)

**Comment by insthync** [comment]
Or just swap caching workflow in `BaseCharacterEntity_Caches.cs` like this (from after event invoking to be before)

![Screenshot_820](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/c8b7c73d-5b58-4cff-bc16-02a90515a756)

**Comment by LordPhrozen** [comment]
moving that above the checks did it. :)
