### ISSUE TITLE
[Question] Websocket vs Normal gameserver for mobile

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#2245]
Hey suri, till now I wasn't aware you can use websocket gameserver (used for webgl) for mobile builds as well, thought you need non-websocket gameserver (normal) for non-webgl builds.
This is really cool as it will allow consistent gameplay for webgl and mobile players.

But I had a question regarding the performance or any pros/cons for using websocket gameserver for mobile. 
Are there any major performance loss or other disadvantages in doing so ?

PS: The kit is working quite good on webgl

**Comment by insthync** [comment]
You actually can use both, it can use lite net lib for mobile, and can use web socket for webgl, try find a mix transport component

**Comment by shubhank008** [comment]
> 

That would be quite interesting, any docs or usage guide available for Mix Transport component ? Found it but where to attach it and its config. 

Any reason why its not being used as the default component considering that would provide a single setup for truly cross platform

**Comment by insthync** [comment]
https://insthync.github.io/LiteNetLibManager/#/advanced/custom_transport_layer

**Comment by insthync** [comment]
I don't have a reason for it, I actually don't like to make WebGL games, it takes too long time to build. If I will do it, I won't use Unity.
