### ISSUE TITLE
[Bug]Monster behavior after chasing target

### ISSUE THREAD

**Issue by kaal86** [suriyun-production/mmorpg-kit-docs#2246]
When Monster chase a target and then walk back to spawn position, the monster dont react to other player which are in range or attack it. so you can just kill it and they wander streight to spawn position

to reproduce.
1) in monster prefab just change maxDistanceFromSpawnpoint to 0.
2) FollowTarget duration to e.g
3) attack a Monster and run away till FollowTargetDuration timer is over
4) Monster walk back to spawn position and dont do anything else.

-> Monster should attack target again when in range or monster is attacked

**Comment by insthync** [comment]
As I test, it still attacking, and I didn't made any changes, https://youtu.be/cbIbta6rxO4

You actually can change codes in `MonsterActivityComponent` to fix it, then tell me how you fix it, or atleast tell me where is cause the problem.

You actually can make your own activity component by create a new class which extends from `BaseMonsterActivityComponent` and write logic as you wish.

**Comment by moepi2k** [comment]
Yes, same behavior in your video. When the monster walk back to spawnpoint it wont attack anymore till arrived even when attack it while movibg back.
