### ISSUE TITLE
MMO hotkey bug

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2247]
Hello, when you change the skill when the skill is not on cooldown, it does not change, and even if I remove the skill that is on cooldown, the place there still shows it as on cooldown, I added a video you can watch.

[Video](https://youtu.be/sy-XtiY-tAI)

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2210 ?

**Comment by CLAXES** [comment]
I did it before, I showed the code, it gets better when the map changes or something, but when putting the skill, there is a problem like in the video

**Comment by insthync** [comment]
![Screenshot_823](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/91912d88-bfe8-41c9-87fc-8e9ebae9daa7)

**Comment by CLAXES** [comment]
I added as you said PlayingCharacterEntity_onHotkeysOperation as below, it works now, but the waiting time counts down even if I change the ability.

        private void PlayingCharacterEntity_onHotkeysOperation(LiteNetLibSyncList.Operation operation, int index)
        {
            UpdateData();
        }

**Comment by CLAXES** [comment]
Now working properly thanks.
