### ISSUE TITLE
[Help] server ram usage with map instance

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#2248]
I'm having a problem with excessive use of ram on the server, I don't know if it's my settings, but when an instance is created it consumes 800mb of ram for each instance, with 10 players there are already 8gb of ram consumed
Is there any solution for this? even if it is paid, you can tell its value
Please help me, my game is already being tested with players 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/563475e1-4cc6-4009-bd2c-4a6cd25dcdd0)

**Comment by RafaelRBizachi** [comment]
it's not very big, but it's a game that is waiting for many players and with many open instances and it doesn't have monsters, it's just an area to build 
however in monstrous instances the consumption is being the same

**Comment by RafaelRBizachi** [comment]
But is there any way to open just one instance and the others to be clones? because it ends up being unfeasible to have 100 players in instances because they would already use 40/80 gb of ram

**Comment by insthync** [comment]
How to clone it?

**Comment by insthync** [comment]
Did you ever test RAM usage when a player enters the game? Each player shouldn't require a high number of RAM usage.

**Comment by RafaelRBizachi** [comment]
when the player accesses the game it is not being the problem, only when opening Dungeon Instances
For example: 1 player accessed the dungeon and allocated 600mb of ram memory, when another player accesses it will also allocate 600mb of ram memory again, following this with 10 players accessing a dungeon there are already 6 gb of ram memory spent on the server, with 100 players there are already 60 gb of ram
Is there any way for instances to only use codes? apparently it is generating images on the server
Even if it is a paid measure 🙏

**Comment by insthync** [comment]
Yes, because it has to create a new instance

**Comment by RafaelRBizachi** [comment]
But is there any way for instances to be more scalable? because if you have 5000 players online and 500 open a dungeon instance, it would already be 200 gb of memory allocated

**Comment by insthync** [comment]
No

**Comment by RafaelRBizachi** [comment]
ok thx
