### ISSUE TITLE
Mobile version issue

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#225]
When I assign building elements in the shortcuts the first one works fine, but the 2nd item does not work.

To make it work, I must go to the main menu and enter again.

![WhatsApp Image 2020-02-13 at 11 36 57 AM](https://user-images.githubusercontent.com/45702662/74445772-b3908100-4e55-11ea-8e83-a5edb18f3caf.jpeg)

**Comment by insthync** [comment]
Okay, I will check it.

**Comment by Blunnyn** [comment]
When i want put some building, no exist any button for accept or cancel 
And also have no button for mount/dismount

**Comment by insthync** [comment]
Oh, I see, for now you can press attack button to build it. But if you want to make it showing confirm dialog after press attack button you can turn this option on.

![Screenshot_36](https://user-images.githubusercontent.com/2697550/74584932-19be0500-500a-11ea-909b-b5d6869a710b.png)
