### ISSUE TITLE
[Bug]Character Death Rules

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2251]
player dont drop loot on death while this is enabled
https://gyazo.com/c877ad8e12033b9bdc1239db7f329281

**Comment by insthync** [comment]
Check you gameplay rule -> `itemDecreaseOnDeadMin` and `itemDecreaseOnDeadMax`

**Comment by moepi2k** [comment]
ohh didnt saw that new options, thank you
