### ISSUE TITLE
CanUse for Skillusage not validated by Server

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2252]
The CanUse Methode in BaseSkill is not validated by Server

i made a new skill and inherit from baseSkill to add my conditions, then i noticed that my serverside code not running.
so i put my conditions directly in baseskill CanUse and build a server and client.

result conditions works. soo but those condiotions only checks by client. when i remove those conditions and run client again i can use the skill.

**Comment by insthync** [comment]
Can you fix it?

**Comment by insthync** [comment]
This one is already fix, check it in the git, you've got the accessibility, hope you can learn something like as you told me.

**Comment by moepi2k** [comment]
nvm found the issue but its a bit weird

left normal client, right modified client with removed conditions -> https://gyazo.com/261d49646d63b1fb541223abd0f50139
https://gyazo.com/bae290032873fd9d00c232a1e9e520fc

u see clientside u can use the skillitem. but other client cant see it because its not running on server, BUT the skill applys

and in this video i add same checks also in BaseSkill.cs ApplySkill methode
https://gyazo.com/e5b37d71efe16d9cd995fcb8bcd34dba

and it works.
i thought condition in can use is enought but dont seems so. 

thx anyway
