### ISSUE TITLE
[Paid Request] Personal loot

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2253]
Hello,

It would be very nice to have the option (most likely in GameInstance) to toggle if the loot should be private or not.

So if the loot is private, the loot dropped will only be seen by the player who dropped it. So for example, player A and player B. Both players fight a monster in the same party, when the monster is dead, player A see loot on the floor, but not player B. After X amount of time if player A is not looting the items, the items will be now seen from any players or destroyed or what ever we set it in GameInstance. Both player could also drop at the same time but they will not see the dropped item from each other.

Because the way its curently implemented, when players are in the same party, they are fighting to loot first because all loot are shared between all party members.

And for the players that are not in the same party, it just makes things better, by adding a % of chance to drop for each players instead of choosing between one of the players that hit the mobs.

Let me know if you need more information and if it is possible, and dont forget to shoot me your price :)

**Comment by LordPhrozen** [comment]
If this doesn't get picked up, you could do this for bosses at least with a quest -> Gacha item.

**Comment by Eniotnacram** [comment]
> If this doesn't get picked up, you could do this for bosses at least with a quest -> Gacha item.

Oh damn that's a great alternative! But yea I would like this for all drops in my game not only bosses
