### ISSUE TITLE
Purchase problem and warning problems

### ISSUE THREAD

**Issue by john5514** [suriyun-production/mmorpg-kit-docs#2255]
Hi,

https://prnt.sc/wWGYoZ1T_YCz
https://prnt.sc/jqiN-7LCUwqZ
https://prnt.sc/MB2Zus3lPaRG

I hope your day is going well I am about to publish my game, this is my only problem left, the purchase does not work, I entered the code given in the scripts define section, I entered the code given for google play, I added in-app purchase packages, but it gives an error again INFO GameInstance [2023-09-19 09:13:52] - [IAP_INIT]: Initialized without purchasing 
separately, it gives errors as unused scripts in the form of warning vertex paint, mmo rpg kit gives yellow errors, how can we fix this? can u help me guys

**Comment by john5514** [comment]
And joystick use not runing both input if u click shift runing how to fix

**Comment by insthync** [comment]
You cannot test IAP in editor, you have to build to test it, the movement too, it can't detect more than 1 touch in editor.

**Comment by john5514** [comment]
thank u for reply then say this problem 

https://prnt.sc/12hHhg2J25uM

I also logged in from the unity control panel project settings, but it does not accept it, I enter the license in the monotize setup section, it gives an error, how can we solve this, I tried a lot of methods, I deleted it, I reinstalled the package.

**Comment by insthync** [comment]
For that error, you should ask unity

**Comment by john5514** [comment]
thank u for reply 

then if If we set up a pvp site like metin2, can we make a shop integration to it?

**Comment by insthync** [comment]
You can develop a web?
