### ISSUE TITLE
[Bug] UIs Controlling for Console platforms 

### ISSUE THREAD

**Issue by sdk2016** [suriyun-production/mmorpg-kit-docs#2256]
I'm sorry to tell you that i've found some issue regarding to UI for Console Platforms (Version 1.85).:

(1) **unable to use Gamepad or Joystick to place building**
we are unable to use Gamepad or Joystick to place building in Console platform. Currently, to place building, we must use mouse cursor and button. I wonder if Mobile UI can be adapted to place building in Console UI. Thank you.

(2) how to change select button?
Curently, we use X on Gamepad or Joystick to select UI Button (for example: Start Game, Delete). CAn we replace this X with another? Just like actions we found in InputActions asset (kindly find the attached picture bellow)? 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/20059348/86439341-4d2a-482d-9de8-50110c898f5d)

Thankyou for your support.

**Comment by insthync** [comment]
1. I have not implemented building controlling yet, do you have any example to show how is it being controlled for both the shooter controller and the default one?

2. It uses Unity's built-in control setting for menu nav, you should try to check in the event system -> input module

So... no bug here.

**Comment by insthync** [comment]
Don't tell anything to me if you can't make it work yet, it is not helpful.

I know how to make it work immediately after I've read this post, you don't have to try to do anything. The thing you can help me is pay me some coffee.

**Comment by insthync** [comment]
Why what? you request me to help you for free?

**Comment by insthync** [comment]
Why what? 
Did i force you to do it? NO
Do you know the word: "should" mean?
If it not "should" then it mean I must always do what you request for free? You should pay because I helping you, that is it, is that hard to understand?

**Comment by insthync** [comment]
Yes, if it is a really serious bug, and the reporter can tell me how to reproduce it not just tell me what is happening without any helpful information, I am willing to pay for it.

And I didn't force you to pay or anything, I just told you what you can do to help me because I saw you can't do anything except disturb me by posting useless information.
