### ISSUE TITLE
[BUG] Item loot GameMessage not working in MMO (Version 1.85)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2258]
The Exp and Gold messages are working but when the player loot an item the message are not shown anymore.

It works in Not MMO but Server Message for item loot not working in MMO mode.

(Tested with fresh kit install)

**Comment by insthync** [comment]
I don't get it

**Comment by Eniotnacram** [comment]
When players are looting items, a GameMessage is usually shown. "Obtain Chest armor x1 ea". Those messages are bugged and not shown in latest update.

**Comment by insthync** [comment]
Please don't bring exp, gold loot to make me confuse if it is not related, do you just wanna tell me that their is no messages sent to player when pick up the item?

**Comment by Eniotnacram** [comment]
> Please don't bring exp, gold loot to make me confuse if it is not related, do you just wanna tell me that their is no messages sent to player when pick up the item?

Exactly, Not message sent to the player when item is pickup, in MMO. (Messages are working in LAN).

**Comment by LordPhrozen** [comment]
I also experience this issue on 1.85. 

Picking up an item off the ground = no message ❌
Taking item from a shop = message✅
taking an item out of a corpse entity = message✅

**Comment by insthync** [comment]
![Screenshot_2023-09-23-13-35-12-344_com android chrome](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/e8f32d7b-da44-4857-88eb-34b0c334fd22)
Make changes like this.

**Comment by LordPhrozen** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7896457/4aebd4b7-afb7-463a-8331-b8a717f6b098)
This did not address the issue, and no message is displayed.

**Comment by insthync** [comment]
It fixed
