### ISSUE TITLE
[Bug] Quest Tasks or new Quest 1.85

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2260]
I created a new quest and filled a quest task in random tasks. I only added 1 random task to make it not random.
talk to npc seems bug if you put two talks and it seems to ignore the task.

on the video is a fresh kit 1.85 
i just added 1 quest  to test. it does not work.
in addition to it i modified the existing talk to npc quest task, added tasks but it wont apply. 
It seems to save the task in the existing task. when i remove the element of task in random task,
it removes it. but when i remove the random task element , it shows back the entry.

video Reference for new quest
https://streamable.com/ep2fq6

video reference to modified quest
https://streamable.com/rohipt

**Comment by insthync** [comment]
To fix issues in the second video

![Screenshot_859](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/1f26d618-599b-49e0-b450-e1775f6056cf)

**Comment by chumleader** [comment]
> To fix issues in the second video
> 
> ![Screenshot_859](https://user-images.githubusercontent.com/2697550/270295861-1f26d618-599b-49e0-b450-e1775f6056cf.png)

thanks for this, how about the quest not working?

**Comment by insthync** [comment]
Fixing
