### ISSUE TITLE
[BUG] Creation new Character (v1.85)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2261]
Hello,

-Creating a new character takes very much longer than before using the newest version. (Loading takes a while)

-If we spam the create button, it will create MULTIPLES character at once, with the same name.

**Comment by Eniotnacram** [comment]
So you greatly suggest to build the database server externally now? I was going to do it anyway.

Will it prevent the player from spamming the create button tho and create multiple characters at once ?

**Comment by insthync** [comment]
No, have to add codes to prevent it
