### ISSUE TITLE
Projectile direction error.

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2263]
As it says in the title, there is an error with the direction of the projectiles, sometimes they come out correctly, other times they are fired in the wrong position. Example gif:
![GIF 26-09-2023 14-41-26](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/5d54dd38-1068-4b9e-a019-648f985b715f)

**Comment by insthync** [comment]
Check your launch transform first, where is it?

Are you sure that it is wrong, try looking at the image below, it might make you understand what is happening

![Screenshot_860](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/37b742af-474d-4da2-bc7e-f99a2f8b68b7)

1. Blue rectangle is camera
2. Black circle is your character
3. Red circle is your target
4. Orange line is direction

**Comment by Niinra** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/d6a3c57d-64d5-46be-9e68-f7aec11e421e)
I put a cube to show you where the projectiles transform, is that wrong?

**Comment by Niinra** [comment]
Although it is strange, before updating I did not have this problem

**Comment by insthync** [comment]
Did you intended to make use of difference melee and missile?, that skill is using missing damage transform ?

**Comment by insthync** [comment]
Which update ?

**Comment by Niinra** [comment]
1.85b

**Comment by Niinra** [comment]
> ¿Tenías la intención de hacer uso de la diferencia cuerpo a cuerpo y misil?, esa habilidad está usando la transformación de daño faltante?

Something I still didn't understand was why the projectiles transformed in the melee area and not in the missile

**Comment by insthync** [comment]
From which version

**Comment by Niinra** [comment]
In 1.85 they worked fine

**Comment by insthync** [comment]
I did not make changes to anything related to it.

**Comment by Niinra** [comment]
You can also review the latest version that I sent you for gmail and it doesn't pass either

**Comment by insthync** [comment]
What is mean?

**Comment by insthync** [comment]
What is not pass?

**Comment by Niinra** [comment]
The projectiles were not fired in the wrong direction, they always took the correct crosshair position , I'll show you a gif with the gizmos on, see if it gives you an idea, because I arranged the camera in a default position of the asset and it continues happening

**Comment by moepi2k** [comment]
that behavior is also in 185 and older version. its because of this line in ShooterPlayerCharacterController.cs
https://gyazo.com/111e9ca798cdea588b330ff437bc8b37
comment it out and it works.
its because raycast change to target when aim on it

**Comment by moepi2k** [comment]
it only happen im specific situation when an entity or something is in line of sight. if u directly shoot in the air it goes streight

**Comment by Niinra** [comment]
That suggestion you said, I commented on that line and it's still happening

**Comment by Niinra** [comment]
1.84b2 is the version in which this problem does not occur, it is the same one that I sent you privately

**Comment by Niinra** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/8c2599ba-06c6-45ba-99f1-0180021f4dbc)
It seems that the error is caused by this because removing the code execution control causes all the lines to be executed in due time and the problem stops occurring.

**Comment by insthync** [comment]
Okay, I will find a proper way to fix it

**Comment by insthync** [comment]
I knew it was related to [FPS camera stutter issues](https://github.com/suriyun-production/mmorpg-kit-docs/issues/2219) fixing, and afraid that if I fixed it FPS camera stutter issues would come back
