### ISSUE TITLE
Hit Restration Error

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2264]
ERROR No Tag [2023-09-27 23:10:00] - ArgumentException: An item with the same key has already been added. Key: 0_0
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <391154401d904e0ca279fe00c621b01b>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <391154401d904e0ca279fe00c621b01b>:0)
MultiplayerARPG.DefaultHitRegistrationManager.PerformValidation (MultiplayerARPG.BaseGameEntity attacker, System.String id, System.Int32 simulateSeed, MultiplayerARPG.HitData hitData) (at <d1a5ab6d958046768225903e21b30c18>:0)
MultiplayerARPG.DefaultHitRegistrationManager.Register (MultiplayerARPG.BaseGameEntity attacker, MultiplayerARPG.HitRegisterMessage message) (at <d1a5ab6d958046768225903e21b30c18>:0)
MultiplayerARPG.BaseGameNetworkManager.HandleHitRegistrationAtServer (LiteNetLibManager.MessageHandlerData messageHandler) (at <d1a5ab6d958046768225903e21b30c18>:0)
LiteNetLibManager.TransportHandler.ReadPacket (System.Int64 connectionId, LiteNetLib.Utils.NetDataReader reader) (at <b99342316e06476f8a9371507575a8db>:0)
LiteNetLibManager.LiteNetLibServer.OnServerReceive (LiteNetLibManager.TransportEventData eventData) (at <b99342316e06476f8a9371507575a8db>:0)
LiteNetLibManager.LiteNetLibServer.Update () (at <b99342316e06476f8a9371507575a8db>:0)
LiteNetLibManager.LiteNetLibManager.Update () (at <b99342316e06476f8a9371507575a8db>:0)
MultiplayerARPG.BaseGameNetworkManager.Update () (at <d1a5ab6d958046768225903e21b30c18>:0)
MultiplayerARPG.MMO.MapNetworkManager.Update () (at <d1a5ab6d958046768225903e21b30c18>:0)

**Comment by insthync** [comment]
Is it cause any issues?, if not, then you can skip it.
