### ISSUE TITLE
Builds entity directly on the map Question

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2265]
I was wondering if there was any way to put fire pits, storages and workbenches directly on the map, so that everyone could use them?

**Comment by juniormagalhaes** [comment]
> Yes

I tested it on a clean project and it works just by placing it in the scene, but it didn't work in my project. Is there anything that needs to be configured beforehand for it to work?

**Comment by insthync** [comment]
As I know it has nothing needed, but you may check your building max HP

**Comment by juniormagalhaes** [comment]
It was just stupid of me, the crafting window was disabled '-'
