### ISSUE TITLE
DefaultCharacterUseSkillComponent.UseSkillRoutine error

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2266]
ERROR No Tag [2023-09-29 00:09:44] - NullReferenceException
UnityEngine.Object.get_name () (at <7234610152e147df8d3e4eb4436d83e1>:0)
LiteNetLibManager.LiteNetLibBehaviour.get_LogTag () (at <fb07bfd9e58245ceb5b1e7621d71e9b4>:0)
MultiplayerARPG.DefaultCharacterUseSkillComponent.UseSkillRoutine (System.Int32 simulateSeed, System.Boolean isLeftHand, MultiplayerARPG.BaseSkill skill, System.Int32 skillLevel, System.UInt32 targetObjectId, MultiplayerARPG.AimPosition skillAimPosition, System.Nullable`1[T] itemDataId) (at <f7c05597e4f349caab539ada54d5ebc2>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<UseSkillRoutine>d__73:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(Object)
Cysharp.Threading.Tasks.DelayIgnoreTimeScalePromise:MoveNext()
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore()
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run()

I realized a lot of errors about it.I guess because of that -> System.Nullable`1[T] itemDataId

Almost 1 error everyhour.How can I fix it?

**Comment by insthync** [comment]
Does it cause any problems?, if not, you may ignore it

**Comment by temelkirci** [comment]
I have a monster respawn issue, I thaught because of it.I added try catch in killed function in BaseMonsterCharacterEntity.cs, not fixed yet.

**Comment by insthync** [comment]
And your guess is wrong, those line `MultiplayerARPG.DefaultCharacterUseSkillComponent.UseSkillRoutine (System.Int32 simulateSeed, System.Boolean isLeftHand, MultiplayerARPG.BaseSkill skill, System.Int32 skillLevel, System.UInt32 targetObjectId, MultiplayerARPG.AimPosition skillAimPosition, System.Nullable1[T] itemDataId)` is telling where is the function, not where is the error, does it have more messages?

It seems like the error occuring when it try to write some log message but it can't get log tag by object's name because the object is null, it may be destroyed before it is going to write log message.

If you want to help me find it, you may change `Logging.LogException(LogTag, ex);` to `Logging.LogException(ex);` (no log tag)

**Comment by insthync** [comment]
@temelkirci That one again?, did you try the latest version?, what I found from @AsheshPlays 's project is problem occurring because of his custom addons.

**Comment by temelkirci** [comment]
I am using v1.83.I tried it, but did not work for me.I changed killed function like that, but I do not see any error in database logs.

        public override void Killed(EntityInfo lastAttacker)
        {
            base.Killed(lastAttacker);

            try
            {
                lastAttacker.TryGetEntity(out BaseCharacterEntity attackerCharacter);

                // If this summoned by someone, don't give reward to killer
                if (attackerCharacter == null || !CharacterDatabase.EnableDrop())
                {

                }
                else
                {
                    // Giving gold and exp to players
                    GivingRewardToKillers(FindLastAttackerPlayer(lastAttacker), out float itemDropRate);

                    receivedDamageRecords.Clear();
                    // Clear dropping items, it will fills in `OnRandomDropItem` function
                    _droppingItems.Clear();

                    itemDropRate *= GameInstance.Singleton.GameplayRule.DropRate;

                    // Drop items
                    CharacterDatabase.RandomItems(OnRandomDropItem, itemDropRate);

                    switch (CurrentGameInstance.monsterDeadDropItemMode)
                    {
                        case DeadDropItemMode.DropOnGround:
                            for (int i = 0; i < _droppingItems.Count; ++i)
                            {
                                ItemDropEntity.DropItem(this, RewardGivenType.KillMonster, _droppingItems[i], _looters);
                            }
                            break;
                        case DeadDropItemMode.CorpseLooting:
                            if (_droppingItems.Count > 0)
                                ItemsContainerEntity.DropItems(CurrentGameInstance.monsterCorpsePrefab, this, RewardGivenType.KillMonster, _droppingItems, _looters, CurrentGameInstance.monsterCorpseAppearDuration);
                            break;
                    }
                }

                if (!IsSummoned)
                {
                    // If not summoned by someone, destroy and respawn it
                    DestroyAndRespawn();
                }

                // Clear looters because they are already set to dropped items
                _looters.Clear();

                if (this != null && CharacterDatabase != null)
                    CharacterDatabase.ClearMonsterSpawns();
            }
            catch(Exception ex)
            {
                Logging.LogError("Killed error : " + ex.Message);
            }       
        }



I also add aggro for item.When you use it all monster your around will attack you.

        [ServerRpc]
        protected virtual void ServerBraveryCape()
        {
#if UNITY_EDITOR || UNITY_SERVER
            List<BaseMonsterCharacterEntity> monsters = FindGameEntitiesInDistance<BaseMonsterCharacterEntity>(25, CurrentGameInstance.monsterLayer.Mask);
            foreach (BaseMonsterCharacterEntity monster in monsters)
            {
                if (monster != null && !monster.IsDead() && !monster.CharacterDatabase.useOnlySkill)
                {
                    monster.SetTargetEntity(this);
                }
            }
#endif
        }

My my custon addons will break it.

**Comment by temelkirci** [comment]
My rewardingtokillers function here


private void GivingRewardToKillers(BasePlayerCharacterEntity lastPlayer, out float itemDropRate)
        {
            itemDropRate = 1f;
            if (receivedDamageRecords.Count <= 0)
                return;

            Reward reward = CurrentGameplayRule.MakeMonsterReward(CharacterDatabase, Level);
            BaseCharacterEntity tempCharacterEntity;
            bool givenRewardExp;
            bool givenRewardCurrency;
            float tempHighRewardRate = 0f;

            BaseCharacterEntity enemy = null;


            foreach(var temp in receivedDamageRecords.Keys)
            {
                if(enemy == null)
                {
                    enemy = temp;
                    break;
                }
            }

            if (enemy == null)
                return;

            tempCharacterEntity = enemy;
            givenRewardExp = false;
            givenRewardCurrency = false;

            float rewardRate = 1;
            if (rewardRate > 1f)
                rewardRate = 1f;

            if (tempCharacterEntity is BaseMonsterCharacterEntity tempMonsterCharacterEntity && tempMonsterCharacterEntity.Summoner != null && tempMonsterCharacterEntity.Summoner is BasePlayerCharacterEntity)
            {
                // Set its summoner as main enemy
                tempCharacterEntity = tempMonsterCharacterEntity.Summoner;
            }

            try
            {
                if (tempCharacterEntity is BasePlayerCharacterEntity tempPlayerCharacterEntity)
                {
                    bool makeMostDamage = false;
                    bool isLastAttacker = lastPlayer != null && lastPlayer.ObjectId == tempPlayerCharacterEntity.ObjectId;
                    if (isLastAttacker)
                    {
                        // Increase kill progress
                        tempPlayerCharacterEntity.OnKillMonster(this);
                    }
                    // Clear looters list when it is found new player character who make most damages
                    if (rewardRate > tempHighRewardRate)
                    {
                        tempHighRewardRate = rewardRate;
                        _looters.Clear();
                        makeMostDamage = true;
                        // Make this player character to be able to pick up item because it made most damage
                        _looters.Add(tempPlayerCharacterEntity.Id);
                        // And also change item drop rate
                        itemDropRate = 1f + tempPlayerCharacterEntity.CachedData.Stats.itemDropRate;
                    }
                    GivingRewardToGuild(tempPlayerCharacterEntity, reward, rewardRate, out float shareGuildExpRate);
                    GivingRewardToParty(tempPlayerCharacterEntity, isLastAttacker, reward, rewardRate, shareGuildExpRate, makeMostDamage, out givenRewardExp, out givenRewardCurrency);

                    // Add reward to current character in damage record list
                    if (!givenRewardExp)
                    {
                        // Will give reward when it was not given
                        int petIndex = tempPlayerCharacterEntity.IndexOfSummon(SummonType.PetItem);
                        if (petIndex >= 0 && tempPlayerCharacterEntity.Summons[petIndex].CacheEntity != null)
                        {
                            tempMonsterCharacterEntity = tempPlayerCharacterEntity.Summons[petIndex].CacheEntity;
                            // Share exp to pet, set multiplier to 0.5, because it will be shared to player
                            tempMonsterCharacterEntity.RewardExp(reward, rewardRate, RewardGivenType.KillMonster);
                            // Set multiplier to 0.5, because it was shared to monster
                            tempPlayerCharacterEntity.RewardExp(reward, rewardRate, RewardGivenType.KillMonster);
                        }
                        else
                        {
                            // No pet, no share, so rate is 1f
                            tempPlayerCharacterEntity.RewardExp(reward, rewardRate, RewardGivenType.KillMonster);
                        }
                    }

                    if (!givenRewardCurrency)
                    {
                        // Will give reward when it was not given
                        tempPlayerCharacterEntity.RewardCurrencies(reward, 1, RewardGivenType.KillMonster);
                    }
                }
            }
            catch (System.Exception ex)
            {
                Logging.LogException(ex);
            }
        }

**Comment by insthync** [comment]
I won't read it, and I won't fix what I've fixed again.

**Comment by insthync** [comment]
What I told you to change to log without log tag, I mean in `DefaultCharacterUseSkillComponent -> UseSkillRoutine`

**Comment by temelkirci** [comment]
OK I will try it.Thak you
