### ISSUE TITLE
Error dedicated server

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#227]
hi, i follow every step in documentation for dedicated server in D O but when i try the run the server , this message appear :
/root/Build.x86_64: error while loading shared libraries: UnityPlayer.so: cannot open shared object file: No such file or directory

**Comment by insthync** [comment]
Please check that when you build it, did you tick on server build or not, And your Droplet is a Linux 64 bit or not.

![Screenshot_33](https://user-images.githubusercontent.com/2697550/74503599-fae54300-4f23-11ea-9364-8f27c180b8ac.png)

**Comment by Blunnyn** [comment]
this is my Droplet
![WhatsApp Image 2020-02-14 at 8 28 53 AM](https://user-images.githubusercontent.com/45702662/74529784-5228ea80-4f07-11ea-88ec-85cd615258fc.jpg)

and the build settings
<img width="626" alt="Captura de Pantalla 2020-02-14 a la(s) 08 49 29" src="https://user-images.githubusercontent.com/45702662/74529833-666ce780-4f07-11ea-8fd1-93be6d4bfa25.png">

**Comment by Callepo** [comment]
Ur not using the Config Files properly cuase "/root/Build.x86_64" is the default name in the kit for server 
to check if its  the Config files try this Command
/root/Test.x86_64 -startMapSpawnServer -spawnExePath  "/root/Test.x86_64" -startCentralServer -startChatServer -machineAddress "123.123.123.123"

the Test should be ur Build name and the 123.123 ur server ip adress

**Comment by poaq** [comment]
This is super feature from unity. Solution: COPY UnityPlayer.so from project folder to place where you have server binary and data folder.
