### ISSUE TITLE
Alpaca is constantly getting bugs.

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#2270]
Hello!
Fresh installation of the package (1.85b3) / Unity ver: 2022.3.10f1
Alpaca is constantly getting bugs.
NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.RigidBodyEntityMovement.GetGroundCheckRadius () (at Assets/UnityMultiplayerARPG/ObsoleteEntityMovements/Scripts/EntityMovementSystems/RigidBodyEntityMovement.cs:208)
MultiplayerARPG.RigidBodyEntityMovement.OnDrawGizmos () (at Assets/UnityMultiplayerARPG/ObsoleteEntityMovements/Scripts/EntityMovementSystems/RigidBodyEntityMovement.cs:216)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

![изображение](https://github.com/suriyun-production/mmorpg-kit-docs/assets/16080577/cb199844-0e44-46c1-b5f2-9b91e2097a1c)
![изображение](https://github.com/suriyun-production/mmorpg-kit-docs/assets/16080577/ebf0ec3b-8402-4a3b-ae0d-052547ae6904)

**Comment by insthync** [comment]
This one can be ignored, not a big thing, it was fixed and it will be included in the next version
