### ISSUE TITLE
after xp tree update mobs giving -gold - xp

### ISSUE THREAD

**Issue by john5514** [suriyun-production/mmorpg-kit-docs#2272]
Hi

After updating the level tree, mobs give -gold and -xp

I tried to solve it but it didn't work, I would be very grateful if you can help me how to solve it

https://prnt.sc/Hdkib39BejMy
https://prnt.sc/vjZZpZvslAxR

https://prnt.sc/S8LMvwAbgek5
https://prnt.sc/lwkUtCT4QMym

**Comment by john5514** [comment]
any help?

**Comment by insthync** [comment]
I didn't check it yet. I have to tell you I didn't work on this project full time.

**Comment by john5514** [comment]
Okey i am waiting thanks
