### ISSUE TITLE
[Bug?] Dealing with debuffs.

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#2273]
This isn't really a bug, but it seems to be a bit of an oversight on how buffs /status effects work. 

Its fairly easy to set attacks or items up to give players debuffs/status effects, however I don't see a good way to deal with them from an item/skill perspective. For example, let's say my skill causes poison a player. This is a status effect that lowers the movement capability of the player, **until dealt with**.

**How could I set up a skill and item, to remove that? i.e. a player using an antidote on themselves, or another player casting a spell to cure poison.**

**Comment by insthync** [comment]
Bug?

**Comment by LordPhrozen** [comment]
@insthync Perhaps I am just missing something.

How could I set up a skill and item, to remove a specific buff or status effect? ( like curing a poison ).

**Comment by insthync** [comment]
Did not implement it yet

**Comment by LordPhrozen** [comment]
Ah ok, thanks for the info. Eagerly awaiting that feature for sure. Thanks!
