### ISSUE TITLE
PlayerCharacterEntity prefabs error

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2274]
hello I upgraded to version 1.85b3, the character prefab was like this, how can I fix the problem, there was no such thing in the previous version.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/03b3a8c0-7c46-4d1b-afaf-6ac4b293af68)

**Comment by CLAXES** [comment]
This place in CharacterControllerEntityMovement :

        private Vector3 GetGroundCheckCenter(float radius)
        {
            return new Vector3(CacheTransform.position.x, CacheTransform.position.y + radius - groundCheckYOffsets, CacheTransform.position.z);
        }

worked when I did it this way:

        private Vector3 GetGroundCheckCenter(float radius)
        {
            return new Vector3(CacheTransform.position.x, (CacheTransform.position.y + radius) - groundCheckYOffsets, CacheTransform.position.z);
        }

PlayerCharacterNpcActionComponent I have not found the problem here yet.

**Comment by insthync** [comment]
What is the problem?

**Comment by insthync** [comment]
Did you just add `()` to fix issues?

**Comment by CLAXES** [comment]
yes CharacterControllerEntityMovement is fixed here now, but PlayerCharacterNpcActionComponent I can't understand what's wrong with it, I can't add it into the object, it doesn't see the scprit.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/e8005e2c-5f16-484f-9a3a-d52f860a6a17)

**Comment by insthync** [comment]
You don't have to change codes, you can revert that one, you have to reimport the script by right-clicking on the script file and selecting reimport. It is Unity's issue.

You should know that adding `()` is just like doing nothing.

**Comment by CLAXES** [comment]
I didn't know there was such a thing, sorry, the problem was caused by unity, it's fixed now.
