### ISSUE TITLE
Problem When Moving Using a Skill With Root Motion / Suggestions?

### ISSUE THREAD

**Issue by joabekaul** [suriyun-production/mmorpg-kit-docs#2276]
Hello, I have a bug here, I believe it's easy to solve, but as I'm not an expert I don't know how to do it, what happens is the following, I have my attacks using root motion, some of these attacks move my character forward, however If my movement keys were pressed at the same time (forward or backward) my character will move according to the keys and not according to the animation, so I tried to leave the movement speed as 0, however, this way, if the player presses the movement keys during the attack (which will definitely happen) the animation gets stuck in place without movement, so I was wondering if you could tweak a solution for me? Maybe a box to disable the movement keys while using the skill instead of just reducing the character's speed? I don't know how to do that, thanks

VÍDEO BUG:

https://youtu.be/y1wW0Mlik40

**Comment by moepi2k** [comment]
Set movespeed while attack to 0 and change script to this
https://gyazo.com/c5471fe14a8cc9871f6aaa56aa6ee58f
-> removing the directions. With this u can let the key pressed without stopping the rootmotion

**Comment by joabekaul** [comment]
what is this script?

**Comment by joabekaul** [comment]
thx bro, this solved it

**Comment by joabekaul** [comment]
OMG, this solved the problem, but it created others, such as desynchronization and also bugged the direction of movement, when I walk backwards, my character doesn't move, and for others it moves forward :/

**Comment by joabekaul** [comment]
and also changed the movement speed

**Comment by insthync** [comment]
Very tired of everything related to root motion, I should not have implemented it in the first place. Should I just remove it and tell you guys that it is not supported? No? :)

**Comment by insthync** [comment]
Root motion problem every week.

**Comment by joabekaul** [comment]
:/ please don't remove it, we use it like this

**Comment by moepi2k** [comment]
@joabekaul i use that fix for my game for over 1 year and its fine. the direction thing u mention is something else. and the slight desync its how it is with rootmotion. i think @insthync was able make rootmotion really good now. we should live with how it is :)

**Comment by joabekaul** [comment]
yes, I agree, it's very good now... thanks for the great kit @insthync... but if there is a definitive solution to this key issue that would be great, thanks for now

**Comment by joabekaul** [comment]
Hello friend, I solved the problem by creating a new function to disable movement when using the skill

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/114507343/153330a7-f0a3-4b79-b9c6-787fca1694f6)
