### ISSUE TITLE
Add our own keys in UITextKeys & UIFormatKeys

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2278]
Hello,

It would be really fun to be able to add our own keys to those scripts without modifying the core script directly.

I have no clue if using partials for them could work, or some sort of magic at runtime to add our custom keys to the list.

Currently the only way to add our custom keys (if I understand properly) is to use the UI_CUSTOM from the UIFormatKeys and this only works using the LocaleKeySetting script. And all of this, only works for client stuff, it wont work for server messages, game messages, etc.

Currently I have a region in those scripts with my custom keys added for my game, it works, but I need to keep track of those changes every updates. Is there any other way, we could modify those scripts so it can let us add our custom keys for messages sent by the servers?

Thanks a lot

**Comment by insthync** [comment]
The same thing with `TextSetterByLocaleKey` ?

You should try to create a pull request.

**Comment by Eniotnacram** [comment]
"TextSetterByLocaleKey" works really well for UI client stuff, like buttons, titles and all. But if I want to send a game messages from server, like an error or an alert, how should I proceed without creating a new key (modifying core) in UITextKeys or UIFormayKeys ?

**Comment by Eniotnacram** [comment]
I'm really talking about, servers messages, that I want to create. All of the existing server messages (gamemessage) logic from kit uses the UITextKeys to sent the messages. How I am supposed to proceed if I want to do the same thing using new UITextKeys? Without Modifying the UITextKeys directly to add more keys (my custom keys).

**Comment by insthync** [comment]
Add codes to send custom ID to client

**Comment by Callepo** [comment]
> Add codes to send custom ID to client

i helped him, created an addon for custom servermessages by partial scripts
Only the UIGameMessageHandler script is very bad,
Everything is private, no virtuals nothing.
had to literally copy paste the whole script to add 1 method..
Ill change this later or u can do it, would be much easier to get custom messages

**Comment by insthync** [comment]
Don't know whats you've made changes, you can create a new pull request for that

**Comment by insthync** [comment]
@Callepo you actually can make you directly to core's 

- `ClientGenericActions`
- `IClientGameMessageHandlers`
- `DefaultClientGameMessageHandlers`
