### ISSUE TITLE
Sheathing

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2279]
How do i call Weapon Sheathe via Button?
i know there is a duration to activate sheathing but i want it via button toggle to sheathe weapons.

Additionally i want the Default animations to be used when weapon is Sheathed.

i just need some tips or guide on where would i find this

**Comment by insthync** [comment]
Just write a script to change this value `GameInstance.PlayingCharacterEntity.IsWeaponsSheathed`
