### ISSUE TITLE
BUG 1.53 Item dismantle

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#228]
You can dismantle all items (junks and etc)
[Item Dismantle Bug 1.53.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4202780/Item.Dismantle.Bug.1.53.zip)

**Comment by Koodetat** [comment]
an option to exclude an object would be interesting.

**Comment by insthync** [comment]
Fixed in 1.53b, and also add `dismantleFilter` setting to `GameInstance`, you can select type of items that can be dismantled.
