### ISSUE TITLE
Misses when attacking

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2282]
Hello, sometimes it doesn't hit between attacks, previous versions didn't have this problem, this problem started in the latest version, also when I press the buff skill, sometimes it works but it doesn't work in general, it works when I make cast duration 1, it used to work even if I didn't add it before.

I also leave the video below, when I press for skill buff, sometimes it presses and sometimes it does not press.
[Video](https://www.youtube.com/watch?v=FHpYazgrnSo)

skill buff settings like this
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/8796f76a-b314-4d8c-84d0-c5a16bf8e7f6)

I may not have been able to explain because my English is not very good, if you want, I can shoot a new video.

**Comment by insthync** [comment]
I can't reproduce it

**Comment by insthync** [comment]
Can you find anyone to confirm that this is occurring on their project too?

**Comment by insthync** [comment]
Found it and fix it already

**Comment by LordPhrozen** [comment]
Just caught this happening. Glad it was fixed, thanks so much!
