### ISSUE TITLE
IOS Auction house and zoom issue

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2283]
My all IOS players have these issues

When they click auction house button, game suddenly crash and exit.
When they rotate camera or zoom, game suddenly crash and exit.
When they teleport to a different maps, sometimes crash and exit.

I am using 1.83 kit verison, Unity 2022.3.8, xcode 14.3.1

My android players do not have these issue.What is problem ? 

[ProjectSettings.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/12890969/ProjectSettings.zip)

**Comment by shubhank008** [comment]
> My all IOS players have these issues
> 
> When they click auction house button, game suddenly crash and exit. When they rotate camera or zoom, game suddenly crash and exit. When they teleport to a different maps, sometimes crash and exit.
> 
> I am using 1.83 kit verison, Unity 2022.3.8, xcode 14.3.1
> 
> My android players do not have these issue.What is problem ?
> 
> [ProjectSettings.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/12890969/ProjectSettings.zip)

You should test in Unity Editor by switching build target to iOS and see if it crashes/exception, or use a exception/crash reporting tool on ios build to get some logs, there can be X number of factors for this if it happens and without logs its throwing darts in air.

Other options are, test auction house in kit's default demo on ios and see if it crashes
If it does, you can also test latest version in a new project to see if it crashes.

But yeah, get some logs mate

**Comment by temelkirci** [comment]
I realized that if I have a error in console (in game), IOS crash game suddenly.I think problem is about expection in xcode settings.I wsolved the auction house issue like that.I just uncommented refresh page funciton.

**Comment by insthync** [comment]
You can tell me where did you comment it.

**Comment by temelkirci** [comment]
![Ekran görüntüsü 2023-11-05 144550](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/1651318b-40f5-4401-aa29-b0dc7f8db13c)
