### ISSUE TITLE
(BUG)Bug in buff hide character

### ISSUE THREAD

**Issue by darkkriteus** [suriyun-production/mmorpg-kit-docs#2284]
I believe this option should be to hide the character, make him invisible

- However, when used, the character disappears, and appears when the buff ends, but when he appears he is unassailable, I tested this in a duel, as soon as the player appears again, he cannot be attacked. Maybe the server understands that he left the duel, something like that

- Another bug when used as a monster's ability, when the monster uses the hide character buff, it disappears, but no longer appears, as if it had completely disappeared from the map... I don't know if this was meant to be used on monsters as well, but it would be useful to have an ability buff for monsters as well.

tested on the latest version

**Comment by insthync** [comment]
Fixed, it will be included in 1.85c
