### ISSUE TITLE
How can I make a Game Control Panel in game?

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2285]
I want to manage all players and see all data on the screen.Like that -> https://www.youtube.com/watch?v=52Q7dFNqn_I&ab_channel=GameFunSPB

I want to get user information from database in character list screen.How can I succed it ?

![abcf7595-2800-4a2b-8276-725995448e28 (1)](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/eddc13fb-e5d1-49bc-912d-dacd460fd5d5)
![8877e5db-59e4-43b2-935d-4d4623a94127](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/b0f0284a-a099-4c39-b814-1ff8df72c537)

**Comment by insthync** [comment]
Easiest way might be
- Create a webservice which will connect and retrieve data from database directly.
- At the client connect to the webservice to get data
That is it, not hard.

**Comment by temelkirci** [comment]
@insthync Thank you
