### ISSUE TITLE
Mysql Exception

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2286]
ERROR No Tag [2023-10-15 20:57:59] - InvalidOperationException: Connection is not open.
MySqlConnector.MySqlConnection.BeginTransactionAsync (System.Data.IsolationLevel isolationLevel, System.Nullable`1[T] isReadOnly, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/MySqlConnection.cs:138)
MySqlConnector.MySqlConnection.BeginTransaction () (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/MySqlConnection.cs:43)
(wrapper remoting-invoke-with-check) MySqlConnector.MySqlConnection.BeginTransaction()
MultiplayerARPG.MMO.MySQLDatabase.UpdateCharacter (MultiplayerARPG.IPlayerCharacterData character, System.Collections.Generic.List`1[T] summonBuffs, System.Collections.Generic.List`1[T] storageItems, System.Boolean deleteStorageReservation) (at <132ed91020b548cdbc9bbadc2cc9fa7b>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at <5245e3d73fb64df6b6a9156f87588263>:0)
Cysharp.Threading.Tasks.UniTask+WhenAllPromise.TryInvokeContinuation (Cysharp.Threading.Tasks.UniTask+WhenAllPromise self, Cysharp.Threading.Tasks.UniTask+Awaiter& awaiter) (at <5245e3d73fb64df6b6a9156f87588263>:0)
--- End of stack trace from previous location where exception was thrown ---
Cysharp.Threading.Tasks.UniTask+WhenAllPromise.GetResult (System.Int16 token) (at <5245e3d73fb64df6b6a9156f87588263>:0)
MultiplayerARPG.MMO.DatabaseNetworkManager.UpdateCharacter (LiteNetLibManager.RequestHandlerData requestHandler, MultiplayerARPG.MMO.UpdateCharacterReq request, LiteNetLibManager.RequestProceedResultDelegate`1[TResponse] result) (at <132ed91020b548cdbc9bbadc2cc9fa7b>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.MMO.<UpdateCharacter>d__41:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.WhenAllPromise:TryInvokeContinuation(WhenAllPromise, Awaiter&)
Cysharp.Threading.Tasks.<>c:<.ctor>b__3_0(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception)
MultiplayerARPG.MMO.<UpdateCharacter>d__65:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetResult()
MultiplayerARPG.MMO.<OpenConnection>d__15:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

Im getting a bunch of that errors causing some Rollback or delays
can't send the whole logs but the exception is all that from GetMailNotification UpdateCharacter, ValidateUserLogin, All that has OpenConection on MySQL

**Comment by insthync** [comment]
I don't want to fix it, I've made [this](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager.git) to use instead of the database management server, learn about custom database client [here](https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/157-custom-database-client)
