### ISSUE TITLE
(animations improvements)

### ISSUE THREAD

**Issue by darkkriteus** [suriyun-production/mmorpg-kit-docs#2287]
I would like to ask if possible, add more animations for skills and movement, in the case of jumping, for example if I cast jumping it has a different cast animation than the cast on the ground, same thing for attacks, jumping attacks have a different animation

I think it would be interesting, also the possibility of having a jump counter would be cool, if the player jumps more than once in some games it would be cool.

**Comment by insthync** [comment]
How the config should be looks like?

**Comment by darkkriteus** [comment]
Simple, for example in the magic creator, the animation options like cast state and activate animation, also have to add animations in the air, for example

- Cast Animation in Jump/Air

- Activate Animation in Jump/Air

As for the attack, in the default Animation settings of the playerCharacterModel
In addition to the normal attack, it could have Attack Animations in Jump/Air

about having more jumps, I managed to implement it here, but if it was in the kit it would be something like

MaxPlayerJumps
AnimationsPlayerJumps, to have an animation for each jump, jump1, jump2, etc.

It would be interesting to have a sound when jumping and on land

I think that's it, thanks

**Comment by insthync** [comment]
How about hack detection for multiple jump?

**Comment by darkkriteus** [comment]
> How about hack detection for multiple jump?


It would be great if anyone wants to bypass the multiple jumps 😊

**Comment by insthync** [comment]
No, I mean did you think about how to do it?

**Comment by darkkriteus** [comment]
oh yes, actually I didn't modify the logic of sending the jump, I just changed the restrictions so you can jump without having to be on the ground, I also added the check if you still have jumps available, otherwise it will be impossible to jump again

**Comment by moepi2k** [comment]
sounds complex and is really game specific to me, isntit?

**Comment by hiraku1994** [comment]
It would be really interesting, since when the character jumps and releases skills, his animation is still like the ground.

**Comment by insthync** [comment]
Decline, I don't want to do anything about animation/movement anymore.
