### ISSUE TITLE
1.53 mobile third person shooter issue

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#229]
Mobile third person shooter. Player only attacks forward. Its funky you'll have to try it to see what I'm saying. If you attack from the side you face forward an attack.

**Comment by insthync** [comment]
I intently make the character turn forward to attack at location that player aiming, so I think it's working correctly.

**Comment by Fallen01** [comment]
you are saying if i am behind someone to the north and attack them to the south i should turn north and attack? That is what is happening.

**Comment by insthync** [comment]
Yes

**Comment by Fallen01** [comment]
I dont think your understanding me at all. Im just gonna hope i have a bad install or something and do it up fresh. Your convinced things are working normal im going to hope this issue is just in my project.

**Comment by Fallen01** [comment]
Im not saying its your fault that you dont understand me. I know i explain poorly at times. I lack the words to describe what im seeing yet its not right. Im going to install a fresh project and hope the issue vanishes.

**Comment by insthync** [comment]
Okay, you may capture the video which show the issues, upload to YouTube or zip and post here :)

**Comment by imakeinternet** [comment]
As it turns out, @Fallen01 is NOT crazy...entirely. Here is a video demonstrating the issue that happens when you attack from the north of side of an enemy. I think we need to check the orientation of the player relative to the target enemy and reverse the direction in these instances.

https://www.youtube.com/watch?v=IEfdiVpuJJw

**Comment by Fallen01** [comment]
Thank you for having the words I didnt!

**Comment by MostHated** [comment]
Hold on now. I would not go as far as saying @Fallen01 isn't crazy...

**Comment by Fallen01** [comment]
Were both crazy if were going to get into this on git..... Thats not the point! ;)

**Comment by insthync** [comment]
I made it always turn forward because most 3rd person shoulder games always turn character forward, I've added option `turnForwardWhileDoingAction` which while it's `TRUE`  character will turn forward while doing action, if not it will turn to target. So I will close this issues post.

**Comment by imakeinternet** [comment]
Cheers @insthync --- this was a nice surprise to wake up to. Thank you.
