### ISSUE TITLE
[Suggestion]Buffs/GM Commands

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#2290]
Hello,
Features I told you about
(Blind) You cannot see players when you are cursed.
(RevealsHide) When you use this, only those who have this buff will see invisible players.
GM Commands
/inv - Always makes the GM character invisible, even if the map changes. Is not affected by the (RevealsHide) curse.

Thank you.

**Comment by insthync** [comment]
Done
