### ISSUE TITLE
1.85c Error regarding ItemRandomBonusCache

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#2293]
Hey there,

i just imported 1.85C in my existing project (which was working fine before upog 1.85b). But i get 2 errors now:

Assets\UnityMultiplayerARPG\Core\Scripts\Scripts\GameInstance\Caching\ItemRandomBonusCache.cs(132,83): error CS1929: 'DamageAmount' does not contain a definition for 'ToKeyValuePair' and the best extension method overload 'GameDataHelpers.ToKeyValuePair(DamageIncremental, int, float)' requires a receiver of type 'DamageIncremental'

and

Assets\UnityMultiplayerARPG\Core\Scripts\Scripts\GameInstance\Caching\ItemRandomBonusCache.cs(395,83): error CS1503: Argument 3: cannot convert from 'MultiplayerARPG.RandomCharacterStats' to 'bool'

is this an issue from the newest package or something on my part? i cant see the reason why my project should be the issue because it was working fine before upgrading it to the newest version

**Comment by insthync** [comment]
Delete the file named `ItemRandomBonusCache.cs`

**Comment by ChaosXIII** [comment]
Hey @insthync I had this same issue but with ItemRandomBonusCacheManager.cs

I deleted ItemRandomBonusCache.cs and nothing happened so I deleted ItemRandomBonusCacheManager.cs and the error went away. 

Was this wrong? Do I need ItemRandomBonusCacheManager.cs?

**Comment by insthync** [comment]
Yes, delete it, then tell me what are those error?

**Comment by ChaosXIII** [comment]
No more errors after deleting ItemRandomBonusCacheManager.cs 

Is  ItemRandomBonusCacheManager.cs  needed?

**Comment by insthync** [comment]
Yes, it is not needed anymore

**Comment by ChaosXIII** [comment]
Thank you!
