### ISSUE TITLE
Area skil error

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2294]
hello this error occurs when using area skil

Version: 1.85c

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/7765b48e-7839-4d24-bbd6-f9a487ccd8ce)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/4baec4df-a104-4e73-ae9e-f0807ceb80cc)

**Comment by insthync** [comment]
The first one occurred because I changed the parameters for the update character dev ext method invoking, you have to change the parameter for those dev ext methods to be `(MySqlConnection connection, MySqlTransaction transaction, IPlayerCharacterData character)`

**Comment by insthync** [comment]
![Screenshot_886](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/73b7a8c7-d536-497f-90c5-d516e5f9f744)

The second one
