### ISSUE TITLE
(Bug) Area cast casting error in mobs

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2299]
As the title says, when we give a mob the ability to throw a cast area, it will throw it in the player's position 0, 0, 0. It is a small bug. What it does is put the area in the middle of the player example image:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/62655c92-2923-42f6-af8e-52483b623286)
I was able to fix this by adding some new values ​​in the position and the transformation of the skills in MonsterActivityComponent class, but I imagine that it is only momentary and I will find a better way to fix it example code:
<img width="621" alt="Captura" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/286e04d7-a74d-4493-b84a-f4e1ff3478e6">

**Comment by insthync** [comment]
I don't think it is a bug, so I won't applies that one into the project, I recommend you to adjust the effects transform, collider center down to fit to the ground.

**Comment by Niinra** [comment]
I already tried to download the prefab and nothing like it fixes the position in the center of the target

**Comment by insthync** [comment]
Ahhh, just saw it is cast skill to opponent aim position, I will fix it by change condition to cast skill to grounded position if skill is area skill

**Comment by Niinra** [comment]
Well, thank you very much, if I could I would give him a hug but I can't, so I tell him that he is the best at what he does <3
