### ISSUE TITLE
Fps hiding object and hiding Renderers

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#230]
When u try to hide Object on switching From Tps to Fps
ur character animations stop.. u stay in frozen and character glides around..
when u Exit the Fps mode ( switch back to Tps)
The object that was hidden is still hidden..
in my case i was hiding the head.. my character was headless in Tps and no animation

when hiding Renderers.. Using 1 Render is Fine..
Using >1 it has same issue as above with Objects hiding

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.53b, if the problem still occurring, you can reopen it.
