### ISSUE TITLE
[Bug]Stackable items with diffrent Level

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2301]
There is an issue. when you have stackable items with diffrent levels e.g a potion and craft/loot/pickup anyother one of same type but diffrent level, it override the one in inventory.

**Comment by insthync** [comment]
I intended to make level for an equipment items only.

**Comment by moepi2k** [comment]
oh then, i extended my crafting system so that as higher the crafting skill as higher the level of the item. so i think i need to make the changes into my project then. any advice in what script it handle the merge when pickup/loot etc. an item?
