### ISSUE TITLE
[Request] Attack Status Effects to show in UI Character Skill

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2302]
Hello,

With the new Status effect implementation (resistance), I've added them to my skills instead of using the built in buff/debuff. Problem is, the data of that status effect (stats, effects, etc) cannot be shown in the UI Character Skill.

Would appreciate if we can add this, so players can read the effects of the status effects in game. (Like it is already working for the buff/debuff).

Thanks for your great work again.

**Comment by insthync** [comment]
It is actually can be added by writing it manually in description :P

**Comment by Eniotnacram** [comment]
> It is actually can be added by writing it manually in description :P

.... okay, I will try to do it and make a merge request. Using description wont work for me

**Comment by insthync** [comment]
You can write anything, how it won't work :P

**Comment by Callepo** [comment]
yea, the point of the status effect is u can use same S/O for 200 skills, and have the same data show there, instead of having to manually type description on the skill.

Or atleast if the Description of the status effect was the one that was showed on the skill, that would also be decent. but not that u gotta write on 200 skills even if its the same status effect

**Comment by Callepo** [comment]
Something like just 
[Status Effect Title] : [Apply chance], [Duration]
[Stun] : [30% chance], [3 Seconds]

**Comment by insthync** [comment]
I see, I am just trolling, have check that status effects are parted with which features, as I remember, they are parted of buffs, and equipments, so may create a new component for status effect, and use it as part of equipment UI and buff UI

**Comment by Callepo** [comment]
> I see, I am just trolling, have check that status effects are parted with which features, as I remember, they are parted of buffs, and equipments, so may create a new component for status effect, and use it as part of equipment UI and buff UI

yea i know ur just playing cuase of the ( :P) and yea, i tried creating one, but the list for the effect made it more dificullt

**Comment by Eniotnacram** [comment]
> I see, I am just trolling, have check that status effects are parted with which features, as I remember, they are parted of buffs, and equipments, so may create a new component for status effect, and use it as part of equipment UI and buff UI

I knew you were just trolling me aha! Thank you for checking this :)

**Comment by LordPhrozen** [comment]
If you're taking a second look at status effects, I would love to ask that spells get a "remove these status effects" section added. 

Lot's of fun gameplay from both the PvE and PvP side of things if we can remove them.

#2273
