### ISSUE TITLE
[Question] Get Instance ID on the Clientside

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#2304]
Hey Suri,

i´m sorry to disturb you with my question. I hope you could answer it anyway.

Is there anyway to get the ID from an instance on the clientside? ( i want to generate my dungeon with a seed and the instance id would be perfectly for that).

![Log](https://github.com/suriyun-production/mmorpg-kit-docs/assets/93816817/6b759dda-a286-4d22-a009-f12c90b35d5c)

by instance id i mean the part at the end of the logfiles Log_Map(Dungeon001)-Channel(1)-Allocate(False)-Instance(XXXXXXXXXX).info

Thank you for your time :)

**Comment by xnitro1** [comment]
Still hoping for an answer :)

**Comment by insthync** [comment]
Create a dev ext function for `WriteMapInfoExtra (NetDataWriter)` and `ReadMapInfoExtra (NetDataReader)`

write seed with `WriteMapInfoExtra`, read seed with `ReadMapInfoExtra`

**Comment by insthync** [comment]
Or create a class which extended from `BaseGameNetworkManagerComponent` which implements `WriteMapInfoExtra` and `ReadMapInfoExtra` and attach the class to the same game object with map network manager
