### ISSUE TITLE
Archer damage problem

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2306]
When I enter the bottom of the creature I added with the archer, when I attack, it does not give hit damage when I attack, it does damage when I move away and hit. how can I fix this problem?

**Comment by insthync** [comment]
If you really want to fix it by yourself, then read this  https://github.com/suriyun-production/mmorpg-kit-docs/issues/2300#issuecomment-1815354534).If you are not, then please don't ask "how" next time, just tell me your problem, that is it. I know I cannot expect anything from my customers, but please don't make me down by expecting that you are going to do it.
