### ISSUE TITLE
Navmesh Question

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2307]
Does the kit support any type of navigation for AI? Or does it have to be the Unity's NavMesh? What I am asking is if I can use custom NavMesh? Or can i use "A* NavMesh" / "A* Pathfinding" without any problems?

**Comment by insthync** [comment]
You've to write your own new component, If you can write your own entity movement component, then you can use any movement components without problems, if you want to learn how to write it, you can learn from NavMeshEntityMovement, which made to works with Unity's NavMeshAgent only.

**Comment by AsheshPlays** [comment]
Yes I will write a custom one. I want to clarify this too, do i need to edit the network part for custom NavMesh or no need? I am planning to write an "A* (star) NavMesh / Pathfinding".

**Comment by insthync** [comment]
I don't know too, it is up to that component and how are you going to implement it.
