### ISSUE TITLE
[Bug]Equipped Item UI

### ISSUE THREAD

**Issue by ayaldabos** [suriyun-production/mmorpg-kit-docs#2309]
Whenever i use skill or potion or buff that has duration the equipped item UI stop working untill the skill or potion duration ends 
that happens only to the equipped items 
unequipped items ui works normally

**Comment by insthync** [comment]
I don't get how is it?

**Comment by ayaldabos** [comment]
> I don't get how is it?

try to use any potion or buff skill that has duration time and u will not be able to select any equipped item in inventory it will keep auto close the itemdialog Ui untill the potion duration finish

**Comment by insthync** [comment]
You can fix it by changes codes in `UISelectionEntry.cs` -> `OnClickSelect` function

```
    public void OnClickSelect()
    {
        if (selectionManager != null)
        {
            UISelectionMode selectionMode = selectionManager.selectionMode;
            if (selectionMode == UISelectionMode.Toggle && IsSelected)
                selectionManager.Deselect(this);
            else if (!IsSelected)
                selectionManager.Select(this);
        }
    }
```

**Comment by LordPhrozen** [comment]
@insthync This seems to also be occurring with shop item info panels, and equipment compare panels too.

**Comment by insthync** [comment]
It has been fixed, but not like I posted here.
