### ISSUE TITLE
Character Body parts Manager Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2311]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/b49e42a4-183b-423c-b5fd-d780aa2b6315

Whatever is the first character, His list of parts will be applied to all the other models in the selection list...
I changed the list from male to be Bald as default and hair 2, and female hair as default and bald 2,
when female is first in the list, and i had created selected bald, all other models will also be bald, cuase its using the female body parts index list for all the models

This is becuase the fake equip data thats being generated through code is the same, so the equipmodel from basecharactermodel is not remaking it, cuase it thinks its reequipping the same model.

**Comment by Callepo** [comment]
On it self u can think, maybe just use the same order for all of them and it wont matter, but it does..
if u have different models, and it tries to setup the same body parts for all models, it looks very bad.. 
But this only happens in the Character Select List, Ingame u only load 1 character at a time, so its fine in game.. 

https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/ba2a36cb-dc8b-486a-8fd9-034cc3c4362f

**Comment by insthync** [comment]
Is it only a materials problem or meshes too?

**Comment by Callepo** [comment]
> Is it only a materials problem or meshes too?

Mesh

**Comment by Callepo** [comment]
They both are used from the first character spawned, mesh + material color

**Comment by insthync** [comment]
Fixed
