### ISSUE TITLE
Hit Validation

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2312]
IDK if its worth mentioning, 
The New changes to hit validation, are a bit better, but at higher speeds like 150>200 is still missing alot. 

But the thing is, in the older version, when i did this. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/1024a969-ffc8-4da2-b53d-ec77b06644d1)

It was hitting perfect 150-200 etc, 0 misses,

With all the new changes, even when i change the hit validation back to what i did before, at 150  it start to miss alot now.. 
and 200 is like unplayable
So the older version with my Edits aka ,just implementing a variable to adjust the ranged based on missile speed, was working very well, and now doing the same with all the extra changes, not even my edit is working on 200.

so idk if we should even be having projectiles above 150-200 etc, 
because at very close ranged, even with the Validation disabled, u can still miss.

but in any case, the older version was more accurate, with or without hit validation enabled.

**Comment by insthync** [comment]
I want to know how the 0.002 come from

**Comment by Callepo** [comment]
> I want to know how the 0.002 come from

Random value i added to Take from the 0.8 u added based on missile speed. 
So if missile speed is 50
Its 0.8-0.1=0.7
But if missile speed is 200
its 0.8- 0.4 = 0.4

At High speeds, the missile was going below 0.8, which is what was making it miss, cuase would declare it as false.. 
The value is static, which didnt work wel, having it be adjusted by the Missile Speed, made it still do validation and be able to have high speeds.

So like if server speed is just 50
and someone speedhacks client, the calculation will still determine it was false, cuase it wouldnt match up with server speed and the calculation. 

Ive tested 0.001 and 0.0015, but they both start failing above 150 ish
the 0.002 worked for 200 with 0 issues

Only issue, which is not hit validation related i think is if the monster is standing close to the player, u sometimes dont hit, u have to  take 1 step back

**Comment by insthync** [comment]
I think my calculation about acceptable speed is wrong

It calculated client's missile speed by client's missile dist and time

It should accept if client's missile speed is lower or a bit higher

but with formula `if (client missile speed / server missile speed < 0.8) => false`, it won't accept very low client's missile speed and not accept a bit higher

for example, if server speed is `200` and client speed is `150`, it should accept because client speed is very low

then 150 / 200 = 0.75, so it is less than 0.8 and does not accept.

I think I will change formula to `if (client missile speed / server missile speed < 1.05) => true`

**Comment by Callepo** [comment]
> I think my calculation about acceptable speed is wrong
> 
> It calculated client's missile speed by client's missile dist and time
> 
> It should accept if client's missile speed is lower or a bit higher
> 
> but with formula `if (client missile speed / server missile speed < 0.8) => false`, it won't accept very low client's missile speed and not accept a bit higher
> 
> for example, if server speed is `200` and client speed is `150`, it should accept because client speed is very low
> 
> then 150 / 200 = 0.75, so it is less than 0.8 and does not accept.
> 
> I think I will change formula to `if (client missile speed / server missile speed < 1.05) => true` to not accept if client's missile speed is too high

Sure when u push changes to repo, ill make new tests and let you know how it goes.

**Comment by Callepo** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/fab1f56f-e1e5-433d-9e8c-8674823c765f

@insthync Perfect.. 200 speed.. not a single miss, even when super close it hits target
