### ISSUE TITLE
get_item() error when I sometimes close to player in map

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2315]
I a getting this error when I sometimes close to a player.What is the reason?

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:0)
LiteNetLibManager.LiteNetLibSyncList`1[TType].get_Item (System.Int32 index) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibSyncList.cs:100)
MultiplayerARPG.SyncListCharacterBuff.DeserializeValueForSetOrDirty (System.Int32 index, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/Scripts/CharacterData/RelatesData/CharacterBuff.cs:132)
LiteNetLibManager.LiteNetLibSyncList`1[TType].DeserializeOperation (LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibSyncList.cs:407)
LiteNetLibManager.LiteNetLibSyncList`1[TType].ProcessOperations (LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibSyncList.cs:372)
LiteNetLibManager.LiteNetLibIdentity.ProcessSyncList (LiteNetLibManager.LiteNetLibSyncList syncList, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibIdentity.cs:364)
LiteNetLibManager.LiteNetLibIdentity.ProcessSyncList (LiteNetLibManager.LiteNetLibElementInfo info, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibIdentity.cs:357)
LiteNetLibManager.LiteNetLibGameManager.HandleServerUpdateSyncList (LiteNetLibManager.MessageHandlerData messageHandler) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:896)
LiteNetLibManager.TransportHandler.ReadPacket (System.Int64 connectionId, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:78)
LiteNetLibManager.LiteNetLibClient.OnClientReceive (LiteNetLibManager.TransportEventData eventData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:77)
LiteNetLibManager.LiteNetLibClient.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:36)
LiteNetLibManager.LiteNetLibManager.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:149)
MultiplayerARPG.BaseGameNetworkManager.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/Networking/BaseGameNetworkManager.cs:118)
MultiplayerARPG.MMO.MapNetworkManager.Update () (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Networking/Map/MapNetworkManager.cs:176)

**Comment by Niinra** [comment]
Does this affect anything in your game? , I see that it is due to a buff that is not instantiated or it seems that it does not read the information of the buff data, if it does not affect the playability of your game at all, I think you could ignore it and that's it, or provide more information about what it causes because really just putting the logs is not very helpful...

**Comment by Callepo** [comment]
Core error messages, and logs shouldn't be ignored, can cause other stuffs later on, you never know.
the github is for these things also, prolly one of few post related
