### ISSUE TITLE
Swim To Surface bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2317]
When enable Swim to surface, u cant get out of water anymore
Not even with ShooterCharacter Controller
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/7036cb3d-c9ec-4666-ae34-c22337f99172

It even sees it as ground, cause i can jump. but ur stuck there.
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/81522bbf-62b7-4443-b93b-512c41efb8cd

**Comment by moepi2k** [comment]
another weird thing i noticed is when enable swimm to surface is. stock kit character works fine. but custom character bounce at surface. i tested diffrent.

**Comment by Callepo** [comment]
> another weird thing i noticed is when enable swimm to surface is. stock kit character works fine. but custom character bounce at surface. i tested diffrent.

u gotta fix settings on ur char, i had the same, played with it alot and got it working

**Comment by Callepo** [comment]
Ur center has to be smaller than the Height/2
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/4da66cba-a6d6-4025-af0f-9781778bb625)
@moepi2k if its same or bigger it keeps glitching at top

**Comment by Callepo** [comment]
is what worked for me
But now im stuck in water same as base kit

**Comment by insthync** [comment]
Try latest commit

**Comment by Callepo** [comment]
> Try latest commit

From what i could see, its working nicely, even with my custom models. no glitching on water, gets out good. 
Looks nice

**Comment by Callepo** [comment]
If ur using Rootmotion While not Moving, ur character Sinks to the bottom @insthync 
the bools for rootmotion are not great, cuase to be able to use rootmotion while attacking
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/ea89383f-338e-4512-a247-d0aa35aa34e6)

we need to select this one, and then edit the buildin movement 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/bfe41bfb-601f-436b-9dc5-1b3497feaa87)

To remove those, so we can have skills/ auto attacks with root motion. cuase even if character movespeed is 0 while attacking, it will still be false, and not apply rootmotion, cuase ur pressing forward or backwards etc.

**Comment by Callepo** [comment]
So option are
1) find animations for swim with rootmotion idle
2) Dont have Rootmotion for attacking
3) Dont have swimming at all

**Comment by insthync** [comment]
Then I think I should change `useRootMotionWhileNotMoving` name to `alwaysUseRootMotion`

**Comment by Callepo** [comment]
there should be an option to use rootmotion for attacks
Cuase a lot of us uses normal animation for movement, and only root for attacking

**Comment by insthync** [comment]
Yes, that is why I ask to change its name and conditions

**Comment by Callepo** [comment]
Are u also adding 1 for just attacking? 
cuase otherwise there would still be the problem when swimming and u idle in water, it will expect u have an animation that has rootmotion to keep it above water

https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/5b910a50-2c1c-4ffa-84d6-a86b5f8474c3

**Comment by Callepo** [comment]
Or a Bool in the animation
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/9d506ee2-f9ea-412a-9c18-3af712f6f5b8)

To use Rootmotion for that specific animation

**Comment by insthync** [comment]
I will add it

**Comment by Callepo** [comment]
ur the man as always!

**Comment by insthync** [comment]
Did it, but did not tested yet :P
