### ISSUE TITLE
Small improvement to the expiration system

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2318]
Good evening, I wanted to see if a small improvement could be made to the item expiration system to be able to use minutes and seconds as well, it's a small thing so I checked and adjusted it in the core, but since this is only possible directly by changing this in the core, if I'm wrong correct me, it's just to add this small change
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/ddbb3435-cb81-4cbc-993c-7aa1a645d20b)

Example: enter 30 seconds, the object expires in 30 seconds. If you enter 60, it expires in one minute, I think it can be simplified better

If it is more complex than I think and not a small change, then do not waste time on this, there are more important things, thank you very much :3

**Comment by Callepo** [comment]
What benefit would this offer? 
i cant see a single reason.
60 seconds is a minute, do u just want him to add a value specifically to put minutes? 
and then what if someone wants an hour? 
add another for hours? 

While 60 secs = 1 min..
3600 secs = 1 hour.
Etc etc. 
This is the simplest way without being dumb and adding bunch of values while 1 can do the same.

**Comment by Niinra** [comment]
If you had stopped to think for just 1 second you wouldn't say ''What benefit would this offer'' or call it dumb.

Since I see you weren't resourceful enough to come up with some scenarios where this could be useful, I'm going to help you out a bit because I'm in a good mood.

Case 1: This opens the possibility of making skills with new features, example: A skill that will craft you a pretty powerful sword with a duration of 10 seconds, you only have 10 seconds to use that sword and then it is destroyed, the value of seconds and minutes would come in handy for this scenario because it is a very powerful item and its disadvantage would be only in that duration window, it wouldn't make sense that it existing during 1 hour don't you think?

Case 2: Missions with time limit. Imagine a mission where you have to deliver an item whose expiration time is 10 min, this adds a more creative way to make delivery missions.

You can extrapolate this to several things if you are smart enough.

Now the simplest solution to my mind would be:

make a boolean that changes the way the ''expiration time'' value is handled from hours to seconds 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/d80fea49-4b8a-4fbe-91b9-3496fbce4500)
The example code I made would look like this :
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/dc53e5d8-3668-4d76-a534-18aa576b9cce)

**Comment by LordPhrozen** [comment]
> @Callepo If you had stopped to think for just 1 second you wouldn't say ''What benefit would this offer'' or call it dumb.
> 
> Since I see you weren't resourceful enough to come up with some scenarios where this could be useful, I'm going to help you out a bit because I'm in a good mood.
> 
> Case 1: This opens the possibility of making skills with new features, example: A skill that will craft you a pretty powerful sword with a duration of 10 seconds, you only have 10 seconds to use that sword and then it is destroyed, the value of seconds and minutes would come in handy for this scenario because it is a very powerful item and its disadvantage would be only in that duration window, it wouldn't make sense that it existing during 1 hour don't you think?
> 
> Case 2: Missions with time limit. Imagine a mission where you have to deliver an item whose expiration time is 10 min, this adds a more creative way to make delivery missions.
> 
> You can extrapolate this to several things if you are smart enough.
> 
> Now the simplest solution to my mind would be:
> 
> make a boolean that changes the way the ''expiration time'' value is handled from hours to seconds ![image](https://private-user-images.githubusercontent.com/115952096/285552227-d80fea49-4b8a-4fbe-91b9-3496fbce4500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjY5NzEsIm5iZiI6MTcwMDg2NjY3MSwicGF0aCI6Ii8xMTU5NTIwOTYvMjg1NTUyMjI3LWQ4MGZlYTQ5LTRiOGEtNGZiZS05MWI5LTM0OTZmYmNlNDUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNFQyMjU3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2ZiZDYyZWExNmFhYzY4NzcwOWNkOGEzZjI2M2NlM2NhMGRhODlkNWFlZTg0MDg0OWE1YjUwYmY3YmI3MzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HIMoGOU_7vumHSM_QOj9oTR8YTP1nSGMf4lUxPL-lPU) The example code I made would look like this : ![image](https://private-user-images.githubusercontent.com/115952096/285552257-dc53e5d8-3668-4d76-a534-18aa576b9cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjY5NzEsIm5iZiI6MTcwMDg2NjY3MSwicGF0aCI6Ii8xMTU5NTIwOTYvMjg1NTUyMjU3LWRjNTNlNWQ4LTM2NjgtNGQ3Ni1hNTM0LTE4YWE1NzZiOWNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNFQyMjU3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODUwYWMxYTBlMzhmMWYxMjE0M2RkMWNmYTFiNGRhMWYxMzEwMzVlMjJiNTE0YmVkZWE2NGQzOTA1MDBmNzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Ogi7f6W26WipXoQE1cgTuPbHTSwxifFCgMUmtCPmac)

@Callepo  isn't wrong. You are just not using math. 

With the current system, I could have something last 1.5 minutes, and have something last 5 hours.
With your system I could NOT have something last 1.5 minutes, but could have something last 5 hours.

This change is a downgrade to the current system. If you want something to last for 1 hours, set the value to "3600". Wild.

**Comment by AlejandroJB** [comment]
Hey, this would help me for my project. @Callepo In my project I want to create an item that boost the EXP but expire in 30 minutes. How can I do it with the current settings?

PS: Keep in mind this field only accept integer.

**Comment by LordPhrozen** [comment]
> Hey, this would help me for my project. @Callepo In my project I want to create an item that boost the EXP but expire in 30 minutes. How can I do it with the current settings?
> 
> PS: Keep in mind this field only accept integer.

By setting the value to 1,800.

**Comment by Callepo** [comment]
@Niinra so the current expire is in hours and not in seconds? if 1 means only 1 hour, than i can understand it being converted to Seconds, but if 1 == 1 second, than there is literally no point.. 

If 1 == 1 hour than i agree with ur point, but then we shouldnt add a 2nd value or anything, it should just be converted to seconds, and be done with. 

Also without looking into it, my understanding was it would be seconds, like everything else was. 
and i asked whats the reasoning behind ur request. 

But go off young man lol, i called the notion of keep adding a value for everything would be dumb, rather than what ur saying, but you can whatever  u want u know

Also asking cuase i have acces and can make any of these simple changes/ fixes, but wont push changes without fully understanding the idea and reasoning behind it.

but hey, you do you.

**Comment by AlejandroJB** [comment]
> > Hey, this would help me for my project. @Callepo In my project I want to create an item that boost the EXP but expire in 30 minutes. How can I do it with the current settings?
> > PS: Keep in mind this field only accept integer.
> 
> By setting the value to 1,800.

But If I use 1800 the duration is 75 days because is in hours
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/23462563/6c18bc5f-cc00-4d51-8c05-3d03b7785cc6)

**Comment by LordPhrozen** [comment]
> > > Hey, this would help me for my project. @Callepo In my project I want to create an item that boost the EXP but expire in 30 minutes. How can I do it with the current settings?
> > > PS: Keep in mind this field only accept integer.
> > 
> > 
> > By setting the value to 1,800.
> 
> But If I use 1800 the duration is 75 days because is in hours ![image](https://private-user-images.githubusercontent.com/23462563/285552972-6c18bc5f-cc00-4d51-8c05-3d03b7785cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4Njc2NDQsIm5iZiI6MTcwMDg2NzM0NCwicGF0aCI6Ii8yMzQ2MjU2My8yODU1NTI5NzItNmMxOGJjNWYtY2MwMC00ZDUxLThjMDUtM2QwM2I3Nzg1Y2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIzMDkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZWI0ODM3NmYwYmJhMDNkMWNlZWNjZWUwZDc4ZTgxY2RhYjg1OTlmNjk5YjBhY2IyOTE1OGU2OGM4MGY3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtzsXEYVyB0ncxjuAndVCiESg2vjrpe8CzLkVspOCHI)

Yeah I honestly made the same mistake Cal did. But I  think I can see why its set that way. You do not want that logic loop, checking every online players, every item slot, every second.

**Comment by Callepo** [comment]
> > > Hey, this would help me for my project. @Callepo In my project I want to create an item that boost the EXP but expire in 30 minutes. How can I do it with the current settings?
> > > PS: Keep in mind this field only accept integer.
> > 
> > 
> > By setting the value to 1,800.
> 
> But If I use 1800 the duration is 75 days because is in hours ![image](https://private-user-images.githubusercontent.com/23462563/285552972-6c18bc5f-cc00-4d51-8c05-3d03b7785cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4Njc2NDUsIm5iZiI6MTcwMDg2NzM0NSwicGF0aCI6Ii8yMzQ2MjU2My8yODU1NTI5NzItNmMxOGJjNWYtY2MwMC00ZDUxLThjMDUtM2QwM2I3Nzg1Y2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIzMDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYzJkY2RjM2UxZjJhM2ZlZWY2MThjMWU4MzdkNzdiODI2M2Y0MzFkODNhYjFhNjAyYTlkOGI2ZWZlNzAzYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjLIN0GM507unUwfQt_fOQX_M0E0XYHnX-oCsILG0EY)

yea seconds would be much more viable in giving u more options, cuase ud have alot of options, The duration is somethin that was adding very long time ago, so prolly outdated or idk, cuase most other time based values are sec's

**Comment by LPTwenty** [comment]
> @Niinra so the current expire is in hours and not in seconds? if 1 means only 1 hour, than i can understand it being converted to Seconds, but if 1 == 1 second, than there is literally no point..
> 
> If 1 == 1 hour than i agree with ur point, but then we shouldnt add a 2nd value or anything, it should just be converted to seconds, and be done with.
> 
> Also without looking into it, my understanding was it would be seconds, like everything else was. and i asked whats the reasoning behind ur request.
> 
> But go off young man lol, i called the notion of keep adding a value for everything would be dumb, rather than what ur saying, but you can whatever u want u know
> 
> Also asking cuase i have acces and can make any of these simple changes/ fixes, but wont push changes without fully understanding the idea and reasoning behind it.
> 
> but hey, you do you.

I'm reading everything and I see that you were offended by the way the guy responded to you, but first of all you shouldn't call something stupid or meaningless without even knowing how what the guy is telling you works think things through a bit before you respond hostilely

**Comment by Callepo** [comment]
Adding multiple values for same thing is worthless and dumb. 
i stated an example and than called my own example as not being something smart to do.. 

Changing how it works atm that it only accepts hours is not,  so turning hours to seconds, and keeping 1 input value would be ideal.

My point remains.
Take it how u want it 

tired of having to dance around like im talking to lil girls. everyone getting offended by everything..

**Comment by LPTwenty** [comment]
> Agregar múltiples valores para la misma cosa es inútil y tonto. Di un ejemplo y luego llamé a mi propio ejemplo como algo que no era inteligente de hacer.
> 
> Cambiar la forma en que funciona atm para que solo acepte horas no lo es, por lo que lo ideal sería convertir las horas en segundos y mantener 1 valor de entrada.
> 
> Mi punto sigue siendo el mismo. Tómalo como quieras
> 
> Cansado de tener que bailar como si estuviera hablando con chicas pequeñas. todo el mundo se ofende por todo.

You did not even know that the value was handled in hours, for me it has no validity what you tell me, it shows that you talk about what you think you know and do not stop to check if it is true, anyway greetings, accept your mistake and make that change if you have access, it is quite interesting.

**Comment by Niinra** [comment]
> @Niinra so the current expire is in hours and not in seconds? if 1 means only 1 hour, than i can understand it being converted to Seconds, but if 1 == 1 second, than there is literally no point..
> 
> If 1 == 1 hour than i agree with ur point, but then we shouldnt add a 2nd value or anything, it should just be converted to seconds, and be done with.
> 
> Also without looking into it, my understanding was it would be seconds, like everything else was. and i asked whats the reasoning behind ur request.
> 
> But go off young man lol, i called the notion of keep adding a value for everything would be dumb, rather than what ur saying, but you can whatever u want u know
> 
> Also asking cuase i have acces and can make any of these simple changes/ fixes, but wont push changes without fully understanding the idea and reasoning behind it.
> 
> but hey, you do you.

Perfect that we are agree that it is better in seconds, the suggestion about Boolean field was just an example to keep the hour setting for old projects but changing it to accept seconds works fine for me. Thank you.

**Comment by insthync** [comment]
I will add a enum which contains 4 units of time, days, hours, minutes, seconds

Then just add condition for how it will be calculated like this

```
                if (tempItem.ExpireDuration > 0)
                {
switch (tempItem.ExpireDurationUnit) {
case ETimeUnits.Days
                    newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + (tempItem.ExpireDuration * 60 * 60 * 24);
break;
case ETimeUnits.Hours
                    newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + (tempItem.ExpireDuration * 60 * 60);
break;
case ETimeUnits.Minutes
                    newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + (tempItem.ExpireDuration * 60);
break;
case ETimeUnits.Seconds
                    newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + tempItem.ExpireDuration;
break;
                }
```

**Comment by Niinra** [comment]
> I will add a enum which contains 4 units of time, days, hours, minutes, seconds
> 
> Then just add condition for how it will be calculated like this
> 
> ```
>                 if (tempItem.ExpireDuration > 0)
>                 {
> switch (tempItem.ExpireDurationUnit) {
> case ETimeUnits.Days
>                     newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + (tempItem.ExpireDuration * 60 * 60 * 24);
> break;
> case ETimeUnits.Hours
>                     newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + (tempItem.ExpireDuration * 60 * 60);
> break;
> case ETimeUnits.Minutes
>                     newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + (tempItem.ExpireDuration * 60);
> break;
> case ETimeUnits.Seconds
>                     newItem.expireTime = System.DateTimeOffset.UtcNow.ToUnixTimeSeconds() + tempItem.ExpireDuration;
> break;
>                 }
> ```

Thank you very much suriyun for this change :3
