### ISSUE TITLE
[Question] PlayerCharacterBlendshapeComponent ?

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#2319]
Hey Suri! 

Finally got to implementing the character customization stuff I kofi'd you for, and it came out great, ( aside from one issue that Callepo already pointed out)

I did notice a Blend Shape component and just wanted to ask if there was plans to continue working on that piece? Or is there a way to get it to work already and I am misunderstanding it? 

Thanks again, awesome job !  ^_^

**Comment by LordPhrozen** [comment]
Be happy to test it for you, I'm just not sure how the client UI side of things gets hooked up.

I have a couple of test blendshapes set up on my character:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7896457/71a8d274-63e5-4a5a-96fc-03d719f3a324)

But what connects to that component from the UI side?
If its the same UIBodyPartManager I'm not sure what I would enter in these two fields:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7896457/d84a0c79-d021-43be-a28c-245e7783a1ea)

I don't see a corresponding prefab to test against.

I would be very greatful if how to hook that up was added to the documentation when you have a free moment.

Thanks again!!!

**Comment by Callepo** [comment]
maybe the usecase of that is u set the value on the component, and thats what the players get from selecting the option in the game, and not that they can manually slide the values to make their own face, otherwise there wouldnt be an option to have different faces, would just be some sliders in ui and they make their thing.

Atleast thats how im viewing it

**Comment by LordPhrozen** [comment]
the default values on the model's blend shapes for those, isnt zero, so im pretty sure its not setting the zero correctly either 🤔

**Comment by insthync** [comment]
It has no implemented UI components yet

**Comment by insthync** [comment]
Its UI components were added to 1.86
