### ISSUE TITLE
Changing maps or re-logging with summoned character causes character model not to move

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#232]
When you summon a monster and then switch maps or log out and back in, the character will not move. Only the follow camera works. This was tested on a fresh kit install version 1.53.

**Steps to Reproduce:**

1. Summon monster
2. Change maps or relog
3. Try to move

**Expected Behavior:**
Character model should move around as normal.

**Actual Behavior:**
Only follow camera moves.

**Comment by insthync** [comment]
Thank  you for bug report, try this package it may fix your issues. 
[MMORPG-KIT_FixSummonedCharacterDisappears.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4212824/MMORPG-KIT_FixSummonedCharacterDisappears.zip)

**Comment by vaughanb** [comment]
This appears to have fixed the problem. Thank you!
