### ISSUE TITLE
voxel terrain on mmorpg kit

### ISSUE THREAD

**Issue by Yaya2503** [suriyun-production/mmorpg-kit-docs#2321]
Hello
I'm currently using a voxel terrain, I use voxel play 2 to make "minecraft" type terrains, I'd like to know if Mmorpg kit supports this type of terrain, I'd like to be able to place/break blocks on authorized zones but I don't really know how to go about it or even if your assets support voxel terrains, If not, can you tell me if it's possible to integrate it and, above all, how easy/difficult it is? I've only been using unity for over 1 year and, for the moment, I've just been doing tutorials and a few uncomplicated games of my own to practise, so my level on unity isn't really advanced, I wouldn't even say intermediate. How can I integrate a voxel terrain into mmorpg kit?

**Comment by insthync** [comment]
It is just a generated terrain or it is the terrain which can be saved when players make changes?

**Comment by Yaya2503** [comment]
> C’est juste un terrain généré ou c’est le terrain qui peut être sauvegardé lorsque les joueurs font des changements ?

there will be 2 types of terrain, a terrain to which players can add prefabricated objects on a large map such as bridges, cities, etc., and for the cities, once in contact with them they are transported to a terrain (a bit like the old rpg) that they can modify as they see fit by removing or deleting the voxels, so it's a voxel terrain that players can modify and that will save all the modifications made by the players.

**Comment by insthync** [comment]
Hope [this](https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/176-custom-map-system-loading-awaiting-procedural-dungeon-generation) help.
