### ISSUE TITLE
How can I change InterestManager base on some specific map

### ISSUE THREAD

**Issue by desertfoxgame** [suriyun-production/mmorpg-kit-docs#2322]
I'm creating a game that player character gonna have house, which i only want player just see his character only in house. I tried instance dungeon but it's not idealy when player in party.
So anyway that I can change write InterestManager for that and use for some specific map only?

**Comment by insthync** [comment]
Have to change LiteNetLibManager codes structure, I am going to change it too, to implement skill which can make character be able to see hidden characters.

**Comment by desertfoxgame** [comment]
Nice! Will it be available soon?

**Comment by insthync** [comment]
Maybe tomorrow

**Comment by insthync** [comment]
I also added `SubChannelId` to `LiteNetLibIdentity`  component, can set difference channel ID for players in difference houses
