### ISSUE TITLE
[Suggestion] The ability to eliminate the effects of attenuation

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2323]
Hello, there are debuff effects in the game, but there is no ability to delete them before they expire with cure, I think such a skill can be good for priests.

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2273 the same thing?

**Comment by CLAXES** [comment]
Yes, it would be very good for priests if there is a skill to remove debuff effects.

**Comment by CLAXES** [comment]
It would also be nice if there was an option to press buff skills only to people in the same party.

                case SkillBuffType.BuffToNearbyAllies:
                    if (skillUser.GetInfo().PartyId > 0)
                    {
                        tempCharacters = skillUser.FindAliveEntities<BaseCharacterEntity>(buffDistance.GetAmount(skillLevel), true, false, false, overlapMask);
                        foreach (BaseCharacterEntity applyBuffCharacter in tempCharacters)
                        {
                            if (skillUser.GetInfo().PartyId == applyBuffCharacter.GetInfo().PartyId)
                                applyBuffCharacter.ApplyBuff(DataId, BuffType.SkillBuff, skillLevel, instigator, weapon);
                        }
                    }
                    skillUser.ApplyBuff(DataId, BuffType.SkillBuff, skillLevel, instigator, weapon);
                    break;

I have it set this way and I use it but I wish there was an option for it

**Comment by insthync** [comment]
You should create a new post
