### ISSUE TITLE
[Suggestion] Buff abilities only for party members

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2325]
Hello buff abilities would be nice if there was an option only for party members, I use it like the code I gave at the bottom, but it would be nice to have an extra option for it.

            case SkillBuffType.BuffToNearbyAllies:
                if (skillUser.GetInfo().PartyId > 0)
                {
                    tempCharacters = skillUser.FindAliveEntities<BaseCharacterEntity>(buffDistance.GetAmount(skillLevel), true, false, false, overlapMask);
                    foreach (BaseCharacterEntity applyBuffCharacter in tempCharacters)
                    {
                        if (skillUser.GetInfo().PartyId == applyBuffCharacter.GetInfo().PartyId)
                            applyBuffCharacter.ApplyBuff(DataId, BuffType.SkillBuff, skillLevel, instigator, weapon);
                    }
                }
                skillUser.ApplyBuff(DataId, BuffType.SkillBuff, skillLevel, instigator, weapon);
                break;

**Comment by insthync** [comment]
Done
