### ISSUE TITLE
Server achitecture

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2326]
Would this be accurate? just made it, cuase the one in the docs is old.
Planning to update it
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/11020c73-78ad-48a9-9b06-9bf28384f2f5)

**Comment by insthync** [comment]
Cluster client and server are made for server-to-server communication, I think it should be like the second one.

**Comment by Callepo** [comment]
> Cluster client and server are made for server-to-server communication, I think it should be like the second one.

yea i know, i made em visual so people know how the communication works

so on left side u have only clusterclient and clusterserver communicating with eachother 
to visually show that the map is not directly connected to the central, but more of the clusterclient is what sending and receiving data from the Cluster server

And than u have the mapserver and central server communicating with the db server without a medium

Both images represent the same thing, just trying to make people understand that the ClusterClient/Server is also a factor in the communication, cuase that part seems a bit confusing for people, so those 2 options are my attempt to visualize it

**Comment by insthync** [comment]
I don't know what you want me to do. Do you have more question? Are you going to update the image in the document?

I will close this one because I've determined that I have nothing to do any more here.
