### ISSUE TITLE
Inventory slot grid system like metin2 or diablo

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2327]
How can I change inventory slot gird system like metin2 or diablo?.You know each item contains 1 row x 1 column in inventory.I want to change it depends on item 1x1 or 1x2 or 1x3 like that.

![R](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/de0fa152-f159-483a-be6e-80edf05dcfb5)

**Comment by insthync** [comment]
There is no built in grid inventory system implemented

**Comment by temelkirci** [comment]
how can I convert it to like that ?

**Comment by insthync** [comment]
Did you ever try to develop the grid inventory?

**Comment by temelkirci** [comment]
I will try somethings to change it.But I do not have any idea how can I put these items without use grid layout system in UIInventory.
