### ISSUE TITLE
(Help) List of guilds

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#2330]
I'm trying to create a list of created guilds where the player who doesn't have a guild can see existing guilds and request access
With this, the guild leader receives the request and decides whether to accept it or not.

I added the UI Guild List script, prepared the prefab with the buttons by calling the OnClickSendGuildRequest() function, but when I start the server and create some guilds this menu is not populated with the created guilds so that other players can send the request

Maybe I was wrong and this script doesn't work for that

**Comment by insthync** [comment]
The service is not implemented yet :P

**Comment by RafaelRBizachi** [comment]
Ah, I understand, and I saw the same scripts as friendRequest and I thought it was already implemented🥹, thank you for your patience
