### ISSUE TITLE
[BUG] TRADE

### ISSUE THREAD

**Issue by chumleader** [suriyun-production/mmorpg-kit-docs#2332]
**TRADE** is really bugged. we cant reproduce the exact duplication process for item, for gold we had tried and successfully recreated by fully trading the gold 
results will make the user gold to be negative and then the trading partner will get doubled amount. same for item because we made logs and items were doubling

**Comment by insthync** [comment]
How to reproduce?

**Comment by chumleader** [comment]
Trade all the item making the inventory empty
including gold

in gold i just trade all the gold of other player back and forth until i saw the gold became negative. once it shows negative gold the trade will become doubled 
the player which has negative gold cannot trade their gold but the player who received all the gold become doubled. then if i trade all the gold again the other player's gold will become negative then the gold he traded to mine become doubled.

No one reports how they produce it but i made logs on trading items making us confirm that the trade is bugged resulting doubled item and gold

**Comment by insthync** [comment]
Why it is unlike whats you've told me in the chat?

**Comment by insthync** [comment]
Capture video to show how to reproduce it

**Comment by insthync** [comment]
How it can hack gold?, gold amount is being checked by server

![Screenshot_1016](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/c9859b4b-63c3-470b-9b0a-f1925b35d7f5)

**Comment by chumleader** [comment]
the problem is 
when the trade is confirmed
the server doubles everything

**Comment by insthync** [comment]
Video please

**Comment by chumleader** [comment]
i do not have a video now i disabled the trade completely if you think this is a made up issue then leave it as it is .
i explained everything specifically sorry for taking your time.

**Comment by insthync** [comment]
I cannot reproduce whats you've explained, so I ask for it.

**Comment by chumleader** [comment]
ill try to find my video

**Comment by insthync** [comment]
Still cannot reproduce :P

**Comment by insthync** [comment]
Still waiting :)

**Comment by sayonarakit** [comment]
this hopeless

**Comment by insthync** [comment]
Hopeless to what? :p

**Comment by insthync** [comment]
@chumleader Where is it?

**Comment by insthync** [comment]
Time wasting
