### ISSUE TITLE
(Bug) requests to join the guild

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#2335]
I added the UIGuildRequest component to a menu, and added a toggle that when clicked applies UIGuildRequest.SetVisible
After creating the build, and starting the server, when the player opens the guild menu and clicks on the button to open the guild request menu, it displays an error "the service is not available"

**Comment by insthync** [comment]
Not suer that can we called it as a bug, because it is implemented yet, so it is not available as it said.
