### ISSUE TITLE
[bug]Gold drop didn't disappear - infinite loot

### ISSUE THREAD

**Issue by khongtuong** [suriyun-production/mmorpg-kit-docs#2336]
Gold drop didn't disappear after start game about 5 or more minutes, you can loot it infinite, tested in both mmo and single mode

https://github.com/suriyun-production/mmorpg-kit-docs/assets/6816616/a859845c-3c47-4edb-8fff-55d889727ef2

**Comment by insthync** [comment]
How it can be occurred?

**Comment by insthync** [comment]
You should tell me that I have to pickup gold until this is occurring, so I will wait for 10 mins and do pickup test :P

**Comment by khongtuong** [comment]
just playing normal, all gold didn't disappear at all but you still can loot but after 3-5 or more minutes it'll start freeze so player can loot infinite

**Comment by insthync** [comment]
No, as I can reproduce I have to keep pickup until it is occurring, if it is like what you told exactly then it is not the same thing, please make sure about that.

**Comment by khongtuong** [comment]
> No, as I can reproduce I have to keep pickup until it is occurring, if it is like what you told exactly then it is not the same thing, please make sure about that.

yes, keep pickup also has bug

**Comment by khongtuong** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/6816616/e3b4dbe9-d80d-41b9-a7ec-0a25a6ec674a

like this, and this time i test it has bug after 2 minutes playing

**Comment by insthync** [comment]
I cannot reproduce the case that I have to wait a few minutes before start picking up, show me the full video from start.

**Comment by khongtuong** [comment]
here: https://youtu.be/g3zfi7X6MGM

**Comment by insthync** [comment]
Hey, 
1. start the game -> then stay idle for a few minutes -> before starting to pick up an item 
and 
2. start the game -> Start picking up an item 

are different, so in your case is case #2, right?

**Comment by insthync** [comment]
What you've told: "Gold drop didn't disappear after start game about 5 or more minutes, you can loot it infinite, tested in both mmo and single mode" 

Is case 1 isn't it?

**Comment by khongtuong** [comment]
> Hey,
> 
> 1. start the game -> then stay idle for a few minutes -> before starting to pick up an item
>    and
> 2. start the game -> Start picking up an item
> 
> are different, so in your case is case No.2, right

Yes
