### ISSUE TITLE
Two people dying at the same time

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2337]
Hello, I open 2 warriors, sometimes both of them die at the same time, the damage of the first dead person should not be processed, it may be in missile damages, but there should not be such a problem in mele damages.

**Comment by insthync** [comment]
How long is the last hit time difference between 2 characters?

**Comment by CLAXES** [comment]
I don't know exactly, we are trying 2 people, I can shoot video this evening, but sometimes I cut the other guy, he dies, 1 second later I die, sometimes he dies at the same time, maybe the person with a bad connection sends the packets late or something, but I don't know exactly what it is caused by, I will try to shoot a video for you to see.

**Comment by Fnatic91** [comment]
Can happens with monsters too, when the player died and collapsed a "last hit" being made on the monster(but obiviously should not while the player already collapsed lying on the ground so it looks like if a ghost would hit the monster).

**Comment by insthync** [comment]
Try 1.86, if it is still occurring then reopen this.
