### ISSUE TITLE
(Help) Jump animation

### ISSUE THREAD

**Issue by RafaelRBizachi** [suriyun-production/mmorpg-kit-docs#2338]
I changed my character from AnimatorCharacterModel to PlayableCharacterModel using the same animations, but the jump causes a small bug when landing, I tried several things including changing the jumping animations, changing the AvatarMask of the actions, adding pause time when landing, and They have the same defect (they raise their arms when landing), what could it be? I don't know if anyone has had a similar problem

https://github.com/suriyun-production/mmorpg-kit-docs/assets/106054872/2d628da3-ce44-4337-90ff-ae72aee25694

**Comment by insthync** [comment]
Animation Clip's Loop is turned on?

**Comment by RafaelRBizachi** [comment]
My God, that was the problem😅
The landing animation had the loop enabled, and I didn't notice why it didn't occur in the AnimatorCharacterModel
Thank you very much for the tip and sorry to take your time with simple questions
