### ISSUE TITLE
[Question] What takes priority between serverConfig SpawnMaps, GameDatabase MapInfos and Unity BuildSetting Scenes

### ISSUE THREAD

**Issue by shubhank008** [suriyun-production/mmorpg-kit-docs#2339]
Hi Suriyun,

I have many maps made and set in my GameDatabase.MapInfos
![Screenshot 2023-12-16 at 3 47 00 PM](https://github.com/suriyun-production/mmorpg-kit-docs/assets/3790163/34160d24-6e19-4e98-b696-3c341e2a8819)

but I had only a few of them/their scenes added to my build settings scene list
![Screenshot 2023-12-16 at 3 47 54 PM](https://github.com/suriyun-production/mmorpg-kit-docs/assets/3790163/15127dca-526b-4219-b1bb-43cc3eff2e4e)

And I had even lesser maps configured in my server's Config/serverConfig.json file
<img width="643" alt="Screenshot 2023-12-16 at 3 48 35 PM" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/3790163/9b7ef862-076d-42e6-918b-0935054f07b9">

Out of these, which configuration would take priority and would not having all the maps/scenes in my build settings, that I have configured in my GameDatabase cause problem ?
I always thought serverConfig's SpawnMaps take precedence even regardless of Scenes in Build Settings

**Comment by insthync** [comment]
Scenes in builds settings won't be modified by anything, so if you add map info to database, you still have to put the scene into scenes in builds by yourself.

Maps which being spawned by map-spawn server, can be configured in server configs, list of maps which will be spawned will be replaced by config in server configs, server config prioritized like this `Command Line -> Config files -> Component data` [info](https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/031-server-config-files)

List of maps which will be spawn will be set in `MMOServerInstance.cs` (try find `if (ConfigReader.ReadArgs(args, ProcessArguments.ARG_SPAWN_MAPS, out spawnMaps, defaultSpawnMaps)`)

**Comment by shubhank008** [comment]
> Scenes in builds settings won't be modified by anything, so if you add map info to database, you still have to put the scene into scenes in builds by yourself.
> 
> Maps which being spawned by map-spawn server, can be configured in server configs, list of maps which will be spawned will be replaced by config in server configs, server config prioritized like this `Command Line -> Config files -> Component data` [info](https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/031-server-config-files)
> 
> List of maps which will be spawn will be set in `MMOServerInstance.cs` (try find `if (ConfigReader.ReadArgs(args, ProcessArguments.ARG_SPAWN_MAPS, out spawnMaps, defaultSpawnMaps)`)

Got it, but just to reconfirm my exact doubt/question.
Regardless of whatever scenes we have or have not in build settings or GameDatabase.MapInfos, whatever is set in serverConfig will take effect, am I right ?
And only whatever is present in serverConfig.SpawnMaps need to exist in GameDatabase.MapInfos and BuildSettings and not vice versa ?

Just trying to understand for scenarios where we might have 10's of maps in our GameDatabase, but only need to keep whatever we are actively using in Build Settings (Scenes) and in serverConfig (SpawnMaps)

**Comment by insthync** [comment]
If you have 10 map infos in game database, 10 scenes from those map inofos in scenes in build, and you set only 3 maps to spawn then it will spawns only 3 maps.

**Comment by insthync** [comment]
If you have 3 map infos in game database, 3 scenes from those map inofos in scenes in build, and you set 10 maps to spawn then it will spawns 10 map seevers, but 7 of them win't be able to load data and run properly .

**Comment by shubhank008** [comment]
> If you have 10 map infos in game database, 10 scenes from those map infos in scenes in build, and you set only 3 maps to spawn then it will spawns only 3 maps.

Thanks, this is what I wanted to confirm, together with what you said in last comment.
