### ISSUE TITLE
Hide Object

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#234]
Hi, I want to know how can i hide some part of the body when i equipped an armor.
i mean if X armor or helmet was equipped my "hair" can hide.
eso puede ser para diferentes partes del cuerpo

**Comment by Callepo** [comment]
He doesnt speak spanish, but its not yea u can..
Create an empty prefab.. 
put it in the equipmodel with the item u want to hide
and it will hide it on equip.. can be any weapon... here im hiding Hair with a bow
![Capture1](https://user-images.githubusercontent.com/7702658/75304199-08af9800-5843-11ea-8663-950756b79b6e.PNG)
