### ISSUE TITLE
UICharacterSkill bug

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2344]
Hello, version 1.86b does not show features such as uiDamageInflictions, uiAdditionalDamageAmounts.

**Comment by CLAXES** [comment]
if (Skill == null || Skill.TryGetAttackAdditionalDamageAmounts(Character, Level, out Dictionary<DamageElement, MinMaxFloat> additionalDamageAmounts))

works when I do it this way

    !Skill.TryGetAttackAdditionalDamageAmounts

**Comment by insthync** [comment]
Thank you :)
