### ISSUE TITLE
Refine and crafting feature

### ISSUE THREAD

**Issue by br20o0ly** [suriyun-production/mmorpg-kit-docs#2345]
Hi
Can you add new feature
 for refine when you fail you will get an item (e.g.: item that's helps on future enhancement)
 for crafting adding a fail chance and getting deferent multiple items by a chance

i did this changes to my offline/lan version but failed to make it for mmo

**Comment by br20o0ly** [comment]
can you make campfire window works without buildings same like crafting. i failed to make it happen

**Comment by insthync** [comment]
> can you make campfire window works without buildings same like crafting. i failed to make it happen

I don't want to do it.

**Comment by insthync** [comment]
> Hi Can you add new feature for refine when you fail you will get an item (e.g.: item that's helps on future enhancement) for crafting adding a fail chance and getting deferent multiple items by a chance
> 
> i did this changes to my offline/lan version but failed to make it for mmo

Just simply returns items to player or each set of items must have an chance setting?

**Comment by insthync** [comment]
What will happen if your character's inventory is not enough to add returning items?

**Comment by insthync** [comment]
Done

**Comment by CLAXES** [comment]
This feature is very good, but it may be better if something like this is done, instead of adding unlimited, it can add 1 or 5 at most, because it is constantly adding now, it can always make 100%.

**Comment by insthync** [comment]
@CLAXES I don't get it, you means to random items? Or the entries of rewards?, if it entries of rewards then I think it is up to developer to setup it.

**Comment by CLAXES** [comment]
In this section you can select the item and add whatever amount you have on it and you can do it 100%, it would be nicer to have the option to add 1 or 5 instead of adding unlimited

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/84a7fd54-cdab-46f3-a4bf-b74decc62448)

**Comment by CLAXES** [comment]
I want to make an item and only increase the rate by 10%, for example, but when it is in this way, it can put 10 and make 100%, I only want it to increase by 10%.

**Comment by CLAXES** [comment]
I did it this way now, but I don't know how safe it will be

        public void OnClickAddRefineEnhancer()
        {
            List<UICharacterItem> selectedUIs = uiRefineEnhancerItems.CacheSelectionManager.GetSelectedUIs();
            if (selectedUIs.Count == 0)
                return;
            foreach (UICharacterItem selectedUI in selectedUIs)
            {
                if (enhancerDataIds.Contains(selectedUI.CharacterItem.dataId))
                    continue;
                enhancerDataIds.Add(selectedUI.CharacterItem.dataId);
            }
            OnUpdateCharacterItems();
        }

**Comment by insthync** [comment]
Okay, I think you should create a new post because this one is difference thing with this post
