### ISSUE TITLE
Error msg

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2348]
just show an error msg which i saw for the first time

https://gyazo.com/a8f7eabfb1a7a4b26d6b4659cbd06411

updated kit to 186b2. when i loged in i was dead. respawn button not worked. even restart not, new to create new character.
maybe something messed up when updated project?

after creating new char everything was fine. so just i leave it here maybe u can use that info

**Comment by insthync** [comment]
I think you saw your character die because something is breaking the update function loop, so the next update function won't be called. Have to fix that error, then it may fix character dead issues, so don't delete your character for testing purpose.

**Comment by moepi2k** [comment]
as i said this was the first time i saw this  error. was bad decision to delete the char for debuging i know xD
