### ISSUE TITLE
Cash shop issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2349]
The HandleRequestCashPackageBuyValidation 
has a bug i think.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/58592367-311e-4547-a75e-5cd048351ebe)

The isupdatingItems in the other methods when its sending response to client all have it to false..
But this one is being set to true..

and i am checking this becuase when you buy cash ingame, you dont get the cash, and when u try to buy 2nd time, it tells u service not available.. 
Which is literally this 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/46c26cad-4037-4f3f-9b1f-de5ea817bbcb)

**Comment by insthync** [comment]
Fixed

**Comment by Callepo** [comment]
> Fixed

was my change the fix?
tried looking at commits, but dont see it yet in there

**Comment by Callepo** [comment]
@insthync ?

**Comment by insthync** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMO/commit/0e6339710a119432f0b0e686dd88342a2be1e5e6

**Comment by Callepo** [comment]
hmm, even with that change, we still got the error when purchasing
First this one
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/6065f886-5e80-4542-b8eb-e8d4a1047110)

And then it says service not available..
But the thing we trying to purchase is a consumable, not subscription, so we should be able to buy it multiple times

**Comment by insthync** [comment]
Why `service not available` still occuring, is there any error in server log?

**Comment by insthync** [comment]
The already own thing might be a message from Google Play, so I can't know why, maybe you should try ask Google Play

**Comment by Callepo** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/d877e574-814b-4c67-bb82-cc4a4bda0461)
I see this.

**Comment by Callepo** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/b2f7cd24-be49-4f06-9bbb-c69e002aed42)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/40b7b1da-d18d-4bd2-989e-e16a7986144f)

Well i guess ill start here

**Comment by insthync** [comment]
Hmm, seems like I have to change its implementation, a new one will connects to external web-service, which uses https://github.com/voltrue2/in-app-purchase, also plan to store purchasing log to database by the web-service.

**Comment by Callepo** [comment]
> Hmm, seems like I have to change its implementation, a new one will connects to external web-service, which uses https://github.com/voltrue2/in-app-purchase, also plan to store purchasing log to database by the web-service.

that would be great yea.
If it can log product bought with Cash would be cool too, aka when someone uses their cash to buy something in the shop, it records what they bought, so you have prove of them spending the cash.




Im also looking into making a General Logger for the game, like Dealings, Login , log out, location from login etc
But im doing this on my own

**Comment by Callepo** [comment]
@insthync After fixing the IAP Bug server side
This is what we get now.. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/fd7993a9-5626-4461-8895-fb5efa129a2d)

Client sends request to google to purchase cash..
W8's for response.. doesnt get it fast enough and times out.. 
SO when the response do come later on, its not processed, cuase its not listening anymore.. 
SO, server never processes the receipt, and u never get cash ..
then the whole cash shop is bugged, u cant do anything anymore.. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/f4134d38-a4d6-42de-9dcf-23cc9c0a66ca)


It Took 2 minutes for order to be processed.. Client Timed out long ago..
Cuase the Client didnt get the receipt, google refunds all purchases.

And then anything u try to do in the shop you get this..
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/b4e2e824-47da-4055-ad1c-5ecc7e47024c)


Client shouldnt be responsible for processing this.. Server should be or an API..
Cuase it should keep listening for the response.. and not time out cuase it took longet than 10 seconds.. 

And what if my client crashes before i get my receipt? 

The whole process is bad. 
I didnt find a single person who managed to get IAP working properly in the community..
Everyone using their own external API to purchase cash.. and just update the KIT DB cash on the account..

**Comment by insthync** [comment]
How did you fix it? just apply my commit? If yes, then why it will fix issues because the issues are from `DefaultIAPReceiptValidator` which uses Unity's IAP system to validate receipts but it is not working on the current version, so I have to change the receipt validation.

**Comment by Callepo** [comment]
> How did you fix it? just apply my commit? If yes, then why it will fix issues because the issues are from `DefaultIAPReceiptValidator` which uses Unity's IAP system to validate receipts but it is not working on the current version, so I have to change the receipt validation.

I did say it will fix the issue, im saying After applying the Server side Bug fix, its still not working because of others reasons, being the Receipt, i didnt even know the DefaultIAPReceiptValidator wasnt working on current version, i figured that out based on Testing and debugging. 

But we know now its not working cuase im testing it

**Comment by insthync** [comment]
Ahh, I see, so it won't have anything fixed yet.

**Comment by Callepo** [comment]
When u change something to it, let me know pls, so i can test it out. 
 thank you <3

**Comment by Callepo** [comment]
@insthync 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/b33c3185-7179-4403-b9c8-ea6d578559ec)

Move Crash Logs from IAP

**Comment by insthync** [comment]
As I said  issues are from `DefaultIAPReceiptValidator`, that error are from that component, if you want to fix it by yourself just try to validate the receipt, if you can't do it, then just wait for me to do it.

**Comment by shubhank008** [comment]
> @insthync ![image](https://private-user-images.githubusercontent.com/7702658/292689798-b33c3185-7179-4403-b9c8-ea6d578559ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODMyNDAsIm5iZiI6MTcwMzY4Mjk0MCwicGF0aCI6Ii83NzAyNjU4LzI5MjY4OTc5OC1iMzNjMzE4NS03MTc5LTQ0MDMtYjljOC1lYTZkNTc4NTU5ZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMTMxNTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGNjNGFlNTFmMmUyNTU5ZmUyZWNmOTFmMWUxNDE3MGU2OTRjZmM1ZDI2ZjZjOWU1Njc1ZGMzNDhlYzVlNWQ2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.557h5XTDGj28DxJRosGlocKOj5u2AXQTF8MtGjAG2m4)
> 
> More Crash Logs from IAP

The `GooglePlayTangle.Data()` error used to happen if you did not setup/use obfuscated keys for google play store 
https://docs.unity3d.com/Manual/UnityIAPValidatingReceipts.html. 
Although a stupid question, are your google play keys correct setup and obfuscated ?


Also, as Suri mentioned, Unity's IAP is a bit insecure as its client-side validation and they themselves refer/link to https://github.com/voltrue2/in-app-purchase for server side validation (cause they donot provide it). 
But this package hasnt been updated in years and nodejs based.  


It might be worth the effort to create our own server-side validation using direct GooglePlay/Apple APIs.  

@Callepo can you try to run the `unityIAPReceipt` through this `https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/get` manually (browser/reqbin) ? If it works, I can help implement server-side validation using REST API (server->Google/Apple).  
Relevant info I found for above approach. 
https://stackoverflow.com/a/54658639

**Comment by insthync** [comment]
@shubhank008 Seems like Unity's IAP validation won't work on standalone platforms anymore, so `DefaultIAPReceiptValidator` won't work anymore.

So I am just telling you guys to try to create your own validating component by implements `IIAPReceiptValidator` interface, it may connect to the external web-service which may being developed by NodeJS with https://github.com/voltrue2/in-app-purchase for server-side validation, the https://github.com/voltrue2/in-app-purchase still fine.

But if you guys want to implement it by yourself then go ahead it is fine too, Or if you are going to use Google's API for validation by yourself at map-server (like as I did to `DefaultIAPReceiptValidator` but this one is using Unity's IAP and currently not working) then it is okay too, might have to find JWT, base 64 decoding (and so on) libraries to implements it, I have an example to implements it: [here](https://github.com/suriyun-turnbase-rpg/rpg-php-service/blob/master/functions/Billing.php).

What I've planned to do is: I will create a new component which implements `IIAPReceiptValidator` interface, which when it is going to validate, it (map-server) will connect to web-service with receipt/user data to validate, if it is valid then it will store billing history to database and send success message to map-server to increase player's currencies, so I have to develop web-service for the validating too.

But I actually recommend you guys to create your own IAP system including product listing UIs (at client) because the built-in one was planned to make it work for both Offline and MMO games projects and it is hard to update product data, which you have to do it in Unity then build then upload.

**Comment by Callepo** [comment]
Atm i just need the simplest and easiest one that works for now, and than i can take the time to check for any alternatives. 
Just need whats currently in kit to work for now cuase its a bit urgent, all the extra stuff i can do later or w8 how ever long idm.

" Seems like Unity's IAP validation won't work on standalone platforms anymore, so DefaultIAPReceiptValidator won't work anymore."
Also not using standalone platforms, its all Mobile builds

**Comment by Callepo** [comment]
> As I said issues are from `DefaultIAPReceiptValidator`, that error are from that component, if you want to fix it by yourself just try to validate the receipt, if you can't do it, then just wait for me to do it.

i wasn't rushing you, u asked me for logs before, and i found logs so i shared it with you.
Simply did what u asked. :)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/7701b1c6-99ca-44fa-a40f-ac74846588bd)

**Comment by insthync** [comment]
> Atm i just need the simplest and easiest one that works for now, and than i can take the time to check for any alternatives. Just need whats currently in kit to work for now cuase its a bit urgent, all the extra stuff i can do later or w8 how ever long idm.
> 
> " Seems like Unity's IAP validation won't work on standalone platforms anymore, so DefaultIAPReceiptValidator won't work anymore." Also not using standalone platforms, its all Mobile builds

I mean receipt validating by server, server builds are standalone platforms.

**Comment by insthync** [comment]
> > As I said issues are from `DefaultIAPReceiptValidator`, that error are from that component, if you want to fix it by yourself just try to validate the receipt, if you can't do it, then just wait for me to do it.
> 
> i wasn't rushing you, u asked me for logs before, and i found logs so i shared it with you. Simply did what u asked. :)
> 
> ![112](https://private-user-images.githubusercontent.com/7702658/293285326-bbdd381d-6e53-403a-9227-22d7ed75ad9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjI5MTAsIm5iZiI6MTcwMzgyMjYxMCwicGF0aCI6Ii83NzAyNjU4LzI5MzI4NTMyNi1iYmRkMzgxZC02ZTUzLTQwM2EtOTIyNy0yMmQ3ZWQ3NWFkOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDQwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTU3MjFhMDY0ZTRmYzE4ODkyMWM4NTcwZjI4ZDU1NTMyYTczMTgxYTBmZGM5ZjIzZDlhOWZiMDk2NWQzNTU0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lbtZdP_-XZvrvSb3MpiS-oRj_ZmtEMrazyesHaYxq34)

It should not warn service is not available by logs you've shown me, because playerCharacterEntity.IsUpdatingItems should set to false so next request should not warn that message

**Comment by insthync** [comment]
@Callepo Where can I find this history ![](https://private-user-images.githubusercontent.com/7702658/292661729-f4134d38-a4d6-42de-9dcf-23cc9c0a66ca.png)

I can't find it in Google Play Console, and as I try I can't find "you already own this item" problems.

**Comment by insthync** [comment]
![292661729-f4134d38-a4d6-42de-9dcf-23cc9c0a66ca](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/823d36ed-3075-431b-b97b-c5aa2b122e58)

This history

**Comment by insthync** [comment]
The service is done, tested, work as intended

https://github.com/suriyun-mmorpg/mmorpg-kit-iap-validation-service

**Comment by shubhank008** [comment]
> The service is done, tested, work as intended
> 
> https://github.com/suriyun-mmorpg/mmorpg-kit-iap-validation-service

Repo seems private, cannot access it

**Comment by insthync** [comment]
Okay, changed it to be public

**Comment by Callepo** [comment]
> ![292661729-f4134d38-a4d6-42de-9dcf-23cc9c0a66ca](https://private-user-images.githubusercontent.com/2697550/293418803-823d36ed-3075-431b-b97b-c5aa2b122e58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5ODAyMzQsIm5iZiI6MTcwMzk3OTkzNCwicGF0aCI6Ii8yNjk3NTUwLzI5MzQxODgwMy04MjNkMzZlZC0zMDc1LTQzMWItYjk3Yi1jNWFhMmIxMjJlNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMjM0NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q1OTliZTM0NmEzMGQ1MTMwYTFhZThjMGU0NTdkNDc5YzEzMTM0M2JmZGE3ZjZlODFhYjc3Nzc5Zjk3M2JkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EvNf3DUT4HK8Qd_Q6XRMLfI0rdZ2qMShH6yV-Z7RSqc)
> 
> This history

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/6e234026-00f8-4bc8-b1e5-3c9f281b697c)

**Comment by Callepo** [comment]
@insthync is it supposed to add cash to account even when doing sandbox mode for testing? Or only in live mode?
Service is receiving receipt, ingame showing no errors everything fine, Log added to Db but the Status is 0
and Acknowledged is false. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/18672103-3246-4e3e-901c-dd7e6cc0017f)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/44603c43-2a2d-41af-b569-bc06a34a9b21)

**Comment by insthync** [comment]
Should be added while it is in test mode, I did internal test.

**Comment by insthync** [comment]
Status 0 is success.

**Comment by Callepo** [comment]
yea im looking through code now 
saw this
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/5d4e1ffb-55f2-45b6-9c9b-b2a6b2331906)

so figured 0 is good.. 
but no cash added to the player

**Comment by Callepo** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/badcabe1-3754-4a5b-b6f2-60808afa76ef)
Started with this amount, before purchasing. 

it should have added all those amounts, but its stays the same
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/a8b7469e-5ce4-4df2-ae29-05240752554d)

**Comment by Callepo** [comment]
> Should be added while it is in test mode, I did internal test.

We are also doing the same, Internal Testing

**Comment by Callepo** [comment]
> Try latest commit of MMO repo
RESTIAPReceiptValidator Error
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/c50ed460-5ce4-431f-a9b8-649767a9d9e3)


Shouldnt it be 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/3db62c09-a2eb-400b-ac20-c49382fc5a9d)

Like 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/5e287f9d-fff2-4e5a-ae81-55c6ad65f1db)

**Comment by insthync** [comment]
Pushed

**Comment by Callepo** [comment]
@insthync 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/b3537e24-ca47-4ebe-8db4-5bb6586d34d4)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/542c6be0-ce5a-489a-88da-35ddfa0c36d5)

Still same 1300 cash
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/c95045f6-275b-4412-818d-d04e954d80b8)

:(

There is literally 0 errors anywhere.. everything is passing and validating, the last piece just doesnt wanna work lol .. wtf
This look good? 
I have the Cash amount set as 2000 or it needs to be somewhere else? cuase seems like its not getting the amount properly
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/c4fae6ca-1f03-4832-96b5-2be73934eeb8)

**Comment by insthync** [comment]
Try to debug amount of `ChangeCash`

**Comment by Callepo** [comment]
> Try to debug amount of `ChangeCash`

XD 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/28153135-4820-445a-9298-bb07e5beb400)

Literally what i was doing, uploading build etc to try and buy again

**Comment by Callepo** [comment]
nothing showed up in log files or console feel like it should have. i changed debug logs to logger to be sure
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/c49d871f-3d7f-499f-aab6-bdd7025bfa8d)

making new build now and testing again.

**Comment by Callepo** [comment]
@insthync im retarded.. 
i have 2 Server build folders 1 for SEA Region and 1 for EU Region.. i did the changes in the project, made a build in the SEA folder
And kept uploading EU build to the EU server, so none of the changes were added.. I uploaded the correct build now and it works .. FML.. 

Sorry

**Comment by insthync** [comment]
Nice

**Comment by Callepo** [comment]
> Nice

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/98ef15a3-7f8f-42ce-b454-d0f511f6d724)

**Comment by Callepo** [comment]
But yea ur latest commit 100% fixed it. its showing instantly now

**Comment by LordPhrozen** [comment]
Glad to see this fixed :)

**Comment by tubhluas** [comment]
> The service is done, tested, work as intended
> 
> https://github.com/suriyun-mmorpg/mmorpg-kit-iap-validation-service

do i have to use this above package for this fixed to take effect?
