### ISSUE TITLE
1.53 mac / linux issue

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#235]
after build headless try to load windows libs. 

Linux:
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/libadvapi32.dll
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/advapi32.dll
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/libadvapi32
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/libadvapi32.so
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/advapi32
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/libadvapi32.dll
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/libadvapi32.dll.so
Fallback handler could not load library /home/unity/Ao-Server-Linux_Data/Mono/libadvapi32.dll

MAC:
fallback could not load/Contents/Frameworks/MonoEmbedRuntime/osx/libadvapi3

**Comment by insthync** [comment]
I don't know the exact way to fix it, this never happens to me, it seems like it's problem which can occur to other Unity users, not only `MMORPG KIT` users, Not sure did you be able to fix it yet?

**Comment by poaq** [comment]
according to unity forum (https://forum.unity.com/threads/libadvapi32.828759/), its unity bug.
