### ISSUE TITLE
A Simple note of thanks.

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#2351]
@insthync 

**Honestly I just wanted to take the time to say thank you.** You put a tremendous amount of effort into this framework, and it shows. You're doing amazing work. 

However community... frequently I see this area of the git, and it can become hostile, or conflict ridden, as we have different goals with our projects, language gaps, and culture differences. 

**I urge everyone to take a moment, and remember that we're all on the same team with seeing this kit grow.**  

But the holidays are here, and I, from the depths of my PvP-focused heart.... wish everyone a wonderful holiday. So cheers to Suri for wonderful frame work, and thanks for dealing with us. I look forward to seeing where all of this goes. 

**_Thanks for reading, and happy holidays to all of you!_**

**Comment by insthync** [comment]
Thank you
