### ISSUE TITLE
Projectile Dmg Entity

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#2352]
Why did u change the Projectile Dmg Entity ?
It had Prediction steps, angle and Gravity implemented. 
But now its all removed and the same as MissileDmgEntity

Was there a reason for it?? like it didnt work will with the server side hit validation? or something?

(EDIT)
Angle still works and gravity.. Prediction is gone

**Comment by moepi2k** [comment]
still wondering why it changed. i think the impact effect is in wrong pace since prediction step is gone? also wondering why need to change, and if there any plane to fix the hit registration?

**Comment by insthync** [comment]
The predict step is not needed because it is detects hitting raycast/spherecast for hit detection to previous frame? That is why I remove it, is it affect hit detection? When you change it back then problem gone? Did you try to fix it?

**Comment by moepi2k** [comment]
i dont know if it affect hit detection. only thing i notice is that since there was some changes in recent version the impac effect is out of range when use angle. so actually i dont know why it happen now. the damage apply where it impact only the pos of effect is wrong. i try to debug when at home. if i could fix it i would. same for the pooling effect issue which i made a report.
just wondering why you changed projectile because in 185 the hit registration was perfect and now its bad again.

i know there was an issue with missile with speedhack detection, but that wasnt an issue for the projectile one?

**Comment by insthync** [comment]
So the hit registration is bad or just this projectile is bad?

**Comment by moepi2k** [comment]
the hit registration also, thasts why i made this report this week
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2418

**Comment by insthync** [comment]
I am not sure that I can trust you, did you test it all with other kind of damage info? Or did you just test only the projectile?

**Comment by moepi2k** [comment]
atm i tested with projectile. and im sure it was perfect in 185 and after some changes i have bad hit reg, even in offline game.
when at home i will test in fresh kit and make some debug logs.

btw -> just used the projectile script before removing the prediction step -> https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_Core/blob/bea180e34e06a464e62ddcc92a8f2e30a77f6b18/Scripts/Gameplay/DamageEntities/ProjectileDamageEntity.cs

and impact effect is fine again. i will also test hit registration at home

**Comment by insthync** [comment]
Then what is bad hit registration or projectile damage entity?

**Comment by insthync** [comment]
It is not hot because the hit registration or the projectile damage entity?

**Comment by insthync** [comment]
Those are questions that you have to answer me

**Comment by moepi2k** [comment]
I dont understand. The projectiledamageentity is the script of the projectile and yes the projectile entity hit properly. Even on serverview i add debug logs and the projectile hit the hitbox, but the hit applied no damage. Thats all in the report i made this week

**Comment by insthync** [comment]
If it is not hit at the client then it won't have hit data to send to server, then hit validation won't being proceeded.

**Comment by moepi2k** [comment]
Yes thats what im saying, the hit is properly in serverview. But no dmg https://github.com/suriyun-production/mmorpg-kit-docs/issues/2418

**Comment by insthync** [comment]
Don't check the server, just check the Projectile damage entity -> HitDetect() and check the the hit registration message is being sent to server or not.

**Comment by insthync** [comment]
> Yes thats what im saying, the hit is properly in serverview. But no dmg #2418

No, I told you to check at the client
