### ISSUE TITLE
BuffToNearbyPartyMembers Bug

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2354]
Hello here targetEntity.GetInfo().PartyId is added wrongly applyBuffCharacter.GetInfo().PartyId should be

**Comment by insthync** [comment]
How do you think it should be like that?

**Comment by CLAXES** [comment]
targetEntity gets null value, there is an error when trying to find partyID and it does not buff anyone

**Comment by CLAXES** [comment]
it works smoothly when I organise it this way

                case SkillBuffType.BuffToNearbyPartyMembers:
                    if (instigator.PartyId > 0)
                    {
                        tempCharacters = skillUser.FindAliveEntities<BaseCharacterEntity>(buffDistance.GetAmount(skillLevel), true, false, false, overlapMask);
                        foreach (BaseCharacterEntity applyBuffCharacter in tempCharacters)
                        {
                            if (instigator.PartyId != applyBuffCharacter.GetInfo().PartyId) // targetEntity.GetInfo().PartyId)
                                continue;
                            applyBuffCharacter.ApplyBuff(DataId, BuffType.SkillBuff, skillLevel, instigator, weapon);
                        }
                    }

**Comment by insthync** [comment]
Ahh, I see

**Comment by CLAXES** [comment]
I updated 1.86d but this is still the same as before targetEntity.GetInfo().PartyId shouldn't this part change

                case SkillBuffType.BuffToNearbyPartyMembers:
                    if (skillUserInfo.PartyId > 0)
                    {
                        tempCharacters = skillUser.FindAliveEntities<BaseCharacterEntity>(buffDistance.GetAmount(skillLevel), true, false, false, overlapMask);
                        foreach (BaseCharacterEntity applyBuffCharacter in tempCharacters)
                        {
                            if (skillUserInfo.PartyId != targetEntity.GetInfo().PartyId)
                                continue;
                            applyBuffCharacter.ApplyBuff(DataId, BuffType.SkillBuff, skillLevel, skillUserInfo, weapon);
                        }
                    }
                    skillUser.ApplyBuff(DataId, BuffType.SkillBuff, skillLevel, skillUserInfo, weapon);
                    break;

**Comment by insthync** [comment]
Thank you to inform me, just forget to implement it.
