### ISSUE TITLE
Problems with buffs when player is killed

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2358]
As the title says, a problem is occurring with the buffs when the character uses it and is killed during its execution, here is an example video:https://imgur.com/QWm1dwI

**Comment by insthync** [comment]
I can't reproduce it yet, but pretty sure that it is a UI issues.

**Comment by Niinra** [comment]
> I can't reproduce it yet, but pretty sure that it is a UI issues.

Hmm, yeah, I get it, it could be that, but because the buff counter keeps resetting, it's also like having a buff doesn't trigger the death UI and puts your life in the negative even though I don't know. I'm sure

**Comment by insthync** [comment]
What is "I'm sure"?

Share your project to me again, I will check it.

**Comment by Niinra** [comment]
> What is "I'm sure"?
> 
> Share your project to me again, I will check it.

I'm not sure* (sorry translator), I already sent you the project immediately

**Comment by insthync** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2369
