### ISSUE TITLE
HealAera skill problem

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#236]
HealArea cast by player heal also ennemy monsters I think it should only heal the players.

**Comment by insthync** [comment]
I'll fix it.

**Comment by insthync** [comment]
Fixed in 1.53b, if the problem still occurring, you can reopen it.

I also add config to `applyBuffToEveryone` to `AreaBuffEntity`. If this is `TRUE`, buffs will apply to everyone including with an enemies
