### ISSUE TITLE
[Question] Converting int to long (exp)

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2360]
Hello! Ive been trying to rework the exp to convert to long, but I have to change everything on the source and it was working but during an update, id have to do it again. Is there a way to convert it easily without going through all of it, or can it be extended using another script ?

**Comment by insthync** [comment]
No

**Comment by AsheshPlays** [comment]
Ok sir. Thanks for the response.
