### ISSUE TITLE
How to integrate Mobile Controller with mmorpg kit

### ISSUE THREAD

**Issue by john5514** [suriyun-production/mmorpg-kit-docs#2363]
Hi sir

How to integrate Mobile Controller ur asset with mmorpg kit

**Comment by john5514** [comment]
i've read the docs, but it's not clear, or I don't understand, I don't know

i would be very glad if you could help

**Comment by Niinra** [comment]
just search the scene if it's a normal rpg or your mmo, look for the gameinstance , are you looking for the canvasgameplaymobile
example:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/3871a8c2-d3ed-486e-bc41-936f149f0ede)
and you are going to put it in this box in the game instance object
example:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/f69af915-ada7-4a32-a0c1-240a2fbb951c)
and finally activate this box
example:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/c62ad377-db4b-4030-b6d9-d19ca11f5542)
The documentation is very clear so check carefully

**Comment by john5514** [comment]
@Niinra not for this i am saying this asset https://assetstore.unity.com/packages/templates/systems/mobile-controller-system-161533

**Comment by john5514** [comment]
I bought it but I didn't understand anything in docs, there are no pictures, there are two pictures, the others are always text 

I wish integrated docs specific to mmorpg kit were explained
I bought this asset for him

**Comment by john5514** [comment]
The assets are very nice, the support here is also nice, but I think I don't understand this asset

**Comment by john5514** [comment]
@insthync sir can u check

**Comment by insthync** [comment]
Not sure whats you are expecting from that asset package? by comparing it to the built-in one.

**Comment by john5514** [comment]
I would expect something in the docs files, integration with the mmorpg kit because most people who buy it also use your other assets

I've seen a lot of people using it, so I bought it. 

can you please help me how to integrate it

**Comment by Niinra** [comment]
> @Niinra not for this i am saying this asset https://assetstore.unity.com/packages/templates/systems/mobile-controller-system-161533

I think that's on your side. This is for problems related to the mmorpg kit and the one you mention is another asset.

**Comment by john5514** [comment]
> > @Niinrabunun için değil bu varlığı söylüyorum https://assetstore.unity.com/packages/templates/systems/mobile-controller-system-161533
> 
> Bence bu senin tarafında. Bu mmorpg kitiyle ilgili sorunlar içindir ve bahsettiğiniz şey başka bir varlıktır.
is the presence of the same creator? 

How can I get support about this being? Should I pray?

what I want is already related to this issue with the mmorpg kit.

**Comment by insthync** [comment]
That one is actually not made by me, and I haven't tried it yet, and the built-in one covers all people need for the game, it has many different of events set up, so if you gonna use it, you will have to modifies a lots of player character controller codes.

**Comment by john5514** [comment]
How long does it take to replace just the joystick?

Would it be easier, sir?

**Comment by insthync** [comment]
What would be easier?

**Comment by john5514** [comment]
just change the controller on the mobile side


The joystick found in the standard has too much deadzone and is not smooth


would it be easier to replace it with the joystick that is in the other asset I bought?

**Comment by insthync** [comment]
Easier to use?

**Comment by insthync** [comment]
What is not smooth ? the built-in mobile controller?

**Comment by john5514** [comment]
> Easier to use?

https://assetstore.unity.com/packages/templates/systems/mobile-controller-system-161533 yes 

the one in this pack offers more comfortable use 


but the one in the mmorpg kit is not very smooth

I want to change it too

**Comment by john5514** [comment]
> What is not smooth ? the built-in mobile controller?

mmorpg kit in mobile controller yes.

**Comment by insthync** [comment]
How is it more comfortable?

If it is not smooth, then you should tell me to improve it.

And as I said you will have to change events handling in the player character controller.

**Comment by john5514** [comment]
> Nasıl daha rahat?
> 
> Eğer düzgün değilse, bana onu geliştirmemi söylemelisin.
> 
> Ve söylediğim gibi, oyuncu karakter denetleyicisindeki olayların işlenmesini değiştirmeniz gerekecek.

Basically, there is no correct detection in many screen types, yes, if you look at the main screen you give, it scales it up and applies it according to the screen, but this time


the joystick doesn't work properly, I guess it's not the same on every screen, it causes problems on mobile phones, sometimes it doesn't recognize when you press it.

I think it's because of the screen proportions.
I tried it on different phones and it works fine on some and not smooth on others. Think of it like a pubg mobile joystick, it should work correctly every time you press it. I don't know if it can be from the axes in mobile input as standard.


For example, when I first installed it, running used to work on the joystick, when I moved it forward, it doesn't work now, if I say it's broken, I open the old project and it goes after a while, I don't understand, I tried to add the run button, I press the button and nothing happens.


running was working without a button before, I give an example

I've seen people using the same asset you did and using mobile controls in this way so I actually bought the package 

https://www.youtube.com/watch?v=yH_HKKotuTk

**Comment by insthync** [comment]
You might try to ask those people, I don't want to integrate yet, I want to improve whats I did.

**Comment by insthync** [comment]
And how the running is not working ?

**Comment by john5514** [comment]
> Peki koşu nasıl çalışmıyor?

I don't know

normally, when the joystick goes up, it should run, but for some reason it turned off long ago, and now we can't run
