### ISSUE TITLE
black screen on build single player

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2365]
I updated my project to version 1.86d, but when building the game in single player mode, and when running the game it appears on a black screen

https://gyazo.com/678afec1713b49777f59b396ac9f7d9a

after the logos, there is just a black screen

https://prnt.sc/8jUQI5vqyiaC

**Comment by Niinra** [comment]
I don't understand, I see that you are compiling the server. You said that only the information would be compiled for servers, right? Another thing I see in your build settings is that you don't have the scene only for clients.

**Comment by juniormagalhaes** [comment]
the build is single player, not mmo

**Comment by Niinra** [comment]
> La construcción es para un solo jugador, no MMO

I was looking around and that looks like a Unity package, did you check that your version of Unity is okay? , try reinstalling another version , I updated too and everything is normal

**Comment by juniormagalhaes** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/d8e729fe-6b2d-4993-9c06-a561c4884915)
i use this version

**Comment by Niinra** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/adfeee5a-7afc-43be-aedd-991250ad53fe)
We use the same one so I tell you, I think it's something up to for you unity

**Comment by juniormagalhaes** [comment]
I have no idea what it is, I updated the way I always update

**Comment by Niinra** [comment]
How do you update the asset? , I generally delete the entire folder from it and import it again

**Comment by juniormagalhaes** [comment]
I create another clean project, import the updated asset, copy the folder, and then delete the asset folder in my project, and paste the updated kit folder in its place

**Comment by Niinra** [comment]
> I create another clean project, import the updated asset, copy the folder, and then delete the asset folder in my project, and paste the updated kit folder in its place

Yes, try that if not, try downloading another version of Unity

**Comment by insthync** [comment]
How about this 

![Screenshot_1038](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/da788880-22a5-4e90-94ec-102a89ac1d32)

**Comment by insthync** [comment]
No error messages?

**Comment by moepi2k** [comment]
btw (not related to ur issue) but unity 2022.3.8 till around 2022.3.11 or 12 is a big memory leak. so i recommend use 2022.3.16

**Comment by insthync** [comment]
Can you solve this?

**Comment by juniormagalhaes** [comment]
> Can you solve this?

no

**Comment by insthync** [comment]
I might have to try by remoting to your PC again.

**Comment by juniormagalhaes** [comment]
I think there was a missing item in the database
