### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2366]
I updated my project to version 1.86d, when running the game within unity, it keeps giving this error

https://prnt.sc/ij5pfy__8n8N

**Comment by insthync** [comment]
Please show all messages including with info and warning, it will tells where it is requesting

**Comment by juniormagalhaes** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/9b5d8629-256d-4b4b-bd52-4683cb004371)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/ac918a96-d301-4831-b861-1746a9f15b78)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/c2392acf-6500-440d-95d6-0e18f34e417b)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/2ba7c1ec-491d-478a-8299-57db3308ad66)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/59762351-4fc7-447c-8336-651794fe6f36)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/ca18fefb-e021-49eb-855c-964c435d060d)

**Comment by insthync** [comment]
These log messages are not relates to rest client, are there any other messages?

**Comment by juniormagalhaes** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/b96d7c2b-2d14-4c4d-971c-ad4a9df4ac4d)

**Comment by juniormagalhaes** [comment]
This is another error, I realized now while taking off the prinsts, when I attack the monster he doesn't come after me.

https://gyazo.com/e7c0426e362ec601214679af4b8afc81

**Comment by insthync** [comment]
Are there any log which telling which URL it is connecting?

**Comment by insthync** [comment]
Can we just gradually talks about each problems in one post, so it will lesser confusing

**Comment by juniormagalhaes** [comment]
> Are there any log which telling which URL it is connecting?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/dc2acdb6-94fc-4155-af82-01b48d274c40)
this maybe?

**Comment by juniormagalhaes** [comment]
> Seems like it is a guild war service, are you intended to use it?

I don't think I'll need to use it anymore

**Comment by juniormagalhaes** [comment]
> Seems like it is a guild war service, are you intended to use it?

I disabled it, the get error stopped

**Comment by juniormagalhaes** [comment]
but the error of monsters not coming to attack me still continues.

**Comment by insthync** [comment]
Only that character?

**Comment by juniormagalhaes** [comment]
> Only that character?

all monsters

**Comment by insthync** [comment]
May I check

**Comment by juniormagalhaes** [comment]
> May I try yours?

yep, your need remote access?

**Comment by insthync** [comment]
Yes

**Comment by juniormagalhaes** [comment]
anydesk or teamviewer? Send me your email so I can send you the credentials

**Comment by insthync** [comment]
AnyDesk, I remember I sent you my email many times: ittipon.bay@gmail.com

**Comment by juniormagalhaes** [comment]
sent

**Comment by insthync** [comment]
Fixed by change from [SetDestination](https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.SetDestination.html) to use [SetPath](https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.SetPath.html)

Might be Unity's bug
