### ISSUE TITLE
Item drop Entity Bug

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2367]
When placing an Item drop Entity directly in the scene, you collect the item but it does not go to the inventory nor does the message appear.

when you use Spawn Area it works correctly.

https://gyazo.com/e4c4d4b6363e7b94d0dfb2d75ab44a85

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/feed7834-95b6-4cd7-956e-33eb0c710daf)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/0d45e342-801d-4ae7-946a-3fd990e27fed)

**Comment by insthync** [comment]
Did you re-generate its scene ID?

**Comment by juniormagalhaes** [comment]
> Did you re-generate its scene ID?

no, this is a clean project that I imported the kit

**Comment by insthync** [comment]
So you didn't, aren't you?

**Comment by juniormagalhaes** [comment]
> So you didn't, aren't you?

no, In fact I'm not even sure I know how to re-generate scene ID

**Comment by insthync** [comment]
Fixed, but you will have to re-generate scene ID

![Screenshot_1039](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/24f302c7-913f-4504-9a3c-f31474a30b29)
