### ISSUE TITLE
UICharacterBuffs bug

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2369]
UIPartyMember-Tiny prefab in the buffs I add to show the buffs in the prefab, it works properly at first, it shows it, it deletes it when it is finished, but after a while it enters the bug, buffs debuffs do not appear.

Could there be a problem with UISocialCharacter.cs
I think there's a bug when the guy in the party dies.

**Comment by CLAXES** [comment]
I think the following code place in the protected override void UpdateUI() in UISocialCharacter.cs takes the data only once and does not update the buffs later if it leaves the line of sight

                if (dirtyCharacterId != Data.id)
                {
                    dirtyCharacterId = Data.id;
                    GameInstance.ClientCharacterHandlers.TryGetSubscribedPlayerCharacterById(Data.id, out characterEntity);
                }

**Comment by insthync** [comment]
Fixed
