### ISSUE TITLE
Problems when attacking monsters

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#237]
When starting to attack a monster with melee attacks, player starts to attack correctly, but after it, trying to enter a the center of the monster. This is most noticeable when using large monstrers.
![Sans titre-1](https://user-images.githubusercontent.com/19147694/74924717-3627bc00-53d3-11ea-9a0c-555fcf6c3f2f.png)

**Comment by insthync** [comment]
Fixed in 1.53b, if the problem still occurring, you can reopen it.
