### ISSUE TITLE
(Paid Request)  Ragdoll System

### ISSUE THREAD

**Issue by AlcidesJunior123** [suriyun-production/mmorpg-kit-docs#2370]
Hi, I wanted to request the implementation of a ragdoll system, it doesn't need to be something sophisticated but just something that the character receives some damage from falls to the ground and gets up.
 I thought the ragdoll could happen in a specific chance when the attack speed surpasses the opponent's or every time a critical hit occurs or also when receiving damage from skills. There could be an option so we can set the ragdoll chance.
 Something like that :

https://youtu.be/IsKkD7yZaAs

**Comment by insthync** [comment]
It is knock back

**Comment by AlcidesJunior123** [comment]
Yes, it's true, I didn't stop to think about what it's called, I actually know it as ragdoll. But then that's the request, the knock back. Thanks.

**Comment by hiraku1994** [comment]
It would be really cool, it would make combat more dynamic, a combo system would also be cool. :)

**Comment by AlcidesJunior123** [comment]
Of course, I personally believe that this would make an excellent upgrade to the kit's battle system. Another thing to also think about is a flight controller for the mounts. It doesn't need to be anything very sophisticated either, just something that controls the ascent and descent during flight and something for the flight and landing transition, perhaps with a landing animation.

**Comment by khongtuong** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/6816616/be1f3c55-6c76-429e-9977-0fa8c1e68635)
can be resolve solution?

**Comment by AlcidesJunior123** [comment]
Yes, it is one of the possibilities, but I still believe that it is very limited to receiving a critical hit. I'm not a programmer, but I believe that to make the conditions I presented before sound more natural, the attack speed and taking damage from skills would still be missing.

**Comment by hiraku1994** [comment]
the configuration would be in the skill effect or basic attack, you could choose the percentage of chance of knocking down

**Comment by insthync** [comment]
The same with this?
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1925

The force functionality is almost done, have to implements it for 2D and NavMeshEntityMovement,

How much can you guys pay for this request?

**Comment by AlcidesJunior123** [comment]
Hi Suri, sorry for the delay in responding. It's actually not quite what I expected. I really need something that has a fee to happen without it having to be a skill. Since Knock down occurs during combat, I didn't want to have to configure this as an ability but rather as a part of the Default animations. I'm even trying to implement some things regarding custom animations, trying to do something so that when the knock down occurs, it calls a custom animation. We are still developing some things. I saw that there is already a call here for custom animations and I will also wait. At the moment the current form is not usual for me. If you can, please look into the possibility of including knock down as part of the default animations. Simply run an animation and set a rate chance of it occurring within the weapon entity. 
I'm not trying to be rude, but I've been avoiding as much as possible from the moment I opened this topic commenting or requesting something here since I saw the methods that others treat in their requests. Thank you in advance for your goodwill and excellent work.

**Comment by insthync** [comment]
How is it not what you want?, at least it can applies force for knock back, it is a part of that, isn't it?
It just remains custom animations when it is knocking back, isn't it?

As for the current state, I have just a question, how much you guys can pay for it?
If it is too low then I won't continue, that is it.

All hard tasks are done. Add new character stats and playing animation are simpler tasks.

Just the force applying, it takes around 20 hrs to complete, if I charge it 15 USD / Hrs, then 20 * 15 = 300 USD, so at least you should pay me 300 USD

**Comment by insthync** [comment]
Hmm, seems like you are not gonna pay for it, maybe you can't because of its price, so I will not develop it.
