### ISSUE TITLE
How do I Join party?

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2371]
I have successfully made the client and server

When I connect two clients, and to trade or join party, i cant find the option for the life of me.

I can create a party, but how do I invite someone? 

thanks!

**Comment by insthync** [comment]
Walk to the character and press E

**Comment by anthonyselias** [comment]
> Walk to the character and press E

I've tried doing this several times and it does not work

**Comment by insthync** [comment]
Try to this 
![Screenshot_1044](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/0890ef46-9f39-4890-8687-7fe422536264)

**Comment by anthonyselias** [comment]
Thank you!
