### ISSUE TITLE
How do I enable server console?

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2372]
When I run the server and client I am able to connect just fine.

But the console does not have any details like it shows in the docs, how do i fix this??

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/3c8f8ac2-9449-4cda-bc33-26441ec5e388)

**Comment by insthync** [comment]
Build as development build

**Comment by anthonyselias** [comment]
Thank you!
