### ISSUE TITLE
Successfully compiling with console errors

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2373]
I'm having no problems compiling the project, but I do have some errors in the console.

I'm wondering, are any of these errors normal? Are they of any concern? Are there any problems that I need to address?

thanks!

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/4e794eb2-7e54-4449-b28e-0d89f7c72f44)

**Comment by insthync** [comment]
Not sure those showing up when it is compiled while playing?

**Comment by insthync** [comment]
Please select one of them to show full error log messages

**Comment by anthonyselias** [comment]
Thank you for answering. I ended up remaking the project, i probably needed to do that because i was learning at the beginning. thank you for trying to help me! I'm currently working on adding grid tile walking/pathing
