### ISSUE TITLE
Tile  Movement in 2D Gameplay

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2374]
Is there an option to set movement to Tile Grid movement? Instead of being able to walk anywhere, to only be able to walk 1 tile at a time?

**Comment by insthync** [comment]
You have to use this addons: https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_2DAI

**Comment by anthonyselias** [comment]
I'm working on it now, but im having difficulty understanding this

" Attach A Star Character Movement 2D to your character entity
Attach AI Lerp or AI Path component "

Where is my chracter entity located for me to attach them? thank you

**Comment by anthonyselias** [comment]
Is this the character entity i need to attach them to? 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/72ecabfd-b360-44e5-abc2-d89f18c89373)

**Comment by insthync** [comment]
Attach `A Star Character Movement 2D` (replace `RigidBodyEntityMovement2D`) to the prefab of your character.

**Comment by anthonyselias** [comment]
So, find for example, the warrior prefab, remove rigidbody, add A Star character movement, and ai LERP. then go to my map , and add the pathfinder component, ami getting it correcT? Sorry, I know some Python,  never used unity, but im trying to get the hang of it. I have been reading alot of guides, been spending many hours and kinda got the grasp here and there.

If, by any chance, you could make a super quick video or something, I would definately get you some KOFI! 👯‍♂️

**Comment by Niinra** [comment]
> A Star Character Movement 2D



> So, find for example, the warrior prefab, remove rigidbody, add A Star character movement, and ai LERP. then go to my map , and add the pathfinder component, ami getting it correcT? Sorry, I know some Python, never used unity, but im trying to get the hang of it. I have been reading alot of guides, been spending many hours and kinda got the grasp here and there.
> 
> If, by any chance, you could make a super quick video or something, I would definately get you some KOFI! 👯‍♂️

What Suriyun told you to do is remove this script, which is what controls the character's movement, and add A Star Character Movement 2D example:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/d5bacfec-f9e2-4124-a925-04125aa41b12)

note: remember this in the prefab you use as a character
