### ISSUE TITLE
New character spawn problem

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2375]
I have recently added the grid pathfinder to my project. But, whenever I make a new character, I see the user interface but the map is black, but when i move it goes back to normal, any clue on what it might be? Also, when i log back in with the character it loads up as normal.

So basically, I'm having a new issue of when i create a new character, it's pitch black until i move then it works.

**Comment by Niinra** [comment]
send a video to see what happens

**Comment by anthonyselias** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/9c841372-9cd0-41f2-a4c3-d9d4426292eb

there ya go

**Comment by Niinra** [comment]
Did you buy in the scene if there is something that initially makes black on the camera or something that is instantiated? If you have not checked, check the scene to check if it is not a problem with the camera, And did you follow all the steps in Suriyun's documentation for that plugin?

**Comment by anthonyselias** [comment]
Yeah, im not sure why it's doing this. There isn't much in my map scene either, so i've been going back and forth compiling, checking, etc. its driving me crtazy

**Comment by anthonyselias** [comment]
Also doing the same with characters in the demo repo,
