### ISSUE TITLE
Chat text above head stopped working

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2376]
Chat text above head stopped working

How do I fix this?

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/36e4ee1e-2209-4642-a50f-3e6acf9f7cbd

**Comment by insthync** [comment]
Not enough info, Is it disappearing just in this scene or always disappearing? It might be just a layer issues

**Comment by insthync** [comment]
Try this

![Screenshot_1050](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/8cd30142-e7a0-4958-89f5-f3403c8b7eb6)

**Comment by anthonyselias** [comment]
I do not have that option 

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/542d9857-2ed7-4ddb-bda8-6be9f8f035e3

**Comment by insthync** [comment]
Don't you see the `Add Sorting Layer...` menu?

Try it!

You will have to learn many things by yourself if you gonna makes games, if just this layer adding can be an issue, I think you can't finish your games.

**Comment by anthonyselias** [comment]
I understand the concept of layers and I ended up making a new one assigned to chat and it didn't work

**Comment by Niinra** [comment]
> I understand the concept of layers and I ended up making a new one assigned to chat and it didn't work

Send more photos of how you have it, I just recreated the same thing and it works, you marked the layers for the prefabs, right?
