### ISSUE TITLE
Adding a mark on clicked tile

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2377]
I'm using AI lerp for grid tile walking. How can I make it so when I click on a tile, it draws a temporary square on if? I got a example video of another game that has it to see what I'm talking about 
https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/ba439117-8f26-4d68-9952-6fdaabe507d2

**Comment by anthonyselias** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/589305b5-5971-41b1-9f3d-9f9ebbfa0d3b

**Comment by insthync** [comment]
Might be an layer issues, again, just try to change the layer.

**Comment by insthync** [comment]
Why it is not, I think you meant to this, notice the circle when I click on the ground, it is already in the demo

https://youtu.be/Un7Ty9OssL8

**Comment by anthonyselias** [comment]
The circle does appear that is correct. I was asking, how can I have the tile that I'm clicking on marked with a outer layer shade. Similar to the video I sent you. When I click on the tile, it marks the tile that I'm headed to. 

Which file/script handles the circle that it currently has? I might be able to modify it myself to highlight the grid node it's going to unless you are able to help me with that. 

Thank you.

**Comment by Niinra** [comment]
> The circle does appear that is correct. I was asking, how can I have the tile that I'm clicking on marked with a outer layer shade. Similar to the video I sent you. When I click on the tile, it marks the tile that I'm headed to.
> 
> Which file/script handles the circle that it currently has? I might be able to modify it myself to highlight the grid node it's going to unless you are able to help me with that.
> 
> Thank you.

First I would start by changing the shape of the floor of the map with mosaics, then adjusting the target in the prefab of the character controller, changing it to a grid and that's it, you should look better at the asset documentation to orient yourself better, example:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/0c70b871-285a-4cf2-8ab7-b501f60c3d8b)

**Comment by anthonyselias** [comment]
Do you have any instant messaging service where we can communicate better?

**Comment by Niinra** [comment]
> Do you have any instant messaging service where we can communicate better?

is that my id to discord:546846760426012693

**Comment by anthonyselias** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/0723ff4f-bb49-4c29-9b0d-9cba23f5de2c)


never seen an id like that? usually its username#number

**Comment by anthonyselias** [comment]
I think I found you, i sent a friend request 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/25f8c321-f1d7-4433-8501-9ac7a9df8be2)
