### ISSUE TITLE
[Bug]Mobile npc dialog

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#2379]
In the latest versions, NPC dialog does not show in Android build.
pc working.

**Comment by insthync** [comment]
![Screenshot_2024-01-19-23-12-40-322_com suriyun unitymultiplayerarpg](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/31660796-763b-4457-adf9-6fb085dabf3e)

Mine showing, Do you have more info?

**Comment by fedas61** [comment]
its works thank you
