### ISSUE TITLE
Inventory Slots

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#238]
When u Equip and item or Drop or sell etc, The slot where the item was gets destroyed... And all ur inventory slots move up by 1.. and a new slot is made at the end when ur using Limitslot..

Ive changed it so that the Slots never dissapear.. they just gets replaced by a Empty slot...
This only works on Limitslot.. cause i put a check there..
With this players can Arrange their inventory in a way and never have it change by itself again..
its a simple code change in a few places...

This line of code is in a few places.. Like EquipWeapon and Equiparmor and Dropitem or Sell Item
![Capture](https://user-images.githubusercontent.com/7702658/75071386-8d25b200-54f5-11ea-8b81-9f7db9bcc936.PNG)

I changed it to 
![Capture1](https://user-images.githubusercontent.com/7702658/75071490-bd6d5080-54f5-11ea-926e-ad919727698a.PNG)

It checks if ur using Limitslot inventory and swaps the slot with an Characteritem.empty
on Simple inventory .. it still deletes the slot.

Im sure u already know how to do this.. and the places to edit
but most of them are in BaseCharacterEntity_NetworkResponse.cs
Line 167, 204
CharacterDataExtension.cs
line 959

And thank you.

**Comment by insthync** [comment]
Thank you :)

**Comment by Callepo** [comment]
will this be included next version ?

**Comment by insthync** [comment]
Yes

**Comment by Callepo** [comment]
ty <3

**Comment by insthync** [comment]
I've implemented this in 1.53b including when drop item from inventory, use the item until it empty, refine item until it destroyed, sell an item, dismantle item, use ammo until it empty and so on.
