### ISSUE TITLE
player spawn

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2381]
Where is the player spawn setting? I want to try to delay the player's spawn a little, due to an optimization asset in World Streamer 2, which delays the instantiation of the terrain a little, and the player always ends up falling

**Comment by insthync** [comment]
Don't have it.

**Comment by insthync** [comment]
You may try delaying it before spawning an entities at first time when scene is loaded by create a class based on `BaseGameNetworkManagerComponent` like this

```
public class WaitSceneLoadComp : BaseGameNetworkManagerComponent {
  public override bool UpdateReadyToInstantiateObjectsStates(BaseGameNetworkManager networkManager, Dictionary<string, bool> readyToInstantiateObjectsStates) {
    readyToInstantiateObjectsStates["ANY_WAITING_KEY"] = true; // Set new key with TRUE/FALSE value (TRUE when data loaded)
  }
}
```

**Comment by juniormagalhaes** [comment]
thanks
