### ISSUE TITLE
[Bug] Enemies in 2d MMO 'shake' at end of movement.

### ISSUE THREAD

**Issue by wtfcolt** [suriyun-production/mmorpg-kit-docs#2383]
When the 2d mode is using mmo, the enemies will shake at the end of their movement a lot of the time.  User Riryan in the discord has reason to believe it may be something to do with 8 direction animations when only having 4 assigned on your enemy. I've seen this shake on the player characters as well sometimes, but it's much more rare to see.

This does not appear to happen in singleplayer/lan mode, only MMO.

Video on the discord here: https://discord.com/channels/460801727789137920/672178123579719740/1184289826955075666

**Comment by insthync** [comment]
Is this the same with [this](https://github.com/suriyun-production/mmorpg-kit-docs/issues/2390) ?

**Comment by insthync** [comment]
Seems like it was fixed, if you still having this issues, you can reopen this.
