### ISSUE TITLE
[Bug?] Building Repair system by menu / "_repairDataForMenu.HasValue" always false

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#2384]
Hello, I'm now trying the building repair system with 1.86d fresh kit.
However when I tried it, "_repairDataForMenu" variable always empty so "_repairDataForMenu.HasValue" returns false everywhere in the code so repair button in "UICurrentBuilding" is not shown and cannot repair

I asked this to discord but nobody answered me...
Can you check this?

**Comment by insthync** [comment]
Did you turn `canRepairFromMenu` on?

**Comment by dglee2592** [comment]
Yes sure. I did double check

**Comment by insthync** [comment]
Try replace the function in building entity 

```
        public bool CanRepairByMenu()
        {
            if (CacheRepairs.Count <= 0)
                return false;
            return _repairDataForMenu.HasValue;
        }
```
