### ISSUE TITLE
[Bug]Server Auth and Swimming

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2385]
there is an issue when use serverauth and are in water

https://gyazo.com/5b218632c6c87dba6429b145482b290a

in default demo set moveSpeedRateWhileSwimming to e.g 0.1 so u can notice it better.
in serview the movespeed is correct. but client not

**Comment by insthync** [comment]
I will fix it

**Comment by insthync** [comment]
fixed

**Comment by moepi2k** [comment]
i tested the commit, but its not working. the problem now is. when player is in water but idle. it has the no grounded state and it plays the fall animation

**Comment by insthync** [comment]
If it is a difference issues, please create a new post

**Comment by insthync** [comment]
Problem in this post is movement speed, if its animation is not correct then create a new post about it.

**Comment by moepi2k** [comment]
Yea its diffrent issue, but issue occure with that change. Just wanted to let u know, since that wadnt a bug before. will make new report :)
