### ISSUE TITLE
When the buff is applied, the enchantment item window automatically closes.

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#2386]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/58978516/aff3ece6-423c-470b-8e45-6998cd0c5a69

The same phenomenon occurs when removing an enchantment function item 
from the item refining window.

unity version : 2022.3.10f1

[MMORPG KIT] Version: 1.86d

**Comment by insthync** [comment]
![Screenshot_1056](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/6fcf64fe-e407-4144-a407-b8d34ce551c8)

Fixed
