### ISSUE TITLE
Enemy not facing the right direction.

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2387]
I am using 2DAI with AILerp. When I attack enemies, they do not face the correct directions.  Instead of facing my direction they face a random different direction. 
How can I fix this?

Also, if I do not cause damage to enemy in the first hits, the enemy won't attack. Enemy only attacks if I do the first hit with the attack setting at non aggressive.

**Comment by insthync** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_2DAI/commit/8ffcda570d48628fd74ef5f14903237e3674cb8a

**Comment by anthonyselias** [comment]
> [suriyun-mmorpg/UnityMultiplayerARPG_2DAI@8ffcda5](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_2DAI/commit/8ffcda570d48628fd74ef5f14903237e3674cb8a)

Thank you bro!
