### ISSUE TITLE
Questions about Hero Editor

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2388]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_HeroEditor4D

I'm thinking of getting the hero editor. Can you confirm if it works with the latest mmorpgkit?

Does this allow you to customize character at character selection screen? I tried YouTube, and looking through old GitHub questions, couldn't find a clear answer. 

Thank you!

**Comment by anthonyselias** [comment]
Can anyone confirm?

**Comment by insthync** [comment]
Always have to be me to answer this? :P

It works with the latest MMORPG KIT, but it doesn't have character customizing in the demo, I think it can, just needs some setup.

I am really tired, I developed an add-on and made it open-source, everyone can use it for free, and I have to answer all usage questions, I think I should take it down, and stop its publishing, it sounds better :D

**Comment by anthonyselias** [comment]
You are the only one that can answer these questions. And it is your responsibility since we pay you for your great kit you made, the only thing we ask is for some support or help at whatever extent you choose. 

It's great that you have the add one, because it gives people great incentive to buy the kit. I think you can get very sarcastic and not so charismatic in a lot of your responses, no offense. 

I was asking if it still works, because it costs $50 and that's a lot of money so I was making sure that it still works correctly, I don't think it's a bad question. 

I appreciate your support, and I think you could use a little patience. Thank you.

**Comment by insthync** [comment]
If it does not work then it will have someone tell me to update it, so it will always work after I make an update

**Comment by anthonyselias** [comment]
Thank you for the reassurance, I appreciate it.
