### ISSUE TITLE
Skills Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#239]
skills dont work.. Like example Bash..
if u use Bash ingame.. the character will just walk to enemy and use auto attack.. the skill is never used..
never  goes on cooldown and dont use no mana.. its just an auto attack
leveled bash to lvl 4 to test and still same mana comsuption changed to 10.. Cooldown timer changed to 40.. Nothing.. Just auto attacking 
Same with Firebolt and fireArrow etc

but FireboltScroll does work

**Comment by insthync** [comment]
I was fixed it, may upload it tomorrow.

**Comment by insthync** [comment]
Fixed in 1.53b, if the problem still occurring, you can reopen it.
