### ISSUE TITLE
Shakiness during Mellee Combat

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2390]
i get this shakiness. I have gotten it with the default collider dimensions, any clue on what might cause this? Could this be due to A*/ailerp?

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/a0f6d8e2-d571-4644-9cd9-84092d386b08

**Comment by insthync** [comment]
Try apply this https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_2DAI/commit/326a43ece8d7ca384c53211c30b66cda3b44491b

**Comment by anthonyselias** [comment]
Thank you for the great support. It works!

**Comment by anthonyselias** [comment]
It still happens :(

**Comment by anthonyselias** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/a6732303-56de-4603-9c0a-57846028d0eb

**Comment by insthync** [comment]
Try turn interpolatePathSwitches in ai lerp off

**Comment by anthonyselias** [comment]
It's off with the same behavior. In the video I last posted, it was OFF. Were you able to test and replicate? All it should take it AI Lerp and A*/AIPath + Default colliders to replicate.

**Comment by anthonyselias** [comment]
> Try turn interpolatePathSwitches in ai lerp off

Did you get a chance to further test this?

thanks

**Comment by insthync** [comment]
I am going to fix it please wait

**Comment by anthonyselias** [comment]
Thank you. I appreciate it. When you get a moment can you let me know how I can add default spells to spell bars? I want to have them preaasigned 

https://github.com/suriyun-production/mmorpg-kit-docs/issues/2392

Also, I've tried to donate in ko fi but it keeps giving me errors. Do you have a link to PayPal donation, I can donate like that instead?

I appreciate all your help

**Comment by anthonyselias** [comment]
Also ,not sure if this information might help you, but I'll add it. It does it on mobile aswell. Im still trying to fix it myself, but no luck. looking forward to the fix, thank you

**Comment by insthync** [comment]
Try the latest commit

**Comment by anthonyselias** [comment]
Ok, so character stop shaking. But monster behaviour has changed. Now the monsters are shaking. Can you please test with mellee monster? i see that you tested with the archer npc thank you


https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/040daa7c-dbfc-46a4-a47a-142a47adda2c

**Comment by anthonyselias** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/c2811648-7f9f-4acf-89a4-f1ce3b8235e5

**Comment by anthonyselias** [comment]
Also, monsters are stacking on player

**Comment by insthync** [comment]
Did you remove AILerp/AIPath component?

**Comment by anthonyselias** [comment]
I have not, do I need to remove it? It was still on the Archer2D prefab you updated in the commit

**Comment by insthync** [comment]
Yes, you can remove the component.

**Comment by anthonyselias** [comment]
I removed it, and it's basically the same. When I attack the monster they all gather to the same position and attack me. How can we change it so they will spread out around the player instead of stacking? Colliders don't seem to help.

**Comment by insthync** [comment]
As I try, it has no problem, I want to see your monster damage info settings

**Comment by anthonyselias** [comment]
Can you send me your mellee monster prefab?

**Comment by anthonyselias** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/a70353ae-e4e3-41ed-a122-83afc5723883)

**Comment by anthonyselias** [comment]
Can you also check if texttransform for monster hits have been effected by the changes? I am unable to see the damage I do to the monsters, but I can see the damage they do to me, i have double checked and the texttransfo
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/b482baab-2ffc-46b6-806e-3e7f471f917f)
rm

**Comment by insthync** [comment]
Look at your Monster Character data file (in the image it is Rat), then find for Damage Info, and change settings there.

**Comment by anthonyselias** [comment]
I started a fresh new project with all changes. It's only fair to troubleshoot it like that because I've made so many modifications and I dont want it to conflict with the work you have done. I'll start a new thread for all future issues.
