### ISSUE TITLE
Cash problem

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2391]
Hello, I'm installing the google play consola game test, I'm making a purchase, the payment says successful, but the in-game cash does not change, does this part work properly in the current system?

**Comment by insthync** [comment]
Yes it is work.

I don't want to answer the same old answer again and again, you should try read this https://github.com/suriyun-production/mmorpg-kit-docs/issues/2349

**Comment by CLAXES** [comment]
I installed the se mmorpg-kit-iap-validation-service service you provided, I set the necessary things, but I could not understand exactly what to write in these two places below.

    IAP_GOOGLE_PUBLIC_KEY =
    IAP_GOOGLE_PUBLIC_KEY_SANDBOX =

**Comment by insthync** [comment]
Try to use google something like google public key in-app purchase , I think it it not hard to find.
