### ISSUE TITLE
Adding pre-assigned spells on mobile ui?

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2392]
How do we add Pre-Assigned spells on the mobile UI?

So, if I made a new character, I would like the default UI to have assigned spells already

**Comment by anthonyselias** [comment]
I'm trying different ways, if you could point me in the right direction that would be great, thanks!

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/e8a0f108-cf97-4960-878a-5290971d3126)

**Comment by anthonyselias** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/e43c4033-24f6-417e-be93-28f8fe28eb3b)

**Comment by shubhank008** [comment]
> How do we add Pre-Assigned spells on the mobile UI?
> 
> So, if I made a new character, I would like the default UI to have assigned spells already

You can use this addon for the kit
https://github.com/ljars/auto-assign-hotkeys

**Comment by anthonyselias** [comment]
Thank you, I had found it on discord already, I forgot to close this. I appreciate it.
