### ISSUE TITLE
server using GPU

### ISSUE THREAD

**Issue by hiraku1994** [suriyun-production/mmorpg-kit-docs#2394]
I don't know if this should be like that, but because when I open the server it starts using my GPU, with the server open my GPU is always at 60% usage, and another strange thing is that if I open the game and reduce the graphics , and then I open the server again, it seems to consume much less GPU, it seems that the server also handles graphics processing

**Comment by insthync** [comment]
Did you build it as a server build?

**Comment by hiraku1994** [comment]
Yes, even when building with the server, the server remains open while consuming the GPU

The way I found to improve it is by opening the exe client, and reducing all the graphics, then I close and restart the server, then it consumes less, as I said it seems that the server is dealing with graphics processing

**Comment by shubhank008** [comment]
> Yes, even when building with the server, the server remains open while consuming the GPU
> 
> The way I found to improve it is by opening the exe client, and reducing all the graphics, then I close and restart the server, then it consumes less, as I said it seems that the server is dealing with graphics processing

Are you using the ` -batchmode and -nographics` flags ? The server build should not render any graphics and thus not use GPU at all (other than perhaps a minor %)

**Comment by temelkirci** [comment]
any news or update ?

**Comment by insthync** [comment]
From me?

**Comment by insthync** [comment]
You guys actually should ask Unity, if you built it as server build, run it in batchmode/no graphics but the result is not as you expected. I cannot do anything with this part, I don't have you Unity source codes to find out why, okay?
