### ISSUE TITLE
Passive skill not applied

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#2396]
Passive skills are not applied.
This is the latest version.

show buff options are checked.
Despite this, the increase is not displayed in the UI.

Hit, evasion, critical, critical damage, etc. are not applied.

https://github.com/suriyun-production/mmorpg-kit-docs/assets/58978516/9a55dce1-f88d-498c-8b13-5f0967ac9104

![image1](https://github.com/suriyun-production/mmorpg-kit-docs/assets/58978516/0ccd4807-f95e-45b5-9a3a-d76542345584)

![image2](https://github.com/suriyun-production/mmorpg-kit-docs/assets/58978516/621b8615-97b9-4846-ae44-6a80fecf4014)

**Comment by insthync** [comment]
Fixed, change codes like this

![Screenshot_2](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/5c2f0a60-9312-4c14-811e-a47f03ef36ec)
