### ISSUE TITLE
Wrong exit position when leave Vehicle in MMO

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2398]
i have an issue when exit Vehicle in MMO. i think it has something to do with the FindGroundPosition here:
https://gyazo.com/f827568e2bc026f743ab986fb0cdf18b

In singleplayer it works fine but in MMO the Player spawn in terrain. i draw something to explain it from the side
https://gyazo.com/b4a553a260ba567b2a3da86bcf40f678

the green cross is the exit transform. an in sp it find the correct groundposition (orange), but in MMO player spawn at purple cross.
i put the exit transform to y 10 to test and eventhen the playerspawn in terrain

**Comment by insthync** [comment]
As I seen it has no difference between server and client codes, I guess Unity build might have difference proceeding with client which is non-headless.

**Comment by insthync** [comment]
You should try to debug the position, check if it pass find ground position function or not, then tell me the info later.

**Comment by moepi2k** [comment]
Thought same, i will debug it today

**Comment by moepi2k** [comment]
ok added some logs, and even on server the groundposition is correct. but somehow the player still teleports under the terrain (server and client) i noticed its only with few vehicles. others are fine. i need to check why

**Comment by moepi2k** [comment]
p.s found the issue. its because the player seat.position.y is lower then the exit.position.y. any idea whats best solution in this case?

**Comment by moepi2k** [comment]
can you change VehicleEntity.cs:

public bool RemovePassenger(byte seatIndex)
and
public void RemoveAllPassengers()
to virtual so we can override it in inherited class?

else we cant make our own methode since the interface always call the base class.

**Comment by insthync** [comment]
Yes, you can do it because you have the repo access

**Comment by insthync** [comment]
Then make a pull request, that is it

**Comment by insthync** [comment]
Why did you request for a repo accessibility if you are not going to try to use it to improve the project?

**Comment by moepi2k** [comment]
cool i do, just wanted to ask before. maybe im doing something wrong but i think it need to be virtual to use the interface in inherited methode.

also debuged yesterday the thing with exit vehicle and maybe u have another solution for the problem as i described above.
if it would work then i dont need to make my own methode.

so i wanted to wait till ur answer before i make request

**Comment by insthync** [comment]
Don't have to ask, when you create a pull request, it is just like to ask me to applies the changes, so if you ask here it is like double asking.

**Comment by moepi2k** [comment]
ok perfect thanks for the info. so for the issue with exit vehicle when player.transform.position.y is lower than exit.transform.position.y do you have any idea? actually i dont know why it cause to that issue in mmo, since even the debug log shows the correct position but still spawn under terrain in this case.
