### ISSUE TITLE
How do change default Zoom?

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2399]
I want to change the default zoom orientation for new players to be all the way out. I tried reading the documentation for the kit, but i dont see anything written about it. I also tried seeing if its stored in the database, but i think its locally saved. How do I add the zoom orientation to be all the way out for new players? thanks

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/58117e3a-9a1b-4cab-b2c2-4f02c221a347

**Comment by Niinra** [comment]
> I want to change the default zoom orientation for new players to be all the way out. I tried reading the documentation for the kit, but i dont see anything written about it. I also tried seeing if its stored in the database, but i think its locally saved. How do I add the zoom orientation to be all the way out for new players? thanks
> 
>  screen-20240130-203740.mp4

Wherever I mark you, look for the controller you have 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/f9b38772-f911-4434-8a04-8bc9c895149a)

I imagine this is your controller you select where I marked you go to the camera and change the zoom option


![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/65c67b84-8be1-41b5-ba8a-c21ae5f97c9c)


change zoom:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/fe95d3c5-f61b-431f-95a3-e38e930df93b)

**Comment by anthonyselias** [comment]
thank you!
