### ISSUE TITLE
Feature: Coupon/Code shop system

### ISSUE THREAD

**Issue by legionfrontier** [suriyun-production/mmorpg-kit-docs#240]
Hello, I will like to suggest a feature to add to this kit:
A coupon shop system where the developer sells an unique coupon code on their site, the player then puts it inside mmorpg and gets gold/items/skill or whatever is associated with it the code in the database.
I hope I expressed my idea good enough and I appreciate it to be added into the kit.
Thank you very much.

**Comment by Fallen01** [comment]
I like your idea and i think it would be a great feature!

**Comment by JestHWas** [comment]
Definitely something that would be very nice to have in the kit.

**Comment by poaq** [comment]
good idea

**Comment by xEdwinF** [comment]
nice idea :)

**Comment by insthync** [comment]
I won't do it for free, and if that one could be developed on web, then you can just develop it as a web, don't have to touch the kit codes, just create a web to do it and send an items by email by just insert it to database -> mail like I did for auction service one.
