### ISSUE TITLE
Enemies not facing the right direction when attacking

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2400]
With the new commits to prevent player shakiness, there was an updated astarplayermovement2d that made enemies not face in the right direction again when attacking.

I updated with new commits today, and the new code does not include this anymore. Enemies are no longer facing me when attacking like they were in the old commits, can you please fix the new commit to include this fix. thank you!

**Comment by insthync** [comment]
Okay, it is back.
