### ISSUE TITLE
Animationspeed while Underwater

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2401]
first, i tested new commit. state and speed now works as intend, but there is a problem with the animation speed while in underwater state.

when u set movementspeedWhileUnderwater to e.G 0.5 the animation speed for swimming is also halfed. this leads to a missmatching animation when for example are mounted in water ant the mount has fixed movement speed. i think its not intend that movementspeedWhileUnterwater should affect animation speed. for that you have the animspeed variable

**Comment by insthync** [comment]
Fixed
