### ISSUE TITLE
2DAI* Issue with Melee Combat

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2402]
There seems to be an issue with the player attacking a monster, even with a higher or lower attack distance setting, it produces the same result. If the distance is higher, my player will indeed attack from a further distance, but the issue of the player not being able to attack at all sometimes, is still there. 

This is a FRESH PROJECT. 

I am using the latest updated asset in the github

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/cadc8245-8308-46c9-a1a0-24f847a02849

As you can see in the video, there are 2 instances of where I try to attack a monster, and I cannot. When I use a lower distance, I get the same issue.

Before the last update, the player was probably having the issue of constantly going back in forth because it was trying to position itself so it can attack the monster. With the latest fix, the player doesn't keep moving back and forth, but it sometimes can't get in combat with the monster properly.

**Comment by anthonyselias** [comment]
Can you confirm you are looking into this? Thank you so much

**Comment by insthync** [comment]
Want to hear "I will fix it", that is it, right? :P

**Comment by anthonyselias** [comment]
> Want to hear "I will fix it", that is it, right? :P

I just wanted to know if it was brought to your attention and/if you are able to replicate the issue and fix it. It's basically the only bug that needs fixed at the moment, besides that all seems to be working fine, I have gotten quite familiar with the kit since I started using it. Thank you and I appreciate your time

**Comment by insthync** [comment]
Can I says no?

**Comment by anthonyselias** [comment]
Lol, of course.

Look, I appreciate all the help and support. You have fixed some issues that were present in the past, and I greatly appreciate you. As a matter of fact I would like to donate to you for your time, effort, and patience. I tried with Kofi but it wont accept my payment, idk why I tried several credit cards and it wont work. If you have another way for me to donate, please let me know, or a paypal donation link etc.

The kit is amazing, and I just want the basic functionalities to work, to a bare bone standard, that I can work from.

**Comment by insthync** [comment]
Nah, I still want to fix it :P

**Comment by anthonyselias** [comment]
Thank you, you are amazing!

**Comment by insthync** [comment]
[change_deltatime.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/14174846/change_deltatime.zip)

Try this.

**Comment by anthonyselias** [comment]
Thank you! It seems to be working! I LOVE YOU. I APPRECIATE YOU <3

**Comment by insthync** [comment]
Great :)
