### ISSUE TITLE
[SUG] Optional Delayed Spawn Bool

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2403]
There's a few folks (including me) using SECTR or World Streamer 2. The player character spawns before the terrain chunks have loaded meaning the player somtimes falls through the floor.

Falling through floor at spawn: https://i.imgur.com/metYBM4.mp4

An optional bool in GameInstance to hold player spawn X amount of seconds.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/48354382/f22831bc-36b0-4912-925b-2cdc66f4db32)

Will let chunks load and then player will land on terrain.

**Comment by insthync** [comment]
With time?, how can you sure it will be enough for all devices?

**Comment by BJPickles** [comment]
Seconds was my initial thought.
Not sure about that last one, I suspect trial & error unless you have an idea?

**Comment by insthync** [comment]
Yes, I have an idea, just do like I did to `IsReadyToInstantiateObjects` function

**Comment by BJPickles** [comment]
Ok sounds good. My main thought was not wanting affect other people's projects so still having it as Bool.

Good idea, waiting for the terrain to load before instantiating player

**Comment by insthync** [comment]
Done, let's test it later.

**Comment by BJPickles** [comment]
Hi Suri, sorry to bug you. I can't find where you've put it.
Is it this?
https://i.imgur.com/KlIPRDe.png

**Comment by insthync** [comment]
No, it is not that ready to use like that, you will have to write codes to determine that the client is ready or not, like as how the IsReadyToInstantiateObjects is working

**Comment by BJPickles** [comment]
Thanks for your quick response! That makes sense, thank you for explaining.
Unfortunately I can't code very well so I won't be able to test this my apologies
