### ISSUE TITLE
Problemas con combat, una BUG

### ISSUE THREAD

**Issue by CarlosMEd88** [suriyun-production/mmorpg-kit-docs#2405]
Hello. I am using a translated, I hope you can understand. I am using 2D con kit, con a* asset. I have problem with sometimes I attack and I walk to monster but nothing happen. Sometime I attack and it work. Is problem with pathfinder and attacking monster because sometime it not stay on tile like when walking and not attacking.

**Comment by Niinra** [comment]
Send a video, sube un video no se entiende cual es el problema

**Comment by insthync** [comment]
Same with this https://github.com/suriyun-production/mmorpg-kit-docs/issues/2402

**Comment by insthync** [comment]
Seems like it was fixed (https://github.com/suriyun-production/mmorpg-kit-docs/issues/2402), if you still having the issues, you can reopen this.
