### ISSUE TITLE
Missile and raycast attack problem

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2407]
Hello, when I use one of these, when I go inside the damage hitbox collider area, the hits are wasted, I guess the damage does not work.

When the monster is big, the damage hitbox collider is also big and the archer's shots are wasted when the monster approaches

**Comment by insthync** [comment]
I will check it

**Comment by CLAXES** [comment]
This problem occurs when there is a big monster and the archer gets into it when it gets too close

**Comment by CLAXES** [comment]
Have you had a chance to check

**Comment by insthync** [comment]
Not yet.

**Comment by insthync** [comment]
Seems like I cannot do anything, the hit detection codes, is Unity's stuff, I can change anything, if you want to try to fix it then in `MissileDamageEntity.cs` find for `Physics.Raycast` and try to do something
