### ISSUE TITLE
[Bug] Can't respawn if killed by Consume Hp

### ISSUE THREAD

**Issue by ljars** [suriyun-production/mmorpg-kit-docs#2408]
[Tested in single player.]
If you use a Skill with a `Consume Hp` amount equal to your current Hp, it kills you (as expected).
But you don't get the Respawn option in the System menu.

The problem seems to be fixed by adding:
```
if (Entity.IsDead())
{
    Entity.CallRpcOnDead();
}
```
after the calls to AddOrUpdateSkillUsage() in DefaultCharacterUseSkillComponent.UseSkillRoutine()

**Comment by insthync** [comment]
Fixed, but I did it like this
![Screenshot_15](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/1cee5e7a-2164-40bf-86ba-8eed28763902)
