### ISSUE TITLE
Beginner Errors

### ISSUE THREAD

**Issue by Gallamanji** [suriyun-production/mmorpg-kit-docs#2409]
Hi all,

I just downloaded and imported the MMORPG Kit today, and have been following the steps in the documentation, but I have encountered some errors. If anyone could help me resolve these I would be very grateful.

I got to the "Building" stage of the guide, still in "getting started". I either click to "build" the project, or "build and run" and I encounter these errors...

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/50011694/7a6969cb-8942-4424-b494-3d6a84582203)

I get these if trying to build from en empty SampleScene or from a demo scene from the package...

Also, after I closing the project and then trying to open it for the first time since making it, I encounter this error...

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/50011694/b36052d9-fa4f-4eab-8872-e69ede8a62fd)

And these are shown in the console when opening in Safe Mode...

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/50011694/8fadcb6a-c380-4a50-bea2-a3528b557256)

Any help is much appreciated! Thank you!

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan?id=want-to-use-new-input-system

**Comment by Gallamanji** [comment]
> https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan?id=want-to-use-new-input-system

So I should use the new input system? Thank you very much I will try this later and report back if it doesnt work :)

**Comment by insthync** [comment]
You can use the old one, but you have to change input handling to old.
