### ISSUE TITLE
[BUG] Swimming & AutoSwim to Surface - State issue

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2410]
Version: 1.87
Hey Suri, sorry to report a bug! Found something when swimming:

When swimming, if "AutoSwim to suface" is enabled, the player is constantly changing between states when on the surface - as seen in this video:

https://i.imgur.com/9KWKPS9.mp4

In the video I then disable autoswim to surface (loading screen). When you disable it, swimming works fine.
I think it might be the "fall" state, but I'm not sure.

In normal Character Controller, there is no way to swim up or down, so when "autoswim to surface" is turned off, if you jump into a deep part of the water, you can't always swim back up to the surface to get out of the water.

Please can you add `Spacebar` to ascend and `CTRL` to descend when swimming.

**Comment by insthync** [comment]
NO

**Comment by BJPickles** [comment]
Okie dokie, thanks anyway

**Comment by insthync** [comment]
You want to disable or enable auto swim-up?, or you just want both? I really boring of the swimming can't you see how many of it was reported? can't you see how many times I try to fix it? https://github.com/suriyun-production/mmorpg-kit-docs/issues?q=is%3Aissue+is%3Aclosed+swim .

I really want to say NO, can I?, it is having too many of entity movement features requested and they are always affect each other when I fix one or add one, it must be able to be controlled by point-click then it must be able to be controlled by WASD, then swim, then root-motion supports, then slide on steep slope, stair climbing, whats else then.

I hope someday it will have someone can just sharing the codes, you guys can copy mine to create yours, or create yours from scratch, it is up to you.

**Comment by insthync** [comment]
Send me your AnyDesk number, I will check it.

**Comment by insthync** [comment]
I am waiting

**Comment by BJPickles** [comment]
Email sent

**Comment by moepi2k** [comment]
> Version: 1.87 Hey Suri, sorry to report a bug! Found something when swimming:
> 
> When swimming, if "AutoSwim to suface" is enabled, the player is constantly changing between states when on the surface - as seen in this video:
> 
> https://i.imgur.com/9KWKPS9.mp4
> 
> In the video I then disable autoswim to surface (loading screen). When you disable it, swimming works fine. I think it might be the "fall" state, but I'm not sure.
> 
> In normal Character Controller, there is no way to swim up or down, so when "autoswim to surface" is turned off, if you jump into a deep part of the water, you can't always swim back up to the surface to get out of the water.
> 
> Please can you add `Spacebar` to ascend and `CTRL` to descend when swimming.

the problem with the state u mention when use autoswimtosurface is when u center in charactercontroller.
try use this https://gyazo.com/8c88cc747dfa5e6dd34b2f40ea1a81f9

add 0.05 in height. i dont know why but this solve the issue

**Comment by insthync** [comment]
I've sent the fix package.
