### ISSUE TITLE
Effects not showing on hero editor

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2411]
Hey, I recently started using https://github.com/insthync/UnityMultiplayerARPG_HeroEditor4D . it works great, but I'm having a problem with skill effects, and level up effects. When I switch to old prefab default character it's fine, but when I use the Hero editor, I am unable to see the level up graphics effects, or sound, and im also unable to see the skill effects.

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/fba901e2-a0f3-4397-bace-df3cd6e66a72

**Comment by insthync** [comment]
It is all about effect transforms, try find settings in character model / player character entity.

**Comment by anthonyselias** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/90e41377-b0b5-4735-ae39-f2e0b1598a8d)

**Comment by anthonyselias** [comment]
The default prefab didn't have chat bubble, I had copied and pasted it and got the chat bubble to work, but I still can't see effects working, such as spells or level up

**Comment by anthonyselias** [comment]
Can you please fix the refabs so the proper effects are showing. Such as level up, etc

**Comment by insthync** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/177-game-effect
