### ISSUE TITLE
Problem again with Hit Detection in new patch + Bugs in updated A* 2 ISSUES

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2412]
Hey, Suri!

_ISSUE 1_

**Recently you fixed an issue I had with hit detection, and after the fix it worked perfectly. With the new patch, the problem is back.**

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/92db3c5a-b1bc-4566-a1bf-3793adf2776d

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/59848d5c-e52d-4aef-8f21-8c201cd0e6ec)

**The problem is back again.** 

_ISSUE 2_

**Updated to the latest A Star on github, breaks the game, i had to look in my backups and copy and paste older version to fix it**

https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_2DAI

https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/89f9e38a-6158-4a4d-bf9a-de3fc4d65039

**Comment by insthync** [comment]
This one ? https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_2DAI/commit/e9bf2201f8608ff7bb49aa3f958ed8b111c422b4

**Comment by insthync** [comment]
There is no error message in console log?

**Comment by anthonyselias** [comment]
[Uploading Player.log…]()

here it is

**Comment by anthonyselias** [comment]
[Player.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/14227035/Player.log)

**Comment by anthonyselias** [comment]
& yes, i did rebuild the server

**Comment by anthonyselias** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/ce0d5b7b-74de-4ee7-b673-3d157d9f55b6

I replaced the A* with the old one while u fix the new one, but I wanted to show you another video of the combat issue

**Comment by insthync** [comment]
From what I seen from your video, it is not starts an attacking I guess that it is because the character stops before it reach target at client, it might stopping because it have to stop on the grid, but it won't starts an attacking because start attacking distance is not long enough to target, you have to try to increase damage info -
> attack distance

**Comment by insthync** [comment]
Which old Astar? Whats are difference?

**Comment by insthync** [comment]
You should copy logs from server folder / log, not that one, it is hard to find issues.

**Comment by anthonyselias** [comment]
The updates from 4 days ago on https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_2DAI breaks the game. i have a backup of the files before the change 4 days ago that works fine. 

I just copied the new files back to the project so i can troubleshoot it for you some more.

Once again, this is what it does

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/f99e1af4-5db6-4294-a578-7429464f67ea)


Here are the logs from server file
[Logs.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/14228100/Logs.zip)


I have tried changing the attack distance on both the monster and the unarmed prefab, it did not change the problem. From what i can see, after trying a million times, is it gets stuck like that when I am attacking a monster that is about to move. So if the monster tries to wander exactly when I try to attack, this happens.

The fix that you sent me, just a couple days ago, made it work perfectly. But when I upgraded to new kit, I started having this issue.

**Comment by anthonyselias** [comment]
Old Files that work

[Old2DAI.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/14228139/Old2DAI.zip)

New files that don't work
[UnityMultiplayerARPG_2DAI-master (3).zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/14228150/UnityMultiplayerARPG_2DAI-master.3.zip)

**Comment by anthonyselias** [comment]
OK, I have checked my gamedatabase, and for some reason when I put the new A*, it replaced my mapinfos. So, the new one actually works.

I still have the issue of it not attacking properly, i have changed the distance on both the monster and player and I get the same results

**Comment by anthonyselias** [comment]
I will close this issue, and create a new one so this wont be confusing.
