### ISSUE TITLE
Player Attacking Monster BUG with New Kit Version

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2413]
I had made a previous post, but I closed it and made a new one to avoid confusion since it had two separate issues in them.

Previously, I had this problem, and it was fixed on #2402 

But, with the new kit update, I am having the same issue. I tried changing both monsters and player attack distance and it did not make a difference.

The last fix had to do with RigidEntityMovement2D and since the last fix, it had another set of updates that may have affected it

**Comment by insthync** [comment]
The RigidEntityMovement2D which was posted here a few days ago is newer than the one from the asset store.

**Comment by anthonyselias** [comment]
ok, I did that, 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/6fb24400-1fab-4ff4-bd40-573e2c013c97)


so currently I'm using 

the newest kit version, newest a* addon + the rigidentitymovement2d, using default character prefabs, and monster settings are the same as the last time it worked, I've tried changing the distance with no luck unfortunately :/


https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/efa8f343-6d5f-4e83-bd64-9b73c9b89436


It happens like 1 out of 4 times

**Comment by anthonyselias** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/58800b72-9679-4c62-b174-e96360ae817d)


Someone else has the same exact issue since updating to the new kit version. And, similarly, when you attack the monster right as the monster is about to wander, this happens

**Comment by insthync** [comment]
And so, is that a helpful info?, how will it helping me to fix it?

**Comment by anthonyselias** [comment]
Perhaps there's a problem with the logics of when the player gets in combat with a monster that is beginning to wander

**Comment by insthync** [comment]
What is it?

**Comment by anthonyselias** [comment]
I'm not sure. That's why I'm posting, perhaps the professional can assist?

**Comment by insthync** [comment]
How it help me to fix it?

**Comment by anthonyselias** [comment]
How would I know? 

All I know is it worked before the update, and it doesn't after. 

So, you must have modified something that interfered with it. 

Are you joking with me?

**Comment by insthync** [comment]
I don't get why you keep posting non-sense thing such as what other said, how is that helping me? Just a simple question, if it not then just stop.

Is that a joke?, are you laughing with that?

**Comment by anthonyselias** [comment]
Letting you know that there are other people experiencing the same issue is non sense? What kind of support is that? 


I'm giving you as much information as I can to help you resolve the issue. 


Idk what you are trying to say exactly. I'm just reporting a bug. 

If I could fix it, I would have already. So I'm depending on your support.

**Comment by insthync** [comment]
How do other people's experience is makes sense to fix the bugs?

The support is simple, If you have problems, then you tell me your problems, how to make it happen (for reproducing), and should attach an error logs, then you don't have to do anything, just wait for me to fix it. Or asking you.

Go back and read what you tell me before you tell me about what other people saying
Did I ask for anything? No, I didn't, and I am going to try it and fix it by myself.

Then you tell me that other having the same issues, how I knowing that other having the same issues will help me to fix the bugs?, you don't have to tell me that other having the same issues because it is not helpful.

After that you try to guess what is happen but you don't know what it is, is that help me to fix it? still no, right?

Just wait me to try it and fix it y myself is better than telling me those information.

**Comment by anthonyselias** [comment]
Telling you that others have the same problem is not a reason to get offended. I wasn't trying to offend you, or be offensive. Like I said I was trying to give you as much information to aid you as much as I can. 

If I was the only one having the issue, there may have been a possibility of me having a problem that I created. By letting you know others are having the same issue, in assuring you that it isn't something that I messed up on my end. 

I wouldn't want you to try to fix something that doesn't need to be fixed. 

I'm sorry if you thought I was being rude or offensive, this isn't the case at all. 

I'll be waiting for the fix, thank you.

**Comment by shubhank008** [comment]
> ![image](https://private-user-images.githubusercontent.com/134556081/303821040-58800b72-9679-4c62-b174-e96360ae817d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MDEwODEsIm5iZiI6MTcwNzYwMDc4MSwicGF0aCI6Ii8xMzQ1NTYwODEvMzAzODIxMDQwLTU4ODAwYjcyLTk2NzktNGM2Mi1iMTc0LWU5NjM2MGFlODE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQyMTMzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTBlN2JiYjM4MzkxMDhmMGI5ZTY4MTkwZDVjNmY3OTE1YzkzYTU1Y2VhNTIyNWNiMjNiY2MyYTJmOWFmMzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IM_S3Or14uV2eB3NRrccwCuFaG0vaXWNj6sjcsZtWao)
> 
> Someone else has the same exact issue since updating to the new kit version. And, similarly, when you attack the monster right as the monster is about to wander, this happens


Just to clarify since someone notified me that my message was being used in wrong sense, I do not have this or any such bug. 
My message was clearly for discussing in-general on how to improve attack chance on monsters by speeding up animations i.e. it was a general gameplay mechanic discussion, not bug discussion or report.  

<img width="1298" alt="Screenshot 2024-02-11 at 3 09 45 AM" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/3790163/f92900da-f67a-4a77-8adc-42d8bf6de4ba">

Just 2 message down, Neomis even provided the improvement feedback I was looking for. 

So yes, I donot have any such bug per say.

**Comment by shubhank008** [comment]
> ok, I did that,
> 
> ![image](https://private-user-images.githubusercontent.com/134556081/303819866-6fb24400-1fab-4ff4-bd40-573e2c013c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MDE1ODksIm5iZiI6MTcwNzYwMTI4OSwicGF0aCI6Ii8xMzQ1NTYwODEvMzAzODE5ODY2LTZmYjI0NDAwLTFmYWItNGZmNC1iZDQwLTU3M2UyYzAxM2M5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQyMTQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Mzg2Y2E1NDg4M2U1ZGI5ZTMxMjc2N2Q0OTlmMjQwMDczNWFhNjJlZTQ1MGY1ZjljMjQzMzhlZmViNGY5M2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CK75jhFohpDfulDfIFqmDdSYA6g3clZRVGOm-icjtvc)
> 
> so currently I'm using
> 
> the newest kit version, newest a* addon + the rigidentitymovement2d, using default character prefabs, and monster settings are the same as the last time it worked, I've tried changing the distance with no luck unfortunately :/
> 
>  newrecord.mp4 
> It happens like 1 out of 4 times

Also, did you confirm this problem in a fresh kit demo ? To make sure none of the addons/custom code interfering ?
Did you check if its perhaps a case of Miss Chance ?
Any client or server error logs ? 
Perhaps try to add a Debug statement yourself when attacking to check if the target is still actually the monster ?

What are exact steps to reproduce this problem ?

That's the kind of things Suriyun meant if you tried yourself and to provide more details.

**Comment by anthonyselias** [comment]
To reproduce it, just import a new 2D project, set A* path finding, and just run the default prefabs. Attack the orc archers with melee and you will see that 2 out of 10 times it will walk to the monster, attack it once; then stop. The monster will continue attacking you assuming you didn't miss the first attack. The only way to hit it would be to move to a different time re engage in combat.

**Comment by anthonyselias** [comment]
/
