### ISSUE TITLE
error when importing assets

### ISSUE THREAD

**Issue by nammaster31** [suriyun-production/mmorpg-kit-docs#2414]
![bug](https://github.com/suriyun-production/mmorpg-kit-docs/assets/160015022/e424bf9c-b57c-43a0-9247-e62269824d2a)
hello I'm a newbie, after importing your package into the new project, here are 2 errors that appear that I can't fix, can someone help me, very grateful

**Comment by insthync** [comment]
Hmm, weird, can you find ZLogger folder in your project's assets?

**Comment by nammaster31** [comment]
> Hmm, weird, can you find ZLogger folder in your project's assets?
 
![bugâ](https://github.com/suriyun-production/mmorpg-kit-docs/assets/160015022/3158653f-dd06-4a94-aaa4-309b7202008a)
Is it?

**Comment by nammaster31** [comment]
> Hmm, weird, can you find ZLogger folder in your project's assets?

i'm so sorry about the original error message, that happened after i deleted zlogger because i couldn't find a solution, this is the real error, so sorry
![Uploading bug3.PNG…]()

**Comment by insthync** [comment]
Hmm, so.. what is the problem?

**Comment by nammaster31** [comment]
> Hmm, so.. what is the problem?

![bug3](https://github.com/suriyun-production/mmorpg-kit-docs/assets/160015022/4654169c-4ea3-4b61-bfae-95f7ce962d49)
here sir

**Comment by insthync** [comment]
Which unity version ?, Which MMORPG kit version ?

**Comment by insthync** [comment]
Please send me your invoice ID to my email: ittipon.bay@gmail.com

**Comment by insthync** [comment]
Nothing sent to me, I will determine that you've got it from pirate site, and I won't help you (If you do then I have 2 words for you but I think you can guess what are them) ;)
