### ISSUE TITLE
interactable objects

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2416]
What method is used so that when interacting with the object the player executes an animation?
and also that changes the item in the player's hand?
I tried to find it here but without success.

**Comment by insthync** [comment]
Might have to write your own scripts, will you do it?

**Comment by juniormagalhaes** [comment]
> Might have to write your own scripts, will you do it?

Yes, I have an experienced programmer friend who is helping me.

**Comment by insthync** [comment]
To play custom animation...

Okay, do you know that it has `customAnimations` in `PlayableCharacterModel`, you can set custom animation there.

Then in `BaseGameEntity` it have `CallRpcPlayCustomAnimation` and `CallRpcStopCustomAnimation` functions which you can use it for animation playing.

 You also can see demo's `PlayCustomAnimationAfterIdle` class to learn how to use it.

Then you may hide weapons by deactivate weapon equipment sockets game objects.
