### ISSUE TITLE
Server RAM Usage Issue

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2417]
I have server RAM problem.My server has 128 GB.I start server as 25 GB RAM usage, but It increase all the time.Players cannot enter game when server has 75 GB RAM usage.I think there is a memory leak due to my code changes or asset or vfx problem.How can I detect RAM usage problem ?.

What kind of things cause server RAM problem in Kit (Memory lack) ?

**Comment by insthync** [comment]
I'm going to fix it, it will have many thing to be changed, afraid it will affect your version :P

**Comment by temelkirci** [comment]
Thank you, but what is problem excatly ?. Is it memory leak because some references do not release properly?

**Comment by insthync** [comment]
Yes, that is it too, and I also want to reduce memory usage by not storing attributes/stats in to dictionary, and implements addressable assets because with Unity system, every references of prefabs/scriptable objects which set into any game objects in the scene will be loaded when scene loaded.

**Comment by temelkirci** [comment]
Thank you so much.I will wait next update about memory reduce

**Comment by temelkirci** [comment]
@insthync  Sorry for reopen.But I have +100 online players in my server and 128 GB Ram.I have to restart my game everyday.Please Could you give me a example to detect memory leak in kit.I can find another memory leaks and try to fix as soon as possible.I just need some examples.

I want to ask BasePlayerCharacterEntity player = attackerCharacter as BasePlayerCharacterEntity;  I do many conversion like that in kit.I am worry this cause any memory leak?

What are the memory leak reasons  in KIT?.

**Comment by insthync** [comment]
You can try to use Unity's memory profiler or heap explorer which is not made by Unity to finding for which one use a lots of memory.

Conversion is fine.

Someone told me that turn incremental GC off is better, memory usage are reduce but it is having noticeable spike while playing.

**Comment by temelkirci** [comment]
When is your plan about it ?

**Comment by insthync** [comment]
I've told you

**Comment by temelkirci** [comment]
I took a memory snapshot in runtime in my server.I am not sure Leaked Managed Shell mcause memory leak in RAM.I am not sure how can I detect memory leak in memory snapshot.I share some screen shots, maybe help you.I can share whole memory profiler file for you.

![Ekran görüntüsü 2024-03-06 093731](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/c10a18fe-8e65-476a-b315-c5d35d4d69c7)
![Ekran görüntüsü 2024-03-06 093935](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/ff7e9c12-0c57-43ab-a1c4-705bca3707ba)
![Ekran görüntüsü 2024-03-06 094236](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/b94de63d-0755-4734-8bee-b2924b36ad9c)
![Ekran görüntüsü 2024-03-06 094411](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/61981b10-e08e-4ddb-b96a-82cbc4836ec0)
![Ekran görüntüsü 2024-03-06 094515](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/d5a43550-b016-431e-b67c-722a45fd244a)
![Ekran görüntüsü 2024-03-06 094611](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/e92470cd-435e-4c79-9885-613919e56f46)
![Ekran görüntüsü 2024-03-06 094740](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/ba20b28b-ac06-479d-ac5d-b97ddaf1521c)

**Comment by mhmmdciftciler** [comment]
:MMORPGKit, in its bare form, increases the amount of RAM usage with a linear increase, without any add-ons. Those who developed the kit, you are in trouble on this issue. I didn't analyze it, but this was the process I observed on my remote server. I want to develop a project with MMORPGKit, but I realized that this is not a good decision.

**Comment by temelkirci** [comment]
I am trying to analyze and fix it.Do you have any idea or sugesstion about it?

**Comment by insthync** [comment]
Yep, I am fixing it

**Comment by insthync** [comment]
If you guys, can't wait  me to implements a new addressable assets integration and new movement features then I will publish a new version today, it will have an addressable assets integration features which you guys should use it to reduce memory leaks issues.

**Comment by temelkirci** [comment]
I am very appricate about it.I will try new version in my new MMORPG game project.It will be fix all memory leaks issues? Otherwise you will keep it fix it until no memory leaks?

**Comment by insthync** [comment]
Yes, that is what I am going to do

**Comment by insthync** [comment]
I will ignore more new feature requests 😜

**Comment by insthync** [comment]
And I've clear ref to Unity object to avoid leaked managed shells https://docs.unity3d.com/Packages/com.unity.memoryprofiler@1.1/manual/managed-shell-objects.html

**Comment by insthync** [comment]
I've added you as a core repo collaborator.

**Comment by insthync** [comment]
Are you sure that you are using 1.82, if yes then I might add tag for that version then you can check out it then applies your change before pull my commits

**Comment by insthync** [comment]
> :MMORPGKit, in its bare form, increases the amount of RAM usage with a linear increase, without any add-ons. Those who developed the kit, you are in trouble on this issue. I didn't analyze it, but this was the process I observed on my remote server. I want to develop a project with MMORPGKit, but I realized that this is not a good decision.

So you are not going to use my kit, then why still asking me to fix IAP?

**Comment by temelkirci** [comment]
Yes I am sure about it.I updated my kit around october lastly.

**Comment by insthync** [comment]
@temelkirci @mhmmdciftciler do you guys works in the same team with suitech?

**Comment by temelkirci** [comment]
@insthync no, I have my own game company as Kayra Games.I do not know suitech and @mhmmdciftciler .

**Comment by mhmmdciftciler** [comment]
You misunderstood my message. Having memory problems is a problem for a serious project. I wanted to say this. I work with Suitech. My unit works on optimization issues and I wrote it here because we have the same problem.

**Comment by insthync** [comment]
@mhmmdciftciler So? did you try to do anything to fix it?
