### ISSUE TITLE
Missile Hit registration issue

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2418]
in 186+ hit registration with missile is bugged. it was fine in 185. i add debug logs on the impact and it clearly hit the target, missile gets destroyed but no dmg. this occure random

here a video
https://gyazo.com/4787423a8da3d581e19a0483af64e355

u see 1 and 7 hit not register. overall 14 hits. and followed the debug log from server. all hits on hitbox but 2 not register.

**Comment by insthync** [comment]
Yep, but I can't understand the log messages :P

**Comment by moepi2k** [comment]
Thats just to show what the missiles hit. Like in game i hit the monster 14x and in the log i count from bottem upwards those 14 hits 😄
