### ISSUE TITLE
Possibility to hide item drops tables from users

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#242]
For the moment server and client share gameinstance so with little effort it is possible to check any drop table / success chances etc. It would be cool if there would exist possibility to hide it from client side.

**Comment by insthync** [comment]
No, but you can make a drop table at the server-side difference to the client by change game data before start servers, you may changes codes in MMOServerInstance.cs → OnGameDataLoaded() to load game data from web-service then replace each game data before start server. This would relate to the feature that someone requested: "Can setup game data via database", but I didn't do it yet.

**Comment by JestHWas** [comment]
I think getting game data such as drop tables from the database would be a fantastic addition.
