### ISSUE TITLE
About Hit Chance

### ISSUE THREAD

**Issue by MagicHope** [suriyun-production/mmorpg-kit-docs#2422]
If first character have Accuracy = 45, (Set OrcWarrior‘s BaseStats accuracy to 45)
Second character have Evasion = 5, (Player's Evasion is  5)
Hit chance = 2 * (45 / (45 + 5)) = 1.8
Then second character will receives damage if random result from 0 to 1 <= 1.8

According to the result the second character(Player) should be hit by 100%, but got a lot of MISS...

**Comment by moepi2k** [comment]
check also the level difference. in gameplayrule.cs you can make ur own formula. by default i checks also for level

**Comment by MagicHope** [comment]
Thank you...That's the reason..
