### ISSUE TITLE
"Do not random animation" not working

### ISSUE THREAD

**Issue by gochaboy1** [suriyun-production/mmorpg-kit-docs#2423]
Most often 2 animations are used and 1 animation can be repeated several times in a row.

https://github.com/suriyun-production/mmorpg-kit-docs/assets/41185982/85254a8a-86c1-405e-bd5f-cc77c81d7f63

**Comment by insthync** [comment]
How about `animationResetDelay` setting?

**Comment by gochaboy1** [comment]
> How about `animationResetDelay` setting?

I tried doing the values 1 2 3 4 5, but the result is the same

**Comment by insthync** [comment]
Can you help me try to debug it by just write log message `_lastAttackAnimationIndex` , `time - LastAttackEndTime`

**Comment by gochaboy1** [comment]
> Can you help me try to debug it by just write log message `_lastAttackAnimationIndex` , `time - LastAttackEndTime`

I can provide you with anydesk

**Comment by insthync** [comment]
Are you available in next 4 hours?

**Comment by gochaboy1** [comment]
> Are you available in next 4 hours?

Yes

**Comment by gochaboy1** [comment]
it was my mistake, everything works correctly
