### ISSUE TITLE
unable to basic attack

### ISSUE THREAD

**Issue by Usernameeder** [suriyun-production/mmorpg-kit-docs#2425]
Hello, after updating to newest version I tried using the old input manager and new input manager they seem to work as my skills work and jumping with space bar. But attacking does not work V or left click wont work and its assigned I tried using both inputs and still nothing. No errors in console.

Any advice or ideas is appreciated thank you

**Comment by insthync** [comment]
Which kind of player character controller ?

**Comment by Usernameeder** [comment]
thank you for your response. Its the shooter controller

**Comment by insthync** [comment]
No auto attack for shooter, not sure that are we understand auto attack as the same thing, in my understandation, it is when press the button, your character will move into front of enemy and attack, that is it?

**Comment by Usernameeder** [comment]
> No auto attack for shooter, not sure that are we understand auto attack as the same thing, in my understandation, it is when press the button, your character will move into front of enemy and attack, that is it?

what I mean is pressing V or left click basic attack not automatic sorry

**Comment by insthync** [comment]
How is automatic?, there is no automatic move to target to attack for shooter player character controller.

**Comment by Usernameeder** [comment]
Sorry didn't mean automatically sometimes in NA we call basic attack auto
attack. My problem is I had basic attack with v working fine then I update
and it stop working

**Comment by Usernameeder** [comment]
Sorry didn't mean automatically nothing is automatic thats not the issue.
My problem is I had basic attack with v working fine then I update and it stop working this is the regular hand basic attack with v or left click

**Comment by Usernameeder** [comment]
do you have any ideas why it would stop working after update? any advice is appreciated

**Comment by insthync** [comment]
Send your Anydesk number to my email ittipon.bay@gmail.com, I will check it

**Comment by insthync** [comment]
At least please attach the video, I don't know how is it yet, because mine works as intended.

**Comment by Usernameeder** [comment]
sorry I didnt see your reply I sent you the anydesk via email, I seriously appreciate this

**Comment by Usernameeder** [comment]
found out what it was thank you!
