### ISSUE TITLE
[Bug]CalculateItemRandomBonus.cs

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2426]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_Core/commit/2cffd30112c42a797753a5815bb794b739a3aa0a 

this commit leads to a bug so that bonuses sometims not apply.

**Comment by insthync** [comment]
Are you sure?

**Comment by insthync** [comment]
Can you understand the codes?

**Comment by insthync** [comment]
Too slow :(

**Comment by moepi2k** [comment]
Sry just noticed that 10min before goin to bed 😅 just tested commits and not checked what changed in latest commit
