### ISSUE TITLE
Question about PlayCustomAnimation

### ISSUE THREAD

**Issue by darkkriteus** [suriyun-production/mmorpg-kit-docs#2427]
Good evening, I use custom animations a lot to execute certain movements in my game, but I have a question as to how I can correctly call a CustomAnimation in a loop, as it is only executed once even though it is in a loop.

Here in PlayableCharacterModel in public void PlayCustomAnimation(int id), I noticed that no parameter is passed if the animation is in a loop
![ss1](https://github.com/suriyun-production/mmorpg-kit-docs/assets/49356246/a7a55949-20bd-49cb-ab7f-9b0617ce6481)

however, even adding a true parameter if it is a certain animation[id], the animation is executed in a loop, but it is not overlaid by other animations, only if another CustomAnimation is executed

would this be a bug? or how should I do it correctly to work in a loop

**Comment by insthync** [comment]
Which loop?

**Comment by darkkriteus** [comment]
I want to call a customAnimation in a loop, but it never plays in a loop

**Comment by insthync** [comment]
How did you call it?

**Comment by darkkriteus** [comment]
the movements I modify BuiltIn3dMovementfunctions and call Entity.PlayCustomAnimation(id)

I need to run a customAnimation in a loop, but even though the "loop" animation is selected, it does not remain

**Comment by insthync** [comment]
Is the animation playing should being synced to other clients

**Comment by insthync** [comment]
In a loop you mean to play animation looply?

**Comment by insthync** [comment]
I can misunderstand if you keep telling me that you want to play in a loop, because:

```
// This is loop (for...loop)
for (int i = 0; i < 10; ++i)
{
   // This is play in loop
   Play();
}

```

**Comment by darkkriteus** [comment]
sorry for the misunderstanding, the loop I mean would be an animation time loop

![Screenshot_20240309-074623](https://github.com/suriyun-production/mmorpg-kit-docs/assets/49356246/b49e6610-713d-4a3f-a7a0-d1ee6fc86065)

even the animation marked in a loop, it is executed only once

**Comment by insthync** [comment]
Yep, it is not use Unity's animator component to play animation, so that setting won't work

**Comment by darkkriteus** [comment]
That's why I sent the image up there,It does not send any parameters if the animation is to be looped
So I tried sending a true argument just to test, so it works, but the animation is only overlaid by another customAnimation, I don't know if you understand what I mean.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/49356246/70d7b7f2-131a-484a-a711-e2a02fd656be)

**Comment by darkkriteus** [comment]
I thought about doing something like
`if (id == 5)
{
Behavior.PlayAction(customAnimations[5], 1f, loop = true, actionId: _latestCustomActionId);
}
else
Behavior.PlayAction(customAnimations[id], actionId: _latestCustomActionId);
`

**Comment by insthync** [comment]
Enough, don't do anything, just wait for me to add new settings for custom movements, that is all you can do. Even it is currently having many settings but it is not enough, custom animation was made for emotion animation playing, that is it.

**Comment by darkkriteus** [comment]
OK, thanks for the help

**Comment by insthync** [comment]
How are you going to use this? why custom movement animation is needed for your game?

**Comment by darkkriteus** [comment]
I used it to create additional movements for my game, then it was easy to use customAnimation

**Comment by AlcidesJunior123** [comment]
I had this problem, I made a script to try to get custom animations when pressing a certain key, I'm still trying to finalize it and add details. The animation loops are still a bit messy. I'm also waiting for something like that.

https://github.com/suriyun-production/mmorpg-kit-docs/assets/139077085/eb55b3c3-e6d2-4d5e-b7cd-8b8141ccd29a

**Comment by insthync** [comment]
I don't know that you guys can use Unity's animator system to play animation or not, I might consider to create an example of mixing Unity's animator system and playable graph, so you guys might be able to create custom character model which can play animations as you wish with mix of playable graph layer to player action animations, so you guys won't have to create new state to put action clips (but still have to set clips in to that character model's settings)

**Comment by insthync** [comment]
> I had this problem, I made a script to try to get custom animations when pressing a certain key, I'm still trying to finalize it and add details. The animation loops are still a bit messy. I'm also waiting for something like that.
> 
>  MotorTest1.mp4 
> The animations are looping, but at the end of the animation time, before restarting the animation, it tries to call the animation Idle. I'm working to avoid this only, after I think it should work. I think that's what you might need too. I showed it here for further clarification.

How did you order it to play the lean animation?, which functions are you using?, play custom animation functions?

**Comment by insthync** [comment]
In next version (1.89), it will have `bool loop` parameter added to `CallRpcPlayCustomAnimation` function, turn it on to play loop animation properly.
