### ISSUE TITLE
Monsters Stop Respawning / Dissapear

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2428]
I'm having an issue with monster spawns. They initially spawn when I start the server, but over time they despawn and map becomes empty with no monsters.

I posted error logs below

![Screenshot 2024-03-14 171615](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/4b4a7968-657b-4c8c-b3fb-07357362ee91)
![Screenshot 2024-03-14 231709](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/eea9eb14-d95b-4bdc-a285-2e024775e3a0)
![Screenshot 2024-03-14 232423](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/fee85e2f-843c-4309-a13a-03b2d454c700)
![Screenshot 2024-03-14 232438](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/62def813-7b45-4f2b-a151-cc9033858317)
![Screenshot 2024-03-15 001756](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/0a2cbd97-103b-40b8-bbb0-782ff10670c4)
![Screenshot 2024-03-15 003138](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/71676bf2-0992-46d7-b2a5-6c2c9da6fc5d)
![Screenshot 2024-03-15 003200](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/74f36a0e-942d-47df-9bd6-7bd4a10bb849)
![Screenshot 2024-03-02 153238](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/5c85a630-dce5-4ee6-8358-41fe2e46e4ff)
![Screenshot 2024-03-03 013715](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/423d47fd-6f7b-4741-b6a6-90835a423543)
![Screenshot 2024-03-14 171421](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/fa2c8da9-fb14-4d84-91c3-41939cf23165)
![Screenshot 2024-03-14 171447](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/d843fa68-154f-4945-b6f3-47035038c66a)
![Screenshot 2024-03-14 171505](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/a8096ede-4cc9-4563-958f-2091098df103)
![Screenshot 2024-03-14 171519](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/df242ef2-96a2-447c-9820-62bb940e7e34)
![Screenshot 2024-03-14 171542](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/b7836da7-d03a-4c3d-86d0-7c5f3a01b208)
![Screenshot 2024-03-14 171605](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/4369cc60-ac32-4cda-b60c-02a23546a216)

`ERROR No Tag [2024-03-15 00:46:43] - Prefab is Found
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:56)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

ERROR No Tag [2024-03-15 00:46:43] - 1
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:60)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

ERROR No Tag [2024-03-15 00:46:43] - 2
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:62)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

ERROR No Tag [2024-03-15 00:46:43] - 3
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:67)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

ERROR No Tag [2024-03-15 00:46:43] - 4
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:69)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

ERROR No Tag [2024-03-15 00:46:43] - 6
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:81)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

ERROR No Tag [2024-03-15 00:46:43] - 7
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:83)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

ERROR No Tag [2024-03-15 00:46:43] - 8
UnityEngine.Debug:LogError (object)
MultiplayerARPG.MonsterSpawnArea:SpawnInternal (MultiplayerARPG.BaseMonsterCharacterEntity,int) (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/MonsterSpawnArea.cs:85)
MultiplayerARPG.GameSpawnArea`1/<SpawnRoutine>d__15<MultiplayerARPG.BaseMonsterCharacterEntity>:MoveNext () (at C:/Users/Antho/My project/Assets/UnityAssetsa/UnityMultiplayerARPG/Core/Scripts/Gameplay/Area/GameSpawnArea.cs:106)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at C:/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)
`

**Comment by insthync** [comment]
It is not reached 9 ?

**Comment by anthonyselias** [comment]
> It is not reached 9 ?

It does, here is the complete debugs i've implemented and gotten. I still cant figure out why. I tried also trying with the prefab map that comes with the kit, and I get this error still.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/37a57bc5-64db-41df-9e22-106132afb076)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/274e73f9-9614-4e10-9a69-40295da992f9)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/134556081/0561ab04-c923-478d-acaf-4d6a0d2c87e6)

**Comment by insthync** [comment]
No useful info yet, attach all log files, and I will try to find the cause of the problem.
