### ISSUE TITLE
Bug when using active skills

### ISSUE THREAD

**Issue by gochaboy1** [suriyun-production/mmorpg-kit-docs#2429]
an active skill stops an auto attack!
for example, you started attacking a monster and activated an active skill, which, for example, deals additional damage!
But the problem is that after the drop, the attack is interrupted.

**Comment by insthync** [comment]
What is drop?

**Comment by gochaboy1** [comment]
> What is drop?

I meant that when we used an active skill during an auto attack, then after the active skill was used, the auto attack does not continue

**Comment by insthync** [comment]
At least please attach the video, I don't know how is it yet, because mine works as intended.

**Comment by gochaboy1** [comment]
> At least please attach the video, I don't know how is it yet, because mine works as intended.

can you join me at anydesk? I'll show you the problem

**Comment by insthync** [comment]
Fixed

**Comment by gochaboy1** [comment]
> Fixed

What do you have in mind? How to fix it?

**Comment by insthync** [comment]
Can't you just wait for an updating?

**Comment by gochaboy1** [comment]
> Can't you just wait for an updating?

I just don't understand what you mean, but okay! There is just one more error associated with this, I wanted to show you! But I'll explain it to you here. and I'll record a video!

The error lies in the animation of the active skill.
When you just attack another character or monster and use an active skill, there are no problems!
But if you take damage from a character or monster, this interrupts the animation of the active skill. This does not apply to other animations, only to the animation of the active skill.

**Comment by gochaboy1** [comment]
Now I will record a video and attach it here
