### ISSUE TITLE
1.53b item dismantle

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#243]
With this, you still cannot dismantle other types of items. Only armor and weapons. 
* ![image](https://user-images.githubusercontent.com/47291794/75290396-4a374780-5831-11ea-8526-5b846f68c6d9.png)

In the previous version, if we dismantle a stack of 99 items, we get resources for only 1 item. Not over 99

**Comment by insthync** [comment]
Thank you, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.53c

**Comment by DimasjkTV** [comment]
> Fixed in 1.53c

Still not working for all item types

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/75604034-b0e48b80-5ae5-11ea-92b8-d58c3fe4b2bf.png)
![image](https://user-images.githubusercontent.com/47291794/75604036-ba6df380-5ae5-11ea-8683-7af81bcd37f5.png)

**Comment by insthync** [comment]
Oh, the problem occurring while can dismantle item by player turn on.

**Comment by insthync** [comment]
You can fix it by add 
```
            if (buttonDismantle)
                buttonDismantle.gameObject.SetActive(GameInstance.Singleton.canDismantleItemByPlayer && GameInstance.Singleton.dismantleFilter.Filter(ui.CharacterItem));
```

to ButtonsActivatorForUICharacterItem.cs → OnSetUnEquippableData() line 93.

**Comment by DimasjkTV** [comment]
about "In the previous version, if we dismantle a stack of 99 items, we get resources for only 1 item. Not over 99". This works with items but not with gold. Gold is still awarded for 1 item, not 99

**Comment by insthync** [comment]
Oh, thank you, I will fix it.
