### ISSUE TITLE
[BUG] Sheathing Off-hand not playing

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2430]
Hi Suri, currently when you sheathe, it only plays the animation for the main-hand & won't play off-hand sheathe animation. Not sure if this is a bug or intentional. Please close if not a bug, but thought I'd post just in case.

Try:
- Left Arm (Off-hand) Mask
- Right Arm (Main hand) Mask

Then can play both animations at the same time if both a main hand and off-hand item are equipped.

**Comment by LordPhrozen** [comment]
I think I've come across this as well, was on my list to retest, but if you're seeing it too, its likely a bug.

**Comment by insthync** [comment]
I will check it

**Comment by insthync** [comment]
May I see your masks?

**Comment by insthync** [comment]
About this one, it is actaully works as intended, but I will try to improve it.

**Comment by BJPickles** [comment]
Ah okay might be my setup then, I'm just grabbing the masks now & I'll make a video as well to show how I'm using it. Just bare with me as it takes a little while to open the project (as you know 😆)

**Comment by insthync** [comment]
I mean that to play only one sheath animation (one hand) is works as intended, I will try to make it able to play 2

**Comment by BJPickles** [comment]
> I mean that to play only one sheath animation (one hand) is works as intended, I will try to make it able to play 2

Ah I see, thank you for doing that.

Here are the layer masks for left arm and right arm.
[LayerMasks.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/14977839/LayerMasks.zip)

![Unity_BZHkuFF0rs](https://github.com/suriyun-production/mmorpg-kit-docs/assets/48354382/574ce00a-a2f1-4746-ab64-15a4dadb4d6d)

I've assigned these masks in the default animations list on my character.
![Unity_Gso9HQrPPQ](https://github.com/suriyun-production/mmorpg-kit-docs/assets/48354382/88377060-2a54-409c-872a-94e8f9b9c714)

**Comment by insthync** [comment]
Done
