### ISSUE TITLE
equipment entity

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2432]
I saw that there is the equipment entity script where you can change the amesh and equipment materials, it would also be good to have the option either in the equipment entity, or the refinement item to change the item's icon, because if you change the mesh based on the level of the item, but the item icon still has the old appearance.

**Comment by insthync** [comment]
Not accept, if you want to do it, you can add settings to `BaseItem` and create UI component and set icon by item's level, that is it.
