### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by bloodfor1** [suriyun-production/mmorpg-kit-docs#2433]
Hello, I can't connect to Discord, it says the invitation is invalid. DC: hunturk.

**Comment by darkkriteus** [comment]
> Hello, I can't connect to Discord, it says the invitation is invalid. DC: hunturk.

https://discord.gg/Jz8vqdCB8e

**Comment by bloodfor1** [comment]
I can't connect to it either. When I ask to join, it doesn't accept me.
Most likely someone kicked me out years ago. I want to be accepted again.
