### ISSUE TITLE
Errors when switching platform to build for ANDROID

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2434]
When switching platform, even in fresh kit project using unity 2022.3.20f1 those 2 errors are triggered:

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Src\Database\DatabaseNetworkManager.cs(99,23): error CS0103: The name 'UniTask' does not exist in the current context

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Src\Database\DatabaseNetworkManager.cs(105,13): error CS0103: The name 'Application' does not exist in the current context

Seems like this is a problem with the DEFINES

**Comment by insthync** [comment]
Fixed: https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMOSource/commit/97595d022289b5f3839bae8e0b0a45f189a869c2
