### ISSUE TITLE
FPS Shooter

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#2435]
Hi ! 

I found that on your youtube channel : 

https://www.youtube.com/watch?v=3FYCXoK-6Ds 

Is it still aviable ? And do you plan to add an real shooter controller with AIM system / scope ? 

Thanks

**Comment by insthync** [comment]
It is included in the kit (try shooter demo), not sure how is your aim system/scope, if it is an ads then I don't have plan yet.
