### ISSUE TITLE
Problem with root motions with certain states of player

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2437]
The problem is the following when the character is in the idle state normally and you use a skill with root motion, this desynchronization passes or fails, here is a video of what happens:https://imgur.com/RezmQTl

SOLUTION:But this does not happen when the character is running and I use the skill with root motion, that is, the solution is in the lines of code when the character is moving and use them for the idle and crounch state which also happens this desynchronization

**Comment by insthync** [comment]
Did you try to turn these on?

![Screenshot_31](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/8f8da872-8abc-4bb4-9053-e246061e7f2b)

**Comment by Niinra** [comment]
If that's how I use it, I'll try activating the skip movement validation

**Comment by Niinra** [comment]
Ok activate that skip movement validation and it still happens, but I think that to reflect the change I have to build my server to check

**Comment by Niinra** [comment]
I will be building my server to see if this problem persists with the skip movement validation and I will notify you, this problem does not happen when you are running it's very strange

**Comment by insthync** [comment]
?

**Comment by Niinra** [comment]
Sorry for the delay, @insthync , but it seems that if the skip movement validation fixes this problem, I'm trying it from my server compilation uploaded to digital ocean and it's going very well 
https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/3a43a839-21d8-4ef7-be6d-139c49a174e7
