### ISSUE TITLE
IAP Issues

### ISSUE THREAD

**Issue by suitechsoftware** [suriyun-production/mmorpg-kit-docs#2438]
We followed all the steps regarding IAPs, but we are having issues. I'm sending our settings

![image (22)](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/2d58a7e5-bef1-493a-b60a-6a7664b8c186)
![image (24)](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/4b690d6e-1ff0-4fd8-871b-c59be22050a9)
![image (25)](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/2006a915-55f2-4fd7-a706-2892551fc9dc)

**Comment by insthync** [comment]
Try change platform to Android/iOS it may shows the product ID

**Comment by suitechsoftware** [comment]
![image (26)](https://github.com/suriyun-production/mmorpg-kit-docs/assets/106386940/7da3eb18-9071-488a-8b8b-6d3207bcb9dc)

**Comment by suitechsoftware** [comment]
@insthync

**Comment by suitechsoftware** [comment]
@insthync

**Comment by insthync** [comment]
Don't have to tag me, I saw it.

**Comment by suitechsoftware** [comment]
We upgraded our Unity version but there is no any progress on this issue.

**Comment by insthync** [comment]
As I try, It has no issues, may I try on your device by using AnyDesk?

**Comment by suitechsoftware** [comment]
Of course you can, is that possible to get your contact telegram or discord etc.?

**Comment by insthync** [comment]
Send the anydesk info to my email ittipon.bay@gmail.com

**Comment by insthync** [comment]
Nothing have to be fixed, just have to update to a new version.
