### ISSUE TITLE
MMO build is not working with Setup for MMO Build

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2439]
The MMO build is not working after choose Setup for MMO Build. This is failing even in a plain demo version, and also after update Unity it is still happening.

Here bellow is the information in the console:

```
Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Src\Database\DatabaseNetworkManager.cs(99,23): error CS0103: The name 'UniTask' does not exist in the current context
Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Src\Database\DatabaseNetworkManager.cs(105,13): error CS0103: The name 'Application' does not exist in the current context
```

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/93fbb8f2-635d-457e-9d44-2fa00892f262)

Erros:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/47fad5bd-5711-4375-b4af-4f44d674f358)

**Comment by Niinra** [comment]
Reviewing the DatabaseNetworkManager script I removed the use of the unity library and made the instances directly and it seems to fix the problem And I let me do the coopilation for the clients my change is here:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/2d896585-2873-4e50-9b30-9ff451004ecc)

**Comment by insthync** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMOSource/commit/97595d022289b5f3839bae8e0b0a45f189a869c2

**Comment by Niinra** [comment]
Oh thanks suri
