### ISSUE TITLE
Item Refine

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#244]
are we supposed to manually turn on if items can be refined?
Before if the item had an Itemrefine info attach.. aka not null.. u would see the Refine button appear.
The script ButtonsActivatorForUICharacterItem has nothing turning the bool true or false..
Checked this bool "canRefineItemByOwnerCharacter" it is never used outside of this script..
and in this script it never has its value changed..

its always what u put it manually..meaning even items that cant be refined.. will show refine option.. and when clicked.. it does nothing..
![unknown](https://user-images.githubusercontent.com/7702658/75298515-ff1e3400-5832-11ea-8d16-457bb0dac1ea.png)
![unknown2](https://user-images.githubusercontent.com/7702658/75298517-01808e00-5833-11ea-85d6-228c1c9c6a7b.png)

was this intended? or just unfinished?

**Comment by Callepo** [comment]
Figured the reason behind it..
If its toggled off.. u can only refine and dismantle through npc...
If u toggle it on.. players can do it anywhere without needing npc.. 
which is nice if u want to have like blacksmith only one who can refine ur items...

But the location for the toggle is not handy...
It would be better imo in game instance under the dismantle filter list

**Comment by Callepo** [comment]
Like this maybe
![unknown3](https://user-images.githubusercontent.com/7702658/75303172-3ba45c80-5840-11ea-9736-4dc04972e1af.png)
![Capture](https://user-images.githubusercontent.com/7702658/75303176-3e9f4d00-5840-11ea-83c2-c37f60429240.PNG)

**Comment by insthync** [comment]
Yes, you're right, I will move the config to GameInstance :)

**Comment by Callepo** [comment]
Ty, I'm sure people would appreciate it.. cuase it was confusing at first.. people thought item refine was bugged

**Comment by insthync** [comment]
Fixed in 1.53c
