### ISSUE TITLE
The duel counter is not removed at the end of the duel

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2440]
When the players do not kill each other and the counter reaches 0 it is not removed, even sometimes when you win it is not removed it passes
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/b5cd5233-0e3b-47d4-9e9f-2588cb83b629)

**Comment by insthync** [comment]
Fixed

![Screenshot_36](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/8a98c9b4-1dbc-4daf-b9e3-2e6eedb9b6bd)
