### ISSUE TITLE
[Feature Suggestion] - Hide Objects Between The Camera and Player

### ISSUE THREAD

**Issue by GeoffCee** [suriyun-production/mmorpg-kit-docs#2442]
Currently, the camera will move to avoid obstacles. It would be good to have an option to hide the obstacle instead. So for example roofs can hide when the player enters the building in a top-down view. Would need to be compatible with standard and custom materials/shaders and usable on any game object including child prefabs. This is for the player in local view only, no need to send it via the network transport.

**Comment by insthync** [comment]
Don't accept because it is pretty specific up to shader setup, you have to implement it by yourself.

**Comment by GeoffCee** [comment]
Yeah, that is the problem I was hoping could be avoided. The shader is what would render things invisible and to implement this, the shaders need to be changed on effected objects.
