### ISSUE TITLE
Teleportation problem with jumping and desynchronization

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2443]
Well basically I have a vanila project the only thing I have added has been a model I made it using character controller and use your controller for cinemachine , nothing else and at the time of jumping in MMO this problem happens: https://imgur.com/KBsSDoa

basically still vanila the only thing I changed was the gravity and activated not to change the speed in the air.
my configuration:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/820a6168-5990-4316-b870-b44473babd55)

**Comment by insthync** [comment]
Can I just delete the do not change velocity while air borne option? ;)

**Comment by Niinra** [comment]
> Can I just delete the do not change velocity while air borne option? ;)

I can only imagine how annoying it can be this in general but only you understand how annoying it is, to be honest with you if the issue is hard to fix or brings more problems than a solution, you can just delete it. I will always support your decisions

**Comment by insthync** [comment]
As I try, it has no problem

**Comment by insthync** [comment]
https://youtu.be/H4cMwMXjDxQ

**Comment by Niinra** [comment]
> As I try, it has no problem


What do you think is my configuration?, the only thing I use differently is the gravity, I will check using the default one and comparing the jump animations of the asset with the one I use

**Comment by Niinra** [comment]
https://imgur.com/hmX8plF It keeps happening, I have no idea what could be happening. If you want, I'll give you the project

**Comment by insthync** [comment]
Okay, send it to me

**Comment by Niinra** [comment]
> Okay, send it to me

Ready, I sent it to you
