### ISSUE TITLE
WeaponAbility not working in Kit versions above 1.85c3_2023

### ISSUE THREAD

**Issue by timspurgeon** [suriyun-production/mmorpg-kit-docs#2445]
WeaponAbility not working in Kit versions above 1.85c3_2023.

I'm using Unity 2022.3.21 and installed the latest kit 187 and zoom for sniper doesn't work. When you right click the weapon fires. I went back to 1.85c3_2023 and Zoom works as expected. I then installed each package up in new projects and no Zoom only fire. I tried to see the issue and not be a bother. Ill stay on 1.85c3 for now.

Thank you

**Comment by insthync** [comment]
Fixed

**Comment by timspurgeon** [comment]
Is there somewhere I can get the updated scripts or just when a new update is put on store.
Thank you for the quick resolution!!
