### ISSUE TITLE
Crafting queue from and to storage buildingentity

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2446]
Hi,
in the previous version i have written my own workbench type which is a storage buildingtype with crafting queue.
So basically it takes the items from the storage buildingentity and craft in a public queue then the crafted item is stored in the storage.

Since the latest version i upgraded too witht the new activatable entity revamp and ui revamp i have troubles to make my old script work again.
Suriyun could you please help me by letting me know where does the code now managed the craft item source and destination with the queued craft items and/or queued workbench ?

I don't know what i'm missing, i have no errors but i'm pretty sure i must haved missed  some of the code i had to hardcode due to the old version limits on dev ext.

Thanks

**Comment by insthync** [comment]
Update from which version to which version?

Don't you use version controls system?, can't you compare codes changes?

**Comment by sawcisson** [comment]
i did compared code changes and everything is similar , it seems that something is missing or was skipped/forgotten from our side. We work with plastic SCM.
We are on the latest version now.

Could you just direct me to the functions/files that decide of where a crafting formula is taking it's resources and where it deposit the crafted item.

I might have missed something on that side.
For now we can open the new QueudStorageWorkbench entity we created and we have access to the storage, crafting formula, filtering system, etc... but the formulas work just as the standard queuedworkbench and fo from player inventory to player inventory.

We would just need to change the player inventory to the buildingentity storage inventory.

Thanks

**Comment by sawcisson** [comment]
Any direction to which files i should look into ?

**Comment by insthync** [comment]
I don't know, may I see your component?

**Comment by sawcisson** [comment]
Thanks, email is sent to you with 3 videos, let me know if you need my c# scripts or else.

**Comment by insthync** [comment]
I've told you in the email that I want to see your script, but you are not answered, so I will close this.
