### ISSUE TITLE
Shooter controller animations Bug

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2448]
When Sprint, it executes the normal forward animation, but when Sprint backwards, diagonally or sideways, the animation does not execute, NOTE: I am using Shooter controller Combat mode

**Comment by insthync** [comment]
It might be fixed, but I want to see how is it, so.. please upload the video

**Comment by darkkriteus** [comment]
> When Sprint, it executes the normal forward animation, but when Sprint backwards, diagonally or sideways, the animation does not execute, NOTE: I am using Shooter controller Combat mode

This is because you are using combat mode, where the character has direction to the sides and back, it changes to Adventure mode where you run freely
