### ISSUE TITLE
when you disconnect with low health and reconnect on the player canvas it does not refresh

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2450]
What the title says is basically the problem, here's an image:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/bf0f1b1a-6989-47e7-a9b5-88937ae2ea38)

note: when they do get damage to you again now it refreshes

**Comment by Eniotnacram** [comment]
Have you tested in fresh kit? I never seen that problem.

**Comment by Niinra** [comment]
> Have you tested in fresh kit? I never seen that problem.

The default asset has hp restoration so if this is active you won't notice it because it refreshes hp
