### ISSUE TITLE
(Integration) UIGageValue

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2451]
Hi, I modified the UIGageValue to add the option to make the gages smooth. I added a bool (false by default) so it doesnt break customers projects. Simple bool to activate it, and a float to set the smoothness speed. The user need to make sure to set the "Update UI Repeat Rate" lower to make the transition smooth.

There is the modified code:
[UIGageValue.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/14967999/UIGageValue.zip)

Note that I tried to make a merge request but it seems that I dont have access to the core repo anymore.

**Comment by insthync** [comment]
Thank you, I will check it later

**Comment by Eniotnacram** [comment]
Hello,

For some reason it's not working properly on the Monster Character UI, it works perfectly fine for the Gameplay UI. Maybe some sort of entity sync problem, I'm not sure. The "Update UI Repeat Rate" is set to 0.05 on them. I will investigate

**Comment by insthync** [comment]
Try my commit: feat: smooth gage updating

**Comment by Eniotnacram** [comment]
Nice! I was wondering about using coroutines! Going to bed now, I will test tomorow!

Thanks suri

**Comment by Eniotnacram** [comment]
Hello,

A little error was triggering "NullReferenceException"

Line 117: (!Mathf.Approximately(imageGage.fillAmount, targetRate)) (It should be sliderGage.value instead of imageGage.fillAmount)

With that simple fix, it works PERFECTLY!, thank you.
