### ISSUE TITLE
[Small paid request]Skill Damage

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2453]
we discused this already. also in discord we had that many times. its a small change with a big improvement which really laks in kit atm when work with skills. and its something everyone can use

example. You have 2 kind of weapons 

Weapon A -> 10 Slashing Damage
Weapon B -> 10 Pircing Damage

then you have 1 skill, lets say Power Attack. This skill can be used with both weapons. and the skill should do additional damage to the weapon damage. like +150% Weapon damage. So here comes to problem. you have that option already but you need to assign a damage element. which will override the damage element from weapon. lets say we assign Slashing Damage to the Skill then the damage output would be

Weapon A -> 15 Slashing Damage
Weapon B -> 15 Slashing Damage (instead of Pircing)

https://gyazo.com/371c9b79f89ec68942cdb311bbf538d5

even in kits demo, you use it without damage element. which uses the default damage element. but the problem with this is you can not make a skill which be used for diffrent kind of weapon damage.

i think a simple damage modificator would be used or if you keep the damage element empty in the weapon damage infliction it just use the damage element from weapon.

**Comment by insthync** [comment]
Can you just try to implement it and make a pull request ?

**Comment by moepi2k** [comment]
jup i will do

**Comment by moepi2k** [comment]
okey, it seems its not a simple task :P all the damage multiplier needs a damage element. sadly. i need to rethink then how i should setup my skills.
