### ISSUE TITLE
[Paid Request] "PlayerActivityComponent"

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2454]
Hi, I would like to request additionnal scripts for my project.

My goal is to make my playerCharacter automatically fight monsters, loot etc. (I already achieved that using a custom controller). Sadly, for my project, using the controller wont work, because I want the playerCharacter to keep existing in map servers, even if the player disconnects. So that means, I would like my playerCharacter to use the "same" logic as the monsters to fight, walk, wander, etc. 

I tried duplicating the MonsterActivityComponent logic and made one for my playerCharacter, (and made partials of PlayerCharacter and BasePlayerCharacterEntity) but on play mode, I receive some errors due to the logic of the weapons, skills, not the same as the monsters. For my knowledge, it is very difficult for me to make that work.

I'm pretty sure you can do it relatively fast as it is pretty much a copy paste (with some modifications). I could even send you my existing scripts if it can speed up the process of doing it.

But in other words, I would need a "PlayerActivityComponent" to control the wandering, fighting logic of my playerCharacterEntity.

(Note that I've also made a custom CharacterController and removed all the logic for moving and attacking as it should be done using the "PlayerActivityComponent" only.

I can give you good money for this, I dont want you to feel like you are wasting your time, so even if it takes you only 2 hours I can give you 100$ usd for this.

**Comment by Eniotnacram** [comment]
Will try to do it on my end,

**Comment by insthync** [comment]
Nice, I know you can do it! :)
