### ISSUE TITLE
[Bug] Do Not Destroy When Disconnect (Lite Net Lib Identity)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2455]
It looks like the Do Not Destroy When Disconnect bool on the Lite Net Lib Identity is not working. (On player character).

When I enable the bool, it doesnt keep my character in map server on disconnection.

**Comment by insthync** [comment]
It may be changed by my codes, did you check it?

**Comment by Eniotnacram** [comment]
I have not, I will check it after work.

**Comment by Eniotnacram** [comment]
Map Server disconnection logic is not using that bool at all. I will try to implement it with calle's help.

**Comment by insthync** [comment]
You are wrong, the disconnect logic uses it to not destroy the character immediately when the player leaves.

It works as intended, read codes in `MapNetworkManager` -> `OnPeerDisconnected` you will see the `NetworkDestroy` is being used, which means it is forced to be destroyed.

**Comment by Eniotnacram** [comment]
You are right, sorry for this, its implemented, I simply need to modify it for my use case.

Thanks!
