### ISSUE TITLE
Problem with projectiles and area damage cast

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2456]
Ok the following happens when you throw a projectile and press an area damage cast skill the projectile goes sideways 100% sample gif:
![GIF 23-04-2024 0-08-32](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/9b8a828b-bdb1-4429-af91-030e498c86ee)

**Comment by insthync** [comment]
Using 2 skills?

**Comment by Niinra** [comment]
> ¿Usas 2 habilidades?

Not only do I just press the damage cast area and this happens

**Comment by insthync** [comment]
What is damage cast?

**Comment by Niinra** [comment]
> What is damage cast?

Sorry is the area damage entity

**Comment by insthync** [comment]
I don't get what are you doing, do you attack then use skill?

**Comment by Niinra** [comment]
> I don't get what are you doing, do you attack then use skill?

The problem is reproduced when you press a projectile skill and then continuously press an area skill but do not press to cast the skill, if you do not keep the area casting active and this happens I recorded a gif with the default asset if you still do not understand me I show you my screen with some application for this, example gif:https://imgur.com/yHTfxnR

**Comment by insthync** [comment]
Okay, I will try it.

**Comment by Niinra** [comment]
> Okay, I will try it.

:3 okay

**Comment by insthync** [comment]
Fixed

![Uploading Screenshot 2567-04-24 at 03.39.42.png…]()

**Comment by insthync** [comment]
<img width="1067" alt="Screenshot 2567-04-24 at 03 39 42" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/d6ae3a14-e503-49b7-94f1-7a87abbe06ab">

**Comment by Niinra** [comment]
now without activating an area skill all the projectiles go sideways example:
![GIF 23-04-2024 17-52-39](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/1851815e-a1ed-44d0-8cb9-c193ba77b257)

**Comment by insthync** [comment]
How did you made changes?

**Comment by Niinra** [comment]
> How did you made changes?

delete these conditionals in the shootercontroller like in the photo you sent me

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/d51172dc-4972-403c-9f2c-38f6558a959b)

**Comment by insthync** [comment]
![Screenshot_20240424-075347996](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/2f8d435f-f3a4-4f8a-a152-8188938e6325)

**Comment by Niinra** [comment]
Ready fixed thanks suri I hadn't seen the keys properly 💯
