### ISSUE TITLE
On the mobile side, when I click the attack button, it will trigger both the attack and the move action.

### ISSUE THREAD

**Issue by 53957105** [suriyun-production/mmorpg-kit-docs#2457]
By clicking the attack button, the character automatically selects the target and moves towards it, but because another click on the ground is triggered, the character loses the target and moves towards the white mark

https://github.com/suriyun-production/mmorpg-kit-docs/assets/8380930/bc69a351-36e2-47d4-9620-93c450bd55c1

**Comment by insthync** [comment]
It might have to attach a component to tells that it is blocked UI, I cannot remember it's name, please wait, I will check it

**Comment by Eniotnacram** [comment]
> By clicking the attack button, the character automatically selects the target and moves towards it, but because another click on the ground is triggered, the character loses the target and moves towards the white mark
> 
>  QQ.20240425160339.mp4

It's not happening in default kit is it? Im pretty sure the block UI is setup in UIGameplay and it prevent this from happening by default.
