### ISSUE TITLE
Pistol shot pass enemy

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#246]
Hey, if you for example use pistol and mobs are in one line - particle dmg all of them. I guess its unintended feature :D

**Comment by Koodetat** [comment]
I confirm that, it happens with the raycast damage system.

**Comment by insthync** [comment]
I intently made it able to pierce through entities, in the next version I will add `pierceThroughEntities` config to `damagInfo` then when it set to 0, it won't pierce through entities.

**Comment by insthync** [comment]
Fixed in 1.53c
