### ISSUE TITLE
[Request] Immediate reward item instead of looting.

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2460]
Hello,

It would be very nice to have the option to reward the players immediately with the items when killing monsters instead of either looting the corpse or looting the item on the floor.

So using the Immediate reward, no ItemDropEntity would be spawned when monsters are killed.

**Comment by insthync** [comment]
Okay, I will add the option for this one

**Comment by Eniotnacram** [comment]
Thank you a lot  🙏🏼

**Comment by insthync** [comment]
Added to 1.88b
