### ISSUE TITLE
Errors in 1.88

### ISSUE THREAD

**Issue by MagicHope** [suriyun-production/mmorpg-kit-docs#2461]
Use completely blank project, 2022.3.17 LTS 

1. Install dependencies 
Input System 
Newtonsoft Json 
Addressable 

2. Import MMORPG KIT 1.88 

3. Modified the input method 

4, play DemoSurvival/Scenes / 00 init_survival 

5, Single-player mode, create a character, start

6, get 6 errors, and display result “No cameras rendering” .

![errors](https://github.com/suriyun-production/mmorpg-kit-docs/assets/108127365/e5702c57-4835-417e-94d8-8e424ce7dec5)

**Comment by insthync** [comment]
Try make those prefab which it is telling in log messages to be addressable (by simply click on addressable checkbox)

**Comment by MagicHope** [comment]
Thank you. It's settled.
