### ISSUE TITLE
Black screen on lan build/ single player after adding a new item/ map info into the database.

### ISSUE THREAD

**Issue by Nyogosz** [suriyun-production/mmorpg-kit-docs#2462]
I recently added a new map and a new item into the game and every time I click play/ host/ make a new character I get a black screen, and can't click or do anything.
But I can still hear the audio source music present in the scene.

**Comment by insthync** [comment]
Any error messages?

**Comment by Nyogosz** [comment]
> Any error messages?
Not in the build version. I can't test it in the editor because of some other errors.
![Untitled](https://github.com/suriyun-production/mmorpg-kit-docs/assets/111643557/d8637c95-cd7a-4ede-bb4e-98dc2dba0842)

**Comment by insthync** [comment]
It might be easy to fix, but I am not in front of my PC, just do what's the log messages telling, send me your Anydesk info to my email ittipon.bay@gmail.com

**Comment by Nyogosz** [comment]
> It might be easy to fix, but I am not in front of my PC, just do what's the log messages telling, send me your Anydesk info to my email [ittipon.bay@gmail.com](mailto:ittipon.bay@gmail.com)

Sent you an email.

**Comment by Nyogosz** [comment]
Fixed, it was the cinemachine controller. Switched to the old one and now it works.
