### ISSUE TITLE
Two bugs when I try testing the game in the editor on the new version.

### ISSUE THREAD

**Issue by Nyogosz** [suriyun-production/mmorpg-kit-docs#2466]
ERROR NetworkManager(LanRpgNetworkManager) [2024-05-07 15:08:29] - Cannot start server at port: 7770.
UnityEngine.Debug:LogError (object)
ZLogger.Providers.UnityDebugLogProcessor:Post (ZLogger.IZLoggerEntry) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/Unity/ZLoggerUnityLoggerProvider.cs:71)
ZLogger.AsyncProcessZLogger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/AsyncProcessZLogger.cs:36)
Microsoft.Extensions.Logging.Logger:<Log>g__LoggerLog|12_0<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.ILogger,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>,System.Collections.Generic.List`1<System.Exception>&,Microsoft.Extensions.Logging.FormattedLogValues&)
Microsoft.Extensions.Logging.Logger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>)
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,System.Exception,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:LogError (Microsoft.Extensions.Logging.ILogger,string,object[])
LiteNetLibManager.Logging:LogError (string,string,object[]) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Logging/Logging.cs:45)
LiteNetLibManager.LiteNetLibManager:StartServer () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:199)
MultiplayerARPG.BaseGameNetworkManager:StartServer () (at Assets/UnityMultiplayerARPG/Core/Scripts/Networking/BaseGameNetworkManager.cs:271)
LiteNetLibManager.LiteNetLibManager:StartHost (bool) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:245)
MultiplayerARPG.LanRpgNetworkManager:StartGame () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:63)
MultiplayerARPG.UICharacterList:OnClickStart () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/UI/UICharacterList.cs:266)
UnityEngine.EventSystems.EventSystem:Update () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)

Is the first one and the second one is:

ERROR No Tag [2024-05-07 15:08:29] - Cannot start discovery server
UnityEngine.Debug:LogError (object)
ZLogger.Providers.UnityDebugLogProcessor:Post (ZLogger.IZLoggerEntry) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/Unity/ZLoggerUnityLoggerProvider.cs:71)
ZLogger.AsyncProcessZLogger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/AsyncProcessZLogger.cs:36)
Microsoft.Extensions.Logging.Logger:<Log>g__LoggerLog|12_0<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.ILogger,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>,System.Collections.Generic.List`1<System.Exception>&,Microsoft.Extensions.Logging.FormattedLogValues&)
Microsoft.Extensions.Logging.Logger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>)
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,System.Exception,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:LogError (Microsoft.Extensions.Logging.ILogger,string,object[])
LiteNetLibManager.Logging:LogError (string,object[]) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Logging/Logging.cs:117)
LiteNetLibManager.LiteNetLibDiscovery:StartServer () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Components/LiteNetLibDiscovery.cs:61)
MultiplayerARPG.LanRpgNetworkManager:StartGame () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:74)
MultiplayerARPG.UICharacterList:OnClickStart () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/UI/UICharacterList.cs:266)
UnityEngine.EventSystems.EventSystem:Update () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)

**Comment by Nyogosz** [comment]
Also these two:
NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.PlayerCharacterController.Desetup (MultiplayerARPG.BasePlayerCharacterEntity characterEntity) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Default/PlayerCharacterController.cs:212)
MultiplayerARPG.BasePlayerCharacterController.set_PlayingCharacterEntity (MultiplayerARPG.BasePlayerCharacterEntity value) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/BasePlayerCharacterController.cs:48)
MultiplayerARPG.BasePlayerCharacterEntity.EntityOnSetOwnerClient () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity_NetworkData.cs:511)
MultiplayerARPG.BaseGameEntity.OnSetOwnerClient (System.Boolean isOwnerClient) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/BaseGameEntity.cs:282)
MultiplayerARPG.BasePlayerCharacterEntity.OnSetOwnerClient (System.Boolean isOwnerClient) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity.cs:118)
LiteNetLibManager.LiteNetLibIdentity.OnSetOwnerClient (System.Boolean isOwnerClient) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibIdentity.cs:539)
LiteNetLibManager.LiteNetLibAssets.NetworkSpawn (LiteNetLibManager.LiteNetLibIdentity identity, System.UInt32 objectId, System.Int64 connectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibAssets.cs:408)
MultiplayerARPG.LanRpgNetworkManager.SpawnPlayerCharacter (System.Int64 connectionId, MultiplayerARPG.PlayerCharacterData playerCharacterData, System.Collections.Generic.List`1[T] summonBuffs) (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:258)
MultiplayerARPG.LanRpgNetworkManager.OnServerUpdate (LiteNetLibManager.LogicUpdater updater) (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:193)
LiteNetLibManager.LogicUpdater.OnAction () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Utils/LogicUpdater.cs:84)
LiteNetLibManager.LogicUpdater.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Utils/LogicUpdater.cs:107)
LiteNetLibManager.LiteNetLibManager.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:144)
MultiplayerARPG.BaseGameNetworkManager.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/Networking/BaseGameNetworkManager.cs:131)
MultiplayerARPG.LanRpgNetworkManager.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:171)

And:

NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.CharacterPitchIK.LateUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/CharacterPitchIK.cs:82)

**Comment by insthync** [comment]
If you already start a server, then you cannot start it again

**Comment by insthync** [comment]
You may try attach a video to show how can this is occurring

**Comment by Nyogosz** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/111643557/5b7c6a40-7f73-406d-b7d4-72c9579b14fc

**Comment by insthync** [comment]
Try to look at the codes see what is null, and then setup it.
