### ISSUE TITLE
Hotkey Not Saving MMO Build (1.88d)

### ISSUE THREAD

**Issue by lunidel** [suriyun-production/mmorpg-kit-docs#2467]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/21c11c6e-f089-4941-a1e5-b905a145f9a7

Hotkey on SQL DB is saved.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/0fa76d69-a36f-4957-9205-c4b8ac595bcb)

**Comment by insthync** [comment]
It make me confused when you told me DB is saved, you should told me relate ID is missing

**Comment by CLAXES** [comment]
This problem also occurs in version 1.88e. It happens in MMO, single player does not have this problem

**Comment by insthync** [comment]
@CLAXES Don't have to repeat it, I know it, and that is why this post is not closed yet.

**Comment by insthync** [comment]
Try this changes https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManagerSource/commit/8d5f922a25a312d44bad44c3202d0c0a4ac4c7d6

**Comment by CLAXES** [comment]
> Try this changes [suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManagerSource@8d5f922](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManagerSource/commit/8d5f922a25a312d44bad44c3202d0c0a4ac4c7d6)

Yes this worked no problem now thanks
