### ISSUE TITLE
Movement Bug when set to Movement Secure as Server Auth ( 1.88d )

### ISSUE THREAD

**Issue by lunidel** [suriyun-production/mmorpg-kit-docs#2468]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/4d15ca4b-3282-46c3-aeb4-39fda221bf56)

https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/e22db11b-6817-47d1-b71d-1714eb096771

**Comment by insthync** [comment]
Why RTT is minus?

**Comment by lunidel** [comment]
@insthync it seems to be related to 1.88d and might have been causing the movement problem 

I did a comparison with clean build using the same server host and these are the results:

1.88d Version MMO Build ( untouched )
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/24fd2c76-5fda-44d2-9738-bda7dceaed13)


1.86d Version MMO Build ( untouched )
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/43dfce98-2a28-4abc-abc7-55db9656c406)

**Comment by insthync** [comment]
Please make sure that you've update the kit properly, delete old codes before updating, rebuild server and re-test.
