### ISSUE TITLE
UI scales abnormally in play

### ISSUE THREAD

**Issue by MagicHope** [suriyun-production/mmorpg-kit-docs#2469]
About UI Scaling

The following are the initial Settings in Demo and have not been modified.
UISkillDialog size 200x250.
CanvasLoading is set to 800x600, so running at this resolution, I should get its original size 200x250, but instead I get another size 165*208(approximate size).
How can I get its original size 200x250?
![UISkillDialog](https://github.com/suriyun-production/mmorpg-kit-docs/assets/108127365/b1005ab6-f75d-49d6-a283-c765e1747500)
![UISkillDialog2](https://github.com/suriyun-production/mmorpg-kit-docs/assets/108127365/30f3ba79-24f9-4dfb-bc6f-2c34d130a6f0)

**Comment by insthync** [comment]
I really don't like to answer these kind of questions, it is  not relates to the kit and I am not intend to be a unity tutor, I am just selling an assets.

You must learn more about Unity UI, its canvas system. You may find the canvas component and try changes its settings to see the result.

**Comment by MagicHope** [comment]
There are multiple canvas prefabs, find them, and set them all to the same resolution, and the problem is solved.

The cause of this problem is that multiple Canvas uses two different resolutions.

As a UI novice, we may not find it at the beginning of making UI.

Thanks to the author for the hint, but really didn't find a solution anywhere. Because this is a result of lack of experience.
