### ISSUE TITLE
Projectile (Missile) has no gravitation

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#247]
the prefab BowDamageEntity has a rigidbody but the gravitation is not affected by the mass. projecitl always fly streigth forward

**Comment by Callepo** [comment]
would be nice feature yea

**Comment by Fallen01** [comment]
It would be great if it was optional or adjustable, but i agree its a good idea.

**Comment by moepi2k** [comment]
i will close this, have own solution
