### ISSUE TITLE
Instance Map termination problem

### ISSUE THREAD

**Issue by mhmmdciftciler** [suriyun-production/mmorpg-kit-docs#2471]
Even when there are no players in Instance Maps, Linux doesn't kill the process about instance map so the resources used are not given back to the operating system. Version 1.86f. I had this issiue with your native demo. Warp Portal Type => Enter Instance.
![Ekran görüntüsü 2024-05-16 233722](https://github.com/suriyun-production/mmorpg-kit-docs/assets/73231479/69e55ff9-7439-4d5d-9f5c-a6536d3a7866)
![Ekran görüntüsü 2024-05-16 233745](https://github.com/suriyun-production/mmorpg-kit-docs/assets/73231479/699d3f4f-43b6-497e-b77f-12af0cb2dfae)
![Ekran görüntüsü 2024-05-16 233813](https://github.com/suriyun-production/mmorpg-kit-docs/assets/73231479/e350c007-4fe0-4843-8c26-7904d59d6d09)
![Ekran görüntüsü 2024-05-17 003412](https://github.com/suriyun-production/mmorpg-kit-docs/assets/73231479/0b15655f-b998-4187-a3e9-cf14ce9f6842)

**Comment by mhmmdciftciler** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/73231479/f2e66419-5029-4b8e-924d-0b01f13708c2)
It was a nice solution in my case. It works for Instance Maps if it doesn't cause any other problems.

**Comment by insthync** [comment]
Hmm, seems like it would not, I will apply it

**Comment by insthync** [comment]
You should not do it, because it has to make sure that all data were saved before kill the process, look at `MMOServerInstance` -> `Application_wantsToQuit`,  and `MapNetworkManager` -> `ProceedBeforeQuit`

I am not sure about Unity process killing too, not sure that with Application.Quit(), the process will be killed properly or notl.
