### ISSUE TITLE
Trade bug

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2472]
Hello, when buying and selling, not the item I put, but the item to the left of it is deleted. the version I use is 1.86d

**Comment by insthync** [comment]
I don't understand it

**Comment by insthync** [comment]
You may try capture and upload the video

**Comment by insthync** [comment]
And I've fix trade bugs in previous version already, so I am not sure that it is the same issues or not

**Comment by CLAXES** [comment]
[video](https://youtu.be/B2nYSrmeLxQ)

**Comment by CLAXES** [comment]
is this problem fixed in the current version?

**Comment by CLAXES** [comment]
I think the problem may be due to the ExchangeDealingItemsAndGold function in PlayerCharacterDealingComponent.cs

**Comment by insthync** [comment]
Try this 2 months ago fix

<img width="1416" alt="Screenshot 2567-05-18 at 01 57 18" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/475ff469-40fb-4b75-814c-e9e458d4c418">

**Comment by insthync** [comment]
How is it?

**Comment by CLAXES** [comment]
I have not tried it yet, I will try it today and give information.

**Comment by CLAXES** [comment]
When I do as follows, it deletes the correct item, no problem thanks.

    if (nonEquipItem.id == dealingItem.id && nonEquipItem.amount >= dealingItem.amount)
