### ISSUE TITLE
Player shop like metin2

### ISSUE THREAD

**Issue by john5514** [suriyun-production/mmorpg-kit-docs#2473]
Hello there

is there a system where the user can stand on the map and open a market and sell their items? i saw it in other projects but i didn't see it in the mmorpg kit, what should i do for this? can you help me sir @insthync insthync

**Comment by insthync** [comment]
Did you try the vending system?

**Comment by john5514** [comment]
How can I try what exactly is the vending system?

**Comment by insthync** [comment]
The button is big enough, you should be able to find it in the demo. If you can't then it might be because you're using old version. So I want to ask for your invoice ID, if you don't have it then I won't support.
