### ISSUE TITLE
User id

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2474]
Hello, I'm developing a website for the kit, and I would like to ask a question, how is the user account ID generated?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/b8fd3140-b8d6-4861-8c48-9017ac0f1ac1)

**Comment by insthync** [comment]
Try find it in function named: `CreateUserLogin` from any classes which extended from `BaseDatabase`
