### ISSUE TITLE
Desynchronization problem

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2475]
There is a problem with player's position when you use a skill with root motion and you are idle, but when you are in motion, the position updates perfectly on all clients. Could it be that player's position does not update after use a skill in state idle with root motion? 

Example to idle position
https://imgur.com/UGYw92x

Example to working perfectly while you run
https://imgur.com/YzuCdhV

**Comment by insthync** [comment]
The root motion again? I wanna thrown my phone always after I saw this word.

**Comment by insthync** [comment]
Is that a dash skill?

**Comment by insthync** [comment]
It is no one paid for that requested dash feature yet, why do I should fix it?

**Comment by Niinra** [comment]
Unfortunately, it is the root motion. Everything works excellent with it, but when you use a skill with root motion while you are idle, the behavior shown in the first gif occurs, this is not rush take your time 🙉

**Comment by insthync** [comment]
Is it a dash skill?

**Comment by Niinra** [comment]
is this a skill that uses a root motion animation to dash
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/abb1b6ff-01e6-4c23-bd04-239538e403d8)

**Comment by insthync** [comment]
Send me your project

**Comment by insthync** [comment]
Or add me as your project's collaborator

**Comment by Niinra** [comment]
If you are too right taking years
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/3362ee36-06dd-4b9d-b796-b4e5be8dadeb)
I'll add you right away

**Comment by Niinra** [comment]
Done, all development is in the developer branch🙈

**Comment by insthync** [comment]
Okay, whats are those skills, including from this one https://github.com/suriyun-production/mmorpg-kit-docs/issues/2443

**Comment by insthync** [comment]
Okay, I can find them

**Comment by AlejandroJB** [comment]
Hello Suriyun,

I hope you're doing well, those two skills are in:
Gaiden > Prefab > Gameplay > TechniquesEntities > General > Dash
Gaiden > Prefab > Gameplay > TechniquesEntities > DevelopingJutsus > WaterWave

**Comment by moepi2k** [comment]
Is this laatest version? Im on 187 and rootmotion with skillls is fine. In idle and also with movement. Just wondering if somethi g changed in 188 because i wanted to update my project soon.

**Comment by Niinra** [comment]
> Is this laatest version? Im on 187 and rootmotion with skillls is fine. In idle and also with movement. Just wondering if somethi g changed in 188 because i wanted to update my project soon.

I am on version 1.86f but I think it is 1.87. I am also preparing the project for the latest version and I have those desynchronization problems with root motion but it is only in the example I sent

**Comment by moepi2k** [comment]
then i think its an issue on ur side. because 187 is pretty good for rootmotion. i dont have that issue like in ur video

**Comment by Niinra** [comment]
> then i think its an issue on ur side. because 187 is pretty good for rootmotion. i dont have that issue like in ur video

Ehm the truth is that not even a vanilla project happens to me

**Comment by moepi2k** [comment]
in the demo is no rootmotion setting up, maybe ur settings wrong then? because mine works fine

**Comment by moepi2k** [comment]
sp and mmo. but i only use rootmotion for some attacks. rootmotion sometimes is a bit out of sync, but just a littlebit, cant even notice it

**Comment by insthync** [comment]
@Niinra Try the commit in brance `dev--fix-root-motion-dash-skill`

**Comment by Niinra** [comment]
> @Niinra Try the commit in branch `dev--fix-root-motion-dash-skill`

right away master x)

**Comment by Niinra** [comment]
@insthync If it seems to work very well, I can close it anyway if something strange happens again, I will notify you thank you very much
