### ISSUE TITLE
Server ram usage

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2476]
hello, when I first turn on the server, it uses 45% ram, after 1 day it becomes 80% or so, when it stops a little more, the server stops the programs due to lack of memory due to excessive ram usage. Is this problem a general problem or is it only me.

**Comment by insthync** [comment]
Annoying.

Don't you see the previous post?, don't you see what I have done to fix it?

Why don't try the latest version?
