### ISSUE TITLE
attack while moving

### ISSUE THREAD

**Issue by Gamadorium** [suriyun-production/mmorpg-kit-docs#2477]
In the mobile version, when we press the attack button for straight hits while the character is moving, he does not attack. The character has to stand still to attack. What settings do we need to make to make straight hits while walking for some combos and a better attack flow?

**Comment by insthync** [comment]
I am not sure how is it, you may try change weapon's fire type to automatic, and test it, and see if it is as you wish or not.

**Comment by Gamadorium** [comment]
Actually, I think there is something that prevents this because there is no such problem in the PC version. You can attack while the character is walking and the character performs the attack, but this is not possible on mobile. I think there is something that prevents us from pressing both the walk and attack buttons at the same time.

**Comment by insthync** [comment]
I saw many Metin 2 videos, seems like it is a popular game, but I still don't know what is a problem.

**Comment by Gamadorium** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/3700ce7b-ba1c-4363-8af3-fe6658384f3e

As you can see in the video, when we want to attack while the character is moving, there is something that prevents walking, what I mean is that while the character is attacking, he moves forward after each combo, as in the previous video, but I think there is something preventing this.

**Comment by insthync** [comment]
How about move speed rate while attacking setting?

**Comment by Gamadorium** [comment]
I don't have much technical knowledge on this subject, so I don't fully understand what you mean.

**Comment by insthync** [comment]
Your weapon setting

**Comment by Gamadorium** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/ddc53f94-1bf6-420d-b7fb-c38c23cb1607)
Yes, exactly increasing the value here a little worked for me, thank you very much.

**Comment by Gamadorium** [comment]
I would like to ask one last question on this topic in order to avoid confusion.

**Comment by Gamadorium** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/b7749d87-c2f8-404e-a2f0-22dab54cb112)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/f5a33f2b-d811-4877-9c8d-51aefd3a9e4d)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/0ca486f9-d38e-4b12-915e-d0fd188ebae0)



Here is the animation group of a creature in my project. I added an active "Run" animation to run towards the player, but the problem is that the monster does not use this animation while running towards the character and constantly displays the "Walk" animation. Moreover, even if the monster comes near the player, it moves back without attacking the player. How can I overcome it?

**Comment by Gamadorium** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/e5dc9fd7-77be-47a0-9185-5c1520038b91

**Comment by insthync** [comment]
Did you set it's base stats -> move speed?

**Comment by Gamadorium** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/bddc266f-2c3f-410c-8860-32e8f9c5fd63)
yes

**Comment by insthync** [comment]
Did you set move animation clip, not walk, not sprint?

**Comment by Gamadorium** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/bfc4cb19-efc6-46b1-80d2-5a6c592ae691)
Actually, I only defined the animations and did not put any speed rate on them. Can this be fixed by doing this?

**Comment by insthync** [comment]
No

**Comment by Gamadorium** [comment]
So what would you suggest me to fix the situation I mentioned?

**Comment by insthync** [comment]
I asked you about move animation setting

**Comment by insthync** [comment]
The default move not walk not sprint

**Comment by Gamadorium** [comment]
Where can I find this? Where exactly should I look?

**Comment by insthync** [comment]
Nearby in the images you've sent

**Comment by insthync** [comment]
Set run animation to DefaultAnimations -> moveStates 

And set walk to DefaultAnimations -> walkStates 

Don't have to set sprint

**Comment by Gamadorium** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/2c9c8b00-6b8b-4df0-aca3-7f9072195429)
So are you telling me to use the animations here and remove the sprint animations?

**Comment by insthync** [comment]
Can you just try it before ask ?

**Comment by Gamadorium** [comment]
This worked, thank you very much, could you please answer my last question if you have time?
  Question ;
- There is a skill I defined for the character. I want a glowing effect to appear on the weapon the character is holding when he uses this skill. What is the way to do this? I tried many options but I could not come to a conclusion about it. Here is a video of what I am talking about;

https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/09aeaf54-2fb6-4bee-ae48-036b96d6ea7a

**Comment by Gamadorium** [comment]
@insthync I thought you created this place to ask questions and find answers, my friend. You are so rude

**Comment by insthync** [comment]
If you think that I told you are very annoying is so rude, then yes, I am. 

But you should realize that is because you said last question, but you keeping asking new question, and it is not relates to the attacking/moving anymore,  it is very annoying, is n't it ?

You should just ask, I don't want to know it is the last question or not, so don't tell me that and lying with new questions.

**Comment by Gamadorium** [comment]
I was just asking the questions that came to my mind, I think you are having a bad day, you are very aggressive, I was sending my questions instead of opening new topics to avoid extra pollution, but you broke my heart in a way I didn't understand. Anyway, thank you.

**Comment by insthync** [comment]
It is better to create a new post because it will be easier for bug/feature tracking.

**Comment by Gamadorium** [comment]
I didn't know this, I apologize if I was rude, I respect your job and you, of course, if I offended you by thinking that you may have been tired and stressful during the day, I apologize again, take care of yourself, see you later.
