### ISSUE TITLE
Error after version update

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2478]
Hello, I was using version 1.86d before, now I have updated to version 1.88e, I get the error in the picture, what should I do?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/ed89c248-cc6a-41a4-b47d-965724b8434f)

**Comment by Niinra** [comment]
You also have a component that references the script that is asking you and possibly that is why it throws the nullreference error.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/7757fb43-4f31-4a3c-b141-252d8fcf2be4)
Check which prefabs are missing the reference to a script and if you find the prefab send me a photo so I know which script goes there

**Comment by insthync** [comment]
Fixed, I hope you can fix it by yourself, it is very easy.

**Comment by CLAXES** [comment]
> Ayrıca size soran betiğe referans veren bir cihazınız de var ve muhtemelen bu nedenle boş referans hatası veriyor. Hangi prefabriklerde bir komut dosyası referansının eksik olup olmadığını kontrol edin ve prefabrik bulursanız bana bir fotoğraf gönderin, böylece hangi betiğin gideceğini bileyim ![görüntü](https://private-user-images.githubusercontent.com/115952096/332881232-7757fb43-4f31-4a3c-b141-252d8fcf2be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTgwODMsIm5iZiI6MTcxNjM5Nzc4MywicGF0aCI6Ii8xMTU5NTIwOTYvMzMyODgxMjMyLTc3NTdmYjQzLTRmMzEtNGEzYy1iMTQxLTI1MmQ4ZmNmMmJlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNzA5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDZiY2QyNjhiMGNhMjdiN2U2Y2E2NTAwNDg2YjAxM2I2ZDAzNGE2OTYyNzFjZGQzYmI4NWYyZmQ2NDU5OWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_i6rlu1APcd0LSLFbDl8Vx0ky0_PGBMrwpYSxCUmNo)

I have corrected the missing reference but this error still persists in the character list.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/5eabdcd6-cd73-4e9c-b701-bf69ddf584c9)

**Comment by CLAXES** [comment]
I think the problem is caused by the code at the bottom of this item

                // Setup equipment entity
                tempEquipmentEntity = null;
                if (tempEquipmentObject != null)
                {
                    tempEquipmentEntity = tempEquipmentObject.GetComponent<BaseEquipmentEntity>();
                    if (tempEquipmentEntity != null)
                    {
                        tempEquipmentEntity.Setup(this, tempEquipmentModel.equipPosition, tempEquipmentModel.item);
                        tempEquipmentEntity.SetupRefToPrefab(tempEquipmentModel.meshPrefab);
                    }
                    if (CacheRightHandEquipmentEntity == null && GameDataConst.EQUIP_POSITION_RIGHT_HAND.Equals(tempEquipmentModel.equipPosition))
                        CacheRightHandEquipmentEntity = tempEquipmentEntity;
                    if (CacheLeftHandEquipmentEntity == null && GameDataConst.EQUIP_POSITION_LEFT_HAND.Equals(tempEquipmentModel.equipPosition))
                        CacheLeftHandEquipmentEntity = tempEquipmentEntity;
                }

I do not get an error when I cancel the following place

    // tempEquipmentEntity.SetupRefToPrefab(tempEquipmentModel.meshPrefab);

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/c7f31951-f240-463e-893f-78c223b081ad)

am I getting this error because mesh is not defined in items?

**Comment by insthync** [comment]
What you have to do is simple, just add codes to avoid null ref, that is it ;)
