### ISSUE TITLE
Create button disabled

### ISSUE THREAD

**Issue by JestHWas** [suriyun-production/mmorpg-kit-docs#248]
There has been a report that the create button for the character is disabled or not interactable on the latest version of the kit. I am not near a pc to test this out, but if this is true it would be essential to fix this and release this as a fix as soon as possible on the asset store.

If this is not true then please close

**Comment by insthync** [comment]
In `GameInstance` there is setting called `maxCharacterSaves` increase it to allow player to create more characters.

**Comment by JestHWas** [comment]
Yes. We tested it in discord and it works fine. Just have to move over some UI stuff to our custom scenes.

Thanks.
