### ISSUE TITLE
items in email

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2481]
I'm building a website and I'm at the point of integrating it with the email system that's in the kit. I'd like to know the logic of these email items? I understood that the item id comes first, then the quantity, but I would like to know what the zeros are after that.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/5b20f4bc-3986-4f71-9550-acfc0cfdee4a)

**Comment by insthync** [comment]
Look in `Mail.cs` file -> `WriteItems` function, it tells what are them.
