### ISSUE TITLE
MMO map transition problem

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2482]
Hello, when I try the MMO mode, when I change the map, it throws me back to the login screen as in the video. When I try with single player mode, this problem does not occur.
Version: 1.88e
[Video](https://youtu.be/mCmO7gSktE4)

**Comment by insthync** [comment]
Send me your AnyDesk address to my email ittipon.bay@gmail.com

**Comment by lunidel** [comment]
Getting the same problem (1.88e) , You will need to close the game and log back in to be able to connect again.

**Comment by insthync** [comment]
@CLAXES Try this https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMO/commit/89a34a8c03dd1a271e9103396a29bf232185608a

**Comment by CLAXES** [comment]
> @CLAXES Try this [suriyun-mmorpg/UnityMultiplayerARPG_MMO@89a34a8](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMO/commit/89a34a8c03dd1a271e9103396a29bf232185608a)

Works properly when I do it this way thanks

**Comment by insthync** [comment]
Thank you for bug reporting :)
