### ISSUE TITLE
Summon Problem

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#2483]
In the latest version, when you exit the game while summon is available, you enter it again and it gives this error.
![bandicam 2024-05-25 22-08-11-130](https://github.com/suriyun-production/mmorpg-kit-docs/assets/46999478/0e9bc37f-3590-4b1f-b319-46dabf5b1744)

**Comment by insthync** [comment]
Try 1.88f

**Comment by fedas61** [comment]
error not fixed

**Comment by insthync** [comment]
Send me your AnyDesk address

**Comment by insthync** [comment]
My email ***@***.***

**Comment by insthync** [comment]
ittipon.bay@gmail.com

**Comment by insthync** [comment]
Fixed in 1.88f2
