### ISSUE TITLE
Random Bonus Options not applying ( 1.88f2 )

### ISSUE THREAD

**Issue by lunidel** [suriyun-production/mmorpg-kit-docs#2486]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/e8ad59c3-4847-4bd3-bf58-7eeae5376ecb)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/56a96d54-da97-4ae2-9d6f-573bf2f7670d)

Not sure if it doesn't apply entirely or just a UI issue.

**Comment by lunidel** [comment]
This applies to all Random Bonus Option type

**Comment by insthync** [comment]
<img width="1140" alt="Screenshot 2567-05-28 at 22 23 36" src="https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/bf3782e3-f5d9-4d3a-a605-a9425f485064">

No problem here, how about the quest issues that you told me in the Facebook chat?

**Comment by lunidel** [comment]
@insthync can you check if the item option came from random bonus?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/7e33a7e4-5b48-4fea-9564-30fc56e44a8b)

**Comment by lunidel** [comment]
for the quest issue, it only happens on a specific quest when the task is completed but I can't replicate on other quests. It might be an isolated case.

**Comment by lunidel** [comment]
@insthync 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/b8665ea2-52c7-4cd9-9735-6159cc240710)


![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/d3e3fd0d-37df-4bcb-bd8e-7fd4caee0d61)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/bfdf153a-80d5-4349-a4c5-32e332fdfb36)
