### ISSUE TITLE
Random Bonus Options Not Working ( 1.88f2 )

### ISSUE THREAD

**Issue by lunidel** [suriyun-production/mmorpg-kit-docs#2488]
Sorry for reopening a new issue as the previous one was tagged as completed. It seems the problem is not only UI related but the Bonus Buff options do not apply at all.

As can be seen from the screenshots below, 

HP does not add
MP does not add
Damage does not add
Crit Rate does not add

Options do not work if they are set from Random Bonus but will work properly if set as normal item buff stat

https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/65d35d42-e6ef-47ad-abbc-6e9304569e1f

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/2b007f0e-0acb-4242-ade4-305509ce7dcd)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/361288a2-e805-46b7-83eb-389537bda7be)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/ffc45778-1864-4a94-aa1b-570ffe4878b1)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/7ab6198b-4e2c-40d1-a576-a9412524c33c)

**Comment by insthync** [comment]
I close it because it was fixed.

**Comment by insthync** [comment]
And you actually should reopen it, can't you?

**Comment by insthync** [comment]
I saw you can comment on another closed issue post, I don't get why you decided to repost a new one.

**Comment by lunidel** [comment]
sorry my bad
