### ISSUE TITLE
Auto Assign Hotkey

### ISSUE THREAD

**Issue by Gamadorium** [suriyun-production/mmorpg-kit-docs#2489]
Hello, I was thinking something like this;

For example, I want to add a hotkey and I want only "HP Pot" to be defined in this hotkey and no other item or skill should be assigned to this shortcut. If there is an HP pot on the character, it should be automatically defined to this shortcut and as it is used, it should decrease from the pot on us. I tried to do this for mobile, but there is a problem. I couldn't get any results, can you give me some guidance?

**Comment by insthync** [comment]
As I remember I have the script to do it, let me check it, but if it is not then I think you will have to write a component which will be attached to the same game object with the UI Character Hotkey which will assign those items when character's data (cache) updated.

**Comment by Gamadorium** [comment]
Thank you, I look forward to hearing back from you.

**Comment by Gamadorium** [comment]
@insthync Should I continue to wait for you on this matter?

**Comment by Eniotnacram** [comment]
https://github.com/ljars/auto-assign-hotkeys

**Comment by insthync** [comment]
I will have auto assign option added to UICharacterHotkeys component in next version (1.89)

**Comment by insthync** [comment]
Oh, I found it is already has autoAssignItem option in UICharacterHotkey component, try it.
