### ISSUE TITLE
New version without path to upgrade?

### ISSUE THREAD

**Issue by anthonyselias** [suriyun-production/mmorpg-kit-docs#2490]
Is there a proper guide on how to upgrade to the newest kit version?

Assuming there are no changes to core, I imagine upgrading to a new kit version should be simple.

If the upgrade method shown in the kit docs are correct, upgrading should be relatively straight forward. But, unfortunately, upgrading does not seem to be that easy.

Can we get a proper guide/tutorial on how we can upgrade the kit to a new version?

In addition to that, it would be great if you would let people know what has changed in the newest versions. Such as new gameplay rules, etc. 
The new kit version requires addressable package installed, but the doc's aren't updated to reflect this. This could bring great confusion to those upgrading or those especially new to the kit.

Upgrading without knowing what has changed and what's needed to upgrade, etc is like the blind leading the blind.

Please invest more time in making proper documentation for the kit. It would greatly reduce the questions posted here on github and in general in the community. Just food for thought.

**Comment by Niinra** [comment]
Ehm, generally to update the asset I literally delete the asset folder and reimport it to also bring the prefabs with specific changes, although now with the addressable package I don't know if it is possible to preserve the changes I make because it is a unity package, I know how to update it now with addressable because you simply have to check with the checkbox the things that need to be passed by reference but you also have to figure out how this works as well and the codes regarding the references because it is very important, I feel like that anyway People must be prepared for this type of thing since making an MMO is not easy, even if the asset promotes you a lot, the base is not easy.

**Comment by insthync** [comment]
How about this https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/147-how-to-update-to-new-version ?

**Comment by anthonyselias** [comment]
> How about this https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/147-how-to-update-to-new-version ?

Yes, that is the docs I followed, unfortunately that did not work. It ends up corrupting the whole project. 
For instance,  the gameinstance in init will show alot of missing scripts.

I have my project backed up, so I will attempt a few more times, but it seems like I'll be stuck with the old version until a proper solution is available.

**Comment by insthync** [comment]
A lots, then show me

**Comment by insthync** [comment]
How the fuck I can know whats are problems if you don't show anything, do I have to ask you everytime to show them?

You came here to just complain or do you really want solution.

How I can find a proper solution if I don't know the source of problem.

You said it has no document then after I show you the document you (which was a proper guide) tell me it is not working, you should just tell me it is not working and tell me how is it not working then I will update it properly.

**Comment by insthync** [comment]
And I won't write all list of changes files, you guys should use version controls to track list of changes files, list of big changes/new features are written in changelog.

**Comment by anthonyselias** [comment]
That's a great way to treat your customers. Very professional, keep it up!

**Comment by insthync** [comment]
Yes, thank you!

**Comment by insthync** [comment]
Then when will you show me the cuase of problem?

**Comment by insthync** [comment]
Okay, so after an hours, I've not seen any cause of problems, I'll assume that you are here just for complaining, and it won't help you find an solution, maybe only you having the problem.
