### ISSUE TITLE
Craft Success/Fail Rate (REQUEST)

### ISSUE THREAD

**Issue by lunidel** [suriyun-production/mmorpg-kit-docs#2493]
Our current Crafting system always generates items at a 100% rate with no chance of failure.

Requesting for a system to have a similar function for Refining items but instead for Crafting.

Adjustable Success Rates and Destroys materials when failing

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/c7202dbe-5e2c-4cc6-85c4-296e8d4ab0b3)

Something like this:

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/100618103/8fe85e1e-0726-4b52-8176-ca1d9269964b)

**Comment by insthync** [comment]
So what you want is crafting system with chance to fail?

**Comment by lunidel** [comment]
Yes hopefully to add a twist in terms of usage for the materials when crafting it helps give it more value having to craft items harder.

**Comment by insthync** [comment]
No, because you never paid for anything
