### ISSUE TITLE
Mail and auction error

### ISSUE THREAD

**Issue by CLAXES** [suriyun-production/mmorpg-kit-docs#2494]
Hello, these were working fine when I was using 1.86d, now it can't find the items

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/165d2ab2-ffbd-4b59-a295-e029f3076d20)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/31149983-7f6c-4aa7-82bd-ea049985e698)

**Comment by insthync** [comment]
No error messages?

**Comment by CLAXES** [comment]
It gives this error when I try to get the item in the mail, it does not give any other error message

	NullReferenceException: Object reference not set to an instance of an object
	at MultiplayerARPG.DefaultInventoryManager.IncreaseItems (System.Collections.Generic.IList`1[T] itemList, MultiplayerARPG.CharacterItem increasingItem) [0x00011] in <af4615e94f9949cf91c0a027f3256629>:0
	at MultiplayerARPG.CharacterDataExtensions.IncreaseItems (System.Collections.Generic.IList`1[T] itemList, MultiplayerARPG.CharacterItem increasingItem) [0x0000a] in <af4615e94f9949cf91c0a027f3256629>:0
	at MultiplayerARPG.CharacterDataExtensions.IncreaseItems (MultiplayerARPG.ICharacterData data, System.Collections.Generic.IEnumerable`1[T] increasingItems, System.Action`1[T] onIncrease, System.Action`1[T] onFail) [0x0001e] in <af4615e94f9949cf91c0a027f3256629>:0
	at MultiplayerARPG.MMO.MMOServerMailMessageHandlers.ClaimMailItems (System.String mailId, MultiplayerARPG.IPlayerCharacterData playerCharacter) [0x00134] in <af4615e94f9949cf91c0a027f3256629>:0
	at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in <063937552a9749c3b98ce3a6f7766086>:0
	at MultiplayerARPG.MMO.MMOServerMailMessageHandlers.HandleRequestClaimMailItems (LiteNetLibManager.RequestHandlerData requestHandler, MultiplayerARPG.RequestClaimMailItemsMessage request, LiteNetLibManager.RequestProceedResultDelegate`1[TResponse] result) [0x00102] in <af4615e94f9949cf91c0a027f3256629>:0
	UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	UnityEngine.Logger:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
	MultiplayerARPG.MMO.<HandleRequestClaimMailItems>d__6:MoveNext()
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
	Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
	Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetException(Exception)
	MultiplayerARPG.MMO.<ClaimMailItems>d__5:MoveNext()
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
	Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
	Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(DatabaseApiResult`1)
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(DatabaseApiResult`1)
	MultiplayerARPG.MMO.<GetMailAsync>d__190:MoveNext()
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
	Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
	Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(DatabaseApiResult`1)
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(DatabaseApiResult`1)
	MultiplayerARPG.MMO.<SendRequest>d__132`2:MoveNext()
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
	Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
	Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncResponseData`1)
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(AsyncResponseData`1)
	LiteNetLibManager.<SendRequestAsync>d__23`2:MoveNext()
	Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
	Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
	Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(Object)
	Cysharp.Threading.Tasks.DelayPromise:MoveNext()
	Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore()
	Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run()

**Comment by insthync** [comment]
I want to see your mail data from the database, just the one which having an issues

**Comment by CLAXES** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/95127578/52c0f02a-8d53-41e2-a87b-a8a216a6d3fb)

**Comment by insthync** [comment]
Try make changes follow this: https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_SharedData/commit/91cc6db5eac8afa1581cd47a2855cf496abd553c

And also make sure that the item data ID is correct (must not be removed or changed after the auction started)

**Comment by CLAXES** [comment]
> Şunu takip ederek değişiklik yapmayı deneyin: [suriyun-mmorpg/UnityMultiplayerARPG_SharedData@ 91cc6db](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_SharedData/commit/91cc6db5eac8afa1581cd47a2855cf496abd553c)
> 
> Ayrıca öğe veri kimliğinin doğru olduğundan emin olun (açık artırma başladıktan sonra kaldırılmamalı veya değiştirilmemelidir)

I tried, but unfortunately it didn't work.

**Comment by khongtuong** [comment]
replace the Mail.cs with old version from 1.79 will work fine

**Comment by insthync** [comment]
@khongtuong Thank you, I will check it.

**Comment by insthync** [comment]
Try this https://github.com/suriyun-production/mmorpg-kit-docs/issues/2497
