### ISSUE TITLE
MMO Server Start Problem

### ISSUE THREAD

**Issue by Gamadorium** [suriyun-production/mmorpg-kit-docs#2496]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/069ebb95-d7d9-47e9-a3d5-8d373036af7c)

`{
  "useCustomDatabaseClient": false,
  "databaseOptionIndex": 0,
  "disableDatabaseCaching": false,
  "useWebSocket": false,
  "webSocketSecure": false,
  "webSocketCertPath": "",
  "webSocketCertPassword": "",
  "centralAddress": "45.150.149.47",
  "centralPort": 7000,
  "centralMaxConnections": 1100,
  "mapSpawnMillisecondsTimeout": 0,
  "defaultChannelMaxConnections": 500,
  "channels": [
    {
      "id": "1",
      "title": "Kanal 1",
      "maxConnections": 5000
    },
    {
      "id": "2",
      "title": "Kanal 2",
      "maxConnections": 5000
    },
    {
      "id": "3",
      "title": "Kanal 3",
      "maxConnections": 5000
    },
    {
      "id": "4",
      "title": "Kanal 4",
      "maxConnections": 5000
    },
    {
      "id": "5",
      "title": "Kanal 5",
      "maxConnections": 5000
    }
  ],
  "clusterPort": 6010,
  "machineAddress": "45.150.149.47",
  "mapSpawnPort": 6001,
  "spawnExePath": "C:\\Server\\Server.exe",
  "notSpawnInBatchMode": false,
  "spawnStartPort": 8000,
  "spawnChannels": [
    "1",
    "2"
  ],
  "spawnMaps": [
    "Map001",
    "Village",
    "Vadi",
    "Map_GuildWar"
  ],
  "spawnAllocateMaps": [
    {
      "mapName": "Map001",
      "allocateAmount": 0
    }
  ],
  "mapPort": 7770,
  "mapMaxConnections": 1100,
  "databaseManagerAddress": "127.0.0.1",
  "databaseManagerPort": 6100
}`

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/b171e5d8-7fb0-48cd-a1bb-28b3c3ba744f)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/29961a6c-423a-49a0-ba53-4e64b4583568)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/89e9f7bc-b181-4c09-9989-e71d7e10ba1c)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/9e545d01-0e0d-461a-82a3-758ac97b9d72)

I am trying to run the server part on a windows server, I wonder where my mistake is?

**Comment by insthync** [comment]
It might be started, you may check the running game processes, then try close them and run the servers again

**Comment by Gamadorium** [comment]
@insthync I solved the server problem and I can log in to the game, but after creating a character, I receive many errors on the server side as follows. I could not find the reason, can you help me?

[Player.log](https://github.com/user-attachments/files/15571996/Player.log)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/4c3054b1-db0c-41e5-ac7c-e21e146fdc12)

**Comment by Gamadorium** [comment]
@insthync 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/15fbb1b7-f356-4a41-86a7-3b7e2a3083ca)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/9b32192d-0620-42f6-aa44-2f78614b5222)

I developed the enchantment system in a different way, that is, I added an additional feature

**Comment by Gamadorium** [comment]
I do as stated in the documentation, but I encounter these problems.

**Comment by insthync** [comment]
Did you add the tables/columns to the database?

**Comment by Gamadorium** [comment]
Dude, is your goal here to talk to people or to help, are you constantly talking like an egotistical person and being rude to people, what's your goal?

**Comment by insthync** [comment]
Just telling you what you have to learn is rude?

You are here to make bugs reporting?, but it is not bugs from mine, it is because of your added codes.

The logs messages is telling what is missing, you told me that it was your codes, but you don't know about the error messages, so I telling you what you have to learn. Because if you have lack of knowledge then it will take time to tell you what you have to do, I am selling game asset, I am not intend to be a coding tutor.

My goal for this project is to develop it, improve it and sell it, so helping people for every of game development aspect is not my goal.
