### ISSUE TITLE
Mail system

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#2497]
I have a problem receiving objects via email, in a fresh project (1.88f4), it appears like this
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/6138cb7d-2fb3-4941-bd8a-84e58f9878a0)
And when I try to claim

https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/987bc7b6-8eaa-40a0-b555-cea289afb979

**Comment by insthync** [comment]
No error message on server?

**Comment by Blunnyn** [comment]
Nope, I'm attaching my logs in case it's of any use, but in the same way it doesn't throw any errors on the server.
[log.zip](https://github.com/user-attachments/files/15541987/log.zip)

**Comment by Blunnyn** [comment]
Finally it appears like this

https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/bed35fc7-9589-462a-9b42-ca05f7774958

and then...
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/45702662/ca666447-eff7-40e9-a65e-573afa2d71c4)

**Comment by khongtuong** [comment]
replace the Mail.cs with old version from 1.79 will work fine

**Comment by moepi2k** [comment]
got same issue, also with auction house items -> https://gyazo.com/cffd73208c83163303590a5692bae9cd

**Comment by insthync** [comment]
@moepi2k Yep, it was reported https://github.com/suriyun-production/mmorpg-kit-docs/issues/2494

**Comment by moepi2k** [comment]
oh didnt saw that, thanks :)

**Comment by moepi2k** [comment]
so should i just replace the mail.cs from 179 or is there a better fix?

**Comment by insthync** [comment]
Always me who can fix it?, you guys have all codes, there is no coder here?

**Comment by moepi2k** [comment]
Not many i think. But as he said replace mail.cs from 179 i wondering if its the solution, since u did no made any changes on it

**Comment by insthync** [comment]
Try it!

**Comment by moepi2k** [comment]
thank you it works

**Comment by insthync** [comment]
Fixed by just one line of codes, if you guys really try to do something I think you guys can fix it, that is why I have disappointment feeling.

**Comment by moepi2k** [comment]
I understand you, but i can talk just for me that i not figured out that fix :(

**Comment by temel61** [comment]
@khongtuong  Can you share mail.cs V1.79 Code?.I could not fix it yet
