### ISSUE TITLE
Client Builds not Populating Server List

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#25]
Building "00Init_MMO_ClientOnly" does not populate a list of servers to connect to.  Building "00Init_MMO" does work.

Windows 10 Build
Kit 1.43b
Unity 2018.3.11f1

**Comment by insthync** [comment]
Did you try set `Network Settings` in `MMO Client Instance` ?
![Screenshot_140](https://user-images.githubusercontent.com/2697550/55681260-7bbfcf80-594e-11e9-8500-3e93bf802520.png)
