### ISSUE TITLE
[Paid Request] Mouse Cursor Change and hover

### ISSUE THREAD

**Issue by ayaldabos** [suriyun-production/mmorpg-kit-docs#2502]
i'm using the playercharactercontroller setting in my game and i would like to implement change cursor system 
changing cursor depending on target hover on ally change cursor ,hover on enemy show different cursor, hover on npc change cursor

**Comment by Niinra** [comment]
Write to me on discord and give me more details about this my ID: Ninra#0898

**Comment by insthync** [comment]
You may create a new component which will do raycasting every frames, then if it hitting any entity, try to find the kind of entity (may use `is`) and then use that for cursor changing. This component may be attached to the same game object which is a `PlayerCharacterController` prefab, so when enter the game, `PlayerCharacterController` prefab is instantiated and the new component will start working at same time.
