### ISSUE TITLE
[Bug]Queue Crafting

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2503]
Tested with 188f5

When build a queued workbench there are two issues.

1) you cant cancle the queued item
2) when walk away from queued workbench, the item still crafting

https://gyazo.com/4dc7e2a28bfc1348d354d5716429da9a 

weird is, when you craft an item from a workbnech then open the 'local' queued list, you can cancel the items from workbench

**Comment by moepi2k** [comment]
thx for the fast fix. it works now to cancel, also when walk away. but now the personal crafting when use 'CanBeCraftedWithoutSource' no longer works. nothing happen when click craft an item.

**Comment by insthync** [comment]
Fixed
