### ISSUE TITLE
[Bug]Socket Enhancer

### ISSUE THREAD

**Issue by kaal86** [suriyun-production/mmorpg-kit-docs#2504]
**Describe the bug**
When use thew new socket enhancer, it seems there is a bug. by default its only used 'Red' for sockets and on all items which have sockets. but i tried to use Red, Blue Green for sockets and for example Sword001 Red, Armor001, Blue etc.

for the first time u open socket menu, it always show all sockets, even those which you cant apply. then when you put the right socket into the item it only shows those socket which you can apply. then for all other items it wont update properly it always shows only that socket.

also wondering where to change the enum names like red blue green etc?

**To Reproduce**
1) change sockets from demo to blue, red, green
2) change socket on item e.g sword001 to red, armor001 to blue
3) try apply socket on those items and check what happen (described above)

**Expected behavior**
it should only show the socket which you can apply to the item -> red to red, blue to blue etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2022.3.29
 - kit 188f5

**Comment by insthync** [comment]
Have to change its workflow, to select a socket before select gems

**Comment by insthync** [comment]
Fixed, it has no change to its workflow

**Comment by kaal86** [comment]
thank you very much, sorry for late replay
