### ISSUE TITLE
Skill animation for weapon type

### ISSUE THREAD

**Issue by gochaboy1** [suriyun-production/mmorpg-kit-docs#2506]
And so I think this proposal is useful. Since there can be many types of weapons and animations for weapons can be different!

Let's imagine that we have a character "archer" who has two types of weapons "bow" and "gun" 
Now let’s imagine that our character has the “powerful shot” skill with active animation.

the problem is that in the current version of the kit we can only set 1 animation per skill
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/41185982/5bd6afd5-6f9c-41b4-ae66-bcf148e5ff80)
and as a result, we can set only 1 animation on either a bow or a gun, and there are situations when a character has 5-6 types of weapons and they all have different skill animations, you know?)

My proposal is to add a skill animation setting to the Weapon Animation section so that you can make your own animation for each type of weapon

I tried to do this in PlayableCharacterAnimation.cs 
adding 
[Header("Skill animations")]
 public SkillAnimations[] skillAnimations;
 
As a result, setting skills in animation in the weapons section became available, but the animation still does not play in the game, since I’m sure this needs to be added in other places in the code!

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/41185982/326642f0-70bb-4718-a590-04fc7ba43741)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/41185982/3f9cdb67-5c55-47df-a65e-469f3c40832c)

**Comment by insthync** [comment]
Added, wait for 1.89 update
![Screenshot_4](https://github.com/user-attachments/assets/0559b8ec-2981-42a0-95e5-2675b28b7cc0)
