### ISSUE TITLE
User ID

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2507]
How can I retrieve the logged in user's ID and, if possible, also his IP.

It's for an integration I'm doing with my website

**Comment by insthync** [comment]
When do you want those information?, if the character is in game you can get it from BasePlayerCharacterEntity -> UserId

**Comment by juniormagalhaes** [comment]
> When do you want those information?, if the character is in game you can get it from BasePlayerCharacterEntity -> UserId

I want to add new functions to the website I made for the kit, does this reference you sent take the character or account ID? I need the account ID.

https://www.youtube.com/watch?v=wMSLtFukoxQ&t=7s&ab_channel=Magalh%C3%A3es

**Comment by insthync** [comment]
User Id is account Id

**Comment by juniormagalhaes** [comment]
I tried to recover just to have the visual return, in mmo mode it doesn't appear, in single player mode it appeared. Am I doing it right?


using UnityEngine;
using UnityEngine.UI;
using MultiplayerARPG;

public class DisplayUserId : MonoBehaviour
{
    // Referência ao componente Text
    public Text userIdText;

    // Referência ao componente BasePlayerCharacterEntity
    public BasePlayerCharacterEntity playerCharacterEntity;

    void Start()
    {
        // Verifica se as referências estão atribuídas
        if (userIdText == null)
        {
            Debug.LogError("UserIdText não está atribuído!");
            return;
        }

        if (playerCharacterEntity == null)
        {
            // Tenta encontrar automaticamente o BasePlayerCharacterEntity na cena
            playerCharacterEntity = FindObjectOfType<BasePlayerCharacterEntity>();

            if (playerCharacterEntity == null)
            {
                Debug.LogError("BasePlayerCharacterEntity não encontrado!");
                return;
            }
        }

        // Atualiza o texto da UI com o UserId
        userIdText.text = "UserId: " + playerCharacterEntity.UserId;
    }
}

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/56885137/d587b5a8-455a-4a9b-8802-7df5fd65fd36)

**Comment by insthync** [comment]
It will be set at server only, if you want to change it, you must add a sync field string and use it in user id property

**Comment by juniormagalhaes** [comment]
> It will be set at server only, if you want to change it, you must add a sync field string and use it in user id property

ah ok, thanks
