### ISSUE TITLE
Windows server problem

### ISSUE THREAD

**Issue by Gamadorium** [suriyun-production/mmorpg-kit-docs#2508]
When I run the game's server, I don't get an error, but I see a lot of clones like this in the task manager, how can I fix this?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/e5706416-9d7b-4e0a-9dd4-da51926bdd7e)

**Comment by insthync** [comment]
That are maps that were spawned by map-spawn server?

**Comment by Gamadorium** [comment]
I only have 3 maps in the game. After starting the server, it replicates itself like this. What can I send you for control?

**Comment by insthync** [comment]
Want to see your serverConfig.json, it may spawn by allocate maps settings

**Comment by Gamadorium** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/0025cf6b-c287-4dd2-b446-cc2fa85fe5d8)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/01f4ff98-e39b-4018-bfda-8bd22060c8f3)

This is the extension I defined in the shortcut:

C:\Server\Game.exe -startMapSpawnServer -spawnExePath "C:\Server\Game.exe" -startCentralServer -startDatabaseServer -machineAddress "212.10.127.36"

**Comment by insthync** [comment]
Try set spawnChannels to ["1"]
And set spawnAllocateMaps to []

**Comment by Gamadorium** [comment]
I will try it and follow it and let you know immediately.

**Comment by Gamadorium** [comment]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/4a539abc-68ca-47cb-b498-679d8007afdd)
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/e791cbae-c253-448f-ba7e-6096a505a699)
I did as you said, but it still happens like this. What do you think could be the reason for this problem?

**Comment by insthync** [comment]
Is it lesser, right?

**Comment by insthync** [comment]
From what I see, the problem is you are not understand about how map-spawn server work yet.

When it spawn it will create new instance like that.

So it is work as intended, there is no problem

**Comment by Gamadorium** [comment]
Currently, I changed the RAM resource of my server to 32 GB. Yes, it copies less, but it closes the game after a certain period of time. Can we prevent this?

**Comment by insthync** [comment]
It use Unity as server, so that is how it is, you can reduce amount of ram use by exclude meshes/texture from server build, that is it

**Comment by Gamadorium** [comment]
This would be great. Could you please direct me to a place where I can find an example of this?

**Comment by insthync** [comment]
Simplest way is to remove renderers components from the scene when you are going to build for a server

**Comment by insthync** [comment]
You also can try this https://forum.unity.com/threads/unity-dedicated-server-package.1419295/
