### ISSUE TITLE
(Paid Request) Change base models of the player, npc and monsters

### ISSUE THREAD

**Issue by rodrisolisavila** [suriyun-production/mmorpg-kit-docs#2509]
I need help to update the 3D base models of player characters, NPCs, and monsters. For the player characters, I want to replace the current models with a basic male and female model, both customizable in terms of clothing and hair style. Additionally, I need to create at least three sets of additional clothing and hair styles that players can purchase from an in-game store. I am willing to negotiate the price for these sets and am looking for a collaborator to implement these modifications.

**Comment by Niinra** [comment]
Ehm Write to me on discord and give me more details about this my ID: Ninra#0898

**Comment by rodrisolisavila** [comment]
> Ehm Write to me on discord and give me more details about this my ID: Ninra#0898

I have sent you a request, I am ruri

**Comment by gochaboy1** [comment]
> > Ehm Write to me on discord and give me more details about this my ID: Ninra#0898
> 
> I have sent you a request, I am ruri
Discord
mrken2024_71390
