### ISSUE TITLE
Create button disabled by default

### ISSUE THREAD

**Issue by JestHWas** [suriyun-production/mmorpg-kit-docs#251]
The create button is disabled by default, even though maxCharacterSaves is 5 and you have no characters. When enabling this it then works as normal and then when the limit is hit it disables and if i delete a character so go below the limit it re-enables.

This is for both 2d & 2d

**Comment by insthync** [comment]
What Unity version are you using, it still works correctly for me, both singleplayer and MMO mode.

**Comment by Callepo** [comment]
Some people report it not working.. and have to toggle in on by default themselfs save then scene.... and after that it works like intended and others have no issue..so yea, its a bit weird. We all ysing 1.53c 
idk if its a unity version issue

**Comment by JestHWas** [comment]
i'm using 2019.3. Version 1.53c

**Comment by Callepo** [comment]
2019.2.12f1 here

**Comment by Oseriduun** [comment]
2019.3.2f1 ver 1.53c
confirming that the create char button is not set to interactable by default for mmo demo

**Comment by insthync** [comment]
[MMORPG-KIT-FixInvalidAbleToCreateCharacterLogic.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4273543/MMORPG-KIT-FixInvalidAbleToCreateCharacterLogic.zip)
Try fix by this package, I was written invalid logic codes

**Comment by JestHWas** [comment]
Thanks. Will you be able to push out a  new version for this as quick as possible. Quite a few people may end up complaining about it.

**Comment by insthync** [comment]
Yes, I'll do it today, thank you for issues report :)

**Comment by insthync** [comment]
Just uploaded the new version.

**Comment by Oseriduun** [comment]
glad to see such a quick update on this, i look forward to testing the new version

**Comment by insthync** [comment]
I will close this, if it's still occurring, you can reopen it.
