### ISSUE TITLE
Iventory

### ISSUE THREAD

**Issue by kaal86** [suriyun-production/mmorpg-kit-docs#2510]
this is more like a question, since im reading through the docs but cant find anything related. my question is, is there an option to switch to a diablo like inventory -> gridbased where items use multible slots like 1x1, 2x2, 3x3 2x6 or whatever you want. and have option to rotate those items to organize inventory.

**Comment by insthync** [comment]
There is no grid based inventory system yet.

**Comment by kaal86** [comment]
okey, thank you very much for the info
