### ISSUE TITLE
Wrong UI Data 

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2513]
Lets say we have a Sword which use random stats. when you put the item in shop, everytime the data changes when open the shop, this is because it not has a set seeed.

but, when you have an item in inventory which has a fixed seed then somethings wrong when the item is for example on ground. when u use UIPickup to show nearby items on ground, the stats on the same item is always diffrent when to UIPickup opens. 

i tested in mmo when trade an item. the random data shows correctly for seller and buyer in trade window, so i dont know why not for the UIPickup?

**Comment by insthync** [comment]
What is the exact probem? just a UI Pickup?

**Comment by insthync** [comment]
Try latest commit

**Comment by moepi2k** [comment]
yes, that fixed the problem :) thank you very much

btw, just saw this https://gyazo.com/8e5423149662ddd8d61e61ab947b1ec3 the ik stuff seems new. is it to correction when using 2 hand weapons?

**Comment by insthync** [comment]
It will :)

**Comment by moepi2k** [comment]
nice i will check it out. did not see any thing in patchnotes or docs :P
