### ISSUE TITLE
Visible/Invisible Material bug

### ISSUE THREAD

**Issue by ayaldabos** [suriyun-production/mmorpg-kit-docs#2514]
Visible/Invisible Material in Playable Character Model doesn't work while using the invisible skill 

i tried the other options like hide object and hide render while invisible they work just fine but the material option doesn't work at all 
https://i.gyazo.com/ca7e6d294a5b265ed18c1399b564680e.png

**Comment by ayaldabos** [comment]
https://vimeo.com/968268637?share=copy here's a video show how i'm trying to setup the materials for the renderer

**Comment by insthync** [comment]
Hmm, it might be because the renderer you've selected is a default one, not the one which character equipped, I might have to change its workflow, may add hiding renderers settings to equipment entity component

**Comment by insthync** [comment]
[feat-equipment-model-visible-state-updating.zip](https://github.com/user-attachments/files/16617437/feat-equipment-model-visible-state-updating.zip)

Hey!, try this, it will have options to set **visibleMaterials,  invisibleMaterials, fpsMaterials, hiddingObjects, hiddingRenderers, fpsHiddingObjects, fpsHiddingRenderers** settings added to equipment entity component, they works like as game entity model.

You can reopen if it don't work :)
