### ISSUE TITLE
[Suggestion]Item Level

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2515]
Just a small suggestion which i think use useful for everyone :)

option to set item level for shop and itemdrop. 
atm every item you buy or drop will be 1. would be nice to have option to set the item level.

if its to big effor then its also ok :)

wish you a nice day

**Comment by lunidel** [comment]
Agree on this!

**Comment by insthync** [comment]
I will do it.

**Comment by gochaboy1** [comment]
> I will do it.

Please make another morphing system, I'm looking forward to it like many others =)

**Comment by insthync** [comment]
Added, wait for 1.89 update
