### ISSUE TITLE
 'System.Reflection.AssemblyProductAttribute' attribute

### ISSUE THREAD

**Issue by Gamadorium** [suriyun-production/mmorpg-kit-docs#2516]
I was editing the values ​​in the language section in the GameInstance section and all these errors occurred. I did not understand how to fix it. Can you help me with this?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/99f426a9-3490-482f-ad0a-e15906b977e9)

**Comment by insthync** [comment]
Are you sure that is all what you did?

The error is telling that you have duplicated source codes
