### ISSUE TITLE
Help about mobile skill bar

### ISSUE THREAD

**Issue by Gamadorium** [suriyun-production/mmorpg-kit-docs#2517]
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/170323096/af8a3b02-7154-4a80-b4d5-4fca52425a0e)
Is there something I need to do software to remove the joystick here and turn it into a directly clickable button, because I can't turn it back to normal?

**Comment by Gamadorium** [comment]
@insthync

**Comment by insthync** [comment]
I don't understand what are you going to tell me at all

**Comment by Gamadorium** [comment]
What I want to say is that when I click on the Skill Boxes in mobile controls, a joystick appears and I can use skills when I drag and drop it, but when I change the design, this becomes completely difficult and I only have to press from the edge of the Skill Box and drag the joystick extra. I mean, can I make the Skill Boxes directly clickable? Instead of dragging and dropping a joystick, I just want to press it.

**Comment by Niinra** [comment]
I don't understand what you want at all, do you want the button to be pressable or how about a video with a better explanation?
