### ISSUE TITLE
Fast pressing action button occurs in few skills

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#252]
if you for example press 1 many times, hotkey is executed twice or more time before getting cooldown.

**Comment by insthync** [comment]
Is this occurring when using skill or item or skill item (scrolls) or all of them?, I pretty sure that I've made it avoid spamming keys.

**Comment by poaq** [comment]
It happens with fireball skill for example. Didn't test itmes.

**Comment by insthync** [comment]
Uploaded the new version, try 1.53d

**Comment by insthync** [comment]
I will close this, if it's still occurring, you can reopen it.
