### ISSUE TITLE
Dash extension 

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2520]
Hi, I really like the dash! I tried to implement on my end the dash to cost stamina when triggered. I've been kinda successful using gameplay rules and some partials, but I'm really not sure if I implemented it correctly.

Could you please add this to core if you have time for it? I think others could benefit that too.

- Cost stamina or mp to use (or not)
- Delay between each dash (so players cannot spam it)

Thank you!

**Comment by insthync** [comment]
Yep, I will show the example next month, I will travel from 20-30

**Comment by Eniotnacram** [comment]
Perfect, thank you!

**Comment by khongtuong** [comment]
make a dash as a skill, call dash when using that skill, that'll make dash unique for some class, so you can use mp or whatever stat for it

**Comment by Eniotnacram** [comment]
> make a dash as a skill, call dash when using that skill, that'll make dash unique for some class, so you can use mp or whatever stat for it

That's bright! I'll do that

**Comment by Eniotnacram** [comment]
Made it work perfectly with the skill! So suri, if you implement it, maybe simply create a skill for it, but again it's not needed because I created one pretty easily!

One thing to fix tho, even before i created it as a skill, the dash is pretty jittery (transform). Also I got a animation event on my dash start. The event is called multiple times, so I think there is an issue in the playablecharactermodel and the animation is triggered multiple times.

**Comment by insthync** [comment]
How is it jittery?, jitter by transform, not animation?, did you uses root motion for animation?

**Comment by Eniotnacram** [comment]
Never mind.. Just need to finds the sweet spots in the dash settings, maybe the value were just too fast. I also had my animations in loop so that was making it jittery, my bad!

So yea, I think we could close this request unless you want to create a custom skill for it, but if not, I can simply share mine to the community

**Comment by Eniotnacram** [comment]
Maybe one thing that you could help me, as the dash is a skill now, it count as an Action. So if we are using the shooter player character controller, in adventure mode, the character is not dashing from where it looks but instead it will dash where the camera is looking at. When "Turn forward while doing action" is enabled. (I need it enabled for my attack skills) but for the dash I would like it to be disabled. 

Do you have any idea what would be the best way to disable it only for the dash?

**Comment by khongtuong** [comment]
> Maybe one thing that you could help me, as the dash is a skill now, it count as an Action. So if we are using the shooter player character controller, in adventure mode, the character is not dashing from where it looks but instead it will dash where the camera is looking at. When "Turn forward while doing action" is enabled. (I need it enabled for my attack skills) but for the dash I would like it to be disabled.
> 
> Do you have any idea what would be the best way to disable it only for the dash?

add a bool to player character, then when using dash, disable the turn forward, migh work :D
