### ISSUE TITLE
Question Player Data

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2522]
just a question. i noticed that some variables only work serverside. two of them are userLevel and guildRole. is there any reason why those are not synced to client? is saw in BasePlayerCharacterEntity.NetworkData that few are not synced. or whats best way to get access to it clientside? because i need it for few thinkgs

**Comment by insthync** [comment]
Just made it not an sync fields just for message size reducing, if you want to change you may create sync fields for them and change property's getter/setter values

**Comment by moepi2k** [comment]
can we not make it as sync fields and you just set sync behaviour to 'do not sync update' so that it not increase package size for those who not need it? im not sure but i think when i want to add the syncfields in partial class i still need to modify the core?

**Comment by insthync** [comment]
It will be synced only when data changed and when server send object spawning to client.

**Comment by moepi2k** [comment]
yea i mean syncfields, but even when we use it and in the inspector set  sync behaviour to 'do not sync update' then it has no impact, right? thats why im asking if we can make the guildRole and userLevel as sync field but set it to not sync by default and if someone need it he can change to default

**Comment by insthync** [comment]
Yes, no impact
