### ISSUE TITLE
How to access storage items from UI

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2523]
Hi,
I can't figure out how to access the quantity of a specific item in a storage from UI. It seems based on what i found only using playingcharacter inventory.

**Comment by insthync** [comment]
Want to show amount of item in storage?

**Comment by sawcisson** [comment]
I want to compare it with the requirement in a crafting formula

**Comment by insthync** [comment]
I don't know how you store data into `CacheListStorage`?

**Comment by sawcisson** [comment]
CacheListStorage.Generate(characterItems, (index, characterItem, ui) =>
            {
                Debug.Log("CraftStorage generate");
                tempUI = ui.GetComponent<UICharacterItem>();
                tempUI.Setup(new UICharacterItemData(characterItem, InventoryType.StorageItems), GameInstance.PlayingCharacter, index);
                tempUI.Show();
                if (characterItem.NotEmptySlot())
                {
                    TotalWeight += characterItem.GetItem().Weight * characterItem.amount;
                    Debug.Log("Cachelist characteritem " + characterItem.GetItem() +" amount of : " + characterItem.amount);
                    
                    UsedSlots++;
                }
                UICharacterItemDragHandler dragHandler = tempUI.GetComponentInChildren<UICharacterItemDragHandler>();
                if (dragHandler != null)
                    dragHandler.SetupForStorageItems(tempUI);
                CacheSelectionManagerStorage.Add(tempUI);
                if (!string.IsNullOrEmpty(selectedId) && selectedId.Equals(characterItem.id))
                    selectedUI = tempUI;
                showingCount++;
            });

**Comment by insthync** [comment]
The CacheListStorage data, when it's being added?

**Comment by sawcisson** [comment]
Okay i managed to fix it by adding a public variable of the StorageUI and accessing the Storage UIList from the other Amount Ui script and it was able too
