### ISSUE TITLE
Disable and enable gameobject in monster on target

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#2524]
Hello, I placed a game object on the monster, now I wanted to know how to make the game object disappear when the monster finds a target. and when it loses the target the game object appears again.

I would like to know which script I should modify to create this function and if it is possible to use the dev extensions to do this.

![image](https://github.com/user-attachments/assets/26c67d7c-0737-4fec-a8e3-60195be925a9)

**Comment by insthync** [comment]
You can create new component which extend from LiteNetLibBehaviour, this component will be attached to the same game object with monster character entity, it will have variables which will being synced to clients (such as SyncFieldBool isFinding), and then set the value by the monster's behaviour
