### ISSUE TITLE
Why LAN/Singleplayer requires UNITY_SERVER?

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2526]
In was implementing steam SDK through an asset and noticed a problem where it was considering the project a headless server.
I also noticed that if i remove the UNITY_SERVER define from the LAN setup it won't work properly.

But UNITY_SERVER define is supposed to be used for headless server without the game build itself. Which is also causing steam to consider the game not as a client build but a server build.

Why is it necessary and what would be the work around ?

Thanks

**Comment by insthync** [comment]
It need UNITy_SERVER to make offline/lan works because it have to include server side codes to make it work

**Comment by insthync** [comment]
Just use the setup menu from MMORPG Kit menu

**Comment by insthync** [comment]
In the new version, it will use EXCLUDE_SERVER_CODES as compile condition, if it is still using UNITY_SERVER, then it is outdated
