### ISSUE TITLE
Item Duping Issue on Multiplayer; Items in the last chest opened show up in the Player Storage after exit (Client Only)

### ISSUE THREAD

**Issue by ApolloGM** [suriyun-production/mmorpg-kit-docs#2527]
Steps:
start a game on LAN
join as a client
open a storage chest and add items
Log out or exit as a client
Join the same session again
now open player storage on the NPC
items in the chest are  now duped in the Player Storage
![image (4)](https://github.com/user-attachments/assets/ec7efc3d-4efd-47d0-879e-597382db01fb)
![image (5)](https://github.com/user-attachments/assets/4d4fa9b3-8478-4db2-94fe-ea518277041c)

**Comment by insthync** [comment]
I will fix it.

**Comment by ApolloGM** [comment]
Thanks! what files do you think will need changes? I will make sure to lock them on my end so they are ready for merge :)

**Comment by insthync** [comment]
[separated_building_and_user_storage_saving.zip](https://github.com/user-attachments/files/16591288/separated_building_and_user_storage_saving.zip)

And 

![Screenshot_2](https://github.com/user-attachments/assets/8c9af282-6ba8-4716-8d77-ef9406ab25cf)

**Comment by ApolloGM** [comment]
thank you! it worked. I merged the code in LanRpgNetworkManager
