### ISSUE TITLE
Player Title/Icon/Frame 

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2528]
i wanted to test the player title and checked the code. so it seems its mostly like guild icon. so i copied the guild icon stuff and replaced with player title. so far so good.

also created few titles and add to game data base. 
so now when i want to open the ui the titles get not populated, in singleplayer nothing happen but when i try in mmo i get the error 
'Service not available' with the following error

ERROR MapNetworkManager<M_MapNetworkManager>.C [2024-07-30 15:10:24] - Cannot create request. Request type: 187 not registered.
UnityEngine.Debug:LogError (object)
ZLogger.Providers.UnityDebugLogProcessor:Post (ZLogger.IZLoggerEntry) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/Unity/ZLoggerUnityLoggerProvider.cs:71)
ZLogger.AsyncProcessZLogger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/ZLogger/AsyncProcessZLogger.cs:36)
Microsoft.Extensions.Logging.Logger:<Log>g__LoggerLog|12_0<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.ILogger,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>,System.Collections.Generic.List`1<System.Exception>&,Microsoft.Extensions.Logging.FormattedLogValues&)
Microsoft.Extensions.Logging.Logger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>)
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,System.Exception,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:LogError (Microsoft.Extensions.Logging.ILogger,string,object[])
LiteNetLibManager.Logging:LogError (string,string,object[]) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/Logging/Logging.cs:45)
LiteNetLibManager.TransportHandler:CreateAndWriteRequest<MultiplayerARPG.RequestAvailableContentsMessage> (LiteNetLib.Utils.NetDataWriter,uint16,MultiplayerARPG.RequestAvailableContentsMessage,LiteNetLibManager.ResponseDelegate`1<LiteNetLib.Utils.INetSerializable>,int,LiteNetLibManager.SerializerDelegate) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:157)
LiteNetLibManager.LiteNetLibClient:SendRequest<MultiplayerARPG.RequestAvailableContentsMessage> (uint16,MultiplayerARPG.RequestAvailableContentsMessage,LiteNetLibManager.ResponseDelegate`1<LiteNetLib.Utils.INetSerializable>,int,LiteNetLibManager.SerializerDelegate) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:118)
LiteNetLibManager.LiteNetLibManager:ClientSendRequest<MultiplayerARPG.RequestAvailableContentsMessage, MultiplayerARPG.ResponseAvailableContentsMessage> (uint16,MultiplayerARPG.RequestAvailableContentsMessage,LiteNetLibManager.ResponseDelegate`1<MultiplayerARPG.ResponseAvailableContentsMessage>,int,LiteNetLibManager.SerializerDelegate) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:385)
MultiplayerARPG.DefaultClientUserContentHandlers:RequestAvailableContents (MultiplayerARPG.RequestAvailableContentsMessage,LiteNetLibManager.ResponseDelegate`1<MultiplayerARPG.ResponseAvailableContentsMessage>) (at Assets/UnityMultiplayerARPG/Core/Scripts/Networking/Implements/DefaultClientUserContentHandlers.cs:17)
MultiplayerARPG.UIPlayerTitleEditing:LoadAvailableTitles () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Social/PlayerTitle/UIPlayerTitleEditing.cs:71)
MultiplayerARPG.UIPlayerTitleEditing:OnEnable () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Social/PlayerTitle/UIPlayerTitleEditing.cs:66)
UIBase:Show () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UIBase.cs:86)
UnityEngine.EventSystems.EventSystem:Update () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)

so it seems the msg not registered properly, i dont know if its an issue on my side. but i found an issue in two scripts. 
https://gyazo.com/524ae3027d6334cddd1cf044ee5134df

it uses UnlockableContentType.Frame for all PlayerTitle, Icon and Frame in the TitleEditing script.

but even chanign to the correct one its not working. any advice? also im wondering how to make the titel unlocking part since there is a request call for available titles.

sincerly

**Comment by insthync** [comment]
It is not done in the kit yet, that is parted of my project,  can I exclude those part from the kit?, everything I did for my project must have to be included in the kit?

**Comment by moepi2k** [comment]
ohh then everythings clear :) sure its up to you whats in kit and what not. but its anyway something i wanted to implement in my game and as i saw it i digged through it.

**Comment by moepi2k** [comment]
ok i see why some ppl had it running before 188. i think it was more like a copy paste of the guild icon and in 188 you added the request part which is used to check if title is available,right?

**Comment by insthync** [comment]
Yes

**Comment by moepi2k** [comment]
will you remove it from kit?

**Comment by moepi2k** [comment]
thats really nice, thank you for the info
