### ISSUE TITLE
Game View Scrolls when scrolling skill window with mouse wheel

### ISSUE THREAD

**Issue by Oseriduun** [suriyun-production/mmorpg-kit-docs#253]
Game view is zooming when trying to use the mouse wheel to scroll through the skills/spells list

skill/spell list scroll slows to nothing once main camera has fully zoomed out and does not allow itself to scroll to bottom.

mouse is hovered over skill/spell list when this is happening, which i feel is unintended behaviour

**Comment by insthync** [comment]
Fixed in 1.53d

**Comment by insthync** [comment]
I will close this, if it's still occurring, you can reopen it.
