### ISSUE TITLE
Npc Interacting Issue in SingleMode Build

### ISSUE THREAD

**Issue by Muhammad-Asim-Dev** [suriyun-production/mmorpg-kit-docs#2530]
When i interact NPC in window build single mode player do not interact but in  unityeditor and multiplayer interacting working fine anyone have solution

**Comment by insthync** [comment]
Want to see your NPC dialogs and NPC entity settings

**Comment by insthync** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/1f4eb5cf-6429-4403-a6ce-0ff4286c2938)

Try do this, if it not work then you can reopen this post.
