### ISSUE TITLE
[1.88f5] The same data Settings get different final damage.

### ISSUE THREAD

**Issue by MagicHope** [suriyun-production/mmorpg-kit-docs#2532]
This test is performed in the asset sample Demo.

1, set the player to 0 armor,100 damage, make sure its Atrributies, skills, etc., are set to 0.
2. Set OrcWarrio to 0 armor,100 damage, make sure its Atrributies, skills, etc. are set to 0.
Result: Player deals 100 damage to OrcWarrior and OrcWarrior deals 200 damage to player.
![OrcWarriorDMG200](https://github.com/user-attachments/assets/21a82893-84c1-410c-960f-08055e36ee6a)

3. Set OrcArcher to 0 armor,100 damage, make sure its Atrributies, skills, etc. are set to 0.
Result: Player deals 100 damage to OrcArcher,OrcArcher deals 100 or 200 damage to player.
![OrcArcherDMG100](https://github.com/user-attachments/assets/2f8aba00-02dd-456b-85f2-5c1fbbc86dcd)
![OrcArcherDMG200](https://github.com/user-attachments/assets/4c20a922-4aba-4aa1-8e42-8d5cec77f67e)

Wondering:
Given the same Settings, why do the player, OrcWarrior, and OrcArcher have 3 different damage?
What Settings should I check to make sure I get the same result.

**Comment by insthync** [comment]
How about monster level ?

**Comment by MagicHope** [comment]
Both are lv1

**Comment by insthync** [comment]
Orc archer deals 100 to 200 or random from 100 to 200?

**Comment by MagicHope** [comment]
Just 100 or 200, no other numbers

**Comment by insthync** [comment]
Okay, I will check it, it is really weird, it will be better if you can export the assets and send to my email: ittipon.bay@gmail.com so I won't have to setup it again (and might not same as yours)

**Comment by MagicHope** [comment]
I have used the blank project, imported the MMORPG Kit 1.88f5 and set the values for play, asher, and warrior.
I also exported the file and sent it to you by email .

**Comment by insthync** [comment]
Okay, it is working properly, for the archer it takes 200 damage sometimes because sometimes the arrow hitting player's head, head hitbox has 2x damage multiplier, so the randomed damage is 100, but it is hitting head then damage x2 so applying damage is 200

**Comment by insthync** [comment]
I will close this one, if you think it should be improved then create a new post and tell me how it should work.

**Comment by MagicHope** [comment]
Thank you very much for your patient answer.
It does not need to be changed because it is consistent from setup to result.
