### ISSUE TITLE
I Cannot Get Server Build

### ISSUE THREAD

**Issue by Gamadorium** [suriyun-production/mmorpg-kit-docs#2535]
Hello, good luck

I have been trying every way for almost 10 hours but I can't get a build for windows server. I create a shortcut to the "Exe" file in the resulting build and enter the necessary commands as in the documentation, but it never starts as a server, the game opens directly. Here are the methods I tried;

I clicked "Setup for mmo with server codes build" from the top menu and waited for it to compile and got the build again, but the process failed
![image](https://github.com/user-attachments/assets/71eba91a-8bb7-412b-8e80-fbf79a5b847d)

I clicked "Setup for mmo" from the top menu again and waited for it to compile and got the build again, but the process failed

I got a build in dedicated mode, but the process failed, no matter what I tried, I couldn't see the screen below
![image](https://github.com/user-attachments/assets/3ca5c9f5-239e-4098-b159-176253e04687)

"UNITY_SERVER" is actively added in the script define but it still doesn't work. Where exactly should I look or how can I find the problem? I would be glad if you could help me.

**Comment by Eniotnacram** [comment]
Hello,

No issues at all with building servers. You made mistakes and discord is made for that, not creating an issue here.
