### ISSUE TITLE
GM commands not work cross map server

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2537]
as title said, i dont know if im wrong but i thought gm commands would work cross map server in the past. but its not working anymore

aslong as CharacterA is in MapA and CharacterB in MapB you cant use any commands which are other character related like

/warp_character
/summon
/give_item
/summon

etc.

**Comment by insthync** [comment]
As I test, it is working

**Comment by moepi2k** [comment]
how? https://gyazo.com/8f3ebe084b543754a355405518fe9bf4
fresh kit 188f5

**Comment by insthync** [comment]
I don't know how too, it just works
https://youtu.be/g111LxJ9Rqg

Why don't you try from the core repo, you've requested for an accessible for that isn't it?

**Comment by moepi2k** [comment]
Yes your right i can try from core repo but i did not saw any changes recently for the gm command stuff. Btw test the warp_to_character command, thats the one i showed which is not working cross map and not the summon command

**Comment by moepi2k** [comment]
for this, i remember the thing is that some commands not work crossserver is because it lose target character via crossmap server.  but its really important  that you  commands work crossmap, if someone cheat u need to use ban or other commands to summon character to you or whatever. any ideas what or where need to make those changes?

**Comment by insthync** [comment]
My idea is just make it work, I don't believe that you are able to do it, you have to wait me to fix it, that is it.

**Comment by moepi2k** [comment]
Alright thx for info 👍

**Comment by insthync** [comment]
> for this, i remember the thing is that some commands not work crossserver is because it lose target character via crossmap server. but its really important that you commands work crossmap, if someone cheat u need to use ban or other commands to summon character to you or whatever. any ideas what or where need to make those changes?

After reproducing and re-reading this again, it is very annoying all commands that were mentioned, such as summon, and ban are working except warp_to_character, are you lying to me, I really hate it if you do.

**Comment by moepi2k** [comment]
hää what u talking about. it was just an example for crossmap commands. as it lose target character via crossmap. so yea. warp_to_character give_item etc not working.  

so whats the problem? i just reported a bug

**Comment by insthync** [comment]
The problem is it is working and I have to reproduce it again and again. It is very annoying.

**Comment by insthync** [comment]
And it is always working as shown here in the old video https://www.youtube.com/watch?v=g111LxJ9Rqg

**Comment by insthync** [comment]
I fixed it, that is it, if you really want to know why, you can check MMO repo.
