### ISSUE TITLE
[Animation Avatar Mask bool option]

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2538]
Hello it's me again.

It would be very usefull to add a bool to the action animation logic in PlayableCharacterModel to use the AvatarMask ONLY when the character is moving.

Usecase:

I got some attack animations that I would like to play FULLY when my character is not moving. But when he is, the legs need to be masked. So a bool in "AnimationPlayableBehaviour"  to enable or not the activation of the AvatarMask Only when moving for that specific animation.

**Comment by insthync** [comment]
:)

**Comment by Eniotnacram** [comment]
Hello,

I modified the necessary to add that. Very simply modifications.

- Added a bool with a tooltip
- Added the logic in "PlayAction" and "GetPlayingStateId" to use the new bool to activate the AvatarMask only when the character is moving. (If the bool is disabled it uses the default logic)

[Scritps.zip](https://github.com/user-attachments/files/16631779/Scritps.zip)

**Comment by Eniotnacram** [comment]
Let met add the script back. As my code didint have all the recent changes with the climbing logic and all.

**Comment by Eniotnacram** [comment]
Hello,

Made a pull request on core repo :)
