### ISSUE TITLE
There is a small problem regarding the crosshair

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2539]
**Describe the bug**

**To Reproduce**
1. Go to 'In the character controller'
2. Click on 'Crosshairs'

**Expected behavior**
There is a small problem regarding the crosshair when it touches a little the character the damage entity area collides with the same player and remains stuck in the same character here is an example video, I have already tried changing the layers and nothing although I have not tried other ideas but the truth is no idea.

**Screenshots**
Example video:"
https://imgur.com/KCx48Pp
**Desktop (please complete the following information):**
 - Version [1.86f]

**Smartphone (please complete the following information):**

**Additional context**
Nothig.

**Comment by moepi2k** [comment]
thats not a bug that behavior is intended. if you dont like it you can change GetAreaSkillGroundDetectionLayerMask

**Comment by Niinra** [comment]
> thats not a bug that behavior is intended. if you dont like it you can change GetAreaSkillGroundDetectionLayerMask

Where is that? I don't know if it seems like an error since the area damage entity collides with the player or directly the targeted one collides and a quick pvp will not result in the area damage entity where you are aiming but on top of the player

**Comment by insthync** [comment]
It pointed on your character, and in GetAreaSkillGroundDetectionLayerMask function (from game instance) is includes playing layer so it will pointed on your playing character, and then set aim position to where the character is stand

**Comment by insthync** [comment]
It is works as intended.

You can see how it works in `ShooterAreaSkillAimController` -> `UpdateAimControls_PC`, where the `GameplayUtils.ClampPosition`
function is calling,

In `GameplayUtils.ClampPosition` function it will find target by raycast from center of screen with mask value from `GameInstance.Singleton.GetTargetLayerMask()` function

If it hit target it will move the area pointer to the target's grounded position

**Comment by insthync** [comment]
In 1.89, it will have these settings 

![Screenshot_6](https://github.com/user-attachments/assets/d1393f31-0ab5-4986-a5d0-7f7abe3e060e)
