### ISSUE TITLE
Language change issue.

### ISSUE THREAD

**Issue by wtfcolt** [suriyun-production/mmorpg-kit-docs#254]
If you are in 'English', pick up some quests, and switch to 'Cat', then switch back to 'English', some text remains in 'Cat' until logout/login again.

![image](https://user-images.githubusercontent.com/1743424/75715641-bc79b300-5c9b-11ea-9643-ea1e7f7a8dfe.png)

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
This was fixed in 1.54
