### ISSUE TITLE
[Addon] Add next quest - working code

### ISSUE THREAD

**Issue by khongtuong** [suriyun-production/mmorpg-kit-docs#2540]
I share an addon that assigns the next quest when completion of the current one, which could be useful for many MMORPGs, I believe.

Add to Quest.cs
In my case, I'm creating a partial class for Quest.
```
        [Header("AutoAssignQuest Settings")]
        [SerializeField] private Quest[] nextAssignQuest = new Quest[0];
        [FormerlySerializedAs("autoTrack")]
        public bool autoTrackQuest;

        public Quest[] NextAssignQuest
        {
            get { return nextAssignQuest; }
            private set { nextAssignQuest = value; }
        }
```

UnityMultiplayerARPG\Core\Scripts\Gameplay\CharacterEntity\PlayerCharacterEntity\BasePlayerCharacterEntity_QuestFunctions.cs
In my case, I use updatedata with UICharacterQuest to verify completion before adding the next one; however, this becomes complex when it involves dialogue with NPC quests

`public virtual bool CompleteQuest`
around 180 add below 
```
            // Add skill points
            checked
            {
                SkillPoint += quest.rewardSkillPoints;
            }
```
add below: 
```
            // add next quest
            if (quest.NextAssignQuest.Length > 0)
            {
                foreach (Quest nextQuest in quest.NextAssignQuest)
                {
                    //already has quest?
                    int indexOfNextQuest = this.IndexOfQuest(nextQuest.DataId);
                    if (indexOfNextQuest >= 0)
                        continue;

                    //add and track quest
                    this.AcceptQuest(nextQuest.DataId);
                    this.ChangeQuestTracking(nextQuest.DataId, true);
                }
            }
```
Hope that you'll add to the core, have a nice day.

**Comment by insthync** [comment]
What if we abandon the quest?

**Comment by khongtuong** [comment]
> What if we abandon the quest?

Typically, this is used in the main quest and cannot be abandoned. If a user somehow abandons the quest, a custom action dialog on the server can re-add the quest at the abandon dialogue.

**Comment by insthync** [comment]
can abandon option should be added to quest

**Comment by insthync** [comment]
And from your codes, it must update quest tracking in accept function, not in complete function

**Comment by insthync** [comment]
Added, thank you!
