### ISSUE TITLE
AimPosition ProjectileDamageEntity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2543]
hey i want to extend the projectileDamageEntity.

the recalculatespeed only works if you have lockettarget.
but for shooter or aimatcursor controler (or any other) you dont have it so it wont work.

in this case i need the aimposition of the player like

https://gyazo.com/bfe77efc1d52215a69a9eea89babefd5

but this not working it AimPosition.position always is the vector3 of the player becasue missile use directional. i tried follow the areadamageentity becasue there you instantiate the dmg entity at mouse position, but i dont know how to get that vector for missile?

**Comment by insthync** [comment]
What you actually want?

- Extend projectile damage entity?
- Or just want to get vector?
- WTF?

**Comment by moepi2k** [comment]
actually what i was needed is that the projectile spawn at specific transform. i used the transform from the equipmententity -> missiledamagetransform. but that not fully worked since i used it and somehow it not followed correctly. i made a new damageinfo like that   public override void LaunchDamageEntity(BaseCharacterEntity attacker, bool isLeftHand, CharacterItem weapon, int simulateSeed, byte triggerIndex, byte spreadIndex, Vector3 fireStagger, List<Dictionary<DamageElement, MinMaxFloat>> damageAmounts, BaseSkill skill, int skillLevel, AimPosition aimPosition)
  {
      // Spawn missile damage entity, it will move to target then apply damage when hit
      // Instantiates on both client and server (damage applies at server)
      if (missileDamageEntity == null)
          return;

      // Get generic attack data
      EntityInfo instigator = attacker.GetInfo();
      System.Random random = new System.Random(unchecked(simulateSeed + ((triggerIndex + 1) * (spreadIndex + 1) * 16)));
      Vector3 stagger = new Vector3(GenericUtils.RandomFloat(random.Next(), -fireStagger.x, fireStagger.x), GenericUtils.RandomFloat(random.Next(), -fireStagger.y, fireStagger.y));
      //this.GetDamagePositionAndRotation_Hubi(attacker, isLeftHand, aimPosition, stagger, out Vector3 damagePosition, out Vector3 damageDirection, out Quaternion damageRotation);

      // Adjust the spawn Position at Weapon
      Vector3 damagePosition = attacker.CharacterModel.GetRightHandMissileDamageTransform().transform.position;

      // Calculate the new direction towards the aim position
      Vector3 aimDirection = (attacker.TargetAimPosition - damagePosition).normalized;

      // Apply the stagger offset to the aim direction
      Quaternion aimRotation = Quaternion.LookRotation(aimDirection);
      aimRotation = Quaternion.Euler(aimRotation.eulerAngles + stagger);

      Vector3 damageDirection = aimRotation * Vector3.forward;
      Quaternion damageRotation = aimRotation;

      // Prepare hit reg data
      HitRegisterData hitRegData = new HitRegisterData()
      {
          SimulateSeed = simulateSeed,
          TriggerIndex = triggerIndex,
          SpreadIndex = spreadIndex,
          LaunchTimestamp = BaseGameNetworkManager.Singleton.Timestamp,
          Origin = damagePosition,
          Direction = damageDirection,
      };

      DamageableEntity lockingTarget;
      if (!hitOnlySelectedTarget || !attacker.TryGetTargetEntity(out lockingTarget))
          lockingTarget = null;

      // Instantiate missile damage entity
      float missileDistance = this.missileDistance;
      float missileSpeed = this.missileSpeed;
      PoolSystem.GetInstance(missileDamageEntity, damagePosition, damageRotation).Setup(instigator, weapon, simulateSeed, triggerIndex, spreadIndex, damageAmounts[triggerIndex], skill, skillLevel, hitRegData, missileDistance, missileSpeed, lockingTarget);
  } and it works. only weird thing is. when i debug a raycast from missiledamagetransform to aimposition the start is not the missiledamagetransform. maybe i just need to track down why it happen
