### ISSUE TITLE
Animation behavior not the same

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2544]
Hello,

I got a real weird problem, my root motion animation doesnt work when im only using the game view, but if I split the view and i have the editor view and the game view at the same time, the root motion works... How is this happening...
You can see, the first attack, my character doesnt go up but the next one he does.... (when I got the Editor view open) What is this how im supposed to figure out what is the problem 😂

RM and skip movement validation is enabled on my skill.

I tried to play with all possible settings, using the skill MULTIPLE times.. It never works in client build or in unity editor if I only use the game view. But as soon as I open the Editor view, now the root motion of the animation is correctly applied. It makes no sense to me

https://github.com/user-attachments/assets/60c8cb1e-baab-46d2-9065-d15b36971482

![Screenshot 2024-08-30 082638](https://github.com/user-attachments/assets/76801451-79ca-4f89-bd40-094a98897b47)

**Comment by Niinra** [comment]
Did you try to compile the game and see if everything works normally, if so you could ignore it

**Comment by Eniotnacram** [comment]
Yes I did client build to test and the animations is not played correctly either. I really think there is an issue with Y root motion

**Comment by Eniotnacram** [comment]
You can see here the collider stays on the floor even if the character jumped. (thats what happen when Y is baked and no root motion for Y is applied)

![Screenshot 2024-08-30 201639](https://github.com/user-attachments/assets/9bf325f5-9deb-44c4-9d73-e12ec446f3eb)

**Comment by insthync** [comment]
The character must jump because of animation right?
then the collider must be on ground or not?

**Comment by Eniotnacram** [comment]
Yes because Y is not baked, the root of the character (all the armature) should be going up. So in that case, the collider should follow the character so going up. If the animation is baked (no rootmotion) then the the root should not move and this is working properly.

The issue seems that the Y rootmotion is simply not applied.

**Comment by insthync** [comment]
How it should be?

It must moving up by root motion, not just a animatio?

**Comment by Eniotnacram** [comment]
In the playable animation setting, (action) the bool "shouldUseRootMotion" is enabled, meaning the animation's root motion should be used for that action. It works for the Root transform position (XZ), but for the root transform position (Y) it doesn't. My animations on the server do NOT have the Y root motion applied. Even if the bake-into-pose option on the animation itself is disabled as shown in the picture.

If bake into pose was enabled, then the root should stay at 0 0 0 (baked). But as it is disabled, the root of my character should move UP (Y) as the animation does.

In the video I sent you. The first time I do the animation you can see that the character is NOT going up. For some reason when I open the editor window, the character do Go up and Y root motion works (but only client) on server and the other players do NOT see my character going up.

**Comment by Eniotnacram** [comment]
So in other words, as the actual animation have root motion in the Y direction, and useRootMotion is enabled on the playable animation, the Y root movement should be applied to the animations, but it's not.

**Comment by moepi2k** [comment]
here in mmo environment 2 clients with not y axis baked

https://gyazo.com/b84887efa1ef5e10011542d43659c569

everythings fine with rootmotion

**Comment by Eniotnacram** [comment]
Then what could be my issue? Root motion Y axis is not applied on server for skill animations. Is there any unity settings I need to check?

**Comment by Eniotnacram** [comment]
Ayt, I tested on brand new fresh kit, it works.. But man I have nothing modified for that logic.... Using humanoid avatar like the kit.. everything is the same, I dont get it

**Comment by Niinra** [comment]
Mhm, check inside your character how the objects are arranged because they may not be anchored to the bones of the character

**Comment by Eniotnacram** [comment]
Yes :( all from root but even with default character from kit. Almost everything is not patented to the root (armature) but instead simply the parent of the character and it still works

**Comment by Eniotnacram** [comment]
No clue what fixed it but it's fixed now. Played a little bit with the hiearchy on my character, rebuilt DB and serv from scratch, did a lot of stuff and now it works.
