### ISSUE TITLE
Auction House some errors

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2545]
I have just updated AuctionHouse codes but I am having with some errors like ConfigManager and like these,

Assets\UnityMultiplayerARPG_AuctionHouse-main\Scripts\Networking\REST\AuctionRestClient.cs(18,88): error CS0117: 'GameInstance' does not contain a definition for 'AccessToken'

Assets\UnityMultiplayerARPG_AuctionHouse-main\Scripts\Networking\REST\AuctionRestClient.cs(18,101): error CS0103: The name 'BearerAuthHeaderSettings' does not exist in the current context

Assets\UnityMultiplayerARPG_AuctionHouse-main\Scripts\Networking\REST\AuctionRestClient.cs(49,114): error CS0103: The name 'ApiKeyAuthHeaderSettings' does not exist in the current context

Assets\UnityMultiplayerARPG_AuctionHouse-main\Scripts\Networking\BaseGameNetworkManager_AuctionHouse.cs(60,41): error CS0103: The name 'ConfigManager' does not exist in the current context

**Comment by insthync** [comment]
Please use the older version of auction house service or wait for a new version of the assets

**Comment by temelkirci** [comment]
I do not have older version.Please can you share older version with me for V1.88?

**Comment by insthync** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_AuctionHouse/commits/v1

**Comment by temelkirci** [comment]
@insthync Thank you
