### ISSUE TITLE
Animation issue after dead

### ISSUE THREAD

**Issue by temel61** [suriyun-production/mmorpg-kit-docs#2547]
All mobs and characters have this issue after dead.they do not stick to ground, stay like that until destroy.How can I fix it?

![Image Sequence_020_0000](https://github.com/user-attachments/assets/6921c5f8-88be-4fa1-a7a0-8ed1aa6cd1bf)

**Comment by insthync** [comment]
How is the end of animation? is the animation played until its end?

**Comment by temelkirci** [comment]
https://drive.google.com/file/d/1_IZWJp7Yl-NrhpJHMrvqqMfgi1n3INRu/view?usp=sharing

**Comment by insthync** [comment]
Wow you can implement the knock back by yourself, great :)

From the video, it seems like the animation is not end yet, right?

**Comment by temelkirci** [comment]
It is easy to implenet dashing (knock back) by applyforce function.It seems the animation end properly.

But I am not sure it is about navmesh or character collider or collision matrix or code ?.I also have same issue for all mobs.I follow your default characters settings in kit.

**Comment by temel61** [comment]
@insthync Ahh yes I think you are right.I realized that All animations never end.Included attack animation also.
