### ISSUE TITLE
Add posibility to copy root bone by skinned mesh render on equip container

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#255]
For example you have 5 skinned render mesh on character prefab - you want to make separate prefabs as variants but if they are skinned mesh they require root bone to work correctly. 

It would be nice if out of the box equipment setter could set this bone on new instanced prefab.

**Comment by insthync** [comment]
Like this? https://www.youtube.com/watch?v=OF1webwzUuY&list=PLPc4hSd4HARf107_w22XkU0BffC8t2T8O&index=4

**Comment by poaq** [comment]
With your method something like that happen: https://gyazo.com/681b1108030b413874feaaedc40be106

Whats so funny when you back to lobby it start to animate again. 
https://gyazo.com/85c2c66fac94ce9c2de537fb5fd6c8a6

Character Prefab:
https://gyazo.com/3f5c1909e2d4dbaef3b80a5201ea3ab6
https://gyazo.com/c83da65ff5c323c2475e9aa92a545b78
https://gyazo.com/06f5d3e09e5465ed666db0a70264db1b

Example Item Prefab:
https://gyazo.com/d8a89cdbb8f47c1b8025cf1d2d7e9e4b
https://gyazo.com/f4004a65cfaeff4131649606436daaf8

From my point of view when item is instancable on character it lose root bone. Maybe we could find a possibility to attach root bone from character to the item when its switched by equipment setter ?

Sth like: 

```
[SerializeField] GameObject targetSkin;
    // Use this for initialization
    void Start () {
        SkinnedMeshRenderer mySkin = GetComponent<SkinnedMeshRenderer>();
        mySkin.rootBone = targetSkin.GetComponent<SkinnedMeshRenderer>().rootBone;
    }
```

**Comment by poaq** [comment]
It can be closed - i find the solution - activate cull completly.
