### ISSUE TITLE
Where to get Update 1.89?

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#2550]
Hello Suri,

i´m sorry to use the Issue reporting this way. I saw in the changelog that the update 1.89 is ready. but neither the unity store nor your invoice page has this version available. i thought i waited for a few days, but even after waiting there is no new version in the unity store.

Is this on purpose or have i missed something?

best regards

**Comment by insthync** [comment]
It was rejected by Unity team, try to make changes as their requests and try it again.

Uploaded to my web page.
