### ISSUE TITLE
Many errors in version 1.89b

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#2551]
Hi , when i test the new version in fresh project using unity version 2022.3.44 f1, i get those 42x errors when i start the game and also when i move to any map 
![1](https://github.com/user-attachments/assets/ca71f4f2-cb58-4e94-812f-287ea0e17dd4)

**Comment by insthync** [comment]
It is because there is no addressable settings included in the demo, seems like I have to delete addressable demo.

**Comment by RunOrDi3** [comment]
-.-

**Comment by insthync** [comment]
What?

**Comment by RunOrDi3** [comment]
nothing boss , thanks alot for this update .. you did a good job <3

**Comment by johnmoney** [comment]
Tracked it down to the AddressablePrefab set in scene Map001 for all the spawners. Remove the reference, errors go away.
![image](https://github.com/user-attachments/assets/cb5c841b-1f65-4942-98ff-95aa2a8fa749)
