### ISSUE TITLE
How can I remove all adressable system form KIT?

### ISSUE THREAD

**Issue by temel61** [suriyun-production/mmorpg-kit-docs#2552]
New adressable system ruins everythink in my project.How can I remove all system from my project.I do not want to use it

**Comment by insthync** [comment]
Just don't use it, that is it, It didn't force you to use it.

**Comment by insthync** [comment]
I try to reduce memory usage by implement it, then you want me to remove :(

**Comment by temel61** [comment]
@insthync I am very appreciate about it.But I have some problem about loading adressables.Maybe I make a mistake about using it.Please can you tell me adressable settings for client and server build.Which scene should I check as adressable for client and server?.I am using these settings for server build but sometimes gettings error.I also have problem about your adressable download demo.Can you explain me about initial objects?

![Ekran görüntüsü 2024-09-09 094443](https://github.com/user-attachments/assets/ac5f9e1d-a0d0-4a18-b73b-ccbd77fd27d2)

![Ekran görüntüsü 2024-09-09 094457](https://github.com/user-attachments/assets/abad3638-3003-4d5f-b0af-fd4931c84b5d)

![Ekran görüntüsü 2024-09-09 094521](https://github.com/user-attachments/assets/49dfae2e-2f0a-49be-b2a1-28fdc8f20def)

![Ekran görüntüsü 2024-09-09 094916](https://github.com/user-attachments/assets/18f4bf6e-20c6-4c19-8f9b-4da34435d058)

![Ekran görüntüsü 2024-09-09 094927](https://github.com/user-attachments/assets/49c7fdb1-5c2f-4766-bbf9-cd6933b9b16d)

![Ekran görüntüsü 2024-09-09 094410](https://github.com/user-attachments/assets/d7761ddd-5389-4b77-80f0-e2915221172f)

**Comment by insthync** [comment]
You can use only one init scene up to how you setup it to download files and load scene after that.

**Comment by temel61** [comment]
![Ekran görüntüsü 2024-09-11 042427](https://github.com/user-attachments/assets/c43915db-97ee-4334-b1f0-10c1babc8b04)

This is my android client setup.But I am having error during download.Not key founded error.Are my Initial objects set properly?.

**Comment by temel61** [comment]
![Ekran görüntüsü 2024-09-11 042427](https://github.com/user-attachments/assets/9e305c13-ef1f-41e3-956a-44f48ca9fc6a)
![Ekran görüntüsü 2024-09-11 042636](https://github.com/user-attachments/assets/75dcaa37-c4e9-4a43-803f-8a0bb1699560)

![Ekran görüntüsü 2024-09-11 042733](https://github.com/user-attachments/assets/f3aa18f7-55bc-4dd3-831b-027bfcc743a2)


![Ekran görüntüsü 2024-09-11 042704](https://github.com/user-attachments/assets/4bff2153-27e4-47a3-854e-9a13892cf8fa)
![Ekran görüntüsü 2024-09-11 042717](https://github.com/user-attachments/assets/40566bd8-6269-4d94-9a04-8483006cbe10)


Can you check my settings on picture?

**Comment by temel61** [comment]
how can I disable addressable ?
