### ISSUE TITLE
Move animation issue for non owner client

### ISSUE THREAD

**Issue by temel61** [suriyun-production/mmorpg-kit-docs#2554]
I have a floating move animation issue for non owner client.

https://drive.google.com/file/d/1dms_j19gxBS2uImEclmg076wk6VrMuB1/view?usp=sharing

**Comment by insthync** [comment]
Did you check movement state on non-owner client yet?, how is it?

**Comment by temel61** [comment]
How can I check it?

**Comment by insthync** [comment]
PlayerCharacterEntity entity;

entity.MovementState

**Comment by RunOrDi3** [comment]
@temel61 Have you bought kit to get support ? if yes send your invoice number in discord and you will get support

**Comment by insthync** [comment]
@RunOrDi3 I actually want everyone to ask me here, if you want to get support from me.

**Comment by RunOrDi3** [comment]
i see , i just saw him in discord didn't sent his invoice and there are many ppl use kit from pirate sites

**Comment by insthync** [comment]
Oh, I see

**Comment by temel61** [comment]
@RunOrDi3  @insthync  Here 
IN010201948634

**Comment by temel61** [comment]
![Ekran görüntüsü 2024-09-15 154651](https://github.com/user-attachments/assets/e2ca834f-55d5-4e71-9651-6a2b147e5269)


It looks None for Non owner client.

            if(IsOwnerClient)
            {
                Debug.Log("Me : " + MovementState.ToString() + "     " + ExtraMovementState.ToString());
            }
            else
            {
                Debug.Log("Other : " + MovementState.ToString() + "     " + ExtraMovementState.ToString());
            }

**Comment by insthync** [comment]
Yep, I don't why yet, did you make changes to movement classes?

**Comment by temel61** [comment]
Are you sure it works in V1.89 properly?

**Comment by insthync** [comment]
Yes, I am using it in my project.

Why do you always have unique issues?

**Comment by temel61** [comment]
Because I am unique person and have unique project :). By the way I think I can fix it myself but I am open to your any trick or help :)

**Comment by insthync** [comment]
I don't know what you did to your project, so I have no any idea to help you. I can't reproduce any of your bugs, including the dying animations.

**Comment by temel61** [comment]
I did nothing about animations in my projects, but I think these can be problem for my project -> 3d model import settings, character mask and avatar, navmesh surface, wrong animation clip settings.By the way ping look minus, I check old topic here , I update my rttcalculate class but still same

**Comment by RunOrDi3** [comment]
Show me a video !

**Comment by temel61** [comment]
@RunOrDi3 Already here https://drive.google.com/file/d/1dms_j19gxBS2uImEclmg076wk6VrMuB1/view?usp=sharing

**Comment by RunOrDi3** [comment]
your animation stop at the end of frame and start again ? because the video not clear

**Comment by reidsneo** [comment]
@insthync  @temel61 
just for notice, please remove the IN number above, it can lead to another pirate

**Comment by insthync** [comment]
@reidsneo Thank you :)

**Comment by temel61** [comment]
Still same even in V1.89

**Comment by insthync** [comment]
I can't reproduce it, I never found this issues, can you send me your animation file with its setting to test?

**Comment by insthync** [comment]
Oh, this is not a dead animation issue, so you don't have to send an animation file

**Comment by insthync** [comment]
The problem is it is not grounded, right?

then why?

did you make changes to entity movement codes?

And it's always only you having issues that can't be reproduced.

**Comment by temel61** [comment]
Mobs does not have this issue.Only players have it.I thaught It cause due to high ping but all players reported it to me even they have low ping.Somewhere set Nonownerclient walking animastion as None, I am trying to find which line set MovementState as None.

if(IsOwnerClient)
        {
            Debug.Log("Me : " + MovementState.ToString() + "     " + ExtraMovementState.ToString());
        }
        else
        {
            Debug.Log("Other : " + MovementState.ToString() + "     " + ExtraMovementState.ToString());
        }

![367582484-e2ca834f-55d5-4e71-9651-6a2b147e5269](https://github.com/user-attachments/assets/0a919e15-81b5-4c6a-94b3-c5d0c1fcf74e)

**Comment by temel61** [comment]
@insthync I solved dead animation issue.I delete dead animation clip first 5 frame and last 5 frame.But I could not fix non owner clientwalking animation issue.

**Comment by temel61** [comment]
@insthync  I removed navmeshagent and added character controller system and my issue was solved like that.I am closing this post.

**Comment by insthync** [comment]
Okay then I will try the nav mesh entity movement, this has to be fixed

**Comment by insthync** [comment]
Now I hope you will see the important of issues information, you just didn't tell me that you use navmeshentitymovement then I just not able to reproduce, and it takes an hours to reproduce.
