### ISSUE TITLE
Kits Have Compiler Errors at Start

### ISSUE THREAD

**Issue by SodosTheDeveloper** [suriyun-production/mmorpg-kit-docs#2556]
As I followed the instructions,
the compiler has errors,
it can't build the stock video game,
and can't be played.

![image](https://github.com/user-attachments/assets/ebbefd64-305a-4ac0-b515-93279579c9e1)

**Comment by insthync** [comment]
Try find Zstring in both assets and packages , I want to know is it redundant or not

**Comment by SodosTheDeveloper** [comment]
It's not there.

**Comment by insthync** [comment]
Send me your AnyDesk number to my email: ittpon.bay@gmail.com, then I will check it, all packages are included if you have problems then it is because of your setup

**Comment by SodosTheDeveloper** [comment]
Hello what is your discord name,
So we may connect first at the right time then I can let you AnyDesk it?
________________________________

**Comment by insthync** [comment]
I don't use Discord, it is too disturbing me

**Comment by SodosTheDeveloper** [comment]
Oh, do you have Steam. Or WhatsApp?
________________________________

**Comment by insthync** [comment]
Can you just send me your AnyDesk number to my email and make an appointment?

**Comment by SodosTheDeveloper** [comment]
Ok, that makes sense,
1 047 378 370
________________________________

**Comment by insthync** [comment]
Entering

**Comment by SodosTheDeveloper** [comment]
Thanks,
One question...
Do I distribute the client able to download for those normally,
As do they login the same server when I am playing it?

For population entrance, server joining, and I am the host some how.
________________________________

**Comment by insthync** [comment]
I don't understand the question

**Comment by SodosTheDeveloper** [comment]
Oh, ok, never mind.
I had to check further to understand.
________________________________

**Comment by SodosTheDeveloper** [comment]
How do I change your models to my models of 3D character player graphics?
________________________________

**Comment by SodosTheDeveloper** [comment]
Hello again,
The script corrupted to 20 problems,
That I was making levels, and then was about to test it,
Now it has an animator problem, I can't seem to move, then the
Script just freezes now,
Help if you can?
________________________________

**Comment by SodosTheDeveloper** [comment]
Hello,
How do I start the MMO version?
I am trying to create warps and it fails, the starter warp doesn't appear in the list.
________________________________

**Comment by insthync** [comment]
Create new posts for those question
