### ISSUE TITLE
[FEATURE REQUEST] Additional Special/Critical Damage Rates

### ISSUE THREAD

**Issue by lunidel** [suriyun-production/mmorpg-kit-docs#2558]
I would like to request an expanded Critical Damage feature. 

Currently we only have 1 which is focused Critical Rate and Critical Damage Rate

![image](https://github.com/user-attachments/assets/b9ec7cb0-d0e3-4947-8907-2b0c19ec4c97)

I was hoping if we could expand it just so we can create more damage types and damage rates 

Ex.
From Equipment Set Options I would like it to have Double Damage Rates or Triple Damage Rates

to do this with our current default, I would have to set Critical Damage rate to 2 ( 200% ) or 3 ( 300% ) but the problem is they all share only 1 Critical rate and all options that applies to Critical Damage Rate will be added as a whole.

It would be great to add separate Critical Rates or Special Damage Rates depending on the Damage Type and design of our game.

It can be Critical Rate 1, 2, and 3 and has it's own controllable Critical Damage Rate 1, 2 and 3 as well. 

This is so we can have these bonus options added for our Weapons, or Sets, or even buffs.

**Comment by moepi2k** [comment]
you can make ur own gameplayrule. just inherit from the the base gameplayrule and add ur own logic

**Comment by insthync** [comment]
No, because you never paid for anything
