### ISSUE TITLE
[FEATURE REQUEST] Reflect Damage / Return Damage

### ISSUE THREAD

**Issue by lunidel** [suriyun-production/mmorpg-kit-docs#2559]
I would like to request a feature that gives Bonus Option to items for Reflecting or Returning Damage inflicted on you.

It should be controlled with Reflect Rate ( Chance to return damage ) and Reflect Damage Rate ( % of damage to be reflected ).

Ex. If you get hit with 100 damage, and you have 10% Reflect Rate ( 10% chance to return damage ) and Reflect Damage Rate of 20%

you Return 20 damage to the enemy.

**Comment by insthync** [comment]
No, because you never paid for anything
