### ISSUE TITLE
Question : How to keep turn on the campfire when map change?

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#256]
I understood this kit does not save the status of buildings. 
Can you give me a clue how to add the status of building, to save its processing time?
I'm now looking BuildingSaveData.cs and trying to add new save data like "public float processingTime;" to make campfire save its status(if processing time is not zero, it is turn on) and keep continue the processing.
Any hints or advice will be highly appreciate.

**Comment by dglee2592** [comment]
![image](https://user-images.githubusercontent.com/58107601/75846538-02f81a80-5e20-11ea-9440-be34f9c44dba.png)
I tried to add new savedata to almost of related code but still not working.. 
Any clue will be highly appreciated.

**Comment by dglee2592** [comment]
This image show where I add the new data variable.
![image](https://user-images.githubusercontent.com/58107601/75846759-9e898b00-5e20-11ea-82f0-00c4b1822dec.png)

**Comment by insthync** [comment]
For an MMO games, it's currently still turn on after moved to other maps. For offline games, when teleport to other maps it will have to add fields you want to save to IBuildingSaveData.cs, then implement save fields to BuildingEntity. Implement the clone function in BuildingSaveDataExtension.cs. Implement serialize surrogate in BuildingSaveDataSerializationSurrogate.cs

**Comment by insthync** [comment]
I would add just 1 field called ExtraData, then in CampFireEntity.cs, I will implement the field like this:
```

        public override string ExtraData
        {
            get
            {
                return new StringBuilder().Append(IsTurnOn ? byte.MaxValue : byte.MinValue).Append(':').Append(TurnOnElapsed).ToString();
            }
            set
            {
                if (string.IsNullOrEmpty(value))
                    return;
                string[] splitedTexts = value.Split(':');
                byte isTurnOn;
                if (splitedTexts.Length == 2 && byte.TryParse(splitedTexts[0], out isTurnOn))
                    IsTurnOn = isTurnOn != 0;
                float turnOnElapsed;
                if (splitedTexts.Length == 2 && float.TryParse(splitedTexts[1], out turnOnElapsed))
                    TurnOnElapsed = turnOnElapsed;
            }
        }
```

**Comment by dglee2592** [comment]
Thank you very much!!!
I made it works!
I'll close this ticket! Thanks again!
