### ISSUE TITLE
The type or namespace name 'AddressableAssets' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by jacobjgrant** [suriyun-production/mmorpg-kit-docs#2561]
**Describe the bug**
I have just purchased the kit and created a new project in unity 2022.3.16f1 and I have 86 errors.
It has something to do with the new addressable system.

**To Reproduce**
Install a new project

**Expected behavior**
It to work. Can you please tell me what I need to do to resolve this?

![image](https://github.com/user-attachments/assets/5b2693e3-9160-4b1f-a063-53b41a34bb20)

**Comment by Niinra** [comment]
![image](https://github.com/user-attachments/assets/e2141de2-3546-4ba3-b1ee-328fda787e78)
go here
![image](https://github.com/user-attachments/assets/868b72fb-b00c-4593-b9e9-18d400158964)
install this package

**Comment by jacobjgrant** [comment]
Perfect thats great. Also had to install the input system as well.
