### ISSUE TITLE
Random portal Spawner

### ISSUE THREAD

**Issue by jacobjgrant** [suriyun-production/mmorpg-kit-docs#2562]
I would like to create a random portal system so that random instance portals are spawned over the map area like the mobs or harvestable items.

When the portal is used up, its destroyed and a new one is randomly spawned in.

Can anyone help with this?

**Comment by insthync** [comment]
Seems like it must have randomed warp portal entity, and a instanced map-server for that, right?

**Comment by jacobjgrant** [comment]
Not sure mate. This is why I was asking. I didn't know what would be the best way to attack this. Any help is appreciated.

**Comment by Eniotnacram** [comment]
You simply need to make a new WarpPortalEntity and makes the position an array that you set in editor. And at runtime it randomly gets a value from that array to teleport the players
