### ISSUE TITLE
MapNetworkManager.SetPlayerReadyRoutine Error in MMO v1.89

### ISSUE THREAD

**Issue by temel61** [suriyun-production/mmorpg-kit-docs#2563]
ERROR No Tag [2024-09-26 09:40:18] - NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.MMO.MapNetworkManager.SetPlayerReadyRoutine (System.Int64 connectionId, System.String userId, System.String accessToken, System.String selectCharacterId) (at D:/M3 Mobile/Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Networking/Map/MapNetworkManager.cs:585)
[Log_Map(Town)-Ch(1)-Alloc(False)-Instance().err.log](https://github.com/user-attachments/files/17146269/Log_Map.Town.-Ch.1.-Alloc.False.-Instance.err.log)

**Comment by insthync** [comment]
Are you going to use addressable assets or not?

**Comment by temel61** [comment]
I am using addressable, but now I added my characters as prefab , I will try both because server cannot find my character to spawn in map.It works for LAN singleplayer.Any advice?

**Comment by temel61** [comment]
I think spawnobj is null

LiteNetLibIdentity spawnObj = Assets.GetObjectInstance(
                GameInstance.GetPlayerCharacterEntityHashAssetId(playerCharacterData.EntityId, out metaDataId),
                playerCharacterData.CurrentPosition,
                characterRotation);

            // Set current character data
            BasePlayerCharacterEntity playerCharacterEntity = spawnObj.GetComponent<BasePlayerCharacterEntity>();

**Comment by insthync** [comment]
Yes, it is relates to previous post which you choose to fix it by return true even when the data is incorrect and unable to load

**Comment by temel61** [comment]
I do not see any error during loading assets.It seems added BasePlayerChaarcterEntities successfully.

 INFO No Tag [2024-09-26 09:37:39] - BasePlayerCharacterEntity->PrepareRelatesData
 INFO No Tag [2024-09-26 09:37:43] - BasePlayerCharacterEntity->PrepareRelatesData
 INFO No Tag [2024-09-26 09:37:45] - BasePlayerCharacterEntity->PrepareRelatesData
 INFO No Tag [2024-09-26 09:37:50] - BasePlayerCharacterEntity->PrepareRelatesData
 INFO No Tag [2024-09-26 09:37:53] - BasePlayerCharacterEntity->PrepareRelatesData
 INFO No Tag [2024-09-26 09:37:54] - BasePlayerCharacterEntity->PrepareRelatesData
 INFO No Tag [2024-09-26 09:37:55] - BasePlayerCharacterEntity->PrepareRelatesData
 INFO No Tag [2024-09-26 09:37:56] - BasePlayerCharacterEntity->PrepareRelatesData

**Comment by temel61** [comment]
maybe sometings wrong here


        public static int GetPlayerCharacterEntityHashAssetId(int entityId, out int? metaDataId)
        {
            metaDataId = null;
            if (PlayerCharacterEntityMetaDataList.TryGetValue(entityId, out PlayerCharacterEntityMetaData metaData))
            {
                metaDataId = metaData.DataId;
                return metaData.GetPlayerCharacterEntityHashAssetId();
            }
            else if (AddressablePlayerCharacterEntities.ContainsKey(entityId))
            {
                return entityId;
            }
#if !EXCLUDE_PREFAB_REFS
            else if (PlayerCharacterEntities.ContainsKey(entityId))
            {
                return entityId;
            }
#endif
            return 0;
        }
