### ISSUE TITLE
UIAddressableAssetDownloadManager does not update progress on UI

### ISSUE THREAD

**Issue by temel61** [suriyun-production/mmorpg-kit-docs#2565]
UIAddressableAssetDownloadManager does not update progress bar and text.It only update Initializing text after It downloaded all assets.

**Comment by temel61** [comment]
I think somethings block the UI system during download.

**Comment by insthync** [comment]
Do you able to built addressable asset?

**Comment by temel61** [comment]
yes I can.I waited 5 minutes after start game in home scene.My map load successfully now 5 minutes later.I tried it second time, It open so fast, not delayed.Somethings happend fist time loading scenes.

**Comment by insthync** [comment]
Yesterday you can't what did you do then?

**Comment by temel61** [comment]
It happens me after upgrade kit to V1.89.It was working in 1.88 properly.

**Comment by insthync** [comment]
I don't want to hear about it, if you mentioning 1.88 again, I will stop helping you.

Yes, I try it everyday, are you sure that you've build addressable asset properly, yesterday you said you found an error when build addressable so assuming it is not built properly.

**Comment by insthync** [comment]
You mentioning about older version more than 10 times, very annoying, why don't we just do anything to make the current version works, I don't try to find issues from current version?

**Comment by temel61** [comment]
@insthync I tell you broke sometings in V1.89. Just try it in v1.89 yourself and let me know If you can not find any problem in your project, that's mean I have wrong someting in my project.I am sure nobody use this kit in deeply expect me.

**Comment by insthync** [comment]
I use it everyday.

**Comment by insthync** [comment]
Just make sure that you've built addressable properly with no errors first.

**Comment by temel61** [comment]
I think I have some missing scriptables in different folders, but ok I will fix it but I have around 2000 game data and entities in my gamedatabse.You should not try a few gamedata in fresh kit, you can not reproduce it like that, not enough data.If you are pretty make sure just like loading addressable yesterday, I will close this issue.

**Comment by temel61** [comment]
@insthync Tell me how many gamedata and entities in your project.I am sure you always try it a few low poly basic game data and entities.I work with huge project around 20-25 GB.I have 700 mb adressable data in remote server.

**Comment by insthync** [comment]
![Screenshot_198](https://github.com/user-attachments/assets/1c5b5578-16d1-4240-90db-5cedab0a5f46)

addressable size is around 1 GB, is it enough info?

**Comment by temel61** [comment]
ok.you say me I do not have any loading and downlaod asset issue and additive scene issue in your project in V1.89.I will close this post.
