### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SodosTheDeveloper** [suriyun-production/mmorpg-kit-docs#2569]
Hello,
I need help.
With 1. How do I change it to MMO mode?
2. How do I set a portal right to another scene or another area?
3. How do I set my own created sprites for a 3D player and 3D enemy?

**Comment by SodosTheDeveloper** [comment]
I'll get into that again, those 2, excuse me, 3D Models.

**Comment by insthync** [comment]
Try follow these
https://dev.to/insthync/create-game-with-mmorpg-kit-part-1-project-preparation-13cj
https://dev.to/insthync/create-game-with-mmorpg-kit-part-2-map-and-first-character-54dl
https://dev.to/insthync/create-game-with-mmorpg-kit-part-3-first-monster-and-map-s-navmesh-5277

**Comment by SodosTheDeveloper** [comment]
Do you have time to AnyDesk the server MMO portion?
I've been following the instructions, and it fails to succeed.
________________________________

**Comment by insthync** [comment]
No free help anymore

**Comment by insthync** [comment]
I will do it only it is a bug which I have to try to reproduce

**Comment by SodosTheDeveloper** [comment]
How much do you charge?
________________________________

**Comment by SodosTheDeveloper** [comment]
Well an error message appears, each time.
________________________________

**Comment by SodosTheDeveloper** [comment]
<https://1drv.ms/i/c/cf8bcd2ea385bf8d/EVz9jVaSXX1Ju9REEbvP10wBhJKDr_a1ANSRnc90lR_W1w>
[https://centralus1-mediap.svc.ms/transform/thumbnail?provider=spo&farmid=194139&inputFormat=png&cs=NWQ2NjE5NTAtMzQ3NS00MWNkLWEyYzMtZDY3MWEzMTYyYmMxfFNQTw&docid=https%3A%2F%2Fmy.microsoftpersonalcontent.com%2F_api%2Fv2.0%2Fdrives%2Fb!kSp0wOeaCEq1mLkyQGPfkianh71XbTNPjZnFiy6GfikNRQXUKhWQTpl23R8sTWmO%2Fitems%2F01UFBDME247WGVNES5PVE3XVCECG547V2M%3Ftempauth%3Dv1e.eyJzaXRlaWQiOiJjMDc0MmE5MS05YWU3LTRhMDgtYjU5OC1iOTMyNDA2M2RmOTIiLCJhcHBpZCI6IjVkNjYxOTUwLTM0NzUtNDFjZC1hMmMzLWQ2NzFhMzE2MmJjMSIsImF1ZCI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC9teS5taWNyb3NvZnRwZXJzb25hbGNvbnRlbnQuY29tQDkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImV4cCI6IjE3Mjc4NzA0MDAifQ.zQFecNri3sfKrF5g3inSnyxh9aNibRASgekCPu77cSWTQxSD88O2Iy4J-F3Thwdxhe76svvb3Yrvt_lC5FKUFFpGvpzdyjOUKISgg4H8uljjlF2MhpyesJYgMYfNbKUupBu0JuWi5gjlw6OkbgfzxC432ZhVYjNNNiejps8LOCx7XA8kR5HDpsxJDSXbHFvmrGyuCwbSdBmxfd8VNloy1Z4tkn7D0bUNGU0rXq7EEYwvDu3mVdKdCanHRzy7IzOqzxW2pJuXfgrFLHKkcanKaUbPecReC423nH7IA4FfCk4dM5FHA6FnDvMOj5cUPWjBu5Ku9jZ3Tc_03VLw0Rb44hxg2VxV9uNVQV_SGiYShjGIY34jaxe8OEpXa_VgWz6krwzTXIA_4rtXlHFchttCmWMniNi6aThArtPBwqwYsjQOKbGgik5iR6Nzt1sbzgp6.Jzwh5C-WajdTik3psJMFaGSgr7oVNNY1L96L_Rgy4cY%26version%3DPublished&width=176&height=176&cb=63863456101]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]2024-10-02.png
________________________________

**Comment by SodosTheDeveloper** [comment]
I tried so many types of methods of a run script, the same error message appears.
________________________________

**Comment by insthync** [comment]
I cannot see the image

**Comment by SodosTheDeveloper** [comment]
<https://1drv.ms/i/c/cf8bcd2ea385bf8d/EVacDgN7mXJFnX-nQ1FOc_0Bp6IWyVlPPZuW3r-0fBZxCg>
[https://centralus1-mediap.svc.ms/transform/thumbnail?provider=spo&farmid=194139&inputFormat=png&cs=NWQ2NjE5NTAtMzQ3NS00MWNkLWEyYzMtZDY3MWEzMTYyYmMxfFNQTw&docid=https%3A%2F%2Fmy.microsoftpersonalcontent.com%2F_api%2Fv2.0%2Fdrives%2Fb!kSp0wOeaCEq1mLkyQGPfkianh71XbTNPjZnFiy6GfikNRQXUKhWQTpl23R8sTWmO%2Fitems%2F01UFBDME2WTQHAG64ZOJCZ275HINIU4475%3Ftempauth%3Dv1e.eyJzaXRlaWQiOiJjMDc0MmE5MS05YWU3LTRhMDgtYjU5OC1iOTMyNDA2M2RmOTIiLCJhcHBpZCI6IjVkNjYxOTUwLTM0NzUtNDFjZC1hMmMzLWQ2NzFhMzE2MmJjMSIsImF1ZCI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC9teS5taWNyb3NvZnRwZXJzb25hbGNvbnRlbnQuY29tQDkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImV4cCI6IjE3Mjc4ODEyMDAifQ.sIYlbyAFR9KGwQETnFM6C1QX5_uIAoSmhF7W9WbGNXo_hKCzbjEqfrqQckmFp8Mfx4nupf_9clEjV9ube8ty-VRWIehHpDFqKdk1RinFjsx37MnjuQY6G4znRnq7tKTjxd5Ndb8LDRIhrJ2-Fkqo1Hprh95EhrG1lwp6yIT2heZ3p3cuAwkps93VVQq2o9BLemOZeUsUqdqm36-k1BOfUaNyouf9PBJLWPq-RVvSUrUvYrVo_S9u786cFavQJ2dZ4ggX6l_KKh6z409draMegKNqPLHSrTyWhRsHJbDDi2sIJjj4ExG-PntqD0O3BH9IGBV3lhbyLg3YPGqXlDPpQwx040bAcFUd5BhWXYa5YM7Fi_3FSOKEwMHya-pFmOPPnSCkzqa4IrAoRttITsDtQBZnR47a_CfG5u_SqHeUol94fq-Hs6ZNYq7kxHhWYtwi.BwLucz8aFaRLABC0WQpH7IuHlNgWv_QB5QS60Ev1TXc%26version%3DPublished&width=176&height=176&cb=63863460878]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]2024-10-02.png
________________________________

**Comment by SodosTheDeveloper** [comment]
[
![2024-10-02](https://github.com/user-attachments/assets/4a133e93-3503-4c2d-983e-aa8ff832007f)
](url)

**Comment by insthync** [comment]
It cannot find Build.exe file, you have to set proper config to find the build file.

**Comment by insthync** [comment]
Just build a game, which you are already did it, but your file name is not Build.exe, so you will have to change exe path in serverConfig.json

**Comment by SodosTheDeveloper** [comment]
the build.exe is not findable in the folder, I did find the path in the serverconfig

**Comment by SodosTheDeveloper** [comment]
![image](https://github.com/user-attachments/assets/482845cc-8707-4dfc-b14c-bbb69db3e2a0)

**Comment by insthync** [comment]
Just change it to your build file, I did not tell you that it must have build.exe file

**Comment by SodosTheDeveloper** [comment]
https://github.com/user-attachments/assets/1b655d8e-06d9-40e3-8d77-b39f3dd4370a

I edited the server config with the .exe address,
I checked the target info is correct,
I waited for about 15 minutes for the shortcut server to connect it did what is in the video,
still open, not done though.

**Comment by insthync** [comment]
Why did you have to wait for 15 minutes?

**Comment by SodosTheDeveloper** [comment]
It does not open a server for the client.

**Comment by insthync** [comment]
How did you know that? Did you try to enter game with client ?

**Comment by SodosTheDeveloper** [comment]
I checked it, it does not show a server.

**Comment by insthync** [comment]
Where ?

**Comment by insthync** [comment]
Did you enter game from 00Init_MMO scene?

**Comment by SodosTheDeveloper** [comment]
Isn't it suppose to be off Unity, and on a shortcut + a client to play the game on a server?
________________________________

**Comment by insthync** [comment]
What is not show?, I don't get it.

**Comment by insthync** [comment]
You have just open a game select a local server then register, login then enter game, why is that so hard?

**Comment by SodosTheDeveloper** [comment]
The instructions indicate I need to create a shortcut to operate a server for a build for other peoples.
________________________________

**Comment by insthync** [comment]
Yes, just create a short cut to run servers, then run a client by default .exe file to test

**Comment by SodosTheDeveloper** [comment]
I tried that, it doesn't work.
Currently I am trying to create the steps provided to test a new character.
Can you help with AnyDesk again to setup the server?
It's buggy apparently.

________________________________

**Comment by insthync** [comment]
It is not free help, are you ok?

**Comment by insthync** [comment]
Because it is very very very basic, if you can't do it, I think I will have to help you a lot

**Comment by SodosTheDeveloper** [comment]
What am I supposed to do with this?
The whole plot is not solved yet.

________________________________

**Comment by insthync** [comment]
Try follow this one https://www.youtube.com/watch?v=7V1ChDPY_Ww

**Comment by SodosTheDeveloper** [comment]
I followed the video instructions,
And it continues to not connect the server,
It does a loop and doesn't close either,
Possibly its the code of the serverconfig?

**Comment by SodosTheDeveloper** [comment]
![image](https://github.com/user-attachments/assets/4e665392-e8a9-4d03-ad78-e147a201032f)
just checking... is that the build file title?

**Comment by SodosTheDeveloper** [comment]
![image](https://github.com/user-attachments/assets/b9fca9c2-4b6d-4417-aa7b-b733ea07a2f9)

**Comment by SodosTheDeveloper** [comment]
excuse me, it's working, but I think my problem was that I could not identify a server name,
how do I name the server?
