### ISSUE TITLE
UMA Integration up to date

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#257]
Hello i integrated UMA. i noticed that the CharacterModelUMA.cs script is not up to date. for example in the Default Animato Data are just the basic field. sprint, crouch, crawl for example is missing. i dont checked everything now so maybe other stuff is also missing for uma.

**Comment by insthync** [comment]
No, it's missing from the CORE, not UMA, you have to use `AnimatorCharacterModelUMA` component.

**Comment by moepi2k** [comment]
tried and works, but when i AnimatorCharacterModelUMA and remove CharacterModelUMA.cs and create new character i dont get the menu to customize the player and the player is also naked.

**Comment by insthync** [comment]
Yes, `CharacterModelUMA` and `AnimatorCharacterModelUMA` has almost the same scripts, just inherit from base script to change some processes, I've update new version which add interface which using in character list, character creation scene and implement it.

(https://github.com/insthync/UnityMultiplayerARPG_UMA/releases)
