### ISSUE TITLE
Linux Null Reference for TBehavior

### ISSUE THREAD

**Issue by chuckyw** [suriyun-production/mmorpg-kit-docs#2570]
OS: Linux Mint 20.04
Kernel: 5.15.0-122-generic
Unity 2022.3.44f1

Fresh install of MMOKIT without modification produces the following error when running the game in Play Mode.  Game runs and I can play it however receive several errors in the console.  Any help would be greatly appriciated.

![null](https://github.com/user-attachments/assets/286ed9e1-2d1a-4dee-8f94-75bd9df39eb7)

**Comment by insthync** [comment]
It is just addressable error, if you try the demo, which have addressable content, and this is occurs then you can ignore it.

If you intend to use addressable asset, then you have to learn about addressable asset first.

**Comment by chuckyw** [comment]
Great!  Thanks for the info.
