### ISSUE TITLE
Custom 3d Player Models: I need help!

### ISSUE THREAD

**Issue by SodosTheDeveloper** [suriyun-production/mmorpg-kit-docs#2572]
I can't seem to configure it well, I only have my own models I had animated,
How do I configure the models to work in the game?
Doing all animations/maintaining grounds/ and fighting.
I read that manual online, and it only lead to a still model underneath ground moving with no animation but a 3D clone.

**Comment by insthync** [comment]
Which document you've followed ?

**Comment by SodosTheDeveloper** [comment]
https://dev.to/insthync/create-game-with-mmorpg-kit-part-2-map-and-first-character-54dl

**Comment by insthync** [comment]
Then what part you don't understand, or it didn't work for you?

**Comment by SodosTheDeveloper** [comment]
It did not work, I can take screenshots if you want to correct it?

**Comment by insthync** [comment]
How is it not work?

**Comment by SodosTheDeveloper** [comment]
I'm not sure, it just doesn't, as I play the game it maintains a model that is in one stance, and goes on like a bot that doesn't animate what I put there.

**Comment by SodosTheDeveloper** [comment]
![image](https://github.com/user-attachments/assets/1b83818c-c70b-4e6d-9aa2-d8988d4d19e2)
![image](https://github.com/user-attachments/assets/0968dc49-49c1-4b6a-8390-21b90e5fcd97)

**Comment by SodosTheDeveloper** [comment]
![image](https://github.com/user-attachments/assets/165ea109-7073-4880-95dd-3792b4cf8fb6)
![image](https://github.com/user-attachments/assets/3feb2fef-6f15-4c3f-a3f6-3eb75f51be2b)
I use 3DS Max to animate this guy, the animations come out okay, I could not afford the set that was indicated in the manual.

**Comment by insthync** [comment]
What kind of animation, generic or humanoid, Is is able to play properly in unity asset preview?

**Comment by SodosTheDeveloper** [comment]
Generic, and I can't seem to get the animation to play, I'm not sure where asset preview is.

**Comment by insthync** [comment]
Are you new unity user ?

**Comment by insthync** [comment]
Did you make sure that your animation work in unity and how you do it?

**Comment by SodosTheDeveloper** [comment]
I have been using Unity for about a year now, the animation does play, but I am not sure how this portion is done.

**Comment by insthync** [comment]
Then how did you set idle animation?

**Comment by insthync** [comment]
From given image, it shows that animation not working,  so I want to know why, animation not working, or you didn't set it properly

**Comment by SodosTheDeveloper** [comment]
![image](https://github.com/user-attachments/assets/c93dd6e5-246c-4c14-967a-30a850380ddd)

I set the animations to the set areas.
It does not proceed that way in the video game playing.
The problem maybe the past animation cluttering it, the stock given?
Maybe deleting some files is the answer?

**Comment by SodosTheDeveloper** [comment]
![image](https://github.com/user-attachments/assets/b875864f-ea96-4de9-a8db-f6cd052a7f9e)

**Comment by SodosTheDeveloper** [comment]
Possibly one of those errors lead to a malfunction in the player model?

**Comment by insthync** [comment]
No, it is not

**Comment by SodosTheDeveloper** [comment]
What to do then?

**Comment by insthync** [comment]
What are you planning to do then? 

For me, I will make sure that the animation is work properly, if it is generic then character must be generic too, then play testing, then fix something if error occurs.

That is it.

**Comment by SodosTheDeveloper** [comment]
Where did I go wrong?

**Comment by insthync** [comment]
Can you show me that the animation is really able to be played in unity, by showing a video which do it?

**Comment by SodosTheDeveloper** [comment]
https://github.com/user-attachments/assets/7876fc9a-c1b4-40bf-8a3a-8b03dc42bbc5

**Comment by insthync** [comment]
Then how is it going when you use the animation with character?

**Comment by insthync** [comment]
You have to drag your character prefab to the animation clip preview to see if it work or not

**Comment by SodosTheDeveloper** [comment]
I'll do that, be right back.

**Comment by SodosTheDeveloper** [comment]
Same effect.

**Comment by SodosTheDeveloper** [comment]
The character in the video game, is one graphic, moving like a still image going.

**Comment by insthync** [comment]
Then play testing, don't have to enter the game, just in character create scene, if it not working then look in console find message which you can guess it is the cause of probelm

**Comment by SodosTheDeveloper** [comment]
I think I had the wrong character controller on, he's doing movements, also I think it's the time setting on the animation, i'll be right back after a full test.

**Comment by SodosTheDeveloper** [comment]
Some controller had an animation to it, but I am not sure where it came from... possibly I can send you my animations and you can try to do it, on your Unity?

**Comment by insthync** [comment]
OKAY

**Comment by SodosTheDeveloper** [comment]
[jump_up.max.zip](https://github.com/user-attachments/files/17268894/jump_up.max.zip)

**Comment by insthync** [comment]
Can you export it to FBX, I don't have 3D max installed

**Comment by SodosTheDeveloper** [comment]
I'm on the same point about it being .fbx, i'll be right back and export it to .FBX types.

**Comment by SodosTheDeveloper** [comment]
[fbx animations.zip](https://github.com/user-attachments/files/17268985/fbx.animations.zip)

**Comment by insthync** [comment]
https://youtu.be/fetTsOKdPOk working immediately, did you setup avatar for your character properly?

**Comment by SodosTheDeveloper** [comment]
I'll check into that, BRB.

**Comment by SodosTheDeveloper** [comment]
The animations I uploaded, I found after reupload, it has a "take"# file, each of them, and is Generic, must I edit the take file names to a custom and change it to Humanoid?

**Comment by insthync** [comment]
No, generic is working

**Comment by SodosTheDeveloper** [comment]
It fails to work on my behalf...
Is it possible to get the files zipped to study?

**Comment by insthync** [comment]
Please wait, I am having dinner

**Comment by SodosTheDeveloper** [comment]
Ok, sir.

**Comment by SodosTheDeveloper** [comment]
> Please wait, I am having dinner

When you're ready.

**Comment by SodosTheDeveloper** [comment]
May I have those files zipped?

**Comment by insthync** [comment]
[animations.zip](https://github.com/user-attachments/files/17286984/animations.zip)

**Comment by SodosTheDeveloper** [comment]
it's missing the scripts

**Comment by insthync** [comment]
I don't get what are you going to tell me.

**Comment by SodosTheDeveloper** [comment]
The character configurer, created the clone, but I am not sure where to push it in to, what object in what map, what aspect?

**Comment by SodosTheDeveloper** [comment]
I went to the manual and it didn't succeed.

**Comment by insthync** [comment]
I still don't get what are you going to tell me.

The files which I've sent to you it not working or something?

**Comment by SodosTheDeveloper** [comment]
Where do I post the files at in the Unity?
What script?
They should work if they were working on your PC.

**Comment by insthync** [comment]
Just extract the file then import `.unitypackage` file with Unity, that is it.

I start to think that you're lying to me about your Unity skills

Honestly, I want to stop helping you, at least you should says thank you when I try to help you, not continue complain what not understandable.

**Comment by insthync** [comment]
Okay, no more help for you, you're too noob, all problems are all your skill issues.

**Comment by SodosTheDeveloper** [comment]
Thank you.
