### ISSUE TITLE
Change in how animations work

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2575]
**Describe the bug**
With the arrival of the last update, the animations were modified while attacking laterally, now it seems as if you were in a walking state when the running state is active, in previous versions it worked differently, you maintained the speed even if you continued running and attacked laterally, no Yes, it was incorrect behavior but it was quite frenetic and fun in the game that I created a video of examples here.

[Old]
https://streamable.com/8f53ta

[New Version last 1.89]
https://streamable.com/kadn77

**Expected behavior**
I want to know what causes the new behavior, what class is it in to modify the code, if possible to add a Boolean value to leave it as the old one since it seems better to me for the game I am making

**Desktop (please complete the following information):**

 - Version [1.89]

**Comment by moepi2k** [comment]
A bool? This will confuse many ppl. Even the the new avatar mask stuff is really confusing

**Comment by Niinra** [comment]
> A bool? This will confuse many ppl. Even the the new avatar mask stuff is really confusing

I think it would be the easiest

**Comment by Niinra** [comment]
![image](https://github.com/user-attachments/assets/02c07e3a-6754-4474-a451-4c0f4ff707ca)
I solved what I needed this way, adding the aiming inside the while with an enum you could change the behavior to the base or modified one, but of course to make it easier you create your own controller class and you make an override and that's it, easier
