### ISSUE TITLE
CanUseByEveryone not working anymore? Alternative solution ?

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2579]
Hi in old version there was this changelog:
[1.54c (2020-04-10)](https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/000-changelog?id=_154c-2020-04-10)
    Add canUseByEveryone to StorageEntity and CampFireEntity to allow other players to use storage buildings.

Now it seems that there is one on StorageEntity but it's useless and no more on other buildingentities. I did testing in Lan and now with latest version other players cannot access storage of other players and it seems that this function was removed without changelog ?

I also can't download any version older than 1.70 unfortunately to go see what happened

**Comment by insthync** [comment]
What? It is still there

![Screenshot_17](https://github.com/user-attachments/assets/8728e7ed-7bc2-419f-b36f-8bf3c10a75c0)
