### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2580]
kit version 188f5

crash report 
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object.
  at MultiplayerARPG.BaseDamageEntity.get_FxCollection () [0x00000] in <00000000000000000000000000000000>:0 
  at MultiplayerARPG.BaseDamageEntity.StopFx () [0x00000] in <00000000000000000000000000000000>:0 
  at MultiplayerARPG.ProjectileDamageEntity.OnPushBack () [0x00000] in <00000000000000000000000000000000>:0 
  at MultiplayerARPG.PoolDescriptor.PushBack () [0x00000] in <00000000000000000000000000000000>:0 
  at MultiplayerARPG.PoolDescriptor.PushBackRoutine (System.Single delay) [0x00000] in <00000000000000000000000000000000>:0 
  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].TrySetResult (TResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at Cysharp.Threading.Tasks.UniTask+DelayPromise.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<PushBackRoutine>d__14:MoveNext()
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(TResult)
Cysharp.Threading.Tasks.DelayPromise:MoveNext()
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore()

**Comment by insthync** [comment]
Just add a null check to fix it, isn't it?, you actually have access to help me, you never try to help me to fix anything, I have to tell you to do it, I don't want to give you any access any more.

**Comment by insthync** [comment]
You've asked for github repo accessibility every time, I gave it to you and expected you to help me to fix minor bugs,

This one is very easy to fix, but you don't help me to fix it, Does that sound stupid?

**Comment by moepi2k** [comment]
dont get me wrong. but while we using this kit we are something like testers. we find bugs we report kit can be improved. thats how things works isntit?

**Comment by insthync** [comment]
Then just stop asking for core repo accessibility, so I won't expect anything from you, that is it.

**Comment by moepi2k** [comment]
Huh? I dont ask for core access? I thibk thats someone else then

**Comment by insthync** [comment]
> Huh? I dont ask for core access? I thibk thats someone else then

If you don't requested for it then why I gave it to you?

**Comment by moepi2k** [comment]
I requested it once because i thought its something you provide when i bought the kit back in 2020. Its nice to see what changed when stay at specific version. So u can pick those bugfixes and implement by self

**Comment by insthync** [comment]
So, you requested for it aren't you, any benefit to me to give it to you then?

I made it, sale it very cheap, fix bugs for free, sometime accept some new features requests for free, aren't it good enough?

**Comment by Eniotnacram** [comment]
Hello,

Moepi2k got a released game on Steam using the kit, there are a LOT of backend issues. Instead of arguing, would that be a really good opportunity to fix all the issues? That's literally the perfect example to see what are the issues and bugs with an active player base.

Instead of arguing like that, I think you guys should have a way to talk to each other in realtime and try to fix all the issues a "complete" project occurs.

That's my point of view tho, I could be wrong!

**Comment by moepi2k** [comment]
Lol, its up to you to give access, and its fine if you decide not to. But selling it cheap? What about the kit? Thats a different perspective. For me, yes, its cheap, but that was never the question. Fixing bugs for free? Of course, its a product you sell. Its your job to fix it for free, isnt it?

On the other hand, weve always told you to stop adding features for free, because thats exactly where you can make extra money. The kit is good as it is, but its full of bugs and far from being production ready. There are so many known critical bugs, and you dont fix them.

In the end, its your decision, but it just seems like youre burned out, tired of handling everything on your own, and frustrated with your customers.

**Comment by insthync** [comment]
@moepi2k then don't ask for it again, @Eniotnacram  then just list only critical issues for now to fix them first, what i saw for now is moepi2k one which make his player cannot enter the game, hmmmm, sound not many :)

**Comment by insthync** [comment]
And yes bug fixing is what I have to do when did I decline to fix?, I just upset that you ask me to fix this simple bug while you have an access to the core repo with your word which have told me that you will push bug fixes when you can. just null check applying to fix this, you really can't?

**Comment by insthync** [comment]
You said I don't fix critical bugs then list all of them, I will fix it, that is it.

**Comment by insthync** [comment]
Closes around 2500, having 50+ open, and you said I don't fix bugs, :)
