### ISSUE TITLE
Mount Issue

### ISSUE THREAD

**Issue by temel61** [suriyun-production/mmorpg-kit-docs#2581]
It calls wrong different mount when I click use button.

![Ekran görüntüsü 2024-10-21 101759](https://github.com/user-attachments/assets/709ab803-73c6-4b9f-b913-94135622cabb)

**Comment by temel61** [comment]
it must be summon nirvana dragon (Blue dragon).But it summon wrong vehicle.I added some debug.log in code.Why it always changing?.

**Comment by temel61** [comment]
![Uploading Ekran görüntüsü 2024-10-21 103929.png…]()

**Comment by insthync** [comment]
You may try check if asset ID is difference or not in your vehicle entity -> `LiteNetLibIdentity` component

**Comment by temel61** [comment]
It always calls last vehicle in the list. 
![Ekran görüntüsü 2024-10-21 121726](https://github.com/user-attachments/assets/c7f38690-ac9b-4209-9b83-737f259f51e9)

**Comment by insthync** [comment]
Please do what I've told you.

**Comment by temel61** [comment]
I will do that.But my only horses inluded in to addressableplayer prefab list.No camel, no alpaca,no tiger in the list.

![Ekran görüntüsü 2024-10-21 123729](https://github.com/user-attachments/assets/87c61a0f-b6e8-43f8-9035-20e33af24c9a)
![Ekran görüntüsü 2024-10-21 123810](https://github.com/user-attachments/assets/a0645a51-6a2d-450b-9661-17ea3a37f2f7)

**Comment by temel61** [comment]
![Ekran görüntüsü 2024-10-21 170815](https://github.com/user-attachments/assets/e4fcdb3c-e5b0-4b3a-90c8-0f6950519b42)

**Comment by insthync** [comment]
I don't understand what the log is telling

**Comment by temel61** [comment]
I use alpaca mount with HashAsassetId 372029326, but It found griffin with HashAsassetId 372029326, same key but different prefab in GuidToPrefabs.I think it create same HashAssetId for different entity or duplicate entity.

BaseGameEntity_MountFunction.cs

        public virtual async void Mount(VehicleEntity prefab, AssetReferenceLiteNetLibBehaviour<VehicleEntity> addressablePrefab)
        {
            if (!IsServer || (prefab == null && !addressablePrefab.IsDataValid()) || Time.unscaledTime - _lastMountTime < CurrentGameInstance.mountDelay)
                return;

            if (addressablePrefab != null)
            {
                Debug.Log("Start_Name : " + addressablePrefab.editorAsset);
                Debug.Log("Start_HashAssetId : " + addressablePrefab.HashAssetId);
                Debug.Log("Start_AssetGUID : " + addressablePrefab.AssetGUID);
            }

            _lastMountTime = Time.unscaledTime;

            Vector3 enterPosition = EntityTransform.position;
            if (PassengingVehicleEntity != null)
            {
                enterPosition = PassengingVehicleEntity.Entity.EntityTransform.position;
                await ExitVehicle();
            }

            // Instantiate new mount entity
            LiteNetLibIdentity spawnObj;
            if (prefab != null)
            {
                spawnObj = BaseGameNetworkManager.Singleton.Assets.GetObjectInstance(
                    prefab.Identity.HashAssetId, enterPosition,
                    Quaternion.Euler(0, EntityTransform.eulerAngles.y, 0));
            }
            else if (addressablePrefab.IsDataValid())
            {
                spawnObj = BaseGameNetworkManager.Singleton.Assets.GetObjectInstance(
                    addressablePrefab.HashAssetId, enterPosition,
                    Quaternion.Euler(0, EntityTransform.eulerAngles.y, 0));
            }
            else
            {
                return;
            }

            if (spawnObj == null)
            {
                return;
            }

            VehicleEntity vehicle = spawnObj.GetComponent<VehicleEntity>();

            if (addressablePrefab != null)
            {
                Debug.Log("Result_AssetId : " + vehicle.Title);
                Debug.Log("Result_AssetId : " + spawnObj.AssetId);
                Debug.Log("Result_HashAssetId : " + spawnObj.HashAssetId);
            }

            BaseGameNetworkManager.Singleton.Assets.NetworkSpawn(spawnObj, 0, ConnectionId);

            // Seat index for mount entity always 0
            await EnterVehicle(vehicle, 0);
        }

MountItem.cs

        public void UseItem(BaseCharacterEntity characterEntity, int itemIndex, CharacterItem characterItem, int amount)
        {
            if (!characterEntity.CanUseItem() || characterItem.level <= 0)
                return;

            if(AddressableVehicleEntity != null)
            {
                Debug.Log("UseItem_editorAsset : " + AddressableVehicleEntity.editorAsset);
                Debug.Log("UseItem_HashAssetId : " + AddressableVehicleEntity.HashAssetId);
            }
            characterEntity.Mount(VehicleEntity, AddressableVehicleEntity);
        }

**Comment by insthync** [comment]
Okay, then you have to fix duplicated key by change a asset ID in `LiteNetLibIdentity` component
