### ISSUE TITLE
LAN - Warp coordinate not working for non host

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#2582]
Player who are not host don't spawn on the spawn position of the map inside the instance for some reason.
They spawn else where and fall through ground

Reproduce :

Host a lan game
Go into a warp to another map
NON host player get teleported to wrong coordinate

**Comment by Eniotnacram** [comment]
Hello,

Hosting the server (host) on the same machine ur playing right? Do you have DNS/RDNS setup ? If you do, i had the same problem in MMO, you need to modify ur windows host file and add "DNS name":localhost

**Comment by sawcisson** [comment]
The host and client are on different machines through steam

**Comment by insthync** [comment]
Fixed: https://youtu.be/6_JB_vYzVpo

**Comment by sawcisson** [comment]
Could you please tell me how you fixed it and where should I update my file ?

**Comment by insthync** [comment]
In `LanRpaNetworkManager.cs`

Add 
```
        private readonly HashSet<string> _teleportingPlayerCharacterIds = new HashSet<string>();
```

![Screenshot_24](https://github.com/user-attachments/assets/046227e8-465b-431c-b0a3-01b50d0171c7)


In function `SpawnPlayerCharacter`, find `!CurrentMapInfo.Id.Equals(playerCharacterData.CurrentMapName)`
Add `|| _teleportingPlayerCharacterIds.Contains(playerCharacterData.Id)` condition, and remove character ID from `_teleportingPlayerCharacterIds` later

![Screenshot_25](https://github.com/user-attachments/assets/2064560e-0239-4ad9-9bd4-eceffa557514)

In function `WarpCharacter` add character ID to `_teleportingPlayerCharacterIds` before proceeding to warp

![Screenshot_26](https://github.com/user-attachments/assets/32c68dfb-f4b8-4d73-a064-35f254f1c37a)
