### ISSUE TITLE
Losing item when shut down server

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2583]
could it be that server not save all together at same time? 

a player claimed an item directly before server shut down. the item was in inventory. after restarting the item was gone. but the mailbox say its already claimed

**Comment by insthync** [comment]
I have added delay to before the server closed, isn't it helped?

**Comment by moepi2k** [comment]
seems not. i just checked logs and saw that the guy buyout an item but it was not saved into db e.g he lost the item and also the gold he paid for

**Comment by insthync** [comment]
When you close the server, did you wait until it closed automatically or you just force close it?

**Comment by insthync** [comment]
Did you try killall -15 xxx.x86_64 instead?
I also change how to update inventory, now it will be updated almost immediately after changes occurs, hope it help
