### ISSUE TITLE
Moving Items stuck on sreen

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2584]
1) this issuea appears for a long time. to simply reproduce just drag an drop items while hold left + right mouse button at the same time.
also happen rarely also when only use one mouse button and moving items 

https://gyazo.com/8bdcd7867521bcea18bf0d3017eba703

2) when moving items to not ui slots u will get an error
https://gyazo.com/977c953352c7e95ae77510c10ed25639

**Comment by insthync** [comment]
Fixed: https://youtu.be/wzizTGNDMlI
