### ISSUE TITLE
Logging System

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2588]
using ur interface (IServerLogHandlers) for loggin stuff. there is a small problem for loggin chat message

https://gyazo.com/e30f1cce75e725acb0e3b7630a373c62

so when using global chat. it makes entry for each mapserver
https://gyazo.com/be4a80dd3932789e4b0c7c42ac0ef7cc

here u can see the logs for e.g global message and local message. local only log once global as many as mapservers

**Comment by insthync** [comment]
Fixed: https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMO/commit/aa8216a3a368ec7c14673c9b143c4c5fce6bb368
