### ISSUE TITLE
Building Storage wipe after server restart

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2591]
as title said, when u have building storage with stuff in it. afte serve restart. its all gone

**Comment by insthync** [comment]
Yep, how it gone? removed from the database or weren't loaded on start?

**Comment by insthync** [comment]
You never report this, and you said I don't fix bug :)

**Comment by moepi2k** [comment]
need to check if its in db. but it not load on start 

You never report this, and you said I don't fix bug :) -> u killing me xD

**Comment by moepi2k** [comment]
checking tables. all items in storageitems has storagetype 1 which i assume the items for building storage not save in db.

**Comment by insthync** [comment]
Did you check while playing the game? the data is still there?

**Comment by moepi2k** [comment]
do you mean while in game, the items in storage? yes they are there. and when i restart the server the building entity is still there. for example the campfire. but all items in it are removed.

im not sure but in mysql it should list in storageitem too, right? just with a diffrent storagetype. storagetype 1 = player storage 2 guild, 3 building and so on?

**Comment by insthync** [comment]
Check the database while server is running

**Comment by moepi2k** [comment]
i do
https://gyazo.com/2bc8f4d0d5dcc572759a1b9f00567dd1
only stroagetype 1

**Comment by insthync** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMO/commit/ff42ba5fc3c0d1d18b21d204d7be0bfa0d2276ad

**Comment by moepi2k** [comment]
this again. 191. and stuff in building storage still not save in database...
