### ISSUE TITLE
Pet reset

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2593]
pet level sometime reset to 0 for no reason. 
some player reported it could happen when have mulible pets of same type in inventory. maybe it override the data from one to another

**Comment by insthync** [comment]
0 not 1?

**Comment by moepi2k** [comment]
1

**Comment by insthync** [comment]
How about EXP after reset ?

**Comment by moepi2k** [comment]
Its also gone

**Comment by moepi2k** [comment]
actually its as like you have a new item. level 1, exp 0.

**Comment by insthync** [comment]
I see, but I cannot reproduce it yet.

**Comment by moepi2k** [comment]
yea really hard. i was able only once. i think it happen when u pickup a pet item of same type and sometimes override the one in inventory. :/

**Comment by insthync** [comment]
Change its workflow, now it won't destroy item after summon, but it will update item's level exp while summoned, hope it can fix this bug

**Comment by moepi2k** [comment]
ok thats a good idea, so actually same like pets but it has an issue now
https://gyazo.com/d899a7ca266480d62711ee8b54ab6f3a

same as pet before. u can spawn summon and then drop the item and pet will not dispawn
