### ISSUE TITLE
Problem with displaying the drop object

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2594]
**Describe the bug**
Does not show the prefab of the object when it is dropped , Here is a demonstration video
https://streamable.com/6mxzeo

**To Reproduce**
1. Go to 'Simply drop an object and there will be the problem, nothing is seen but the itemdropentity prefab is shown in the container, there is nothing'

**Desktop (please complete the following information):**
 - Version [1.89]

**Comment by insthync** [comment]
Cannot reproduce, as I test it works fine, might be fixed sometime ago.

**Comment by Niinra** [comment]
You're right coopile and the error is no longer there, this could be a Unity cache error
