### ISSUE TITLE
ArgumentOutOfRangeException Mail List

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2595]
ERROR No Tag [2024-10-28 17:08:40] - ArgumentOutOfRangeException: value must be between 0 and 91
Parameter name: value
MySqlConnector.Protocol.Serialization.ByteArrayReader.set_Offset (System.Int32 value) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Protocol/Serialization/ByteArrayReader.cs:19)
MySqlConnector.Core.TextRow.GetDataOffsets (System.ReadOnlySpan`1[T] data, System.Int32[] dataOffsets, System.Int32[] dataLengths) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/TextRow.cs:28)
MySqlConnector.Core.Row.SetData (System.ReadOnlyMemory`1[T] data) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/Row.cs:17)
MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncRemainder|9_1 (MySqlConnector.Core.ResultSet resultSet, MySqlConnector.Protocol.PayloadData payload, MySqlConnector.Core.Row row) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:347)
MySqlConnector.Core.ResultSet.ScanRowAsync (MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, MySqlConnector.Core.Row row, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:236)
MySqlConnector.Core.ResultSet.ReadAsync (MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:200)
MySqlConnector.Core.ResultSet.ReadEntireAsync (MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:187)
MySqlConnector.MySqlDataReader.NextResultAsync (MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/MySqlDataReader.cs:65)
MySqlConnector.MySqlDataReader.DisposeAsync (MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/MySqlDataReader.cs:583)
MySqlConnector.MySqlDataReader.Dispose (System.Boolean disposing) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/MySqlDataReader.cs:417)
System.Data.Common.DbDataReader.Dispose () (at <ec0065ff2d3e44229c6ad5f6d45313fa>:0)
MultiplayerARPG.MMO.MySQLDatabase.ExecuteReader (MySqlConnector.MySqlConnection connection, MySqlConnector.MySqlTransaction transaction, System.Action`1[T] onRead, System.Boolean isAsync, System.String sql, MySqlConnector.MySqlParameter[] args) (at <3ad1481be4e14fce80cd1cde36655968>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.MySQLDatabase.ExecuteReader (MySqlConnector.MySqlConnection connection, MySqlConnector.MySqlTransaction transaction, System.Action`1[T] onRead, System.String sql, MySqlConnector.MySqlParameter[] args) (at <3ad1481be4e14fce80cd1cde36655968>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.MySQLDatabase.ExecuteReader (System.Action`1[T] onRead, System.String sql, MySqlConnector.MySqlParameter[] args) (at <3ad1481be4e14fce80cd1cde36655968>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.MySQLDatabase.MailList (System.String userId, System.Boolean onlyNewMails) (at <3ad1481be4e14fce80cd1cde36655968>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.DatabaseNetworkManager.MailList (LiteNetLibManager.RequestHandlerData requestHandler, MultiplayerARPG.MMO.MailListReq request, LiteNetLibManager.RequestProceedResultDelegate`1[TResponse] result) (at <3ad1481be4e14fce80cd1cde36655968>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.MMO.<MailList>d__90:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetException(Exception)
MultiplayerARPG.MMO.<MailList>d__151:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception)
MultiplayerARPG.MMO.<ExecuteReader>d__20:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetResult()
MultiplayerARPG.MMO.<OpenConnection>d__10:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

i assume this is also something that cant be fixed because of mysql connector version?

**Comment by moepi2k** [comment]
highest id in mail is 4148. not even fully a tinyint

**Comment by insthync** [comment]
I asked what kind of mail ID, so you have just look at table structure -> column type, that is it.

**Comment by moepi2k** [comment]
BIGINT(20)

**Comment by insthync** [comment]
Okay, then find in the codes, if you can find `.Id = reader.GetInt32` and change it to `.Id = reader.GetInt64` then test it

**Comment by moepi2k** [comment]
ok changed and i will test it. thank you

**Comment by moepi2k** [comment]
https://gyazo.com/b537e539b5c56c5d892ff4370506fcdd
but isnt the error say that it has an issue with MailList instead of GetMail?

**Comment by insthync** [comment]
Then you may change another to GetInt32, you should try it first.
