### ISSUE TITLE
Quest filter

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2597]
ist quest filter broken or do i using it wrong?

https://gyazo.com/689a65fce63db71e78af84a6d0a3487e

in my case i have only two kind of quests -> Normal and Daily.
but it even show when clikc Event, or Faction 

and it seems its randomy filled with content which not match the criteria

**Comment by khongtuong** [comment]
case sensitive, in your quest category is Normal but in filter normal

**Comment by insthync** [comment]
No problem found

**Comment by moepi2k** [comment]
So is my setup wrong then? At first its good but when switching tabs with diffrent quest co ditions, sometimes its mixed and it show quest in some filter which should not. And there should maybe be an option also to only show completed quest so you can filter those out and only show in e.g completed quest tab

**Comment by insthync** [comment]
How can I know your setup?, maybe your toggle events is incorrect
