### ISSUE TITLE
Added OnRewardItem For Immediate Item Rewards

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2598]
Hello,

I modified the BaseMonsterCharacterEntity "Killed" function To notify the player when an Item is looted when the looting is set to Immediate.

Because the Function didin't call "OnRewardItem" so the Item was not notified.

Those are my changes only for Line 490: 

looterEntity.IncreaseItems(_droppingItems[i], characterItem => looterEntity.OnRewardItem(RewardGivenType.KillMonster, characterItem));

I added this: "=> looterEntity.OnRewardItem(RewardGivenType.KillMonster, characterItem));"

**Comment by insthync** [comment]
Applied, thank you
