### ISSUE TITLE
[Bug]seed of items change

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2599]
when u have an item with random bonus (seed) when u put it in auction house it changes the seed

this is before i put ring into auction house
https://gyazo.com/fc320c375cf7319fd6cfe9c0ba7d2e41

this when its in auction house
https://gyazo.com/6deb4e0c2bdd926e9c1de85752a380fc

when u cancel the action or someone buy it out and u claim from post it will keep the changed seed which was in the auction house
so actually its not just a visual issue

**Comment by insthync** [comment]
Please list when the seed changed

**Comment by moepi2k** [comment]
at the moment when u create the auction. need to check when back from work

**Comment by insthync** [comment]
Really cannot reproduce, when is your last update for those 2 repos?

**Comment by moepi2k** [comment]
For auction house and service. Its latest. Do you have an item with random bonuse and put it in auction house?

**Comment by insthync** [comment]
Yes, why will I test seed changing without items that won't have random bonus?

**Comment by insthync** [comment]
May try check read/write items function here

https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_SharedData/blob/main/Scripts/CharacterData/CharacterDataExtensions.cs

**Comment by moepi2k** [comment]
U tested it with latest kit version?

**Comment by insthync** [comment]
Yes I never test on the old version, why I have to test on the older versions?

**Comment by moepi2k** [comment]
so how should i test on latest when its not released yet. maybe its fixed there somewhere already

**Comment by insthync** [comment]
How should you test? you said issues occurring when create an auction then you have to debug a create auction part, that is it

I told you to check read/write did you do it?

Hint in case you are inability to debug create auction part, check the seed [here](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_AuctionHouse/blob/main/Scripts/Networking/BaseGameNetworkManager_AuctionHouse.cs#L171), and [here](https://github.com/suriyun-mmorpg/mmorpg-kit-auction-house-service/blob/main/src/functions/index.ts#L179)

**Comment by moepi2k** [comment]
ok then i will setup fresh kit with 189 and new auction and try again. but i cant see any changes in the read write stuff from 188 to 189 so i wondering why you are not able to reproduce it. or if its possible would be nice to send a current version of the core so i can also test with it since u dont know when u gonna release it

**Comment by insthync** [comment]
Try debugging the seed value first.

**Comment by moepi2k** [comment]
ok will do it when at home, thx

**Comment by moepi2k** [comment]
ok debuged it and its even more weird now. when i create the item the seed is -1992666332. after puting in auction house the seed NOT change, even when i put out of mailbox. so seed is always correct. but the bonus attributes of the item changes one time when u put it in the auction house. and only one time. the second time it will be like it was after changed once.

c0e7fd587a306a8a08e1f23b62b7bf05

**Comment by insthync** [comment]
So what you have told me that put item in/out to auction can random stats every time is wrong it is actaully can be changed once (by change version to 0), which lead me unable to reproduce correctly.

**Comment by insthync** [comment]
This is the fix https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_SharedData/commit/a5818963fe47e07b736d6cde4126cf26b0fe06b6
