### ISSUE TITLE
Server Authoritative Movement

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#26]
Using Server Authoritative Movement is causing severe stuttering on the player character.

**Comment by insthync** [comment]
I will check it

**Comment by insthync** [comment]
Try set SendOptions to Sequenced and Send Interval to 0.01 to make it sync position faster and arrive to clients sequenced
![Screenshot_149](https://user-images.githubusercontent.com/2697550/56136020-1ad27000-5fbc-11e9-9dbb-b90daee3ef8d.png)

**Comment by shubhank008** [comment]
Is Authoritative movement broken again ?

Enabling Server Authoritative Movement prevents that player from loading into the game.  The client stops at 100% Loading.

**Comment by insthync** [comment]
@shubhank008 As I try I don't having the problem, I want to see both server and client error logs.

**Comment by shubhank008** [comment]
> @shubhank008 As I try I don't having the problem, I want to see both server and client error logs.

Sorry I posted that message from another guy having problem in discord, forgot to update he said its fixed now. The below was his message:
"Apparently, if you set the Visibility Checker to 2D, it won't load with Server Auth enabled.
3D works tho, so, I forgot I had changed it."

Told him to report and open issues in github repo in future.
