### ISSUE TITLE
Scrolling with shooters

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#260]
Shooter controller still zooms in and out when ur over scrollview ui 
think this one was overlooked

**Comment by Callepo** [comment]
@insthync i meant scrolling not zooming

**Comment by insthync** [comment]
I don't understand this issue

**Comment by Callepo** [comment]
when u using shooter controller and have ur camera on able to scroll 
opening inventory.. when u scroll down ur items list ur camera zooms in and out while ur scrolling in ur inventory

https://github.com/suriyun-production/mmorpg-kit-docs/issues/253

same as this issue.. But for shootercharactercontroller camera

**Comment by insthync** [comment]
This was fixed in 1.54
