### ISSUE TITLE
Map drop options no longer work

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2600]
**Describe the bug**
As the description says, items are no longer dropped when dying on a certain map.

**To Reproduce**
Video Example :https://streamable.com/2ar4lg

**Expected behavior**
When you activate these options, everything should drop like in older versions, but it no longer drops anything.

**Desktop (please complete the following information):**
 - Version [1.89]

**Additional context**
I was reviewing the code and it seems that this line is always fulfilled and that is why it no longer drops anything 
![image](https://github.com/user-attachments/assets/34a30ba9-7f55-4ff5-8419-8dd00c589527)

**Comment by insthync** [comment]
You can just set high number dead drop in gameplay rule to fix it, that is it, seems like I have to change that condition to something else.

**Comment by Niinra** [comment]
I'm an idiot, sorry, I didn't realize that, I failed you :(
