### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object GraphicSettings.UrpAntiAliasingSetting.Load ()

### ISSUE THREAD

**Issue by bn9981** [suriyun-production/mmorpg-kit-docs#2601]
**Describe the bug**
NullReferenceException: Object reference not set to an instance of an object
GraphicSettings.UrpAntiAliasingSetting.Load () (at Assets/UnityMultiplayerARPG/Core/GraphicSettings/Scripts/UrpAntiAliasingSetting.cs:65)
GraphicSettings.GraphicSettingInitializer.Initialize () (at Assets/UnityMultiplayerARPG/Core/GraphicSettings/Scripts/GraphicSettingInitializer.cs:20)

**To Reproduce**
1. Create new URP project
2. Download and import latest mmorpg kit (version 1.89b) as showing on [follow](https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/101-getting-started-singleplayer-lan) 
3. Open then run demo scene  Assets/UnityMultiplayerARPG/Demo/Scenes/00Init.unity
4. Open setting in game and change anti-alias setting
5. Run demo scene again
6. See error

**Expected behavior**
No error showing on the console log.

**Screenshots**
![image](https://github.com/user-attachments/assets/6a927bbd-eebf-4929-a7e1-0f35e2df35ac)
![image](https://github.com/user-attachments/assets/cce21d21-1f0d-499e-98b4-d84e81259691)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
 - Unity version 6 (6000.0.23f1)

**Comment by Eniotnacram** [comment]
This is 100% unity and not related to the kit at all.

**Comment by bn9981** [comment]
@Eniotnacram  Can you please point me to correct the graphics setup? I only import whole kit into a fresh project and it using the demo setting from the kit. This is my graphics setting

![image](https://github.com/user-attachments/assets/b9d66066-dcfc-4eda-a673-0a07167c0917)

**Comment by Eniotnacram** [comment]
Could be related to the kit, go see whats on the line 65. But im using unit 6 at the moment, latest kit version, and I dont have this error.

**Comment by insthync** [comment]
Unity URP having changes again?

**Comment by insthync** [comment]
![Screenshot_1066](https://github.com/user-attachments/assets/e9e091a7-83b2-48a2-8f01-c7da9d939577)

Did you setup this one?
