### ISSUE TITLE
SelectedModel.UpdateAnimation(Time.deltaTime)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2602]
Hello,

I have a UI script to show my player character in my inventory. It is using SelectedModel.UpdateAnimation(Time.deltaTime). I was working very well before. In all versions, but after the 1.89 updates, the character animation is now very, very jittery, updated at like 1-2 fps. Nothing changed on the script and I tested back in 1.88 and it works fine. I cant figure out what changed in 1.89 to make this happen.

Can you help or maybe redirect me to where the issue could be? Could it be the new LOD logic in playable?

I can send My UICharacterViewer script privately if you want to.

**Comment by insthync** [comment]
Yes, it can be because of animation LOD

You may try to force it to update animation like this

```
model.UpdateAnimation(deltaTime);
model.animationLodUpdater.Graph.Evaluate(deltaTime);
```

In the next version it will have changes to update function to
`void UpdateAnimation(float deltaTime, bool disableLod)`
