### ISSUE TITLE
Monster movement jittery client view

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2605]
i noticed this many times but its random

https://gyazo.com/742cb6aeec8c6f2609d3244a12b49b79

right is server view left client view

on server to mosnter moves fine, but on client its jittery. sometims its good sometimes not, dont know why

**Comment by insthync** [comment]
It is because your character move too slow, if I fix this one another bug will occurs the bug which characters will not stop moving immediately when reached destination.

**Comment by moepi2k** [comment]
Kk np, when i build for linux its gone. I only have it when build for windows, very strange
