### ISSUE TITLE
Just upgraded to unity 6 and I have Siccity.SerializableCallback.Editor error

### ISSUE THREAD

**Issue by jacobjgrant** [suriyun-production/mmorpg-kit-docs#2606]
I have just upgraded to unity 6 installed json, input system and also adressables, but I have this error I cant seem to fix. Im sure in the last install I had to remove a folder not sure..

![image](https://github.com/user-attachments/assets/a76aba3d-b050-4016-945a-86cb96cd10a8)

**Comment by insthync** [comment]
Try removing `com.unity.learn.iet-framework` (Tutorial Framework) in package manage

**Comment by jacobjgrant** [comment]
Ok ill try that mate ty

**Comment by jacobjgrant** [comment]
Ok so i uninstalled the tutorial framework and got a ton of errors, so I re-installed package again and left with 1 different error mate..
![image](https://github.com/user-attachments/assets/cf855860-ed00-4c0a-bf22-44c7541995fb)

**Comment by insthync** [comment]
It is easy to fix by just change variable type, please try it.

When you are going to upgrade Unity to the version which the package is not fully support yet, you should know side-effects and please try to fix it by yourself.

**Comment by jacobjgrant** [comment]
Ok fixed it just need a colour. Thanks for help buddy much appreciated
