### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by AlcidesJunior123** [suriyun-production/mmorpg-kit-docs#2607]
How do I change these player entity icons when creating a character in the entity window?
![abc5c42d-0c28-42cd-8323-c652562ba27a](https://github.com/user-attachments/assets/3397381a-5f9d-499f-ad66-a5891a2e333c)
![2cc14b6b-02a2-413a-9f08-d8f792ece4cc](https://github.com/user-attachments/assets/76111cb6-6100-4dcd-93ba-bf8b2d878e76)

**Comment by Eniotnacram** [comment]
Dont create issues for that.. Go to the community discord, and we'll gladly answer that. But the short answer is that it's in the character scriptable object of that class.
