### ISSUE TITLE
Config folder can be totally deleted, server will somehow remember values.

### ISSUE THREAD

**Issue by epicality85** [suriyun-production/mmorpg-kit-docs#2608]
**Describe the bug**
If you upload a server build to a linux server, allow it to start up (it creates a folder 'Config', and then shut it down again, or stop the process. If you delete the config folder, the server somehow remembers the information in the configs. 

**To Reproduce**
1. Build and deploy to linux.
2. Start server with options, note that it creates config folder.
3. Shut server down.
4. Delete config folder (rm -r Config/), or rename it to '_Config'.
5. Start server again, note in logs says config found at ./Config/serverConfig.json

**Expected behavior**
I expect that deleting the config files would make the server either recreate them or crash out on null exception.

**Screenshots**
Not required.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
I am having a connection error to the map server, and cannot figure out where the map names are coming from.  The server starts up and runs all instances of maps, but I can't tell which maps are actually running using Linux top command.  I have even deleted the entire folder in root folder and rebuilt, to no avail.

**Comment by epicality85** [comment]
Any thoughts on this bug?

**Comment by Niinra** [comment]
> Any thoughts on this bug?

As I understand it, if a config does not exist, one will be created automatically, although I am not sure, but what is the problem?

**Comment by insthync** [comment]
Yes, if a config does not exist it will be created by using settings from components

**Comment by epicality85** [comment]
Yeah I understand fully that it will, but why does it work if I delete the configuration folder and restart the server? Does the forced termination (ctrl+c) maybe leave a variable allocated and pointed? I will try to get a screen recording of it.

**Comment by insthync** [comment]
it creating config files just for being an example so you will be able make chnages easily, and it will never being saved again while server is running, it just read and forget the files, that is it. 

what is the problems?

**Comment by insthync** [comment]
No responding, so I will determine that it has no problem.
