### ISSUE TITLE
maxLevel in BaseSkill

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2609]
Hello,

Is it possible to make the MaxLevel int in BaseSkill a property instead or in any other way that it is possible to override in upper classes?

Or remove the range of it? Because I would like my max skill level to be 200 but it's getting locked to 100 without any modifs. If I make the Maxlevel "new" in my class,  it gives serialization errors in the editor.

**Comment by insthync** [comment]
Hmm, how is it being locked?

**Comment by Eniotnacram** [comment]
Because of the range set from 1 to 100 in the baseSkill

**Comment by insthync** [comment]
Cannot set its max level to 200

**Comment by Eniotnacram** [comment]
If I modify the BaseSkill yes, but that's a core modif and not convenient. I just don't get why there is a range for that. We could remove it and if we want 1000 levels we could set it up

**Comment by Eniotnacram** [comment]
As per the screen, because of the range, the max level is set to 100. So in Skill, or any other class that inherits base skill, the max level is 100 and cannot be changed as it's not overridable. The only option is to modify the BaseSkill class.

![Screenshot 2024-11-11 at 8 59 08 AM](https://github.com/user-attachments/assets/7d72d2b0-4c8a-4d91-8f84-e26b8533a82f)

**Comment by insthync** [comment]
Oh, i see, it actually must not have range limit

**Comment by Eniotnacram** [comment]
> Oh, I see, it actually must not have range limit

Yes, that would be better, and more flexible.
