### ISSUE TITLE
Avatar is null

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#2611]
Hi , i have created my character prefab and when i test it , i get this error 
![1](https://github.com/user-attachments/assets/5df36555-ae55-45a9-8b9d-fc17b705c571)
when i create avatar and avatar mask i get this error 
![2](https://github.com/user-attachments/assets/c93e7f6c-0dcf-4d05-981d-56cadcb04610)
note : i use generic type , not humanoid and when i test without avatar , character works fine with animations and with avatar no animation works

**Comment by insthync** [comment]
for the first one , i guess it is because of transform copy component which made for humanoid

the second one i think you might use the wrong avatar

**Comment by RunOrDi3** [comment]
I didn't copy any component , i just created it by Character Entity Creator (3D) and im sure i use the same avatar

**Comment by Eniotnacram** [comment]
Not a bug, it's a setup fault. Come in discord @RunOrDi3

**Comment by RunOrDi3** [comment]
> Not a bug, it's a setup fault. Come in discord @RunOrDi3

Whats your name in Discord ?

**Comment by Eniotnacram** [comment]
Go in the public MMORPG kit discord server

**Comment by RunOrDi3** [comment]
Fixed it , it's because a component called FollowBone in CanvasIsInSafeArea .. not from my setup character 
![1](https://github.com/user-attachments/assets/647ea9d0-045c-440c-87af-ec3f7e18b904)
