### ISSUE TITLE
Player Storage Bug

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#2612]
Hello

offline player storage items not saved

**Comment by Niinra** [comment]
Friend, this is a bit annoying that you just say this doesn't work and that's it. Please send a video or some images reproducing the error because it may happen that several of us don't have this problem.

**Comment by moepi2k** [comment]
i think he just use an old kit version. because it was fixed in 189 i think

**Comment by fedas61** [comment]
I am using the latest version
The old version did not have this problem

**Comment by fedas61** [comment]
https://github.com/user-attachments/assets/4ebd1e95-63a5-4f0f-bfb4-460beba65e2e

**Comment by insthync** [comment]
As I test, it has no problem, you may have to wait for a new version, might be uploaded in next 20 hours
