### ISSUE TITLE
[SUG]option that skill level, increase by monster level

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2613]
as title said. right now you can just set a flat level. so e.g u set skill level to 1 then a level 1 monster has the same skill level like a level 100 monster. makes it hard to balance monsters

**Comment by Eniotnacram** [comment]
Can't you set the skill level by level on the monster scriptable? I think you could. So monster lvl 30 would have that skill level 30 for example.

**Comment by insthync** [comment]
Okay, I will change it to be a incremental int
