### ISSUE TITLE
LastUpdated read as local instead of UTC. Latest version.

### ISSUE THREAD

**Issue by codecustard** [suriyun-production/mmorpg-kit-docs#2618]
**Describe the bug**
LastUpdated seems to read as local when expected behaviour is to read it as UTC.

**To Reproduce**
1. Add a trigger to update 'lastUpdated' (Tested SQLITE)
```
// Create the trigger to automatically update the 'updateAt' column on updates
ExecuteNonQuery(@"CREATE TRIGGER IF NOT EXISTS update_characters_updateAt
                AFTER UPDATE ON characters
                FOR EACH ROW
                BEGIN
                    UPDATE characters
                    SET updateAt = CURRENT_TIMESTAMP
                    WHERE id = OLD.id;
                END;"
            );
```
2. Retrieve from database:

 ```
PlayerCharacterData characterData = await GetCharacterWithUserIdValidation(request.CharacterId, request.UserId);

            if (characterData != null)
            {
                long lastOnline = characterData.LastUpdate;
                long currentTime = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
                long elapsedTime = currentTime - lastOnline;

                if (writeAddonLogOfflineRewards)
                {
                    // Convert Unix timestamps to DateTimeOffset
                    DateTimeOffset lastOnlineTime = DateTimeOffset.FromUnixTimeSeconds(lastOnline);
                    DateTimeOffset currentDateTime = DateTimeOffset.FromUnixTimeSeconds(currentTime);

                    Debug.Log($"[DEVEXT] [{name}] - {characterData.CharacterName}");
                    Debug.Log($"[DEVEXT] [{name}] - Last Online: {lastOnline} (Unix Timestamp) / {lastOnlineTime}");
                    Debug.Log($"[DEVEXT] [{name}] - Current Time: {currentTime} (Unix Timestamp) / {currentDateTime}");
                    Debug.Log($"[DEVEXT] [{name}] - Offline Time: {elapsedTime} seconds");
                }
            }
```

3. Notice invalid date/time.

**Expected behavior**
![image](https://github.com/user-attachments/assets/22e81dc1-79b1-404f-b25c-bdb0872592c3)

**Wrong behavior Screenshots**
![image](https://github.com/user-attachments/assets/3307eb1f-1a58-41dc-9f54-8d9d480b3337)
![image](https://github.com/user-attachments/assets/f7079c9c-cf6d-4743-bac8-7dd7d180d831)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Latest kit version 1.89

**Solution**
Specify kind before casting.
![image](https://github.com/user-attachments/assets/9aff9287-de1c-4579-bea4-d9a2fd1a3763)
Kind is unspecified so the cast treats the date wrong.

**Comment by Eniotnacram** [comment]
So replace the line with this right?

                result.LastUpdate = ((System.DateTimeOffset)System.DateTime.SpecifyKind(reader.GetDateTime(38), System.DateTimeKind.Utc)).ToUnixTimeSeconds();

**Comment by Eniotnacram** [comment]
@insthync can you take a look at this? I think that's right and it should be using UTC

**Comment by insthync** [comment]
https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManagerSource/commit/7bd6b9d9bc9da4eff2eb1a4acb7ddef24a405d18

Is this enough?

**Comment by Eniotnacram** [comment]
Looks right, thank you !
