### ISSUE TITLE
190 update

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2619]
updated project to 190 and when i click play (not even in home screen) i get this error

https://gyazo.com/b2bc69ebf99fe38172d6bcddfe96a10b

when i click the error it shows my diffren scriptable which not even have something todo with that script. i removed the script  and then i just spam the same error with another script.

**Comment by insthync** [comment]
Did you try to close unity and reopen it?

**Comment by insthync** [comment]
You may try to replace codes in `BaseGameData`

```
        [Tooltip("Game data ID, if this is empty it will uses file's name as ID")]
        [SerializeField]
        protected string id = string.Empty;
        public virtual string Id
        {
            get { return string.IsNullOrEmpty(id) ? (this == null ? string.Empty : name) : id; }
            set { id = value; }
        }
```

I don't know how is your scriptable object instance is empty, do you have any scripts which create game data instance at runtime ?

**Comment by moepi2k** [comment]
yes even removed whole library folder, thoguht there is a serialization issue.

**Comment by moepi2k** [comment]
no most of my custom scriptables have just custom conditions like https://gyazo.com/2f107e030069a409ca1d5c821927e089

**Comment by insthync** [comment]
Try what I've told you

**Comment by moepi2k** [comment]
> You may try to replace codes in `BaseGameData`
> 
> ```
>         [Tooltip("Game data ID, if this is empty it will uses file's name as ID")]
>         [SerializeField]
>         protected string id = string.Empty;
>         public virtual string Id
>         {
>             get { return string.IsNullOrEmpty(id) ? (this == null ? string.Empty : name) : id; }
>             set { id = value; }
>         }
> ```
> 
> I don't know how is your scriptable object instance is empty, do you have any scripts which create game data instance at runtime ?

this is working but then im wondering why i have empty data..

**Comment by insthync** [comment]
Maybe just an empty ref to any game data scripts

**Comment by moepi2k** [comment]
ok i will check thx
