### ISSUE TITLE
Map Loading gage finished before loading the map (before spawn all monsters)

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#262]
Game Type : Single
My map has a lot of monsters so it takes some time to finish spawning all monsters to the map.
But the map loading gage is finished (100%) and show frozen map scene until all monsters are spawned.

I had a look into UINetworkSceneLoading.cs but I cannot find the how to update "progress" value for the gage according to the monster spawning. 

Can you advise me how to make this loading gage works  with the monster spawning?

**Comment by insthync** [comment]
Loading progress update at LiteNetLibGameManager.cs → LoadSceneRoutine, I will change OnClientOnlineSceneLoaded and OnServerOnlineSceneLoaded to by async function, so it can wait until  OnClientOnlineSceneLoaded and OnServerOnlineSceneLoaded finished before onLoadSceneFinish event will be called.

**Comment by insthync** [comment]
Oh, I change my mind, I won't change OnClientOnlineSceneLoaded and OnServerOnlineSceneLoaded to be async function. I will add spawn entities start / progress / finish to SpawnEntities function in BaseGameNetworkManager

**Comment by insthync** [comment]
I've added spawn entities start / progress / finish events to LanRpgNetworkManager, you can set and callbacks from UINetworkSceneLoading like this.

![Screenshot_57](https://user-images.githubusercontent.com/2697550/76284426-d9336d80-62cf-11ea-8acc-d70ed97bb140.png)

**Comment by dglee2592** [comment]
Thank you so much!!!!
