### ISSUE TITLE
Monster Activity Component

### ISSUE THREAD

**Issue by Credosk** [suriyun-production/mmorpg-kit-docs#2623]
Hello,

I'm working on modifying the behavior of enemies (monsters) in MMORPG Kit, and I'm encountering an issue that I can't seem to resolve. I would like to ask for your help in implementing the following behavior.

Specifically, I need the enemy to immediately stop returning to its spawn point and start attacking the player if it receives damage during the return. Currently, I added a custom extended method (onReceivedDamage) where I monitor if the enemy gets hit, and I try to force it to stop and attack. However, even after making this modification, the enemy pauses for a moment but then continues returning to the spawn point instead of attacking the player.

I have added code that checks whether the enemy is returning and, if so, stops its movement using MovementComponent or StopMove, but I am getting errors stating that these methods or properties do not exist. I am also unable to correctly assign the attack target to the enemy.

I would like to request your help with the following:

How can I properly stop the movement of the enemy when it's returning to its spawn point so that it reacts immediately to a player's attack?
How can I correctly assign the attack target (the attacking player) to the enemy so that it stops returning and starts attacking?
I have also tried using MonsterCharacterEntity_Extension.cs and DevExtMethods to implement extensions, but I still can't achieve the desired behavior. If you have any recommendations or an example of how to correctly implement this within MMORPG Kit, I would greatly appreciate it.

Additionally, if anyone in the community has experience with this kit and would be willing to help me with more complex modifications, I'm open to offering financial compensation. I have several planned changes that will require deeper modifications, and I would greatly appreciate the assistance of someone with expertise.

Thank you very much for your help in advance.

**Comment by Eniotnacram** [comment]
Yea no dev ext needed for that, you need to expand the MonsterActivityComponent and you can simply create a new class that inherits it and override/add what is needed.

**Comment by insthync** [comment]
If you can do coding, I recommend you to inherit `BaseMonsterActivityComponent` and implements your logic as you wish :)
