### ISSUE TITLE
Migrate process not working for .net database

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2624]
the migrate process is not working when have fresh mysql database an starting the server for the first time with .net database

https://gyazo.com/6af1daf6398cca15cba77fb0bcf43899

i changed to start server with default database and then it migrate process was done (seen in console)
so i checked mysql tables and the accesstokken default was ""

then switched back ti .net and i was able to register account. but then when create a character i got the reputation issue again.

dont know if the migrate process for the reputation thing is separate when in character creation window.

**Comment by insthync** [comment]
Fixed

**Comment by moepi2k** [comment]
that was fast :) thank you very much
