### ISSUE TITLE
Refine not work

### ISSUE THREAD

**Issue by Credosk** [suriyun-production/mmorpg-kit-docs#2627]
Hello, I'm currently testing version 1.90b and I found that the refine of any item does not work, is this a problem only for me or does anyone else have it?

**Comment by Eniotnacram** [comment]
Have you tested in the fresh kit? What doesn't work? Any errors? Any screenshots?

Highly suggest testing in the fresh kit without modifications, in MMO and single-player, to reproduce the issue. If it happens, surely means it's a bug if it doesn't, means it's a miss configuration from your project.

**Comment by Credosk** [comment]
I tried it on a more empty new version without any modification, nothing happens at all, I open the refine window and when I select an item and click on Refine, nothing happens, it cannot be added there.

**Comment by insthync** [comment]
I will check it

**Comment by insthync** [comment]
Fixed
