### ISSUE TITLE
[BUG]Invisible

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2628]
there are few weird bugs with invisible visible, video -> 

https://gyazo.com/b9b44bc1b33bfa68b2260239d889d095

when mount unmount while using visible invisible it lead to issues (mounts visible while character is invisible) then it spams an error

Error -> https://gyazo.com/8325c8810accaac67a761826dd0dd8ac

and sometimes whle using the mount while invisible (dont know whats the excat step) but seems making visible while unmounted then while mounted use invisible or vise versa then in view of other player the player dies.

also the new visible invisible option for equipment entity. it only updates only once u use invisible. but while invisible and equip other item the defualt material appears

**Comment by insthync** [comment]
I will check it

**Comment by insthync** [comment]
Okay, I make it hide its vehicle when the driver hide
