### ISSUE TITLE
Monster animations

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#263]
Monsters still using Charactermodel for animator controller.. which is old i think.. and if u put animations in here.. it keeps using the default animations..and u have to make new controller for each monster..
![Capture](https://user-images.githubusercontent.com/7702658/76120655-cd316e00-5fa6-11ea-9441-177cdc1e6a79.PNG)

This needs to be swapped out with Animtor character model... and then it will work like intended.
Alot of people asking why it dont work..
![Capture](https://user-images.githubusercontent.com/7702658/76120686-db7f8a00-5fa6-11ea-977b-1b485d4a4f84.PNG)

i helped them figure it out but would be nice if it was by default

**Comment by insthync** [comment]
In next version I will add context menu to help developer to convert character model  easier.

![Screenshot_53](https://user-images.githubusercontent.com/2697550/76124638-b97d1a80-602d-11ea-81d0-898818eca551.png)

**Comment by Callepo** [comment]
cool

**Comment by insthync** [comment]
The context menu was added to 1.54
