### ISSUE TITLE
[BUG]Npc 190b

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2631]
NPC are broke in 190b. existing npc works but when u add a new one to scene it get invalid data when interact with him

https://gyazo.com/54b624682b293ffd019619bf7cc743a8

**Comment by insthync** [comment]
Did you set it's id?

**Comment by moepi2k** [comment]
What id? Litenetlib? I made npc same time as always. Bit the thibg is the npc which was in scene before upgrafe kit are working. U can just add  the same again and it not working

**Comment by insthync** [comment]
https://youtu.be/hZRyM50JyLY ??

**Comment by moepi2k** [comment]
so what u did? in just use a fresh project 190b and just placed npc1 in scene. same error for my game

**Comment by moepi2k** [comment]
the thing is objectid in litenetlib will not set when place npc in scene. never had this issue before and i never set them manualy

**Comment by insthync** [comment]
tra

**Comment by moepi2k** [comment]
So maybe u should mention this in patch notes and docu so ppl know about it

**Comment by insthync** [comment]
No

**Comment by moepi2k** [comment]
Ok 😅

**Comment by Callepo** [comment]
Just my opinion lol.

After having Entities world 1 way for as long as i can remember in the kit.. 
Being able to just drag and drop them and it works.. IS honestly in my opinion the correct way it should work..

Needing to do it manually now for no reason is just moving backwards.
Its like saying Next kit version, there will be 0 scripts, u gotta write them manually lol. 

i dont know if this was done intentionally or a side effect of some changes. but 99% of the community doesnt know what object id even is.. they will drag and drop in the scene.. and come ask u why it doesnt work.

this will not be the last time u get this report im 100% of it.
Even if this was done Intentionally, it doesnt feel like an improvement, rather old and bad.

ill check the codes and see what was changed, if i can make the functionally work as it did before ill push it.. 
up to you if u wanna keep it or not <3

**Comment by Callepo** [comment]
@insthync https://github.com/insthync/LiteNetLibManager/commit/466f9e4d3455d0a920cbefa871d007d4bcb47183
May i ask why it was changed to manual ? what was the problem with it ? maybe idk why it was changed.

Prolly has a good reason

**Comment by insthync** [comment]
I have plans to make changes, It was setup object ID > 0 for scene object automatically, and spawning by that, the problem is it is not reliable, I am going to change its workflow, for scene objects, it won't use saved object ID anymore in the future, it will use in-scene object -> hashed asset ID to instantiates scene object instead, so everything in scene will be place holder, and will be destroy when server/client start, but before destroying it will store asset ID and its transform to memory, to spawn from asset, workflow after this will be like generic networked objects instantiation. but it still can have problem with in scene object which is not prefabs which no asset ID, I might use its name instead, and may sort by position.

**Comment by Callepo** [comment]
> I have plans to make changes, It was setup object ID > 0 for scene object automatically, and spawning by that, the problem is it is not reliable, I am going to change its workflow, for scene objects, it won't use saved object ID anymore in the future, it will use in-scene object -> hashed asset ID to instantiates scene object instead, so everything in scene will be place holder, and will be destroy when server/client start, but before destroying it will store asset ID and its transform to memory, to spawn from asset, workflow after this will be like generic networked objects instantiation. but it still can have problem with in scene object which is not prefabs which no asset ID, I might use its name instead, and may sort by position.

Ah i see , i believe its best to keep it automatically until its gone. Thats up 2 you tho.

Seems we are just in a bad time atm in between transition from old to new methods and it just feels bad now.
cuase u will have more people asking this, some also pmed me about it, i had to update my project to test it to make sure its really changed or they not doing some dumb XDDD
