### ISSUE TITLE
Fresh import errors

### ISSUE THREAD

**Issue by wendellsn** [suriyun-production/mmorpg-kit-docs#2635]
**Describe the bug**
its a fresh  install,

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\Transports\WebSocket\WebSocketClient.cs(78,24): warning CS0414: The field 'WebSocketClient._error' is assigned but its value is never used

The GUID inside 'Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/AddressableAssets.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.

The GUID inside 'Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/AddressableAssets.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.

The GUID inside 'Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/AddressableAssets.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.

The GUID inside 'Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/AddressableAssets.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.

Creating missing CharacterLadderComponent component for PlayerCharacterEntity2D in Warrior2D.

Creating missing CharacterLadderComponent component for MonsterCharacterEntity2D in OrcsArcher2D.

Creating missing CharacterLadderComponent component for PlayerCharacterEntity2D in OrcsWarrior2D.

![image](https://github.com/user-attachments/assets/329f6fe8-14a7-4c36-98a6-40ad4a29bb5e)

i was trying to follow teh document but it was sayigng to skill the install of dependencies; but when i fif skip i've got 89 errors.
than i installed the dependencies and got only those.
do you have any updated tutorial video? im new to this and doing for myself

windows 11 
unity version 2022.3.53f1

**Comment by insthync** [comment]
All of those can be ignored
