### ISSUE TITLE
Put FxCollection to partial

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2636]
Hello,

As the GameEffect class is now partial we can do more with it, but we are still locked by FxCollection not being partial and not having it's variable protected.

So can I ask to put FxCollection to partial and change the variable to protected?

Like that:

[FxCollection.txt](https://github.com/user-attachments/files/17962631/FxCollection.txt)

**Comment by insthync** [comment]
Can, but I want to know how are you going to extend it?

**Comment by Eniotnacram** [comment]
Simply want to add a new public function in it to destroy smoothly. And I need the particles reference, audio source etc.

And I will use that function in my Game effect class

**Comment by insthync** [comment]
Can you share the destroy function code?
