### ISSUE TITLE
IsWeaponSheathed MMO Action restrictions not working

### ISSUE THREAD

**Issue by jprules321** [suriyun-production/mmorpg-kit-docs#2639]
I made Component to sheath and unsheath weapons. On LanRPG build the restrictions in CanUseSkill and CanAttack are working since if the weapon is sheathed you cannot attack or use skills.

On MMO build, you can still use skills and attack when weapon is sheated.

I have confirmed that the IsWeaponSheated is properly set on the server and the client and also synced across multiple clients, however, the server still let you attack.

The code below is my component, I know that I did not have to use "ServerRPC" because the SyncMode is set to Multicast but I wanted to make sure that the server gets the message.

Maybe I am doing something wrong ?

```
using LiteNetLibManager;
using UnityEngine;

namespace MultiplayerARPG
{
    public class WeaponSheathComponent : BaseNetworkedGameEntityComponent<BaseCharacterEntity>
    {

        public override void EntityUpdate()
        {
            if (!Entity.IsOwnerClient)
                return;

            if (Entity.IsRecaching)
                return;

            if (!Entity.CanDoActions()) 
                return;

            if (InputManager.GetButtonDown("Sheath"))
            {
                if (Entity.IsWeaponsSheathed)
                    RPC(UnSheathWeapon);
                else
                    RPC(SheathWeapon);
            }
        }

        [ServerRpc]
        public void SheathWeapon()
        {
            if (!IsServer) return;
            Entity.IsWeaponsSheathed = true;
        }

        [ServerRpc]
        public void UnSheathWeapon()
        {
            if (!IsServer) return;
            Entity.IsWeaponsSheathed = false;
        }

    }
}
```

**Comment by khongtuong** [comment]
use this:
`using LiteNetLibManager;

namespace MultiplayerARPG
{
    public partial class PlayerCharacterEntity
    {

        [DevExtMethods("Awake")]
        protected void PlayerSheathAwake()
        {
            onUpdate += PlayerSheathOnUpdate;
            IsWeaponsSheathed = !IsWeaponsSheathed;
        }

        [DevExtMethods("OnDestroy")]
        protected void PlayerSheathOnDestroy()
        {
            onUpdate -= PlayerSheathOnUpdate;

        }

        protected void PlayerSheathOnUpdate()
        {
            if (!IsOwnerClient)
                return;

            if (this.IsDead())
                return;

            if (InputManager.GetButtonDown(CurrentGameInstance.sheathButtonName))
            {
                IsWeaponsSheathed = !IsWeaponsSheathed;
            }
			
			if (PlayingCharacterEntity.IsInSafeArea)
			{
				if (!PlayingCharacterEntity.IsWeaponsSheathed)
					PlayingCharacterEntity.IsWeaponsSheathed = !PlayingCharacterEntity.IsWeaponsSheathed;
			}
        }
    }
}`

**Comment by insthync** [comment]
@jprules321 It is being proceeded from client (by owner client) so you won't have to use RPC, just set `IsWeaponsSheathed`
's value directly

**Comment by jprules321** [comment]
Hi, thanks for taking the time.

I understand, as I said, I did it like you suggest at first. I just tried again, and, in LanRPG while your weapon is sheathed you cannot attack. However, in the MMO build, you can still attack and use skills.

I have confirmed that the IsWeaponSheated is synced on MMO server aswell so I dont understand why.

**Comment by insthync** [comment]
Just change it to 
```
using LiteNetLibManager;
using UnityEngine;

namespace MultiplayerARPG
{
    public class WeaponSheathComponent : BaseNetworkedGameEntityComponent<BaseCharacterEntity>
    {

        public override void EntityUpdate()
        {
            if (!Entity.IsOwnerClient)
                return;

            if (Entity.IsRecaching)
                return;

            if (!Entity.CanDoActions()) 
                return;

            if (InputManager.GetButtonDown("Sheath"))
            {
                if (Entity.IsWeaponsSheathed)
                    Entity.IsWeaponsSheathed = false;
                else
                    Entity.IsWeaponsSheathed = true;
            }
        }
    }
}
```

**Comment by jprules321** [comment]
The reason I made a public function is that I want to call SheathWeapon on Monsters. But it is like this now :

```
using LiteNetLibManager;
using UnityEngine;

namespace MultiplayerARPG
{
    public class WeaponSheathComponent : BaseNetworkedGameEntityComponent<BaseCharacterEntity>
    {

        public override void EntityUpdate()
        {
            if (!Entity.IsOwnerClient)
                return;

            if (Entity.IsRecaching)
                return;

            if (!Entity.CanDoActions()) 
                return;

            if (InputManager.GetButtonDown("Sheath"))
            {
                if (Entity.IsWeaponsSheathed)
                    UnSheathWeapon();
                else
                    SheathWeapon();
            }
        }

        public void SheathWeapon()
        {
            Entity.IsWeaponsSheathed = true;
        }

        public void UnSheathWeapon()
        {
            Entity.IsWeaponsSheathed = false;
        }

    }
}
```

Still the same problem in the MMO build.

**Comment by jprules321** [comment]
Sorry I'm an idiot. I was using the wrong ActionInput on Gameinstance MMO so Sheath button never triggered properly.
