### ISSUE TITLE
Re-cast buff effects when use/unuse mounts

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#264]
Is this a bug or is it planned like that?
[Re-cast buff effects when use mounts.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4301465/Re-cast.buff.effects.when.use.mounts.zip)

**Comment by insthync** [comment]
This is a bug :P

**Comment by DimasjkTV** [comment]
> This is a bug :P

Also, effects re-cast when switching between locations

**Comment by insthync** [comment]
It was fixed in 1.54 except when teleporting to another map
