### ISSUE TITLE
191 unplayable, and monster skill calc by level is wrong

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2641]
it seems something broke 191 hard. every action or attack leads to massiv fps spike. around 250ms.

and this is also broken
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2626

dont know what math it is but it has no logic. it starts something like x3 and at the end its 700 or so

**Comment by insthync** [comment]
Mine work properly, no more info?, Did you try to look at profiler to find which function cause it?

**Comment by insthync** [comment]
Quick I am waiting

**Comment by insthync** [comment]
Hey, you said it is unplayable, which is critical, why I have to wait for the info?

**Comment by moepi2k** [comment]
was testing. it seems its the changes from the fix of https://github.com/suriyun-production/mmorpg-kit-docs/issues/2626
because i only added those changes to mine to test and since than i have ultra fps drop after every action

**Comment by moepi2k** [comment]
https://gyazo.com/9d7b7f2dc5841e6c2ef128943f2e8896

**Comment by insthync** [comment]
Unplayable ?

**Comment by moepi2k** [comment]
yes as u see in video. 0.8mb every action. every attack i got lag spikes

**Comment by moepi2k** [comment]
https://gyazo.com/297892b67e56911ddde91f6529cf87bc

both. monster and player

**Comment by moepi2k** [comment]
i gues at this point but im pretty sure its the changes u made for this https://github.com/suriyun-production/mmorpg-kit-docs/issues/2626

because i manualy added that to check and since there i have it.

**Comment by insthync** [comment]
Okay, I will check it later, I have to sleep

**Comment by insthync** [comment]
Try these changes

*Scripts/CharacterData/CharacterDataExtensions.cs -> ValidateSkillToUse*
```
        public static bool ValidateSkillToUse(this BaseCharacterEntity character, int dataId, bool isLeftHand, uint targetObjectId, out BaseSkill skill, out int skillLevel, out UITextKeys gameMessage)
        {
            skillLevel = 0;
            gameMessage = UITextKeys.NONE;

            if (!GameInstance.Skills.TryGetValue(dataId, out skill))
                return false;

            if (!character.GetCaches().Skills.TryGetValue(skill, out skillLevel) ||
                !skill.CanUse(character, skillLevel, isLeftHand, targetObjectId, out gameMessage))
                return false;

            return true;
        }
```

*Scripts/GameData/Character/MonsterCharacter.cs -> GetSkillLevels*
```
        public override Dictionary<BaseSkill, int> GetSkillLevels(int level)
        {
            if (level <= 0)
                return new Dictionary<BaseSkill, int>();
            return GameDataHelpers.CombineSkills(skills, new Dictionary<BaseSkill, int>(), level);
        }
```

*Scripts/GameData/Character/PlayerCharacter.cs -> GetSkillLevels*
```
        public override Dictionary<BaseSkill, int> GetSkillLevels(int level)
        {
            if (level <= 0)
                return new Dictionary<BaseSkill, int>();
            return GameDataHelpers.CombineSkills(skills, new Dictionary<BaseSkill, int>(), level);
        }
```

**Comment by moepi2k** [comment]
perfect, that fixed it. thank you very much
