### ISSUE TITLE
191 LitenetlibIdentity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2642]
sorry to bug u again. but i notice now in 191 everytime when login it stuck in loading screen when change maps with following errors

MissingReferenceException: The object of type 'LiteNetLibIdentity' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Object.Instantiate[T] (T original) (at <2d8783c7af0442318483a199a473c55b>:0)
LiteNetLibManager.LiteNetLibAssets.InitPoolingObject (System.Int32 hashAssetId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibAssets.cs:269)
LiteNetLibManager.LiteNetLibAssets.InitPoolingObjects () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibAssets.cs:240)
LiteNetLibManager.LiteNetLibGameManager.ProceedOnlineSceneLoaded (LiteNetLibManager.ServerSceneInfo serverSceneInfo) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:410)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:218)
LiteNetLibManager.LiteNetLibGameManager.LoadSceneRoutine (LiteNetLibManager.ServerSceneInfo serverSceneInfo, System.Boolean isOnline) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:393)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskScheduler.cs:90)
LiteNetLibManager.<LoadSceneRoutine>d__70:MoveNext() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:402)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.cs:25)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:210)
LiteNetLibManager.<ProceedOnlineSceneLoaded>d__71:MoveNext() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:438)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:194)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Update() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:159)
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run() (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/ContinuationQueue.cs:118)

im not sure hows the workflow for litenetlibidentity now. since the objectid is no longer greyd out and we are able to fill own objectid. anyway when i have scene objects it doesntmater if i have set an objectid or not same for assetid. i always get this error

**Comment by insthync** [comment]
Don't have to set the object ID for scene objects anymore, all in-scene objects will be determined as a prefab, then it will instantiate those objects later, about the error, I will check it later.

**Comment by moepi2k** [comment]
mhh but then it will mess reference when i have for example doors and levers which are referenced by assigned it in inspecotor.
in singleplayer it works fine. 

https://gyazo.com/2bfc78bebed59415b5d4b0226214d509

but in multiplayer all my levers have same changed to doors 

https://gyazo.com/fc461b14850e23ec62b883934c1b7438

i have alot of networked stuff like puzzle mini games etc which have references to each other. so when it gets destroyed on init. how will it work anymore?

**Comment by insthync** [comment]
Okay, I will bring back the old one

**Comment by moepi2k** [comment]
if you had something in mind im open for changes. just wanted to know whats the idea. because right now its difficult to handle situation like this

e.g one minigame for example looks like this 

https://gyazo.com/8eb35d6546971c445b8d9ecca06484aa

its a prefab in the prefab i have a door and 4 levers. all are separate objects with litenetlib. then i have a manager which handle all the logic and in the inspector i set the references for it. i think the problem is right now it handles the whole prefab as one and replace all the child object to same type and lose reference.

**Comment by insthync** [comment]
My idea is just to make it work, that is it.

**Comment by moepi2k** [comment]
mh  what was broken with scene object? any hints what i need to redo so it works in old way?

**Comment by insthync** [comment]
Yes, I knew it was broken for your project, can't you just wait me to fix it?

If you want to revert then just check LiteNetLibManager commits, it have a few, so you will be able to find what you have to do easily.

**Comment by moepi2k** [comment]
okey thank you

**Comment by insthync** [comment]
Try the latest version of LiteNetLibManager

**Comment by moepi2k** [comment]
no its not working. i made it like this and works as before with scene objects 

https://file.io/H9mYgnGmWKec

**Comment by moepi2k** [comment]
i think for ur new solution the problem is that objectid for scene object are still not set automaticly. even when u check autoassignsceneobjectid it leave the objectid field empty it will not generate it. why not making this field just readonly and auto set id on runtime as before? i saw u added networkobjectid for the new usecase. the problem is when u need to set it manualy and u have 1000 of objects u need to be worried about of not set same objectid for diffrent objects. so how is objectid generated to make it unique?

**Comment by insthync** [comment]
Try Context menu -> generate

**Comment by insthync** [comment]
I will not assign ID at runtime anymore, it is not reliable, but I will make it generate when save scene.

**Comment by moepi2k** [comment]
oh ok good to know then, yea solution with generating them using contex menu is working. but u def should mention it somewhere. im sure other will face same problem then. 

thank you very much for the update

**Comment by moepi2k** [comment]
mh still facing another issue now. seems like objectid is now initialized later? because i have some code which need objectid and its initialized in awake. but now i enter game its objectid is always 0 because before it was read in awake.

**Comment by insthync** [comment]
Yes, how do you using the object ID?

**Comment by moepi2k** [comment]
```
using UnityEngine;
using System.Collections.Generic;

namespace MultiplayerARPG
{
    public class MultiTriggerManager : MonoBehaviour
    {
#if (UNITY_EDITOR || UNITY_SERVER || !EXCLUDE_SERVER_CODES) && UNITY_STANDALONE
        [SerializeField]
        private MultiTriggerLever_Hubi lever1;
        [SerializeField]
        private MultiTriggerLever_Hubi lever2;
        [SerializeField]
        private MultiTriggerLever_Hubi lever3;
        [SerializeField]
        private MultiTriggerLever_Hubi lever4;
        [SerializeField]
        private MultiTriggerDoor_Hubi doorObj;

        [Tooltip("Set the lever sequence by index: 0 = Lever1, 1 = Lever2, 2 = Lever3, 3 = Lever4")]
        [SerializeField]
        private List<int> leverSequence = new List<int>(); // Sequence defined in the Inspector by indices.

        private List<uint> correctSequence = new List<uint>(); // Stores ObjectIds resolved from leverSequence.
        private List<uint> activationSequence = new List<uint>();
        private List<MultiTriggerLever_Hubi> levers = new List<MultiTriggerLever_Hubi>();

        private void Awake()
        {
            // Add all levers to a list for easier referencing
            if (lever1 != null) levers.Add(lever1);
            if (lever2 != null) levers.Add(lever2);
            if (lever3 != null) levers.Add(lever3);
            if (lever4 != null) levers.Add(lever4);

            InitializeCorrectSequence();
        }

        private void InitializeCorrectSequence()
        {
            correctSequence.Clear();
            foreach (int index in leverSequence)
            {
                if (index >= 0 && index < levers.Count && levers[index] != null)
                {
                    uint objectId = levers[index].ObjectId;
                    correctSequence.Add(objectId);
                    Debug.Log($"Added ObjectId {objectId} to correctSequence");
                }
                else
                {
                    Debug.LogWarning($"Invalid lever index {index} in leverSequence. Skipping.");
                }
            }
            Debug.Log($"Correct sequence initialized: {string.Join(", ", correctSequence)}");
        }

        public void SetTriggerState(uint triggerId, bool isActivated)
        {
            if (isActivated)
            {
                activationSequence.Add(triggerId);
                Debug.Log($"Lever activated: {triggerId}. Current activationSequence: {string.Join(", ", activationSequence)}");

                // Limit sequence length to match correctSequence
                if (activationSequence.Count > correctSequence.Count)
                {
                    activationSequence.RemoveAt(0);
                }

                CheckSequence();
            }
        }

        private void CheckSequence()
        {
            Debug.Log($"Checking sequences... Activation: {string.Join(", ", activationSequence)} | Correct: {string.Join(", ", correctSequence)}");
            if (activationSequence.Count == correctSequence.Count)
            {
                for (int i = 0; i < correctSequence.Count; i++)
                {
                    if (activationSequence[i] != correctSequence[i])
                    {
                        Debug.Log($"Sequence mismatch at index {i}: {activationSequence[i]} != {correctSequence[i]}");
                        return;
                    }
                }

                // Sequence matches
                if (doorObj != null && !doorObj.IsOpen)
                {
                    doorObj.IsOpen = true;
                    Debug.Log("Correct sequence entered. Door is now open!");
                }

                activationSequence.Clear();
            }
        }
#endif
    }
}

```

da is my manager script. its like u have to use levers in correct combination to opne a door. and it was using objectid to check which lever is used. the initial code was save in awake

**Comment by moepi2k** [comment]
i could make a coritouine to check again if objectid is 0. but i liked it better as it was before :P

**Comment by insthync** [comment]
You may try to use scene object if instead, or you may just fork the repo and make changes its codes as you wish

**Comment by moepi2k** [comment]
jup will try this thank you :)
