### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by wendellsn** [suriyun-production/mmorpg-kit-docs#2643]
do i really skip this like it's saying in the documentation?
![image](https://github.com/user-attachments/assets/5a4c305d-8eb2-46ad-846d-7ec526c3308d)

when i skip it i get more than 80 errors

**Comment by insthync** [comment]
After you skip it then you install newtonsoft json and something else?

**Comment by insthync** [comment]
The document is old the old version of asset store tools don't have options for me to select including packages, so I was recommend to skip, for the current version, don't have to skip it

**Comment by wendellsn** [comment]
can you helop me to fix this?

**Comment by insthync** [comment]
Did you try to not skip?

**Comment by wendellsn** [comment]
i did the install , im asking about the issue with the aimatcursor addon, i added  the screne but it's like in the screenshot i sent, i can move but it's all blue. 3d build

**Comment by insthync** [comment]
Create a new post for a new question
