### ISSUE TITLE
Linux server Config for production build

### ISSUE THREAD

**Issue by jprules321** [suriyun-production/mmorpg-kit-docs#2644]
Hi Suri,

Could you tell me what IPs and stuff needs to be set to what in the linux build serverConfig.json because I can login and create an account but it always says MapServer Not Ready when I want to enter the game. In my log, everything says no error and map server is spawned.

I don't have a Firewall installed for testing so I doubt it is about the port.

Let me know and I will update your guide with the proper information.

**Comment by jprules321** [comment]
![image](https://github.com/user-attachments/assets/5de518f4-5ed5-476a-8cb1-2f8c50d222e9)

Current Config, I only changed CentralAddress and MachineAddress as per your Digital Ocean guide.

**Comment by jprules321** [comment]
![image](https://github.com/user-attachments/assets/c37edf03-211e-4ec5-9a02-21ab1f4c76a5)


Here is my config, I set MachineAddress and centralAddress as per your DigitalOcean guide.

**Comment by jprules321** [comment]
![image](https://github.com/user-attachments/assets/8d5bfdac-b25a-4e56-a86a-45cfb2078b62)

I think that is the problem, shouldn't it be just TestScene ? Why does it add default_

**Comment by insthync** [comment]
Did you setup IP/Port for the client?, you can see an example in `Demo/GameData/MmoNetworkSettings/Local.asset`

**Comment by jprules321** [comment]
![image](https://github.com/user-attachments/assets/7785250d-ed0a-4def-b4e8-4f9559ad79f4)

Yes. I added SpawnChannels to my Config and now when I create my character and try to log in it simply says "Cannot connect to server" instead of Map Server Not Ready.

**Comment by insthync** [comment]
Did you open ports 8000-8010 ?

**Comment by jprules321** [comment]
https://streamable.com/7yjfvh

![image](https://github.com/user-attachments/assets/3a54777f-5ba6-4f84-b38f-ce25675220ad)

**Comment by jprules321** [comment]
![image](https://github.com/user-attachments/assets/51570017-3a46-456d-a08a-54ab4df4ecd5)

![image](https://github.com/user-attachments/assets/0f0da2ce-8e12-4318-af01-3227fd313477)

**Comment by insthync** [comment]
Hmm, it seems to be correct, it should work

**Comment by jprules321** [comment]
I used "Linux Server" as build profile. Is it what I need or Linux

**Comment by insthync** [comment]
It still should work, I saw that map server can connect to central server, then central server should have the map in the connection list

**Comment by jprules321** [comment]
If my ports config would not be OK, I wouldnt be able to connect to create an account in the first place right? I wonder why only map.

**Comment by insthync** [comment]
it is because you can connect to central server at port 7000, for maps it starts from 8000 (by your config), you may tru look at mapnetworkmanager when connecting to map to see where it is going to connect

**Comment by jprules321** [comment]
![image](https://github.com/user-attachments/assets/f48a8943-8c92-41b1-a023-b30e3fd1406d)

**Comment by insthync** [comment]
is this when connecting?

**Comment by jprules321** [comment]
No, I see what you mean. I will check.

Thanks for taking the time btw.

**Comment by jprules321** [comment]
![image](https://github.com/user-attachments/assets/46cd43ec-1a7c-4626-a3a4-720d53a9d876)


I see, it tries to connect to localhost for client. Where can I change that for Client ?

**Comment by insthync** [comment]
oh, try change the config, from machineAddress to publicAddress

**Comment by jprules321** [comment]
Worked :)
