### ISSUE TITLE
aim at cursor help

### ISSUE THREAD

**Issue by wendellsn** [suriyun-production/mmorpg-kit-docs#2646]
hi i tried to add the addon but  im getting a blue screen in front of the player

![image](https://github.com/user-attachments/assets/18ccaa3a-f492-4afe-920c-d3022dc898a2)
i've adde d the prefab to gamedata and gameinstance, can you help me?

**Comment by moepi2k** [comment]
you have to switch ur project to URP

**Comment by wendellsn** [comment]
im using 1.91, ill try to overlay it

**Comment by insthync** [comment]
![1](https://github.com/user-attachments/assets/a26eb862-f25c-407b-97c7-00dac25066de)
![2](https://github.com/user-attachments/assets/f5b20bc9-7c55-4da1-b6da-bea5c0f69b94)
![3](https://github.com/user-attachments/assets/d1d91e82-d9b6-42e3-ba2f-e95a63366c80)
