### ISSUE TITLE
CanvasGameplay_Survival Quickslot not work

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#265]
Hello when change to CanvasGameplay_Survival Canvas. Then its no longer possible per drag&drop items into quickslot list

**Comment by insthync** [comment]
Have to add UICharacterHotkeyDropHandler component to each key

![Screenshot_54](https://user-images.githubusercontent.com/2697550/76144291-546b0880-60b1-11ea-8021-5b4b71e09178.png)

**Comment by moepi2k** [comment]
Alright thank you, found nothing about that step in the docu 👍
