### ISSUE TITLE
Swimming (Combat Controller)

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2651]
Polite request for additional animation slots for swimming when using combat controller.

- Forward
- Backward
- Left
- Right
- Forward Left
- Forward Right
- Backward Left
- Backward Right

- Ascend (Swimming upwards)
- Descend (Swimming down)

**Comment by insthync** [comment]
What is that controller?, is it a shooter?

**Comment by BJPickles** [comment]
Yes shooter.
In camera controller can choose between Adventure and Combat.

**Comment by insthync** [comment]
Adventure have them?

**Comment by BJPickles** [comment]
Only Swim Idle & Swim Forward for both adventure & combat at the moment.

Shooter uses 8 direction so needs the extra anim slots

Would also be useful to have ascend and descend for swimming up and down, as well

**Comment by insthync** [comment]
What is this then?

![Screenshot_32](https://github.com/user-attachments/assets/ed624acf-0d1e-4e6a-9730-d20248629a05)

**Comment by BJPickles** [comment]
Functions well, but no animations on character entity to add to them under swimming?

**Comment by insthync** [comment]
![Screenshot_33](https://github.com/user-attachments/assets/163e0872-fd3a-4295-8bbc-0d2c1e90992a)

They are not enough for you ?

**Comment by BJPickles** [comment]
Sorry Ittipon, I must be using an outdated script because I dont have those in my script, thought they were missing.
