### ISSUE TITLE
1.91 building no longer working

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2656]
cant see what exactly changed. but in 1.91 building no longer working. building always shows red and cant be placed. dont know if it was in 189 and 190 already

**Comment by insthync** [comment]
Is it in safe area?

**Comment by moepi2k** [comment]
no i tried also outside safe arena. i just noticed in my game that i was no longer able to build anythjing then i tested 191 and had same issue

**Comment by moepi2k** [comment]
ah and in discord i saw someone having that problem so i wanted to help him and noticed it

**Comment by insthync** [comment]
Okay I will try it again

**Comment by jprules321** [comment]
I think I am having the same issue, I placed the BuildingArea on my map and Foundation as the building type and always red.

**Comment by Niinra** [comment]
in 1.89b it works , I have the component added on the terrain and no problems 
![image](https://github.com/user-attachments/assets/9dc9560b-517f-4e0a-a352-cf66f302e0e3)

**Comment by moepi2k** [comment]
Yes there was some changes in 190 which break it.we should wait for fix

**Comment by moepi2k** [comment]
btw the build which is not working is just this as i posted in other report https://github.com/suriyun-production/mmorpg-kit-docs/issues/2604

when u change to this it works

```
public virtual bool AllowToBuild(BuildingEntity newBuilding)
{
    if (newBuilding == null || (entity != null && !entity.IsCreator(newBuilding.Builder)))
        return false;
    if (!newBuilding.BuildingTypes.Contains(buildingType))
        return false;
    if (buildConditions != null && buildConditions.Length > 0)
    {
        for (int i = 0; i < buildConditions.Length; ++i)
        {
            if (!buildConditions[i].AllowToBuild(this, newBuilding))
                return false;
        }
    }
    return true;
}
```
