### ISSUE TITLE
Respawning Scene Objects -> Harvestable item drop etc

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2659]
as with the latest changes how can we make scene objects respawning as it worked before? e.g droping a tree in scene directly no longer works for respawning when its harvested

**Comment by Niinra** [comment]
I imagine that was the change in the ID codes, it was a mistake to suggest to suriyun to change the code, it works better and without so much problem to add an object in the scene and use the reorder scene object ID

**Comment by moepi2k** [comment]
Yea also have problems with new changes. But i hope there will be a good solution for scene objects.

**Comment by Niinra** [comment]
> Yea also have problems with new changes. But i hope there will be a good solution for scene objects.

For everyone, in my opinion, it is leaving it as it was before and simply putting it in the documentation , I think it's the best :/

**Comment by insthync** [comment]
The reason that I am making changes is it is not seems reliably.

**Comment by moepi2k** [comment]
in what way is it not reliable?

**Comment by insthync** [comment]
Object ID can be changed to something else when you save scene or reorder scene object ID

**Comment by moepi2k** [comment]
Hm yea but as long as it is unique it wont make any issues. So far i never had some with scene objects

**Comment by insthync** [comment]
Some of what?

**Comment by moepi2k** [comment]
Issues

**Comment by insthync** [comment]
But I have

**Comment by moepi2k** [comment]
Ohh okey, i know u will find good solution :)
