### ISSUE TITLE
Created CharacterItem in IncreaseItems not getting level from RewardedItem - Solution

### ISSUE THREAD

**Issue by jprules321** [suriyun-production/mmorpg-kit-docs#2664]
As you can see in the picture below, the gacha rolled an item level 5. However, when the item reaches the function IncreaseItems in CharacterDataExtensions at line 363, the CharacterItem.Create function has a hardcoded level of 1 instead of passing the level from the RewardedItem.

![image](https://github.com/user-attachments/assets/b5632a9e-049f-4f65-b3fb-0f46813daf05)

**Comment by moepi2k** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/2654
