### ISSUE TITLE
Missing Script on GameInstance 00Init_MMO

### ISSUE THREAD

**Issue by pogsdbest** [suriyun-production/mmorpg-kit-docs#2668]
**Describe the bug**
After import and opening 00Init_MMO GameInstance has one missing script which prevents us from running running the kit

**To Reproduce**
1.create project on unity 6
2.import json
3.add addressables
4.import kit with skip process
5.open 00Init_MMO and check GameInstance, scroll down theres a missing script

**Screenshots**
![Screenshot 2024-12-18 035424](https://github.com/user-attachments/assets/b99e25a1-e8f3-41ac-a249-35818873d0bf)

using 1.91 from unity asset store

**Comment by insthync** [comment]
This one is not being used anymore, you can remove the component
