### ISSUE TITLE
Building System

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#267]
there should be an option what you can check on each building part so that only owner can attach new building parts on each other. else strangers can manipulate your house. 

or better solution to make an item with a radius on it so only player that have registered with a code on this object can build in a radius of this item. -> like rust for example

**Comment by insthync** [comment]
Noted, I will implement it in future version.

**Comment by moepi2k** [comment]
added in v1.56 thank you :)
