### ISSUE TITLE
mmorpgkit 1.91 interface becomes pink 

### ISSUE THREAD

**Issue by arnosf1996** [suriyun-production/mmorpg-kit-docs#2671]
when i update my interface and installed the interface 1.91 , the server intro become all pink like a shader crash, how can i fix this?

**Comment by insthync** [comment]
Which interface?

**Comment by insthync** [comment]
Interface or mesh objects in login scene?

**Comment by arnosf1996** [comment]
when i started the game the "Server Selection" screen became all purple
and the buttons too

**Comment by insthync** [comment]
Screen shot images please, I guess it is just a render pipeline issues.

**Comment by arnosf1996** [comment]
ok
what the recommended pipeline to use? this happen when i changed but i dont saw on doc nothing about render used for mmorpgkit

**Comment by insthync** [comment]
It is Unity thing, I can't decide it for you, you must learn about Unity's pipeline system.

**Comment by insthync** [comment]
This is one of Unity's suck thing

**Comment by arnosf1996** [comment]
understand i will try test it

**Comment by arnosf1996** [comment]
![Captura de tela 2024-12-19 090654](https://github.com/user-attachments/assets/26eb6012-7810-4a5f-a502-5100a7c5f7fa)
here the screenshot

**Comment by insthync** [comment]
What is your selected render pipeline currently?

**Comment by arnosf1996** [comment]
![Captura de tela 2024-12-19 091639](https://github.com/user-attachments/assets/04bbdc48-fd60-45e4-864e-04008bf1535e)
![Captura de tela 2024-12-19 091646](https://github.com/user-attachments/assets/265259b5-9c3b-4370-a806-49edae4a13fa)

**Comment by insthync** [comment]
I don't know how to fix it.

**Comment by arnosf1996** [comment]
ok i will try to fix thank you

**Comment by arnosf1996** [comment]
![Captura de tela 2024-12-19 092130](https://github.com/user-attachments/assets/76483351-112f-42e4-bca3-b79a69a02402)
its weird , the in editor run work, but build bugs

**Comment by insthync** [comment]
![Screenshot_281](https://github.com/user-attachments/assets/83d16119-efd7-4442-9fd6-0cda1e1a62ad)

Try this

**Comment by insthync** [comment]
Set it to all quality settings

**Comment by arnosf1996** [comment]
ok let me try

**Comment by arnosf1996** [comment]
i solve the error 
![Captura de tela 2024-12-19 102749](https://github.com/user-attachments/assets/d758defc-b404-43b7-9996-1dafe82b6f65)
this ones need to be this way but i had another bug, 
the console server

**Comment by arnosf1996** [comment]
when i start the server the console screen from the shortcut not appear
