### ISSUE TITLE
Jump bug

### ISSUE THREAD

**Issue by Credosk** [suriyun-production/mmorpg-kit-docs#2676]
Hello, I would like to report a minor bug, namely that if a character has increased movement speed, it will ruin the animation or jump speed, shouldn't it be separate that movement speed does not affect the jump? As you can see in the video, the jump animation is duplicated, so it goes 2x https://files.fm/u/xxa9vnwpf7

**Comment by moepi2k** [comment]
ur setup is just wrong. play with the settings and animations

**Comment by Credosk** [comment]
But all the settings are original, I didn't change anything with the animations, I have no idea where to do that

**Comment by Eniotnacram** [comment]
Please, stop making unecessary bug reports like that.. Its not a bug, its only your setup as per moepi.. Most of the issue you reported recently are not issues are simple unity behaviors that you need to learn.
