### ISSUE TITLE
Player Storage empty after updating to 191

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2677]
building storage fixed, but now all my player report that theier personal storage is empty :////////////////

in mysql data are there https://gyazo.com/c070d139294b5957239d61b3f351bb38

**Comment by insthync** [comment]
fixed in 192

**Comment by insthync** [comment]
fixed before you post this one

**Comment by insthync** [comment]
and i don't trust you that it is because of 191

**Comment by insthync** [comment]
because 191 have building storage issues, but not player.

**Comment by moepi2k** [comment]
yea could be i dont take care of player storage because it worked before. so maybe because of the recently changes.

**Comment by moepi2k** [comment]
ok i updated to 192. personal storage working with new items. but all the old data from database is ignoring. so all my player still have empty storage. but in databaase data is in. something changed that it lost reference to existing stuff

**Comment by insthync** [comment]
WHAT?, is it ignored? or it is gone because the data was replaced?

**Comment by moepi2k** [comment]
when start server all storage is empty even when there is data in mysql from before. but when player then put items in storage it save the new one + loads the new one. maybe it override the old, i dont know. i have 10k of items. just the old one not load

**Comment by insthync** [comment]
I think it was replaced by empty list

**Comment by moepi2k** [comment]
yes i think that too. i have backup and will test that one yet

**Comment by moepi2k** [comment]
yes was that. it was override. thanks
