### ISSUE TITLE
1.44b Bugs

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#27]
Spells no longer works (firebolt ...) once placed on the hotkey, they are not usable.

There is a problem with ItemDialog gems (sockets). After having socket an object, it appears systematically, as soon as you want to loot an object or attack.

**Comment by Koodetat** [comment]
On a fresh project.

**Comment by insthync** [comment]
Thank you, I will fix it.but I don't understand about item dialog, socket items problems how it is ?

**Comment by Koodetat** [comment]
After socketing an item, a popup with the last gem used appears regularly, without reason.

**Comment by Koodetat** [comment]
When looting or fightin.

**Comment by insthync** [comment]
Fixed in 1.44c

**Comment by Koodetat** [comment]
Great thank you.
