### ISSUE TITLE
Valid prefab configuration - Animator Bug

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#270]
There are cases when character animation works in editor / during creation character process. But stop when getting into game scene. 

If you for example find character and restart animator component it starts to work. 

What can be possibly source of this problem ?

**Comment by insthync** [comment]
Hmm, maybe character model class, you use `Character Model` or `Animator Character Model`?

**Comment by poaq** [comment]
Animator Character Model:

Behaviour:
https://gyazo.com/28e10d77e55d3b07905ba13a721194c2

Character conf: 
https://gyazo.com/1d37c8c67703163a205abbe85239162f

**Comment by poaq** [comment]
And after you set on scene controller to none (wich is none on prefab) then it get strange "himp" and animate:
https://gyazo.com/efdbc6533fcd0c4e79d9e58b4a714394

**Comment by insthync** [comment]
Are there any error or warning?, I also want to see your `Character Model Manager` settings.

**Comment by poaq** [comment]
when i switch to "Always animate" to animation are working. But still character have this "strange" himp: on female model its even worse: https://gyazo.com/ebdaed21436b9ace9f9962e4162d1b1d

There is no errors on console. Character model manager config : https://gyazo.com/024c93884f5b9d31ca9870d64cb5643e

**Comment by poaq** [comment]
Pitch IK script make it himp. So this is resolved by removing it. But the question that still remain is does animator should be set to always animate?

**Comment by insthync** [comment]
I will check it, its actually should not need to be always animate.

**Comment by insthync** [comment]
Weird, As I tried, it's working correctly.

**Comment by insthync** [comment]
You may try add codes to `BaseCharacterEntity.cs` → OnValidate function to avoid validating character model while the game is playing
So the codes will be
```
        protected override void OnValidate()
        {
            base.OnValidate();
#if UNITY_EDITOR
            if (Application.isPlaying)
                return;
            ModelManager = GetComponent<CharacterModelManager>();
            if (ModelManager == null)
                ModelManager = gameObject.AddComponent<CharacterModelManager>();
            if (model != ModelManager.ActiveModel)
            {
                model = ModelManager.ActiveModel;
                EditorUtility.SetDirty(this);
            }
#endif
        }
```
