### ISSUE TITLE
Building System destroy parts

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#271]
when place a foundation and attach 2,3 or 4 on it. then there is an issue when destroy the base (first placed) foundation. after destroy it all other will also destroy. that not happen if you destroy one of the attached ones

**Comment by insthync** [comment]
Oh, it's chain destroy which someone requested. For now, if you don't want it, you can remove `OnNetworkDestroy` codes in `BuildingEntity.cs`

**Comment by moepi2k** [comment]
Yes Chaindestroy is needed when destroy a foundation so that walls dont flaot in the air. but it should not work for foundation. so it make no sense that all child foundation will destroy when destroy the base foundation. in t should only work in vertical direction and not horizontal. you know what i mean?

**Comment by insthync** [comment]
I've add `destroyWhenParentDestroyed` setting to `BuildingEntity` (in 1.54b) turn it on to apply child entity chain destroy.
