### ISSUE TITLE
UICharacterBuff is not working in Mobile

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#272]
This work fine in standAlone mode. Only problem in mobile. (I only test this in survival mode)
Use a or several buff skill, then I check the CanvasGameplay-survival-mobile > UICharacterHpMp > UICharacterBuffs, There's no UICharacterBuff prefab.
Nothing is cloned here so nothing to show.
Can you check this?

**Comment by insthync** [comment]
![Screenshot_58](https://user-images.githubusercontent.com/2697550/76495529-a0c79700-6469-11ea-8171-e641966d91c5.png)

**Comment by dglee2592** [comment]
Oh, Thanks! It was there!
