### ISSUE TITLE
PartyList

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#274]
Is there an easy way to Get a list of all the parties made on a client?
I created netfunctions that grab the parties in gamemanager.. it works fine in singleplayer but in mmo it doesnt fill list.. list is always 0..
tried multiple methods .. all work for single.. not for mmo..

Any tips?

Can provide codes and screenshot to show what i did if need be

**Comment by insthync** [comment]
All parties from the server not all members of the party, right?

**Comment by Callepo** [comment]
exactly,
i need a list of all parties created by any player .. not the members.

**Comment by Callepo** [comment]
![Capture](https://user-images.githubusercontent.com/7702658/76565490-f708fa00-64aa-11ea-8e87-0d01714fb27a.PNG)
Im Making a party matching system.. 
where u open a window .. u see all the existing parties.. and u press Join group 
and send the party leader a request to join his party..
the list shows up in single..
but not mmo.. cant figure out why

**Comment by insthync** [comment]
Ahh, I see. I don't know how you do it, but if I do this, I will add new message Id for party listing to BaseGameNetworkManager 

```
// Message id
public const ushort PartyListing = 201;
````

Then create the listing function and register the message at client and server
```
// Client-side codes
void HandleResponsePartyListFromServer(LiteNetLibMessageHandler messageHandler)
{
    // Read party list which receives from the server
    // Then show it in parties UI
}

[DevExtMethods("RegisterClientMessages")]
void RegisterClientMessages_PartyList()
{
    RegisterClientMessage(PartyListing /*The Message Id*/, HandleResponsePartyListFromServer);
}

public void RequestPartyList()
{
    ClientSendPacket(DeliveryMethod.ReliableOrdered, PartyListing /*The Message Id*/); // Just request for party list, so it does not have to write any data
}
```
```
// Server-side codes
void HandleRequestPartyListFromClient(LiteNetLibMessageHandler messageHandler)
{
    // Write party list and send to the client
    ServerSendPacket(messageHandler.connectionId, DeliveryMethod.ReliableOrdered, PartyListing /*The Message Id*/, (writer) =>
    {
        // Write party list data here
    });
}

[DevExtMethods("RegisterServerMessages")]
void RegisterServerMessages_PartyList()
{
    RegisterServerMessage(PartyListing /*The Message Id*/, HandleRequestPartyListFromClient);
}
```

Then when you want to request party list, you can do it by calling the function `RequestPartyList()`

**Comment by Callepo** [comment]
Ty <3

**Comment by Callepo** [comment]
i think i missed the ServerSendpacket 
i was looking at it .. but didnt fully understand it..
that was one of the issues for sure.. 
without it never work lol
