### ISSUE TITLE
When loot new items, Hotkeys of stacked items removed.

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#276]
When loot new items, Hotkeys of stacked items like waterbottle, meat, wood, portion etc are removed from the hotkeys because number of stacked is changed.

![image](https://user-images.githubusercontent.com/58107601/76659325-784eb280-65b9-11ea-8ac3-f871832e69ee.png)

**Comment by DimasjkTV** [comment]
I havent this problem in 1.54

**Comment by dglee2592** [comment]
Oh indeed. Thanks!
