### ISSUE TITLE
How to edit character UI HP / MP etc. Image fill to diffrent options.

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#277]
public abstract class UIDamageableEntity<T> : UIBaseGameEntity<T>
        where T : DamageableEntity

contains method that update HP / MAX HP on the character ui. For example instead of using image fill option i would like to do sth diffrent. How i can override this part without touching your core?

**Comment by insthync** [comment]
You may create new component which will attach to the same game object with the `UIDamageableEntity` then get `Data` from `UIDamageableEntity` and get HP/MaxHP value

For example
```
public class HPComp : MonoBehaviour {
  UIDamageableEntity cacheUI;
  void Awake() {
    cacheUI= GetComponent<UIDamageableEntity >();
  }
  void Update() {
    {UI}.fill = cacheUI.Data.Hp / cacheUI.Data.MaxHp;
  }
}
```
