### ISSUE TITLE
How to make monster attack buildings? (please help me)

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#278]
I'm sorry for this question several times. I was advised and tried but still not able to make monster attack buildings.. I struggled this several weeks and finally ask again something I missed or not.
What I did is as below.

1. Add findBuilding funciton to MonsterActivityComponent → FindEnemy(Vector3 currentPosition)
2. Set found builing as target by using CacheEntity.SetTargetEntity(characterEntity) funciton.

Monster successfully found buildings and it is assigned as target correctly. I confirmed this through  Debug.log of each attack fuction steps in below script

Can you just please advise me once again if something I missed?
My apology for this several questions but I really need your help...

Thanks

![image](https://user-images.githubusercontent.com/58107601/76684362-dd081c80-664e-11ea-9662-4b4e39a482f4.png)

![image](https://user-images.githubusercontent.com/58107601/76684377-045ee980-664f-11ea-9826-1500d7b4317b.png)

![image](https://user-images.githubusercontent.com/58107601/76684390-16408c80-664f-11ea-876e-ff3d6d423822.png)

![image](https://user-images.githubusercontent.com/58107601/76684401-2d7f7a00-664f-11ea-8fe4-32eafd1a2a9a.png)

**Comment by insthync** [comment]
I will create new monster activity class  which will attack building entities to `https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand` repository

**Comment by dglee2592** [comment]
Oh my goodness!!!
Thanks for the answer and feture update!!!!

**Comment by dglee2592** [comment]
Hi Suriyun, I dont wanna push on you or anything. 
but just wandering when you can have time for this.
I know you are so busy, so any clue or hint can help me try this by myself.

Thanks for the great Kit!!!

**Comment by insthync** [comment]
I've added `isAttackBuilding` option to `MonsterActivityComponent`, If this is `TRUE`, monster will attacks buildings. Try 1.54e

**Comment by dglee2592** [comment]
Thank you very very much!
I'll close this ticket!
