### ISSUE TITLE
1.54 Summoned creatures

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#280]
* Summoned creatures (with aoe) attack the character and fight among themselves.
1. Archer has single target attack
2. Mage has aoe targets attack
[1.54 Summoned bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4333906/1.54.Summoned.bug.zip)

* About single target skills at summoned creatures:
1. We summoned two creatures that attack 1 target.
2. We attack one monster.
3. Both of our summoned creatures use the skill.
4. The first summoned creature kills the target
5. And the second upon begins to attack the character.
That is, a bug occurs when the summoned creatures strikes, but the target is already dead.

* The timer of summoned creatures is not updated.
[1.54 Summoned timer.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4334033/1.54.Summoned.timer.zip)

Also, summoned creatures do not want to use a normal attack after using a skill. They just stay in place after using skill.

**Comment by insthync** [comment]
This was fixed in 1.54c, if issues still occurring, you can re-open it.
