### ISSUE TITLE
central network list

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#285]
https://www.youtube.com/watch?v=RXiW3G1EXp4
i made a partymatching system..
it works nice.. register ur party/ people can join etc..
but i have a problem with where to place the List of Registered parties..
i tried in basegamenetworkmanaget.. tried in Gameinstance and fetched it with Currentgameinstance.. tried Just GameInstance and a static list..
Even put in CentralNetworkmanager and got with mmo..
All work exactly the same..
 it act like there are 2 list on the server.. 1 per every map
instead of 1 global list for every map instance

where can i put this so it works like i want ?
![image](https://user-images.githubusercontent.com/7702658/77017202-1a83e700-697a-11ea-8763-468b3d298e2c.png)

**Comment by JestHWas** [comment]
i really need information on this as well. A place where i can store information for server created at runtime and then reusable across all maps.

**Comment by Callepo** [comment]
Just a tip if which script is best to put this would help.. dont need nothing else
or if only way to do it is use of database @insthync

**Comment by insthync** [comment]
Current architect working like this, when creating a party, it will create at map-server then it passes created party data to chat-server then chat-server pass it to other map-servers to have the same list.

Clients will connect to central-server to login and manage character, then it will disconnect from central-server and connect to map-server only while playing the game.

**Comment by Callepo** [comment]
Ahhh... Ty so much

**Comment by JestHWas** [comment]
@insthync  I cannot find in the code how does it pass this list to the other maps.

This is what i see - 

After a party is created from the NetFuncCall to create a party this is called - SendCreateParty

This makes the call to the chatnetworkmanager method HandlePartyUpdateAtServer - which performs this code 

`if (mapServerConnectionIds.Contains(connectionId))
            {
                foreach (long mapServerConnectionId in mapServerConnectionIds)
                {
                    if (mapServerConnectionId != connectionId)
                        ServerSendPacket(mapServerConnectionId, DeliveryMethod.ReliableOrdered, MMOMessageTypes.UpdateParty, message);
                }
            }`

Where does it go once ServerSendPacket is called. I cannot see where this would be sent. Any help with this would be very helpful. 
Thanks.

**Comment by JestHWas** [comment]
nvm - i have found it out.

**Comment by JestHWas** [comment]
should this be closed @Callepo ?
