### ISSUE TITLE
Spawnable Objects MMO

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#286]
![image](https://user-images.githubusercontent.com/7702658/77023883-51afc380-698d-11ea-968a-1bf18bc1835c.png)
Everytime u warp to any map.. 
the objects are added to list.. but old ones are not removed.. 
so the more u warp the longer it gets ..
not ideal
its not clearing the list and reading based on the current map.. it just keeps em forever..
same map added again and again

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.54b
