### ISSUE TITLE
Client closed connection when warping while server debugging in editor

### ISSUE THREAD

**Issue by JestHWas** [suriyun-production/mmorpg-kit-docs#288]
When i debug the server from the editor and run a client build, i warp my character to another map but then the message about the server is closed appears and it goes back to the character selection screen.

Any help on what i'm missing.

Thanks

**Comment by insthync** [comment]
That is because while running in editor it can run only 1 map-server which set to `MMOServerInstance` → `StartingMap`, so it can't connect to other map servers

**Comment by JestHWas** [comment]
Ah okay. Thanks. will close.
