### ISSUE TITLE
Default Attack Skill/Skill on Monster (1.54)

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#289]
There is no option to stop monster movement while default attack. Also when attach a skill and set "move speed rate while using skill" set to 0 or check "can be interrupted while casting" does not stop enemy while attack.

and there is also an issue for "trigger duration rate" i set it to 1 but the damage apply at start phase of the animation.

-> Version 1.54

**Comment by insthync** [comment]
I've add option to stop monster movement while attacking in 1.54c to `MonsterCharacter` game data.
