### ISSUE TITLE
Mobs dont playing animation

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#291]
Hey!

I would like to ask what can be possible source of problem when mob roam but dont play animations?
Example: https://gyazo.com/996817c721ed19dc0bccb0ed87933aa0

**Comment by insthync** [comment]
Check your character model setting, which character model are you using? and it was set move animation correctly or not. The move animation is looping or not.

**Comment by poaq** [comment]
I converted it to new animation controller. And issue now occurs only on idle / run state. When you switch off and put on animator it goes into idle and stuck on movement and then never back to idle anymore and dont play run animaton. Attack / Die animations work. 
Example:
https://gyazo.com/9999a110ef5baebd47601c94d33327aa

**Comment by poaq** [comment]
Issue was on animation. it would be worth to add information what should be animation configuration.
