### ISSUE TITLE
Mobile auto attack and aim

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#292]
* How can I disable auto-attack on mobile? 
We have a situation that after using the skill, the character immediately uses an auto attack. This is very disturbing during kiting. And the controls seem responsive
* About Aim on mobile.
Unable to kite with ranged attacks. I think the character should complete the attack on the target, and then turn around if we pressed the joystick
[Mobile Aim.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4373164/Mobile.Aim.zip)

**Comment by insthync** [comment]
Try changes codes in `PlayerCharacterController_Input.cs`

In function `UpdateWASDInput` (between line 397-405) to

```
            // Move
            if (moveDirection.sqrMagnitude > 0f)
            {
                destination = null;
                ClearTarget();
                if (!PlayerCharacterEntity.IsPlayingActionAnimation())
                    PlayerCharacterEntity.SetLookRotation(Quaternion.LookRotation(moveDirection));
            }
```

**Comment by DimasjkTV** [comment]
Yes, it got better. With this, there is no need to remove the auto attack. But it would be nice to remove the auto-attack. Thank you!
