### ISSUE TITLE
Top Down Controller no longer supports WASD movement.

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#296]
The title says it all.

**Comment by insthync** [comment]
I intently made it not support WASD controls, I made controller working like Diablo.

**Comment by Fallen01** [comment]
It still has the option for WASD which lead to my confusion.

**Comment by Fallen01** [comment]
I'm not currently using it I just happened to notice it and reported it.

**Comment by insthync** [comment]
Ahh, Yes, You're right, it can make people confuse, I will add editor class which will show relates configs only.
