### ISSUE TITLE
Advanced Animator issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#298]
When using Advanced animator the character doesnt do the animation how its supposed to look..
U get this weird morphed animation compared to when using Simple

Example..The bash skill animation using Simple.. makes the character jump in the air and swing his sword when coming down..
Advanced... ur character just stand there waves his arms and does some weird attack..

Victory animation which is used for Skillcasting..
Simple- Character jumps back and forth on his legs like he celebrating someting..like the name said.. victory..
Advanced- character just waves in the air..no feet movent no nothing..

This happens with all animations we have of our own..
Walking is fine in away.. just attacking and skill casting looks very bad..

And we cant simply use the Simple animator.. cuase then we have no strafing for shootercontroller..
(walk sideways).. in simple when u try this.. the character just glides on the floor..

**Comment by lundgren84** [comment]
think its same issue as in my report -> https://github.com/suriyun-production/mmorpg-kit-docs/issues/275

**Comment by moepi2k** [comment]
This is not an issue. Adcanced controller use animation mask. So lowerpart of body never do any of this animation, just the upper part

**Comment by Callepo** [comment]
@moepi2k i dont wanna sacrifice the use of all my animations.. to have em look stupid for just to have side strafing..
yes.. only top moving is good for when ur on mount..
i mentioned more than 1 issue here..
using shooter controller with simple animator.. when u go sideways... ur character just glides on the floor and doesnt do any animation.. while looking forward.. even tho if u have animations to walk sideways

It doesnt need to act like advanced.. cuase its not..
but atleast animate :)

**Comment by insthync** [comment]
I think I might be able to add option to make it play same animation for all layers. I will try it. :p

**Comment by Callepo** [comment]
ty for taking a look

**Comment by moepi2k** [comment]
I know what u mean, it would be great if there would be an option for advanced controller where you can set for each animation if animation only upper body with avatar mask or animate whole body for som special animations. (Rolling for example)

**Comment by insthync** [comment]
I've added `PlayClipAllLayers` settings to an action clip and skill cast setting in 1.54c.
![Screenshot_86](https://user-images.githubusercontent.com/2697550/79091080-162ecc00-7d76-11ea-9949-44291cc820f6.png)

* * *

For developers who made custom animator controller, you have to add `DoActionAllLayers`(boolean) and `IsCastingSkillAllLayers`(boolean) parameters.

![Screenshot_87](https://user-images.githubusercontent.com/2697550/79091405-5773ab80-7d77-11ea-8c44-8c63861763bc.png)

Then create action state which its clip set to `__Action` and cast skill state which its clip set to `__CastSkill`. 

![Screenshot_88](https://user-images.githubusercontent.com/2697550/79091462-8722b380-7d77-11ea-9541-2d20285b93a3.png)

Then set transition the states with created parameters

![Screenshot_89](https://user-images.githubusercontent.com/2697550/79091494-ade0ea00-7d77-11ea-9e43-986d9f62dd32.png)

And add conditions to other states to avoid it playing while doing an action or cast skill

![Screenshot_90](https://user-images.githubusercontent.com/2697550/79091544-e680c380-7d77-11ea-9ef6-afd737fa9515.png)
