### ISSUE TITLE
First freeze in single player.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#299]
I think this is only in single player. It has long been noticed, if you enter the game for the first time, then the first time you use any effect (skills, item drops, etc.), the character receives a freeze for a split second. It feels like some components are not loading at boot time. They are loaded during the game. Any ideas?

**Comment by insthync** [comment]
I going to add a pooling system which will prepare prefabs before the game start.

**Comment by insthync** [comment]
Pooling system was added to 1.54c

**Comment by DimasjkTV** [comment]
> Pooling system was added to 1.54c

Anyway, a frieze occurs during the first run when using skills.

**Comment by insthync** [comment]
What us the kind of the skill ?, Buff skill or attack skill or something?

**Comment by DimasjkTV** [comment]
> What us the kind of the skill ?, Buff skill or attack skill or something?

All.
[Bug pooling system.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4469706/Bug.pooling.system.zip)

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/79124643-6ffaba80-7da5-11ea-8d9a-4b9c1c20fbe8.png)

**Comment by DimasjkTV** [comment]
and "ItemDropEntity"

**Comment by DimasjkTV** [comment]
very long loadigs have begun between locations on smartphones. Previously, everything was loaded in 1-3 seconds. Now 20-30

**Comment by insthync** [comment]
When scene loaded, there is an skill effects instantiated or not?

**Comment by DimasjkTV** [comment]
> When scene loaded, there is an skill effects instantiated or not?
All prefab effects are loaded on each scene. This seems to be the problem. Every time we upload a new scene, prefabs are also reloaded

**Comment by DimasjkTV** [comment]
I also noticed that if a character has more than 100 items in his inventory, then locations also load more slowly + freezes during the game. The more items the character has, the slower the loading of locations and the more freezes during the game. Maybe there is a way to fix this? I understand that i can limit the number of items, but in my game, characters can take 300-400 items with them. I do not use storage because people write that items disappear there.
