### ISSUE TITLE
Error in ChatNetworkManager

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#30]
I've this error:
NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.MMO.ChatNetworkManager.OnDestroy () (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Networking/ChatNetworkManager.cs:135)

![Sans titre-1](https://user-images.githubusercontent.com/19147694/56274330-d3083180-60fe-11e9-88e7-53adc7b574e2.png)

**Comment by insthync** [comment]
I think I fixed it, I don't see it anymore
