### ISSUE TITLE
 item that give bonus stat when equip(armor) is giving those stat when in inventory slots and take them away when equiped

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#301]
item that give bonus stat when equip(armor) is giving those stat when in inventory slots and take them away when equiped

https://youtu.be/FxGuqEuzSsY

**Comment by insthync** [comment]
Thank you for bug report, the fix will be included in next update.

**Comment by insthync** [comment]
This was fixed in 1.54c, if issues still occurring, you can re-open it.
