### ISSUE TITLE
Single/Lan - Let everyplayer access fireplace or chest

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#302]
Hi,

i want to be able to let all the players in LAN access a fireplace or a chest and not only the owner.

How would that be possible ?

Thanks

**Comment by sawcisson** [comment]
I found the code that manage it but not sure of how to override it without touching core code.
![image](https://user-images.githubusercontent.com/62859548/77907565-1a44ef00-728a-11ea-8c4b-82f4d58c9386.png)

**Comment by insthync** [comment]
Okay, I will make checkbox in next version.

**Comment by sawcisson** [comment]
Thanks :)

**Comment by DimasjkTV** [comment]
And if it is possible for a single player game, so that all created characters have a common stash as in MMO :P

**Comment by moepi2k** [comment]
and a check for same faction would also be nice

**Comment by insthync** [comment]
I've added `canUseByEveryone` setting to Storage Entity and Camp Fire Entity in 1.54c, about setting for specific party / guild / faction, I didn't do it yet because it's pretty complex, I have think about storage access permissions changes when player change party / guild / faction.
