### ISSUE TITLE
Building respawn point ?

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#303]
Is it possible to have a respawn point we can craft/build ?

**Comment by insthync** [comment]
I don't understand how it work?

**Comment by sawcisson** [comment]
So for example ;
I build a bed and put it down on the ground
If i die -> i respawn near the bed

**Comment by DimasjkTV** [comment]
You can create object with NPC dialog for save respawn position. It is already in the kit.

**Comment by sawcisson** [comment]
@DimasjkTV
I saw that there is a method to set up the respawn point i will try to add it to a custom building script.
I'll keep this post updated

**Comment by sawcisson** [comment]
So i basically made a new BuildingEntity that change respawn info on setup/build:

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using LiteNetLibManager;
using LiteNetLib;

namespace MultiplayerARPG
{
    public class BedEntity : BuildingEntity
    {
        [Header("Bed data")]
        public bool lockable;
        
        [SerializeField]
        public Transform respawnobject;

       

        public override void OnSetup()
        {
            base.OnSetup();

            BasePlayerCharacterController.OwningCharacter.RespawnMapName = CurrentMapInfo.name;
            BasePlayerCharacterController.OwningCharacter.RespawnPosition = respawnobject.position;
        }

        
    }
}
`

You can use that to make an entity make you respawn here.
You can also overrid the Activatable function to set the respawn when the player use the object.
And make a reset on object destroy if you need it.
