### ISSUE TITLE
Display remaining inventory slot

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#305]
Is it possible to add UI for remaining inventory slots like weight limit? I tried this but I experienced some problems so I was not able to do this.

**Comment by insthync** [comment]
As I investigate my codes, I have to changes some function name, for example `BaseGameplayRule` → `GetTotalSlot` its current functionality is to get max slot, not count of an used slots.

So for now if you want to get used slots in UICharacter class you have write codes like this:
```
        short countUsedSlots = 0;
        foreach (CharacterItem item in Data.NonEquipItems)
        {
            if (item.IsEmptySlot()) continue;
            countUsedSlots++;
        }
        return countUsedSlots;
```

Then set text like this 
```
textComp.text = countUsedSlots + "/" + Data.GetCaches().Stats.slotLimit;
```

**Comment by dglee2592** [comment]
Oh thanks a million!!!!!

**Comment by insthync** [comment]
This was added to `UICharacter` in 1.54c
