### ISSUE TITLE
We need a robust logging system

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#306]
Developing and shipping a game specially an MMORPG is only a small portion of the undertaking, upon release and as long as the MMORPG is in service you will have to support your players. 

Without proper support the game you have taken a few years of your life to develop will bow down to an overwhelming negative reviews and lose players.

So a system that can help you manage and support players should be a major feature of any MMORPG kit but often gets neglected.

I propose that another process called "logging server" should be created too. This will handle all logging where you can easily write your own logger, either log it to file or ideally a database that is separate from the game database.

For every action a player makes, the logging server is notified and logs that action. Basic information should include: player id, map server where the action happened, a timestamp, some meta data.

Connections
--------------
- What time did the user logged in? 
- Did he log in with the correct password? 
- How many times did he get the password wrong? 
- What time did he logout? 
- How many hours was he in game by the time he logged out? 
- Did he logout normally or got disconnected unexpectedly?

Chat
-----
- What did the player say?
- Was it a guild chat? party chat? a private chat directly to another player?
- If it's a private chat to who did he send the chat to?

Death
-------
- Why did the player die? Got killed by a monster? Got killed by another player? (used to catch bullying for repeated killing)
- If a feature like item dropped on death is active, what items got dropped?

Deal/Trade 
------------
- What items were exchanged and who exchanged them? (used to trace stolen items)

Storage
---------
- What items were added into storage?
- What items were removed from storage? (this can also help for lost items)

Items
------
- Crafting, what was crafted, what was used, what is the result?
- Broken item due to durability 0?

Character 
-----------
- Character leveled up, what time? What is the level now?
- Character added skill?
- Character increased stats?

Those are just a few of the things that could be logged to help make sense of your community and help players with issues.

I don't expect something like this to be included anytime soon, but would appreciate if it gets on the roadmap.

I understand that we can implement these ourselves, but having this out of the box where we'll just need to expand it to our needs would make this kit a lot more valuable than other kits out there that also didn't think to make logs important.

This is only a suggestion and thank you for the awesome kit!

**Comment by insthync** [comment]
Noted, Thank you for your suggestion :)

**Comment by iMakedonsky** [comment]
Some generic interface that makes adding logging for any function/method call would be great.

Like, a decorator/function to easily mark certain methods/network calls to log em, along with a possibility to log certain types of events(filtering), via config, say
`
config {
    LogFilter: (LogMessage mess) => mess.Level == INFO & mess.type == MessageTypes.ItemTransfer
}
`

**Comment by Fr-Coder** [comment]
Good idea, maybe using a separate process only for logging as for MySQL

**Comment by insthync** [comment]
Wow, it is very informative.

**Comment by insthync** [comment]
I've created a log handling component interface (IServerLogHandlers) in 1.87, you will have to implement the interface by yourself, and the component which implements that interface has to be attached to the same game object with map network manager to use it for log handling.
