### ISSUE TITLE
Vendor System

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#307]
I suggest that we include a vendor system, a little bit different than deals/trade. Basically a player can stand on a certain area and open shop. They can sell their items while their character is just standing there. Another player can treat them like another NPC that is selling items.

A vendor can sell items and set the price. This is helpful for the economy of the game since players can leave their character if they are busy with something else and just let it vend.

This is just a suggestion. Thank you for this awesome kit again.

**Comment by ybb95** [comment]
It's a good idea
