### ISSUE TITLE
[BUG] No camera display when using Universal Render Pipeline 

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#308]
![image](https://user-images.githubusercontent.com/6186420/78323656-14f6e580-75a5-11ea-9145-9216b7114d6b.png)

Using a fresh project with no modification running on the latest version of mmorpg-kit only difference is it's using the URP. (Project created using URP template)

This is the issue: GameplayCamera only shows a blue screen.

**Comment by Koodetat** [comment]
you must deactivate the child UI camera on the prefab of the main camera for your project.  (deactivate the gameobject)

**Comment by majimboo** [comment]
@Koodetat it worked but can you explain why? Also, is it really okay to disable that component? What was that for?

**Comment by majimboo** [comment]
I just realized that the HP bar and character name are now gone after disabling that.

**Comment by majimboo** [comment]
Thanks to @Nathan from discord for the help.

Reference to a blog post that helped me fix this too: https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.2/manual/camera-stacking.html

2 steps on fixing this:

1.  Change **CharacterUICamera** render type from _base_ to _overlay_
![image](https://user-images.githubusercontent.com/6186420/79694324-31339b80-82a2-11ea-9ae4-568c443fe5c7.png)

2. On **GameplayCamera** scroll down to stacks and add **CharacterUICamera**.
![image](https://user-images.githubusercontent.com/6186420/79694372-73f57380-82a2-11ea-8c8d-8585e3266e3e.png)

That's all and it should fix your camera for URP.

**Comment by HugoCortell** [comment]
...What happens if there _is_ _**no**_ Render Type?
![image](https://user-images.githubusercontent.com/59887727/133427597-a573272e-4279-4e06-9b20-ac7db5b65c0f.png)

**Comment by GeoffCee** [comment]
Where is the CharacterUICamera?

**Comment by insthync** [comment]
Child of `GameplayCamera` prefab
