### ISSUE TITLE
Improving the asset for adding new types of dialogues

### ISSUE THREAD

**Issue by AnisimovArthur** [suriyun-production/mmorpg-kit-docs#309]
Hi

I was faced with the problem that adding a new type of dialogue is incredibly difficult.
I need to change dozens of files to add a new dialogue type
<img width="200" alt="image" src="https://user-images.githubusercontent.com/39820747/78346915-6654a400-75a8-11ea-959c-c78acef12574.png">

Is it possible to bring the mechanics of dialogs to your class so that you can add your own dialogs without changing the source code?

![telegram-cloud-photo-size-2-5195317519735434915-y](https://user-images.githubusercontent.com/39820747/78347168-be8ba600-75a8-11ea-9bf5-c9dcaf995dee.jpg)
![telegram-cloud-photo-size-2-5195317519735434916-y](https://user-images.githubusercontent.com/39820747/78347175-c0ee0000-75a8-11ea-9874-82ebf8e71325.jpg)
![telegram-cloud-photo-size-2-5195317519735434917-y](https://user-images.githubusercontent.com/39820747/78347182-c4818700-75a8-11ea-9569-8e5baba31d24.jpg)

Its just to show my new type in xNode/ScriptableObject
Then I need to handle many switches in many classes

![telegram-cloud-photo-size-2-5197569319549120085-y](https://user-images.githubusercontent.com/39820747/78347508-44a7ec80-75a9-11ea-9086-e7802f0dd667.jpg)
![telegram-cloud-photo-size-2-5197569319549120086-y](https://user-images.githubusercontent.com/39820747/78347367-0f030380-75a9-11ea-854e-b9cc2d0e200f.jpg)
![telegram-cloud-photo-size-2-5197569319549120083-y](https://user-images.githubusercontent.com/39820747/78347373-11fdf400-75a9-11ea-873b-86c6a757f2cd.jpg)
And so on...

What is the best way to add a new dialog type with own mechanics?

**Comment by JestHWas** [comment]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/139-npc-entity

have you had a look at this?

**Comment by insthync** [comment]
For now there is no the best way to create new type of npc dialog yet, I will create abstract class which contains functions to override to process an dialogs activities later.
