### ISSUE TITLE
When warping between servers, hotkey bar is reset to default

### ISSUE THREAD

**Issue by epicality85** [suriyun-production/mmorpg-kit-docs#31]
When you add skills to the hotbar, and then warp between maps, your hotbar is cleared.  The intention is to not clear, since having to arrange your skills should only be done once. Unity 2018.3.8f1 and Kit 1.44b.

**Comment by epicality85** [comment]
Continuing on from this, after you warp (bar is blank) and then you add another skill/item to the bar, it then loads all the previously set keys on the bar.

**Comment by insthync** [comment]
Okay, I will fix it :)

**Comment by insthync** [comment]
This is fixed in 1.45
