### ISSUE TITLE
[Urgent] FactionPvp and Pvp modes issues on default maps

### ISSUE THREAD

**Issue by Blueeyer27** [suriyun-production/mmorpg-kit-docs#310]
Tried Pvp mode on Map002 and FactionPvp mode on Map001. Pvp - can attack, but can't harm other players, nothing happens, only mobs can be harmed. FactionPvp - when trying to attack it selects other faction player as target and just starts following him, can't attack at all.

**Comment by Blueeyer27** [comment]
Tried multiple types of weapons. 
Version: 1.54b

**Comment by insthync** [comment]
Not sure characters are inside safe-zone or not, try to move characters out from safe-zone (For the demo is where monsters spawn)

**Comment by insthync** [comment]
Oh, As I try it is a bug, I will fix it.

**Comment by insthync** [comment]
[MMORPG_KIT-FixInvalidAllyEnemyDetector.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4430573/MMORPG_KIT-FixInvalidAllyEnemyDetector.zip)
Fix by this package

**Comment by insthync** [comment]
This was fixed in 1.54c, if issues still occurring, you can re-open it.
