### ISSUE TITLE
[Urgent] Jittery movement when server auth is on.

### ISSUE THREAD

**Issue by JestHWas** [suriyun-production/mmorpg-kit-docs#311]
Hi @insthync 

A few users are reporting that there is jittery movement,  latest version of the kit, in their games for both pc and mobile, when server authoritative is enabled.

They are running their server build on the same machine as the client. And some others have ran a server build on a remote server. Same result on both.

It was mentioned that pre version 1.5 this jittery movement was not present.

Could you please take a look at this.

Thanks

**Comment by Callepo** [comment]
the movement feels  really bad compared to when using Not secure...
almost to the point where u dont wanna use it at all..
and when looking at other players online .. they have this jittery movement also..
cuase its being updated by the server..

so in a way there is no way around this..
just clientsided u can remove this by going not secure..

**Comment by Blueeyer27** [comment]
Tested on 1.54b, same problem. On mobile client this mode shakes camera a lot, especially when you're running around something (when running just straight forward it works a bit smoother).

**Comment by insthync** [comment]
The fastest way to make it smoother, for now, is to change all stack trace logging to none in the `Console`

![Screenshot_81](https://user-images.githubusercontent.com/2697550/78414919-c7cc4f80-7648-11ea-90dc-9ac5e42c5117.png)

**Comment by insthync** [comment]
And then rebuild the server

**Comment by JestHWas** [comment]
Thanks. Will try it out.

**Comment by JestHWas** [comment]
@insthync  - callepo was still having jittery movements and stack trace logging was turned off. Others will probably answer when they have tried it out.

Noticed you said for now? Does this mean you have something coming up which will improve client to server communication? :D

**Comment by insthync** [comment]
Yes, I have plan to create new entity movement, especially for FPS games.

**Comment by JestHWas** [comment]
@insthync  do you have a rough idea on when the new entity movement will be available?

**Comment by Fallen01** [comment]
Client side prediction would be fantastic.

**Comment by moepi2k** [comment]
Any news? :)

**Comment by insthync** [comment]
I've changes entity movement in 1.63
