### ISSUE TITLE
Quest icon in 2D

### ISSUE THREAD

**Issue by MrTemka** [suriyun-production/mmorpg-kit-docs#312]
I added a quest and its icon in 2D across the screen stretches [https://media.discordapp.net/attachments/460803281455939595/695669918070210690/unknown.png?width=1204&height=677](url)
[https://media.discordapp.net/attachments/460803281455939595/695672857321144370/unknown.png?width=1247&height=677](url)

**Comment by insthync** [comment]
You have to reduce text size or scale in `CanvasNpcQuestIndicator` prefab or create new `CanvasNpcQuestIndicator` prefab then set to `GameInstance` → `NpcQuestIndicator`

**Comment by MrTemka** [comment]
Thanks. It helped!
