### ISSUE TITLE
Weird pet behavior

### ISSUE THREAD

**Issue by iMakedonsky** [suriyun-production/mmorpg-kit-docs#313]
I launched latest initial demo via mmo docs section, summoned orc archer with appropriate skill.

Initially he behaved correctly(following me, attacking whoever attacked me).
Then after some point, he started to stand still shooting in single direction, and only follow me by teleports when i gone too far from him.

Here's a video of it happening in real time:
https://youtu.be/_82do0fOLQw

**Comment by DimasjkTV** [comment]
Yes, I described this bug here. Now summoned creatures are not working. They attack the character and after that they stand in one place
![image](https://user-images.githubusercontent.com/47291794/78463063-6c01d500-76e1-11ea-86eb-34dc723f4bde.png)

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
This was fixed in 1.54c, if issues still occurring, you can re-open it.
