### ISSUE TITLE
Poison Area Skill with TPS FPS Combat Controller.

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#315]
There is an issue with the Combat controller when use Skills like Posion Area where you have the preview Target (green circle) before use. Dont remember if its TPS or FPS (not at computer atm) but on one of  them you are not able to aim. the green Circle is always on the players transfrom.position.

**Comment by insthync** [comment]
I can't reproduce it, as I try it casting on target correctly

**Comment by moepi2k** [comment]
It works. my fault, i used an offset for the fps controller. Thats why it happened
