### ISSUE TITLE
MMORPG-Digital Ocean Mobile error

### ISSUE THREAD

**Issue by ybb95** [suriyun-production/mmorpg-kit-docs#317]
Use version - Unity 2018.4.14f
Use version - MMORPG 1.53d
Cellphone device - Android Galaxy S10

I am using MMORPG as a digital ocean
Inventory error when running on mobile

### Normal when running on PC
![33333](https://user-images.githubusercontent.com/58978516/78666371-3a238500-7912-11ea-9a66-7e0f5ef54068.png)

### Error when running on Mobile
![444444444](https://user-images.githubusercontent.com/58978516/78666378-3d1e7580-7912-11ea-9663-607458876fbc.png)

### Mobile log
![111111](https://user-images.githubusercontent.com/58978516/78666750-c635ac80-7912-11ea-8427-aa51104f9bef.png)
![22222](https://user-images.githubusercontent.com/58978516/78666754-c766d980-7912-11ea-86cc-083801577d55.png)

**Comment by insthync** [comment]
You can find solution from this https://github.com/suriyun-production/mmorpg-kit-docs/issues/300

I will upload the patched package later

**Comment by ybb95** [comment]
thank you!!

**Comment by insthync** [comment]
This was fixed in 1.54c, if issues still occurring, you can re-open it.
