### ISSUE TITLE
Attack Skill target issue

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#318]
Attack skill got an issue. when use it and while animation is runing you aim. the spell/projectil goes there where you aimed at start not where you aim at end of animation.

It seems that issue is only for skill projectiles. Default attack works

here is a video with the issue: 
https://youtu.be/bAX5Ad_r4nk

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
This was fixed in 1.54c, if issues still occurring, you can re-open it.
