### ISSUE TITLE
Skill Learn items not works!

### ISSUE THREAD

**Issue by MrTemka** [suriyun-production/mmorpg-kit-docs#319]
I just tried it and the skill wasn't added and the item wasn't used

**Comment by insthync** [comment]
Your character must have a skill to be able to learn it.

![Screenshot_84](https://user-images.githubusercontent.com/2697550/78881469-10d53700-7a81-11ea-9d99-4bb0a129ec53.png)

**Comment by MrTemka** [comment]
but according to my plans, the character has no skills, he should learn from books
