### ISSUE TITLE
MMORPGKit Community Board/Forum

### ISSUE THREAD

**Issue by julhad** [suriyun-production/mmorpg-kit-docs#320]
Discord can sometimes be a bit annoying and confusing, so i would like to create a community board/forum for the kit as an alternative to the already existing discord server. It would feature a plugin where developers can present their project to the community and post updates as well as a download section where community add-ons and other content can be shared.

Of course, I would pay for everything related to the community board. Just wanted to ask if such a project would be okay for you?

**Comment by insthync** [comment]
It's okay, you can do it, but I won't be there frequently.

**Comment by insthync** [comment]
Is it was created ?

**Comment by julhad** [comment]
Still under construction, should be online for the public within this week, you can reach it under [mmorpgkit-community.com](https://mmorpgkit-community.com/) 
If you wish i can create an account (with the email of your github-profile) for you, then you can bypass the "under construction" notification and have a look

**Comment by Callepo** [comment]
@insthync its looking really nice.. 
@julhad make him an account like mineor above so he can have a look around

**Comment by julhad** [comment]
@insthync the community board is up, you can register under https://mmorpgkit-community.com/register
