### ISSUE TITLE
Monsters animation/speed issue

### ISSUE THREAD

**Issue by nakedfighter3d** [suriyun-production/mmorpg-kit-docs#322]
There are two speed options available for monster entity: **wandering speed** for calm roaming and **stats speed** - the actual speed for chasing player. But there is no way to use different animations for each speed. I use __simple animator controller, but the  MoveSpeed in the animator is always = 0..1 so I can't use blend tree as I do for player character entity.

**Comment by majimboo** [comment]
+1 
would be nice to be able to have monster have run animation for chasing and walk animation for wandering.

**Comment by moepi2k** [comment]
I also posted this again, dont saw that there was already a report for it. But yea need this function also, else wandering speed make less sense without the option do change animation

**Comment by insthync** [comment]
It already has walk animation for wandering in 1.55d
