### ISSUE TITLE
Vehicle/Mount doesn't move when set movement to server auth

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#324]
I tried setting the vehicle/mount movement to server auth and it won't move. If I set it back to not secure it can move.

Not sure, if it's intended or a bug. Since it might be a problem if the movement speed is set to vehicle speed and it's not being checked by the server.

**Comment by majimboo** [comment]
Just wanted to point out: both character and vehicle entities must be set to secure movement.

**Comment by majimboo** [comment]
I noticed something else, when I dismount the vehicle, Movement turns Server Auth (runtime) when I mount it it becomes Not Secure again.

**Comment by insthync** [comment]
An vehicle entities which set `Movement Secure` to `Server Authoritative`, its `Movement Secure` must always be `Server Authoritative`. An vehicle entities which set `Movement Secure` to `Not Secure`, it will switch to `Server Authoritative` when there is no rider. So if an vehicle entities which set `Movement Secure` to `Server Authoritative` turn to another, it's problem that I have to fix, I will check about it.

**Comment by insthync** [comment]
About move speed client able to change speed, but if it is `Server Authoritative`, changed speed won't apply

**Comment by insthync** [comment]
As I test `Movement Secure` settings is correctly.
