### ISSUE TITLE
Add relaxed and change weapon animation

### ISSUE THREAD

**Issue by majimboo** [suriyun-production/mmorpg-kit-docs#326]
After sometime, without attacking, change animation to relaxed mode. Put weapon to back of character (a slot) and relax animation starts. Will also auto activate when entering a safezone. Will go back to weapon animation when attacking again, or go outside safezone. Get weapon from back animation and start "unarmed" or "armed" animation set.

When changing weapons, have option to add animation of changing weapon.

Just a suggestion.

**Comment by gordowebdesign** [comment]
This is a good suggestion, +1
