### ISSUE TITLE
1.54с BUG NPC Sale dialogue 

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#327]
Fresh project. No items for sale in dialogue with NPCs

![image](https://user-images.githubusercontent.com/47291794/79160932-4eb8bf00-7de3-11ea-8753-17410322ce68.png)

**Comment by insthync** [comment]
Oh, I will upload the fix today.

**Comment by DimasjkTV** [comment]
> Oh, I will upload the fix today.

Can you post fix here please?

**Comment by insthync** [comment]
[MMORPG-KIT_FixNpcDialog.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4475816/MMORPG-KIT_FixNpcDialog.zip)

**Comment by DimasjkTV** [comment]
Now in my game the sale window is always open in any dialogue. At the same time, 3 items that are not connected with any dialogue got into the dialogue window.

**Comment by insthync** [comment]
[UnityMultiplayerARPG_FixNpcDialog.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4476859/UnityMultiplayerARPG_FixNpcDialog.zip)
This

**Comment by DimasjkTV** [comment]
Works fine. Thank you!

**Comment by JestHWas** [comment]
Is this fix in version 1.54c?

**Comment by insthync** [comment]
Next release

**Comment by insthync** [comment]
Updated (http://insthync.com/mmorpg_kit)

**Comment by JestHWas** [comment]
Thanks a lot Suriyun. Is it just the above fix in that release?

**Comment by insthync** [comment]
Just above fix and improve some player character controller  (some details https://github.com/suriyun-production/mmorpg-kit-docs/issues/292)
