### ISSUE TITLE
Map loaded twice v1.54c

### ISSUE THREAD

**Issue by JestHWas** [suriyun-production/mmorpg-kit-docs#328]
Hi,

I've noticed that the map loads are now done twice on version 1.54c.

This seems to be down to how pooling is done.

First Load
![image](https://user-images.githubusercontent.com/54454177/79162425-232ed800-7dd5-11ea-8c54-6c7446a6288a.png)

Then scene after second load
![image](https://user-images.githubusercontent.com/54454177/79162460-3641a800-7dd5-11ea-8cfb-90648bf99723.png)

Thanks,

**Comment by insthync** [comment]
It did not load twice, the progress show scene load progress and then show spawn progress (For some details https://github.com/suriyun-production/mmorpg-kit-docs/issues/262)

Because of pooling system it's going to instantiates an effects, that's normal for all pooling system.

**Comment by JestHWas** [comment]
Ah cool. So we can turn off the effect of the gauge finishing twice? If yes then I'll close this.

**Comment by insthync** [comment]
Yes, changes spawn entities events in `LanRpgNetworkManager` or `MapNetworkManager`

![Screenshot_92](https://user-images.githubusercontent.com/2697550/79217614-59be2e80-7e79-11ea-99f8-e29034278adf.png)

**Comment by JestHWas** [comment]
Thanks
