### ISSUE TITLE
Multiple summons stop map server in mmo mode 

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#33]
I have a new massive bug, in mmo mode, on a dedicated server (digital ocean), a multiple summon (more than one) causes the server to crash (map server).  Require to restart the server each time.

**Comment by insthync** [comment]
Oh this is very bad l, is there any error logs, I going to check it

**Comment by Koodetat** [comment]
[Log.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/3111261/Log.txt)

**Comment by insthync** [comment]
You're using SQLite database right ?

**Comment by Koodetat** [comment]
I use mysql.

**Comment by insthync** [comment]
Okay, I've fixed I push the update tonight

**Comment by Koodetat** [comment]
Fixed in 1.45 Thank you
