### ISSUE TITLE
[MMO2D] UiCharacterList won't hide after clicking Start Game

### ISSUE THREAD

**Issue by bortoletto** [suriyun-production/mmorpg-kit-docs#330]
I'm trying to find why this is happening, probably something in "UIMmoCharacterList.cs" but I'm kinda new in Unity so I didn't find anything yet. Here's a screenshot:

![bug_mmorpgkit](https://user-images.githubusercontent.com/29919334/79257856-9df10500-7e60-11ea-8d9b-9a0b650a92a1.jpg)

**Comment by insthync** [comment]
Did you set Map001_2D to build settings → scene in build ?

**Comment by bortoletto** [comment]
Wow, I can't belive that was the problem, sorry for the amateur mistake. Thank you very much.
