### ISSUE TITLE
1.54c Area skills

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#332]
* All this because pooling was set to 0

Problem with area skills. After upgrading from 1.54b to 1.54c, the duration of these skills is endless. On video skill duration 3 seconds but we can see more seconds.
Same thing with damage area skills. But it was possible to fix this with the help of an event. (see screenshot)
[Area skills 1.54c.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4477660/Area.skills.1.54c.zip)
![image](https://user-images.githubusercontent.com/47291794/79271915-44f98f00-7ea9-11ea-9e4e-b71ecf3a2622.png)
I tried to do the same with area buff, but nothing worked.

**Comment by insthync** [comment]
Is it already resolved?

**Comment by DimasjkTV** [comment]
> Is it already resolved?

i added 1 to pool size for this skill (works). Will test  loading time on phone
