### ISSUE TITLE
1.54c Bug Summoned Creatures

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#333]
1. If we run through monsters, then our summoned beings remember the first target and try to kill it first. Even if we run the whole map. (look at video)
[1.54c Summons Bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4478001/1.54c.Summons.Bug.zip)
2. Timer of summoned creatures does not update upon repeated summoning. (using skill)

**Comment by insthync** [comment]
Okay I will fix it now.
