### ISSUE TITLE
[2D] Guild creation won't work after last updates

### ISSUE THREAD

**Issue by bortoletto** [suriyun-production/mmorpg-kit-docs#334]
I'm getting a console error after clicking on the button Create Guild. It takes the gold but it doesn't create the guild. It was working fine in the 1.54b version. I've tested with an clean install of the old and the new, working just on the old one.

Unity version: 2018.4.20f1 LTS

error:
ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
MultiplayerARPG.SocialGroupData.AddMember (MultiplayerARPG.SocialCharacterData memberData) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/SocialGroupData.cs:55)
MultiplayerARPG.GuildData.AddMember (MultiplayerARPG.SocialCharacterData memberData) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/Guild/GuildData.cs:101)
MultiplayerARPG.GuildData..ctor () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/Guild/GuildData.cs:47)
MultiplayerARPG.GuildData..ctor (System.Int32 id) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/Guild/GuildData.cs:51)
MultiplayerARPG.GuildData..ctor (System.Int32 id, System.String leaderId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/Guild/GuildData.cs:57)
MultiplayerARPG.GuildData..ctor (System.Int32 id, System.String guildName, System.String leaderId, MultiplayerARPG.GuildRoleData[] roles) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/Guild/GuildData.cs:64)
MultiplayerARPG.GuildData..ctor (System.Int32 id, System.String guildName, System.String leaderId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/Guild/GuildData.cs:71)
MultiplayerARPG.GuildData..ctor (System.Int32 id, System.String guildName, MultiplayerARPG.BasePlayerCharacterEntity leaderCharacterEntity) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/Social/Guild/GuildData.cs:77)
MultiplayerARPG.BaseGameNetworkManager.CreateGuild (MultiplayerARPG.BasePlayerCharacterEntity playerCharacterEntity, System.String guildName, System.Int32 guildId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Networking/BaseGameNetworkManager_PlayerActivity.cs:602)
MultiplayerARPG.LanRpgNetworkManager.CreateGuild (MultiplayerARPG.BasePlayerCharacterEntity playerCharacterEntity, System.String guildName) (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:490)
MultiplayerARPG.BasePlayerCharacterEntity.NetFuncCreateGuild (System.String guildName) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity_NetworkResponse.cs:633)
LiteNetLibManager.LiteNetLibFunction`1[T1].HookCallback () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:207)
LiteNetLibManager.LiteNetLibFunction.SendCall (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Int64 targetConnectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:82)
LiteNetLibManager.LiteNetLibFunction.Call (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameterValues) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:106)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction (System.String id, LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameters) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:588)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction[T1] (LiteNetLibManager.NetFunctionDelegate`1[T1] func, LiteNetLibManager.FunctionReceivers receivers, T1 param1) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:477)
MultiplayerARPG.BasePlayerCharacterEntity.RequestCreateGuild (System.String guildName) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity_NetworkRequest.cs:422)
MultiplayerARPG.UIGuildCreate.OnClickCreate () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Social/Guild/UIGuildCreate.cs:42)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:66)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:108)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/EventSystem.cs:377)

**Comment by hiyall360** [comment]
Confirmed that this happens on the latest 3d mmo build too:
```(Error) [No Tag][ThreadedJob] Error occurs on ReadGuildJob

(Exception) [No Tag]System.ArgumentNullException: Value cannot be null.
Parameter name: key
  at System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) [0x00008] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at MultiplayerARPG.SocialGroupData.AddMember (MultiplayerARPG.SocialCharacterData memberData) [0x00000] in <852b83d032594fa98553ebd75953485b>:0 
  at MultiplayerARPG.GuildData.AddMember (MultiplayerARPG.SocialCharacterData memberData) [0x00000] in <852b83d032594fa98553ebd75953485b>:0 
  at MultiplayerARPG.GuildData..ctor () [0x00054] in <852b83d032594fa98553ebd75953485b>:0 
  at MultiplayerARPG.GuildData..ctor (System.Int32 id) [0x00000] in <852b83d032594fa98553ebd75953485b>:0 
  at MultiplayerARPG.GuildData..ctor (System.Int32 id, System.String leaderId) [0x00000] in <852b83d032594fa98553ebd75953485b>:0 
  at MultiplayerARPG.GuildData..ctor (System.Int32 id, System.String guildName, System.String leaderId, MultiplayerARPG.GuildRoleData[] roles) [0x00000] in <852b83d032594fa98553ebd75953485b>:0 
  at MultiplayerARPG.MMO.MySQLDatabase.ReadGuild (System.Int32 id, MultiplayerARPG.GuildRoleData[] defaultGuildRoles) [0x00049] in <852b83d032594fa98553ebd75953485b>:0 
  at MultiplayerARPG.MMO.ReadGuildJob.ThreadFunction () [0x00000] in <852b83d032594fa98553ebd75953485b>:0 
  at ThreadedJob.Run () [0x00015] in <852b83d032594fa98553ebd75953485b>:0```

**Comment by Callepo** [comment]
@insthync it was broken Since 1,54C after the party and guild update 

Fix invalid party and guild ally or enemy checking logics.

**Comment by Callepo** [comment]
@insthync  2d, 3d , single, mmo none work

**Comment by Callepo** [comment]
@bortoletto @hiyall360 @insthync 
![GuildFix1](https://user-images.githubusercontent.com/7702658/79777299-56261e00-8337-11ea-86db-1567be3345d1.png)
![GuildFix2](https://user-images.githubusercontent.com/7702658/79777333-60e0b300-8337-11ea-94d8-d5ce153948cc.png)

Temp fix 

I added a Debug log to check the memberdata..
it was being called 5 times on guild create..
4 of them is null only 1 is good..
Nullpointer check Prevent it from going further and crashing

**Comment by Callepo** [comment]
![Guildfix3](https://user-images.githubusercontent.com/7702658/79777720-f2e8bb80-8337-11ea-9bff-1500fe03696a.png)

**Comment by Callepo** [comment]
@insthync 
![goodfix](https://user-images.githubusercontent.com/7702658/79778564-368ff500-8339-11ea-99c7-411454f3290f.png)

This seems to be the reason it was sending nulls ..addmember being called before data has been set .. Commenting it out works fine

**Comment by insthync** [comment]
@Callepo Thank you, this is source of problem. So... everyone, you guys can remove this line.

**Comment by insthync** [comment]
This was fixed, if the issue still occurring, you can reopen it.
