### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#335]
The server is running, but I don’t like the errors.

![1](https://user-images.githubusercontent.com/56482598/79505479-a020b280-805e-11ea-94b0-cc62df53d8a4.jpg)

[log.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/4489659/log.txt)

**Comment by insthync** [comment]
You want me to change log format?, I just changed in 1.54c, did you try it?
