### ISSUE TITLE
1.54e Bug Summoned Creatures

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#337]
When using an attack, a character chooses a summoned creature as his target. This is very interfering in the battle, because the character does not want to beat opponents, instead, he constantly selects the summoned creature as the target.
[1.54e Summoned Creatures Bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4493640/1.54e.Summoned.Creatures.Bug.zip)

**Comment by majimboo** [comment]
yes noticed this on the latest version too.

+1

**Comment by insthync** [comment]
Thank you for bug report, I will fix it.

**Comment by insthync** [comment]
You can fix it by change logic in `BaseCharacterEntity.cs` → `IsCharacterWhichLookingFor` function to

```
private bool IsCharacterWhichLookingFor(BaseCharacterEntity characterEntity, bool findForAlive, bool findForAlly, bool findForEnemy, bool findForNeutral, bool findInFov, float fov)
        {
            if (characterEntity == null || characterEntity == this)
                return false;
            if (findForAlive && characterEntity.IsDead())
                return false;
            if (findInFov && !IsPositionInFov(fov, characterEntity.CacheTransform.position))
                return false;
            return (findForAlly && characterEntity.IsAlly(this)) ||
                (findForEnemy && characterEntity.IsEnemy(this)) ||
                (findForNeutral && characterEntity.IsNeutral(this));
        }
```

**Comment by DimasjkTV** [comment]
Works well! Thank you!
