### ISSUE TITLE
UMA Integration

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#338]
UMA integration throws an error on latest UMA 2.10 version

![issue](https://user-images.githubusercontent.com/2422714/79584654-f9282f00-80ce-11ea-82b4-1c8bb5878115.png)

**Comment by nakedfighter3d** [comment]
> UMA integration throws an error on latest UMA 2.10 version
This issue was discussed and fixed in UMA addon repository. [Check it here](https://github.com/insthync/UnityMultiplayerARPG_UMA/issues/4)

**Comment by insthync** [comment]
I just uploaded latest package, try it.
