### ISSUE TITLE
Character becomes stuck at end of combat animation

### ISSUE THREAD

**Issue by TashaSkyUp** [suriyun-production/mmorpg-kit-docs#34]
I'm using UMA and the UMA extension. But after attacking my character will become stuck at the end of the attack animation.. but only about 50% of the time.

**Comment by insthync** [comment]
Okay, I will fix it

**Comment by kazuden** [comment]
> Okay, I will fix it

I'm just waiting for this.please

**Comment by insthync** [comment]
Not sure this is like → https://gyazo.com/aaee022240d3bfcf196a3e9b5757c4ef ?
