### ISSUE TITLE
Updating LiteNetLib

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#344]
Hello,
Could you comment on how you are going about keeping LiteNetLib up-to-date?  Are we allowed to pull the latest commits and just add them to our projects or is that not advised?

Thank You.

**Comment by insthync** [comment]
I'm going to use the latest release version (from [this page](https://github.com/RevenantX/LiteNetLib/releases)) not the latest commit version from their master branch, you're allowed to pull latest commits to your project, just have to remove `LiteNetLib.dll` from Plugins folder

**Comment by JestHWas** [comment]
Yeah agree with Suriyun's approach. The master branch is not entirely stable.

Think there next version is coming out soon though.
