### ISSUE TITLE
Bug with Navmesh

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#347]
Character twitches if we use this parameter "Use nav mesh"
![image](https://user-images.githubusercontent.com/47291794/79904949-2dc51f00-841e-11ea-8d7e-b96916214127.png)

[Navmesh bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4512189/Navmesh.bug.zip)

**Comment by majimboo** [comment]
+1 yes, it also looks 360 around while walking if walk is fast. it twitches a lot on fast speed too. (like when I use skill to speed up movement)
