### ISSUE TITLE
No "use" option for consumables in inventory

### ISSUE THREAD

**Issue by hiyall360** [suriyun-production/mmorpg-kit-docs#348]
@insthync I'd like for there to be an option to "use" a consumable (like food) from the inventory without putting the item into a slot first.

At the moment, we are forced to put a food item into a slot in order to use it, rather than just using it from the inventory.

**Comment by insthync** [comment]
It will be added in next update

**Comment by majimboo** [comment]
+1 please also include "use" button (mobile) and right click (desktop) for potion and other consumables in inventory.

**Comment by insthync** [comment]
Added to 1.54f
