### ISSUE TITLE
Equipment doesn't show socket item with no bonuses

### ISSUE THREAD

**Issue by artyrambles** [suriyun-production/mmorpg-kit-docs#35]
When I add a socket item to an equipment and the socket item doesn't give any bonuses, nothing is shown on the equipment where the applied socket should be shown - not even the socket item's name. This also applies if the socket modifies a custom stat added with the DevExt.

If I take the same socket item and give it for example 1 bonus on HP, the socket item shows up as intended.

**Comment by insthync** [comment]
I think it was fixed, reopen it if you still have an issues
