### ISSUE TITLE
Gw addon

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#350]
Assets\UnityMultiplayerARPG_MMO_GuildWar-master\Scripts\GWCastleHeart.cs(18,123): error CS1061: 'BaseGameNetworkManager' does not contain a definition for 'GetPlayerCharacters' and no accessible extension method 'GetPlayerCharacters' accepting a first argument of type 'BaseGameNetworkManager' could be found (are you missing a using directive or an assembly reference?)

There is no GetplayersCharacters method, is there a new kit version coming out with this ? or ?

**Comment by insthync** [comment]
It's a new function which will be added in next update, It's just a function which return playerCharacters values
```
        public Dictionary<long, BasePlayerCharacterEntity>.ValueCollection GetPlayerCharacters()
        {
            return playerCharacters.Values;
        }
```
