### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#351]
Ive made some changes to the SkillListComponent which do not show up until the player gains a level. Im guessing an update to your UI is invoked on level up and thats why they are showing up. Can you tell me how to call this update?

**Comment by Fallen01** [comment]
To be more specific Im using another script to change a value of the first entry in filter on the SkillListComponent and though the string has changed UISkillDialog is not reflecting that change until i gain a level.

**Comment by Fallen01** [comment]
it also appears that if i attack or am attacked it also updates.

**Comment by insthync** [comment]
There is a `onLevelUp` event in `BaseCharacterEntity`, did you use it ?

**Comment by Fallen01** [comment]
no i didnt is it safe to use?

**Comment by Fallen01** [comment]
Anyway it updates if im hit or I hit someone else. That has nothing to do with onlevelup. Or are you saying i should use it?

**Comment by Fallen01** [comment]
public UISceneGameplay UIMain;

UIMain.UpdateSkills();

this was the answer thx for your time.
