### ISSUE TITLE
BasePlayerCharacterController.Singleton is null in MMO

### ISSUE THREAD

**Issue by AnisimovArthur** [suriyun-production/mmorpg-kit-docs#352]
Hi

I ran into a problem that BasePlayerCharacterController.Singleton somewhere **is null in MMO mode.** (it's ok in single player)

For example, NpcDialog.cs
If we make a log in RenderUI() it will be ok
But if we make a log in GetNextDialog() it will be null
<img width="847" alt="Screenshot 2020-04-25 at 21 36 50" src="https://user-images.githubusercontent.com/39820747/80287907-e0f28880-873c-11ea-87e7-f1350bbbffbb.png">
<img width="836" alt="Screenshot 2020-04-25 at 21 38 27" src="https://user-images.githubusercontent.com/39820747/80287937-2616ba80-873d-11ea-8eeb-841799bd0ac2.png">

Why can this happen? Can I get access to BasePlayerCharacterController from BasePlayerCharacterEntity?

**Comment by insthync** [comment]
It is null because at server-side, it runs without the client, the controller won't be instantiated, it will be instantiated when the client starts.

**Comment by AnisimovArthur** [comment]
Thank you.

So how I can get access to current controller in MMO in dialog?

**Comment by insthync** [comment]
I think you don't have to access dialogs at server-side, but you can check null then access the dialogs at client side
