### ISSUE TITLE
BUG Auto attack mobile

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#353]
1. Before us is a ranged monster
2. We use normal melee attack
3. The character runs up to the monster, makes an attack, but does not reach the hit box.
4. After that, the character gets into a stupor and normal attacks stop working.
5. If you move the character from his place, then he comes to life again.
6. This bug fails not always, but very often.
[Bug auto attack.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4535096/Bug.auto.attack.zip)

**Comment by insthync** [comment]
It's stopping attack the enemy or it still attack the enemy but does not hit target?

**Comment by DimasjkTV** [comment]
> It's stopping attack the enemy or it still attack the enemy but does not hit target?

stopping attack

**Comment by DimasjkTV** [comment]
> It's stopping attack the enemy or it still attack the enemy but does not hit target?

A bug with a joystick was also discovered. Sometimes he begins to move in one direction himself
[BUG Joystick mobile.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4536240/BUG.Joystick.mobile.zip)

**Comment by DimasjkTV** [comment]
Also, there is no smooth movement. It seems that the calculation of frames does not have time

[Not smooth movement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4536353/Not.smooth.movement.zip)

**Comment by DimasjkTV** [comment]
> It's stopping attack the enemy or it still attack the enemy but does not hit target?

By the way. I created a test build for iOS and there are no problems with smoothly movement on iOS. The movement is very smooth without microfreezes. Similarly, with skill effects. They do not cause friezes. Very strange.
