### ISSUE TITLE
MissileDmg pooling

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#357]
![image](https://user-images.githubusercontent.com/7702658/80509477-c6592300-8979-11ea-8b2f-1aed2a8ad286.png)
when starting game and some skills dont have prefab in them .. the game crashes..

![image](https://user-images.githubusercontent.com/7702658/80509560-e0930100-8979-11ea-9985-a1b073b5d27d.png)
 adding this null checker here in Basedamageentity line 108.. prevent it from crashing even tho there are like 2 or more null checks above before this point.. none stops it untill ur here for some reason

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/80510247-c148a380-897a-11ea-85bd-cad2b03a4f92.png)
with the null check added.. works fine

**Comment by insthync** [comment]
Okay, I will add the null check like you did, but it still weird that there are null checks but it still occurs :P

**Comment by Callepo** [comment]
yea i found it really weird too.. there is at least 2 or more null checks in codes before u reach this place..
but it still throws null pointer exception.. only after adding it here it stopped..
so i was confused lol

**Comment by insthync** [comment]
Added null check in 1.55
