### ISSUE TITLE
1.54f Missiles Damage on Mobile

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#359]
If we disable "WASD lock attack target", then the character does not turn towards the opponent when using ranged skills. The arrow flies back at the monster, but the character look in the opposite direction. If we use normal ranged attack, then the character turns in the direction of the opponent.
[Missiles skill 1.54f.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4547484/Missiles.skill.1.54f.zip)
![image](https://user-images.githubusercontent.com/47291794/80518814-ab91a900-898f-11ea-9de7-cad7a9e756d8.png)

**Comment by insthync** [comment]
Fixed in 1.55
