### ISSUE TITLE
Question: Where in script does the character figure out they are grounded?

### ISSUE THREAD

**Issue by TashaSkyUp** [suriyun-production/mmorpg-kit-docs#36]
In my character list scene my character thinks they are falling. but they work fine in my custom map scene.. where is it that they are colliding with the ground but the animation is not changing?

**Comment by insthync** [comment]
Oh, you fix it in Character creation scene by add following codes in UICharacterCreate.cs line 135
```
                characterModel.UpdateAnimation(false, MovementFlag.IsGrounded);
```
and in UICharacterList.cs line 92
```
                    characterModel.UpdateAnimation(false, MovementFlag.IsGrounded);
```
You also can make it play other animations (if you want) for example if you want it to play move animation you can use
```
                    characterModel.UpdateAnimation(false, MovementFlag.IsGrounded | MovementFlag.Forward);
```
To make it play move forward animation

**Comment by TashaSkyUp** [comment]
Thank you very much for your response! I'm sure it will work marvelously. I just wonder though.. where in the code is the logic failing to detect that the character is on the ground? I'd rather work with the framework instead of against it.

**Comment by insthync** [comment]
For `PlayerCharacterEntity` it is check ground in GroundCheck() function
