### ISSUE TITLE
Cannot carry more items

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#360]
The “cannot carry more items” message does not appear when the character is overloaded and cannot pick up more items from ground. This inscription appears when an overloaded character buys an item from an NPC.

**Comment by insthync** [comment]
It was check for overwhelming items (`IncreasingItemsWillOverwhelming`) in `BasePlayerCharacterEntity_NpcFunctions` → `NetFuncBuyNpcItem` function, it not working ?

**Comment by DimasjkTV** [comment]
> It was check for overwhelming items (`IncreasingItemsWillOverwhelming`) in `BasePlayerCharacterEntity_NpcFunctions` → `NetFuncBuyNpcItem` function, it not working ?

yes. i created character with 100+ items and dropped item on ground. Fresh project

**Comment by DimasjkTV** [comment]
Fixed. Thank you!
