### ISSUE TITLE
Damage Figures on mounts

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#362]
Вamage numbers on vehicle  twitch (double)
[Damage Figures on mounts.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4564923/Damage.Figures.on.mounts.zip)

**Comment by insthync** [comment]
Try increase `snapDistance` in `UIFollowWorldPosition` component 
![Screenshot_122](https://user-images.githubusercontent.com/2697550/81024614-19613780-8e9e-11ea-88b8-016f95e97350.png)

**Comment by DimasjkTV** [comment]
Works! Thanks!
