### ISSUE TITLE
TopDownController

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#363]
After adding the TopDownController to the kit, I can not attack enemies until I cast a spell on an enemy first.  Like Bash.  After I have casted a spell, the auto attacking starts to work.

Unity 2019.3.11f1
MMO Kit: 1.54f
UnityMultiplayerARPG_TopDownController: Latest commit

Video Footage:
https://youtu.be/-GXCnncP3ew

Edit:
Tested on MMO Kit: 1.54e and the TopDownController works as intended.  I believe the issue is from 

> Improve PlayerCharacterController. Now, while wasdLockAttackTarget is FALSE it will turn to enemy when press attack or use skill. And it won't clear selected target when press movement keys (WASD), it will deselect target when distance to target more than wasdClearTargetDistance value.

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed, try update latest repository commit.

**Comment by Hawkadium** [comment]
Fixed. Working as intended along side 1.55
