### ISSUE TITLE
Target Building Entity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#364]
When "Turn Forward While Action" is checked, then you cant target building (maybe other entitys also) entity when stand exactly in front of it. the health bar not appear. you need to stand 2-3 steps away. this is annoying becuase you cant interact with doors or sometime select the false entity. 

other thing. you can select entity through other entitys like open doors/chest or destroy by hold button "E"

**Comment by insthync** [comment]
I will improve it.

**Comment by moepi2k** [comment]
i saw you add it to 1.55 but the bug is still there

here a video where you can see the problem
-> https://youtu.be/avnuaQWcHN0

**Comment by moepi2k** [comment]
In ShooterPlayerCharacterController.cs line 552

```
// Entity is in front of character, so this is target
                    if (turnForwardWhileDoingAction && !IsInFront(tempHitInfo.point))
                        continue;
```

just remove it to fix it. dont know for what it is. can you remove it?
