### ISSUE TITLE
Missile Dmg Entity

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#365]
Can this script be a partial .. and Setup method be overridable
Or change missileDuration to Protected.. 
cuase we cant create custom missiledmgentity..
if we do .. our Duration will always be 0.. and projectiles explode instantly

![image](https://user-images.githubusercontent.com/7702658/80845618-10f0ce80-8c0a-11ea-8c84-098c22f77346.png)

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/80845957-1ac70180-8c0b-11ea-8557-f91998efd8d7.png)
and launchtime to protected

**Comment by insthync** [comment]
You actually can create a custom missile damage entity by copy the whole codes, but it's okay, I will changes it.

**Comment by Callepo** [comment]
the Skills requires an entity of missileDmgEntity so only way is to inherit from missiledmgEntity or added the skills to take Basedmgentity..thats why i did this 
![image](https://user-images.githubusercontent.com/7702658/80852649-78b71180-8c2a-11ea-9287-0517fe3b8867.png)
dont need partial for there.. but
to get the private variables i had to create getters and setters..
![image](https://user-images.githubusercontent.com/7702658/80852667-97b5a380-8c2a-11ea-8dc3-9038692a2ebb.png)
 which do require partial on the missile script



or how i did it was wrong idk..
But like this u only edit what u wanna edit

**Comment by insthync** [comment]
Ahh, I see, I am not thinking about missile damage entity class required for damage info

**Comment by Callepo** [comment]
np, happens
Ty for adding the partial

**Comment by insthync** [comment]
Updated codes in 1.55
