### ISSUE TITLE
2d character

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#366]
when i level up, my hp doesn't recover to full !

**Comment by insthync** [comment]
I didn't make it to recover hp to full when level up, if you want to do it and you know how to coding, you may create new gameplay rule class which may extend from `DefaultGameplayRule` class to modify `RewardExp` function to recover hp when level up.

Or wait next version which I will add option to recover hp when level up

**Comment by RunOrDi3** [comment]
ok thx alot , i wil wait you :)

**Comment by insthync** [comment]
Updated in 1.55 
- Add `recoverHpWhenLevelUp` to `DefaultGameplayRule`. If it's `TRUE` it will recover character's HP when level up.
- Add `recoverMpWhenLevelUp` to `DefaultGameplayRule`. If it's `TRUE` it will recover character's MP when level up.
- Add `recoverFoodWhenLevelUp` to `DefaultGameplayRule`. If it's `TRUE` it will recover character's Food when level up.
- Add `recoverWaterWhenLevelUp` to `DefaultGameplayRule`. If it's `TRUE` it will recover character's Water when level up.
- Add `recoverStaminaWhenLevelUp` to `DefaultGameplayRule`. If it's `TRUE` it will recover character's Stamina when level up.
