### ISSUE TITLE
[PlayerCharacterController2D] WASD controller mode still works with mouse click

### ISSUE THREAD

**Issue by bortoletto** [suriyun-production/mmorpg-kit-docs#368]
I'm using the WASD controller mode on PlayerCharacterController2D with lock attack target unchecked and before the last update the mouse click would do nothing, after this last update it started doing character movement. After some investigation, I've found the cause of this:

In the file "PlayerCharacterController_Inputs.cs" you removed a condition that checked the controller mode and kinda disable the mouse click.

` if (controllerMode == PlayerCharacterControllerMode.WASD)
                    {
                        destination = null;
                    }
                    else
                    {
                                 // code
                     }`

After putting this back the mouse click stopped working again as intended.

**Comment by insthync** [comment]
Thank you for bug report, I will put this in next update :)

**Comment by bortoletto** [comment]
Nice, you're the best!
