### ISSUE TITLE
Players Lagging

### ISSUE THREAD

**Issue by Skillerdk5** [suriyun-production/mmorpg-kit-docs#37]
Character lagging out.

https://www.youtube.com/watch?v=Iz4SMUKlzxw&feature=youtu.be

**Comment by insthync** [comment]
I want to see your settings in LiteNetLibTransform which attached to  the same game object with PlayerCharacterEntity

**Comment by Skillerdk5** [comment]
![image](https://user-images.githubusercontent.com/48094092/57979683-9b541880-7a21-11e9-9348-dc68dfd540dd.png)

**Comment by insthync** [comment]
Fixed (Talked in Discord)
