### ISSUE TITLE
UI Item Icon

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#374]
Hello, could you please explain where I can change the default Empty Slot Icon?  I can not find it for the life of me and no one else in the Discord seems to know.

Thank you,
https://i.postimg.cc/y6RnMTFn/icon.png

**Comment by Zaraath** [comment]
Select None as an option.   That's the default image.   It isn't an icon,  so you can't find it.


Sent from my Sprint Samsung Galaxy S10+.



-------- Original message --------

**Comment by insthync** [comment]
It's the same prefab with item icon prefab. For the demo content, there are `UIItemIcon_WithDragHandler` and `UIItemIcon_WithoutDragHandler` you just have to add new children with image (or raw image) attached then set sprite (or texture) which you wish to use as a empty slot
![Screenshot_124](https://user-images.githubusercontent.com/2697550/81034056-10815d80-8ec0-11ea-8d68-635b4c1dc6f8.png)

**Comment by Hawkadium** [comment]
Perfect, thank you.
