### ISSUE TITLE
Suggestion: EXP & Gold

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#378]
Make drop EXP & Gold from monsters for each level if possible. Thank you!

**Comment by insthync** [comment]
I not sure when you wish it to drop EXP and Gold, you means players will obtain EXP and Gold when finish level ?

**Comment by DimasjkTV** [comment]
> I not sure when you wish it to drop EXP and Gold, you means players will obtain EXP and Gold when finish level ?

![image](https://user-images.githubusercontent.com/47291794/81126891-69470980-8f45-11ea-9a32-4b563e9d4b8b.png)
i mean this at monsters =)

**Comment by insthync** [comment]
I see
