### ISSUE TITLE
Select a flag before the character entry screen

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#38]
Hello there. I want to add 3 different kingdoms to my game. Think of them as blue, red and yellow kingdoms. When the player enters the game, he will choose which kingdom he wants to be.then selects the character.3 kingdom maps within the game will be different, each map of each kingdom will be separate. The user will be born on the map of his kingdom when he starts the game after selecting the kingdom. and this kingdom can go through the game to other kingdom maps.The kingdoms will become enemies with other kingdoms (except dueling) that will become friends among themselves. fight one another.how can I do that

**Comment by insthync** [comment]
Yeah, I planned to add it later

**Comment by kazuden** [comment]
> Yeah, I planned to add it later

I hope it will be updated as soon as possible. this is my only problem. I'm waiting
