### ISSUE TITLE
<any-mmorpg-like> Combat log

### ISSUE THREAD

**Issue by iMakedonsky** [suriyun-production/mmorpg-kit-docs#381]
Would be great if the kit included a combat-log option, like what you see in other games.
Example: 
![image](https://user-images.githubusercontent.com/13186918/81143720-2d2e9b80-8f7b-11ea-93dc-1c5f4745b4f0.png)

**Comment by iMakedonsky** [comment]
Also, it shows 0 exp gained when killing trees/rocks, which is not what you would expect.

**Comment by Hawkadium** [comment]
There is a fix for this posted in the Discord.

In UIGameMessageHandler.cs
Find OnNotifyRewardExp(int exp)
Change **if (rewardExpPrefab == null)** to **if (rewardExpPrefab == null || exp == 0)**
