### ISSUE TITLE
Possibility to ignore main mesh renderer on spwned item prefab

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#383]
Hey, 

Can you add possibility to ignore main renderer on skinned mesh items when they are spawned as clones in equipment slots? 

For example now if you have set skinned mesh renderer and prefab with another rig - item takes root bone from main model instead of taking one that is set in prefab. 

Best regards

**Comment by insthync** [comment]
Added to 1.82c2
