### ISSUE TITLE
Harvesting and new character bug in 2D Mode

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#386]
i have created new character and 95% of it works fine inside the game but when i attack an enemy with bow , the animation stop after first hit but the character still giving hits without animation , also with harvesting , when i cut a tree the animation stop after first hit and the character still cutting!

**Comment by insthync** [comment]
2D right ?

**Comment by RunOrDi3** [comment]
yes

**Comment by insthync** [comment]
Fixed in 1.55b
