### ISSUE TITLE
2D Platformer style

### ISSUE THREAD

**Issue by jovtrc** [suriyun-production/mmorpg-kit-docs#388]
Is it possible to modify the MMO kit to a 2d platformer game?
For example, something like MapleStory and WindSlayer.

If yes, what should I edit to everything work without problems?

Thanks!

**Comment by insthync** [comment]
If I going to make a 2d platformer with this kit, I will setup the game as 3D, the thing we have to add is platformer entity movement which may fix  x or z position when character move and lock gameplay camera to look at character's side.
