### ISSUE TITLE
2D animations Bug

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#390]
1/ animation stops after first or second hit but the character still giving hits in ( Harvesting , killing monsters and other players ) .
2/ also stop with monsters while they attack the players.
all of this happens in 2D mode !
3/ the monsters when they move , they don't move in direct, i mean ( when they move to up , they don't move straight to up, they take curve ) it happens with all directions .
i hope you understand me and fix them in the next Update ^^ , cuz im creating an 2d mmo game :)

**Comment by insthync** [comment]
Fixed in 1.55b

**Comment by RunOrDi3** [comment]
thx alot
