### ISSUE TITLE
Passive Skills not applying to character.

### ISSUE THREAD

**Issue by jwilde8464** [suriyun-production/mmorpg-kit-docs#392]
I have created a new passive skill that is automatically given to the character on creation. When I enter the game the skill is shown in the skills UI, complete with its effects. However the effects aren't applied to the character.

The effects =
Increase in HP (added through, Buff->Increase Stats->Base Stats->HP)
Increase in Attributes (added through, Buff->Increase Attributes)

This has been tested with a fresh setup using 1.55.

**Comment by insthync** [comment]
Did you increase the the skill level?

As I try, it working correctly.

**Comment by jwilde8464** [comment]
If you mean in the character prefab, under where I added the skill, then yes. When I load the game it shows as Level 1 on the character's skill sheet, but fails to add anything.

**Comment by jwilde8464** [comment]
I know that Callepo also stated that it worked for him, however I've tried this several times, including on a fresh setup and nothing...

**Comment by moepi2k** [comment]
its also not working here. set skill level to 1 but dont get the bonus when login

**Comment by insthync** [comment]
I found the issue, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.55b
