### ISSUE TITLE
Area dmg skills

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#393]
Mobile platform. Prior to version 1.54f, we could use these skills while running in battle. That is, we hold down the button, select the place of the caste and the character uses the skill. Now in battle, when we use these skills while running, the character does not apply it. To apply it you need to release the joystick. Can you return the use of area skills, as in previous versions? Or how can I do this. Thank you!

Outside of battle, the character uses these skills as in previous versions. The problem is only during the battle, when there is an enemy nearby.

**Comment by insthync** [comment]
Fixed in 1.55b
