### ISSUE TITLE
Bug: isHide in debuff and stuns

### ISSUE THREAD

**Issue by iMakedonsky** [suriyun-production/mmorpg-kit-docs#396]
So i modified the Bash demo skill to be like that for Hide test: http://joxi.ru/J2bB0NI0RKno26.png
![image](https://user-images.githubusercontent.com/13186918/81582380-a6cdeb80-93b8-11ea-9907-3a54cdeaa988.png)

And like that skill cast breaks test: http://joxi.ru/EA44Jnfo6Ql4Ab.png

- if player attacks the monster, monster's mesh is still visible(although target box disappears), and navmesh movement takes his collision box into account(e.g. tries to not go though it).
- if monster attack player with same skill, player stops seeing himself(invisible to himself).
- also you're able to cast heal on dead and disapped entities(i heal monster after it died and disappeared).
 - also **receiving** a debuff to disallow move/attack/skills/items(**Stun**) **does not interrupt your started skill casts/attack animations** – you still finish them **after** receiving stun, even with "Can be interrupted = true"

See the demo: https://giphy.com/gifs/kfRbMg6smN4gJzNa6s

**Comment by insthync** [comment]
I did not set hidding objects in the previous Demo so you won't see monster hide
![Screenshot_150](https://user-images.githubusercontent.com/2697550/82187615-dfb91380-9916-11ea-9e5a-3d44aa8841b1.png)

I try to fix skills not interrupted, please try the new version.

**Comment by iMakedonsky** [comment]
Hiding mechanic is much better now. But one more issue:
target canvas still don't disappear when enemy is hidden: https://giphy.com/gifs/Q7k1CIDUBYzuOt8OtR
You still can see his hp, regen ticks, buffs.

**Comment by insthync** [comment]
Fixed in 1.63
