### ISSUE TITLE
AreaDamageEntity

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#399]
Can AreaDamageEntity also be updated to have its privates turned into protected?
So we can create custom AreaDmges..
cuase skills take only Areadmg
![image](https://user-images.githubusercontent.com/7702658/81745034-592ead00-94a4-11ea-859f-f15e9f28d4af.png)
so we gotta inherit it 
but privates are annoying

**Comment by Callepo** [comment]
Same issue as the missileDmgEntity i posted last week

**Comment by insthync** [comment]
Update as your request in 1.55b
