### ISSUE TITLE
Quest Spawner

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#40]
A little idea that seems very interesting: add in each quest, the ability to activate one (or more) inactive monsterSpawner, with the level of spawn monsters.  An option to spawn monsters of the same level as the player could be interesting too.  This could avoid losing too much performance.  Activation of the spawn monster begins when the quest is accepted.

**Comment by insthync** [comment]
I'm not sure exactly how it work
