### ISSUE TITLE
UIArmourAmounts 

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#400]
Armor amounts dont update when u remove all equipped parts only when u have 1 or >
Equiping 1 works fine.. it sets the stats ..
when u unequip it stats dont go back 0.. unless u relog..Ui isnt updating

0 items
![image](https://user-images.githubusercontent.com/7702658/81758285-99505880-94c1-11ea-9638-3483408bb737.png)

1
![image](https://user-images.githubusercontent.com/7702658/81758303-a9683800-94c1-11ea-8bc1-4b5e806b33e5.png)

2 
![image](https://user-images.githubusercontent.com/7702658/81758324-bd139e80-94c1-11ea-873c-5ff819995258.png)

1 
![image](https://user-images.githubusercontent.com/7702658/81758343-c8ff6080-94c1-11ea-9187-6bea15d99f27.png)

0
![image](https://user-images.githubusercontent.com/7702658/81758364-d288c880-94c1-11ea-94e5-01fc9c3e1b53.png)

Stays same as if had 1 equiped

**Comment by Callepo** [comment]
Works fine if u have have Base armors in ur Character class.. 
cuase its not null 
0 
![image](https://user-images.githubusercontent.com/7702658/81758553-72465680-94c2-11ea-95b1-02e67a78a2c8.png)

1
![image](https://user-images.githubusercontent.com/7702658/81758568-7c685500-94c2-11ea-9aaf-cc8afa7ac154.png)

0
![image](https://user-images.githubusercontent.com/7702658/81758581-85f1bd00-94c2-11ea-9a38-95990056f650.png)

**Comment by insthync** [comment]
Fixed, it will be included in next update.

**Comment by Callepo** [comment]
cheers
