### ISSUE TITLE
[Bug] UICurrentBuilding is not shown many times

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#402]
155f fresh installation / Survival / Mobile

In the past by holding click on the building shows UICurrentBuilding(which can set lock, destory etc)
But in this version, sometimes UI shown sometimes not shown.
According to my many tries, while opening the buildingUI(storage/workbench/campfire), UICurrnetBuiling is shonw without problem.
But in case close the buildingUI, UICurrentBuilding is not shown again.

**Comment by insthync** [comment]
Fixed in 1.55b
