### ISSUE TITLE
Open Character Slope

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#403]
Slope works .. but if u spam jump .. u can still climb anything
![image](https://user-images.githubusercontent.com/7702658/81877410-450eac80-9585-11ea-8c91-45b32302f3d9.png)

And was ground check distance removed?
character keeps doing Falling animation randomly

**Comment by Callepo** [comment]
u cant just walk up things anymore

**Comment by insthync** [comment]
Move to https://github.com/suriyun-production/mmorpg-kit-docs/issues/405
