### ISSUE TITLE
Slope limit & jump

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#405]
thank you for adding slope limit. it works. problem is player still can climb a 100m high wall by stam jump. maybe need to check that player cant jump on >max set slopes

**Comment by insthync** [comment]
Try changes codes at line 394 from (in RigidbodyEntityMovement.cs)
```
            if (CacheOpenCharacterController.isGrounded && isJumping)
```
to
```
            if (CacheOpenCharacterController.isGrounded && !CacheOpenCharacterController.startedSlide && isJumping)
```
I did not try it yet.

**Comment by insthync** [comment]
And also set slide start time value higher.

**Comment by Callepo** [comment]
Was gonna make a post.. but this one already here..
version 1.55b3
https://youtu.be/NPxnYepT3yQ

**Comment by Callepo** [comment]
@insthync

**Comment by insthync** [comment]
I also added velocity check before make it move, You may change magnitude checking to higher number to avoid move update which can change is ground state while idle.
```
            if (tempMoveVelocity.sqrMagnitude > 0f) // <-- You may change number higher than 0
            {
                collisionFlags = CacheOpenCharacterController.Move(tempMoveVelocity * deltaTime);
                if ((collisionFlags & CollisionFlags.CollidedAbove) == CollisionFlags.CollidedAbove)
                {
                    // Hit something above, falling in next frame
                    tempVerticalVelocity = 0f;
                }
            }
```

**Comment by insthync** [comment]
And to avoid spam jump you have to set slide start time higher

**Comment by insthync** [comment]
About invalid `is ground` state I will check it again. I might have to modify Unity's Open Character Controller.

**Comment by Callepo** [comment]
yea i changed it to 2 and it stopped..
i increased magnitude to 1 but dont think it did anything
still get random fall animations

**Comment by Callepo** [comment]
https://imgur.com/shScHlq

**Comment by insthync** [comment]
How about your Rigidbody Interpolate settings? Is it None or Interpolate or Extrapolate?

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/81986576-56fd5780-9638-11ea-95e6-57bf0dfb8da5.png)

**Comment by Callepo** [comment]
None is same 
Extrapolate made a difference.. its seems better.. alot better..but still does it some time..but its alot better

**Comment by Callepo** [comment]
https://imgur.com/Us2x2dh

https://imgur.com/7dhxw6n

**Comment by moepi2k** [comment]
works perfect now

**Comment by Callepo** [comment]
yea i tested in mmo works nice..
just idk why singleplayer acts different.. 
its doesnt do random falling animation in mmo

**Comment by moepi2k** [comment]
i got this issue not in singleplayer. whats your settings?
