### ISSUE TITLE
Flying after update & random falling animation

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#406]
https://gyazo.com/8d2ee963cb56783a2834b3ba8a6a86da

**Comment by insthync** [comment]
Try use context menu to set open character controller settings, as I described in changelog.

![Screenshot_137](https://user-images.githubusercontent.com/2697550/81938410-0fb69d00-961f-11ea-86ab-6cf84e13f996.png)

**Comment by poaq** [comment]
added, same effect: https://gyazo.com/6f4de87c0786be217251867233cc95bd

**Comment by insthync** [comment]
Or you may try to adjust `Radius`, `Height` and `Center` values in `Open Character Controller` component by your self, notice there will be 3 cyan (or blue) crosses which tell ground point, center and head point.

**Comment by poaq** [comment]
That fixed position of character. However random failing animation still occur: https://gyazo.com/293a41cad278795510bd1a8c00a1eafd

**Comment by poaq** [comment]
New errors: 
https://gyazo.com/f3bb3e645e118ef10bad7310edc9609b

**Comment by poaq** [comment]
Falling on mob attakcs:
https://gyazo.com/a6c91b33083b53afb33dd2e3784a02bb

**Comment by insthync** [comment]
Try 1.55b3 (just uploaded).

**Comment by poaq** [comment]
Partially fixed but now there are new bugs: you walk on mobs / items:
https://gyazo.com/1e1c6b498dca135c8cb57af97495c520
https://gyazo.com/7b96842dc1b86bccb6297425f93b1051

new errors: 
https://gyazo.com/086c0793ed90700358444b452209c3ba
providing to:
https://gyazo.com/3db926ba2ce33152bdd59aa19220cf4d

**Comment by insthync** [comment]
About character can move above item, you have to set `open character controller` -> `collision layer mask`, you may set like as my setting:

![Screenshot_140](https://user-images.githubusercontent.com/2697550/81974775-393bec80-9650-11ea-9526-be774b3f4c9d.png)

Another problem, add null check at that point
```
                if (skillCancellationTokenSource != null)
                    skillCancellationTokenSource.Dispose();
```

**Comment by poaq** [comment]
Fixed.
