### ISSUE TITLE
[Bug?] Rotate camera while attacking a target, then stop to attack

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#407]
155b fresh / Survival / Mobile

If rotate camera while attacking a target (monster or harvestable), then stop to attack. But target is still selected.

It seems targeting method had been changed.
For example, in the past If character move, target was cleared but now target is still selected.
In case of pointclickmove, target is cleared.

**Comment by insthync** [comment]
This is not occurring when I test it.

**Comment by dglee2592** [comment]
Did you test Mobile? Standalone works fine because it rotate camera with right mouse.
But in case of mobile, camera rotation uses left mouse click, so this happens.

**Comment by dglee2592** [comment]
This is not a bug so I'll figure this out by myself.
Thanks!!
