### ISSUE TITLE
Passive skills bugs (continuation from #392)

### ISSUE THREAD

**Issue by jwilde8464** [suriyun-production/mmorpg-kit-docs#409]
Continuation to #392 

I've just tried 1.55b and the passive skills are finally applying to the Character's stats (HP, MP etc) however a weird bug is appearing. On the initial log into the game your character will die within around 2/3 seconds (nothing is damaging it, they just drop dead). Once you respawn you do not encounter the bug again unless you create a new character.

**Comment by insthync** [comment]
You mean character falling to underground or start as dead?

**Comment by jwilde8464** [comment]
(Only effects characters that start with a passive skill)
The easiest way I can explain it is,
On your initial log in with your new character, it will have full HP etc (as you'd expect). After around 1-3 seconds (seems to vary slightly each time), your characters HP just drops to 0 and you obviously see the respawn menu. After you respawn there's no further bugs. I've confirmed that no NPCs etc are attacking them.

**Comment by jwilde8464** [comment]
This was seen on a fresh install.

**Comment by jwilde8464** [comment]
Well just updated to 1.55b3 and the problem has gone...not going to question it...
