### ISSUE TITLE
Loot tables gamedata

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#41]
Create loot gamedata table, and associate them with each monster.  it would be more convenient to add them (in case of similar loot table) to each AI monster.  (for example generic loot gamedata, boss loot gamedata) etc ...

**Comment by insthync** [comment]
Good idea, I will implement it later (after mount system done)

**Comment by Koodetat** [comment]
done in 1.46b. Thanks !
