### ISSUE TITLE
Sealed Classes

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#410]
![image](https://user-images.githubusercontent.com/7702658/81997862-47d6d380-9651-11ea-8bef-702a8d2d2714.png)

Can this class be unsealed. so i can inherit it and customize content

Obviously i can do it myself on my end.. 
but if its default in kit..
i can do my customization's and update kit later on without any issue..
Trying to keep the core untouched and only use DevExt and partials etc..
thats why i been asking for acces on alot of Classes and private variables

Thank you for applying them .. doesnt just benefit me, it helps alot of others too

![image](https://user-images.githubusercontent.com/7702658/81998251-5671ba80-9652-11ea-8f14-ba2c0801c0b4.png)

this the reason.. method requires just this.

![image](https://user-images.githubusercontent.com/7702658/81998489-e879c300-9652-11ea-8519-6091b0478252.png)

Can this method be Protected too instead of priv

**Comment by insthync** [comment]
Update as your request in 1.55c
