### ISSUE TITLE
Integrating loot bag into kit

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#411]
Hello Suriyun! 

Several months ago, I developed an alternative 'loot-bag' loot system for your kit which can be found in the following repo: https://github.com/vaughanb/UnityMultiplayerARPG_LootBag

There are a number of your users who prefer this loot method and they have been relying on me to update it for them as your kit progresses. It has been challenging keeping up with your kit updates due to my time constraints and I was wondering if you would be willing to incorporate this (or your own implementation of it) directly into the kit instead? I think it would lead to far less problems overall as people attempt to keep up to date.

Please let me know if you have any questions about my implementation. Thanks in advance!

**Comment by insthync** [comment]
I will integrate it in future version, then the kit will be able to switch between 2 kind of inventory system.

**Comment by vaughanb** [comment]
That would be great. Thank you!  From: Ittipon TeerapruettikulchaiSent: Wednesday, May 27, 2020 1:58 PMTo: suriyun-production/mmorpg-kit-docsCc: vaughanb; AuthorSubject: Re: [suriyun-production/mmorpg-kit-docs] Integrating loot bag into kit (#411) I will integrate it in future version, then the kit will be able to switch between 2 kind of inventory system.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LordPhrozen** [comment]
also looking forward to this method, for PVP reasons.

**Comment by insthync** [comment]
Oh, I forget this for long time

**Comment by vaughanb** [comment]
Not a big deal. I've continued to maintain my addon in the meantime.

**Comment by insthync** [comment]
Integrated into 1.71b, but it might not be like what you did.
