### ISSUE TITLE
[Possible Bug] webgl build redirecting to idbfs

### ISSUE THREAD

**Issue by Joshua2504** [suriyun-production/mmorpg-kit-docs#413]
try opening https://cdn.treudler.net/lagnum/webgl/player/index.html

It'll redirect you to https://cdn.treudler.net/idbfs/XXXXXXXXXXXXXXXX

Using latest build that's available in the asset store right now.

**Comment by Gui205** [comment]
Not related with MMORPG Kit, i use it on WebGL and never got this problem, it's look like the problem is your hebergement
