### ISSUE TITLE
[bug] Animation slide on long distance

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#415]
Hello, 

character start to slide if you click on bigger distance:

https://gyazo.com/837c338d58c4128a6fa29753b4803e96

**Comment by insthync** [comment]
I am not sure what's going on, I want to know the ground layer (the game object's layer) where the character moves to after goes down from stairs.

**Comment by insthync** [comment]
You can change entity movement to `CharacterControllerEntityMovement`
