### ISSUE TITLE
How do we disable this new movement controller?

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#416]
Hello,
How do we disable this new movement controller?  Its completely messed up my top-down RPG. My character is now too high above the ground. I cannot control Root-Motion anymore. And if I disable "Open Character Controller (Script)" my player just falls through the ground.  

Any help would be appreciated.
Thanks.

https://cdn.discordapp.com/attachments/460803281455939595/711434759892500490/fix.PNG

**Comment by insthync** [comment]
Seems like I have to bring old script back...

**Comment by insthync** [comment]
If you want to use old rigidbody movement system, import following package

[UnityMultiplayerARPG_LegacyRigidBodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4639759/UnityMultiplayerARPG_LegacyRigidBodyEntityMovement.zip)

Then attach `LegacyRigidBodyEntityMovementConversion` to your characters, you can select multiple characters to attach at once.

![Screenshot_148](https://user-images.githubusercontent.com/2697550/82137492-eaa27400-9842-11ea-87ac-de7cc9690a1e.png)

Then use context menu `Convert From New Rigid Body Entity Movement` to convert it back to old rigid body entity movement

![Screenshot_149](https://user-images.githubusercontent.com/2697550/82137504-102f7d80-9843-11ea-9e8f-2fe5b0cd3d90.png)

If conversion done, `RigidBodyEntityMovement` and `OpenCharacterController` will be removed and `LegacyRigidBodyEntityMovement` will be added

**Comment by Hawkadium** [comment]
Beautiful. Everything is working again. Thank you for the fast response.
