### ISSUE TITLE
"Animator Controller is Empty" errors on build

### ISSUE THREAD

**Issue by jonathaniscarroll** [suriyun-production/mmorpg-kit-docs#418]
Hi, getting these errors when I try to build from fresh project.
<img width="985" alt="Screen Shot 2020-05-17 at 3 58 14 PM" src="https://user-images.githubusercontent.com/2230668/82161276-8db1b880-9858-11ea-9d99-ecfd65b25a51.png">

**Comment by insthync** [comment]
I'm not sure that you change something?, As I try with fresh project version 1.55b3 and my Mac, it can be built.

**Comment by vw6** [comment]
Hi, I also get a build error on a clean mac os project.

![image](https://user-images.githubusercontent.com/19575067/94003415-dbf53c00-fda3-11ea-8529-50bf9aeee280.png)

**Comment by insthync** [comment]
@vw6 You should create new issues post, this is not related at all. It's seems to be Unity's bug https://forum.unity.com/threads/type-has-an-extra-field-of-type-in-the-player-and-thus-cant-be-serialized-error.497963/

**Comment by insthync** [comment]
I will close it because it seem like this does not exist anymore.
