### ISSUE TITLE
[Bug] in mobile, character keep move after exit a portal

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#419]
155b3 fresh / mobile / survival

When character enter a portal and respawned in a new position, character keep move.

**Comment by insthync** [comment]
It's portal which portal to the same map or difference map?

**Comment by Zaraath1** [comment]
I had this happen before. I think what it is, is that it is still processing your last destination before you ported.  So when you warp, you head to that prior destination which is next to the initial portal.  I kept looping back and forth because i set the entrance and exit next to eachother.

**Comment by dglee2592** [comment]
> It's portal which portal to the same map or difference map?

Different map. Map A to mapB, Map B to Map A

**Comment by insthync** [comment]
Ahhh, I see, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.55c
