### ISSUE TITLE
Click-to-Move and Animation States

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#420]
If I click to move to a destination.  Before I reach the destination, I cast a spell. Casting that spell will set my MoveSpeed to 0.0, the player will cast the spell, then continue to his destination.  Without MoveSpeed being set back to 1.0.  So the Player is stuck in the Idle animation until new input is given by the player.

https://youtu.be/hbA4z0EX9Kw

MMO Kit 1.55b3
Unity 2019.3.11f1

**Edit:**
Just did a few tests on the default kit.  This bug only happens after I have ran the "Legacy Rigid Body Entity Movement Conversion (Script)" and then added the "Legacy Rigid Body Entity Movement (Script)".

**Comment by insthync** [comment]
I want to see your transition settings from action state to stand state

**Comment by Hawkadium** [comment]
Appears to have been an issue on my end. I re-imported the SimpleCharacter and AdvancedCharacter Animation controllers and they seem to work now.
