### ISSUE TITLE
Unarmed Harvesting 

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#421]
If you setup an ressource on weapon type unarmed ( if you wanna pickup an ressource with just your hand ) i can't because you do 0 damage on the ressource

**Comment by insthync** [comment]
You have to set unarmed weapon type to harvestable game data

![Screenshot_152](https://user-images.githubusercontent.com/2697550/82414113-c0e68880-9aa0-11ea-9a0d-8044af82ba5b.png)

And also have to set default weapon's harvest damage 

![Screenshot_153](https://user-images.githubusercontent.com/2697550/82414184-dbb8fd00-9aa0-11ea-98f8-f9dc3d100300.png)

**Comment by Gui205** [comment]
Yes that's what i did, but i try to do it with an separate animation, so i did it with something call "pickup" and set it in melee type, with harvest damage, and setup my ressource with pickup item type for getting harvest but he still play Unarmed ( i set Unarmed at 0 damage in harvest ) and not pickup
