### ISSUE TITLE
Point Click Controller and Casting Spells

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#423]
Hello,
If the player Casts a spell, with Lock Attack Target enabled.  The player is unable to stop movement or interrupt the movement until the character has casted its spell on the target.

Alternatively, if I disable Lock Attack Target.  The same spell will just cast into the air, with no target.  Cost Mana and go on Cooldown.

Unity 2019.3.14f1
MMO Kit 1.55b3

https://youtu.be/8XpOF9pS91w

**Comment by insthync** [comment]
It never interrupts using skill after point click, I will fix it. 

And about when `Wasd Lock Attack Target` disabled, it's working as intended, it will turn to the enemy within attack range. it will
