### ISSUE TITLE
UMA Character Floats

### ISSUE THREAD

**Issue by klarkitgames** [suriyun-production/mmorpg-kit-docs#424]
UMA characters float above ground near top of grass and flowers.
![Floating UMA](https://user-images.githubusercontent.com/25287660/82375409-2aee2780-99e6-11ea-8b27-3ad4021e2c3e.PNG)

**Comment by poaq** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/406

**Comment by insthync** [comment]
Try set `OpenCharacterController`'s center, radius, height to cover your character, that is it.
