### ISSUE TITLE
Cash Packages not working

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#425]
https://cdn.discordapp.com/attachments/460856634302922763/712617846605086750/unknown.png

**Comment by insthync** [comment]
It's made for Android / iOS, you have to build and test this feature on device

**Comment by fedas61** [comment]
![resm](https://user-images.githubusercontent.com/46999478/82459382-8987d400-9ac0-11ea-9e00-971620cf816f.jpeg)

android not workin

**Comment by insthync** [comment]
So this is solved?, I saw you close this.

If it not yet, you have to learn about 
- How to setup [Unity Purchasing](https://docs.unity3d.com/Manual/UnityIAPSettingUp.html)
- How to use [script define symbols](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) (Read **Platform custom #defines** section), we have to add `ENABLE_PURCHASING` to the `script define symbols`
- Then learn how to [manage IAP catalog](https://docs.unity3d.com/Manual/UnityIAPDefiningProducts.html)
- Then set product Id by created item in `IAP catalog`.
![Screenshot_155](https://user-images.githubusercontent.com/2697550/82461850-0cbb2100-9ae5-11ea-990a-b5eb3be29b53.png)

**Comment by fedas61** [comment]
I understood the problem, thanks for the solution.

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

________________________________
Gönderen: Ittipon Teerapruettikulchai <notifications@github.com>
Gönderildi: Wednesday, May 20, 2020 5:58:55 PM
Kime: suriyun-production/mmorpg-kit-docs <mmorpg-kit-docs@noreply.github.com>
Bilgi: fedas61 <cixss_ulusoylu@hotmail.com>; State change <state_change@noreply.github.com>
Konu: Re: [suriyun-production/mmorpg-kit-docs] Cash Packages not working (#425)


So this is solved?, I saw you close this.

If it not yet, you have to learn about

  *   How to setup Unity Purchasing<https://docs.unity3d.com/Manual/UnityIAPSettingUp.html>
  *   How to use script define symbols<https://docs.unity3d.com/Manual/PlatformDependentCompilation.html> (Read Platform custom #defines section), we have to add ENABLE_PURCHASING to the script define symbols
  *   Then learn how to manage IAP catalog<https://docs.unity3d.com/Manual/UnityIAPDefiningProducts.html>
  *   Then set product Id by created item in IAP catalog.
[Screenshot_155]<https://user-images.githubusercontent.com/2697550/82461850-0cbb2100-9ae5-11ea-990a-b5eb3be29b53.png>
