### ISSUE TITLE
Debug - Right way 

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#426]
Hey, can you suggest what is the easiest way to debug server/client in the same time ? Do you use some third party plugins or there is some setup in kit ? 

Best regards,
M.

**Comment by insthync** [comment]
While testing in editor, I set breakpoint in Visual Studio to see variable changes.

But after built the client or server, I just see the log files.

**Comment by JestHWas** [comment]
@poaq - unless you are trying to debug something which requires a server, you can just debug everything in single player mode. 80-90% of the codebase does not require a server. Only need to test if you are doing any work requiring more than one player.
