### ISSUE TITLE
Shiled Weapon Type

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#428]
how will the animator character model weapon animations shield type be?
this type should only occupy one hand so weaponL
video;
https://discordapp.com/channels/460801727789137920/460803281455939595/713022954107174972

![bandicam 2020-05-21 17-21-17-019](https://user-images.githubusercontent.com/46999478/82568440-7e4bab80-9b87-11ea-8604-ebeda89a4375.jpg)

**Comment by insthync** [comment]
I don't get it.
