### ISSUE TITLE
Key binding

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#430]
I wanna change the key binding, i read the documentation, but many key are missing, and they are not in the input, so i wanna know where i can change the key for "Q" who open the Quest panel, "i" who open the inventory "T" for skill etc etc etc, for the moment i can only change the key you have set up on the game instance :/

**Comment by insthync** [comment]
In `UI Scene Gameplay` component there is `Toggle Uis` which you can set keys for toggle UIs

![Screenshot_159](https://user-images.githubusercontent.com/2697550/82667957-0652b380-9c63-11ea-8055-4a7f86e35a23.png)
