### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#432]
Hello,
Could you please consider moving the kit into two separate builds?  One for "LTS", bug fixes, etc.  And one for all the new features you are adding?

Every time you release a new feature, things break or new bugs are introduced or the workflow changes.  This is very difficult to grasp when the kit is already so big most of us just want to work on our MMO, without missing out on all the important bug fixes.

Another option might be a "Component Type system".  Where we could just check a box to enable/disable new Character Controller or Guild Wars or Top-Down Controller or whatever new feature is coming.

That being said, I don't know how difficult it would be to run two separate builds or to make sure drastic changes.

Thank you for considering this.

**Comment by insthync** [comment]
I think I didn't any add big new features that break old workflow, and just fixing bugs as you said. What is the feature that you think it's the thing that breaks or introduces new bugs?

And about "Component Type System", I think it is currently working as you said, you can change entity movement component by just remove one and then add one which you want, Can switch character controller by just change controller prefab setting in `Game Instance`.
