### ISSUE TITLE
[Bug?] Monsters/Harvestables can be spawned in "Water" layer

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#434]
I do not want to spawn monsters and harvestables in water, so I add and set a water area but monsters/Harvestables are still spawned in this "Water" layer.

I set this water plane with "Water" layer, and add mesh and/or box collider as trigger.
Of course water layer is masked in "GetHarvestableSpawnGroundDetectionLayerMask" and "GetMonsterSpawnGroundDetectionLayerMask", as it is.

Is this a bug or something I did wrong?

![image](https://user-images.githubusercontent.com/58107601/82738055-09879580-9d70-11ea-8285-f48a127994c5.png)

**Comment by moepi2k** [comment]
not a bug for me. i have some objects that need to spawn in water. just move your spawnarea out of water
