### ISSUE TITLE
1.55c BUG Timer of Summoned Creatures

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#436]
Timer of summoned creatures does not update upon repeated summoning. (using skill)
[Bug Timer Summoned Creatures (skill).zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4672425/Bug.Timer.Summoned.Creatures.skill.zip)

**Comment by insthync** [comment]
You can fix it by add codes to `UICharacterSummon` to function `UpdateData` line 75
```
            summonRemainsDuration = CharacterSummon.summonRemainsDuration;
```
![Screenshot_177](https://user-images.githubusercontent.com/2697550/83071265-06094c80-a097-11ea-8625-0df8fe6c4c28.png)

**Comment by DimasjkTV** [comment]
Works!
