### ISSUE TITLE
[Bug] First time buffs are applied, icons do not appear in GUI

### ISSUE THREAD

**Issue by Fashtas** [suriyun-production/mmorpg-kit-docs#437]
The first time a skill that applies a Buff to a player, the buff ICON does not appear under the character in UICharacterBuffs (both under UICharacterHpMp and UITargetCharacterHp)

Once a buff has been applied, and then expires, further buffs applied to the character from that point on work correctly.

The buffs appear to work correctly, just the ICON does not appear.

In Editor, if you pause the game, you can see the buff icon GameObject created, and placed on screen, it is just not visible. However I tried to compare a working buff icon vs an invisible one and all settings and properties of all game objects involved appeared to be identical.

If you target the player character, use the skill/apply the debuff, the icon also does not appear in the targeted character panel. Close and reopen that panel and the buff appears.

What it looks like in the Game View:
![image](https://user-images.githubusercontent.com/65834768/82742308-c80ede80-9d9f-11ea-8ef6-5d9740b1d94f.png)

When paused in editor, you can see the invisible game objected under the UICharacterHpMp panel:
![image](https://user-images.githubusercontent.com/65834768/82742318-eecd1500-9d9f-11ea-9232-96ad0e1e76aa.png)

**Comment by Fashtas** [comment]
Forgot to mention this is tested with a a fresh download, clean install, no code changes : 1.55c

Ran the basic Demo, created a Warrior, leveled up by choosing the demo Quest "Make Swords" then immediately handing in to level so I gained skill points.

Then took one level in the demo skill "StrengthUp"

Finally, used the skill to apply the buff.

**Comment by DimasjkTV** [comment]
Same with summoned creatures

**Comment by iMakedonsky** [comment]
I can confirm this issue exists.

**Comment by insthync** [comment]
I try to reproduce, but it's not occurring yet.

**Comment by DimasjkTV** [comment]
> I try to reproduce, but it's not occurring yet.
This is with summoned creatures
[BUG Summoned creaures timer.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4698151/BUG.Summoned.creaures.timer.zip)

**Comment by Fashtas** [comment]
I've uploaded a video reproducing the bug and showing what it looks like. I don't upload to youtube very often, so no idea why detail is so low, hopefully you can see whats happening

https://youtu.be/b2EkYvh7xfA

I used the same steps as above:
1) Clear empty new Unity project, import MMORPG KIT 1.55c
2) Run the demo (Assets/UnityMultiplayerARPG/Demo/Scenes/00Init.unity)
2) Create new warrior character
3) Do sword quest to gain XP
4) Buy StrengthUp skill
4) Use that skill.

I discovered one thing though, if you cast any spell (I cast a healing spell, this does not have any buff as far as I know) and that after that, skills work and show the buff icon (That's the second half of video)

**Comment by DimasjkTV** [comment]
abpunt summons UI.
Initially my "UISummons" was placed in UICharacterHp and due to this the summon icons sometimes disappeared. Now everything works.
![image](https://user-images.githubusercontent.com/47291794/84703234-97fec980-af60-11ea-9729-87a0ba429d28.png)

**Comment by insthync** [comment]
This was fixed some time ago.
