### ISSUE TITLE
BUG? Crit chance

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#438]
I use this
![image](https://user-images.githubusercontent.com/47291794/82753866-e7befa80-9dd1-11ea-8800-b03e167696a3.png)
1. Monster has 100 evasion and 0 accuracy.
2. Сharacter has 100 accuracy and 0 evasion
3. In battle, everything works correctly. A character cannot hit a monster, and a monster cannot hit a character.
4. I added a 100% crit chance to the character and he started to hit with a probability of 100%
Conclusion: Critical hits always hit the target. It does not depend on hit rate.
Is this a bug? If not, how can this be removed and made so that critical hits depend only on accuracy.

[Bug with crt chance.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4673459/Bug.with.crt.chance.zip)

In fresh project without script changes i added 99999999 evasion for monster and 0 accuracy for character, but +100% crit chance. Same situation, character can hit with 100% chance.

**Comment by iMakedonsky** [comment]
Yeah, i noticed this a while ago while digging through the damage calculation code.

Critical hits don't calculate miss chance.

Would be great to see a gameplay rule boolean to have this as an optional feature, or something like that.
![code](http://joxi.ru/Y2LQdpF7WMpEA6?d=1)

**Comment by insthync** [comment]
I intently made it always hit if critical occurs, I will move this codes part to gameplay rule so other developers can change it.

**Comment by insthync** [comment]
From latest version, I've move this part to `BaseGamePlayRule`  → `RandomAttackHitOccurs` (Implemented to `DefaultGameplayRule`)
