### ISSUE TITLE
Apply damage on building

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#439]
I try to make a script who will be attach to building entity, and make X damage each X second on the building. 

But the problem is i'm really lose with all this code to know how i can apply damage to the building with just a script attach on him. 

I saw the "ApplyDamageTo(entity)" but he have to much parameter and i dont know how can i use it.

**Comment by insthync** [comment]
You should use `BuildingEntity` -> `ReceiveDamage` to applies damages

There are following parameters: 
- Vector3 fromPosition: position of attacker (character or damage entity) if you want to make it applied damage to itself, you may set this value to this parameter to `transform.position`.
- IGameEntity attacker: attacker (character or other game entity) if you want to make it applied damage to itself, you may set this value to this parameter to `this`.
- Dictionary<DamageElement, MinMaxFloat> damageAmounts: receiving damages, if there is just one physical damage (no fire , no poison and so on), you can add 1 entry to dictionary with `null` as key then set randoming min/max amount of damage.
- CharacterItem weapon: weapon which character equipped, can set it to `null`.
- BaseSkill skill: skill which character use to attack, can set it to `null`
- short skillLevel: level of skill which character use to attack, can set it to `0`
