### ISSUE TITLE
MMORPGKIT Community is online

### ISSUE THREAD

**Issue by julhad** [suriyun-production/mmorpg-kit-docs#440]
Hi @insthync, in case you didn't see it in the [first "issue"](https://github.com/suriyun-production/mmorpg-kit-docs/issues/320) i just wanted to let you know that the community forum has been online for the past week. In case you want to join just tell me your username so i can give you proper privileges.

[https://mmorpgkit-community.com](https://mmorpgkit-community.com)

Have a nice day!

**Comment by insthync** [comment]
Registered (display name: Insthync) your website look good ;)

**Comment by julhad** [comment]
Thanks :) Gave you privileges, if you have any suggestion just let me know

Would be cool if you could add the url of the board to the description of the asset on the unity asset store, so more people know that there is also a community board

**Comment by insthync** [comment]
I just add the forum link to product description, Thank you :)
