### ISSUE TITLE
Controller issues

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#443]
Its acting up since its recent changes. It seems to continue to wander forward and you can get through walls this way. 

https://imgur.com/ZaB2KvI

heres a link leading to a video of the issue. 

thx for your time.

**Comment by insthync** [comment]
I want to see the wall colliders, please select the wall and capture screen shot.

**Comment by insthync** [comment]
And I also want to know wall layer, is it the one which checked in Collision Layer Mask or not.

![Screenshot_161](https://user-images.githubusercontent.com/2697550/82842875-6a94a200-9f05-11ea-8b19-336a5ceb8926.png)

**Comment by Callepo** [comment]
That video was made by me..
I have collidors on doors and walls and all..
And character cant walk through then when running
But if u walk and stop right infront of the wall.. the character moves forward slightly and go inside the wall..once inside u can just walk through... In the video fallen showed..
U can see me running into the wall and it stops me.. but if i do what i mentioned above.. i go through the wall

**Comment by Callepo** [comment]
I have same layers u showed in that pick and some extra that are custom to my game

**Comment by insthync** [comment]
Try this -> 
[RigidbodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4695460/RigidbodyEntityMovement.zip)

**Comment by Callepo** [comment]
Works.. no more wall ghosting
