### ISSUE TITLE
Request: Integration of World Manager API

### ISSUE THREAD

**Issue by kittrellbj** [suriyun-production/mmorpg-kit-docs#444]
I would suggest integrating World Manager API into the kit so that environment assets and time-keeping assets (and some others) can be managed with a common interface and allow the server to have control over certain aspects of the world manager.

The World Manager API can be found here on github and is free to use. https://github.com/adamgoodrich/WorldManager

This would allow users who have environmental assets that they like to use and integrate them with the kit much faster and much easier. Many of the leading environmental assets already can be switched to the WM API mode.

**Comment by MostHated** [comment]
I am not 100% on this, but I thought I heard that is not really being used anymore. It has not been updated since 2017.

**Comment by kittrellbj** [comment]
Let me check with Adam and see if it was considered code-complete at that time or not.

**Comment by kittrellbj** [comment]
According to Bryan in the Procedural Worlds discord, the World Manager API is functioning properly. They have not received any complaints to the contrary.
