### ISSUE TITLE
Respawn harvestables / monsters

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#445]
I noticed that harvestables and monsters respawn after leaving / joining game in single player mode.  Duration of respawn is not taken into account between two game cession. To compensate this, it is possible to add a probability variable (% chance) on each harvestables and monsters.  (single player and mmo) this will allow for example to configure rare encounters / harvestables

for mmo mode, I think it will also require a reset timer.

**Comment by sawcisson** [comment]
The easiest way would be to rewrite your own spawnable script i think.

Just reuse the existing code and add some more data % etc... as you wish
