### ISSUE TITLE
[Issue] Projectile shooting with shooter controller

### ISSUE THREAD

**Issue by harmoxyne** [suriyun-production/mmorpg-kit-docs#446]
Using ShooterCharacterController in MMO set-up, allow zooming (in my case from 3 to 10) and change TPS offset to: X: 0, Y: 2.5, Z: 0 (to have crosshair right above your character).

Melee weapons works fine, bow and gun shooting also ok.

Casting a magic spell (for example Fire Bolt from Demo) without target will cast it up to the sky, casting it with target will cast it to target.

Expected result, as for me, is when casting without target, it will cast magic spell parallel to the ground in looking direction.

Here is a video with issue demonstration: https://youtu.be/wjWNBDg0WAk

Also, sometimes it's cast damage as expected (right where crosshair is looking), but skill effect as show in video.

**Comment by Blunnyn** [comment]
same problem

**Comment by insthync** [comment]
Fixed, please wait for next update.

**Comment by insthync** [comment]
Fixed in 1.55d
