### ISSUE TITLE
If Monster summon monsters they are passive

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#450]
I was working on a boss mechanic and i added a summon skill to my monster to summon more monsters.
But the monsters are inactive and just follow the summoner and don't attack the player.

How could i fix this ?

![ezgif com-optimize (3)](https://user-images.githubusercontent.com/62859548/83244845-35f04700-a1a0-11ea-9465-629ad9b9142f.gif)

**Comment by DimasjkTV** [comment]
Yes. There is such a bug. If a monster uses summoning skills, summoned creatures are passive and do not attack the character.

**Comment by insthync** [comment]
Try 1.55d
