### ISSUE TITLE
BUG update 1.55d player fall through ground

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#453]
Since the latest update our players now fall through the map when they spawn

**Comment by sawcisson** [comment]
If i use Navmesh agent the player doesn't fall throught but it's uncontrollable

**Comment by insthync** [comment]
Not sure when you use rigidbody entity movement, did you setup open character controller ?

**Comment by sawcisson** [comment]
Well before updating i was using Navmesh for main movement checkbox.

I setted up the open character controller and also tried with the legacy one.

When i use rigid body it just goes through the ground .

If i want to use navmesh this is what happen : https://youtu.be/Ts1DjmkAXF4

Character just go crazy , i tried to work with numbers and config but the character goes full bananas

**Comment by insthync** [comment]
Okay i will check nav mesh entity movement

**Comment by sawcisson** [comment]
Thanks, Let me know if you need any kind of video , screenshot or testing to be done.
I'll gladly provide testing material.

**Comment by insthync** [comment]
As I try with demo content, it's working correctly, I want to try your build.

**Comment by sawcisson** [comment]
Allright, how do you want me to send it to you ?

**Comment by insthync** [comment]
Send to ittipon.bay@gmail.com

**Comment by DimasjkTV** [comment]
Add a script for the character "Open Character Controller"
