### ISSUE TITLE
Issue with UI while using campfire

### ISSUE THREAD

**Issue by harmoxyne** [suriyun-production/mmorpg-kit-docs#454]
When using campfire, put default meat, put some wood. Turn campfire ON, click on default meat to open it's info. 
After that, everytime campfire will produce something, window with default meat info will appear until you close campfire window or turn it off.

https://youtu.be/tLI7vx39q6E

**Comment by insthync** [comment]
Oh, I will fix it.

**Comment by insthync** [comment]
Sorry for lately fix

You can import this package to fix it.

[MultiplayerARPG-FixStorageItemsSelectedItemNotDeselect.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4962731/MultiplayerARPG-FixStorageItemsSelectedItemNotDeselect.zip)
