### ISSUE TITLE
Weapon Animation 

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#455]
I setup my weapon animation, but when i equip my weapon he still play the default animation. 

I did something wrong ? 

https://image.noelshack.com/fichiers/2020/22/7/1590923061-animation.png

**Comment by insthync** [comment]
Not sure too, Your weapon item type may wrong or something, You may test is animation by weapon type were set correctly or not by set `TestAnimActionType` to weapon and `TestWeaponType` to your weapon type then click on `Set Animator Clips For Test`. Then go to `Animation` tab find your animation clip if you can found it and play correctly so it were set correctly.

**Comment by Gui205** [comment]
> Not sure too, Your weapon item type may wrong or something, You may test is animation by weapon type were set correctly or not by set `TestAnimActionType` to weapon and `TestWeaponType` to your weapon type then click on `Set Animator Clips For Test`. Then go to `Animation` tab find your animation clip if you can found it and play correctly so it were set correctly.
> 
> ![Screenshot_184](https://user-images.githubusercontent.com/2697550/83434667-1b022900-a465-11ea-90b8-046ab1e90e66.png)
> 
> ![Screenshot_185](https://user-images.githubusercontent.com/2697550/83434674-1d648300-a465-11ea-8af5-7409f8b66c73.png)

I did it, but i have only the animation i have on the animator controller, and not the custom animation i set for my weapon
