### ISSUE TITLE
CombatTextTransform distance display 

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#456]
Is it possible to change the distance how the name entity will be display ? Actually it's seem to be fix, and when you have many entity arround you it quickly inconsitant and unreadable.

Example with this tree, i'm at 10m and he's display, the small banana on his left is display too : 

https://image.noelshack.com/fichiers/2020/22/7/1590923062-distance.jpg

Maybe if is not possible yet, it will be cool to have the option like the harvestable range for display the name of the entity

**Comment by harmoxyne** [comment]
If you are talking about targeting with shooter controller, simply change "Find Target Raycast Distance" in controller prefab

**Comment by Gui205** [comment]
> If you are talking about targeting with shooter controller, simply change "Find Target Raycast Distance" in controller prefab

Thanks you but that's do it for every Entity including player and monster, what i do it something configurable each harvestable depend of the size of the harvestable, a tree or an flower don't have the same size on the screen so have to display the text transform at different distance.

**Comment by insthync** [comment]
Try set `GameInstance` → `CombatTextDistance`

![Screenshot_182](https://user-images.githubusercontent.com/2697550/83431652-dfb22b00-a461-11ea-9c7f-ae67857dcbe4.png)

**Comment by Gui205** [comment]
Not work : 

![DistanceSet1](https://user-images.githubusercontent.com/11931221/83434656-2b9da980-a43b-11ea-98b2-9093e9c75148.jpg)

**Comment by insthync** [comment]
Oh, I see, you mean raycast to objects, for now you can set `Find Target Raycast Distance` as harmoxyne  saids. I will add more option to `ShooterPlayerCharacterController` later.
