### ISSUE TITLE
Player game crash when having ping

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#457]
During some testing we noticed that some players when they have ping will just have their game crashing.

Do you have an idea where this is coming from ?

**Comment by JestHWas** [comment]
Do you mean if they have a high ping? I would guess it may be something to do with the player timing out.

**Comment by sawcisson** [comment]
Yeah i think so but crashing the whole .exe process (Game not responding) is kinda weird
On the other hand if he is hosting and has ping we will all lag but he won't crash.

**Comment by insthync** [comment]
If it's still ocurring, you can reopen it.
