### ISSUE TITLE
Enemy skills (melee/ranged)

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#458]
Enemy right now can only use melee or ranged attacks but not mixed. Would be nice when enemy switch from melee to ranged when player is away for. When you see attack distance to e.g 2 and you add a bow skill to the enemy.he will only use it when he is <= 2 distance

**Comment by Blunnyn** [comment]
+1

**Comment by insthync** [comment]
Noted, I will add it later.
