### ISSUE TITLE
x2 Damage 1.45c

### ISSUE THREAD

**Issue by bboydimas8** [suriyun-production/mmorpg-kit-docs#46]
Default damage deals x2 damage with 0 crit damage and 0 crit chance. 
Number above the monster is correct, but if you look at monster health, then the Number is 2 times bigger

**Comment by insthync** [comment]
Oh, I will fix it

**Comment by DimasjkTV** [comment]
U can close this

**Comment by DimasjkTV** [comment]
> Oh, I will fix it

u can close this
