### ISSUE TITLE
Player Slide down slopes

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#460]
after patching v1.55d i noticed that player slides down slopes (not the feature from the openCharacterController). it doesnt matter what angle the slope has. player slide down slowly.

i noticed you changed 

RigidBodyEntityMovement.cs
**tempVerticalVelocity from 0f to -0.1f**

when i change back to 0 it works. i dont know why you changed it to -0.1f

**Comment by insthync** [comment]
I try to set to -0.1 because while it's 0 the `OpenCharacterController` → `IsGround` state incorrect sometime.

**Comment by Gui205** [comment]
> I try to set to -0.1 because while it's 0 the `OpenCharacterController` → `IsGround` state incorrect sometime.

It's look like is still incorrect with -0.1 that's why sometime the character play the fall animation randomly

**Comment by insthync** [comment]
Try this: 
[RigidbodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4719936/RigidbodyEntityMovement.zip)

Also fixing character bouncing when `autoSwimToSurface` set to `TRUE`

**Comment by Gui205** [comment]
> Try this:
> [RigidbodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4719936/RigidbodyEntityMovement.zip)
> 
> Also fixing character bouncing when `autoSwimToSurface` set to `TRUE`

Work perfect thanks you

**Comment by Gui205** [comment]
> Try this:
> [RigidbodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4719936/RigidbodyEntityMovement.zip)
> 
> Also fixing character bouncing when `autoSwimToSurface` set to `TRUE`

The bouncing is correctly fixed. But the slope problem is still broken : 

https://gyazo.com/2207e5c69e250b5096cc5778bfebbe13

**Comment by insthync** [comment]
[RigidbodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4756957/RigidbodyEntityMovement.zip)

Try this :P

**Comment by Gui205** [comment]
> [RigidbodyEntityMovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4756957/RigidbodyEntityMovement.zip)
> 
> Try this :P

https://gyazo.com/00516375fc3f47932e17856f54cad70f 

Not work IsGround state is incorrect.

**Comment by insthync** [comment]
I feel that I made wrong decision to implement Unity's standard assets character, I have to fix bug for this many time :P

**Comment by Gui205** [comment]
> I feel that I made wrong decision to implement Unity's standard assets character, I have to fix bug for this many time :P

It's not an critical bug, if your terrain is mainly flat or have real slope and not just 1 to 5° slope you don't have this issue

**Comment by moepi2k** [comment]
i would like to ask if the slide on minor slope angles after jump can be fixxed? it feels like player is on icy floor :P

**Comment by moepi2k** [comment]
seems to be fixed in 1.58c, great thank you
