### ISSUE TITLE
[ Suggestion ] for 2D

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#462]
What about adding Run Animation 2D for running by SHIFT Button ? with other animation set < check the photo > without run animation its not good while playing..

![Untitled](https://user-images.githubusercontent.com/64667641/83566225-f454f880-a51f-11ea-8f07-75bf30a5999e.jpg)

**Comment by insthync** [comment]
Okay, I will add it.

**Comment by RunOrDi3** [comment]
thx :)

**Comment by insthync** [comment]
Added in 1.56b
