### ISSUE TITLE
Suggestions: Portals

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#463]
1. Teleportation between locations using the button. This is done in the Turnbase kit. With this, we can do different GUI for teleports. Now we are limited only by NPC dialogues. Or is it already implemented in the kit, I just don’t know this? 
2. Items that allow you to teleport to different locations. (like teleportation scrolls)

**Comment by RunOrDi3** [comment]
teleportation's item will be good like any mmo game

**Comment by fedas61** [comment]
It can be done with some work.
I made a portal that works with Ui

**Comment by DimasjkTV** [comment]
> It can be done with some work.
> I made a portal that works with Ui

Everything can be done with some work. The question is how.
