### ISSUE TITLE
[Bug?] Hip and Leg animation is not working

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#465]
1.55d fresh install / survival / mobile

I recognized that the attack animation is different from the animation clip.
Especially, half of body(hip and leg) is not animated.(or keep idle)

I test this with fresh kit and compare attack2 animation between ingame and original clip(apply same avatar)

Can you check this? I record this in below zip file

[2020-06-04 04-21-42.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4725792/2020-06-04.04-21-42.zip)

**Comment by moepi2k** [comment]
this is not a bug. it use avatar mask for upper body actions

**Comment by dglee2592** [comment]
Oh indeed!
Thanks!

**Comment by lol1hp-games** [comment]
Hello , why is this happening?
[MsVampy.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/11082811/MsVampy.zip)
