### ISSUE TITLE
[ 2x BUGS ] Harvest and Monster Spawn in 2D

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#468]
When i create a a harvest spawner or monster spawner with square or Radius , the monster or the trees comes out of the area which i made  also with the monsters....look at the picture

![1234](https://user-images.githubusercontent.com/64667641/83943835-50a96800-a7ff-11ea-8715-a012d84e3548.jpg)

**Comment by insthync** [comment]
The purple squere is the spawn area ?

**Comment by RunOrDi3** [comment]
yes , spawn harvest and monster have the same bug

**Comment by insthync** [comment]
It was fixed some time ago, try 1.58, if it's still occurring tell me then.
