### ISSUE TITLE
BUG with mounts

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#470]
Single player
1. We put a mount to the storage.
2. We exit the game.
3. We enter the game.
4. We take a mount from the storage.
5. We can not use a mount, which was taken from the storage.

[Bug mount storage.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4750181/Bug.mount.storage.zip)

**Comment by insthync** [comment]
[FixStorageItemIdNotSaved.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4772117/FixStorageItemIdNotSaved.zip)
Can be fixed by this package.

**Comment by insthync** [comment]
Fixed in 1.56
