### ISSUE TITLE
Suggestion ( Adding hit points to vehicles )

### ISSUE THREAD

**Issue by Hellwood** [suriyun-production/mmorpg-kit-docs#471]
Vehicles having hit points will allow other players and monsters to attack your vehicles. If I'm inside a tank, the tank should take the damage first. It would also be great to fix or heal it back. Thank you

**Comment by Fallen01** [comment]
great idea i think it makes the system more complete and I hope its considered as a feature.

**Comment by Koodetat** [comment]
Yes it's a good idea !  repairing buildings is also missing!

**Comment by RunOrDi3** [comment]
good suggestion :)

**Comment by moepi2k** [comment]
Yeeeeaaa 🙌

**Comment by Gui205** [comment]
yes stats on vehicule/mount will be realllyyyy great

**Comment by gordowebdesign** [comment]
very needed
