### ISSUE TITLE
1.55d Bug Summoned creatures

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#473]
Summoned creatures are not summoned with full health. At the first level, everything is fine, but as soon as you increase this skill, the health when summoning is not full.
[1.55d summoned creatures bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4756183/1.55d.summoned.creatures.bug.zip)

**Comment by insthync** [comment]
You can fix it by add following codes to `BaseMonsterCharacterEntity.cs` function `InitStats()` line `121`
```
            ForceMakeCaches();
```
(Line before `CharacterStats stats = this.GetCaches().Stats;`

**Comment by insthync** [comment]
Fixed in 1.56
