### ISSUE TITLE
Repairing items

### ISSUE THREAD

**Issue by Benamas** [suriyun-production/mmorpg-kit-docs#475]
Hello,
Items have durability but when the durability reach 0  you cant use it and it needs to be repaired
and i cant find the option on npc dialog for repairing the item is this missing or it will be added on future updates ?

**Comment by Gui205** [comment]
You can repair item using the ItemRefine.

https://gyazo.com/4de0ef4c29d10ed3c3efa0c98c08c400

**Comment by insthync** [comment]
I will add repair NPC dialog in next version

**Comment by Gui205** [comment]
I do a simple modification for repair building, that's allow the owner to repair his building, that's use event so you can add animation/sound/fx when you repair on the entity ( not the player ) :

https://gyazo.com/54e1a7c1e645ad536ae8958c6cbb380c

 - First you have to add the button in UICurrentBuilding.cs
 - In BasePlayerCharacterController you have to add  
`  PlayerCharacterEntity.RequestRepairBuilding(TargetBuildingEntity.ObjectId);`
 - On BasePlayerCharacterEntity_NetworkResquest.cs you have to call net function 
`CallNetFunction(NetFuncRepairBuilding, FunctionReceivers.Server, new PackedUInt(objectId));`
- On BasePlayerCharacterEntity_NetworkSetup.cs  you have to register the repair net function 
- On BasePlayerCharacterEntity_NetworkResponse.cs 
CurrentGameManager.RepairBuildingEntity(buildingEntity.Id);
- And in BaseGameNetworkManager.cs you have to call the Repair()
` public virtual void RepairBuildingEntity(string id)
        {
            if (buildingEntities.ContainsKey(id))
            {
                buildingEntities[id].Repair();                
            }
        }`

Repair() have to be add in BuildingEntity.cs you can add an Unity Event for the FX, if you want to all player see the FX of the Event do it with an netfunction.

**Comment by Benamas** [comment]
Thank you for looking @insthync

**Comment by Benamas** [comment]
@Gui205 did you add some custom script on rafine for reapiring or ?

**Comment by Gui205** [comment]
> @Gui205 did you add some custom script on rafine for reapiring or ?

Not really, i just add the Repair button in UIRefine.cs all the rest is actually ready

![repairtool](https://user-images.githubusercontent.com/11931221/84539678-2c182900-acf4-11ea-8893-26e08fe300e0.gif)

To do that just add 
`public void OnClickRePair()
        {
            if (CharacterItem.IsEmptySlot())
                return;
            activated = true;
            activeItemId = CharacterItem.id;
            OwningCharacter.RequestRepairItem(InventoryType, (short)IndexOfData);
        }`

After that do an news button in UIRefine do that : 
https://i.gyazo.com/76832348504d26b11227a14c8009f573.png
