### ISSUE TITLE
[BUG] Buildings

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#476]
Two small building bugs:

-Player can attack his own buildings.
-Monsters can attack buildings in safe zones.

**Comment by moepi2k** [comment]
one more thing -> other players can build on your foundation/houseparts.

**Comment by Gui205** [comment]
in BasePlayerCharacterEntity_NetworkResponse.cs you can maybe work around and fix that with BoundsDistance and buildingEntity.IsCreator you can maybe look for who build the previous entity and set and range with BoundsDistance to build if you are not the owner of the previous building.

But i'm not sure and i didn't test that so you have to look maybe that could work

**Comment by insthync** [comment]
Fixed in 1.56
