### ISSUE TITLE
Suggestion: Storage

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#477]
Tabs for storage.
![image](https://user-images.githubusercontent.com/47291794/84401728-48409b00-ac0c-11ea-9a3c-449a50848e5d.png)

**Comment by insthync** [comment]
I can add 1/2/3 tabs (and so on) immediately, but it will take long time to make tabs which separate items by category.

**Comment by DimasjkTV** [comment]
> I can add 1/2/3 tabs (and so on) immediately, but it will take long time to make tabs which separate items by category.

I think that categorization is not necessary. There are only tabs in the screenshot. The icons on the right are irrelevant. It will simply facilitate the use of storage with a large number of slots.
