### ISSUE TITLE
Mobile drag and drop (inventory)

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#478]
A strange situation with a mobile canvas (see a video). Also in the mobile build items drop out of inventory if they shift in inventory (old bug).

[mobile inventory bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4782931/mobile.inventory.bug.zip)

**Comment by insthync** [comment]
Ahh, seems like it dropping on touch to rotate camera area.
