### ISSUE TITLE
[ Suggestion ] premium subscription Pass

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#479]
What about adding premium subscription pass system to mmorpg kit in the future ? any online game have this feature :)
 i hopefully you will add it

**Comment by Koodetat** [comment]
it's a good idea to monetize your game, for example with an xp / gold boost ... and specific items.

**Comment by RunOrDi3** [comment]
yeah

**Comment by gordowebdesign** [comment]
Restricting access based on a database 0/1 value for subscription based games

**Comment by insthync** [comment]
Make a paid request then I will consider it later.
