### ISSUE TITLE
animations problem

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#48]
When the forward command is given after the attack movement, the attack movement continues
it shouldn't be like this

https://gyazo.com/aaee022240d3bfcf196a3e9b5757c4ef

**Comment by insthync** [comment]
How about make it not move while attacking ?

**Comment by kazuden** [comment]
> How about make it not move while attacking ?, Is that practical idea?

yes don't move during the attack

**Comment by kazuden** [comment]
> How about make it not move while attacking ?, Is that practical idea?

yes don't move during the attack. let the attack continue

**Comment by insthync** [comment]
![Screenshot_27](https://user-images.githubusercontent.com/2697550/60857858-55078280-a236-11e9-93e4-2162259d1669.png)
Just set in your `Weapon Item` → `Move Speed Rate While Attacking` to 0
