### ISSUE TITLE
[BUG] Storage

### ISSUE THREAD

**Issue by SheepaCZE** [suriyun-production/mmorpg-kit-docs#480]
Report Bug: CurrentGameManager.IncreaseStorageItems(..) -> MinSlotIndex is not working well in SuriMMOKit
// if slots are full function is putting to anywhere empty slot, and if storage is total full, then function is putting it above MaxItemStack limit

**Comment by insthync** [comment]
Not sure what is the problem, As I try, I can't deposit my item to storage while it is full

**Comment by SheepaCZE** [comment]
Thank you. If you do so, could you also add it for MinSlotIndex and MaxSlotIndex . If there is not any free slot in the range, then it throws the item out.

**Comment by insthync** [comment]
I've fix it in 1.56, while I fix it I decide to change an APIs, so it won't have `MinSlotIndex` because I think it's hard to use and it's not very useful.
