### ISSUE TITLE
BUG Monster range attack

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#483]
1. Monster has 4 hit distance of normal attack
2. Monster has a skill with 10 hit distance
3. Monster uses skill
4. After uses a skill, all normal monster attacks have a 10 hit distance like in skill

Tested with melee 
![image](https://user-images.githubusercontent.com/47291794/84950784-19d52b00-b0f8-11ea-9c95-b556842f888e.png)

**Comment by insthync** [comment]
Try 1.56, I've try to fix it.
