### ISSUE TITLE
Is there possibility to equip diffrent item base on gender?

### ISSUE THREAD

**Issue by poaq** [suriyun-production/mmorpg-kit-docs#487]
Hey,

Is there possibility to equip diffrent item base on gender?

best regards,
Poaq

**Comment by insthync** [comment]
You means like if both male character and female character wear the same item but show difference model?

**Comment by poaq** [comment]
Yes. :)

**Comment by DimasjkTV** [comment]
It is possible just to create slots with different names. For example, a boots on a male character, Boots_M, and a boots on a female character Boots_F, use two models on each item. I use this in my game.
