### ISSUE TITLE
MMO Accounts

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#49]
Hello. Is it possible to add MMO Accounts & Characters System to the mmorpg_kit system.MMO Accounts & Characters System is at the following link 
https://assetstore.unity.com/packages/tools/network/mmo-accounts-characters-system-100334

**Comment by insthync** [comment]
It already have register / login / character create / create delete system, not sure which part you want from that asset ?

**Comment by kazuden** [comment]
> Zaten kayıt / giriş / karakter oluşturma / silme sistemi oluşturmuştur, o öğeden hangi bölümü almak istediğinizden emin değil misiniz?



> It already have register / login / character create / create delete system, not sure which part you want from that asset ?

you just want the kingdom election so the region election place

**Comment by insthync** [comment]
I will add faction feature soon, let's talk about it later
