### ISSUE TITLE
trouble with UI

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#491]
download new version 1.55 
new project, nothing change
when i try add image it's okey. 
![image](https://user-images.githubusercontent.com/48797909/85216896-a5d3a500-b3cd-11ea-8f8c-b5b8359e031f.png)

![image](https://user-images.githubusercontent.com/48797909/85216915-eaf7d700-b3cd-11ea-920f-3fc654fbd3f6.png)

but when I put on the armor and take it off, the background picture disappears ..

![image](https://user-images.githubusercontent.com/48797909/85216926-04008800-b3ce-11ea-95e1-92129ebde5c7.png)

part of the prefab becomes inactive after putting on and removing the armor element

how can i fix it?

**Comment by insthync** [comment]
You should create new image to use as place holder icon, that icon will be deactivated when no item set.

**Comment by insthync** [comment]
No answer for long time, I will close it.
