### ISSUE TITLE
[Suggestion]Monster Characteristic: Afraid

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#493]
Hello,

it would be nice when you can add one more Characteristic for monsters:

Right now we have: Neutral, Aggressive and Assist. The new one could be: Afraid.
and when someone attack the monster it will flee away from attacker from maybe 5 or 10 seconds.

**Comment by sawcisson** [comment]
Would be a great addition

**Comment by gordowebdesign** [comment]
We really just need BD integration.
