### ISSUE TITLE
[Bug] Custom Conditional in Dialog Graph does not work (with a fix)

### ISSUE THREAD

**Issue by Fashtas** [suriyun-production/mmorpg-kit-docs#498]
You cannot select the CUSTOM value as a conditional in the Dialog Graph. Even if you could, the parameter that allows you to attach your own Function does not appear.

To fix (As far as managed to do so anyway)
\UnityMultiplayerARPG\Core\Scripts\GameData\Npc\Enums\NpcDialogConditionType.cs
Line 12,
Change
```c#
   Custom = 255
```
to
```c#
   Custom = 254
```
\UnityMultiplayerARPG\Core\Scripts\GameData\Npc\NpcDialogConditionData.cs
Insert at line 6 above the "public class..."
```c#
   [System.Serializable]
```

Tested with fresh download of 1.55d

There is also an issue dragging gameobjects etc onto the Conditional function slot but you can click the 0 and browse all gameobjects in the project and add that way. I think there is no drop handled override added to that field.

**Comment by insthync** [comment]
Oh,thank you, I will fix it.

**Comment by Fashtas** [comment]
Thanks! Love this project :)

**Comment by insthync** [comment]
Fixed in 1.57, but I still set `Custom` enum value to  255 (byte.MaxValue)
