### ISSUE TITLE
bug 1.55

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#499]
after updating to version 1.55, new projects crashed every time they are different, I can’t start the project, for example, here’s the last error, I didn’t change anything, created several items and restarted the unit in a day, everything, the project doesn’t work

![image](https://user-images.githubusercontent.com/48797909/85369429-727d4b80-b570-11ea-8189-096ad605eed6.png)

this is the 4th time when I recreate the project, especially without changing anything in it, but different errors appear in the scripts

**Comment by insthync** [comment]
If you doesn't changes anything, you should try remove Assets/MultiplayerARPG/Core and Assets/MultiplayerARPG/MMO folders, then try reimport the package
