### ISSUE TITLE
generic character root motion error

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#50]
generic character does not allow root motion.does not complete the animation and then runs where it is.there is no problem with character and animation.You can watch the video from the link below.

https://gyazo.com/cbdb0ff747fe268490c40e01ffa24519

image:

https://gyazo.com/d08e698a9b71b3b2134e8b0ea2350346

**Comment by insthync** [comment]
Update version 1.50d which contains this root motion implementation (for RigidBodyEntityMovement only) is already uploaded.
