### ISSUE TITLE
ItemDropEntity place in Scnee

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#500]
-> Make ItemDropEntity can be placed in the scene and also able to respawn after picked up by characters.

how should  that work? whould be nice if docs are updated for new features. dont know how to place it in scene so that player can take it

**Comment by insthync** [comment]
This: https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/143-item-drop-entity

**Comment by moepi2k** [comment]
when i place it directly to scene and try to loot it throw this error: 

NullReferenceException: Object reference not set to an instance of an object
CharacterDataExtension.IncreaseItems (ICharacterData data, System.Collections.Generic.IEnumerable`1[T] increasingItems, System.Action`3[T1,T2,T3] onIncrease) (at Assets/UnityMultiplayerARPG/Core/Scripts/CharacterData/CharacterDataExtension.cs:974)
MultiplayerARPG.BaseCharacterEntity.NetFuncPickupItem (PackedUInt objectId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity_NetworkResponse.cs:70)
LiteNetLibManager.LiteNetLibFunction`1[T1].HookCallback () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:212)
LiteNetLibManager.LiteNetLibFunction.SendCall (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Int64 targetConnectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:87)
LiteNetLibManager.LiteNetLibFunction.Call (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameterValues) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:111)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction (System.String id, LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameters) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:587)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction[T1] (LiteNetLibManager.NetFunctionDelegate`1[T1] func, LiteNetLibManager.FunctionReceivers receivers, T1 param1) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:476)
MultiplayerARPG.BaseCharacterEntity.RequestPickupItem (System.UInt32 objectId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity_NetworkRequest.cs:131)
MultiplayerARPG.ShooterPlayerCharacterController.UpdateInputs_BattleMode () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Shooter/ShooterPlayerCharacterController.cs:826)
MultiplayerARPG.ShooterPlayerCharacterController.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Shooter/ShooterPlayerCharacterController.cs:430)

when i make a spawner it wont spawn.

**Comment by insthync** [comment]
Try 1.56b

**Comment by moepi2k** [comment]
works
