### ISSUE TITLE
Bug ItemDrop

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#501]
- Item Drop Spawn Area don't spawning the asset DropItemEntity
- When you place an DropItemEntity in the world you can pickup it but i got an eror ( I make my test with Material_Stone amout 5 ): 
`NullReferenceException: Object reference not set to an instance of an object
CharacterDataExtension.IncreaseItems (ICharacterData data, System.Collections.Generic.IEnumerable`1[T] increasingItems, System.Action`3[T1,T2,T3] onIncrease) (at Assets/UnityMultiplayerARPG/Core/Scripts/CharacterData/CharacterDataExtension.cs:974)
MultiplayerARPG.BaseCharacterEntity.NetFuncPickupItem (PackedUInt objectId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity_NetworkResponse.cs:70)
LiteNetLibManager.LiteNetLibFunction`1[T1].HookCallback () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:212)
LiteNetLibManager.LiteNetLibFunction.SendCall (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Int64 targetConnectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:87)
LiteNetLibManager.LiteNetLibFunction.Call (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameterValues) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:111)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction (System.String id, LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameters) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:587)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction[T1] (LiteNetLibManager.NetFunctionDelegate`1[T1] func, LiteNetLibManager.FunctionReceivers receivers, T1 param1) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:476)
MultiplayerARPG.BaseCharacterEntity.RequestPickupItem (System.UInt32 objectId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity_NetworkRequest.cs:131)
MultiplayerARPG.ShooterPlayerCharacterController.UpdateInputs_BattleMode () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Shooter/ShooterPlayerCharacterController.cs:826)
MultiplayerARPG.ShooterPlayerCharacterController.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Shooter/ShooterPlayerCharacterController.cs:430)`

- The news ItemDropEntity don't correctly instanciate the model drop when you put the Scriptable Object you want to drop in Random Item field ( Model Container didn't instantiate the Item )

**Comment by insthync** [comment]
Fixed in 1.56b
