### ISSUE TITLE
[Question] Lan Game / Sync Sun(Directional Light)'s position 

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#502]
I'm very struggling with this.. so I know you are very busy but If you can give me a clue, it will help me a lot.

I have day/night system in my project so in single play, directional light(Sun) is rotating.
However in case of Lan game, day/night is different with host and client, so I'm trying to sync the sun's position.

What I tried is, add LiteNetLibTransform script to sun, but not working..
Can you give me a clue?

Thanks in advance!!!

**Comment by Gui205** [comment]
What is your system ? 
You have to also make an script to sync all the value of your day/night system ( I do know what he is so can realy help you on that point ). 

You can follow the documentation of LiteNetLib for that : 
https://insthync.github.io/LiteNetLibManager/#/basic/sync_variables

**Comment by dglee2592** [comment]
Thanks, I'll look into
