### ISSUE TITLE
Unity higher version crash

### ISSUE THREAD

**Issue by Benamas** [suriyun-production/mmorpg-kit-docs#503]
This week i updated my unity version from 2018.4.17 to 2019.4.0f1 LTS after this version change i get some wierd crash.

I get crash from those actions.
First one is when i save character  prefab or save the scene.
![Screenshot_5](https://user-images.githubusercontent.com/18700648/85606841-d62c7500-b653-11ea-9e09-6f31163eafe3.png)

Second crash is when i test my build in mobile device
the crash happen only if i add monster to the map or add spawner to it.

![Screenshot_51](https://user-images.githubusercontent.com/18700648/85606995-f8be8e00-b653-11ea-8dfc-a618dc3b6275.png)
![Screenshot_4](https://user-images.githubusercontent.com/18700648/85606999-f9572480-b653-11ea-852f-0c6c42f6c748.png)

Not sure if  its a bug or something that i mess with the settings.

**Comment by insthync** [comment]
I will try 2019.4.0f1, I also saw 2019.4.1f1 did you try it ?

**Comment by Benamas** [comment]
No i didnt try for 2019.4.1f1 only 2019.4.0f1 LTS
 one of my test was a clean build in 2019.4.0f1 it was working good on mobile no high cpu problem

**Comment by moepi2k** [comment]
i got crash when i save scene. 2019.3.13
never had this before

**Comment by moepi2k** [comment]
update unity to 2019.4.1 fixed the problem for me

**Comment by Benamas** [comment]
updating to 2019.4.1 fix the first problem thats true but the second one is giving the same resault high cpu usage for npc spawner

**Comment by Benamas** [comment]
The high cpu problem was due my old npc scripts so everything is oke soory for that.
closing the thread
