### ISSUE TITLE
Suggestion: Events called on Entity Actrivate (others?)

### ISSUE THREAD

**Issue by Fashtas** [suriyun-production/mmorpg-kit-docs#504]
It would be nice to attach events to handle user Activates for entities without making code changes to Core.

I can't see a way to do this with DevExt or overrides since all user Activate code is run from ActivateBuilding in BasePlayerCharacterController.cs which cannot be overridden.

I've not looked at other events but there could be scope for more assuming they aren't already handled (Destroy may be I think, and Start/Awake have DevExt)

**Comment by Gui205** [comment]
Yes that's true ... each update i have to re write all my event :/.

**Comment by insthync** [comment]
You adding new kind of building then you want to add new condition for that building, right?

Then I will add the action which you can add an action via DevExt for example

```
public partial class BasePlayerCharacterController {
    
        [DevExtMethods("Awake")]
    public void AdditionalAwake() {
        onActivateBuilding += OnActivateMyBuilding;
    }

    public void OnActivateMyBuilding(BuildingEntity buildingEntity)
    {

    }
}
```

**Comment by Fashtas** [comment]
Yes this would work perfectly!
