### ISSUE TITLE
GetHit animation issue -> animator controller

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#505]
Could it be that you changed something on animator controller in 1.56? it seems that enemy when they get hit while walking the gethit animation override the walkanimation then they slide during motion. never noticed that before.

**Comment by insthync** [comment]
You actually can create your own animator controller but you have to put prepared empty clips which located in `Assets/UnityMultiplayerARPG/Core/Animations`, it's named like __Idle, __Dead

Because if I changes it, it will affect other developers projects
