### ISSUE TITLE
Disable side walk

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#507]
I try to disable sidewalk and add this in BaseGameEntity.cs

public void SetMovement(MovementState movementState)
        {
            **_if (!canSideMove && (MovementState.HasFlag(MovementState.Left) || MovementState.HasFlag(MovementState.Right)))
            {
                movementState = MovementState.None;
            }_**

on line 805

but im still able to strafe right and left. i checked how you do it for allow Sprint left right in extraMovementState.

can you pls help me out?

**Comment by insthync** [comment]
You should disable side movement in entity movement, the MovementState is movement input state which can be changed by Entity Movement component before pass to Game Entity.

**Comment by moepi2k** [comment]
Hm, i cant find the right place to change it. I checked BaseEntityMovement.cs and IEntityMovement.cs

**Comment by insthync** [comment]
Find in RigidbodyEntityMovement or NavMeshEntityMovement or other, I don't know which one are you using.

**Comment by moepi2k** [comment]
I use rigidbodyentitymovemet. Okey i check it again whenon computer. Thank you
