### ISSUE TITLE
BUG Elemental Dmg UI

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#508]
1. 
UI is not updated after removing weapon.
See video
[BUG Elemental Dmg UI.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4842602/BUG.Elemental.Dmg.UI.zip)

![image](https://user-images.githubusercontent.com/47291794/85952907-20c03100-b975-11ea-8814-26830570481b.png)

I created in UICharacter script
![image](https://user-images.githubusercontent.com/47291794/85956369-18282480-b98e-11ea-950b-b277cda24c55.png)
![image](https://user-images.githubusercontent.com/47291794/85956377-21b18c80-b98e-11ea-865a-2da9c9d66d64.png)
and seems to be working with elemental damage now

public UIDamageElementAmounts uiDamageElementAmounts;    55 line

and 351 line

if (uiDamageElementAmounts != null)
            {
                uiDamageElementAmounts.isBonus = false;
                uiDamageElementAmounts.Data = cacheDamages;
            }

2. 
* We have two items. 1 item with resistance to lightning, and a second item with resistance to poison.
* The first we equip item with resistance to lightning. Resistance increases
* The second we equip item with resistance to poison. Resistance increases
* We remove the second item and see that in the tooltip the resistance has not changed.
This only happens with two items or more.
If you equip 1 item with a resistance and remove it, the tooltip will be updated. 
See video
[BUG Elemental Dmg UI 2.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4843089/BUG.Elemental.Dmg.UI.2.zip)

**Comment by DimasjkTV** [comment]
I created
![image](https://user-images.githubusercontent.com/47291794/85956369-18282480-b98e-11ea-950b-b277cda24c55.png)
![image](https://user-images.githubusercontent.com/47291794/85956377-21b18c80-b98e-11ea-865a-2da9c9d66d64.png)
and seems to be working with elemental damage now

**Comment by insthync** [comment]
[MultiplayerARPG_FixAmountsUI.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/4874399/MultiplayerARPG_FixAmountsUI.zip)

Try this package :)

**Comment by insthync** [comment]
Fixed in 1.57
