### ISSUE TITLE
Adding option for align to ground

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#509]
It would be great when you can add option where devs can check "Align to Ground". good for entities that are have 4 legs like mounts (horses) else it looks weird

![align to terrain](https://user-images.githubusercontent.com/2422714/86032046-06e72280-ba37-11ea-9944-db64d626d29a.png)

maybe this free asset can help.
https://assetstore.unity.com/packages/tools/animation/ground-fitter-121798

**Comment by insthync** [comment]
I will add it to the entity movement script.

**Comment by insthync** [comment]
Added `CharacterAlignOnGround` component in version  1.57, attach it to your horse entity then set skinned mesh's root bone's transform to `rootBoneTransform` field.
