### ISSUE TITLE
Dialogue Condition "Quest Ongoing" Bugged

### ISSUE THREAD

**Issue by 23rdsilence** [suriyun-production/mmorpg-kit-docs#511]
The show condition "Quest Ongoing" in the dialogue system doesn't seem to work correctly.

It should only show this dialogue option when the specified quest is ongoing because it has the "Quest Ongoing" show condition.

![image](https://user-images.githubusercontent.com/59323771/86071964-62181580-ba35-11ea-805e-b2f1d13a0cab.png)

However, even when the player has not started any quests

![image](https://user-images.githubusercontent.com/59323771/86071928-52003600-ba35-11ea-9f1a-428cde6c7fd2.png)

the dialogue option still shows.

![image](https://user-images.githubusercontent.com/59323771/86071896-40b72980-ba35-11ea-88ab-5766a9ca07be.png)

**Comment by insthync** [comment]
How about `Bryan 5`, is it a quest dialog ?

**Comment by insthync** [comment]
Ahh, I get it, I will fix it.

**Comment by insthync** [comment]
This was fixed some time ago.
