### ISSUE TITLE
[Bug] Enabling TextMeshPro throws error in GenericUtils.cs (with fix)

### ISSUE THREAD

**Issue by Fashtas** [suriyun-production/mmorpg-kit-docs#512]
Every time I do an update of the Kit I receive the following error due to a missing "using TMPro" in GenericUtils.cs

```c#
Assets\UnityMultiplayerARPG\Core\Scripts\Utils\GenericUtils.cs(12,25): error CS0246: The type or namespace name 'TMP_InputField' could not be found (are you missing a using directive or an assembly reference?)
```

Fix is to add to following to the top of the Assets\UnityMultiplayerARPG\Core\Scripts\Utils\GenericUtils.cs file in using clauses:

```c#
#if USE_TEXT_MESH_PRO
using TMPro;
#endif
```

Confirmed still in 1.56b

**Comment by insthync** [comment]
Thank you, I will fix it.
