### ISSUE TITLE
[Bug] Monster spawner

### ISSUE THREAD

**Issue by ArpanShingala** [suriyun-production/mmorpg-kit-docs#513]
Facing issues with monsters where monster spawner spawns the monster incorrectly which causes an issue with Navmesh.

- Monster spawner gizmo looks way above the terrain
- Checked Navmesh and everything looks baked

![SS2](https://user-images.githubusercontent.com/24749279/86520306-9d309500-bdf7-11ea-847f-2ca47dc75fbf.png)
![SS1](https://user-images.githubusercontent.com/24749279/86520309-a1f54900-bdf7-11ea-9af0-d3c412dd7537.png)

**Comment by DimasjkTV** [comment]
+ Such errors sometimes occur when summoned creatures teleport to the character.
