### ISSUE TITLE
URP

### ISSUE THREAD

**Issue by Brodter** [suriyun-production/mmorpg-kit-docs#516]
How do I make urp with this kit? When I press play the screen is blue.
https://ibb.co/SxCTXRj

**Comment by Gui205** [comment]
I use URP and i got any problem, maybe just reimport all and update all the material with URP Shader

**Comment by insthync** [comment]
Try look at this https://github.com/suriyun-production/mmorpg-kit-docs/issues/308 it may solve your problem.

**Comment by insthync** [comment]
No answer for long time, I will close it.
