### ISSUE TITLE
Input manager

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#517]
Hi,
Since the basic Unity Input Manager is now deprecated. Is there any custom input manager available or planned for the MMORPG Kit ?

Or do we have to rewrite it all ourselves ?

There is no way to easily make a custom setting menu to rebind the keys especially sicne half the keys are in the input manager and the other half is hard coded.

**Comment by insthync** [comment]
I will implement new input system in future version, I also might change minimum Unity version for the package to 2019.4.2f1 for faster development.

**Comment by sawcisson** [comment]
Allright, is there any ETA on this ?

**Comment by insthync** [comment]
Next month :)
