### ISSUE TITLE
Walking Attack Problem

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#518]
hello, how can i cancel the attack while moving joystick
attack duration I added enough.
netfuncattack() function add stopmove() work point click but not joystick.

**Comment by insthync** [comment]
You want character to stop moving while attacking, right?

**Comment by fedas61** [comment]
yes

**Comment by insthync** [comment]
Try set `Move Speed Rate While Attacking` in Item setting to 0

**Comment by fedas61** [comment]
ty.Solved.
