### ISSUE TITLE
BuildingEntity -> on build function?

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#519]
Is there any "onBuild" function or similar for buildingentities ?
i used OnSetup() but it is gonna execute the same code everytime it spawns when the game save is loaded.
i want it to be only done when the building is built and not everytime the object is loaded on the map.

**Comment by insthync** [comment]
I will add onBuildingConstruct (UnityEvent) to BuildingEntity in next version

**Comment by insthync** [comment]
Added in version  1.57
