### ISSUE TITLE
Resource Script Issues

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#520]
![Test](https://user-images.githubusercontent.com/57778639/87361333-fa37f380-c539-11ea-851c-05712272e843.PNG)
![test2](https://user-images.githubusercontent.com/57778639/87361337-fefca780-c539-11ea-8584-39fb1b87a22b.PNG)

huge FPS drop if you noticed im not really spawning that many objects and they should instantiate and be removed outside of your net range anyway. In the past i tested this and it worked like a charm no idea whats going on here now.

As you can see in the screen shot i extended the range of the spawn. and tripled its output.

**Comment by insthync** [comment]
Not sure that is because of gizmos or not, I've made it draw bound gizmos (see in BaseGameEntity → OnDrawGizmos), I will move it to OnDrawGizmosSelected in next version

**Comment by Fallen01** [comment]
Ok, thank you for taking the time to look into it.

**Comment by Fallen01** [comment]
Heres another example. Its extreme but I wanted to see what happened. 
![test3](https://user-images.githubusercontent.com/57778639/87445063-96f3a300-c5c5-11ea-84f1-7007090b923c.PNG)
Now if these objects only spawn in range of the player why would this keep the client from even loading?

**Comment by Fallen01** [comment]
This is a bit extreme, but it was just an experiment.

**Comment by sawcisson** [comment]
I'm having lags since the last updates aswell + an other harvestable bug i posted on GIT

**Comment by Fallen01** [comment]
Good to know its not just me.

**Comment by insthync** [comment]
Not sure it was fixed in 1.58 ?
