### ISSUE TITLE
2D Click on monster work only clicking in head. not work clicking in body monster.

### ISSUE THREAD

**Issue by applive3** [suriyun-production/mmorpg-kit-docs#521]
![gif](https://user-images.githubusercontent.com/40783613/87429931-dc5ea300-c5ba-11ea-8ae5-3cd103fa5b61.gif)

Could you tell me how I can correct this would be the box colider or another component of the monster entity that must be corrected?

**Comment by insthync** [comment]
I want to see your colliders, did you set it cover your character ?

**Comment by applive3** [comment]
![QUETION BODY](https://user-images.githubusercontent.com/40783613/87568506-22d7fe80-c69c-11ea-85d1-47a3fbcdcd5e.png)
This monster entity

**Comment by insthync** [comment]
There is any colliders in its children?

**Comment by applive3** [comment]
No

**Comment by insthync** [comment]
Your setting look good, but I still not sure is it cover your character or not.

You can notice it by green rectangle around the character

![Screenshot_257](https://user-images.githubusercontent.com/2697550/88500335-978f2f00-cff2-11ea-98fa-a9e2d61590c2.png)
