### ISSUE TITLE
Navmesh for key movement

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#522]
Before the latest updates there was an option to use navmesh for key movement.
Is it totaly gone ?

**Comment by insthync** [comment]
Yes, it's gone from RigidbodyEntityMovement because I don't think it is required to use it.

**Comment by sawcisson** [comment]
Was kinda useful in my situation :/ well i guess i'll get back to the legacy one.
Thanks for the fast answer.

BTW i sent you emails but never had any answer.

**Comment by insthync** [comment]
Did you send the video to the email?

**Comment by insthync** [comment]
No answer, I will close it.

**Comment by sawcisson** [comment]
Yes i did send the video by email.

**Comment by insthync** [comment]
Send it to ittipon.bay@gmail.com
