### ISSUE TITLE
Simple & Advanced animator controller

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#523]
It seems that i don't have any difference between using the simple or the advance animator controller.
Why is that ? is it related to something with the player controller ?
Any documentation on it ?

**Comment by moepi2k** [comment]
advanced is for shooterontroller. you have animation for strafe backwards and so on

**Comment by insthync** [comment]
In https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/108-animator-character-model

```
- **Controller Type** there are 3 choices: `Simple` it will use pre-made Animator Controller which has 1 layer and made for non shooter-games, `Advance` it will use pre-made Animator Controller which have 2 layers and made for shooter-games which can attack while moving and `Custom` which use custom Animator Controller
```
