### ISSUE TITLE
Build compiled version crashes while in Unity editor works fine. Singleton in line "if (GameInstance.Singleton.DimensionType == DimensionType.Dimension3D))" in GameplayUtils is null (ie initalized)

### ISSUE THREAD

**Issue by Skitosh** [suriyun-production/mmorpg-kit-docs#525]
Summary of problem.

In unity editor code runs successfully. Loads 00Init, 01Home, Map00_00_00_VolcanoTown (First scene of game) while build version fails.

Build\Compiled Version (Running executable as administrator)
Same problem occurs with most basic build, debug profiles turned on or visual studio solution turned on. (see image for build options used 
![01_01_BuildOptions](https://user-images.githubusercontent.com/66407302/87610955-27f38700-c74a-11ea-9ae3-688e48f162d6.png)

Executing build from executable gets the following errors
![image](https://user-images.githubusercontent.com/66407302/87611132-90daff00-c74a-11ea-8907-59d3f80dfd09.png)

Attaching the visual studio as the Managed Debugger reveals the following. 
Steps used to identify the issue.
1) Execute program
![image](https://user-images.githubusercontent.com/66407302/87611460-781f1900-c74b-11ea-95d0-7743dc5e4004.png)
2) Wait for attach debugger popup
![image](https://user-images.githubusercontent.com/66407302/87611507-971dab00-c74b-11ea-9d0a-48ec9e4fdd39.png)
3) Go to visual studio project and attach visual studio
![image](https://user-images.githubusercontent.com/66407302/87611571-b7e60080-c74b-11ea-81c9-9a34212f6d84.png)
![image](https://user-images.githubusercontent.com/66407302/87611790-45c1eb80-c74c-11ea-8c8c-dbdd2999aeb0.png)

4) Click "ok" on the popup from the executable. Breakpoint reveals that the singelton (GameplayUtils: line "if (GameInstance.Singleton.DimensionType == DimensionType.Dimension3D)") has not been initialized.
![image](https://user-images.githubusercontent.com/66407302/87611889-80c41f00-c74c-11ea-9240-373c6d54ffb4.png)

5) Additionally I put a breakpoint in GameInstance.Awake on line "Singelton = this".
In the build version "Singelton = this" is not being hit before GameplayUtils hence the null.
In the unity editor "Singelton = this" is being hit before GameplayUtils.

Any thoughts on how to resolve this issue ?

Thank you for your help
Kind regards
Skitosh

**Comment by insthync** [comment]
You must set 00Init scene as a first scene in build to initialize game instance when the game start.

**Comment by Skitosh** [comment]
Thank you. A second set of eyes always helps.

**Comment by Skitosh** [comment]
Thank you very much, a second set of eyes helps.
Keep up the great work

Pawel (akk Skitosh).
