### ISSUE TITLE
[Question] How to add sockets of equipments from script? (with a chance based on attribute amount)

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#528]
This is not an issue, just I'm looking for a help..

I'm now trying to add a feature to add new sockets when crafting equipments item with a chance which is based on specific attribute amount. 
For example, if a player's Intelligent amount exceed 200, It will give a chance to add a new(or additional) socket when craft equipments item.

What I'm trying now is add this fucntion to "Create()" function in the CharacterItem.cs.
I have two problems..,
1. how to check player's Inteligent amount exceeds 200 or not
2. how to add new socket.

If you can give me any clue or hint, it will help me a lot.

Thanks in advance.

////For example I want to add **BOLD code** as below
    public static CharacterItem Create(int dataId, short level = 1, short amount = 1)
    {
        CharacterItem newItem = new CharacterItem();
        newItem.id = GenericUtils.GetUniqueId();
        newItem.dataId = dataId;
        newItem.level = level;
        newItem.amount = amount;
        newItem.durability = 0f;
        newItem.exp = 0;
        newItem.lockRemainsDuration = 0f;
        newItem.ammo = 0;
        BaseItem tempItem = null;
        if (GameInstance.Items.TryGetValue(dataId, out tempItem) && tempItem is IEquipmentItem)
        {
            newItem.durability = (tempItem as IEquipmentItem).MaxDurability;
            newItem.lockRemainsDuration = tempItem.LockDuration;
            **if (PlayerCharacter.attribute.intelligent.amount > 200)
                    newItem.sockets = tempItem.sockets + 1;**
        }
        return newItem;
    }

**Comment by insthync** [comment]
You can check player's Inteligent amount exceeds 200 or not by calling 
```
            Attribute attribute;
            if (GameInstance.Attributes.TryGetValue("Intelligent".GenerateHashId(), out attribute) &&
                this.GetCaches().Attributes[attribute] > 200)
            {

            }
```

About socket, you  means  `Item.cs` -> `maxSocket`?

**Comment by dglee2592** [comment]
Oh Thanks!!!
and Yes, Item.cs -> maxSocket

**Comment by insthync** [comment]
I will find out the quite easy solution

**Comment by dglee2592** [comment]
Thank you Thank you so much.. you are so kind...

**Comment by insthync** [comment]
Next version I will add overrideable function to `BaseGameplayRule`. Then you will have to override that function to change max sockets.

**Comment by dglee2592** [comment]
Thank you so much!!
