### ISSUE TITLE
Doubling items situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#529]
Single player mobile
Based on feedback from my users, a very rare bug was noticed. During the transfer of items from storage to inventory, items are doubled.
There was also the same bug with sockets. When we insert a stone into the socket and the item is duplicated.

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by insthync** [comment]
I am not sure, it's just UI bug or item will be duplicated permanantly?

**Comment by DimasjkTV** [comment]
> I am not sure, it's just UI bug or item will be duplicated permanantly?

permanantly

**Comment by insthync** [comment]
I try to reproduce the bug but it's not occur yet.

**Comment by DimasjkTV** [comment]
> I try to reproduce the bug but it's not occur yet.

I only managed to duplicate items once in all the time when I inserted stones into sockets. This is a very rare bug and it just can't be reproduced. Only a few of my users had this bug.

**Comment by DimasjkTV** [comment]
I just wrote this. I can't even imagine how this can be fixed =)

**Comment by DimasjkTV** [comment]
Maybe when more finished projects appear, we can collect more information on this matter.

**Comment by insthync** [comment]
As I investigate my codes, I think it can occur when decrease gem item and remove the gem item from inventory then enhancing item index will changes then when update enhancing item it will update on wrong index.

**Comment by Koodetat** [comment]
I saw this bug so I will make a video to reproduce it, it's when we drag an object from the inventory (socket enhancer) onto a socket enhancer in the socket UI if I remember correctly.

**Comment by DimasjkTV** [comment]
> As I investigate my codes (When enhance item), I think it can occur when decrease gem item and remove the gem item from inventory then enhancing item index will changes then when update enhancing item it will update on wrong index.
> 
> For move item from storage to inventory it seems not going to duplicate.

I got a feedback. Player opened the stash and inventory at the same time. Equip +15 weapon from inventory and received a copy of this weapon.

**Comment by insthync** [comment]
I've fixed it. If it's still occurring, tell me later.
