### ISSUE TITLE
There is a racing problem in version 1.46

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#53]
There is a racing problem in version 1.46. When I add the race system, the characters freeze in place and the inventory does not work in the mobile version

**Comment by insthync** [comment]
About inventory does not work in mobile it is because of race system ?

**Comment by kazuden** [comment]
> About "inventory does not work in mobile", it is because of race system ?

I made a video about the problem. This is a general problem. everyone has this problem.
https://youtu.be/cd4Waa5cOms

**Comment by insthync** [comment]
Haha, I found how to fix the problem, in `UINonEquipItems.cs` line 113 changes it from
```
if (nonEquipItem.GetItem() == null) continue;
```
to
```
if (nonEquipItem.GetItem() == null)
{
    ++counter;
    continue;
}
```

**Comment by insthync** [comment]
About character freeze it's only your new character not the demo right ?

**Comment by kazuden** [comment]
all character problem. did the video above watch. there is a video about the problem above

**Comment by kazuden** [comment]
> About character freeze it's only your new character not the demo right ?

all character problem. did the video above watch. there is a video about the problem above

**Comment by insthync** [comment]
I don't have character movement issues *-*

**Comment by kazuden** [comment]
> I don't have character movement issues O_O

mobile is also fine. other platform has problem

**Comment by insthync** [comment]
Yes, I tried other platform, not sure it has an error logs in console ?

**Comment by kazuden** [comment]
> Yes, I tried other platform, not sure it has an error logs in console ?

https://gyazo.com/e2cd82955f37e2af4b49f67b3181d608

**Comment by insthync** [comment]
Please selection that error message and copy all text

![Screenshot_29](https://user-images.githubusercontent.com/2697550/60994383-9dc85400-a37a-11e9-9f66-c85d4e5a352c.png)

**Comment by kazuden** [comment]
> Please selection that error message and copy all text
> 
> ![Screenshot_29](https://user-images.githubusercontent.com/2697550/60994383-9dc85400-a37a-11e9-9f66-c85d4e5a352c.png)

https://gyazo.com/926ac989c935e7772ea81915ff32ff4b

https://gyazo.com/5ef61b34d04350080f06e625e1807f05


ArgumentException: Input Button ExitVehicle is not setup.
 To change the input settings use: Edit -> Settings -> Input
InputManager.GetButtonDown (System.String name) (at Assets/UnityMultiplayerARPG/Core/CameraAndInput/Scripts/Input/InputManager.cs:68)
MultiplayerARPG.PlayerCharacterController.UpdateInput () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Default/PlayerCharacterController_Inputs.cs:94)
MultiplayerARPG.PlayerCharacterController.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/Default/PlayerCharacterController.cs:173)

**Comment by insthync** [comment]
Ahh, I see, go to the GameInstance → Find for `Input Setting Manager` component then add `ExitVehicle` key

![Screenshot_30](https://user-images.githubusercontent.com/2697550/61002865-b80b2d80-a38c-11e9-81d2-0b79104054bb.png)

**Comment by kazuden** [comment]
> Ahh, I see, go to the GameInstance → Find for `Input Setting Manager` component then add `ExitVehicle` key
> 
> ![Screenshot_30](https://user-images.githubusercontent.com/2697550/61002865-b80b2d80-a38c-11e9-81d2-0b79104054bb.png)

problem improved 👍  👯‍♂  everyone will face this problem. :)   O_o

**Comment by insthync** [comment]
So it's fixed the issues?, I will update the package later :P

**Comment by kazuden** [comment]
problem fixed thanks.
