### ISSUE TITLE
Harvestables bug - Multiplying on respawn

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#530]
I have a small problem with harvestables now multiplying on respawn.

https://youtu.be/1q7rQ03lOU8

**Comment by insthync** [comment]
It is harvestable entity which you placed on scene or spawned by spawner ?

**Comment by sawcisson** [comment]
Spawned by spawner, but i found the problem it was doing Die&Respawn multiple time instead of once per harvestable.
