### ISSUE TITLE
[Bug]New open Character controller crouch collider issue

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#535]
on the new open character controller. when player crouch the collider only adjust for hitbox but not for detecting other collider so you are not able to crouch under obstacles. it detect same as when you stay

**Comment by insthync** [comment]
In 1.58,
```
- Make `MovementColliderAdjustment` adjust `OpenCharacterController`'s capsule but it can't change direction.
```
