### ISSUE TITLE
[Suggestion]Building Storage placable in Scene

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#536]
Its not possible to place Building Storage Chest in Scene so that player can put items in it. when someone try to open it he will get the message "Cannot access storage".

would be great to make this stuff placeable in scene to make world more lively and interactable

**Comment by sawcisson** [comment]
Would be a great addition

**Comment by Hellwood** [comment]
This is huge, To find a locker with loot in it. Or to store stuff in the locker after finding it. (Both)  Games like Observation and 
The Long Dark have it. In today's Survival games it a big deal. I would love to see this.

**Comment by insthync** [comment]
I am thinking about when it destroyed, it should save destroy state or not.

**Comment by moepi2k** [comment]
also a good idea is when storage is destroyed that items inside of it fall on floor.
