### ISSUE TITLE
CharacterAlignOnGround component jitter

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#538]
Thank you for adding this component, its a bit buggy. when i put this on alpaca 2 and set rootbone to field and walk to a slope. the whole mount with player object begin to jitter and is glitchy and slides down slopes. camera also shaking then

-> It works great when i attach this script on enemies.

**Comment by insthync** [comment]
Try the 1.57b update.

**Comment by moepi2k** [comment]
Works, thank you
