### ISSUE TITLE
Npc Shopitems issue

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#539]
1) The color of shop items on npcs are bugged. weapon and armor name are white. (i set a name, when i click on it i can see it in shopmenu which more darker white color) type "potion and junk" works. i dont tested all types only noticed  that i have issue for armor and weapons now.

it seems its randomly. on your default vendor armor and weapons works. i tested now armor001 on mine and its name is also white.

2) on shop items there is no item descrpition when click on it. so player cant see what exactly they buy. would be good if they can click on it to see description like in inventory

![name color](https://user-images.githubusercontent.com/2422714/88274523-255dd800-ccdc-11ea-9854-b285b7f770fd.png)

edit: i checked in editor. the items where name are white its showed as this: "<color=#FFFFFF>Warlock Shoulder< / color >"

**Comment by insthync** [comment]
Its title color was set in `ItemRefine` game data, and it was set to white so it's white :p

**Comment by moepi2k** [comment]
oops, never saw that before xD thanks.
what about point 2? item description on shop items?

**Comment by DimasjkTV** [comment]
> oops, never saw that before xD thanks.
> what about point 2? item description on shop items?

u can do description without additional code

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/88375641-9bc60d00-cda4-11ea-9fab-6912cd2a83a3.png)

**Comment by moepi2k** [comment]
do you just copy paste it from normal item? why is this not standard? :)

**Comment by DimasjkTV** [comment]
u just copy TextItemTitle and drag and drop to Ui text description.
