### ISSUE TITLE
Interface input screen nonsense

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#54]
Hello there. UICharacterList screen appears as the first screen when creating characters.this is ridiculous.The person who entered the game will already enter to create the character. UICharacterCreate needs to face first.there is no button to create character first in any game.the player enters the game and displays the first character screen

https://gyazo.com/12c7b8ecdb161ea413a02a03f7457f70

https://gyazo.com/e2a3d0904bc247635ce3f4ecc08306ff

The first screen that should appear should be as follows:

https://gyazo.com/1718603376269a478a7a4eb7da2ff0f4

**Comment by insthync** [comment]
I don't get what you want to tell me, You want it enter to character creation screen when there is no character ?

**Comment by kazuden** [comment]
> I don't get what you want to tell me, You want it enter to character creation screen when there is no character ?

I'm new to the game. I entered the game. I came across this screen:
https://gyazo.com/e2a3d0904bc247635ce3f4ecc08306ff

This should be the screen. I need to see this screen first:
https://gyazo.com/1718603376269a478a7a4eb7da2ff0f4

**Comment by insthync** [comment]
Okay

**Comment by kazuden** [comment]
https://www.youtube.com/watch?v=xVnrq-lV0fs&t=69s
Follow after 0.45

**Comment by kazuden** [comment]
> I don't get what you want to tell me, You want it enter to character creation screen when there is no character ?

https://www.youtube.com/watch?v=xVnrq-lV0fs&t=69s
Follow after 0.45
