### ISSUE TITLE
Text Wrapper Textmesh pro

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#542]
hello how to work text wrapper textmesh pro ?

**Comment by insthync** [comment]
You have to enter `USE_TEXT_MESH_PRO` into `Scripting Define Symbols` settings
![Screenshot_261](https://user-images.githubusercontent.com/2697550/88943759-17005500-d2b6-11ea-82be-a73db1fb533f.png)
