### ISSUE TITLE
Saving login details in PlayerPrefs

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#545]
In MMO mode, is it possible to add an option to save login details (username and password) in playerprefs? It's pretty boring to write them every time you connect, especially on mobile.

**Comment by insthync** [comment]
Okay, I will add it.

**Comment by Koodetat** [comment]
Awesome !  thank you

**Comment by insthync** [comment]
I've added toggles to UIMmoLogin in version 1.58
```
- Add `toggleRememberUsername` to `UIMmoLogin`, use it to remember username to login later.
- Add `toggleAutoLogin` to `UIMmoLogin`, use it to remember username and password to login automatically later.
```
