### ISSUE TITLE
Visability checker on trees in 2d seems to cause a large drop in FPS

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#547]
Beluci, originally reported this issue extreme lag in 2d on discord and after having him run several experiments we got it down to the visability checker. With no trees at all fps takes a pretty heavy hit from 90 fps to 70 fps for example. Ive had issues with 3d myself with the resource script recently youve done some work on that because of my reports. Thanks for that, Ive been sick recently so havent checked it out yet. However maybe this is part of that issue to, but even if its not its def happening in 2d. Thanks for your time.

**Comment by Fallen01** [comment]
Im told by Beluci taking the issue further that the tile map collider is acting strange.

![collission](https://user-images.githubusercontent.com/57778639/89114477-ff0e0a00-d44a-11ea-93c2-2c2454cbd3e3.png)

**Comment by Heronbeluci** [comment]
if you change the cell size of the grid the collision just breaks, when you walk the screenshot fact happens...

**Comment by insthync** [comment]
I will remake the object proximity system, won't use Unity's physics, may use https://github.com/bartofzo/SuperGrid2D.

**Comment by insthync** [comment]
I've added new visible checker component in 1.58, try it.
```
- Add visible checker which implemented by [`SuperGrid2D`](https://github.com/bartofzo/SuperGrid2D) developer can use it instead of `LiteNetLibVisibleChecker` to improve performance.
```
