### ISSUE TITLE
[Potantial Bug] On Quest Ongoing

### ISSUE THREAD

**Issue by ZMZS** [suriyun-production/mmorpg-kit-docs#548]
Recently i spoted a wierd quest bug thats happen sometimes.
The bug is happening on this scenario.
-You recive a quest from npc
-Your quest sub task is  killing 5 monster
-You start to kill monster
Here comes when you check if your quest counter is changing nothing happens not only the counter even if you kill 5 monster the quest will not work. Like i say thats happen sometimes i didnt checked from a clean project but this weekend i will try and let you know.

Have a nice day or night

**Comment by insthync** [comment]
I will check it.

**Comment by ZMZS** [comment]
I tryed on a clean build 10 times with the test scene quest nothing happen.

**Comment by insthync** [comment]
As I try, it's working correctly, accept quest / kill monster / NPC notify are working correctly.

**Comment by ZMZS** [comment]
Well i think its maybe due something on my project thank you again for looking

Have a great week
