### ISSUE TITLE
[Suggestion] Npc Sell Item Dialog

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#549]
I wrote in the title
thanks.

**Comment by insthync** [comment]
It already have the sell item dialog, isn't it?

![Screenshot_10](https://user-images.githubusercontent.com/2697550/89761618-f8e9ee80-db18-11ea-9b3c-fb9a07f765f9.png)

**Comment by fedas61** [comment]
Click item Info Dialog
shop type

**Comment by insthync** [comment]
Added in 1.58, but I didn't made the demo yet, you'll see `uiSellItemDialog` field in `UINpcDialog` component
