### ISSUE TITLE
[Question] some questions.

### ISSUE THREAD

**Issue by Minjae-K** [suriyun-production/mmorpg-kit-docs#552]
Hello, There are some functions that I want to make while using MMORPG KIT, but I have some questions because I lack coding skills.

1. how to move the Playercharacter using the code. 
For example, I want to make a new skill type and put the movement into the ApllySkill.

2. how to take other actions during the attack. 
For example, if a player uses a skill during an attack, the attack is canceled and the skill is used.

3. I'd like to know how to create a combo attack. For example, the attack animations 1,2,3 are played in order rather than random clip playback, and if the attack does not take a certain amount of time, it returns to number 1.

Or can I know how to contact you directly if paid customization of the engine is possible for the above three Questions?

**Comment by Minjae-K** [comment]
> Hello, There are some functions that I want to make while using MMORPG KIT, but I have some questions because I lack coding skills.
> 
> 1. how to move the Playercharacter using the code.
>    For example, I want to make a new skill type and put the movement into the ApllySkill.
> 2. how to take other actions during the attack.
>    For example, if a player uses a skill during an attack, the attack is canceled and the skill is used.
> 3. I'd like to know how to create a combo attack. For example, the attack animations 1,2,3 are played in order rather than random clip playback, and if the attack does not take a certain amount of time, it returns to number 1.
> 
> Or can I know how to contact you directly if paid customization of the engine is possible for the above three Questions?

**Comment by insthync** [comment]
1. Create class which extends from `BaseSkill`. Then in `ApplySkill` function, you may teleport your character to `AimPosition` by calling teleport function from character entity, for example `skillUser.Teleport(aimPosition)`
2. Have to change codes to make it not check only is attacking or not, for now there is `IsAttackingOrUsingSkill` field, I may separate it to `IsAttacking` and `UsingSkill` and also change condition in `CanAttack()` and `CanUseSkill()` to allow player to use skill while attacking. Other than that you should create cancel token source for attack action, then cancel attack action when use skill.
3. Have to change codes in `AnimatorCharacterModel` or `AnimationCharacterModel` to not random animation in `GetRandomRightHandAttackAnimation` and `GetRandomLeftHandAttackAnimation` functions
