### ISSUE TITLE
[Bug]Use items in shortcut

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#553]
there is an issue for shortcut items. if you have for example two stacks from same items like 2x5 Health potion and you put one stack in shortcut. when they are all consumed, the shortcut wont work for the other stack. this happen for all kind of items in shortcut. its a bit annoying to replace items every used. when you have consumebles that are only 1er stacks for example. shortcut should save ID of the specific itemtype.

another issue is. when we take the example above and player used all 5 health potions in shortcut. after warping map the shortcut item is gone

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.58

**Comment by moepi2k** [comment]
the bug with multile stacks is still there, if you have two stacks of same items and one is consume, shortcut item will destroy instead of remains as copie for using that kind of item

**Comment by insthync** [comment]
https://youtu.be/pS1VgxdL8wA

Is this what you want?

**Comment by moepi2k** [comment]
exactly, when u drag the item to quickslot then its just a copie of that kind of item, and then it doenst matter how many stucks you have in your inventory it just consume one after other. and when all are consumed the quickslot copy should remain. so its easier to organize your inventory. thats how it works in most games i know :)
