### ISSUE TITLE
[Suggestion]Warping and Startposition need rotation for check facing forward

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#557]
there is no option for rotation when using a portal or start position, where you can set facing direction after warping. so when you enter a door it can be that in next map you look in false direction.

this integration would make sense.

thank you

**Comment by insthync** [comment]
I will also save rotation when login :P

**Comment by moepi2k** [comment]
not saving rotation. i mean when you for example use warp portals for entering a house. you need to set rotation for facing after warping. right now its always same. so it could be you enter a door and in the house after warping you look at door side.

i hope you understanf what i mean :D

**Comment by insthync** [comment]
Added to 1.58
