### ISSUE TITLE
Sound and visual inverted

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#558]
For some reason in LAN the sound & character are inverted but the controller is on the right character.

Basically Player 1 host and plays, he see his own character (Player camera on 2d texture) in the inventory, hear his own sound etc...

As soon as Player 2 join the game now Player 1 see player 2 in inventory (Player camera on 2d texture) and hear only Player 2 sound.
And the Player 2 is experiencing the same issue on his side.

Do you have any idea of where this might come from ? I tried to understand or find it but with no luck. i'm not even sure of where to look for it.

**Comment by insthync** [comment]
![Screenshot_29](https://user-images.githubusercontent.com/2697550/90988800-dac3ca00-e5bf-11ea-9786-06fc1814f2dc.png)

Try set `Owner Objects` and `Non Owner Objects`

The `Owner Objects` will be activated if the character is character which player controlling, `Non Owner Objects` for other
