### ISSUE TITLE
[Bug]WarpPortal

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#560]
when add Warpportal directly to scene and uncheck ->

Warp Immediately When Enter, set this to TRUE to make player’s character warp immediately when trigger it

player wont warp when pressing "E"

**Comment by moepi2k** [comment]
great  :) maybe this addition make also sense. find no solution to set look direction after warping

**Comment by insthync** [comment]
Fixed in 1.58
