### ISSUE TITLE
Seatindex NetDataReader

### ISSUE THREAD

**Issue by Zodly** [suriyun-production/mmorpg-kit-docs#561]
I'm not entirely sure if this is an error on my part or the kits.

So I have it set up that the server on boot up loads in numerous havestable entities randomly. It registers them and instantiates. Then on the client it requests them and it networkspawns them. The harvestables come in proper. They have their hp and are "attackable", but I receive an error that spams regarding outofrangeofindex on seatIndex for PassengerVehicle. I did some debugging on it and it starts out spamming 0, then begins randomly throwing the error and then I've had it randomly throw random numbers out and then index error again continually.

Is there a networkspawn limit or is this some other issue at play.

**Comment by insthync** [comment]
There is any vehicle or character is riding vehicle or not ?

**Comment by Zodly** [comment]
No vehicles or mounts present at all. 
Matter of a fact I haven't even messed with that system as of yet, I have 0 in the GameDatabase2D.

**Comment by Zodly** [comment]
This may have been my error and you can speak to that more.

My chunks were originally set up as BaseGameEntities as I was trying to get my systems fully working so they were actually spawning on the client via NetworkSpawn because originally I was trying to do sync values and all that fun stuff with them.  So I was Registering the Prefab then NetworkSpawning them when I needed them on the client, destroying when I didnt.  This issue didn't show up when I had just that, the mesh ground.  Then I add the foliage that is spawned via the server (NetworkSpawn) and that's when this issue occurred.

So to test again, I removed the foliage.  No error.
Readded the foliage.  Error.

Changed how I spawned my chunks, removed client side NetworkSpawn and instead just instantiated them and.. No Error..  

So is this a situation where I misunderstood functions or did is this some underlying issue?

**Comment by Zodly** [comment]
I believe the error I was receiving was more human error then kit error. Closing.
