### ISSUE TITLE
[Bug]Survival Building Door

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#565]
i dont know if its a fault side of mine, but when i place a door lock it then use door the window with enter code appears. and im only able to insert 2 charts instead of 6 and throw this console error:

`NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.BasePlayerCharacterEntity.NetFuncOpenDoor (PackedUInt objectId, System.String password) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity_NetworkResponse.cs:793)
LiteNetLibManager.LiteNetLibFunction`2[T1,T2].HookCallback () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:260)
LiteNetLibManager.LiteNetLibFunction.SendCall (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Int64 targetConnectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:104)
LiteNetLibManager.LiteNetLibFunction.Call (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameterValues) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:132)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction (System.String id, LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameters) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:602)
LiteNetLibManager.LiteNetLibBehaviour.CallNetFunction[T1,T2] (LiteNetLibManager.NetFunctionDelegate`2[T1,T2] func, LiteNetLibManager.FunctionReceivers receivers, T1 param1, T2 param2) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:496)
MultiplayerARPG.BasePlayerCharacterEntity.RequestOpenDoor (System.UInt32 objectId, System.String password) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity_NetworkRequest.cs:541)
MultiplayerARPG.BasePlayerCharacterController+<>c__DisplayClass64_0.<ActivateBuilding>b__0 (System.String password) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterControllerSystems/BasePlayerCharacterController.cs:255)
UIInputDialog.OnClickConfirm () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UIInputDialog.cs:205)
UnityEngine.Events.InvokableCall.Invoke () (at <3dc54541a2574ac7826a004a212a4332>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <3dc54541a2574ac7826a004a212a4332>:0)
UnityEngine.UI.Button.Press () (at C:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)`

**Comment by insthync** [comment]
Is this occuring while you testing singleplayer game?

**Comment by moepi2k** [comment]
i got this error in singleplayer and mmo. but not everytime. dont know exactly when it happen.
