### ISSUE TITLE
Server authorative movement bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#567]
The female character is movement secured by default. and she keeps spinning around.
The male character is not secure and doesnt spin.

https://imgur.com/Cn2q2Nd 

here is a video of it

The Male Character
![image](https://user-images.githubusercontent.com/7702658/91658483-cf453700-eac8-11ea-8c24-b202f2362189.png)

and Female

![image](https://user-images.githubusercontent.com/7702658/91658487-db30f900-eac8-11ea-97c6-f4502137fc84.png)

**Comment by Callepo** [comment]
it appears to be a controller issue
https://imgur.com/Kguq7LD

**Comment by Callepo** [comment]
@insthync

**Comment by moepi2k** [comment]
Ya hope there come soon the new client side prediction and lag compensation mechanic too, server auth movement is useless atm and without you cant release a game.....

**Comment by insthync** [comment]
Okay, I will changes rigidbody movement after next update (which is uploading)

**Comment by Callepo** [comment]
@insthync https://imgur.com/Mb3Cm2x 

there is a slope issue too , or my settings are wrong.. but jumping u move from ur spot.. even on small slopes which is very annoying

**Comment by moepi2k** [comment]
yes thats the issue i mentioned. u slide after jump also on minor slopes. slide would be okey when slope are great like >45degree
but on small slopes its annoying

**Comment by moepi2k** [comment]
https://github.com/suriyun-production/mmorpg-kit-docs/issues/460

**Comment by Callepo** [comment]
@insthync i didnt wanna make new Report
https://imgur.com/xcnHhvf

Character still slide away when jump 
is this a slope setting thing?

**Comment by insthync** [comment]
I see, I'm going to find out how to fix it after finish rework for entity movement which will have only server authoritative and will predict movement at client.

**Comment by Callepo** [comment]
ty
