### ISSUE TITLE
[Bug] Mmo side don't display back hotkeys or buffs ui 

### ISSUE THREAD

**Issue by Xentar** [suriyun-production/mmorpg-kit-docs#568]
Hey, Suriyun

Found this 2 issues. On discord was mentioned too: "After warping or relog. quickslot list is always empty. then you need to readd something to make all visible again"

So:
If you assign skills or items and exit/warp the character, when you came back the skills/items don't show on the hotkeys ui, but they are there because you can activate them.
If you used a buff, its saved and applied (db too), but if you log back the buff icon its no displayed, just the effect stay.

Reason:
Figured out that the problem with the shortcuts is in UIOwningHotkeys.cs that is no calling the UpdateData(), or is calling earlier so don't fetch the data.
About the buffs, still don't search, but my guess is that is something similar.

Edit: The buff icon issue was... different. the icon is there, with the graphic applied, etc. but don't show. Sound like a sorting thing... i fixed it changing the "Generate" on UIList:
"ui = Instantiate(uiPrefab, uiContainer);
 //ui.transform.SetParent(uiContainer);"
Still is strange. Just sharing if helps, but no sure if is an editor glich...

Cheers

**Comment by moepi2k** [comment]
Try default canvas. It fixed the issue for me. Maybe you use also n old one

**Comment by Xentar** [comment]
Tryed them all, including the mobile ones just in case, but same issue. Actually i duplicated the default one to build up, but i noticed this issue just in the last version. 1.56 didn't have this issue... or never noticed. Anyway, my current experiment started on the last version, so old assets shouldn't be the reason. But, as always, could be on my side... Just reporting because someone else post it as an issue, so wasn't just me, jejeje. or is 2019.4.8f1 laughting at me.

**Comment by moepi2k** [comment]
it was me that reported it but i removed it as i tested it with default canvas and it solved the issue. tested on 1.57b

**Comment by Xentar** [comment]
Then there must be a side issue on my side that is affecting it. Actually i upgraded my unity to 2019.4.9f1 and now just dissapear the skills but no the items from hotkeys. The buff, same issue, but that change of behavior... is strange.

Well, reported just in case. Lets see if the next version do something.

**Comment by Blunnyn** [comment]
I have the same problem, even with the drop items.
I "pick up" the mushroom from the ground and when I log in again it is no longer

**Comment by insthync** [comment]
I've fixed it, please wait for next update

**Comment by Xentar** [comment]
Thanks a lot, @insthync

**Comment by insthync** [comment]
Fixed in 1.58
