### ISSUE TITLE
Character fall down when harvestable spawn on him

### ISSUE THREAD

**Issue by majausone** [suriyun-production/mmorpg-kit-docs#569]
i realice that if the character are in the exactly position that one harvestable when the harvestable spawn, the character can be traped or fall down, i think that the spawn system must prevent spawn if there are characters in the position.

**Comment by insthync** [comment]
Not sure the character was spawned after harvestable spawn or harvestable spawned after character, In the `HarvestableSpawnArea` class I already try find overlapping entities before spawn harvestable entity.

**Comment by majausone** [comment]
The truth is that I don't know if the asset is intended to use harvestables from the prefab (without using the spaw area), but I have noticed another bug that has to do with this:
If the character spams looking at a harvestable, it gives an error that prevents further:
MissingComponentException: There is no 'Canvas' attached to the "UITargetDamageableHp" game object, but a script is trying to access it.
You probably need to add a Canvas to the game object "UITargetDamageableHp". Or your script needs to check if the component is attached before using it.
MultiplayerARPG.UIBaseGameEntity`1 [T] .UpdateUI () (at Assets / UnityMultiplayerARPG / Core / Scripts / UI / Gameplay / UIBaseGameEntity.cs: 105)

**Comment by majausone** [comment]
I think this is solver now, i test it in a clean project with new version and work
