### ISSUE TITLE
Intantiated Armour issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#570]
When u have 1 type of armour hide another.. the ones that being hidden gets turned off as expected..
but when u unequip the previous armour.. the one that was hidden does not reappear, which is not good.
There is a video Example below

https://imgur.com/9qG1y8V

**Comment by Callepo** [comment]
@insthync

**Comment by insthync** [comment]
How you setup it? as I remember I didn't made setting to hide meshes when equip items except default model which will show when unequip item and hide when equip item.

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/92039767-e6f51780-ed75-11ea-89e9-b0dfe76fe561.png)

lets say my character has hair index 4 on.. 
i equip an item which changes my hair to different one short hair example or bald..
it works
but when i unequip the item.. it doesnt check which one was before i hide it to put it back on
can be any thing.. i can make example my chest swap my chest + legs.. when i unequip the chest .. my chest will change .. but  legs dont..
so it only checks exactly what ur equip or unequiping instead of making the subs reappear too

**Comment by Callepo** [comment]
the way i had to do to make it work was to create an extra slot for hair , set the All_01_Hair parent as a Child to Hair
with All_01_Hair as default model.
And than instantiate a Blank object on Hair.. Which makes it hide Default.. and this work..
cuase when i unequip helm.. the default comes back and u see the hair again.
![image](https://user-images.githubusercontent.com/7702658/92040179-a9dd5500-ed76-11ea-8fbe-28db5727168f.png)

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/92040307-e1e49800-ed76-11ea-8868-e3d0b86568eb.png)
 This basically

**Comment by insthync** [comment]
May I try on your computer?, I've tried on my it work correctly

**Comment by Callepo** [comment]
Sure, Should ill Pm on discord

**Comment by insthync** [comment]
Contact me via my email: ittipon.bay@gmail.com

**Comment by Callepo** [comment]
Email sent

**Comment by Callepo** [comment]
Ty for ur time , Appreciated
