### ISSUE TITLE
Survival Gameplay Rules not working

### ISSUE THREAD

**Issue by thiinkbox** [suriyun-production/mmorpg-kit-docs#571]
Your survival mode stats; Water and Food don't seem to work with your Gameplay Rules. It stays stuck at 100/100
MMORPG v.1.57b
Unity v. 2019.4.5.f1

Thanks!

**Comment by thiinkbox** [comment]
Update: Gameplay Rules is now working but you must update the one located inside the Unity MultiplayerARPG/Demo/GameData 
The file located inside DemoSurvival doesn't work.

**Comment by insthync** [comment]
I was set wrong GameplayRule, that is it. I will update fixed demo later.
![Screenshot_34](https://user-images.githubusercontent.com/2697550/92302106-9c50e680-ef93-11ea-9633-dc3e5807cbbf.png)
