### ISSUE TITLE
[Bug]Jitter Movement big problem for "shootercontroller"

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#572]
Hey Suri,

i noticed a big problem long time ago. i dont mess with em because i always tested from top down or tps mode and with it you cant notice the problem very good.

when you move the player "Shootercontroller", it will not update movement smoothly its like you turn mouse and and player rotate or move step by step behind mouse movemnet. best way to notice is when you rotate player.

now i changed my game to fps and here is the big problem. in fps you notice every single jitter. its unplayable. i created 3 videos to see. in realtime when u player its 100% worser as in the video. the problem is i attached the fps camera to the bone of the player (theres no other way) anyway where you attach camera. the problem is the whole player object is jittering. and so you can notice the jitter in your cam.

video1 : see at hints back when moving. it jitter
https://youtu.be/yzYVN1ngfGo

video2 : look at the edge of the house it jitter when strafe
https://youtu.be/IUNn79w13Ic

video3 : look at the player when moving
https://youtu.be/r5r5Yg3JBg4

when you stay still (idle) and look around it its perfect. only when you begin to move

**Comment by nakedfighter3d** [comment]
Have same issue with every controller. Camera is jittering while following the character.

**Comment by moepi2k** [comment]
i tried this because i think it should fix the jitter:
Improve ShooterPlayerCharacterController: add smooth turn settings turnSpeed, turnSpeedWhileSprinting, turnSpeedWhileCrouching, turnSpeedWileCrawling, turnSpeedWileSwimming and turnSpeedWileDoingAction.

i tried valeus between 0.1 and 100 but no changes.

i think the problem is in the core of rotate and move character.
i made a new video where you can see the jitter on character on a fresh project v1.58
its just set to shooter and fps. when you turn around and look at character you see how delayed in jitter the turn is depent on mouse move. this jitter you have also when move the player. the result is when you walk (best to notice is when strafe) in front of objects. all objects are jittering because the camera is attached on the player


https://www.youtube.com/watch?v=BHPhY2ZpfTs&feature=youtu.be

**Comment by insthync** [comment]
Those config are not intend to fix this issues. I just use it to turn character smoother.

**Comment by insthync** [comment]
> Have same issue with every controller. Camera is jittering while following the character.

Camera jitter or character jitter ?

**Comment by moepi2k** [comment]
alright. the jitter comes from the character like you can see in the video above and the camera is attached to the character. so you got the jitter in camera also

**Comment by nakedfighter3d** [comment]
Yes, the jitter itself persist on a character but it becomes a visible issue because of camera attached to this character. I suppose the easy fix would be not trying to makes actual character movement smoother, but use some kind of camera following with minor damping.

**Comment by nakedfighter3d** [comment]
And following should happens in LateUpdate. The jittering could be cause by the fact that the camera is following a target that is a physics gameobject, and when you do so, the camer must get the position on late update, not on update. I had this kind of issues before. If we deal with physics, both object and camera should be set in LateUpdate or it will be jittering.

**Comment by moepi2k** [comment]
yea forgot the thing with lateupdate. i had that camera issue in another project also when following physic objects. but here i think the problem is because the camera is attached on character and the character already has not smooth moving

**Comment by moepi2k** [comment]
oh yes i also noticed you fixed the camera jitter in shooter <3 great improvment, thank you very much surit :)))
