### ISSUE TITLE
Direction2D Not Set

### ISSUE THREAD

**Issue by Zodly** [suriyun-production/mmorpg-kit-docs#573]
Using 2D side of the kit when using server authoritative movement never has the server set Direction2D when using WASD. 

Click to move does infact set it though.

Tested using fresh build with 157b and 2020 unity. I've ran through debugging the actual setting of the variable and Direction2D or setting of it with WASD just never gets called on the server that I can tell.

[Gif of issue](https://imgur.com/bjIyWD6)

**Comment by Zodly** [comment]
For the time being I've made a change in the RigidBodyEntityMovement2D script.

Line 203

```
                    if (currentDestination.HasValue)
                        CacheEntity.SetDirection2D(tempMoveDirection);
```


To


```
                    //if (currentDestination.HasValue)
                        CacheEntity.SetDirection2D(tempMoveDirection);
```

**Comment by Zodly** [comment]
For the time being I've made a small change in the _RigidBodyEntityMovement2D.cs_

Line 202

```
                    if (currentDestination.HasValue)
                        CacheEntity.SetDirection2D(tempMoveDirection);
```
**To**
```
                    //if (currentDestination.HasValue)
                        CacheEntity.SetDirection2D(tempMoveDirection);
```

**Comment by insthync** [comment]
Thank you, I will remove that line. Then in the future version I will remove movement choices, all movement will be server authoritative.
