### ISSUE TITLE
Problem, client->server not working on custom code based on tutorials.

### ISSUE THREAD

**Issue by Skitosh** [suriyun-production/mmorpg-kit-docs#574]
Hi All

I'm attempting to make a class which will open doors in the network world. If one player clicks the door it opens for all. I've leveraged the tutorials and believe I'm 90% there. For some reason when attempting to open door from client agent the network calls to the server aren't getting in. Could someone look at it and tell me what I'm missing ?
This is the current behavior.
1) On Single Player Mode. The Door behavior is as expected. Click on door->Door opens->Waits for a while->Closes automatically.
2.1) 1 Host and 1 Join. From Host Console. The Door behavior is as expected on both Host and Join console.
2.2) 1 Host and 1 Join. From Join Console. Door does not open. Using c# debugger I can see that 

- RequestNetFuncResetAllSkillsOpen is being called.
- For some reason both procs "OnSetupExtension()" and "OnSetup()" which have RegisterNetFunction call in the code don't register the calls (or something) and the Join console does not communicate to the Host console.
- I have included the class that does the network communication for the door below. If someone could have a look at it and tell me what I'm missing for the client->server communication that would be great. (Please note the animation of the door is controlled by another class which extends NetworkObject2 calss. 

[NetworkObject2.cs.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5173807/NetworkObject2.cs.txt)

Many thanks in advance

**Comment by moepi2k** [comment]
i use also buildingentities doors. just drop it in scene and it works in mmo server. syncing well. what i have in mmo is sometime i got this error -> https://github.com/suriyun-production/mmorpg-kit-docs/issues/565

dont know if its from door that player create or from doors that i place in scene

**Comment by insthync** [comment]
You try to open door with `RequestNetFuncResetAllSkillsOpen()`, right?

So then when you call it, it will call `NetFuncResetAllSkillsOpen()` at **server only**
Reference from your codes
```
CallNetFunction(NetFuncResetAllSkillsOpen, FunctionReceivers.Server); //<- FunctionReceivers.Server
```
* * *
You may do something at server to sync door state to clients in `NetFuncResetAllSkillsOpen` function, for example, you may add is open state
```
[SerializeField]
protected SyncFieldBool isOpen = new SyncFieldBool();
```
Set it sync mode to `ServerToClients`
```
protected override void SetupNetElements()
{
    base.SetupNetElements();
...
    isOpen.deliveryMethod = DeliveryMethod.ReliableOrdered;
    isOpen.syncMode = LiteNetLibSyncField.SyncMode.ServerToClients;
...
}
```
Then change open state in `NetFuncResetAllSkillsOpen`
```
protected virtual void NetFuncResetAllSkillsOpen()
{
    isOpen.value = true;
}
```
* * *
or call that function on call clients by change receiver to FunctionReceivers.All

**Comment by Skitosh** [comment]
Hi Insthync
Thank you for your response, in response to your additional questions.

(Your question) You try to open door with RequestNetFuncResetAllSkillsOpen(), right? 
(Answer) Correct

(Your statement) So then when you call it, it will call NetFuncResetAllSkillsOpen() at server only
Reference from your codes
(Comment)  My understanding is that when NetFuncResetAllSkillsOpen() is called on a client (eg isClient == true, isServer == false) it will execute NetFuncResetAllSkillsOpen() on the server (ie isClient == true/false, isServer == true).

(Your statement) "You may do something at server to sync door state..." 
(Comment) The variable syncFieldInt1 in the code serves same purpose as your suggestion SyncFieldBool isOpen
 
(Your question) This is not relates to DoorEntity right?
(Comment) Not related

To reiterate the problem. Say I have two instances running
InstanceOne - isClient = true, isServer = true
InstanceTwo - isClient = true, isServer = false
I have breakpoints on line "CallNetFunction(NetFuncResetAllSkillsOpen, FunctionReceivers.Server);"  and "if(isServer)" in NetFuncResetAllSkillsOpen

First experiment, When on InstanceTwo The breakpoint on "CallNetFunction(NetFuncResetAllSkillsOpen, FunctionReceivers.Server);" line is hit. CallNetFunction executes correctly with no exception. Door does not open. And no other breakpoint is hit.

Second experiment, I'm looking at InstanceOne. Expectation is that if I click the door the CallNetFunction in InstanceTwo will result in "NetFuncResetAllSkillsOpen()" executing. (Can you please confirm that my expectations are correct ?) Breakpoint on "if(isServer)" in NetFuncResetAllSkillsOpen() is not being executed. And this is the problem :-)

Additional Information: Attempted CallNetFunction with  FunctionReceivers.All. No change in behavior.

The problem I'm seeing is why aren't the "CallNetFunction(NetFuncResetAllSkillsOpen, FunctionReceivers.Server);" on InstanceOne getting through to InstanceTwo ?

Is there a way to test CallNetFunction call from the NetworkObject2 class ? Has something not been initialized ?

Once again thank you and looking forward to your thoughts
Kind Regards
