### ISSUE TITLE
BaseAreaSkill Problem

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#575]
If u have like a ground or any floor below ur player.. ( not the one ur standing on) 
and try to use area skill .. it sometimes spawns on the one below and not the one ur standing on.. 
can also happen in building etc
https://imgur.com/xcnHhvf

In the video u can see the Effect spawning below on the other floor
and if i aim at different spot it works fine.

With floor below i mean this.
https://imgur.com/vdyncr7

**Comment by insthync** [comment]
Try 1.59, it should be fixed
