### ISSUE TITLE
[Bug]look direction after Warping still missing

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#576]
regarding this post https://github.com/suriyun-production/mmorpg-kit-docs/issues/557#event-3732710058

its still missing. i mean when you use a warp portal. you have no option to set look direction after warping. its always in same direction.

but sometimes when you use warping for example to go in a house. you need to set look direction so that after warping you look inside room and door is on back from player. right now it can be when you warp in then you look to the door and this is not good.

**Comment by insthync** [comment]
Did you set `warpOverrideRotation` to `true` and set `warpToRotation` to rotation which you wish character to turn to ?

**Comment by moepi2k** [comment]
yes, but it dont take the rotation. its always same

**Comment by insthync** [comment]
Not sure is it because your game's camera mode always FPS ?

**Comment by moepi2k** [comment]
i tested on fresh project, and yea it was in fps.

**Comment by moepi2k** [comment]
i tested again, with normal controller it works. when you use shooter (tps) then it takes new rotaten of player, but not for the camera and when you use shooter (fps) then it also dont take rotation for player. so issue is in shootercontroller
