### ISSUE TITLE
SqLiteDatabase missing

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#577]
When u create a new project with version 1.58
and build mmo using Sqlite database.
it used to create a Sqldatabase in ur folder so u can use

Atm it doesnt create any database anymore at all.

is this something else i gotta do now for it to make it ? 
did the command line to start server properly changed?
or this a bug?

**Comment by insthync** [comment]
Now server architecture changes, you have to run database management server, did you add `-startDatabaseServer` to run it yet?

![mmo_arch](https://user-images.githubusercontent.com/2697550/92322935-befc0180-f05e-11ea-8696-c4b6144868a3.png)

**Comment by Callepo** [comment]
ah no i was using old command line still

there need to be info on this somewhere so others can know too
cuase i wouldnt have known if i didnt ask

**Comment by Callepo** [comment]
What should it look like ?
path.exe -startDatabaseServer -startMapSpawnServer -spawnExePath "path.exe " -startCentralServer -startChatServer -machineAddress "127.0.0.1"

Like this ?


or 

path.exe -startDatabaseServer -startMapSpawnServer -spawnExePath "path.exe " -startCentralServer -startChatServer -machineAddress "127.0.0.1"

**Comment by Callepo** [comment]
tried putting it multiple locations, and i keep getting map server not ready
![image](https://user-images.githubusercontent.com/7702658/92330306-266d7d80-f06e-11ea-8094-52fd7fe3db2c.png)

But it did create the sqlite db

**Comment by insthync** [comment]
Your `-spawnExePath` is full path ?

**Comment by Callepo** [comment]
yes
C:\Users\Clifford\Documents\UnityBuilds\NewTest\NewTest.exe -startMapSpawnServer  -spawnExePath "C:\Users\Clifford\Documents\UnityBuilds\NewTest\NewTest.exe" -startCentralServer -startChatServer -startDatabaseServer

**Comment by Callepo** [comment]
C:\Users\Clifford\Documents\UnityBuilds\NewTest\NewTest.exe -startMapSpawnServer  -spawnExePath "C:\Users\Clifford\Documents\UnityBuilds\NewTest\NewTest.exe" -startCentralServer -startChatServer -startDatabaseServer -machineAddress "127.0.0.1"

And tried this one

**Comment by insthync** [comment]
Try  set exe path to "C:\\Users\\Clifford\\Documents\\UnityBuilds\\NewTest\\NewTest.exe"

Or try create `config` folder, inside this folder create file name `serverConfig.json` open it and put configs
```
{
    "databaseOptionIndex" : 0,
  
    "centralAddress" : "localhost",
    "centralPort" : 6000,
    "centralMaxConnections" : 1100,
    "machineAddress" : "localhost",
  
    "mapSpawnPort" : 6001,
    "mapSpawnMaxConnections" : 2,
    "spawnExePath" : "C:\\Users\\Clifford\\Documents\\UnityBuilds\\NewTest\\NewTest.exe",
    "notSpawnInBatchMode" : true,
    "spawnStartPort" : 8000,
    "spawnMaps" : ["Map001","Map002"],
  
    "chatPort" : 6002,
    "chatMaxConnections" : 1100,

    "databaseManagerAddress" : "localhost",
    "databaseManagerPort" : 6003
  }
```

Then let's see what's happen.

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/92333362-1f059e80-f085-11ea-858e-0f9276481526.png)
This is the same as i had before, the same exe path.

And i tried serverconfig and still Map not ready
![image](https://user-images.githubusercontent.com/7702658/92333377-49575c00-f085-11ea-9a30-d6f3797c2ceb.png)

![image](https://user-images.githubusercontent.com/7702658/92333385-52482d80-f085-11ea-86ec-c5c8c557e660.png)

**Comment by Callepo** [comment]
when i run with config files it opens 3 windows
is this correct?
![image](https://user-images.githubusercontent.com/7702658/92333480-16619800-f086-11ea-9c81-57ac82175a5b.png)

**Comment by Callepo** [comment]
ok after rebooting it all again it worked
![image](https://user-images.githubusercontent.com/7702658/92333500-3729ed80-f086-11ea-8a5e-690c720e9a3c.png)

**Comment by Callepo** [comment]
ill go test without config files and see if that fixed it

**Comment by Callepo** [comment]
Only works With Config file, just command line and no serverconfig u get map server not ready

**Comment by insthync** [comment]
Try set exe path to `C:\\Users\\Clifford\\Documents\\UnityBuilds\\NewTest\\NewTest.exe`

( 2 slashes )

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/92333688-c1bf1c80-f087-11ea-88f8-c63451da3e06.png)

**Comment by Callepo** [comment]
C:\Users\Clifford\Documents\UnityBuilds\NewTest\NewTest.exe -startMapSpawnServer -spawnExePath "C:\\Users\\Clifford\\Documents\\UnityBuilds\\NewTest\\NewTest.exe" -startCentralServer -startChatServer -startDatabaseServer -machineAddress "127.0.0.1"

**Comment by Callepo** [comment]
C:\\Users\\Clifford\\Documents\\UnityBuilds\\NewTest\\Newtest.exe -startMapSpawnServer -spawnExePath "C:\\Users\\Clifford\\Documents\\UnityBuilds\\NewTest\\Newtest.exe" -startCentralServer -startChatServer -startDatabaseServer -machineAddress "127.0.0.1"

I even renamed everything from NewTest to Newtest to see if it was the capital letter making it not work

**Comment by Callepo** [comment]
^ the code above has 2 // but idk why it shows only 1 lol
![image](https://user-images.githubusercontent.com/7702658/92333813-b02a4480-f088-11ea-8364-a25a1c8ffe75.png)

i edited it 3 times it tells me 2 but only shows 1 in the message

**Comment by Serivatech** [comment]
I have the same error. But I have a server on vps. I also use sqllite.
![img1](https://user-images.githubusercontent.com/56482598/92333958-51c28d80-f0ab-11ea-89d3-1187b742ccd1.png)
![img2](https://user-images.githubusercontent.com/56482598/92333976-79b1f100-f0ab-11ea-9b61-3bbec33b2c09.png)

**Comment by Callepo** [comment]
i only managed to make it work with config files on a new project.. my own game still dont work with sqlite on local.
i havent tested my vps yet but that one uses mysql

**Comment by Serivatech** [comment]
And this is a new project. But the server is on linux.

**Comment by Callepo** [comment]
@Serivatech i found ur problem

Check his config file above.. urs is different..
i went to check my games config file and noticed it wasnt same 2 
i fixed it now my game runs fine with config file
ur missing the top part 
![image](https://user-images.githubusercontent.com/7702658/92334179-f03ef680-f08b-11ea-8180-d25447767983.png)

aka this     "databaseOptionIndex" : 0,

this made mine work fine.. But still cant start without config file.. 
i used to always test local build without file cuase was handy..
i only used config files for mysql linux server builds

**Comment by Serivatech** [comment]
No, it does not work
![img3](https://user-images.githubusercontent.com/56482598/92334310-72401700-f0ae-11ea-9fd1-b8ad33694467.png)

**Comment by Callepo** [comment]
why is ur databasemanager on local ? and the others above on an ip
put all on same ip

**Comment by Blunnyn** [comment]
same problem

**Comment by Callepo** [comment]
i tried linux server 2 and i couldnt start it i used 
/root/TestServer/TestServer.x86_64  -startCentralServer -startChatServer -startMapSpawnServer -startDatabaseServer 

AS command line and fixed serverconfig files
but nothing

**Comment by insthync** [comment]
Map server not spawn, Fix it by add () cover inline conditional codes in `MapSpawnNetworkManager.cs` at line `250`

from `Arguments = !NotSpawnInBatchMode ? "-batchmode -nographics " : string.Empty +`
to `Arguments = (!NotSpawnInBatchMode ? "-batchmode -nographics " : string.Empty) +`

So, From line `250` codes will be
```
                Arguments = (!NotSpawnInBatchMode ? "-batchmode -nographics " : string.Empty) +
                    $"{MMOServerInstance.ARG_MAP_ID} {mapId} " +
```

**Comment by Callepo** [comment]
ok i will try this,

Question how do we start linux server build ? cuase i tried 
/root/TestServer/TestServer.x86_64 -startCentralServer -startChatServer -startMapSpawnServer -startDatabaseServer 
and it doesnt work

i used to be 
/root/TestServer/TestServer.x86_64 -startCentralServer -startChatServer -startMapSpawnServer

**Comment by Callepo** [comment]
@insthync 
![image](https://user-images.githubusercontent.com/7702658/92346788-24d3a200-f0ce-11ea-8004-ac78beda0217.png)
This worked perfectly ty

**Comment by Zodly** [comment]
> @insthync
> ![image](https://user-images.githubusercontent.com/7702658/92346788-24d3a200-f0ce-11ea-8004-ac78beda0217.png)
> This worked perfectly ty

Did this.  Also tried to create the serverConfig.json and double checked my shortcut parameters.

Shortcut Parameters
`"P:\Test\New Unity Project\Build\New Unity Project.exe" -startMapSpawnServer -spawnExePath "P:\Test\New Unity Project\Build\New Unity Project.exe" -startCentralServer -startChatServer -startDatabaseServer`

serverConfig.Json
`{
    "databaseOptionIndex" : 0,
  
    "centralAddress" : "localhost",
    "centralPort" : 6000,
    "centralMaxConnections" : 1100,
    "machineAddress" : "localhost",
  
    "mapSpawnPort" : 6001,
    "mapSpawnMaxConnections" : 2,
    "spawnExePath" : "P:\\GarbageTest\\New Unity Project\\Build\\New Unity Project.exe",
    "notSpawnInBatchMode" : true,
    "spawnStartPort" : 8000,
    "spawnMaps" : ["Map001","Map002"],
  
    "chatPort" : 6002,
    "chatMaxConnections" : 1100,

    "databaseManagerAddress" : "localhost",
    "databaseManagerPort" : 6100
  }`

Two things are occuring. 

1) I can't register or login, exception happens on the server

`(Exception) MultiplayerARPG.MMO.CentralNetworkManager+<HandleRequestUserLoginRoutine>d__62.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.MMO.<HandleRequestUserLoginRoutine>d__62:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<HandleRequestUserLoginRoutine>d__62&)
MultiplayerARPG.MMO.CentralNetworkManager:HandleRequestUserLoginRoutine(LiteNetLibMessageHandler)
MultiplayerARPG.MMO.CentralNetworkManager:HandleRequestUserLogin(LiteNetLibMessageHandler)
LiteNetLibManager.TransportHandler:ReadPacket(Int64, NetDataReader)
LiteNetLibManager.LiteNetLibServer:OnServerReceive(TransportEventData)
LiteNetLibManager.LiteNetLibServer:Update()
LiteNetLibManager.LiteNetLibManager:LateUpdate()`

2) Both map servers receive errors and never load up.

`(Exception) MultiplayerARPG.MMO.MapNetworkManager+<PreSpawnEntities>d__84.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <17aa5125c4544a82a13b7a57c6fdaf46>:0)
MultiplayerARPG.BaseGameNetworkManager+<SpawnEntities>d__117.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<SpawnEntities>d__117:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run()`

**Comment by insthync** [comment]
> > @insthync
> > ![image](https://user-images.githubusercontent.com/7702658/92346788-24d3a200-f0ce-11ea-8004-ac78beda0217.png)
> > This worked perfectly ty
> 
> Did this. Also tried to create the serverConfig.json and double checked my shortcut parameters.
> 
> Shortcut Parameters
> `"P:\Test\New Unity Project\Build\New Unity Project.exe" -startMapSpawnServer -spawnExePath "P:\Test\New Unity Project\Build\New Unity Project.exe" -startCentralServer -startChatServer -startDatabaseServer`
> 
> serverConfig.Json
> 
> ```
> {
>     "databaseOptionIndex" : 0,
>   
>     "centralAddress" : "localhost",
>     "centralPort" : 6000,
>     "centralMaxConnections" : 1100,
>     "machineAddress" : "localhost",
>   
>     "mapSpawnPort" : 6001,
>     "mapSpawnMaxConnections" : 2,
>     "spawnExePath" : "P:\\Test\\New Unity Project\\Build\\New Unity Project.exe",
>     "notSpawnInBatchMode" : true,
>     "spawnStartPort" : 8000,
>     "spawnMaps" : ["Map001","Map002"],
>   
>     "chatPort" : 6002,
>     "chatMaxConnections" : 1100,
> 
>     "databaseManagerAddress" : "localhost",
>     "databaseManagerPort" : 6100
>   }
> ```
> 
> Two things are occuring.
> 
> 1. I can't register or login, exception happens on the server
> 
> `(Exception) MultiplayerARPG.MMO.CentralNetworkManager+<HandleRequestUserLoginRoutine>d__62.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0) UnityEngine.Debug:LogException(Exception) Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) MultiplayerARPG.MMO.<HandleRequestUserLoginRoutine>d__62:MoveNext() Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<HandleRequestUserLoginRoutine>d__62&) MultiplayerARPG.MMO.CentralNetworkManager:HandleRequestUserLoginRoutine(LiteNetLibMessageHandler) MultiplayerARPG.MMO.CentralNetworkManager:HandleRequestUserLogin(LiteNetLibMessageHandler) LiteNetLibManager.TransportHandler:ReadPacket(Int64, NetDataReader) LiteNetLibManager.LiteNetLibServer:OnServerReceive(TransportEventData) LiteNetLibManager.LiteNetLibServer:Update() LiteNetLibManager.LiteNetLibManager:LateUpdate()`
> 
> 1. Both map servers receive errors and never load up.
> 
> `(Exception) MultiplayerARPG.MMO.MapNetworkManager+<PreSpawnEntities>d__84.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0) --- End of stack trace from previous location where exception was thrown --- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0) Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <17aa5125c4544a82a13b7a57c6fdaf46>:0) MultiplayerARPG.BaseGameNetworkManager+<SpawnEntities>d__117.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0) UnityEngine.Debug:LogException(Exception) Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) MultiplayerARPG.<SpawnEntities>d__117:MoveNext() Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid1:Run() Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore() Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run()`

Are you testing on windows?, when you build you build with `Server Build` enabled?, it's `x86` or `x86_64`?

**Comment by Callepo** [comment]
@insthync Whats command line to boot server on linux ?
i tried this
/root/TestServer/TestServer.x86_64 -startCentralServer -startChatServer -startMapSpawnServer -startDatabaseServer
and it doesnt work, Server starts but not database server.. i cant even login or create account cuase no db

it used to be
/root/TestServer/TestServer.x86_64 -startCentralServer -startChatServer -startMapSpawnServer

**Comment by Zodly** [comment]
> > > @insthync
> > > ![image](https://user-images.githubusercontent.com/7702658/92346788-24d3a200-f0ce-11ea-8004-ac78beda0217.png)
> > > This worked perfectly ty
> > 
> > 
> > Did this. Also tried to create the serverConfig.json and double checked my shortcut parameters.
> > Shortcut Parameters
> > `"P:\Test\New Unity Project\Build\New Unity Project.exe" -startMapSpawnServer -spawnExePath "P:\Test\New Unity Project\Build\New Unity Project.exe" -startCentralServer -startChatServer -startDatabaseServer`
> > serverConfig.Json
> > ```
> > {
> >     "databaseOptionIndex" : 0,
> >   
> >     "centralAddress" : "localhost",
> >     "centralPort" : 6000,
> >     "centralMaxConnections" : 1100,
> >     "machineAddress" : "localhost",
> >   
> >     "mapSpawnPort" : 6001,
> >     "mapSpawnMaxConnections" : 2,
> >     "spawnExePath" : "P:\\Test\\New Unity Project\\Build\\New Unity Project.exe",
> >     "notSpawnInBatchMode" : true,
> >     "spawnStartPort" : 8000,
> >     "spawnMaps" : ["Map001","Map002"],
> >   
> >     "chatPort" : 6002,
> >     "chatMaxConnections" : 1100,
> > 
> >     "databaseManagerAddress" : "localhost",
> >     "databaseManagerPort" : 6100
> >   }
> > ```
> > 
> > 
> > Two things are occuring.
> > 
> > 1. I can't register or login, exception happens on the server
> > 
> > `(Exception) MultiplayerARPG.MMO.CentralNetworkManager+<HandleRequestUserLoginRoutine>d__62.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0) UnityEngine.Debug:LogException(Exception) Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) MultiplayerARPG.MMO.<HandleRequestUserLoginRoutine>d__62:MoveNext() Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<HandleRequestUserLoginRoutine>d__62&) MultiplayerARPG.MMO.CentralNetworkManager:HandleRequestUserLoginRoutine(LiteNetLibMessageHandler) MultiplayerARPG.MMO.CentralNetworkManager:HandleRequestUserLogin(LiteNetLibMessageHandler) LiteNetLibManager.TransportHandler:ReadPacket(Int64, NetDataReader) LiteNetLibManager.LiteNetLibServer:OnServerReceive(TransportEventData) LiteNetLibManager.LiteNetLibServer:Update() LiteNetLibManager.LiteNetLibManager:LateUpdate()`
> > 
> > 1. Both map servers receive errors and never load up.
> > 
> > `(Exception) MultiplayerARPG.MMO.MapNetworkManager+<PreSpawnEntities>d__84.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0) --- End of stack trace from previous location where exception was thrown --- System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0) Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <17aa5125c4544a82a13b7a57c6fdaf46>:0) MultiplayerARPG.BaseGameNetworkManager+<SpawnEntities>d__117.MoveNext () (at <119f75f9efb444cfbe6aad26e46387b1>:0) UnityEngine.Debug:LogException(Exception) Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) MultiplayerARPG.<SpawnEntities>d__117:MoveNext() Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid1:Run() Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore() Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run()`
> 
> Are you testing on windows?, when you build you build with `Server Build` enabled?, it's `x86` or `x86_64`?

Did not try Server Build, never have but I can try it if you want me to.
x86. Have not tried x86_64

**Comment by Xentar** [comment]
Going to join here. Did tests with x86 and x86_64 with and without server build.
Same issues, can't register or login. Actually i tested all that has been said here before i was told there was a "issue open"... except the json config

**Comment by Zodly** [comment]
`x86_64` seems to do the trick. Running into a whole 'nother issue now though. 

Map Instance sometimes throws 

This is with `"databaseOptionIndex" : 0,`
```
(Exception) System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
MultiplayerARPG.MMO.MapNetworkManager+<PreSpawnEntities>d__84.MoveNext () (at <a801a819f8ab486cac4399f42d2a68a0>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at <9574ea5d20f1429e950f9e740c24c125>:0)
MultiplayerARPG.BaseGameNetworkManager+<SpawnEntities>d__117.MoveNext () (at <a801a819f8ab486cac4399f42d2a68a0>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<SpawnEntities>d__117:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception)
MultiplayerARPG.MMO.<PreSpawnEntities>d__84:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
```

This is with `"databaseOptionIndex" : 1,`
```
(Exception) System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <fb001e01371b4adca20013e0ac763896>:0)
MultiplayerARPG.MMO.MapNetworkManager+<PreSpawnEntities>d__84.MoveNext () (at <a801a819f8ab486cac4399f42d2a68a0>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <fb001e01371b4adca20013e0ac763896>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at <9574ea5d20f1429e950f9e740c24c125>:0)
MultiplayerARPG.BaseGameNetworkManager+<SpawnEntities>d__117.MoveNext () (at <a801a819f8ab486cac4399f42d2a68a0>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<SpawnEntities>d__117:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception)
MultiplayerARPG.MMO.<PreSpawnEntities>d__84:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
```

**Comment by insthync** [comment]
Just uploaded 1.58b, please try it.

**Comment by Callepo** [comment]
Will do TY

**Comment by Callepo** [comment]
Downloading right now

**Comment by Callepo** [comment]
@insthync i only managed  to start server without config files.. 
/root/TestServer/TestServer.x86_64 -startMapSpawnServer -spawnExePath  "/root/TestServer/TestServer.x86_64" -startCentralServer -startChatServer -startDatabaseServer -machineAddress "185.95.13.129"
This worked fine and i could login and start game and walk all good
i  tried config files and 
/root/TestServer/TestServer.x86_64 -startDatabaseServer -startCentralServer -startChatServer -startMapSpawnServer
it didnt work, same issue as before
![image](https://user-images.githubusercontent.com/7702658/92421578-7ab15400-f179-11ea-9ab9-c5c7ddfb05a9.png)

is this correct?

**Comment by Callepo** [comment]
[Log_Map(Map002) Instance().txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5185455/Log_Map.Map002.Instance.txt)
[Log_Database_Central_Chat_MapSpawn.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5185456/Log_Database_Central_Chat_MapSpawn.txt)
[Log_Map(Map001) Instance().txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5185457/Log_Map.Map001.Instance.txt)
Log files

**Comment by Callepo** [comment]
Think my config files are bad.. it works fine without it 
whenever i try use it i cant login

**Comment by Zodly** [comment]
So all my issues are gone. Biggest thing seems you HAVE to build in `x86_64` not sure if that was intended.

**Comment by insthync** [comment]
Ahhh, yes, I've included only Grpc plugins for x86_64 platforms
