### ISSUE TITLE
Grid Visibility Checker

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#579]
![image](https://user-images.githubusercontent.com/7702658/92358704-362aa780-f0ea-11ea-924e-83e73b0f654d.png)

 
At time randomly when u kill a mob.
They die and dont dissapear and u get bunch of errors
1
![image](https://user-images.githubusercontent.com/7702658/92358727-40e53c80-f0ea-11ea-8ea2-9caec0385727.png)
2
![image](https://user-images.githubusercontent.com/7702658/92358474-ccaa9900-f0e9-11ea-8b87-2b9c78e0f88e.png)
3
![image](https://user-images.githubusercontent.com/7702658/92358512-dd5b0f00-f0e9-11ea-851e-332d003ca316.png)

Video 
https://imgur.com/ZOMj6EN

**Comment by insthync** [comment]
I've forget to tell that you have to attach `GridManager` to `LanRpgNetworkManager` or `MapNetworkManager`

![Screenshot_74](https://user-images.githubusercontent.com/2697550/92360540-2aa1a580-f117-11ea-881d-ab20ef9ba5ba.png)

**Comment by insthync** [comment]
Next update I will make it not require to attach it by try get or add it on initial

**Comment by moepi2k** [comment]
maybe its same issue: i have a warpportal placed in scene and when login i get this also:

`
NullReferenceException: Object reference not set to an instance of an object
LiteNetLibManager.SuperGrid2D.GridVisibleChecker.LateUpdate () (at Assets/UnityMultiplayerARPG/Core/SuperGrid2DVisibleChecker/Scripts/GridVisibleChecker.cs:45)`

**Comment by insthync** [comment]
Yes, that is it, did you tried following my anwser ?

**Comment by Callepo** [comment]
cool ty

**Comment by moepi2k** [comment]
> Yes, that is it, did you tried following my anwser ?

not yet, i will do it after work.

thank you

**Comment by insthync** [comment]
Fixed in 1.58b
