### ISSUE TITLE
punch error

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#58]
character shift after fist movement.character shifts when given forward movement.
please don't move during the attack.

https://gyazo.com/8a954202d1f72fb5bd9bc73f1f37fd0d

**Comment by Callepo** [comment]
there is an option for this . Movementspeed while attacking put it to 0 .. and ur done its not an error

**Comment by kazuden** [comment]
> there is an option for this . Movementspeed while attacking put it to 0 .. and ur done its not an error

where exactly is it. I couldnt find it

**Comment by insthync** [comment]
![Screenshot_59](https://user-images.githubusercontent.com/2697550/62689976-034d4600-b9f6-11e9-8469-eae8de9663ce.png)

**Comment by insthync** [comment]
Oh, I found bug here, set move speed rate to default weapon item will not work, I'm going to fix it, it will be applied in version 1.47c

**Comment by insthync** [comment]
Fixed, please try it

**Comment by kazuden** [comment]
teşekkürler

**Comment by kazuden** [comment]
thank you
