### ISSUE TITLE
[Bug]MySQLDatabase_UMA + SQLiteDatabase_UMA

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#580]
i think this is not updated in 1.58

greeeeets

`Assets\UMAExtension\Scripts\MMO\Database\SQLiteDatabase_UMA.cs(52,13): error CS0246: The type or namespace name 'SQLiteRowsReader' could not be found (are you missing a using directive or an assembly reference?)
`

`Assets\UMAExtension\Scripts\MMO\Database\SQLiteDatabase_UMA.cs(52,53): error CS1503: Argument 1: cannot convert from 'string' to 'System.Action<Mono.Data.Sqlite.SqliteDataReader>'`

`Assets\UMAExtension\Scripts\MMO\Database\SQLiteDatabase_UMA.cs(53,17): error CS1503: Argument 2: cannot convert from 'Mono.Data.Sqlite.SqliteParameter' to 'string'`

`Assets\UMAExtension\Scripts\MMO\Database\MySQLDatabase_UMA.cs(43,13): error CS0246: The type or namespace name 'MySQLRowsReader' could not be found (are you missing a using directive or an assembly reference?)`

`Assets\UMAExtension\Scripts\MMO\Database\MySQLDatabase_UMA.cs(43,52): error CS1503: Argument 1: cannot convert from 'string' to 'System.Action<MySqlConnector.MySqlDataReader>'
`

`Assets\UMAExtension\Scripts\MMO\Database\MySQLDatabase_UMA.cs(44,17): error CS1503: Argument 2: cannot convert from 'MySqlConnector.MySqlParameter' to 'string'`

**Comment by insthync** [comment]
Oh, I will update it.

**Comment by moepi2k** [comment]
great thank you :) im stuck at it atm, cant run 1.58 in my project :P

**Comment by moepi2k** [comment]
Thanks for updating. It worksfor sqlite but mysql still have errors

**Comment by insthync** [comment]
You will have to update MMO repository too.

**Comment by insthync** [comment]
MMO repository included in 1.58b
