### ISSUE TITLE
[Bug]Shootercontroller(FPS) FireStagger

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#581]
i tried some stuff with firestagger and noticed that there is an issue when you aim on a entity, it doenst matter if its an enemy or building entity.

the problem is when you aim on it, all projectiles go in a diffrent random direction, everywhere but not there where it should. its like the entity has a shield to reflect all projectiles ^^

i made a video. its easier to understand.

https://youtu.be/Z1-oq4wSvlM

i noticed in the past that there is something weird in shootercontroller when you aim to a entity. sometimes its like auto aim for projectils. but i dont find any solution for it, maybe you can help me out. if its like auto aim then an option to disable would be nice.

**Comment by moepi2k** [comment]
here another video where you can see diffrence a bit better. when i aim on non entity it works. as long as i aim on an entity it happen weird things

https://youtu.be/Rv9E17KTtjc

**Comment by insthync** [comment]
Fixed in 1.58b
