### ISSUE TITLE
Problem with starting MMO Server from shortcut

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#584]
i updated to 1.58b. now i want to test some things and i just added the new parameter
-startDatabaseServer 

like this

C:\Users\hubla\Desktop\Build\1.58b.exe -startMapSpawnServer -spawnExePath "C:\Users\hubla\Desktop\Build\1.58b.exe" -startCentralServer -startChatServer -startDatabaseServer -machineAddress "127.0.0.1"

when i now run shortcut, then just the window opens without console informations. i also not able to login with players or register an account.

when i remove the -startDatabaseServer the window start with console informations. when i now test i can login and get to registration field and then for sure i cant register becuase databaseserver ist not started.

it worked in 1.57b.

i tested in fresh project.

**Comment by insthync** [comment]
Please capture screenshot of blank screen, I dont know how it is.

And I not sure that the command may too long to put into the target properties? Check all character filled into the text box or not.

**Comment by moepi2k** [comment]
yes everything is in target properties.
i building as x86
changing to x86_64 solved the issue with empty console. but now i got alot of console errors regarding mysql.

has something changed by default? i use sqlite and i never changed something for database

i changed 
[Log_Database_Central_Chat_MapSpawn.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5188900/Log_Database_Central_Chat_MapSpawn.txt)
[Log_Map(Map001) Instance().txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5188902/Log_Map.Map001.Instance.txt)
[Log_Map(Map002) Instance().txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5188903/Log_Map.Map002.Instance.txt)

**Comment by moepi2k** [comment]
it is working now. by default it use mysql now, i changed back to sqlite.

and maybe a note would be good that you need to build with 86_64

**Comment by insthync** [comment]
Okay, I will add note about it.

**Comment by moepi2k** [comment]
Great thank you 🙌👍
