### ISSUE TITLE
[Bug]1.58b MMO and UMA

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#585]
there is an issue with 1.58b when using uma and mmo

you can create character and then character is in the list but you cant select it, also you cant see the character as preview.

heres unity console error:

`NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.UICharacterList.OnSelectCharacter (IPlayerCharacterData playerCharacterData) (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/UI/UICharacterList.cs:173)
MultiplayerARPG.UICharacterListUMA.OnSelectCharacter (IPlayerCharacterData playerCharacterData) (at Assets/UMAExtension/Scripts/UI/UICharacterListUMA.cs:13)
MultiplayerARPG.UICharacterList.OnSelectCharacter (MultiplayerARPG.UICharacter uiCharacter) (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/UI/UICharacterList.cs:153)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <3dc54541a2574ac7826a004a212a4332>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <3dc54541a2574ac7826a004a212a4332>:0)
UISelectionManager`4[TData,TUI,TDataEvent,TUIEvent].Select (System.Object ui) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionManager.cs:106)
UISelectionManager`4[TData,TUI,TDataEvent,TUIEvent].Add (TUI ui) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionManager.cs:51)
MultiplayerARPG.MMO.UIMmoCharacterListUMA.<OnRequestedCharacters>b__1_0 (System.Int32 index, PlayerCharacterData characterData, UnityEngine.GameObject ui) (at Assets/UMAExtension/Scripts/MMO/UI/UIMmoCharacterListUMA.cs:81)
UIList.Generate[T] (System.Collections.Generic.IEnumerable`1[T] list, System.Action`3[T1,T2,T3] onGenerateEntry) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UIList.cs:50)
MultiplayerARPG.MMO.UIMmoCharacterListUMA.OnRequestedCharacters (LiteNetLibManager.AckResponseCode responseCode, LiteNetLibManager.BaseAckMessage message) (at Assets/UMAExtension/Scripts/MMO/UI/UIMmoCharacterListUMA.cs:66)
LiteNetLibManager.TransportHandler.ReadResponse[T] (System.UInt32 ackId, LiteNetLibManager.AckResponseCode responseCode, T messageData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:85)
MultiplayerARPG.MMO.CentralNetworkManager.HandleResponseCharacters (LiteNetLibManager.LiteNetLibMessageHandler messageHandler) (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Networking/Central/CentralNetworkManager_Character.cs:210)
LiteNetLibManager.TransportHandler.ReadPacket (System.Int64 connectionId, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:53)
LiteNetLibManager.LiteNetLibClient.OnClientReceive (LiteNetLibManager.TransportEventData eventData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:65)
LiteNetLibManager.LiteNetLibClient.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:31)
LiteNetLibManager.LiteNetLibManager.LateUpdate () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:110)`

**Comment by klarkitgames** [comment]
Also it only shows 1 character no matter how many you make.

**Comment by insthync** [comment]
Fixed, https://github.com/insthync/UnityMultiplayerARPG_UMA/releases/tag/1.16b

**Comment by moepi2k** [comment]
great, thank you very muuuch
