### ISSUE TITLE
arm64 support via IL2CPP

### ISSUE THREAD

**Issue by stanica** [suriyun-production/mmorpg-kit-docs#587]
With Apple now requiring 64-bit applications and Android having the same requirement starting 2021, I was wondering if there's support for IL2CPP. Currently, an empty unity project with the latest version of the kit throws errors when trying to compile with IL2CPP.

**Comment by insthync** [comment]
I will check it again, last week I was able to build the Arm64 apk

**Comment by insthync** [comment]
I still can build Arm64 API, I want to see an errors

**Comment by stanica** [comment]
Turns out I'm an idiot and it works fine for compiling Android.
