### ISSUE TITLE
[Bug] Attack animations using V key

### ISSUE THREAD

**Issue by majausone** [suriyun-production/mmorpg-kit-docs#588]
Congratulations on the update.
If you attack using the V key quickly, the animations stop running or are lost.
This happens in a clean project, without touching any parameters, just open and press v many times, with several controllers and it happens to more people.
Regards!

**Comment by insthync** [comment]
Thank you for bug report , i will fix it

**Comment by moepi2k** [comment]
yea this issue also appears here with shootercontroller in 1.58b. animation sometimes missing but sound and attack work

**Comment by insthync** [comment]
I've uploaded 1.58c, try it.

**Comment by moepi2k** [comment]
works, great thank you

**Comment by moepi2k** [comment]
oh no its not fixed, now there are other issues, some enemies animation are borken. they attack and animation is cutted so they attack again between in middle of first animation. and in my fps animation there are some animation mixed, when i use a skill with Animation X then a skill with animation Y, animation X is still running and animation Y is broken, he try to make the animation but it repeatly fast

**Comment by insthync** [comment]
Try set action state names

![Screenshot_75](https://user-images.githubusercontent.com/2697550/92979566-56c57980-f4bd-11ea-8e82-f6c8724e64a9.png)

**Comment by moepi2k** [comment]
it is set to Action. i changed nothing. its same enemy like i used before and it worked then

**Comment by insthync** [comment]
Try add check can attack validation codes to `BaseCharacterEntity_AttackFunctions.cs` in function `NetFuncAttack`
```
        protected virtual void NetFuncAttack(bool isLeftHand)
        {
            if (!CanAttack())
                return;
```

**Comment by moepi2k** [comment]
still same issue

**Comment by moepi2k** [comment]
Here another Video. it seems that the problem is with State "CastSkill" when use a skill it never find an exit.
for monsters also when they only make default attacks (no skills attached to enemies) then they work. when you attach a skill and he use it, the problem beginns.

https://youtu.be/jxz1EhSgBjo

**Comment by insthync** [comment]
Please try 1.58d
