### ISSUE TITLE
[Bug]1.58b something broke building stuff

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#589]
In Shootercontroller (FPS + TPS) its no longer possible to build stuff. for example the foundation is always red and you cant place it, it also jumping around when you move it a bit further away from player and the preview is very unsmooth.

**Comment by insthync** [comment]
I've uploaded 1.58c, try it.

**Comment by moepi2k** [comment]
i can place stuff again, but there is still an issue, when you move it away it beginns to jump. on prefab is an variable to set building distance. maybe its better when you click on building item and preview appears that it appears at the distance position, then when you move with mouse the preview is always at this position and wehn move mouse up/down you will change up/down position of preview,so you can change its y direction when placing, becuase when you wanna place it on a ground that is not exactly flat then it could happen that terrain is inside the building foundation floor.

here a video of the issue https://youtu.be/qNXPbAqw4nI

**Comment by insthync** [comment]
Please try 1.58d

**Comment by moepi2k** [comment]
fixed thanks
