### ISSUE TITLE
Animation issue 

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#591]
In the new version 1.58C
The animator script has a new method, some bout StartedCouroutine.
this makes the animations in the game repeat over and over and look very glitchy / buggy.
its a new edit in AnimatorCharacterModel and one other script.. 
i already undid the changes and dont remember the name.
https://imgur.com/xQ5xuef

This how it should look/ and look when i removed the StartedCouroutine code.
https://imgur.com/JvXDdB6

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Please try 1.58d
