### ISSUE TITLE
FPS situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#592]
Fresh project 1.58c, unity 2019.3.13f1. No assets installed. Single player.
There are 800 monsters on the map. No monsters are visible on the screen, but the FPS has dropped very much. The more monsters, the more FPS falls. 
Can anyone know the reason for this?
An example in the video.
[FPS situation.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5214239/FPS.situation.zip)

**Comment by insthync** [comment]
While playing singleplayer, it's being both server and client, monster activity component always updating at server, so while playing singleplayer all monster will still updates their movement, decision to do something while it's hidden from screen. try remove `!IsServer` from the condition in `MonsterActivityComponent`, it may helps.

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/93025708-e592dd00-f608-11ea-80c0-59c9fafe8411.png)
With this i get 1-2 fps. If i did the right thing

**Comment by insthync** [comment]
I said that !IsServer does not have to be deleted because I think the condition is correct, but still have to find which components should be disable when hosting player's not subscribed.

**Comment by insthync** [comment]
I can improve Grid visible checker, I may disable monster character entity updates while there is no subscribers

**Comment by DimasjkTV** [comment]
> I can improve Grid visible checker, I may disable monster character entity updates while there is no subscribers

It will be very good if it helps me add more than 40 monsters to the map that I currently have. 
Maybe you can add a function to spawn monsters when the character enters the collider? At least for a single game.
Initially, there are no monsters on the map, but there are colliders. For example, a collider will spawn 10 monsters. The character enters the collider and 10 monsters appear. Maybe it helped somehow

**Comment by DimasjkTV** [comment]
> I can improve Grid visible checker, I may disable monster character entity updates while there is no subscribers

Drops on fps started up to 1-2 fps every 2 seconds. If I understand correctly, then this comes during the saving of progress.
[bandicam 2020-09-15 12-12-16-085.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5223838/bandicam.2020-09-15.12-12-16-085.zip)

**Comment by DimasjkTV** [comment]
> I can improve Grid visible checker, I may disable monster character entity updates while there is no subscribers

1.58d  Don't sync 800 monsters 38-42 fps
![image](https://user-images.githubusercontent.com/47291794/93197232-10d61300-f754-11ea-8447-3464b5c4329c.png)


1.58c  Don't sync 800 monsters, same map (copyed from 1.48d) 28-35 fps
![image](https://user-images.githubusercontent.com/47291794/93197138-f3a14480-f753-11ea-9bd4-71058ffa51c3.png)

**Comment by DimasjkTV** [comment]
> I can improve Grid visible checker, I may disable monster character entity updates while there is no subscribers

About FPS on mobile single player
drop from normal 40-50 to 22-30 when attacking also fps dropped when pick up loot. Also, some small friezes are visible during the movement of the character. I understand that the asset itself is not intended for single player games, but I would like at least some solution that could slightly increase performance for a single player game.
[20200927_223541.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5288935/20200927_223541.zip)

**Comment by DimasjkTV** [comment]
I also noticed that during the skill cooldown there are micro freezes

**Comment by insthync** [comment]
This is not about amount of monster anymore, right ?

**Comment by insthync** [comment]
About amount of monster I have another plan to store monster character state to some class then destroy monster entity if there is no player character nearby monster area (and respawn when there is any player character in the area).

**Comment by DimasjkTV** [comment]
> About amount of monster I have another plan to store monster character state to some class then destroy monster entity if there is no player character nearby monster area (and respawn when there is any player character in the area).

The number of monsters still reduces FPS. It's a good idea to do as you wrote above. Earlier I suggested something similar, when the character enters the collider and the monsters spawn. For example, there are 20 colliders on the map. Each will spawn 10 monsters. When a character appears on the map, there are no monsters on it, but only colliders. The character enters the collider, the monsters have appeared. If a character does not attack monsters for 10 seconds and leaves the collider, then the monsters in this collider disappear. Re-entering the collider should not summon monsters again or after a while.

**Comment by DimasjkTV** [comment]
1.59b  Dont sync

160 monsters 
around 60-70 fps (max amount)

320 monsters (loading of the map noticeably increases)
around 50-68 fps

640 monsters
around 20-38 fps

**Comment by DimasjkTV** [comment]
But, there is a strange situation
The same 640 monsters, but located as in the screenshot.
And i have 55 FPS
![image](https://user-images.githubusercontent.com/47291794/94717594-3d477d00-0359-11eb-919b-4a517a6911dc.png)

**Comment by DimasjkTV** [comment]
> This is not about amount of monster anymore, right ?

I will sum up.
1. The total FPS decreases from the number of monsters on the map
2. A sharp decrease in FPS occurs when a character attacks monsters. (noticeable on mobile devices)
3. I have 50-55 fps on my phone, but when moving the camera jerks and it seems that fps is only 25-30. (on powerful devices, where there is always 60 fps, the picture does not twitch. Rarely freezes

**Comment by DimasjkTV** [comment]
Here you can see the twitching of the picture when moving, although everything is fine with the FPS. It feels like the frames per second don't keep up. There is no syncronization. I do not know.
[20201009_163540.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5355266/20201009_163540.zip)
