### ISSUE TITLE
Skill : Damage Info : Damage Type cannot be set to Custom

### ISSUE THREAD

**Issue by Fashtas** [suriyun-production/mmorpg-kit-docs#593]
For Skills : Damage Info there is a setting for damage type with the following options:
Melee
Missile
Raycast 
Custom

First three work, but if you set to "Custom" the combo resets to Melee

**Comment by insthync** [comment]
Did you try create custom damage info class by inherit from `BaseCustomDamageInfo` ?

**Comment by insthync** [comment]
I will change custom to 254

**Comment by Fashtas** [comment]
Changing the ENUM to 254 allows the CUSTOM combobox selection to be selected!

I still cannot actually attach a `BaseCustomDamageInfo` script to it however. I created a custom class, inherited from it, but it will not "attach" to the "Custom Damage Info" object

Attached the very basic non-functional script that inherits from the base class.
[CDI.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5221799/CDI.zip)

**Comment by insthync** [comment]
Did you create it as scriptable object asset ?

**Comment by Fashtas** [comment]
Whoops, no I didn't. works now (Well "works" as in I attached it but never added any code to the function calls so it is a VERY boring bit of Custom Damage!)

Thanks! With the 254 change to ENUM should all work fine now!

**Comment by Fashtas** [comment]
Downloaded latest 1.58d and ENUM to 254 seems to work. Custom Damage Info can now be selected
