### ISSUE TITLE
v1.58b NavMeshEntityMovement.cs Resume and SetDestination Intermittent error

### ISSUE THREAD

**Issue by Skitosh** [suriyun-production/mmorpg-kit-docs#596]
Hi Support

The two errors sometimes occur when the monster spanner starts. Currently unknown if it occurs with Harvestable spanner. 
1) 1st image below shows the error message in that shows up in the console.
2) Errors occurs in file NavMeshEntityMovement.cs line contining "CacheNavMeshAgent.isStopped = false;" and "CacheNavMeshAgent.SetDestination(position);" See second image
3) Shows navmesh overlay in the spawning area (Purple sphere)
4.1) (Question) Are you aware of this issue ? 
4.2) (Question) Any suggestions on how to resolve this problem ?

![image](https://user-images.githubusercontent.com/66407302/93171153-e4c68c00-f76b-11ea-830e-b01945cfdde6.png)

![image](https://user-images.githubusercontent.com/66407302/93171584-b85f3f80-f76c-11ea-9f32-7a3d16f38e52.png)

![image](https://user-images.githubusercontent.com/66407302/93171811-20158a80-f76d-11ea-9663-f0cce003eae7.png)

**Comment by Skitosh** [comment]
Additional information. Increasing the number of spawned creatures reproduces the error more often. eg noOfSpawns = 100-200

**Comment by insthync** [comment]
This problem occurring while `NavMeshAgent` not on the scene's `NavMesh`, I tried many thing to fix this, 
- It raycast to find ground position from above and below randomed position in `GameArea` -> `GetRandomPosition` function.
- When spawning with `MonsterSpawnArea` it will find grounded position before spawn with `NavMeshEntityMovement`'s function named `FindGroundedPosition`.
- In `NavMeshEntityMovement` -> `FindGroundedPosition`, it's finding grounded position with [AI.NavMesh.SamplePosition](https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html) function
- If [AI.NavMesh.SamplePosition](https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html) cannot find ground position, monster should not be spawned, but it was.

You may try this changes `NavMeshEntityMovement` -> `FindGroundedPosition` codes
To use [AI.NavMesh.Raycast](https://docs.unity3d.com/ScriptReference/AI.NavMesh.Raycast.html) to find ground position from above and below randomed spawn position.
```
        public override bool FindGroundedPosition(Vector3 fromPosition, float findDistance, out Vector3 result)
        {
            result = fromPosition;
            NavMeshHit navHit;
            if (NavMesh.Raycast(fromPosition, fromPosition + Vector3.down * findDistance, out navHit, NavMesh.AllAreas))
            {
                result = navHit.position;
                return true;
            }
            if (NavMesh.Raycast(fromPosition, fromPosition + Vector3.up * findDistance, out navHit, NavMesh.AllAreas))
            {
                result = navHit.position;
                return true;
            }
            return false;
        }
```

**Comment by insthync** [comment]
Another thing that I didn't try yet is to disable navmeshagent on awake and enable it on start (ref: https://answers.unity.com/questions/771908/navmesh-issue-with-spawning-players.html)

Try find `EntityAwake` function in `NavMeshEntityMovement` the replace codes to
```
        public override void EntityAwake()
        {
            base.EntityAwake();
            // Prepare network transform component
            CacheNetTransform = gameObject.GetOrAddComponent<LiteNetLibTransform>();
            // Prepare nav mesh agent component
            CacheNavMeshAgent = gameObject.GetOrAddComponent<NavMeshAgent>();
            CacheNavMeshAgent.enabled = false;
        }

        public override void EntityStart()
        {
            base.EntityStart();
            CacheNavMeshAgent.enabled = true;
        }
```

**Comment by Skitosh** [comment]
Hi Insthync

Thank you for your advice. The recommendation unfortunately does not work as image 1+2 show but I have managed to reproduce the error consistently. It would be great to see if you can reproduce it and add code so that it doesn't cause you more problems. 

Here's how to reproduce the error.
1) Take a look at image 3. The cylinder is a "Monster Character" that uses navmesh. It sits 3.0 y point above the ground and nothing else in the scene is using navmesh (Also nothing is being spawned).
2) I start the game and as you can see on the left of the image the errors show up.
3) After stopping the game, next I lower the cylinder down using "ApplyGravityInEditor.cs" (included below). The cylinder now sits on the terrain.
4) I press run and the game works with no errors. 👍 
5) (Summary) When a "Monster Character" is above the Y navmesh (~3 points) the error occurs.
6) (A task for you) Can you reproduce the problem
7) (Here's a thought) If you look at the very first image lodged with this ticket there are some trees there. My trees have a capsule collider Y=3.64,Radius=0.8,Height=9.01. Given the shape of the terrain and the collider it is possible that sometimes the random spawning location is on top of the tree collider. As a result the spawned monster is >3 units above the terrain, which means it can't utilize the navmap. Hence the error :-) Maybe one way around this would be to utilize layers on gameobjects somehow. Let me know your thoughts ?

Please let me know your thoughts 
Kind Regards
Skitosh



Image 1 (Added code for debugging)
![image](https://user-images.githubusercontent.com/66407302/93277997-c3ff4480-f806-11ea-883f-ad767f617059.png)

Image 2 
![image](https://user-images.githubusercontent.com/66407302/93277974-af22b100-f806-11ea-988d-3056b62d0484.png)

Image 3
![image](https://user-images.githubusercontent.com/66407302/93279932-d5971b00-f80b-11ea-9475-a8716c127301.png)

[ApplyGravityInEditor.cs.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5229021/ApplyGravityInEditor.cs.txt)

**Comment by Skitosh** [comment]
Hi Insthync
There are 3 causes that I have identified that cause this problem and how I resolved them. Please use this information as you see fit.
1) First is using NavMesh.SamplePosition. If GameArea.GROUND_DETECTION_DISTANCE is large sometimes the agent will not attach to the navmesh. I've altered GameArea.GROUND_DETECTION_DISTANCE = 0.1f and altered GameArea.GetRandomPosition() so once random position is chosen it looks for the ground. (See image below). As a result the number of pending in GameSpawnArea<t> is large. Therefore I created an update class in GameSpawnArea<t> which is a copy of LateUpdate() in the class. With time all monsters are generated.
![image](https://user-images.githubusercontent.com/66407302/94094928-06a6c980-fe64-11ea-9605-5ab4945dc4de.png)


2) If agentPosition.y < hit.position.y (hit from NavMesh.SamplePosition) the error can occur. This does occur when you have slopes. Changing agentPosition.y = hit.position.y solves this problem.
3) For some reason sometimes cacheNavMeshAgent.isOnNavMesh becomes false.  To fix this following has to be done cacheNavMeshAgent.enabled = false; cacheNavMeshAgent.enabled = true;. This reattaches the agent to the navmesh. See next image showing my setMovePaths and IsAgentOnNavMesh

![image](https://user-images.githubusercontent.com/66407302/94095568-60f45a00-fe65-11ea-8e01-68c045a097c2.png)

There may be other areas in the code that have similar problems but I don't know the code as well as you do.
Thank you for the help
Skitosh

**Comment by insthync** [comment]
In 1.59, I've changes how to find ground position by move origin from finding position to above before cast the ray down, you should try it.
