### ISSUE TITLE
[Bug]Reload Time Fps

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#598]
The Reload time is not working. I Tested by clip length and fixed time and set Trigger Duration to 1. The animation starts and then you can immediately shoot also when the reload animation still runing. my animation for example goes 4 seconds, but you can start shoot again direct after reload anim started.

anyway what setting you take

**Comment by insthync** [comment]
You set reload animation for FPS character model only or you're already set to Non-FPS model too ?

**Comment by moepi2k** [comment]
its set to fps and tps. because i need both animations.

**Comment by moepi2k** [comment]
i tested it again. when you set reload on default animation it works. there you can add animation and time/trigger.

but:
 when you want set animation and time to weapon animation to set diffrent for each weapon it will not work. 
on fps you can add animation -> this will player when reload but it ignore the time/trigger (means you can directly shoot while still in reload animation)

and in tps: is same for time and also the animation will not play
