### ISSUE TITLE
LiteNetLibVisibleChecker  'Renderer' does not contain a definition for 'forceRenderingOff'

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#599]
I get this error when I import your asset. please help

Assets\UnityMultiplayerARPG\Core\LiteNetLibManager\Scripts\GameApi\LiteNetLibVisibleChecker.cs(104,30): error CS1061: 'Renderer' does not contain a definition for 'forceRenderingOff' and no accessible extension method 'forceRenderingOff' accepting a first argument of type 'Renderer' could be found (are you missing a using directive or an assembly reference?)

**Comment by insthync** [comment]
You have to use Unity version 2019.3 or above to use `forceRenderingOff`

**Comment by shinimaru** [comment]
😯 thank you! My unity client is saying it's up to date but it's not up to that version. Thanks again. That makes sense

**Comment by shinimaru** [comment]
Hey, bro I have a few questions and I'm not sure where to post them so I'll asked them here.

I'm new to anything multiplayer but I plan on making a mmo in the future so...

1. Can the "single player/lan" version of this asset pack function as a purely offline game on mobile or PC? 

I bought this asset pack for the 2d top down arpg and survival game functionality. Plus a bunch of other game play features you advertised like summoning and skill customisation. I'm not planning on making a multiplayer game with them tho. Is there a way to bypass all the server stuff or will it just work internally with single/lan without needing to connect to an outside server for a player to run the game on their device?

2. When I do start work on a multiplayer version of the game, pvp will be the focus. Is that able to be set up with this asset?

It seems like it would be simple to set up even if the asset doesn't have options for a "battleground" type of scene, but as I said I'm completely new to developing anything online multiplayer related.

Thanks for any answers you can give him n advance

**Comment by insthync** [comment]
1. It work as single player game with just start single player game not have to connect to outside server.
2. It can PVP

**Comment by shinimaru** [comment]
Again thank you for the answer. This asset pack will be very useful and more than worth the money when I can start using it.

I won't be able to download a new version of unity any time soon though.

Sorry, another newbie question incoming...

You mentioned setting enable to false to disable rendering... I don't see that on the two scripts that have the error

What script or editor extension are you referring to?

Is there a way to bypass the litenetlib stuff all together? I have read that it was put in recently to solve a problem that I could probably find another work-around to once I can start experimenting. Lol I don't really need trees in my scenes lol or I can just make a flat picture of a tree with a collider or something. I'm not sure I even need that more recent update...

**Comment by insthync** [comment]
> You mentioned setting enable to false to disable rendering... I don't see that on the two scripts that have the error

I means in to check codes from 
```
        public override void OnServerSubscribingAdded()
        {
            base.OnServerSubscribingAdded();
            if (SystemInfo.graphicsDeviceType == GraphicsDeviceType.Null)
                return;
            Renderer[] renderers = GetComponentsInChildren<Renderer>();
            for (int i = 0; i < renderers.Length; ++i)
            {
                renderers[i].forceRenderingOff = false;
            }
        }

        public override void OnServerSubscribingRemoved()
        {
            base.OnServerSubscribingRemoved();
            if (SystemInfo.graphicsDeviceType == GraphicsDeviceType.Null)
                return;
            Renderer[] renderers = GetComponentsInChildren<Renderer>();
            for (int i = 0; i < renderers.Length; ++i)
            {
                renderers[i].forceRenderingOff = true;
            }
        }
```
To
```
        public override void OnServerSubscribingAdded()
        {
            base.OnServerSubscribingAdded();
            if (SystemInfo.graphicsDeviceType == GraphicsDeviceType.Null)
                return;
            Renderer[] renderers = GetComponentsInChildren<Renderer>();
            for (int i = 0; i < renderers.Length; ++i)
            {
                renderers[i].enabled = true;
            }
        }

        public override void OnServerSubscribingRemoved()
        {
            base.OnServerSubscribingRemoved();
            if (SystemInfo.graphicsDeviceType == GraphicsDeviceType.Null)
                return;
            Renderer[] renderers = GetComponentsInChildren<Renderer>();
            for (int i = 0; i < renderers.Length; ++i)
            {
                renderers[i].enabled = false;
            }
        }
```
