### ISSUE TITLE
please help creating new armor :(

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#60]
Please help me.My main character is unsuccessful in armor dressing.I've tried all kinds of methods but each time comes as T pose.The character and armor are not at fault.

https://gyazo.com/dde5db9a3eef9c5d17997d17df074df8

https://gyazo.com/5b62d70f6c4de3a6ae338980fa52dbb6

https://gyazo.com/ac0c2be66d91e1ffb514fa30398a9ffc

https://gyazo.com/1a6c05416e17e3e9ad0b12e13f68d9ae

**Comment by fedas61** [comment]
o brom mobil mt2 mi yapıyon :D

**Comment by kazuden** [comment]
> o brom mobil mt2 mi yapıyon: D

aynen. ama bu paket baya zayıf. çok eksikleri var.

**Comment by fedas61** [comment]
yanide birebir mt2 sistemleri olmaz  benim aklımdaydı ama metin2 ye benzetilmesi zor sistem yönünden model-map-Uı benzetirsinde yazılımsal olarak el atman lazım

**Comment by fedas61** [comment]
discordda Sensei61 kullanıcı adım birşey danışmak istersen bildigim kadarıyla yardımcı olmaya calışırım

**Comment by kazuden** [comment]
> yanide birebir mt2 sistemleri olmaz benim aklımdaydı ama metin2 ye benzetilmesi zor sistem yönünden model-harita-Uı benzetirsinde yazılımsal olarak el atman lazım
benzememişmi :)
https://gyazo.com/7b705be027e70f3c4227dd8787af746e

**Comment by fedas61** [comment]
adamlar benzetmiş

**Comment by kazuden** [comment]
> adamlar benzetmiş

bunu ben yaptım benim projem :) şuanki durumu

**Comment by fedas61** [comment]
şu yabancıların uğraştığı proje sandım k.b :D Uı bile benziyorya

**Comment by kazuden** [comment]
> şu yabancıların uğraştığı proje sandım k.b :D Uı bile benziyorya
yok onların daha kötü ui. kontrolleri vede ui çok kötü onların. zaten mobil oyunlar birbirine benziyor azda olsa
https://gyazo.com/c109ebd447cc0d1fcaa7a94d55d43069

**Comment by fedas61** [comment]
yolun başındaymışsın bro daha :D işin zor

**Comment by fedas61** [comment]
https://youtu.be/pUPSfXE8m_E 
ben bile basit birşey cıkarmaya calışıyorum 2 ay sürdü :D daha ne kadar sürcek bilmem metin2 ise 3 yıl anca 1 kişi ile biter

**Comment by kazuden** [comment]
mmorpg_kit de sorun olmasa 2 ay içinde biterde daha paket yeni yeni gelişiyor. herşeyde sorun çıkıyor.

**Comment by fedas61** [comment]
aynen

**Comment by insthync** [comment]
You can learn how to make bone weight for your cloth from this video https://www.youtube.com/watch?v=rzau6SFcNOk&list=PLFt_AvWsXl0f4c56CbvYi038zmCmoZ4CQ&index=9
