### ISSUE TITLE
latest update broke one of my scripts.

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#601]
Is there anyway to reference the CacheUISceneGameplay from inside UISceneGameplay? If you could show me an example that would be great!

**Comment by insthync** [comment]
I don't understand your problem, what and how it is broking your scripts?

**Comment by Fallen01** [comment]
bool isPointerOverUIObject = CacheUISceneGameplay.IsPointerOverUIObject(); this breaks my script specifically

**Comment by Fallen01** [comment]
i was loading a different UI from the UI itself it was working fine but after the update my controller blows up and my script no longer works.

**Comment by Fallen01** [comment]
Instantiate(characterDb.ClassUIPrefab.DesktopUIPrefab); this used to work from UISceneGameplay now its doesnt and im having great difficulty fixing it.

**Comment by insthync** [comment]
`CacheUISceneGameplay` in `BasePlayerCharacterController` right?

It will be instantiated in `BasePlayerCharacterController` -> `Setup` function

I don't know when you are going to instantiate your character class UI, and what is actually problem.

**Comment by Fallen01** [comment]
i instantiate it on awake in UISceneGameplay.cs which did in fact used to work.  It seems the pointer detection gets very angry now.

![Example](https://user-images.githubusercontent.com/57778639/93280548-ec038f00-f797-11ea-8324-2c3c7965efd3.PNG)

**Comment by Fallen01** [comment]
![Example](https://user-images.githubusercontent.com/57778639/93280623-19e8d380-f798-11ea-97df-ddfaefc7e1a7.PNG)

**Comment by insthync** [comment]
No error when instantiate `UISceneGameplay` ? 

It seems like `UISceneGameplay` was not instantiated

**Comment by Fallen01** [comment]
its not anymore no the UI doesnt appear and im unable to move cause the controller blew up to.

**Comment by Fallen01** [comment]
also i posted the error it throws now above along with the exact reference it gives me.

**Comment by insthync** [comment]
May I try on your PC with TeamViewer ? (If can, send info to my email: ittipon.bay@gmail.com)

**Comment by Fallen01** [comment]
sent and thank you

**Comment by Fallen01** [comment]
Issue resolved, thx again for being the best :)
