### ISSUE TITLE
[Bug]Ammo Capacity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#603]
When u set Ammo Capacity on weapon for eg 6. and put some ammo in inventory also, then create new character and login, in the magazinr are 12. then you can shoot and afer reload you only have the set capacity for eg 6 in this example.

**Comment by moepi2k** [comment]
this issue happen only when you set a the weapon in hand as starter weapon. thant when login he reload also when magazine is already full. so it double it

**Comment by insthync** [comment]
Try 1.59, it should be fixed
