### ISSUE TITLE
Suggestion: Comparison of items

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#605]
For example, in the inventory, we clicked on the "Helmet" item. A tooltip with the characteristics of this helmet has opened. Can you make the tooltip of the item equipped in this slot additionally open? The concept on the screenshot.

![image](https://user-images.githubusercontent.com/47291794/93660772-015c1000-fa5b-11ea-999a-d06352453b39.png)

**Comment by insthync** [comment]
Added to 1.59
