### ISSUE TITLE
Client / Server separation

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#606]
Creating a client from ur game has potential for people to basically steal ur game and make their own.
you can reverse engineer the Files in Data  > Managed and see everything.
Down to every single Server code and scripts etc.
this is a problem as anyone can basically make a private server or basically steal the kit and make their own game just from a demo or a client.

is it possible to implement a Client only project that would essentially prevent this? 
even if they reverse engi the code they will only see client stuff .. not server logic

OR add #if defs for code stripping 
basically a form of protection against this

this images are basically the dll files in the builded project.
![image](https://user-images.githubusercontent.com/7702658/93664691-20659c80-fa71-11ea-9dee-38fbb8dfa5c1.png)

![image](https://user-images.githubusercontent.com/7702658/93664697-26f41400-fa71-11ea-92f0-58b97041c8eb.png)

![image](https://user-images.githubusercontent.com/7702658/93664702-2d828b80-fa71-11ea-895f-39ba3d9e0bd5.png)

![image](https://user-images.githubusercontent.com/7702658/93664710-3d01d480-fa71-11ea-9660-f08ca033c2d4.png)

![image](https://user-images.githubusercontent.com/7702658/93664717-44c17900-fa71-11ea-8721-72ed6af02565.png)

**Comment by Serivatech** [comment]
Are you doing everything right?
Server:
![sample1](https://user-images.githubusercontent.com/56482598/93669928-149dc880-fab9-11ea-9b85-b72f8abefbb3.png)

Client:
![sample2](https://user-images.githubusercontent.com/56482598/93669931-1cf60380-fab9-11ea-9e53-b9fa8bd3c0c5.png)

This is from my project, but I think it will be clear.

**Comment by Callepo** [comment]
@Serivatech think u didnt understand the issue that i Mentioned.. i have no issues with creating a server or a client... im theone people ask in discord for setting up server.

The problem here is ecen if u use client only init (which is the same as every other init, just without the serverinstance prefab that makes it possibly to use command line to start server.)

The build itself is basicaly the same anyways .. and using softwares to read the dll files in the data folder u can see every line code every file in the project..i can see the server logic by reverse engineering any client

**Comment by Callepo** [comment]
@Serivatech @insthync 
There literaly a video about this 
https://www.youtube.com/watch?v=c1MyTJVf7AU&feature=emb_logo

i need  to check if this asset could pull of what i mentioned here

**Comment by Callepo** [comment]
is IL2CPP possible?

**Comment by insthync** [comment]
Can add #if defs for code stripping, for some net functions which will runs at server only for example 
```
// Codes for BasePlayerCharacterEntity

        protected void NetFuncUseItem(short itemIndex)
        {
#if !CLIENT_BUILD
            if (!CanUseItem())
                return;

            if (itemIndex >= nonEquipItems.Count)
                return;

            CharacterItem characterItem = nonEquipItems[itemIndex];
            if (characterItem.IsLock())
                return;

            IUsableItem usableItem = characterItem.GetUsableItem();
            if (usableItem == null)
                return;

            usableItem.UseItem(this, itemIndex, characterItem);
#endif
        }
```

Will stripped to 

```
        protected void NetFuncUseItem(short itemIndex)
        {
        }
```

You also can use an Obfuscator plugins to makes codes harder to read. I will try IL2CPP build later.

**Comment by Callepo** [comment]
can this be part of the kit? the #if.. me adding it manually every update gonna be alot of work
and yes im planning on using obfuscator but its not 100% effective

**Comment by insthync** [comment]
I will do it

**Comment by Callepo** [comment]
i know this is not ur fault.. its simple unity builds that are the issue, it shouldnt be this easy to read everything
But ty

**Comment by insthync** [comment]
In 1.59 you can add `CLIENT_BUILD` to `Scripting Define Symbols` setting to don't include some server codes when building.
