### ISSUE TITLE
Resurection skill

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#607]
This doesnt work or i have no idea how to use it..
tried doing it in party.. nothing.. 
standing on the dead.. nothing
select the player before he dies.. when he dies the target is removed.. and nothing.. 
U cant target the dead

how are u supposed to ress people ?

or the skill is just broken

**Comment by insthync** [comment]
Have to fix controller, it's currently can't select dead characters.

**Comment by Callepo** [comment]
ok cool i thought i was doing something dumb.
Good to know

**Comment by insthync** [comment]
Try 1.59, it should be fixed
