### ISSUE TITLE
Difficulty retrieving data

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#608]
![zz](https://user-images.githubusercontent.com/57778639/93709788-42156100-fb0f-11ea-864b-2572d081a7bd.png)
![ff](https://user-images.githubusercontent.com/57778639/93709789-45a8e800-fb0f-11ea-986d-746a30d62754.PNG)

"Im trying to retrieve the category string from the scriptable from where its stored."

It lights up as if it will work but always results in this error. Im new to trying to work like this and obviously Im doing something wrong. If you would be so kind as to tell me where Im screwing up I would be very thankful.

Thx for your time.

**Comment by insthync** [comment]
`uiPlayerActivateMenu` will be used to show: party invitation, guild invitation, deal request and so on.

`uiPlayerActivateMenu.Data` will be set when activate (Press E) on another character to set data of character which player activating.

So I will be `null` on awake.

**Comment by Fallen01** [comment]
Having trouble finding a reference that one lit up, what should i use?

**Comment by insthync** [comment]
Try get character entity with `BasePlayerCharacterController.OwningCharacter`

**Comment by Fallen01** [comment]
worked like a charm thank you!
