### ISSUE TITLE
vanilla install + UMA extension 'ResponseSelectCharacterMessage' does not contain a definition for 'connectKey' 

### ISSUE THREAD

**Issue by rickcollette** [suriyun-production/mmorpg-kit-docs#61]
Following the instructions in the documentation; I get the following error:

Assets/UMAExtension/Scripts/MMO/UI/UIMmoCharacterListUMA.cs(121,160): error CS1061: 'ResponseSelectCharacterMessage' does not contain a definition for 'connectKey' and no accessible extension method 'connectKey' accepting a first argument of type 'ResponseSelectCharacterMessage' could be found (are you missing a using directive or an assembly reference?)

**Comment by insthync** [comment]
Okay, I just made version 1.06 package, try it
