### ISSUE TITLE
[Bug]ShooterController Zoom Ability

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#610]
When use zoom with a weapon and while zooming switch weapon, then the zoom is still active. i also noticed that when zooming the mouse move is unsmooth.

**Comment by moepi2k** [comment]
p.S it would be great when you can add a new Field for animation when player use zoom. :) must have for shooter games :)

**Comment by insthync** [comment]
Zooming animation for Third-person character model or First-person ?

**Comment by insthync** [comment]
About FPS mode not smooth, I think I should change how to instantiate FPS hand model, now it will instantiate as character's children, I think it should be camera's children.

**Comment by insthync** [comment]
The FPS Model should be instantiated from `CharacterModelManager` -> `fpsModelPrefab` as gameplay camera transform child, it should smooth when camera move, as I see your video from previous issues post, it seems like the hand model not attached gameplay camera transform child.

**Comment by moepi2k** [comment]
Animation fields for tps and fps. so when you use the zoom ability you can add an animation for it like when zoom you put your gun more infront of your head or something like that.

``_The FPS Model should be instantiated from CharacterModelManager -> fpsModelPrefab as gameplay camera transform child, it should smooth when camera move, as I see your video from previous issues post, it seems like the hand model not attached gameplay camera transform child._``

in tps it works. while zoomed and switch weapon it smooth go out. but not in fps.

my fpsarms are attached to my player prefab ->CharacterModelManager -> fpsModelPrefab
and in PlayerCharacterEntity i attached player head to FpsCameraTargetTransform Field so when switch to fps, shootercamerea will switch to that transform.

**Comment by insthync** [comment]
About hand model, it will instantiate like this
![Screenshot_82](https://user-images.githubusercontent.com/2697550/94099086-45348800-fe54-11ea-81b7-0a8a65c3157d.png)

And it must smooth while moving camera because it was attached and stick to camera.

**Comment by moepi2k** [comment]
it is like your picture -> 
![fpsarms](https://user-images.githubusercontent.com/2422714/94116336-31385880-fe4b-11ea-8cb6-229d5e6063bf.png)

the fps arms are smooth. that was not the problem. i meant when you use SniperZoom, but decreasing RotationSpeedSclaeWhileZoom fixed the problem.

here a video with the problem. when use button to switch weapons while zoomd, zoom will remain 
https://youtu.be/neFyZz6YjPc
on tps it works fine. when you zoomd and use inventory it also works. but not when switching weapons

**Comment by insthync** [comment]
Try 1.59, it should be fixed
