### ISSUE TITLE
Changing 3d skills to 2d skills

### ISSUE THREAD

**Issue by shinimaru** [suriyun-production/mmorpg-kit-docs#611]
I pretty much want to make 2d versions of all the 3d skills already in the asset and then continue making and adding more 2d skills.

The problem is Im not sure what causes a skill to be used in the 2d scene in skill list or as a drop.

The guide says put the skill in a resource folder but the 3d skills are in same resource folder as some of the 2d skills already. 

1. What is causing the 2d skill list to pick up some skills from the resource folder and not the other?

2. If used as a drop, will the skill automatically be added to the in-game skill list when picked up? 

2d. Will the skill point system still work or be required for the picked up skill?

**Comment by Fallen01** [comment]
they mostly seem to work despite obvious differences. Like a summoning skill needs a 2d entity not a 3d entity. FX are different in 2d as well, but ive found for the most part the skills seem to work. Skills are loaded into the class scriptable found under data in player character in the 2d demo folder. If you examine the class scriptable you will see where skills are added to the game. I hope this answers some of your questions.

**Comment by shinimaru** [comment]
Yeah I actually found it a few days ago. But thanks for the answer. This asset pack has everything I needed. Already made some new skills and a boss battle and a quest chain and branching story lines. Now I just gotta get the food/water system and harvesting systems working on 2d and I will have everything I need to start my empire lol. Yes thank whoever made this
