### ISSUE TITLE
[BUG] Hotkeys FilterSkills and nonEquiped items

### ISSUE THREAD

**Issue by Xentar** [suriyun-production/mmorpg-kit-docs#612]
Hey Suri.
Found 2 little errors on the hotkeys.
1- UICharacterHotKey.cs on line 322, should be False, or just don't filter the skill type. (noticed because it was showing the passives)
2- For some reason i still don't find out, i can add weapons and armors, but they show the icon just if i equip them. Tested on last version clean and modded project.

**Comment by Zaraath1** [comment]
I mentioned this in discord.   Weapons and armor are filtered to show on hotkeys on standalone and action buttons on mobile but don't show.   If you equip the own after trying to add it to the bar,  it will add the icon,  but revert once the item is unequipped.

**Comment by insthync** [comment]
@Xentar I was fixed them, it will be included in next version. Thank you for bug report :).

@Zaraath1 Please post all bug report in this issues board here, I didn't enter Discord for a long time.

**Comment by Xentar** [comment]
My pleasure, going to try to report anything i find. Thanks!
