### ISSUE TITLE
[Suggestion]Hitbox for Survival/Shooter Fps

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#613]
It would be great when its possible to add diffrent hitboxes for player/enemies. in a shooter usualy there are minimum 3 hitbox types like body, legs/arms and head.
 
i dont know how to achieve this but an idea is when you can add collider to bone of skeleton and then change resistance for it or something like that?

**Comment by insthync** [comment]
There is a `CharacterHitBox` component, attach it to each parts with collider, you can set `damageRate` to 2 to head part, then it will  receives 2x damage, or 0.25 to any feet part to receives lower damage.

**Comment by moepi2k** [comment]
amaaaaaazzzzziiiiiing. i never seen this component before 👍 👍 👍 
this kit is so great 

what does the DamageableHitbox do?

**Comment by insthync** [comment]
It's like `CharacterHitBox` but made for building, harvestable entities, `CharacterHitBox` was made before `DamageableHitBox`, I might move functionalities from `CharacterHitBox` to `DamageableHitBox` later and make it work the same way for every damageable entity

**Comment by moepi2k** [comment]
Alright. i tested the CharacterHitBox on enemie, it works great. but when i put it on my player and test, projectiles dont collide or make damage. only melee make dmg, but i dont know what melee triggers, the new hitbox colliders or the capsule collider from parent player object.

![collider](https://user-images.githubusercontent.com/2422714/94126701-39e35b80-fe58-11ea-8f2c-ad8dc8f3c094.png)

becuase you cant delete capsule collider on parent object. its depends on RigidBodyEntityMovement and OpenCharacterController component. so whats best idea? just disable it or shrink it to 0, 0, 0?

**Comment by insthync** [comment]
If there is any `CharacterHitBox` attached to character, capsule collider will not being used to receives damage, but still use it for mouse picking, find character nearby and so on.

**Comment by moepi2k** [comment]
ok great, but then maybe is an other issue why CharacterHitBox not work on Player. i test it now also with fresh kit

**Comment by moepi2k** [comment]
ok tested on fresh project. when adding CharacterHitBox on players, it not work for projectiles like Missile or Raycast. only for melee

**Comment by insthync** [comment]
Try 1.59, it should be fixed
