### ISSUE TITLE
Character race addon

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#615]
Include the addition of the character's race in the kit. There are more people who need this functionality than those who do not need it. It makes no sense to make it a separate addition, those who do not need it can simply delete the extra races.

**Comment by Callepo** [comment]
there's alot more that dont use it then do tbh..
but u just import 1 thing and its done ?
but whatever maybe to me its simple af

**Comment by Serivatech** [comment]
Is there a reason why this is a separate addition?

**Comment by Callepo** [comment]
Same as Uma, Topdown etc and the others 
just not part of the kit.. but there if u want them  or need them
More people use uma than they use race but uma aint part of the kit 
i dont know his exact reasoning, but its still accesable to everyone in Community addons

**Comment by insthync** [comment]
Okay, I accepted this request, in next version it will include race.

**Comment by insthync** [comment]
Moved to core project in 1.61b update
