### ISSUE TITLE
[Bug]CharacterHitBox component still not work on players

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#616]
the hitboxes still not work on players only on enemies.
i tested in pvp with missile or raycast, it never collide on it.

**Comment by insthync** [comment]
So missile damage entity from player not hit other players, right ?

**Comment by moepi2k** [comment]
exactly. missile and raycasts dont hit other players

**Comment by insthync** [comment]
Try 1.59b

**Comment by moepi2k** [comment]
no still not working.
i noticed now that there is another component UnHittable. i think this need to be attached on main playerp prefab to avoid colliding with the main collider.

i tried now also with this and its not working

-> another thing. is there maybe an option to get git access for licensed user? would be great to following update steps for learning new stuff or just to know what exactly changed

**Comment by insthync** [comment]
I am now doubting why it's not working, may I try your project on your PC/Mac via TeamViewer?

**Comment by moepi2k** [comment]
sure, i send data to you in discord

**Comment by insthync** [comment]
Send it to my email : ittipon.bay@gmail.com
