### ISSUE TITLE
1.59b PickUp all button

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#617]
I created a button for pick up all. The character does exactly the same animation as when picking up an item, but items do not loot.
![image](https://user-images.githubusercontent.com/47291794/94581043-46feb100-0283-11eb-9d5a-1a15d7d64d97.png)
Is the function not working or am I doing something wrong?

**Comment by insthync** [comment]
Fixed in 1.59c
