### ISSUE TITLE
Bag in 1.59b

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#619]
When pressed, most gear in Item 2 windows fall out!
Version 1.59 update to 1.59b 
Examples:
![1bug](https://user-images.githubusercontent.com/16080577/94703042-1aac6880-0347-11eb-9ace-3081ae7bd8af.jpg)
And here I pressed the bow, and received both a bow and a sword!
![2bug](https://user-images.githubusercontent.com/16080577/94703166-39aafa80-0347-11eb-9339-823bbf3577df.jpg)

**Comment by Zaraath1** [comment]
Pretty sure that's the compare feature.   You clicked on the bow and have that sword equipped.   The armor doubled because you had one on and one in bag.   Unless I'm missing what you are pointing out.

**Comment by insthync** [comment]
It is equipment comparison as @Zaraath1 says.
