### ISSUE TITLE
Entity can take damage from spawn/warp below 0y

### ISSUE THREAD

**Issue by clapplegate** [suriyun-production/mmorpg-kit-docs#620]
Players and creatures can take damage if ground and warp are set below 0y while also being above the instant death height.
To reproduce lower ground on Map002 to 0, -35, 0
Change warp portal database entry to 0, -34.5, 0
Create new character and warp to Map002
The player spawns at ground height but still takes damage as if they fell from 0,0,0

**Comment by Zaraath1** [comment]
Go in to your map asset settings,  there is a fall height variable you plug in.

**Comment by moepi2k** [comment]
i think he dont mean the Dead Y option. i dont understand his question. why should you dont take damage below y0? its normal that you take damage when you fall for 35 units.

**Comment by clapplegate** [comment]
you shouldn't be falling for 35 units if you're supposed to spawn(and do) spawn 0.5units above the terrain
