### ISSUE TITLE
Character rotation around the creature

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#621]
hi why is  player spinning around the beast?  (02-04)
This does not happen when we act ourselves, but only when you press the attack button.
[bandicam 2020-10-02 11-54-40-629.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5316923/bandicam.2020-10-02.11-54-40-629.zip)

**Comment by fedas61** [comment]
[bandicam 2020-10-02 12-29-00-183.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5317079/bandicam.2020-10-02.12-29-00-183.zip)

**Comment by insthync** [comment]
I want some info about your character entity, which entity movement are you using? `NavMeshEntityMovement` or `RigidBodyEntityMovement`. I also want to see colliders which attached on the character entity, please capture screenshot. And Damage settings  capture screenshot of weapon type setting which character equipping like this

![Screenshot_85](https://user-images.githubusercontent.com/2697550/94909925-178fb480-04ce-11eb-9c16-76b9675f61e5.png)

**Comment by fedas61** [comment]
I use rigidbodymovement
but when the open character controller turns into player, the character does not move, so I remove it
![image](https://user-images.githubusercontent.com/46999478/94910587-97f1ed80-04ad-11eb-9b9b-5dde03ff1428.png)

**Comment by fedas61** [comment]
There was some improvement when the Distance value changed to 1
but there is some problem
![image](https://user-images.githubusercontent.com/46999478/94910924-0f278180-04ae-11eb-9c52-e6ea040fa93d.png)

**Comment by fedas61** [comment]
i fixed it
thanks.
