### ISSUE TITLE
1.59b - Namespace problem

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#622]
![image](https://user-images.githubusercontent.com/62859548/94997118-69593d00-05a9-11eb-9e50-fb174b04834c.png)

Hi since i tried to updated to the latest version i'm having this error and can't fix it neither by reimporting neither by other ways.

Do you have any idea of where this might be coming from and how to fix it ?

**Comment by insthync** [comment]
Try delete SerializableCallback  folder (Assets\UnityMultiplayerARPG\Core\SerializableCallback) then re-import the package.

**Comment by sawcisson** [comment]
Managed to make it work by deleting every single folder that contained scripts and reimporting it.
MMO folder was also a problem.

Now i have this problem when i start my init scene 
![image](https://user-images.githubusercontent.com/62859548/95003583-fd92c680-05e0-11eb-9b82-092e9a986676.png)

Do you  have some ideas of where that's coming from ?

**Comment by insthync** [comment]
May I check your project on your device by TeamViewer?

**Comment by sawcisson** [comment]
Yes we can do that, how do you want to set it up ?
Maybe we can schedule a call ?

**Comment by sawcisson** [comment]
After many attempts and reimports and transfer and backup loading 
It finally worked
