### ISSUE TITLE
Spawned dropitem don't render

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#625]
![image](https://user-images.githubusercontent.com/62859548/95021665-a2a9af80-0672-11eb-8c5d-29a2fe3b53e1.png)

For some reason the 3D model isn't showing up.

**Comment by insthync** [comment]
Maybe the `RedMushroom`  attached `GridVisibleChecker` while your character attaching `GridVisibleChecker` or other `LiteNetLibVisibleChecker`, check your character entity and the mushroom which visible checker was attached ?

**Comment by sawcisson** [comment]
i see, should we upgrade everything to gridvisiblechecker or can we keep use litenetlibvisiblechecker ?

**Comment by insthync** [comment]
Changes to Grid visible checker will also get better performance

**Comment by sawcisson** [comment]
Allright, i'm upgrading from 1.55 so a lot of things have changed, a lot of custom code aswell etc.
Trying to get back on tracks on what you changed and improved.

Thanks for the help
