### ISSUE TITLE
Problems warping

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#626]
Would there be any reason i may be overlooking to why i cant tp to a map in instance mode in mmo.. 
but if its normal it works fine
this the message that gets spammed when its instanced.
Test default kit and instance works fine..
but ive had instance working before and everything.. it suddenly stopped..i cant find a good reason to why it would
![image](https://user-images.githubusercontent.com/7702658/95243111-7035b900-0810-11eb-846a-674abf2fbb72.png)

**Comment by insthync** [comment]
I will check it
