### ISSUE TITLE
Problems after update to last version

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#628]
![image](https://user-images.githubusercontent.com/47291794/95456449-00424280-0978-11eb-9b7f-807bf923e35e.png)
What could have happened?

**Comment by insthync** [comment]
Delete Item_Refine, Item_Repair because it was renamed to BaseItem_Refine, BaseItem_Repair

**Comment by DimasjkTV** [comment]
> Delete Item_Refine, Item_Repair because it was renamed to BaseItem_Refine, BaseItem_Repair

Thanks! I removed these and a few more scripts. That helped
