### ISSUE TITLE
1.59b BUG: ItemRefine 

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#629]
If an item is needed to enhance an item, but it is not in the inventory, then the requirements for enhancing the item are not displayed. The required gold is written 0, although 100 is needed. As soon as the required item for enhancement appears in the inventory, the requirements are displayed normally. See video.
![image](https://user-images.githubusercontent.com/47291794/95469481-60d97b80-0988-11eb-9669-ed2291be128a.png)
![image](https://user-images.githubusercontent.com/47291794/95469551-7484e200-0988-11eb-9334-a7053f1e5ace.png)

[1.59b refine tooltip bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5348391/1.59b.refine.tooltip.bug.zip)

**Comment by insthync** [comment]
Fixed in 1.59c
