### ISSUE TITLE
please help me. there may be system error

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#63]
I want to add a new armor or dress to the character. the result fails.I wanted to add the dress above the character's own. result failed.I thought the character had a bone mismatch, but he did not accept the dress on the character.does not even accept their own plug-in.I think this could be a system error.please watch the video.Tell me where I made a mistake.than you. I love you :)

https://youtu.be/OAdJSYQKr_Y

**Comment by insthync** [comment]
Did you set skinned mesh renderer in character model?

**Comment by kazuden** [comment]
> Did you set skinned mesh renderer in character model?

yes.

**Comment by insthync** [comment]
There are many thing I have to check out, can you capture video how you set up your character and clothes, I want to see all settings

**Comment by kazuden** [comment]
> There are many thing I have to check out, can you capture video how you set up your character and clothes, I want to see all settings

https://youtu.be/qmfJDX8A9Ls

**Comment by insthync** [comment]
Thank you, I will check it

**Comment by insthync** [comment]
Try set this 
![Screenshot_51](https://user-images.githubusercontent.com/2697550/62531196-2a780c00-b86c-11e9-8f81-75b3dbf1981d.png)

**Comment by kazuden** [comment]
> Try set this
> ![Screenshot_51](https://user-images.githubusercontent.com/2697550/62531196-2a780c00-b86c-11e9-8f81-75b3dbf1981d.png)

you are a great friend. thank you.

**Comment by kazuden** [comment]
problem solved
