### ISSUE TITLE
1.59b BUG UIDamageElementAmounts GUI

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#632]
Again, elemental damage is not displayed individually as is the case with resistances. This worked fine in previous versions. Instead of 0%, there should be 3-5 fire damage
![image](https://user-images.githubusercontent.com/47291794/95594126-31dc0c00-0a53-11eb-8991-3c315c2cdddc.png)
![image](https://user-images.githubusercontent.com/47291794/95594179-45877280-0a53-11eb-9089-f615fb241d49.png)

**Comment by DimasjkTV** [comment]
I added a code to UIDamageElementAmounts and this fixed my problem

Line 48
public UIDamageElementAmounts uiCharacterElementalDamages;

Line 443

if (uiCharacterElementalDamages != null)
            {
                uiCharacterElementalDamages.isBonus = false;
                uiCharacterElementalDamages.Data = cacheDamages;
            }

**Comment by insthync** [comment]
Thank you, it will be included in next version

**Comment by DimasjkTV** [comment]
> Thank you, it will be included in next version


I confused the names of the scripts. UICharacter.cs in this script i added a code
