### ISSUE TITLE
[Bug]Building Entity Layers

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#633]
There is an issue with Building Entity parts. The Slots (marked in picture) for snaping eg walls using same layer (Building) as the main object. The Problem is then the projectiles are colliding with it. When you change layer for slot then snapping no longer works.

![Building](https://user-images.githubusercontent.com/2422714/95612540-d5cdb380-0a63-11eb-8638-07f5f41378f2.png)

best way would be to that slots are in a new layer that ignores raycast. 

another issue is when you build for example a foundation. then aim to the wall slot it will target as foundation. so slots should also ignore target marking.

![target](https://user-images.githubusercontent.com/2422714/95612694-1af1e580-0a64-11eb-96b4-80000cd2ee70.png)

**Comment by insthync** [comment]
Try find `IUnHittable` component from game object, if found it, don't apply damage.

**Comment by moepi2k** [comment]
i tried this, it still collider with it and projectile destroy (tried with default BowDamageEntity). also the issue with targeting will not solve with it. when you aim on a Slot the main Gameobject (Foundation in this case) will be targeted

**Comment by insthync** [comment]
> could it be that this Component only works when its on Parent object?

No it should works when it's on children object too.

**Comment by moepi2k** [comment]
Okey, then there is an other issue, i will check it on fresh project

**Comment by insthync** [comment]
May try add 
```
                if (tempHitInfo.collider.GetComponent<IUnHittable>() != null)
                {
                    // Don't aim to unhittable objects
                    continue;
                }
```
Into `ShooterPlayerCharacterController.cs` in find aim position loop like this

![Screenshot_95](https://user-images.githubusercontent.com/2697550/95655899-be123000-0b34-11eb-8b48-768d92ba8b98.png)

**Comment by moepi2k** [comment]
ok sorry, i tested in fresh project, there everything is okey. i need to check whats wrong here :/

**Comment by moepi2k** [comment]
okok sorry thats a bit stupid, but i need to reopen this report. the thast before wa on my computer. fresh project and everything worked.

now i tested it on my laptop again. also fresh project. Same unity version on computer and laptop (2019.4.1f1) 
and i got this issue :///

https://youtu.be/6-U2JLb5Zu4

here a video

how can this happen?

**Comment by moepi2k** [comment]
alright,

i figured the bug out. the problem was on my computer. in asset stores id showed me 1.59b. but it downloaded an older version. maybe 1.58. 

the thing now is:

in 1.58 the bug with targeting building slots is not there everything before 1.59 or 1.59b worked. but with the new version we have the bug with targeting like in picture above post.

this 

` if (tempHitInfo.collider.GetComponent<IUnHittable>() != null)
                {
                    // Don't aim to unhittable objects
                    continue;
                }`

will fix it.

another thing. when i dont use the code above and shoot projectiles and there is the foundation as target. projecitles go in other way as usual. same as the bug with dead enemys when you shoot them, projectiles goes everywhere but not straight.

here small video of projectiles:  https://www.youtube.com/watch?v=3_KxiKg_Wrw

why does this happen, and any idea why the foundation slot target worked in previous versions?

**Comment by insthync** [comment]
Please try 1.59c

**Comment by moepi2k** [comment]
Works
