### ISSUE TITLE
MySQL Issue?

### ISSUE THREAD

**Issue by Monty001** [suriyun-production/mmorpg-kit-docs#634]
Noticed I was getting exceptions thrown by the server build on MySQL when equipping an offhand item, seemed to come from this function

MySQLDatabase_CharacterItem.cs

       public async UniTask CreateCharacterEquipWeapons(MySqlConnection connection, MySqlTransaction transaction, byte equipWeaponSet, string characterId, EquipWeapons equipWeapons)
        {
            await UniTask.WhenAll(
                CreateCharacterItem(connection, transaction, equipWeaponSet, characterId, InventoryType.EquipWeaponRight, equipWeapons.rightHand),
                CreateCharacterItem(connection, transaction, equipWeaponSet, characterId, InventoryType.EquipWeaponLeft, equipWeapons.leftHand)); 
        }

The exception linked to a mysql page which basically said, maybe to do something like 

  
      public async UniTask CreateCharacterEquipWeapons(MySqlConnection connection, MySqlTransaction transaction, byte equipWeaponSet, string characterId, EquipWeapons equipWeapons)
        {

            await CreateCharacterItem(connection, transaction, equipWeaponSet, characterId, InventoryType.EquipWeaponRight, equipWeapons.rightHand);
            await CreateCharacterItem(connection, transaction, equipWeaponSet, characterId, InventoryType.EquipWeaponLeft, equipWeapons.leftHand));
        }

This seemed to fix this issue, not sure if it effects all MySQL / theres just something dodgey with my setup.

**Comment by insthync** [comment]
Thank you, that is correct way to fix

**Comment by insthync** [comment]
Fixed in 1.59c
