### ISSUE TITLE
[Bug]Recoil

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#636]
First, thank you for adding this :-)

to the bug. i made a video, its easier to understand.

problem is in multiplayer. for the server/hoster it works (left side)
for client, the projectile goes in the direction after recoil. its just visual (serverside it goes right) 
it looks/feels bit weird :)

https://youtu.be/AsWGOiFDMT4

**Comment by brabaris** [comment]
You have a shell flying out of the camera ...

**Comment by moepi2k** [comment]
?

**Comment by moepi2k** [comment]
You can also add the EquipmentEntity component and attach a MissileDamageTransform. the issue is the same.
on clients the projectil effect fly in false direction (that one after recoil)

**Comment by moepi2k** [comment]
i have a temporary fix for it. just add a delay like 

`public void Recoil(float strength)
    {
        float tempVelocity;
        tempVelocity = strength;
        StartCoroutine(DelayedRecoil(strength));
    }

    IEnumerator DelayedRecoil(float strength)
    {
        yield return new WaitForSeconds(0.05f);
        xVelocity += strength;
    }`

but i think  this is not a clean solution.
because when a clients ping is higher it not works (i think the issue comes because of ping between server/client) like client shoot - instantly camera goes up(recoil) then server validate projectile flytime and spawns, during this time the camera is already on new position and projectil fly in false direction. thats what i thinkg is the issue, but maybe im wrong and you have idea what it is.

**Comment by insthync** [comment]
I will fix it by make it applies recoil force at client when play attack animation (order to play animation by server).

**Comment by moepi2k** [comment]
that is great solution

**Comment by insthync** [comment]
Fixed in 1.59d
