### ISSUE TITLE
Audio Manager issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#637]
If u set a maximum Volume for any of the settings
![image](https://user-images.githubusercontent.com/7702658/95762135-972b3980-0cad-11eb-8e2a-d0d777c9a206.png)

everytime u open the ui.. ( OnEnable) will lower the volume to the rate u put in game instance.
instead of just manager the audio.. it lowers volume every time u open it along with the slider.
should not happen

https://imgur.com/LOyr4WM

**Comment by insthync** [comment]
Fixed patch
[AudioManager-FixVolumeLevelSetting.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5366832/AudioManager-FixVolumeLevelSetting.zip)
