### ISSUE TITLE
[Update]ZoomAbility When Reload

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#639]
Zoom ability will not deactivate while reloading. :-)

just add in

ShooterPlayerCharacterController.cs

line:  934

else if (reloadInput.IsPress)
            {
                // Reload ammo when press the button
                ReloadAmmo();
                DeactivateWeaponAbility();
            }

and line: 968
// Auto reload when ammo empty
            if (!tempPressAttackRight && !tempPressAttackLeft && !reloadInput.IsPress &&
                (PlayerCharacterEntity.EquipWeapons.rightHand.IsAmmoEmpty() ||
                PlayerCharacterEntity.EquipWeapons.leftHand.IsAmmoEmpty()))
            {
                // Reload ammo when empty and not press any keys
                ReloadAmmo();
                DeactivateWeaponAbility();
            }

ah and an option would be nice to make autoReload(), optional for each weapon if possible

**Comment by insthync** [comment]
Fixed in 1.61
