### ISSUE TITLE
shooter mobile controls will not work

### ISSUE THREAD

**Issue by kazuden** [suriyun-production/mmorpg-kit-docs#64]
shooter mobile controls will not work.no sniper binoculars for sniper.
https://gyazo.com/ddd5b216704496644a88cfc4b2951785

**Comment by insthync** [comment]
You can just add virtual button for that in CanvasGameplayMobile with key Fire2

![Screenshot_18](https://user-images.githubusercontent.com/2697550/63314678-a4ab9480-c332-11e9-8a96-8765fcd2b53d.png)

**Comment by insthync** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/2697550/63314711-c147cc80-c332-11e9-94f4-87ffbdbc797c.png)

**Comment by kazuden** [comment]
thank you
