### ISSUE TITLE
[Bug]Input Setting Manager

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#640]
Its not possible to set two same button like:

Activate to "E"
and
PickUpItem also to "E"

also for mounting and dismounting you need diffrent keys, that confuse the players

**Comment by insthync** [comment]
This was fixed, it will be included in next update.

**Comment by insthync** [comment]
Try 1.60

**Comment by moepi2k** [comment]
Super great, works. Thank you
