### ISSUE TITLE
BUG: Monster Area Effect

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#641]
1. The monster has a damage skill with an area effect.
2. If the character moves at low speed or stands still, then monster casts its skills normally. But if the character moves quickly, then the effect of these skills is in one direction, but the damage occurs in the other. See video
![image](https://user-images.githubusercontent.com/47291794/95917908-a2688d00-0db3-11eb-98d5-71d1021c0ae7.png)
[Area skills monster bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5374259/Area.skills.monster.bug.zip)

**Comment by Callepo** [comment]
Not a bug.. lol its a Casting skill which u gotta aim..
the monster grabs current location and it spawns it on that location .. u just moved away from the location..
Thats what Area effect is .. u use it on an area.. and everything in that "Area" gets dmg..

**Comment by Fallen01** [comment]
its not a bug, its a feature...

**Comment by DimasjkTV** [comment]
> Not a bug.. lol its a Casting skill which u gotta aim..
> the monster grabs current location and it spawns it on that location .. u just moved away from the location..
> Thats what Area effect is .. u use it on an area.. and everything in that "Area" gets dmg..
I assume you haven't watched the video. The skill's damage is in a different location, the skill's effect is in the opposite location.

**Comment by DimasjkTV** [comment]
![Uploading image.png…]()

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/96149063-90046580-0f11-11eb-8c52-6bbcbad5d213.png)

**Comment by DimasjkTV** [comment]
The skill has an area of the collider, which is affected by the damage. But in this video and screenshot, we see that the character takes damage, but at the same time he is not in the area of the skill.

**Comment by Callepo** [comment]
I watched the video .. maybe u should watch it again or make a better one ..
u took dmg from a Green effect.. which was used 5 times.. and there was only 1 purple effect which didnt hit u .. 
the one and only time u took dmg was from a new skill With Green effect on the floor becuase u stood still ..
all others missed

did u upload wrong vid ? :)

![image](https://user-images.githubusercontent.com/7702658/96200986-ab945e00-0f5b-11eb-82f7-917de5e538e7.png)

O dmg taken .. purple effect out .. 

New Area skill with green effect ..
![image](https://user-images.githubusercontent.com/7702658/96201024-bea72e00-0f5b-11eb-94a5-d93ee7747863.png)

![image](https://user-images.githubusercontent.com/7702658/96201046-cb2b8680-0f5b-11eb-9fa3-67a912c78376.png)

Dmg Taken.. cuase ur stand in the green effect.. 
?? where is the bug ? Purple effect never hit u ..
green did 1 time.. cuase u didnt move

all the 4 other times it was used missed cuase u ran away

**Comment by Callepo** [comment]
Ur boss is using 2 attacks .. 1 with green 1 with purple effect.. purple never hit.. 1 out of 5 green hit .. because u didnt move

**Comment by moepi2k** [comment]
im with callepo ^^ the dmg you recceive is from the green spell. becuase you stand in it. you cant see what purple one is doing. because boss cast it only once. maybe you need to make new video. but i also tested area effect and it works here

**Comment by DimasjkTV** [comment]
> im with callepo ^^ the dmg you recceive is from the green spell. becuase you stand in it. you cant see what purple one is doing. because boss cast it only once. maybe you need to make new video. but i also tested area effect and it works here

Perhaps in my project this is due to the long-term activation of the skill. I'll try to customize all the animation, and make the last part of the activation quick. I think this should help me.
