### ISSUE TITLE
Harvestable Spawners

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#642]
Sometimes Entities spawn invisible on the map. no errors nothing..
u just walk and hit a wall but there is nothing there..
i checked it a few times the position of the invisible wall change.. cuase spawn is random location..
i turned off my spawners.. and there was no invisible walls anymore

Someone else also reported noticing this a while back.
Might be something to look into
i had a spawner spawn 200 trees in a 200x 200y area
walking in that area u randomly hit a invisible object

**Comment by Callepo** [comment]
@insthync  https://imgur.com/xtc7ls6
video

**Comment by Callepo** [comment]
https://imgur.com/xNKJKSN

**Comment by insthync** [comment]
I guess it's visible checker problem.
