### ISSUE TITLE
[Bug]Fire Stagger Projectile Position

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#645]
I noticed that when use fire stagger, the random position of projectile is not synced over network. for a shooter its important that projectile is synced else client notice other impac posiotion compared to server. result is. client sometimes mean he hit the target but server say no you dont.

so is it possible that the randomness position of projectiles when use stagger will synced?

**Comment by insthync** [comment]
I will fix it by generate random seed at server then send it to client to make it random the same value at client (better than send rotation value)/

**Comment by insthync** [comment]
Fixed in 1.59d
