### ISSUE TITLE
[Bug?]Building Entites not save in mmo and Sqlite

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#647]
i dont know if its a bug or whats wrong. i tested now on fresh project 1.59c mmo mode and sqlite. when i build stuff and restart server. building stuff is gone (not saved) but it works on lan.

in older versions im sure it saved in mmo.

i dont know if its sqlite thing. i try now with mysql

**Comment by moepi2k** [comment]
also tested with mysql. when placing buildingentity db table for building is empty and after restarting building stuff is gone

**Comment by moepi2k** [comment]
ok definitively its a bug. i tested now with 1.57b and everythings fine there. building stuff saves with sql and mysql. seems after adding new db server in 1.58 it break something

**Comment by moepi2k** [comment]
i play now with 1.57b until it works again in 1.59c :)

one more thing. i try to make player instances, where player can build theier house. when they leave the instance it will save in database. i have done that building stuff save in instance. player can leave instance and enter again. stuff is there. the problem is, the building stuff loads also for other players when they enter the instance. (they cant see other player in it but theier building stuff)

i found this code block in MapNetworkManager.cs that load building stuff when enter a map

`protected override async Task PreSpawnEntities()
        {
            // Spawn buildings
            if (!IsInstanceMap())
            {
                // Load buildings
                // Don't load buildings if it's instance map
                ReadBuildingsJob job = new ReadBuildingsJob(Database, Assets.onlineScene.SceneName);
                job.Start();
                // Wait until all building loaded
                while (!job.IsDone)
                {
                    await Task.Yield();
                }
                HashSet<StorageId> storageIds = new HashSet<StorageId>();
                List<BuildingSaveData> buildings = job.result;
                BuildingEntity buildingEntity;
                foreach (BuildingSaveData building in buildings)
                {
                    buildingEntity = CreateBuildingEntity(building, true);
                    if (buildingEntity is StorageEntity)
                        storageIds.Add(new StorageId(StorageType.Building, (buildingEntity as StorageEntity).Id));
                }
                // Load building storage
                foreach (StorageId storageId in storageIds)
                {
                    StartCoroutine(LoadStorageRoutine(storageId));
                }
                // Wait until all building storage loaded
                while (loadingStorageIds.Count > 0)
                {
                    await Task.Yield();
                }
            }
            else
            {
                // instanced 
                // load only stuff from that player that join this instance
            }
        }`

at the bottom i add the else for loading stuff when its instanced. the problem is i dont figure out how to check it that only stuff load from that player who builded it. something like:

`if (BuildingSaveData.creatorId == PlayerCharacterData.Id) {load building stuff}`

i think this would be a cool feature that player has its own "land" to build stuff. and he can also invite players to his instance like the regular thing -> invite someone in group and go in instance.

**Comment by insthync** [comment]
Fixed in 1.59d
