### ISSUE TITLE
Instanced Warping

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#648]
Warping from npc to an instanced map is still bugged.
You will get Warping message and get stuck there till u dc.
other people have this issue too.

**Comment by insthync** [comment]
Not sure that map loading done or not, You may test with server config `notSpawnInBatchMode` set to `false`.

**Comment by Callepo** [comment]
ok i will

**Comment by moepi2k** [comment]
I also noticed when use a portal to warp to an instance , the smalll white loading window lasts longer than when us warp to normal scene, for eg 5 seconds, during this time you can still walk around

**Comment by Callepo** [comment]
thats normal .. its looking for party members.. and it has a timer set for that

**Comment by moepi2k** [comment]
alright thank you

**Comment by Callepo** [comment]
@insthync No effect.. Still dc 
still no working Batchmode = false

**Comment by ollisan05** [comment]
I can confirm still getting DC'd, tried everything, even the notSpawnInBatchMode = false

**Comment by insthync** [comment]
It may be because it takes so long time to load map then it's timed out before map loaded

**Comment by insthync** [comment]
I will make it no timing out  for spawn map messages.

**Comment by ollisan05** [comment]
Sounds good 👍

**Comment by insthync** [comment]
Try 1.60

**Comment by Callepo** [comment]
This is simply amazing.. holy shit..

**Comment by ollisan05** [comment]
For me i can still not get into instanced map, on mmo server you can only teleport between for example Map001 and Map002, but I added a Map003 copy of Map002 and added a teleporter for it, It warps and then camera gets removed from scene and you are still in Map001 (latest update fresh project)

**Comment by insthync** [comment]
Did you create map info and add to game database yet ?

**Comment by ollisan05** [comment]
Yes sir i did

**Comment by insthync** [comment]
There is no error in any log files ?

**Comment by ollisan05** [comment]
[Log_Database_Central_Chat_MapSpawn.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5506993/Log_Database_Central_Chat_MapSpawn.txt)

**Comment by ollisan05** [comment]
[Log_Map(Map003) Instance().txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5506994/Log_Map.Map003.Instance.txt)

**Comment by insthync** [comment]
Hmmm, no errors in the logs.

**Comment by ollisan05** [comment]
Callepo said that i probably haven't opened the ports other than 8000 and 8001 which is most likely true so i will allow 8002 and see if that works!

**Comment by ollisan05** [comment]
omg i feel so stupid, i can confirm that this issue is now fixed works totally fine now!! :D Awesome job Insthync!

I just forgot to add ports for the new maps.

**Comment by Callepo** [comment]
@insthync its solved XD
