### ISSUE TITLE
Multiple Weapon Slots

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#65]
s there an easy way to add more Weapon slots? like the character can have 2 sets of weapon on, 1 active and 1 inactive.
![weaponslot](https://user-images.githubusercontent.com/7702658/63395004-9016dd00-c3c2-11e9-8d73-ad698c43c640.JPG)

The top sword and shield is main weapon which is the one u have equipped.. and the one below will be an empy uicharacitem which u can place an weapon in it.. to be able to swap later on .
instead of putting weapons on ur action bar to use u will put the 2 weapons u want to use and with 1 hotkey will switch them back and forth. this fuction i will do myself but adding an uicharacterter item in game that is not connected to Equipitems or Unequipitems will give nothing but Error.
Tried creating an subEquip slot which didnt work well either cuase it runs deep in the core.
Tried added to equipitems components to my uiscenegameplay script.. it just mirrors the items on both 
![unequip](https://user-images.githubusercontent.com/7702658/63395140-0a476180-c3c3-11e9-85ea-6f263c995f18.JPG)
is there a way for it to not mirror eachother so it can be used for weapon switching?
if i could get a push in the right direction would really be usefull

**Comment by insthync** [comment]
Okay, I will add it :P

**Comment by insthync** [comment]
Added in 1.48c
