### ISSUE TITLE
[Bug]WarpPortalEntity use by key not work (shootercontroller)

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#650]
the function "WarpImmediatelyWhenEnter" not work when unchecked and using shootercontroller.
it work only for defaultcontroller.

**Comment by insthync** [comment]
I've reupload 1.59d package which include the fix (just remove IUnHittable implementation from WarpPortalEntity). If people want to make WarpPortalEntity unhittable, they can attach UnHittable component.

**Comment by moepi2k** [comment]
yes without IUnHittable it works, the problem is, when you add a warpsignla to indicate player that he stand on the warpportal he cant use it with press "activate" because player stand inside the collider. you need to be outside and target collider to use it. but when you stand outside the singal not work.

**Comment by insthync** [comment]
Try 1.60

**Comment by moepi2k** [comment]
Works thank you
