### ISSUE TITLE
[Issue]Animation network sync

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#653]
is it possible to make animation synced over network? problem is following. if you use hitboxes. clientside you shoot an enemy and register a hit. but on server it will not register as hit because animation state was diffrent.

this is annoying. it could happen that you shoot 3 times in head and register as hit clientside(1 should kill enemy)
but only the last hit will register on server because  animation state(hitbox position) was same on client and server.

this issue happen most time when enemies or player are in idle and the idle animation has much motion like arm/head swing.

if you need video to explain what exactly i mean. let me know

**Comment by insthync** [comment]
Oh, then, seems like it has to sync character animation time or normalized time between server and client, not sure it should syncing every time or just when movement/action states changes.

**Comment by moepi2k** [comment]
I dont know either, but it need for sure some sync :) 
I search abit in internet. I dont know how its done in other multiplayer shooters, but in the lag compensation mechanic is something to check if a hit is legit on client (also when its in the past)
