### ISSUE TITLE
Need to PvP reward...

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#656]
Hello, will there be any PvP rewards, at least like monsters?

**Comment by insthync** [comment]
You may write a new extension to add action to `onReceivedDamage` like this
```
// BasePlayerCharacterEntity_PvpReward
namespace MultiplayerARPG {
  public partial class BasePlayerCharacterEntity {
      [DevExtMethods("Awake")]
      public void Awake_AddPvpKillEvent() {
          onReceivedDamage += OnReceivedDamage_PvpKillEvent;
      }

      [DevExtMethods("Destroy")]
      public void Destroy_AddPvpKillEvent() {
          onReceivedDamage -= OnReceivedDamage_PvpKillEvent;
      }

      void OnReceivedDamage_PvpKillEvent(
        Vector3 fromPosition,
        IGameEntity attacker,
        CombatAmountType combatAmountType,
        int damage,
        CharacterItem weapon,
        BaseSkill skill,
        short skillLevel) {
      if (this.IsDead())
      {
        // ... Give an rewards to attacker ...
      }
    }
  }
}
```

**Comment by brabaris** [comment]
Tried it in every way, but nothing works, even Debug.Log ("You Dead!"); does not display ... Can you tell me how to get 100 experience? Thanks in advance!

**Comment by insthync** [comment]
This is an example of how to make it work 
https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand/blob/master/Scripts/PvpGetGoldExtension/BasePlayerCharacterEntity_PvpGetGold.cs

**Comment by brabaris** [comment]
Thank you so much! I got a like, a subscription and a positive review on the assetstore!

**Comment by brabaris** [comment]
Added randoms range for experience and gold, but how to level up?
![1](https://user-images.githubusercontent.com/16080577/98485190-3431b180-221d-11eb-9a83-75f2eb94598d.jpg)

**Comment by insthync** [comment]
Use gameplay rule's RewardExp() function to increase EXP

Example codes:
```
GameInstance.Singleton.GameplayRule.RewardExp(characterWhichReceiveExp, new Reward()
    {
        exp = addingExp,
    }, 1f, RewardGivenType.None);
```

**Comment by brabaris** [comment]
The script works. Thanks! And where to add CallAllOnLevelUp(); ?
           GameInstance.Singleton.GameplayRule.RewardExp(character, new Reward()
            {
               // exp = character.Exp,            // Commented out, incorrect addition of EXP!
            }, 1f, RewardGivenType.None);

**Comment by insthync** [comment]
```
if (GameInstance.Singleton.GameplayRule.RewardExp(characterWhichReceiveExp, new Reward()
    {
        exp = addingExp,
    }, 1f, RewardGivenType.None))
{
// CallAllOnLevelUp
}
```

If you are going to add exp to character you actually can use `RewardExp` function like this
```
character.RewardExp(new Reward()
    {
        exp = addingExp,
    }, 1f, RewardGivenType.None);
```
it will call on level up when level up

**Comment by brabaris** [comment]
Leveling up is already working, I need to render this GameEffect levelUpEffect! I don't know where to add CallAllOnLevelUp ();
Here is the script:

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MultiplayerARPG
{
    public partial class BasePlayerCharacterEntity
    {

        [Header("Killing Rewards:")]
        [SerializeField]
        private int rewardGoldMin;
        [SerializeField]
        private int rewardGoldMax;
        [SerializeField]
        private int rewardExpMin;
        [SerializeField]
        private int rewardExpMax;

        public virtual int RewardGold()
        {
            int min = rewardGoldMin;
            int max = rewardGoldMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }
        public virtual int RewardExp()
        {
            int min = rewardExpMin;
            int max = rewardExpMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }

        [DevExtMethods("Awake")]
        public void Awake_PvpGetGold()
        {
            onReceivedDamage += ReceivedDamage_PvpGetGold;
        }

        [DevExtMethods("OnDestroy")]
        public void OnDestroy_PvpGetGold()
        {
            onReceivedDamage -= ReceivedDamage_PvpGetGold;
        }

        private void ReceivedDamage_PvpGetGold(
            Vector3 fromPosition,
            IGameEntity attacker,
            CombatAmountType combatAmountType,
            int damage,
            CharacterItem weapon,
            BaseSkill skill,
            short skillLevel)
        {
            if (!IsServer)
                return;

            if (attacker == null || !(attacker.Entity is BasePlayerCharacterEntity))
                return;

            int rewardGold = RewardGold();
            int rewardExp = RewardExp();
            BasePlayerCharacterEntity character = (attacker.Entity as BasePlayerCharacterEntity);
            if (!this.IsDead())
                return;

            character.Gold += rewardGold;
            CurrentGameManager.SendNotifyRewardGold(character.ConnectionId, rewardGold);

            character.Exp += rewardExp;
            CurrentGameManager.SendNotifyRewardExp(character.ConnectionId, rewardExp);

            GameInstance.Singleton.GameplayRule.RewardExp(character, new Reward()
            {
               // exp = character.Exp,
            }, 1f, RewardGivenType.None);
            //CallAllOnLevelUp();

        }
    }
}
`

**Comment by insthync** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MultiplayerARPG
{
    public partial class BasePlayerCharacterEntity
    {

        [Header("Killing Rewards:")]
        [SerializeField]
        private int rewardGoldMin;
        [SerializeField]
        private int rewardGoldMax;
        [SerializeField]
        private int rewardExpMin;
        [SerializeField]
        private int rewardExpMax;

        public virtual int RewardGold()
        {
            int min = rewardGoldMin;
            int max = rewardGoldMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }
        public virtual int RewardExp()
        {
            int min = rewardExpMin;
            int max = rewardExpMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }

        [DevExtMethods("Awake")]
        public void Awake_PvpGetGold()
        {
            onReceivedDamage += ReceivedDamage_PvpGetGold;
        }

        [DevExtMethods("OnDestroy")]
        public void OnDestroy_PvpGetGold()
        {
            onReceivedDamage -= ReceivedDamage_PvpGetGold;
        }

        private void ReceivedDamage_PvpGetGold(
            Vector3 fromPosition,
            IGameEntity attacker,
            CombatAmountType combatAmountType,
            int damage,
            CharacterItem weapon,
            BaseSkill skill,
            short skillLevel)
        {
            if (!IsServer)
                return;

            if (attacker == null || !(attacker.Entity is BasePlayerCharacterEntity))
                return;

            int rewardGold = RewardGold();
            int rewardExp = RewardExp();
            BasePlayerCharacterEntity character = (attacker.Entity as BasePlayerCharacterEntity);
            if (!this.IsDead())
                return;

            character.Gold += rewardGold;
            CurrentGameManager.SendNotifyRewardGold(character.ConnectionId, rewardGold);

            character.Exp += rewardExp;
            CurrentGameManager.SendNotifyRewardExp(character.ConnectionId, rewardExp);

            if (GameInstance.Singleton.GameplayRule.RewardExp(character, new Reward()
                {
                    exp = character.Exp,
                }, 1f, RewardGivenType.None))
            {
                CallAllOnLevelUp();
            }
        }
    }
}

**Comment by brabaris** [comment]
I've already tried it! The script does not work correctly...
Twice as much Exp as it should have! Adds levelUpEffect on enemy corpse! :(

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MultiplayerARPG
{
    public partial class BasePlayerCharacterEntity
    {

        [Header("Killing Rewards:")]
        [SerializeField]
        private int rewardGoldMin;
        [SerializeField]
        private int rewardGoldMax;
        [SerializeField]
        private int rewardExpMin;
        [SerializeField]
        private int rewardExpMax;

        public virtual int RewardGold()
        {
            int min = rewardGoldMin;
            int max = rewardGoldMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }
        public virtual int RewardExp()
        {
            int min = rewardExpMin;
            int max = rewardExpMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }

        [DevExtMethods("Awake")]
        public void Awake_PvpGetGold()
        {
            onReceivedDamage += ReceivedDamage_PvpGetGold;
        }

        [DevExtMethods("OnDestroy")]
        public void OnDestroy_PvpGetGold()
        {
            onReceivedDamage -= ReceivedDamage_PvpGetGold;
        }

        private void ReceivedDamage_PvpGetGold(
            Vector3 fromPosition,
            IGameEntity attacker,
            CombatAmountType combatAmountType,
            int damage,
            CharacterItem weapon,
            BaseSkill skill,
            short skillLevel)
        {
            if (!IsServer)
                return;

            if (attacker == null || !(attacker.Entity is BasePlayerCharacterEntity))
                return;

            int rewardGold = RewardGold();
            int rewardExp = RewardExp();
            BasePlayerCharacterEntity character = (attacker.Entity as BasePlayerCharacterEntity);
            if (!this.IsDead())
                return;

            character.Gold += rewardGold;
            CurrentGameManager.SendNotifyRewardGold(character.ConnectionId, rewardGold);

            character.Exp += rewardExp;
            CurrentGameManager.SendNotifyRewardExp(character.ConnectionId, rewardExp);

            if (GameInstance.Singleton.GameplayRule.RewardExp(character, new Reward()
                {
                    exp = character.Exp,  // - INCORRECT EXP ADDITION! When commented out, everything is ok.
                }, 1f, RewardGivenType.None))
            {
                CallAllOnLevelUp(); // - ADDES levelUpEffect ON THE CORPSE OF THE ENEMY, NOT ON THE CHARACTER!
            }
        }
    }
}`

**Comment by insthync** [comment]
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MultiplayerARPG
{
    public partial class BasePlayerCharacterEntity
    {

        [Header("Killing Rewards:")]
        [SerializeField]
        private int rewardGoldMin;
        [SerializeField]
        private int rewardGoldMax;
        [SerializeField]
        private int rewardExpMin;
        [SerializeField]
        private int rewardExpMax;

        public virtual int RewardGold()
        {
            int min = rewardGoldMin;
            int max = rewardGoldMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }
        public virtual int RewardExp()
        {
            int min = rewardExpMin;
            int max = rewardExpMax;
            if (min > max)
                min = max;
            return Random.Range(min, max);
        }

        [DevExtMethods("Awake")]
        public void Awake_PvpGetGold()
        {
            onReceivedDamage += ReceivedDamage_PvpGetGold;
        }

        [DevExtMethods("OnDestroy")]
        public void OnDestroy_PvpGetGold()
        {
            onReceivedDamage -= ReceivedDamage_PvpGetGold;
        }

        private void ReceivedDamage_PvpGetGold(
            Vector3 fromPosition,
            IGameEntity attacker,
            CombatAmountType combatAmountType,
            int damage,
            CharacterItem weapon,
            BaseSkill skill,
            short skillLevel)
        {
            if (!IsServer)
                return;

            if (attacker == null || !(attacker.Entity is BasePlayerCharacterEntity))
                return;

            int rewardGold = RewardGold();
            int rewardExp = RewardExp();
            BasePlayerCharacterEntity character = (attacker.Entity as BasePlayerCharacterEntity);
            if (!this.IsDead())
                return;

            character.Gold += rewardGold;
            CurrentGameManager.SendNotifyRewardGold(character.ConnectionId, rewardGold);

            if (GameInstance.Singleton.GameplayRule.RewardExp(character, new Reward()
                {
                    exp = character.Exp,
                }, 1f, RewardGivenType.None))
            {
                character.CallAllOnLevelUp();
            }
        }
    }
}
```

*-*

**Comment by brabaris** [comment]
HUGE THANKS!

**Comment by brabaris** [comment]
exp = character.Exp, - нужно удалить! С ним считает как (RandomExp + текущий Exp) x2
Т.е. если RandomExp = 15, ТекущийExp был 50/1000, посчитает как (15+ 50) x 2
