### ISSUE TITLE
Unity events on hit / on death > entity

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#657]
Hello, is it possible to add Unity events « on death » and « on hit »on monsters and players?  I'm working on an addon project and this will make things easier.

**Comment by moepi2k** [comment]
Event for respawn would also be great

**Comment by Koodetat** [comment]
yes that would be very useful too!

**Comment by insthync** [comment]
There delegate events `onReceiveDamage`, `onReceivedDamage`, `onDead`, `onRespawn`,  can you use them or I have to change them to be UnityEvent?

**Comment by Koodetat** [comment]
I personally prefer to use UnityEvents.

**Comment by insthync** [comment]
Try 1.60

**Comment by Koodetat** [comment]
thank you it's perfect !
