### ISSUE TITLE
Mass dismantle situations

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#658]
Single player. My users have noticed that sometimes during the mass items dismantle. Items that player did not select are disappear. Unfortunately, I cannot provide a video. This is very rare. Seems like old bug with item dublications.

**Comment by DimasjkTV** [comment]
We managed to record a video. The video shows that after items dismantle, those items that were not selected disappeared.
[Item Dismantle BUg.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5466516/Item.Dismantle.BUg.zip)

**Comment by insthync** [comment]
Thank you for bug report, I will fix it.

**Comment by insthync** [comment]
Try 1.60

**Comment by insthync** [comment]
If it's still occuring, you can reopen it or create new post :)
