### ISSUE TITLE
Article from hunt -> client side prediction reconcilation

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#660]
I found this article from the game hunt

https://www.huntshowdown.com/news/the-state-of-hit-registration-in-hunt

Its very interesting. Most ppls from thus kit are still in developing aand not tested things live for multiplayer. Im in this phase and i got alot feedback regarding this "issue" -> not registered hits/desync and so on. 

We had this thread already in the past. So my question is, can we calculate with a system like this for client side prediction and reconcilation / hit validation system?

I know its a very complex mechanic. But i think its needed for every multiplayer game. For sure flr shooters and fast pased games.

**Comment by insthync** [comment]
I am going to implement it but there are always have new many little requests so I don't have time to implement it yet.

**Comment by moepi2k** [comment]
Great, then from my side i will not make new posts until then 😄
