### ISSUE TITLE
Sniper Zoom, crouch and crawl ( Survival Mode)

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#661]
Why there is no sniper zoom in survival mode also crouch and crawl doesnt work in survival mode .. trying to press on ctl , z and right mouse and nothing work ? i cannot find it ..

**Comment by insthync** [comment]
The survival mode controller is `PlayerCharacterController` did you change it to `ShooterPlayerCharacterController` yet?

**Comment by RunOrDi3** [comment]
No .. Where can i find it ?
