### ISSUE TITLE
DOTS

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#662]
i was trying to Implements DOTS for harvestables, cuase they are very heavy on ur Core cuase of unity being SingleThread.. and each map is only being processed by 1 core.
This is my game with 0 entities on the map..
![image](https://user-images.githubusercontent.com/7702658/98144378-a2e3d780-1eca-11eb-990c-8a4733cbb2dd.png)

And same game.. same map same everything just 2.5k ish entities this time..
![image](https://user-images.githubusercontent.com/7702658/98144474-b3944d80-1eca-11eb-83a2-34a0f27d4a75.png)

I converted orcArcher prefab into Entity, its spawned through unity entity  manager. here u see 6k + mobs.. and fps is same as 0 mobs.. with Burst Compiler.
![image](https://user-images.githubusercontent.com/7702658/98144868-e2122880-1eca-11eb-827d-0db1ae17d200.png)

This is same amount same all ..But burst compiler turned off..
![image](https://user-images.githubusercontent.com/7702658/98145140-053cd800-1ecb-11eb-9456-6e91099b5484.png)

Is there an Estimate of when DOTS will be implimented on the monster entities in the kit ?
![image](https://user-images.githubusercontent.com/7702658/98145400-2ac9e180-1ecb-11eb-8ec0-f077f24f53e1.png)

Monsters and harvestables would be enough for now. Even if its just spawning + wander

the time this will take for me to learn and impliment dots is gonna be a while lol..
so if this is planned and coming soon... i would rather spend the time on something else.

**Comment by Callepo** [comment]
OR is it possible for Entities to be Inactive on server also while there is no player around? 
Seems to me like they are constantly updated and tracked.. even when the world has 0 players..

**Comment by Callepo** [comment]
@insthync

**Comment by insthync** [comment]
I actually avoid updating while there are no subscribers, you can check codes in `BaseMonsterCharacterEntity` line `110`

I may improve it by add a property which overrideable to avoid EntityComponents updating in `BaseGameEntity` (in Update, LateUpdate and FixedUpdate function)

**Comment by insthync** [comment]
If you can do DOTS things and it goes well why don't continue it how is your progress with DOTS?

**Comment by Callepo** [comment]
i just started today lol.. My progress is almost null :P
i just managed to spawn orc as Entities instead of gameobjects.. they dont move or anything yet XD

**Comment by Callepo** [comment]
@insthync i was checking out the cpu issue.. 
Its just monsters that cuase it .. nothing else..2k Harvestables on map.. and core is 5%.. 
500 monsters... 60-70% , 1k 100%

**Comment by insthync** [comment]
Please try 1.60, I have a condition to monster character entity to not update an entity components

**Comment by Callepo** [comment]
@insthync Seems a bit better.. it doesnt let 1 core Max out at 100% constantly anymore..
It just spikes alot to 100 and then back down to 60-70 few seconds later spikes to full then goes back down..
it could also be just because im using VPS , my cpu prolly not so good to handle so much Monsters..
but id assume with 0 players monsters should be spiking the server
