### ISSUE TITLE
NPC Movement after update to 1.60

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#667]
In my level/Map the NPCs(Monsters ) stopped moving after updating the Kit to 1.60 from 1.59d.
I am not 100% sure what the reason is as there no error on the console 
And I am certain that before the update in 1.59d it was working 

I did check the navmesh it's still there so it's not that navmesh is missing.
Still trying to debug the issue will update is there if I find anything

**Comment by Deepankar1993** [comment]
So, Looking at the default maps everything is working fine 
When I check the NPC on my custom map compare  to the default map 
After selecting the NPC and checking the Animator window. 
I noticed that In my custom Map with custom NPC(monster)
The MoveSpeed parameter in Animator is not Updating/Changing in my Map and NPC compare to Default NPC like OrcWarrior etc

**Comment by Deepankar1993** [comment]
Found the issue my existing NPC and Player Prefabs are missing the Grid Visible Checker Script adding that fixed the Issue

**Comment by insthync** [comment]
So you can close it
