### ISSUE TITLE
1.60 Harvestable

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#668]
New project. mmo

![unknown](https://user-images.githubusercontent.com/56482598/98442555-7f6d9680-212f-11eb-8f68-733940c89191.png)

**Comment by insthync** [comment]
This is not occurring on my project, you should try open Map001 scene then select  `HarvestableSpawnArea ...`  game objects then drag `HarvestableSpawnArea` scripts from `Project` tab and placed on them.
![Screenshot_102](https://user-images.githubusercontent.com/2697550/98443333-29075480-213d-11eb-83d1-60c158884cb3.png)

**Comment by Serivatech** [comment]
![image](https://user-images.githubusercontent.com/56482598/98443498-d4aca680-2135-11eb-897e-d8b3dda43c6a.png)

**Comment by insthync** [comment]
Find the harvestable entity and place each of them 
![Screenshot_103](https://user-images.githubusercontent.com/2697550/98443741-eeeb8200-213f-11eb-835e-7a927eb1f915.png)

**Comment by Serivatech** [comment]
These files are not present in 1.60
![image](https://user-images.githubusercontent.com/56482598/98444264-e3e22300-213a-11eb-8e13-16927368ce60.png)
![image](https://user-images.githubusercontent.com/56482598/98444369-83071a80-213b-11eb-8bfd-86158a420f6f.png)

**Comment by insthync** [comment]
Weird, I still can find it 
![Screenshot_104](https://user-images.githubusercontent.com/2697550/98444480-7e932f80-2144-11eb-98d0-849d382aaeeb.png)

**Comment by Serivatech** [comment]
I don't understand how this can be. In previous versions, I deleted extra folders with examples, leaving only the Demo and everything worked. Why do I need Demo Survival now?

**Comment by insthync** [comment]
Harvestable Entity is in DemoSurvival folder.

**Comment by Callepo** [comment]
There is nothing wrong in 1.60.. no one else has this issue.. literally no one else
