### ISSUE TITLE
No Movement Animations with "Point Click"

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#67]
When the Player Controller Mode is set to "Point Click", there is no run/walk animations on server build.  Other animations work, like attackSwing, skill, etc.

**OS:** Windows 10
**Connection:** Separate Client and Server build, connecting over Local Area Network
**Problem:** No walk/run animations for any viewer on the server
**Version:** 1.48c

**Video:** https://www.youtube.com/watch?v=Ilgun2I9pMw

**Comment by insthync** [comment]
As I try, I don't having this problem, I want to see all of your character model settings

**Comment by Hawkadium** [comment]
I did a clean install of the kit, no changes and I did not remove any other 2D/Shooter stuff like I did before.  I made a new video to show the animation window and so on.

https://www.youtube.com/watch?v=3aSO3TMJsFY

**Comment by insthync** [comment]
Ahhh, I see, fixing it now

**Comment by Hawkadium** [comment]
Fixed as of 1.48d
