### ISSUE TITLE
When will the mail and auction system be completed?

### ISSUE THREAD

**Issue by bingbingyou** [suriyun-production/mmorpg-kit-docs#671]
Need a donation?

**Comment by insthync** [comment]
Donation won't change my task priority. But the mail may be added soon because I want to implement a guild war's reward.

**Comment by bingbingyou** [comment]
Thank you. hope the auction system can be completed soon too.

**Comment by RunOrDi3** [comment]
Yeah , we need auction system .. if you want any donations , we will pay man :)

**Comment by moepi2k** [comment]
auction system will be best feature :) 👍

**Comment by Callepo** [comment]
I could potentially make the auction house.. ill check it out

**Comment by insthync** [comment]
Mail is done

**Comment by insthync** [comment]
@Callepo I think some part may be done easier by web-api/rest-api development because I think it actually has to write real-time codes just when assign items to the market to remove item from inventory, other than that can be done by web-api.

**Comment by Callepo** [comment]
ive created systems like this in the past in the kit, with db entries etc, dont think if i make it ill use web api's tho, im much better with just coding.
i can even integrate it with the mail system to send u an email when u sold something. etc

if ur not planning on doing it now i can make a little demo or something and show u. and u can see if its ok or decent.
but if ur already gonna make it i wont. no reason 2 people do same thing 
@insthync

**Comment by insthync** [comment]
Mail is done, about auction house...
Moved to https://github.com/suriyun-production/mmorpg-kit-docs/issues/1129
