### ISSUE TITLE
Bug in shooter control [Fixed]

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#675]
when i press on z or left crtl just one time , the animation repeating automatic .. but it become fine when i off the crouch or prone and press on again .. this bug happens everytime when i join unity play game scene ... you can check the video to understand ( https://youtu.be/PT0doL8EeKM )
UPDATE : Fixed

**Comment by moepi2k** [comment]
its not a bug. adjust opencharactercontroller settings and movementcollideradjusment component

**Comment by RunOrDi3** [comment]
i did , i get the same problem...

**Comment by moepi2k** [comment]
You can close your post self when its fixed @RunOrDi3 :)

**Comment by RunOrDi3** [comment]
Fixed
