### ISSUE TITLE
1.60c update situation.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#678]
After update to 1.60c i have few errors.
![image](https://user-images.githubusercontent.com/47291794/99414831-417b2a00-2908-11eb-9860-31ddd83e6933.png)
![image](https://user-images.githubusercontent.com/47291794/99414858-4809a180-2908-11eb-9631-24653d0cf42c.png)
![image](https://user-images.githubusercontent.com/47291794/99414967-67083380-2908-11eb-9fb2-9cfeeed8fb59.png)
![image](https://user-images.githubusercontent.com/47291794/99415010-70919b80-2908-11eb-8588-fceda807e83a.png)

Any ideas?

**Comment by insthync** [comment]
Try change parameter following this: 
```
        public override float GetDamageReducedByResistance(Dictionary<DamageElement, float> damageReceiverResistances, Dictionary<DamageElement, float> damageReceiverArmors, float damageAmount, DamageElement damageElement)
```

**Comment by DimasjkTV** [comment]
> public override float GetDamageReducedByResistance(Dictionary<DamageElement, float> damageReceiverResistances, Dictionary<DamageElement, float> damageReceiverArmors, float damageAmount, DamageElement damageElement)

Thank you. My fault, there were a few new changes to this script.

**Comment by DimasjkTV** [comment]
> Try change parameter following this:
> 
> ```
>         public override float GetDamageReducedByResistance(Dictionary<DamageElement, float> damageReceiverResistances, Dictionary<DamageElement, float> damageReceiverArmors, float damageAmount, DamageElement damageElement)
> ```

![image](https://user-images.githubusercontent.com/47291794/99420181-fbc16000-290d-11eb-9cdb-16bffb4a9358.png)
Characters are not created in the game. Something with the database

**Comment by DimasjkTV** [comment]
Last version was 1.59c

**Comment by insthync** [comment]
Try find and delete `CharacterQuest.cs` and reimport it.

**Comment by insthync** [comment]
Not sure that you have changes anything in `CharacterQuest` class or not

**Comment by DimasjkTV** [comment]
> Not sure that you have changes anything in `CharacterQuest` class or not

Didn't change anything in this script. Reimport didn't help.

I also have this errors when importing
![image](https://user-images.githubusercontent.com/47291794/99499071-62d02a80-2989-11eb-81bc-a83d5b948fe4.png)
![image](https://user-images.githubusercontent.com/47291794/99499113-72e80a00-2989-11eb-85e5-357c633111b4.png)

**Comment by insthync** [comment]
Try replace `CharacterQuestSerializationSurrogate` codes to 
```using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;

public class CharacterQuestSerializationSurrogate : ISerializationSurrogate
{
    public void GetObjectData(System.Object obj,
                              SerializationInfo info, StreamingContext context)
    {
        CharacterQuest data = (CharacterQuest)obj;
        info.AddValue("dataId", data.dataId);
        info.AddValue("isComplete", data.isComplete);
        info.AddValue("killedMonsters", data.killedMonsters);
        info.AddValue("completedTasks", data.completedTasks);
    }

    public System.Object SetObjectData(System.Object obj,
                                       SerializationInfo info, StreamingContext context,
                                       ISurrogateSelector selector)
    {
        CharacterQuest data = (CharacterQuest)obj;
        data.dataId = info.GetInt32("dataId");
        data.isComplete = info.GetBoolean("isComplete");
        data.killedMonsters = (Dictionary<int, int>)info.GetValue("killedMonsters", typeof(Dictionary<int, int>));
        // TODO: Backward compatible, this will be removed in future version
        try
        {
            data.completedTasks = (List<int>)info.GetValue("completedTasks", typeof(List<int>));
        }
        catch { }
        obj = data;
        return obj;
    }
}

```

**Comment by DimasjkTV** [comment]
> using System.Collections.Generic;
> using System.Runtime.Serialization;
> 
> public class CharacterQuestSerializationSurrogate : ISerializationSurrogate
> {
>     public void GetObjectData(System.Object obj,
>                               SerializationInfo info, StreamingContext context)
>     {
>         CharacterQuest data = (CharacterQuest)obj;
>         info.AddValue("dataId", data.dataId);
>         info.AddValue("isComplete", data.isComplete);
>         info.AddValue("killedMonsters", data.killedMonsters);
>         info.AddValue("completedTasks", data.completedTasks);
>     }
> 
>     public System.Object SetObjectData(System.Object obj,
>                                        SerializationInfo info, StreamingContext context,
>                                        ISurrogateSelector selector)
>     {
>         CharacterQuest data = (CharacterQuest)obj;
>         data.dataId = info.GetInt32("dataId");
>         data.isComplete = info.GetBoolean("isComplete");
>         data.killedMonsters = (Dictionary<int, int>)info.GetValue("killedMonsters", typeof(Dictionary<int, int>));
>         // TODO: Backward compatible, this will be removed in future version
>         try
>         {
>             data.completedTasks = (List<int>)info.GetValue("completedTasks", typeof(List<int>));
>         }
>         catch { }
>         obj = data;
>         return obj;
>     }
> }

This works. Thank you!

**Comment by DimasjkTV** [comment]
> Try replace `CharacterQuestSerializationSurrogate` codes to
> 
> ```
> using System.Collections.Generic;
> using System.Runtime.Serialization;
> 
> public class CharacterQuestSerializationSurrogate : ISerializationSurrogate
> {
>     public void GetObjectData(System.Object obj,
>                               SerializationInfo info, StreamingContext context)
>     {
>         CharacterQuest data = (CharacterQuest)obj;
>         info.AddValue("dataId", data.dataId);
>         info.AddValue("isComplete", data.isComplete);
>         info.AddValue("killedMonsters", data.killedMonsters);
>         info.AddValue("completedTasks", data.completedTasks);
>     }
> 
>     public System.Object SetObjectData(System.Object obj,
>                                        SerializationInfo info, StreamingContext context,
>                                        ISurrogateSelector selector)
>     {
>         CharacterQuest data = (CharacterQuest)obj;
>         data.dataId = info.GetInt32("dataId");
>         data.isComplete = info.GetBoolean("isComplete");
>         data.killedMonsters = (Dictionary<int, int>)info.GetValue("killedMonsters", typeof(Dictionary<int, int>));
>         // TODO: Backward compatible, this will be removed in future version
>         try
>         {
>             data.completedTasks = (List<int>)info.GetValue("completedTasks", typeof(List<int>));
>         }
>         catch { }
>         obj = data;
>         return obj;
>     }
> }
> ```

in 1,60c old situation with time out 
![image](https://user-images.githubusercontent.com/47291794/99531962-93798980-29b4-11eb-9154-f788fa27250a.png)

**Comment by insthync** [comment]
When you press on accept it still can continue to play or not?

**Comment by DimasjkTV** [comment]
> When you press on accept it still can continue to play or not? or it is disconnect and go to home scene?

can play but the character disappears and the camera cannot move

**Comment by insthync** [comment]
Is this occuring when enter game or while playing game ?

**Comment by DimasjkTV** [comment]
> Is this occuring when enter game or while playing game ?

This happens after the screen goes off for a while or the alt tab in the phone menu.

**Comment by insthync** [comment]
I will fix it.
