### ISSUE TITLE
idle and walk animations doesn't work [3D Demo]

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#679]
Hi sir, i have added a new monster and i have added the animations .. for some reasons idle and walk animations doesn't work and when the monster come to attack me, the walk animation works for 1 time and then stops .. die,  attack and hit animations works fine .. check the video < https://youtu.be/FXSzi2YgGX0 > .. i tried a lot of things but doesn't work

**Comment by Koodetat** [comment]
no problem for me on version 1.60C.  I think your character settings are incorrect (run and idle animations must be looped).

**Comment by insthync** [comment]
Animation clip -> Loop time was on?

**Comment by RunOrDi3** [comment]
ohh , thx alot .. its fine now
