### ISSUE TITLE
I want to join the farm mode

### ISSUE THREAD

**Issue by qipaworld** [suriyun-production/mmorpg-kit-docs#68]
I want to join the farm mode, where players can grow farmers, fruit trees and vegetables.
Players can raise poultry, pigs and cattle.
Players can catch pets in the wild.
Players can upgrade with pets.

**Comment by shubhank008** [comment]
Its certainly possible with the kit. The kit is a base, anything you make or can make on top of it is on you.  

Just strip down all the battle/spells functionality code. Replace items/weapons with farming tools, seeds, etc. 
The kit already has functionality for "harvesting" so you can harvest trees, flowers, fields, and anything you add harvestable data to.
"Catching pets" can be done by simply spawning pers as enemies and replace the fight mechanics with a catching one. Perhaps use a net or something as a item and when it hits the pet, you "catch it".
Kit already has pet option.

All in all, your idea of a open world or massive multiple online farming game is possible and not that hard with the kit. It provides you with a framework and most of the features as a template, but you do need to know some intermediate level of game development and coding/c# to make it work for you.  

If you are hoping for a prebuilt example or something, this is not for you.

**Comment by qipaworld** [comment]
Thank you
