### ISSUE TITLE
Spawn area issue

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#681]
I have created spawn areas with new monsters .. when i join the area i don't see any monsters but when i go to the spawn area the monsters appear ( https://youtu.be/Z7_H8uK2I2c ).. why it's happening ?

**Comment by Xentar** [comment]
Hey, Run
I suggest you to ask this kind of questions on Discord (https://discord.gg/jQHgRu4). Here are more bugs/glich at code base.
The problem you have there is probably from the "GridVisibleCheker" on the monster. There is a range there you need to adjust. 80 is ok for thirdperson cameras.
