### ISSUE TITLE
Drag & Drop handlers

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#682]
UICharacterItemDropHandler & UICharacterItemDragHandler are closed off Classes.. and most of their methods are privates..
this makes it extremely hard to add functionality to em without trying to find some weird work around..

Can u make these classes atleast Partials so that we can acces stuff like 
![image](https://user-images.githubusercontent.com/7702658/99860823-87e4b900-2b94-11eb-9fb4-865aa1c2906b.png)

With Getters and Setters.
Just Partial class would help a lot..
i can do it myself.. but ill have to keep changing the kit every update.
ty

**Comment by insthync** [comment]
Changed, it will be included in the next update.

**Comment by insthync** [comment]
Changed in 1.61
