### ISSUE TITLE
[Suggestion] More than 1x kind of monster in the same spawn area 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#683]
Will be great if you add option to add more than 1x kind of monster in the same spawn area , to not make lots of spawn areas in the place

**Comment by Fallen01** [comment]
My addon does that and alot more... ;)

**Comment by RunOrDi3** [comment]
ohh...i will check it

**Comment by insthync** [comment]
I will add list in spawn area in next version

**Comment by RunOrDi3** [comment]
good
