### ISSUE TITLE
Map info Pvp Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#684]
![image](https://user-images.githubusercontent.com/7702658/99893241-df128880-2c7d-11eb-9023-03ddc56ef3ce.png)

On Pvp mode is none.. ally should always be true..
atm its default to false.. 
means same party can kill same party/ Guild can kill guild/
faction can kill faction
Basically its a free for all pvp .. 
![image](https://user-images.githubusercontent.com/7702658/99893270-226cf700-2c7e-11eb-9ff3-1b547539dd11.png)
@insthync 

If None = true... no one can attack anyone on that map

**Comment by RunOrDi3** [comment]
yeah , you are right .. we hope he will fix it in the next update

**Comment by insthync** [comment]
Fixed, it will be included in the next update.

**Comment by insthync** [comment]
Fixed in 1.61
