### ISSUE TITLE
Error at BulkDismantleItems

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#686]
Error at BulkDismantleItems. Added UIBulkDismantleItems (shown in screenshot). What else needs to be edit?!
P.S. : Ver. 1.58 ->1.60c
![1](https://user-images.githubusercontent.com/16080577/100610124-cce8b800-3317-11eb-9582-10d1ddbdc31d.jpg)

**Comment by brabaris** [comment]
The same error occurs when bulk sell ... Moreover, the request goes to a file in another project! Now project 34 is launched, and the file request is in 31 projects!
![2](https://user-images.githubusercontent.com/16080577/100622300-5ce32d80-3329-11eb-9a36-8414bc2bc736.jpg)

**Comment by brabaris** [comment]
Deleted LiteNetLibManager folder and re-imported the package. Now swears at: error CS0246: The type or namespace name 'BaseAckMessage' could not be found (are you missing a using directive or an assembly reference ...
![3](https://user-images.githubusercontent.com/16080577/100760410-67b9c300-33fa-11eb-8450-47e438be7a37.jpg)

**Comment by brabaris** [comment]
Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\Messages\Character\RequestCharactersMessage.cs(8,45): error CS0246: The type or namespace name 'BaseAckMessage' could not be found (are you missing a using directive or an assembly reference?)

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\Messages\Character\RequestCharactersMessage.cs(10,30): error CS0115: 'RequestCharactersMessage.DeserializeData(NetDataReader)': no suitable method found to override

Assets\UnityMultiplayerARPG\MMO\Scripts\MMOGame\Networking\Messages\Character\RequestCharactersMessage.cs(14,30): error CS0115: 'RequestCharactersMessage.SerializeData(NetDataWriter)': no suitable method found to override

**Comment by brabaris** [comment]
After upgrading to version 1.60 there were errors related to LiteNet. Installed UnityMultiplayerARPG_LiteNetLibFix20-05-11 - the errors disappeared, but when updating, the message appears:
![4](https://user-images.githubusercontent.com/16080577/100763886-6be7df80-33fe-11eb-8e53-d251d8a6e264.jpg)

**Comment by insthync** [comment]
You can delete `BaseAckMessage`, `RequestCharactersMessage`.

You actually should try to delete all scripts (From Assets/UnityMultiplayerARPG/Core/Scripts and Assets/UnityMultiplayerARPG/MMO) then reimport the package

**Comment by brabaris** [comment]
I'm copying the project, I'll try it now!

**Comment by brabaris** [comment]
I did everything as I wrote it, but now this error!
![5](https://user-images.githubusercontent.com/16080577/100772346-20d2ca00-3408-11eb-95d5-a5fa3012c681.jpg)

ArgumentException: NetDataWriter cannot write type List`1
LiteNetLib.Utils.NetDataWriterExtension.PutValue (LiteNetLib.Utils.NetDataWriter writer, System.Type type, System.Object value) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/NetDataWriterExtension.cs:150)
LiteNetLibManager.LiteNetLibFunction.SerializeParameters (LiteNetLib.Utils.NetDataWriter writer) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:196)
LiteNetLibManager.LiteNetLibFunction.SerializeForSend (LiteNetLib.Utils.NetDataWriter writer) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:171)
LiteNetLibManager.LiteNetLibFunction.SerializeForClient (LiteNetLib.Utils.NetDataWriter writer, LiteNetLibManager.FunctionReceivers receivers, System.Int64 connectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:165)
LiteNetLibManager.LiteNetLibFunction+<>c__DisplayClass14_0.<ClientSendCall>b__0 (LiteNetLib.Utils.NetDataWriter writer) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:61)
LiteNetLibManager.TransportHandler.WritePacket (LiteNetLib.Utils.NetDataWriter writer, System.UInt16 messageType, LiteNetLibManager.SerializerDelegate extraSerializer) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:100)
LiteNetLibManager.LiteNetLibClient.SendPacket (LiteNetLib.DeliveryMethod deliveryMethod, System.UInt16 msgType, LiteNetLibManager.SerializerDelegate serializer) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:85)
LiteNetLibManager.LiteNetLibManager.ClientSendPacket (LiteNetLib.DeliveryMethod options, System.UInt16 msgType, LiteNetLibManager.SerializerDelegate serializer) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:256)
LiteNetLibManager.LiteNetLibFunction.ClientSendCall (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Int64 targetConnectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:61)
LiteNetLibManager.LiteNetLibFunction.SendCall (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Int64 targetConnectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:112)
LiteNetLibManager.LiteNetLibFunction.Call (LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameterValues) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:132)
LiteNetLibManager.LiteNetLibBehaviour.RPC (System.String methodName, LiteNetLib.DeliveryMethod deliveryMethod, System.Object[] parameters) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:1478)
LiteNetLibManager.LiteNetLibBehaviour.RPC (System.String methodName, System.Object[] parameters) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:1461)
LiteNetLibManager.LiteNetLibBehaviour.RPC[T1] (LiteNetLibManager.NetFunctionDelegate`1[T1] func, T1 param1) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:1135)
MultiplayerARPG.BasePlayerCharacterEntity.CallServerDismantleItems (System.Collections.Generic.List`1[T] indexes) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity_NetworkRequest.cs:275)
MultiplayerARPG.UIBulkDismantleItems.OnClickDismantleItems () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Item/UIBulkDismantleItems.cs:80)
UnityEngine.Events.InvokableCall.Invoke () (at <8691ad7005ed4755a1828378ff0b52b1>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <8691ad7005ed4755a1828378ff0b52b1>:0)
UnityEngine.UI.Button.Press () (at C:/Program Files/2019.4.11f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Program Files/2019.4.11f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Program Files/2019.4.11f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/Program Files/2019.4.11f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/2019.4.11f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)

**Comment by insthync** [comment]
Ahhh, I found it, I will fix it.

**Comment by brabaris** [comment]
Ok, we wait!

**Comment by insthync** [comment]
Fixed, it will be included in next update, which may be done next week.

**Comment by insthync** [comment]
Fixed in 1.61
