### ISSUE TITLE
Guild Exp Gain

### ISSUE THREAD

**Issue by fedas61** [suriyun-production/mmorpg-kit-docs#687]
Guild Increase Exp Gain Skill is not working

**Comment by insthync** [comment]
I will fix it, thank you for bug report :)

**Comment by insthync** [comment]
Fixed, it will be included in next update

**Comment by insthync** [comment]
Fixed in 1.61

**Comment by fedas61** [comment]
hello this is what i am talking about
these codes are written but have no functional value.


![image](https://user-images.githubusercontent.com/46999478/101137762-5d790e00-3620-11eb-9a12-9e70869c92bc.png)
![bandicam 2020-12-04 11-04-16-946](https://user-images.githubusercontent.com/46999478/101137837-78e41900-3620-11eb-9af8-ebc50d96bd87.jpg)

**Comment by insthync** [comment]
Yes, it was fixed

**Comment by fedas61** [comment]
my English is bad
yes its works but skill  %50 increase exp gain 
monster min 10 max 10 exp value = 14 exp 
role exp share = 0
%50 10 = +5  but +4 
It gives the missing percentage. What is the reason?

**Comment by insthync** [comment]
It was a wrong calculation bug,
In `DefaultGameplayRule.cs` 
Line 344 change it to
`exp += Mathf.CeilToInt(exp * guildData.IncreaseExpGainPercentage * 0.01f);`
Line 348 change it to
exp += Mathf.CeilToInt(exp * guildData.IncreaseShareExpGainPercentage * 0.01f);
