### ISSUE TITLE
Add BulkDismantle to mobile UI!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#691]
Add BulkDismantle to mobile / survival UI!
![1](https://user-images.githubusercontent.com/16080577/101166966-d472ce80-3641-11eb-8ac4-bf3f5751977b.jpg)

**Comment by insthync** [comment]
I just forget to set it. Don't worry about it, it will find automatically and assigned when enter the game, If you want to assign it just edit the prefab.
