### ISSUE TITLE
CanvasGameplay The camera does not turn!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#692]
CanvasGameplay UI The camera does not turn!

**Comment by insthync** [comment]
What? I don't understand this.

**Comment by brabaris** [comment]
:) Sorry, my mistake ...

**Comment by brabaris** [comment]
Indeed, the camera does not rotate in the Unity editor, but rotates in the compiled project ...

**Comment by insthync** [comment]
Which camera?, game play camera?

**Comment by brabaris** [comment]
Yes

**Comment by insthync** [comment]
To test mobile game you have to build and test on mobile device (or test on Bluestack :P).

**Comment by brabaris** [comment]
On previous versions (up to 1.61) everything worked fine!
