### ISSUE TITLE
CanvasGameplayMobile

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#693]
CanvasGameplayMobile not working: Jump, attack and move with joystick!
Although everything works fine in the editor!
![2](https://user-images.githubusercontent.com/16080577/101187876-984d6700-365d-11eb-93aa-73b84061a93d.jpg)
![3](https://user-images.githubusercontent.com/16080577/101187882-9aafc100-365d-11eb-846b-b74a96108f80.jpg)

**Comment by insthync** [comment]
To test mobile game you have to build on mobile device.

**Comment by brabaris** [comment]
On previous versions (up to 1.61) everything worked fine!

**Comment by insthync** [comment]
Hmm, but I actually does not changes anything relates to mobile controller :P
