### ISSUE TITLE
New UPDATE V 1.61 < Reload Ammo in Shooter Player Controller [Issue]

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#694]
![Untitled](https://user-images.githubusercontent.com/64667641/101224548-9902ef00-3697-11eb-9652-80e0974b7d2f.jpg)
This Error Shows up after i updated to V 1.61 ! i cannot move the character and cannot reload the gun .. it happens only when i use shooter player controller.

**Comment by RunOrDi3** [comment]
![fh](https://user-images.githubusercontent.com/64667641/101224883-99e85080-3698-11eb-9a2b-e17b59a0ede5.jpg)
Issue comes from this lines.

**Comment by insthync** [comment]
Oh, thank you for bug report.

You can fix it by add codes to avoid null data
from line 1056
```
        private void ReloadAmmo()
        {
            if (WeaponAbility != null && WeaponAbility.ShouldDeactivateWhenReload)
                WeaponAbility.ForceDeactivated();
```

**Comment by RunOrDi3** [comment]
np , it works now after i added WeaponAbility != null && .. thanks alot
