### ISSUE TITLE
Scope's Camera Position while Crawl

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#695]
in here when i open the scope , the camera moves to the place which the character body stands so i cannot see anything ... How can i change the location of the camera when i open the scope ? i have tried but no success...also i asked in discord but no one helped me .
![2](https://user-images.githubusercontent.com/64667641/101267529-5823dc80-3762-11eb-9169-f6382aad265b.jpg)

**Comment by insthync** [comment]
Try set `Fps Hidding Objects` and `Fps Hidding Renderers` 
![Screenshot_128](https://user-images.githubusercontent.com/2697550/101283002-b5736880-380a-11eb-9721-095cb37b7683.png)

Game Objects in `Fps Hidding Objects` will be deactivated and Renderers in `Fps Hidding Renderers` will be disabled when switch to FPS mode.
