### ISSUE TITLE
FPS Sound

### ISSUE THREAD

**Issue by klarkitgames** [suriyun-production/mmorpg-kit-docs#697]
In FPS mode guns make no sound when shooting.

**Comment by insthync** [comment]
It's because there is no fps model with the gun model with attached `EquipmentEntity` component attached, I will change how to setup weapon launch effects to make it easier to use later.

**Comment by klarkitgames** [comment]
Thank you!

**Comment by insthync** [comment]
Added `LaunchClip`, `ReloadClip` and `EmptyClip` to `WeaponItem`, `Item`(Have to set type to `Weapon`). Try it.
