### ISSUE TITLE
Limit buildings number / players

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#699]
Is it possible to add an option to limit the number of building per type (foundation, wall etc...) / per player? I ran a server test (mmo) and encountered performance issues related to the number of buildings. Thank you

**Comment by insthync** [comment]
Where the option should be, and how does it work?

**Comment by Koodetat** [comment]
I think a setting on each gamedata building (eg Building_Campfire) with the maximum number (X) of buildings per player, would be perfect. And a game warning message if you try to build a higher number of buildings.

In this case, a player cannot build more than X campfire for himself.
