### ISSUE TITLE
LiteNet Vis Checks and Server Auth

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#70]
When server authoritative movement is enabled, and the LiteNetLib Visible "Check Method" is set to Physics 2D, the player cannot load into the game.  Setting the Check Method back to 3D, fixes the issue.

OS: Windows 10
Connection: Separate Client and Server build, connecting over Local Area Network
Problem: Client stops loading at 100% (Not freeze).  Server logs keep outputting **[Chat] Update map user: Qfdd7EY2 by 0** over and over until the client is closed.
Version: 1.48c

**Comment by insthync** [comment]
Hmm, I will check it, I guess it is because of character's collider is 3D while "Check method" is 2D it is going to find for nearby characters with collider 2D, then when it can't find, it's freeze.

**Comment by Hawkadium** [comment]
Fixed
