### ISSUE TITLE
Issue V 1.61b Can assign more than one kind of entity to one spawn area. Missing

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#700]
i have updated my project to 1.61b and i have checked monster spawn area , i didn't find the option .. so i reimported from your site and nothing changed .. made new project and imported the asset and it still missing ... i found mail system and other things works but i didn't find that option
![Untitled](https://user-images.githubusercontent.com/64667641/101489534-c090da80-3969-11eb-99b1-c9522c958fff.jpg)

**Comment by Fallen01** [comment]
Ya and it broke advanced spawner which did everything you were asking for and so much more....
Suri do you think you can just do your new spawner as a different spawner and leave the old spawner as is for my addon.
My addon does alot more then you were trying to add and many of your customers own it. Its well loved and so much work has gone into it.

**Comment by Fallen01** [comment]
I basically tweaked up your game area spawners object, resource, and monster and gave them awesome options that people love. Random sizes, level, 4 groups of spawns based on rarity so you get everything from uncommon spawns to bosses from a single spawner. Y control max height and minimum height and even ground texture based resource spawning.... To much to list here, but hopefully you get the idea. Please leave the old spawner in the project.

**Comment by insthync** [comment]
[MMORPG_KIT_Fix_NoListInSpawnAreas.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5662867/MMORPG_KIT_Fix_NoListInSpawnAreas.zip)

**Comment by RunOrDi3** [comment]
Thanks

**Comment by insthync** [comment]
Fixed in 1.61c
