### ISSUE TITLE
DDL deploy error on mail using 1.61b

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#701]
Hi,
I got this error trying to execute mysql_main query to intialize db:

_ALTER TABLE `mail`   MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT	Error Code: 1075. Incorrect table definition; there can be only one auto column and it must be defined as a key	0.032 sec_

Am I missing somethings?

**Comment by brabaris** [comment]
Check out my post!
https://github.com/suriyun-production/mmorpg-kit-docs/issues/702

**Comment by insthync** [comment]
[mysql_main.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5662761/mysql_main.zip)

Use this file, I was missed to add indexing query script for `mail`.
