### ISSUE TITLE
Import MySQL Error!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#702]
There was an error while importing the database into MySQL 8.0. MMORPG version 1.61b.
#1075 - Incorrect table definition; there can be only one auto column and it must be defined as a key.
![mysql_error](https://user-images.githubusercontent.com/16080577/101530179-3f057080-399a-11eb-9bdf-fd365548640f.jpg)

**Comment by brabaris** [comment]
Required in line 524: MODIFY `id` bigint (20) NOT NULL ** AUTO_INCREMENT **;
Remove AUTO_INCREMENT.

**Comment by insthync** [comment]
[mysql_main.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5662751/mysql_main.zip)

Use this file, I was missed to add indexing query script for `mail`.
