### ISSUE TITLE
World map and quest navigation.

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#703]
Will it be added to the roadmap?

**Comment by insthync** [comment]
How quest navigation work? you means to make character move automatically to quest NPC ?

**Comment by Serivatech** [comment]
No. A mark on the map, for example, where the desired NPC is located or the monsters that need to be killed. As well as navigation to the desired place (Shows the path along which to go to get to the right place), for example (In this video, after receiving the quest, look at the ground in front of the player):

https://www.youtube.com/watch?v=EUoz4WQ8Y9E

This is very useful for open world games.

**Comment by insthync** [comment]
I am finding out how to setup it easily because especially: How to find the shortest path between Maps.
