### ISSUE TITLE
[BUG] ios build application "in background" (Single Player)

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#705]
When I deploy my game on ios (single player, not tested in mmo mode or on android), if i put the application in the background, when i return to the game, i encounter a UI_ERROR_CONNECTION_TIMEOUT. The character disappears and i have to do menu> quit. Is it possible to pause the game? I tried with "render extra frame on pause" (projectc settings> player> ios> others settings) but it doesn't change anything. It's not very user friendly, I'm looking for an alternative solution.

**Comment by insthync** [comment]
Okay, I will fix it.
