### ISSUE TITLE
[BUG] Canvas gameplay mobile UIHotkeyAssigner

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#706]
Since version 1.60 it is not possible to assign a weapon / shield or armor to the hotkey buttons (HotkeyButton) as on the previous versions. This works normally for potions and spells.

**Comment by brabaris** [comment]
mobile or standelone?

**Comment by Koodetat** [comment]
on mobile

**Comment by Koodetat** [comment]
Can anyone confirm this bug?

**Comment by insthync** [comment]
I still can assign weapon/armor to hotkeys and can use it.
You may check your hotkey filter in `CharacterHotkeys` component
![Screenshot_140](https://user-images.githubusercontent.com/2697550/101903767-5be2b380-3be7-11eb-806f-e4be9eb804f2.png)
