### ISSUE TITLE
Issue on update to 1.61b

### ISSUE THREAD

**Issue by applive3** [suriyun-production/mmorpg-kit-docs#707]
Hi how to solve this issues?
![issues](https://user-images.githubusercontent.com/40783613/102292622-50172a00-3f24-11eb-83c7-41160ad0c8f8.png)

thks

**Comment by insthync** [comment]
Try find  `TargetConstraintAttribute`
![Screenshot_144](https://user-images.githubusercontent.com/2697550/102304399-f64c4980-3f8f-11eb-9d7a-491328e30442.png)

Found it or not?

**Comment by applive3** [comment]
Yes the file exists.
![foud](https://user-images.githubusercontent.com/40783613/102331807-0e10d700-3f6a-11eb-8867-73d12357d8ee.png)

**Comment by insthync** [comment]
Try change from `In Assets` to `All` it may have the same class name in other packages
![Screenshot_145](https://user-images.githubusercontent.com/2697550/102339778-40512180-3fc8-11eb-89b4-bca36e078c65.png)

**Comment by applive3** [comment]
![foud2](https://user-images.githubusercontent.com/40783613/102340223-0acf1880-3f75-11eb-9db5-b7844969f083.png)
the file exists in all and in assets
![code](https://user-images.githubusercontent.com/40783613/102340363-34883f80-3f75-11eb-8e8e-ee421dbbd56a.png)

**Comment by insthync** [comment]
You may try to delete `SerializableCallback` folder which located in `/Assets/UnityMultiplayerARPG/Core` then try reimport te package by select only this folder.

**Comment by applive3** [comment]
Solved. one problem i canot change to mysql database in mmoserverinstance. How to fix? sorry for disturb :/
![oneproblem](https://user-images.githubusercontent.com/40783613/102350056-13c6e680-3f83-11eb-9f17-59c8cfe40971.png)

**Comment by applive3** [comment]
Ok in database network manager. ip address put real ip or localhost?

**Comment by applive3** [comment]
other question port 6100 should be opened in ssh just like the others?

**Comment by insthync** [comment]
If you're going start all servers at the same place with database server you can use localhost and doesn't have to open port for database server because it won't be connected remotely.

**Comment by applive3** [comment]
Solved. Thanks
