### ISSUE TITLE
Timeout in register - Using digital ocean.

### ISSUE THREAD

**Issue by applive3** [suriyun-production/mmorpg-kit-docs#708]
Hi. I did the whole process it connects to the server but the Timeout error appears in the user's registration. how can i fix this?
![timeout](https://user-images.githubusercontent.com/40783613/102372641-2a2e6b80-3f9e-11eb-80df-c95001c34186.png)

**Comment by insthync** [comment]
Is it server log?

**Comment by insthync** [comment]
Which command you use to start servers?

**Comment by applive3** [comment]
nohup /root/Build.x86_64 -startCentralServer -startChatServer -startMapSpawnServer
![log](https://user-images.githubusercontent.com/40783613/102379293-8052dd00-3fa5-11eb-8131-dc64c5fdfa62.png)
In directory log generated only this two files

**Comment by insthync** [comment]
Try `nohup /root/Build.x86_64 -startCentralServer -startChatServer -startMapSpawnServer -startDatabaseServer`

**Comment by applive3** [comment]
Same problem "Conection timeout"

**Comment by applive3** [comment]
Hello, I managed to solve it, it was just updating the net.framework but now I'm having trouble logging on to the map :(
![mapnotready](https://user-images.githubusercontent.com/40783613/102390344-0f1a2680-3fb3-11eb-9262-ccd5ba925fb3.png)

**Comment by insthync** [comment]
Did you open ports for map-servers?

**Comment by applive3** [comment]
work 👍 I forgot to open the map-server port now everything is working perfectly

**Comment by applive3** [comment]
Hello had succeeded. but when making some changes and sending to the server the error returned. same error in the pc and android version. how can i fix this?

(Exception)[No Tag] MySqlConnector.MySqlException (0x80004005): Authentication method 'caching_sha2_password' requires a secure connection (prior to .NET 4.6).

**Comment by applive3** [comment]
i m try install dotnet same error (Authentication method 'caching_sha2_password' requires a secure connection (prior to .NET 4.6).)
![dotnet](https://user-images.githubusercontent.com/40783613/102517149-75b04a80-406e-11eb-8820-5b3954757ac6.png)

**Comment by insthync** [comment]
You may try change mysql connection string codes in `MySqlDatabase.cs` -> function `GetConnectionString()`

```
        public string GetConnectionString()
        {
            string connectionString = "Server=" + address + ";" +
                "Port=" + port + ";" +
                "Uid=" + username + ";" +
                (string.IsNullOrEmpty(password) ? "" : "Pwd=\"" + password + "\";") +
                "Database=" + dbName + ";" +
                "SSL Mode=Required;AllowPublicKeyRetrieval=true;";
            return connectionString;
        }
```
Then rebuild/upload server files 
More detail: https://mysqlconnector.net/troubleshooting/retrieval-public-key/

**Comment by applive3** [comment]
should I put the access data in quotation marks in place of the semicolon?

**Comment by insthync** [comment]
To `true`

**Comment by applive3** [comment]
Oh ok will try

**Comment by applive3** [comment]
Work 👍
