### ISSUE TITLE
2dmmo bow problem and a doubt.

### ISSUE THREAD

**Issue by applive3** [suriyun-production/mmorpg-kit-docs#709]
1 According to the video even equipped with the bow. it does not attack from a distance or consume arrows. he follows the monster.

video --:>
https://drive.google.com/file/d/1ytZ3dgGMSOHQT5DWrV1JxkfMMemtrI0S/view?usp=sharing

2 - on the item staff001_2D how can I configure it so that when equipping it the attacks are the same distance as the bow but without the need for an item such as arrows. basically a simple magic attack.

**Comment by applive3** [comment]
Skill fire bolt same problem of the bow

**Comment by insthync** [comment]
As I try my demo, it still works, I want to see your `WeaponType` settings.

**Comment by applive3** [comment]
Hmm ok bow is ok, but fire bolt doesn't work what could be happening?

**Comment by insthync** [comment]
Try check damage info settings in skill game data
![Screenshot_146](https://user-images.githubusercontent.com/2697550/102577230-3fd09c00-412a-11eb-9cc9-d8a101cffe94.png)

**Comment by applive3** [comment]
it's like yours, I really don't understand why it's not working
![firebolt](https://user-images.githubusercontent.com/40783613/102608512-bf4d7380-4108-11eb-8206-fb89bd8bb637.png)

**Comment by applive3** [comment]
Skill Heal works fine. but firebolt not. :(

**Comment by insthync** [comment]
How about this setting 
![Screenshot_147](https://user-images.githubusercontent.com/2697550/102614759-6234da80-4167-11eb-88e5-781cf7d06cec.png)

**Comment by applive3** [comment]
apparently all right but it doesn't work.
![weapon](https://user-images.githubusercontent.com/40783613/102635907-b6719780-4132-11eb-83ac-8a4f6972538a.png)

**Comment by insthync** [comment]
Did your character equip staff item before use skill?

**Comment by applive3** [comment]
Yes. is equiped. see video 

https://drive.google.com/file/d/10qkl30QdZcEeiY6BW84bEoOv1iTQitkN/view?usp=sharing

**Comment by insthync** [comment]
Weird, it looks like the calculated attack range is 0

**Comment by applive3** [comment]
Hi insthync, I did some tests and testing on another character the firebolt really works but on the character "wizzard" that I created firebolt does not work I suspect that there is something wrong with the prefab of the character wizzard since on the other character the skill works perfectly. if you can analyze the video I made showing all the components and manage to identify where my error is, I would be grateful if you can inform me so that I can correct it. Thanks in advance. sorry for the inconvenience.
https://drive.google.com/file/d/1_TL9ZI0pQ4EgDBygZhrgFENalgKHSV7u/view?usp=sharing

**Comment by applive3** [comment]
Solved :)

**Comment by insthync** [comment]
How ?

**Comment by applive3** [comment]
I really do not understand.  I just redid the prefab and it worked.  honestly I couldn't identify what was wrong.  thank you very much for your attention and help
