### ISSUE TITLE
Quest, skillbar, and stones Bug

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#71]
Quest working fine in singleplayer mode, but as soon as you built the kit for mmo mode.. its all glitched..
Data writer works fine for the data reader does not.
deserialising of the data from database to client does not end well and u cant finish any quest or do any quest.

 Ive sent a few clips to you in pm on discord that shows exactly what these errors are.
Names Callepo in discord

**Comment by insthync** [comment]
Okay, I will check it and fix it

**Comment by Callepo** [comment]
we found the issue with quest and its fixed it seems
was by adding these 4 lines of code
![quest](https://user-images.githubusercontent.com/7702658/65567120-53a44700-df55-11e9-9e28-6650f93f98b4.JPG)

**Comment by insthync** [comment]
Okay, If it can solve the problem, then you can remove `DeserializeValueForSetOrDirty` and `SerializeValueForSetOrDirty` functions, I was override them to reduce packet size but it might too much :p, I will try to serialize everything except `dataId`, because `dataId` should be set only once when data insert or add to the list.

**Comment by Callepo** [comment]
yea that worked can u take a look at this ?
its hotkey assigning.. its deleting the assing window instead of closing it
https://www.youtube.com/watch?v=cDT9VLGQClQ&feature=youtu.be

**Comment by insthync** [comment]
Yep, I fixing it

**Comment by Callepo** [comment]
Someone reported this issue if u can look at it too would be nice

![Mounts](https://user-images.githubusercontent.com/7702658/65568926-bc8ebd80-df5b-11e9-939f-19877c2362af.JPG)

**Comment by insthync** [comment]
To fix `UICharacterHotkeyAssigner` you have to make `UIList` → `DetectPrefab` function to be public

![Screenshot_57](https://user-images.githubusercontent.com/2697550/65569370-92eb8b80-df87-11e9-86cd-497f6cbc2ae5.png)

Then in `UICharacterHotkeyAssigner` call `DetectPrefab` function before `Generate`

![Screenshot_58](https://user-images.githubusercontent.com/2697550/65569399-b0205a00-df87-11e9-9529-c5271f46cd22.png)

**Comment by insthync** [comment]
I will test mount animation and fix it

**Comment by Callepo** [comment]
thank you for ur time man we appreciate it.

Last thing if u have time.
ive been trying to equip armour  thats skinned mesh but its not been working..
tried ur tutorial and nothing.. idk if im doing something wrong or its glitched atm in kit

https://www.youtube.com/watch?v=F82PkyJ5AkQ&feature=youtu.be

**Comment by insthync** [comment]
Did you set this ?
![Screenshot_59](https://user-images.githubusercontent.com/2697550/65570073-22923980-df8a-11e9-8a92-5cb234fbd69f.png)

**Comment by Callepo** [comment]
if i remember correctly yes i did .. was the character skinned mesh body

**Comment by insthync** [comment]
Then you have to set armor model's bone weights, see this https://www.youtube.com/watch?v=rzau6SFcNOk&list=PLFt_AvWsXl0f4c56CbvYi038zmCmoZ4CQ&index=10

**Comment by Callepo** [comment]
this what i did 

![legs](https://user-images.githubusercontent.com/7702658/65572271-e64de180-df67-11e9-8187-9892583b9204.JPG)
![legs2](https://user-images.githubusercontent.com/7702658/65572312-fcf43880-df67-11e9-9f88-ced84f8a952d.JPG)

**Comment by insthync** [comment]
Yes, but seems like bone weights did not applied to the pants model, not sure your pants model has Skinned mesh renderer attached to it or its children?

**Comment by Callepo** [comment]
maybe its the bone weight or im doing something else wrong.. idk lol, Can i sent u a copy of the model and u can try set it up in the kit if urs dont work either ill check the bone weights.. if it works i know 100% im stupid lol
![legs3](https://user-images.githubusercontent.com/7702658/65573116-49d90e80-df6a-11e9-8908-1935c98daf99.JPG)

**Comment by insthync** [comment]
Yes, send it to my Discord

**Comment by Callepo** [comment]
done

**Comment by Callepo** [comment]
i seem to got it working.. but its not great.. 
instead of the body i had to put the legs for it to workd properly and not be buggy...
![legs 4](https://user-images.githubusercontent.com/7702658/65578542-421f6700-df76-11e9-8140-4263519f85de.JPG)

but now i have an issue with a different model that has a skinned mesh body and a skinned mesh legs 

![chest](https://user-images.githubusercontent.com/7702658/65578657-81e64e80-df76-11e9-8ea0-f9f8831094ca.JPG)
by doing the same i did before this model skinned mesh works fine too.. but problem is with the legs now...
if i put body here .. the body works fine,, and legs is glitched
if i put legs there.. the legs work fine but the body is glitched.. ..
This model doesnt have a Full body skinned mesh .. its all different parts 

https://www.youtube.com/watch?v=7J61Cev0Rc0&feature=youtu.be

**Comment by insthync** [comment]
For the first character pack, it will combine textures for `HumanMale_Mesh`  when changes clothes, I think the better way for this is to write `Character Model` extension to support it.

About the second one, as I see in the video, I think each clothes have difference bone weights, not use the same for every clothes, you can notice that each clothes has difference root bone, Try add following codes to make it work in `BaseCharacterModel.cs` after line 325
```
                if (tempContainer.defaultModel != null && tempEquipmentObject != null)
                {
                    SkinnedMeshRenderer defaultSkinnedMesh = tempContainer.defaultModel.GetComponentInChildren<SkinnedMeshRenderer>();
                    SkinnedMeshRenderer newSkinnedMesh = tempEquipmentObject.GetComponentInChildren<SkinnedMeshRenderer>();
                    if (newSkinnedMesh != null && defaultSkinnedMesh != null)
                    {
                        newSkinnedMesh.bones = defaultSkinnedMesh.bones;
                        newSkinnedMesh.rootBone = defaultSkinnedMesh.rootBone;
                    }
                }
```

![Screenshot_60](https://user-images.githubusercontent.com/2697550/65596403-fb0a9380-dfc0-11e9-9f2d-4bed28dc1ac3.png)

If it work I will improve the codes later

**Comment by Callepo** [comment]
Yes it works perfectly now with every part , Thank you for that fix.

**Comment by Callepo** [comment]
uhm The patch fixes u gave for the hotkey assigner works for 1.48C but in 1.48D it gives another error
and sockets are deleted when u teleport from weapons.. they are not saved.
u can see it all in this video
https://youtu.be/ldeXtwiNTRw

**Comment by insthync** [comment]
Equipment Sockets not saved is fixed

**Comment by insthync** [comment]
Hotkeys lose issue is fixed
