### ISSUE TITLE
Skill cast effect

### ISSUE THREAD

**Issue by lundgren84** [suriyun-production/mmorpg-kit-docs#711]
If you create a skill and want a effect your forced to add `Cast Duration`
and this triggers the cast animation and so on.. is it possible to have a `Cast Effect` with 0 in `Cast Duration`

![image](https://user-images.githubusercontent.com/17403413/102456647-c9586f00-4041-11eb-9463-1f75d354cb81.png)

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.61c
