### ISSUE TITLE
How to make character repeat crafting skill?

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#712]
I want to make crafting skill can be repeated as user want(input number of craft skill repeat) This is for the case user need to craft many same items.
I'm going to add a input ui to UISkillDialog to input the number of skill repeat,  then add repeat code to "OnClickSkillUse" function.

But here I have a problem. How to know previous crafting is done?

Can you advise me how to implement this?
Thanks!!!

**Comment by insthync** [comment]
I will make it add to crafting queue when click on use button, so I also have to add craft queue system.

**Comment by insthync** [comment]
In next version, it will have queued crafting system
https://storage.ko-fi.com/cdn/useruploads/display/b1b64de1-3f88-49f8-9fc7-f1dd6e25218f_screenshot_230.png

**Comment by dglee2592** [comment]
Thank you so much!!!!
