### ISSUE TITLE
Respawn monsters FPS drop

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#713]
Target platform: ios (single player)

When monsters respawn, fps drop (micro freeze) by around 5-6 fps. Except this problem,  mygame works normally, I have limited the fps to 30, to conserve battery life, but the game runs smoothly at 60 fps on high end mobiles.  

On a windows build it is less noticeable, but the problem also exists.

**Comment by insthync** [comment]
Seems like it's because of network spawn codes, I will improve it.

**Comment by insthync** [comment]
It's slow because of identity object id assigning function and stats caching codes, I will improve it.

**Comment by Koodetat** [comment]
Great thank you

**Comment by insthync** [comment]
This was fixed.
