### ISSUE TITLE
Root motion using server authoritative movement

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#714]
Hi,
My character uses **server authoritative** movement and **root motion** but it result motionless when using skills/attack (**mmo mode**).
The same skills/attack in local mode have forward movements.
Is root motion supported using mmo mode and server authoritative ??
Everything work using Local.
I am using 1.61b and "move speed rate while attacking" set to 0.
Thanks

**Comment by insthync** [comment]
Hmm, it should work, I will test it.

**Comment by Fr-Coder** [comment]
Hi, any update on this ?

**Comment by Fr-Coder** [comment]
Closing because it needs to be retested with new kit version (that use client side prediction)
