### ISSUE TITLE
[Suggestion] Player Shop system in MMO

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#715]
because you won't add auction house soon , i offer to you an small good option and that option is the player be able to open an shop to sell his items to other players like he will be sitting on the ground and his name will be like red color and other players can press on him , when they press on him , an ui will be appear can handle the items with price and able to be buying by players..i found this option in many mmo professional games.
Thank you for your great effort

**Comment by applive3** [comment]
good.  these days had even asked if he had any addons.  would be great.  something like Ragnarok autotrade / player shop

**Comment by applive3** [comment]
Up

**Comment by RunOrDi3** [comment]
i hope suriyun will accept this .. its very important if there is no auction house

**Comment by Serivatech** [comment]
I saw it somewhere. Lineage :)

**Comment by insthync** [comment]
I saw it from Ragnarok, Cabal :P

**Comment by Serivatech** [comment]
What have you decided about this?

https://github.com/suriyun-production/mmorpg-kit-docs/issues/703

**Comment by RunOrDi3** [comment]
@insthync i hope you will do it as soon as you can 👍

**Comment by Fr-Coder** [comment]
I agree, this a great things better then auction house for me

**Comment by insthync** [comment]
Moved to https://github.com/suriyun-production/mmorpg-kit-docs/issues/1129
