### ISSUE TITLE
NewMesh Surface not showing in My_TestMap

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#716]
I am following your youtube video -> https://www.youtube.com/watch?v=BsuWScMnRYA&list=PLPc4hSd4HARf107_w22XkU0BffC8t2T8O&index=2 . Without missing any step until In the 'Preparing Database and Test Map', I noticed that
I do not see anything like NavMesh Surface in my own My_TestMap even when I didn't skip and step. I just got this asset yesterday. and compile it to PC and Android and it worked correctly. Please what is wrong? Please assist me. Thanks!

**Comment by insthync** [comment]
You can use following [this instruction](https://docs.unity3d.com/Manual/nav-BuildingNavMesh.html) to build nav mesh

**Comment by isaanyoha** [comment]
Ok, Thanks! Let me check it out
