### ISSUE TITLE
About the updated Area Spawner

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#718]
delete

**Comment by moepi2k** [comment]
or implement it in core? ^^

**Comment by Zaraath1** [comment]
I agree,  Fallen's addon was nice.

**Comment by Fallen01** [comment]
Its fixed hehe

**Comment by insthync** [comment]
In next version, I am going to add randoming level setting, you may share your addon to my email (ittipon.bay@gmail.com) so I will try to make it work with yours.

**Comment by Fallen01** [comment]
I have random levels Y control random sizes.. %chances for different groups of spawns and more

**Comment by Fallen01** [comment]
Would it be easier to just give you git access?  Insynchc

**Comment by insthync** [comment]
Okay

**Comment by insthync** [comment]
I am not going to include it to the Core, just to make Core's codes not break your addon :P

**Comment by Fallen01** [comment]
I appreciate that your busy making a whole mmorpg kit. I have alot more time to work on smaller things haha,

**Comment by Fallen01** [comment]
I need to update my repo but youll get an invite to FallenEntertainment at some point today thank you for taking the time.

**Comment by Fallen01** [comment]
Ive sent you an Invite Let me know if you get it. Thanks again for your time.
