### ISSUE TITLE
Mount Sounds and Player Movement

### ISSUE THREAD

**Issue by Hawkadium** [suriyun-production/mmorpg-kit-docs#72]
1) If a Player tries to use his mount, while moving, the foot step sounds will play indefinitely.

2) If a Player uses Click to Move and mounts up before reaching the Destination, movement is stopped and appears to be working as normal.  However, once the player gets off the mount, the Character will start moving to the original Click to Move destination.

Windows 10
MMO Mode
1.148d
Video: https://youtu.be/DPRcQFM12dM

**Comment by insthync** [comment]
Fixed, this will be included in the next version package, Thank you for your issues report :)
