### ISSUE TITLE
WebGL websocket not working

### ISSUE THREAD

**Issue by Joshua2504** [suriyun-production/mmorpg-kit-docs#723]
Hey,

great asset! Everything is working fine in 2D, apart from websocket.

I followed your YouTube tutorial, but ended up with the server not running websocket. I ticked the option in MMOServerInstance. Server is running on linux. This is the actual app: http://httpcdn.treudler.net/RO2D_webgl/index.html

I can connect using the editor to port 7000 non-websocket, but as soon as I enable websocket for MMOClientInstance, it doesn't connect anymore.

Is this known? Seems like someone asked this months ago in Discord, here https://discord.com/channels/460801727789137920/460803281455939595/745169859696132117

Regards

**Comment by insthync** [comment]
Here is some checklist:
* Not sure did you already tick on `Use Web Socket` in `MMO Server Instance` or not.
![Screenshot_153](https://user-images.githubusercontent.com/2697550/103051891-64b18d00-45ca-11eb-9512-702b04840ae1.png)
* Did you open ports that client have to connect?

**Comment by Joshua2504** [comment]
Websocket is ticked in MMO server instance

All ports are open. I'm not using any firewall.

Could you test it yourself please? Seems like I'm not the only one having this issue. 

note the server is running on Linux. Do I need to pass some start parameter?

**Comment by insthync** [comment]
Okay, I will test it again.

**Comment by Joshua2504** [comment]
Thank you a lot. DM me in Discord (Joshua2504#2917) if you want a demonstration of the problem.

It's the only thing I need to fix to get started with the kit.

**Comment by insthync** [comment]
It's an execution order problem, I will fix it in the next version, for now, you can tick `Use Web Socket` for the 
following components

- CentralNetworkManager
- MapSpawnNetworkManager
- ChatNetworkManager
- MapNetworkManager

![Screenshot_276](https://user-images.githubusercontent.com/2697550/103472651-503b7480-4dc2-11eb-9b94-89bdd25fb80c.png)

**Comment by insthync** [comment]
Try 1.61c
