### ISSUE TITLE
[Bug]Trade with dead players

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#724]
if a player is dead and click on continue, while dead he can still trade with other players

**Comment by insthync** [comment]
Not sure that it is a bug or not, some games may allow players to trade resurrect item to another character :P, I'm okay to add option to allow this or not in gameplay rule.

**Comment by moepi2k** [comment]
Ah then 😂😂😂 an option would be nice yea 👍
