### ISSUE TITLE
MMORPG KIT Stress Test 

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#725]
Hi, Me and a few other community members performed a high level stress test with bout 1.2k clients and i written up a full report with everything we found . 
Please have a look,

Edit.. Ill Email it to you to not make it public.

@insthync

**Comment by insthync** [comment]
Wow, thank you :)

**Comment by Callepo** [comment]
@insthync is it possible to check into the login server as mentioned in the results .
i would love to try 1k+ CCU combined over multiple maps

**Comment by Callepo** [comment]
I redid a Test with Mysql today thinking maybe SQLITE was the issue..
Same results with Mysql that I got with Sqlite..
so I gather the logs from todays test and found a lot of error logs in it..
maybe they mean something to u

kind regards

Callepo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Callepo** [comment]
IF u want more info bout the test pls let me know ill provide whatever I can.

Best Regards.

Callepo.
