### ISSUE TITLE
[Bug]Interacting throught Colliders

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#728]
right now you can interact (talk to npc, open door/chest) throught walls. only way to prevent this is to reduce conversation distance. but it need to be <0.2 that it works.

when player build houses and place chest in it, other players can open it throught the walls. I know there is an option to lock it, but there also some things they can interact like workbenchs, campfires or pick up items on ground.

so is there a way to check serverside if there is a collider between player and the interactable object?

**Comment by insthync** [comment]
Can add codes to do raycast in `BasePlayerCharacterEntity_NetworkResponse` class there are several functions such as `ServerOpenDoor`, `ServerCloseDoor` and so on. I will add check walls codes in next version.
