### ISSUE TITLE
UMA database Issues

### ISSUE THREAD

**Issue by klarkitgames** [suriyun-production/mmorpg-kit-docs#731]
UMA characters do not save changes when they are created.

**Comment by insthync** [comment]
Your project is MMO game or Singleplayer game, which database are you using ?

**Comment by klarkitgames** [comment]
It happens using MMO & single player using SQLite.

**Comment by insthync** [comment]
New release for `UMAExtension`, But it's required CORE version `1.62`, As I try it has no data saving problems.
