### ISSUE TITLE
[Suggestion] More than 1x drob table inside Monster MMO

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#732]
Will be great if you make option to add more than 1x drob table inside Monster , because its important to make 1 table for weapons , another for items and so on in 1 monster ..so more than 1x drob table in 1 monster is important
thanks for your hard work.

**Comment by DimasjkTV** [comment]
Yes, this will greatly simplify the process.

**Comment by RunOrDi3** [comment]
i hope he saw this anyway
