### ISSUE TITLE
UICharacterSkill Modification Help

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#733]
Ive been trying to get skills to be usable from the UISkillDialog directly and Ive attempted to modify UICharacterSkill in order to do this. Studying everything from the workbench to hotkey Im not having any luck. Is there a way to accomplish this? Thanks for your time.

**Comment by Fallen01** [comment]
![image](https://user-images.githubusercontent.com/57778639/103928883-7165d300-50ea-11eb-8f96-1ebbb0ab17e0.png)

**Comment by Fallen01** [comment]
I check this post multiple times per day so if your answer is no please say it so i can move on with life, lol.
<3

**Comment by insthync** [comment]
Have to changes many things to do it,
- Define a source of skill to `UICharacterSkill`, it is from an Item or learned skill.
- Have to make a queueing skill function in `BasePlayerCharacterController` to be public
- Add button event function to `UICharacterSkill`
- Add function to update aim position to `UICharacterSkill` and may be called in `Update` function to update aim position, and will call functions in `BasePlayerCharacterController` to use skill with aim position.

**Comment by Fallen01** [comment]
wow that is a mess thank you for responding

**Comment by Fallen01** [comment]
What im trying to do here is move crafting to its own dialog because it really doesnt belong on your hotkeybar

**Comment by Fallen01** [comment]
I thought the best way would be to do its own skill dialog filter for the desired crafts and use from the dialog, but now im not so sure.

**Comment by insthync** [comment]
In next version, it will have queued crafting system
https://storage.ko-fi.com/cdn/useruploads/display/b1b64de1-3f88-49f8-9fc7-f1dd6e25218f_screenshot_230.png
