### ISSUE TITLE
Suggestion: Quest indicators & Hint

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#734]
We have now two quest indicators:
1. In progress
2. New
Can you add a third indicator after the quest is marked as completed?
For the "In progress" example, the question mark is gray, and after completion, the question mark is yellow. Just like in WoW.

Text hint on the screen after completing the quest "Quest completed".

**Comment by Koodetat** [comment]
Good idea !

**Comment by insthync** [comment]
Added in `1.61d`
