### ISSUE TITLE
Suggestions&Questions.

### ISSUE THREAD

**Issue by FleksisLV** [suriyun-production/mmorpg-kit-docs#735]
1. Need to make info when item is droped like name of the item and the level of it, on top of the item, like nickname is showed, because for moment when item is droped, you need to pick it up to know how good it is.

2.Is there chance that you can make that the skills cast straith way after pressed hotkey on the direction where mouse is located ?

I have also question, can you please tell me how can i make area skill cast straith way after pressed hotkey, where mouse is located, not like i still need to press the mouse to cast it.

Thanks, i hope you will add the's features in future .

**Comment by insthync** [comment]
For the 2. 
Try changes codes in `UICharacterHotkeys` -> function `UpdateHotkeyInputs` -> remove `if (Input.GetMouseButtonDown(0))` to make it use skill immediately, I didn't tried it yet.

**Comment by FleksisLV** [comment]
Thanks, works like charm.
