### ISSUE TITLE
Quest: Talk to NPC

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#736]
Did anyone manage to set up this quest? It feels like it doesn't work.
And it looks like there is no code in the script language to describe such quests.
![image](https://user-images.githubusercontent.com/47291794/104092451-1fad7c00-5295-11eb-95da-fafdd3f0f5e0.png)
![image](https://user-images.githubusercontent.com/47291794/104092459-2d630180-5295-11eb-94b8-028d4a0f3abc.png)

**Comment by insthync** [comment]
Format for task to npc task will have only 1 parameter for NPC's name, default keys are:
- `UI_FORMAT_QUEST_TASK_TALK_TO_NPC` for In-progress task
- `UI_FORMAT_QUEST_TASK_TALK_TO_NPC_COMPLETE` for complete task

![Screenshot_162](https://user-images.githubusercontent.com/2697550/104590343-c6cb5280-569d-11eb-9884-5cfdd0f22ab6.png)

**Comment by DimasjkTV** [comment]
> Format for task to npc task will have only 1 parameter for NPC's name, default keys are:
> 
> * `UI_FORMAT_QUEST_TASK_TALK_TO_NPC` for In-progress task
> * `UI_FORMAT_QUEST_TASK_TALK_TO_NPC_COMPLETE` for complete task
> 
> ![Screenshot_162](https://user-images.githubusercontent.com/2697550/104590343-c6cb5280-569d-11eb-9884-5cfdd0f22ab6.png)

Was this added recently? When I created this theme, the version where I tested it did not have this. But had the opportunity to add talk to NPCs to quests.

**Comment by insthync** [comment]
It was added maybe 2 months ago.
