### ISSUE TITLE
BUG? Quests

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#738]
Watch the video.

In my game, I take a quest from one NPC and turn it over to another NPC. Because of this, they for some reason have common indicators. And after that, if the first NPC no longer has quests, and the second one will have quests - the first NPC will also receive indicators from the second NPC.

[Quests bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5792063/Quests.bug.zip)

**Comment by insthync** [comment]
I will check it.

**Comment by DimasjkTV** [comment]
> I will check it.

Also, indicators of the availability of the quest are displayed by the NPC even if the character has not yet met the requirements for obtaining this quest.

**Comment by insthync** [comment]
Okay

**Comment by insthync** [comment]
Try 1.61d

**Comment by DimasjkTV** [comment]
> Try 1.61d

Still indicators of availability of the quest are displayed by the NPC even if the character has not yet met the requirements for obtaining this quest.

**Comment by DimasjkTV** [comment]
> Try 1.61d

still same situation. I need to take the quest from the first NPC and turn in the same quest to the second NPC. In this case, we get general indicators. The first NPC should not show an indicator if the quest is not handed over to him.

**Comment by DimasjkTV** [comment]
or maybe can u add Quest task completed req for quests?
![image](https://user-images.githubusercontent.com/47291794/105578436-4a1d3000-5d91-11eb-9544-e97ba1d70893.png)

**Comment by insthync** [comment]
Try changes condition in `NpcEntity.cs`, function `FindQuestFromDialog`, line `165` 
from
```
if (menu.isCloseMenu && !menu.IsPassConditions(playerCharacter)) continue;
```
to
```
if (menu.isCloseMenu || !menu.IsPassConditions(playerCharacter)) continue;
```

**Comment by DimasjkTV** [comment]
> if (menu.isCloseMenu || !menu.IsPassConditions(playerCharacter)) continue;

yes it works! thank you so much!
