### ISSUE TITLE
1.61c changelog

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#739]
is it possible to put the changelog of version 1.61c?  thank you

**Comment by RunOrDi3** [comment]
ye we hope so too...

**Comment by Callepo** [comment]
lol.. it always come up give him time to write it.. update was big lol

**Comment by RunOrDi3** [comment]
we noticed that ye , we are waiting

**Comment by Joshua2504** [comment]
He could just write the changelog while he changes things. That's what you use commits for.

LOL

**Comment by Callepo** [comment]
1 ) The kits repo is not public... we cant see his commits..
2) change log is on a page, he always provides it.. and i update it to discord...
3) Always some loudmouthed fool lol..

not thats a lol.. 
act like u cant w8.. is ur game gonna release today ? change log change anything?

**Comment by RunOrDi3** [comment]
for sure change log its important , we are not coder like you to understand the files which he has changed it or the improvments he made , so its important for us!

**Comment by insthync** [comment]
A new version changelog was written

**Comment by Joshua2504** [comment]
> 1 ) The kits repo is not public... we cant see his commits..
> 2) change log is on a page, he always provides it.. and i update it to discord...
> 3) Always some loudmouthed fool lol..
> 
> now thats a lol..
> act like u cant w8.. is ur game gonna release today ? change log change anything?

you don't release an update if you don't have the changelog for it. people want to actually use the update if it's made public, so it's clear non-sense to not write a changelog before updating.
Also, I never said that the commits are public. If he does proper commits in his repo, he can use them to write a changelog pretty quickly - that's what I do.

Actually, I'm not gonna release any game. But yes, always some loudmouthed fool - which is you, who crawled in his ass as deep as only possible and doesn't want to leave a single bad word about him. It's fine.

**Comment by Callepo** [comment]
XD took you long enough to respond.. 
best u could have come up with after 24 hours :P
Its amusing at the very least.

i dont sit around and complain like lil bitches.
i only speak truth, but u wouldnt know that lol.
ive tested the whole kit and givin my honest opinion about it, number of times.
told him exactly whats bad. whats needs fixing. with proof.
so miss me with that bs 

The release wasnt even official yet as he didnt upload it to his site , which when he does he instantly put up changelog with it
but cheers m8 lol. ill go put my head back up his ass, its so warm

**Comment by Callepo** [comment]
ps. Changelog is up now :) along with 1.61D + its changelog hurry go read it. do nothing with it anyways..
hurry
