### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by pparkdea** [suriyun-production/mmorpg-kit-docs#74]
![01](https://user-images.githubusercontent.com/55903220/65810312-e8bc6f80-e1e3-11e9-90f7-d724a333e25b.gif)

Become a move during skill casting.

![01](https://user-images.githubusercontent.com/55903220/65810316-01c52080-e1e4-11e9-87cc-43b9e0f31149.jpg)

![05](https://user-images.githubusercontent.com/55903220/65810343-4ea8f700-e1e4-11e9-8cec-792e40a45f3e.jpg)

This only happens with keyboard:WASD
version: 1.48c

++
click move is the same...
If you click once, move speed becomes 0, but if you click several times quickly, you get a problem.

**Comment by insthync** [comment]
![Screenshot_75](https://user-images.githubusercontent.com/2697550/65829199-cfdbb900-e2cc-11e9-8622-e13cfd507d3a.png)

Try set `MoveSpeedRateWhileUsingSkill` in your skill to `0`

**Comment by pparkdea** [comment]
![01](https://user-images.githubusercontent.com/55903220/65829512-6619da00-e2e1-11e9-9171-b5b4dc9d3e29.jpg)

**Comment by pparkdea** [comment]
Setting it to 0 causes problems.

**Comment by pparkdea** [comment]
![01](https://user-images.githubusercontent.com/55903220/65829616-3a4b2400-e2e2-11e9-9d2f-732678991edc.jpg)
Same animation clip
![03](https://user-images.githubusercontent.com/55903220/65829627-55b62f00-e2e2-11e9-9022-4c942da4c7c2.gif)
attack
![04](https://user-images.githubusercontent.com/55903220/65829637-69fa2c00-e2e2-11e9-9a21-54c1cd79556c.gif)
skill

**Comment by insthync** [comment]
Okay, I will check and fix it

**Comment by insthync** [comment]
Thank you for your bugs report :)

**Comment by pparkdea** [comment]
thank you!!!

**Comment by insthync** [comment]
Fixed, will be included in 1.49

**Comment by pparkdea** [comment]
thank you!!

**Comment by pparkdea** [comment]
What files did you edit?
The character has some delay after blocking motion and I want to fix it.

**Comment by pparkdea** [comment]
I am trying to modify the "bool action" time.

**Comment by insthync** [comment]
In BaseCharacterEntity_SkillFunctions.cs find for `moveSpeedRateWhileAttackOrUseSkill = GetMoveSpeedRateWhileAttackOrUseSkill`

I was fix it from
```
moveSpeedRateWhileAttackOrUseSkill = GetMoveSpeedRateWhileAttackOrUseSkill(animActionType, null);
```
To
```
moveSpeedRateWhileAttackOrUseSkill = GetMoveSpeedRateWhileAttackOrUseSkill(animActionType, skill);
```

**Comment by pparkdea** [comment]
Thank you!!!

**Comment by pparkdea** [comment]
yield return new WaitForSecondsRealtime((totalDuration - triggerDuration) * playSpeedMultiplier);
To
yield return new WaitForSecondsRealtime(triggerDuration * playSpeedMultiplier);


This change eliminated the delay. :)
