### ISSUE TITLE
1.61C mapserver issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#740]
![image](https://user-images.githubusercontent.com/7702658/104449700-4b837700-559f-11eb-9cd8-bb0db6c7893a.png)

it keeps saying reconnecting over and over again none stop
all works except maps.. u cant click start

**Comment by Callepo** [comment]
@insthync

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/104450246-13306880-55a0-11eb-9a2f-d4a4b10d17f5.png)

**Comment by Callepo** [comment]
oh.. 
![image](https://user-images.githubusercontent.com/7702658/104451073-59d29280-55a1-11eb-84ec-2eea7da5043a.png)

Network port was 7000.. i changed to 6000 and it works.. 
i saw u used 7000 for testing webgl.. did u forget to put back to 6000?

**Comment by insthync** [comment]
I've changed Central-server port to 7000 for WebSocket testing,
But I didn't other servers ports (I've use configs file for testing)
You have to changes central port setting in `00Init_MMO` -> following components
- MapSpawnNetworkManager
- ChatNetworkManager
- MapNetworkManager
![Screenshot_159](https://user-images.githubusercontent.com/2697550/104451265-ded69f80-55d3-11eb-9bb5-2e52a6da1840.png)

Or use server-configs file

**Comment by Callepo** [comment]
ah cool ty

**Comment by Callepo** [comment]
@insthync  i changed them all to 7000 but now client wont connect to it
![image](https://user-images.githubusercontent.com/7702658/104452317-22fd7c00-55a3-11eb-997f-3977dc8e5143.png)

**Comment by Callepo** [comment]
Sorry,.. nvm i had web sockets checked by accident..sorry

I will be performing a nother stress test later on today or tomorrow with this new Version to see if there any improvement..
i noticed you changed how the kit handles request and responses. and the new handler scripts! .. i love it! 
im hoping it performs much better.. 
I will keep u updated

**Comment by Callepo** [comment]
@insthync 
![image](https://user-images.githubusercontent.com/7702658/104463373-fa30b300-55b1-11eb-8fa7-9b43d65764c2.png)

Any suggestion?

**Comment by insthync** [comment]
Not sure that you built it as x86 or x86_64, it have to be x86_64 because the dll file complied for x86_64
![Screenshot_160](https://user-images.githubusercontent.com/2697550/104464948-14848400-55e6-11eb-9df6-099d79b412ea.png)

**Comment by Callepo** [comment]
Linux build on ubuntu 20.04 server 
![image](https://user-images.githubusercontent.com/7702658/104465152-074ea180-55b4-11eb-966c-4f0bf0edc1e9.png)
i think my grpc plugin is busted..
in my folder its 1kb.. 
but on github is show 86mb..
i tried reimporting it and its 1 kb again
![image](https://user-images.githubusercontent.com/7702658/104465259-24837000-55b4-11eb-95ae-b30d9873c57e.png)

**Comment by Callepo** [comment]
https://github.com/insthync/UnityMultiplayerARPG_MMO/tree/main/Plugins
downloaded this..
grabbed the whole plugin folder.. put in project.. 
and the So file went back to 1kb.. ? is this supposed to happen?

**Comment by Callepo** [comment]
https://github.com/insthync/UnityMultiplayerARPG_MMO/blob/main/Plugins/Grpc.Core/runtimes/linux/x64/libgrpc_csharp_ext.so

I had to download this separately.. put it in my project . Only like this did it not go to 1kb..
and server started

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/104465996-fce0d780-55b4-11eb-8034-be7c73ddae88.png)

100% dll issue.. 
it keeps going to 1kb.. idk why.. only by manually adding only the .so file it will work any other way it breaks and go to 1kb.

**Comment by insthync** [comment]
Hmm, maybe it is an asset store tools packing issues...

**Comment by Callepo** [comment]
@insthync 
https://we.tl/t-9w2AcPC2QP

Can u login pls? and look

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/104469440-cf962880-55b8-11eb-8c0b-aa2290d00dfe.png)
226 clients

**Comment by insthync** [comment]
Okay

**Comment by Callepo** [comment]
Log mailed to u @insthync

**Comment by insthync** [comment]
Okay

**Comment by Joshua2504** [comment]
I wonder how you guys got webgl to run, because it never worked for me.

**Comment by Callepo** [comment]
was clearly stated im using linux build not webgl or websockets

**Comment by Joshua2504** [comment]
You're right, I missunderstood.

**Comment by moepi2k** [comment]
i got same error. changed port back to 600 but then i cant reach server.

what exactly need to be changed now?

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/104494452-c0be6e80-55d6-11eb-9eda-8de837de6437.png)
Do this..
or use config files and put central on 7000 also

**Comment by Callepo** [comment]
@insthync i have mailed u regarding Sequenced
