### ISSUE TITLE
(!!!) Reboot and shutdown of the server.

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#742]
(Translated from Russian)

It is necessary to add the ability from the game with the GM command to reboot and shut down the server for maintenance.
For example:
* Reboot the server immediately or after a certain time (in this case, the players are shown a message and the time counts down). The server is started without the participation of the administrator.
* Turn off the server immediately or after a certain time (in this case, the players are shown a message and the time counts down). The game server shuts down and you can update the files.

Add the ability to do this:
* Reboot the server at 6:00 on Monday (Before the reboot, there is a notification to the players with a countdown).

**Comment by insthync** [comment]
I think most developers would build the server for Linux, which I don't know how to make it able to enter console commands with Unity. So I think it should have a management web that can enter commands there then after entered it will send commands to game-servers.
