### ISSUE TITLE
Errors in update V 1.61d latest one

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#744]
![Untitled](https://user-images.githubusercontent.com/64667641/104667282-690b2a80-56de-11eb-8664-630e3b42d6e7.jpg)
when i have updated my files to v 1.61d , that errors shows up..that errors cannot be clean !! my files not working now -.-

**Comment by RunOrDi3** [comment]
![fg](https://user-images.githubusercontent.com/64667641/104668406-ad97c580-56e0-11eb-8d0a-358b7f37be73.jpg)
![dsf](https://user-images.githubusercontent.com/64667641/104668410-ae305c00-56e0-11eb-85aa-16aa04a96df3.jpg)
errors in that lines..

**Comment by insthync** [comment]
Delete `MixTransportEventListener` and `LiteNetLibTransportEventListener`

**Comment by RunOrDi3** [comment]
the whole scripts ?delete them from files ? @insthync

**Comment by insthync** [comment]
Delete those files (.cs files)

**Comment by RunOrDi3** [comment]
thanks , works fine now 💯

**Comment by FleksisLV** [comment]
Also get error on the tcp version on the same folde after deleting them i find the error get's away. But not sure if it was right thing to do.

**Comment by FleksisLV** [comment]
@insthync when click on an item an error appear "NonEquipItem"

**Comment by insthync** [comment]
> Also get error on the tcptransport.cs on the same script folder after deleting them i find the error get's away. But not sure if it was right thing to do.

You can re-download TcpTransport, I was updated it.

**Comment by insthync** [comment]
> @insthync when click on an item an error appear "NonEquipItem"

Oh, it's just a testing log, I will remove it, you can ignore it for now or go to the codes where it told you in `Console` to remove it.

**Comment by DimasjkTV** [comment]
> > @insthync when click on an item an error appear "NonEquipItem"
> 
> Oh, it's just a testing log message, I will remove it, you can ignore it for now or go to the codes where it told you in `Console` to remove it.

![image](https://user-images.githubusercontent.com/47291794/105623867-35db4080-5e2e-11eb-9cf5-562f25851663.png)
After monster kills

**Comment by DimasjkTV** [comment]
> > @insthync when click on an item an error appear "NonEquipItem"
> 
> Oh, it's just a testing log message, I will remove it, you can ignore it for now or go to the codes where it told you in `Console` to remove it.
Abount this. What is script? When I click on this, nothing happens.
![image](https://user-images.githubusercontent.com/47291794/105623892-691dcf80-5e2e-11eb-9532-c89ee097947c.png)

**Comment by DimasjkTV** [comment]
It's strange. In my project I click on the error and the screen doesn't open. Created a fresh project and the script opened after clicking.
