### ISSUE TITLE
Add Friends issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#746]
You can add same person as friends over and over infinitely 
![image](https://user-images.githubusercontent.com/7702658/104776586-95748480-577a-11eb-9b33-3600189e60af.png)

And before if UIFriend was closed.. i can still add people to friends
now u cant anymore.

![image](https://user-images.githubusercontent.com/7702658/104776820-f7cd8500-577a-11eb-9299-bb89d3645ccc.png)

i have an addon where u can right click a chat and u can add that person as friend or join them to ur party or guild etc
But after 1.61D if u add them, cuase the ui is closed it wont get invoked.. and it doesnt add to friends.
But party and guild all works fine.

Is there something wrong with friends being processed on the server?
is should still add it to db on the server and when i open the ui it should update the friends list..

**Comment by insthync** [comment]
- I will fix duplicating friend list issues.
- I want to know when you press on add friend, then whic function will be invoked?

**Comment by Callepo** [comment]
it works exactly how opening the UIfindplayer works with selecting a player name and click add friend
A window will open for Do u want to add "Playername" as friend which then u click yes.
So im using this 
![image](https://user-images.githubusercontent.com/7702658/104796226-afcb5400-57b4-11eb-9e88-5aa6d6289b9d.png)

But i changed it to grab the player name from Chat Right click.

It works perfectly fine if u have the ui opened and then right click chat and click add friend..
it updates instantly in the list.
but if ui is closed and i do add friend, And then after open ui.. the list is empty.
i try now with ui opened... Now it appears 2 times same name.

So the first one did go through.. but it was never processed. cuase ui is closed
Ill make a video

**Comment by Callepo** [comment]
@insthync  https://imgur.com/gTbHK6i
