### ISSUE TITLE
Partial Class

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#747]
![image](https://user-images.githubusercontent.com/7702658/104790044-b945c380-5796-11eb-9ff0-2e27f3dcb194.png)

GameNetworkTransportExtensions
I think this class was Partial before, cuase i have a few scripts using it as partial.. and now its telling me 
![image](https://user-images.githubusercontent.com/7702658/104790083-d9758280-5796-11eb-868b-a13ee7dc0530.png)

was it changed? if so why ?
and can it go back to partial?
Thank you

**Comment by insthync** [comment]
Okay i will changes it back to be partial, it's changes to not partial because I think it might no anyone who would extends it.

**Comment by Callepo** [comment]
XD, i touch everything, my whole game is build solely out of devext and partials and overwrites Xd .. so the more there are the better for me haha
