### ISSUE TITLE
ANDROID build doesn't work

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#749]
(translated from Russian)

Starts normally.
Enter your username and password.
Choosing a character.
When loading the map, it stops by 90%. Does not freeze, but stops. At the same time, there is an active data transfer. If you turn off wi-fi, it throws it onto the character selection screen with an unknown error.

Нормально запускается.
Вводим логин и пароль.
Выбираем персонажа.
При загрузке карты остонавливается на 90%. Не зависает, а останавливается. При этом идет активная передача данных. Если отключить wi-fi то выкидывает на экран выбора персонажа с неизвестной ошибкой.

**Comment by insthync** [comment]
Did you changed networking transport or not?

**Comment by Serivatech** [comment]
Version 1.61c. Everything works in the PC build, the problem is in the android build.

**Comment by Serivatech** [comment]
https://user-images.githubusercontent.com/56482598/104815199-4fccc000-583d-11eb-8938-14cbe7061ab2.mp4

It's the same on a real device.
addon from callero for character creation.

**Comment by insthync** [comment]
This should be fixed in 1.62f, if you still having an issues relates to this you can reopen this.
