### ISSUE TITLE
BaseUISceneGameplay.IsBlockController()  FindObjectOfType showing up in profiler

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#750]
Using
if (FindObjectOfType<UIBlockController>())

in
BaseUISceneGameplay.IsBlockController()

is showing up in the profiler (~3ms).

Could you please see if it is possible to somehow redo this withouth using FindObjectOfType? (eg. register UIBlockController with a global manager and check if registered)

**Comment by insthync** [comment]
I will improve it.

**Comment by insthync** [comment]
Improved in 1.62c

**Comment by insthync** [comment]
Fixed in 1.62e
