### ISSUE TITLE
Instanced Warping issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#751]
When u try to teleport to a instanced map, u get message Service unavailable

![image](https://user-images.githubusercontent.com/7702658/104819059-6c5ffc80-582b-11eb-969f-142effb0db6f.png)

**Comment by Joshua2504** [comment]
Do you have any errors on the console?

**Comment by Callepo** [comment]
![image](https://user-images.githubusercontent.com/7702658/104820878-3f661680-5838-11eb-836d-a823cd3ae5ff.png)

**Comment by insthync** [comment]
I will fix it.
