### ISSUE TITLE
How to check attribute amount with the BaseCharacterEntity class?

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#754]
In the past I was asvised this as below.

Attribute attribute;
            if (GameInstance.Attributes.TryGetValue("Intelligent".GenerateHashId(), out attribute) &&
                character.GetCaches().Attributes[attribute] > 200)
            {
            }

this works perfect with IPlayerCharacterData class but if the variable "character" is BaseCharacterEntity, above is not working.
Can you advise me how to make this work with "BaseCharacterEntity"?

Thanks.

**Comment by moepi2k** [comment]
do you figured out how to get amount? i need same
