### ISSUE TITLE
Try to get amount of specific Attribute

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#755]
this is not a bug just a question.

i make an addon and need to have access to the amount of specific attribute what a player has
like amount of Intelligence, Strength and so on.
i need to access to it from any script, i have tried several things but i dont get it.

something like:
Attribute attribute; 
if (GameInstance.Attributes.TryGetValue("Strength".GenerateHashId(), out attribute))
{
                character.Attributes[attribute.DataId].amount;
}

maybe you can give me a hint :)

**Comment by insthync** [comment]
Did you try: 
```
character.GetCaches().GetAttribute("Str");
```

**Comment by moepi2k** [comment]
great that works.

thank you very much my friend :)
