### ISSUE TITLE
[BUG]AreaDamageEntity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#757]
there is a bug with AreaDamageEntity. i just copy paste the PoisonAreaDamageEntity to make something like firewall.
i set area duration to 60 secons to have enouth time (tested in mmo)

when i cast it and log out and log back in. there are two issues

issue 1) the prefab will not instantiate, i cant find any way to instantiate the effect. this is need when we a spell has long duration and a player login are teleport from other maps

issue 2) the firewall do damage to the caster after relog.

regarding the damage. i also recommend a bool to set if area damage do dmg to player self anyway. so its optional.

i made a video where you can see the issue
https://gyazo.com/c58ff323992b21d45b1074bd8cb13e0b

best regards

**Comment by insthync** [comment]
I will fix it.
