### ISSUE TITLE
UI on Android not working properly

### ISSUE THREAD

**Issue by Pymann** [suriyun-production/mmorpg-kit-docs#758]
Its for Android 10, built with Unit 2019.4.17f1. I noticed that the UI is not working properly.
When I click on Items, it does not open a second time, unless I open the hotkey choice and close it.
Same for other menu-buttons.

**Comment by insthync** [comment]
I don't understand how it is, can you capture video screenshot

**Comment by insthync** [comment]
I will close this because you don't tell me what is not working.
