### ISSUE TITLE
Android - Connecting time out

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#759]
Single player game.
The bug is still on smartphones.
1. The game is running and we are playing it.
2. The phone screen goes blank if we are afk
3. We turn on the screen and get an error
4. If you click OK, the error window disappears, but the character also disappears. You need to relog.
![zoP_3dCbT5w](https://user-images.githubusercontent.com/47291794/105669566-9a5ed400-5ef0-11eb-9b87-69de8e54c239.jpg)
![B_2plBVunKI](https://user-images.githubusercontent.com/47291794/105669571-9af76a80-5ef0-11eb-922a-021319b2c38d.jpg)

**Comment by insthync** [comment]
Try 1.62 or 1.62b, it should be fixed
