### ISSUE TITLE
1.48 Weight BUG

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#76]
Old bug.
1. For example, we have 10/10 potions, each potion weighs 1.
2. As a result, the total weight of potions should be 10.
3. But, in the inventory we have 1 weight per stack, that is, 10 potions in the inventory take 1 weight. In the storage, the weight works correctly and 10 potions take 10 weights there.

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/65970964-23d2d300-e470-11e9-815d-cded055c73be.png)
![image](https://user-images.githubusercontent.com/47291794/65970989-2e8d6800-e470-11e9-8493-0cc2e4592674.png)

**Comment by insthync** [comment]
Oh, I will fix it

**Comment by insthync** [comment]
Fixed, find `GetTotalItemWeight(this IList<CharacterItem> itemList)` in `CharacterDataExtension.cs` then multiply weight with amount

FROM
```
            result += item.GetItem().weight;
```
TO
```
            result += item.GetItem().weight * item.amount;
```

**Comment by insthync** [comment]
1.49b is out now, try it :P
