### ISSUE TITLE
[SUGGESTION]Random Values on Items

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#760]
It would be cool if values can be random like:

on e.g Armors -> Resistance, Attributes, Increase Damage and so on.

so you can make one armor piece with random values. and when items will generate on loot drop or craft it will have the random values.

this will make the loot and crafting more interesting

**Comment by insthync** [comment]
Yeah, this can be added, I will do it later.

**Comment by moepi2k** [comment]
amazing, thank you

**Comment by dglee2592** [comment]
I really want this. When do you expect this can be added?
