### ISSUE TITLE
(BUG) Multiple UMA issues

### ISSUE THREAD

**Issue by klarkitgames** [suriyun-production/mmorpg-kit-docs#761]
with a clean project using Unity 2020.1.11f1 and newest kit with newest UMA Add-on I get the following errors. 

There are multiple errors of this type pertaining to character selecting and deleting all in same script.
Assets\UMAExtension\Scripts\MMO\UI\UIMmoCharacterListUMA.cs(13,59): error CS0407: 'void UIMmoCharacterListUMA.OnRequestedCharacters(ResponseHandlerData, AckResponseCode, INetSerializable)' has the wrong return type

There are multiple errors of this type pertaining to hiding objects and FPS renders all in same script.
Assets\UMAExtension\Scripts\CharacterModelUMA.cs(371,19): error CS1540: Cannot access protected member 'GameEntityModel.effectContainers' via a qualifier of type 'AnimatorCharacterModelUMA'; the qualifier must be of type 'CharacterModelUMA' (or derived from it)

**Comment by insthync** [comment]
Please wait for next package update, I've changes a lot of codes structure and it's affecting UMA extensions, I have to update UMA extensions too.

**Comment by insthync** [comment]
New release for `UMAExtension`, But it's required CORE version `1.62`.
