### ISSUE TITLE
[BUG]Skills -> Passive

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#762]
When switch skills to Passive and set for example Buff Distance to 10 and Recover HP to 10, nothing happen.

i think something is also missing there. The enum for "Buff to nearby Allies",  "Buff to User",  "Buff to nearby Characters" and so on is missing. Also the Field for tick rate. when use passives like Aura in this case. so you can set that all 5 seconds it tick for 10 hp

**Comment by insthync** [comment]
It actually has no aura skills yet, So when set skills to passive it just increase character's stats.

**Comment by moepi2k** [comment]
ah i thought passives could be used as aura ;/
