### ISSUE TITLE
Package issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#764]
1.62B is corrupt or bad upload.
![image](https://user-images.githubusercontent.com/7702658/106067476-04e55f00-60ff-11eb-8866-9115099e86e4.png)

tried extracting with 7zip also.. 7zip fails to extract

**Comment by insthync** [comment]
Reuploaded, and also tested.

**Comment by Callepo** [comment]
Cheers, 
Was there any changes to the previous issue that i can test out ?
im planning on doing a stress test on 1.62B again.
but if there nothing new i wont bother
