### ISSUE TITLE
1.62

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#765]
Idk if this is fixed in 1.62B ( Cant test it cuase file corrupt)

But in 1.62 harvestables are flickering on and off 
https://imgur.com/99eg8Y5

and abnormal amount of debug logs, u cant see actual logs..
![image](https://user-images.githubusercontent.com/7702658/106070743-57297e80-6105-11eb-94a5-20da354e7867.png)
![image](https://user-images.githubusercontent.com/7702658/106070758-5db7f600-6105-11eb-9ceb-4807e707e31e.png)

**Comment by insthync** [comment]
Which visible checker component are you using? `LiteNetLibVisibleChecker` or `GridVisibleChecker`

**Comment by Callepo** [comment]
Ah ! my prefab had both of them on for some reason.. 
LiteNetLibVisibleChecker And GridVisibleChecker

removed litenet and it works fine now 
Cheers

**Comment by Callepo** [comment]
@insthync https://imgur.com/EvfQ5CE

noticed this yesterday in 1.62 and now in 1.62B too 
when u kill an enemy and it dies , IF he respawns next to u .. it will be invisible. u have to leave and come back so that the visibility gets updated.

**Comment by insthync** [comment]
Fixed in 1.62c
