### ISSUE TITLE
Destroy Delay in Missiles

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#77]
Can you return the "Destroy Delay" component to missiles. He removed in version 1.48c

**Comment by insthync** [comment]
You means the `Lite Net Lib Identity` component ?

**Comment by insthync** [comment]
Okay, I will bring it back :p

**Comment by insthync** [comment]
Done, It will be included in next update

**Comment by insthync** [comment]
1.49b is out now, try it :P
