### ISSUE TITLE
Handlers

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#770]
Can the Handlers + Message Handlers be Partials?
way too much hassle when they not

**Comment by insthync** [comment]
Okay, I will make all interfaces and implemented classes be partially

**Comment by Callepo** [comment]
@insthync Weaponset Switching is bugged too
keybind only does +1 and doesnt reset.

so if ur on weapon set 1 and press it u go to 2. 
but if ur on 2 it never goes back to 1.. 
u have to do it manually from ui

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by insthync** [comment]
Do follow your request and fix the reported issues in 1.62d

**Comment by Callepo** [comment]
cheers
