### ISSUE TITLE
Important Animations Fields Missing (Shooter) & jumping and falling problem !

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#772]
For Shooter , there are very important animations fields missing like ( die and attack when you crouch and prone) ... about jumping and falling , you made jump contact with fall .. it must be each one alone , meaning not contacting to each other.. for example ( right now when i set full animation jump it lands well on ground and after 1 sec fall anim work after it while im on ground ) so it must be jump works alone and not connected with fall anim ... fall anim should work only while we fall from high place... i hope you understand me and thanks for your hard work.. believe me its very important

**Comment by insthync** [comment]
Too much and may very specific for your project only, I recommend creating a new character model class to handle it, Do you know how to work with unity's animator controller? If yes, then you may create a new animator controller that contains all states for your character then send it to me then I will be able to help you to create a new character model easier.

**Comment by RunOrDi3** [comment]
ok i will try
