### ISSUE TITLE
VehicleEntity can receives damage

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#773]
Hi ! 

In patch 1.60, section "Improvement" : 
- VehicleEntity can receives damage, have to set canBeAttacked to TRUE then set its stats.

But i don't see anything like that in the last version actually.

**Comment by insthync** [comment]
It's in vehicle entity component 
![Screenshot_190](https://user-images.githubusercontent.com/2697550/106432465-57c56a80-64a1-11eb-8597-3279bf08f915.png)

**Comment by Gui205** [comment]
My bad it was baddly updated. It's work fine
