### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by khongtuong** [suriyun-production/mmorpg-kit-docs#774]
can't close door from inside, some time can't interact from outside either

https://user-images.githubusercontent.com/6816616/106418559-39537500-6489-11eb-8989-0d1c54c89a6e.MP4

**Comment by insthync** [comment]
It's currently hasn't supported 2 ways door yet, I will improve it later.

**Comment by khongtuong** [comment]
and one more thing about building: after you or monster destroy building, this error show up

MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Transform.get_position () (at <17ad9609ae064f2c9315931ff97adcf1>:0)
MultiplayerARPG.BuildingEntity.get_Position () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/BuildingSystems/BuildingEntity.cs:110)
MultiplayerARPG.DefaultGameSaveSystem.SaveWorld (MultiplayerARPG.IPlayerCharacterData hostPlayerCharacterData, System.Collections.Generic.IEnumerable`1[T] buildings) (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/SaveSystem/DefaultGameSaveSystem.cs:89)
MultiplayerARPG.LanRpgNetworkManager.LateUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:142)

**Comment by insthync** [comment]
Destroyed builing bug fixed in  1.62f, I will do door improvement later.
