### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#775]
hi ! 

Since i make the update ( i didn't update for a while ). I got really bad performance ( only on my project not on a blank one ). 
I propably got something wrong, but i really don't know why ... 

![PerformanceProblem](https://user-images.githubusercontent.com/11931221/106521543-ab09de00-64de-11eb-8fc1-6cf455bf700a.png)

Maybe someone know why, it's only when i got mount, or monster. 

Edit : That's seem to not impact performance when it's build, only in editor

**Comment by insthync** [comment]
Logging string while updating can be the cause of problems

**Comment by Gui205** [comment]
> Logging string while updating can be the cause of problems

Thanks, how can i avoid that ?

**Comment by insthync** [comment]
You does not add logging scripts?, Please expand this, I don't know where it comes from
![Screenshot_191](https://user-images.githubusercontent.com/2697550/106534782-6eaea000-6527-11eb-8324-d33d1cf7bb8e.png)

**Comment by Gui205** [comment]
> You does not add logging scripts?, Please expand this, I don't know where it comes from
> ![Screenshot_191](https://user-images.githubusercontent.com/2697550/106534782-6eaea000-6527-11eb-8324-d33d1cf7bb8e.png)

Nop it's fresh update all is vanilla. 

https://gyazo.com/e46357c7ccae1365cbd274b0c4e10706

**Comment by insthync** [comment]
Just noticed the warning log message, Is it come from character model ?

**Comment by Gui205** [comment]
> Just noticed the warning log message, Is it come from character model ?

Yes but not it's on the character selection scene 
![bug101](https://user-images.githubusercontent.com/11931221/106540226-d05b1400-64ff-11eb-8f5a-2ce72d79f6ba.png)

**Comment by insthync** [comment]
Are you using custom animator controller ?

**Comment by Callepo** [comment]
i have similar type of issue too..
Default kit looks fine..
but in my game its glitchy.
https://imgur.com/OCXOt7O

**Comment by Gui205** [comment]
> Are you using custom animator controller ?, What's it saying is: it can't find states which has clip with mentioned hash ID.

Yes i use custom animator, but it's strange because all my animation work fine, and my mount&monster are correctly animate, it's look like he look at the defaut animation and it's empty so give me an alerte with logstring, but after he continue and look at my custom animation and play it normaly

**Comment by insthync** [comment]
> i have similar type of issue too..
> Default kit looks fine..
> but in my game its glitchy.
> https://imgur.com/OCXOt7O
> 
> @insthync Checked every scripts on default male player model on my prefab.. all same and settings are same.
> checked all monsters scripts..
> checked all objects in the Init_mmo scene and compared it to my scene.. all of it was change to be the same.. but i still have this
> 
> Any idea's?

Yours is online environment right ?

**Comment by Gui205** [comment]
UPDATE : I fix the hash error with recreate a full news controller animtor ( based on your, with your defaut animation), and fill the animation field on Animator Character Model component but when i play my character play no animation and stay in T pose

**Comment by Callepo** [comment]
> > i have similar type of issue too..
> > Default kit looks fine..
> > but in my game its glitchy.
> > https://imgur.com/OCXOt7O
> > @insthync Checked every scripts on default male player model on my prefab.. all same and settings are same.
> > checked all monsters scripts..
> > checked all objects in the Init_mmo scene and compared it to my scene.. all of it was change to be the same.. but i still have this
> > Any idea's?
> 
> Yours is online testing, right ?

Yes, Singleplayer is fine.
Default kit mmo server is fine
just my game in mmo does it..
i checked every script on the models+ Init_mmo scene thinking i have an option wrong.. but after making sure all same..
i still have it

**Comment by Gui205** [comment]
> > > i have similar type of issue too..
> > > Default kit looks fine..
> > > but in my game its glitchy.
> > > https://imgur.com/OCXOt7O
> > > @insthync Checked every scripts on default male player model on my prefab.. all same and settings are same.
> > > checked all monsters scripts..
> > > checked all objects in the Init_mmo scene and compared it to my scene.. all of it was change to be the same.. but i still have this
> > > Any idea's?
> > 
> > 
> > Yours is online testing, right ?
> 
> Yes, Singleplayer is fine.
> Default kit mmo server is fine
> just my game in mmo does it..
> i checked every script on the models+ Init_mmo scene thinking i have an option wrong.. but after making sure all same..
> i still have it

Check if your animator controller is the same as the defaut kit

**Comment by insthync** [comment]
> > > i have similar type of issue too..
> > > Default kit looks fine..
> > > but in my game its glitchy.
> > > https://imgur.com/OCXOt7O
> > > @insthync Checked every scripts on default male player model on my prefab.. all same and settings are same.
> > > checked all monsters scripts..
> > > checked all objects in the Init_mmo scene and compared it to my scene.. all of it was change to be the same.. but i still have this
> > > Any idea's?
> > 
> > 
> > Yours is online testing, right ?
> 
> Yes, Singleplayer is fine.
> Default kit mmo server is fine
> just my game in mmo does it..
> i checked every script on the models+ Init_mmo scene thinking i have an option wrong.. but after making sure all same..
> i still have it

Yeah, the problems occurring from LiteNetLibTransform, I've trying to change interpolation codes, older version was lerping by `SendRate` now it is lerping by RTT, if RTT is high it will jitter like that, I am going to improve it. If you interests where the codes is you can find `Interpolate` function in `LiteNetLibTransform`

**Comment by Callepo** [comment]
cool, ty
but why when i test the normal kit it doesnt do it ?
only in my game? 
do i have something wrong in my settings?

**Comment by insthync** [comment]
> cool, ty
> but why when i test the normal kit it doesnt do it ?
> only in my game?
> do i have something wrong in my settings?

Testing offline or online ?

**Comment by Callepo** [comment]
Online

**Comment by insthync** [comment]
@Callepo  Please try this 
[WIPLiteNetLibTransformImprovement.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5916482/WIPLiteNetLibTransformImprovement.zip)

**Comment by Callepo** [comment]
Works ty

**Comment by Callepo** [comment]
@insthync Something else happening now tho
![image](https://user-images.githubusercontent.com/7702658/106747228-e8c44f00-6623-11eb-81be-601df8e40890.png)

When playing my screen goes black and server spams this error

**Comment by insthync** [comment]
Yeah, I got it too, maybe comes from extrapolation codes.

**Comment by insthync** [comment]
Try this
[WIPLiteNetLibTransformImprovement2.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5918989/WIPLiteNetLibTransformImprovement2.zip)

**Comment by Callepo** [comment]
thats seems to be working good.
But my fps seems to be hit by something..
its low , really low..
![image](https://user-images.githubusercontent.com/7702658/106783244-5e8fe100-664b-11eb-97aa-9ba5f3f0655a.png)

this my fps now.

This was before

![image](https://user-images.githubusercontent.com/7702658/106783418-972fba80-664b-11eb-835c-a7e7ecd4a92e.png)


it never use to fall under 60

**Comment by Callepo** [comment]
in unity editor thats suppoed to be Worst.,
it has more fps lol
![image](https://user-images.githubusercontent.com/7702658/106783752-eaa20880-664b-11eb-9af8-474fb6d824bb.png)

My own fps counter and the unity editor stats show 50+ 
![image](https://user-images.githubusercontent.com/7702658/106783803-fa215180-664b-11eb-9778-5d78510b835a.png)

but in stand alone client its 30 idk why

**Comment by insthync** [comment]
Maybe because of this setting (in GameInstance)
![Screenshot_196](https://user-images.githubusercontent.com/2697550/106790170-c3682d00-6685-11eb-9c6f-3225cec5ebb9.png)

**Comment by insthync** [comment]
@Gui205 Clip name which set in animator controller states must be the same as packaged default clips name
![Screenshot_197](https://user-images.githubusercontent.com/2697550/106790879-c44d8e80-6686-11eb-9674-e5b85468c994.png)

Because I using https://docs.unity3d.com/Manual/AnimatorOverrideController.html which will override animation clips at runtime by **CLIP NAME**, not state name. I actually think, if it's overriding by state name it would be more make sense but I cannot changes what Unity did.

The best way to create a character model that suits your project is to create a new character model class that inherits from `BaseCharacterModel` :P.

**Comment by Callepo** [comment]
@insthync 
![image](https://user-images.githubusercontent.com/7702658/106794324-f942ec80-6658-11eb-9ecc-7121d5ce1b6f.png)
these are my settings atm

**Comment by Callepo** [comment]
LOL.. i reopened client now.. and its fine
![image](https://user-images.githubusercontent.com/7702658/106794571-5474df00-6659-11eb-8c72-9d1049b3f2c7.png)

**Comment by Callepo** [comment]
Whats the benefit of this new controller ? "CharacterControllerEntityMovement" 
would it make stuff better? or is it same as what we have now ? 
basically would it improve the controller? @insthync

**Comment by Callepo** [comment]
there doesnt seem to be an issue anymore,
i just noticed a few things, 
1)Some times.. a skill animation will only play on the main client on not on server for everyone else.. but the dmg + skill efx still appear.. other people sees the one attacking performing walk /run animation.

2) Not secure feels much smoother than serv autho gameplay wise using shooter controller. it feels a bit delayed on serv auth.

Everything else seems to be working fine tho.

**Comment by Gui205** [comment]
> @Gui205 Clip name which set in animator controller states must be the same as packaged default clips name
> ![Screenshot_197](https://user-images.githubusercontent.com/2697550/106790879-c44d8e80-6686-11eb-9674-e5b85468c994.png)
> 
> Because I using https://docs.unity3d.com/Manual/AnimatorOverrideController.html which will override animation clips at runtime by **CLIP NAME**, not state name. I actually think, if it's overriding by state name it would be more make sense but I cannot changes what Unity did.
> 
> The best way to create a character model that suits your project is to create a new character model class that inherits from `BaseCharacterModel` :P.

That's what i did, i have no longer issue on that point. BUT i still have really bad performance with another news issue, each time i put random model no matter what's the model. 

![BUGPERF](https://user-images.githubusercontent.com/11931221/106816536-d115b680-6675-11eb-8f2c-f4207c76e6b8.png)

When i got only the terrain with the foliage ( I use nature Renderer ) i got no problem, but since i populated with my tree i got that ShooterPlayerCharactercontroller.Update take all the ressources. 
I got strictly no error, or no warning, i can put tree, or rock, or all i want the issue is the same. Only if i put model like AI, Mount, or Harvestable with your script.

**Comment by Callepo** [comment]
@insthync  
![image](https://user-images.githubusercontent.com/7702658/106821517-9748ae00-667d-11eb-8291-49432c2e3838.png)
on spawn .. Gravity is not applied.. ,Seen someone Mention it with Dropped Items too but i dont have that one. not sure

**Comment by Gui205** [comment]
@insthync  My problem come from from that :
`   if (FindObjectOfType<UIBlockController>())
    return true;` 
    
    Line 139 of BaseUISceneGameplay, it's called in ShooterPlayerCharacterController line 479, if i understand, he check at each frame if any UI block the Controller. 
    
    But if you have to many gameobject ( that's my case ) that make an CPU bottleneck because he looks at each frame all my gameobject and i have more than 100K on my scene so ... But that's work ok on small scene that's why on my test scene it's work fine. 
    
    Why you didn't continue to use singleton like before ?

**Comment by insthync** [comment]
> @insthync My problem come from from that :
> ` if (FindObjectOfType<UIBlockController>()) return true;`
> 
> `Line 139 BaseUISceneGameplay.cs`, it's called in `line 479 ShooterPlayerCharacterController.cs`, if i understand, he check at each frame if any UI block the Controller.
> 
> But if you have to many gameobject ( that's my case ) that make an CPU bottleneck because he looks at each frame all my gameobject and i have more than 100K on my scene so ... But that's work ok on small scene that's why on my test scene it's work fine.
> 
> Why you didn't continue to use singleton like before ?

Ahh, I see, this was reported, okay I will improve it now.

**Comment by insthync** [comment]
> @insthync
> ![image](https://user-images.githubusercontent.com/7702658/106821517-9748ae00-667d-11eb-8291-49432c2e3838.png)
> on spawn .. Gravity is not applied.
> I need to move to fall down.
> Seen someone Mention it with Dropped Items too but i dont have that one. not sure
> And this
> 
>  2021-02-04.00-17-16.mp4

In the video, did you try to turn on `Extrapolate` in Alpaca -> LiteNetLibTransform ?

**Comment by Callepo** [comment]
https://user-images.githubusercontent.com/7702658/106970987-46ed5100-674e-11eb-8f7b-17e0f1952cfa.mp4

Alpaca with extrapolate on or off is bad..
alpaca is not secured movement.

Wolf is fine , Wolf is Server authorative

**Comment by Callepo** [comment]
i managed to get player movements Good.
![image](https://user-images.githubusercontent.com/7702658/106972741-bdd81900-6751-11eb-974a-21d00d5302f7.png)

https://user-images.githubusercontent.com/7702658/106972683-9c772d00-6751-11eb-82a1-668b15f42616.mp4

Wolf good too, idk bout alpaca
https://user-images.githubusercontent.com/7702658/106972699-a567fe80-6751-11eb-90e7-1262f81ed0b3.mp4

**Comment by Callepo** [comment]
@insthync Locally it feels nice than in server, which is obv. but, u shouldnt be able to feel it

**Comment by insthync** [comment]
@Callepo Try this: 
[WIPLiteNetLibTransformImprovement3.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5933155/WIPLiteNetLibTransformImprovement3.zip)

**Comment by insthync** [comment]
@Callepo 
[WIPLiteNetLibTransformImprovement4.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5933230/WIPLiteNetLibTransformImprovement4.zip)

Try this, I am going to improve owner client syncing by passing received transform at server to other clients, not sending server's interpolating position.

**Comment by Callepo** [comment]
will do now

**Comment by Callepo** [comment]
@insthync u still spawn floating in air.. gravity is never applied till after u start walking.
was this set in place for stuff like Sectr? which loads the chunk after character is spawned to not let them fall out ?

**Comment by Callepo** [comment]
@insthync yea ! CharacterControllerEntityMovement! is so much better than old style, jumping movement etc are nice.. 
only when sprinting its shakes a bit, like a bit of lag or jittery movement... but everything else is so responsive!

**Comment by Callepo** [comment]
@insthync nah, still not smooth, 1.61B was smoother when walking, now its something start to jitter/bad movement with just 1 player.

its not a load issue, its just the movement script not making it move smoothly

**Comment by Callepo** [comment]
@insthync Testing The Default kit seems smooth, i believe the problem sits in my own game.
so nvm what i said above.

I will do a Stress Test on 1.62E this week
