### ISSUE TITLE
Text mesh Pro wraper not working in ios build

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#776]
Text mesh pro wraper is not working in ios build (i use USE_TEXT_MESH_PRO define), it works on a windows build.

**Comment by insthync** [comment]
I'll check it :)

**Comment by insthync** [comment]
When you switch to iOS, did you define USE_TEXT_MESH_PRO again?

**Comment by Koodetat** [comment]
yes, in the editor it works but not when I build the project.

**Comment by insthync** [comment]
It can't be built to XCode project or it has error while running?

**Comment by Koodetat** [comment]
i'm using Unity Cloud Build, it works, but all text mesh pro wrapper dont' works

**Comment by Koodetat** [comment]
no error

**Comment by insthync** [comment]
In 1.71b it has no `USE_TEXT_MESH_PRO` requirement
