### ISSUE TITLE
Character doesn't move well when i attack with sniper

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#777]
i have added rifle weapon and sniper , when i attack with rifle in back , left and right sides , character moves well to attack but when i do it with sniper character doesn't move well ( https://youtu.be/1cCL7JFi2tI ) check the video , From where i can fix this ? i have checked lots of things but no success ( i have made it the same as the default sniper in demo )

**Comment by insthync** [comment]
Try set `turnSpeed` to `0`
![Screenshot_192](https://user-images.githubusercontent.com/2697550/106610897-e3babd80-6599-11eb-9cee-c408cab8b76a.png)

**Comment by RunOrDi3** [comment]
thanks , it works well now when i set to 0 :)
