### ISSUE TITLE
Character Doesn't move when i attack while moving ( shooter controller ) <another problem>

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#778]
i did like you told me before and it fixed only while im not moving .. now when i use single fire , character doesn't move ! 
![Untitled](https://user-images.githubusercontent.com/64667641/106680790-df0cfe00-65c7-11eb-8fce-3810f0490de5.jpg)
thats my settings .. check the video.. i know it works well in demo but i swear god i did the same settings :(
https://youtu.be/Vmsc1SxDV48

**Comment by insthync** [comment]
Check your character model attack trigger duration, it may too short so after it played and triggered it is assuming playing action animation state is FALSE and turn character immediately, or wait me to add option to add some delay before turn character after playing action animation state is FALSE 
![Screenshot_193](https://user-images.githubusercontent.com/2697550/106736868-92b5d280-6648-11eb-8062-6f020eab239f.png)

**Comment by RunOrDi3** [comment]
thank you so much <3 , it works well now :)

**Comment by insthync** [comment]
It's just a temporary solution, for a better solution, wait for next update.

**Comment by RunOrDi3** [comment]
ok , i will wait it for sure :) , also im waiting grenade weapons too
