### ISSUE TITLE
MySQL Performance Issue

### ISSUE THREAD

**Issue by Reinhartdelille** [suriyun-production/mmorpg-kit-docs#779]
Hi, during multiple events where we hosted > 100 players, we ran into some database deadlocks.

Analysis of our MySQL server showed, that following statements resulted in full table scans and almost took all database time

DELETE   FROM `characteritem` WHERE `characterId` = ?,
DELETE   FROM `characterskill` WHERE `characterId` = ?
DELETE   FROM `characterattribute` WHERE `characterId` = ?,
DELETE   FROM `characterhotkey` WHERE `characterId` = ?,
DELETE   FROM `characterbuff` WHERE `characterId` = ?
DELETE   FROM `characterquest` WHERE `characterId` = ?

In the default MySQL implementation, there is no Index on CharacterID in these tables, and that results in heavy impacting the database.

on all tables above we have added an extra index

![image](https://user-images.githubusercontent.com/19047081/106922653-8e072200-670d-11eb-9fe6-4cf5425074c2.png)

If we find any more SQL issues, we will sure let you know in the future ! :)

Reinhart

**Comment by insthync** [comment]
Oh, Thank you, I will add indexes to tables

**Comment by Reinhartdelille** [comment]
Tnx, I will keep you informed as we have more and more data coming in. 

PS : can you also take a look at my discord PM regarding licenses?

**Comment by Callepo** [comment]
@insthync 
![image](https://user-images.githubusercontent.com/7702658/107026011-716cf780-67aa-11eb-924a-677c016b44c7.png)
mysql file in wrong folder , just a FYI
