### ISSUE TITLE
1.49 Bug - Unequiping weapon from secondary itemset unequips primary one

### ISSUE THREAD

**Issue by astromediaonly** [suriyun-production/mmorpg-kit-docs#78]
When i drag weapon from secondary itemset back to inventory primary one gets unequiped instead. Somebody else on discord confirmed this and sayed it was not doing before if i remember correctly, so its probably this version issue.

**Comment by insthync** [comment]
Fixed, it will be include in next update

**Comment by Callepo** [comment]
@insthync is it possible u share the patch fix here just the codes ? ive set 1.49 as a base and implimented most of my design for my game in it already and wouldnt want to redo it just for the unequip section and ps. Quest is still bugged in mmo same reason as last time with the code that was supposed to make the packet size smaller u said to remove for now( in characterQuest)
![quest](https://user-images.githubusercontent.com/7702658/66087161-d3926880-e576-11e9-99ea-f0a56bc87f95.JPG)

**Comment by insthync** [comment]
No it from another place, and I just fixed it

**Comment by insthync** [comment]
I set `CharacterItem` → `equipSlotIndex` before setup the UI data in `UIEquipItems` → `SetEquipWeapon()`

**Comment by insthync** [comment]
1.49b is out now, try it :P

**Comment by astromediaonly** [comment]
Thx, i will eventually but i would prefer for minor versions just "diff" packages like you did in past sometimes (only with changed files) ... doing update of whole project is kinda problematic and messy - especially for me because im running HDRP and so and i need some settings differently and your package is reverting them every time if im not cautious enough to pick which setup files should not be updated and so :)

**Comment by insthync** [comment]
I think with Unity package importer, you can choose files that you want to import and it also shows files that have changed and new files, I think you can choose only script files for bug fixes updates

**Comment by Callepo** [comment]
yea im gonna try do that .. but i changed a few scripts myself too so it will show more changes than normal, i can ry with github too thank you

**Comment by astromediaonly** [comment]
![image](https://user-images.githubusercontent.com/14101093/66120662-ab892080-e5db-11e9-8c44-32f3fb2fead4.png)
just to showcase how usefull that package importer is - this is what it thinks was changed from 1.49 to 1.49b which does not looks right (its like half of files) if you are not even more hyperactive then i thought (lol) :D
but yeah, i will sort it out somehow :)

**Comment by Callepo** [comment]
lol was this from a clean 1.49 kit ?XD

**Comment by Callepo** [comment]
github it is then .. atleast i can add ignore files to it

**Comment by astromediaonly** [comment]
one in my project, but there should not be that much files different ... especially when i was doing update to 1.49 like two days back ... i changed my self like two files, else should be same ... who knows how its figuring out whats new/changed :/

**Comment by insthync** [comment]
If you ae not made changes on scripts, you can choose just `Core` folder

**Comment by astromediaonly** [comment]
Oh, thanks so much that info is huge help
One side question if i may: do you use Billboard.cs for something? i have to delete it now every time because its not namespaced and it interfeers with mTree asset ... if not it would be nice to remove it from project :)

**Comment by astromediaonly** [comment]
That was wrong thread ;) ... but ok thx for info, that would be great.

This issue seems to be solved, thx again.
