### ISSUE TITLE
UI doesn't work 1.62e

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#781]
Hi ! 

I update to 1.62e today, and now all the UI doesn't work anymore, i can open them, they block the camera right, but when i click on them nothing happen. 

It's maybe an problem on my side because on blank project everything work good, buti dont where the problem is, i import all the script, your UI prefab try with your shooter controller prefab but the problem still persist.

**Comment by insthync** [comment]
You mean you can't click on UI buttons? I not sure how it's going, as I try the shooter demo, I got no problems.

**Comment by Gui205** [comment]
> You mean you can't click on UI buttons? I not sure how it's going, as I try the shooter demo, I got no problems.

Yes exactly. I try on a blank i got no problem too, but i make many change on your asset so since the update it's hard to understand all the change ... That's why i ask you if you have an idea :).

**Comment by insthync** [comment]
You may try select `EventSystem` and see which object is pointed
![Screenshot_198](https://user-images.githubusercontent.com/2697550/107103440-36250400-6850-11eb-9801-61334e546cbb.png)

**Comment by RunOrDi3** [comment]
@Gui205 UI works great, the problem comes from your side .. im using both Shooter and normal one , @insthync  thanks about the new improvements for shooter :) , works great ^_^

**Comment by Gui205** [comment]
> You may try select `EventSystem` and see which object is pointed
> ![Screenshot_198](https://user-images.githubusercontent.com/2697550/107103440-36250400-6850-11eb-9801-61334e546cbb.png)

Thanks for your help i fix it :)
