### ISSUE TITLE
[SUGGESTION] Merge Standalone + Mobile canvas

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#784]
Hi,
do you think it would be possible to merge/combine the standalone and mobile canvas into 1? (Use the standalone canvas as the base, and just add the mobile controls. Then add a script that toggles the root of the mobile controls depending on the platform. Also add a script that would change the position of a window depending on the platform).
This will make it easier since just 1 canvas.

**Comment by insthync** [comment]
If you want to do it, you just create one canvas then set it to both `Ui Scene Gameplay Prefab` and  `Ui Scene Gameplay Mobile Prefab`.

**Comment by rasto61** [comment]
Yes, that is what I am doing now. 
I was just wondering if it was possible to somehow make a change like this in the kit. It would also reduce the need to keep duplicates for some of the UI prefabs.

**Comment by insthync** [comment]
How it reduce the need to keep duplicates for some of the UI prefabs?

**Comment by rasto61** [comment]
Right now there are some prefabs in UI/Gameplay/Standalone and UI/Gameplay/Mobile that could be unified  (UIChat, UIDialogs)

**Comment by insthync** [comment]
I won't do it, It can break other customer projects.
