### ISSUE TITLE
Small bug in documentation

### ISSUE THREAD

**Issue by Reinhartdelille** [suriyun-production/mmorpg-kit-docs#785]
Hi

The documentation for the server config files still states the central port to be 6000, where it should now be 7000

![image](https://user-images.githubusercontent.com/19047081/107144379-220a0100-693b-11eb-98e7-9805aae02075.png)

**Comment by Fr-Coder** [comment]
I agree, it is wrong. Can we contribute with documentation in anyway ?

**Comment by insthync** [comment]
Yes, pull requests are welcome :)
