### ISSUE TITLE
Latest updates don't have migration scripts

### ISSUE THREAD

**Issue by Reinhartdelille** [suriyun-production/mmorpg-kit-docs#786]
Hi

it seems there are no migration scripts since 1.57? I just did a vanilla import of 1.62e

![image](https://user-images.githubusercontent.com/19047081/107144696-2fc08600-693d-11eb-8ad7-db47aba21305.png)

**Comment by insthync** [comment]
Because it will running migration script when start server from version 1.58, you can find how it works in `MySQLDatabase.cs` -> `Migration` function.

**Comment by Reinhartdelille** [comment]
Ow, ok, that's clear then, thank you !
