### ISSUE TITLE
Few problems with nav mesh movement

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#788]
See videos

1 Video: The character makes substeps if we hold down the joystick and approach the wall point-blank, and then release the joystick. 
[1.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5941846/1.zip)
This problem is also present in the fresh project 1.62e 
[1.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5941896/1.zip)
Maybe this is due to the fact that the running animation is interrupted and then continues? 

2 Video: The character keeps walking on his own.
[2.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/5941847/2.zip)

**Comment by insthync** [comment]
You have to understand that when uses movement keys with `NavMeshEntityMovement` it will simulate point click on character's forwarding position. So in 2nd video, simulated point click position is behind the wall so it keeps moving to that position. I will add option to limit paths while use movement keys, so if calculated paths is higher than the value it will not move.

**Comment by insthync** [comment]
The option to set max paths to stop movement added in  1.62f
