### ISSUE TITLE
[Bug]Animation + Player Movement -> Multiplayer

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#789]
i updated to 1.62e and there are some problems with animations now. i made two videos (Left is Server, right is client)

1) animations sometimes not synced to clients
https://gyazo.com/581fd3599c4bce294b7bc19273bd78e4

2) Movement feels jittering since 1.62e. (also only for cleints)
https://gyazo.com/e2e4f1d8d38d955d4358b2c9f1af22f0

**Comment by isaanyoha** [comment]
Hi @insthync! Please can you confirm these issue? Thank you!

**Comment by insthync** [comment]
It may be a problem at client-side that it won't play action animation over previous playing animation so it has to wait for previous animation end to be able to play new action animation, I will find how to fix it.

**Comment by isaanyoha** [comment]
Ok, Thanks.

@insthync What about issue 2?

**Comment by insthync** [comment]
@isaanyoha Not sure is it server-auth movement ?

**Comment by isaanyoha** [comment]
Hi! @moepi2k, please can you help answer this question Suriyun is asking? Thanks!

**Comment by moepi2k** [comment]
1) Animation sync issue is still there in 1.62f

2) Jitter movement is only when you use the new "Smooth Follow" for Camera

Auth Movement was on 

Both tested in MMO

**Comment by isaanyoha** [comment]
Hi @insthync! The author of this opened issue just answered your question

**Comment by moepi2k** [comment]
@isaanyoha you dont need to comment him extra, he will see it anyway. so let him time. he has his priority

**Comment by moepi2k** [comment]
Problem 1 is because i set send interval <0.1, theres already a report regarding this, so i will close this one
