### ISSUE TITLE
Fps aiming issues

### ISSUE THREAD

**Issue by astromediaonly** [suriyun-production/mmorpg-kit-docs#79]
While using sniper riffle scope:
- objects behind player are obstructing view
- player is not rotating in aim direction (probably should so others could see where he is aiming)

PS: And i still think there should be some "iron sight" aim option even for weapons without scope - its otherwise weird to handle in 3rd person fps mode. And other weird thing is probably there are no steps for "having gun holstered" and "having gun in hand but not aiming yet" ... but im not sure how this should work yet and Opsive controller will probably solve it eventually anyway so im not looking much into that yet.

**Comment by insthync** [comment]
`objects behind player are obstructing view` issues is fixed, will be included in next update

**Comment by insthync** [comment]
`player is not rotating in aim direction (probably should so others could see where he is aiming)` issues is fixed, will be included in next update

**Comment by insthync** [comment]
1.49b is out now, try it :P

**Comment by astromediaonly** [comment]
Ok, both issues seems to be solved but when im in scope mode its extreeemly lagy to move in, im not sure why tho.

**Comment by insthync** [comment]
I didn't use it too, next time I will cover it with namespace

**Comment by insthync** [comment]
Oh, I use it with an Character Hp canvases

**Comment by astromediaonly** [comment]
May i ask if you have changed something releated to ``zoomByAspectRatioSettings`` while fixing that?

**Comment by astromediaonly** [comment]
If i change inside ``FollowCamera`` script:
```csharp
        // Update rotation
        if (!dontSmoothLookAt)
            CacheTransform.rotation = Quaternion.Slerp(CacheTransform.rotation, lookAtRotation, lookAtDamping * deltaTime);
        else
            CacheTransform.rotation = lookAtRotation;```
to
```csharp
        // Update rotation
        if (!dontSmoothLookAt)
            CacheTransform.rotation = Quaternion.Slerp(CacheTransform.rotation, lookAtRotation, lookAtDamping * deltaTime);
        else
            CacheTransform.rotation = currentRotation;```
its ok ... do you think you can clarify me why there is so much computed stuff between that? Im trying to find when my solution unexpectedly breaks because i have forgot something :)

**Comment by insthync** [comment]
You don't have to use `zoomByAspectRatio` stuff, I made it for games that fixed zoom distance to make it change zoom distance based on screen aspect ratio, I don't know how your lag is, it's okay to set `CacheTransform.rotation = currentRotation`

**Comment by astromediaonly** [comment]
Ok, thx for info ... i have tryed fresh version and it works even on my Unity version and screen resolution so i suppose something have got messed up during update again :/ ... for now i have that fix and hopefully this problem will go away during future updates i suppose.
