### ISSUE TITLE
Kit Documentation

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#791]
I would like access to be able to update the Kits Documentation, some things are outdated or gone.
and people keep asking daily the same questions over and over again, and its a lil exhausting repeating same thing 50x

**Comment by Callepo** [comment]
@insthync Nvm i found out how i can Fork the repo and just Do Pull Request to you.
i will be updating what i can and do 1 big push

**Comment by Reinhartdelille** [comment]
If you want, i can make some time to review before the pull :)

**Comment by insthync** [comment]
Yes, pull requests are welcome :)
