### ISSUE TITLE
Mobile (Android) Login won't work

### ISSUE THREAD

**Issue by battousaidlt** [suriyun-production/mmorpg-kit-docs#792]
The project is working fine on other platforms, but when i switch to android the login/registration button won't work to retrieve data from the DB and send a error:
 [https://imgur.com/RdToUKH](url)

https://user-images.githubusercontent.com/5970310/107559801-4d028800-6bbb-11eb-956d-3d48c8c27ca5.mp4

**Comment by insthync** [comment]
OH, I will fix it ASAP, thank you for bug reporting :)

**Comment by battousaidlt** [comment]
Thanks! Glad i can help! o/
