### ISSUE TITLE
Scene objects using LiteNetLibItentity are disabled on load

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#795]
Hello!

In my game I use a game object in my scene with several scripts utilizing LiteNetLibIdentity to sync things like time of day, weather, and ocean movements between client and server. Previously this object would stay active in game and would keep things synced, but at some point in one of the recent updates, it stopped working. Now I find that in MMO mode, the object is being automatically disabled. 

This appears to be occurring in the RegisterSceneObjects method in LiteNetLibAsset.cs on line 138. It seems you are disabling all objects when they are registered and then re-enabling them elsewhere? 

In order to ensure that my syncing game object is active and doing its job, how would you suggest that I handle activating it? What is the correct way to do this currently in the kit?

Thanks in advance!

**Comment by insthync** [comment]
It's a bug, I am going to fix it.

**Comment by insthync** [comment]
Fixed in  1.62f
