### ISSUE TITLE
[Bug]Debuff

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#796]
Debuffs not fully works.

i add a skill that should reduce targets stamina, but it doenst work

here the settings
https://gyazo.com/82915eb6ae02298e55582216c48b5433

it also would be better to make a seperate field for attacks like this. because debuffs are temporary and need a duration.

better would be a new field or something to reduce stuff like stam, mana?

another thing. what is the bool for: Increase Damage Amount with buffs?

**Comment by moepi2k** [comment]
p.S right now i saw the tooltips for Duration: "If Duration less than or equals 0, buff stats wont applied only recovery will be applied"

so then new field not required, but still the bug that stam an mana will not reduce on hit

**Comment by insthync** [comment]
Fixed, thank you for bug report.

**Comment by insthync** [comment]
Fixed in  1.62f
