### ISSUE TITLE
Building rotation

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#798]
The rotation work correctly when is not snapped, but when you snap to the build point you can not rotate the thing any more

https://gyazo.com/8f9e50f5a527c4e11f67ef7cec423f37

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed, in next version it will have new configs called `buildRotateSpeed` while `buildRotationSnap` is `false` it will rotate while hold on rotate buttons by `buildRotateSpeed` * `Time.deltaTime`.
If `buildRotationSnap` is `true` it will rotate when pressed on rotate buttons by `buildRotateAngle`, so for example if start Y angle is 0, when press rotate Y rotate will be increased to 45 then 90 and so on.

**Comment by insthync** [comment]
Fixed in  1.62f
