### ISSUE TITLE
Double Crafts - MMO Mode with simple inventory

### ISSUE THREAD

**Issue by Monty001** [suriyun-production/mmorpg-kit-docs#799]
When using a craft skill, in MMO mode with the gameinstance inventory setting as 'simple' (no slot limt, only weight)  the inventory receives two versions of the item. The second isn't actually the item and doesn't behave like an item, it reports as an invalid inventory index when attempting to manipulate it. Its not actually a dupe.

It looks all client side as relogging fixes the inventory. This doesn't appear in non-MMO.

This doesn't seem to happen if you have a slot limit set.

**Comment by insthync** [comment]
Okay I will fix it.

**Comment by insthync** [comment]
Fixed, I might upload the fixed package tonight

**Comment by Monty001** [comment]
Thank you.
