### ISSUE TITLE
Completely custom UI?

### ISSUE THREAD

**Issue by astromediaonly** [suriyun-production/mmorpg-kit-docs#80]
Are there any plans on revisiting how UI is structured/designed? I was looking into creating own gameplay canvas from scratch with only UI parts i need but it does not seems currently posible because you have to provide canvas of type UISceneGameplay which is huge all controlling script. It would be better (atleast for me) to have as base only some "data provider" or so script where you can get info about players stats, inventory and so on + something where you can call server requests like "drop item" or "complete trade" and where you can subscribe to events when server wants to open some UI like prompt or trade ui. And handle all UI custom based only on that data, subscribed events and calling API functions. It should be also easier to maintain and update than this all-in-one solution in theory. Especialy if we can easily create our custom solution. ATM it works great if you want just to reskin it but im kinda scratching my head how to create for example completely different inventory solution with search, item type filters and items having more info/icons over their primary icon, rarity colors and so (this is giving me most hedaches - figuring out how this diferent item/slot prefabs are designed/structured and why) without need to rework it every time there is update. And its just me or its so overly complicated codewise? :)

PS: Sorry for so much text, it just some insight how i feel working with current UI
I understand it would be probably too much work to make it more understandable and accessable at this point but it would be great
PS2: Im kinda hoping overall there will be some time/patch adressing making API and so more coherent and accessible (and more devextension methods, there is never enough of those :D ), i can imagine after so much time in development and so much features added you would have done some things differently now - every big project seems to need some time to stop and clean up/rewrite to make things more clean :)

**Comment by astromediaonly** [comment]
I was talking more about code intelligibility and extendability but UIEelements is also interesting, maybe you can kill two birds with one stone i suppose, thanks for adding that :)

**Comment by insthync** [comment]
I am afraid that I will not do it like as you request, can you explain it with some example?

**Comment by astromediaonly** [comment]
Thanks for commenting. I see, i have kinda hoped i can replace gameplay canvas with my own and do there only UI elements i want. At this moment its too intertwined witch character controller, character camera and zoom ability and maybe something else so  its not as modular as i thought.

I wish it was possible to replace gameplay canvas with blank canvas and do something like this in my custom UI script:
```
Client.Instance.OnPopupMessage.AddListener((string title, string message) => {
        //i will handle here if server or some game logic wants to show message to user
});

Client.Instance.OnNonequipItemsUpdate.AddListener((List<ItemData> data) => {
        //i will handle here update of my inventory ui to reflect item changes
});

Client.Instance.OnTradeRequested.AddListener((Player initiator, ...) => {
        //i will handle here opening trade window
        //and after everything is done i can do something like:
       Client.Instance.SendTradeComplete(tradedItems);
});

Client.Instance.OnHotkey.AddListener((string key) => {
        //i will handle here which window is supposed to show 
       //and i could notify camera to unlock cursor and stop rotation update
       GamePlayCamera.Instance.SetMode(CameraMode.Locked);
});
```
So UI could be completely independent of the rest and i can use some API functions and events to hook whatever i need and how i need it. (I have used singletons in this example so i dont have to look for client or camera script in scene and Unity events so something can trigger those methods and i can subscribe to them but i suppose you figured that out) Maybe this is not the best approach, im still experimenting with it but to give you some idea what i mean. Maybe you can figure out better approach, i just wanted to be able to remove specific ui elements and replace them with my own working differently without need to modify that huge UI script responsible for everything - for ui to be more modular.

Tho im still unsure if it will not be for me better to just create base from scratch using my structure and litenetlib + your wrapper and port over logic from your kit i need ... it will be comfortable to use your KIT because updates and tested stuff but im sometimes having hard time to customize things without too extensive core changes and you are quite hard to catch sometimes :) (nothing wrong about that, i see how bussy you are) ... on the other hand i have tryed to port your map spawn and teleport logic to my base and my curse is i need to understand code before changing it to see why it is the way it is and if there is not some good reason behind it and no way i can find logic responsible for loading map on client when player is warping through portal ... you probably took there some shortcut im not aware of or im too tired :) ... point is lot of stuff will probably not be as easily portable to my code so this is another reason to stick with your base but on the other hand i would have better control over some stuff to be more creative while using it. I could probably wait for ospive integration and then stop updating and do all core changes i need but there is always some neat update to have - you are awesome in this way :) ... Im still undecided and quite conflicted.

My 3 biggest problems requiring me to do too much core changes atm are: 
- i will need to have better control of UI because i like to design it completely on my own and this way it will not be that obsolete or overwritten every update
- i wanted to load npcs, items and so from database and just pair models to them on client using model name/id so i can modify placement and behavior from database like Wow has ... its quite addictive approach :)
- i wanted more complex instancing behavior i described you in other topic (but this will be probably doable after i have got that devext methods)

Sorry if im too picky and demanding customer ... and for so much text again, i know its not easy for you to understand but i cant help my self to try to extensively describe what i want and why every time :) ... Maybe my goals and ideas/visions are just too high. I hope this helped you in some way or atleast clarified my curent position a bit. Im writing it at morning so i hope it make sense :)
