### ISSUE TITLE
Missing Impact effect for melee Damage type

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#800]
Could you add impact effects for melee damage type like raycast damage type ? check the photos .. will be great 
![Untitled](https://user-images.githubusercontent.com/64667641/108205765-2b128380-712e-11eb-801f-6ce11c67fae4.jpg)
![2](https://user-images.githubusercontent.com/64667641/108205767-2bab1a00-712e-11eb-82ac-ae24607b6c0e.jpg)

**Comment by insthync** [comment]
Okay, I will add it.

**Comment by RunOrDi3** [comment]
thanks alot
