### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#802]
Hy, 

i have a quesiton. i try to extend the BaseCharacterEntity_BuffFunction

Methode: 
`ApplyBuff(int dataId, BuffType type, short level, EntityInfo buffApplier)`

now i need to know whats the name (scriptable object name) of the buff is.

i dont wanna change all methodes to add like this:

`ApplyBuff(int dataId, BuffType type, short level, EntityInfo buffApplier, **string name**)`

maybe you you have a better way to get skill name for the buffs?

thank you very much :)

**Comment by insthync** [comment]
Uses type and dataId to find source of buff like this
```
            switch (type)
            {
                case BuffType.SkillBuff:
                case BuffType.SkillDebuff:
                    BaseSkill skill;
                    if (GameInstance.Skills.TryGetValue(dataId, out skill))
                    {
                        // Now you got the skill
                    }
                    break;
                case BuffType.PotionBuff:
                    BaseItem item;
                    if (GameInstance.Items.TryGetValue(dataId, out item) && item.IsPotion())
                    {
                        // Now you got the item
                    }
                    break;
                case BuffType.GuildSkillBuff:
                    GuildSkill guildSkill;
                    if (GameInstance.GuildSkills.TryGetValue(dataId, out guildSkill))
                    {
                        // Now you got the guild skill
                    }
                    break;
            }
```

 You can use `onApplyBuff` action to add functionality without code changes.

**Comment by moepi2k** [comment]
greeeeat that works thank you :)

**Comment by moepi2k** [comment]
ok was a bit to fast to close ^^

i try to make devext to applybuff.

but i got this error
![msg](https://user-images.githubusercontent.com/2422714/108370502-033e2100-71fd-11eb-9171-4dcaedf01f2f.png)


any idea?

**Comment by insthync** [comment]
May `;` after `)` of function declaration

**Comment by moepi2k** [comment]
xD

sorry i really need to sleep, what an embarrassing mistake haha

**Comment by moepi2k** [comment]
One mlre thing 🙈

![Screenshot_20210218-172203~2](https://user-images.githubusercontent.com/2422714/108393825-57083480-7214-11eb-82a3-112a2e480549.png)
This log will never valled when use a buff, i do devex in same way like in my other addons but i never used onApplyBuff before, so i dont know whats wrong and why its never called

**Comment by insthync** [comment]
Did you try uses LiteNetLibManager.Logging.Debug(""); ? the action may be triggered in  async thread

**Comment by insthync** [comment]
Hmm, it's correct, why it not work? :P

**Comment by insthync** [comment]
How about namespace?, did you add cover the partial class codes with `MultiplayerARPG` namespace?

**Comment by moepi2k** [comment]
yes namespace is there,

hier a screenshot ->
https://gyazo.com/0c29b907193d64d01267da72ce211174

**Comment by moepi2k** [comment]
ok it works now, there was maybe some problems in compiler yesterday. today after restarting pc and project it works. 
sorry again :) and thank you very much for your help
