### ISSUE TITLE
Red Errors in new UPDATE V 1.62f

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#803]
![123](https://user-images.githubusercontent.com/64667641/108361401-1cde6900-71fb-11eb-841e-0d11c296a3c3.jpg)

**Comment by insthync** [comment]
You can deletes `UICraftItemSelectionManager`, `UICraftItem` and `UICraftItems`, they renamed to `UIItemCraftSelectionManager`, `UIItemCraft` and `UIItemCrafts`

**Comment by RunOrDi3** [comment]
thanks alot
