### ISSUE TITLE
login/registeration button not working on MMO for Android (1.62e)

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#804]
Hi @insthync! Someone made mention of this issue on our discord and I want to know if it was fixed in the update 1.62f, because I will also go through this same route when using the kit. Thank you!

He said, "The project is working fine on other platforms, but when i switch to android the login/registration button won't work to retrieve data from the DB and send a error:"

https://user-images.githubusercontent.com/4920405/108366892-29fa5880-71f9-11eb-91f8-46d1a99cd51b.mp4

**Comment by insthync** [comment]
Yes, it was reported and fixed in 1.62f
