### ISSUE TITLE
Building Snap rotation error 1.62f

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#805]
When I place a building as a floor, the next floor does not fit correctly, it happens with any building that has "snap build" activated.
video:
https://youtu.be/83eMtpQPTlU

update 1.62f

**Comment by insthync** [comment]
Oh, haha, I will fix it.

**Comment by Blunnyn** [comment]
thnks

**Comment by Gui205** [comment]
For me is still not work at all with custom model : 

https://gyazo.com/fd3cbaf424f6f1b246a677dbdac218c3

I correctly set "Build Rotation Snap" on my player controller 

I also respect the hierarchy for setup my custom model : 

![fondation](https://user-images.githubusercontent.com/11931221/108425681-153eb480-723b-11eb-905f-752160472442.png)

**Comment by insthync** [comment]
@Gui205  Did you updated to 1.62g ?

**Comment by Gui205** [comment]
> @Gui205 Did you updated to 1.62g ?

Yes still same issue : 
https://gyazo.com/79817fe351d709b4ebb7cbff360f9d3b 

Maybe that's come from the collider trigger the my fondation did they have to got a special rotation or something like that ?

**Comment by insthync** [comment]
Oh, I see. Now it will always snap to building area's rotation, it's can't rotate by players when snapping to building area's yet.

**Comment by Gui205** [comment]
> Oh, I see. Now it will always snap to building area's rotation, it's can't rotate by players when snapping to building area's yet.

Oh ok ! My bad i tryed to rotate him when he was snapped

**Comment by insthync** [comment]
Yeah, but I think it should be able to rotate while snapping too, because some building such as chest, workbench should be able to rotate.

**Comment by Gui205** [comment]
> Yeah, but I think it should be able to rotate while snapping too, because some building such as chest, workbench should be able to rotate. So I will improve it later.

I can send you my model & prefab if you want. It's appear actually they are instanced on the snap slot, so they take the slot rotation. 
Chest doesn't.
