### ISSUE TITLE
file contains invalid scripts 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#806]
sorry again :( , i have did like you told me to delete the scripts , now i cant locat them inside my canves prefab .. i changed some stuff but i cannot save it 
![Untitled](https://user-images.githubusercontent.com/64667641/108370978-f245dd80-7205-11eb-8d0a-78b1b405af2b.jpg)

**Comment by insthync** [comment]
You found it ?
