### ISSUE TITLE
prefab contains invalid scripts

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#807]
sorry again , i did like you told me to delete UICraftItemSelectionManager, UICraftItem and UICraftItems , now i have changed some stuff to my canves but i cannot save it .. i cannot locate them inside the canves 
![Untitled](https://user-images.githubusercontent.com/64667641/108375221-70a47e80-720a-11eb-88a8-1d6ebe00c1e3.jpg)

**Comment by insthync** [comment]
- Try find `CraftItemInfo`, `CraftItem`, `UICraftItemDialog` and see that it has unknow behaviour or not, if it is remove it and add `UIItemCraft` component and set its data.

- Try find `BuildingCraftItemsComponents` and see that it has unknow behaviour or not, if it is remove it and add `UIItemCrafts` component and set its data.

**Comment by RunOrDi3** [comment]
![Untitled](https://user-images.githubusercontent.com/64667641/108378870-10afd700-720e-11eb-9615-b06a914ec3bf.jpg)
Why i cannot add anything here like the old one ?

**Comment by insthync** [comment]
The prefab may has missing component too, so find `UICraftItemIcon` in `Project` and fix it.

**Comment by RunOrDi3** [comment]
![2](https://user-images.githubusercontent.com/64667641/108387902-bebf7f00-7216-11eb-94f7-0bfc99705b7b.jpg)
![3](https://user-images.githubusercontent.com/64667641/108387909-c0894280-7216-11eb-8961-ce927308d97b.jpg)
![1](https://user-images.githubusercontent.com/64667641/108387911-c121d900-7216-11eb-9271-2ee49dcb09c2.jpg)
 i have added for UiCraftItemIcon , UIBuildingCraftItemsDialog and UICraftItemDialog .. still have the problem

**Comment by RunOrDi3** [comment]
i have added to UICraftItemDialog , UIBuildingCraftItemsDialog , CraftItemInfo and UICraftItemIcon and still get the problem which i cannot save the canves prefab 
![3](https://user-images.githubusercontent.com/64667641/108434220-f565bb80-724f-11eb-8047-815a0aeb6a6c.jpg)
![4](https://user-images.githubusercontent.com/64667641/108434222-f696e880-724f-11eb-8991-ba26cdff6071.jpg)
![1](https://user-images.githubusercontent.com/64667641/108434224-f72f7f00-724f-11eb-9b56-928024affa0d.jpg)
![2](https://user-images.githubusercontent.com/64667641/108434226-f7c81580-724f-11eb-8fd2-47b985a270c9.jpg)

**Comment by insthync** [comment]
You may try use http://wiki.unity3d.com/index.php/FindMissingScripts to find missing script and where it come from (it will tell you in console log after you pressed find button)
