### ISSUE TITLE
Sqlite / Mysql ext issue

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#808]
Partials for sqlite and mysql give off errors when switching to a mobile build. These errors vanish when switching back to a pc build in the build settings window. Code that works 💯 in mmo in a pc build breaks in mobile. This happens in both 1.62e and 1.62f.

**Comment by insthync** [comment]
An extension codes should cover "Server only" codes by 
```
#if UNITY_STANDALONE && !CLIENT_BUILD
// An extension codes
#endif
```
