### ISSUE TITLE
Interpolation Question (with a video description)

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#809]
The owning player character (right window) moves smoothly (ignore the skipping video) but her move on the other player's side (left window) is looks jumpy, this may make it difficult for another character to aim easily and shoot at her. I want her movement to interpolate smoothly from her previous position to the next. How do I achieve this @insthync, please. Thanks!

https://user-images.githubusercontent.com/4920405/108446353-467cac00-725e-11eb-8fe3-24cbc693f464.mp4

**Comment by insthync** [comment]
Try turn on extrapolate in LiteNetLibTransform. And while you testing multiplayer the game in inactive windows (from your video it is the left one) will always jittering

**Comment by isaanyoha** [comment]
Ok. Thanks for responds!
