### ISSUE TITLE
Mobile camera rotation

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#81]
When using mobile and shootercontroller idk if the normal controllor is same, but when u rotate the camera it keeps rotating the direction u started rotating to non stop untill u tab on the screen with ur fingers again. I want it to only move when dragging and stops as soon as u remove ur fingers instead of needing to tab the screen again. where can i edit the codes to makes this happen ?

**Comment by Callepo** [comment]
https://www.youtube.com/watch?v=6SLung7ZZwk&feature=youtu.be

found out the !isdragging bool is set to false accordingly, but if u was moving while the button was released it will continue in the direction it was going.. so bascially if u dont want it to happen .. u need to rotated camera.. stop and then release.. if u drag and release mid movement it keeps going instead of stopping when released

**Comment by insthync** [comment]
Okay, this is fixed, the problems occurs because the shooter controller was made for PC controls only, so I add codes to move by touch-screen.

**Comment by insthync** [comment]
1.49b is out now, try it :P
