### ISSUE TITLE
No more swimming with navmesh ?

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#810]
Hi since latest version i notice we can't swim anymore if we use navmesh for key movement.
in the navmeshentitymovement it seems that nothing is checking for water anymore.

how could we turn water swimming back on ?

**Comment by insthync** [comment]
`NavMeshEntityMovement` never has swimming. 

Rigidbody, LegacyRigidbody and CharacterController have it, they're able to move by point click like navmesh because it uses navmesh system to find paths.
