### ISSUE TITLE
wrong standing place and non smooth movement

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#811]
i recorded a video to show you .. at the first in video in left scene im standing in front of him and in the right scene im standing in the back .. also movements lagging not moving smoothly( that happen when im opening more than one account just 2x accounts and its happening.. i have tried extrapolate and still have that issues ( https://youtu.be/rumCPpz3-xo )

**Comment by insthync** [comment]
I want to see your LiteNetLibTransform settings

**Comment by RunOrDi3** [comment]
![Untitled](https://user-images.githubusercontent.com/64667641/108526193-816ff580-72d9-11eb-935c-6eaa9f28d991.jpg)
sure , here it is

**Comment by insthync** [comment]
Try change `Owner Client Send Interval` to `0.1`, I think problem occurring because it send message to fast to expect move speed.

**Comment by insthync** [comment]
In next version I will change how to interpolate and extrapolate to use character's move-speed to do it not an expecting move-speed.

**Comment by RunOrDi3** [comment]
ok i will try it and ye will be better

**Comment by RunOrDi3** [comment]
standing place better now but not good .. but movement now is so fast ( https://youtu.be/BOS_F9mnH7k ) check the video .. anyway i will wait next update

**Comment by moepi2k** [comment]
In your second video with setting 0.1 everything is fine. Tje problem is when you reduce send interval <0.1 stufff not sync correctly, i had this issue also thatsometimes animations nlt synced. But my game is really fast paced and 0.1 is too high, i need to reduce it to max 0.05.

Hope this could be fixed

**Comment by RunOrDi3** [comment]
@moepi2k still have Tje . i will have to wait till the next update

**Comment by insthync** [comment]
Close this because entity movement where changes sometime ago.
