### ISSUE TITLE
BUG? Displaying a set in the crafting window

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#812]
I am trying to add a set display on craft items, but I get an error. 
I have this item:
![image](https://user-images.githubusercontent.com/47291794/108608217-9d0cf600-73d6-11eb-9fe4-75c84f85bb22.png)
With this settings:
![image](https://user-images.githubusercontent.com/47291794/108608235-bca41e80-73d6-11eb-87d2-44e238951c91.png)
With sockest works well.
But when I try to add an equipment set with settings like this: 
![image](https://user-images.githubusercontent.com/47291794/108608259-e78e7280-73d6-11eb-99be-f67217ffaaf3.png)
I get an error when I select a crafting item:
![image](https://user-images.githubusercontent.com/47291794/108608273-012fba00-73d7-11eb-8600-3b800177caf3.png)
Am I missing something or is this not provided in the current version or is a bug?

**Comment by DimasjkTV** [comment]
> I am trying to add a set display on craft items, but I get an error.
> I have this item:
> ![image](https://user-images.githubusercontent.com/47291794/108608217-9d0cf600-73d6-11eb-9fe4-75c84f85bb22.png)
This item has set bonuses.
> With this settings:
> ![image](https://user-images.githubusercontent.com/47291794/108608235-bca41e80-73d6-11eb-87d2-44e238951c91.png)
> With sockest works well.
> But when I try to add an equipment set with settings like this:
> ![image](https://user-images.githubusercontent.com/47291794/108608259-e78e7280-73d6-11eb-99be-f67217ffaaf3.png)
> I get an error when I select a crafting item:
> ![image](https://user-images.githubusercontent.com/47291794/108608273-012fba00-73d7-11eb-8600-3b800177caf3.png)
> Am I missing something or is this not provided in the current version or is a bug?

**Comment by insthync** [comment]
I was did these:
- Rename `UICraftItem` to `UIItemCraft`
- Rename `UICraftItems` to `UIItemCrafts`
- Rename `UICraftItemSelectionManager` to `UIItemCraftItemSelectionManager`
So components reference may be missed.

**Comment by DimasjkTV** [comment]
> I was did these:
> 
> * Rename `UICraftItem` to `UIItemCraft`
> * Rename `UICraftItems` to `UIItemCrafts`
> * Rename `UICraftItemSelectionManager` to `UIItemCraftItemSelectionManager`
>   So components reference may be missed.

i use 1.62e. This error was already a very long time ago, I just forgot to say about it. Half a year for sure, since I decided to try it.

**Comment by insthync** [comment]
I want to see full error log message, so I can find where is the source of problem.

**Comment by DimasjkTV** [comment]
> I want to see full error log message, so I can find where is the source of problem.

Where can I see the entire error log? 
In the console, only this is what I showed above.

**Comment by DimasjkTV** [comment]
I will try to test a fresh project in a new version.

**Comment by DimasjkTV** [comment]
In a fresh project, the crafting selection is not fully displayed. You cannot click on an item to create it. 
![image](https://user-images.githubusercontent.com/47291794/108617721-abd0c880-7429-11eb-9cdb-db1dbb3b373d.png)

**Comment by insthync** [comment]
Mine still work correctly

![Screenshot_222](https://user-images.githubusercontent.com/2697550/108618243-0cbec780-744f-11eb-9502-da4daa8b7a5f.png)

Not sure that you are trying to create new dialog or it is just from the demo?

**Comment by DimasjkTV** [comment]
> Mine still work correctly
> 
> ![Screenshot_222](https://user-images.githubusercontent.com/2697550/108618243-0cbec780-744f-11eb-9502-da4daa8b7a5f.png)
> 
> Not sure that you are trying to create new dialog or it is just from the demo?

from demo but i update old 1,61 to the last version. I will try create new last version without updates.

**Comment by DimasjkTV** [comment]
> Mine still work correctly
> 
> ![Screenshot_222](https://user-images.githubusercontent.com/2697550/108618243-0cbec780-744f-11eb-9502-da4daa8b7a5f.png)
> 
> Not sure that you are trying to create new dialog or it is just from the demo?

Yes it towks in fresh project, but Equipment set doesnt displaing.
![image](https://user-images.githubusercontent.com/47291794/108618478-c6a63b80-742f-11eb-8545-6f86e8aaad1c.png)
NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.UICharacterItem.UpdateData () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Item/UICharacterItem.cs:586)
UISelectionEntry`1[T].ForceUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionEntry.cs:64)
UISelectionEntry`1[T].set_Data (T value) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionEntry.cs:16)
MultiplayerARPG.UIItemCraft.UpdateData () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Item/UIItemCraft.cs:84)
UISelectionEntry`1[T].ForceUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionEntry.cs:64)
UISelectionEntry`1[T].set_Data (T value) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionEntry.cs:16)
MultiplayerARPG.UIItemCraft.Setup (MultiplayerARPG.CrafterType crafterType, MultiplayerARPG.BaseGameEntity targetEntity, MultiplayerARPG.ItemCraft data) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Item/UIItemCraft.cs:29)
MultiplayerARPG.NpcDialog.RenderUI (MultiplayerARPG.UINpcDialog uiNpcDialog) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Npc/NpcDialog.cs:213)
MultiplayerARPG.UINpcDialog.UpdateData () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Npc/UINpcDialog.cs:48)
UISelectionEntry`1[T].ForceUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionEntry.cs:64)
UISelectionEntry`1[T].set_Data (T value) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionEntry.cs:16)
MultiplayerARPG.UISceneGameplay.ShowNpcDialog (System.Int32 npcDialogDataId) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Scenes/UISceneGameplay.cs:340)
MultiplayerARPG.BasePlayerCharacterEntity.TargetShowNpcDialog (System.Int32 dataId) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/PlayerCharacterEntity/BasePlayerCharacterEntity_NpcFunctions.cs:61)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
LiteNetLibManager.LiteNetLibFunctionDynamic.HookCallback () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:219)
LiteNetLibManager.LiteNetLibIdentity.ProcessNetFunction (LiteNetLibManager.LiteNetLibFunction netFunction, LiteNetLib.Utils.NetDataReader reader, System.Boolean hookCallback) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibIdentity.cs:316)
LiteNetLibManager.LiteNetLibIdentity.ProcessNetFunction (LiteNetLibManager.LiteNetLibElementInfo info, LiteNetLib.Utils.NetDataReader reader, System.Boolean hookCallback) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibIdentity.cs:307)
LiteNetLibManager.LiteNetLibGameManager.HandleServerCallFunction (LiteNetLibManager.MessageHandlerData messageHandler) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:733)
LiteNetLibManager.TransportHandler.ReadPacket (System.Int64 connectionId, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:79)
LiteNetLibManager.LiteNetLibClient.OnClientReceive (LiteNetLibManager.TransportEventData eventData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:62)
LiteNetLibManager.LiteNetLibClient.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:30)
LiteNetLibManager.LiteNetLibManager.FixedUpdate () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:110)
LiteNetLibManager.LiteNetLibGameManager.FixedUpdate () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:66)
MultiplayerARPG.BaseGameNetworkManager.FixedUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/Networking/BaseGameNetworkManager.cs:84)
MultiplayerARPG.LanRpgNetworkManager.FixedUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/LanGame/Networking/LanRpgNetworkManager.cs:131)

**Comment by DimasjkTV** [comment]
I don't know why my console in my main project is not displaying this information.

**Comment by insthync** [comment]
Great, now I can find where is a source of problem :P

**Comment by insthync** [comment]
Try change codes in `UIDataForCharacter.cs` like this 
![Screenshot_225](https://user-images.githubusercontent.com/2697550/108620061-e6ebef80-745b-11eb-9a86-3fcf0f338d70.png)


```
        private ICharacterData character;
        public ICharacterData Character
        {
            get
            {
                if (character != null)
                    return character;
                return GameInstance.PlayingCharacter;
            }
            protected set
            {
                character = value;
            }
        }
```

**Comment by DimasjkTV** [comment]
> private ICharacterData character;
>         public ICharacterData Character
>         {
>             get
>             {
>                 if (character != null)
>                     return character;
>                 return GameInstance.PlayingCharacter;
>             }
>             protected set
>             {
>                 character = value;
>             }
>         }

![image](https://user-images.githubusercontent.com/47291794/108620657-a5008080-743e-11eb-9d26-dbb54219ea2f.png)

**Comment by insthync** [comment]
Did you replace all class scripts ?, I mean to just replace `Character` property getter setter codes. Like this
![Screenshot_226](https://user-images.githubusercontent.com/2697550/108623829-aac48900-7473-11eb-973e-a622b2757595.png)

**Comment by DimasjkTV** [comment]
> Did you replace all class scripts ?, I mean to just replace `Character` property getter setter codes. Like this
> ![Screenshot_226](https://user-images.githubusercontent.com/2697550/108623829-aac48900-7473-11eb-973e-a622b2757595.png)

I did not do anything. I did just what you told me to replace above.

**Comment by DimasjkTV** [comment]
I thought I needed to be replaced. But it turns out it was necessary to add.

**Comment by DimasjkTV** [comment]
> private ICharacterData character;
>         public ICharacterData Character
>         {
>             get
>             {
>                 if (character != null)
>                     return character;
>                 return GameInstance.PlayingCharacter;
>             }
>             protected set
>             {
>                 character = value;
>             }
>         }

It works! Thank you!

**Comment by DimasjkTV** [comment]
Now the error occurs when we open the skills window.
![image](https://user-images.githubusercontent.com/47291794/108636091-34844e80-7494-11eb-809c-0a4dfbc56dbc.png)
NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.UICharacterSkill.UpdateUI () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Skill/UICharacterSkill.cs:147)
UISelectionEntry`1[T].OnEnable () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UISelectionEntry.cs:43)
UnityEngine.Object:Instantiate(GameObject)
UIList:Generate(IEnumerable`1, Action`3) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UIList.cs:41)
MultiplayerARPG.UICharacterSkills:UpdateData(ICharacterData) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Skill/UICharacterSkills.cs:178)
MultiplayerARPG.UICharacterSkills:UpdateOwningCharacterData() (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Skill/UICharacterSkills.cs:128)
MultiplayerARPG.UICharacterSkills:OnEnable() (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Skill/UICharacterSkills.cs:67)
UnityEngine.GameObject:SetActive(Boolean)
UIBase:Show() (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UIBase.cs:62)
UIBase:Toggle() (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/UIBase.cs:93)
UnityEngine.EventSystems.EventSystem:Update() (at D:/Program Files/2019.4.10f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)

**Comment by insthync** [comment]
Replace UpdateUI function to 
```

        protected override void UpdateUI()
        {
            if (IsOwningCharacter() && Skill != null && Skill.CanLevelUp(GameInstance.PlayingCharacter, CharacterSkill.level, out _))
            {
                onAbleToLevelUp.Invoke();
            }
            else
            {
                onUnableToLevelUp.Invoke();
            }
        }

```

**Comment by DimasjkTV** [comment]
> protected override void UpdateUI()
>         {
>             if (IsOwningCharacter() && Skill != null && Skill.CanLevelUp(GameInstance.PlayingCharacter, CharacterSkill.level, out _))
>             {
>                 onAbleToLevelUp.Invoke();
>             }
>             else
>             {
>                 onUnableToLevelUp.Invoke();
>             }
>         }

Yes works thanks again=)
