### ISSUE TITLE
[Urgent] Client side prediction & Server reconciliation for Server Authoritative Mode Needed

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#813]
Hi @insthync! Hope you are ok. Please kindly Include client side prediction & server reconciliation for server authoritative mode. It is urgently and highly needed; avoiding cheat but still keeping gameplay smooth and also accurate with server's own state. I would appreciate if this request is granted. Thanks @insthync!

**Comment by insthync** [comment]
I'm working on this.

**Comment by isaanyoha** [comment]
Ok, Thanks!

**Comment by insthync** [comment]
Done in 1.63
