### ISSUE TITLE
Remove Jump from Character

### ISSUE THREAD

**Issue by Taludo** [suriyun-production/mmorpg-kit-docs#814]
Hello i would like to remove Jump from character i set Jump Height from 2 to 0 and character continusly jumping and i also deleted the jump key from input setting manager and changed key from space but everytime i press space character jumps so there is something wrong.
I have found solution in "PlayerCharacterController_Inputs.cs" i have removed line 430 and 431 `if (InputManager.GetButtonDown("Jump"))
                movementState |= `MovementState.IsJump;`
`
And character is no more jumping but im not sure if its the best way and if im not breaking the core code

**Comment by insthync** [comment]
You also have to remove jump input setting from Project Settings -> Input Manager

![Screenshot_231](https://user-images.githubusercontent.com/2697550/108845239-be0c5b80-760f-11eb-90c5-83621473c98c.png)

Not sure did you also remove it from game instance?

![Screenshot_232](https://user-images.githubusercontent.com/2697550/108845281-c9f81d80-760f-11eb-8fe9-f45af7c71c30.png)

**Comment by Taludo** [comment]
ok it works now i had to remove from  Project Settings  thank you
