### ISSUE TITLE
Question Projectil direction 

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#815]
Hy i noticed longer time ago that projectiles have a weird behaviour (tryied diffrent controllers -> current one Custom AimAtCursor)

to the problem: In the AimAtCursor controller, Projectiles go in mouse direction. but when your mouse is over an entity projectiles goes to that transform like you can see in the video. where can i disable that? 

https://gyazo.com/2b77b307898db4d38067c345adc51460

**Comment by insthync** [comment]
Update to latest version (0.6), there is a `doNotTurnToPointingEntity` option, turn it on then it won't turn to the pointing entity.

**Comment by moepi2k** [comment]
hi, thank you. but that was not the problem. i already changed in my controller that player not turn to entity. the problem ist not regarding wiht controller i think.

check the video again. its the projectile that fly to targeted entity transform. this happen also when use raycast or melee as attack type.

**Comment by insthync** [comment]
Your meaning is the Projectile is not go to where you point to, right?

**Comment by moepi2k** [comment]
exactly. aslong as you not hover over an entity projecitle is fine.

here i made a new video and incresed collider of tree, so you can better see what i mean

https://gyazo.com/9316e85a334b3f5f21cc1f84a13457b6

when i hover over tree and it select the entity and i shoot. the projectil no longer go to mouse position, it always goes to entity transform position

**Comment by moepi2k** [comment]
here a video on fresh project, same behaviour. when you shoot without aim on an entity the projectile has a diffrent fly rout, when an entity is targeted it take automaticly its transform anyway where you aim.

i cant find where to disable that.
