### ISSUE TITLE
BUG in Android Build

### ISSUE THREAD

**Issue by Taludo** [suriyun-production/mmorpg-kit-docs#816]
i have found a bug, when i build for windows i can create party and guild, but when i build for android i cant create party and i cant create guild
check 
https://gyazo.com/3d1eb622b82a16a1014031a15ceeee3d
https://gyazo.com/71b471938a88e8b7b636b8bdc07d1f15
https://gyazo.com/dbda8f4b364d8e7e4207b7e563796d57
https://gyazo.com/38ed136e19afdb8d735f0cfcf4935c66

**Comment by insthync** [comment]
Thank you for bug report, to fix it you have to change `#if UNITY_STANDALONE && !CLIENT_BUILD` condition in `MapNetworkManager.cs` -> `Awake()`, you can follows this https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/a555d4b8be94075348802d5941d5d060a5010300

**Comment by Taludo** [comment]
so i should replace all `#if UNITY_STANDALONE && !CLIENT_BUILD`  for  `Awake()`

**Comment by insthync** [comment]
You can replace awake function codes
