### ISSUE TITLE
Seamless transition between map servers

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#817]
This is not really an issue, but more of a question...

One of the biggest hurdles to designing a large open world with the kit is the limitation of players per map server without noticeable lag. In other MMORPGs, this problem is solved by implementing buffer zones on the borders between maps where a player effectively exists on both map servers at the same time, in order to be visible to other players on both. Once the player fully moves into the next server's map, the character is transitioned fully to the second map server and removed from the first. This allows developers to split their large open world maps into many different map servers, while allowing seamless transition between them. 

My question is two parts:
1. Do you think this is possible with the LiteNetLib and the kit?
2. Do you have any plans to implement it?

The initial world design of many of our games will rely on this.

Thanks in advance!

**Comment by insthync** [comment]
It is possible, but I don't have a plan to implement it yet.

**Comment by vaughanb** [comment]
Thanks for getting back to me! I am attempting to implement this myself for an add-on. Would you please make your LiteNetLib libraries partial in a future release so that they can be extended without core edits?
