### ISSUE TITLE
Cant connect to server while being on android.

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#819]
I have a weird error where I cant log in to server while being in android. I can log in being in the section of PC (Windows/Linux) but when I change to ANDROID cant log in. Connects me fine to the server but cant register or log in. Got this error. 
![Captura (2)](https://user-images.githubusercontent.com/12781104/109230398-0ba8d580-7782-11eb-81b1-bfbe4c492324.png)

**Comment by MosesGomez** [comment]
Error send me to this line. 
![Captura (3)](https://user-images.githubusercontent.com/12781104/109231626-2b40fd80-7784-11eb-8189-375c7c34306f.png)

**Comment by insthync** [comment]
Which version?, I've already fixed it.

**Comment by MosesGomez** [comment]
> Which version?, I've already fixed it.

I dont really know, but havent update since first download which was in feb 15. Update should solve the problem? Really thank you so much for this fast rensponse :D

**Comment by insthync** [comment]
If it still not works, tell me then :)

**Comment by MosesGomez** [comment]
> If it still not works, tell me then :)

Works Sir. Thank you so much 👍

**Comment by Zikang2610** [comment]
Hi, may I know how to setup a server for andriod version?
