### ISSUE TITLE
Root Motion Animation

### ISSUE THREAD

**Issue by pparkdea** [suriyun-production/mmorpg-kit-docs#82]
![01](https://user-images.githubusercontent.com/55903220/66099234-0ec98180-e5e1-11e9-81d9-57d903cf3205.gif)
![02](https://user-images.githubusercontent.com/55903220/66099240-12f59f00-e5e1-11e9-9c4a-a81add6429f6.gif)

I would appreciate it if you could create an option to selectively apply root motion to animation. ^-^;;

**Comment by insthync** [comment]
There are many requests for this, so I will do research about networking root motion and apply it to the project later.

**Comment by pparkdea** [comment]
Ok, thank you!!

**Comment by insthync** [comment]
Update version 1.50d which contains this root motion implementation (for RigidBodyEntityMovement only) is already uploaded.
