### ISSUE TITLE
Die Animation stop working like pause

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#820]
Hi sur , something strange happen to die animation of monster when i kill him and move the camera to another scene and back again to the monster which i killed i found the die animation stopped when i changed the location of camera and play again which he paused when i move the camera to him again and monster destroy before the end of animation.. ( https://youtu.be/DtaqMTbUj78 ) you can watch the video to understand.
much appreciated for your hard work

**Comment by insthync** [comment]
Try change `Animator` -> https://docs.unity3d.com/ScriptReference/AnimatorCullingMode.html

**Comment by RunOrDi3** [comment]
thanks so much , changed to always animate and now works fine :) much appreciated
