### ISSUE TITLE
respawn position

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#822]
Good afternoon, there was a problem. clean install 
changed nothing, added a map

![image](https://user-images.githubusercontent.com/48797909/109385522-6c145000-7905-11eb-8cd5-161700fda292.png)

After death, the character comes to life only once in the same place where he died. If the character dies again teleports him to map001

version unity: 2020.2.0f1
version project: 16.02.21

**Comment by 1isenok** [comment]
I checked the spawn position of the NPC through the write point.
This is how it works.
But if you put the overwrite point on the map does not work

**Comment by insthync** [comment]
Noted, I will fix it.

**Comment by insthync** [comment]
Fixed in 1.63
