### ISSUE TITLE
Guild war map

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#823]
good day, after loading the Guild war map, the following happens

![image](https://user-images.githubusercontent.com/48797909/109385667-9a465f80-7906-11eb-91b4-96b7a6f1d05c.png)
loading of the map itself occurs, but teleports back to the map001.

with the message as in the picture.

If you try to enter the Guild War map again, it will be empty

![image](https://user-images.githubusercontent.com/48797909/109385699-d7125680-7906-11eb-9931-a5a52a348814.png)

at the same time, on the stage, the heart of the castle can be seen

![image](https://user-images.githubusercontent.com/48797909/109385721-07f28b80-7907-11eb-9bec-a1c6829a6c1d.png)

i nothing changed, please tell me what i do wrong  ? 
in old version all works
use version unity:  2020.2.0f1 
use client version; 16.02.20

**Comment by insthync** [comment]
Noted, I will fix it.

**Comment by 1isenok** [comment]
excellent thank you

**Comment by SourJay** [comment]
I still have this issue I was wondering if it was fixed in the new version but I just checked and its still there making guild wars not functional at all.. :( I appreciate all you do Suri please help!

**Comment by insthync** [comment]
I tried, it's working, I test in MMO mode, not Singleplayer/LAN, You have to join a guild to attack the crystal.

**Comment by SourJay** [comment]
ok ill try again im testing on singleplayer im in a guild and the heart wont spawn its 0 hp killed auto when the game starts with no errors
