### ISSUE TITLE
npc

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#824]
good afternoon, tell me please.
I need to change npc settings

![image](https://user-images.githubusercontent.com/48797909/109385862-dded9900-7907-11eb-9a19-293deabeddba.png)

the npc can set the quest parameter, it can be repeated

But I need that the quest can be repeated a limited number of times a day or at a certain time interval

![image](https://user-images.githubusercontent.com/48797909/109385938-5a807780-7908-11eb-93e8-9b6c15a08cb1.png)

or as an example worked at a specific time like in the guild war map

thank you in advance

**Comment by insthync** [comment]
Noted, I will fix it.

**Comment by 1isenok** [comment]
хорошо, спасибо большое, буду ждать

**Comment by insthync** [comment]
In 1.85 it have repeat setting are: anytime, daily and weekly
