### ISSUE TITLE
 Currency

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#825]
Good day, how can i add currency to drop or drop table ? >
![image](https://user-images.githubusercontent.com/48797909/109387529-f1eac800-7912-11eb-9b66-b02c7deb47ee.png)

**Comment by insthync** [comment]
I have to add codes for that. Please wait next version.

**Comment by 1isenok** [comment]
I got it, thanks for the quick reply

**Comment by insthync** [comment]
Added to 1.63
