### ISSUE TITLE
 Currency reward is not displayed

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#826]
Currency reward is not displayed
For example:

![image](https://user-images.githubusercontent.com/48797909/109406223-77f52600-7988-11eb-9f06-ee0b8f6a5ced.png)
![image](https://user-images.githubusercontent.com/48797909/109406227-804d6100-7988-11eb-9e3d-99bb8916d602.png)

When the quest is completed it is also not displayed:

![image](https://user-images.githubusercontent.com/48797909/109406249-abd04b80-7988-11eb-88b4-00833c1342a6.png)

But the reward itself appears:
![image](https://user-images.githubusercontent.com/48797909/109406296-eafe9c80-7988-11eb-9105-cad66e2a779c.png)

there is also no container for the purchased reward, if a notification about the receipt of these things is displayed when gaining experience / gold. Then there is nothing in gaining fame

**Comment by insthync** [comment]
In `CharacterQuest` class actually have reward currencies settings, but I forget to set up the demo, I will do it now, it will be included in next version.

![Screenshot_244](https://user-images.githubusercontent.com/2697550/109406663-93bef300-79ad-11eb-8b4b-a4899fa13b60.png)

**Comment by 1isenok** [comment]
it;s good thanks i will try, if it doesn't work i will wait for the next version

**Comment by insthync** [comment]
Added to 1.63 demo
