### ISSUE TITLE
EntityUpdate()

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#829]
Hi !

I wanna got more information about this function "EntityUpdate()" especialy in BuildingEntity.cs, how the function work, and when she's call ? 

Because i make modification on the script to update my material, that's partially work, ... As you can see in this video : 
https://youtu.be/un0jWhEplW8
In certain weather condition my building take damage, and damage are visually materialised with an shader on the building at each step of the entity currentHP. This part work good. 
BUT first problem my lerp seem doesn't work when he call in EntityUpdate() because as you can see the transition of each step are instant. Maybe i have to do it in an coroutine ?

**Comment by insthync** [comment]
EntityUpdate will be called in Update (Generic Unity monobehaviour update function). It's correct to lerp/transition your building in EntityUpdate, not have to use coroutine, you may have to change how to lerp/transition it. I don't know how you do that?

**Comment by Gui205** [comment]
> EntityUpdate will be called in Update (Generic Unity monobehaviour update function). It's correct to lerp/transition your building in EntityUpdate, not have to use coroutine, you may have to change how to lerp/transition it. I don't know how you do that?

Like basic lerp A to B time/5. the same code work correctly in the unity Update() function ( also when i use the generic Update() in your script ). That's why i thought your function is call or work differently than the regular one, it is as he read the lerp but only one time and dont continue to update it at each frame like the unity update()

**Comment by insthync** [comment]
Want to make sure that which is that `EntityUpdate`, it is function from `BaseGameEntity` or `BaseGameEntityComponent`?

Did you try logging some messages in that `EntityUpdate`? Is it logging every frame?

**Comment by insthync** [comment]
Or you may just create a new component for transitioning and do it in `Update` function just have to get a building entity reference in `Awake` to get updating HP.

**Comment by Gui205** [comment]
> Or you may just create a new component for transitioning and do it in `Update` function just have to get a building entity reference in `Awake` to get updating HP.

Yes i think i will do that it's sound better and avoid to remake all the modifcation at each update ahaha
