### ISSUE TITLE
Quest still bugged

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#83]
Quest in mmo mode is still glitched i know u provided a temporary fix for this but it would be nice to have a fully working kit as some people will just download kit and think quest dont work and never use it again ..could u add the patch to the next version
Either a fix for the codes or removal of the codes like the temporary patch u provided to me few days ago in characterQuest
![quest](https://user-images.githubusercontent.com/7702658/66155561-3a1f9100-e620-11e9-82e9-91ab38ba4d79.JPG)

**Comment by insthync** [comment]
Okay, I will remove this part

**Comment by insthync** [comment]
Just updated 1.49c, try it :p
