### ISSUE TITLE
UI item dialog Slot

### ISSUE THREAD

**Issue by 1isenok** [suriyun-production/mmorpg-kit-docs#830]
Hello. When i add the type of armor i see this:

![image](https://user-images.githubusercontent.com/48797909/109447351-86a90f00-7a54-11eb-974b-b3fb8aa558a2.png)

When i add a pet (or mount item) i can't see this: 

![image](https://user-images.githubusercontent.com/48797909/109447448-beb05200-7a54-11eb-9278-53fd4cdcf805.png)

and I can't make a thing dressable in ui dialog

please, tell me how I can change this so that these things can also be added to the UI item dialog:

![image](https://user-images.githubusercontent.com/48797909/109447591-1949ae00-7a55-11eb-91c6-cc0dda4b3688.png)

**Comment by insthync** [comment]
Mount/Pet in this kit isn't an equipable item, it is a usable item, which when using it, character will ride the mount entity. For pet items, it will be used and spawn monster entity to help you to fight. When the monster entity dies it will return the item back.

**Comment by 1isenok** [comment]
yes, I understand it, but If you have more than 400 types of resources, it is problematic to find the desired mount / pet before the battle, so I wanted to store them in a separate window of the user interface. That would be possible to contain a large database of pet models, riding models.

Or maybe you can show me how to create a separate box in the inventory, when you open it, an additional user interface window will open for storing items, but in the main inventory it will take up 1 slot

**Comment by insthync** [comment]
Or may create new systems especially for that?, I used to play Ragnarok M, MU Mobile, which have separate parts for pet/mount.

**Comment by 1isenok** [comment]
Unfortunately I don't play Ragnarok.
Yes, something like this would be great, if you could show how to do this, perhaps with a separate, paid asset, it would be great, perhaps it would be of interest not only to me.
Think about it, maybe you will have time
