### ISSUE TITLE
where is mmorpgtemplate.sqlite3？

### ISSUE THREAD

**Issue by shenhua8369** [suriyun-production/mmorpg-kit-docs#831]
When I run the mmo in the editor, I can't find the mmorpgtemplate.sqlite3 file. where is mmorpgtemplate.sqlite3？
**DirectoryNotFoundException: Could not find a part of the path "C:\Users\ITTIPON\Desktop\UnityBuilds\MultiplayerARPG\mmorpgtemplate.sqlite3".**

**Comment by insthync** [comment]
While testing in editor with SQLite you have change this settings to where you want to place sqlite3 file

![Screenshot_266](https://user-images.githubusercontent.com/2697550/109487049-48dcd280-7ab6-11eb-91d7-f7d91d3eabbc.png)
