### ISSUE TITLE
Turning on and off spot lights with day and night time

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#832]
its not a bug or something , i just wanna make my street spot lights turn on while the time of night and turn off when the time of day come.. How can i make it ?

**Comment by insthync** [comment]
You can see `SampleDayNightTimeApplyer.cs` codes, it has updating light scripts by time, you may create new component which will be attached to the light to turn on/off by time

**Comment by RunOrDi3** [comment]
ok i will try with it .. thanks alot
