### ISSUE TITLE
I get error '...The type or namespace name 'CraftItemEvent' could not be found'

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#834]
Assets\UnityMultiplayerARPG\Core\Scripts\UI\Item\UIItemCraftItemSelectionManager.cs(3,91): error CS0246: The type or namespace name 'CraftItemEvent' could not be found (are you missing a using directive or an assembly reference?)

when I try to upgrade to 1.62g (2021-02-18)

**Comment by insthync** [comment]
You can delete `UICraftItem`, `UICraftItems` and `UICraftItemSelectionManager` because filenames were changed

**Comment by isaanyoha** [comment]
Ok. Thanks!
