### ISSUE TITLE
Aim Assist on hill

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#835]
Hi,
You can see the attached gif for details.
![Q1CnjucGHV (1)](https://user-images.githubusercontent.com/55019005/109874834-ee877180-7c6f-11eb-8e87-0683583b1c04.gif)

Only happen when the OrcWarrior is on a hill and the Aim Assist X is checked.
![image](https://user-images.githubusercontent.com/55019005/109874904-07902280-7c70-11eb-9e9b-d692a552f6c4.png)

What is happening? Thanks

**Comment by insthync** [comment]
Try 1.64, if it's still not working then tell me later.
