### ISSUE TITLE
Cannot build as APK

### ISSUE THREAD

**Issue by Zikang2610** [suriyun-production/mmorpg-kit-docs#837]
Error is about:
Unable to sign the application ; please provide password.
Build completed with a result of 'Failed' in 108 second 
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002bf] in <8d21067e8d9c494db25a2b2485216e63>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <8d21067e8d9c494db25a2b2485216e63>:0 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Picture:
![Capture](https://user-images.githubusercontent.com/79124942/110060302-a9169180-7da0-11eb-9c82-847654fa88ee.PNG)

**Comment by insthync** [comment]
See how to sign your android project here: https://unitycoder.com/blog/2015/05/04/building-apk-with-release-mode/

**Comment by Zikang2610** [comment]
[image: Capture2.PNG]
Why have this error?

**Comment by insthync** [comment]
I can't see an images

**Comment by Zikang2610** [comment]
[image: Capture2 (7).jpg]

**Comment by insthync** [comment]
No images, You should post in github not replying from your email
![Screenshot_278](https://user-images.githubusercontent.com/2697550/110080598-4089dd80-7dbd-11eb-991a-4663057e3567.png)

**Comment by DimasjkTV** [comment]
You must enter the password for your key. This is not a problem with this kit. These are standard unity requirements.
