### ISSUE TITLE
Can't create LAN to join ?

### ISSUE THREAD

**Issue by OrtharionProject** [suriyun-production/mmorpg-kit-docs#838]
Hello, I just launched the asset but I'm already having problems. I followed the little tutorial, nothing complicated but when I run the 2 builds, I correctly create the server but cannot see it in the list of servers to join ... bug or incomprehension on my part? 
I specify that I have already published a Unity game so I know the basics.
Thanks in advance.

**Comment by Gui205** [comment]
You can try to use Hamachi to make distant LAN

**Comment by OrtharionProject** [comment]
Thanks for the suggestion.
the LAN in this asset is like "couch-LAN"/split screen , there is nothing that allows direct integration? Or how can i integrate for exemple Hamachi in this asset ? There is no tuto about something like this :s ... I don't know anything about multiplayer yet. 
All multiplayer tutorial speak about mirror, Photon, so hamachi is made to do something totaly different that thoses ? 
If this asset does not manage all the multiplayer functions, it is better that I create my solution? Because I wouldn't need the Rpg part, I already have my own asset that I will "simply" rebuild for multiplayer,

**Comment by Gui205** [comment]
> Thanks for the suggestion.
> the LAN in this asset is like "couch-LAN"/split screen , there is nothing that allows direct integration? Or how can i integrate for exemple Hamachi in this asset ? There is no tuto about something like this :s ... I don't know anything about multiplayer yet.
> All multiplayer tutorial speak about mirror, Photon, so hamachi is made to do something totaly different that thoses ?
> If this asset does not manage all the multiplayer functions, it is better that I create my solution? Because I wouldn't need the Rpg part, I already have my own asset that I will "simply" rebuild for multiplayer,

I dont understand your problem, this asset use LiteNetLib, it's socket based so for LAN you just need to join the IP of the hoster nothing more. 
Hamachi is an external software ( free ) allow you to connect multiple computer inside one network/lan, so it's usefull to test the lan feature of MMORPG kit between friends if you are not on the network ( physicly ).

**Comment by OrtharionProject** [comment]
on my computer i host, then with another game (on my computer) i try to join, i can't see any button in the "Find game" panel, but i can join.
if i try with another computer i can't join the party and of course can't see anything in the "Find game" panel.

**Comment by Gui205** [comment]
> on my computer i host, then with another game (on my computer) i try to join, i can't see any button in the "Find game" panel, but i can join.
> if i try with another computer i can't join the party and of course can't see anything in the "Find game" panel. ( with the corect ip)

Maybe try to just type the ip of hoster before and press join after

**Comment by OrtharionProject** [comment]
funny man ;)

**Comment by insthync** [comment]
Are you going to run LAN game, not MMO, right?

As I try, it's working

![Screenshot_284](https://user-images.githubusercontent.com/2697550/110232148-af4a7080-7f4e-11eb-80a6-cd5bdcf1bd68.png)

Not sure when you're running the game you press disallow firewall? or you have some app running on port `19050`?, It's a port for networking discovery.

**Comment by OrtharionProject** [comment]
Will players also have to disallow their firewall in order to play the game? I did not indeed verify this but if the players have to do this as well I will look for another way, I prefer to create a system that is easy to use. 
And I can join on my pc too, but not from another pc.

**Comment by insthync** [comment]
No no, I mean you have to allow firewall in this window 

![](http://recover-it.biz/images/article/07/windows-firewall-5.jpg)

(But as I just saw in the image it force to allow :P)

**Comment by OrtharionProject** [comment]
haa ok sorry i didn't understand that way. i have no window security alert.
Yes my problem is exactly this, i can open the Find Game panel, but there is nothing in it.
But even if there is no character to join i can simply click the "Join" green button to join in my computer, but not in another computer.

**Comment by insthync** [comment]
Not sure that you can connect to another computer by put another computer IP and press join or not? (not press find game). If not I guess that it has something block your PCs to connect together, you may try ping to another PC to check that it can connect or not.

**Comment by OrtharionProject** [comment]
if i create a game on my computer it's like if the hosting did'nt work, i have try firewall/avast/ clean my computer (malware, cach, coockie etc ....) rebuild the game, create another Unity project, nothing works.

But i can create a host in another computer and then join with this one, so internet is ok, but i don't understand why i can't find the hosting game if i create with this game.
I just wanted to share my latest tries in case if this happens to others, I'm not especially waiting for a response.
Regards

**Comment by insthync** [comment]
If you still not able to make it work, you may emailing me: ittipon.bay@gmail.com, then may let me try on your devices via TeamViewer.
