### ISSUE TITLE
=========> [Bug]1.63 Player Position MMO -Update 1.63b <=========

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#839]
Hello, first thank you for the great update.

to the issue. i made a video. player position is false. use 1.63 fresh project in mmo

https://gyazo.com/0146a29508c31bbd3068b674f864f04b

Database: Sqlite

**Comment by insthync** [comment]
I am thinking that I will remove server authoritative movement because I working on it so long, and it's not suitable for "MMO games", I also don't use it in my games. But I will add speed hack detection at the server.

**Comment by moepi2k** [comment]
what? that would be devastating. even if speedhack detection is in. players would find a way to teleport through thin walls..

**Comment by insthync** [comment]
Hmm, Or I may just send point click inputs after calculated target position at client to server?

**Comment by moepi2k** [comment]
i dont know whats best solution as the kit use diffrent controllers. i had no time to test 1.63 yet i just started a fresh project. in my game i use aimatcursorcontroller and customized it. so you mean the current disync issue is only with point click controller? 

you invest alot of work already in adding client side prediction. so why removing it? maybe you find a way to fix the issues?
i mean not all ppl that use the kit making an mmo, but for some, server auth is very important. in my game for example is player housing a core feature and its very important that other players cant hack through walls with teleport hacks or something else.

also interactable through walls should not work.

your idea with speedhack detection is a good way to reduce impact serverside. i think wow do it in same way and atavism.
but make it optional so like it is right now.

**Comment by Callepo** [comment]
@insthync i agree with by removing server auth completely would be bad imo, just cuase point click works fine, if its removed the shooter controller will be pretty much useless in a way, there are more ways to hack then just speedhack
like for example running the game in editor, on not secure, i can drag the player to anywhere on the map i want even in mmo and nothing happens cuase movement is not secured, with serv auth its unmoveable, and many other small ways people can perform small hack etc

and the whole reason Client side prediction was added is to make serv auth movement better, removing it means we have no use for CSP anymore. basically all u did on the movement update was for nothing.

**Comment by RunOrDi3** [comment]
@Callepo there are more than me use shooter controller

**Comment by Callepo** [comment]
i use shooter also, but thats not the point.

Like if serv auth gets removed and something is added in its place that will prevent most hacks and be secured like serv authorative was.. idm.. 
but to remove serv auth + csp and just add speed hack detection isnt that good.

@insthync im willing to donate to compensate for the amount of work ur doing, i know csp wasnt easy to add... and can be frustrating, i know many other would be willing to donate something too if that can help with atleast to give it an attempt on fixing the position sync.

**Comment by Fr-Coder** [comment]
If it is working using point and click i don't think you are too far away from the goal. I agree with @Callepo we can help you effort by donation or any support or testing do you need :)

**Comment by RunOrDi3** [comment]
@insthync i have tested your new update with shooter controller and everything works great :)

**Comment by Callepo** [comment]
i was literally bout to do the exact same lol, i have some free time today.. im busy updating my project to go do a mmo test

**Comment by RunOrDi3** [comment]
i have tested in mmo with shooter controller in my game

**Comment by moepi2k** [comment]
Im also willing to donate you, your work is great and i belive in you

**Comment by Callepo** [comment]
i also tested and there is no issue.. lol maybe its just the normal controller?



https://user-images.githubusercontent.com/7702658/110332811-1c2e3b00-8021-11eb-964f-8c2845b0bc23.mp4

**Comment by RunOrDi3** [comment]
i think the problem is inside player character controller

**Comment by Callepo** [comment]
i will make new build with normal controller

**Comment by Callepo** [comment]
https://user-images.githubusercontent.com/7702658/110333426-db82f180-8021-11eb-9801-02f2c96e3ac8.mp4

Normal PlayerCharacter Controller.. no position sync issue ..

**Comment by RunOrDi3** [comment]
no it is , i found the same issue ^^ try more

**Comment by RunOrDi3** [comment]
move up and down , left and right and so on and you will find it after time

**Comment by Callepo** [comment]
ok i will play for like 10 minutes, and level up etc and see

**Comment by Callepo** [comment]
so ur spamming random keys to make it happen?
thats basically means ur client is processing more inputs than ur server which is why the position gets weird. the server just needs to adjust the clients after then

**Comment by RunOrDi3** [comment]
i just moved around the character and move left and right and so on tryin to move inside him and so on so i get wrong position , i did the same with shooter and everything great

**Comment by Callepo** [comment]
i made a very long video of spamming , running around map, jumping, waling in circles.. being a complete idiot just to try and find it. 
https://youtu.be/dd0UKd9nzK4

**Comment by RunOrDi3** [comment]
weird , i will do test again and record it

**Comment by RunOrDi3** [comment]
https://youtu.be/iHPe_VgVqSM ) check this one ? and the problem not happen everytime or all the time anyway

**Comment by Callepo** [comment]
Same.. the update is very nice.. no need for drastic change.. in ur video the position sync issue fixed itself lolol so yea.. idk..

**Comment by RunOrDi3** [comment]
@insthync me and calle tested both controllers and works good , but we have noticed that player character controller have small issue maybe you need to check it again , you dont need to remove anything, just keep on your amazing work ( its very good update ) thanks alot 
![Untitled](https://user-images.githubusercontent.com/64667641/110339198-8c908880-8030-11eb-81d1-2f55418dc628.jpg)

**Comment by Callepo** [comment]
@insthync  Very long clip or shooter serv autho movement lol 
https://youtu.be/vMO_D76UDpc

Works Perfectly Fine!

**Comment by moepi2k** [comment]
as calle already mentioned. you should stop hear to all the ppl asking for new features. the kit is good as it is, it should be polished now and bug fixxing. the most iimportant part is to fix movement with the new csp.

i tested new patch 1.63b and noticed that rubberband works now. but the problem ist that player is too fast out of sync.

here a video https://gyazo.com/fc25d17c511e54880ce90daa8269a7d9

**Comment by insthync** [comment]
Thank you for all of your suggestion, encouragement and donation :), I will find the best way to implement it :)

**Comment by RunOrDi3** [comment]
we all believe in you that you will find the best way , best of luck man :)

**Comment by Callepo** [comment]
> as calle already mentioned. you should stop hear to all the ppl asking for new features. the kit is good as it is, it should be polished now and bug fixxing. the most iimportant part is to fix movement with the new csp.
> 
> i tested new patch 1.63b and noticed that rubberband works now. but the problem ist that player is too fast out of sync.
> 
> here a video https://gyazo.com/fc25d17c511e54880ce90daa8269a7d9
> 
> p.S i think your not far away for the fix. maybe just an input. i may be wrong but should the clients position not checked on every serve tick and correct it when its diffrent from server position and correct it? right now it seems that it only correct if thresold is > 5 and then rubberband

what happens if u change snap to like 0.5?

**Comment by moepi2k** [comment]
then you rubberband around alot. problem is that somewhere is an issue that player goes out of sync too fast.
https://gyazo.com/6efb2daec3948795e4d846d65b366c73

**Comment by moepi2k** [comment]
set Thresold to 0. so client never goe out of sync, but for others you lagging around ^^ seems lerping no longer works then

https://gyazo.com/9b216bf9ecf86a8da12544707f908c51

**Comment by Callepo** [comment]
ah i see
