### ISSUE TITLE
Aiming Issue with shooter controller

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#84]
IF u are a main hand pistol and offhand sword and shoot its fine .. but if u swap ur weapons to a mainhand sword and offhand pistol .. ur pistol doesnt aim right.. the only way to shoot straight is to stand still or backwards  .. if ur running forward it will shoot it off high in the air 

this is only an issue if u wear a melee weapon as main hand, Pistol /Pistol is fine and 2 handed weapons are fine too 

https://youtu.be/aigOQ4tjog0

**Comment by insthync** [comment]
Fixed, will be included in next update

**Comment by Callepo** [comment]
awesome thank you. Is it a small fix ? or you had to do alot ? if its small can i have code patch ?
And thank you for all the fixes u been doing lately, We appreciate it alot thank you

**Comment by insthync** [comment]
There are changes in 1 file (ShooterPlayerCharacterController.cs) by move set aim position function call (`SetAimPosition(aimPosition);`) at line 663 to line 425, and I also make it change which weapon (which hand) is going to attack when attack keys press, by add condition before set `isLeftHandAttacking` at line 268

```
                    if ((tempPressAttackRight || tempPressAttackLeft) &&
                        turningState == TurningState.None)
                    {
                        // So priority is right > left
                        isLeftHandAttacking = !tempPressAttackRight && tempPressAttackLeft;
                    }
```

**Comment by Callepo** [comment]
thank you so much .. its works

**Comment by insthync** [comment]
Just updated 1.49c, try it :p
