### ISSUE TITLE
1.62G; Issue with DemoShooter camera

### ISSUE THREAD

**Issue by LeafRockJ** [suriyun-production/mmorpg-kit-docs#840]
If you have added ShooterGameplayCamera to game and select/open that prefab in Uninty Editor, It will create to scene these _CameraTargetFollower objects. 
![_CameraTargetFollower](https://user-images.githubusercontent.com/71341252/110249608-93ab8e00-7f7f-11eb-8e4b-2ead931a9443.jpg)

Unity version: 2019.4.18f1

Project is using URP pipeline

Edit; 
It also generates this error to console:
``Destroy may not be called from edit mode! Use DestroyImmediate instead.
Destroying an object in edit mode destroys it permanently.
UnityEngine.Object:Destroy(Object)
FollowCamera:OnDestroy() (at Assets/UnityMultiplayerARPG/Core/CameraAndInput/Scripts/Camera/FollowCamera.cs:81)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
``

**Comment by insthync** [comment]
This was fixed in 1.63, sorry for the issue :(
