### ISSUE TITLE
in-app-purchasing

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#841]
I have the following problem when I try to enable IAP I followed all the steps in the documentation, but I keep getting this error.

**Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance_Purchasing.cs(159,24): error CS0407: 'UniTaskVoid GameInstance.ResponseCashPackageBuyValidation(ResponseHandlerData, AckResponseCode, ResponseCashPackageBuyValidationMessage)' has the wrong return type**

**Comment by insthync** [comment]
Oh, I forget to change codes after structure changes you can fix it by change `GameInstance_Purchasing.cs` -> `ResponseCashPackageBuyValidation` return type to `void`

Like this 

```
        private void ResponseCashPackageBuyValidation(ResponseHandlerData requestHandler, AckResponseCode responseCode, ResponseCashPackageBuyValidationMessage response)
        {
            if (responseCode == AckResponseCode.Unimplemented)
            {
```

![Screenshot_286](https://user-images.githubusercontent.com/2697550/110279968-986a5380-800c-11eb-9b8b-1c4a7ea5e8b9.png)

**Comment by Blunnyn** [comment]
Thank you very much, close the thread

**Comment by Blunnyn** [comment]
Hello again me, I think I have completed all the steps, I even created the IAP CATALOG but when I put play the following error appears:  
<img width="989" alt="Captura de Pantalla 2021-03-08 a la(s) 18 45 05" src="https://user-images.githubusercontent.com/45702662/110385962-67a31200-803e-11eb-89c0-236564cf2417.png">

As a consequence, this generates that there are no products to buy in the cash shop

<img width="460" alt="Captura de Pantalla 2021-03-08 a la(s) 18 45 32" src="https://user-images.githubusercontent.com/45702662/110386049-8d301b80-803e-11eb-8b8d-1375748fd88c.png">
