### ISSUE TITLE
Leak/Loop in AudioSourceSetter

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#844]
During my testing i noticed a huge performance problem with the AudioSourceSetter. The update is being run way too much and caused 40+MS lag with the CPU, and 40-50% CPU usage.

```
  private void Update()
    {
        if (playMode == PlayMode.PlayClipAtAudioSource)
            cacheAudioSource.volume = AudioManager.Singleton.GetVolumeLevel(SettingId);
    }

```

You should investigate it

**Comment by insthync** [comment]
I've made it set `volume` only when the volume level changed in 1.63c
