### ISSUE TITLE
LiteNetLibIdentity

### ISSUE THREAD

**Issue by sawcisson** [suriyun-production/mmorpg-kit-docs#845]
![image](https://user-images.githubusercontent.com/62859548/110322800-f2bae280-8013-11eb-8ed6-10f37e6e3841.png)

So we should remove LitenetlibIdentity from all characters right ? I see that example characters in the kit still have this script.
Should this component be removed from harvestables etc... also ? 
![image](https://user-images.githubusercontent.com/62859548/110322766-e9317a80-8013-11eb-89a6-a76aa4239dc7.png)

**Comment by insthync** [comment]
Oh, it must be `LiteNetLibTransform`

**Comment by sawcisson** [comment]
Yeah i thought so aswell, thx for clarification !
