### ISSUE TITLE
error 1.63

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#848]
There is a bug with version 1.63 when killing a monster.
This prevents the monster from dropping any items.
<img width="1131" alt="Captura de Pantalla 2021-03-08 a la(s) 13 31 03" src="https://user-images.githubusercontent.com/45702662/110350627-ade27c00-8012-11eb-8e2c-08554547f4e1.png">

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by Blunnyn** [comment]
thnks
