### ISSUE TITLE
Guild name

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#85]
Is it possible to set a limit on the number of characters in a guild name?
![image](https://user-images.githubusercontent.com/47291794/66197606-6af4da00-e6a3-11e9-8d11-b4134877d927.png)

**Comment by insthync** [comment]
Oh, I will add setting to `SocialSystemSetting` in next version

**Comment by DimasjkTV** [comment]
> Oh, I will add setting to `SocialSystemSetting` in next version
Nice! thank You!

**Comment by DimasjkTV** [comment]
> Oh, I will add setting to `SocialSystemSetting` in next version

role name also needs character restrictions
![image](https://user-images.githubusercontent.com/47291794/66254714-e7121f00-e782-11e9-978e-dff9d6667fdc.png)

**Comment by insthync** [comment]
Yep, and I also adding max length for guild message too.

**Comment by DimasjkTV** [comment]
> Yep, and I also adding max length for guild message too.


Another small bug. You can create guilds with the same name.

**Comment by DimasjkTV** [comment]
![image](https://user-images.githubusercontent.com/47291794/66257125-d15e2300-e79d-11e9-9770-25af2455f762.png)

**Comment by insthync** [comment]
Okay, it's fixed :p

**Comment by insthync** [comment]
Just updated 1.49c, try it :p
