### ISSUE TITLE
ItemDropEntity2D

### ISSUE THREAD

**Issue by Zodly** [suriyun-production/mmorpg-kit-docs#850]
I'm pretty certain it isn't deliberate, but it has 2 `LiteNetLibVisibleChecker `scripts, no `GridVisibleChecker`.

The basic, 3d version of ItemDropEntity has the proper components.

**Comment by insthync** [comment]
Oh it's my mistake, I will remove them and add `GridVisibleChecker`, Thank you to tell me :)
