### ISSUE TITLE
StorageEntity

### ISSUE THREAD

**Issue by Zodly** [suriyun-production/mmorpg-kit-docs#851]
I'm unsure if this effecting 3D chests, but from what I assume is they run the exact same, but when first laying down a chest and opening the UI for it, the Viewport Content does not populate, so there is no direct indication of how many spots are available in a new storage entity until you drag an item into it, in which then it updates and shows the available slots and there after it works, it's just the very first initial opening of it.

Forgive me for the shoddy screenshots.

![InitialOpen](https://user-images.githubusercontent.com/63520118/110546469-21a88580-80f4-11eb-8e8c-ddf2fd346d9f.PNG)
![AfterDeposit](https://user-images.githubusercontent.com/63520118/110546471-22411c00-80f4-11eb-88f3-d0483e729a5e.PNG)

**Comment by sawcisson** [comment]
i've got the same problem here and campfire aswell

**Comment by insthync** [comment]
Fixed, I will include the fix in next update.
