### ISSUE TITLE
[Suggestion] Open dialog via button 

### ISSUE THREAD

**Issue by Exzezz** [suriyun-production/mmorpg-kit-docs#854]
Hi, is it possible to open an npc dialog directly through clicking on an button?

**Comment by Callepo** [comment]
no, npc dialog need a npc entity with a npc dialog on them to know what dialog to open.. 
you can open the window with a button yes.. but it wont show none.. if u want it like that u gotta code it urself.

**Comment by insthync** [comment]
@Exzezz Not sure that you mean to click on talk to NPC when your character is near NPC?
