### ISSUE TITLE
TPS crosshair alignment issue

### ISSUE THREAD

**Issue by SourJay** [suriyun-production/mmorpg-kit-docs#855]
![Capture](https://user-images.githubusercontent.com/62675710/110865983-5134ca80-8279-11eb-9b18-f98956395cb8.JPG)
if you change the TPS target offset x it moves the bullets from going in the center of the crosshair they only go dead center if you put the X at 0 and that makes it hard to see the crosshair.... is there anyway to align the bullets to the crosshair instead of coming from the player x position?

**Comment by insthync** [comment]
It's always launching from character's damage transform to where you aiming which raycasting by weapon range or skill range to world position which find by raycasting to center of screen, I don't sure how you want it to work?
