### ISSUE TITLE
1.62G: Attack animation does nothing

### ISSUE THREAD

**Issue by LeafRockJ** [suriyun-production/mmorpg-kit-docs#856]
Using Unity 2018.4.18f1.

I have ShooterGameplay Controller in use. My player has set Controller type to Advance and for the Monster it is using Custom with duplicated __AdvanceMonster and I have configured separate Right Hand Attack Animation.
Player:
![image](https://user-images.githubusercontent.com/71341252/110972564-cb8e4900-8364-11eb-8d39-ea9385bea525.png)

Monster:
![image](https://user-images.githubusercontent.com/71341252/110972686-f082bc00-8364-11eb-8790-1c2979cc125f.png)

For Player, if use my 2H weapon and press attack, nothing happens (Same for Monster, it should attack the player):
![image](https://user-images.githubusercontent.com/71341252/110972948-435c7380-8365-11eb-8886-e7b518204724.png)

I have tested the animations on 1.61C and those are working fine.

**Comment by insthync** [comment]
I want to see your `Weapon Animations` settings too, did you set weapon type correctly or not.

**Comment by insthync** [comment]
I want to see your `Weapon Animations` settings too,  to find out that did you set weapon type correctly or not.

**Comment by LeafRockJ** [comment]
Here is my Weapon animations:
![image](https://user-images.githubusercontent.com/71341252/111068713-94d64100-84d2-11eb-9279-7ac4b2672a47.png)
![image](https://user-images.githubusercontent.com/71341252/111068721-a0c20300-84d2-11eb-8a69-2e47d86db0ae.png)

**Comment by LeafRockJ** [comment]
I just tested out that if I config something for example Idle Clip, that idle animation will work. 
![image](https://user-images.githubusercontent.com/71341252/111078676-602cae80-84ff-11eb-8be6-d17121be6ffb.png)


Only attack is currently the issue.

**Comment by LeafRockJ** [comment]
Update; Current situation is only happening on Single Player mode, not on the MMO

**Comment by insthync** [comment]
I try to fix animation duration issues in 1.63g, try it.
