### ISSUE TITLE
BuildingMaterial  use renderer.sharedMaterials instead of renderer.materials

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#857]
In BuildingMaterial  

                  switch (currentState)
                    {
                        case State.Default:
                            meshRenderer.materials= defaultMaterials;
                            break;
                        case State.CanBuild:
                            meshRenderer.materials= canBuildMaterials;
                            break;
                        case State.CannotBuild:
                            meshRenderer.materials= cannotBuildMaterials;
                            break;
                    }

can you please use  meshRenderer.sharedMaterials  instead of  meshRenderer.materials ?

also change
       defaultMaterials = meshRenderer.materials;
to
       defaultMaterials = meshRenderer.sharedMaterials;

meshRenderer.materials creates a new copy of the materials.

**Comment by insthync** [comment]
Okay

**Comment by insthync** [comment]
Did it in 1.63c
