### ISSUE TITLE
Error at loading Map.

### ISSUE THREAD

**Issue by Deepankar1993** [suriyun-production/mmorpg-kit-docs#858]
![image](https://user-images.githubusercontent.com/1295862/111021183-98919700-83f0-11eb-9523-ebc793a3762e.png)

This happens 9 out 10 times when starting the game and it gets stuck at the loading screen 90%

**Comment by insthync** [comment]
Did you set `EquipmentEntity` to any character entity ?

**Comment by insthync** [comment]
Did you attach `PoolingGameEffectsPlayer` to any game entity ?

**Comment by insthync** [comment]
You should find which and how that game effects prefab destroyed when initial its pool.

**Comment by Deepankar1993** [comment]
`EquipmentEntity ` and `PoolingGameEffectsPlayer `

Where there should be attached, I crossed it with the default `Map001` and `Male`  character I didn't find and reference of these 2 scripts to be attached

**Comment by Deepankar1993** [comment]
Update : This same behaviour is also present when running in with defaults 00Init and Map001

**Comment by insthync** [comment]
Map loading is not the cause of the problem, the cause of the problem is your game effects settings. I don't know which one of yours is wrong.

**Comment by Deepankar1993** [comment]
Where I can the "Game effects settings"

**Comment by insthync** [comment]
I mean `Game effects` components which attached to your game effects, such as hit effects. It should not place in the scene because it gonna be destroyed on load scene

![Screenshot_293](https://user-images.githubusercontent.com/2697550/111148009-b5c79080-85bd-11eb-929b-6467f8e0c085.png)

**Comment by insthync** [comment]
In 1.63c I've made it find null data and avoid it. But the problem is your game effects can be not instantiated while playing game.
