### ISSUE TITLE
Ladder System

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#859]
Hi ! 

Is it possible to add an ladder climbing system ? 

It's not hard to do but i have no choice to make modification in base script and after it's really hard to keep everything update :(

**Comment by RunOrDi3** [comment]
+1

**Comment by ayyluca** [comment]
Yes please this would be very usefull :)

**Comment by Gui205** [comment]
> Yes please this would be very usefull :)

If you want a really Quick way to do it you can make an truffée collider at the bottom of your ladder Who will teleport your player at the top of the ladder. No code skill requiert

**Comment by BJPickles** [comment]
+1
