### ISSUE TITLE
BUG Reset attributes 

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#86]
If we reset the attributes, then after the restart they cannot be pumped and they are reset.

**Comment by insthync** [comment]
I don't understand the issues

**Comment by DimasjkTV** [comment]
> I don't understand the issues


check discord

**Comment by DimasjkTV** [comment]
1. We reset attributes using an item to reset attributes.
2. We do logout
3. We go into the game and see that our attributes are 0 and you cannot put attribute points in them

**Comment by insthync** [comment]
Okay, I will fix it

**Comment by insthync** [comment]
Just updated 1.49c, try it :p
