### ISSUE TITLE
[Bug]Ability Hide

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#860]
i make a new post because you closed old one 

https://github.com/suriyun-production/mmorpg-kit-docs/issues/771

this bug is still there -> 1.63b

**Comment by insthync** [comment]
Checking again, You mean your controlling player or other players.

**Comment by insthync** [comment]
Oh, I see, it's controlling character

**Comment by insthync** [comment]
Fixed in 1.63c
