### ISSUE TITLE
[Issue] Spawn On Building Roof

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#861]
When I add a Ceiling/Roof piece to the building system and build a structure with a Ceiling/Roof, when I quit the game and enter again, the player is spawned on the roof. (Even when the player was inside the building when quitting the game)
(I also cannot exclude the roof layer on the Open Character Controller, because the roof should be walkable)

Can you add a Ceiling/Roof piece to the Survival Demo so that you see the issue?

**Comment by moepi2k** [comment]
i also noticed that. player always spawn on the highest part even when its not a building entity

**Comment by insthync** [comment]
I actually try to find nearest position to spawn position, you can see how it work in `RigidBodyEntityMovement` -> `FindGroundedPosition`. So it should set character's position to grounded position which nearest to spawn position.

**Comment by rasto61** [comment]
> I actually try to find nearest position to spawn position, you can see how it work in `RigidBodyEntityMovement` -> `FindGroundedPosition`. So it should set character's position to grounded position which nearest to spawn position.

I had a look in RigidBodyEntityMovement. I will try to think how this could be remedied.

(But try to add a Ceiling/Roof piece to the demo, so you can see what we mean)

**Comment by insthync** [comment]
![Screenshot_300](https://user-images.githubusercontent.com/2697550/111190574-cd1c7300-85e9-11eb-8a1d-05241ba2415a.png)
Like this ?

**Comment by rasto61** [comment]
Yes. When you save a reenter game, does the player spawn inside ?

When I exit play mode like this:
![Screenshot (243)](https://user-images.githubusercontent.com/7036357/111191995-e6f19200-85b8-11eb-9d46-e46b6af9fbba.png)

I respawn like this:
![Screenshot (244)](https://user-images.githubusercontent.com/7036357/111192076-fa046200-85b8-11eb-972e-32b1f0159cc3.png)

**Comment by insthync** [comment]
Hmm, mine still spawn inside the building.

**Comment by rasto61** [comment]
> Hmm, mine still spawned inside the building.

I will try to find why its spawning on the roof.

**Comment by insthync** [comment]
You may try delete find grounded position calling in `BaseGameEntity` -> `Teleport` function 

![Screenshot_302](https://user-images.githubusercontent.com/2697550/111347467-d2dd8b80-86b1-11eb-86a2-f6047a909720.png)

**Comment by insthync** [comment]
Please try 1.64, if it's still not working, you can reopen this post.
