### ISSUE TITLE
New Feature Charge missing Field?

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#862]
hello,

today i tried the new feature for charge and wanted to implement in shooter. 

on the new charge field i added the animation for holding the arrow. it looks like this:
https://gyazo.com/92a014f5b90e953a191af50e609f1053

the problem is, the animation for pulling the bow runs after it. and there is no field for release fire

in my mind it should be

1) Pulling Bow
2) Hold (Charged)
3) Release

what do you mean?

**Comment by insthync** [comment]
Release animation should be continued from hold, not full shoot animation.

**Comment by moepi2k** [comment]
Exactly, but its this animation field is missing. Only charge is new.

I can use the attack animation field for release animation but because that one runs after the charge one, but then there is no field for start (load) the charge animation

I have two animation variants, one for bow and one for melee.

Both are like

Load animation
Hold anination
Release animation

**Comment by insthync** [comment]
Okay, I will add it, I was intending to use attack animation as release animation and also no hold loop. I think it's currently has a lot of fields XD

**Comment by moepi2k** [comment]
great, ye there are alot of fields. but the FireOnRelease is a great feature for Shooter to make Archery and other stuff.
Charging Bow and hold button before fire is great. all AAA game use this :)
