### ISSUE TITLE
Animation interruption

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#863]
Is an possibility to make an animation interruption by the next state ? Because actually when you set up the interruption in the animator it's seem to doesn't work.

As exemple for pikcup : 

https://gyazo.com/3620ec746b7de347ea77bb1a16408fff

The pickup still play when i move.

**Comment by RunOrDi3** [comment]
that happen to me too .. +1

**Comment by gordowebdesign** [comment]
+1

**Comment by khongtuong** [comment]
+1

**Comment by insthync** [comment]
Try set transition from pickup state to move state like this
![Screenshot_301](https://user-images.githubusercontent.com/2697550/111327376-ebdd4100-869f-11eb-816e-bc12a0585a05.png)

Some info: https://blogs.unity3d.com/2016/07/13/wait-ive-changed-my-mind-state-machine-transition-interruptions/

**Comment by Gui205** [comment]
> Try set transition from pickup state to move state like this
> ![Screenshot_301](https://user-images.githubusercontent.com/2697550/111327376-ebdd4100-869f-11eb-816e-bc12a0585a05.png)
> 
> Some info: https://blogs.unity3d.com/2016/07/13/wait-ive-changed-my-mind-state-machine-transition-interruptions/

Thanks for you answer, i finally do something different because at my opinion move and cut the animation at the middle when you pickup something in the ground was a bit strange, so i set the player movespeed at 0 when he picking something during the half time of the animation, and i do the same when he get hurt ( Same for the AI ). It's have better sence for me, i assume it's again some script modification i will have to do at each update but that's the price :p
