### ISSUE TITLE
How to build server in apk

### ISSUE THREAD

**Issue by Zikang2610** [suriyun-production/mmorpg-kit-docs#865]
https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/025-getting-started-mmo

This link is about how to build the server for window and linux only. May I know have any tutorial about how to build server in apk ?

**Comment by moepi2k** [comment]
how you wanna host a server on mobile? thats not possible.

**Comment by Zikang2610** [comment]
Mean if I using apk cannot be have host or server? Just can play single
game?

**Comment by insthync** [comment]
You actually can host LAN games if other players want to connect to your host, they have to use the same wifi as yours, but if you are going to make MMO which anyone can connect, you have to run the server on Linux or Windows. You may try google about client-server model.

**Comment by Zikang2610** [comment]
Thank you for your explanation and very fast replying my question.

**Comment by Zikang2610** [comment]
Hi, may I know we can import photon system into the kits or not?It will be
duplicate with the network system in the kits or not?

**Comment by insthync** [comment]
It's a different networking system, to change to another network system is like remake the project.
