### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe.dll conflict with MMO Plugins and Unity Jobs Package

### ISSUE THREAD

**Issue by gordowebdesign** [suriyun-production/mmorpg-kit-docs#866]
\Assets\UnityMultiplayerARPG\MMO\Plugins\System.Runtime.CompilerServices.Unsafe.dll

Im getting this error on a fresh install of urp + kit + unity jobs package  (2019 LTS)

Would it be possible to use a different library for MMO plugins as the Unity Jobs package uses System.Runtime.CompilerServices.Unsafe.dll and having both causes a conflict.
![unknown](https://user-images.githubusercontent.com/71939436/111250491-ca1e8400-85e3-11eb-8bbb-67c49b7c2ad2.png)

**Comment by insthync** [comment]
You can delete Assets\UnityMultiplayerARPG\MMO\Plugins\System.Runtime.CompilerServices.Unsafe.dll

**Comment by gordowebdesign** [comment]
![unknown](https://user-images.githubusercontent.com/71939436/111254871-59c83080-85ec-11eb-89e4-2a785e3feef8.png)
7 new errors after deleting.

**Comment by insthync** [comment]
Oh, I will find how to fix it.

**Comment by gordowebdesign** [comment]
> Oh, I will find how to fix it.

Thank you!

**Comment by insthync** [comment]
About this, I have to change how to connect to the database server, it's currently using GRPC for connection, which I have to change it. It might take some time.

**Comment by gordowebdesign** [comment]
It seems like this issue cannot be reproduced in 2020 LTS - maybe call it resolved since it only affects an older version of Unity?

**Comment by insthync** [comment]
Okay, but I still have to do it because it was reported that it can't be built as an IL2CPP build while using GRPC.
