### ISSUE TITLE
Performance Issues 

### ISSUE THREAD

**Issue by 2324268086** [suriyun-production/mmorpg-kit-docs#867]
Shooter IO 100 robots, can only 5 fps
mmorpg-kit 200 bots, 50 fps ！！！！

**Comment by 2324268086** [comment]
Same environment, LAN

**Comment by moepi2k** [comment]
this is github for mmorpg kit, you are in wrong place

**Comment by rasto61** [comment]
> Shooter IO 100 robots, can only 5 fps
> mmorpg-kit 200 bots, 50 fps ！！！！

There is nothing that can be done with what you provided.

Ideally look at the profiler and point out what the bottleneck is...
Or at least include the Profiler graph.

**Comment by Callepo** [comment]
told this guy 50 times.. shooter.io is not mmorpg kit .. so there is nothing "same" bout any of it..
