### ISSUE TITLE
Root motion ignore collision 

### ISSUE THREAD

**Issue by khongtuong** [suriyun-production/mmorpg-kit-docs#868]
https://youtu.be/-mCZfQYwX6Y

**Comment by insthync** [comment]
I don't know how can I fix it. Did you have an example which anyone can fix this issue, it's about Unity's animation system and its physic system that I can't fix it. Do you use rigid body entity movement? You may try character controller entity movement which uses character controller not kinematic rigidbody for movement.

**Comment by insthync** [comment]
If you are going to use character controller entity movement, you have to remove following components: `rigidbody entity movement`, `open character controller`, `capsule collider` and `rigidbody` then add `character controller entity movement` and set `character controller` settings

**Comment by khongtuong** [comment]
thanks you, it's working
