### ISSUE TITLE
[Bug]Summoned Creatures

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#869]
Summoned Creatures collide with other Enemies and push them away.

You can test on fresh project when summon an orc archer and walk through other orcs. they collider with each other

**Comment by insthync** [comment]
In next version I will add `obstacleAvoidanceWhileMoving` and `obstacleAvoidanceWhileStationary` to `NavMeshEntityMovement` to change agent's `obstacleAvoidanceType` setting
