### ISSUE TITLE
DevExt requests

### ISSUE THREAD

**Issue by astromediaonly** [suriyun-production/mmorpg-kit-docs#87]
I have figured it would be nice to have thread for DevExtension hooks requests.

It would be great if those would be added:

**ShooterPlayerCharacterController**:
- OnIdChange (im not sure what is it exactly for, only that i need it :) )
- Setup
- Desetup
- OnNonEquipItemsOperation
- OnEquipItemsOperation
- OnEquipWeaponSetChange
- OnAttributesOperation
- OnSkillsOperation
- OnSummonsOperation
- OnBuffsOperation
- OnHotkeysOperation
- OnQuestsOperation
- OnStorageItemsOperation

**MapSpawnNetworkManager**
- way to register custom message as its done for example for ``MMOMessageTypes.RequestSpawnMap``

**Comment by insthync** [comment]
I'll add 2 DevExt functions for `BasePlayerCharacterController` there are `Awake` and `OnDestroy`

In `BasePlayerCharacterController` there are an `onSetup` and `onDesetup` actions and in `BaseCharacterEntity` there are an `onIdChange `, `onNonEquipItemsOperation`, `onEquipItemsOperation`, `onEquipWeaponSetChange`, `onAttributesOperation`, `onSkillsOperation`, `onSummonsOperation`, `onBuffsOperation`, `onHotkeysOperation`, `onQuestsOperation`, `onStorageItemsOperation`

So you will able to setup like this
```
public partial class ShooterPlayerCharacterController
{
        [DevExtMethods("Awake")]
        public void DevExtSample_Awake()
        {
                onSetup += OnSetupSample;
                onDesetup += OnDesetupSample;
        }

        [DevExtMethods("OnDestroy")]
        public void DevExtSample_OnDestroy()
        {
                onSetup -= OnSetupSample;
                onDesetup -= OnDesetupSample;
        }

        void OnSetupSample(BasePlayerCharacterController ctrl)
        {
                PlayerCharacterEntity.onIdChange += OnIdChangeSample;
        }

        void OnDesetupSample(BasePlayerCharacterController ctrl)
        {
                PlayerCharacterEntity.onIdChange -= OnIdChangeSample;
        }

        void OnIdChange(string id)
        {
                Debug.Log("Id change to " + id);
        }
}
```

**Comment by astromediaonly** [comment]
Thanks so much, i was kinda thinking that it should not be that time consuming and was wondering why it had no response :)

That makes sense, i had kinda overcomplicated it you are right, this should suffice in theory. Thanks again, this will allow me to do some progress. Relying on devextensions is still very restraining because lot of them are missing yet but i hope it will pay up in long term ... custom core modifications are hard to track :)

**Comment by insthync** [comment]
Added in 1.50

**Comment by astromediaonly** [comment]
Nice, thanks ... was that ``MapSpawnNetworkManager`` part added as well? :)

**Comment by insthync** [comment]
Oh, I forgot it

**Comment by astromediaonly** [comment]
I see, it was just minimalistic reminder at bottom of what we talked about back somehere in June, so i suppose it was easily missable :) 

This is relevant part of conversation if it helps somehow:
![image](https://user-images.githubusercontent.com/14101093/67282209-877d7880-f4d1-11e9-843e-daf3dcacdfdc.png)
Its not in hurry for now but i would be a bit sad if it would have been forgoten completely .. more sophisticated way of handling instances is kinda crucial to my project :)

**Comment by insthync** [comment]
I don't know why you want it ?

**Comment by insthync** [comment]
I just add `OnInitCentralAppServerRegister` dev ext methods, you can download it at https://github.com/insthync/UnityMultiplayerARPG_MMO

**Comment by astromediaonly** [comment]
I was trying to explain it inside that discord conversation but i suppose i will try to make it more simple ... english is not my primary language, sorry:

So current instance system works you port party leader and everybody in party to instance at once right?
What i want to do is create system acting like this:
- if player goes through instance portal map server will ask central server
- - central server will check its list if there is instance of that map already running for that player or party leader if in party based on my map id and player id
- - if there is already running map, player will be ported there
- - if there is not, central server will ask map spawn server to spawn new map, then that map's server willl notify central server when its ready, central server will store id of map, id of owner (player, party leader) to some list and then player will be ported there

Idea is to be able to go inside and outside of instances at any time without being ported at once with party leader - instance will be created when any party member will go trough portal at first time for party leader and when any additional party member will go trough that portal central server will see there is already map spawned for that party leader and that player will just be ported to same map.

Additionaly i plan to have multiple types of instanced maps - one which will be locked to party leader id and one which will be caped by player count and i plan this system to handle both. So when port request will be received on central server, server will check map info and if its "global map" and has player limit it will go trough all spawned instances of that map and if any has less ppl than limit it will port him there but if there is none it will spawn new one and port player there. And if its "instanced" map it will go trough that paty leader based logic i have described in previous parargraph.

Problem is there was no visible way for me to make this communication without core changes: central server asks map spawn server to spawn map with custom info -> map spawn server notifyes central server map is spawned giving custom info back

Its kinda hard to describe properly and im still in trial error development phase but i hope its understandable atleast partialy.

**Comment by astromediaonly** [comment]
Thanks, sadly im sick atm so it will take me some time to get back to "operational state" to develop something that complex but i will check it out eventually and let you know if it helped :)
