### ISSUE TITLE
1.63c Server Auth Movement

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#870]
Thank you for Updating and fixing stuff in 1.63c.

i tested it already, the sync issues seems to be fixxed.

problem now when using AimAtCursorController -> Video https://gyazo.com/443c67665a9d033d315a4c72624108d8

Rotation are not updated correctly for clients and Server.
also projectiles then fly in diffrent ways.

**Comment by insthync** [comment]
I will fix it.

**Comment by moepi2k** [comment]
Great.

one more thing noticed.
https://gyazo.com/7a5dcfec16835c54f93727f06ddfb792
this is shooter controller test with male (Non Secure) when rotate player. it is stuttering. you will notice it more when u walk an rotate.

on owning player its good only when you look at other players it stutters whiel rotate

**Comment by moepi2k** [comment]
alright i tested 1.63d

following results
rotation is better but its still stuttering. it update not smoothly
video -> https://gyazo.com/3c0f6b09f026373a36b7d5a1014c1316

then noticed some other bugs
video -> https://gyazo.com/d6b77ddf3241252fbd62b58954c0751b
i reduced speed of bow projectile to see better the problem
1) projectile has diffrent direction from onwing player and server. when you look around and fire the projectile goes always in false direction. there where the projectile from owning player goes is not counting when hit, because server has diffrent aim target.

2) as you can see theres a problem, sometimes projectile is not instantiate and when shoot it hit instant without flytime.

let me know if you need more videos

ah and btw this is with male prefab so its "non secure"

**Comment by insthync** [comment]
For stuttering rotation, try changes codes in `HandleSyncTransformAtClient` function to set client target position instead of set move paths

![Screenshot_303](https://user-images.githubusercontent.com/2697550/111389105-f836bd80-86e2-11eb-91cf-dd91078c63e8.png)


About projectile, I am going to change inputs to set aim position at the same time with other inputs.

**Comment by Callepo** [comment]
nice

**Comment by moepi2k** [comment]
Sounds good, after that its nearly perfect

**Comment by moepi2k** [comment]
Update: 1.63e Projectil direction 

it seems that the issue is fixxed for Shootercontroller -> Video
https://gyazo.com/811442ff48d1cf377526deaa70b81796

but its not working for AimAtCursorsController -> Video
https://gyazo.com/a2d03cd3fad2aba205379cccb888880d

for shootercontroller it take the first clickposition as target and send that to server right?
so when you have a bow with a long animation like 2 second and use triggertime to 1 so that projectil will fired at end of animation, then player look around during animation, will that not be a problem? like at beginning of animation the player look at 0,0,0, start firing, animation runs 2 seconds during that he looks to 2,2,2, then projectil goes still to 0,0,0

**Comment by moepi2k** [comment]
Update: 1.63d Projectil direciton

still same issue
video ->
https://gyazo.com/00b71954ade4ca0fe95c408b4a0fd9e4
