### ISSUE TITLE
Is it possible to send an item via mail?

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#871]
I asked this to the community and someone told me it is possible, but I cannot find how to attach an item to email because the inventory is deactivated when compose an mail. 

Is this doable in this kit currently or not implemented yet?
If yes, can you advise me how to attach an item to mail?

Thanks!

**Comment by moepi2k** [comment]
thats not possible, was false information from the guy

**Comment by RunOrDi3** [comment]
i was wrong , you can give items via trade not mail , my mistake

**Comment by dglee2592** [comment]
Thanks guys for the answer 👍
