### ISSUE TITLE
fake date in mail system [Bug]

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#872]
when i send an mail to any player it always give 2 Hours ago and i have sent that mail right now ...
![Untitled](https://user-images.githubusercontent.com/64667641/111454643-8a5bb780-871d-11eb-9c87-42e64604044c.jpg)

**Comment by insthync** [comment]
It is not fake, it is wrong timezone, I will fix it to store to database as your local time zone.

**Comment by RunOrDi3** [comment]
aha ok
