### ISSUE TITLE
[Bug]Campfire Entity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#873]
Campfire Entity is bugged when multible slots with fule are filed and reach 1. then it never consume more but the entity is running.
version: 1.63e
settings: Convert interval 2 for fuel
consume amount fuel: 1

https://gyazo.com/fb0a1578a0eb2d4b21ac4ca5b587df79

**Comment by insthync** [comment]
Fixed in 1.63f
