### ISSUE TITLE
[BUG] Melee attack

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#874]
Hi ! 

Since i update to last version i got that's error when i use melee attack ( The attack doesn't make any dammage, but the animation is played ) : 

https://gyazo.com/d919a0660782fcc890007ca7aa2d140d

( The skill and other type of attack work correctly ). 
I don't have this bug on vanilla project so i don't really know where i have to look, do you change something on melee ? 

UPDATE : 

This bug appear only on character who was created before the update.

**Comment by insthync** [comment]
These line ? 

![Screenshot_304](https://user-images.githubusercontent.com/2697550/111751514-2f65c400-88c7-11eb-8792-fd6cc4b0bcd5.png)

**Comment by insthync** [comment]
![Screenshot_305](https://user-images.githubusercontent.com/2697550/111752291-1873a180-88c8-11eb-98ee-1a2e6b1aa5ae.png)

These lines?

**Comment by insthync** [comment]
I guess that you might have removed skill data.

**Comment by Gui205** [comment]
> I guess that you might have removed skill data.

Yes those lines, but it's strange because it's melee type, so the axe, pick, and unarmed attack give me that error, all other skill and attack work correctly, and i dont remove/rename/change those 3 skills. 

But anyway, this error doesn't appear on news character so i close this issue, i maybe do some change i didn't remember.
