### ISSUE TITLE
Weapon type and weapon item

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#875]
Hi !

Is it possible to add an bool on weapon item that's allow the player to move or not when he shot. Like the weapon type melee or single shot ( You can't move when you do a melee attack and Move speed rate While attacking it's at 0 ).

It's also appear the option "Move speed rate While attacking" doesn't work correctly ( or complety ) when you are in state "IsWeaponCharge"

**Comment by insthync** [comment]
Added `Move Speed Rate While Reloading` and `Move Speed Rate While Charging` to weapon items in 1.63g
