### ISSUE TITLE
PlayWeaponChargeClip loads wrong charge clips

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#877]
PlayWeaponChargeClip in AnimationCharacterModel.cs loads the weapon charge clip for the left hand if weapon is right handed and vice-versa.

This appears to be the result of the ternary operator:
`AnimationClip chargeClip = isLeftHand ? GetRightHandWeaponChargeClip(dataId) : GetLeftHandWeaponChargeClip(dataId);`

GetRightHandWeaponChargeClip and GetLeftHandWeaponChargeClip should be swapped.

**Comment by insthync** [comment]
Fixed in `1.63g`
