### ISSUE TITLE
Crit, Evasion, Block, Hit Chance

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#878]
Hi ! 

Something is really weird, i have many trouble with those stats actually, maybe someone could explain me. 
- Enemy miss me to many time but i have 0 evasion 0 block and they have 300 accuracy : 
https://gyazo.com/ae33dca9a3e86e0091f3f45395931278
- Is too easy to dodge the enemy, when you move, they attack your previous position

Someone could explain me how those all stats work the actual documentation is not really clear.

**Comment by Gui205** [comment]
This is what happen when you try to make an enemy who could attack you when you run : 
https://gyazo.com/11a49d0548c0d2ca4d20ef8666e747b2
It's jerky and not smooth

**Comment by insthync** [comment]
You can see how hit chance calculation in `DefaultGameplayRule` -> `RandomAttackHitOccurs`, `GetCriticalChance`, `GetHitChance`, `GetBlockChance` and also create your gameplay rule by create class which inherit from `DefaultGameplayRule` and override functionality.

**Comment by moepi2k** [comment]
> This is what happen when you try to make an enemy who could attack you when you run :
> https://gyazo.com/11a49d0548c0d2ca4d20ef8666e747b2
> It's jerky and not smooth

I notice this problem also, when the enemies move speed is higher as the player and player running away and enemy stick on him the enemies movement is jerky

**Comment by Gui205** [comment]
> > This is what happen when you try to make an enemy who could attack you when you run :
> > https://gyazo.com/11a49d0548c0d2ca4d20ef8666e747b2
> > It's jerky and not smooth
> 
> I notice this problem also, when the enemies move speed is higher as the player and player running away and enemy stick on him the enemies movement is jerky

I dont think it's speed problem, but the way who the melee damage work, from the DamageTransform you can see it, when he update the position for apply the damage that cause the jerk

**Comment by moepi2k** [comment]
im not sure, try set up enemy so that he only follow you without attacking, i think the problem is the same

**Comment by Gui205** [comment]
> im not sure, try set up enemy so that he only follow you without attacking, i think the problem is the same

On my project is not, that my initial problem before, he run behind me but never attack whilde he sould because he's faster than me ... So i change the place of the DamageTransform front off him and now he run behind and attack me but he's jerky like my gif

**Comment by moepi2k** [comment]
But when hes faster then you and chasing you without attack how is it looking?

**Comment by Gui205** [comment]
> But when hes faster then you and chasing you without attack how is it looking?

It's smooth the enemy run at the speed of the player even if he could run faster than him ( That my problem that why i have to move the Damage Transform to do the enemy attack but that make the enemy entity jerky )

@insthync Do you have an idea to avoid that the jerky enemy ? 
https://gyazo.com/11a49d0548c0d2ca4d20ef8666e747b2

**Comment by insthync** [comment]
I guess that It's try to attack but then it moving follow enemy then it's stop playing attack animation to play move animation.

**Comment by Gui205** [comment]
> I guess that It's try to attack but then it moving follow enemy then it's stop playing attack animation to play move animation.

I'm not sure about that because i make upper layer for the attack, so the base layer always stay on move and the speed is alway greater than 0 : 

https://gyazo.com/f5143d51b7d056723edf158fb05bf9de

**Comment by insthync** [comment]
How about upper layer? Is it playing attack state?

**Comment by Gui205** [comment]
> How about upper layer? Is it playing attack state?

when he should yes :

 https://gyazo.com/eec9d9d0d159db91adf49ea9930ce6f6

**Comment by insthync** [comment]
In `MonsterActivityComponent` try delete codes at line: 172 (`Entity.StopMove();`)

**Comment by Gui205** [comment]
> In `MonsterActivityComponent` try delete codes at line: 172 (`Entity.StopMove();`)

That's solve the problem and work perfectly !
