### ISSUE TITLE
Area Attack and Buffs Shooter issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#88]
when ur using shooter controller.. u have like a 50% chance of ur ability casting or just using an auto attack. i think it prolly needs a check somewhere to see if it busy with a spell it shouldnt auto attack. for normal controller this isnt an issue cuase ur left click doesnt attack ur V button does

https://youtu.be/Jaik4qQMkeY

**Comment by Callepo** [comment]
Ps. We all love the new updates .. people been wanting it for a while now and some people are really happy bout it

**Comment by insthync** [comment]
Hmm, I probably uploaded the wrong package file, I will re-upload it, to fix it by yourself just add codes to `ShooterPlayerCharacterController`
```
            if (UICharacterHotkeys.UsingHotkey != null)
                return false;
```
To function `GetPrimaryAttackButton()` and `GetSecondaryAttackButton()`
So codes will be
```
        public bool GetPrimaryAttackButton()
        {
            if (UICharacterHotkeys.UsingHotkey != null)
                return false;
            return InputManager.GetButton("Fire1") || InputManager.GetButton("Attack");
        }

        public bool GetSecondaryAttackButton()
        {
            if (UICharacterHotkeys.UsingHotkey != null)
                return false;
            return InputManager.GetButton("Fire2");
        }
```
