### ISSUE TITLE
Weapon position & euler angles not adjusting. Pls what am I doing wrong?

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#880]
Weapon can local scale to any value & you can will see the size of the weapon obviously adjust on character's hand but local position & local euler angles do not reflect when adjusted no matter what parameter I type in. Please, what are my doing wrong? It started after I updated to 1.63g. Help me. Its been almost 2 days & to no avail
![CaptureXXXXXXXXXXXXX](https://user-images.githubusercontent.com/4920405/112109188-89a9a200-8bb1-11eb-9e0f-32f83a7e0878.PNG)

**Comment by isaanyoha** [comment]
![CaptureXXXXXXXXXXXXX](https://user-images.githubusercontent.com/4920405/112109121-7565a500-8bb1-11eb-916f-1ff867e41f95.PNG)

**Comment by insthync** [comment]
Sorry, I've put work-in-progress codes, I've removed it in 1.63h

**Comment by isaanyoha** [comment]
Ok. Thank you!

**Comment by isaanyoha** [comment]
Ok. So as it is now removed, what will be used then?

**Comment by insthync** [comment]
The settings which is in WeaponItem data

**Comment by isaanyoha** [comment]
Ok, let me check
