### ISSUE TITLE
Jerky rotation in multiplayer

### ISSUE THREAD

**Issue by Gui205** [suriyun-production/mmorpg-kit-docs#883]
Hi !

I noticed in multiplayer when an enemy attack you the rotation is jerky. I saw this problem was reported but actually is closed but i still have this issue in the actual version 1.63g

**Comment by insthync** [comment]
The problem which solved by delete stop move codes?

**Comment by Gui205** [comment]
> The problem which solved by delete stop move codes?

That's not the same problem, this one is server rotation synch rate problem, in local, or for the hoster ( For server side ) everything is smooth, but for the client the rotation is jerky ( And only the rotation the position transform is smooth )

**Comment by Gui205** [comment]
https://gyazo.com/02e0470deeb46a7b7786715a9c5768b3 That's maybe explain better ... It's not the best but you can see the rotation of the enemy

**Comment by Gui205** [comment]
https://gyazo.com/a04f36db58a7d64ebf45b95ce5840a04
https://gyazo.com/42d88c2904296d93592630cceadc10a9

That's could maybe show you better, the left windows is the hoster it's smooth, but at the right the rotation are jerky for the enemy only ( Player are smooth )

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.64
