### ISSUE TITLE
[Bug]Wrong Damage calculation

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#884]
Hey, 

i noticed that damage calculation for skills is wrong

https://gyazo.com/06b5ccb21f20ca814ca0a6f26108cce9
this is my skill.

my weapon do 10 dmg so means the skill should do + 150% = 15 dmg but the damage is 20+
when i use a weapon with 20 dmg the result is 40+

**Comment by insthync** [comment]
Calculation formula is `Dmg` = `WeaponDmg` + (`WeaponDmg` * `Inflictions`) for each kind of element
So if your `WeaponDmg` is `10(Normal)`, `5(Fire)` and `Inflictions` is `1.5(Normal)` then: 
- `Dmg` = `10` + (`10` * 1.5`) + `5(Fire)`
- `Dmg` = `10` + `15` + `5(Fire)`
- `Dmg` = `25` + `5(Fire)`
If your weapon damage is `20` it should be `20` + `30` = `50`

**Comment by moepi2k** [comment]
ahhh inflictionrate multiplies the whole base damage and adds it again. but then the tooltip is wrong
https://gyazo.com/6460282ead72c032c065e67c8a9c6fc7

this means it will just multiplay 1.5 to the base damage. not base damge + (base damage * 1.5)
