### ISSUE TITLE
[Bug]Harvestable DropToGround

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#886]
there is a small bug.

when use DropToGround on harvestable -> https://gyazo.com/50ceaa3c3cefe4d0058fa6443c9e8cc2

then playe will get the message on loot "Not allowed to pickup"
so like if someone other gathered it and the Loot block timer is running

**Comment by ayyluca** [comment]
Yeah it happens to me too , looks like you need to wait a few seconds before u can pick it up?

**Comment by insthync** [comment]
I will fix it.
