### ISSUE TITLE
Equipment Entity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#887]
can you explain how this works?

https://gyazo.com/6f459f1672515db418cbd4d4cb04f891

anyway what i change (Material or Effect Objects) it does not change by leveling up item

**Comment by RunOrDi3** [comment]
1+

**Comment by insthync** [comment]
It should change equipment's material and effects gameobject will be activated when item's level >= `Level`,

**Comment by moepi2k** [comment]
Effect is a gameobject like particle attached as child?

Both material and effect not working correct then. 
In the picture above, it always has the material from level 1 alsp when the item has lvl 0 or lvl 2, the effect is also always visible (level 0) but should activate at lvl 1

**Comment by insthync** [comment]
Fixed in 1.64
