### ISSUE TITLE
guild war error

### ISSUE THREAD

**Issue by SourJay** [suriyun-production/mmorpg-kit-docs#888]
im getting this error in the guild war but its a a default base kit singleplayer and local and mmo all the same result, its a fresh imported project just mmorpg kit installed. it happens when you kill the guild heart, i checked the settings and everything seemed to be set right, no matter what damage entity it does the same also no rewards come in the mail at all from rounds or end 

NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.BaseGameNetworkManager.GiveGuildBattleRewardTo (System.Int32 winnerGuildId) (at Assets/UnityMultiplayerARPG/GuildWar/Scripts/BaseGameNetworkManager_GuildWar.cs:239)
MultiplayerARPG.BaseGameNetworkManager.CastleOccupied (System.Int32 attackerGuildId) (at Assets/UnityMultiplayerARPG/GuildWar/Scripts/BaseGameNetworkManager_GuildWar.cs:150)
MultiplayerARPG.MMO.GuildWar.GuildWarCastleHeart.Killed (MultiplayerARPG.EntityInfo lastAttacker) (at Assets/UnityMultiplayerARPG/GuildWar/Scripts/GuildWarCastleHeart.cs:11)
MultiplayerARPG.BaseCharacterEntity.ValidateRecovery (MultiplayerARPG.EntityInfo causer) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity.cs:399)
MultiplayerARPG.BaseCharacterEntity.ReceivedDamage (UnityEngine.Vector3 fromPosition, MultiplayerARPG.EntityInfo instigator, MultiplayerARPG.CombatAmountType combatAmountType, System.Int32 damage, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/BaseCharacterEntity.cs:537)
MultiplayerARPG.BaseMonsterCharacterEntity.ReceivedDamage (UnityEngine.Vector3 fromPosition, MultiplayerARPG.EntityInfo instigator, MultiplayerARPG.CombatAmountType damageAmountType, System.Int32 damage, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterEntity/MonsterCharacterEntity/BaseMonsterCharacterEntity.cs:283)
MultiplayerARPG.DamageableEntity.ApplyDamage (UnityEngine.Vector3 fromPosition, MultiplayerARPG.EntityInfo instigator, System.Collections.Generic.Dictionary`2[TKey,TValue] damageAmounts, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageableEntity.cs:130)
MultiplayerARPG.DamageableHitBox.ReceiveDamage (UnityEngine.Vector3 fromPosition, MultiplayerARPG.EntityInfo instigator, System.Collections.Generic.Dictionary`2[TKey,TValue] damageAmounts, MultiplayerARPG.CharacterItem weapon, MultiplayerARPG.BaseSkill skill, System.Int16 skillLevel) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageableHitBox.cs:48)
MultiplayerARPG.BaseDamageEntity.ApplyDamageTo (MultiplayerARPG.DamageableHitBox target) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageEntities/BaseDamageEntity.cs:85)
MultiplayerARPG.MissileDamageEntity.TriggerEnter (UnityEngine.GameObject other) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageEntities/MissileDamageEntity.cs:184)
MultiplayerARPG.MissileDamageEntity.OnTriggerEnter (UnityEngine.Collider other) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageEntities/MissileDamageEntity.cs:152)

**Comment by insthync** [comment]
**DO NOT TEST GUILD WAR IN SINGLEPLAYER GAME !**
 That error will be occurring in single-player game only because it has no implemented mail system.
