### ISSUE TITLE
Add quest condition to Monster Spawn Area ?

### ISSUE THREAD

**Issue by Koodetat** [suriyun-production/mmorpg-kit-docs#89]
Hello, 

My project has more than a hundred quests.  I have to position many Monster Spawn Area on the map, which causes some performance problems. 

Is it possible to add an optional active quest(s) condition to each Monster Spawn Area?  (The quest or quests are specified and the Monster Spawn Area only activates when the player enters in the monster area and has the related quest). 

Is it finally possible to add an option to spawn monsters of the same level as the player?

**Comment by insthync** [comment]
Yeah, I can add it

**Comment by Koodetat** [comment]
Great !!

**Comment by Koodetat** [comment]
do you have news about this feature?

**Comment by insthync** [comment]
Did not do it yet, I will add it to this repository: https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand

**Comment by Koodetat** [comment]
Great !  thank you !  sorry to be impatient my project is almost ready!

**Comment by insthync** [comment]
Added the scritp `QuestMonsterSpawnArea.cs` (https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand/blob/master/Scripts/QuestMonsterSpawnArea.cs)

You will have to modify CORE code `MonsterSpawnArea.cs` Line 30 to
``` 
public virtual void Spawn(float delay)
```

**Comment by Koodetat** [comment]
Exactly what i wanted !  thank you !!

**Comment by Koodetat** [comment]
is it possible adding two little things to this script: 
-the possibility of spawning monsters with the same level as the player with an option to select?  
- And make the quest condition optional to make it more versatile?

**Comment by insthync** [comment]
Not accept, please try to do it by yourself
