### ISSUE TITLE
[Change] BuildingMaterial make meshRenderer public

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#891]
Is it possible to change in BuildingMaterial 
   private Renderer meshRenderer;
to
   public Renderer meshRenderer;

and change:
   meshRenderer = GetComponent<MeshRenderer>();

to:
   if (meshRenderer == null)
                meshRenderer = GetComponent<MeshRenderer>();

(also similar change for spriteRenderer and tilemap)

So that we can have multiple BuildingMaterial on a box collider and assign different mesh renderers, irrespective of the collider?

**Comment by insthync** [comment]
Okay, I will change it.

**Comment by insthync** [comment]
Changed in 1.64
