### ISSUE TITLE
[Bug]Item Requirement not works

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#892]
Hello,

item requirement not works. i set attribute for requirement. check follow pictures

editor item
1) https://gyazo.com/d53780184f50c26cfa1deeb5d1102c98

ingame item
2) https://gyazo.com/6cf9521fdd974d38c697578cfa18b3db

msg when try to equip
3) https://gyazo.com/45cc26a7f9606d5f933070a1798fe446

tested with shields dont know if this happen also for other item types like weapons for example

**Comment by moepi2k** [comment]
p.s i tested with other items. its also not working

**Comment by insthync** [comment]
Okay, I wil fix it.

**Comment by moepi2k** [comment]
hi. 
item requirement is still bugged
https://gyazo.com/c235293e50bb19aca85ef2154b35e58d requirement is met but still get msg
https://gyazo.com/1c583c3c806b5f035b763451365f39b7

**Comment by insthync** [comment]
As I test, mine work correctly.

**Comment by moepi2k** [comment]
sorry my fault, forgot to add Attribute to player scriptable O.o

mh strange, i use it in diffrent way. let me explain.
player can unlock a passive skill called e.g "Shield Fighter" that skill gives the player the Attribute "Shield" +1

on the shields requirement i set "Shield == 1"

this is my skill:
https://gyazo.com/01e11fb7bf546c90440664831850ba6b

this the item:
https://gyazo.com/9c68cb1a5bdf7e8c0afeb405facba454

**Comment by moepi2k** [comment]
maybe attributes that should increased over skills will not apply right?
but on item descrpition it looks it is -> Shield 1/1
https://gyazo.com/06f7664f516227fd51922572b8926ddb -> this is descrption of the item

i tested item requirement over standard attribute (that not applied over a skill) and your right it works in that way. 

so what can be the issue here?

**Comment by insthync** [comment]
Okay, I will change passive skill's buff to be included to check requirement.

**Comment by moepi2k** [comment]
alright,

but actually functionswise there is a bug in code right now. because the passive skill increase the attribute which the item will check for attribute and that is not working.

so maybe better fix that or remove it, else other will also confronted with it when they use increase attribute over passive skills

**Comment by insthync** [comment]
It met in UI. not in equipping function.

**Comment by insthync** [comment]
Fixed

**Comment by moepi2k** [comment]
cool thx :)
