### ISSUE TITLE
[Bug]DB

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#894]
sorry for spaming reports ^^

but alot of issues now.

when i click play i always got this error
https://gyazo.com/7f389add68335c7e2270a02bdbfa368c

in this case its an npcs that its not in db, but it is.
sometimes i got it for building parts.
then i need to remove it from db list
after add it again it works, then close and open unity again, i got same error again.

never had this before and i nothing changed.

the only way to fix it and to play is to remove that one
https://gyazo.com/871981864b697227526c65227894e462

its the default one with npc on map001, never changed something there or added something.
so dont know why this error occure now

**Comment by insthync** [comment]
I didn't changes anything relates to npc database too, which Unity version are you using?

**Comment by moepi2k** [comment]
2019.4.23

**Comment by moepi2k** [comment]
this error makes me crazy. i cant start my project anymore.
today i updated back to 1.63h on my laptop. everything worked fine, then on my computer i start click play and always got this error:

MissingReferenceException: The object of type 'BuildingEntity_Damageable' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Component.GetComponent[T] () (at <7c9c9bc2498143d08e2e3c523ff86731>:0)
LiteNetLibManager.LiteNetLibBehaviour.get_Identity () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:99)
MultiplayerARPG.DamageableEntity.MultiplayerARPG.IGameEntity.get_Identity () <0x2b424d81b40 + 0x00052> in <fbd60d09ae3646538b14a034d3d6edd0>:0
MultiplayerARPG.GameInstance.AddGameEntity[T] (System.Collections.Generic.Dictionary`2[TKey,TValue] dict, T entity) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:1183)
MultiplayerARPG.GameInstance.AddManyGameEntity[T] (System.Collections.Generic.Dictionary`2[TKey,TValue] dict, System.Collections.Generic.IEnumerable`1[T] list) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:1174)
MultiplayerARPG.GameInstance.AddBuildingEntities (System.Collections.Generic.IEnumerable`1[T] buildingEntities) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:1077)
MultiplayerARPG.GameInstance.AddBuildingEntities (MultiplayerARPG.BuildingEntity[] buildingEntities) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:1072)
MultiplayerARPG.Item.PrepareRelatesData () (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Item/Item.cs:457)
MultiplayerARPG.GameInstance.AddGameData[T] (System.Collections.Generic.Dictionary`2[TKey,TValue] dict, T data) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:1162)
MultiplayerARPG.GameInstance.AddManyGameData[T] (System.Collections.Generic.Dictionary`2[TKey,TValue] dict, System.Collections.Generic.IEnumerable`1[T] list) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:1149)
MultiplayerARPG.GameInstance.AddItems (System.Collections.Generic.IEnumerable`1[T] items) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:786)
MultiplayerARPG.GameInstance.AddItems (MultiplayerARPG.BaseItem[] items) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:781)
MultiplayerARPG.GameDatabase.LoadData (MultiplayerARPG.GameInstance gameInstance) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Database/GameDatabase.cs:54)
MultiplayerARPG.GameInstance.Start () (at Assets/UnityMultiplayerARPG/Core/Scripts/GameInstance/GameInstance.cs:506)

in db nothing is empty, even on each building scriptable is a building prefab attached.

**Comment by insthync** [comment]
Prefab is not in the scene right?, Error told like an objects were destroyed before added to game instance's dictionaries
