### ISSUE TITLE
MonsterSpawnArea script spawns monsters off navmesh

### ISSUE THREAD

**Issue by vaughanb** [suriyun-production/mmorpg-kit-docs#895]
I have noticed that the MonsterSpawnArea script often spawns monsters above or below the navmesh, resulting in them either appearing under the map or floating in the air, not moving. This happens more frequently on terrain with some slope.

I have had some minor success with this by adding the following code to EntityFixedUpdate() in NavMeshEntityMovement.cs:

```         
            if (!CacheNavMeshAgent.isOnNavMesh)
            {
                Vector3 groundPosition;
                FindGroundedPosition(transform.position, 100f, out groundPosition);
                transform.position = groundPosition;
            }
```

However, I'm sure this is not the best way to fix this and it still doesn't appear to solve the problem in all cases. All the monsters are now on the terrain, but some still won't move. 

Any help you could provide would be appreciated!

**Comment by insthync** [comment]
I actually try to find ground position before spawn monsters with `NavMesh.SamplePosition` function, If it can't find ground it won't spawn. If it's spawned I think it's because it can hit nav mesh surface.

But when I uses `NavMesh.SamplePosition` area mask set to `areaMask`, you may try set `areaMask` in `NavMeshEntityMovement` -> `FindGroundedPosition` function.

**Comment by vaughanb** [comment]
I know the monsters weren't on the navmesh because I was getting errors saying they weren't. 

I'm not sure what the problem was, but I re-baked the navmesh with a higher smaller voxel size and that seems to have fixed it. I'll try your area mask solution if I run into it again.

Thanks!

**Comment by vaughanb** [comment]
I was wrong. The problem was still occurring after re-baking the navmesh. However, this code in EntityFixedUpdate() in  NavMeshEntityMovement appears to completely resolve it:

```
            if (!CacheNavMeshAgent.isOnNavMesh)
            {
                Vector3 groundPosition;
                FindGroundedPosition(transform.position, 100f, out groundPosition);
                CacheNavMeshAgent.Warp(groundPosition);
            }
```
Using Warp instead of setting the transport position seems to fix the problem I was having with the agents not moving. Not getting any errors now and all monsters are on the navmesh and moving correctly. 

Just figured I'd share in case it was useful to you or anyone else.

Thanks!
