### ISSUE TITLE
"isGrounded" behave glitchy

### ISSUE THREAD

**Issue by nakedfighter3d** [suriyun-production/mmorpg-kit-docs#896]
![isGrounded](https://user-images.githubusercontent.com/38335953/112929023-a8de8d00-90e5-11eb-9343-5b7fb3ee2814.gif)

Using out-of-the-box controller with minor adjustments _(not secure movement)_. After a couple of jumps in one place, **isGrounded** starts flickering.  It can be turned back to normal after some movement&jumps but with the next couple of jumps, it will flicker again. As you can see, the ground is 100% flat

**Comment by Fr-Coder** [comment]
Did you tried to change Movement Collider Adjustment on character?

**Comment by nakedfighter3d** [comment]
> Did you tried to change Movement Collider Adjustment on character?
I set up my collider accordingly to the character, it looks pretty regular. I didn't see any option named "Movement Collider Adjustment" tho

**Comment by insthync** [comment]
You may try change to use `CharacterControllerEntityMovement` instead of `RigidbodyEntityMovement`

**Comment by nakedfighter3d** [comment]
Thanks, `CharacterControllerEntityMovement` works much better!
