### ISSUE TITLE
Animator not switched to "Fall" correctly

### ISSUE THREAD

**Issue by nakedfighter3d** [suriyun-production/mmorpg-kit-docs#897]
![NotFalling](https://user-images.githubusercontent.com/38335953/112930933-3374bb80-90e9-11eb-81a1-bc0bd578d4d5.gif)
Transition from **Stand** to **Fall** use 2 conditions: **isGrounded**=false and **Exit Time = 0.25**
Unfortunately, this way it will not switch to Fall if you're using a long idle animation. I'm using ~6 seconds idle animation and it's almost no chance I will switch to Fall state from it. And if I remove the Exit Time condition - it will just randomly switch to Fall all the time even on a flat surface _(because of glitchy isGrounded check)_. Is there any solution that allows using long idle states?

**Comment by insthync** [comment]
Try change transition setting like this
![Screenshot_321](https://user-images.githubusercontent.com/2697550/112948329-2647e300-9162-11eb-9496-474a41ec0381.png)

**Comment by nakedfighter3d** [comment]
Oh, yes! Thanks, that's better, this way I can fall! It still stuck _(now in a different manner)_ when the **isGrounded** got flicker, but I suppose it's a different issue, right?
![isGrounded](https://user-images.githubusercontent.com/38335953/112949657-780f4f80-9107-11eb-8bc5-e4243b9a92e7.gif)

**Comment by nakedfighter3d** [comment]
Yeah, 7 of 10 jumps end with **isGrounded** glitch, so I have like first 0.5 sec of my idle pose starting over and over again :(

**Comment by insthync** [comment]
You may try change to use `CharacterControllerEntityMovement` instead of `RigidbodyEntityMovement`
