### ISSUE TITLE
Add Shooter Controller to downloadable demo for potential customers to try out.

### ISSUE THREAD

**Issue by MostHated** [suriyun-production/mmorpg-kit-docs#9]
Someone had asked to try out the shooter controller but said they didnt see it in the demo. Add Shooter Controller to downloadable demo for potential customers to try out.

**Comment by insthync** [comment]
Okay uploaded here
https://drive.google.com/open?id=1L9WZgg3eZLJt1X_EzLbkavXTkVRixqYU

**Comment by MostHated** [comment]
Perfect, thanks. : D I sent it over to the person who asked for it.
