### ISSUE TITLE
Digital Ocean server

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#900]
Hello, I followed each step indicated here
https://suriyun-production.github.io/mmorpg-kit-docs/#/dedicates/digitalocean
 and I get the following error

![Captura de pantalla 2021-03-30 195221](https://user-images.githubusercontent.com/45702662/113079014-8144fe80-9191-11eb-9b08-838768989efa.png)

![Captura de pantalla 2021-03-30 190616](https://user-images.githubusercontent.com/45702662/113075860-07aa1200-918b-11eb-99e7-94d8cb84d36d.png)

**Comment by insthync** [comment]
Please check that your database manager configs are correct or not. And did you start database manager when runs server (`-startDatabaseServer`)

**Comment by Blunnyn** [comment]
hi, I checked everything in the project. databasemanager is still correct even use the parameter (-startDatabaseServer) to start the server but it happens to me when I compile with the server build option activated
<img width="353" alt="Captura de Pantalla 2021-04-01 a la(s) 12 52 23" src="https://user-images.githubusercontent.com/45702662/113320646-1b6b8a80-92e9-11eb-9588-4997dd9fbe89.png">



Even for other platforms like mac I had to download this: https://github.com/insthync/UnityMultiplayerARPG_MMO/blob/main/Plugins/Grpc.Core/runtimes/osx/x64/grpc_csharp_ext.bundle

and there to run the server locally. But still with problems.

the same thing happened to me on windows.

**Comment by Blunnyn** [comment]
When I try to run the local server on mac I get frozen like this

<img width="768" alt="Captura de Pantalla 2021-04-01 a la(s) 13 14 28" src="https://user-images.githubusercontent.com/45702662/113323446-5622f200-92ec-11eb-9236-76e58e8f45eb.png">

**Comment by insthync** [comment]
Not sure when you set database management configs, did you use localhost or something? You should try set database management address to localhost.

I actually working remove GRPC and use my own networking solution.If you don't have to use it urgently, you may wait for the new 
version.

**Comment by insthync** [comment]
Try 1.64, if it's still not working, tell me later.
