### ISSUE TITLE
[Issue] BaseEquipmentEntity.weaponLaunchSoundEffects not used anywhere

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#902]
BaseEquipmentEntity.weaponLaunchSoundEffects dont seem to be referenced anywhere.

Not sure when the change was made, but with the latest updates the weapons dont play any sfx.

**Comment by insthync** [comment]
Set sfx in item data instead

![Screenshot_330](https://user-images.githubusercontent.com/2697550/113463607-014cbc00-9451-11eb-8b52-944969dd791a.png)
