### ISSUE TITLE
pvp is unplayable in mmo 

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#903]
its very important to fix this .. cos its very bad with shooter ( test it please and check )

**Comment by insthync** [comment]
How is unplayable?, it can't shoot an opponent?

**Comment by RunOrDi3** [comment]
Lag compensation mechanics, problem in mmo is, when you aim and shoot other players and hit them in view of client, the hit will sometime (70%) not registered by server because server pos is already on new position.
Also server auth movement not correct position sometimes after attacking.

**Comment by insthync** [comment]
I am going to implement it, it has hitboxes, has to add clients RTTs, I am working on shooter game too, but it wouldn't works with `MissileDamageEntity` because I don't know how should I rewind it.

**Comment by RunOrDi3** [comment]
@insthync sounds good , i will be waiting

**Comment by moepi2k** [comment]
That are very good news, i also think missiledamageentity is nlt a good way to go since unity has problem detecting collider for fast projectiles, better use raycast with balistic and flytime. Is there a est when u want start implementing RTT? @insthync

**Comment by moepi2k** [comment]
https://twoten.dev/lag-compensation-in-unity.html

Very cool article about lag compensation, also the link in it from http://www.gabrielgambetta.com/lag-compensation.html

I hope this can help you a bit
