### ISSUE TITLE
Hurt animation not playing (1.63h)

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#905]
![aaaaaaa3](https://user-images.githubusercontent.com/4920405/113513241-9c808700-9560-11eb-9d6e-e67d926e4375.PNG)
Hurt animation not playing
Also, you misspelled Landed as Lnaded in weapon animations

 (1.63h)

**Comment by isaanyoha** [comment]
![aaaaaaa5](https://user-images.githubusercontent.com/4920405/113513271-cf2a7f80-9560-11eb-9c8f-58310b528fae.PNG)
Picture of misspelled Landed

I don't know if it is the reason why the hurt animation has refused to work when the other animations are working effortlessly

Please assist me with a clue if the reason is coming from me. Thanks @insthync!

**Comment by insthync** [comment]
I will fix it.

**Comment by isaanyoha** [comment]
Ok @insthync. I will be waiting

**Comment by insthync** [comment]
Fixed in 1.64

**Comment by isaanyoha** [comment]
Thanks man!
