### ISSUE TITLE
Problem where player does the attack and then rotates the body to the enemy.

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#907]
![Screenshot_245](https://user-images.githubusercontent.com/12781104/114141792-4fd5dc80-98cf-11eb-925c-8dbc75227f1d.png)

AFTER ATTACK PLAYER ROTATES TO ENEMY
Cant solve this problem. I have looked in all the attack code in the player input code and didnt find where to add a turn rotation to player.

**Comment by insthync** [comment]
I've fixed it, please wait the next version

**Comment by MosesGomez** [comment]
> I've fixed it, please wait the next version

Hey, if there is no problem. Which script should I update? Because that I dont want to make big update. Just that part. Please :D

**Comment by insthync** [comment]
RigidbodyEntityMovement2D

**Comment by MosesGomez** [comment]
> RigidbodyEntityMovement2D

![Captura](https://user-images.githubusercontent.com/12781104/114589349-d1699980-9c44-11eb-80b0-cabe809fae52.PNG)
I just have this error left, I think I have updated the right files but this error in just IGameEntityComponent. And I have deleted it and re import it and keeps the error. What should I do?

**Comment by insthync** [comment]
Imports 
- `Core\Scripts\Gameplay\Interfaces\IGameEntityComponent.cs` 
- `Core\Scripts\Gameplay\BaseGameEntityComponent.cs`
- `Core\Scripts\Gameplay\BaseNetworkedGameEntityComponent.cs`

**Comment by MosesGomez** [comment]
> Imports
> 
> * `Core\Scripts\Gameplay\Interfaces\IGameEntityComponent.cs`
> * `Core\Scripts\Gameplay\BaseGameEntityComponent.cs`
> * `Core\Scripts\Gameplay\BaseNetworkedGameEntityComponent.cs`

![Captura](https://user-images.githubusercontent.com/12781104/114643147-5c24b580-9c92-11eb-8121-57870d94cdcc.PNG)
After those updates. with the rb2dmovement script gives me those errors.

**Comment by MosesGomez** [comment]
![Captura](https://user-images.githubusercontent.com/12781104/114668570-24cbfe00-9cbe-11eb-82cd-3b79db6c699e.PNG)
Now all tells me for IEntityMovementComponent. But cant find it lol

**Comment by MosesGomez** [comment]
It seems that needs almost all updates.

**Comment by MosesGomez** [comment]
![Captura](https://user-images.githubusercontent.com/12781104/114685249-f0147280-9cce-11eb-8850-61853b107b7d.PNG)
After some more updated files got this 2

**Comment by MosesGomez** [comment]
At the end I updated all core scripts and allright. Now I test it but player still turns after hit.

**Comment by MosesGomez** [comment]
Keeps happening to me and also now if I set my player to player layer wont receive damage. So I set the player at character layer And my projectiles collides with my player and got this error.
![Captura](https://user-images.githubusercontent.com/12781104/115629096-e7b7cb00-a2be-11eb-8759-13db914dabff.PNG)

**Comment by MosesGomez** [comment]
Uploading Prestige2D.1 - Instances - Android - Unity 2020.1.6f1 Personal [PREVIEW PACKAGES IN USE] _DX11_ 2021-04-21 16-31-22.mp4…

**Comment by MosesGomez** [comment]
https://user-images.githubusercontent.com/12781104/115629387-7debf100-a2bf-11eb-953d-1720c6b3c186.mp4

**Comment by insthync** [comment]
Try 1.65
