### ISSUE TITLE
Fractional skill points earned each level instead of whole digit

### ISSUE THREAD

**Issue by gordowebdesign** [suriyun-production/mmorpg-kit-docs#908]
We were thinking to have 1 skill point per 4 levels but currently we can only use int value, could this be changed to float?

**Comment by Fallen01** [comment]
I just fixed this for my game with a quick and dirty netfunction, but yes this should be a built in feature. It was kinda annoying to discover that i was restricted to 1 skill point per level or higher.

**Comment by insthync** [comment]
Okay, I can change it

**Comment by insthync** [comment]
Did it in 1.65d
