### ISSUE TITLE
Auction and in-game mail

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#91]
This needs to be done:
1. Auction.
2. In-game mail with the ability to send items.

But how was the exchange of objects between the players supposed?

**Comment by insthync** [comment]
You can exchange with another player by move your character near another character then press `E` button

**Comment by Serivatech** [comment]
Probably fun to trade like that :)

**Comment by insthync** [comment]
About `Auction` and `In-game mail`, I've added to TODO, I will do it later

https://trello.com/b/u8UU1vML/mmorpg-kit-roadmap

**Comment by insthync** [comment]
Move this talks to https://github.com/suriyun-production/mmorpg-kit-docs/issues/671
