### ISSUE TITLE
[Question] Which area of code do I ext to enable custom respawn map & position died character respawning?

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/mmorpg-kit-docs#912]
What I mean is that I do not want that my character must reappear on the same map & position where it died, I want to be able to respawn to any map by custom conditions (example: respawn on a selected map if certain conditions are met, or to just randomly respawn the character to any map). I will be glad if you answer this

**Comment by insthync** [comment]
You can extends `BaseMapInfo` class and changes `GetRespawnPoint` functionality

**Comment by isaanyoha** [comment]
Ok, Thanks @insthync!

**Comment by insthync** [comment]
You should try to create your own class which implements `IServerCharacterHandlers` (You can copy `DefaultServerCharacterHandlers` to create yours) then in function `Respawn` you can use `option` to teleport to selected map

**Comment by isaanyoha** [comment]
Ok, Thanks so much @insthync! I appreciate

**Comment by isaanyoha** [comment]
Hi! @insthync! Where, in the *Respawn* method, do I put in the *option* variable to enable the teleport
