### ISSUE TITLE
Update existing project t 1.64

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#913]
hello, i updated my project from 1.63h to 1.64

now i got some issues when i run init scene (even the original one)

it thros this error:

https://gyazo.com/0643682cdae902924a0a85de2ff751be

any ideas?

**Comment by moepi2k** [comment]
expoirt/import my custom project folder fixed the problem.. annyoing unity bug

**Comment by moepi2k** [comment]
ok now i got it again and export import my custom folder not working.... it always has something todo with the GameInstance Object. when i click on the error it mark that object. but i dont know what it is.

again something with pooling system like last time, but what and why?

**Comment by moepi2k** [comment]
https://gyazo.com/bf2714b55be7f622dc844ebcc1c9a2a5

**Comment by insthync** [comment]
Try covering it with null check 

```
if (poolingWeaponLaunchEffects != null)
{
...
}
```

I found that sometimes array or list is null if their data does not set (array or list size is 0)

**Comment by moepi2k** [comment]
i will try,
but the problem is i dont changed anything in game. this db errors occure random. it works well then i just restart unity and i have this issue. it happens also to other db entries like
https://gyazo.com/b0eca81091d196019a91f7151915beaf
https://gyazo.com/c3066eac6db1f7d883cc44140889eb09

then i need to go in db end remove the entry and add it again or sometimes replace the prefab on scriptable
like
https://gyazo.com/da509899661a4e824cd1d8731b57832f

its very annoying issue

**Comment by insthync** [comment]
You may try delete `Library` folder, then when open Unity it will re-import all assets, it might be a problem with Library reference.

**Comment by moepi2k** [comment]
already tried multible times, always same issue, i figure out when i put my custom folder with all my data into UnityMultiplayerARPG folder it works. but the question is why

**Comment by moepi2k** [comment]
already tried multible times, always same issue, i figure out when i put my custom folder with all my data into UnityMultiplayerARPG folder it works. but the question is why
