### ISSUE TITLE
Chat Issue

### ISSUE THREAD

**Issue by LordPhrozen** [suriyun-production/mmorpg-kit-docs#914]
Clean fresh install
-Set to SQLite
-Changed client connection to connect to LAN server

Type in chat, hit enter, no chat displayed.

Build settings include the 4 scenes
mmo init, mmo home, map001, map002

Noticed this on most recent version, and 1 version back, if it existed before that im uncertain.

**Comment by insthync** [comment]
As I test it still have chat messages displayed, if it does not appear on other clients, characters distance may be over local chat distance setting

![Screenshot_370](https://user-images.githubusercontent.com/2697550/115052165-d1e58700-9f07-11eb-89db-cc2f6ac5e403.png)

**Comment by LordPhrozen** [comment]
unedited server, other than what i listed, client connecting from unity editor. No other clients present. No chat displayed.

**Comment by LordPhrozen** [comment]
I still dont know what the cause was here. likely a port issue, but i was unable to confirm, and its working now. closing. sorry for the trouble.
