### ISSUE TITLE
[Improve] Allow rotate BuildingEntity in Socket (BuildingArea)

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#918]
I have a pillar that can be rotated in a socket.
Can you add the option to rotate Building Entities when being placed in a BuildingArea?

One way to do this:

add:
  public bool allowRotateInSocket;
to BuildingArea

add:
 public float BuildYRotation { get; set; }
to BuildingEntity

set:
  ConstructingBuildingEntity.BuildYRotation = buildYRotate;
in 
   ShooterPlayerCharacterController.UpdateBuildAimControls(...)

add:
   if (BuildingArea.allowRotateInSocket) {
     CacheTransform.localEulerAngles = new Vector3(CacheTransform.localEulerAngles.x, CacheTransform.localEulerAngles.y + BuildYRotation, CacheTransform.localEulerAngles.z);
    }

inside BuildingEntity.EntityUpdate(...) after
     CacheTransform.position = BuildingArea.transform.position;
     CacheTransform.rotation = BuildingArea.transform.rotation;

**Comment by moepi2k** [comment]
Make sense, good point

**Comment by insthync** [comment]
Thank you.

**Comment by insthync** [comment]
Added to 1.65
