### ISSUE TITLE
In-game purchases

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#92]
Hello! 
Is it possible to add in-game purchases for a single player game?

**Comment by insthync** [comment]
Yes, it's possible

**Comment by DimasjkTV** [comment]
> Yes, it's possible


I don’t want to seem naive, can this be expected in the near future? or maybe some changes to the code are enough? =)

**Comment by DimasjkTV** [comment]
and another question, in order to create a purchase item, do I need to additionally use some kind of script? Or just enter the item ID in google console.

**Comment by insthync** [comment]
Done, next version it will be able to do IAP stuffs for offline games.

Purchasing system requires Unity Purchasing, Product Id from Google Play store

**Comment by DimasjkTV** [comment]
> Done, next version it will be able to do IAP stuffs for offline games.
> 
> Purchasing system requires Unity Purchasing, Product Id from Google Play store

Usually, an ID was assigned to the button with the purchase of an item, which fits into the Google console in creating the price. This has its own system. We cannot assign different IDs to different subjects. So what needs to be entered in google console?

> Done, next version it will be able to do IAP stuffs for offline games.
> 
> Purchasing system requires Unity Purchasing, Product Id from Google Play store

Usually, an ID was assigned to the button with the purchase of an item, which fits into the Google console in creating the price. This has its own system. We cannot assign different IDs to different subjects. So what needs to be entered in google console?

**Comment by insthync** [comment]
You have to create `Managed Product` in Google Play Console

![Screenshot_122](https://user-images.githubusercontent.com/2697550/67285929-a5af9c80-f502-11e9-8ecd-6e6fbb0e0e0c.png)

Then copy the id to set to cash package

![Screenshot_120](https://user-images.githubusercontent.com/2697550/67286038-db548580-f502-11e9-8a72-8e323fd566ba.png)

![Screenshot_121](https://user-images.githubusercontent.com/2697550/67286044-de4f7600-f502-11e9-8fd1-a400cc347131.png)

If there is no IAP catalog button in cash package, you have to add `ENABLE_PURCASING` to scripting define symbols

![Screenshot_119](https://user-images.githubusercontent.com/2697550/67286122-08089d00-f503-11e9-9a44-dc241aa36119.png)

**Comment by DimasjkTV** [comment]
> You have to create `Managed Product` in Google Play Console
> 
> ![Screenshot_122](https://user-images.githubusercontent.com/2697550/67285929-a5af9c80-f502-11e9-8ecd-6e6fbb0e0e0c.png)
> 
> Then copy the id to set to cash package
> 
> ![Screenshot_120](https://user-images.githubusercontent.com/2697550/67286038-db548580-f502-11e9-8a72-8e323fd566ba.png)
> 
> ![Screenshot_121](https://user-images.githubusercontent.com/2697550/67286044-de4f7600-f502-11e9-8fd1-a400cc347131.png)
> 
> If there is no IAP catalog button in cash package, you have to add `ENABLE_PURCASING` to scripting define symbols
> 
> ![Screenshot_119](https://user-images.githubusercontent.com/2697550/67286122-08089d00-f503-11e9-9a44-dc241aa36119.png)

Damn. I followed this picture and because of this I did not have functions. Now everything is clear. Thanks!
![image](https://user-images.githubusercontent.com/47291794/67294935-26fd3400-f4ef-11e9-8e79-2aa9e3aeb07f.png)
