### ISSUE TITLE
item & spells

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#920]
Hello, you could add extra features to spells or weapons such as lifesteal, or stun, etc.

**Comment by insthync** [comment]
For stun, you can tick on 
`disallowMove`
`disallowAttack`
`disallowUseSkill`
`disallowUseItem`
in Skill -> debuff

Now there is no lifesteal skill yet, but I has hpLeechRate in CharacterStats in 1.65f

**Comment by gordowebdesign** [comment]
is there a way to reflect damage or spell damage?

**Comment by insthync** [comment]
There is no way to reflect damage without code changes yet

If you can coding, you may modify codes `DefaultGameplayRule` -> `RandomAttackHitOccurs` to reflect damage to `attacker`
