### ISSUE TITLE
Crafting Formulars filter by Category missing

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#921]
could it be thats not possible to filter by category for the new formula crafting system like for skills for example?
on the formulas there is the field Category
https://gyazo.com/455db7a6d184b7c571457119f48840f8

but i cant find any script to set filter name like this for skills:
https://gyazo.com/9c284472a26f2c55ce8ffd773356d1a9

is this missing or how should it work?

**Comment by insthync** [comment]
`ItemCraftFormula` is part of new item crafting system which is not part of skill anymore, it will be listed and show in `UIItemCraftFormulas`.

I've added `filterCategories` to `UIItemCraftFormulas` it will be included in the next version.

**Comment by moepi2k** [comment]
Great thx for info
