### ISSUE TITLE
1.64 - lastDeadTime missing from DDL script

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#923]
This field lastDeadTime is currently missing in the ddls script.  Could you add it?
![image](https://user-images.githubusercontent.com/55019005/115932450-49c62b00-a48d-11eb-8641-c9123b94bcb8.png)

If it isn't nullable it should be added into the CreateCharacter method (mysql) because it's currently missing.
thanks

**Comment by insthync** [comment]
Its default value is 0 so when insert its value will be 0, it was defined in migrate script (in MySQLDatabase -> migrationID = 1.63b)
