### ISSUE TITLE
Update from 1.62 to 1.64

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#925]
After the update, I got a lot of similar errors. Do i need to remove something? Updated fresh project 1.62 to 1.64.
![image](https://user-images.githubusercontent.com/47291794/116046737-0aa9fc80-a67c-11eb-8240-c7f3c22b05c5.png)

**Comment by nakedfighter3d** [comment]
I got the same result with "updating". But full asset delete and clean install helped.

**Comment by DimasjkTV** [comment]
> I got the same result with "updating". But full asset delete and clean install helped.

this is not an option because I need to update my main project.

**Comment by insthync** [comment]
I've changed MMO -> database server, you can delete 
- MMO\Plugins\Google.Protobuf folder
- MMO\Plugins\Grpc.Core.Api folder
- MMO\Plugins\Grpc.Core folder
- MMO\Scripts\ProtoFiles folder
- MMO\Scripts\MMOGame\Database\DatabaseManagerClient.cs
- MMO\Scripts\MMOGame\Database\DatabaseManagerServer.cs 
- MMO\Scripts\MMOGame\Database\DatabaseServiceImplement.cs
- MMO\Scripts\MMOGame\Database\DatabaseServiceUtils.cs

May have other files to delete :P

**Comment by DimasjkTV** [comment]
> * DatabaseServiceUtils

Only this now 
![image](https://user-images.githubusercontent.com/47291794/116057788-d1778980-a687-11eb-9766-4b960805b2f6.png)

**Comment by insthync** [comment]
Delete it (`uicraftingitemselectionmanager`) too

**Comment by DimasjkTV** [comment]
> uicraftingitemselectionmanager

also
UiCraftingItems
and
DefaultServerOnlineCharacterHandlers

Thank you! =)
