### ISSUE TITLE
RootMotion logic inconsistency

### ISSUE THREAD

**Issue by nakedfighter3d** [suriyun-production/mmorpg-kit-docs#927]
I'm trying to build a RootMotion controller and it looks like some logic inconsistency or I missed something. 

Let's say I have a walking animation with RootMotion, so it has its own speed. To drive character with this particular animation I need to set player Entity Move Speed to zero or otherwise, my character speed will be a sum of RootMotion speed AND entity speed. So I set player base stat speed = 0 and it works perfectly fine on walking/running. But there is no way to handle the "jump".

**Jumping without RootMotion** isn't working because of zero entity speed. No matter how fast you run, as soon as you leave the ground - you'll just jump in one place.  You didn't inherit speed from the previous movement and can't move in the air.
**Jumping with RootMotion** is impossible because  Jump setting on the animator model has only one __Jump animation and doesn't have its own blendtree. So I can't blend between "jump in place/jump forward". 

So how can I use RootMotion movement with jumping?

**Comment by nakedfighter3d** [comment]
As far as I understand, it could be two ways of solving this: 
1. use separated speed in basic stats for the grounded and flying state. So it could move in the air without rootmotion. 
2. use the same kind of blend-tree for **Jump** and **Fall** as we using for Walk/Run

**Comment by nakedfighter3d** [comment]
Thanks for fixing root motion sync movement in 1.65b! But we still didn’t have a working jump while using rootmotion movement.

**Comment by nakedfighter3d** [comment]
Jump&fall  works only in place. Only Y axis. You can't move while airborne because your speed is 0.

**Comment by insthync** [comment]
Your root motion jump and fall hasn't move forwarding right?, So don't set move speed to 0 and also uncheck `useRootMotionForAirMovement`

**Comment by nakedfighter3d** [comment]
Yes, thanks! I think I'll manage it.

**Comment by insthync** [comment]
I will do it.
