### ISSUE TITLE
ShooterController rotation+action bug

### ISSUE THREAD

**Issue by nakedfighter3d** [suriyun-production/mmorpg-kit-docs#928]
Hey! Looks like there is an issue in ShooterController when you use a skill while rotating a camera.  

**Case 1.** You rotating a camera and during rotation, press LMB to hit. The character doesn't hit but starts rotating together with the camera. Only when you stop the camera rotation - the hit animation will happen.
![PreRotation](https://user-images.githubusercontent.com/38335953/116074615-feb04180-a65f-11eb-97ae-4d7d9ee1140c.gif)

Case 2. You press LMB and the character starts hitting animation. If you start rotating the camera during the hit animation - the character will be rotating together with the camera, facing the camera direction. He will be rotating as long as you rotate the camera without pause disregarding the animation end.  
![PostRotation](https://user-images.githubusercontent.com/38335953/116075183-a0379300-a660-11eb-97f7-5cbb1c9102c9.gif)

I suppose that boolean `TurnForwardWhileDoingAction` on `ShooterPlayerCharacterController` should somehow affect this behaviour, but seems like it just doing nothing.

**Comment by insthync** [comment]
In the first gif it turning to camera forwarding but it's too slow so it doesn't start an attack, I may fix it by change turning by speed to turn by calculated time.

**Comment by insthync** [comment]
In the second gif, it's what I intended to do it turn to camera forward while doing an action.

**Comment by insthync** [comment]
As I try, it's not better, So I think just adjust `turnSpeedWileDoingAction` to a higher value is a better way.

**Comment by nakedfighter3d** [comment]
Maybe it will be better not to turn a character to the camera while doing the action?

**Comment by insthync** [comment]
It should turn because when attack character should aim at where the crosshair pointing to

**Comment by Sour-J** [comment]
i have the same issue, but does changing turnSpeedWileDoingAction fix it?

**Comment by insthync** [comment]
Yeah you should try
