### ISSUE TITLE
[Bug]AudioSourceSetter

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#929]
there might be a bug with the audio source setter.

i spawned 300 harvestables on a map. my ping in editor went down from 60 to 10. when i disable audio source setter pings go up to 45-50.

also weird is when i set GridVisiblechecker to e.g 10 and only 10-15 trees around me are visible and all other 290 are invisible i still have low fps.

-> p.S checked GridVisibleChecker a bit more. When i set Value from 80 to 10 on a Harvestable for example. then it does not "cull" the object when player is out of that range. it seems that the Value on the GridVisibleChecker only on the player self works to "cull" all objects around.

i remember it was diffrent in older version. is something changed? and why then is there a GridVisibleChecker on othe entities when it not works?

**Comment by insthync** [comment]
About audio source setter issue, try change `AudioSetting.cs` codes to https://github.com/insthync/unity-audio-manager/blob/master/Scripts/AudioSetting.cs

About GridVisibleChecker, please wait for the next version, I have changes networking interest management system.
You can see changes in 
- https://github.com/insthync/LiteNetLibManager
- https://github.com/insthync/LiteNetLib-SuperGrid2D-Integration

**Comment by moepi2k** [comment]
Great the audioSetting changes fixed the problem. Fps now stable :)
