### ISSUE TITLE
1.49с BUG sockets

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#93]
Bonus from gems in items does not work.

**Comment by DimasjkTV** [comment]
> Bonus from gems in items does not work. Single player game and MMO

**Comment by insthync** [comment]
Fixed, thanks for your report, how to fix it:

In `CharacterDataExtension.cs` line 497
Changes codes from:
```
if (!data.EquipWeapons.NotEmptyRightHandSlot())
```
To
```
if (data.EquipWeapons.NotEmptyRightHandSlot())
```
And line 510
Changes codes from:
```
if (!data.EquipWeapons.NotEmptyLeftHandSlot())
```
To
```
if (data.EquipWeapons.NotEmptyLeftHandSlot())
```

**Comment by DimasjkTV** [comment]
> Fixed, thanks for your report, how to fix it:
> 
> In `CharacterDataExtension.cs` line 497
> Changes codes from:
> 
> ```
> if (!data.EquipWeapons.NotEmptyRightHandSlot())
> ```
> 
> To
> 
> ```
> if (data.EquipWeapons.NotEmptyRightHandSlot())
> ```
> 
> And line 510
> Changes codes from:
> 
> ```
> if (!data.EquipWeapons.NotEmptyLeftHandSlot())
> ```
> 
> To
> 
> ```
> if (data.EquipWeapons.NotEmptyLeftHandSlot())
> ```

Thank you!
