### ISSUE TITLE
[Improve] Add ItemCraftFormulas to Workbench

### ISSUE THREAD

**Issue by rasto61** [suriyun-production/mmorpg-kit-docs#930]
Since there is the new ItemCraftFormula data, do you think it would be worth it to add ItemCraftFormula[] to Workbench entity?
So that the Workbench can work with the ItemCraftFormula (in addition to ItemCraft(s) individually).

**Comment by insthync** [comment]
Added `QueuedWorkbenchEntity` in 1.65d, try it.
