### ISSUE TITLE
Scriptable Object on an Item to override the items normal bonuses

### ISSUE THREAD

**Issue by Fallen01** [suriyun-production/mmorpg-kit-docs#931]
Struggling with this, but I am trying to replace the items bonuses by SO. Any suggestions you could offer would be great.

**Comment by insthync** [comment]
I don't get what are you going to do?

You can set bonus here

![Screenshot_407](https://user-images.githubusercontent.com/2697550/116655995-1ff19480-a9b6-11eb-9a8b-36ee4c14a2f0.png)

Or are you going to add new kind of character stats ?

**Comment by Fallen01** [comment]
Im aware but lets so i want to drop an SO into the item and override that with the SO.

**Comment by Fallen01** [comment]
Making 1000s of items is way to much work sigh... I need to assign these values another way. I noticed equipment sets plug in as an SO so i figured why not use an SO, but im not sure how to get the item to use these values from it rather then the normal values youve got in red above.

**Comment by Fallen01** [comment]
![image](https://user-images.githubusercontent.com/57778639/116664057-edb84680-a965-11eb-8893-0ef2f5c4f63b.png)

**Comment by Fallen01** [comment]
trying to do something like this

**Comment by insthync** [comment]
Ahh, I see, to do that you may modify `BaseEquipmentItem.cs` class or `Item.cs` which has field for your scriptable object, then modify result in `IncreaseStats`, `IncreaseStatsRate`, `IncreaseAttributes`, `IncreaseAttributesRate`, `IncreaseResistances`, `IncreaseArmors`, `IncreaseDamages` and `IncreaseSkillLevels` properties

**Comment by Fallen01** [comment]
I already have the base item equipment part done and im constructing the new name of the item, but the part im having trouble with is this modify the result part can you show me a small example of what you mean?

**Comment by insthync** [comment]
```
        public BonusScriptableObject bonusSO;
        [SerializeField]
        private CharacterStatsIncremental increaseStats;
        public CharacterStatsIncremental IncreaseStats
        {
            get { return if (bonusSO) ? bonusSO.increaseStates : increaseStats; }
        }

        [SerializeField]
        private CharacterStatsIncremental increaseStatsRate;
        public CharacterStatsIncremental IncreaseStatsRate
        {
            get { return if (bonusSO) ? bonusSO.increaseStatsRate : increaseStatsRate; }
        }

```

**Comment by Fallen01** [comment]
so this would go into my scriptable?

**Comment by insthync** [comment]
In BaseEquipmentItem.cs or Item.cs

**Comment by Fallen01** [comment]
ahh ok so this is loading my scriptable from base item or item cs

**Comment by Fallen01** [comment]
I think I understand thank you for responding.

**Comment by Fallen01** [comment]
Is CharacterItem where items are saved and loaded from the DB, I notice you have a todo there for random ranges?
