### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#933]

**Comment by moepi2k** [comment]
There is a bug with harvestable types.

like you can see in video: https://gyazo.com/7622cf3b595dc7abe2774e765021ad8b
the spell only do fire dmg. but when i equip an axe for harvest wood and cast fireball on it it harvest it too with the spell

**Comment by insthync** [comment]
Haha, I will fix it.

**Comment by insthync** [comment]
In 1.65b, there are new updates
- Add `harvestType` and `harvestDamageAmount` settings to skill. If `harvestType` is `BasedOnWeapon`, harvest damage amount will be calculated by weapon type's `harvestDamageAmount` settings. If `harvestType` is `BasedOnSkill`, harvest damage amount will be calculated by skill's `harvestDamageAmount` settings.
- Add `skillHarvestEffectivenesses` to `Harvestable`, it will be used when skill's `harvestType` is `BasedOnSkill` to random dropping items when harvestable entity attacked.

You can set skill's `harvestType` to `None` to not applies damage to harvestable entity.
