### ISSUE TITLE
[BUG] 1.64 RootMotion server sync issues

### ISSUE THREAD

**Issue by nakedfighter3d** [suriyun-production/mmorpg-kit-docs#934]
Hey! I believe it was already mentioned, but since previous posts were closed without solving I'm willing to report that RootMotion sync didn't work in 1.64 as well. 

I'm using the character stat Move Speed as zero (or a very small value like 0.1) so I can get real rootmotion movement without added speed.  New CharacterControllerEntityMovement, ShooterController, Server Authoritative movement, asset version 1.64

Sometimes, the character stopped on a client but it continues to walk on a server. Then the client character starts just teleporting to cath the server position. Most of the time positions are out of sync dramatically. It works slightly better when I set bigger numbers to Move Speed  (like 2..3) but in that case, we lost the whole sense of having rootmotion.

Adventure movement
https://user-images.githubusercontent.com/38335953/116810302-0fa1fc80-ab11-11eb-8676-663902969560.mp4

Combat movement
https://user-images.githubusercontent.com/38335953/116811042-2cd8ca00-ab15-11eb-835a-db0b1d1b2732.mp4

**Comment by Fr-Coder** [comment]
I have a similar problem, using MoveSpeedWhileAttack > 0 the character go out of sync.

**Comment by moepi2k** [comment]
Yea there is also a sync issue without rootmotion. When movespeedratewhile attack is 0 and player walk then attack, player will stand still while attacking, but the position where pöayer stops is diffrent feom owner client to other clients, and server not correct possition. When movement is not secure after attack the server correct position (lile player drift the the servers position) thats missing with server auth on. 

Better would be that the drif (correction) happens while attacking and not after.

Seems the very last issue with csp i found so far. Hope suri will fix this @insthync

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.65b
