### ISSUE TITLE
AimAtCursorController

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#936]
if you check DoNotTurnToPointingEntity then there is a diffrence between aiming at mouse position.
-> when its checked, projectiles goes exactly where the mouse position is -> thats good.
but the problem is when the player stay for example on a bridge (0,5,0) and aims on the ground (0,0,0) the player rotation compared to mousepoisiton is not correct. it seem there is an offset
this line: https://gyazo.com/f96d4537d342a720d2c0f66467546710

and when DoNotTurnToPointingEntity us unchecked. Projecitles goes not exactly to mouse position. but the problem with  the offset is gone.

any idea?

**Comment by insthync** [comment]
This problem occurs from `BaseCharacterEntity` -> `GetAttackAimPosition` function, it will set aim position by target entity if it set. So I fix it by don't set target entity.

**Comment by moepi2k** [comment]
i made a video to see what i mean. look at the rotation of the player when he is on the slope 
https://gyazo.com/2e8b386412ef40644e6dd97aa6f3f68d
AimAtCursor position is wrong.

:)

**Comment by insthync** [comment]
Fixed, it's occurring because of wrong raycast hits ordering

**Comment by moepi2k** [comment]
ok i tested it. still bugged.

when doNotTurnToPointingEntity is checked, then rotation bug on diffrent Y vales is fixed, but then projectiles not goes to mouseposition there are an offset.

if doNotTurnToPointingEntity is unchecked projectiles goes exactly to mouse position but then you have the rotiation bug on Y values

**Comment by insthync** [comment]
Because it will fire forwarding from damage launch transform. So I add `setAimPositionToRaycastHitPoint` option, it this is turn on it will fire to raycast point position

**Comment by moepi2k** [comment]
ok still some weird behaviour xD

this video is with options 
doNotTurnToPointingEntity = OFF
setAimPositionToRaycastHitPoint = OFF
https://gyazo.com/6ecf6b885423260a22d36d2fae0f34a7

if player is on slope (higher Y postion) it take the rotation from the ground, so there are issue for lookto aim position.
but the projectiles goes to the mouse position (straight from missile transfrom. not changing Y direction like the new option setAimPositionToRaycastHitPoint. This option give strange behaviour because you shoot always in the ground so missile should go straight forward but to mouse position

and in that video is set with option
doNotTurnToPointingEntity = ON
setAimPositionToRaycastHitPoint = OFF

Look rotation is good on slope, but projectiles have an offset.

how to combine lookrotation fix of second one and projectile direction from first one?
https://gyazo.com/e79a3d909c6b7dda1879bb562252577b

**Comment by insthync** [comment]
I told you about offset, I can't make projectile move to the mouse position correctly because bullet will move forwarding from damage launch transform, character just turn to where cursor point on but it will not fire to the position where cursor point on while `setAimPositionToRaycastHitPoint ` is off.

**Comment by moepi2k** [comment]
Mh thats bad.  

But here projectile also move forward from damage launch transform and goes perfect to mouse position.

Is there a way to split shoot and rotation maybe? Because without you can only have maps that are completly flat with this controller.

**Comment by insthync** [comment]
About rotating on slope, I've fixed it.
