### ISSUE TITLE
Question MonsterSpawnArea

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#937]
hi i have a lil quesiton

i extend the MonsterSpawnArea script so that my monster only spawn at night.
i use the stuff from DefaultDayNightTimeUpdater for checking time. that works.

now to stop spawning enemies on day i do this
`protected override BaseMonsterCharacterEntity SpawnInternal(BaseMonsterCharacterEntity prefab, short level)
        {
            if (!isDay)
            {
                ...`

that also works. monster now not spawn anymore on day.
when i start server and its night monster spawns

but here comes to problem. when it switch to day and monster are killed and not respawning and then it switch to night. it also not respawns, because the respawn will be called on the monster.

i tried to use RespawnAll() when it switch to night, but then there spawns 2 enemies and one spawns as dead.

do you have an idea how to stop spawner and recontinue it?

**Comment by insthync** [comment]
You should see this as example https://github.com/insthync/UnityMultiplayerARPG_ScriptsOnDemand/blob/master/Scripts/QuestMonsterSpawnArea.cs

Add list to store spawned monsters then use the list to destroy monsters at day or night

```
        public bool IsDay { get { return false; /*Implement yours*/ } }
        private readonly List<BaseMonsterCharacterEntity> monsterEntities = new List<BaseMonsterCharacterEntity>();
        private bool spawnedMonstersAtNight;
        protected override void LateUpdate()
        {
            base.LateUpdate();

            if (!BaseGameNetworkManager.Singleton.IsServer)
                return;
            if (IsDay)
            {
                    if (monsterEntities.Count > 0)
                    {
                        for (int i = monsterEntities.Count - 1; i >= 0; --i)
                        {
                            monsterEntities[i].NetworkDestroy();
                        }
                        monsterEntities.Clear();
                    }
                    spawnedMonstersAtNight = false;
            }
            else
            {
                    if (spawnedMonstersAtNight) return;
                    spawnedMonstersAtNight = true;
                    SpawnAll();
            }
        }

        protected override BaseMonsterCharacterEntity SpawnInternal(BaseMonsterCharacterEntity prefab, short level)
        {
            if (IsDay)
            {
                // Spawn monster at night only
                return null;
            }
            BaseMonsterCharacterEntity spawnedMonster = base.SpawnInternal(prefab, level);
            if (spawnedMonster != null)
            {
                monsterEntities.Add(prefab);
                return spawnedMonster;
            }
            return null;
        }
```

**Comment by moepi2k** [comment]
great thank you very much, that helped alot.
one problem left:

when it switch from night to day and there are still monsters alive
monsterEntities[i].NetworkDestroy();
is called but monsters are not destroyed.

any idea?

**Comment by moepi2k** [comment]
I noticed that the networkdestroy also not work from the example script questmonsterspawnarea.ch

**Comment by insthync** [comment]
Okay, I will check it.

**Comment by insthync** [comment]
Oh, my codes wrong, in `SpawnInternal` function it's adding `prefab` to the list it must add `spawnedMonster`.

![Screenshot_443](https://user-images.githubusercontent.com/2697550/120554559-14b1de80-c424-11eb-91f4-b52760a4bfbc.png)

**Comment by moepi2k** [comment]
great, worked thank you :)
