### ISSUE TITLE
MMORPG 2D Erro

### ISSUE THREAD

**Issue by alexengel1992** [suriyun-production/mmorpg-kit-docs#938]
good evening I came to talk again about an error of mmorpg 2d in which a friend warning me that was already solved, more still happens to me

https://user-images.githubusercontent.com/83098223/116953427-9535c180-ac63-11eb-8130-07ecc671eebd.mp4

**Comment by insthync** [comment]
Try latest version (1.65)

**Comment by MosesGomez** [comment]
> Try latest version (1.65)

Hi suri, what should I import to get this fixed in the new version? :D

**Comment by alexengel1992** [comment]
100% THX
You are the best

**Comment by insthync** [comment]
> > Try latest version (1.65)
> 
> Hi suri, what should I import to get this fixed in the new version? :D

RigidbodyEntityMovement2D
