### ISSUE TITLE
ShooterController on mobile Issue

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#94]
Shooter cant attack with new fix in shooter controllor using mobile editor.
here is a video to show it.. 
https://www.youtube.com/watch?v=Lr9QKeHfaX0&feature=youtu.be

I fixed this by making the controllor check if its mobile inputs or not

Original code
![shooterProblem](https://user-images.githubusercontent.com/7702658/66717264-3e456e80-edd7-11e9-95cb-b87e3f5162cd.JPG)

and i changed it to this , This is working fine now
![ShooterFix](https://user-images.githubusercontent.com/7702658/66717268-49989a00-edd7-11e9-8525-4392294a0f3e.JPG)

**Comment by insthync** [comment]
Thank you

**Comment by Callepo** [comment]
np bro my pleassure
