### ISSUE TITLE
npc animations are bugged

### ISSUE THREAD

**Issue by RunOrDi3** [suriyun-production/mmorpg-kit-docs#941]
it not working over the animator character model -> default animations

**Comment by insthync** [comment]
Npc Entity, not an monster, right?

**Comment by RunOrDi3** [comment]
yes

**Comment by insthync** [comment]
If it has no other movement, you can set simple animator which has idle state as default state

**Comment by moepi2k** [comment]
In the animator state the npc always has the state fall and nkt idle, alsonthe default npcs
