### ISSUE TITLE
Little bug: inventory slots

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#942]
My character has 150 slots in her backpack. But the number of items lifted reaches up to 151/150. I think that after 150 items the items should not picked up into inventory. That is 150/150.
For example my current invetory is 
![image](https://user-images.githubusercontent.com/47291794/117472562-b3503a00-af61-11eb-916e-3b1a34d8d457.png)

I have loot in the ground like this
![image](https://user-images.githubusercontent.com/47291794/117472616-c19e5600-af61-11eb-9813-ad2b244c6ad0.png)

After click loot all i have in my inventory this
![image](https://user-images.githubusercontent.com/47291794/117472694-d549bc80-af61-11eb-95d3-9222c1dcc395.png)

all items was picked up but should pick up only 2 items not 5

**Comment by insthync** [comment]
Try use `IncreasingItemsWillOverwhelming` (extension function which is in `CharacterDataExtension` class) before increase items to inventory

Usage example:
```
BasePlayerCharacterEntity entity;
List<ItemAmount> increasingItems;
if (!entity.IncreasingItemsWillOverwhelming(increasingItems)) {
  // Add items
}
```

**Comment by DimasjkTV** [comment]
> Try use `IncreasingItemsWillOverwhelming` (extension function which is in `CharacterDataExtension` class) before increase items to inventory

I am using a weight system invetory slot (on screenshots) in my game, should this help?

**Comment by insthync** [comment]
Yes
