### ISSUE TITLE
Little Niggles 

### ISSUE THREAD

**Issue by benhamlett** [suriyun-production/mmorpg-kit-docs#943]
Layers for combat, arrows hitting etc are hard coded to "Character" etc layer. Letting us select these layers would help a lot when dealing with making the local player layer seperate for UX purposes. 

Sheath / Unsheath
I made a little addon that does this but honestly should be an option built in given the demand.

LL Documentation ( IMPORTANT ) 
I love to extend the system but in most cases I have to spend alot of time digging through the code to do so, documentation for advanced coders would be much appreciated.

NPCs
Should be able to walk, attack and have dialogues IMO 

Great framework :)

**Comment by Fallen01** [comment]
Decent suggestion!

**Comment by benhamlett** [comment]
> 
> 
> For the Documentation we can help him doing PR.

What do you mean mate?
