### ISSUE TITLE
Drop entity test

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#944]
I added 100 items to the monster that drop after it dies. I also increased the pickup radius to 150.
after kill a monster we have a lag during 1 second
300 items on ground and we have no FPS. Look at the video
[1 drop entity.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6446242/1.drop.entity.zip)
if we use pick up radius around 1-3 FPS is good.
Is it possible to do something so that items on the ground do not break performance so much if we have a large radius of pick up items?

**Comment by moepi2k** [comment]
i think its normal that you will have a fps drop when you instantiate 100 items at once.

**Comment by DimasjkTV** [comment]
> i think its normal that you will have a fps drop when you instantiate 100 items at once.

Yes, I also think it's okay, but maybe there is some way to improve it

**Comment by Gui205** [comment]
> > i think its normal that you will have a fps drop when you instantiate 100 items at once.
> 
> Yes, I also think it's okay, but maybe there is some way to improve it. I've seen single games where more than 1000 items could be displayed in the drop window and this did not affect the fps in any way. But it was a single player game.

With DOTS i guess yes
