### ISSUE TITLE
BUG: 1.65 mount

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#945]
If we use a mount and change weapons with a different animation on it, then this animation is activated on the mount and after we get off it. 
See video
[1.65 MOUNT bug.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6448040/1.65.MOUNT.bug.zip)

**Comment by sdk2016** [comment]
Yes, I also found a bug like that

**Comment by insthync** [comment]
Fixed in 1.65b
