### ISSUE TITLE
BUG: 165 

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#946]
![image](https://user-images.githubusercontent.com/47291794/117587844-9023b700-b128-11eb-8470-9ac9f6bd2597.png)
![image](https://user-images.githubusercontent.com/47291794/117587918-f4df1180-b128-11eb-98f9-7fa0805b9e1c.png)
![image](https://user-images.githubusercontent.com/47291794/117588092-fceb8100-b129-11eb-8b0e-938eda04fa4e.png)

Sometimes, after teleporting from one location to another, this error occurs. It creates endless copies of the character if you press the editor repause.

**Comment by moepi2k** [comment]
Noticed the also in 1.65

**Comment by insthync** [comment]
Please select the error message and copy its description, or you may try change codes following this https://github.com/insthync/LiteNetLib-SuperGrid2D-Integration/commit/3495d83229a3877bbbf086dde35eb2f695572056

**Comment by DimasjkTV** [comment]
> Please select the error message and copy its description, or you may try change codes following this [insthync/LiteNetLib-SuperGrid2D-Integration@3495d83](https://github.com/insthync/LiteNetLib-SuperGrid2D-Integration/commit/3495d83229a3877bbbf086dde35eb2f695572056)
![image](https://user-images.githubusercontent.com/47291794/117610841-14972980-b16b-11eb-8636-551eb12b407a.png)

Will test your fix

**Comment by DimasjkTV** [comment]
Still the same. I do not know why the full error description is not displayed in my console

**Comment by DimasjkTV** [comment]
Perhaps this is due to the fact that the monster in the previous location poisoned me with poison for 7 seconds. With this poisoning, I teleported to another location.

**Comment by DimasjkTV** [comment]
> Try 1.65b

still in last version

**Comment by DimasjkTV** [comment]
> Try 1.65b

this was not in the 1.62f version

**Comment by DimasjkTV** [comment]
> Try 1.65b

also after click on error 
![image](https://user-images.githubusercontent.com/47291794/118559958-6cd4b980-b771-11eb-9e10-03245aa5d929.png)

**Comment by DimasjkTV** [comment]
> Please select the error message and copy its description, or you may try change codes following this [insthync/LiteNetLib-SuperGrid2D-Integration@3495d83](https://github.com/insthync/LiteNetLib-SuperGrid2D-Integration/commit/3495d83229a3877bbbf086dde35eb2f695572056)

seems like this code works but not sure. I need more tests.

**Comment by insthync** [comment]
I don't get what is happening, please capture the video while playing and when problem occurs.

**Comment by DimasjkTV** [comment]
> I don't get what is happening, please capture the video while playing and when problem occurs.

yes i will try record it

**Comment by DimasjkTV** [comment]
> I don't get what is happening, please capture the video while playing and when problem occurs.

[bandicam 2021-05-18 14-11-40-937.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6500823/bandicam.2021-05-18.14-11-40-937.zip)

**Comment by DimasjkTV** [comment]
> I don't get what is happening, please capture the video while playing and when problem occurs.

i had old map info script lol. May be problem in this script. i am testing now

**Comment by DimasjkTV** [comment]
> > I don't get what is happening, please capture the video while playing and when problem occurs.
> 
> i had old map info script lol. May be problem in this script. i am testing now

Not in this =(

**Comment by insthync** [comment]
Still hard to find cause of error, try change Stack trace logging settings to see more info

![Screenshot_427](https://user-images.githubusercontent.com/2697550/118686020-d1ede500-b82d-11eb-9d96-12d5533fe7ee.png)

**Comment by DimasjkTV** [comment]
> Still hard to find cause of error, try change Stack trace logging settings to see more info
> 
> ![Screenshot_427](https://user-images.githubusercontent.com/2697550/118686020-d1ede500-b82d-11eb-9d96-12d5533fe7ee.png)

![image](https://user-images.githubusercontent.com/47291794/118687843-241f0e00-b80e-11eb-9876-c9f664790bfd.png)
still the same with full

**Comment by DimasjkTV** [comment]
oh wait 

NullReferenceException: Object reference not set to an instance of an object
MultiplayerARPG.BaseUISceneGameplay.PrepareCombatText (MultiplayerARPG.DamageableEntity damageableEntity, MultiplayerARPG.CombatAmountType combatAmountType, System.Int32 amount) (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Scenes/BaseUISceneGameplay.cs:65)
MultiplayerARPG.DamageableEntity.AllReceivedDamageFeedback (MultiplayerARPG.CombatAmountType combatAmountType, MultiplayerARPG.DamageSource damageSource, System.Int32 dataId, System.Int32 amount) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageableEntity.cs:168)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
LiteNetLibManager.LiteNetLibFunctionDynamic.HookCallback () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:219)
LiteNetLibManager.LiteNetLibFunction.SendCall (System.Byte dataChannel, LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Int64 targetConnectionId) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:86)
LiteNetLibManager.LiteNetLibFunction.Call (System.Byte dataChannel, LiteNetLib.DeliveryMethod deliveryMethod, LiteNetLibManager.FunctionReceivers receivers, System.Object[] parameterValues) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibFunction.cs:132)
LiteNetLibManager.LiteNetLibBehaviour.RPC (System.String methodName, System.Byte dataChannel, LiteNetLib.DeliveryMethod deliveryMethod, System.Object[] parameters) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:1486)
LiteNetLibManager.LiteNetLibBehaviour.RPC[T1,T2,T3,T4] (LiteNetLibManager.NetFunctionDelegate`4[T1,T2,T3,T4] func, System.Byte dataChannel, LiteNetLib.DeliveryMethod deliveryMethod, T1 param1, T2 param2, T3 param3, T4 param4) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:1216)
MultiplayerARPG.DamageableEntity.CallAllReceivedDamageFeedback (MultiplayerARPG.CombatAmountType combatAmountType, MultiplayerARPG.DamageSource damageSource, System.Int32 dataId, System.Int32 amount) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/DamageableEntity.cs:207)
MultiplayerARPG.CharacterRecoveryData.Apply (MultiplayerARPG.BaseCharacterEntity characterEntity, MultiplayerARPG.EntityInfo causer) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterSystems/CharacterRecoveryData.cs:54)
MultiplayerARPG.CharacterRecoveryComponent.EntityUpdate () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterSystems/CharacterRecoveryComponent.cs:43)
MultiplayerARPG.BaseGameEntity.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/BaseGameEntity.cs:418)

**Comment by DimasjkTV** [comment]
> Still hard to find cause of error, try change Stack trace logging settings to see more info
> 
> ![Screenshot_427](https://user-images.githubusercontent.com/2697550/118686020-d1ede500-b82d-11eb-9d96-12d5533fe7ee.png)

still the same  
![image](https://user-images.githubusercontent.com/47291794/118690256-8e38b280-b810-11eb-83be-216b59452d07.png)

**Comment by DimasjkTV** [comment]
> Still hard to find cause of error, try change Stack trace logging settings to see more info
> 
> ![Screenshot_427](https://user-images.githubusercontent.com/2697550/118686020-d1ede500-b82d-11eb-9d96-12d5533fe7ee.png)

![image](https://user-images.githubusercontent.com/47291794/118690817-1a4ada00-b811-11eb-8f78-920d48d387e4.png)

**Comment by moepi2k** [comment]
The issue after warping map, then stuck in loading screen while create endless copies of player is rarely, i got it since 1.65 too and cant find how to recreate, its random

**Comment by insthync** [comment]
@DimasjkTV May I try by TeamViewer ?

**Comment by DimasjkTV** [comment]
> @DimasjkTV May I try by TeamViewer ?

sure

**Comment by insthync** [comment]
Send me your team viewer info to ittipon.bay@gmail.com

**Comment by insthync** [comment]
Fixed in 1.65e
