### ISSUE TITLE
SUGG: Max skill points

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#948]
Limit the maximum number of skill points at character. For example, a character gets 1 skill point every level. The maximum level is 1000. But I want the character to have a maximum of 200 skill points. That is, so that after level 200 skill points are not credited.
Maybe here
![image](https://user-images.githubusercontent.com/47291794/117807306-23add280-b264-11eb-8a7e-848d5a9ce735.png)

**Comment by insthync** [comment]
In 1.65c

- Add `increaseStatPointsUntilReachedLevel` to `DefaultGameplayRule`, If this > `0`, it will increase stat point until character reached max level. If it's `20`, it will increase stat point until character reached level `20`.
- Add `increaseSkillPointsUntilReachedLevel` to `DefaultGameplayRule`, If this > `0`, it will increase skill point until character reached max level. If it's `20`, it will increase skill point until character reached level `20`.

**Comment by DimasjkTV** [comment]
> In 1.65c
> 
> * Add `increaseStatPointsUntilReachedLevel` to `DefaultGameplayRule`, If this > `0`, it will increase stat point until character reached max level. If it's `20`, it will increase stat point until character reached level `20`.
> * Add `increaseSkillPointsUntilReachedLevel` to `DefaultGameplayRule`, If this > `0`, it will increase skill point until character reached max level. If it's `20`, it will increase skill point until character reached level `20`.

Thank you!
