### ISSUE TITLE
SUGG: Weapons on mounts

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#949]
Hide weapons or ability to change the position of the weapon behind the back if we on mounts. Maybe this already in the Kit?

**Comment by insthync** [comment]
In 1.65c

- Add `activateObjectsWhenSwitchModel` to `BaseCharacterModel`, these game objects will be activated when switch from other model (switching when riding vehicles).
- Add `deactivateObjectsWhenSwitchModel` to `BaseCharacterModel`, these game objects will be deactivated when switch from other model (switching when riding vehicles).

**Comment by DimasjkTV** [comment]
> In 1.65c
> 
> * Add `activateObjectsWhenSwitchModel` to `BaseCharacterModel`, these game objects will be activated when switch from other model (switching when riding vehicles).
> * Add `deactivateObjectsWhenSwitchModel` to `BaseCharacterModel`, these game objects will be deactivated when switch from other model (switching when riding vehicles).

Thank you!
