### ISSUE TITLE
SUGG: Add attributes event

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#953]
is it possible to add a choice of how many points we can add in 1 click? For example, so that the player could, when clicking on 1 click, add 5 or more points at once, instead of clicking 5 or more times.
![image](https://user-images.githubusercontent.com/47291794/117931262-a5a30780-b307-11eb-8d64-b0e82f31bb51.png)
In Diablo 3, for example, this is implemented as follows:
- Standard click = 1 point
- Pressed shift + click = 5 points
- Pressed ctrl + click = 100 points
This solution is good for a PC.
For mobile devices, I think it would be enough to add two buttons. One button is worth 1 point for 1 click. The second button is for example 10 points for 1 click.

**Comment by insthync** [comment]
I won't do it, You can create a new component which has functions which call `OnClickAdd` function multiple time.
