### ISSUE TITLE
1.65c Mount situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#954]
When the character deactivates the mount, the screen jerks.
Look at the video
[Mount 1.65c.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6464356/Mount.1.65c.zip)

**Comment by insthync** [comment]
Because it is falling from seat which a bit higher than the ground, I actually try to teleport to the grounded position but it still falling, don't know why.

**Comment by DimasjkTV** [comment]
> Because it is falling from seat which a bit higher than the ground, I actually try to teleport to the grounded position but it still falling, don't know why.

This was not in version 1.62f

**Comment by DimasjkTV** [comment]
How it is in 1.65c
[Mount 1,65c.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6467240/Mount.1.65c.zip)

How it was in 1.62f (i think "F")
[1.62f.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6467270/1.62f.zip)

The camera twitched, but not as much
