### ISSUE TITLE
increaseSkillPointsUntilReachedLevel

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#955]
It works very strangely. I set the value to 10. My character did not receive skill points until level 10, and after 11 he began to receive. Although he should receive skill points up to level 10, and after the 10th level, he no longer receives.

**Comment by insthync** [comment]
Its condition is wrong :P, try find codes and change condition.

**Comment by insthync** [comment]
Fixed in 1.65d
