### ISSUE TITLE
SUGG: Attributes

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#956]
Is it possible to add rate stats for attributes?
![image](https://user-images.githubusercontent.com/47291794/118027677-dc5e3980-b36a-11eb-9d04-147776f2d827.png)
![image](https://user-images.githubusercontent.com/47291794/118027725-f009a000-b36a-11eb-9531-ac9cc7f120d3.png)

**Comment by insthync** [comment]
Already has it

![Screenshot_415](https://user-images.githubusercontent.com/2697550/118042451-4b08ba80-b39e-11eb-8ff0-e2fec6c74418.png)

**Comment by DimasjkTV** [comment]
> Already has it in an equipment items
> 
> ![Screenshot_415](https://user-images.githubusercontent.com/2697550/118042451-4b08ba80-b39e-11eb-8ff0-e2fec6c74418.png)

i mean on attributes. Like 1% hp per character lvl and etc. Now it is only flat like 10 hp per character lvl

**Comment by insthync** [comment]
How it should be calculated?

**Comment by DimasjkTV** [comment]
> How it should be calculated?

in other words, I wanted to increase the percentage of HP and MP for each point of attributes spent

**Comment by DimasjkTV** [comment]
If it is impossible to do at the moment or you don’t like the idea, then you can close it.

**Comment by insthync** [comment]
I just don't know how to calculate it.

is calculation should be:
value = base value + (level * rate)
or
value = level * rate * (base value + (level * stat increase each level))
or something?

**Comment by DimasjkTV** [comment]
> I just don't know how it calculated
> 
> is calculation should be:
> value = base value + (level * rate)
> or
> value = level * rate * (base value + (level * stat increase each level))
> or something?

base value = flat stat like 10 hp?
level = character lvl or attributes amount?

**Comment by insthync** [comment]
base value = flat stat like 10 hp?
level = character lvl?

Yes

**Comment by DimasjkTV** [comment]
> base value = flat stat like 10 hp?
> level = character lvl?
> 
> Yes

or may be 
value = rate * (base + (level * stat each lvl))
