### ISSUE TITLE
[Bug]QueuedWorkbenchEntity

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#958]
Hi,

great to implement Queued to Workbenchs :)
there is a small issue, when you craft something and walk away (craft window closed) then it still continue crafting. it should stop.

**Comment by Sour-J** [comment]
i thought thats how it works for qued crafting like in rust you can walk away and smelt all your ore, to me its working as it should, what your describing is the regular workbench

**Comment by moepi2k** [comment]
It not works like that in rust, what you mean is a furnance, but that works with fuel. And the thing you means is the qued crafting for players  without workbenchs, so you put formulas in database so you have access everywhere to it and craft it. But for workbenchs there need to be qued aslong as you stand at the workbench, else the system makes no sense. Right now you can stand 1second at the bank, select 100 items that takes 1h to craft and walk away and do what you want.

So for what a workbench then? For that function you can use the regular qued system without workbench

**Comment by DimasjkTV** [comment]
This is necessary so that you can create 5 workbenches and craft 5 items at the same time. Like for example in Dark and Light.

**Comment by moepi2k** [comment]
The system like it is in current way make less sense, let see what suri say. For me not a big problem, i will fix it anyway for my useage. Maybe a bool to make it optional

**Comment by Sour-J** [comment]
> It not works like that in rust, what you mean is a furnance, but that works with fuel. And the thing you means is the qued crafting for players without workbenchs, so you put formulas in database so you have access everywhere to it and craft it. But for workbenchs there need to be qued aslong as you stand at the workbench, else the system makes no sense. Right now you can stand 1second at the bank, select 100 items that takes 1h to craft and walk away and do what you want while its crafting.
> 
> So for what a workbench then? For that function you can use the regular qued system without workbench

You made a good point here I agree with you but it's not that bad the way it is I'm using it as a smelter and just added the fuel to the crafting ingredient

**Comment by DimasjkTV** [comment]
> The system like it is in current way make less sense, let see what suri say. For me not a big problem, i will fix it anyway for my useage. Maybe a bool to make it optional

I think both options make the same sense. In the first option, you need to be near the stove to fry an egg. In the second option, you do not have to be by the bonfire to fry meat or burn firewood.

**Comment by moepi2k** [comment]
ÿes right, only diffrent is if the egg is fried and you are 2km away, after finish it will get into your inventory, instead of stay in the fridge haha

**Comment by insthync** [comment]
I will add crafting distance option.

**Comment by insthync** [comment]
In 1.65e
- Add `craftingDistance` to `QueuedWorkbenchEntity`, if this is > 0 it will limit distance to craft an items with this workbench entity by its value.
