### ISSUE TITLE
monster experience 

### ISSUE THREAD

**Issue by Sour-J** [suriyun-production/mmorpg-kit-docs#959]
hello suri,
would it be possible to add exp per level for monsters for instance if a monster is level 100 it gives more exp you have that in other systems but not for monsters its only a range i would like to see exp per level if you can. experience per level is needed because i have to make a new monster for each experience level when you have a range to spawn so a level 1 is the same exp as a level 10... some other customers in discord also wanted this if not i understand it was worth asking you. we would really appreciate it! thank you for all you do

**Comment by Koodetat** [comment]
Yes that would be very usefull.

**Comment by insthync** [comment]
Yeah, I will do it.

**Comment by insthync** [comment]
In 1.65e
- Make rewarding EXP in `MonsterCharacter` data can be increased by monster level. By add `randomExp` variable, the old `randomExpMin` and `randomExpMax` variables will be set to `randomExp` -> `baseAmount` if any of them != 0 and values in `randomExp` are 0.
- Make rewarding gold in `MonsterCharacter` data can be increased by monster level. By add `randomGold` variable, the old `randomGoldMin` and `randomGoldMax` variables will be set to `randomGold` -> `baseAmount` if any of them != 0 and values in `randomGold` are 0.

**Comment by Sour-J** [comment]
thank you suri, I love you so much
