### ISSUE TITLE
Dialogues Translation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#96]
How to translate these buttons into other languages? Will the integration of dialogs make it possible to translate into other languages?
![image](https://user-images.githubusercontent.com/47291794/66763951-7faa4c80-eeb1-11e9-8b1b-2f6d9beb1ffd.png)
![image](https://user-images.githubusercontent.com/47291794/66764429-71106500-eeb2-11e9-9600-fa6186cf72c3.png)
![image](https://user-images.githubusercontent.com/47291794/66764447-78377300-eeb2-11e9-89e8-7957db2cc688.png)

**Comment by insthync** [comment]
Added, will be included in next update

**Comment by DimasjkTV** [comment]
> Added, will be included in next update

u can close if it already done)
