### ISSUE TITLE
DefaultDayNightTimeUpdater.cs

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#961]
can you change this

public override void InitTimeOfDay(BaseGameNetworkManager manager)
        {
            // Initial time of day based on real world time of day
            double totalSeconds = DateTime.**Now**.TimeOfDay.TotalSeconds;
            TimeOfDay = ((float)(totalSeconds / (secondsToOneDay / 24f)) % 24f) + startHourOfDay;
            TimeOfDay %= 24;
        }

to

public override void InitTimeOfDay(BaseGameNetworkManager manager)
        {
            // Initial time of day based on real world time of day
            double totalSeconds = DateTime.**Today**.TimeOfDay.TotalSeconds;
            TimeOfDay = ((float)(totalSeconds / (secondsToOneDay / 24f)) % 24f) + startHourOfDay;
            TimeOfDay %= 24;
        }

if its set to now it take the actual time from computer. it also is reserved from europen to american time.
if its set to Today it take the time you set in the config as starting time.

**Comment by insthync** [comment]
I can change it but it would affect other customer's project, so I recommend to create new class which extended from `BaseDayNightTimeUpdater`, you can copy all codes from `DefaultDayNightTimeUpdater` but changes codes as you wish. Then create its instance and set to game instance -> 
![Screenshot_417](https://user-images.githubusercontent.com/2697550/118296526-46134a80-b507-11eb-9fbb-dfc7897b1110.png)

**Comment by moepi2k** [comment]
alright i will do that :) thx
