### ISSUE TITLE
BUG?!

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#964]
1.65d . After starting the server starts to restart constantly. I only changed the character models. But it restarts even if you do not enter the game. Logs:
[log.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6487402/log.zip)

**Comment by Serivatech** [comment]
There really is a mistake. The topic was created early, it is necessary to clarify after which it happens. Everything is fine on a clean project.

**Comment by insthync** [comment]
Do you mean server processes were killed? right?

**Comment by Serivatech** [comment]
not. i start the server with parameters. it boots, then after 10-30 seconds it starts downloading again. And so cyclically. No mistakes.

**Comment by insthync** [comment]
When it killed, map-server server will restart it automatically, now we have to find why it were killed, I want to see log in /root/.config/unity3d/{your company}/{your project}/Player.log

**Comment by Serivatech** [comment]
no such file
![image](https://user-images.githubusercontent.com/56482598/118369897-162b7c00-b5c7-11eb-9a4d-716bf9e9bdf4.png)

**Comment by insthync** [comment]
Try run cmd

`nohub /root/server.x86_64 -batchmode -nographics -mapId Map001 -centralAddress 82.146.49.24 -centralPort 7000 -machineAddress 82.146.49.24 -mapPort 8005 -startMapServer > test.out &`

Then see whats inside `test.out` file after process killed.

**Comment by Serivatech** [comment]
[test.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/6487718/test.log)

**Comment by insthync** [comment]
Some data is null, I don't know what it is yet.

**Comment by Serivatech** [comment]
How can you find out?

**Comment by insthync** [comment]
In the file

```
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at MultiplayerARPG.MMO.MapNetworkManager+<PreSpawnEntities>d__73.MoveNext () [0x000b3] in <8602ed25058042dcaf94ee383c1a5b74>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) [0x00000] in <1cb7e6d8b0834651989c8a03c99b5623>:0 
  at MultiplayerARPG.BaseGameNetworkManager+<SpawnEntities>d__181.MoveNext () [0x00140] in <8602ed25058042dcaf94ee383c1a5b74>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.<SpawnEntities>d__181:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception)
MultiplayerARPG.MMO.<PreSpawnEntities>d__73:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(BuildingsResp)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(BuildingsResp)
MultiplayerARPG.MMO.<ReadBuildingsAsync>d__111:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncResponseData`1)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetResult(AsyncResponseData`1)
LiteNetLibManager.<SendRequestAsync>d__18`2:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:RunCore()
Cysharp.Threading.Tasks.Internal.ContinuationQueue:Run()
```

**Comment by Serivatech** [comment]
It seems that I roughly understood what's the matter. 1 minute, I'll sign in more detail.

**Comment by insthync** [comment]
You may try build as development build and try it again

**Comment by Serivatech** [comment]
What did I do:
Created a character using a tool from the menu. Model without animations. And that's when it started. Then I added animations, but it didn’t change the situation (I don’t know which animations are required).

Now I have removed the created character and returned a couple of standard characters. Everything works now.

And now I'm confused: how to properly add my characters and what animations are required?

**Comment by Serivatech** [comment]
There was also no sound on my model.

**Comment by insthync** [comment]
If your character is mechanim uses `AnimatorCharacterModel`, if it's Legacy Animation, uses `AnimationCharacterModel`.

**Comment by insthync** [comment]
About sounds, I have to ask you how you setup audio listener?, you want to attach audio listener to camera or your character?

**Comment by Serivatech** [comment]
![image](https://user-images.githubusercontent.com/56482598/118371829-2b58d880-b5d0-11eb-80e4-e6491934ddeb.png)

**Comment by Serivatech** [comment]
I just selected the model when creating the character through the tool. After that I added only animations and points for attaching weapons.

**Comment by insthync** [comment]
Do you have `OwningCharacterAudioListener` prefab set to GameInstance -> `OwningCharacterObjects` like the demo ?

![Screenshot_420](https://user-images.githubusercontent.com/2697550/118371990-5c89d680-b5d9-11eb-8b3b-5a2b53703015.png)

**Comment by Serivatech** [comment]
Yes it is. But sound is not a problem that I would like to solve. What's wrong with the characters?

**Comment by insthync** [comment]
I don't know, and I don't think server problem above is occurring because of character creation tool

**Comment by insthync** [comment]
Did you try playing and offline game?

**Comment by Serivatech** [comment]
No, just mmo.

**Comment by insthync** [comment]
As I said, try build as development build and try it again to see why it crash.

**Comment by Serivatech** [comment]
Now I have added this character to the database again and reboot again.
![image](https://user-images.githubusercontent.com/56482598/118372250-90adc900-b5d2-11eb-83c0-97b18365b888.png)

Like this?
![image](https://user-images.githubusercontent.com/56482598/118372361-129df200-b5d3-11eb-9da1-ea4c7eb58e9a.png)

**Comment by insthync** [comment]
Yes

**Comment by Serivatech** [comment]
[log.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6487844/log.zip)

**Comment by insthync** [comment]
Error occuring when getting buildings from database server

**Comment by Serivatech** [comment]
Buildings? I'm just saying I'm just adding a character.

**Comment by insthync** [comment]
You can see which error comes from which line in the log file, it's not about content, it's about database server connection. I think you may send me your TeamViewer address to my email: ittipon.bay@gmail.com, then I will try to help you figure it out, this is pretty taking a long time.

**Comment by Serivatech** [comment]
ok

**Comment by Fr-Coder** [comment]
I got a similar problem using a server that have low RAM (2 gb). keep in mind that using URP or HDRP can require more RAM for some reason (i think unity bug). I solved this error creating a script similar that replace all textures with 1 px image and remove all things not used on server side.

**Comment by Serivatech** [comment]
Resolved!
The problem was really the amount of RAM. For development, I rented a weak VPS with 512 MB of RAM for $ 2. Now I changed it to 4 GB of RAM and everything worked as it should.
