### ISSUE TITLE
Ammo/Reagents for Skills

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#965]
Is it possible to switch **"Require Ammo Type"** to Skills? Right now its set to Weapontype. With that there are following problems:

1) If you have for example a Skill called Fireball and want that it use 1 Ammo/Reagent (e.g Sulfur) then you are bounded to a specific weapon with a weapon type where is set the Ammo/Reagent for use Fireball like Staff or something else. I think many want to use skills without a required weapon type. so in this case its important that you can add Ammo/Reagent Type to each Skill. -> best would be an array so you can add diffrent types of Ammo/Reagent. like special spells that require 2 or 3 type of ammo/reagent.

2) Problem 2. if you have for example a spell that not require a weapon, lets take Fireball from example 1. in its current kit state, if you set "Use Ammo Amount" to 1 and then you wear a Bow that requires Arrows and cast fireball. the fireball consumes 1 Arrow. a bit bad, isnt it? :)

I think the logic is wrong here. best would be that you have seperate fields on skills for Ammo Type and Ammo amount(what is already implemented)

**Comment by moepi2k** [comment]
let me explain it with videos. maybe its more clear.

in the video you see default functionality. firebolt that can be used without weapons.
https://gyazo.com/98ad7f3f9c7146d9d9a3b27418b3c7ad
the problem is it consumes arrows when you wear a bow because on firebolt ammo consume is set to 1
https://gyazo.com/5a2a9fda5e3b730b918ba1ec9490f244

so with this logic you cant use skills without a specific weapon type. most ppls use skills without weapons and diffrent kind of ammo/reagents.

so best is to have a seperate array for ammo type/amount on skills like

https://media.discordapp.net/attachments/460803281455939595/843438914974384128/unknown.png

so what your thought?

**Comment by RunOrDi3** [comment]
We all hope suri fix this , its really annoying

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
In 1.65e
- Add `requireItems` settings to skill classes. If this list is empty it won't decrease items from inventory. It will decrease one kind of item in this list when using skill, not all items in this list.
- Add `requireAmmoType` settings to skill classes. If `Require Ammo Type` is `Based On Weapon` it will decrease ammo based on ammo type which set to the weapon, amount to decrease ammo can be set to `Require Ammo Amount`. If weapon has no require ammo, it will not able to use skill. If `Require Ammo Type` is `Based On Skill`, it will decrease ammo based on `Require Ammos` setting.
- Add `requireAmmoAmount` settings to skill classes. It will be used while `Require Ammo Type` is `Based On Weapon` to decrease ammo.
- Add `requireAmmos` settings to skill classes. If this list is empty it won't decrease ammo items from inventory. It will decrease one kind of item in this list when using skill, not all items in this list.
- Add `craftingDistance` to `QueuedWorkbenchEntity`, if this is > 0 it will limit distance to craft an items with this workbench entity by its value.
