### ISSUE TITLE
Kick of an inactive user (AFK)

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#968]
Hello Suriyun!
How to implement the kick of an inactive user (AFK), 2 minutes after inactivity (the position on the x axis and z axis does not change) with his transition to Init.scene?

**Comment by Fr-Coder** [comment]
I think it should be very simple implementing it client side.. Create a timer and reset it if player move, if timer > afk_time_to_disconnect change the scene.

**Comment by insthync** [comment]
You may create a new component that will be attached to player character entity which checking for movement at server only, then if character AFK, call function to kick player 
```
BaseGameNetworkManager.Singleton.Transport.ServerDisconnect(ConnectionId);
```

**Comment by brabaris** [comment]
Ok! Thanks.
