### ISSUE TITLE
Map Server not Ready MMO

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#969]
since i updated to 1.65 i got the msg "Map Server not ready"

when i check the logs, the map server is started

 -- Log Start: 16.05.2021 11:27:23
(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibClient] OnPeerConnected

(Log)[(No Manager)->LiteNetLibClient] OnPeerConnected.

(Log)[(No Manager)->LiteNetLibClient] [Chat] Connected to Central Server

(Log)[(No Manager)->LiteNetLibClient] OnPeerConnected.

(Log)[(No Manager)->LiteNetLibClient] [MapSpawnServer] Connected to Central Server

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 0

(Log)[CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 0

(Log)[CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 1

(Log)[CentralNetworkManager(CentralNetworkManager)] Register Chat Server: [0]

(Log)[CentralNetworkManager(CentralNetworkManager)] Register Map Spawn Server: [1]

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId City -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.1.1 -mapPort 8000 -startMapServer 

**(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 18972**

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId Instance1 -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.1.1 -mapPort 8001 -startMapServer 

**(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 19424**

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId Outlands1 -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.1.1 -mapPort 8002 -startMapServer 

**(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 10120**

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId Outlands2 -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.1.1 -mapPort 8003 -startMapServer 

**(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 9060**

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId Taverne -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.1.1 -mapPort 8004 -startMapServer 

**(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 7424**

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 1

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 2

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 3

any ideas?

what i see is in console,  before there was a line to see that map server is started, i cant remember what exactly the msg was. but i dont get this msg anymore now. i only see in logs that server should started

**Comment by insthync** [comment]
Machine address for local hosting is 127.0.0.1 not 127.0.1.1

**Comment by moepi2k** [comment]
oops. but with 127.0.0.1 i got same issue



 -- Log Start: 16.05.2021 11:45:20
(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibClient] OnPeerConnected

(Log)[(No Manager)->LiteNetLibClient] OnPeerConnected.

(Log)[(No Manager)->LiteNetLibClient] [Chat] Connected to Central Server

(Log)[(No Manager)->LiteNetLibClient] OnPeerConnected.

(Log)[(No Manager)->LiteNetLibClient] [MapSpawnServer] Connected to Central Server

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 0

(Log)[CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 0

(Log)[CentralNetworkManager(CentralNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 1

(Log)[CentralNetworkManager(CentralNetworkManager)] Register Chat Server: [0]

(Log)[CentralNetworkManager(CentralNetworkManager)] Register Map Spawn Server: [1]

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId City -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.0.1 -mapPort 8000 -startMapServer 

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 23368

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId Instance1 -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.0.1 -mapPort 8001 -startMapServer 

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 23272

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process from: C:\Users\hubla\Desktop\Ayluin Build\Ayluin.exe

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Starting process with args: -batchmode -nographics -mapId Outlands1 -centralAddress 127.0.0.1 -centralPort 7000 -machineAddress 127.0.0.1 -mapPort 8002 -startMapServer 

(Log)[MapSpawnNetworkManager(MapSpawnNetworkManager)] Process started. Id: 2880

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 1

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 2

(Log)[DatabaseNetworkManager(DatabaseNetworkManager)->LiteNetLibServer] OnPeerConnected peer.ConnectionId: 3

**Comment by moepi2k** [comment]
-startMapSpawnServer -spawnExePath "C:\xxx\xxx.exe" -startCentralServer -startChatServer -startDatabaseServer -machineAddress "127.0.0.1"

thats the start parameter i use

**Comment by insthync** [comment]
Testing locally in your PC, right?

**Comment by moepi2k** [comment]
yes

**Comment by moepi2k** [comment]
(Log)[CentralNetworkManager(CentralNetworkManager)] Register Map Server: [x] [xxx]

this was the msg i mean is missing.

**Comment by moepi2k** [comment]
damn it works. after updating it lost reference to maps again...
damn unity....

sorry for report
