### ISSUE TITLE
Character movement in slopes 

### ISSUE THREAD

**Issue by Sckarlex** [suriyun-production/mmorpg-kit-docs#97]
I have structures that have sloping stairs, but when the character approaches them, he stops completely. Is there any way to modify this? Or should I add some slope component to the character entity script?

**Comment by insthync** [comment]
You may try set capsule collider radius, I'm not sure how is your slope so I want to see it :p

**Comment by insthync** [comment]
This should be fixed, I'll close it, If you still having this issue, you can reopen it.
