### ISSUE TITLE
MultiplayerARPG.ShopUIActivator.LateUpdate ()  gives a null reference exception on warp with inventory open

### ISSUE THREAD

**Issue by Monty001** [suriyun-production/mmorpg-kit-docs#970]
As per the title, tested on 165d.

To recreate, fresh kit, open inventory, go through warp portal.

**Comment by insthync** [comment]
You actaully can ignore it, but I will add null check codes to avoid it.

**Comment by insthync** [comment]
Fixed in 1.65e
