### ISSUE TITLE
Security issue - Multi Hit Trigger

### ISSUE THREAD

**Issue by Fr-Coder** [suriyun-production/mmorpg-kit-docs#971]
I discovered a security problem on attack and skills
Steps to reproduce:
1) Create a new Attack and set Multi Hit Trigger Duration Rate array to 1;
2) Deploy the server;
3) Change Multi Hit Trigger Duration Rate array to 5 (without rebuild and redeploy the server, so client side only); 
4) 5 attack damges occurs instead of 1.

This mean that everyone modding/hacking the client can basically destroy all bosses using 1 simple attack, because can repeat the damage many times. 
Maybe a simple validation server side is needed.

**Comment by insthync** [comment]
If you are not making shooter game, you may attach `LegacyCharacterAttackComponent` to character entity to use it instead of `DefaultCharacterAttackComponent`

**Comment by Fr-Coder** [comment]
Ok using LegacyCharacterAttackComponent the issue isn't present anymore. Hope to see it in the newest DefaultCharacterAttackComponent too!
Thanks you so much.

**Comment by insthync** [comment]
Fixed in 1.66
