### ISSUE TITLE
Skill situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#972]
Situation with summoning skills and buffs.
1. For example, we have item +10 to skelet summon skill For every 5 skills we get + 1 to an additional skeleton. We equip item with +10 bonus, summoned 3 skeletons, unequip item, but the skeletons remained as they were after equip item. This is the same with all buffs / debuffs skills and skill bonuses on items.
2. We have a skill that we can pump with the help of skill points up to a maximum of 10. We have an item that gives +10 to this skill. If we first pump a skill with the help of skill points, and then equip item, then we will have +20 to the skill. But if we first equip item, then we will not be able to pump the skill up to +20.

**Comment by insthync** [comment]
The Fix for 2) was included in 1.65e
