### ISSUE TITLE
[Bug]NoConstructionArea

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#973]
When i attach this component to any gameobject, in game it switch objects layer to IgnoreRaycast. so then im able to build there, it actually should exactly the diffrent way?

**Comment by insthync** [comment]
My codes 
![Screenshot_423](https://user-images.githubusercontent.com/2697550/118581746-56a01b00-b7bc-11eb-8926-13554be9c9f2.png)

No ignore raycast layer checking anymore

**Comment by moepi2k** [comment]
Oh then its fixed already, im still at 1.65 :)

Thank you
