### ISSUE TITLE
Equipment Quick Change

### ISSUE THREAD

**Issue by dglee2592** [suriyun-production/mmorpg-kit-docs#975]
Hello,

Is there any chance to add equipment quick change not only for weapons but also for armors/accessories?
This would be very nice for the game from this kit.
I'm looking forward your positive consideration about this.

Thanks.!

**Comment by insthync** [comment]
Does not planned to do it yet, there are so many requests :(

**Comment by dglee2592** [comment]
Oh understood!! Thanks for the comment!
I ll digging it out myself!
