### ISSUE TITLE
Storage situation

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#976]
Single player game.
Few users, after update the game, lost all items in the storage. What could it depend on? The previous version of the game was based on 1.62f. New version based on the latest update.

**Comment by insthync** [comment]
Oh, that is bad, but it's hard to find out, you may request a save file from the user then I will help to find out what's happening, I think I will make a cloud save for you soon.

**Comment by DimasjkTV** [comment]
> Oh, that is bad, but it's hard to find out, you may request a save file from the user then I will help to find out what's happening, I think I will make a cloud save for you soon.


[Saves.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6499040/Saves.zip)
this is character + storage (but storage is empty) 
I think the character has overwritten the stash somehow after the update

**Comment by DimasjkTV** [comment]
> Oh, that is bad, but it's hard to find out, you may request a save file from the user then I will help to find out what's happening, I think I will make a cloud save for you soon.

https://github.com/suriyun-production/mmorpg-kit-docs/issues/181 
seems like that

**Comment by DimasjkTV** [comment]
> Oh, that is bad, but it's hard to find out, you may request a save file from the user then I will help to find out what's happening, I think I will make a cloud save for you soon.

I was just informed that the items in the vault were missing after restarting the character. That is, the person updated the game, he had items after the update. He played yesterday. Today he entered the game and the items were gone. Exactly so it was a long time ago

**Comment by insthync** [comment]
There are no items in storage from the save file, it was removed, so I can't find cause of the problem yet but I guess it might be from race condition save and load.

**Comment by insthync** [comment]
But it already has a condition check to make sure that data loaded before save to avoid it :P

**Comment by DimasjkTV** [comment]
> There are no items in storage from the save file, it was removed, so I can't find cause of the problem yet but I guess it might be from race condition save and load.

yes, because the update somehow deleted the stash save file and an empty stash save was automatically created. The man had about 40 items in storage. Today I received 3 such complaints. This hasn't happened since when I posted bug # 181. Strange situation

**Comment by DimasjkTV** [comment]
> Oh, that is bad, but it's hard to find out, you may request a save file from the user then I will help to find out what's happening, I think I will make a cloud save for you soon.

I've just been informed. The character died, appeared in the city, checked his storage and saw that it was empty. That is, the storage was lowered after the death of the character

**Comment by insthync** [comment]
Hmm, it may be because after the teleport function called, the save function still being called in `FixedUpdate`

![Screenshot_428](https://user-images.githubusercontent.com/2697550/118754367-1d85aa80-b891-11eb-9150-fa32b9581461.png)

So I will fix it by mark it to not save when the teleport function called, and then turn ready to save state back after moved to another map

**Comment by insthync** [comment]
But I have to say sorry about the issues, I can't bring the data back :(

**Comment by DimasjkTV** [comment]
> But I have to say sorry about the issues, I can't bring the data back :(

Do not worry. Thanks for the fix!

**Comment by DimasjkTV** [comment]
> But I have to say sorry about the issues, I can't bring the data back :(

can you post fix here?

**Comment by insthync** [comment]
The Fix was included in 1.65e
