### ISSUE TITLE
[Bug]BuildingSystem and Melee Damage through Walls

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#977]
1)
for building system. interacting through walls (e.g opening storage) no longer works thats good, but melee damage still goes through walls.
https://gyazo.com/e82b0a8c6631de28acab9ab671eb6914

2)
i also noticed that raycast only blocked (interact with chests for example) on buildings if there is a collider combined with the BuildingMaterial component. without BuildingMaterial you can still interact throught Walls

https://gyazo.com/f867a784cfbd2de4118d5705e8150f9b
here the red colliders of each wall are the collider with BuildingMaterial. if they collide with another building part, building is blocked. you often need to make these colliders a bit smaller (e.g for corners, else you cant build, because the collider of each wall collide with each other). so that i dont have a gap after placing i add a child object with colliders that activate after placing (orange colliders). but the problem is through this gap even if there is a collider you can interact through the wall.

**Comment by moepi2k** [comment]
so i tested it again. i attached the BuildingMaterial on the seperate collider and interacting through wall (gaps) no longer works. so it seems you need to attach them. so i think problem 2 is fixed with that.

but melee damage still goes through walls

**Comment by moepi2k** [comment]
One more thing noticed.
on the Building Prefabs is an event "OnBuildingConstruct"
in singleplayer this will call everytime when login into game. so i used it to activate the colliders i mention in the post above.
in MMO the event is only called on server but not on client.
can you fix this?

https://gyazo.com/5802db17ba05400f8f6aaee7a45ada00

best regards

**Comment by moepi2k** [comment]
i made a picture from demo map so easier to see what i mean:
https://gyazo.com/17f7ec9b10a224bda6058f0e9dd79d28

the red marked gaps is the problem. collider need to be smaller to place walls in corner.

**Comment by moepi2k** [comment]
Can you give me a short feedback about it? if you not change anything on it i will add my own solution. not that i make it now and then you will update something.

best regards

**Comment by insthync** [comment]
About the gap, I've changed how material trigger each other by finding bounds contained rate, if it's at a low rate it won't add to the triggered list, so we could set collider cover the material

**Comment by moepi2k** [comment]
ok sounds good, so i will test as soon as update is out. thank you

**Comment by moepi2k** [comment]
one small thing when you anyway work on it. i just noticed when building part is in preview mode (before placing)
the NavMeshObstacle component should temporary disabled, else you can walk around with a preview wall infront of you and enemy cant walk through
