### ISSUE TITLE
Low fps and character moving

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#978]
Single player.
I tested it on smartphones. If the fps in the game is below 20-25, then the character starts to twitch. He begins to be thrown back. Or wherever he starts to go. This looks like a very large delay in online games. Also, this has not happened before. It looks like it came with new changes.

You can add about 1000 monsters to the map and reproduce a small fps. Below 5-6 it is desirable to see these delays

**Comment by DimasjkTV** [comment]
Seems like this is only with Female_CC or male_CC
[Character_CC.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6513969/Character_CC.zip)

**Comment by DimasjkTV** [comment]
Seems like all is okay with NavMesh characters

**Comment by insthync** [comment]
Don't change the root motion settings, it's not related to the problem.

**Comment by DimasjkTV** [comment]
> Don't change the root motion settings, it's not related to the problem.

[bandicam 2021-05-20 12-06-22-573.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/6514455/bandicam.2021-05-20.12-06-22-573.zip)
with mobile

**Comment by insthync** [comment]
Hmm, is there any way to simulate low FPS on my PC ? :P

**Comment by insthync** [comment]
Okay, I found how to do it, fixing it.

**Comment by DimasjkTV** [comment]
> Hmm, is there any way to simulate low FPS on my PC ? :P

yes you can add 1000-2000 monsters on the map

**Comment by insthync** [comment]
Fix by move update movement function to update in fixed update 

![Screenshot_429](https://user-images.githubusercontent.com/2697550/118969006-c669fd80-b996-11eb-91d6-9d3116f62d8a.png)

**Comment by DimasjkTV** [comment]
> Fix by move update movement function to update in fixed update
> 
> ![Screenshot_429](https://user-images.githubusercontent.com/2697550/118969006-c669fd80-b996-11eb-91d6-9d3116f62d8a.png)

the character still going the opposite way with mobile controller

**Comment by insthync** [comment]
If you use `RigidBodyEntityMovement` changes in  `RigidBodyEntityMovement`

**Comment by DimasjkTV** [comment]
> If you use `RigidBodyEntityMovement` changes in `RigidBodyEntityMovement`

ah yes. works well! thank you!

**Comment by DimasjkTV** [comment]
> If you use `RigidBodyEntityMovement` changes in `RigidBodyEntityMovement`

Now the picture on smartphones jerks at 30 fps. And at 60 fps, the game does not have a smooth movement, as it was before the new fix. The first video was recorded with new changes. Second video with old changes, but with a bug. 

1 Video
https://youtu.be/FtsOM2KtWRw


2 Video
https://youtu.be/GYJG_gU4668

**Comment by DimasjkTV** [comment]
Or is it possible to make sure that with NavMesh, the character does not get stuck near the walls?
NavMesh
https://youtu.be/eD6hXNZmQuQ

RigidBody
https://youtu.be/GT6EbJ-LsLo

**Comment by insthync** [comment]
Fixed

**Comment by DimasjkTV** [comment]
> Fixed

can you add it here? I will test

**Comment by insthync** [comment]
Revert old changes and add this condition

![Screenshot_431](https://user-images.githubusercontent.com/2697550/119104945-0e485d80-ba47-11eb-96b2-d9224bb83a4e.png)

**Comment by DimasjkTV** [comment]
> Revert old changes and add this condition
> 
> ![Screenshot_431](https://user-images.githubusercontent.com/2697550/119104945-0e485d80-ba47-11eb-96b2-d9224bb83a4e.png)

works. Thanks!

**Comment by insthync** [comment]
The Fix was included in 1.65e
