### ISSUE TITLE
Apk android situations

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#979]
I have two versions of the game. The first version is based on 1.65c and the second version is based on 1.65d. So old characters of version 1.65c work fine, but characters of version 1.65d are loaded up to 90% and that's it.
I will describe in more detail:
- I had two projects based on 1.62ph. I updated one project to 1.65s, and the other to 1.65d. Then he released an update. And people did not load characters in the project based on 1.65d, which were created in 1.62f. Only l90% loading screen

p.s rewrite characters from project on 165c to project on 165d and will test

Something of this influenced it
![image](https://user-images.githubusercontent.com/47291794/118836339-6c9d0100-b8cc-11eb-8123-8a85fae8d2fd.png)

**Comment by insthync** [comment]
Your problem solved?

**Comment by DimasjkTV** [comment]
> Your problem solved?

tested. I had a script with lvl req at the map info. Up to a certain level, the character is teleported to the location. But then he doesn't teleport. Character lvl 175, location requires lvl 55. Testing this now

**Comment by DimasjkTV** [comment]
seems like problem not in this

**Comment by DimasjkTV** [comment]
> Your problem solved?

it's funny, but the location didn't want to load due to the fact that the texture size on the floor was 4k and 50% compression
