### ISSUE TITLE
Attributes BUG

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#98]
Attributes from items do not add parameters to the character. Bow has 5 vitality. The character must have 52 health.
![image](https://user-images.githubusercontent.com/47291794/66788203-72ac4e00-eeef-11e9-906d-fd5d94d36b17.png)
![image](https://user-images.githubusercontent.com/47291794/66788208-7b9d1f80-eeef-11e9-995f-973f4bf4dffc.png)

**Comment by insthync** [comment]
It can be fixed by the same code changes with https://github.com/suriyun-production/mmorpg-kit-docs/issues/93
