### ISSUE TITLE
MMO Mode start only first 3 maps from Database

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#980]
any ideas why it only starts the first three maps?
https://gyazo.com/e221f313f75e27263a674bd7bdb4b4e1

log for other will create on start, but the map will not load
https://gyazo.com/d2583d2bb7a36c0a44eaf0bd4f7af91f

port for mapserver are open 8000-8020

**Comment by moepi2k** [comment]
ooh i found the issue.

change this value to e.g 10 then it works.
https://gyazo.com/fdcad4d3d4bc5c7f409abc3f15d87d25

i thought this is the limit for connected players?

**Comment by insthync** [comment]
No, it's a max connection for Central Server + Map Servers

**Comment by moepi2k** [comment]
Alright good to know, but for what is this option? I mean only developer is able how many maps are used in the game, so why an ootion to set a limit?

**Comment by insthync** [comment]
`DatabaseNetworkManager` is overrided from `LiteNetLibManager` so it have those options like `LiteNetLibManager`.

**Comment by moepi2k** [comment]
alright thx :)
