### ISSUE TITLE
how to translate TextGameMessage

### ISSUE THREAD

**Issue by juniormagalhaes** [suriyun-production/mmorpg-kit-docs#981]
how to translate TextGameMessage, I changed the gameinstance but even so it doesn't translate it is only in English

![image](https://user-images.githubusercontent.com/56885137/119063708-1f925b00-b9b0-11eb-8f9a-834f2085b954.png)

![image](https://user-images.githubusercontent.com/56885137/119063727-2b7e1d00-b9b0-11eb-9425-d2ae17a45707.png)

![image](https://user-images.githubusercontent.com/56885137/119063944-9a5b7600-b9b0-11eb-9f3f-d1bb65858a68.png)

**Comment by insthync** [comment]
`RefineSuccess` key was changed to `UI_REFINE_SUCCESS`, there are other keys changed too.

You can use `MigrateOldGameMessage` context menu to changes keys

![Screenshot_430](https://user-images.githubusercontent.com/2697550/119072848-6a46be00-ba16-11eb-907a-f78a34b07c46.png)

**Comment by juniormagalhaes** [comment]
> `RefineSuccess` key was changed to `UI_REFINE_SUCCESS`, there are other keys changed too.
> 
> You can use `MigrateOldGameMessage` context menu to changes keys
> 
> ![Screenshot_430](https://user-images.githubusercontent.com/2697550/119072848-6a46be00-ba16-11eb-907a-f78a34b07c46.png)

where can I find the other keys that have been changed?
