### ISSUE TITLE
Transformation skills

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#983]
It seems that we are one step away from such skills. You recently introduced a very nice thing: 
![image](https://user-images.githubusercontent.com/47291794/119154243-a6037700-ba5a-11eb-9249-c9c20f7824e9.png)
With this thing, we can completely hide the character. He kind of transforms into any creature while using the mount.
Also in the skills, we can add the use of the mount:
![image](https://user-images.githubusercontent.com/47291794/119154578-f549a780-ba5a-11eb-8b1d-ed25b15f5d23.png)
This allows us to transform into a creature by using skill.
Can we somehow force now our mounts to use their own animations when our character attacks while sitting on the mount?

**Comment by insthync** [comment]
Okay, I will do it.

**Comment by insthync** [comment]
Implemented in 1.70

**Comment by Blunnyn** [comment]
How does this really work? It is not in the changelog.

> Implemented in 1.70
