### ISSUE TITLE
"Make CharacterRace to be partial class."

### ISSUE THREAD

**Issue by Serivatech** [suriyun-production/mmorpg-kit-docs#984]
Can I ask you more details?

**Comment by Fr-Coder** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods

**Comment by Serivatech** [comment]
The addition with the races moved to the main set, now something has changed. As before forgot to add information about this in the documentation and now the information in one line.

**Comment by moepi2k** [comment]
We told you alreay in discord what that means. Partial is to extend code, its not a feature..........

Close this

**Comment by Serivatech** [comment]
Как же вы меня бесите! Что не спроси, то либо отвечают совсем про другое, или начинают говорить что не вежлив. Да вы блядь не вкурсе что такое невежливость! Если я не начал слать нахуй в ответ на каждый ваш тупой высер, то я просто ОЧЕНЬ вежлив! Просто, бля, истинный джентльмен!
