### ISSUE TITLE
[Bug]BuffToTarget

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#987]
BuffToTarget no longer works with AimAtCursor controller. you fixed this few weeks/month ago. so when mouse was over entity and used buff, it buffed entity.

right now en an enemy/other player is targeted and use buff, the buff only apply on player self

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.65f
