### ISSUE TITLE
[Bug]Hover with Enemy CharacterController (CC)

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#988]
sometimes it happen when you fight against monster that you hover over them, it happens with the new character controller.
https://gyazo.com/4a415daf77cf0b92b7bbb69d0190ce6f

**Comment by insthync** [comment]
Maybe because of stick to moveable platform codes, try delete codes (or comment it out) from line 543 to 553

![Screenshot_440](https://user-images.githubusercontent.com/2697550/120049655-de9be580-c044-11eb-8f90-63c29aca1265.png)

**Comment by moepi2k** [comment]
ok i will comment it out :)
