### ISSUE TITLE
[Suggestion] Instanced Player Housing

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#989]
As title states. I think it would make a nice addition to the kit. 

Designate a map I.e a blank area, and then use the "designated building area" to allow players to build on it. Progress / building etc is then saved.

I think it would also complement the ability to invite people to your instance and vice versa so people can visit your house and you visit theirs.

Something easy like a conversation with an NPC to access or a portal etc.

**Comment by LordPhrozen** [comment]
This is one of the few things that I do wish was out of the box..

**Comment by rasto61** [comment]
Yes, this would be quite a nice feature

**Comment by Randolphjand** [comment]
Denarius has done a lot in relation to building.  You might talk to him about it.

**Comment by BJPickles** [comment]
> Denarius has done a lot in relation to building. You might talk to him about it.

True, but an official addition to the kit has been highly requested and would be very welcome.

**Comment by BJPickles** [comment]
Being developed into a private addon.
