### ISSUE TITLE
[Bug]Interacting Workbench through walls -> Fix

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#990]
this should be added so that player can interact through walls for workbench
public bool CallServerAppendCraftingQueueItem(uint sourceObjectId, int dataId, short amount)
  
`public bool CallServerAppendCraftingQueueItem(uint sourceObjectId, int dataId, short amount)
        {
            if (!CurrentGameplayRule.CanInteractEntity(this, sourceObjectId))
                return false;
            RPC(ServerAppendCraftingQueueItem, sourceObjectId, dataId, amount);
            return true;
        }`

**Comment by insthync** [comment]
Okay, added

**Comment by insthync** [comment]
Fixed in 1.65f
