### ISSUE TITLE
BUG: Negative character health

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#992]
![image](https://user-images.githubusercontent.com/47291794/119819569-2d3c6900-bef9-11eb-8035-80ead313f2e1.png)
After the resurrection of the character, negative effects continue to be on the character. This leads to the fact that he cannot be resurrected.
https://youtu.be/mla8RMtQacA

**Comment by insthync** [comment]
Fixed in 1.65f
