### ISSUE TITLE
[Bug]Placing Building Parts MMO

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#993]
When placing a building part then it throws this error

https://gyazo.com/a40b34a3689643d444583b782593147c

chests, doors, campfire and so on cant be interactable by pressing activation button. it only works after restart game.

**Comment by insthync** [comment]
This is actually can be ignored, but I will add null checking codes to avoid it.

**Comment by moepi2k** [comment]
Its not just the error, i think theres another issue in mmo, because it never consume the fuel, when i add otherfuel i get message something like overhelming

**Comment by insthync** [comment]
This is fuel issues fixing https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/009ae7c84d1d1eeb5fcc7dc33c38f27e9521fbab

**Comment by moepi2k** [comment]
Sorry mixed posts. So when you add a null check when placing items, does it fix that you can interact with the building (chest, workbench, campfire) without relog? Because right now it only works after restart in mmo.

Interacting works with the menu button but not with activation key (find nearest entity)

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed in 1.65f
