### ISSUE TITLE
Different damage effects

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/mmorpg-kit-docs#995]
Hello everyone! Is it possible to realize different effects? That is, when attacking a tree - chips flew, when attacking a stone - sparks, when attacking characters - blood? Otherwise, only the Default effect is used in GameInstance ...
Thanks in advance!

**Comment by brabaris** [comment]
And one more thing: do you need to remove the Grid visible checker from the tree prefab? If yes, how does the visibility range work now?

**Comment by moepi2k** [comment]
yes this is possible by default. pls ask question in discord. we will answer you there everything we can

**Comment by insthync** [comment]
Yes, you can remove grid visible checker from any prefab, set visible range in `LiteNetLibIdentity` component
