### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by Blunnyn** [suriyun-production/mmorpg-kit-docs#997]
I am in a clean project and using the "mobile" version it is impossible for me to put building walls

https://www.youtube.com/watch?v=ZY1NGpJfkvE&ab_channel=KevinSeura

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by sdk2016** [comment]
I also encounter problem like this.

**Comment by insthync** [comment]
Fixed in 1.65f

**Comment by sdk2016** [comment]
Great. Thankyou!
