### ISSUE TITLE
[Error] I have a problem where not all my portals work 

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#998]
(I have 5 maps and just cant warp to 2) and sometimes one of the ones that dont work works and so on. 

And Im having this error, and as I know I set everything fine in the database. 
![Captura](https://user-images.githubusercontent.com/12781104/120082064-0fe4d780-c07e-11eb-9591-8ab733a9cc85.PNG)

**Comment by insthync** [comment]
MMO games or offline ?

**Comment by MosesGomez** [comment]
2D MMO for mobile.

**Comment by insthync** [comment]
This is breaking a game or you still can continue and play it ?

**Comment by insthync** [comment]
I asked because from the error message it seems like it is just UI error.

**Comment by insthync** [comment]
My `Attribute.cs` codes also don't have any list being called in `CanIncreaseAmount` function. I guess you might have some code changes?. Whats are changes?

**Comment by MosesGomez** [comment]
> This is breaking a game or you still can continue and play it ?

Can play, just pauses the editor while being in unity but outside nothing bad.

**Comment by MosesGomez** [comment]
> My `Attribute.cs` codes also don't have any list being called in `CanIncreaseAmount` function. I guess you might have some code changes?. Whats are changes?

I didnt change anything in atributte, I make changes outside the code, in an extention for player entity to increase 1 attribute called prestige. I didnt update the attribute too.

**Comment by insthync** [comment]
May I try on your PC by using TeamViewer?

**Comment by MosesGomez** [comment]
> May I try on your PC by using TeamViewer?

Sure is good, let me know when you can :D

**Comment by insthync** [comment]
Send your TeamViewer info to my email: ittipon.bay@gmail.com when you're ready
