### ISSUE TITLE
BUG: Max item drop

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#999]
For example, we have a skill that poisons the target and deals periodic damage.
![image](https://user-images.githubusercontent.com/47291794/120098834-cb6e4000-c140-11eb-8344-592a9c199b1a.png)
if a monster dies from this effect, then the drop list ignores the maximum number of dropped items from the monster.
![image](https://user-images.githubusercontent.com/47291794/120098862-f35da380-c140-11eb-81b1-bf49c07dab0f.png)
I found that it multiplies the maximum value by a factor of 2. For example, my monster had a 7 item limit. When a monster died from a normal attack, 7 items dropped. But when the monster died of poison debaff, 14 items dropped out.

**Comment by insthync** [comment]
I will fix it.

**Comment by DimasjkTV** [comment]
> I will fix it.

Thank you! Can you post fix here?

**Comment by insthync** [comment]
Your problem may be related to this https://github.com/suriyun-production/mmorpg-kit-docs/issues/992

When a character dies it should clear buffs, if it still poison applies it will call drop function again, not sure why yours won't, let's make an appointment to try it on your PC

**Comment by DimasjkTV** [comment]
> Your problem may be related to this #992
> 
> When a character dies it should clear buffs, if poison still applies it will call drop function again, not sure why yours won't, let's make an appointment to try it on your P

> Your problem may be related to this #992
> 
> When a character dies it should clear buffs, if poison still applies it will call drop function again, not sure why yours won't, let's make an appointment to try it on your PC

i am ready

**Comment by insthync** [comment]
Fixed in 1.65f
